### ISSUE TITLE
Fatal errors are harmful

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#1000]
Under the model of 'next tipset execution', fatal errors of any kind are incredibly disruptive to the system. We should remove all of them from the system, and the readd them back in only for the specific errors that they should be there for

Realistically, i think i'm fine if all errors in the vm are non fatal, and maybe we just panic if theres a truly fatal error, like a disk failure or something.

**Comment by magik6k** [comment]
I feel like this is now solved
