### ISSUE TITLE
Populating the index on snapshot import

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#10044]
Great work here. Some loose ends we need to tie up in subsequent PRs:
- [ ]  Populating the index on snapshot import.
- [ ] ~Mpool index management (see threads above).~
- [x] ~~#10075~~

_Originally posted by @raulk in https://github.com/filecoin-project/lotus/pull/9965#pullrequestreview-1252671531_

**Comment by magik6k** [comment]
#10119
