### ISSUE TITLE
lotus send from an eth address

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#10049]
lotus currently support f410 address in wallet , and also can compute a f410 address from eth address. tho whats missing from a lotus dev tooling perspective is to be able to do `lotus send` from a eth address:
- that means we either allow user to `lotus wallet import` a eth account
- or when we call `lotus send --from ethAddr`, lotus will get the f410 address of that ethaddr, check if that account's PK is in wallet keystore, use that keystore to sign the message. 

i think 2 is the right option here, but we also need to confirm a f410's pk of a specific eth address is/can be properly imported in lotus wallet keystore.

why want this in lotus cuz, most of the eth developer will be using eth address to sign the message directly and using them to call eth apis. we need an easy way to mimic behavior and perform testing.

**Comment by shrenujbansal** [comment]
Is this specifically referring to the cli tooling or needs additions/changes to the Lotus node JSONRPC API?

**Comment by magik6k** [comment]
Done in https://github.com/filecoin-project/lotus/pull/10056 and https://github.com/filecoin-project/lotus/pull/10160
