### ISSUE TITLE
Error report: bad handshake

### ISSUE THREAD

**Issue by Cyanglacier** [filecoin-project/lotus#1005]
When running any "lotus" cmd (except lotus daemon), it will report    

WARN    main    lotus/main.go:75        websocket: bad handshake

**Comment by whyrusleeping** [comment]
please follow the bug report template or your issues will be closed.

I cannot provide you any advice without more information about how you reproduced the issue

**Comment by qupenghui** [comment]
I'm having the same issue too .
System OS : CentOS 8
lotus version: lotus version 0.4.1+git.e5fdae4.dirty

# lotus sync wait
2020-07-05T11:03:50.918-0400	WARN	main	lotus/main.go:81	websocket: bad handshake

**Comment by qiluge** [comment]
hello, please, how to solve this problem?
