### ISSUE TITLE
failed to configure storage miner

### ISSUE THREAD

**Issue by Cyanglacier** [filecoin-project/lotus#1006]
When running lotus-storage-miner init, it report:

ERROR   main    lotus-storage-miner/init.go:199Failed to initialize lotus-storage-miner: failed to configure storage miner:

![捕获](https://user-images.githubusercontent.com/47769205/71366157-2d398a80-25dc-11ea-99d0-587544dbd90e.JPG)

**Comment by chengwds** [comment]
We’ll be back soon!
Sorry for the inconvenience but we’re performing some maintenance at the moment. For more information please check our community channels, otherwise we’ll be back online shortly!

— The Team

**Comment by whyrusleeping** [comment]
I need a bit more information than this, can you please follow the issue template and file a new issue if this happens again?
