### ISSUE TITLE
🚀  Hyperspace Patch Release 19/01/2023

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/lotus#10074]
We are going to do a pre-hackathon release to address the issues currently experienced on the Hyperspace. 

**Scope**
Code:
- https://github.com/filecoin-project/lotus/issues/10067
- https://github.com/filecoin-project/lotus/issues/10061
- #10072
- https://github.com/filecoin-project/lotus/pull/10079
- https://github.com/filecoin-project/lotus/pull/10052

Docs:
-  Instructions for block explorers and other partners to reconstruct the tipset CIDs that are missing from past tipsets.
- backfills tx id maps
- instructions for enabling eth api support (which enables tx id map)

**Not confirmed scope additions**

-  

**Decided to skip in this patch**
- https://github.com/filecoin-project/lotus/issues/10049
- https://github.com/filecoin-project/lotus/issues/10075

**Comment by maciejwitowski** [comment]
@jennijuju do we need this https://github.com/filecoin-project/lotus/issues/10049? What's the impact of not shipping it now?

**Comment by raulk** [comment]
#10061 is fixed by https://github.com/filecoin-project/lotus/pull/10069 and tested by https://github.com/filecoin-project/lotus/pull/10071.

**Comment by raulk** [comment]
* Need to merge the simplified Eth endpoint setup as well, which activates the transaction hash index.
* Need to add the tool to backfill missing Eth transaction hashes, and add instructions for operators.

**Comment by raulk** [comment]
> Instructions for block explorers and other partners to reconstruct the tipset CIDs that are missing from past tipsets.

For this, we have two options:
1. Use `lotus chain set-head` to rewind the chain and resync.
2. Create a tool, but because badger does not allow concurrent writes from different processes, there would be an interruption anyway.

Since the chain is short and light, I propose (1). Easier on us, known to them.

**Comment by raulk** [comment]
More for instructions:
- Enable the EnableEthRPC flag.

**Comment by jennijuju** [comment]
We likely no longer need #10075 for this tag given 
- for all existing node operators and block explorers they will need to backfill the tipserCIDs that's missing. The way to do it is to resync via set-head.
- now with the new release, whoever that's serving ethapis will have the tx hash map enabled by default. during the resync, the tx hash will be populated as well.

@geoff-vball is verifying the above.

**Comment by maciejwitowski** [comment]
Adding https://github.com/filecoin-project/lotus/pull/10052  to the scope.
Reasons:
- important fixes
- 1st review pass looks promising. Just a few minor fixes Raul will do without waiting for Ian
- Low risk of regression because of isolated changes +

**Comment by jennijuju** [comment]
Update - given the config changes and the resyncing needed, we believe it's easier just for the node operators to start a  fresh repo.

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/lotus/tree/v1.20.0-hyperpsace-0119


This is an optional tag highly recommended for chain service providers(eth api provider, block explorers and etc). 

- feat: [config: Fevm.EnableEthRPC #10072](https://github.com/filecoin-project/lotus/pull/10072)
    - For node operators who want to support Eth APIs, set `EnableEthRPC`  to `true` in your node config.toml, or you can `export LOTUS_FEVM_ENABLEETHRPC=true`  as your env var.
    - If Eth APIs RPC are supported, events & eth tx hash map will be stored in two sqlite db by default.
- feat: [enable txid hash map by default if service ethAPIs #10067](https://github.com/filecoin-project/lotus/issues/10067)
    - always store eth tx id <> filecoin message cid to support eth api methods
- fix: [Tipset CID flakiness #10061](https://github.com/filecoin-project/lotus/issues/10061)
    - some Tipset CID was not correctly stored into the block store
- [fix: events: put the _signed_ message through the pipeline. #10079](https://github.com/filecoin-project/lotus/pull/10079)
    - eth tx hash was calculated wrongly
- [itests: Add tests for EthGetLogs filter combinations #10052](https://github.com/filecoin-project/lotus/pull/10052)

We recommend that all chain service providers, i:e: node, api, block explorer & etc, sync hyperspace from scratch to persist the most accurate historical chain states/information. Recommended node update/redeployment steps:
- remove your existing lotus repo.
- create a new lotus repo and download [https://gist.github.com/jennijuju/a0c9bd09a353ba8cd0255a09396c5915](https://gist.github.com/jennijuju/a0c9bd09a353ba8cd0255a09396c5915), the only default that’s adjusted is `EnableEthRPC = true` . Adjust other configurations as you see fit,
- now start your daemon and start to sync your node!

If you want to opt-out events/logs, just disable `Fevm.Events`
