### ISSUE TITLE
lotus-miner proving check 0 - ERROR: rg is nil

### ISSUE THREAD

**Issue by f8-fil-ops** [filecoin-project/lotus#10098]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner version 1.18.0+mainnet+git.bd10bdf99
```

### Describe the Bug

```
lotus-miner proving check 0 

ERROR: rg is nil
```

command fails with unclear error message

`lotus-miner proving compute wondow-post 0` works fine

```
Took 2m45.159382168s
[{"Deadline":0,"Partitions":[{"Index":0,"Skipped":[0]}],"Proofs":[{"PoStProof":8,"ProofBytes":"p0x7Qh9ROI5/jhzQQuwTD849yLU3A8n3QScZdTG+9p47e6hDQAOJwxEP0rPP5vnTtu40bUAXhRr40V3ehlu8DB2v/tMKUxc5mxY3J2wtHUztWDFog7Bh2JKwq24Snz36AWRJPrO2VUwhwOXgUc+upx/3qcQHUMX3T9dWIbGszw/XRLeTPIDl2BFuf/I1eP9RpgVVtJcOShONS0P1JCK9PZs7FLSln4FaXKQFgE14dZAe9PYUQ9/AnccE9nk4e6iN"}],"ChainCommitEpoch":0,"ChainCommitRand":null}]
```

### Logging Information

```text
tell me what you need and we get it
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by rjan90** [comment]
Hey @f8-fil-ops! Thank you so much for the issue report. This issue has been fixed with this PR: https://github.com/filecoin-project/lotus/pull/9643, which is included in `Lotus v1.19.0` and higher
