### ISSUE TITLE
Failed to initialize lotus-storage-miner

### ISSUE THREAD

**Issue by GFZRZK** [filecoin-project/lotus#1009]
**Describe the bug**
when I setup local devnet, the lotus-storage-miner start failed.

**To Reproduce**
1. When I got this step Set up the genesis miner:
./lotus-storage-miner init --genesis-miner --actor=t0101 --sector-size=1024 --pre-sealed-sectors=~/.genesis-sectors --nosync
2.
 ERROR   main    lotus-storage-miner/init.go:199 Failed to initialize lotus-storage-miner: getting genesis miner sector builder config:
![57F3B601-0089-40C7-A6DB-24FD3932235A](https://user-images.githubusercontent.com/34792731/71403883-180c3c80-266c-11ea-9b1c-4e978cca21a4.png)

**Comment by AsherHuu** [comment]
me too

**Comment by oem0105** [comment]
me too

**Comment by whyrusleeping** [comment]
This is likely because you already have a miner initialized, and youre running with new code. Please remove ~/.lotusstorage before trying to set up a new miner

**Comment by ilzc** [comment]
same error while creating dev-net. ~/.lotusstorage do not exist.
