### ISSUE TITLE
lotus-shed terminate doesn't actually terminate sector

### ISSUE THREAD

**Issue by mrworkdev** [filecoin-project/lotus#10135]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus version 1.19.0+mainnet+git.64059ca87
lotus-miner version 1.19.0+mainnet+git.64059ca87
```

### Describe the Bug

lotus-shed terminate doesn't actually terminate sector

As help topic says: "lotus-shed sectors terminate - Forcefully terminate a sector (WARNING: This means losing power and pay a one-time termination penalty(including collateral) for the terminated sector)".

Recently tried to terminate sector from home laptop:

```
lotus-shed sectors terminate --actor f02012221 --from f3s7b..........42lvq --really-do-it 11
```

Got succesfull termination message:
```
https://filfox.info/en/message/bafy2bzaced3ccgz7dl7qqiumg57r5gzzx7qqg2da63q5vrhbeecvrl6b5umd2
```

But actually sector becomes OnChain YES and Active NO.
```
ID  State    OnChain  Active  Expiration                    Deals  
...     
11  Proving  YES      NO      4084301 (in 1 year 23 weeks)  CC
...
```

Sector log:
```SectorID:       11
Status:         Proving
CIDcommD:       baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq
CIDcommR:       bagboea4b5abcaqbxcl7iko7a7bekgh4iuraiomhtkzaylpodbjr2hrnjakafqzzz
Ticket:         eb6fbd555c6303a36dea5175520597ad1a3de676d27c682b0121aff98a450fc7
TicketH:        2533529
Seed:           8a5a49d2cce7c8e05eae9b7d71fb40a8c8ae33b2a4cbd8e0da9bd81e855ae08b
SeedH:          2535013
Precommit:      bafy2bzacecydfyof67hwyvjgwjgw5d22dqdqihq3za5zvfgotydtryqpveihs
Commit:         bafy2bzacedn5oyvcaijorqauejno32bvcvqjeqtix5djy2icaqcove4ic4akw
Deals:          [0]
Retries:        0
--------
Event Log:
0.      2023-01-21 22:13:14 +0000 UTC:  [event;sealing.SectorStartCC]   {"User":{"ID":11,"SectorType":8}}
1.      2023-01-21 22:14:55 +0000 UTC:  [event;sealing.SectorPacked]    {"User":{"FillerPieces":[{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}]}}
2.      2023-01-21 22:14:55 +0000 UTC:  [event;sealing.SectorTicket]    {"User":{"TicketValue":"62+9VVxjA6Nt6lF1UgWXrRo95nbSfGgrASGv+YpFD8c=","TicketEpoch":2533529}}
...
9.      2023-01-22 03:23:13 +0000 UTC:  [event;sealing.SectorCommitSubmitted]   {"User":{"Message":{"/":"bafy2bzacedn5oyvcaijorqauejno32bvcvqjeqtix5djy2icaqcove4ic4akw"}}}
10.     2023-01-22 03:26:30 +0000 UTC:  [event;sealing.SectorProving]   {"User":{}}
11.     2023-01-22 09:01:51 +0000 UTC:  [event;sealing.SectorFinalized] {"User":{}}
```

But next day also start to get penalties for this secor (key issue of this topic):
```
https://filfox.info/en/message/bafy2bzaced3ccgz7dl7qqiumg57r5gzzx7qqg2da63q5vrhbeecvrl6b5umd2
```

Looks like command doesn't work as expected. It doesn't terminate sector but only removes its OnChain data.
And its opposite to help topic which says "This means losing power and pay a one-time termination penalty(including collateral) for the terminated sector)".

Like "lotus-shed actor withdraw" I expected that "lotus-shed sectors terminate" with --actor flag will terminate it without actual access to miner but do it with correct actor. (Simulating situation when access to miner setup completely lost)

P.S. After doing additional termination with lotus-miner sector change its state to TerminateWait.

### Logging Information

```text
no other logs
```

**Comment by mrworkdev** [comment]
What are my (as miner operator) actions in case of loss of access to the miner?

**Comment by mrworkdev** [comment]
Found answer in Slack.

**Comment by fylsan3** [comment]
+1
