### ISSUE TITLE
lotus sync wait unsuccessful

### ISSUE THREAD

**Issue by aioloszcy** [filecoin-project/lotus#1014]
**Describe the bug**
When I execute lotus sync wait, I get an error every hour and 30 minutes
2019-12-28T07:19:47.781Z        ERROR   chain   chain/sync_manager.go:388       sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /home/filecoin/lotus/chain/sync.go:397
  - collectChain syncMessages:
    github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /home/filecoin/lotus/chain/sync.go:1157
  - message processing failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).iterFullTipsets
        /home/filecoin/lotus/chain/sync.go:1063
  - GetChainMessages failed with all peers(96):
    github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).GetChainMessages
        /home/filecoin/lotus/chain/blocksync/blocksync_client.go:213
  - i/o deadline reached
github.com/filecoin-project/lotus/chain.(*SyncManager).syncWorker
        /home/filecoin/lotus/chain/sync_manager.go:388

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**
v0.1.5

**Additional context**

**Comment by taulzhu** [comment]
I encountered  it also but after restarting ubuntu and sync process， sync wass passed.

**Comment by whyrusleeping** [comment]
The chain was in a weird state over holiday break, we have patched a number of issues and will be resetting the testnet soon.
