### ISSUE TITLE
 Beneficiary change and withdrawal failed

### ISSUE THREAD

**Issue by jhyehuang** [filecoin-project/lotus#10141]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Deamon:lotus-1.18.0-rc5+calibnet+git.c1e1d00d0.dirty
```

### Describe the Bug

After I became more beneficiary, the following problems occurred：
1、The new beneficiary cannot withdraw successfully。
2、You can execute the following command to directly change the beneficiary to owner。
```
lotus-miner actor propose-change-beneficiary <owner> 0 0

```
And after the beneficiary is changed to yourself, cash withdrawal is also available.

### Logging Information

```text
Requested withdrawal in message bafy2bzaceahoshe4j2naqguvgpr4gsqpmd5q6iekpozvm7enl5u2jlbkyvyqw
waiting for it to be included in a block..
Successfully withdrew 20 FIL
```

### Repo Steps

After I became more beneficiary, the following problems occurred：
1、The new beneficiary cannot withdraw successfully。
![image](https://user-images.githubusercontent.com/14520654/215254949-adece6fa-a827-40d7-8c6f-76dd9d127340.png)
![image](https://user-images.githubusercontent.com/14520654/215254972-328136de-8c5b-4585-8ea8-f5566a53d7ae.png)

2、You can execute the following command to directly change the beneficiary to owner。
```
lotus-miner actor propose-change-beneficiary --really-do-it=true  t3q2zrhs6mkmnkvymmkocxk5cwbb76zhterxspnjpfshduqhdbdtugmffixxkpemdzofial6n5cy4wazneurba 0 0
```
![image](https://user-images.githubusercontent.com/14520654/215255025-0eefd713-3ea2-4ea3-9ccd-7783f69223f4.png)
![image](https://user-images.githubusercontent.com/14520654/215255040-7d264e88-d741-4d71-9bc0-9e42a7326f9f.png)
Even if the beneficiary is changed, the owner can still be forced to change to himself.

And after the beneficiary is changed to yourself, cash withdrawal is also available.
![image](https://user-images.githubusercontent.com/14520654/215255113-9d4ff6da-1b70-4e1b-b932-e1d0d6d132b5.png)

**Comment by rjan90** [comment]
Hey @jhyehuang! 

The reason for you not being able to withdraw to you beneficiary address seems to be that the exipration epoch has passed:

![image](https://user-images.githubusercontent.com/8628857/215256494-7f3e98d1-6dc5-4691-bd55-9ed79a933817.jpeg)

The expiration epoch is block height, so you based on this image it seems like it was set to 12000, while the height on calibration is currently 252300+ https://calibration.filscan.io/mobile/

**Comment by jhyehuang** [comment]
@rjan90 thanks，i get it. I'll try it.

**Comment by rjan90** [comment]
Closing this issue since it was fixed by updating the expiration: https://filecoinproject.slack.com/archives/C03KGBTJ0BY/p1674898828969419?thread_ts=1674011779.296929&channel=C03KGBTJ0BY&message_ts=1674898828.969419
