### ISSUE TITLE
[Lotus Lite <-> Lotus Gateway] - `lotus client list-deals` is showing precommit failed error, but the deal is created on chain.

### ISSUE THREAD

**Issue by mur-me** [filecoin-project/lotus#10167]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.19.1-dev+hyperspacenet+git.d8df55b+api1.5.0
Local: lotus version 1.19.1-dev+hyperspacenet+git.d8df55b
```

### Describe the Bug

User is creating deal against Lotus Gateway endpoint and getting error like below, but deal is already on chain.
We observe this error only against Lotus Gateway wss endpoint, ordinary Lotus is working fine.
Example:

```
$ lotus client list-deals --show-failed
DealCid      DealId  Provider  State             On Chain?        Slashed?  PieceCID     Size       Price  Duration  Verified
...muyanimu  828     t01130    StorageDealError  Y (epoch 25562)  N         ...5ffijqiy  3.969 MiB  0 FIL  521709    false
Message: error waiting for deal pre-commit message to appear on chain: handling applied event: failed to get dealinfo: looking for publish deal message
bafy2bzaceccukv5j37crxxx6lhf4jireiu6v3o3cmhakq4lhmk2j3etvzf5m4: not found
```

### Logging Information

```text
Lotus line logs:

{"level":"info","ts":"2023-01-31T11:33:31.946Z","logger":"markets","caller":"loggers/loggers.go:16","msg":"storage client event","name":"","proposal CID":"bafyreibveexr4a5k7eh5jfamoujox6tbln5h7pfww6m5zh4qrxxpfvndtu","state":"StorageDealError","message":"error waiting for deal pre-commit message to appear on chain: failed to set up called handler: on head changed error: called check error (h: 43867): failed to check deal activity: failed to look up deal on chain: looking for publish deal message bafy2bzaceb4pd3vexl5tzvtffzkusde2ezg5vk55hn7yvtfr72n7isd74okmc: not found"}
```
```


### Repo Steps

**NOTE: Issue was reproduced only against Lotus Gateway
we haven't observed it when the Lotus was pointed to the normal Lotus.
**

0. Create new test wallet and add some funds in it
1. Run your lite node against full node:
`FULLNODE_API_INFO=wss://wss.hyperspace.node.glif.io/apigw/lotus lotus daemon --lite`
2. Create sample file:
`dd if=/dev/urandom of=10mb-filecoin-payload.txt bs=1M count=10`
3. Import this file
`lotus client import 10mb-filecoin-payload.txt`
4. Create a deal with data CID from previous step:
```
lotus client deal
Deal duration (days): 180
Miner Addresses (f0.. f0..), none to find: t01130
```
5. Run 
`lotus client list-deals --show-failed`
6. Wait 10-15 minutes
7. Deal will go through the all stages and fail on `StorageDealAwaitingPreCommit` with message
```
Message: error waiting for deal pre-commit message to appear on chain: handling applied event: failed to look up deal on chain: looking for publish deal message bafy2bzaceb4pd3vexl5tzvtffzkusde2ezg5vk55hn7yvtfr72n7isd74okmc: not found
```
8. Check that deal was published on-chain:
https://hyperspace.filfox.info/en/message/bafy2bzaceb4pd3vexl5tzvtffzkusde2ezg5vk55hn7yvtfr72n7isd74okmc

**Comment by Shekelme** [comment]
I have the same symptoms. At least on one miner.
`Jul 18 11:07:53  true   bafyreian77cju4j5glkn6kzw6o3f2nlalskgtzwn3kv4ofi2whyq25uotq  46648487  StorageDealError           f1ieughpsgkdynelb2tipfpuhdvcvltfvsuv54q2q                                               32GiB   0 FIL                  1530231                                                                                                                                 error awaiting deal pre-commit: failed to set up called handler: on head changed error: called check error (h: 3041004): failed to check deal activity: failed to look up deal on chain: looking for publish deal message bafy2bzaceahrs7udtjglqwsnyxbbhkz3tkmg2ijoz6qtto24u2ad3evqllvzw: not found`

```
lotus --version
lotus version 1.23.0+mainnet+git.d1d4b35ad
lotus-miner --version
lotus-miner version 1.23.0+mainnet+git.d1d4b35ad
```

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and is being completely removed from the code here:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
