### ISSUE TITLE
Eth RPC: eth_subscribe is missing params for basic filters

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#10175]
reported by @shrenujbansal 
The EthSubscribe API in lotus currently only takes the topic in the params
https://github.com/filecoin-project/lotus/blob/ad14d71978f9d63ff6268b5fbedb781a05fbe384/chain/types/ethtypes/eth_types.go#L659
This seems to be different from other ethereum clients where you can specify the From/To block and the contract address as a filter for the events you'd like to subscribe to.

@ychiaoli18 helped digged into it more 
it does seem that address is missing from the EthSubscriptionParams. [In ethers.js](https://docs.ethers.org/v5/concepts/events/), event subscription method takes address and topics in query filter

From geth’s doc: https://geth.ethereum.org/docs/interacting-with-geth/rpc/pubsub
address, either an address or an array of addresses. Only logs that are created from these addresses are returned (optional)
topics, only logs which match the specified topics (optional)

Ask: add address into subscription param (see behaviour in ether.js/web3.js)

**Comment by jennijuju** [comment]
without this support - event subscription is merely usable for application developers.

**Comment by magik6k** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/10180
