### ISSUE TITLE
Eth JSON-RPC incompatibility - eth_getBlock* is incompatible with go-ethereum client

### ISSUE THREAD

**Issue by shleshg** [filecoin-project/lotus#10183]
Right now I'm participating in [FVM Space Warp](https://ethglobal.com/events/spacewarp/home) hackathon in `Mark3d` team with `FileMarket` project.

I've faced an issue with `eth_getBlockByNumber` and `eth_getBlockByHash` methods. Trying to fetch blocks with [go-ethereum `Client`](https://github.com/ethereum/go-ethereum/blob/v1.10.23/ethclient/ethclient.go#L35) returns following error:
```
2023/01/25 16:39:22 server returned empty uncle list but block header indicates uncles
panic: server returned empty uncle list but block header indicates uncles
```

Code to represent the issue is following:

main.go:
```go
package main

import (
	"context"
	"fmt"
	"github.com/ethereum/go-ethereum/ethclient"
	"log"
)

func main() {
	client, err := ethclient.Dial("https://api.hyperspace.node.glif.io/rpc/v1")
	if err != nil {
		log.Panicln(err)
	}
	defer client.Close()
	block, err := client.BlockByNumber(context.Background(), nil)
	if err != nil {
		log.Panicln(err)
	}
	fmt.Printf("%+v\n", block)
}

```

go.mod:
```
module github.com/mark3d-xyz/file-market/indexer

go 1.18

require github.com/ethereum/go-ethereum v1.10.23

require (
	github.com/StackExchange/wmi v0.0.0-20180116203802-5d049714c4a6 // indirect
	github.com/btcsuite/btcd/btcec/v2 v2.2.0 // indirect
	github.com/deckarep/golang-set v1.8.0 // indirect
	github.com/decred/dcrd/dcrec/secp256k1/v4 v4.0.1 // indirect
	github.com/go-ole/go-ole v1.2.1 // indirect
	github.com/go-stack/stack v1.8.0 // indirect
	github.com/gorilla/websocket v1.4.2 // indirect
	github.com/shirou/gopsutil v3.21.4-0.20210419000835-c7a38de76ee5+incompatible // indirect
	github.com/tklauser/go-sysconf v0.3.5 // indirect
	github.com/tklauser/numcpus v0.2.2 // indirect
	golang.org/x/crypto v0.0.0-20210921155107-089bfa567519 // indirect
	golang.org/x/sys v0.0.0-20220520151302-bc2c85ada10a // indirect
	gopkg.in/natefinch/npipe.v2 v2.0.0-20160621034901-c1b8fa8bdcce // indirect
)

```

This error comes from this [string](https://github.com/ethereum/go-ethereum/blob/v1.10.23/ethclient/ethclient.go#L131) in go-ethereum source code. It compares `sha3Uncles` field with `EmptyUncleHash` [constant](https://github.com/ethereum/go-ethereum/blob/v1.10.23/core/types/block.go#L36), which equals to `0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347`.

But methods `eth_getBlockByNumber` and `eth_getBlockByHash` are returning block with `sha3Uncles` field equals to `0x0000000000000000000000000000000000000000000000000000000000000000` for any block, and for this reason, fetching block with go-ethereum client is not working.

Actually, there is the same issue with `transactionRoot` field. With empty transactions list (which sometimes happens) value of this field will be [compared](https://github.com/ethereum/go-ethereum/blob/v1.10.23/ethclient/ethclient.go#L137) with `EmptyRootHash` [constant](https://github.com/ethereum/go-ethereum/blob/v1.10.23/core/types/block.go#L35), which also not equals to `0x0000000000000000000000000000000000000000000000000000000000000000`.

However, calling RPC manually with avoiding these checks is a workaround (this can help other hackathon participants facing the same issue until it will be fixed).

**Comment by magik6k** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/10190
