### ISSUE TITLE
RPC incompatibility - eth_getBlock* returns empty logsBloom

### ISSUE THREAD

**Issue by jaeaster** [filecoin-project/lotus#10196]
Observed:
`eth_getBlockByHash` returns "0x" in the `logsBloom` field when there is a block with logs.
(other eth_getBlock* methods probably have the same behavior, but I have not checked)

Expected:
`logsBloom` should return "0x00" if the field is meant to be empty in order to maintain compatibility with tools that expect a valid hexstring.

Further, the `logsBloom` field shouldn't be empty if there are logs. So it seems like this is more than a compatibility issue ... there is likely a bug causing `logsBloom` to be `nil` when a logs exists.

```
// When a log exists
logsBloom = "0x"

// When a log does not exist
logsBloom = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001"
```

Relevant error message from ethers-rs
```
Error("invalid length 0, expected a (both 0x-prefixed or not) hex string or byte array containing 256 bytes")
```

**Comment by magik6k** [comment]
#10194
