### ISSUE TITLE
Depreciate some `lotus-worker` commands? 

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#10210]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

The `lotus-worker` currently has a couple of commands that tries to do somewhat the same thing:

`lotus-worker set` - gives the ability to enable/disable new task processing on a worker
- Issue here is that disabling a worker while a sealing task is midway prevents other workers to fetch the finished sealing tasks/sector from the lotus-worker storage. See https://github.com/filecoin-project/lotus/issues/7866.

`lotus-worker wait-quiet` - Using this command when you have a sealing task running, blocks the command from finishing until the sealing task is done.
- Personally I find this command a bit confusing, and I´m unsure what the usability of this command is - If you have a lotus-worker with PC1/PC2 tasks enabled and a PC1-task currently running, the command will block (not finish) until the PC1 task is finished, but the PC2 jobs will start right after. So there seems to be a potential for misconception of the commands usage/what it does.

`lotus-worker tasks enable/disable` - Allows you to enable or disable a single sealing tasks/ ([and soon all sealing tasks](https://github.com/filecoin-project/lotus/pull/10203)), apart from those that are non-configurable (FUS FIN GET FRU C1 PR1).
- This command is quite similar to the `lotus-worker set` command, apart from that it will not block the non-configurable tasks. So in contrast to the `lotus-worker set` cmd, it will allow other workers will be able to fetch/get sealing tasks/sector from the lotus-worker storage when all sealing tasks are disabled.

### Usage of these cmds from an storage providers standpoint:

Based on previous issue reports and Slack threads I think most SPs are looking for a command that gives them the ability to “gracefully shutdown” a worker for maintenance:

1. A lot of incoming sealing tasks in the, but want/need to shut down worker nr.124 for maintainence/upgrade
2. Issue a command to block incoming tasks, and let it finish its current task.
3. `lotus-worker stop` to detach it and do maintenance/upgrades.

Looking for peoples point of view on these commands, and which of these command(s) is actually useful/unuseful. **Depreciating some of these seems desirable to prevent user confusion - given that the command(s) remaining has the desired feature(s).**

**Comment by SBudo** [comment]
You're spot on, this is exactly why I use the `lotus-worker tasks disable` command: maintenance (i.e. gracefully remove a worker from the sealing pipeline so I can shut it down).
I never use the other commands (useless in their current state)

**Comment by SBudo** [comment]
It would also be great to have a command that "forces" the clean out of the a worker for emergency shutdowns.
When running that command, it would abort all the jobs that can be aborted and would safely restart on another worker (for example, abort PC1, PC2, etc. tasks, but not touch any FIN, AP tasks). It would also be good to then move the potential unsealed or cache sectors to another worker...

**Comment by rjan90** [comment]
Posting this [thread from Slack](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1677018762535289), which also showcases a users confusion with some of these commands.

I think based on this thread it is rather safe to at least start the work on an eventual deprecation of:
- `lotus-worker wait-quiet`

I will leave the other two commands up for debate a bit longer, but for now it seems like `lotus-worker tasks enable/disable` is the command that has the most wanted behaviour.
