### ISSUE TITLE
Splitstore Lotus synchronization is stuck 

### ISSUE THREAD

**Issue by luhong123** [filecoin-project/lotus#10231]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
root@wdpost-f0842171-3-90:~# lotus version  
Daemon:  1.18.0+mainnet+git.bd10bdf99.dirty+api1.5.0
Local: lotus version 1.18.0+mainnet+git.bd10bdf99.dirty
```

### Describe the Bug

Lotus synchronization stuck for 8 minutes or longer, staying at a height

SplitStore

Is it related to this configuration file

config.toml
```
[Chainstore]
EnableSplitstore = true
#  EnableSplitstore = false
#  [Chainstore.Splitstore]
[Chainstore.Splitstore]
ColdStoreType = "discard"
HotStoreFullGCFrequency = 20
```
------------

### Logging Information

```text
Worker: 428913; Base: 2590132; Target: 2590133 (diff: 1)
State: message sync; Current Epoch: 2590131; Todo: 2
Validated 0 messages (0 per second)
Exit by user
```

### Repo Steps

lotus sync wait

**Comment by luhong123** [comment]
![image](https://user-images.githubusercontent.com/63142164/218068270-b6b4f1f4-1bb6-4c4c-8bf4-0351b1166232.png)

**Comment by TippyFlitsUK** [comment]
Have you managed to resolve this with changed config values @luhong123?
