### ISSUE TITLE
ETH API: EthGetTransactionCount incorrect for non accounts

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#10255]
EthGetTransactionCount needs to do a bit more special casing:

1. For accounts, it correctly uses the account's nonce.
2. For EVM contracts, it needs to ask the EVM contract for its _internal_ nonce.
3. For other native actors, it should always return 1.

**Comment by jennijuju** [comment]
maybe rc2 (confirm with yushi)
