### ISSUE TITLE
Huge gap between block stamp and real time

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#1026]
**Describe the bug**
In the testnet phase I testing, it is seen that the block timestamp does not reflect the real block generation time. It keeps shift behind, to the height 54000, the difference between the time stamp and the real time is near *8 hours*. 

**To Reproduce**
No need to reproduce, just check the network 

**Expected behavior**
The block stamp reflect the real generation time. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10411723/71865825-1730db80-313f-11ea-9e02-1ecd3cbaf625.png)

**Version (run `lotus --version`):**
lotus version 0.1.5+gitc010bab8.dirty

**Additional context**
This is due to the current implementation, which simply add block time to the previous-height block's time stamp. The assumption here is that all blocks can be generated in a block-time time, or delay can be absorbed. But, the real generation time >= previous-one + block-time, and ePoSt make it slow.

**Comment by whyrusleeping** [comment]
this can happen (and is likely happening now) if the only miners mining are too slow to complete their eposts in the correct time frame.

The way that we increment the timestamp however *is* correct. If we simply jump the timestamp forward, this opens up room for an attacker who can complete eposts faster to fork and make a heavier chain without having more power.

**Comment by steven004** [comment]
Actually,  vice versa.

Take the current net as an example, the huge gap provided a chance for a
faster miner to mine very quickly. If it can complete ePost in one second,
it could produce a block in about one second, since we provided about 8
hours gap, which means there could be 8*60*60/45 = 640 block buffer for it
to mine valid blocks in a short period of time.

Am I right?

**Comment by magik6k** [comment]
Yes, that's correct.

Generally there shouldn't ever be a gap this big in a real network. We now swapped electionPoSt for a faster winningPoSt, so this should be less of an issue now
