### ISSUE TITLE
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError

### ISSUE THREAD

**Issue by Tylertest8** [filecoin-project/lotus#1027]
**Describe the bug**
Replication proves that 32G sector is, using GPU fails
GPU model ：GeForce RTX 2080 SUPER 8G
GeForce RTX 2080 Ti 11G was successfully proved

**To Reproduce**
1. Run 32G sector miners
2. Error using GPU during replication to prove commit

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/41671238/71896217-1b381a00-318e-11ea-902c-f75129963b16.png)

**Version (run `lotus --version`):**

**Additional context**

**Comment by nanshen2015** [comment]
怎么解决

**Comment by nanshen2015** [comment]
How to solve
