### ISSUE TITLE
How can I debug project?

### ISSUE THREAD

**Issue by AlfredZKY** [filecoin-project/lotus#1028]
I want to know some command line call routes, how to debug the code?
Who can help me?

**Comment by magik6k** [comment]
Depending on what you want to debug, you you just need to start `cmd/lotus`, or `cmd/lotus-storage-miner` in the debugger of your choice.

(like https://github.com/go-delve/delve, gdb - https://golang.org/doc/gdb, or using an IDE like GoLand)

**Comment by AlfredZKY** [comment]
yes,I Kown。I'm debugging some RPCS, but I can't stop the breakpoint, it just returns the data, I'm using the vscode
