### ISSUE TITLE
Eth API: On revert, return data in the error

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#10311]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

JSON-RPC supports an optional `data` field in errors to return additional information. Furthermore, it looks like Ethereum clients _use_ this field to return "revert reasons".

Specifically, we have an error type defined here:

https://github.com/filecoin-project/go-jsonrpc/blob/787a96afc5da60084c97b597b61f0fad18c65a3d/handler.go#L68-L72

```go
type respError struct {
	Code    ErrorCode       `json:"code"`
	Message string          `json:"message"`
	Meta    json.RawMessage `json:"meta,omitempty"`
}
```

We should extend this to:

```go
type respError struct {
	Code    ErrorCode       `json:"code"`
	Message string          `json:"message"`
	Meta    json.RawMessage `json:"meta,omitempty"`
	Data    json.RawMessage `json:"data,omitempty"`
}
```

And provide a way to return said data from a JSON-RPC method. Likely the best way is to define `interface { ErrorData() interface{} }`.

**Comment by Stebalien** [comment]
See https://www.jsonrpc.org/specification#error_object

**Comment by aarshkshah1992** [comment]
@virajbhartiya This will be a fun one and has been a long pending ask from users. Want to pick this up ?
Will need changes to Lotus and `https://github.com/filecoin-project/go-jsonrpc`.

**Comment by aarshkshah1992** [comment]
@Stebalien Which ETH APIs should be returning reverted reason in the data field ? Is the `eth_call` and `eth_estimateGas` APIs only ?

**Comment by aarshkshah1992** [comment]
@virajbhartiya is picking this up.

**Comment by Stebalien** [comment]
> @Stebalien Which ETH APIs should be returning reverted reason in the data field ? Is the eth_call and eth_estimateGas APIs only ?

As far as I know, yes.
