### ISSUE TITLE
I forgot the private key of the address and transferred FIL in it, how can I get back the private key

### ISSUE THREAD

**Issue by Sun-dong** [filecoin-project/lotus#10314]
I have tried to export the private key with lotus wallet export, but the result is ERROR:kev not found, what should I do now

![c048dc8b882dd91e68b35c908821cba](https://user-images.githubusercontent.com/42484887/220017536-69ad7ea1-ea0a-4a6a-85ed-6632dc492a9b.png)

**Comment by beck-8** [comment]
You can try looking for it here, if you can't find it, it's gone.
`~/.lotus/keystore`
Look for files starting with OR MR

**Comment by Sun-dong** [comment]
> You can try looking for it here, if you can't find it, it's gone. `~/.lotus/keystore` Look for files starting with OR MR

I only have two files under this folder    MF2XI2BNNJ3XILLQOJUXMYLUMU   NRUWE4BSOAWWQ33TOQ

![7409785a6dc630e94ae5188af881ac1](https://user-images.githubusercontent.com/42484887/220084422-2df81576-2069-4c67-bb14-4bb5c6be6f0f.png)

**Comment by beck-8** [comment]
Then you won’t be able to find your private key in this place.
You can only think about where it is still stored.

**Comment by rjan90** [comment]
Hey @Sun-dong! Where you able to try the above suggestions? I will either closed the issue if you where able to transfer the FIL, or move the issue over to a discussion item by tomorrow for further discussion.

**Comment by Sun-dong** [comment]
I tried to transfer Fil, but it was prompted that I couldn't find the private key

**Comment by rjan90** [comment]
Okay, unfortunately you would need to have import the private key either to this node or another node to be able to transfer the FIL then. If you do not have the private key there is no way to get the FIL I´m afraid.

**Comment by Sun-dong** [comment]
alright, thank you very much
