### ISSUE TITLE
runtime error: integer divide by zero

### ISSUE THREAD

**Issue by paul8046** [filecoin-project/lotus#10327]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.19.0+mainnet+git.64059ca87
```

### Describe the Bug

On a fresh install of Debian 11 after importing a snapshot lotus will run and stay in sync for a few hours before ceasing to sync. The daemon still seems to be running as reported by systemd however running "lotus info" from the terminal produces an "integer divide by zero" error. Restarting the daemon will fix the issue, however "lotus info" will report that the chain has been out of sync from a few hours after the previous restart. The issue will recur after a few hours.

### Logging Information

```text
panic: runtime error: integer divide by zero

goroutine 1 [running]:

github.com/filecoin-project/lotus/cli/util.FullNodeProxy[...].func1.1()
	/home/lotus/lotus/cli/util/api.go:278 +0x1ea
github.com/filecoin-project/lotus/lib/retry.Retry[...]({0x54a3dc0?, 0xc0001a8000}, 0x5, 0x0, {0xc000868b00?, 0x2, 0x2}, 0xc000868b20)
	/home/lotus/lotus/lib/retry/retry.go:21 +0x1a5
github.com/filecoin-project/lotus/cli/util.FullNodeProxy[...].func1()
	/home/lotus/lotus/cli/util/api.go:277 +0x3af
github.com/filecoin-project/lotus/api.(*CommonStruct).Version(0x54831a0?, {0x54a3dc0?, 0xc0001a8000?})
	/home/lotus/lotus/api/proxy_gen.go:1197 +0x32
github.com/filecoin-project/lotus/cli/util.GetFullNodeAPIV1(0xc000d759c0)
	/home/lotus/lotus/cli/util/api.go:364 +0x2e5
github.com/filecoin-project/lotus/cli.infoCmdAct(0x850e840?)
	/home/lotus/lotus/cli/info.go:32 +0x5a
github.com/urfave/cli/v2.(*Command).Run(0x850e840, 0xc000d75900)
	/home/lotus/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:169 +0x631
github.com/urfave/cli/v2.(*App).RunContext(0xc000602d00, {0x54a3dc0?, 0xc0001a8000}, {0xc0001a6000, 0x2, 0x2})
	/home/lotus/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbc8
github.com/urfave/cli/v2.(*App).Run(...)
	/home/lotus/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
github.com/filecoin-project/lotus/cli.RunApp(0x3c80c00?)
	/home/lotus/lotus/cli/helper.go:39 +0x4e
main.main()
	/home/lotus/lotus/cmd/lotus/main.go:111 +0x90c
```

### Repo Steps

1. systemctl start lotus-daemon
2. Wait around 3-4 hours
3. lotus info

**Comment by paul8046** [comment]
Interestingly, lotus-miner also gives the same error without actually being set to mine. Just started as a daemon and left to sit idle.

**Comment by rjan90** [comment]
Hey @paul8046! This issue seems similar to https://github.com/filecoin-project/lotus/issues/10277, care to add your repro +1 there

**Comment by paul8046** [comment]
It seems that lotus-daemon is hanging rather than crashing as if it is left for long enough then it will start to sync again. This behaviour only seems to start after around 72 hours following a snapshot import, but once it has started it occurs every few hours. The log file is filled with:
`{"level":"error","ts":"2023-03-08T20:35:26.561+1300","logger":"retry","caller":"retry/retry.go:29","msg":"Failed after 5 attempts, last error: %!s(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)"}`

**Comment by rjan90** [comment]
Hey @paul8046! I think it was you that posted in Slack that Debian had a bug in setting FD limits, and that you must set the limits in `/etc/security/limits.conf` and `/etc/systemd/system.conf` and `/etc/systemd/user.conf`.

Has your problems gone away after running with these settings for a while?

**Comment by rjan90** [comment]
Thanks for the update - glad to hear that issue got resolved.

I added some small notes about it in the docs yesterday: https://github.com/filecoin-project/lotus-docs/pull/542/files

I will add some additional details today
