### ISSUE TITLE
Imported a snap of a filecoin-lotus and lotus to UBUNTU SERVER 20.04

### ISSUE THREAD

**Issue by Sayaninlele** [filecoin-project/lotus#10322]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
Daemon:  1.18.2+mainnet+git.9416ceb7d.dirty+api1.5.0
Local: lotus version 1.18.2+mainnet+git.9416ceb7d.dirty
```

### Describe the Bug

Hey you ! i installed lotus on my ubuntu server 20.04 on proxmox VM . So i installed a snap of a lotus from here : https://snapcraft.io/install/lotus/ubuntu 
and here : 
https://snapcraft.io/install/lotus-filecoin/ubuntu
So after i did it from snap , i started my lotus daemon, and lotus sync wait . I'm not sure but i dont think everything is okay .
First issue is, after i typed lotus sync wait, the sync stopped at the worker 0, and won't go further than that : 

Worker: 0; Base: 0; Target: 2622174 (diff: 2622174)
Worker: 0; Base: 0; Target: 2622174 (diff: 2622174)0120
State: header sync; Current Epoch: 2461444; Todo: 160730
Worker: 0; Base: 0; Target: 2622174 (diff: 2622174)
State: header sync; Current Epoch: 2459931; Todo: 162243
Validated 0 messages (0 per second)

The second issue is when i try to make a new wallet by : "sudo lotus wallet new bls" The deamon throws out a bunch of information and after a few seconds it is shutting down : 

......................................
......................................
        /root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.22.0/p2p/net/swarm/limiter.go:219 +0xf0 fp=0xc016ac9fc0 sp=0xc016ac9ee0 pc=0x1ce88f0
github.com/libp2p/go-libp2p/p2p/net/swarm.(*dialLimiter).addCheckFdLimit.func1()
        /root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.22.0/p2p/net/swarm/limiter.go:169 +0x2a fp=0xc016ac9fe0 sp=0xc016ac9fc0 pc=0x1ce80ca
runtime.goexit()
        /snap/go/10008/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc016ac9fe8 sp=0xc016ac9fe0 pc=0x6ef441
created by github.com/libp2p/go-libp2p/p2p/net/swarm.(*dialLimiter).addCheckFdLimit
        /root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.22.0/p2p/net/swarm/limiter.go:169 +0x4bb

rax    0xc01b756000
rbx    0xc01b753318
rcx    0xc01b753318
rdx    0xc01b7532b0
rdi    0xc01b71cb00
rsi    0xc0006024e0
rbp    0x7f3253ffe940
rsp    0x7f3253ffe6e0
r8     0xc000680400
r9     0x0
r10    0x7f325002c348
r11    0x20
r12    0xc01b756000
r13    0x0
r14    0xc013f3f860
r15    0xffffffffffffffff
rip    0x230d7f8
rflags 0x10202
cs     0x33
fs     0x0
gs     0x0

So my question is , did i missed something after installing a snap ?, should i configure something first ? 
I want to say im newbie at this thing.
THANK YOU IN ADVANCE !

### Logging Information

```text
LOTUS LOG LIST : 
incrt
autorelay
retrieval_network
gs-notifications
drand
client
rpc
dagstore
pstoremanager
bitswap-server
peerstore/ds
metrics
badgerbs
partialfile
wdpost
watchdog
cmds
data_transfer_network
sectors
ping
storagemarket_impl
retrievaladapter
build
statetree
fsjournal
net/conngater
retrieval-discovery
cliutil
mocknet
fsm
dt-chanmon
importmgr
metrics-prometheus
providers
paramfetch
storageminer
badger
fil-consensus
filestore
dt_graphsync
gs-queryexecutor
pubsub
rcmgr
gs_request_executor
providerstates
graphsync_network
go-legs-dtsync
rand
blankhost
bs:sess
bitswap-client
data-transfer
go-legs-httpsync
provider/engine
storagemrkt
stores
canonical-log
gs-reconciledlaoder
gen
storagemarket_network
go-legs/head
retry
blockservice
events
p2p-holepunch
quic-transport
p2p-config
miner
blockstore
wallet
fullnode
market_adapter
conngater
routedhost
upgrader
p2pnode
discovery-backoff
alerting
ffi-wrapper
ffiwrapper
diversityFilter
piecestore
rpcenc
cli
net/identify
reuseport-transport
markets-rtvl
tarutil
peermgr
sub
lock
backupds
pathresolv
graphsync_allocator
cmds/http
splitstore
repo
peerstore
chunker/cached-entries-chunker
retrieval
preseal
node
cborrrpc
dagstore/upgrader
paych
nat
swarm2
healthcheck
tracing
payment-channel-settler
chain
evtsm
bs:sprmgr
engine
unixfs
retrievalmarket_impl
fsutil
dht
messagesigner
ulimit
tcp-tpt
types
actors
dt-impl
graphsync
main
dht/RtRefreshManager
messagepool
disputer
wallet-ledger
storageadapter
idxprov
sectoraccessor
builder
beacon
bs:peermgr
markets-rtvl-reval
indexer/schema
genesis
statemgr
retrieval-fsm
go-legs-gpubsub
connmgr
bitswap
bitswap_network
amt
panic-reporter
auth
markets
vm
system
go-legs
modules
test-logger
autonat
eventlog
ipns
dht.pb
ctladdr
storedask
chainstore
basichost
p2p-circuit
chunk
resources
advmgr
table
chainxchg
relay
hello
```

### Repo Steps

1. Run : 

sudo apt update
sudo apt install snapd
sudo snap install lotus-filecoin
sudo snap install lotus
sudo lotus daemon
sudo lotus sync wait
sudo lotus wallet new bls
4. See error :
''Worker: 0; Base: 0; Target: 2622174 (diff: 2622174)
Worker: 0; Base: 0; Target: 2622174 (diff: 2622174)0120
State: header sync; Current Epoch: 2461444; Todo: 160730
Worker: 0; Base: 0; Target: 2622174 (diff: 2622174)
State: header sync; Current Epoch: 2459931; Todo: 162243
Validated 0 messages (0 per second)"

And 

......................................
......................................
/root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.22.0/p2p/net/swarm/limiter.go:219 +0xf0 fp=0xc016ac9fc0 sp=0xc016ac9ee0 pc=0x1ce88f0
github.com/libp2p/go-libp2p/p2p/net/swarm.(*dialLimiter).addCheckFdLimit.func1()
/root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.22.0/p2p/net/swarm/limiter.go:169 +0x2a fp=0xc016ac9fe0 sp=0xc016ac9fc0 pc=0x1ce80ca
runtime.goexit()
/snap/go/10008/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc016ac9fe8 sp=0xc016ac9fe0 pc=0x6ef441
created by github.com/libp2p/go-libp2p/p2p/net/swarm.(*dialLimiter).addCheckFdLimit
/root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.22.0/p2p/net/swarm/limiter.go:169 +0x4bb

rax 0xc01b756000
rbx 0xc01b753318
rcx 0xc01b753318
rdx 0xc01b7532b0
rdi 0xc01b71cb00
rsi 0xc0006024e0
rbp 0x7f3253ffe940
rsp 0x7f3253ffe6e0
r8 0xc000680400
r9 0x0
r10 0x7f325002c348
r11 0x20
r12 0xc01b756000
r13 0x0
r14 0xc013f3f860
r15 0xffffffffffffffff
rip 0x230d7f8
rflags 0x10202
cs 0x33
fs 0x0
gs 0x0

**Comment by piknikSteven2021** [comment]
> proxmox VM

Make sure your VM CPU is in passthrough mode.

**Comment by Sayaninlele** [comment]
> 

Hey, first of all thank you for your answer .  I Set a passthrough mode but it didn't worked . Lotus sync stays at the same level , and still after i typed "sudo lotus wallet new bls" lotus daemon crashed with the same errors as above

**Comment by TippyFlitsUK** [comment]
Have you made any progress with this @Sayaninlele?
