### ISSUE TITLE
add human-readable rpc

### ISSUE THREAD

**Issue by beck-8** [filecoin-project/lotus#10325]
As in the title, I want to add an easy-to-read interface to facilitate reading some information directly or make it readable in other languages. for example:

StateMinerPartitionsUint
https://github.com/beck-8/lotus/commit/d8c756f4658e904669824ac5d9ecccc1960df719
StateMinerDeadlinesUint
https://github.com/beck-8/lotus/commit/3d101a7b87b3cbd6dad6bd621da7d5e81b261e08

I would like to ask, is this compliant with the spec? Are there any requirements? If not I will submit a PR. 
@rjan90

**Comment by beck-8** [comment]
Probably my fundamental need is that the BitField is not easy to read.

**Comment by rjan90** [comment]
Hey @beck-8! Thanks for reaching out, I will have to defer to @magik6k to look into if these would be compliant as api-calls that you can PR into Lotus.

I definetly agree that BitFields is not very human readble 😅 And having better more human readble interface would make [commands outputs like this a lot easier to read](https://github.com/filecoin-project/lotus/issues/8561#issuecomment-1116869942)

**Comment by beck-8** [comment]
Thank you for your reply and look forward to his @magik6k  reply.
I've seen your example, and I've looked at it before, and it's easier to do it visually when there are fewer elements, but once there are more elements, it's impossible to see.

**Comment by magik6k** [comment]
I don't think we need/want human-readable RPC - for human readability there are `lotus-shed bitfield` tools (Not sure if there is one for that encoding, but it could be added)

For other languages it should be easy to translate the json encoding to a map with a ~one-line reduce/map statement.

**Comment by beck-8** [comment]
Because the return value of some interfaces cannot be easily read, after getting the result, it is copied to lotus-shed for conversion. The user experience is relatively poor, and some people even don't know the tool of lotus-shed at all.
When it is convenient to read and use, it will process and troubleshoot problems based on this information.
Other languages may be easy to convert for professional people, but for some people who use these interfaces and simply process data, they don't know how to use them.
The two interfaces I exemplified were written in python language, and the wdpost warning mechanism, I will not accurately convert them into readable text, so I choose to return readable information directly in golang.
![image](https://user-images.githubusercontent.com/34204218/220809795-188749d6-a26e-45f4-94d4-e01568dee481.png)
![image](https://user-images.githubusercontent.com/34204218/220809830-284f4c63-f4b4-4247-97de-8a09bce89e64.png)
I know that once this opening is opened, there may be many interfaces that can be added, and there may be duplication.
So, I am listening to your professional opinions. If it is not recommended, then I will only use it on my branch.

**Comment by jennijuju** [comment]
Thank you for contributing and understanding the rationales!  Closing this now 💙
