### ISSUE TITLE
TTDataCid (DC) is missing from lotus-worker CLI (run --option)

### ISSUE THREAD

**Issue by hyunmoon** [filecoin-project/lotus#10351]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version
Daemon:  1.19.0+mainnet+git.64059ca87+api1.5.0
Local: lotus version 1.19.0+mainnet+git.64059ca87

lotus-miner --version
lotus-miner version 1.19.0+mainnet+git.64059ca87

lotus-worker --version
lotus-worker version 1.19.0+mainnet+git.64059ca87
```

### Describe the Bug

```
lotus-worker tasks enable -h
NAME:
   lotus-worker tasks enable - Enable a task type

USAGE:
   lotus-worker tasks enable [command options] [UNS|C2|PC2|PC1|PR2|RU|AP|DC|GSK]

OPTIONS:
   --help, -h  show help (default: false)
```

lotus-worker can either enable or disable DC (data-cid) via `lotus-worker tasks enable` or `lotus-worker tasks disable`

According to this, TTDataCid is a unique task with its own priority:
https://github.com/filecoin-project/lotus/blob/285cc66773466dee06eeda993723da21d2218268/storage/sealer/sealtasks/task.go#L43

Using lotus-worker tasks enable/disable, I configured a lotus-worker process to do DC (data-cid) only and I confirmed that it works as intended.

Also, the fact that lotus-worker tasks enable/disable works on AP and DC separately means that separating the two is intended to be supported.

However, looking at this code, DataCid and AddPiece seem to be run as a package deal.
https://github.com/filecoin-project/lotus/blob/d82b2a58040bf54411427af0edb62ad023647e45/storage/sealer/manager.go#L151

And the run option for data-cid is also missing from the CLI:

```
lotus-worker run -h
NAME:
   lotus-worker run - Start lotus worker

USAGE:
   lotus-worker run [command options] [arguments...]

OPTIONS:
   --addpiece                    enable addpiece (default: true) [$LOTUS_WORKER_ADDPIECE]
   --commit                      enable commit (32G sectors: all cores or GPUs, 128GiB Memory + 64GiB swap) (default: true) [$LOTUS_WORKER_COMMIT]
   --listen value                host address and port the worker api will listen on (default: "0.0.0.0:3456") [$LOTUS_WORKER_LISTEN]
   --name value                  custom worker name (default: hostname) [$LOTUS_WORKER_NAME]
   --no-default                  disable all default compute tasks, use the worker for storage/fetching only (default: false) [$LOTUS_WORKER_NO_DEFAULT]
   --no-local-storage            don't use storageminer repo for sector storage (default: false) [$LOTUS_WORKER_NO_LOCAL_STORAGE]
   --no-swap                     don't use swap (default: false) [$LOTUS_WORKER_NO_SWAP]
   --parallel-fetch-limit value  maximum fetch operations to run in parallel (default: 5) [$LOTUS_WORKER_PARALLEL_FETCH_LIMIT]
   --post-parallel-reads value   maximum number of parallel challenge reads (0 = no limit) (default: 128) [$LOTUS_WORKER_POST_PARALLEL_READS]
   --post-read-timeout value     time limit for reading PoSt challenges (0 = no limit) (default: 0s) [$LOTUS_WORKER_POST_READ_TIMEOUT]
   --precommit1                  enable precommit1 (32G sectors: 1 core, 128GiB Memory) (default: true) [$LOTUS_WORKER_PRECOMMIT1]
   --precommit2                  enable precommit2 (32G sectors: all cores, 96GiB Memory) (default: true) [$LOTUS_WORKER_PRECOMMIT2]
   --prove-replica-update2       enable prove replica update 2 (default: true) [$LOTUS_WORKER_PROVE_REPLICA_UPDATE2]
   --regen-sector-key            enable regen sector key (default: true) [$LOTUS_WORKER_REGEN_SECTOR_KEY]
   --replica-update              enable replica update (default: true) [$LOTUS_WORKER_REPLICA_UPDATE]
   --sector-download             enable external sector data download (default: false) [$LOTUS_WORKER_SECTOR_DOWNLOAD]
   --timeout value               used when 'listen' is unspecified. must be a valid duration recognized by golang's time.ParseDuration function (default: "30m") [$LOTUS_WORKER_TIMEOUT]
   --unseal                      enable unsealing (32G sectors: 1 core, 128GiB Memory) (default: true) [$LOTUS_WORKER_UNSEAL]
   --windowpost                  enable window post (default: false) [$LOTUS_WORKER_WINDOWPOST]
   --winningpost                 enable winning post (default: false) [$LOTUS_WORKER_WINNINGPOST]
```

IMO, it doesn't make a logical sense that the run switch for DC is missing while it is supported by `tasks enable/disable`.
Therefore, I think `lotus-worker` should support `--data-cid` switch for `lotus-worker run`. @magik6k 

### Logging Information

```text
N/A
```

### Repo Steps

`lotus-worker run -h`

`lotus-worker tasks enable DC`

`lotus-worker tasks disable DC`

**Comment by hyunmoon** [comment]
Either a run switch should be supported, or DC should be tied up with AP on `lotus-worker tasks enable/disable`

**Comment by magik6k** [comment]
Yeah, that should be easy to do, and should be useful if you don't want those tasks to conflict with AddPiece

I guess we can:
* Add a --data-cid flag, which defaults to whatever the value of --addpiece is
  * This way we don't break existing setups
* If you only want DataCid enabled, you set `--data-cid`
* If you only want AddPiece, you set `--data-cid=false --addpiece`
