### ISSUE TITLE
Lotus height anomaly

### ISSUE THREAD

**Issue by luhong123** [filecoin-project/lotus#10361]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.18.0+mainnet+git.bd10bdf99.dirty.11290957+api1.5.0
Local: lotus version 1.18.0+mainnet+git.bd10bdf99.dirty.11290957

root@f080468-wdpost-03-32:~# lotus-miner version
Daemon:  1.18.0+mainnet+git.bd10bdf99.dirty.11291010+api1.5.0
Local: lotus-miner version 1.18.0+mainnet+git.bd10bdf99.dirty.11291010
```

### Describe the Bug

The height of lotus is always around 7 and 20. It will automatically recover after changing the public address, but it can only last for about 30 minutes. The exception will reappear

### Logging Information

```text
Log stuck
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...
...............

**Comment by arajasek** [comment]
I don't think there's enough information here to look into this. Please reopen with the Repro steps, logs, and more information about the bug.
