### ISSUE TITLE
Remove markets API calls from lotus-miner info

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/lotus#10362]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

Currently `lotus-miner info` outputs information about the miner, and also information about storage and retrieval deals.
In order to get the deal information it needs to retrieve all storage deals and all retrieval deals ever made by the miner.
As markets functionality is moving over to the boost project, we propose removing the deal information from the output of `lotus-miner info`, so that no calls need be made to the markets subsystem.

**Comment by rjan90** [comment]
Agreed! I propose that we try to get this into the v1.21.0 feature release, targeted for March 7th.
