### ISSUE TITLE
lotus-miner actor withdraw return SIGSEGV

### ISSUE THREAD

**Issue by xiaomdong** [filecoin-project/lotus#10373]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.19.0+mainnet+git.9449583a3.dirty+api1.5.0
Local: lotus-miner version 1.19.0+mainnet+git.9449583a3.dirty
```

### Describe the Bug

lotus-miner actor withdraw return SIGSEGV

![图片](https://user-images.githubusercontent.com/1774981/222017645-5f67abee-ad68-41dd-862f-57d66bd39f90.png)
![图片](https://user-images.githubusercontent.com/1774981/222017697-b2fbf7ae-9faf-4285-9d76-a4541bf1aaa6.png)

### Logging Information

```text
waiting for it to be included in a block..
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x229cef5]

goroutine 1 [running]:
main.glob..func3(0xc000f9d400)
	/home/ubuntu/software/yilian_workspace/YiLian_v1.19.0/src_worker_allinone/with_rust-fil-proofs/lotus/cmd/lotus-miner/actor.go:293 +0x6f5
github.com/urfave/cli/v2.(*Command).Run(0x7d2a0a0, 0xc000f9d280)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:169 +0x656
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc0006836c0, 0xc000f9d0c0)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:490 +0xd4a
github.com/urfave/cli/v2.(*Command).startApp(0x7d28fc0, 0xc000f9d0c0)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:287 +0x78f
github.com/urfave/cli/v2.(*Command).Run(0xc000f9d0c0?, 0xc000c75100?)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:95 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc000683380, {0x4917e50?, 0xc00005ed40}, {0xc000052080, 0x4, 0x4})
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbfd
github.com/urfave/cli/v2.(*App).Run(...)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
github.com/filecoin-project/lotus/cli.RunApp(0x3c69400?)
	/home/ubuntu/software/yilian_workspace/YiLian_v1.19.0/src_worker_allinone/with_rust-fil-proofs/lotus/cli/helper.go:39 +0x4e
main.main()
	/home/ubuntu/software/yilian_workspace/YiLian_v1.19.0/src_worker_allinone/with_rust-fil-proofs/lotus/cmd/lotus-miner/main.go:168 +0x1154
```

### Repo Steps

Just run 'lotus-miner actor withdraw'

**Comment by TippyFlitsUK** [comment]
Thanks for the ticket @xiaomdong.

Did you exit out of the command before 5 blocks had passed?

**Comment by TippyFlitsUK** [comment]
https://github.com/filecoin-project/lotus/issues/9596
