### ISSUE TITLE
HA of WindowPoSt - Techincal Design

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#10379]
**User Story:**

- As a storage provider (SP) I need a high availability solution for windowPoSt to ensure that I don't miss any proving deadlines, scheduling, computations and submissions.

**Acceptence criteria:**
- 

```[tasklist]
### Tasks
- [x] Techincal Design Documentation: https://docs.google.com/document/d/1lPe-6HdVe_oU0mD29f9Zi4233_xhSbyiXxM_6zXG4hY/edit?pli=1
- [x] Review HA of WindowPoSt - Techincal Design
```

**Comment by snadrus** [comment]
Open for community review:
https://docs.google.com/document/d/1lPe-6HdVe_oU0mD29f9Zi4233_xhSbyiXxM_6zXG4hY/edit?pli=1

**Comment by beck-8** [comment]
Current known issues:

1. A damaged sector will cause all partitions to be redone
2. I usually match my SP with the wdpost-worker machine with the largest number of partitions, such as a 20P node. I usually use one miner and six wdpost-workers to ensure that wdpost is completed as soon as possible and has enough time to be packaged . In fact, this part of resources is very idle and wasted.
3. In some cases, it may be necessary to restart the miner. Assuming that the message is not submitted at this time, after the restart, before the wdpost-worker is connected to the miner, the miner has already started to make wdpost proofs, causing the miner to do 6 partitions by itself. , to prove that the time is doubled, and in severe cases, it will time out directly.
4. The daemon miner has no redundancy, and the single point of failure problem is serious. My team usually monitors whether the proof is complete 7 minutes after the start of the proof. If it is not completed, I will call and wake up my partner immediately. My partner will immediately log in to the server to check the reason. At this time, there are about 20 minutes left. 7 minutes are allowed for proof and message submission, and only 13 minutes are left for partners to operate. Within 13 minutes, you must find the cause, restart the miner, switch machines, etc., which is a test of the technical ability and level of personnel. I'm thankful that I have professional partners to support me, but it's not sustainable.

**Comment by magik6k** [comment]
> I usually match my SP with the wdpost-worker machine with the largest number of partitions, such as a 20P node. I usually use one miner and six wdpost-workers to ensure that wdpost is completed as soon as possible and has enough time to be packaged . In fact, this part of resources is very idle and wasted.

This is likely due to the windowPoSt loop only processing one partition at a time - https://github.com/filecoin-project/lotus/pull/9615 implements parallel processing, so should help a lot

**Comment by beck-8** [comment]
https://github.com/filecoin-project/lotus/discussions/11029
