### ISSUE TITLE
ETH RPC: tx reciept returned 'null' when 'out of gas' occured

### ISSUE THREAD

**Issue by mirana777** [filecoin-project/lotus#10383]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.20.0-rc2+hyperspacenet+git.294e399dc+api1.5.0
Local: lotus version 1.20.0-rc2+hyperspacenet+git.294e399dc
```

### Describe the Bug

A compatibility issue with lotus eth rpc. When ‘out of gas’ occurs in a FEVM contract transaction, ‘null’ is returned when the receipt is obtained through eth rpc `eth_getTransactionReceipt.` You can check it through this message :https://hyperspace.filfox.info/zh/message/bafy2bzacecayfv55hllwkeyz3djaftc665v6uafr6veuydksmjqp4qwh63ghe

### Logging Information

```text
curl http://hyperspace.filfox.info/rpc/v1 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getTransactionReceipt","params":["0x911184212029134efd3de7ad2655b770e400a5a73e1fd92c02c7bc3f50e67fbe"],"id":1,"jsonrpc":"2.0"}'

{"jsonrpc":"2.0","result":null,"id":1}
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by arajasek** [comment]
This is another edge-case hit when messages are "skipped" due to being unable to cover on-chain inclusion costs. Shouldn't be a problem on mainnet.

**Comment by tarassh** [comment]
I can confirm this issue on a mainnet using two different rpc endpoints. Interesting note here, after multiple of retries ankh endpoint may return the data.
```
curl --location 'https://rpc.ankr.com/filecoin/49805229922ed7af27aafe38f89d155db8ed93cf715f6f711ba59dadd7ea67fe' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionReceipt",
    "params": [
        "0xb9a41b4df9e7eec28e6b868cf8bf69eb870eb4a05aa03099d95dc38a270163e5"
    ],
    "id": 1
}'
```

```
curl --location 'https://filecoin.chainup.net/rpc/v1' \
--header 'Content-Type: application/json' \
--header 'Cookie: id=1bc331ff-3f5a-4bcc-8b93-75c89854be57' \
--data '{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionReceipt",
    "params": [
        "0xb9a41b4df9e7eec28e6b868cf8bf69eb870eb4a05aa03099d95dc38a270163e5"
    ],
    "id": 1
}'
```

**Comment by Stebalien** [comment]
Fixed by https://github.com/filecoin-project/lotus/pull/11329. We should now return an actual error instead of just returning null and moving on.
