### ISSUE TITLE
CLI: FilPlus: Support calling ExtendClaim

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#10381]
Introduced in nv17, but not supported by tooling yet.

See [here](https://github.com/filecoin-project/lotus/pull/10328#discussion_r1123522936) for more.

**Comment by beck-8** [comment]
`lotus filplus extend-claim <provider-addr> <claim-id>`
In practice, this does not meet the demand. It needs to be.
`lotus filplus extend-claim --from xx --all <provider-addr>`

**Comment by rjan90** [comment]
Closed by: https://github.com/filecoin-project/lotus/pull/11711
