### ISSUE TITLE
Solve Codefi gas oracle returning 0 priority fee

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#10393]
## Situation

The Codefi `suggestedGasFees` oracle keeps returning `latestPriorityFeeRange` and `historicalPriorityFeeRange` as 0 on Hyperspace, even when messages have been included in the last 1-2 tipsets with non-zero priority fee.

```sh
curl 'https://gas-api.metaswap.codefi.network/networks/3141/suggestedGasFees'
```

```json
{
  "low": {
    "suggestedMaxPriorityFeePerGas": "0",
    "suggestedMaxFeePerGas": "0.0000001",
    "minWaitTimeEstimate": 15000,
    "maxWaitTimeEstimate": 30000
  },
  "medium": {
    "suggestedMaxPriorityFeePerGas": "0",
    "suggestedMaxFeePerGas": "0.000000135",
    "minWaitTimeEstimate": 15000,
    "maxWaitTimeEstimate": 45000
  },
  "high": {
    "suggestedMaxPriorityFeePerGas": "0",
    "suggestedMaxFeePerGas": "0.00000017",
    "minWaitTimeEstimate": 15000,
    "maxWaitTimeEstimate": 60000
  },
  "estimatedBaseFee": "0.0000001",
  "networkCongestion": 0,
  "latestPriorityFeeRange": [
    "0",
    "0"
  ],
  "historicalPriorityFeeRange": [
    "0",
    "0"
  ],
  "historicalBaseFeeRange": [
    "0.0000001",
    "0.0000001"
  ],
  "priorityFeeTrend": "level",
  "baseFeeTrend": "up"
}
```

## Impact

This makes MetaMask default to a priority fee of 0. If this situation persists in mainnet, MetaMask senders will have problems with message inclusion.

## Notes

- Codefi's gas oracle uses `eth_feeHistory` under the hood, so it's possible that a bug in `eth_feeHistory` is reporting a zero priority fee.
- Perhaps `eth_feeHistory` should be clamping to [`MinGasPremium` (0.1 nanoFIL) as a bare minimum](https://github.com/filecoin-project/lotus/blob/03b419e3d47f6a1f99045a39eb2fdd5e24d3ad59/node/impl/full/gas.go#L217). 
- `eth_maxPriorityFeePerGas` seems ok:
	```
	⟩ curl "https://api.hyperspace.node.glif.io/rpc/v1" \
	          -X POST \
	          -d '{"method":"eth_maxPriorityFeePerGas","params":[],"id":1,"jsonrpc":"2.0"}' \
	          -H "Content-Type: application/json"
	{"jsonrpc":"2.0","result":"0x30ea8","id":1}
	```

## Next steps

- Check with the MetaMask/Codefi team to understand how they calculate `latestPriorityFeeRange` and `historicalPriorityFeeRange`.
- Implement integration tests for `eth_feeHistory`.
- Figure out what needs to happen here for correct reporting, and fix the root cause.

**Comment by Kubuxu** [comment]
> Perhaps eth_feeHistory should be clamping to [MinGasPremium (0.1 nanoFIL) as a bare minimum](https://github.com/filecoin-project/lotus/blob/03b419e3d47f6a1f99045a39eb2fdd5e24d3ad59/node/impl/full/gas.go#L217).

Its not 0.1nFIL but 0.1pFIL.

**Comment by raulk** [comment]
All open issues in `eth_feeHistory` were addressed. We're in touch with Codefi to robustify the gas oracle integration, but there's no more Lotus work left in this thread.
