### ISSUE TITLE
lotus evm stat f05 is broken

### ISSUE THREAD

**Issue by shrenujbansal** [filecoin-project/lotus#10400]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
release/v1.20.0
```

### Describe the Bug

lotus evm stat cmd not working for builtin actors

### Logging Information

```text
reiers@hyperspace:~$ lotus evm stat f005
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c89026]

goroutine 1 [running]:
github.com/filecoin-project/lotus/cli.glob..func46(0xc000dba7c0)
	/home/reiers/lotus/cli/evm.go:83 +0x366
github.com/urfave/cli/v2.(*Command).Run(0xabb79e0, 0xc000dba700)
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/command.go:173 +0x6ca
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000dcc540, 0xc000dba500)
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:531 +0xd85
github.com/urfave/cli/v2.(*Command).startApp(0xabb7f80, 0xc000dba500)
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/command.go:291 +0x79b
github.com/urfave/cli/v2.(*Command).Run(0x4602f80?, 0xc000f0c170?)
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/command.go:95 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc000dcc380, {0x7585df0?, 0xc0000560a0}, {0xc000052080, 0x4, 0x4})
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:383 +0xfde
github.com/urfave/cli/v2.(*App).Run(...)
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:252
github.com/filecoin-project/lotus/cli.RunApp(0x47335e0?)
	/home/reiers/lotus/cli/helper.go:48 +0x107
main.main()
	/home/reiers/lotus/cmd/lotus/main.go:111 +0x934
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by Stebalien** [comment]
@shrenujbansal what exact commit? Line 83 doesn't appear to be relevant.
