### ISSUE TITLE
EthAPI: Optimize EthGetTransactionReceipt

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#10418]
It currently performs 2 unbounded lookbacks from current head -- one to "find" the message, and a second to "replay" it. The second lookback can be entirely avoided by providing the tipset from the "find" step to StateReplay.

This is one of (likely) many perf improvements that can be made to the EthAPI, but was flagged as being an especially important method.

**Comment by Stebalien** [comment]
We can also avoid replaying entirely. We can use the receipt from `StateSearchMessage`, the base-fee from the tipset, and ComputeGasOutputs to determine the effective gas fees.

**Comment by raulk** [comment]
This will be impacted by the indexing work in #10326, so let's revisit once that has landed.

**Comment by raulk** [comment]
`StateReplay` is a no go.

**Comment by raulk** [comment]
Working on a patch to solve this ahead of #10326, since we don't know if that will land before π day.
