### ISSUE TITLE
Gateway: EthAPI needs to restrict lookbacks

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#10412]
The gateway currently supports some EthAPI methods that could have unrestricted lookbacks. Upon examination, I think the only such methods are:

- EthGetTransactionReceipt
- EthGetTransactionByHash

If called with tx hashes from far in the past, these methods will walk up the chain potentially as far as genesis looking for the relevant message. Due to an inefficiency in `EthGetTransactionReceipt`, it will actually perform this walkup twice, but that is unrelated and easily resolved.

There's an open question about what we want to do about this. We could:

- Leave it as-is: Any good gateway will have a short timeout anyway, the requests will just fail ([default is 5 seconds](https://github.com/filecoin-project/lotus/blob/8975f0b753085854a84dec0049554cad7fdd0c4e/gateway/node.go#L35)).
- Drop these methods from the gateway: I'm guessing we don't want to do this, but it's an option.
- Refactor the system to use the "regular" gateway lookback limits. This is possible, but requires some code moving around. I would propose doing it as follows (not the fastest, but IMO the cleanest way to do this).
  - Add an `EthLookupEthAddress` method to the API. I think we should have this regardless.
  - Refactor `newEthTxFromMessageLookup`, etc. methods to be moved to the `types` package (perhaps defined on the types themeselves). Doing so will require replacing the StateAPI param these methods take with a `lookupEthAddr` func that callers can supply.
  - Extract out the "[get message lookup](https://github.com/filecoin-project/lotus/blob/12496e56317377ece4af744f065d6975ab82674c/node/impl/full/eth.go#L277-L294)" pattern that given a tx hash retrieves the message lookup for it. Implement this in the gateway impl with lookbacks on StateSearchMsg.
  - Modify the gateway impls to use the logic extracted in the previous step. This effectively reimplements the methods on the gateway, but I think can be 2-3 line methods that mostly rely on logic in the types packages.

**Comment by Stebalien** [comment]
So, the dumber way of doing this would be to add two methods:

- EthGetTransactionReceiptWithLimit
- EthGetTransactionByHashWithLimit

And call those from the gateway.

**Comment by Stebalien** [comment]
The precident is `StateSearchMsgLimited`.

**Comment by raulk** [comment]
That probably works, but the exception is eth_feeHistory, where the limit does not represent a lookback, but the actual number of tipsets that will be processed. So it's not safe to use the gateway's chain lookback configuration (operators usually set to 24h worth of tipsets, which would mean that eth_feeHistory would be allowed to process a max of 2880 tipsets, that's a lot!). We might be able to statically limit eth_feeHistory though.

**Comment by Stebalien** [comment]
> That probably works, but the exception is eth_feeHistory, where the limit does not represent a lookback, but the actual number of tipsets that will be processed. So it's not safe to use the gateway's chain lookback configuration (operators usually set to 24h worth of tipsets, which would mean that eth_feeHistory would be allowed to process a max of 2880 tipsets, that's a lot!). We might be able to statically limit eth_feeHistory though in the Eth API.

We already do (128).

**Comment by Stebalien** [comment]
I'm also planning on fudging it and caching rough 5% percentiles.

**Comment by Stebalien** [comment]
Alternatives:

- Configure a limit for just the ETH APIs.
- Re-implement this in the gateway as suggested by Aayush.
- Rely on the index. I.e., we _could_ just flat-out refuse to return anything not indexed.
