### ISSUE TITLE
Eth API: harden parseBlkParam against null rounds

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#10426]
## Problem

Many Eth API calls can take a block parameter, which can be a tagged value (`earliest`, `pending`, `latest`) or a concrete epoch (e.g. `0x1234`). When supplied a concrete epoch, this method uses `GetTipsetByHeight` requesting the **next** tipset if the requested epoch happened to be a null round.

https://github.com/filecoin-project/lotus/blob/d8e324b61ae3d0227f67cb820fbe1f4ca9f73e5a/node/impl/full/eth.go#L256

This logic is not sound since an application traversing the chain with `eth_getBlockByNumber` will be returned the same tipset more than once, and will likely fail to recognise that edge case. The result may be that the app processes the same transactions more than once.

Additionally, other `eth_` methods that access state will return future state, instead of the state prevalent at the requested height.

## Solution

1. Add a "strict" bool param to `parseBlkParam`.
	- When `true`, error when the block is a null round.
	- When `false`, switch to returning the previous non-null tipset, instead of the following one as we do today.
2. Apply the right strictness on `eth_` methods.
	- `strict=true`
		- `eth_getBlockByNumber`: `strict=true`. Return an empty block on a null round.
	- `strict=false` (all these are state accessors, and the relevant state to return is the past one, not the future one)
		- `eth_getTransactionCount`
		- `eth_getBalance`
		- `eth_getStorageAt`
		- `eth_call`
		- `eth_getCode`
		- `eth_feeHistory`

**Comment by arajasek** [comment]
> Many Eth API calls can take a block parameter, which can be a tagged value (`earliest`, `pending`, `latest`) or a concrete epoch (e.g. `0x1234`). When supplied a concrete epoch, this method uses `GetTipsetByHeight` requesting the **next** tipset if the requested epoch happened to be a null round.
...
> Additionally, other `eth_` methods that access state will return future state, instead of the state prevalent at the requested height.

@raulk I think a lot of these gotchas can be avoided if the EthAPI implementation used the other APIs, in particular the ChainAPI, instead of accessing the ChainStore directly. Those APIs have been hardened around sharp edges like these over the years, and so will avoid a wave of minor issues.

In this case, the ChainAPI's `ChainGetTipsetByHeight` defaults to always asking for the previous tipset, which is generally what we want https://github.com/filecoin-project/lotus/blob/71b21db0d9e846ceae006aa764c4e82240a62afa/node/impl/full/chain.go#L252

**Comment by raulk** [comment]
Good flag! I switched the associated PR to use the higher-level API based on the recommendation. For the broader topic of removing the ChainStore, we should evaluate if it's feasible, as in some cases we _do_ need lower-level access. Returning the nonce of an EVM smart contract is an extreme example, but we can probably port others to use high-level APIs, or create high-level equivalents if needed (although this may be superfluous if they're just pass-through).
