### ISSUE TITLE
Add atomic balance lookup by block height

### ISSUE THREAD

**Issue by ianjdarrow** [filecoin-project/lotus#1043]
For various Good Reasons, the Lotus RPC interface should include the ability to fetch an account balance “atomically” (i.e., the account balance response includes the height at which the node performed the balance fetch). 

For example:

`GET /balance/address1` -> `{balance: 10, height: 100}`

**Comment by whyrusleeping** [comment]
StateGetActor accepts an address, and a tipset. IT will return the actor state (which includes balance) as of that particular tipset.

**Comment by magik6k** [comment]
And if you care about a particular height, you can pair this with `ChainGetTipSetByHeight`
