### ISSUE TITLE
retrieve file err

### ISSUE THREAD

**Issue by johnli-helloworld** [filecoin-project/lotus#1044]
**Describe the bug**
When I finished an deal, I started to retrieve the file, but kept getting an error

**To Reproduce**
base：
1. lotus import -> cid
2. lotus deal -> deal complete
2. lotus retrieve -> error

**Expected behavior**
Download the correct file

**Screenshots**
![image](https://user-images.githubusercontent.com/26270251/72029103-d2807e00-32bf-11ea-85d3-c9be5162bfa9.png)

**Version (run `lotus --version`):**
0.1.5

**Comment by johnli-helloworld** [comment]
2020-01-08T07:20:43.127Z	WARN	main	lotus/main.go:75	Retrieval Failed:
    github.com/filecoin-project/lotus/cli.glob..func13
        /home/john/go/src/github.com/filecoin-project/lotus/cli/client.go:243
  - RetrieveUnixfs: retrieval exchange: sending incremental retrieval request: stream reset

**Comment by magik6k** [comment]
This may be caused by opening the stream before setting up payment channels on-chain, which can take ~2min with current block times. During that time we're not using this stream, so it times out. There's likely a similar issue with deals.

cc @hannahhoward

**Comment by arajasek** [comment]
since fixed
