### ISSUE TITLE
Occasional random `error in RPC call to 'Filecoin.StorageReportHealth': health report for unknown storage: <GUID>`

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#10448]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.20.1
```

### Repro Steps

1. When running the miner I see the occasional error message;
```json
{"level":"warn","ts":"2023-03-11T02:12:06.759Z","logger":"rpc","caller":"go-jsonrpc@v0.1.8/handler.go:329","msg":"error in RPC call to 'Filecoin.StorageReportHealth': health report for unknown storage: 100a7cd2-417f-4f5b-93ab-ed92ea4cf262:\n    github.com/filecoin-project/lotus/storage/paths.(*Index).StorageReportHealth\n        /home/lotus/lotus/storage/paths/index.go:315"}
```

I've traced this file back to be in the following sectorstore;
```text
/tmp/lotus-memrepo-temp-2187664587/sectorstore.json
```

Looking at the codepaths, it seems that this one gets created when `lotus-miner init` is called.

After renaming the filepath, the error persist - so this is indicative that there is some cached value somewhere, where lotus tries to prove its storage health to itself with this non-existing datastore.

**Comment by magik6k** [comment]
1. Is this on some test setup
2. Have you run a devnet on that box previously?
  2.1. If yes, can you check if there are any stray lotus-worker processes hanging around?

**Comment by RobQuistNL** [comment]
- This is on all my production machines
- Already checked that - literally nothing else but the main miner and daemon.

**Comment by RobQuistNL** [comment]
Edit: Its not happening on _all_ machines :thinking:

There's some machines where the error is _not_ popping up, but they _do_ have one or 2 of those temp folders.

Any more ideas on where to look? I don't see any stray lotus or boost processes.. Just daemon and miner.

**Comment by RobQuistNL** [comment]
yeah nah
