### ISSUE TITLE
Boost repeatedly logs event diff fn failed: unknown actor code bafk2bzace...

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/lotus#10482]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus v1.20.3
```

### Describe the Bug

Storage Providers running boost are seeing the following message in the logs repeatedly:
```
2023-03-14T15:16:21.093Z	ERROR	events	events/events_called.go:354	event diff fn failed: unknown actor code bafk2bzaceclejwjtpu2dhw3qbx6ow7b4pmhwa7ocrbbiqwp36sq5yeg6jz2bc
```

`bafk2bzaceclejwjtpu2dhw3qbx6ow7b4pmhwa7ocrbbiqwp36sq5yeg6jz2bc` is the actor code cid of the storage market actor in [builtin-actors v10.0.0](https://github.com/filecoin-project/builtin-actors/releases/tag/v10.0.0):
```
"storagemarket":    "bafk2bzaceclejwjtpu2dhw3qbx6ow7b4pmhwa7ocrbbiqwp36sq5yeg6jz2bc"
```

The legacy markets code watches the chain for changes to deal state for legacy storage deals (this chain-watching feature is not present in the newer boost code). From the error message above it seems that the chain watching code is looking for the storage market actor on chain but not finding it. I believe this is coming from:
https://github.com/filecoin-project/lotus/blob/v1.20.3/chain/events/state/predicates.go#L75

I'm not familiar enough with the actors changes in lotus to know how to resolve this issue.

Currently this issue is annoying, but not preventing anyone from making deals or sealing.

### Logging Information

```text
2023-03-14T15:16:21.093Z	ERROR	events	events/events_called.go:354	event diff fn failed: unknown actor code bafk2bzaceclejwjtpu2dhw3qbx6ow7b4pmhwa7ocrbbiqwp36sq5yeg6jz2bc
```
```

**Comment by William8Work** [comment]
Seeing the same thing lotus v1.20.0, and boost v1.6.0-rc2

**Comment by Stebalien** [comment]
That error would be coming from https://github.com/filecoin-project/lotus/blob/b332db0a383229cf43e4836dce6adefd7274c859/chain/actors/builtin/market/market.go#L83.

But we should be hitting https://github.com/filecoin-project/lotus/blob/b332db0a383229cf43e4836dce6adefd7274c859/chain/actors/builtin/market/market.go#L52

But your problem is likely https://github.com/filecoin-project/lotus/blob/2c6e0673046031cb6e759259a8962e0d9bbeebeb/build/builtin_actors_gen.go#L340

Boost is depending on an outdated lotus fork.
