### ISSUE TITLE
lotus daemon crash

### ISSUE THREAD

**Issue by ohJohanZ** [filecoin-project/lotus#1048]
**Describe the bug**
lotus daemon crash

**To Reproduce**
1. Run lotus daemon
2. See error

**Version (run `lotus --version`):**
lotus version 0.1.5+git11bfab67

**Additional context**
2020-01-09T16:02:19.946+0800	[34mINFO[0m	chain	chain/sync.go:156	incoming tipset from [t01475] does not appear to be better than our best chain, ignoring for now
2020-01-09T16:02:20.692+0800	[34mINFO[0m	blocksync	blocksync/blocksync.go:96	block sync request for: [bafy2bzacebzbnpukimc6cgig5dufhzzj7jbpmj7jemu2g7nup3bdwzyttkk6k] 500
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1a29645, 0x16)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc12c000000, 0x5c000000, 0x2a4b538)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x2a32120, 0x5beee000, 0x7fab57ffe928, 0x518e67)
	/usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x2a32120, 0x2df77, 0xffffffff)
	/usr/local/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x2a32120, 0x2df77, 0x2a4b548, 0x23d3388)
	/usr/local/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x2a32120, 0x2df77, 0x101, 0x7c8)
	/usr/local/go/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x2a32120, 0x2df77, 0x7fab57000101, 0xc000318c00)
	/usr/local/go/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x5beee000, 0x100, 0x53b801)
	/usr/local/go/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1146

goroutine 381 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc006107a78 sp=0xc006107a70 pc=0x53f130
runtime.mallocgc(0x5beee000, 0x0, 0x3ad64000, 0xc0b7272000)
	/usr/local/go/src/runtime/malloc.go:1032 +0x895 fp=0xc006107b18 sp=0xc006107a78 pc=0x4ee5b5
runtime.growslice(0x1807c60, 0xc0b7272000, 0x9317c00, 0x9317c00, 0x9317c01, 0xc0b7272000, 0x75ac800, 0x9317c00)
	/usr/local/go/src/runtime/slice.go:175 +0x14e fp=0xc006107b80 sp=0xc006107b18 pc=0x527c5e
github.com/filecoin-project/lotus/lib/rlepluslazy.SliceFromRuns(0x1ce8dc0, 0xc018a1b380, 0x13, 0xc01df91170, 0x1ce8dc0, 0xc018a1b380, 0x0)
	/home/johan/lotus/lib/rlepluslazy/bits.go:144 +0x134 fp=0xc006107c00 sp=0xc006107b80 pc=0xa2df64
github.com/filecoin-project/lotus/chain/types.BitField.AllMap(0xc01dfa0820, 0x13, 0x13, 0xc01df91170, 0xc01fa7fce0, 0x0, 0x0)
	/home/johan/lotus/chain/types/bitfield.go:131 +0x7e fp=0xc006107c70 sp=0xc006107c00 pc=0xa500de
github.com/filecoin-project/lotus/chain/actors.StorageMinerActor.SubmitFallbackPoSt(0xc01df90990, 0x1d0d960, 0xc00f172850, 0xc01df90ff0, 0x50, 0xc006107fe0, 0x5cb3bc, 0x18805e0, 0x18805e0)
	/home/johan/lotus/chain/actors/actor_miner.go:579 +0x2d5 fp=0xc006107f08 sp=0xc006107c70 pc=0xa6c2f5
github.com/filecoin-project/lotus/chain/actors.StorageMinerActor.SubmitFallbackPoSt-fm(0xc01df90990, 0x1d0d960, 0xc00f172850, 0xc01df90ff0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/johan/lotus/chain/actors/actor_miner.go:523 +0x4d fp=0xc006107f60 sp=0xc006107f08 pc=0xa9b0ad
runtime.call128(0xc0153094d0, 0xc007253680, 0xc0143c65a0, 0x2000000048)
	/usr/local/go/src/runtime/asm_amd64.s:541 +0x52 fp=0xc006107ff0 sp=0xc006107f60 pc=0x53f602
reflect.Value.call(0x1874fa0, 0xc007253680, 0x13, 0x1a14feb, 0x4, 0xc006108360, 0x3, 0x3, 0x1, 0x18805e0, ...)
	/usr/local/go/src/reflect/value.go:460 +0x5f6 fp=0xc006108210 sp=0xc006107ff0 pc=0x5c1b46
reflect.Value.Call(0x1874fa0, 0xc007253680, 0x13, 0xc006108360, 0x3, 0x3, 0x0, 0x1806ca0, 0xc006108370)
	/usr/local/go/src/reflect/value.go:321 +0xb4 fp=0xc006108290 sp=0xc006108210 pc=0x5c1304
github.com/filecoin-project/lotus/chain/vm.(*invoker).transform.func2(0xc0143c64b0, 0x3, 0x3, 0xc0143c64b0, 0x30, 0xc01df9ac90)
	/home/johan/lotus/chain/vm/invoker.go:144 +0x226 fp=0xc0061083b8 sp=0xc006108290 pc=0xaaafd6
reflect.callReflect(0xc0081102a0, 0xc006108520, 0xc006108508)
	/usr/local/go/src/reflect/value.go:549 +0x322 fp=0xc0061084f0 sp=0xc0061083b8 pc=0x5c2e42
reflect.makeFuncStub(0xc01df90990, 0x1d0d960, 0xc00f172850, 0xc00ef4ef00, 0xe9, 0xe9, 0xc01df9ac90, 0xc0061085a0, 0x623abd, 0xc01df9ac90, ...)
	/usr/local/go/src/reflect/asm_amd64.s:20 +0x42 fp=0xc006108520 sp=0xc0061084f0 pc=0x5ce992
github.com/filecoin-project/lotus/chain/vm.(*invoker).Invoke(0xc0113f4650, 0xc01df90990, 0x1d0d960, 0xc00f172850, 0x4, 0xc00ef4ef00, 0xe9, 0xe9, 0xc01df90fc0, 0xc01df72200, ...)
	/home/johan/lotus/chain/vm/invoker.go:58 +0x1c2 fp=0xc006108620 sp=0xc006108520 pc=0xaa39c2
github.com/filecoin-project/lotus/chain/vm.(*VM).Invoke(0xc00b815aa0, 0xc01df90990, 0xc00f172850, 0x4, 0xc00ef4ef00, 0xe9, 0xe9, 0x0, 0x0, 0x0, ...)
	/home/johan/lotus/chain/vm/vm.go:648 +0x218 fp=0xc0061087a0 sp=0xc006108620 pc=0xaaa3e8
github.com/filecoin-project/lotus/chain/vm.(*VM).send(0xc00b815aa0, 0x1cf9fc0, 0xc01df24b40, 0xc0121dbf80, 0x0, 0x270, 0x0, 0x0, 0x0, 0x0, ...)
	/home/johan/lotus/chain/vm/vm.go:388 +0x236 fp=0xc0061088a8 sp=0xc0061087a0 pc=0xaa7a46
github.com/filecoin-project/lotus/chain/vm.(*VM).ApplyMessage(0xc00b815aa0, 0x1cf9fc0, 0xc01df24b40, 0xc0121dbf80, 0x0, 0x0, 0x0)
	/home/johan/lotus/chain/vm/vm.go:461 +0x5c1 fp=0xc006108b80 sp=0xc0061088a8 pc=0xaa86e1
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).computeTipSetState(0xc000453140, 0x1cf9fc0, 0xc008820750, 0xc01114b640, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/home/johan/lotus/chain/stmgr/stmgr.go:242 +0x1852 fp=0xc006109068 sp=0xc006108b80 pc=0xbede82
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).TipSetState(0xc000453140, 0x1cf9fc0, 0xc008820720, 0xc00e8bd8c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/johan/lotus/chain/stmgr/stmgr.go:100 +0x69d fp=0xc006109240 sp=0xc006109068 pc=0xbec2ed
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock(0xc000097c20, 0x1cf9fc0, 0xc008b5e240, 0xc00cf42880, 0x0, 0x0)
	/home/johan/lotus/chain/sync.go:567 +0x514 fp=0xc006109618 sp=0xc006109240 pc=0xcf39b4
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet(0xc000097c20, 0x1cf9fc0, 0xc00d619dd0, 0xc00cf427c0, 0x0, 0x0)
	/home/johan/lotus/chain/sync.go:438 +0x242 fp=0xc006109740 sp=0xc006109618 pc=0xcf2e22
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1(0x1cf9fc0, 0xc011ee7710, 0xc00cf427c0, 0xc00d156580, 0x4)
	/home/johan/lotus/chain/sync.go:1024 +0x1d9 fp=0xc006109840 sp=0xc006109740 pc=0xd00479
github.com/filecoin-project/lotus/chain.(*Syncer).iterFullTipsets(0xc000097c20, 0x1cf9fc0, 0xc011ee7710, 0xc012305000, 0x190, 0x200, 0xc006109b48, 0x0, 0x0)
	/home/johan/lotus/chain/sync.go:1083 +0x4c1 fp=0xc006109af8 sp=0xc006109840 pc=0xcf9ed1
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState(0xc000097c20, 0x1cf9fc0, 0xc0118b6cc0, 0xc012305000, 0x190, 0x200, 0x3, 0x3)
	/home/johan/lotus/chain/sync.go:1022 +0x112 fp=0xc006109b70 sp=0xc006109af8 pc=0xcf99b2
github.com/filecoin-project/lotus/chain.(*Syncer).collectChain(0xc000097c20, 0x1cf9fc0, 0xc0118b6b10, 0xc01068ffc0, 0x0, 0x0)
	/home/johan/lotus/chain/sync.go:1157 +0x60e fp=0xc006109d80 sp=0xc006109b70 pc=0xcfb2be
github.com/filecoin-project/lotus/chain.(*Syncer).Sync(0xc000097c20, 0x1cf9fc0, 0xc0118b6b10, 0xc01068ffc0, 0x0, 0x0)
	/home/johan/lotus/chain/sync.go:392 +0x1d5 fp=0xc006109ee8 sp=0xc006109d80 pc=0xcf24c5
github.com/filecoin-project/lotus/chain.(*Syncer).Sync-fm(0x1cf9fc0, 0xc0118b6ae0, 0xc01068ffc0, 0x2a49568, 0x18efa80)
	/home/johan/lotus/chain/sync.go:373 +0x48 fp=0xc006109f28 sp=0xc006109ee8 pc=0xd00ea8
github.com/filecoin-project/lotus/chain.(*SyncManager).syncWorker(0xc000458c60, 0x1)
	/home/johan/lotus/chain/sync_manager.go:386 +0x16f fp=0xc006109fd0 sp=0xc006109f28 pc=0xcfddcf
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc006109fd8 sp=0xc006109fd0 pc=0x541201
created by github.com/filecoin-project/lotus/chain.(*SyncManager).Start
	/home/johan/lotus/chain/sync_manager.go:74 +0x6f

goroutine 1 [IO wait, 3 minutes]:
internal/poll.runtime_pollWait(0x7fb1d987fa28, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc01054af98, 0x72, 0x0, 0x0, 0x1a18595)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc01054af80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc01054af80, 0x203004, 0xc01a3977a8, 0x4ee036)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc010545b60, 0x30, 0x50, 0x50)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc010545b60, 0x1956c40, 0xc01a397828, 0x5501c0, 0x30)
	/usr/local/go/src/net/tcpsock.go:261 +0x47
github.com/multiformats/go-multiaddr-net.(*maListener).Accept(0xc010545be0, 0x7ee2cf, 0xc01a397828, 0x4ee8a8, 0x30)
	/home/johan/go/pkg/mod/github.com/multiformats/go-multiaddr-net@v0.1.1/net.go:243 +0x37
github.com/multiformats/go-multiaddr-net.(*netListenerAdapter).Accept(0xc01055e4a0, 0x1956c40, 0xc01053cc30, 0x1864e60, 0x2920810)
	/home/johan/go/pkg/mod/github.com/multiformats/go-multiaddr-net@v0.1.1/net.go:222 +0x33
net/http.(*Server).Serve(0xc000388460, 0x1cf41c0, 0xc01055e4a0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2896 +0x280
main.serveRPC(0x1d1a380, 0xc000448e00, 0xc010427d70, 0x1d0cae0, 0xc0104e2e40, 0xc010427d70, 0x0)
	/home/johan/lotus/cmd/lotus/rpc.go:65 +0x495
main.glob..func1(0xc000372fc0, 0x0, 0x0)
	/home/johan/lotus/cmd/lotus/daemon.go:129 +0x83b
gopkg.in/urfave/cli%2ev2.(*Command).Run(0x2934f40, 0xc000372f60, 0x0, 0x0)
	/home/johan/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:167 +0x6cf
gopkg.in/urfave/cli%2ev2.(*App).Run(0xc00008a300, 0xc0000ba020, 0x2, 0x2, 0x0, 0x0)
	/home/johan/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/app.go:261 +0x68c
main.main()
	/home/johan/lotus/cmd/lotus/main.go:70 +0x70c

goroutine 19 [select, 3 minutes]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0000acff0)
	/home/johan/go/pkg/mod/github.com/ipfs/go-log@v1.0.0/writer/writer.go:76 +0x144
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	/home/johan/go/pkg/mod/github.com/ipfs/go-log@v1.0.0/writer/writer.go:41 +0xb9

goroutine 20 [syscall, 3 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 13 [select, 3 minutes]:
github.com/jbenet/goprocess/context.CloseAfterContext.func1(0x1cf9f00, 0xc0004f4700, 0x1d09ce0, 0xc00044b920)
	/home/johan/go/pkg/mod/github.com/jbenet/goprocess@v0.1.3/context/context.go:65 +0xd8
created by github.com/jbenet/goprocess/context.CloseAfterContext
	/home/johan/go/pkg/mod/github.com/jbenet/goprocess@v0.1.3/context/context.go:64 +0xa7

goroutine 23 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000ceaa0)
	/home/johan/go/pkg/mod/go.opencensus.io@v0.22.2/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/home/johan/go/pkg/mod/go.opencensus.io@v0.22.2/stats/view/worker.go:32 +0x57

goroutine 31 [select, 3 minutes]:
github.com/jbenet/goprocess/context.CloseAfterContext.func1(0x1cf9f00, 0xc00037a240, 0x1d09ce0, 0xc000385c20)
	/home/johan/go/pkg/mod/github.com/jbenet/goprocess@v0.1.3/context/context.go:65 +0xd8
created by github.com/jbenet/goprocess/context.CloseAfterContext
	/home/johan/go/pkg/mod/github.com/jbenet/goprocess@v0.1.3/context/context.go:64 +0xa7

goroutine 10 [runnable]:
github.com/libp2p/go-yamux.asyncNotify(0xc01997ec00)
	/home/johan/go/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/util.go:15 +0x4d
github.com/libp2p/go-yamux.(*Stream).notifyWaiting(0xc0175b4380)
	/home/johan/go/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/stream.go:382 +0x47
github.com/libp2p/go-yamux.(*Stream).forceClose(0xc0175b4380)
	/home/johan/go/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/stream.go:321 +0x66
github.com/libp2p/go-yamux.(*Session).Close(0xc00da645b0, 0x0, 0x0)
	/home/johan/go/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/session.go:258 +0x1f4
github.com/libp2p/go-libp2p-yamux.(*conn).Close(0xc00da645b0, 0xc00008a780, 0xc00009d0b0)
	/home/johan/go/pkg/mod/github.com/libp2p/go-libp2p-yamux@v0.2.1/yamux.go:19 +0x2b
github.com/libp2p/go-libp2p-swarm.(*Conn).doClose(0xc017419a40)
	/home/johan/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_conn.go:61 +0xb0
sync.(*Once).doSlow(0xc017419a58, 0xc00cc4fdb0)
	/usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
github.com/libp2p/go-libp2p-swarm.(*Conn).Close(0xc017419a40, 0x1cf9f00, 0xc0004f4400)
	/home/johan/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_conn.go:48 +0x77
github.com/libp2p/go-libp2p-connmgr.(*BasicConnMgr).TrimOpenConns(0xc0002d2400, 0x1cf9f00, 0xc0004f4400)
	/home/johan/go/pkg/mod/github.com/libp2p/go-libp2p-connmgr@v0.1.0/connmgr.go:185 +0x383
github.com/libp2p/go-libp2p-connmgr.(*BasicConnMgr).background(0xc0002d2400)
	/home/johan/go/pkg/mod/github.com/libp2p/go-libp2p-connmgr@v0.1.0/connmgr.go:199 +0x15d
created by github.com/libp2p/go-libp2p-connmgr.NewConnManager
	/home/johan/go/pkg/mod/github.com/libp2p/go-libp2p-connmgr@v0.1.0/connmgr.go:114 +0x1e5

goroutine 88 [select, 3 minutes]:
github.com/ipfs/go-bitswap/providerquerymanager.(*ProviderQueryManager).providerRequestBufferWorker(0xc000097080)
	/home/johan/go/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/providerquerymanager/providerquerymanager.go:289 +0x164
created by github.com/ipfs/go-bitswap/providerquerymanager.(*ProviderQueryManager).run
	/home/johan/go/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/providerquerymanager/providerquerymanager.go:315 +0x94

goroutine 30 [select, 3 minutes]:
github.com/ipfs/go-ds-badger.(*Datastore).periodicGC(0xc00ffdeb40)
	/home/johan/go/pkg/mod/github.com/ipfs/go-ds-badger@v0.0.7/datastore.go:144 +0x110
created by github.com/ipfs/go-ds-badger.NewDatastore
	/home/johan/go/pkg/mod/github.com/ipfs/go-ds-badger@v0.0.7/datastore.go:132 +0x369

goroutine 14616 [select]:
github.com/libp2p/go-yamux.(*Session).sendLoop(0xc010031930, 0x0, 0x0)
	/home/johan/go/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/session.go:438 +0x1cb
github.com/libp2p/go-yamux.(*Session).send(0xc010031930)
	/home/johan/go/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/session.go:384 +0x2b
created by github.com/libp2p/go-yamux.newSession
	/home/johan/go/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/session.go:130 +0x3a8

goroutine 9 [select, 3 minutes]:
github.com/libp2p/go-libp2p-peerstore/pstoremem.(*memoryAddrBook).background(0xc0002d0900)
	/home/johan/go/pkg/mod/github.com/libp2p/go-libp2p-peerstore@v0.1.4/pstoremem/addr_book.go:81 +0x12f
created by github.com/libp2p/go-libp2p-peerstore/pstoremem.NewAddrBook
	/home/johan/go/pkg/mod/github.com/libp2p/go-libp2p-peerstore@v0.1.4/pstoremem/addr_book.go:71 +0x18e

**Comment by magik6k** [comment]
This was fixed in 0.1.6
