### ISSUE TITLE
storageask: collateral field

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#1050]
In _2.8.1.7_ section of the spec, it mentions a `Collateral` field:
```
type StorageAsk struct {
    Price             abi.TokenAmount  // attoFIL per GiB per epoch
    Collateral        abi.TokenAmount  // attoFIL per GiB per epoch

    MinPieceSize      piece.PieceSize
    // address of miner actor for deals
    Miner             addr.Address
    // the epoch at the time this ask was published
    PublicationEpoch  abi.ChainEpoch
    MaxDuration       abi.ChainEpoch
    MinDuration       abi.ChainEpoch
    // a miner should update sequence number each time it publishes an ask
    // so that anyone with two asks from the same miner can determine which is
    // more current
    SeqNo             UVarint
}
```
Could be added to the [current](https://github.com/filecoin-project/lotus/blob/f572d9735d21388fd9cc5130f1e9a33730798058/chain/types/ask.go#L18) struct?
There're also other field differences to fully align with the spec description.

**Comment by magik6k** [comment]
Not sure how relevant this is now, but it seems like we still don't have that field

**Comment by hannahhoward** [comment]
This would be Client Collateral requirement presumably? Is this a thing Miners would want?

**Comment by hannahhoward** [comment]
^^ cc: @zixuanzh @whyrusleeping @magik6k  -- I really don't understand the issues well enough to know if miners would actually want to be able to set a ClientCollateral requirement.

**Comment by jsign** [comment]
Notice that I created this on January. This isn't a blocking thing for us.

Might worth checking [other recent issues](https://github.com/filecoin-project/lotus/issues/created_by/jsign) that I created which feel more important.

**Comment by jennijuju** [comment]
probably not the highest required feature rn, can reopen the ticket later with the use case
