### ISSUE TITLE
Problem extending sectors expiration time

### ISSUE THREAD

**Issue by srene** [filecoin-project/lotus#10525]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.21.0-dev+mainnet+git.a5ffab705+api1.5.0
Local: lotus-miner version 1.21.0-dev+mainnet+git.a5ffab705
```

### Repro Steps

I can't extend expiration time of existing CC sectors to enable them for snap-deals

1. Run lotus-miner sectors extend --new-expiration <expiry-epoch> <sectornumber>
2. Result is always 'nothing to extend'

### Describe the Bug

I can't extend expiration time of existing CC, as detailed in here https://lotus.filecoin.io/storage-providers/operate/snap-deals/#extension-workflow
when running the command ' lotus-miner sectors extend --new-expiration <expiry-epoch> <sectornumber>' i always same result 'nothing to extend' with no result
i think the problem started after upgrading lotus to v1.21

### Logging Information

```text
i was not able to observe any related log
```

**Comment by rjan90** [comment]
Hey @srene! Looks like you might have pulled from the master branch as the v1.21.0 release candidate or stable release is not out yet.

The first release candidate of v1.21.0 is expected to be out later today, and with the release there are some changes to the `lotus-miner sectors extend` command that has not been reflected yet.

You can follow along with the lotus-docs changes about this command here: https://github.com/filecoin-project/lotus-docs/issues/526.

For now I would suggest to use the `lotus-miner sectors extend --help` command to navigate. The `lotus-miner sectors extend` command has been refactored to have the features of the lotus-miner sectors renew command: https://lotus.filecoin.io/storage-providers/operate/daily-chores/#extend-sectors

**Comment by srene** [comment]
Hi @rjan90. I didn't realize v1.21.0 was not realease yet. By now i just downgraded to v1.20.4 and problem solved. I'll have a look to the new docs after the changes. Thanks a lot for your help!

**Comment by rjan90** [comment]
Sounds good! I will send you an update here when its done

**Comment by TippyFlitsUK** [comment]
Looks like this has been re-introduced in 1.21.0-rc1 so re-opening the ticket.
@magik6k @shrenujbansal - I'm making this P1 as sector extension is essential for snap deal SPs.

**Comment by TippyFlitsUK** [comment]
I have confirmed that extension is working on 1.20.4. This is only affecting 1.21.0-rc1.

**Comment by TippyFlitsUK** [comment]
I'm able to return the JSON @arajasek but I'm still getting a `--really-do-it` error:

```
lotus-miner sectors extend --new-expiration 4264230 7740
Extending 1 sectors: 
 {
  "Extensions": [
    {
      "Deadline": 0,
      "Partition": 0,
      "Sectors": "7740",
      "NewExpiration": 4264230
    }
  ]
}
1 sectors extended
```
```
lotus-miner sectors extend --really-do-it --new-expiration 4264230 7740
Extending 1 sectors: ERROR: mpool push message: GasEstimateMessageGas error: message execution failed: exit 21, reason: message failed with backtrace:
00: f08403 (method 8) -- Serialization error for Cbor protocol: RequireLength { name: "tuple", expect: 4, value: 5 } (21)
 (RetCode=21)
```

**Comment by TippyFlitsUK** [comment]
This is now working in the latest push to asr/fix-extend-sectors! 👍 

```
lotus-miner sectors extend --really-do-it --new-expiration 4264230 7741
Extending 1 sectors: bafy2bzaceagbvqea44msxjiktd6zsdzrb75yjcggswqhn6b2pr5hgs622b65c
1 sectors extended
```

**Comment by rjan90** [comment]
Closing as this has been fixed with:
- https://github.com/filecoin-project/lotus/pull/10544
- https://github.com/filecoin-project/lotus/pull/10606
