### ISSUE TITLE
Eth RPC: Address performance of EthGetTransactionByHash

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/lotus#10539]
We identified `EthGetTransactionByHash` as one of the hotspots on Glif production nodes. The goal of this issue is to investigate the reason and fix it.

![image (1)](https://user-images.githubusercontent.com/17002645/226992338-1aeef2d2-3498-46de-8fc1-c584d95d7b0f.png)

**Comment by fridrik01** [comment]
This should be fixed with https://github.com/filecoin-project/lotus/pull/10955
