### ISSUE TITLE
Eth RPC: Address performance of EthGetTransactionReceipt

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/lotus#10541]
We identified `EthGetTransactionReceipt` as one of the hotspots on Glif production nodes. The goal of this issue is to investigate the reason and fix it.
![image (4)](https://user-images.githubusercontent.com/17002645/226992828-22a32acc-d2a2-45e0-900b-fb0910af6104.png)

**Comment by fridrik01** [comment]
This should be fixed with https://github.com/filecoin-project/lotus/pull/10955
