### ISSUE TITLE
lotus-fountain: make compatible with 0x addresses

### ISSUE THREAD

**Issue by ognots** [filecoin-project/lotus#10560]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

make calibrationnet and other devnets FVM friendly, by making `lotus-fountain` compatible with 0x addresses.
this is necessary for the [quick start tutorial](https://docs.filecoin.io/smart-contracts/fundamentals/erc-20-quickstart/) to work as published

### Describe the solution you'd like

Call `EthAddressToFilecoinAddress` when an 0x type address is detected in lotus-fountain's address field in the SENDING FUNDS section

**Comment by ognots** [comment]
Relevant code https://github.com/filecoin-project/lotus/tree/master/cmd/lotus-fountain

**Comment by maciejwitowski** [comment]
Took a stab at implementing it https://github.com/filecoin-project/lotus/pull/10784

**Comment by ognots** [comment]
Thanks @maciejwitowski this looks great. we'll still need a review from the lotus maintainers team. Let me know if you want me to escalate the priority of the review, this is a very important feature for the community
