### ISSUE TITLE
lotus lose sync randomly

### ISSUE THREAD

**Issue by Aloxaf** [filecoin-project/lotus#10570]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.21.0-dev+mainnet+git.ad7c79d95+api1.5.0
Local: lotus version 1.21.0-dev+mainnet+git.ad7c79d95
```

### Repro Steps

1. Run 'lotus daemon'
2. Do 'Just wait'
3. See error 'lotus daemon stopped sync'
...

### Describe the Bug

Many of our lotus nodes lose sync randomly recently.
I have tried many ways like "re-import the snapshot", "turn on/off splitstore", "form raid0 with two enterprise SSDs", "update the latest dev version".

Here is an example, y-axis is "lost height":
![图片](https://user-images.githubusercontent.com/17017672/227916015-b5f78fe3-757f-467e-bc35-bc9fb9b5d8b3.png)

`lotus sync wait` shows the state is "complete"
```
> lotus sync wait
Worker: 9421; Base: 2720185; Target: 2720188 (diff: 3)
State: complete; Current Epoch: 2720188; Todo: 0
Validated 0 messages (0 per second)
^C
Exit by user
```

Result of `lotus status` and `lotus sync status`

```
> lotus sync status
sync status:
worker 9419:
        Base:   [bafy2bzacedmzwitw7hz6awuga3ifh6y72xwm5fnfizbrnkikoshgmghj6wxxm bafy2bzaceaayeg6gov5jmxahcl4dpiclb6sr3zsqnkouz33gvjamah5ugru3u bafy2bzacecfku3qfxu56jjtmt3l3z4dkcntwo75nzbn7bzvr54z3jzdbfkeza]
        Target: [bafy2bzaceckt6lsk23rex5vu3l4r2ful3qpfuwrkz2f3x4voxuuaisrfwkvkm bafy2bzacebcikcr3yxw7uhjksekohyjd46cs45zzr4oq2f3z7nmqiqwz46ux6 bafy2bzacedjphzt4kj5n3iycusiqgwt6kkdvggzsq22ahzr2hitg6ypxktacc bafy2bzaceao22zabqn3e7uc6nmihvohvzdky3llpstcjfvdjhjgdcazkqnsae bafy2bzacebf2rnxxlkhrrvst7gwgqulbk7duc4m3jwoo4cpd7lnqqpzg3afc4 bafy2bzaceb73q23clnbbobyru2w4p5w3lanqq2erxzv2y6qjjz66nj5pynsoi] (2720183)
        Height diff:    5
        Stage: complete
        Height: 2720183
        Elapsed: 40.065122316s
worker 9420:
        Base:   [bafy2bzaceckt6lsk23rex5vu3l4r2ful3qpfuwrkz2f3x4voxuuaisrfwkvkm bafy2bzacebcikcr3yxw7uhjksekohyjd46cs45zzr4oq2f3z7nmqiqwz46ux6 bafy2bzacedjphzt4kj5n3iycusiqgwt6kkdvggzsq22ahzr2hitg6ypxktacc bafy2bzaceao22zabqn3e7uc6nmihvohvzdky3llpstcjfvdjhjgdcazkqnsae bafy2bzacebf2rnxxlkhrrvst7gwgqulbk7duc4m3jwoo4cpd7lnqqpzg3afc4 bafy2bzaceb73q23clnbbobyru2w4p5w3lanqq2erxzv2y6qjjz66nj5pynsoi]
        Target: [bafy2bzacecpdiy6ibcs6c5lc7fta4lshnunpf2ylh6cag52vtszui5zb7losk bafy2bzacebayncazfcghbqh2zfgsmrpgse4kp5sdp6pr5cf6ag3vrfplku354 bafy2bzacectcrekovfvrwmh6id56pnkgj76nyzdn762h3wkcecmz5xfofmiqq bafy2bzacec23dpxqbswskvqq4wewtbryno6bklcg5f5cv35rijalopelriope bafy2bzaceahmc5iqg7nvoutxnykfe324aodcfomiaao3whpf3ghrmbr22wpeu bafy2bzacebrhz3lxwngrhqjl7mtpj46lbbhbiharspdnlmqevdxrj7yuvkmwk] (2720185)
        Height diff:    2
        Stage: complete
        Height: 2720185
        Elapsed: 10.1892486s
worker 9421:
        Base:   [bafy2bzacecpdiy6ibcs6c5lc7fta4lshnunpf2ylh6cag52vtszui5zb7losk bafy2bzacebayncazfcghbqh2zfgsmrpgse4kp5sdp6pr5cf6ag3vrfplku354 bafy2bzacectcrekovfvrwmh6id56pnkgj76nyzdn762h3wkcecmz5xfofmiqq bafy2bzacec23dpxqbswskvqq4wewtbryno6bklcg5f5cv35rijalopelriope bafy2bzaceahmc5iqg7nvoutxnykfe324aodcfomiaao3whpf3ghrmbr22wpeu bafy2bzacebrhz3lxwngrhqjl7mtpj46lbbhbiharspdnlmqevdxrj7yuvkmwk]
        Target: [bafy2bzaceacvyz7szmeylbytfqi5jzg2jva2f7jz5ppkalphnwtyxg4ov2eak bafy2bzacecvf35wm4k5czroj2t7i2hab2vsm26qt23szkwrkmj6doejtw6j34 bafy2bzaceclg2gml7ai45fdjtl7xpayxzqstp6qqvolqvhx24baftwa3eb4a4 bafy2bzacedhpub7crd5w2uuwlydoivpw5kisl54mbb7sfth3eqaysbwgzotc4] (2720188)
        Height diff:    3
        Stage: complete
        Height: 2720188
        Elapsed: 19.406979967s
> lotus status
Sync Epoch: 2720188
Epochs Behind: 12
Peers to Publish Messages: 48
Peers to Publish Blocks: 50
```

Here are the goroutine dump and daemon log when it loses sync:

[goroutines.zip](https://github.com/filecoin-project/lotus/files/11077525/goroutines.zip)
[daemon.zip](https://github.com/filecoin-project/lotus/files/11077545/daemon.zip)

### Logging Information

```text
[goroutines.zip](https://github.com/filecoin-project/lotus/files/11077525/goroutines.zip)
[daemon.zip](https://github.com/filecoin-project/lotus/files/11077545/daemon.zip)
```

**Comment by tddey01** [comment]
The community needs to urgently solve the horrible problem of crazy power loss due to the slow synchronization of lotus blocks

**Comment by airstring** [comment]
Is your disk iops and throughput high ?

**Comment by Aloxaf** [comment]
@airstring 
No, the problem disappeared. so strange.
