### ISSUE TITLE
ERROR: hello/hello.go:97 failed to fetch tipset from peer during hello: i/o deadline reached

### ISSUE THREAD

**Issue by chaingrok** [filecoin-project/lotus#1058]
** Description **

While syncing my local node with the filecoin testnet, I repeatedly get the ERROR of the title in the daemon log

Here is a log sample:

2020-01-11T06:26:32.957+0100	ERROR	hello	hello/hello.go:97	failed to fetch tipset from peer during hello: i/o deadline reached
github.com/filecoin-project/lotus/node/hello.(*Service).HandleStream
	/Users/ddurand/lotus/node/hello/hello.go:97
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	/Users/foo/go/pkg/mod/github.com/libp2p/go-libp2p@v0.4.2/p2p/host/basic/basic_host.go:393
2020-01-11T06:26:32.961+0100	WARN	blocksync	blocksync/blocksync_client.go:535	log failure called on peer not in trackerpeerid12D3KooWMQmmiM772u6R5SDtw3FtSNQYuvAFdnDgzELjA8Jyhz7K
2020-01-11T06:26:32.961+0100	ERROR	hello	hello/hello.go:97	failed to fetch tipset from peer during hello: i/o deadline reached
github.com/filecoin-project/lotus/node/hello.(*Service).HandleStream
	/Users/foo/lotus/node/hello/hello.go:97
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	/Users/foo/go/pkg/mod/github.com/libp2p/go-libp2p@v0.4.2/p2p/host/basic/basic_host.go:393
2020-01-11T06:26:33.007+0100	INFO	sub	sub/incoming.go:54	new block over pubsub

**To Reproduce**

- build lotus 0.1.6 via make (MacOs)
- run lotus daemon
- run lotus sync wait in a separate window 

**Expected behavior**

Syncing happens without this error

**Screenshots**
 see daemon log above

**Version (run `lotus --version`):**
lotus version 0.1.6+gitf572d973

**Comment by magik6k** [comment]
The hello protocol has seen some changes since this issue was opened. If you can still see this occurring, please reopen

**Comment by Drug0j** [comment]
hi
    ERROR   hello   hello/hello.go:107      failed to fetch tipset from peer during hello: blocksync req failed:
    github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).sendRequestToPeer
        /home/aqua/lotus/chain/blocksync/blocksync_client.go:269
