### ISSUE TITLE
Use new splitstore config values as default

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/lotus#10580]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

By default splitstore handles hotstore GC with the frequency approach.  By default every 20 compactions we do a full moving GC.  This brings the hotstore size down to 200 - 300GiB at the cost of higher disk space and compute overhead.

This causes a variable amount of disk space at max based on speed of compactions and levels of churn data, total state size and message data in a given day of the chain.  So local hardware and global network conditions can make this vary quite a lot.

### Describe the solution you'd like

We can set the newly developed config `HotStoreMaxSpaceTarget` to create a harder limit on space used before moving GC which more predictably bounds disk space used by the hotstore.

We'll also want to set `HotStoreMaxSpaceThreshold` and `HotstoreMaxSpaceSafetyBuffer` appropriately.

This isn't a panacea because it is possible that network conditions can exceed the threshold and the safefy buffer in one go and that emergency online GC isn't effective enough at bringing things down below safety threshold in this case.  But now excessive disk usage is an edge case that we should alert on (#10428) instead of the common case.

### Describe alternatives you've considered

We could raise the frequency of moving GC to keep average max space down but this still suffers from reproducibility

### Additional context

* @TippyFlitsUK was suggesting a MaxTarget of 500 GiB on slack.
* My own random 2 cents: we could set MaxTarget to 650 Gib and keep default threshold and safety buffers so that we can safely hit 500 GiB but then we will start moving GC at that point.

**Comment by TippyFlitsUK** [comment]
> My own random 2 cents: we could set MaxTarget to 650 Gib and keep default threshold and safety buffers so that we can safely hit 500 GiB but then we will start moving GC at that point.

That sounds even better Zen!!

**Comment by Stebalien** [comment]
It would also be really wonderful to take the actual disk space into account. For example, with my 1TiB drive, the default config seems to be useless. I run out of space to actually perform the moving GC before it can happen.

Instead, I'd rather have badger detect that I'm approaching "half full" and force an early GC.
