### ISSUE TITLE
Brave wallet expects reward in the eth_feeHistory not to be negative

### ISSUE THREAD

**Issue by ychiaoli18** [filecoin-project/lotus#10604]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Currently, in eth_feeHistory,`EffectiveGasPremium` returns a negative value if GasFeeCap < baseFee. However, brave wallet [expects a non-negative value](https://github.com/brave/brave-core/blob/087c36226d791f1610cac7edd3e787d206446025/components/brave_wallet/browser/eth_gas_utils.cc#L96) for reward in this API endpoint. We may have to do further research to understand if this is the desired behavior. 

### Describe the solution you'd like

We may want to return zero if GasFeeCap < baseFee.

**Comment by yrliou** [comment]
FYI we were referencing https://ethereum.github.io/execution-apis/api-documentation/ which the specified reg pattern does not include negative values. 
<img width="1219" alt="Screen Shot 2023-03-31 at 1 57 41 PM" src="https://user-images.githubusercontent.com/4730197/229228763-526c3203-fcec-4ad1-ac1a-d963bf233fe7.png">

**Comment by raulk** [comment]
Looks like we might not be properly calculating the effective gas premium.
