### ISSUE TITLE
Lotus to support eth_syncing RPC method

### ISSUE THREAD

**Issue by honghaoq** [filecoin-project/lotus#10622]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Filecoin nodes don’t support the eth_syncing RPC [method](https://www.quicknode.com/docs/ethereum/eth_syncing). Some of the bridge validators were using that in their monitoring tools. It would be nice to have that supported.

### Describe the solution you'd like

Lotus to support eth_syncing RPC method

**Comment by honghaoq** [comment]
@maciejwitowski FYI, can we get this into FVM eng planning?

**Comment by maciejwitowski** [comment]
>  It would be nice to have that supported.

@honghaoq is it nice-to-have for them or a blocker? Also, any deadlines from their side?

**Comment by honghaoq** [comment]
Nice to have, not blocking and no deadline from their side - they are still planning to landing on mainnet this week.
