### ISSUE TITLE
Investigate using the message index in the ChainStore

### ISSUE THREAD

**Issue by fridrik01** [filecoin-project/lotus#10663]
See Epic: Message Index https://github.com/filecoin-project/lotus/issues/10536 for background

In PR https://github.com/filecoin-project/lotus/pull/10452 we introduced a Message Index to Lotus which is backed by a sqlite backend and allows us to speed up certain calls like `StateSearchMessage`. 

We may be able to use this index in the ChainStore, but it's unclear. We should investigate (see https://github.com/filecoin-project/lotus/pull/10452#issuecomment-1467322283 for context).

**Comment by maciejwitowski** [comment]
Lowering the priority based on info from @fridrik01 

> It turns out that that task was more an "investigation" rather than actually refactor since it was not clear how much that change will improve performance

**Comment by Stebalien** [comment]
Benchmarking determined that this isn't required.
