### ISSUE TITLE
Chain `ExportRangeInternal` returns an EOF error when exporting stateroots

### ISSUE THREAD

**Issue by ognots** [filecoin-project/lotus#10672]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.21.0-dev+mainnet+git.3f74840b6+api1.5.0
Local: lotus version 1.21.0-dev+mainnet+git.3f74840b6
```

### Repro Steps

```lotus chain export-range --head @2770000 --tail @2768000  --messages=true --receipts=true --stateroots=true```

### Describe the Bug

When attempting to call [ExportRangeInternal](https://github.com/filecoin-project/lotus/blob/master/node/impl/full/chain.go#L588-L634) with messages, receipts and stateroots, an ambiguous `EOF` is returned.
1. I would expect the error message to be helpful
2. I would expect the snapshot to complete on a lotus node containing chain data for the tipset range

The error appears to be in the walker, judging from log output.

This error does not occur if one sets `--stateroots=false`

### Logging Information

```text
{"level":"error","ts":"2023-04-14T13:11:35.729-0400","logger":"chainstore","caller":"store/snapshot.go:343","msg":"export workers finished with error","error":"EOF"}
Apr 14 13:11:35 stongops-worker-2 lotus[2335532]: {"level":"error","ts":"2023-04-14T13:11:35.817-0400","logger":"chainstore","caller":"store/snapshot.go:582","msg":"walker scheduler","error":"EOF"}
Apr 14 13:11:35 stongops-worker-2 lotus[2335532]: {"level":"warn","ts":"2023-04-14T13:11:35.817-0400","logger":"rpc","caller":"go-jsonrpc@v0.2.3/handler.go:406","msg":"error in RPC call to 'Filecoin.ChainExportRangeInternal': exporting chain range: EOF"}
```

**Comment by hsanjuan** [comment]
I have a patch for this that will be submitting soon. There's a fix here too https://github.com/hsanjuan/lotus/tree/filcryo-v1.20.0-branch (the final fix will probably be to skip raw-codec cids since they're not supposed to have links anyways.
