### ISSUE TITLE
FEVM: Event observers: Use correct confidence 

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#10706]
The event observers used by the EthAPI and Eth Events systems are created with a "confidence" of 1. I'm not sure how this was chosen, but this means in practice that any reorg is treated as a failure, since it is a "revert past finality" (see [here](https://github.com/filecoin-project/lotus/blob/e65fae28de2a44947dd24af8c7dafcade29af1a4/chain/events/observer.go#L214)).

This is gonna make whatever's listening to these events fairly buggy. We should _definitely_ set a larger value, and _probably_ just use the default, but that depends on how correctly these listeners handle revert events.

**Comment by maciejwitowski** [comment]
@Stebalien Do you think it makes sense to address this while working on https://github.com/filecoin-project/ref-fvm/issues/1350 since AFAIK both are related to events during reorgs?

**Comment by Stebalien** [comment]
Well, "confidence" isn't "finality". I'm not sure why we're logging an error here.

The eth APIs really do expect no confidence and apps are expected to handle chain reorgs. Now, given that Filecoin is rather forky, maybe we want to wait a bit? On the other hand, that will likely cause other issues (events will lag behind the chain head as reported by the eth API).

**Comment by Stebalien** [comment]
Wait, no. Sorry, I didn't realize what "gc confidence" here was. This is definitely a bug.
