### ISSUE TITLE
LOTUS_FVM_CONCURRENCY=48 causes chain sync panic on migration

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#10710]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.23.0-rc1
```

### Repro Steps

1. Run lotus daemon with `LOTUS_FVM_CONCURRENCY=48` (the max as per the docs)
2. See chain won't sync after nv19

### Describe the Bug

Setting it to `LOTUS_FVM_CONCURRENCY=24` fixed the issue.

### Potential fix
Maybe cap the value set in the config, if it causes sync issues like these. Or at least show a warning / make the daemon refuse to start.

**Comment by rjan90** [comment]
Added a PR for the lotus-docs as well: https://github.com/filecoin-project/lotus-docs/pull/560. Although this value (24) seems to be low enough most system, the actual right value depends on the architecture.

The longer term fix would be to consider both the system and whether or not we're going over an upgrade

**Comment by Stebalien** [comment]
This should be fixed now (for all versions of the FVM) as we now over-subscribe instead of allocating all instances up-front.
