### ISSUE TITLE
Regression: 1.22.0 cannot be built with Go 1.20

### ISSUE THREAD

**Issue by yorickdowne** [filecoin-project/lotus#10731]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.22.0
```

### Repro Steps

Build Lotus from source with Go 1.20

### Describe the Bug

Build fails, but succeeds with Go 1.19

Building 1.21.0-rcN with Go 1.20 worked. This looks like a regression

### Logging Information

```text
#0 50.26 # github.com/lucas-clemente/quic-go/internal/qtls
#0 50.26 /go/pkg/mod/github.com/lucas-clemente/quic-go@v0.29.1/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
#0 73.85 make: *** [Makefile:89: lotus] Error 1
```
```

**Comment by RobQuistNL** [comment]
This is expected. For 1.22.0: 
> Note that you must be on a go version higher than Go 1.18.8, but lower than Go v1.20.0. We would recommend Go 1.19.7.

For 1.23.0 and 1.21.x you can use Go 1.20
