### ISSUE TITLE
failed to write and preprocess bytes

### ISSUE THREAD

**Issue by ocean00** [filecoin-project/lotus#1073]
**Describe the bug**
storage/garbage.go:117 failed to write and preprocess bytes

**To Reproduce**
1. Run 'lotus-storage-miner run'
2. See error:
2020-01-14T18:49:48.919+0800    ERROR   storageminer    storage/garbage.go:117 failed to write and preprocess bytes

Caused by:
    No space left on device (os error 28)
github.com/filecoin-project/filecoin-ffi.GeneratePieceCommitmentFromFile
        /home/work/lotus/extern/filecoin-ffi/proofs.go:333
github.com/filecoin-project/go-sectorbuilder.GeneratePieceCommitment
        /home/work/golang/pkg/mod/github.com/filecoin-project/go-sectorbuilder@v0.0.2-0.20200114015900-4103afa82689/simple.go:67
github.com/filecoin-project/lotus/storage.(*Miner).pledgeSector
        /home/work/lotus/storage/garbage.go:25
github.com/filecoin-project/lotus/storage.(*Miner).PledgeSector.func1
        /home/work/lotus/storage/garbage.go:115
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*Miner).PledgeSector.func1
        /home/work/lotus/storage/garbage.go:117

**Expected behavior**
work@master:~$ df -Th
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs   63G     0   63G   0% /dev
tmpfs          tmpfs      13G  1.9M   13G   1% /run
/dev/sdc2      ext4      110G   75G   29G  73% /
tmpfs          tmpfs      63G     0   63G   0% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs      63G     0   63G   0% /sys/fs/cgroup
/dev/sdc1      vfat      511M  7.8M  504M   2% /boot/efi
/dev/loop0     squashfs   55M   55M     0 100% /snap/lxd/12317
/dev/loop1     squashfs   90M   90M     0 100% /snap/core/8213
/dev/loop2     squashfs   90M   90M     0 100% /snap/core/8268
/dev/loop3     squashfs   55M   55M     0 100% /snap/lxd/12631
/dev/sdb1      xfs       7.3T  7.5G  7.3T   1% /storage

**Screenshots**

**Version (run `lotus --version`):**
work@master:~$ lotus version
0.2.0+git3b34eba6+api0.1.6
lotus version 0.2.0+git3b34eba6

**Additional context**
there is so much space, it should be a bug

**Comment by whyrusleeping** [comment]
I think this is the proofs issue where it uses `TMPDIR` to stage some data. Try setting `TMPDIR` to point to a directory on a disk that has lots of space and try again.

**Comment by ocean00** [comment]
@whyrusleeping Thank you, Space has been added to the tmp directory.
