### ISSUE TITLE
Inability / difficulty to sync calibnet from scratch

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#10768]
Users have reported (and I personally have experienced) that it's really hard to sync calibnet from genesis, because getting the early blocks of the network (especially the first 500 or so) nearly always fails. In my experience you can get it to work with multiple attempts, but something is awry.

We need to investigate this by trying to reproduce, and seeing who we attempt to fetch these blocks from and why they fail. Sanity checking that we have the correct bootstrappers packaged is good too.

**Comment by arajasek** [comment]
@eshon Do we have confirmation here?

**Comment by eshon** [comment]
@arajasek Zondax have not had time to check this, so for now it's not clear.

**Comment by arajasek** [comment]
@eshon I've successfully done so, no problem. I'd have liked to get confirmation from the original reporters (just in case the issue is local to them for some reason), but we don't need to.

I'm gonna close for now, please reopen if still a problem.
