### ISSUE TITLE
lotus v1.23.0 compile error

### ISSUE THREAD

**Issue by lbj2004032** [filecoin-project/lotus#10773]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
v1.23.0
```

### Repro Steps

cd lotus
git checkout v1.23.0
export RUSTFLAGS="-C target-cpu=native -g"
export FFI_BUILD_FROM_SOURCE=1
FFI_USE_CUDA=1 make clean all

### Describe the Bug

verifying github.com/ipni/storetheindex@v0.5.10: checksum mismatch
        downloaded: h1:34cPsNGSKJJJRBF5eQJOuAuKkpRh6YhHxnMKKhxIacE=
        go.sum:     h1:r97jIZsXPuwQvePJQuStu2a/kn+Zn8X4MAdA0rU2Pu4=

### Logging Information

```text
go: downloading github.com/libp2p/go-buffer-pool v0.1.0
go: downloading github.com/stretchr/testify v1.8.1
go: downloading github.com/drand/drand v1.4.9
go: downloading github.com/drand/kyber v1.1.15
go: downloading github.com/mattn/go-sqlite3 v1.14.16
go: downloading github.com/Gurpartap/async v0.0.0-20180927173644-4f7f499dd9ee
go: downloading github.com/ipni/storetheindex v0.5.10
go: downloading github.com/hashicorp/go-hclog v1.3.0
go: downloading github.com/hashicorp/raft v1.3.10
go: downloading github.com/hashicorp/raft-boltdb v0.0.0-20171010151810-6e5ba93211ea
verifying github.com/ipni/storetheindex@v0.5.10: checksum mismatch
        downloaded: h1:34cPsNGSKJJJRBF5eQJOuAuKkpRh6YhHxnMKKhxIacE=
        go.sum:     h1:r97jIZsXPuwQvePJQuStu2a/kn+Zn8X4MAdA0rU2Pu4=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
make: *** [Makefile:89: lotus] Error 1
```

**Comment by rjan90** [comment]
hey @lbj2004032!

Can you run:

```
export RUSTFLAGS="-C target-cpu=native -g"
export FFI_BUILD_FROM_SOURCE=1
export FFI_USE_CUDA=1 
cd lotus
git pull
git checkout v1.23.0
git submodule update
make clean
make all
```
And still see if you get the error, it looks like you do not have the correct submodule

**Comment by weizihua** [comment]
It is recommended to change your proxy, or use a smooth network.

**Comment by yushui468** [comment]
Hello, have you solved this problem?

**Comment by lbj2004032** [comment]
> Hello, have you solved this problem?

Not resolved, but can be compiled through another machine

**Comment by LesnyRumcajs** [comment]
@rjan90 I have the same issue; the steps you mentioned did **not** help. I am using `v1.23.2`. This problem occurs on both my desktop and a VPS in Digital Ocean. Both are running Linux Fedora (36 and 38).


> It is recommended to change your proxy, or use a smooth network.
@weizihua, could you please elaborate? Why would networking cause different checksums (but the difference is precisely the same) in two geographically different machines?

The workaround I have at the moment is to modify `go.sum` for this specific dependency but it doesn't seem correct.

Given that this issue was spotted on several machines, two of mine and one of @lbj2004032, I propose to re-open this issue. I'm happy to provide more information regarding my setup.

**Comment by LesnyRumcajs** [comment]
Or maybe it's not worth digging into it, given that `storetheindex` dependency is already removed in `master`.
