### ISSUE TITLE
Continious log spam about indexer in daemon

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#10789]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [X] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [X] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.23.0
```

### Repro Steps

1. Run lotus daemon
2. See a lot of the following logs

### Describe the Bug

{"level":"warn","ts":"2023-04-29T07:43:14.154Z","logger":"sub","caller":"sub/incoming.go:588","msg":"ignoring indexer message","sender":"12D3KooWSqR5FMNJg7zJUBf56qeY6azkUqDpvsxYWp6F81EcziEm","err":"rate limit exceeded"}

### Logging Information

```text
-
```

**Comment by Reiers** [comment]
Thanks for the flag. 💯 
The issue stems from Boost, please update to the latest stable release.
https://github.com/filecoin-project/boost/releases/tag/v1.7.2
