### ISSUE TITLE
chaiwatch run err:

### ISSUE THREAD

**Issue by johnli-helloworld** [filecoin-project/lotus#1081]
**Describe the bug**
chainwatch run error;

**To Reproduce**
1. lotus daemon > normal boot
2. chainwatch run > error

**Expected behavior**
chainwatch run normal boot

**Screenshots**
Normal boot
![image](https://user-images.githubusercontent.com/26270251/72361530-9bc9be00-372c-11ea-81ff-3e0c4aa15e98.png)

**Version (run `lotus --version`):**
v 0.2.0

**Additional context**
main.go:49  dial tcp [ : : 1 ] : 5432: connect: connection refused

**Comment by whyrusleeping** [comment]
where does port 5432 come from here? I havent seen that used

**Comment by johnli-helloworld** [comment]
after installing the postsql database, I successfully started it, which is the port of the postsql database. But a new error occurred while I was generating the blockchain diagram
![image](https://user-images.githubusercontent.com/26270251/72415884-6f578580-37b0-11ea-80de-7088960bd768.png)

**Comment by johnli-helloworld** [comment]
> where does port 5432 come from here? I havent seen that used
after installing the postsql database, I successfully started it, which is the port of the postsql database. 
chainwatch no longer uses the sqlite database

**Comment by johnli-helloworld** [comment]
I executed a chainwatch dot once and then I can't do it again, hint too many clients already

**Comment by johnli-helloworld** [comment]
![image](https://user-images.githubusercontent.com/26270251/72416275-42f03900-37b1-11ea-99b2-59c548ea0270.png)
