### ISSUE TITLE
lotus-miner storage redeclare --all requires an argument

### ISSUE THREAD

**Issue by piknikSteven2021** [filecoin-project/lotus#10859]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
~$ lotus-miner version
Daemon:  1.23.0+mainnet+git.d1d4b35ad+api1.5.0
Local: lotus-miner version 1.23.0+mainnet+git.d1d4b35ad
```

### Repro Steps

1. Run `lotus-miner storage redeclare --all`
2. See error `ERROR: incorrect number of arguments, got 0`

### Describe the Bug

It appears to me that even though it has the `--all` flag on, it still requires an argument. Adding a simple input allowed the command to go through without issue, such as `lotus-miner storage redeclare --all 1` even though it's not a path/ID.

It appears to me that https://github.com/filecoin-project/lotus/blob/a0ebd8bb169ef6df2b9268e5acb325e8e00c886e/cmd/lotus-miner/storage.go#L238 is forcing there to always be an argument. I would think the proper structure would be:

```
if all
  foo
elif cctx.NArg() = 1
  foo do something with the ID
else 
  "incorrect arguments"
fi
```

### Logging Information

```
~$ lotus-miner storage redeclare --all --drop-missing
ERROR: incorrect number of arguments, got 0

NAME:
   lotus-miner storage redeclare - redeclare sectors in a local storage path

USAGE:
   lotus-miner storage redeclare [command options] [path]

OPTIONS:
   --all           redeclare all storage paths (default: false)
   --drop-missing  Drop index entries with missing files (default: false)
   --id value      storage path ID
```

**Comment by rjan90** [comment]
Thanks for the report! It does look like the args check is a bit to aggressive here. I will start working on a fix
