### ISSUE TITLE
Force users to set the lotus-miner legacy markets config to false

### ISSUE THREAD

**Issue by shrenujbansal** [filecoin-project/lotus#10862]
Lotus-markets are being disabled in favor of boost
The default config has already been changed to disable lotus-markets. However, SPs can accidentally/intentionally keep their old config and keep running with lotus-markets code
This code is going away soon, so provide a loud notification to users to disable this

**Comment by rjan90** [comment]
Similar to what happened with the SplitStore config, we should force users to explicitly set this in the next feature release after a network upgrade (PR for reference: https://github.com/filecoin-project/lotus/pull/10488 ).

**Comment by rjan90** [comment]
Added an alert as a start here: https://github.com/filecoin-project/lotus/pull/10868

**Comment by rjan90** [comment]
Closing this ticket, since the legacy markets with be completely removed in: https://github.com/filecoin-project/lotus/pull/12005
