### ISSUE TITLE
memory consumption profiling

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#10889]
originated by @arajasek 

### goal

Build tool to better understand of Lotus's memory footprint

### potential impact
- savings by dropping unnecessary caches etc.
- customizations for users that want to run with less memory usage

### questions to answer
 - [ ] We "know" Lotus takes 32 GiB of RAM but Why? What's taking this memory?
 - [ ] We have a lot of caches -- are they worth it?

**Comment by arajasek** [comment]
Add stats to our caches (size, hitrate)

**Comment by jennijuju** [comment]
grouped into #10890
