### ISSUE TITLE
getBlock return an Error

### ISSUE THREAD

**Issue by amncjf** [filecoin-project/lotus#10909]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
All versions
```

### Repro Steps

1. curl --data '{"jsonrpc": "2.0", "id":1, "method": "eth_getBlockByNumber", "params": ["0x47C87",true] }' -H 'Content-Type:application/json' https://api.node.glif.io/rpc/v1

### Describe the Bug

I in https://api.hyperspace.node.glif.io/rpc/v1 call getBlock (294023) interface, return an Error: Error: requested epoch was a null round, Recommended return:
{
...prevBlock,
parentHash: prevBlock.hash,
blockNumber: prevBlock.blockNumber+1,
}

### Logging Information

```text
N/A
```

**Comment by amncjf** [comment]
There will be no such errors in Ethereum. Most software and libraries are developed according to this setting, such as ethers, web3js, graph_node..., and they are also used to this setting when calling ethereum rpc. 
If you follow the current practice of filecoin, these The software needs to be modified. Returning an exception just obviously gives us the information that filecoin is empty. Most of the time we don’t need this information. 
If we return 
{
...prevBlock,
parentHash: prevBlock.hash,
blockNumber: prevBlock. blockNumber+1,
} 
We can also judge whether a block is a filecoin empty block (hash == parentHash)

**Comment by aarshkshah1992** [comment]
@virajbhartiya 

Want to take this one ? 
Note that this API now supports returning "null" responses if no such block exists and so we should change the signature of the RPC methods accordingly and simply return a "null" value if the requested epoch is a null round.

See https://docs.infura.io/api/networks/ethereum/json-rpc-methods/eth_getblockbynumber and the implementation in `go-ethereum`.

**Comment by virajbhartiya** [comment]
@aarshkshah1992 Yes I would like to work on this!
