### ISSUE TITLE
log's topics is null

### ISSUE THREAD

**Issue by amncjf** [filecoin-project/lotus#10910]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
All versions
```

### Repro Steps

1. curl --data '{"jsonrpc": "2.0", "id":1, "method": "eth_getBlockByHash", "params": ["0x53b5686d0309e3617e02c8e3f2fe8a5facc14672d746afd948a2db8eb29f292b",true] }' -H 'Content-Type:application/json' https://api.calibration.node.glif.io/rpc/v1

### Describe the Bug

https://api.calibration.node.glif.io/rpc/v1 has obtained the receipt of transaction 0x53b5686d0309e3617e02c8e3f2fe8a5facc14672d746afd948a2db8eb29f292b, where the logIndex is 7 and the topics of the log are null. Why? topics are always not null

### Logging Information

```text
N/A
```

**Comment by maciejwitowski** [comment]
Looks like this has already been [discussed on Slack](https://filecoinproject.slack.com/archives/C029MT4PQB1/p1683626031364719). 
This can happen if the contact uses `LOG0`.

**Comment by amncjf** [comment]
It is recommended to set the topics of log0 to [] instead of null, so that I can use getLogs of ethers instead of writing it myself

**Comment by maciejwitowski** [comment]
Not sure why it results in `null` but I agree [] would make more sense.

**Comment by amncjf** [comment]
There is also better compatibility!
