### ISSUE TITLE
Lotus Assigns `SnapDealsWaitDeals` Status to Sectors with +90 Days Duration Causing Snap Failure

### ISSUE THREAD

**Issue by TippyFlitsUK** [filecoin-project/lotus#10914]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.23.1-rc2+mainnet+git.5a1738c9b+api1.5.0
Local: lotus-miner version 1.23.1-rc2+mainnet+git.5a1738c9b
```

### Repro Steps

1. Snap deal is assigned to `Available` CC sector
2. Sector has a duration in excess of 90 days of the deal term
3. Sector progresses to `SnapDea;lsWaitDeals`
4. Snap fails with `term end beyond sector expiration`

### Describe the Bug

Following the activation of FIP-0045, an `Available` CC snap sector must have a duration that is not in excess of 90 days of the underlying deal term.

**Lotus is currently allowing deals to be assigned to sectors with a duration in excess of 90 days of the underlying deal term.**

The aforementioned CC sector is then progressing to a `SnapDealsWaitDeals` status only to fail snapping with the following message:

```
2023-05-22T07:07:25.905-0400	DEBUG	sectors	pipeline/sealing.go:179	deal not assignable to sector	{"sector": "185", "deal": 37635978, "dealEnd": "4036481", "dealStart": "2884481", "dealClaimEnd": "4295681", "lastAssignedDealEnd": "0", "update": true, "sectorExpiration": "4436749", "reason": "term end beyond sector expiration"}
```

Lotus should check the Available CC snap sector duration before assigning the deal and select a more suitable sector if the first sector's duration is in excess of 90 days of the proposed deal term. If no suitable sectors are available, the deal should either be assigned to a newly created deal sector (depending on user config settings) or remain in a pending assignment state.

This issue has been classified as P1. SPs are already seeing snap failures as a result of this and the number of reported failures is likely to grow quickly!

Slack conversation: https://filecoinproject.slack.com/archives/C04DW2KPR97/p1684752175351219
CC. @nonsense, @LexLuthr 

### Logging Information

```text
2023-05-22T07:07:25.905-0400	DEBUG	sectors	pipeline/sealing.go:179	deal not assignable to sector	{"sector": "185", "deal": 37635978, "dealEnd": "4036481", "dealStart": "2884481", "dealClaimEnd": "4295681", "lastAssignedDealEnd": "0", "update": true, "sectorExpiration": "4436749", "reason": "term end beyond sector expiration"}
```

**Comment by magik6k** [comment]
https://github.com/filecoin-project/lotus/pull/10915 adds a whole bunch of improved logging, it would be great to try reproduce this issue with that PR, and get logs grepped for `input.go`

(That PR also cleans up the upgrade sector selection logic a bit, and removes the TargetExpiration knob, but I really doubt it was the cause of this issue)

**Comment by LexLuthr** [comment]
Sure. Let me find a gap in sealing pipeline to rebuild and restart. It might take me some time to test this.
