### ISSUE TITLE
fail to update proving set correctly after declare faults, maybe an amt deletion bug?

### ISSUE THREAD

**Issue by dtynn** [filecoin-project/lotus#1094]
**Describe the bug**
fail to update proving set correctly after fpost/epost with declared faults
https://github.com/filecoin-project/lotus/blob/master/chain/actors/actor_miner.go#L622-L641

**To Reproduce**
we tried to replay the deletion with the demo:
https://gist.github.com/dtynn/94bc060260515146db332fa2f5622184

**Expected behavior**
update proving set & sectors correctly

**Version (run `lotus --version`):**
0.2.2

**Comment by dtynn** [comment]
fixed in #1098

**Comment by whyrusleeping** [comment]
Thanks @dtynn !
