### ISSUE TITLE
maybe need to check the minus operation is safe or not

### ISSUE THREAD

**Issue by ldoublewood** [filecoin-project/lotus#1095]
in actor_miner.go, maybe the minus operation should be carefully checked in the following line:  
newPower := types.BigMul(types.NewInt(pss.Count-uint64(len(faults))), types.NewInt(mi.SectorSize))
is

**Comment by Kubuxu** [comment]
There is no such line in current build.

**Comment by ldoublewood** [comment]
in new version, it is now:
newPower := types.BigMul(types.NewInt(pss.Count-activeFaults), types.NewInt(mi.SectorSize))

**Comment by Kubuxu** [comment]
The core bug is somewhere else (pss.Count in this case is max uint64). The `activeFaults` is not an issue.

**Comment by ldoublewood** [comment]
OK, you can close the issue
