### ISSUE TITLE
[Lotus daemon] Allow validating a tipset at a certain height for debugging purposes.

### ISSUE THREAD

**Issue by ruseinov** [filecoin-project/lotus#10980]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

I'm working on [forest](https://github.com/ChainSafe/forest) project, that is a Rust implementation of a Filecoin client. Oftentimes I need to debug state root mismatches. In order to do that one needs to be able to debug tipset validation at a certain height. 

### Describe the solution you'd like

I'd like to be able to tell the daemon to validate a tipset at a certain height. That would be very useful for debugging. 

Something along these lines should work well: `lotus daemon --import-snapshot <snap> --height 12345`

### Describe alternatives you've considered

Can't really see any viable alternatives at the moment.

### Additional context

This has already been implemented in Forest, an example command would look like:
`forest --no-gc --chain calibnet --encrypt-keystore false --import-snapshot https://forest-snapshots.fra1.cdn.digitaloceanspaces.com/debug/filecoin_snapshot_calibnet_2023-06-13_height_643680.car.zst --height=643585`

**Comment by ZenGround0** [comment]
Even better question: does `./lotus state compute-state` solve your problem?

**Comment by ruseinov** [comment]
> Some questions for you @ruseinov: Can you confirm you know that `lotus daemon --import-snapshot` already exists? Can you further explain what you are trying to achieve that existing import-snapshot flag does not do? Snapshot files include headers which include height information already so what is the point of --height flag in forest's snapshot import command?

The idea here is to be able to `Apply` a block at selected height in order to get debug information. Currently it's a bit tricky, as one needs to `--import-snapshot` and then use a debugger/breakpoints to reach a certain block, which getting tedious if you need to do this multiple times. 



> Even better question: does `./lotus state compute-state` solve your problem?

That might be exactly what we are looking for, am I correct to assume that this would feed a block at a given height to the VM and have exactly the same output that a normal block `Apply` would do when running the daemon? 
If that's correct - that would make this issue irrelevant. Let me check this and get back to you.

**Comment by ruseinov** [comment]
Now that I think about it - the only downside of this approach is that it actually requires a running daemon. In an ideal world we'd be able to execute a block as a one-liner as opposed to having to deal with several moving pieces. Then it would be easier to use and automate.
