### ISSUE TITLE
Lotus Network Check tooling

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#10981]
## User Story
The Lotus team wants to be able to manage and run important network nodes on our own hardware over a long time period. The Lotus team needs to run lotus over a long period of time to ensure the software is functioning well and the Lotus team is not dependent on external parties to identify many issues that will only be identified with long running nodes. Running the state invariant checker periodically will ensure that the specific error related to ghost deals will be identified by the Lotus team as soon as they occur. This will also provide the infrastructure on top of which the Lotus team may add future checks and validations.

## Acceptance Criteria

- [x] a long living lotus node for Lotus team.
- [x] Periodically run the state invariants checker and produce a slack ping with details if there is an error #11023 
- [x] Confirmation that `lotus-shed check-invariants` is the correct command for the state invariant checker

## Technical Breakdowns

```[tasklist]
### Development
- [x] create a command and a cron file that weekly at noon EST runs the state invariant check and pings slack with any errors - command will need to 1. shut down lotus node 2. run checker 3. report to slack if any errors occur 4. start the node
- [x] Create a run book that contains everything needed to set up the node and install the cron
```

```[tasklist]
### Node Setup
- [x] provision ec2 instance for running lotus
```

```[tasklist]
### Deployment
- [x] on ec2 instance set up lotus to be synced to mainnet using splitstore
```

```[tasklist]
### Research
- [x] confirm command `lotus-shed check-invariants` is valid for state invariant check - if not valid find correct command
```

**Comment by snissn** [comment]
I need more information on the details behind
1. state invariants checker
2. slasher
Do they each have documentation that you could link me to?

**Comment by jennijuju** [comment]
chatting with @snissn - we will close this as the documentation on how to spin up a new node setup he has built. basically we have setup thee right infrastructure to spin up a long living node easily, however, there is not a strong user case for us to maintain that right now. (the state invariant checker and state viewer both can be run more effectively against a short lived node started by a snapshot).

Whoever has a use case for a long living node, can use the infra Mikers setup and get it running

**Comment by jennijuju** [comment]
closing as the remaining [] is tracked by #11023

**Comment by snissn** [comment]
done! Project lives here: https://github.com/FILCAT/lotus-ec2-tools and pings slack with updates
