### ISSUE TITLE
Design Proposal: Towards a generic blockchain library

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#10982]
## User Story

We envision a future in which it needs to be easy to build and deploy new, and potentially very different, content-addressed blockchain protocols. These protocols will be arranged in some form of Hierarchical Consensus, such as [IPC](https://ipc.space/).

In order to achieve this, we will need a codebase on which these protocols can be built. This codebase needs to supply the core logic that all blockchain implementations will need, while being generic enough that components can be replaced by applications built on top of it as necessary.

This issue captures very preliminary design work for this codebase could look like, and what portions of the existing Lotus stack could be used to create it. 

## Deliverables

- An architecture diagram of what the components of this generic codebase would be, and how they interact with each other
- A comparative table of the implementation of modules for the different options
  - Go (Lotus)
  - Rust (Fendermint / Forest).
- Pros and cons of each of the approaches
  - How much is already well-written vs. how much would have to be built from scratch
  - Maintenance overhead (cross-team dependencies)
  - Skills of the team(s)
  - FFI / Generics / compatibility with FVM and builtin actors / language features
  - Tooling compatibility.
  - Community and ecosystem
  - How does it compare to other projects in space?
- What open questions do we still have that might change that answer?
- What are next steps we suggest we take?

## Acceptance Criteria

Reviewers of the design should:
- Be able to easily determine for each component:
  - what the component's responsibilities are (and, potentially, are NOT)
  - what core logic we expect to live directly in this codebase without much flexibility
  - what logic will be partially implemented in the codebase, with additional logic to be supplied by developers
  - what logic will be left unimplemented in the codebase, except perhaps for mocks
- Have an understanding of of how much work can be directly lifted from the Lotus stack
- Have an understanding of how much work would be lifted, but need refactoring from Lotus

## Technical Breakdown

- Produce the initial design based on our experience building blockchain implementations. 
- Survey other blockchain implementations (Geth), and other projects that have tried to solve this problem (Tendermint, OpStack)
- Modify our design with any improvements we can draw from
- With the "final" structure ready, assess which pieces are easy to lift from Lotus, and which are not

**Comment by scotthconner** [comment]
This is a really good breakdown. Another one we want to look at is [Sovereign SDK](https://github.com/Sovereign-Labs/sovereign-sdk). While it is essentially new, it's another good data point for how modular blockchains are abstracted and componentized. It might be worth leveraging this abstraction work either indirectly or directly. 

I see common themes across some of them: DA modules, execution modules (state transition function), proof/signature modules. Our problem space will likely map to these as well given our overlapping goals. 

For the "artifact" deliverable itself:
* A high level analysis of the research into other modular stacks
* Some summary of trade-offs made and considerations for how these insights are built into our overall design.

**Comment by scotthconner** [comment]
For the technical breakdown,  I suggest a re-ordering:
1) Analysis of Other Modular Blockchain Stacks (OPStack, Sovereign SDK, Tendermint, geth?)
2) Design for IPLD-based modular development platform with insights from #1.
3) Review and iterate.

There are a few eco-system things we want to consider in our recommendation:

1) Tooling: How much tooling would we get for free? This was a strong driver of FEVM. If developers can roughly take an OPStack-like development cycle, would it be worth, say, building modules inside of the OP Stack abstractions and packaging a "distro".
2) Infrastructure: For things like running nodes, RPC end-points, or even exchanges - how much of their operations and assumptions would need to change against what they are used to? The considerations might be different between providers - for instance, if an Exchange already supports bridged tokens and roll-up finality (coinbase), or if an RPC provider runs non-Filecoin nodes for similar use cases (for instance, Arbitrum)

**Comment by jennijuju** [comment]
Jsorge and I think one of the acceptance criteria to have is:
- By the end of this practice, purely from a client software perspective, what is the ONE stack recommendation we have for yellowbox, with the data points (the component scorecard).

**Comment by jennijuju** [comment]
> There are a few eco-system things we want to consider in our recommendation:

Id prefer to decouple the ux/tooling/ecosystem/product analysis into a different effort & have this one focus on the client software.

**Comment by jsoares** [comment]
While they can't be entirely decoupled, I'd like to make sure we're prioritising our mandate. A truly modular architecture should enable you to adapt a lot of the tooling (see e.g. current Fendermint, on which we got eth tooling working easily despite that not being a design goal). 

On the other hand, prioritising reuse of existing tooling biases the decision towards what everyone else is using, no matter how poor the fit (case in point: OP Stack). Note that that is a valid goal, but it's not the mission we were given, which is to design a flexible codebase for present and future blockchain networks.

**Comment by jennijuju** [comment]
> A truly modular architecture should enable you to adapt a lot of the tooling (see e.g. current Fendermint, on which we got eth tooling working easily despite that not being a design goal).

@jsoares i totally agree with you. That’s another reason why I think we should focus on module design first - if you have a swap-out-ables/addictive/library-like API/yellow type(address and etc) module, tooling will come around with them.

**Comment by arajasek** [comment]
We produced the architecture diagram described, and shared with folks. Early feedback suggests that we should put much more of the Core Validation & Execution flow on-chain. This reduces the number of "blanks" in the Generic Library, and makes much more of the core protocol replaceable and upgradeable in the Runtime.

**Comment by arajasek** [comment]
We have described a series of features that would enable the highly on-chain Consensus described above. Our immediate next step is to outline a roadmap in which we could build and ship these features, in a manner that supports the goals of the InterPlanetary Consensus project. 

We do not plan to immediately build the Generic Blockchain Library designed in this issue using components from Lotus. Instead, it is likely that the IPC team will build out a client based on Tendermint.

We will likely revisit the architecture produced here later, but this issue can be closed for now.
