### ISSUE TITLE
Introduce nv21 skeleton in Lotus

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#10993]
The Filecoin nv21 upgrade, scope and timeline is being [planned here](https://github.com/filecoin-project/core-devs/discussions/140).

In Lotus we need to add the skeleton for nv21 without any upgrade epochs, code / state changes / migrations. It should have no effect except on local devnets to unblock testing and tests.

```[tasklist]
### Tasks
- [x] Lotus actor version integration checklist: https://github.com/filecoin-project/lotus/blob/3636af4cd926a1f1fc2dadbb235bc01af047c75b/documentation/misc/actors_version_checklist.md#L8
```

Example for nv19:
Lotus: https://github.com/filecoin-project/lotus/pull/10592

**Comment by jennijuju** [comment]
can this be closed now?

**Comment by rjan90** [comment]
Yeah, closed by https://github.com/filecoin-project/lotus/pull/11176
