### ISSUE TITLE
SectorIndex rework for HA

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11025]
**User Story**
Lotus Devs want a consistent, Highly-Available sector index for [SturdyPoSt's HA WindowPoSt](https://docs.google.com/document/d/1lPe-6HdVe_oU0mD29f9Zi4233_xhSbyiXxM_6zXG4hY/edit?pli=1).

**Acceptance Criteria**
Sector Index provides data as it did prior, but is read directly from the database as needed

**Tech Scope**
A package sectorindex which:

1. Satisfies the current sector index interface while storing the content using package lotusdb
2. No-longer keeps the sector index in memory.
3. Updates should be a single transaction.
4. Init at start-up continues to rebuild the sector index as it does today (to solve migration and be a clean-up).
5. Consumers such as proving workers can get values from the database.
6. For sectors already reported by another node, add to the list of nodes that can see that sector. (This handles the case of partitioned environments)
7. Update tools that fix the DB state instead of telling the miner:

- lotus-miner storage declare 
- lotus-worker storage redeclare

**Test Plan**
Ensure existing integration tests pass. 
Ensure workers can respond to today's lotus-miner APIs for sector data.

**Comment by rjan90** [comment]
Closing this issue, as this has been completed by: https://github.com/filecoin-project/lotus/pull/11135
