### ISSUE TITLE
State Summary Lotus Task

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/lotus#11022]
## User Story

I want to know what composes the overall filecoin state overtime; I can go to a website that gives me an easy visualization ([example](https://github.com/filecoin-project/lotus/discussions/11037)) of the historical Filecoin state data breakdown summary, built from historical snapshot regularly.

## Acceptance Criteria
```[tasklist]
### Deliverables
- [ ] Lotus infra tasks include running the Filecoin snapshot state inspection job, on Sunday.
- [x] A website hosts the (historical) visualizations output from the snapshots summary task that viewers can inspect the state breakdowns like below. ![](https://user-images.githubusercontent.com/5515260/250125886-f6aff8a7-c55f-45c4-85dd-b097a8246efa.png)
- [ ] A slack integration that posts a capture of the newly generated weekly visualization output & json breakdown. (we will include this in the sitrep)
```

## Technical Breakdown 
```[tasklist]
- [x] Cron file that runs the task weekly with the latest slide
- [x] A task script for running the snapshot state summary
- [x] Output from state summary is a timestamped json file on the main instance
- [x] A website serving the summary treemap graph off of the output json
- [x] Slack intergrtaion for postting the weekly output.
```

**Comment by jennijuju** [comment]
couple of questions for issue completion & effort estimation
-  @snissn For deliverable 1: will we be resuing the infra setup in https://github.com/filecoin-project/lotus/issues/10981 to run this job too, or will we need to setup a new one?
- Zen and I discussed that it would be nice to have a task running against the summary output, and send an alert if a state increased by X% in a week -  @snissn @arajasek do you think it will be useful too?

**Comment by arajasek** [comment]
> couple of questions for issue completion & effort estimation
> 
> * Zen and I discussed that it would be nice to have a task running against the summary output, and send an alert if a state increased by X% in a week -  @snissn @arajasek do you think it will be useful too?

I'm neutral on this -- it doesn't seem too necessary to me, but I don't see any harm in having a well-calibrated alert. I would say "worth doing if it's less than 1 hour of work"?

**Comment by jennijuju** [comment]
@snissn can we add a quick % of each box size to the python script? (or on the side, a breakdown of size ranked by size %

**Comment by ZenGround0** [comment]
> @snissn can we add a quick % of each box size to the python script? (or on the side, a breakdown of size ranked by size %

Note, I looked into doing this with [the graphing library](https://plotly.com/python/treemaps/) last week and had trouble finding a way to do this.  However now that we have a webpage with multiple images we could always print the size values directly from the json in another image.

**Comment by jennijuju** [comment]
just a nice-to-have: a sidebar menu for easily jumping on to the graph specific to a date (if its quick to do - or people can just ctrl-F the date
