### ISSUE TITLE
Lotus DB package

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11024]
**User Story**
As a storage provider I want to run the new database alongside the current lotus-miner process, and get familiar with the requirements and setup, so that I can leverage it once the SectorIndex is able to run on it.

**Technical acceptence criteria** 
- Both SQLX & PGX interfaces to the configuration-specified DB.
- An IntegrationTest() setup  func where the database name starts with itest_ then .IntegrationTestDropAll() will delete the database (for integration tests). 

**Tech Scope**

An init that will sequentially run a set of upgrade scripts (0.sql 1.sql etc) until the database’s lotus-version table’s only row has a value stepped up to the latest version. A missing table is presumed identical to the need for 0.sql 
The SQL files will be included in the package for simplicity.
When not specified, the database will be lotus.
Config values will be used by a wrapper called UseConfig(), and errors meaningful.
Includes building the mock.

**Test Plan**
An integration test will exercise the feature set of the software and the mock.

A package lotusdb which offers:
Both SQLX & PGX interfaces to the configuration-specified DB.
An init that will sequentially run a set of upgrade scripts (0.sql 1.sql etc) until the database’s lotus-version table’s only row has a value stepped up to the latest version. A missing table is presumed identical to the need for 0.sql 
The SQL files will be included in the package for simplicity.
When not specified, the database will be lotus
An integration test setup where the database name starts with itest_ then .IntegrationTestDropAll() will delete the database (for integration tests). 
Includes building the mock.

**Comment by jennijuju** [comment]
can this issue be closed with #11069 or there is still items left to do? did we test it already?

**Comment by snadrus** [comment]
There's no work left for me. Integration tests are merged.
