### ISSUE TITLE
Build, test, and deploy Consensus Fault Detectors

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#11027]
## Background

The Filecoin protocol specifies three consensus faults that block producers can be penalized for. Any user can monitor for these faults, and report them by invoking the `ReportConsensusFault` method on the appropriate miner actor.

For more on the faults, see [here](https://github.com/filecoin-project/lotus/blob/dbbcf4b2ee9626796e23a096c66e67ff350810e4/chain/vm/fvm.go#L113-L132).

## User Story

I, someone running a Lotus node, want to be able to easily run a Consensus Fault Detector. The Detector must monitor all new blocks my node receives, scanning them for any of the 3 Consensus Fault cases. If it detects any, it should immediately send a message from a specified address, invoking the `ReportConsensusFault` method on the faulty miner.

## Acceptance Criteria

- [ ] The Detector correctly detects any new faults occurring on the network, and reports them on the miner actor
- [ ] Running the Detector does not impact the performance of the Lotus node in any significant way
- [ ] The user can configure the sender address of the `ReportConsensusFault` messages
- [ ] If the sender address doesn't have enough funds to cover the cost of the message, a log is emitted detailing the failure.
- [ ] The Detector is well-documented and easy to use, including media calling attention to it (blog post, YouTube video)
- [ ] Dashboard that monitors ReportConsensusFault activity using the existing sentinel database
- [ ] At least 5 individuals are known to be running the Detector 

## Technical Breakdown 
```[tasklist]
### Development DRI @arajasek
- [x] Implement the Detector itself (#10928)
- [x] land https://github.com/filecoin-project/lotus/pull/10979
- [x] Testing: Run the Detector on mainnet, confirming no sync issues
- [x] Testing: Run the Detector on calibrationnet, and intentionally create a ConsensusFault on it -- confirm the Fault is reported
```

### Deployment Breakdown
```[tasklist]
### DRI @TippyFlitsUK
- [ ] Dashboard that monitors ReportConsensusFault activity using the existing sentinel database
- [x] Produce documentation for how to run the Detector easily
- [ ] Produce 👮 the network context: blog post (disputer, consensus slasher), youtube tutorial, and lotus docs.
- [ ] Reach out to 5 individuals to run the Detector, troubleshoot any issues (collect report wallet address)
```

**Comment by jennijuju** [comment]
@arajasek im wondering if we would want to build a quick alert using the existing sentinel -> slack integration on when the consensus fault reported increases drastically in a short period of time for inspection?

**Comment by jennijuju** [comment]
> Dashboard that monitors ReportConsensusFault activity using the existing sentinel databaseDashboard that monitors ReportConsensusFault activity using the existing sentinel database

built some boards https://protocollabs.grafana.net/d/f7c431c5-e106-4137-9a42-efd3472a309e/jennijuju?orgId=1&from=now-90d&to=now

**Comment by arajasek** [comment]
> @arajasek im wondering if we would want to build a quick alert using the existing sentinel -> slack integration on when the consensus fault reported increases drastically in a short period of time for inspection?

Seems reasonable, but I do think this is a fairly separate work item (cuz it's not about the new Fault Detector we're building), just about a new alert. Happy to track it as part of this, though -- it does sound valuable.
