### ISSUE TITLE
Parallel WindowPoSt

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#11036]
**User story:**

As a Storage Provider (SP) with multiple partitions in a WindowPoSt deadline, I want to be able to process partitions in parallel, so that I can make efficient use of multiple WindowPoSt-workers.

**Acceptance criteria:**

The WindowPoSt loop should be able to process multiple partition in parallel instead of processing only one partition at a time.
Storage Providers should have a configuration option to set the level of parallelism they need.
By default, the parallelism limit configuration should be set to 1.

SPs with more than ~5 partitions / deadline do not have issues with proving deadlines.

**Technical scope:**

- [x] Completed (but outdated) draft PR: https://github.com/filecoin-project/lotus/pull/9615

**Additional technical scope**

- [x] Update / finish the PR
- [x] ~~Schedule testing with a SP that has multiple partitions in a deadline and multiple WindowPoSt-workers, and measure the improvements.~~ Based on feedback from large SPs, better to go with the experimental sticker approach in a release. Ref: https://github.com/filecoin-project/lotus/issues/11036#issuecomment-1669772680
- [x] https://github.com/filecoin-project/lotus-docs/issues/630

**Comment by rjan90** [comment]
> Schedule testing with a SP that has multiple partitions in a deadline and multiple WindowPoSt-workers, and measure the improvements.

Based on feedback from some larger SPs with multiple partitions in a deadline, they do have very strict upgrade processes in place, which makes it hard to get tested on a real-life (32/64GiB) setup while in a branch/tag. So going with the approach of adding an experimental sticker on the config and ship it in a stable release will make it easier to get tested on real setups

**Comment by magik6k** [comment]
Curio can do this now
