### ISSUE TITLE
Confirming and Quantifying AMT churn problems

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/lotus#11035]
## User Story

Because of work on #10884 we believe we understand what is going on with the unexpected filecoin state drop.  The problem looks like the AMT.  Our hypothesis is that its overhead nodes are a large part of its structure and a large portion of them are being rewritten very often with market cron updates.  We need to confirm this hypothesis to make sure there is not some other bug in the market actor or AMT that we are missing.

We have a proposed FIP to improve the market cron [in the longer term](https://github.com/filecoin-project/FIPs/discussions/638#discussion-4887671).  If our hypothesis is confirmed then it will confirm that the proposal will work and further support its utility by demonstrating that it will save 4 G a day on chain store / snapshot size.

## Acceptance criteria

- [x] Confirm that this level of massive write amplification comes from overhead nodes as expected and is and reproducible from rewriting AMT values.
- [x] If hypothesis correct document support for long-term market cron fix in [the existing FIP discussion](https://github.com/filecoin-project/FIPs/discussions/638#discussion-4887671).  If not, reevaluate the long term market cron fix
- [x] If hypothesis correct document this datastructure behavior so that the community can be aware of the problem and make better data structure choices in future protocol changes.  Capture in a new FIP discussion about datastructures and the AMT github repo

## Technical Breakdown

1. Investigate AMT code and confirm that this checks out from the inspection
2. Write a basic tool that does market cron style processing on an AMT of similar size to States AMT, confirm that the expected amount of  data is rewritten.

## Background

With help from #10884 we have learned that the nv19 snapshot size reduction is explained by a massive reduction (~55 GB / 2000 epochs) in the market actor's States AMT.  The market actor's States AMT is < 500 MB. In less than a day of syncing all lotus nodes essentially rewrote the whole AMT's size 100 times.  However the protocol logic in cron processing dictates a rewrite of the AMT data once a day.  Our datastruture choice is ~100x less efficient than it should be.

Today's situation is 10x better (now the market actor's state AMT is ~4GB) because we've slowed market cron processing by 30x.  However it is still noticeably inefficient compared to its actual size - 500MB.  Every 2000 epochs AMT churn generates > 4 GB, which is still ~10x the size of the States AMT and by far the single largest contributor to churn.

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/FIPs/discussions/638#discussioncomment-6440054

**Comment by ZenGround0** [comment]
Trail of outputs
- Profiling code: https://github.com/filecoin-project/lotus/pull/11075
- Documentation on running profiling: https://github.com/filecoin-project/lotus/discussions/11074
- Analysis report: https://gist.github.com/ZenGround0/c3285852f45c1f2631a02c047502f850
- Contribution to market cron fip discussion (also in comment above): https://github.com/filecoin-project/FIPs/discussions/638#discussioncomment-6440054
