### ISSUE TITLE
Filecoin storage capacity modeling - Miner cron analysis 

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/lotus#11034]
## User story

Long term stewards of the filecoin network need to understand how chain bandwidth and block validation times degrade at high storage capacity: [see background and action item here](https://www.notion.so/pl-strflt/Cron-safety-survey-of-the-problem-and-solutions-9d67bf645e8f4478888e9d04ac6a17f8?pvs=4).  This will help the community make informed decisions about 
 -  when we expect bad network conditions to show up and predict what they will look like
 -  how to fix degrading network conditions when they do show up
 -  how to design future changes without making things worse 

## Acceptance criteria 

A simple model of how much storage the filecoin network can handle and how much cron times / gas degrades at different storage levels regarding sectors and partitions.

This model will offer answers to questions like: 
1. How much storage can possibly be onboarded to filecoin?
   - This will help us prioritize FIPs like _[Scalable storage onboarding and maintenance (project Neutron)](https://github.com/filecoin-project/FIPs/discussions/240)_

2. How much miner cron gas/time do we expect to see if the network grows to 25 EiB of RBP?
   - This will help us further clarify the problem statement and prioritize [ FIP: Safe Cron](https://github.com/filecoin-project/FIPs/discussions/493), an initiative lotus team is interested in

```[tasklist]
#### Deliverables
- [ ] For this to be done these models should be recorded somewhere, like [Observable](https://observablehq.com).
- [ ] Provide guidance on whether [FIP: Allow SPs to move partitions between deadlines](https://github.com/filecoin-project/FIPs/discussions/735) is acceptable under current network conditions. (This FIP is being actively considered for network upgrade inclusion soon)
- [ ] FIP discussion proposing protocol change that removes unnecessary cron job processing for big cost savings
```

## Technical breakdown
1. Gather information about existing gas, try to do simple regressions against sector size / partition size to match against gas values for PoRep/ConfirmSectorProofsValid, PoSt, HandleProvingDeadline cron.  Make the model more complicated if needed (existence of deals, other state inefficiencies that matter) 
3.  Apply this information to some basic models of different pieces of filecoin: 
```[tasklist]
- [ ] A simple model of network onboarding limits: divide block gas limit by how much gas is for sector onboarding (PreCommit / ProveCommit (PoRep) in the best case
- [ ] A simple model of miner cron gas: per sector / per partition.  Best case + worst case (based on partition packing)
```

### questions to answer

2. At what network storage capacity is the entire chain bandwidth consumed by SP WindowPoSts? 
   - This will be useful for prioritizing FIPs like[ Gas Lane](https://github.com/filecoin-project/FIPs/discussions/679)
4. How long would the miner cron be if half the network faulted their storage today?
   - Help inform design discussions on future of protocol fees: particularly cost benefit of different [termination fee constructions](https://github.com/filecoin-project/FIPs/discussions/691#discussioncomment-5775777)

### work to get there

- [ ] A simple model of PoSt gas: per sector / per partition
- [ ] A simple model composing all of this together in observable
- [ ] A simple model of worst case faulting / terminating impact on cron gas
- [ ] *A simple model of recover/dispute PoSt gas: per sector / partition

**Comment by ZenGround0** [comment]
TODO under question give me the so what
i.e. we have clarity on XXX FIP, we know when and how to pull trigger on certain work

**Comment by jennijuju** [comment]
todo:
- @ZenGround0 add termination fip discussion link

**Comment by ZenGround0** [comment]
Update 

As I got pulled into a few other things this work is only partially complete.  However we've already found some surprises progress.

## Results

### Tools 
Developed some commands for interpreting gas trace [summarized here](https://gist.github.com/ZenGround0/fe929e2c22cccf77b9514a81ff523c8a)
Introduced this shed tool to help: https://github.com/filecoin-project/lotus/pull/11078

### Analysis 

1. Learned that partition proving is not the dominant cost as originally assumed.  Overhead is significant: ~1/2 of the gas / time costs of all of miner proving deadline cron comes from miners with 0 active partitions in their deadline.  Counting overhead of actors with partitions overhead is > 1/2 of resource usage.
2. The number of cron jobs where no partitions have been assigned is ~1/2.  This indicates that miners use on average 1/2 of their deadlines.  This is more dense than I had previously thought.
3. Terminations do have a significant cost (3x ordinary gas in one instance)

## Current Direction

I'm still pursuing modeling per partition cost of miner cron + average porep onboarding costs.  Two new directions are obvious in light of latest findings.

1. Biggest new insight is that overhead is significant.  I've also noticed some variance: some 0 partition jobs take 2x the time as others.  Next thing Im going to do is model gas "overhead".  Current biggest culprits for gas used are 1) miner vesting 2) precommit deposit burning 3) worker key changes.  Getting a clear picture on this will help me develop some ideas for cutting down this cost entirely.  A new output is a protocol change proposal motivated by understanding of gas costs.
2. In order to give feedback to: https://github.com/filecoin-project/builtin-actors/pull/1326 we need to understand worst case costs and its clear that this involves terminations and faults.  Modeling terminations and faults per sector/partition is required for the output of providing guidance on this protocol change in addition to porep / carrying capacity estimations.

## Updated technical breakdown / work sketch

Miner cron work
1. Automate gathering of a full proving period worth of data
2. Investigate code / gas traces and start to find patterns in 0 partition (pure overhead) case
3. Search out faults and expirations in data to model worse case costs

Carrying capacity work
1. Create similar jq parsing command to measure ProveCommitSector and power cron gas
2. Take data over a large region of the chain

**Comment by ZenGround0** [comment]
For time constraints I ended up stopping at miner cron analysis.  TODO follow up issues on prove commit and post for the backlock.

Results published here: https://github.com/filecoin-project/FIPs/discussions/761
TODO code link
TODO FIP discussion moving partitions link
TODO FIP discussion improving cron cost link

**Comment by jennijuju** [comment]
@ZenGround0 could you please also document the tooling you have built for this and how one can run them?

**Comment by ZenGround0** [comment]
Its in the TODOs above ^^ ive been working on publishing slowly but steadily. I'll be updating the comment as I go.  🤞 its done by tomrrow.
