### ISSUE TITLE
Add a metric to display how many peers have pruned your libp2p peer

### ISSUE THREAD

**Issue by shrenujbansal** [filecoin-project/lotus#11044]
**User Story**

This is a followup from the resolution to #10906 
When debugging issues at the libp2p/gossipsub level, we'd like to have more observability into how the outside world is treating your peer. Specifically, a metric to show how many peers have pruned you from their graft would be helpful

**Deliverables**

By the end of this task, we should have a metric displayed in grafana which shows how many lp2p peers have pruned your peer id per constant time period

Further context available here:
https://github.com/libp2p/specs/issues/555

**Comment by rjan90** [comment]
Closed as done through: https://github.com/filecoin-project/lotus/pull/11058
