### ISSUE TITLE
The lotus cluster cannot be synchronized

### ISSUE THREAD

**Issue by Acumes** [filecoin-project/lotus#11089]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.23.2-dev+calibnet+git.f09d2e05c
lotus-miner version 1.23.2-dev+calibnet+git.f09d2e05c
```

### Repro Steps

https://lotus.filecoin.io/lotus/configure/clusters/
According to the document, three lotus nodes are set up. After the synchronization is completed, configure the cluster operation![image](https://github.com/filecoin-project/lotus/assets/24952678/ac68aedf-22b8-41fe-bc6c-c308fc5202e9)

### Describe the Bug

For more details refer to slack:
https://app.slack.com/client/TEHTVS1L6/CEGN061C5/thread/CEGN061C5-1689564692.089529
![image](https://github.com/filecoin-project/lotus/assets/24952678/43f02d0c-6d31-4a92-974a-dc284cdd7bb6)

### Logging Information

```text
https://files.slack.com/files-pri/TEHTVS1L6-F05HRV55WE7/image.png
```

**Comment by rjan90** [comment]
The Lotus raft-cluster has been dropped entirely, in this PR: https://github.com/filecoin-project/lotus/pull/11468. This feature never graduated beyond an experiment, had poor UX (e.g. no way to manage a running cluster, so it didn't even provide HA), and pulled in a lot of heavy dependencies.
