### ISSUE TITLE
mainnet sync err: miner id does not map to peer that sent message

### ISSUE THREAD

**Issue by TonyS001** [filecoin-project/lotus#11090]
Lotus Version:
1.23.2-dev+mainnet+git.517c0a53b
APIVersion:66816

I start a mainnet node but can't sync. I attach the log.

[lotus.log](https://github.com/filecoin-project/lotus/files/12101877/lotus.log)

**Comment by TippyFlitsUK** [comment]
Please use the [bug report template](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fbug&projects=&template=bug_report.yml) to submit an issue @TonyS001!

Many thanks 🙏
