### ISSUE TITLE
Direct Data Onboarding Actors implementation

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/lotus#11103]
## User Story

Filecoin users should have flexibility in how they track their storage deals.  If neither client nor SP is getting utility out of the builtin market they should be able to opt out.  Direct data onboarding is a protocol change that lets users add data (FIL+ or not) to sectors without making a deal.  This can potentially save all (or for FIL+ deals a subset) of publish storage deals gas which makes SP operations and the cost they pass on to clients for storage cheaper.

## Acceptance Criteria

This ticket tracks this change being implemented in builtin actors
Note that this is a bigger job than 2 weeks.  So this ticket can represent a sprint's worth of work towards the goal.

```[tasklist]
### Deliverables
- [x] A well tested builtin actors bundle with this change for integration into lotus
- [x] A finalized FIP design after working through the
```

## Technical Breakdown
```[tasklist]
### Development
- [x] Breakdown here: https://github.com/filecoin-project/builtin-actors/issues/1342
```

```[tasklist]
### Testing
- [x] Also included in the break down here: https://github.com/filecoin-project/builtin-actors/issues/1342
```

**Comment by rjan90** [comment]
Closing this ticket, as DDO shipped with nv22.
