### ISSUE TITLE
Lotus-Provider Binary

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11106]
## User Story
Lotus-Provider will be the new, YugabyteDB-tasked binaries that will eventually replace all the miner/worker tasks (while mostly leaving alone the old binaries in-case they have considerable efforts necessary to migrate to the new setup). 

## Acceptance Criteria
lotus-provider binary that builds with the normal commands, receives config, expresses it to the database.

```[tasklist]
### Techincal tasks:
- [ ] Create lotus-provider and wire it up
- [ ] It should use the Miner's config system and HTTP system to future be able to support Sealing APIs
- [ ] It should support SectorIndex APIs -- Note this has a dependency on Shrenuj
- [ ] It should run a harmony-task instance
```

```[tasklist]
### Techincal decesion to keep in mind:
- [ ] Stage it to resemble lotus-miner internally to be easy to later handle (the remaining) the Miner public APIs.
- [ ] It should use the HarmonyTask library
```

```[tasklist]
### Testing
- [ ] Can I build & run lotus-provider and have it implement file retrieval APIs and established HTTP APIs for monitoring?
```

**Comment by rjan90** [comment]
Closed by: https://github.com/filecoin-project/lotus/pull/11203
