### ISSUE TITLE
WindowPoSt on Lotus-Provider

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11113]
## User Story
Users want the new SturdyPoSt experience using lotus-provider.

## Acceptance Criteria
WindowPoSt can be easily ran on lotus-provider and disabled on lotus-miner so that reliability improves. 

```[tasklist]
### Deliverables
- [ ] A configuration on lotus-miner can disable windowPoSt
- [ ] lotus-provider will automatically run windowPoSt (unless configured otherwise?)
```

## Technical Breakdown
```[tasklist]
### Development
- [ ] Leave existing implementations functional, but reference their codebases for WindowPoSt
- [ ] Create a WindowPoSt HarmonyTask.TaskInterface implementation with listeners in every lotus-provider
- [ ] Wire-up the ability to listen to the lotus daemon and filter for WindowPoSt messages
- [ ] Add configs to disable/limit tasks or listeners (otherwise all): --do="4🪟  🏆  0🎁  0⛓️👂  2🔓" 
```

```[tasklist]
### Testing
- [ ] Test rollout plan for upgrade: Disable Window Post, restart lotus-miner,  then start lotus-provider ?
- [ ] Ensure by integration test that a message for windowPoSt can be received by 1 lotus-provider and worked by another.
- [ ] Ensure old run-style works as well. lotus-provider is optional. 
```

**Comment by jennijuju** [comment]
whats lotus provider?

**Comment by snadrus** [comment]
lotus-provider is the name of a new Lotus binary that will ease the transition to a new scheduler by optionally replacing WindowPoSt's miner+worker arrangement. A config can tell Miner to stop caring about that task. It will grow to include all miner+worker tasks while providing the option for slower migrators to use their stack modifications for a short while longer by holding back onto the miner+worker arrangement.

**Comment by rjan90** [comment]
Closing as this task has been compledted, as WindowPoSt can be ran in lotus-provider
