### ISSUE TITLE
EmptyEthHash duo to GC

### ISSUE THREAD

**Issue by rickiey** [filecoin-project/lotus#11117]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
v1.23.0+
```

### Repro Steps

I query history eth event log , I got ` tx_hash: '0x0000000000000000000000000000000000000000000000000000000000000000'`
my lotus config.toml:
```
[Chainstore]
  EnableSplitstore = true
  [Chainstore.Splitstore]
    ColdStoreType = "discard"
    HotStoreType = "badger"
    MarkSetType = "map"
    HotStoreFullGCFrequency = 1
    HotStoreMaxSpaceTarget = 800000000000
    HotStoreMaxSpaceThreshold = 150000000000
    HotstoreMaxSpaceSafetyBuffer = 50000000000
[Fevm]
  EnableEthRPC = true
  EthTxHashMappingLifetimeDays = 0
  [Fevm.Events]
    MaxFilterHeightRange = 43200
```

### Describe the Bug

I expect get valid txhash,related code at https://github.com/filecoin-project/lotus/blob/43ac79944f36585f43432b9b50dc66330ce1a15f/node/impl/full/eth.go#L2078
it return  EmptyEthHash when cid not found in chain state(duo to GC), but it exist in sqlite database (table eth_tx_hashes),
so ,I think I can check again from the database

I tried to use  `ethtypes.EthHashFromCid`, but it's wrong

### Logging Information

```text
debug
```

**Comment by Stebalien** [comment]
We could but... that's going to be inconsistent. IMO, the correct solution is to trim the event database when we discard messages during splitstore compaction (see https://github.com/filecoin-project/lotus/issues/11681#issuecomment-2007958390).

**Comment by Stebalien** [comment]
I'm going to submit a patch that _skips_ events where we no longer have the associated message.
