### ISSUE TITLE
Consolidation Thread for Ubuntu 22.04 Related Lotus Issues

### ISSUE THREAD

**Issue by TippyFlitsUK** [filecoin-project/lotus#11124]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [X] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
N/A
```

### Repro Steps

See below

### Describe the Bug

This issue ticket will act as a consolidation thread for all reported Lotus issues that appear to occur purely as a result of running Ubuntu 22.04.

I will continue to add further context and "area" tags to this section as new tickets transpire. 

### Logging Information

```text
TBD
```

**Comment by TippyFlitsUK** [comment]
Comment from @stuberman during EMEA SPWG - 14th August 2023


> I asked because I have heard of issues at ESPA. I think Future Tech mention these, and it seems that the new code for sealing (golden Gate) requires 22.04)

**Comment by rjan90** [comment]
Its seems fine to close this now? Given that there has been no reports yet, and we got a couple of users reporting that operations has been fine for over 2 months when running daemon, miner, workers on Ubuntu 22.04
