### ISSUE TITLE
Implementation plan for direct data onboarding proposal' in Lotus-Miner

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#11125]
**Description**
Work plan for the Lotus-Miner implementation of [implementing the direct data onboarding proposal](https://pl-strflt.notion.site/Direct-data-onboarding-FIL-technical-design-c90648ef896b4edeaab0479e33d9dfa0) in lotus-miner. The proposal aims to simplify data onboarding to sectors for Storage Providers (SPs) and reduce data onboarding cost.

```[tasklist]
### LM Tasks
- [x] Expand SectorAddPieceToAny to accept new allocation info (~1 hour)
- [x] Make the sealing pipeline input code be aware of new allocation fields for sector duration calculations (~1 day)
- [ ] #11192
- [x] Inspect other accesses to api/SectorPiece.DealInfo in the pipeline, and extend those to support new allocation fields (~1-2 days)
- [x] [Support new Precommit/Commit methods - switch to using new precommit_batch2](https://github.com/filecoin-project/lotus/issues/11139)
- [x] Support new Precommit/Commit methods - Add codepaths for new Commit
- [ ] Integration testing (~3-5 days)
```

**Comment by magik6k** [comment]
What I see here:
* Lotus-Miner
  * Expand `SectorAddPieceToAny` to accept new allocation info (~1 hour)
    * This can be done by adding new optional fields to `api/PieceDealInfo` for the Allocation, no new method needed
  * Make the sealing pipeline input code be aware of new allocation fields for sector duration calculations (~1 day)
    * This should boil down to replacing instances of accesses to `piece.DealInfo` in [input.go](https://github.com/filecoin-project/lotus/blob/master/storage/pipeline/input.go) with a helper which can handle the new allocation fields
  * Inspect other accesses to `api/SectorPiece.DealInfo` in the pipeline, and extend those to support new allocation fields (~1-2 days)
    * This seems to be mostly just a handful of simple sanity-checks, and error-recovery functions
* Integration testing
  * If we can write some ITests which just interact with SectorAddPieceToAny without the markets subsystem, and exercise the new logic this way, without changes to legacy markets.
    * If we want to fully deprecate legacy markets, we will need a new framework for making deals in integration tests anyways, so this work will be quite useful even outside supporting this proposal
    * Initially this should just be adding a number of test-cases adding coverage to the new codepaths, plus the new deal test harness
    * ~3-5 days
* Lotus
  * Unclear if the proposal will depend on clients/SPs consuming events from native actors, if yes, this may mean some new APIs

**Comment by jennijuju** [comment]
> Unclear if the proposal will depend on clients/SPs consuming events from native actor

so far no - https://github.com/FILCAT/fil-pm/issues/4 i think taking the async approach is better

**Comment by jennijuju** [comment]
@magik6k 
skimming this through:
-  there will be a new PRU method as well to add 
- need some design discussion:  should lotus miner database to have a field to capture the market that the deal is participated in? 
- the estimation seems a bit too optimistic to me, especially for the new commit code path. im interested in what kind of SP ux do we plan to offer here

**Comment by rjan90** [comment]
> - If we can write some ITests which just interact with SectorAddPieceToAny without the markets subsystem, and exercise the new logic this way, without changes to legacy markets.
>    - If we want to fully deprecate legacy markets, we will need a new framework for making deals in integration tests anyways, so this work will be quite useful even outside supporting this proposal

If writing a new framework I think we should also consider doing the sealing/proving through lotus-workers and not the built-in lotus-miner workers, such that https://github.com/filecoin-project/lotus/issues/10870 will not break the tests, and an eventual path for depreciation of the built-in worker is more straight forward.

**Comment by anorth** [comment]
> Support new Precommit/Commit methods
>   - Switch to using the new precommit_batch2 (~1 day)

There will be new PRU methods too, and similarly there's an old legacy one to be deprecated. Can Lotus miner switch to `prove_replica_updates2`? The difference, as for pre-commit, is that the new unsealed CID is required as a parameter.

**Comment by rjan90** [comment]
Closing as https://github.com/filecoin-project/lotus/pull/11226 has been merged into the `feat/nv22` branch
