### ISSUE TITLE
Unable to use lotus-shed for remote ledger connection

### ISSUE THREAD

**Issue by bobdubois** [filecoin-project/lotus#11130]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
1.23.2 mainnet
```

### Repro Steps

1. make lotus-shed lotus-wallet on a Linux system
2. ./lotus-shed ledger list
3. throws error: ERROR   lotus-shed      lotus-shed/main.go:122  LedgerHID device (idx 0) not found

### Describe the Bug

Using a Ledger Nano S Plus, trying to set up remote ledger support for my lotus daemon/miner setup.
Unable to find the JSON string from the Ledger device with `lotus-shed`.
Instantly throws an error:
`ERROR   lotus-shed      lotus-shed/main.go:122  LedgerHID device (idx 0) not found
`
`lususb` shows the Ledger device.
Ledger Live works fine on the system.
Ledger Live not running at the same time!
Ledger is unlocked, Filecoin app is open and in expert mode.

Found the HW path in Ledger Live:
`  "freshAddressPath": "44'/461'/0'/0/0",
`
Tried to run
`lotus-shed ledger key-info "m44'/461'/0'/0/0" `
which throws the same error.

Tried on 3 different Linux flavors (Arch, Manjaro and Ubuntu) with all the same error.

### Logging Information

```text
no errors logged other than on stdout.
```

**Comment by rjan90** [comment]
This issue should now have been fixed in the master branch, after switching to upstream ledger library: https://github.com/filecoin-project/lotus/pull/11651
