### ISSUE TITLE
lotus-worker does not support IPv6

### ISSUE THREAD

**Issue by paul8046** [filecoin-project/lotus#11138]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.23.2+mainnet+git.8347235b5+api1.5.0
Local: lotus-miner version 1.23.2+mainnet+git.8347235b5
```

### Repro Steps

1. Configure `MINER_API_INFO` to use IPv6
2. Run `lotus-worker run`
3. Worker fails to start and go log contains errors

### Describe the Bug

lotus-worker is not able to parse IPv6 formatted API keys

### Logging Information

```text
{"level":"info","ts":"2023-08-05T11:49:22.566+1200","logger":"main","caller":"lotus-worker/main.go:514","msg":"Opening local storage; connecting to master"}
{"level":"warn","ts":"2023-08-05T11:49:22.569+1200","logger":"main","caller":"lotus-worker/main.go:114","msg":"dial tcp: address ::1:49252: too many colons in address"}
```

**Comment by rjan90** [comment]
Thank you so much for the report @paul8046! I can confirm that I was able to repro this by following your repro-steps:

```
8-08T05:09:25.643-0400    INFO    main    lotus-worker/main.go:531        Opening local storage; connecting to master
2023-08-08T05:09:25.659-0400    WARN    main    lotus-worker/main.go:114        dial tcp: address ::1:2345: too many colons in address
```

I have put up the issue on our Sprint planning board https://github.com/orgs/filecoin-project/projects/92, and I will try to shcedule some work on this in the current sprint if we have some spare cycles, else it should get some work done in the next sprint.
