### ISSUE TITLE
Remove Benign `failed to lock map` Message When Sealing a New Sector

### ISSUE THREAD

**Issue by TippyFlitsUK** [filecoin-project/lotus#11143]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.23.4-dev+mainnet+git.d082940d5+api1.5.0
Local: lotus version 1.23.4-dev+mainnet+git.d082940d5

And all other Lotus versions
```

### Repro Steps

1. Start to seal a new sector

### Describe the Bug

Users are currently seeing multiple benign warnings whenever they start to seal a new sector.

```
023-08-07T17:19:51.350 WARN storage_proofs_porep::stacked::vanilla::memory_handling > failed to lock map Os { code: 12, kind: OutOfMemory, message: "Cannot allocate memory" }, falling back
2023-08-07T17:19:51.350 WARN storage_proofs_porep::stacked::vanilla::memory_handling > failed to lock map Os { code: 12, kind: OutOfMemory, message: "Cannot allocate memory" }, falling back
```
```
2023-08-07T17:16:52.086+0100	WARN	ffiwrapper	ffiwrapper/sealer_cgo.go:195	AddPiece: cannot close pieceData reader *nullreader.NullReader because it is not an io.Closer
```

These warning messages need to be removed/tuned in order to prevent further confusion. 

### Logging Information

```text
See above
```

**Comment by cryptonemo** [comment]
Related to https://github.com/filecoin-project/lotus/pull/11145
