### ISSUE TITLE
Direct data onboarding migration (Sector deal mapping)

### ISSUE THREAD

**Issue by snissn** [filecoin-project/lotus#11160]
## User Story

Direct FIL+ is a label for changes to the Filecoin built-in actors, and the components that interact with them, to enable gas-cheap data onboarding, including Filecoin Plus. The built-in storage market actor is bypassed, and the verified registry’s on-chain allocation/claim record suffices to represent a simple “deal”. Direct data onboarding can’t handle client payments (yet), but most  deals today have no on-chain payment anyway.

After the initial Direct FIL+ changes,  subsequent, smaller changes will be possible to support scalable FIL+ allocations (single transaction covering multiple sectors) and flexibility for other kinds of data applications.

for more see direct data onboarding notion doc https://www.notion.so/pl-strflt/Direct-FIL-impacts-work-outline-57399e0fdfd242d09aabad7357945798

## Acceptance Criteria

```[tasklist]
### Deliverables
- [ ] A migration exists
- [ ] Migration is tested for correctness 
- [ ] Migration has acceptable time and memory performance

```

## Technical Breakdown
```[tasklist]
### Development
- [x] find the types need to make a migration (SectorDealIDs vec)
- [x] make an integration branch
- [x] go-state-types PR with all the types needed to run the migration
- [x] 1. In each miner actor migration i.e. the miner actor migration job, construct, populate and flush an HAMT mapping from sector number to deal IDs in that sector
- [x] 2. Figure out what to do with sectors that don't have deals, Im pretty sure we just don't them (TODO)
- [ ] create a  a market migration
- [ ] run market migraiton after all the miners are done migrating, so have it as a post-op step (v9 already did this, so you have prior work).
- [ ] 3. Figure out a way to return the (miner address, cid(the-sectorID-dealIDVector-HAMT)) of each miner actor from its migration job and collect these somewhere in memory so that we can add them to the market actor later
- [ ] 4. Market actor migration must be postponed to the end of the migration (there is a way to do this in the migration framework)
- [ ] 5. figure outa way to pass the (addr, cid) pairs to the market actor migration
- [ ] figure out a way to make the migration jobs communicate as needed
- [ ] 6. Write the market actor migration, it should be a loop over a in memory map and adding to a HAMT and then flushing
```

```[tasklist]
### Testing
- [ ] Use framework to test performance
- [ ] Write itests to confirm validity of migrations
```

**Comment by anorth** [comment]
@ZenGround0 and I are strongly considering removing SectorOnChainInfo.DealIDs as part of direct data onboarding, because those sector infos are to be re-written as part of fixing the sector activation epoch bug. I don't know if that should be part of this issue or not, but please track it somewhere.

**Comment by snissn** [comment]
write down explicitly and clearly what data needs to be migrated in this ticket

**Comment by jennijuju** [comment]
> > ZenGround0 and I are strongly considering removing SectorOnChainInfo.DealIDs as part of direct data onboarding
> 
> There are some uses in / outside of lotus for those fields, but those are mostly around inspecting deal data. I guess the only thing which hurts from this is easy translation from sector->deals.. which will be somewhat annoying for tools like https://dag.parts, but not an end of the world.
> 
> Not sure if any client/data onboarding tooling uses this, @ribasushi may know.

I guess the question is - without this info, how will lotus users still be able to inspect deal <> sector?

**Comment by stuberman** [comment]
> ZenGround0 and I are strongly considering removing SectorOnChainInfo.DealIDs as part of direct data onboarding

Our customers store that data on our Filecoin systems, all they know is their file names, not CIDs or deals.
When a sector faults and we have a problem with the deal/data in that sector, we need to know how to map that deal/data to a sector to correct the issue.

**Comment by anorth** [comment]
This discussion might be better in the protocol forums like https://filecoinproject.slack.com/archives/C05M7U7L648 or https://github.com/filecoin-project/FIPs/discussions/730. But since I've observed it here...

See the [draft technical design](https://pl-strflt.notion.site/Direct-data-onboarding-FIL-technical-design-c90648ef896b4edeaab0479e33d9dfa0?pvs=4). The mapping from sector->deals is moving from the miner actor to the built-in market actor. That is the only reason we can delete this from the per-sector info on chain anyway. There will also be a deal->sector mapping there, which we can happily add at little cost for even more convenience.

**Comment by anorth** [comment]
Code for the destination type is on the integration/direct-onboarding branch. https://github.com/filecoin-project/builtin-actors/blob/integration/direct-onboarding/actors/market/src/state.rs#L77-L83

**Comment by snissn** [comment]
@anorth thanks!

**Comment by rjan90** [comment]
Closing since NV22 & DDO has landed on Mainnet.
