### ISSUE TITLE
WindowPostTask.CanAccept partial impl of harmonytask.TaskInterface

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11172]
## User Story
Users want lotus-provider requesting to accept window-post tasks when it's the best option for a worker.

## Acceptance Criteria
WindowPoSt harmony-tasks will considered by each lotus-provider and ran by a fairly good choice of worker for the task.

```[tasklist]
### Deliverables
- [ ] CanAccept() impl will consider the work against: (sector location / groups) (available disk) (fail/retry profile) (deadline) (fail/retry profile) 
```

## Technical Breakdown
```[tasklist]
### Development
- [ ] Create an impl of harmonytask.TaskInterface.CanAccept in lib/harmony/tasks/windowpost/
- [ ] Evaluate the existing scheduler for any other concerns once handled by it.
- [ ] Implement the above deliverable along with any other findings from the previous task.
```

```[tasklist]
### Testing
- [ ] Not useful to test externally as it's an incomplete implementation. DB entries should be made for partial verification.
```

**Comment by snadrus** [comment]
Lightened the scope: RM sector location & available disk (only a few bytes of leaf data is moved).
It's ready for review, but best tested in a lotus-provider implementation, so it is waiting behind #11322 for completion

**Comment by rjan90** [comment]
Closing as this task has been completed
