### ISSUE TITLE
lotus-storage-miner doesnt seem to recover properly from a 'chain sethead'

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#1118]
When performing a network upgrade this morning, I noticed that I had to restart the storage miner process after the daemon ran a sethead to get it to resume mining on the new head I selected.

**Comment by jennijuju** [comment]
@magik6k has this been worked on/fixed?

**Comment by magik6k** [comment]
I'm not sure, this needs to be verified

**Comment by jennijuju** [comment]
Things got improved a lot since this ticket was open - please create a new issue if you are still running into it with the latest lotus release!
