### ISSUE TITLE
Cannot build lotus-wallet independently

### ISSUE THREAD

**Issue by paul8046** [filecoin-project/lotus#11186]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus-wallet version 1.23.3+mainnet+git.7bb1f98ac
```

### Repro Steps

1. `git clone https://github.com/filecoin-project/lotus`
2. `cd lotus`
3. `git checkout releases`
4. `make lotus-wallet`

### Describe the Bug

lotus-wallet will not build unless proceeded by some other lotus component (such as lotus-shed). `make lotus-shed lotus-wallet` will work.

### Logging Information

```text
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.7bb1f98ac" -o lotus-wallet ./cmd/lotus-wallet
chain/consensus/utils.go:12:2: github.com/filecoin-project/filecoin-ffi@v0.30.4-0.20220519234331-bfd1f5f9fe38 (replaced by ./extern/filecoin-ffi): reading extern/filecoin-ffi/go.mod: open /Users/tintin/Code/lotus/lotus/extern/filecoin-ffi/go.mod: no such file or directory
chain/vm/fvm.go:21:2: github.com/filecoin-project/filecoin-ffi@v0.30.4-0.20220519234331-bfd1f5f9fe38 (replaced by ./extern/filecoin-ffi): reading extern/filecoin-ffi/go.mod: open /Users/tintin/Code/lotus/lotus/extern/filecoin-ffi/go.mod: no such file or directory
make: *** [lotus-wallet] Error 1
```

**Comment by rjan90** [comment]
Hey @paul8046! Thanks for the report, I have added a PR that fixes this in #11187
