### ISSUE TITLE
Integration of WdPost Task generation into Harmony task interface and lotus-provider binary

### ISSUE THREAD

**Issue by shrenujbansal** [filecoin-project/lotus#11207]
## User Story

#11170 implemented the functionality to listen to blockchain head changes and generate WdPost generation work and stick it in a DB

#11165 provides the Harmony Task Interface skeleton and the underlying implementation which ties it together
#11106 provides the binary where everything runs

## Acceptance Criteria

Run the lotus-provider binary and generate wdpost tasks in the DB

```[tasklist]
### Deliverables
- [ ] Integration with Harmony task
- [ ] Integration with lotus-provider binary
- [ ] Integration testing: WDPostGenerationTasks being populated in DB via lotus-provider binary
```

## Technical Breakdown
```[tasklist]
### Development
- [ ] Create WDPost generation task class and move AddTask implementation inside
- [ ] Invoke WDPostScheduler, proveHandler and WDPostGenerationTask threads from the lotus-provider binary
- [ ] Synchronization between proveHandler and WDPostTask threads
```

```[tasklist]
### Testing

```

**Comment by rjan90** [comment]
Closed by: https://github.com/filecoin-project/lotus/pull/11364
