### ISSUE TITLE
lotus-provider config

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11213]
## User Story
Configs for a system with distributed control can be tricky. Users want a simpler config system for lotus-provider.

## Acceptance Criteria
Timeline: This is after "SturdyPoSt: WindowPoSt" is testable, but before it ships so that no release includes the old config system.
 
```[tasklist]
### Deliverables
- [ ] lotus-provider config set <config_file>
- [ ] lotus-provider config get
- [ ] The "config file" will be defaults with documentation comments and group overlays. 
- [ ] The only instance-specific configs will be DB connection string and an ordered list of groups (as CLI or ENV)
```

## Technical Breakdown
```[tasklist]
### Development
- [ ] A config system (structs) with docs & defaults.
- [ ] lotus-provider CLI uploader/downloader which should enrich the result with doc & examples.
- [ ] A config reader which provides lotus-provider with a single final config value set. 
```

```[tasklist]
### Testing

```

**Comment by snadrus** [comment]
Be sure to try:  @TippyFlitsUK 

GOLOG_LOG_LEVEL="debug" ./lotus-provider --db-host=localhost config default
GOLOG_LOG_LEVEL="debug" ./lotus-provider --db-host=localhost config set base.toml 
GOLOG_LOG_LEVEL="debug" ./lotus-provider --db-host=localhost config set someTestLayer.toml 
GOLOG_LOG_LEVEL="debug" ./lotus-provider --db-host=localhost config get someTestLayer 
GOLOG_LOG_LEVEL="debug" ./lotus-provider --db-host=localhost config list     
GOLOG_LOG_LEVEL="debug" ./lotus-provider --db-host=localhost config view someTestLayer

**Comment by snadrus** [comment]
@magik6k Tested the above. Please review.

**Comment by magik6k** [comment]
Config was implemented in curio a long time ago
