### ISSUE TITLE
Add an API that returns all FIL+ pieces 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#11249]
post DDO, we need APIs to support those who wants to build tooling just for FIL+ (i.e FIL+ checker, FIL+ retrieval bot)
   What exists today is:
   - `StateGetClaims` returns all the pieces fully committed post Shark upgrade
   - `StateMarketDeals` returns all the verified pieces published in deals
   What is missing is 
   - one API that returns ALL the verified pieces that are in the network, despite when they are onboarded, whether they are onboarded via f05 or DDO. I would imagine this API has two parts, first is getting all the deals onboarded before shark and collect all the verified ones, and the second pieces would simply getting all the pieces that has a claim (covers all the fil+ deals made post shark). 

I want to bike shed on whether this is something lotus should consider adding, cuz we can also just say get this out https://github.com/filecoin-project/lotus/issues/11173, users can filter out the FIL+ pieces themself. My only concern would be the performance in that (and whether it is trivial for folks to understand how to build that - tho I would imagine fil+ would be interested in building this)

**Comment by rjan90** [comment]
Superceeded by #11614
