### ISSUE TITLE
Pond - attempting to make a deal shows "wrong param count" in console

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#1125]
**Describe the bug**

In the Pond UI, clicking on the "Deal!" button shows a "wrong param count" error in the devtools console.

**Screencast**

![lotus-pond-make-deal](https://user-images.githubusercontent.com/20886/72763805-5416bc80-3b9a-11ea-873c-2209df596126.gif)

**Version (run `lotus --version`):**

```
$ lotus version
0.2.5+api0.1.6
lotus version 0.2.5
$ git rev-parse HEAD
c5ece2a8925e1cb6b7c6a59071f2396d2357c3c3
```

**Comment by whyrusleeping** [comment]
I think we can close this since we're deprecating pond
