### ISSUE TITLE
Different versions that have inconsistent return field values when calling receipts

### ISSUE THREAD

**Issue by dubuqingfeng** [filecoin-project/lotus#11252]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
v1.22.1

v1.23.3
```

### Describe the Bug

We have two nodes with different versions that have inconsistent return field values when calling receipts

v1.23.3:

"effectiveGasPrice":"0x21b84"

v1.22.1：

"effectiveGasPrice":"0x21b82"

### Logging Information

```text
v1.23.3


➜  ~ curl --location --request POST 'https://v1.23.3/rpc/v1' \
--header 'Content-Type: application/json; charset=utf-8' \
--data '
    {
        "id": 744,
        "jsonrpc": "2.0",
        "method": "eth_getTransactionReceipt",
        "params": [
            "0x6accb8eb1ef2eb0a0d9a1262dd8dbc94efe4afff8479951d05a6ee65f97991a2"
        ]
    }
'

{"jsonrpc":"2.0","result":{"transactionHash":"0x6accb8eb1ef2eb0a0d9a1262dd8dbc94efe4afff8479951d05a6ee65f97991a2","transactionIndex":"0x12","blockHash":"0x8d0220c486c6f3f387245bf63b24ccce069a5f1df9b57ca79189966fcbb87465","blockNumber":"0x30b34f","from":"0xff000000000000000000000000000000001f24c5","to":"0xff000000000000000000000000000000001f43de","root":"0x0000000000000000000000000000000000000000000000000000000000000000","status":"0x1","contractAddress":null,"cumulativeGasUsed":"0x0","gasUsed":"0x39450d1","effectiveGasPrice":"0x21b84","logsBloom":"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","logs":[],"type":"0x2"},"id":744}
```
v1.22.1

```
 curl --location --request POST 'http://v1.22.1/rpc/v1' \
> --header 'Content-Type: application/json; charset=utf-8' \
> --data '
>     {
>         "id": 744,
>         "jsonrpc": "2.0",
>         "method": "eth_getTransactionReceipt",
>         "params": [
>             "0x6accb8eb1ef2eb0a0d9a1262dd8dbc94efe4afff8479951d05a6ee65f97991a2"
>         ]
>     }'
{"jsonrpc":"2.0","result":{"transactionHash":"0x6accb8eb1ef2eb0a0d9a1262dd8dbc94efe4afff8479951d05a6ee65f97991a2","transactionIndex":"0x12","blockHash":"0x8d0220c486c6f3f387245bf63b24ccce069a5f1df9b57ca79189966fcbb87465","blockNumber":"0x30b34f","from":"0xff000000000000000000000000000000001f24c5","to":"0xff000000000000000000000000000000001f43de","root":"0x0000000000000000000000000000000000000000000000000000000000000000","status":"0x1","contractAddress":null,"cumulativeGasUsed":"0x0","gasUsed":"0x39450d1","effectiveGasPrice":"0x21b82","logsBloom":"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","logs":[],"type":"0x2"},"id":744}
```
```

**Comment by dubuqingfeng** [comment]
other rpc:

$ curl 'https://rpc.ankr.com/filecoin' \
--data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x6accb8eb1ef2eb0a0d9a1262dd8dbc94efe4afff8479951d05a6ee65f97991a2"],"id":1}
'
{"jsonrpc":"2.0","result":{"transactionHash":"0x6accb8eb1ef2eb0a0d9a1262dd8dbc94efe4afff8479951d05a6ee65f97991a2","transactionIndex":"0x12","blockHash":"0x8d0220c486c6f3f387245bf63b24ccce069a5f1df9b57ca79189966fcbb87465","blockNumber":"0x30b34f","from":"0xff000000000000000000000000000000001f24c5","to":"0xff000000000000000000000000000000001f43de","root":"0x0000000000000000000000000000000000000000000000000000000000000000","status":"0x1","contractAddress":null,"cumulativeGasUsed":"0x0","gasUsed":"0x39450d1","effectiveGasPrice":"0x21b84","logsBloom":"0xfffffffffffffffffeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffdffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff","logs":[],"type":"0x2"},"id":1


curl 'https://api.node.glif.io/' \
--data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x6accb8eb1ef2eb0a0d9a1262dd8dbc94efe4afff8479951d05a6ee65f97991a2"],"id":1}
'

{"jsonrpc":"2.0","result":{"transactionHash":"0x6accb8eb1ef2eb0a0d9a1262dd8dbc94efe4afff8479951d05a6ee65f97991a2","transactionIndex":"0x12","blockHash":"0x8d0220c486c6f3f387245bf63b24ccce069a5f1df9b57ca79189966fcbb87465","blockNumber":"0x30b34f","from":"0xff000000000000000000000000000000001f24c5","to":"0xff000000000000000000000000000000001f43de","root":"0x0000000000000000000000000000000000000000000000000000000000000000","status":"0x1","contractAddress":null,"cumulativeGasUsed":"0x0","gasUsed":"0x39450d1","effectiveGasPrice":"0x21b84","logsBloom":"0xf7ffdffdf3fc5ffafffffffcfdbfffd7ffdfd7ffe7e9fdffdfffbfdefefeffffbfffdffffefbefff9fffffffffffb7ffffcffffffaffffffffdffdf7ff7e9ffbffffffffdebffffddefffffffff3dffffffffffefffffbfffff37fffe777effffffbff7fff93bfef3fffffffffffdffffff5f5ffffbff7fff77fffff7bbffffaffffebfffbff7fbfffe7fffdffdfffffffbbbfbfffffe7fffdfffffefeffefffbf7fdff7dfeebfebffffefffd5fffb7fffffefefffefffffffbfffffdeaedff6eeffdffbffffdf7bbfffebffff6f6e7ddf7fffdfdfffffffffffbffffffbfefbbfbffffffffff7ffdbff7defff7ffffaffffefffffdbff5ffffdbff6fffff6a7","logs":[],"type":"0x2"},"id":1}

**Comment by Stebalien** [comment]
@wanyvic you're absolutely right.
