### ISSUE TITLE
CLI for move-partitons

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11272]
## User Story
Users want a CLI way to move deadlines.

## Acceptance Criteria
The deadlines move when the CLI is used correctly, or else meaningful errors occur.

I expect the code to look fairly similar to the compact-partitions CLI ([link](https://github.com/filecoin-project/lotus/blob/35ceb02c50ef217c22bf36fea4ebaacf284652a5/cmd/lotus-miner/sectors.go#L2227-L2394)), which deals with a lot of the same partition-boundaries as the move-partition FIP.

### Deliverables
A command:
lotus-miner proving deadline move --from [deadline | partition(s)] --to [deadline]

## Technical Breakdown
Target functions are from https://github.com/filecoin-project/builtin-actors/pull/1326

### Development
```[tasklist]
- [x] Make a new branch of Lotus' branch feat/move-partitions
- [ ] Call code from
- [ ] Write code similar to the above example
- [ ] PR back to feat/move-partitions
```

### Testing

lotus-miner proving deadline move --from [deadline | partition(s)] --to [deadline]
This should work on even a "make 2k" local net.

**Comment by rjan90** [comment]
- The `feat/move-partitions` branch is already up: https://github.com/filecoin-project/lotus/tree/feat/move-partitions. It was branched off the `feat/nv21` branch which includes the network upgrade skeleton.

**Comment by jennijuju** [comment]
actor PR https://github.com/filecoin-project/builtin-actors/pull/1326/files

the function we will be calling is https://github.com/filecoin-project/builtin-actors/blob/faa4873e517d43e464338c094aaf7b66df256110/actors/miner/src/lib.rs#L2696 

your params https://github.com/filecoin-project/builtin-actors/blob/faa4873e517d43e464338c094aaf7b66df256110/actors/miner/src/types.rs#L247

**Comment by mb1896** [comment]
Related PRs have been merged.

**Comment by rjan90** [comment]
Closing this issue now that https://github.com/filecoin-project/lotus/pull/11301 has been merged
