### ISSUE TITLE
Add to Docs recommendation to increase UDP Buffer Sizes

### ISSUE THREAD

**Issue by nzenchik** [filecoin-project/lotus#11289]
## User Story
As Lotus client uses quic-go library which requires [UDP Buffer size increase](https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes) as most standard Linux distributions has lower params. It will be a good point to add this recommendation to docs

## Acceptance Criteria
Increase UDP Buffer Sizes section is added to [setup guide](https://docs.filecoin.io/nodes/full-nodes/basic-setup)

**Comment by rjan90** [comment]
Hey @nzenchik! Thanks for the report. I think some steps that can be taken here, as you mentioned is adding to the docs:
- I have opened one in the lotus-docs repo: https://github.com/filecoin-project/lotus-docs/issues/656
- Add an alert to the Lotus node if the UDP Buffer size is too low
