### ISSUE TITLE
Terminating a sector is error

### ISSUE THREAD

**Issue by Andrew-wwj** [filecoin-project/lotus#11280]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
Daemon:  1.23.3+mainnet+git.7bb1f98ac+api1.5.0
Local: lotus-miner version 1.23.3+mainnet+git.7bb1f98ac
```

### Repro Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

### Describe the Bug

actor: f0145162
sectorNumber: 19461 is always Terminating status, but the terminate
message ID: bafy2bzaceawvjxcnb74x3d37t5ffl4bkt74jgiubxr6awsmxjehsz7bdto5w2
shows it is OK.
How can I remove this sector?

SectorID:       19461
Status:         Terminating
CIDcommD:       baga6ea4seaqomqafu276g53zko4k23xzh4h4uecjwicbmvhsuqi7o4bhthhm4aq
CIDcommR:       bagboea4b5abcbwbfwffiih6vjy5bdd5qwuo55v5fitfzzexthpudzuyiwx4k4obd
Ticket:         406f45eaba69bd274116212c6b4342891e95574e0bb576be43ca04956c937252
TicketH:        968740
Seed:           bcf2202e5a7a4e398bb83fc9e854a422cf7c27b190f6f9211c4ed28b9f905ccd
SeedH:          971002
Precommit:      bafy2bzacedddokmy7ikrjuatd6try2jzcxridvnqmt4vjrvdmkefhzv3bnu2m
Commit:         bafy2bzacecf77k6omzzn2unmxrnp36dgk6b6qskxvkbzgvssdllolx6qf7fcg
Deals:          [0]
Retries:        0

Sector On Chain Info
SealProof:              9
Activation:             971057
Expiration:             4053002
DealWeight:             0
VerifiedDealWeight:             0
InitialPledge:          0.379836095945366137 FIL

Expiration Info
OnTime:         0
Early:          0
--------
Event Log:
0.      2021-07-27 23:18:35 +0900 JST:  [event;sealing.SectorStartCC]   {"User":{"ID":19461,"SectorType":9}}
1.      2021-07-27 23:20:20 +0900 JST:  [event;sealing.SectorPacked]    {"User":{"FillerPieces":[{"Size":68719476736,"PieceCID":{"/":"baga6ea4seaqomqafu276g53zko4k23xzh4h4uecjwicbmvhsuqi7o4bhthhm4aq"}}]}}
2.      2021-07-27 23:20:20 +0900 JST:  [event;sealing.SectorTicket]    {"User":{"TicketValue":"QG9F6rppvSdBFiEsa0NCiR6VV04LtXa+Q8oElWyTclI=","TicketEpoch":968740}}
3.      2021-07-28 08:43:56 +0900 JST:  [event;sealing.SectorPreCommit1]        {"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzY0R2lCVjFfMSIsImxhYmVscyI6eyJTdGFja2VkRHJnNjRHaUJWMSI6eyJsYWJlbHMiOlt7InBhdGgiOiIvZ3JvdXAxL3N0b3JhZ2UvbG90dXN3b3JrL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxNDUxNjItMTk0NjEiLCJpZCI6ImxheWVyLTEiLCJzaXplIjoyMTQ3NDgzNjQ4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9ncm91cDEvc3RvcmFnZS9sb3R1c3dvcmsvbG90dXN3b3JrZXIvY2FjaGUvcy10MDE0NTE2Mi0xOTQ2MSIsImlkIjoibGF5ZXItMiIsInNpemUiOjIxNDc0ODM2NDgsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2dyb3VwMS9zdG9yYWdlL2xvdHVzd29yay9sb3R1c3dvcmtlci9jYWNoZS9zLXQwMTQ1MTYyLTE5NDYxIiwiaWQiOiJsYXllci0zIiwic2l6ZSI6MjE0NzQ4MzY0OCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZ3JvdXAxL3N0b3JhZ2UvbG90dXN3b3JrL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxNDUxNjItMTk0NjEiLCJpZCI6ImxheWVyLTQiLCJzaXplIjoyMTQ3NDgzNjQ4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9ncm91cDEvc3RvcmFnZS9sb3R1c3dvcmsvbG90dXN3b3JrZXIvY2FjaGUvcy10MDE0NTE2Mi0xOTQ2MSIsImlkIjoibGF5ZXItNSIsInNpemUiOjIxNDc0ODM2NDgsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2dyb3VwMS9zdG9yYWdlL2xvdHVzd29yay9sb3R1c3dvcmtlci9jYWNoZS9zLXQwMTQ1MTYyLTE5NDYxIiwiaWQiOiJsYXllci02Iiwic2l6ZSI6MjE0NzQ4MzY0OCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZ3JvdXAxL3N0b3JhZ2UvbG90dXN3b3JrL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxNDUxNjItMTk0NjEiLCJpZCI6ImxheWVyLTciLCJzaXplIjoyMTQ3NDgzNjQ4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9ncm91cDEvc3RvcmFnZS9sb3R1c3dvcmsvbG90dXN3b3JrZXIvY2FjaGUvcy10MDE0NTE2Mi0xOTQ2MSIsImlkIjoibGF5ZXItOCIsInNpemUiOjIxNDc0ODM2NDgsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2dyb3VwMS9zdG9yYWdlL2xvdHVzd29yay9sb3R1c3dvcmtlci9jYWNoZS9zLXQwMTQ1MTYyLTE5NDYxIiwiaWQiOiJsYXllci05Iiwic2l6ZSI6MjE0NzQ4MzY0OCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZ3JvdXAxL3N0b3JhZ2UvbG90dXN3b3JrL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxNDUxNjItMTk0NjEiLCJpZCI6ImxheWVyLTEwIiwic2l6ZSI6MjE0NzQ4MzY0OCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZ3JvdXAxL3N0b3JhZ2UvbG90dXN3b3JrL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxNDUxNjItMTk0NjEiLCJpZCI6ImxheWVyLTExIiwic2l6ZSI6MjE0NzQ4MzY0OCwicm93c190b19kaXNjYXJkIjo3fV0sIl9oIjpudWxsfX0sImNvbmZpZyI6eyJwYXRoIjoiL2dyb3VwMS9zdG9yYWdlL2xvdHVzd29yay9sb3R1c3dvcmtlci9jYWNoZS9zLXQwMTQ1MTYyLTE5NDYxIiwiaWQiOiJ0cmVlLWQiLCJzaXplIjo0Mjk0OTY3Mjk1LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LCJjb21tX2QiOlsyMzAsNjQsNSwxNjYsMTkxLDIyNywxMTksMTIxLDgzLDE4NCwxNzMsMTEwLDI0OSw2MywxNSwyMDIsMTYsNzMsMTc4LDQsMjIsODQsMjQyLDE2NCwxNywyNDcsMTEyLDM5LDE1MywyMDYsMjA2LDJdfQ=="}}
4.      2021-07-28 09:25:45 +0900 JST:  [event;sealing.SectorPreCommit2]        {"User":{"Sealed":{"/":"bagboea4b5abcbwbfwffiih6vjy5bdd5qwuo55v5fitfzzexthpudzuyiwx4k4obd"},"Unsealed":{"/":"baga6ea4seaqomqafu276g53zko4k23xzh4h4uecjwicbmvhsuqi7o4bhthhm4aq"}}}
5.      2021-07-28 09:25:46 +0900 JST:  [event;sealing.SectorPreCommitted]      {"User":{"Message":{"/":"bafy2bzacedddokmy7ikrjuatd6try2jzcxridvnqmt4vjrvdmkefhzv3bnu2m"},"PreCommitDeposit":"53104672712174376","PreCommitInfo":{"SealProof":9,"SectorNumber":19461,"SealedCID":{"/":"bagboea4b5abcbwbfwffiih6vjy5bdd5qwuo55v5fitfzzexthpudzuyiwx4k4obd"},"SealRandEpoch":968740,"DealIDs":[],"Expiration":2523526,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}
6.      2021-07-28 09:29:00 +0900 JST:  [event;sealing.SectorPreCommitLanded]   {"User":{"TipSet":"AXGg5AIgEi0UkJ0UP/Xom+XCtI/Hat/J9iRqp5FIs9zG/hYg05MBcaDkAiDL+tEj15iF4BFsw8tSRzB7INg4Bj3/6UVjJ1iki4kyxgFxoOQCIB0g3LtTyPqcUMFrremCx2tRWsgaCubKEQ0Bls9Z/tmEAXGg5AIg7BhRcpc9ba43FIvGBOr4+osZ/j0PYZWf51c3n2HRSto="}}
7.      2021-07-28 10:44:00 +0900 JST:  [event;sealing.SectorSeedReady] {"User":{"SeedValue":"vPIgLlp6TjmLuD/J6FSkIs98J7GQ9vkhHE7Si5+QXM0=","SeedEpoch":971002}}
8.      2021-07-28 11:08:04 +0900 JST:  [event;sealing.SectorCommitted] {"User":{"Proof":"p+rRYJc9iD885hXtMg7ovq1G7hLc3EPaFeitKmjTNq+Z6G/UD0SmP1QmjvwQyK/Lix9CHpQmaIGIcEvpTzNkAtRYAD1OAFQYf14xJXHGaG6IXi1Mgcl8aTTCAH8KnNTSDvqDHfaaHuVNmYdXnNS5+eUBmxWZ3csdr+XSVjiAGORmtDB3RxlomoL087VSfwMTkXqq4RNjrBVMHyKCWLtXJe6Bhi6d9eSEKq2yyl2Y84kMdrVhJ1y+qbJ8ZbOpH9pVj5NS1e2/+7ADHQvMJ9uDCQi5+PEFHj2ELs1B0POzKA2LEVnLpluHK1igiNjJyQS6mZeaVFgj4w/tz43feXoiS15yMwj2ANZ5wVZUI0rObuHqF6n6CcaRjj6PLz4x7lAOGHcjbuDB/xSEig/79J643LR8XVhIvWR2/GHfgOFXyi5E8pYJzyRjWY1ZgnfOto+BtVtLtALmRd/JdNkvc9Y4gMAA/Iqk08Q5uzTFeYSlN69yXq0c/eeut4Jv74cnGk2/p0o64dSO0sVTkIGwTdbcyWgadhRbCLi3lBpCda+VxEW3C5OetXC27BnXRwCVMBbcht4D9zcBj0dho412DjvztLQDsCnFnAnZYYcN71iB+mSDuvACItnDagoKsV39jkHmCKNcID2dbvlXxu7uzeIW8u8jjA5GCtftVF5FpDcj9xqP1fZUTGE/n0F6RCNgz08zjyaymXGJMuonlRXtO3i2jAW7V0TxiSGaskPPM/N7LvXbDqE2MA0mscsog6zgTD+2tdAg5vDY7HYKm8ul6CKfD/wjLsj0RRdmmftkPy3VPHdQwOtjb00NoFAXEV1xu+tgkQ1mXFZ5zV65XYySDpRqSTuSfaNGXcGZb+dz7UL1CpH+JMlM0dCltjzqWoMxk70aDblYqKMrY2m9+MUODjWBCAvOHmFIHcAh4d1ZQWa9a6W7hjgyx6VH0k2/eIRdANi3p/3IDJdUTGGgKHQHcQPpGyQ5VPesdCLYj05GWoWIkp8LQ2WsuAXXV9QQ4nBKylXboWcsaJ7yk7Alv0aaFsVFwDULS8s+ih8CIGCzTQdAcyrHtXAe09gOxsTGkYpgxLoWiM5DWhm2R9a6tEDgRp1gL72uMgzJ+T2x0NQWifCIgITBQk5bvx0PazQJaqEkc8JME3u472YK4K1axDhZiFm0NG5VTa+WtKTWaZWmKFHfgQhq2OoTtU4e/JaDI4EjBOdxrLBIOG3BXtiz7Vuzo2tldO4B8ZITmpb20F6QzbH2TnVK0wCSeU0WjrYd9ZjdMgiKoDdfTlRFrD5SHP5Or4J/QrmHm7uox4DaG1DgMhwUgxQAUdmxsjyNQ7mYkSsg8+Fsh+la3l/zqayze7Fle3GcaCtWWR5zth61H9TDZIDwag7EpTK7zvxwKEEWMSveRURBEPlR7UfKxBD8F3/gJqVYnk6r1AT+RFYrgdW3Sn44KrQ8yrpWOC5MSXcfzPpA7p07rhOPcLs95QRx/PpPnObkkmdpNc95i3hcgvreRPwWeoKke4QwhCdME+wnd/w3b3UAl0Vn3xNsGSaLXX+0syDQ3xU60GJaWybPeQcex/joy0wAhjsY6xtJYiBoH3fXmXgAlIcskgX6otIO7uprzZpqGev5wi6BWdBZpDaInQZvL7e4IbV+BzPqSY/fVNmT+7J+Eg6cvPXCZIoKPC6k8mPoqkJsT6rrFtLibob0yCoC0QIaGe7glwghXK0ntkXcNMvNkTi7u0CPDuFhbXwYpIqwUgLLtsmD0UT0QoWzwEkG3BwmTt0EVLhZ6aoh4At64reHlSDztJFp1AUMWqFIdE7PIEpJVyPDC6TatCvjUL6bDOWNrvQBW7Crh8SqBbJXZMbaklXQtsBALGsmeLqIYeWnl3uk6UNKZVslqynvHFeeboK4SWBsBRXNavEZ3cg3s6FQD5Qw+msZtqq8+1AaghLveLVrzf197cYyRymfcvyyFVUPAhVkdFNqHkOhKcZRvAr+lut6T6ko+Qqs8sVgglFq0dEdjwCBVI2H3IEhzC9X7eO4GIe5eqhJKbxkjNfmF2kCidMflmpSgg9lfXjhYpuLLGjkFGHPjg/HG/fkwX+pqbF0fCiSJ3zglRhaE43XVXnrgffrw9GTl/pRA8ZWw3QXR22NkuqBgp7/40RQIqgGyWRgiE+voC2WYNaym4mlG+DZAyfRWMpJo1eevSzYlVcgYrmNwHFOlXuujU3VGb15POHhPyVT63W09fo84l4f6nlPgh2dj8CQvw9bHdXEZm+UlfmZo8CfnRrdIckz3zBwNxAoUi0COBQl/H1WCUcVSJL+sWjIQ2eERA/Ys9D2UDWNHr4CLurpPD8rGFbq1R2/qPW/2tKiXm7YlYCNMqUfDTzwuKeaTu3cNE4W882qu4Wo37733BomLjZxBT2cXlnvwcHFs2z7bLnJg++QcFsAl9NpBiELxnlxNFvhDn9XJOt1+xu2o1ebq5f0N4lnPdnrxCJ8wMeEa+ruruFY1fPpuhJ3sPqKk/7QB5QCjO/xrKVXCaGy+LrUmX+h3HluumtlZN/vkk7fVtUF+uxvIeJV5Vld"}}
9.      2021-07-28 11:08:10 +0900 JST:  [event;sealing.SectorCommitSubmitted]   {"User":{"Message":{"/":"bafy2bzacecf77k6omzzn2unmxrnp36dgk6b6qskxvkbzgvssdllolx6qf7fcg"}}}
10.     2021-07-28 11:11:30 +0900 JST:  [event;sealing.SectorProving]   {"User":{}}
11.     2021-07-28 11:14:51 +0900 JST:  [event;sealing.SectorFinalized] {"User":{}}
12.     2023-09-18 16:50:03 +0900 JST:  [event;sealing.SectorTerminate] {"User":{}}
13.     2023-09-18 17:55:07 +0900 JST:  [event;sealing.SectorTerminate] {"User":{}}
14.     2023-09-18 17:55:07 +0900 JST:  [event;sealing.SectorTerminating]       {"User":{"Message":{"/":"bafy2bzaceawvjxcnb74x3d37t5ffl4bkt74jgiubxr6awsmxjehsz7bdto5w2"}}}

### Logging Information

```text
How can I remove this sector?
```

**Comment by rjan90** [comment]
Hey @Andrew-wwj! The message on-chain looks good, so your sector should be terminated and not accounted for on-chain! 

I guess the issue here is that it stays in the Terminating-state locally (i.e for example in your `lotus-miner sectors list` output)? Have you by any chance compacted your chain after you sent the termination message?

**Comment by beck-8** [comment]
I remember that after terminating, you need to wait for 900 heights before it becomes removed.
So, you look at the status after 900 height. If this is still the case, you can perform the deletion manually.

**Comment by Andrew-wwj** [comment]
@beck-8 @rjan90 Thanks!!!
