### ISSUE TITLE
nv21 integration and testing

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#11284]
We are preparing to ship Filecoin nv21 on November 7th. Other key dates include:

- First Lotus RC needs to go out on October 3rd
- Calibration test network upgrades on October 19th

In order to prepare for the first Lotus RC, we need to:
- [x] Re-review and test the migration in go-state-types
  - This is a lot simpler now as a result of DDO being descoped, but still a substantial migration
- [x] Reset the butterfly testnet to nv20, have it upgrade to nv21, and perform basic testing
- [x] Land any outstanding work for accepted FIPs in built-in actors and FVM
- [x] Redo the butterfly testnet reset with final code
- [x] Cut RCs for the FVM and built-in actors
- [x] Package it all in Lotus

**Comment by TippyFlitsUK** [comment]
Current testing plan/progress of 32GiB sectors on the Butterfly-network:

### **32GiB sector sizes:**

- [ ]  Seal a SynthPoRep-sector with the builtin-worker on the Lotus-Miner
    - [ ]  Confirm reduction in cache between PreCommit and ProveCommit
- [ ]  Seal a SynthPoRep-sector with a lotus-worker
    - [ ]  Confirm reduction in cache between PreCommit and ProveCommit
- [ ]  Pledge a CC-sector using SynthPoRep
    - [ ]  Let one sector fail WindowPoSt and check that it successfully recovers
- [ ] Extend a sector sealed with SynthPoRep ❌ 
- [ ]  Pledge a deal-sector using SynthPoRep
    - [ ]  Verified deal
        - [ ]  Let one sector fail WindowPoSt and check that it successfully recovers
    - [ ]  Unverified deal
        - [ ]  Let one sector fail WindowPoSt and check that it successfully recovers.
- [ ]  Snap a CC-sector sealed with SynthPoRep
- [ ]  Pass WindowPoSt with sectors sealed with SynthPoRep
    - [ ]  Fail a WindowPoSt with sectors sealed with SynthPoRe and check DeclareFaultsRecovered functions and successfully recovers.
- [ ]  Terminate sector(s) that was published with SynthPoRep
- [ ]  Compact partition(s) that includes sectors published with SynthPoRep
- [ ]  PreCommitBatch sectors with SynthPoRep:
    - [ ]  CC
    - [ ]  Unverified deals
    - [ ]  Verified deals
- [ ]  CommitAggregate sectors with SynthPoRep:
    - [ ]  CC
    - [ ]  Unverified deals
    - [ ]  Verified deals

**Comment by TippyFlitsUK** [comment]
# Calibration Testing

### **32GiB sector sizes:**

- [x]  Seal a SynthPoRep-sector with the builtin-worker on the Lotus-Miner
    - [x]  Confirm reduction in cache between PreCommit and ProveCommit
- [x]  Seal a SynthPoRep-sector with a lotus-worker
    - [x]  Confirm reduction in cache between PreCommit and ProveCommit
- [x]  Pledge a CC-sector using SynthPoRep
    - [x]  Let one sector fail WindowPoSt and check that it successfully recovers
- [x] Extend a sector sealed with SynthPoRep
- [x]  Pledge a deal-sector using SynthPoRep ❗ LEGACY
    - [x]  Verified deal ❗ LEGACY
        - [x]  Let one sector fail WindowPoSt and check that it successfully recovers
    - [x]  Unverified deal ❗ LEGACY
        - [x]  Let one sector fail WindowPoSt and check that it successfully recovers.
- [x]  Snap a CC-sector sealed with SynthPoRep
- [x]  Pass WindowPoSt with sectors sealed with SynthPoRep
    - [x]  Fail a WindowPoSt with sectors sealed with SynthPoRe and check DeclareFaultsRecovered functions and successfully recovers.
- [x]  Terminate sector(s) that was published with SynthPoRep
- [x]  Compact partition(s) that includes sectors published with SynthPoRep
- [x]  PreCommitBatch sectors with SynthPoRep:
    - [x]  CC
    - [x]  Unverified deals
    - [x]  Verified deals
- [x]  CommitAggregate sectors with SynthPoRep:
    - [x]  CC
    - [x]  Unverified deals
    - [x]  Verified deals
    
## Additional
- [x]  Environmental variables such as `PC2_32G_MAX_CONCURRENT=1` are being respected
- [x]  Commit a sector for 3.5y
- [x]  Commit a sector for 1.5y and immediately extend to 3.5y
- [ ] Propose 3.5 year deal ❌ - `ERROR: maximum deal duration is 1555200 blocks`
- [ ]  A deal can be made for just below 3.5y

**Comment by rjan90** [comment]
Closing as the nv21 upgrade has completed.
