### ISSUE TITLE
Lotus-Miner config:  window_post_enable = false

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11324]
## User Story
Users with a lotus-provider setup want the work to not fault due to a lotus-miner running concurrently. This disables that fault risk for windowpost. 

## Acceptance Criteria
A config exists to disable windowpost on the miner

### Deliverables
window_post_enable (defaulting to true) should be a valid config.

### Development
The config needs to disable the startup of windowpost work on the miner entirely. 

### Testing
window_post_enable=false should disable this functionality in the miner.

**Comment by rjan90** [comment]
Closing! As this setting is already in place
