### ISSUE TITLE
lotus-provider -- wdposttask (calculation) integration

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11322]
## User Story
Users want  a way to use harmonytask (lotus-provider) to run workloads in the minerV2 environment, starting with WdPost. This involves calculation and submission. This Github Task is for the calculation to be done. 

## Acceptance Criteria
lotus-provider starts and the wdPostTask works

### Deliverables
PR with lotus-provider starting a working windowpost harmonytask.

### Development
- [ ] Undo changes to Miner in WdPostTask PR while preserving harmonytask as a caller that can do the same thing
- [ ] Have lotus-provider provide all the basics needed to start WdPostTask & WdPostScheduler
- [ ] Add all Configuration to the database configuration system so that the task can be configured correctly. 

### Testing
Does windowPoSt's message get sent to the database when started from a lotus-provider?
NOTE: this will not send a message to the chain until the Submission task is done.

**Comment by magik6k** [comment]
PoSt is supported in curio for a few months now
