### ISSUE TITLE
network id's

### ISSUE THREAD

**Issue by Schwartz10** [filecoin-project/lotus#1138]
Wanted to leave a note somewhere that incorporating a "network_id" into Lotus could provide a few benefits:

- tx signatures could incorporate the network_id to guard against a cross-network (testnet/mainnet) replay attack (if people use their testnet wallets on mainnet).
- applications could query for the network_id to more easily provide testnet/mainnet support (right now we make a genesis block comparison for this information).

Please let me know if there is a more appropriate place for noting future features/ideas.

**Comment by terorie** [comment]
Limiting transactions to a single network is very common and the `network_id` is the simplest way. Let's do it right while we can and hardfork!
I would argue that the `Message` struct is the only right place to put the network ID (causing the CID to change).

**Comment by Schwartz10** [comment]
Related resources:

https://filecoinproject.slack.com/archives/CP50PPW2X/p1579091836331600

**Comment by jleni** [comment]
Because signatures are not applied to the bare tx but to a CID. The values in the CID prefix could be perfectly used for domain separation and a value in the prefix to work as chain id.
Maybe this is a good alternative solution that does not affect the current implementation.
If would be nice if CID prefixes for mainnet and testnet were different.

**Comment by whyrusleeping** [comment]
If you want to fork the network, its on you to add transaction replay protection. I'm not gonna go out of my way to make life easier for someone who wants to split the network.

**Comment by terorie** [comment]
@whyrusleeping I'm mostly worried about people that accidentally use testnet accounts on mainnet. But you have a point, together with the `mark-bad` command it would make forking stupidly easy.

https://github.com/filecoin-project/lotus/blob/5153f67a2ecbbc5d2c7bae7420fe933c21f8c418/cli/sync.go#L94-L96

**Comment by whyrusleeping** [comment]
Well, i've eaten my words and we added a version field to messages. Gonna close this now

**Comment by Schwartz10** [comment]
The Glif Wallet is planning on hosting a testnet and mainnet version in the near future, and we're trying to decide the best way to derive wallet accounts from a BIP39 seed on testnets. Personally, I'm used to my wallet being decoupled from the network (MetaMask is a valid example - it doesn't matter what network the user is connected to, the user will derive the same wallet addresses from the same seed phrase). However, EVM chains make use of a chain-id, which protects against replay attacks.

I'm wondering - if we default to the Filecoin [BIP44 Coin Type](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) (461) when deriving accounts from a BIP39 seed phrase, on testnet and mainnet, are we risking replay attacks on mainnet? Does the `version` field in the message get bumped incrementally, and refer to changes in data models? Or does it refer to the version of the network (and thus could be used to protect against replay attacks)? 

I looked at the [specs](https://spec.filecoin.io/#section-systems.filecoin_vm.message.message-syntax-validation), but couldn't locate this information there.

**Comment by mishmosh** [comment]
@jennijuju or @arajasek should be able to confirm if and how the version field was added.

**Comment by arajasek** [comment]
The version field in `Message` versions the `Message` (and not the network). The only version so far is 0.

I'm not a cryptoperson, but sounds like you would wanna mix in a network ID somewhere in there, yeah.
