### ISSUE TITLE
Lotus Provider Migrate tool

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11381]
## User Story
The SPs want an easy way to get started using lotus-provider. Today's setup is too complicated, so a tool (safe for every configuration) will help

## Acceptance Criteria
The tool (once known about from documentation) will provide a self-explanatory experience to enable a competent SP to get started with little other information. 

```[tasklist]
### Deliverables
- [ ] Lotus-Miner CLI command that will contact the server and complete the setup.
```

## Technical Breakdown
```[tasklist]
### Development
- [ ] CLI
- [ ] Miner API
- [ ] Config creation in the database
- [ ] Convenience: The remaining setup including the exact command switches needed to run lotus-provider.
```

```[tasklist]
### Testing
- [ ] Pretend you're an beginner SP employee 
- [ ] Presume the documentation points to this tool 
- [ ] Use the tool as a first-time migrator
- [ ] Try the resulting config = following command.
```

**Comment by rjan90** [comment]
Closing as completed by: https://github.com/filecoin-project/lotus/pull/11388.

The lotus-provider has a `lotus-provider config from-miner` cmd, to help aid in the migration process from Lotus-Miner --> Lotus-Provider. Completed by
