### ISSUE TITLE
Multi-Miner

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11393]
## User Story
Users want a simpler way to run lotus-provider with multiple miner IDs to simplify their setup.

## Acceptance Criteria
Multiple miner IDs should post window & winning posts with the correct control addresses

```[tasklist]
### Deliverables
- [ ] A config change to make it possible to have control addresses per miner id.
- [ ] Thorough config documentation and guide. 
```

## Technical Breakdown
```[tasklist]
### Development

```

```[tasklist]
### Testing
- [ ] Verify multiple miner id's sectors post.
```

**Comment by magik6k** [comment]
Curio can do this now
