### ISSUE TITLE
Architecture and Dev docs

### ISSUE THREAD

**Issue by snadrus** [filecoin-project/lotus#11390]
## User Story
Those developing & understanding Lotus would like a concise description of important moving parts of the new HA infrastructur.

## Acceptance Criteria
An overview with images and code links to detailed function signatures. 

```[tasklist]
### Deliverables
- [ ] GitBook description sufficient enough to understand the High Availability design
- [ ] GitBook information on lotus-provider as it exists now: Design, Functionality
- [ ] Links back to a user-level Migration guide (not from this ticket)
- [ ] Understandable concepts with images
- [ ] Code pointers for deep-dive

```

## Technical Breakdown
```[tasklist]
### Development

```

```[tasklist]
### Testing

```

**Comment by magik6k** [comment]
https://docs.curiostorage.org/ Exist now and should cover everything mentioned here
