### ISSUE TITLE
Build Lotus with Docker

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/lotus#1143]
It would be useful for some tests to have a simple `Dockerfile` to build lotus in a Docker container (for example to do the fuzz tests of https://github.com/filecoin-project/lotus/issues/1139). As I didn't find anyone in the repo (there might be in other infra repos I'm missing) I adapted the [Ubuntu build instructions](https://docs.lotu.sh/en+install-lotus-ubuntu) into `golang:latest`. As I'm not sure we would like to maintain this I leave it here as an issue (instead of submitting a PR) to have a second opinion (maybe from @travisperson) if there is a simpler or better way to code this.

```dockerfile
# Build as:
# ```
# docker build -t lotus-build .
# ```

FROM golang:latest

# From https://docs.lotu.sh/en+install-lotus-ubuntu.
# ==================================================

# Run
# ---
RUN apt-get update
RUN apt-get install -y mesa-opencl-icd ocl-icd-opencl-dev

# Build
# -----
RUN apt-get install -y software-properties-common # Easy way to have `add-apt-repository` and not expand it into lower level commands here.
RUN add-apt-repository ppa:longsleep/golang-backports
RUN apt-get update || true # FIXME: Ignore for now error `golang-backports/ubuntu focal Release does not have a Release file`.
RUN apt-get install -y  gcc git bzr jq pkg-config mesa-opencl-icd ocl-icd-opencl-dev
# (Removed `golang-go` from the original list, it otherwise installs `go1.11.6`.)

# Clone
# -----
RUN mkdir -p $GOPATH/src/github.com/filecoin-project
WORKDIR $GOPATH/src/github.com/filecoin-project
RUN git clone https://github.com/filecoin-project/lotus.git
WORKDIR $GOPATH/src/github.com/filecoin-project/lotus
# (FIXME: Can we do the above through `go get`? I'm having several errors if I try it, but might not be using the correct arguments.)

# Install
# -------
RUN make clean && make all
RUN make install
```

**Comment by terorie** [comment]
To make the image a bit lighter:

```dockerfile
FROM ubuntu:focal AS builder

RUN apt-get update
# Install Rust toolchain
RUN apt-get install -y rustc cargo
# Install Go toolchain
RUN apt-get install -y golang
# Install utilities
RUN apt-get install -y build-essential pkg-config curl jq git
# Install Mesa OpenCL
RUN apt-get install -y mesa-opencl-icd ocl-icd-opencl-dev

WORKDIR /app

# Fetch dependencies
ADD ./go.mod /app/go.mod
ADD ./extern/filecoin-ffi/go.mod /app/extern/filecoin-ffi/go.mod
RUN go mod download

# Build filecoin-ffi
ADD ./extern /app/extern
RUN cd /app/extern/filecoin-ffi ./install-filecoin

# Build app
ADD ./ /app
RUN FFI_BUILD_FROM_SOURCE=1 make debug

# Use light image
FROM ubuntu:focal
COPY --from=builder \
    /app/lotus \
    /app/lotus-seal-worker \
    /app/lotus-seed \
    /app/lotus-storage-miner \
    /usr/bin/
COPY --from=builder /usr/lib/x86_64-linux-gnu/libOpenCL.so* /usr/lib/
ENTRYPOINT /usr/bin/lotus
```

**Comment by eshon** [comment]
@schomatis - there are some additional Dockers mentioned here: https://github.com/filecoin-project/lotus/pull/745

@terorie - if you Dockerize the local Devnet script please also add a link or make a PR and we'll organize them all somewhere eventually or add to the lotus Docs

**Comment by schomatis** [comment]
Thanks @eshon, should have payed more attention to old issues, closing this one then.

**Comment by eshon** [comment]
I will try to make a PR of moving some of those Docker examples into the tools directory, to improve findability

**Comment by cgwyx** [comment]
FROM archlinux:latest

RUN pacman -Syu --noconfirm opencl-icd-loader &&\
    pacman -Syu --noconfirm go gcc git bzr jq pkg-config opencl-icd-loader opencl-headers base-devel

RUN git clone https://github.com/filecoin-project/lotus.git &&\
    cd lotus &&\
    make clean all &&\
    make install &&\
    make build bench

VOLUME ["/home","/root","/var"]


# API port
EXPOSE 1234/tcp

# P2P port
EXPOSE 1235/tcp

# API port
EXPOSE 2345/tcp

ENV IPFS_GATEWAY=https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/

WORKDIR /lotus

#ENTRYPOINT ["./lotus", "daemon", "&"]

CMD ["./lotus", "daemon", "&"]

**Comment by cgwyx** [comment]
FROM archlinux:latest

RUN pacman -Syu --noconfirm opencl-icd-loader &&\
    pacman -Syu --noconfirm go gcc git bzr jq pkg-config opencl-icd-loader opencl-headers base-devel

RUN git clone https://github.com/filecoin-project/lotus.git &&\
    cd lotus &&\
    make clean all &&\
    make install &&\
    make build bench

VOLUME ["/home","/root","/var"]


# API port
EXPOSE 1234/tcp

# P2P port
EXPOSE 1235/tcp

# API port
EXPOSE 2345/tcp

ENV IPFS_GATEWAY=https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/

WORKDIR /lotus

#ENTRYPOINT ["./lotus", "daemon", "&"]

CMD ["./lotus", "daemon", "&"]

**Comment by eshon** [comment]
Hi @cgwyx, 

You could create a PR for this docker to the lotus [community docker examples directory](https://github.com/filecoin-project/lotus/tree/master/tools/dockers/docker-examples) and label your directory `basic-miner-arch`.

**Comment by panyang1217** [comment]
did you encounter errors when using lotus in docker with gpu? I got one about "GPU Accelerator is disabled!" with nvidia-docker runtime.

**Comment by cgwyx** [comment]
https://hub.docker.com/r/cgwyx/lotusfilecoin,用这个镜像吧，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "panyang1217"<notifications@github.com&gt;; 
发送时间: 2021年2月4日(星期四) 下午3:13
收件人: "filecoin-project/lotus"<lotus@noreply.github.com&gt;; 
抄送: "尾生"<512543469@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [filecoin-project/lotus] [Duplicate - Ignore] Build Lotus with Docker (#1143)





 
did you encounter errors when using lotus in docker with gpu? I got one about "GPU Accelerator is disabled!" with nvidia-docker runtime.

**Comment by panyang1217** [comment]
@cgwyx 我用这个镜像也是报同样的错误，我的配置是如下：
Ubuntu 20.04
GPU：RTX 3090
Driver：NVIDIA-Linux-x86_64-455.45.01
Docker：20.10.3
nvidia-container-toolkit：1.4.0-1
nvidia-container-runtime：3.4.1-1

**Comment by cgwyx** [comment]
又更新了一下，你再试一下

https://hub.docker.com/repository/docker/cgwyx/lotusfilecoin/tags?page=1&amp;ordering=last_updated

docker pull cgwyx/lotusfilecoin:opencl

docker run -d --restart=always --name lotusdocker --gpus all --net host --privileged \
-e BELLMAN_CUSTOM_GPU="GeForce GTX 1660:1408" \
-v /media/p300/lotusmaster/:/root/ -v /media/p300/lotusv28/:/var/tmp/ \
cgwyx/lotusfilecoin:opencl




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/lotus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月5日(星期五) 中午12:41
收件人:&nbsp;"filecoin-project/lotus"<lotus@noreply.github.com&gt;;
抄送:&nbsp;"尾生"<512543469@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [filecoin-project/lotus] [Duplicate - Ignore] Build Lotus with Docker (#1143)





 
@cgwyx 我用这个镜像也是报同样的错误，我的配置是如下：
 Ubuntu 20.04
 GPU：RTX 3090
 Driver：NVIDIA-Linux-x86_64-455.45.01
 Docker：20.10.3
 nvidia-container-toolkit：1.4.0-1
 nvidia-container-runtime：3.4.1-1
