### ISSUE TITLE
No safe concurrency for the expanding field of peer manager

### ISSUE THREAD

**Issue by nikkolasg** [filecoin-project/lotus#1144]
Lotus should use a lock to read / write the field `expanding` of the peer manager, because it is [read](https://github.com/filecoin-project/lotus/blob/master/peermgr/peermgr.go#L128) and [written](https://github.com/filecoin-project/lotus/blob/master/peermgr/peermgr.go#L134) in two different go routines.

**Comment by magik6k** [comment]
Not sure how the code looked at the time, but looking at current master it looks correct
