### ISSUE TITLE
Parallelize GeneratePieceCommitment

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#1156]
This will make the initial phase of pledging sector quite a bit faster. May also alow us to not have to put the entire thing in TMPDIR

**Comment by free1139** [comment]
Maybe it needs to work with remote worker. It needs CPU to calculate the commP

**Comment by magik6k** [comment]
Unless you gave 100G networking, or something exotic like some pcie ntb setup, it's probably not worth the effort, this part is definetly not a bottleneck unless you have 100s of seal workers in operation
