### ISSUE TITLE
LedgerHID device (idx 0) not found

### ISSUE THREAD

**Issue by yichang3** [filecoin-project/lotus#11571]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [x] Other

### Lotus Version

```text
lotus version 1.25.0-rc5+mainnet+git.44c27f7ea
lotus-miner version 1.25.0-rc5+mainnet+git.44c27f7ea
```

### Repro Steps

[3372704.673493] usb 3-2.1: new full-speed USB device number 8 using xhci_hcd
[3372704.804586] usb 3-2.1: New USB device found, idVendor=2c97, idProduct=5011, bcdDevice= 2.01
[3372704.804594] usb 3-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[3372704.804597] usb 3-2.1: Product: Nano S Plus
[3372704.804601] usb 3-2.1: Manufacturer: Ledger
[3372704.804603] usb 3-2.1: SerialNumber: 0001
[3372704.981011] hid-generic 0003:2C97:5011.0004: hiddev0,hidraw0: USB HID v1.11 Device [Ledger Nano S Plus] on usb-0000:23:00.3-2.1/input0

root@01:/# lotus wallet new secp256k1-ledger
ERROR: finding ledger: LedgerHID device (idx 0) not found

### Describe the Bug

root@01:/# lotus wallet new secp256k1-ledger
ERROR: finding ledger: LedgerHID device (idx 0) not found

### Logging Information

```text
root@01:/# lotus wallet new secp256k1-ledger
ERROR: finding ledger: LedgerHID device (idx 0) not found
```

**Comment by yichang3** [comment]
ledger status : 
![pic](https://github.com/filecoin-project/lotus/assets/114650201/fe7977b5-720f-4c7a-a9d9-3cdb1d038f93)

**Comment by yichang3** [comment]
lotus config : 
![image](https://github.com/filecoin-project/lotus/assets/114650201/64933baa-638f-4bd1-a1aa-46df527214c8)

**Comment by rjan90** [comment]
Hey @yichang3! The issue of getting `LedgerHID device (idx 0) not found` should now have been dealt with, as https://github.com/filecoin-project/lotus/pull/11651 has been merged. Its currently in the master branch.
