### ISSUE TITLE
Default value for `lotus-miner sectors extend`'s `--extension` flag

### ISSUE THREAD

**Issue by dd45e640b42e6da7da96faee3996ef7c** [filecoin-project/lotus#11575]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [x] Other

### Lotus Version

```text
v1.25.1
```

### Repro Steps
---

### Describe the Bug

`lotus-miner sectors extend`'s `--extension` flag defaults to 1555200 - the pre nv21 max sector lifetime. with nv21 the max lifetime of sectors changed. 

it should be considered to change the default value of the flag to the new max. lifetime to have previous behavior restored.

this can and does cause confusion/problems when uncarefully extending sectors post nv21 (especially when doing snap deals)

### Logging Information

---

**Comment by TippyFlitsUK** [comment]
https://filecoinproject.slack.com/archives/CP50PPW2X/p1705229863466399
