### ISSUE TITLE
Index Actor Events by ID

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#11594]
Currently, we index actor events by the emitter's f4 address. This will have to change in https://github.com/filecoin-project/lotus/pull/11540 to accommodate non-EVM actors, but really, we simply shouldn't be resolving addresses when we index events.

Instead:

1. We should record the ID in the index (resolve nothing). The ActorID plus the tipset is the "canonical" identifier for the actor.
2. When querying for events, resolve addresses to IDs using the latest tipset, then query. As long as we limit ourselves to querying for non-reverted events, there shouldn't be any issue of ID reuse.
3. When subscribing, we'll have to resolve the filter's addresses to IDs at every tipset.

Unlike the current system, this will work correctly with _every_ address type, will result in more performant indexing, and will reduce the size of the database.

Unfortunately, the correct way to do this involves a migration.

**Comment by masih** [comment]
@rvagg if you haven't started working on this, I might as well take this one too considering I am working on https://github.com/filecoin-project/lotus/issues/11640 ?

**Comment by rvagg** [comment]
@masih I had a look at my code and it wasn't quite as terrible as I imagined. I've tidied it up a little and made it all pass with the latest v1.26 @ https://github.com/filecoin-project/lotus/pull/11694. It's just a draft and shouldn't necessarily be _the_ way this ticket gets done. I have some other things to get done in the meantime so I've removed myself from assignee here but could come back to this if you don't happen to get to it in the course of what you're working on. I started looking at the migration problem but didn't get too far. I really want good tests for migrations and there are none in there yet.

**Comment by masih** [comment]
@Stebalien Question: What is the correct thing to do when migrating the reverted events `emitter_addr`? We can't resolve those address to actor IDs right? Which means some default value for emitter, e.g. `0` for events that cannot be migrated?

**Comment by Stebalien** [comment]
>  We can't resolve those address to actor IDs right?

1. Reverted events exist in reverted tipsets. If we still have the tipset, we _should_ be able to resolve the addresses relative to those tipsets.
2. It might just be faster to re-index from the events in the receipts.

But, honestly, I'd just delete the reverted events from the database in this case. I'm not quite sure why we record them anyways given that, unless I'm mistaken, we only _return_ reverted events from the "subscribe" API. I guess we should add "remove reverted events from the database" to the TODO list...

**Comment by masih** [comment]
> remove reverted events from the database

Since we are iterating over the events as part of the migration for this issue anyway, I can add reverted event removal right there. It should be straightforward

**Comment by masih** [comment]
On second thought, the event collection also needs to be updated to remove storing reverted events. This is a big-ish enough work to make a reasonable size PR on its own. Let's do that in a separate PR.

**Comment by jennijuju** [comment]
@aarshkshah1992 was this address in the new chainindexer api by any chance?

**Comment by rvagg** [comment]
Having some discussion in https://github.com/filecoin-project/lotus/pull/12421/files#r1756198386, but because GitHub's linking into inline comments in PRs is kind of impermanent and often doesn't take you to a discussion, here's a screenshot:

<img width="793" alt="Screenshot 2024-10-08 at 1 01 15 PM" src="https://github.com/user-attachments/assets/16ec0063-ded4-44c1-a2f6-a7bb20f61eba">

I would like a resolution on this one and am concerned about going forward without it in ChainIndexer **if** we believe this is the right way ahead. I'm just not sure now that it is the right thing to do.

**Comment by rvagg** [comment]
Being closed finally in #12421 by storing both the actor id and the `DelegatedAddress` if there is one and then querying as such.

**Comment by rjan90** [comment]
Closing this issue since the new chainIndexer has been merged and shipped.
