### ISSUE TITLE
FIP-0074: CLI to invoke the new SettleDealPayments method

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#11590]
SPs will now need to invoke this method in order to settle deal payment. The lotus-miner should expose functionality to do so.

This method will be similar to, and should be placed alongside, the existing `actorWithdrawCmd` ([here](https://github.com/filecoin-project/lotus/blob/e6dc720224e6fdf99e2fe88d101b4e829af8363d/cmd/lotus-miner/actor.go#L243)), which performs a similar operation.

**Comment by jennijuju** [comment]
needs https://github.com/filecoin-project/go-state-types/issues/239

**Comment by LexLuthr** [comment]
@arajasek @jennijuju Can you please confirm if there is an existing idea about how to create the bitfield for the params? I am just trying to figure out which deals to include in params. I can filter out based on provider but how do I ensure that I am not including the deals which are not going to result in anything and just waste the gas. Or is my assumption about the waste of gas wrong here?

**Comment by ZenGround0** [comment]
@LexLuthr are you still planning to work on this?

I would included two levels of granularity.  First just filter by provider id.  The gas costs shouldn't be significant in the common case.  Second users can provide a list of deal ids if they really want fine grained control.

**Comment by LexLuthr** [comment]
@ZenGround0 I won't be able to work on this at this time.

**Comment by akaladarshi** [comment]
Hey @rjan90
Can I work on this?

**Comment by rjan90** [comment]
Hey @akaladarshi,

Feel free to take this on. If you have any questions or need guidance, don't hesitate to ask here on GitHub or in the #fil-lotus-dev channel on Filecoin Slack.

**Comment by akaladarshi** [comment]
Hey @rjan90,

Hey @Phi-rjan,
I have raised a draft PR for now.
Please review it and let me know if this is the correct implementation.

I am little bit confused about payments for the deal, it was mentioned in `FIP-0074` that the gas fee will be paid by the invoker of the function.
