### ISSUE TITLE
./lotus-provider' 调用 stat 失败: 没有那个文件或目录

### ISSUE THREAD

**Issue by iamhuoge** [filecoin-project/lotus#11610]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
v1.25.2
```

### Repro Steps

1. Run 'sudo make install'
3. See error 
'install -C ./lotus /usr/local/bin/lotus
install -C ./lotus-miner /usr/local/bin/lotus-miner
install -C ./lotus-worker /usr/local/bin/lotus-worker
install -C ./lotus-provider /usr/local/bin/lotus-provider
install: 对 './lotus-provider' 调用 stat 失败: 没有那个文件或目录
make: *** [Makefile:142：install-provider] 错误 1
'
...

### Describe the Bug

1. Run 'sudo make install'
3. See error 
'install -C ./lotus /usr/local/bin/lotus
install -C ./lotus-miner /usr/local/bin/lotus-miner
install -C ./lotus-worker /usr/local/bin/lotus-worker
install -C ./lotus-provider /usr/local/bin/lotus-provider
install: 对 './lotus-provider' 调用 stat 失败: 没有那个文件或目录
make: *** [Makefile:142：install-provider] 错误 1

### Logging Information

```text
1. Run 'sudo make install'
3. See error 
'install -C ./lotus /usr/local/bin/lotus
install -C ./lotus-miner /usr/local/bin/lotus-miner
install -C ./lotus-worker /usr/local/bin/lotus-worker
install -C ./lotus-provider /usr/local/bin/lotus-provider
install: 对 './lotus-provider' 调用 stat 失败: 没有那个文件或目录
make: *** [Makefile:142：install-provider] 错误 1
```

**Comment by magik6k** [comment]
Did you run `make build` before make install or `make all`.

If you run `make build` the problem probably is that the build step is missing lotus-provider dependency

https://github.com/filecoin-project/lotus/blob/95fb198597b8d996b396281da8c975f5c9c858b6/Makefile#L127

If you want to work around the issue you can just run
```
make all
sudo make install
```

**Comment by rjan90** [comment]
Fixed by: https://github.com/filecoin-project/lotus/pull/11616
