### ISSUE TITLE
eth_getTransactionReceipt JSON RPC API returns `#{tx_hash} into an Eth Receipt: failed to parse contract creation result: EOF`

### ISSUE THREAD

**Issue by vbaranov** [filecoin-project/lotus#11622]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
\Daemon:  1.25.2+mainnet+git.f51f83bfe+api1.5.0
Local: lotus version 1.25.2+mainnet+git.f51f83bfe
```

### Repro Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

### Describe the Bug

Note: we run Lotus node for Filecoin Mainnet in the archive mode.

`eth_getTransactionReceipt` JSON RPC API method on FEVM returns `#{tx_hash} into an Eth Receipt: failed to parse contract creation result: EOF` for some transaction hashes.

```
curl -s -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getTransactionReceipt", "params": ["0xe0a9b4e0cb84e6cbf966771f7a74a9336d707130ba859a0fb6c5d452c1895c38"],"id":1,"jsonrpc":"2.0"}' http://localhost:1234/rpc/v1

{"jsonrpc":"2.0","id":1,"error":{"code":1,"message":"failed to convert 0xe0a9b4e0cb84e6cbf966771f7a74a9336d707130ba859a0fb6c5d452c1895c38 into an Eth Receipt: failed to parse contract creation result: EOF"}}
```

At the same time transaction with this hash is included into block:
```
curl -s -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getBlockByHash", "params": ["0xc4ce9cd85b497ef3c03e8ee977c75c5654fe9c8c02939193003105646ce2319c", false],"id":1,"jsonrpc":"2.0"}' http://localhost:1234/rpc/v1 | jq .result.transactions | grep 0xe0a9b4e0cb84e6cbf966771f7a74a9336d707130ba859a0fb6c5d452c1895c38

  "0xe0a9b4e0cb84e6cbf966771f7a74a9336d707130ba859a0fb6c5d452c1895c38",
```

### Logging Information

```text
What exact logs do you need for this specific problem? Please guide me to the right direction how to get those.
```

**Comment by rvagg** [comment]
@vbaranov could you give me the output of this please? `curl -s -X POST -H "Content-Type: application/json" --data '{"method":"Filecoin.EthGetMessageCidByTransactionHash","params":["0xe0a9b4e0cb84e6cbf966771f7a74a9336d707130ba859a0fb6c5d452c1895c38"],"id":1,"jsonrpc":"2.0"}' http://localhost:1234/rpc/v1`

**Comment by vbaranov** [comment]
> @vbaranov could you give me the output of this please? `curl -s -X POST -H "Content-Type: application/json" --data '{"method":"Filecoin.EthGetMessageCidByTransactionHash","params":["0xe0a9b4e0cb84e6cbf966771f7a74a9336d707130ba859a0fb6c5d452c1895c38"],"id":1,"jsonrpc":"2.0"}' http://localhost:1234/rpc/v1`

Sure,
```
{"jsonrpc":"2.0","result":{"/":"bafy2bzacedqktnhazocons7zmz3r66tuvezw24drgc5ilgqpw3c5iuwbrfodq"},"id":1}
```

**Comment by Stebalien** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/11609.
