### ISSUE TITLE
Record processed epochs / tipsets in events index

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/lotus#11640]
Arising out of https://github.com/filecoin-project/lotus/pull/11618 - Lotus currently has no way to know whether the earliest events it has are the earliest there are or the earliest that that have been recorded. Ideally requesting "events from height X" should error if we can say for sure "I don't have events for that height", but that's not possible today because we don't know.

* [ ] Add a minor migration to the event index database with a new table to record "height" once it's been fully processed, the migration could either walk back through indexed events and mark those as done, or to be more comprehensive, walk back through the message receipts and mark them off?
* [ ] Error on the `GetActorEvents` and `SubscribeActorEvents` APIs if you request a height that's earlier than we have.

**Comment by Stebalien** [comment]
In terms of the migration... I believe that checking if we have _any_ events at a tipset is relatively inexpensive, and we only need to do that for tipsets that don't have recorded events.

**Comment by jennijuju** [comment]
@Stebalien iirc we want this for the message index too, is that right (when we were discussing tracing api)?

**Comment by Stebalien** [comment]
Yes.

**Comment by masih** [comment]
@rvagg please feel free to assign me other issues that relate to this, considering the need for migration. That should reduce the need for coordination.

Thanks
