### ISSUE TITLE
why my miner's power is 0 ?

### ISSUE THREAD

**Issue by taoyonggang** [filecoin-project/lotus#1165]
**Describe the bug**
My miner's power is 0, why?

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**
lastet.

**Additional context**
Miner: t017111
Sector Size: 32 GiB
Power: 0 B / 1.87 PiB (0.0000%)
Committed: 544 GiB
Proving: 544 GiB
Worker use:
Local: 0 / 4 (+1 reserved)
Remote: 0 / 0
Queues:
AddPiece: 0
PreCommit: 0
Commit: 0
Unseal: 0
PoSt Submissions:
Previous: Epoch 17614 (9973 block(s), ~7479m 45s ago)
Fallback: Epoch 17644 (in 10003 blocks, ~7502m 15s)
Deadline: Epoch 17814 (in 10173 blocks, ~7629m 45s)
Sectors: map[Proving:17 Total:17]

**Comment by taoyonggang** [comment]
lotus-storage-miner version 0.2.6+git2841edfb

**Comment by taoyonggang** [comment]
tao@tao-ipfs:/data/lotusstorage$ lotus-storage-miner sectors list
1: Proving   sSet: YES pSet: YES tktH: 16048 seedH: 16798 deals: [200151]
2: Proving   sSet: YES pSet: YES tktH: 16299 seedH: 16926 deals: [204251]
3: Proving   sSet: YES pSet: YES tktH: 17448 seedH: 18008 deals: [217744]
4: Proving   sSet: YES pSet: YES tktH: 17955 seedH: 18474 deals: [222028]
5: Proving   sSet: YES pSet: YES tktH: 19445 seedH: 19925 deals: [228668]
6: Proving   sSet: YES pSet: YES tktH: 20051 seedH: 20539 deals: [231437]
7: Proving   sSet: YES pSet: YES tktH: 20529 seedH: 21282 deals: [236175]
8: Proving   sSet: YES pSet: YES tktH: 20861 seedH: 21432 deals: [243551]
9: Proving   sSet: YES pSet: YES tktH: 21922 seedH: 22817 deals: [254789]
10: Proving  sSet: YES pSet: YES tktH: 21922 seedH: 22874 deals: [254790]
11: Proving  sSet: YES pSet: YES tktH: 23436 seedH: 24713 deals: [264071]
12: Proving  sSet: YES pSet: YES tktH: 23436 seedH: 24371 deals: [264072]
13: Proving  sSet: YES pSet: YES tktH: 24150 seedH: 24883 deals: [264580]
14: Proving  sSet: YES pSet: YES tktH: 24838 seedH: 25572 deals: [273433]
15: Proving  sSet: YES pSet: YES tktH: 25819 seedH: 26345 deals: [276757]
16: Proving  sSet: YES pSet: YES tktH: 26335 seedH: 27242 deals: [286936]
17: Proving  sSet: YES pSet: YES tktH: 26335 seedH: 27207 deals: [286935]
18: Unsealed sSet: NO  pSet: NO  tktH: 0     seedH: 0     deals: [302163]
19: Unsealed sSet: NO  pSet: NO  tktH: 0     seedH: 0     deals: [302164]

**Comment by travisperson** [comment]
I believe your miner needs to submit I fallback post before the power will come online. I don't think there is a way to manually trigger this yet. The general advice is to restart your `lotus-storage-miner` process which should trigger a fallback post shortly after.

**Comment by taoyonggang** [comment]
I am ok. It's seem that Fil too low.
Now it is good.But the cache is too large.I have delete them.  So the power is also 0.

**Comment by binarier** [comment]
same here:
```
Miner: t017418
Sector Size: 32 GiB
Power: 0 B / 340 TiB (0.0000%)
	Committed: 832 GiB
	Proving: 832 GiB
Worker use:
	Local: 0 / 4 (+1 reserved)
	Remote: 0 / 0
Queues:
	AddPiece: 0
	PreCommit: 0
	Commit: 0
	Unseal: 0
PoSt Submissions:
	Previous: Epoch 29302 (5562 block(s), ~4171m 30s ago)
	Fallback: Epoch 29332 (in 5592 blocks, ~4194m 0s)
	Deadline: Epoch 29502 (in 5762 blocks, ~4321m 30s)
Sectors:  map[CommitFailed:1 Proving:26 Total:27]
```

**Comment by mostcute** [comment]
![4514b26a1a45eecbfb3fad25caccc37](https://user-images.githubusercontent.com/23225426/73814205-5412ef80-481d-11ea-9490-41d550aa9397.png)
i don't know why my Proving count not equal Commited count in a long time. any problem in PoST submissions on my node?

**Comment by magik6k** [comment]
This should be fixed in testnet/3
