### ISSUE TITLE
 command:lotus filplus list-claims, expiration time

### ISSUE THREAD

**Issue by nezha90** [filecoin-project/lotus#11669]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [x] Other

### Lotus Version

```text
latest
```

### Repro Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

### Describe the Bug

lotus/cli/filplus.go/382

```
for claimId, claim := range claimsMap {
			if ts.Height() > claim.TermMax || !cctx.IsSet("expired") {
				tw.Write(map[string]interface{}{
					"ID":        claimId,
					"Provider":  claim.Provider,
					"Client":    claim.Client,
					"Data":      claim.Data,
					"Size":      claim.Size,
					"TermMin":   claim.TermMin,
					"TermMax":   claim.TermMax,
					"TermStart": claim.TermStart,
					"Sector":    claim.Sector,
				})
			}
		}
```

The expiration time of claim should be TermMax + TermStart

### Logging Information

```text
None
```

**Comment by rvagg** [comment]
Looks right to me, seems like copypasta from the allocations expiration where it's an explicit epoch. @LexLuthr I don't suppose you'd like to tackle this since your head is in this code?

**Comment by LexLuthr** [comment]
@rvagg I will push the PR today.
