### ISSUE TITLE
Sealing tests

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#1169]
Something like a CircleCI pipeline that:
- preseals a sector
- creates genesis
- starts up a miner
- creates another miner
- sets up seal worker
- seals sector using seal worker
- include a deal

**Comment by whyrusleeping** [comment]
We would want this to use the `lotus-seed` and `lotus` binaries, right?

**Comment by jennijuju** [comment]
Might be stale, but these are good ideas to start with

**Comment by BigLep** [comment]
Can we also:
1. Add more commentary on how this relates to other tests that we have
2. Add comments on what we want to assert in the test(s)
3. Link it to https://github.com/protocol/web3-dev-team/pull/28 if they are related

**Comment by jennijuju** [comment]
> Might be stale, but these are good ideas to start with

Stale - Create a new issue with more details when see needed
