### ISSUE TITLE
lotus-miner panic when sealing

### ISSUE THREAD

**Issue by strahe** [filecoin-project/lotus#11706]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner version 1.26.0-rc2+calibnet+git.5c0694c8d
```

### Describe the Bug

![image](https://github.com/filecoin-project/lotus/assets/7932644/2fe25f04-0ceb-4002-9a3e-4bd7cd4c61ab)

When DealInfo is nil, getting EndEpoch will cause the lotus-miner to panic.

![image](https://github.com/filecoin-project/lotus/assets/7932644/dfc394d7-9276-41c2-a12b-cee1fd494378)

### Logging Information

```text
{"level":"debug","ts":"2024-03-11T18:50:00.616+0800","logger":"advmgr","caller":"sealer/sched_worker.go:458","msg":"assign worker sector 28500 (ready)"}
{"level":"debug","ts":"2024-03-11T18:50:00.616+0800","logger":"advmgr","caller":"sealer/sched_assigner_common.go:53","msg":"SCHED 5 queued; 4 open windows"}
{"level":"debug","ts":"2024-03-11T18:50:00.616+0800","logger":"advmgr","caller":"sealer/sched_resources.go:157","msg":"sched: not scheduling on worker 0a16f950-be6d-4ed7-bdb4-591b357ae5ce for startReady; at task limit tt=8:seal/v0/addpiece, curcount=map[]"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x23b9ced]

goroutine 1456317 [running]:
github.com/filecoin-project/lotus/storage/pipeline/piece.(*PieceDealInfo).isBuiltinMarketDeal(...)
        /root/lotus-sp/storage/pipeline/piece/piece_info.go:48
github.com/filecoin-project/lotus/storage/pipeline/piece.(*PieceDealInfo).EndEpoch(...)
        /root/lotus-sp/storage/pipeline/piece/piece_info.go:145
github.com/filecoin-project/lotus/storage/pipeline.(*SafeSectorPiece).EndEpoch(...)
        /root/lotus-sp/storage/pipeline/types.go:312
github.com/filecoin-project/lotus/storage/pipeline.(*Sealing).handleWaitDeals(_, {{_, _}, _}, {{0x53f59d7, 0x9}, 0x6f50, 0x8, 0x65eee033, {0xc0bba77740, ...}, ...})
        /root/lotus-sp/storage/pipeline/input.go:37 +0x12d
github.com/filecoin-project/lotus/storage/pipeline.(*Sealing).Plan.func1({{_, _}, _}, {{0x53f59d7, 0x9}, 0x6f50, 0x8, 0x65eee033, {0xc0bba77740, 0x3, ...}, ...})
        /root/lotus-sp/storage/pipeline/fsm.go:43 +0x76
reflect.Value.call({0x4db0840?, 0xc012e34f30?, 0x13?}, {0x53c3f43, 0x4}, {0xc0356daf98, 0x2, 0x2?})
```

**Comment by magik6k** [comment]
Did you use boost or something custom to accept / make the deal?

**Comment by strahe** [comment]
> Did you use boost or something custom to accept / make the deal?

yes, boost and offline deal.
