### ISSUE TITLE
Update image versions for Dockerfile

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/lotus#11705]
The Dockerfile seems to be using Golang 1.20 image and other such older images. We should update those to currently supported build versions.

**Comment by jennijuju** [comment]
do we wannt to keep supporting dockerfile? (do we own our docker file account now fil infra is no longer here..?

**Comment by LexLuthr** [comment]
Dockerfile is very important to allow building docker devnet. Even if Boost project retires, we should plan to keep docker devnet alive to allow for quick test turnaround times.

**Comment by snadrus** [comment]
Could you point us to docs where we could get the docker dev net running? And able to get patches? 
It would be a good thing for Curio docs to point to.

**Comment by jennijuju** [comment]
questions
- who owns the docker atm? i dont think anyone from Lotus team does today. 
- Whats docker devnet?
- Lets use this chance to discuss how it should look like when lotus client and SP stack is decoupled

**Comment by masih** [comment]
I use (and maintain) [this](https://github.com/filecoin-shipyard/lotus-containers) unofficial repo for lotus containers. It has containers published for devnet and mainnet separately. 

Please feel free to use (and contribute) to those containers until there is a clearer plan on docker image builds within Lotus repo.

**Comment by LexLuthr** [comment]
@jennijuju We can always build images locally within minutes as long as we have a Dockerfile. Boost devnet used the repo setup by Masih and it also allows building image locally for Lotus and Boost. 

https://github.com/filecoin-project/boost?tab=readme-ov-file#running-boost-devnet-in-docker-for-development for instructions.

**Comment by jennijuju** [comment]
seems like just need to backport https://github.com/filecoin-project/lotus/pull/11652/commits - @LexLuthr can you plz do it?
