### ISSUE TITLE
Add Actor Event APIs to gateway

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#11722]
as title

**Comment by arajasek** [comment]
@jennijuju sorry what needs to be done here? Which endpoints are we talking about?

**Comment by jennijuju** [comment]
@arajasek sorry ChainGetEvents & SubscribeActorEvents -> gateway api

**Comment by arajasek** [comment]
Gotcha, thanks. It looks like SubscribeActorEvents is already there, I'll add ChainGetEvents if it seems safe to do so.

**Comment by rjan90** [comment]
Closed by: https://github.com/filecoin-project/lotus/pull/11728
