### ISSUE TITLE
Gas used is more than gas limit for the block in FEVM RPC

### ISSUE THREAD

**Issue by eshon** [filecoin-project/lotus#11721]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus Ethereum RPC
- [ ] lotus FVM - Lotus FVM interactions
- [X] FEVM tooling
- [ ] Other

### Lotus Version

```text
v1.25.2
```

### Repro Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

### Describe the Bug

BlockScout is having this issue that leads to incorrect network utilization data in their explorer - from @vbaranov

How is this possible, that gas used is more than gas limit for the block?
```
curl -s -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x367D1C", false],"id":1}' https://api.node.glif.io/  | jq -r .result.gasLimit

0x2540be400

curl -s -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x367D1C", false],"id":1}' https://api.node.glif.io/  | jq -r .result.gasUsed
0x28a13aaf7
```
Is this JSON RPC bug or somehow possible? I am asking because we noticed, that network utilization sometimes exceeds 100% because of that when blocks are tightly packed with transactions.

### Tooling

```text
Standalone FEVM archival node
```

### Configuration Options

```text
FEVM index backfilling successfully completed
```

**Comment by Stebalien** [comment]
Bleh. That's because tipset gas varies based on the number of blocks, and that API is returning the max gas of one block.
