### ISSUE TITLE
Documentation: Miner's hard drive space is full and can't be expanded.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/lotus#1172]
# What questions need to be answered? 

Can I continue to exist in the worker miner's hard drive?
Can I run lotus on another disk than / on ubuntu?

```
export LOTUS_STORAGE_PATH=/storage/lotuswork/lotusstorage
export LOTUS_PATH=/storage/lotuswork/lotus
export WORKER_PATH=/storage/lotuswork/lotusworker
```

+ Add these lines to the setup instructions.
+ Consult @whyrusleeping and @travisperson on more details here

## Future

+ Configure additional drivers for your miner to seal sectors (cc: @whyrusleeping)

**Comment by travisperson** [comment]
At the moment I believe this is the only information available around how to manage disk storage for lotus binaries.

There is some additional work being done that should help move us towards being able to support expandable storage I believe. However, it's not available at the moment.

**Comment by magik6k** [comment]
We now have the `storage attach` command on both lotus-miner and lotus-worker
