### ISSUE TITLE
lotus-storage-miner init and fetch-params should use same sector size inputs

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#1174]
`fetch-params` was recently changed to use the `docker/go-units` package to allow for fetching proving params by specifying `32GiB` instead of the actual byte amount. 

Initializing a storage miner with the `sector-size` flag should be able to use the same input values as the `proving-params` flag from `fetch-params`

**Comment by laser** [comment]
This issue was resolved in commit #fa86359. I recommend closing this issue.
