### ISSUE TITLE
TestSectorImport is flaking a lot

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#11749]
Specifically, I'm seeing the c1-retry test fail to prove-commit: https://app.circleci.com/pipelines/github/filecoin-project/lotus/32944/workflows/62ec1203-5e0c-4c73-8baf-597215220aed/jobs/1175782/tests

This is concerning given all the DDO changes.

**Comment by rjan90** [comment]
Closing this ticket as outdated. Lotus has moved from CircleCI to GHA, and we are currently monitoring Flaky jobs over time in this [Grafana dashboard](https://ipdx.grafana.net/dashboard/snapshot/TfD5JfybgB0odLmipdZniNgayqr1zv3c?var-interval=1d&var-org=$__all&var-repo=$__all&var-branch=&var-workflow=&var-job=&var-label=&var-granularity=&var-limit=&from=now-7d&to=now).

We have also consolidated flaky test reports into a single tracking issue here: https://github.com/filecoin-project/lotus/issues/12001
