### ISSUE TITLE
<title>https://github.com/filecoin-project/community/issues/698#issue-2195399417

### ISSUE THREAD

**Issue by Liutauras68** [filecoin-project/lotus#11750]
## Acceptance Criteria

```[tasklist]
### Deliverables

```

## Technical Breakdown
```[tasklist]
### Development

```

```[tasklist]
### Testing

```

**Comment by rjan90** [comment]
Closing this ticket due to it being incomplete. The issue referenced in the title has also been moved to the Commuinty section, given that its a contract issue and not a Lotus issue. The FVM DX should be able to give concrete answers why you are seeing the failure you are seeing
