### ISSUE TITLE
Allocation failed with Actor error

### ISSUE THREAD

**Issue by Normalnoise** [filecoin-project/lotus#11792]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [X] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boost version 2.2.0-rc2+calibnet+git.e9a50bb
```

### Describe the Bug

when I used the boost allocate datacap, it failed

### Logging Information

```text
Error: GasEstimateMessageGas error: message execution failed: exit ErrIllegalState(20), reason: message failed with backtrace:
00: f07 (method 80475954) -- receiver hook error from Address { payload: ID(6) }: exit_code=ExitCode { value: 20 }, return_data=RawBytes {  } (20)
01: f06 (method 3726118371) -- failed to flush allocations table: ActorError(exit_code: ExitCode { value: 20 }, msg: put failed with NotFound) (20)
--> caused by: ipld::block_create -- block links to CID with forbidden codec 112 (6: resource not found)
 (RetCode=20)
```

### Repo Steps

```
boost allocate --miner=t081660 --piece-info=QmbSyXnZzRxjVKW7wr5zVwDgwwb6fsL4TMKxB2FbqcZWwk=1048576 --wallet=t132netha273l7d7iqjnp42zevf37syxe3i753u6y
```

````
Error: GasEstimateMessageGas error: message execution failed: exit ErrIllegalState(20), reason: message failed with backtrace:
00: f07 (method 80475954) -- receiver hook error from Address { payload: ID(6) }: exit_code=ExitCode { value: 20 }, return_data=RawBytes {  } (20)
01: f06 (method 3726118371) -- failed to flush allocations table: ActorError(exit_code: ExitCode { value: 20 }, msg: put failed with NotFound) (20)
--> caused by: ipld::block_create -- block links to CID with forbidden codec 112 (6: resource not found)
 (RetCode=20)
```

**Comment by Normalnoise** [comment]
how to fix it? @LexLuthr

**Comment by Normalnoise** [comment]
The DDO just can be used in boost? can I use it by lotus?

**Comment by LexLuthr** [comment]
@Normalnoise Actor team will check this and update the issue. I have transferred it to the Lotus repo for easy coordination. 
Meanwhile, I would strong suggest reading https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0045.md and https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0076.md and https://spec.filecoin.io/#section-systems.filecoin_markets to understand how markets work.

You can make the allocation however you wish. Boost does not care about the source of allocation as long as parameters match. I don't believe there is an existing command in Lotus to create allocation but you can use clients which might have one.

**Comment by rvagg** [comment]
`QmbSyXnZzRxjVKW7wr5zVwDgwwb6fsL4TMKxB2FbqcZWwk` is not a piece CID, it's a dag-pb CID which I believe explains the `block links to CID with forbidden codec 112` error (112 is 0x70 which is dag-pb).

A piece CID is going to start with `baga6...` like this one: https://cid.ipfs.tech/#baga6ea4seaqecmtz7iak33dsfshi627abz4i4665dfuzr3qfs4bmad6dx3iigdq which has codec ` fil-commitment-unsealed` and hash `sha2-256-trunc254-padded`.

To make a DDO allocation, you have to prepare the piece first, use one of the piece CID generation utilities out there which will make it for your CAR or file, or whatever you're onboarding.

**Comment by Normalnoise** [comment]
@rvagg thanks, I change to the right pieceCID, it success

**Comment by aarshkshah1992** [comment]
Closing this as it works for the user now.
