### ISSUE TITLE
GasEstimateMessageGas error

### ISSUE THREAD

**Issue by chenjihu** [filecoin-project/lotus#11803]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.26.1
```

### Repro Steps

1. Replace 1.25.0  with 1.26.1
2. Wait for WindowPost，or Use `lotus send xxxxxx x` command

### Describe the Bug

When the windowpost statge, a lot of errors occur, so the wdpost failed.
When I plan to send some fil to other wallet,  it shows the same error.

### Logging Information

```text
2024-04-02T17:25:16.916+0800    WARN    rpc     go-jsonrpc@v0.3.1/handler.go:444        error in RPC call to 'Filecoin.GasEstimateMessageGas': gas estimation failed:
    github.com/filecoin-project/lotus/node/impl/full.gasEstimateGasLimit
        /root/lotus/node/impl/full/gas.go:319
  - CallWithGas failed:
    github.com/filecoin-project/lotus/node/impl/full.gasEstimateCallWithGas
        /root/lotus/node/impl/full/gas.go:298
  - applying prior message (0, bafy2bzacecmijohjua5kfvdillhafxvmykyxm2ctisb7kbreq7to3qtkghtgq):
    github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).callInternal
        /root/lotus/chain/stmgr/call.go:175
  - failed to unmarshal exectrace:
    github.com/filecoin-project/lotus/chain/vm.(*FVM).ApplyMessage
        /root/lotus/chain/vm/fvm.go:450
  - cbor input had wrong number of fields
```

**Comment by gundamzl** [comment]
I also encountered the same problem, don't know how to solve it?

**Comment by TippyFlitsUK** [comment]
What is your output for `lotus -v`?

**Comment by maxvint** [comment]
Also got same error:
```
2024-04-11T05:39:50.728+0800	INFO	wdpost	wdpost/wdpost_run.go:276	post cycle done	{"cycle": "2024-04-11T05:32:00.182+0800", "took": 470.546543243}
2024-04-11T05:43:30.548+0800	ERROR	wdpost	wdpost/wdpost_run.go:697	estimating gas	{"error": "gas estimation failed: CallWithGas failed: applying prior message (0, bafy2
bzacedg6pgqiqvcyl46uublozyni6zultepc43srx62f7znxx6n6igjdo): failed to unmarshal exectrace: cbor input had wrong number of fields"}
2024-04-11T05:43:30.638+0800	ERROR	wdpost	wdpost/wdpost_run.go:179	submit window post failed: pushing message to mpool:
    github.com/filecoin-project/lotus/storage/wdpost.(*WindowPoStScheduler).submitPoStMessage
        /home/fil/workspace/filecoin/lotus-optimized/storage/wdpost/wdpost_run.go:658
```
`lotus -v ` output: lotus version 1.26.2+mainnet+git.7ac201c1e

**Comment by chenjihu** [comment]
I try to rebuild lotus with 1.26.1, and it does't work.  Finally, I rollback to 1.25.  Expect it can be fixed before mainnet swtich.

**Comment by chenjihu** [comment]
The other solution by [Dan on Slack](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1711715488700789)
```
 I just managed to test something different:
added GasLimit: 3000000, to my transaction payload
changed from post('MpoolPushMessage', [msg, { MaxFee: '0' }]) to post('MpoolPushMessage', [msg, { MaxFee: '70000000000000000' }])
```
Dan: "not ideal, but it seems to be working for the time being"

**Comment by chenjihu** [comment]
upgrade to 1.26.2, this bug disappered.
