### ISSUE TITLE
newHeads subscription compatibility with deferred execution model

### ISSUE THREAD

**Issue by Termina1** [filecoin-project/lotus#11807]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.26.1+mainnet+git.9dc9a5cf4.dirty
```

### Repro Steps

1. Subscribe to newHeads via eth_subscribe
2. When you receive new block from the subscription, immediately send eth_getBlockByNumber(block_num, true)
3. See error `requested a future epoch (beyond 'latest')`

### Describe the Bug

So as per documentation: https://docs.filecoin.io/smart-contracts/filecoin-evm-runtime/difference-with-ethereum

Filecoin returns for latest block n - 1 for compatibility reason, should it also delay the subscription event?

### Logging Information

```text
-
```

**Comment by Stebalien** [comment]
@aarshkshah1992 this is a good one to start with. We should probably just delay blocks in eth_subscribe by one epoch (if we can do it cleanly...).

**Comment by aarshkshah1992** [comment]
Okay, on it.
