### ISSUE TITLE
GasEstimateMessageGas error

### ISSUE THREAD

**Issue by Daniel1984** [filecoin-project/lotus#11814]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.26.0+mainnet+git.5f86ff9a6.dirty+api1.5.0
Local: lotus version 1.26.0+mainnet+git.5f86ff9a6.dirty
```

### Repro Steps

making POST request to `MpoolPushMessage`, which was working fine before the upgrade to v1.26.0

```js
const msg = {
  To: tx.address,
  Value: tx.amount,
  From: fromAddr,
  Version: 0,
  Method: 0
}

post('MpoolPushMessage', [msg, { MaxFee: '0' }], (err, res) => {...
```

### Describe the Bug

POST request to `MpoolPushMessage` returning:

> MpoolPushMessage: GasEstimateMessageGas error: gas estimation failed: CallWithGas failed: applying prior message (0, bafy2bzacedh3ap225pasqtyvmxso5lwubgdskd33qqajehimsu5vbbefe2tng): failed to unmarshal exectrace: cbor input had wrong number of fields

and I saw more people complain about same issue on public FIL slack channels

### Logging Information

```text
> MpoolPushMessage: GasEstimateMessageGas error: gas estimation failed: CallWithGas failed: applying prior message (0, bafy2bzacedh3ap225pasqtyvmxso5lwubgdskd33qqajehimsu5vbbefe2tng): failed to unmarshal exectrace: cbor input had wrong number of fields
```

**Comment by TippyFlitsUK** [comment]
https://github.com/filecoin-project/lotus/issues/11803#issuecomment-2031617560

**Comment by rjan90** [comment]
This is mismatch issue, which usually stems from a build-issue. Are you still encountering this issue on v1.26.2?

**Comment by rjan90** [comment]
We did a quick repro, and it was working on one of our computers.

**Comment by rjan90** [comment]
Closing this ticket as we were unable to repro. Let us know if you are still encountering this issue and we are happy to help torubleshoot, most likely it comes from a build issue.
