### ISSUE TITLE
rDataCap check too early

### ISSUE THREAD

**Issue by beck-8** [filecoin-project/lotus#11810]
https://github.com/filecoin-project/lotus/blob/b27c861485695d3f5bb92bcb281abc95f4d90fb6/cli/filplus.go#L1325

I think we are dealing with a bit of a problem here, I will change the position of the inspection later.
@LexLuthr

**Comment by LexLuthr** [comment]
Why do we need to change the position here? If we don't have Datacap required for those messages, why would I create them? 
Please explain your suggestion in detail.

**Comment by beck-8** [comment]
Because if you check at the original place and the amount is 0, you will directly return and exit. Users have no choice.

**Comment by beck-8** [comment]
On the other hand, the changed order is also reasonable.
1. Inform users that datacap will be consumed
2. Check datacap
If you check the datacap first and then exit, the user will be confused: Why do you check the quota? Why does the quota get consumed?

**Comment by LexLuthr** [comment]
That is the correct way. The command description and docs explain why Datacap is required. There is no point in proceeding further if there is no Datacap.

**Comment by beck-8** [comment]
I couldn't agree more, I'm just saying that the data checked makes this tool currently unusable.

client1's current quota is 0, and he knows this information very well.
This is what I found in actual use. Client1 needs to renew the deals in sp1, but sp1 also has client2's deals, so `len(terms) > 0`and `len(newClaims) > 0`. But client1 does not want to renew newClaims.
If the logic here is not changed, client1 must have a lot of datacap to renew deals that do not require datacap.

**Comment by LexLuthr** [comment]
If client1 only wants to renew only its deals then it should specify those deals in the command. It will not require any Datacap in that case. 
But, I see what you mean. It make UX better by asking client1 if they want to spend the Datacap before checking it.
Can you please open a Pull Requested with the required changes? 
Just send the Datacap check to https://github.com/filecoin-project/lotus/blob/b27c861485695d3f5bb92bcb281abc95f4d90fb6/cli/filplus.go#L1363

**Comment by beck-8** [comment]
Yes, I have submitted [PR](https://github.com/filecoin-project/lotus/pull/11811)
