### ISSUE TITLE
Test TestForkPreMigration hangs if LOTUS_DISABLE_PRE_MIGRATIONS=1 is set in the environment

### ISSUE THREAD

**Issue by ribasushi** [filecoin-project/lotus#11824]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
v1.26.1
```

### Repro Steps

Run

```
LOTUS_DISABLE_PRE_MIGRATIONS=1 go test -v -count=1 -timeout=30s ./chain/stmgr/forks_test.go
```

### Describe the Bug

It is not uncommon to have `LOTUS_DISABLE_PRE_MIGRATIONS=1` set on archival nodes. Its interaction with the above test was unexpected.

### Logging Information

```text
N/A
```

**Comment by rjan90** [comment]
Can confirm that the test fails when having the `LOTUS_DISABLE_PRE_MIGRATIONS=1` env set, and passing when its not set.

While I´m not deep into this part of the codebase, it seems that `TestForkPreMigration` indirectly relies on the `runPreMigration` function through its use of the StateManager.

The simple solution here might just be directly unsetting the environment variable for the duration of this TestForkPreMigration test, to ensure that the test is run, even though the machine might have `LOTUS_DISABLE_PRE_MIGRATIONS` set.
