### ISSUE TITLE
Can you stop constantly forcing upgrades.

### ISSUE THREAD

**Issue by yjgfn** [filecoin-project/lotus#11845]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Can you stop constantly forcing upgrades.

### Describe the solution you'd like

Can you stop constantly forcing upgrades.

### Describe alternatives you've considered

Can you stop constantly forcing upgrades.

### Additional context

Can you stop constantly forcing upgrades. I don't have that much time to deal with these issues

**Comment by TippyFlitsUK** [comment]
Can you elaborate??

**Comment by arajasek** [comment]
I would propose closing this issue, I'm not sure it's relevant (or constructive).

**Comment by TippyFlitsUK** [comment]
No response from OP, so closing this issue as suggested.
