### ISSUE TITLE
lotus-daemon cannot boot on IPv6-only network

### ISSUE THREAD

**Issue by paul8046** [filecoin-project/lotus#11874]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.26.2+mainnet+git.082a9159c
```

### Repro Steps

1. Start lotus-daemon

### Describe the Bug

None of the official bootstrap nodes are IPv6 enabled. As a result lotus-daemon cannot find peers without having IPv4 configured. Node operators on an IPv6-only network cannot operate.

This is _not_ a feature request; in 2024 this is a bug. There are people out there who do not have IPv4 addresses.

### Logging Information

```text
N/A
```

**Comment by rjan90** [comment]
Hey @paul8046! Thanks for the report, I have notified the infra-teams that are running bootstrapper-nodes, and pointed them to this issue-report.

**Comment by rjan90** [comment]
Hey @paul8046!

I just got confirmation from Chainsafe, who are running bootstrapper nodes on both Calibration and Mainnet, that they have enabled IPv6 on their bootstrap nodes without requiring any changes to their multiaddresses. Therefore, I will close the ticket as completed now.

Thanks for the report!
