### ISSUE TITLE
Test FIP-0085 once migration integrated 

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/lotus#11896]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

FIP 0085 is prototyped and can merge in go-state-types once we merge the nv23 banch.  We need to test it.

### Describe the solution you'd like

Migration test in lotus asserting the new state of f090.  Setup f090 with a known key and spend before migration.  Demonstrate that this does not work after migration.

### Additional context

Just filing this so we don't forget

**Comment by rjan90** [comment]
Hey! Is it okay that I move the testing plan for this FIP into this issue https://github.com/filecoin-project/lotus/issues/11939, so its easier to see all the testing surface we have covered?

**Comment by rjan90** [comment]
Completeded an E2E testing with https://github.com/filecoin-project/go-state-types/releases/tag/v0.14.0-dev5, and can confirm that f090 now throws off:

```
lotus msig inspect f090
ERROR: actor code is not multisig: account
```

I will close this ticket now, with the testing plan being moved to #11939. Only need a migration test in Lotus asserting the new state of f090 before we can :green_circle: this for nv23.
