### ISSUE TITLE
Implement FIP 0065

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/lotus#11921]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

FIP 0065 ignoring f05's contribution to locked FIL is accepted.

### Describe the solution you'd like

Implement the FIP

**Comment by rjan90** [comment]
Is my understanding correct that to test this e2e in a devnet, it would basically be:

- Spin up a devnet. Check circulating suppy. Spend some larger amount to lock in the built-in market actor. Confirm that the circulating supply is the same before the network upgrade to nv23. Confirm after the network upgrade to nv23, that this amount if subtracted?


Are there any other edge-cases/testing we would want to cover?
