### ISSUE TITLE
[lotus-daemon] failed to decode state root

### ISSUE THREAD

**Issue by jochasinga** [filecoin-project/lotus#11957]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon: 1.26.0+2k+git.0cdf58849
Miner: 1.23.1-dev+mainnet+git.c6c23ec6d
```

### Repro Steps

Mac OS 13.6.6

1. Run `./lotus daemon --lotus-make-genesis=devgen.car --genesis-template=localnet.json --bootstrap=false`
2. See error:
```
2024-05-02T10:12:25.838-0700	ERROR	statemgr	stmgr/forks.go:253	FAILED pre-migration	{"error": "failed to decode state root: cbor input had wrong number of fields", "errorVerbose": "failed to decode state root:\n    github.com/filecoin-project/lotus/chain/consensus/filcns.upgradeActorsV13Common\n        /Users/pancy/Code/filecoin/lotus-local-net/chain/consensus/filcns/upgrades.go:2220\n  - cbor input had wrong number of fields"}
```

See the screenshot below

<img width="962" alt="Screenshot 2024-05-02 at 10 14 38 AM" src="https://github.com/filecoin-project/lotus/assets/2445163/b2e99873-09a4-45bc-86f6-04ec06e9c6a3">

### Describe the Bug

- I was following the [local network tutorial](https://lotus.filecoin.io/lotus/developers/local-network/) up to the first step to start the node

- I ran the `daemon` command to start the node, and saw the following error output

- The process kept running and didn't crash

### Logging Information

```text
2024-05-02T11:48:42.586-0700	ERROR	statemgr	stmgr/forks.go:253	FAILED pre-migration	{"error": "failed to decode state root: cbor input had wrong number of fields", "errorVerbose": "failed to decode state root:\n    github.com/filecoin-project/lotus/chain/consensus/filcns.upgradeActorsV13Common\n        /Users/pancy/Code/filecoin/lotus-local-net/chain/consensus/filcns/upgrades.go:2220\n  - cbor input had wrong number of fields"}
```
```

**Comment by rvagg** [comment]
> Daemon: 1.26.0+2k+git.0cdf58849

This is likely your problem. See the notice on the release page for 1.26.0: https://github.com/filecoin-project/lotus/releases/v1.26.0, due to a change in the nv22 upgrade timing, a 1.26.2 was needed which meant that both 1.26.0 and 1.26.1 had the wrong timings, which would lead to a problem like you're experiencing.

Grab 1.26.2 and see how you go: https://github.com/filecoin-project/lotus/releases/v1.26.2

**Comment by jochasinga** [comment]
> > Daemon: 1.26.0+2k+git.0cdf58849
> 
> This is likely your problem. See the notice on the release page for 1.26.0: https://github.com/filecoin-project/lotus/releases/v1.26.0, due to a change in the nv22 upgrade timing, a 1.26.2 was needed which meant that both 1.26.0 and 1.26.1 had the wrong timings, which would lead to a problem like you're experiencing.
> 
> Grab 1.26.2 and see how you go: https://github.com/filecoin-project/lotus/releases/v1.26.2

@rvagg I'll report the outcome today. Adding this to avoid auto closing.

**Comment by rjan90** [comment]
Hey @jochasinga! Where you able to resolve this when upgrading to v1.26.2 or higher?
