### ISSUE TITLE
Deprecated Linters Causing failed checks

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#11967]
During the execution of [golangci-lint](https://github.com/filecoin-project/lotus/actions/runs/8969938200/job/24632349545) when submitting a PR, several linters are reported as deprecated and fully inactivated, causing the process to fail. It suggest that we:

- Replace `varcheck` with `unused`.
- Replace `deadcode` with `unused`.
- Replace `scopelint` with `exportloopref`.
- Replace `golint` with `revive`.

**Comment by rvagg** [comment]
Some context, latest update turned deprecation of these into an error, see section 5 in https://golangci-lint.run/product/changelog/#1580

varcheck and deadcode recommended replacement with unused here: https://golangci-lint.run/product/changelog/#v1490

discussion on scopelint: https://github.com/golangci/golangci-lint/issues/1041 - exportloopref and looppointer come up here, but looppointer was rejected @ https://github.com/golangci/golangci-lint/pull/1924

revive mentioned as drop-in replacement to golint: https://golangci-lint.run/usage/linters/#revive

unfortunately revive is quite a bit pickier than golint and throws up a bunch of errors when implementing, so we'll have to fix up a bunch of problems

**Comment by rvagg** [comment]
https://github.com/filecoin-project/lotus/pull/11968 an attempt at what it might take .. a lot, without global exclusions
