### ISSUE TITLE
Flags field is dropped in SectorOnChainInfo conversions

### ISSUE THREAD

**Issue by hanabi1224** [filecoin-project/lotus#11962]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.27.0-dev+calibnet+git.10f7b6ed5
```

### Repro Steps

The `Flags` field is not converted in the code at https://github.com/filecoin-project/lotus/blob/master/chain/actors/builtin/miner/v12.go#L533
```go
func fromV12SectorOnChainInfo(v12 miner12.SectorOnChainInfo) SectorOnChainInfo {
	info := SectorOnChainInfo{
		SectorNumber:          v12.SectorNumber,
		SealProof:             v12.SealProof,
		SealedCID:             v12.SealedCID,
		DealIDs:               v12.DealIDs,
		Activation:            v12.Activation,
		Expiration:            v12.Expiration,
		DealWeight:            v12.DealWeight,
		VerifiedDealWeight:    v12.VerifiedDealWeight,
		InitialPledge:         v12.InitialPledge,
		ExpectedDayReward:     v12.ExpectedDayReward,
		ExpectedStoragePledge: v12.ExpectedStoragePledge,

		SectorKeyCID: v12.SectorKeyCID,

		PowerBaseEpoch:    v12.PowerBaseEpoch,
		ReplacedDayReward: v12.ReplacedDayReward,
	}
	return info
}
```

### Describe the Bug

When posting the below payload to `http://localhost:1234/rpc/v0`
```json
{"jsonrpc":"2.0","id":0,"method":"Filecoin.StateSectorGetInfo","params":
["f04040",102,[{"/":"bafy2bzacedbmki5e4olfcdkruq7qjh7xj4yg6wbcqsiqw2ez7kngiywbdsge4"},{"/":"bafy2bzacebbntlxgcsdq2mjg23lf6fjwbugsbx52umyur3yyhszganidni2p2"}]]
}
```

`Flags` should be 1 in the response.

### Logging Information

```text
N/A
```

**Comment by rvagg** [comment]
https://github.com/filecoin-project/lotus/pull/11963
