### ISSUE TITLE
[DX Streamline] Lean NI-PoRep integration testing

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/lotus#12009]
As part of the effort to decouple lotus node development from lotus-miner development, this task aims to implement integration testing of the [FIP-0090](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0090.md) (and likely [FIP-0092](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0092.md)) NI-PoRep feature without requiring full lotus-miner implementation of the feature. This will likely lead to changes in the itest kit setup and more verbose testing in the short term, but a better understanding of the longer-term implications of decoupling.

**Comment by rjan90** [comment]
Reopening this ticket. 

#12017 delivered the generic testkit manual miner that can be used to onboard CC sectors and Snap deal sectors which was a pre-requisite for the lean NI-PoRep integration testing.

https://github.com/filecoin-project/lotus/pull/12045 is planned to deliver the NI-PoRep part.

**Comment by rjan90** [comment]
Closing as this has been completed
