### ISSUE TITLE
[DX Streamline] Remove Markets and deal making from Lotus Miner and Full Node

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#12004]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

This is a follow-up to https://github.com/filecoin-project/lotus/issues/12002. That issue was for removing Markets from the Lotus Client CLI & API.

This issues is to remove Markets and deal making from Lotus Miner and Full Node.

### Describe the solution you'd like

This issues is to remove Markets and deal making from Lotus Miner and Full Node.

**Comment by rvagg** [comment]
* Taking careful note of builtin actors testing that will be removed in the process so we can restore some kind of coverage via alternate means.
* Clear documentation of what's changing for downstream users.
