### ISSUE TITLE
[DX Streamline] Remove Lotus Client deal making CLI and API

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#12002]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

`go-fil-markets` has been deprecated for a long time. This PR aims to remove the Lotus Client deal making CLI and API as we don't need any of that code anymore.

### Describe the solution you'd like

`go-fil-markets` has been deprecated for a long time. This PR aims to remove the Lotus Client deal making CLI and API as we don't need any of that code anymore.

**Comment by rvagg** [comment]
Some notes I was writing at #12008 before I realised this issue existed:

* Particular focus on what is currently provided by Boost today.
* Possibly moving some functionality into lotus-shed for convenience.
* Taking careful note of builtin actors testing that will be removed in the process so we can restore some kind of coverage via alternate means.
