### ISSUE TITLE
Do not enable `read_uncommitted` by default

### ISSUE THREAD

**Issue by masih** [filecoin-project/lotus#12081]
The `PRAGMA` for 3 databases across lotus repo enable uncommitted reads:

https://github.com/filecoin-project/lotus/blob/395cdd721e7ead60e4b7853b3023f50daeed697f/chain/ethhashlookup/eth_transaction_hash_lookup.go#L25

https://github.com/filecoin-project/lotus/blob/6bc04c8060d59099f5d4eadf7b1ad716f8799b33/chain/events/filter/index.go#L32

https://github.com/filecoin-project/lotus/blob/6bc04c8060d59099f5d4eadf7b1ad716f8799b33/chain/events/filter/index.go#L32

This can have some performance gain but will cause all sorts of problems, specially in db interactions that require ACID properties where data consistency matters. Based on a quick look we _do_ care about data consistency across all three places listed above. Therefore, I recommend against performing dirty reads.

**Comment by snissn** [comment]
I think we can close this - https://github.com/filecoin-project/lotus/pull/12090/files#diff-fe5e47a357d5465c3a2b1002977a53ad7c0990f76da22137417723577b87b19eL32 @rvagg made the change in pull 12090

**Comment by masih** [comment]
That PR only updates events db pragma. right?

**Comment by rvagg** [comment]
yeah, only events sorry, we can follow up with the others as a separate PR

**Comment by BigLep** [comment]
2024-06-18 triage note: @rvagg we wanted to confirm that https://github.com/filecoin-project/lotus/pull/12098 will address this issue.

**Comment by rvagg** [comment]
yes, it will, they'll all have the same pragma and read_uncommitted is gone
