### ISSUE TITLE
Power has always been 0

### ISSUE THREAD

**Issue by szdengbw** [filecoin-project/lotus#1210]
[miner_20200204.log](https://github.com/filecoin-project/lotus/files/4151730/miner_20200204.log)
**Describe the bug**

Restart My Miner every few hours, but power is always 0。
Complete log file reference attachment。 

**To Reproduce**
1. Run ' lotus-storage-miner run'
2. See error：
 
[miner_20200204.log](https://github.com/filecoin-project/lotus/files/4151723/miner_20200204.log)

![image](https://user-images.githubusercontent.com/19684486/73719518-af2fde00-475a-11ea-92f1-c4b06001c094.png)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/19684486/73719424-5ceebd00-475a-11ea-83d7-7a8a1d456111.png)

**Version (run `lotus --version`):**
lotus version 0.2.7+git30fd4ecb.dirty

**Additional context**
[miner_20200204.log](https://github.com/filecoin-project/lotus/files/4151714/miner_20200204.log)

**Comment by magik6k** [comment]
Please retry on testnet/3 and repoen if this is still an issue

**Comment by irocnX** [comment]
> Please retry on testnet/3 and repoen if this is still an issue
How to do on testnet/3? thanks~
