### ISSUE TITLE
Create Migration Test for FIP-0085 in Lotus to Assert New State of `f090`

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#12102]
### Done Criteria

1. A migration test is created in Lotus to assert the new state of f090 as per [FIP-0085](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0085.md).
2. The test verifies that f090 has been converted from a multisig actor to a keyless account actor.
3. The test is integrated into the existing Lotus test suite and passes all checks.

### Why Important

1. Ensures that the migration of f090 to a keyless account actor is correctly implemented and verifiable.
2. Prevents potential issues that could arise from the migration by catching them early in the testing phase.
3. Provides a clear and automated way to verify the state of f090, reducing the risk of human error.

### User/Customer
Maintainers and developers working on the Lotus project.

### Notes
1. The migration of f090 is detailed in FIP-0085](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0085.md).
2. The PR adding the migration can be found [here](https://github.com/filecoin-project/go-state-types/pull/259).
3. Ensure that the test covers all edge cases and scenarios outlined in the FIP.
4. Coordinate with the team to integrate the test into the CI/CD pipeline for continuous verification.

**Comment by BigLep** [comment]
#fil-lotus-dev slack thread: https://filecoinproject.slack.com/archives/CP50PPW2X/p1718627270414419

I'm working to make sure we complete this by EOD 2024-06-26.

**Comment by BigLep** [comment]
Per Slack, @ZenGround0 is going to take this with goal to land before the [Lotus 1.28.0 RC](https://github.com/filecoin-project/lotus/issues/12109).

**Comment by BigLep** [comment]
Closing given https://github.com/filecoin-project/lotus/pull/12139 was merged
