### ISSUE TITLE
[DX Streamline] Add mechanism so PR titles conform to repo standard

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#12148]
## Done Criteria
1. PR creators get feedback if their PR title doesn't match the [repo convention](https://github.com/filecoin-project/lotus/blob/master/.github/pull_request_template.md)
2. PR merges are blocked by default if the convention isn't followed

## Why Important
1. Consistency makes it easier when spotting for certain changes when going through the commit history.
2. Prevents sloppy titles from making it into the commit history 

## User/Customer
1. Maintainers
2. Contributors

## Notes
This most recently happened with https://github.com/filecoin-project/lotus/commit/1e8bc10b04ce65554fc9b5e8c289dec7b57daf83 where https://github.com/filecoin-project/lotus/pull/12139 was checked in with the title "rough draft".

**Comment by galargh** [comment]
It might be a good idea to handle the commit message conformance as well if the team feels the need for it
