### ISSUE TITLE
[WIP] Lotus Client Release v1.27.2

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/lotus#12157]
# Lotus v1.27.2 Release

## 🚢 Estimated shipping date

1-Jul-2024

## ✅ Release Checklist

- [x] Fork a new branch (`release/vX.Y.Z`) from `master` and make any further release related changes to this branch. If any "non-trivial" changes get added to the release, uncheck all the checkboxes and return to this stage.
- [x] Bump the version in `build/version.go` in the `master` branch to `vX.Y.(Z+1)-dev` (bump from feature release) or `vX.(Y+1).0-dev` (bump from mandatory release). Run make gen and make docsgen-cli before committing changes

**Prepping an RC**:

- [ ] version string in `build/version.go` needs to be updated to end with '-rcX' (in the `release/vX.Y.Z` branch)
- [ ] run `make gen && make docsgen-cli`
- [ ] Generate changelog using the script at scripts/mkreleaselog
- [ ] Add contents of generated text to lotus/CHANGELOG.md in addition to other details
- [ ] Commit using PR
- [ ] tag commit with `vX.Y.Z-rcN`
- [ ] cut a pre-release [here](https://github.com/filecoin-project/lotus/releases/new?prerelease=true)

**Testing**

Test the release candidate thoroughly, including automated and manual tests to ensure stability and functionality across various environments and scenarios.

**Stable Release**
  - [ ] Final preparation
    - [ ] Verify that version string in [`version.go`](https://github.com/filecoin-project/lotus/blob/master/build/version.go) has been updated.
    - [ ] Verify that codegen is up to date (`make gen && make docsgen-cli`)
    - [ ] Ensure that [CHANGELOG.md](https://github.com/filecoin-project/lotus/blob/master/CHANGELOG.md) is up to date
    - [ ] Open a pull request against the `releases` branch with a merge of `release-vX.Y.Z`.
    - [ ] Cut the release [here](https://github.com/filecoin-project/lotus/releases/new?prerelease=false&target=releases).
      - The target should be the `releases` branch.
      - Either make the tag locally and push to the `releases` branch, or allow GitHub to create a new tag via the UI when the release is published.

**Post-Release**
  - [ ] Open a pull request against the `master` branch with a merge of the `releases` branch. Conflict resolution should ignore the changes to `version.go` (keep the `-dev` version from master). Do NOT delete the `releases` branch when doing so!
  - [ ] Update [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) with any improvements determined from this latest release iteration.
  - [ ] Create an issue using [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) for the _next_ release.

## ❤️ Contributors

See the final release notes!

## ⁉️ Do you have questions?

Leave a comment in this ticket!

**Comment by rvagg** [comment]
Currently targeting including #12080 and #12135 if we can get that resolved in reasonable time.

**Comment by BigLep** [comment]
@rvagg : per https://github.com/filecoin-project/lotus/pull/12096#issuecomment-2206722959 , I'm wondering if we can do this release with the updated release process.

**Comment by BigLep** [comment]
@rvagg : I know we didn't come to maintainer conclusion on 2024-07-04 about whether to actually go forward with the release.  In talking with @rjan90 on 2024-07-05, we agreed it is worth doing to validate the release automation of https://github.com/filecoin-project/lotus/pull/12096.  That said, no rush on this.  It seems like a good activity to validate during the Brussels/FDS week.

**Comment by rvagg** [comment]
yes, I was meaning to get to this today but got caught up trying to figure out why the niporep impl is not working as it should; it's top of my list other than that

**Comment by rjan90** [comment]
Closing this ticket as we will not progress further with this. Re-posting Rod´s comment on Slack:

> FYI lurkers: a v1.27.2-rc2 was published today https://github.com/filecoin-project/lotus/releases/tag/v1.27.2-rc2
> This was mainly to test a new release process. The release should be solid if you want to run it and you are on 1.27.1. It includes some minor fixes and some improvements for eth_* APIs on top of 1.27.1. We probably won’t push forward with a 1.27.2 final release as we are focused on 1.28.0 which will be a mandatory upgrade for all. It’s got RCs available now if you want to start testing your upgrades.
