### ISSUE TITLE
Butterfly network genesis should have a faucet account for tokens and datacap

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#12160]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Post FIP-0085, we can no longer use Actor `f090` as the faucet for Butterfly. So we need to update the Butterfly genesis block to contain a new account that can be used as a faucet for tokens and datacap.

### Describe the solution you'd like

The solution should be to update the butterfly bootstrap scripts to create this new account and give it a FIL and datacap balance. Still looking into this will be done.

**Comment by BigLep** [comment]
Relevant slack thread: https://filecoinproject.slack.com/archives/CP50PPW2X/p1719487265531159

**Comment by rjan90** [comment]
- Tested https://faucet.butterfly.fildev.network/funds.html after the reset with Lotus v1.28.0-rc1, and can confirm that I was able to get funds after the NV23 upgrade epoch.

- For getting Datacap through the faucet we need https://github.com/filecoin-project/lotus-infra/issues/1584.
   - To unblock testing we can manually hand out Datacap

**Comment by rjan90** [comment]
Closing this issue as we have confirmed that the Butterfly-faucet works after the NV23 upgrade when resetting with Lotus v1.28.0-rc1

For fixing the Datacap faucet, we need to automatically add RKH address during the reset process of the Butterfly-network, which progress can be tracked in https://github.com/filecoin-project/lotus-infra/issues/1584.
- Its not a blocker for testing/continued rollout of v1.28.0 as we can manually hand out Datacap - although its additional manual labour
