### ISSUE TITLE
Calibration network genesis should have a faucet account for tokens and datacap

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#12165]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Caliberation network genesis should have a faucet account for tokens and datacap.

### Describe the solution you'd like

Only migrate the `f090` Actor to a keyless Actor if it is a multisig.

**Comment by BigLep** [comment]
Related butterfly issue (https://github.com/filecoin-project/lotus/issues/12160 ), which links to Slack thread with more info.

**Comment by aarshkshah1992** [comment]
@f8-ptrk 

The implementation now ensures that `f090` is a multisig before doing the migration. Please see https://github.com/filecoin-project/go-state-types/pull/281.

**Comment by rjan90** [comment]
We will keep the ticket open until the Calibration upgrade has happened.

**Comment by rjan90** [comment]
Closing ticket as completed now that the calibration upgrade has happened.
