### ISSUE TITLE
EthTxHashLookup has poor query management

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/lotus#12171]
Noticed in a heap dump:

<img width="663" alt="Screenshot 2024-07-02 at 9 57 56 AM" src="https://github.com/filecoin-project/lotus/assets/495647/a752c633-76ca-4dfe-a09a-dc2c4173d2a5">

`EthTxHashLookup#UpsertHash` creates a new PreparedStatement on each call and then does nothing else with it (probably should be closed at a minimum). The remainder of the queries don't use PreparedStatements at all.

TODO:

* Refactor to use PreparedStatements for all queries not involved in migration
* Retain PreparedStatement instances on the parent `EthTxHashLookup` for re-use

Should be done after https://github.com/filecoin-project/lotus/pull/12098 is merged, or done on top of that branch.

**Comment by jennijuju** [comment]
Can also be a good issue for Mikers
