### ISSUE TITLE
The new version sealed the dc sector, and the DealIDs in sector info are empty.

### ISSUE THREAD

**Issue by nezha90** [filecoin-project/lotus#12197]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.26.3+mainnet+git.e04c1b6c5.amd.Ubuntu.18.04+api1.5.0
Local: lotus version 1.26.3+mainnet+git.e04c1b6c5.amd.Ubuntu.18.04
lotus-miner version 1.26.3+mainnet+git.e04c1b6c5.amd.Ubuntu.18.04
```

### Repro Steps

1. Search the browser for any recent ProveCommitSector messages containing pledges
2. use `lotus state sector-info`

### Describe the Bug

You can see that this is the dc sector, but the dealIDs are empty, but the dealIDs of the dc sector were displayed normally before.
```
lotus state sector-info f03087446 105468
2024-07-09T11:15:33.666+0800    INFO    fil-consensus   filcns/upgrades.go:88   migration worker count: 64
SectorNumber:  105468
SealProof:  8
SealedCID:  bagboea4b5abcbaxje6wyxl2775rursgep725pnkuieaypr2psb6fkxne32gqqfig
DealIDs:  []

Activation:  4041432 (28 Jun 24 12:36 CST, 1 week 3 days ago)
Expiration:  4649100 (25 Jan 25 12:30 CST, in 28 weeks 4 days)

DealWeight:  0
VerifiedDealWeight:  20879313494605824
InitialPledge:  1.540401232329671839 FIL
ExpectedDayReward:  0.001457336193309211 FIL
ExpectedStoragePledge:  0.02898573785224511 FIL

Deadline:  44
Partition:  0
```

### Logging Information

```text
everyone is like this
```

**Comment by rvagg** [comment]
@nezha90 as of FIP-0076 (Direct Data Onboarding), `SectorOnChainInfo` is no longer updated. Deals are more strictly isolated to the market actor, and in the future, "deals" will also include custom smart contract markets. See https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0076.md#sectoronchaininfo

There is now an inverse in the market actor, `ProviderSectors` which contains the mapping I think you're after: https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0076.md#state-1, there's currently an issue asking for API access into this: https://github.com/filecoin-project/lotus/issues/11997 - if this is something you're in need of perhaps you can weigh in there with your use-case as it'll help prioritisation _or_ having someone (yourself?) contributing the feature.
