### ISSUE TITLE
Events db query speed

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/lotus#12255]
While looking at https://github.com/filecoin-project/lotus/issues/12254 I took the opportunity to look into timing. On my mainnet node with quite a bit of events history (42G events.db):

```
$ time curl http://localhost:1234/rpc/v1 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock": "0x3E8872", "toBlock": "0x3E8872"}],"id":1}'
...
real    0m3.377s
```

When I run this query in a loop and then grab 120s of samples to build a flamegraph, it's all in the sqlite native engine:

<img width="1207" alt="Screenshot 2024-07-18 at 10 37 56 AM" src="https://github.com/user-attachments/assets/95c59b21-4cc3-473f-9914-df392e3a7cdc">

The query that's built, prepared and then executed (with substitutions) is:

```
SELECT
      event.id,
      event.height,
      event.tipset_key,
      event.tipset_key_cid,
      event.emitter_addr,
      event.event_index,
      event.message_cid,
      event.message_index,
      event.reverted,
      event_entry.flags,
      event_entry.key,
      event_entry.codec,
      event_entry.value
    FROM event JOIN event_entry ON event.id=event_entry.event_id
    WHERE event.height>=? AND event.height<=? AND event.reverted=?
    ORDER BY event.height DESC, event_entry._rowid_ ASC
```

First thing to note is the stupid `height>=? and height<=?` for the case where fromBlock=toBlock, we can easily optimise that but a quick test of doing that doesn't show much difference in execution speed.

Considering the indexes needed for this:

* `event.id` is a PRIMARY KEY
* `event_entry.event_id` has its own index
* `event.height` has its own index
* `event.reverted` has its own index
* `event_entry._rowid_` I believe is implicitly indexed and by the time it needs to sort this should be minimal anyway

**BUT** if I make a composite index for the two WHERE columns: `CREATE INDEX IF NOT EXISTS tmp_event_height_reverted ON event (height, reverted);` and then re-run the query:

```
$ time curl http://localhost:1234/rpc/v1 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock": "0x3E8872", "toBlock": "0x3E8872"}],"id":1}'
real    0m0.008s
```

That's a bit dramatic!

Unfortunately, there's a lot of other ways that WHERE can be constructed, so we need to consider the variations and also test the differences in introducing composites for these too, and we need to consider cost of doing so with the importance of these query types:

* `tipset_key_cid` could be used instead of `height` for this type of query, so you could get it combined with `reverted`
* For the `addresses` case we can get a compounded `OR` on `emitter_addr`
* In the `keysWithCodec` type query we can get in to `indexed=1 and key=?` for event_entry
  * we also get a compounded `OR` group on `value=? AND codec=?` for each value type specified in the filter

**Comment by rvagg** [comment]
So the `height=?` vs `height>=? and height<=?` actually matters, both the index and that change seem to make a difference, if I do these queries from the commandline (`sqlite3 events.db 'select ...'`), doing a height+`reverted=true`, I can observe:

* With `height>=? and height<=?` and no index - ~3.2s
* With `height>=? and height<=?` and with an index - ~3.2s
* With `height=?` and no index - ~3.2s
* With `height=?` and with an index - ~0.008s

Removing the `reverted` clause then we get everything down to ~0.008s because we have the `height` index.

Adding `tipset_key_cid` to the mix, if I switch the eth query to `"blockHash"` instead of `"fromBlock"` and `"toBlock"` for the same block, then I get it returning even slower, closer to 4s.

If I add a composite key on `(height, tipset_key_cid, reverted)` then I don't really get any benefit on any of the queries, it seems that it can only make use of the precise composite for this. Adding them as two separate composite keys gives us the expected speed-up for both query types.

In terms of cost, looking at the growth of my 40G events.db:

* Adding the `(height, reverted)` composite grows the db file by 1.4%
* Adding the `(tipset_key_cid, reverted)` composite grows the db by an additional 4.9% (tsk is a much larger column so this is expected)

So adding them both my db file goes from 40,924MiB to 43,530MiB.

Then we have the additional clauses. I need to experiment with what happens when we add them and if we can avoid the cost by transforming them into subqueries ontop of the initial height||tsk + reverted query.

**Comment by rvagg** [comment]
I think I’ve figured it out; somewhat, here’s our indexes:

```
CREATE INDEX event_height ON event (height);
CREATE INDEX event_reverted ON event (reverted);
CREATE INDEX event_emitter_addr ON event (emitter_addr);
CREATE INDEX event_tipset_key_cid ON event (tipset_key_cid);
```

we always either select on tsk or height, but when I have any complex condition on `height` that isn’t just `=`, then it will bypass  the height index and use the next index in the list of fields I’m querying against. So, for the simple eth_getLogs query you get `height>=X and height<=X and reverted=false` and it says “too hard, but I have a “reverted” index, let’s use that instead. It also seems to do the same thing with emitter_addr.

But, if I drop those 2 additional indexes, leaving just tsk and height, then it uses it, even for the range query; it’s only then when I can see it showing up in `EXPLAIN QUERY PLAN`:

```
QUERY PLAN
|--SEARCH event USING INDEX event_height (height>? AND height<?)
|--SEARCH event_entry USING COVERING INDEX event_entry_event_id (event_id=?)
```

I think the answer is to just drop those two additional indexes. The bulk of the trim-down work is done by either tsk or height anyway.

I just need to test this with a much larger range, default config allows for a range of 2880 epochs.

**Comment by rvagg** [comment]
Sadly this also applies to joined tables. If I include a typical `keysWithCodec` query that gets built:

```sql
explain query plan SELECT event.height, hex(event.tipset_key_cid),hex(event.emitter_addr),event_entry.indexed,event_entry.codec,event_entry.key,hex(event_entry.value) FROM event JOIN event_entry ON event.id=event_entry.event_id, event_entry ee2 ON event.id=ee2.event_id WHERE event.height>=4095282 AND event.height<=4098162 AND event.reverted=false AND event.emitter_addr=X'040A60E1773636CF5E4A227D9AC24F20FECA034EE25A' AND ee2.indexed=1 AND ee2.key='t1' AND ((ee2.value=X'
DDF252AD1BE2C89B69C2B068FC378DAA952BA7F163C4A11628F55A4DF523B3EF' AND ee2.codec=85)) ORDER BY event.height DESC, event_entry._rowid_ ASC
```

```
QUERY PLAN                                                                                                                                                                                  |--SEARCH ee2 USING INDEX event_entry_codec_value (codec=? AND value=?)
|--SEARCH event_entry USING INDEX event_entry_event_id (event_id=?)                                                                                                                         |--SEARCH event USING INTEGER PRIMARY KEY (rowid=?)
`--USE TEMP B-TREE FOR ORDER BY                                                                                                                                                             ```

bypassing the `height index entirely

If I remove the indexes on `event_entry`  such that we are left with only these indexes on it and `event`:

```sql
CREATE INDEX event_tipset_key_cid ON event (tipset_key_cid);
CREATE INDEX event_height ON event (height);
CREATE INDEX event_entry_event_id ON event_entry(event_id);
```

we get:

```
|--SEARCH event USING INDEX event_height (height>? AND height<?)
|--SEARCH ee2 USING INDEX event_entry_event_id (event_id=?)
|--SEARCH event_entry USING INDEX event_entry_event_id (event_id=?)
`--USE TEMP B-TREE FOR RIGHT PART OF ORDER BY
```

which is what we want.

I can widen the height range by quite a bit and still get fairly responsive queries. 0.11s for a 2880 epoch range query.

**Comment by aarshkshah1992** [comment]
@rvagg The only remaining question to ask if what's the tradeoff of dropping those indices. Does it significantly impact the perf on an API/query ?

**Comment by rvagg** [comment]
https://github.com/filecoin-project/lotus/pull/12261
