### ISSUE TITLE
Bug in lotus-miner sectors expired --remove-expired Command Causes Crashes and High CPU Usage

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/lotus#12260]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
Daemon:  1.28.0-rc4+mainnet+git.ff0e889b5+api1.5.0
Local: lotus-miner version 1.28.0-rc4+mainnet+git.ff0e889b5
```

### Repro Steps

1. Run the command `lotus-miner sectors expired --remove-expired`.
2. Observe the CPU usage and system stability.
3. Note the errors and crashes in the miner logs.

## Observed Behavior:

- High CPU usage upon running the command.
- Multiple RPCConnectionError messages.
- Repeated miner crashes and panics, leading to extensive stack traces.
- Difficulty in recovering the system without multiple restarts.

![screenshot_2024-07-17_at_3 16 50___pm_720](https://github.com/user-attachments/assets/0a7381fd-8208-44f2-97fc-6f2c7bbab8dd)

### Proposed Solution:

Investigate and optimize the implementation of lotus-miner sectors expired --remove-expired to handle large volumes of expired sectors without overloading the system.

Consider adding rate-limiting or batching mechanisms to prevent system overload.

Slack thread: https://filecoinproject.slack.com/archives/CPFTWMY7N/p1703024759270519

### Describe the Bug

Users have reported that running the command `lotus-miner sectors expired --remove-expired` results in high CPU usage and causes the `lotus-miner` to crash. This issue persists across multiple attempts to execute the command, leading to repeated miner restarts and a significant disruption in service.

### Logging Information

```text
Removing sector	219168:	ERROR: RPCConnectionError
Removing sector	219169:	ERROR: RPCConnectionError
Removing sector	224106:	ERROR: RPCConnectionError
Removing sector	224107:	ERROR: RPCConnectionError
Removing sector	227386:	ERROR: RPCConnectionError
```

**Comment by LexLuthr** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/12268
