### ISSUE TITLE
Events database GC

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/lotus#12274]
Tie event lifetime to blockstore lifetime. Make this configurable but if you have a splitstore enabled then events shouldn't persist if you don't have the blocks available for them.

Needs some consideration though: `eth_getLogs` and `GetActorEventsRaw` I think should still work on old epochs even if you don't have the blocks, maybe that's desirable? We could make this configurable to either have a config option with "number of epochs to store" or "follow splitstore".

**Comment by BigLep** [comment]
@rvagg : newbie question here: does this only apply for the events db, or do we need to cover the messages and transactions dbs as well?

**Comment by rvagg** [comment]
txhash.db has a GC already

I think msgindex.db does a basic GC on lotus startup

It's events that's the main problem, because it doesn't have any, and it accumulates a lot quicker and gets a lot larger. But we could apply the same pattern to the others when we implement it.

**Comment by BigLep** [comment]
This is subsumed by work happening in https://github.com/filecoin-project/lotus/issues/12453
