### ISSUE TITLE
Test (itest-eth_legacy_transactions) is flaky

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#12304]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
v1.28.1
```

### Repro Steps

https://github.com/filecoin-project/lotus/actions/runs/10086420086/job/27888967468?pr=12303#logs

### Describe the Bug

https://github.com/filecoin-project/lotus/actions/runs/10086420086/job/27888967468?pr=12303#logs

### Logging Information

```text
https://github.com/filecoin-project/lotus/actions/runs/10086420086/job/27888967468?pr=12303#logs
```

**Comment by rvagg** [comment]
Addressed in https://github.com/filecoin-project/lotus/pull/12200

Probably also https://github.com/filecoin-project/lotus/pull/12219 helps. Either way this should have been addressed on master already.
