### ISSUE TITLE
Expose dht FindPeer through RPC

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#1232]
In order to more easily look up miners on the network, we should provide a 'FindPeer' RPC method.

requested by @steven004 for work on filscan.io

**Comment by steven004** [comment]
This will also benefit clients to know more information of a storage miner, including IP address and geographic location before making a deal.

**Comment by whyrusleeping** [comment]
We should add a `NetFindPeer` api endpoint to expose this, then also write a command to invoke it

**Comment by whyrusleeping** [comment]
Relevant function signature: https://github.com/libp2p/go-libp2p-core/blob/master/routing/routing.go#L43

**Comment by arajasek** [comment]
Done in #1276
