### ISSUE TITLE
[WIP] Lotus Node v1.29.0 Release

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#12343]
# Lotus Node 1.29.0 Release

[//]: # (Below are non-visible steps intended for the issue creator)
[//]: # (Start an issue with title "[WIP] Lotus Node|Miner v1.29.0" and adjust the title for whether it's a Node or Miner release.)
[//]: # (Copy in the content of https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md)
[//]: # (Find/Replace "X.Y.Z" with the actual values.)
[//]: # (Copy/paste the "Release Checklist > RC1" section to "Release Checklist > Stable \(non-RC\) Release" and apply the "diff" called out there.)
[//]: # (Find/Replace "RCX" with "RC1".)
[//]: # (If this isn't a release tied to a network upgrade, remove all items with "\(network upgrade\)")
[//]: # (Adjust the "Meta" section values.)
[//]: # (Apply the `tpm` label to the issue)
[//]: # (Create the issue)
[//]: # (Pin the issue on GitHub)

## 😶‍🌫 Meta
* Scope: Node
* Is this linked with a network upgrade, and thus mandatory? No
* Related network upgrade version: n/a

## 🚢 Estimated shipping date

[//]: # (If/when we know an exact date, remove the "week of".)
[//]: # (If a date week is an estimate, annotate with "estimate".)

| Candidate | Date | Release URL |
|-----------|------|-------------|
| RC1 | Week of 2024-08-19 | https://github.com/filecoin-project/lotus/releases/tag/v1.29.0-rc1 |
| Stable (non-RC) | Week of 2024-09-01 | https://github.com/filecoin-project/lotus/releases/tag/v1.29.0 |

## 🪢 Dependencies for releases
> [!NOTE]
> 1. This is the set of changes that need to make it in for a given RC.  This is effectively the set of changes to cherry-pick from master.  
> 2. They can be checked as done once they land in `master`.  
> 3. They are presented here for quick reference, but backporting is tracked in each `Release Checklist`.

[//]: # (Copy/paste this for each RC, and increment "X")
### RC1
- [x] https://github.com/filecoin-project/lotus/pull/12327

### Stable (non-RC)
- [x] ~https://github.com/filecoin-project/lotus/issues/12414~
   - Noted in the changelog that we are releasing v1.29.0 without this fix.

### Before RC1
- [x] Open PR against [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) with title `docs(v1.29.0): release template improvements` for improving future releases.
   - Link to PR:  https://github.com/filecoin-project/lotus/pull/12378
   - This will get merged in a `Post Release` step, but improvements are better done by collecting notes along the way rather than just thinking about it at the end.
- [x] Fork a new branch (`release/v1.29.0` or `release/miner/v1.29.0`) from `master` and make any further release-related changes to this branch.
- `master` branch Version string updates
   - [x] bump the version(s) in `build/version.go` to `v1.29.1-dev`. 
      - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
   - [x] Run `make gen && make docsgen-cli` before committing changes.
   - [x] Create a PR with title `build: v1.29.1 set initial version string`
     - Link to PR: https://github.com/filecoin-project/lotus/pull/12409
   - [x] Merge PR

### RCs

[//]: # (Copy/paste this "RC1" section for each additional RC, and increment "X")
#### RC1
> [!IMPORTANT]
> These PRs should be done in and target the `release/v1.29.0` or `release/miner/v1.29.0` branch.

**Backport PR**

[//]: # (For RC1 there likely isn't any backporting to do and thus no PR which reduces the steps.)
[//]: # (We do need all these steps for RC2 onwards though.)
[//]: # (If steps are removed for the RC1 checklist, they need to be preserved for future RCs/stable.)
[//]: # (For RC1 we still need to make sure the tracked items land though.)
- [x] All explicitly tracked items from `Dependencies for releases` have landed
- [x] Backported [everything with the "backport" label](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+) 
- [x] Removed the "backport" label from all backported PRs (no ["backport" issues](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+))
- [x] Create a PR with title `build: backport changes for v1.29.0-rcX`
   - Link to PR: 
- [x] Merge PR 

**Release PR**

- [x] Update the version string(s) in `build/version.go` to one ending with '-rcX'. 
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Changelog prep
   - [x] Editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas: `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, mergedAt, .author.login, .title] | @tsv' | sort -k4
- [x] Create a PR with title `build: release v1.29.0-rcX`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12410
   - Opening a PR will trigger a CI run that will build assets, create a draft GitHub release, and attach the assets.
- [x] Merge the PR
   - Opening the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
 - [x] Update `🚢 Estimated shipping date` table
 - [x] Comment on this issue announcing the RC
    - Link to issue comment: https://github.com/filecoin-project/lotus/issues/12343#issuecomment-2306570494

### Testing
> [!NOTE]
> Link to any special steps for testing releases beyond ensuring CI is green.  Steps can be inlined here or tracked elsewhere.

### Stable (non-RC) Release

> [!IMPORTANT]
> These PRs should be done in and target the `release/v1.29.0` or `release/miner/v1.29.0` branch.

**Backport PR**

- [x] All explicitly tracked items from `Dependencies for releases` have landed
- [x] Backported [everything with the "backport" label](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+) 
- [x] Removed the "backport" label from all backported PRs (no ["backport" issues](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+))

**Release PR**

- [x] Update the version string(s) in `build/version.go` to one **NOT** ending with '-rcX'. 
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Changelog prep
   - [x] Editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas: `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, mergedAt, .author.login, .title] | @tsv' | sort -k4
- [x] Create a PR with title `build: release v1.29.0`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12422
   - Opening a PR will trigger a CI run that will build assets, create a draft GitHub release, and attach the assets.
- [x] Merge the PR
   - Opening the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
 - [x] Update `🚢 Estimated shipping date` table
 - [x] Comment on this issue announcing the RC
    - Link to issue comment: https://github.com/filecoin-project/lotus/issues/12343#issuecomment-2324711494 

### Post-Release

- [x] Open a pull request against `master` with a merge of the `release/v1.29.0` branch. 
   - [x] Conflict resolution should ignore the changes to `version.go` (keep the `-dev` version from master). 
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12425
- [ ] Finish updating/merging the [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) PR from `Before RC1` with any improvements determined from this latest release iteration.

## ❤️ Contributors

See the final release notes!

## ⁉️ Do you have questions?

Leave a comment in this ticket!

**Comment by BigLep** [comment]
@rjan90 : FYI that the issue description has been populated with the latest https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md

I did the initial setup steps listed in the hidden comments.  In the process I found a few things to edit in the template and so created the PR for that here: https://github.com/filecoin-project/lotus/pull/12373

**Comment by BigLep** [comment]
Replacement PR where tracking release improvements: https://github.com/filecoin-project/lotus/pull/12378

**Comment by rjan90** [comment]
### 2024-08-15

Updated estimated shipping dates, due to the need for landing patch releases for Lotus Node | Lotus Miner. Estimate that RC1 will be out early next week.
| Candidate | Date | Release URL |
|-----------|------|-------------|
| RC1 | Week of 2024-08-19 | |

**Comment by rjan90** [comment]
### 2024-08-23

The first release candidate of Lotus Node v1.29.0 has been shipped: https://github.com/filecoin-project/lotus/releases/tag/v1.29.0-rc1
