### ISSUE TITLE
Lotus Node and Miner Release v1.31.0 (nv24++)

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#12344]
> [!NOTE]
> This release is _nv24++_ meaning it will have the minimum functionality needed for nv24 (i.e., what is in [v1.30.0](https://github.com/filecoin-project/lotus/issues/12480)), but also some additional functionality that is higher risk that we don't want to obligate users to upgrade to during a network upgrade.

## 😶‍🌫 Meta
* Scope: Node and Miner MINOR
* Is this linked with a network upgrade, and thus mandatory? Yes
* (network upgrade) Related network upgrade version: nv24
   * (network upgrade) Scope, dates, and epochs: https://github.com/filecoin-project/community/discussions/74#discussioncomment-10807265
   * (network upgrade) Lotus changelog with Lotus specifics: <link to section in https://github.com/filecoin-project/lotus/blob/master/CHANGELOG.md with more details>

## 🚢 Estimated shipping date

[//]: # (If/when we know an exact date, remove the "week of".)
[//]: # (If a date week is an estimate, annotate with "estimate".)

| Candidate | Date | Release URL |
|-----------|------|-------------|
| RC1 | 2024-11-12 | https://github.com/filecoin-project/lotus/releases/tag/v1.31.0-rc1 https://github.com/filecoin-project/lotus/releases/tag/miner%2Fv1.31.0-rc1 |
| Stable (non-RC) | 2024-12-02 | https://github.com/filecoin-project/lotus/releases/tag/v1.31.0 https://github.com/filecoin-project/lotus/releases/tag/miner/v1.31.0 |

## 🪢 Dependencies for releases
> [!NOTE]
> 1. This is the set of changes that need to make it in for a given RC.  This is effectively the set of changes to cherry-pick from master.  
> 2. They can be checked as done once they land in `master`.  
> 3. They are presented here for quick reference, but backporting is tracked in each `Release Checklist`.

[//]: # (Copy/paste this for each RC, and increment "X")
### rc1
- [x] https://github.com/filecoin-project/lotus/issues/12453 
- [x] https://github.com/filecoin-project/filecoin-ffi/issues/490

### Stable (non-RC)
- [x] https://github.com/filecoin-project/lotus/pull/12603
- [x] https://github.com/filecoin-project/lotus/pull/12694
- [x] https://github.com/filecoin-project/lotus/pull/12695
- [x] https://github.com/filecoin-project/lotus/pull/12698
- [x] https://github.com/filecoin-project/lotus/pull/12700
- [x] https://github.com/filecoin-project/lotus/pull/12708
- [x] https://github.com/filecoin-project/lotus/pull/12720
- [x] https://github.com/filecoin-project/lotus/pull/12725
- [x] https://github.com/filecoin-project/lotus/pull/12729

### Before RC1
- [x] (network upgrade) Make sure all [Lotus dependencies are updated to the correct versions for the network upgrade](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/Update_Dependencies_Lotus.md)
   - Link to Lotus PR:
- [x] Open PR against [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) with title `docs(release): v1.31.0 release template improvements` for improving future releases.
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12563
   - There likely aren't any changes at this point, but this can be opened with a small whitespace change so the PR is open and we can more easily hold the standard of making improvements incrementally since improvements are usually better done by collecting changes/notes along the way rather than just thinking about it at the end.
   - This will get merged in a `Post Release` step.
- [x] (minor release) Fork a new branch (`release/v1.31.0` or `release/miner/v1.31.0`) from `master` and make any further release-related changes to this branch.
- `master` branch Version string updates
   - Skip this set of steps if you are patching a previous minor release. 
   - [x] bump the version(s) in `build/version.go` to `v1.31.1-dev`. 
      - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
   - [x] Run `make gen && make docsgen-cli` before committing changes.
   - [x] Update the CHANGELOG
     - [x] Change the `UNRELEASED` section header to `UNRELEASED v1.31.0`
     - [x] Set the `UNRELEASED v1.31.0` section's content to be "_See https://github.com/filecoin-project/lotus/blob/release/v1.31.0/CHANGELOG.md_"
     - [x] Add a new `UNRELEASED` header to top.
   - [x] Create a PR with title `build: update Lotus Node version to v1.31.1-dev in master`
     - Link to PR: https://github.com/filecoin-project/lotus/pull/12692
   - [x] Merge PR

### RCs

[//]: # (Copy/paste this whole "rc1" section for each additional RC, and increment "X")
#### rc1
> [!IMPORTANT]
> These PRs should be done in and target the `release/v1.31.0` or `release/miner/v1.31.0` branch.

**Backport PR**

[//]: # (For RC1 there likely isn't any backporting to do and thus no PR which reduces the steps.)
[//]: # (We do need all these steps for RC2 onwards though.)
[//]: # (If steps are removed for the RC1 checklist, they need to be preserved for future RCs/stable.)
[//]: # (For RC1 we still need to make sure the tracked items land though.)
- [x] All explicitly tracked items from `Dependencies for releases` have landed
- [x] Backported [everything with the "backport" label](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+) 
- [x] Removed the "backport" label from all backported PRs (no ["backport" issues](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+))
- [x] Create a PR with title `build: backport changes for node v1.31.0-rc1`
   - Link to PR: 
- [x] Merge PR 

**Release PR**

- [x] Update the version string(s) in `build/version.go` to one ending with '-rc1'. 
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Create a draft PR with title `build: release Lotus node v1.31.0-rc1`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12693
   - Opening a PR will trigger a CI run that will build assets, create a draft GitHub release, and attach the assets.
- [x] Changelog prep
   - [x] Go to the [releases page](https://github.com/filecoin-project/lotus/releases) and copy the auto-generated release notes into the CHANGELOG
   - [x] Perform editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] (network upgrade) Specify whether the Calibration or Mainnet upgrade epoch has been specified or not yet.
      - Example where these weren't specified yet: [PR #12169](https://github.com/filecoin-project/lotus/pull/12169)
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas (where `YYYY-MM-DD` is the start search date): `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, .mergedAt, .author.login, .title] | @tsv' | sort -k4`
    - [x] Update the PR with the commit(s) made to the CHANGELOG
- [x] Mark the PR "ready for review" (non-draft)
- [x] Merge the PR
   - Merging the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
 - [x] Update `🚢 Estimated shipping date` table
 - [x] Comment on this issue announcing the RC
    - Link to issue comment: https://github.com/filecoin-project/lotus/issues/12344#issuecomment-2483807857

**Testing**
> [!NOTE]
> Link to any special steps for testing releases beyond ensuring CI is green.  Steps can be inlined here or tracked elsewhere.

### Stable (non-RC) Release

> [!IMPORTANT]
> These PRs should be done in and target the `release/v1.31.0` or `release/miner/v1.31.0` branch.

**Backport PR**

- [x] All explicitly tracked items from `Dependencies for releases` have landed
- [x] Backported [everything with the "backport" label](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+) 
- [x] Removed the "backport" label from all backported PRs (no ["backport" issues](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+))
- [x] Create a PR with title `build: backport changes for node v1.31.0`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12721
- [x] Merge PR 

**Release PR**

- [x] Update the version string(s) in `build/version.go` to one **NOT** ending with '-rc1'. 
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Create a draft PR with title `build: release Lotus node v1.31.0`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12735
   - Opening a PR will trigger a CI run that will build assets, create a draft GitHub release, and attach the assets.
- [x] Changelog prep
   - [x] Go to the [releases page](https://github.com/filecoin-project/lotus/releases) and copy the auto-generated release notes into the CHANGELOG
   - [x] Perform editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas (where `YYYY-MM-DD` is the start search date): `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, .mergedAt, .author.login, .title] | @tsv' | sort -k4`
    - [x] Update the PR with the commit(s) made to the CHANGELOG
- [x] Mark the PR "ready for review" (non-draft)
- [x] Merge the PR
   - Merging the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
 - [x] Update `🚢 Estimated shipping date` table
 - [x] Comment on this issue announcing the RC
    - Link to issue comment: https://github.com/filecoin-project/lotus/issues/12344#issuecomment-2510802533

**Testing**
> [!NOTE]
> Link to any special steps for testing releases beyond ensuring CI is green.  Steps can be inlined here or tracked elsewhere.

### Post-Release

- [x] Open a PR against `master` cherry-picking the CHANGELOG commits from the `release/v1.31.0` branch. Title it `chore(release): cherry-pick v1.31.0 changelog back to master`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12746
   - Assuming we followed [the process of merging changes into `master` first before backporting to the release branch](https://github.com/filecoin-project/lotus/blob/master/LOTUS_RELEASE_FLOW.md#branch-and-tag-strategy), the only changes should be CHANGELOG updates.  
- [x] Finish updating/merging the [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) PR from `Before RC1` with any improvements determined from this latest release iteration.

## ❤️ Contributors

See the final release notes!

## ⁉️ Do you have questions?

Leave a comment in this ticket!

**Comment by BigLep** [comment]
The issue description was updated to make clear that this will be a parallel release to [v1.30.0](https://github.com/filecoin-project/lotus/issues/12480) and that it will include functionality beyond what is required for nv24.

**Comment by BigLep** [comment]
@rjan90 : FYI I populated the release issue with the template.

**Comment by BigLep** [comment]
RC1 was shipped on 2024-11-12:
https://github.com/filecoin-project/lotus/releases/tag/v1.31.0-rc1
https://github.com/filecoin-project/lotus/releases/tag/miner%2Fv1.31.0-rc1

**Comment by BigLep** [comment]
@rjan90:
1. I update the issue title and [description](https://github.com/filecoin-project/lotus/issues/12344#issue-2449221938) to make clear this is a Node and Miner release.
2. I added an rc2 section to the [description](https://github.com/filecoin-project/lotus/issues/12344#issue-2449221938).
3. I know we talked about it, but I'm completely forgetting why we decided we need a miner release as well.  Do you mind adding a comment so it's documented (and to help me remember).  Thanks - sorry I'm not self-sufficient on this one.

**Comment by rjan90** [comment]
Thanks for catching, and updating this issue. Missed a couple of things while ✈️.

> I know we talked about it, but I'm completely forgetting why we decided we need a miner release as well. Do you mind adding a comment so it's documented (and to help me remember). Thanks - sorry I'm not self-sufficient on this one.

We decided to do a lotus-miner release as well release to allow thorough testing of PR #12690. This PR modifies the mining loop, which is considered highly sensitive code and requires careful validation.

**Comment by rjan90** [comment]
The stable releases of v1.31.0 has been published here:
- https://github.com/filecoin-project/lotus/releases/tag/v1.31.0
- https://github.com/filecoin-project/lotus/releases/tag/miner/v1.31.0

**Comment by rjan90** [comment]
Closing as the stable release of v1.31.0 has been released
