### ISSUE TITLE
Filecoin.StateCirculatingSupply method is not working right after nvm23

### ISSUE THREAD

**Issue by ArseniiPetrovich** [filecoin-project/lotus#12347]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.28.1+mainnet+git.4950c4b+api1.5.0
Local: lotus version 1.28.1+mainnet+git.4950c4b
```

### Repro Steps

1. Run 'Filecoin.StateCirculatingSupply'
2. See error `{"error":{"code":1,"message":"unexpected actor: f07"},"id":1,"jsonrpc":"2.0"}`

### Describe the Bug

The StateCirculatingSupply function stopped working which is affecting any calculcations that are based on that method.

### Logging Information

```text
There are no related logs except but `{"error":{"code":1,"message":"unexpected actor: f07"},"id":1,"jsonrpc":"2.0"}`. Glif Nodes logs would be way too spammed for me to provide anything meaningful here.
```

**Comment by rjan90** [comment]
Hey @ArseniiPetrovich - thanks for the issue ticket.

This was also one of the issues that I encountered when completing the NV23 checklist: https://docs.google.com/document/d/11jN9E4IcgcbU_6acAIHuh29v7yGFj7OHiiGYpoUuSEs/edit?disco=AAABTRqPuzA. I will highlight it to the engineers to look into this, so that we can unblock you.
