### ISSUE TITLE
add ETH DB GC config

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#12355]
while EnableEthRPC is set to false by default, however, node operators may enable it if they are 
1. indexer / RPC / explorer nodes: who may want to get event/message index and keep a record of it
2.  dapp users, like SPs who are hoping to take onchain deals.

For users that fit under category 2, they shall only care about listening to events from now and forward, and likely most events are only meaningful for a certain period of time or they have to react to the event as soon as they get it - that said, historical events are not useful for them.

For these users, we should have an auto gc process, to prune the event & msg index db automatically so to reduce the node load.
I think as a good start, add a config to allow auto GC every X epochs, where X is defined by users is a good start

**Comment by rvagg** [comment]
dealt with by chainindexer
