### ISSUE TITLE
mac m3 chip make lotus prompt ld: library 'hwloc' not found

### ISSUE THREAD

**Issue by gsp-hub** [filecoin-project/lotus#12365]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.28.1
```

### Repro Steps

1.brew install go bzr jq pkg-config hwloc coreutils

2.curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

3.git clone https://github.com/filecoin-project/lotus.git
cd lotus/

4. make

### Describe the Bug

rm -f lotus
go build  -ldflags="-s -w -X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.34a12db.dirty" -o lotus ./cmd/lotus
# github.com/filecoin-project/lotus/cmd/lotus
/opt/homebrew/Cellar/go/1.22.6/libexec/pkg/tool/darwin_arm64/link: running cc failed: exit status 1
ld: warning: ignoring duplicate libraries: '-lSystem', '-lc', '-lhwloc', '-liconv', '-lm', '-lproc', '/Users/spgao/lotus/extern/filecoin-ffi/libfilcrypto.a'
ld: library 'hwloc' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [lotus] Error 1

### Logging Information

```text
# github.com/filecoin-project/lotus/cmd/lotus
/opt/homebrew/Cellar/go/1.22.6/libexec/pkg/tool/darwin_arm64/link: running cc failed: exit status 1
ld: warning: ignoring duplicate libraries: '-lSystem', '-lc', '-lhwloc', '-liconv', '-lm', '-lproc', '/Users/spgao/lotus/extern/filecoin-ffi/libfilcrypto.a'
ld: library 'hwloc' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by gsp-hub** [comment]
My mac installed the required environment once before when nv22, when I cloned the latest lotus again directly and made it, I found this prompt, I tried to find ways to fix it (according to the https://lotus.filecoin.io/lotus/install/macos/ page macOS steps), but they all failed! .

**Comment by gsp-hub** [comment]
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/50125591-e729-4b01-9d21-8cb0856bdbbf">
export LIBRARY_PATH=/opt/homebrew/lib
Yes there is no such variable, and when I set it, a new error was reported

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/05ba3f7b-605b-455c-8115-a230b1dc9c60">

**Comment by gsp-hub** [comment]
<img width="1379" alt="image" src="https://github.com/user-attachments/assets/332262f7-f788-45df-858b-bcca4a9523db">
Yes there is no such variable, and when I set it, a new error was reported

**Comment by rvagg** [comment]
those warnings should be ignorable in most cases

**Comment by gsp-hub** [comment]
Ok I found it, it's an alert but it doesn't affect the program generation.thanks for your support @rvagg  @ribasushi
