### ISSUE TITLE
Lotus Miner & Node v1.28.2 Release 

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#12379]
# Lotus Miner and Node v1.28.2 Release

[//]: # (Below are non-visible steps intended for the issue creator)
[//]: # (Start an issue with title "[WIP] Lotus Node|Miner vX.Y.Z Release" and adjust the title for whether it's a Node or Miner release.)
[//]: # (Copy in the content of https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md)
[//]: # (Find/Replace "X.Y.Z+1" with the actual values.  This is intentinoally done before tbe find/replace X.Y.Z step because that will also match.)
[//]: # (Find/Replace "X.Y.Z" with the actual values.)
[//]: # (If this isn't a release tied to a network upgrade, remove all items with "\(network upgrade\)")
[//]: # (Copy/paste the "Release Checklist > RCX" section to "Release Checklist > Stable \(non-RC\) Release" and apply the "diff" called out there.)
[//]: # (Find/Replace case sensitive "RCX" with "RC1".)
[//]: # (Adjust the "Meta" section values.)
[//]: # (Apply the `tpm` label to the issue)
[//]: # (Create the issue)
[//]: # (Pin the issue on GitHub)

## 😶‍🌫 Meta
* Scope: Miner & Node
* Is this linked with a network upgrade, and thus mandatory? No
* Related network upgrade version: n/a

## 🚢 Estimated shipping date

[//]: # (If/when we know an exact date, remove the "week of".)
[//]: # (If a date week is an estimate, annotate with "estimate".)

| Candidate | Date | Release URL |
|-----------|------|-------------|
| Stable (non-RC) | Week of 2024-08-12 | https://github.com/filecoin-project/lotus/releases/tag/v1.28.2 |

## 🪢 Dependencies for releases
> [!NOTE]
> 1. This is the set of changes that need to make it in for a given RC.  This is effectively the set of changes to cherry-pick from master.  
> 2. They can be checked as done once they land in `master`.  
> 3. They are presented here for quick reference, but backporting is tracked in each `Release Checklist`.

[//]: # (Copy/paste this for each RC, and increment "X")

### Stable (non-RC)
- [x] https://github.com/filecoin-project/lotus/pull/12341
- [x] https://github.com/filecoin-project/lotus/pull/12395

### Before Release
- [x] Open PR against [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) for capturing updates: https://github.com/filecoin-project/lotus/pull/12378
- [x] Fork a new branch (`release/v1.28.2`) from `release/v1.28.2` and make any further release-related changes to this branch.
- `master` branch Version string updates
   - [x] bump the version(s) in `build/version.go` to `vX.Y.Z+1-dev`. 
      - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
   - [x] Run `make gen && make docsgen-cli` before committing changes.
   - [x] Create a PR with title `build(vX.Y.Z+1): set initial version string`
     - Link to PR: https://github.com/filecoin-project/lotus/pull/12380
   - [x] Merge PR

**Stable Release PR**

- [x] Update the version string(s) in `build/version.go` to one **NOT** ending with '-rcX'. 
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Changelog prep
   - [x] Editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] (network upgrade) Specify whether the Calibration or Mainnet upgrade epoch has been specified or not yet.
      - Example where these weren't specified yet: [PR #12169](https://github.com/filecoin-project/lotus/pull/12169)
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas: `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, mergedAt, .author.login, .title] | @tsv' | sort -k4
- [x] Create a PR with title `build(vX.Y.Z): release vX.Y.Z`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12392
   - Opening a PR will trigger a CI run that will build assets, and attach the assets.
- [x] Merge the PR
   - Opening the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
- [x] Publish the release:
   - “Draft a new release” in GH
   - Choose the release/v1.28.2 branch, for the tag, set it to v1.28.2 - and create title + description.
- [x] Add the second tag via git cmd´s
   - git checkout v1.28.2
   - git tag miner/v1.28.2
   - git push origin miner/v1.28.2
- [x] Update `🚢 Estimated shipping date` table
- [x] Comment on this issue announcing the release
    - Link to issue comment:   

### Testing
> [!NOTE]
> Link to any special steps for testing releases beyond ensuring CI is green.  Steps can be inlined here or tracked elsewhere.

### Post-Release

- [x] Open a pull request against `master` with a merge of the `release/vX.Y.Z` branch. 
   - [x] Conflict resolution should ignore the changes to `version.go` (keep the `-dev` version from master). 
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12400
- [x] Finish updating/merging the [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) PR from `Before RC1` with any improvements determined from this latest release iteration.

## ❤️ Contributors

See the final release notes!

## ⁉️ Do you have questions?

Leave a comment in this ticket!

**Comment by rjan90** [comment]
Scribbling down some notes while I go through this process and then we can consider. Keep in mind that this is a patch-release, and therefor a little outside the normal release flow:

> - [ ] Fork a new branch (`release/vX.Y.Z` or `release/miner/vX.Y.Z`) from `master` and make any further release-related changes to this branch.

This is only relevant in the case when shipping a normal release (i.e not a patch release)

**Comment by rjan90** [comment]
> Open PR against [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) with title docs(vX.Y.Z): release template improvements for improving future releases.

This is kind of in a weird spot, since we are asking for opening a PR - but unless you have any immediate changes to the RELEASE_ISSUE_TEMPLATE.md file you can´t open a PR.

**Comment by BigLep** [comment]
@rjan90 : not in the critical path of the release itself, but FYI concerning template improvements:
1. I expanded https://github.com/filecoin-project/lotus/pull/12378 to include 1.28.2 and 1.29.0
2. Concerning [differentiating minor vs patch release steps](https://github.com/filecoin-project/lotus/issues/12379#issuecomment-2286158690), I created https://github.com/filecoin-project/lotus/pull/12378/commits/a3747f5171814d45867689ea4fa2e9eec0a1fc89
3. Concerning [opening the RELEASE_ISSUE_TEMPLATE.md improvements early](https://github.com/filecoin-project/lotus/issues/12379#issuecomment-2287981498), I added some text with https://github.com/filecoin-project/lotus/pull/12378/commits/1692ece344b708d1d57f38d3edd280b28f99d5c9

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/lotus/releases/tag/v1.28.2 is a thing

**Comment by rjan90** [comment]
> Finish updating/merging the [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) PR from Before RC1 with any improvements determined from this latest release iteration.

Feedback has been incorporated as part of https://github.com/filecoin-project/lotus/pull/12378. Closing this release ticket now.
