### ISSUE TITLE
Confirmations around rejected transactions

### ISSUE THREAD

**Issue by jesseclay** [filecoin-project/lotus#1241]
**Additional context**
Confirmation that when a transaction is rejected by the node:
-  the transaction will not appear in the mempool
-  an error response will be provided

**Comment by arajasek** [comment]
I confirmed that some simple invalid messages (insufficient balance, invalid nonce, etc.) are correctly rejected by the node. Such messages don't enter the mempool, and a meaningful error response is provided.

If we want a more detailed investigation, we can do that, or write a reproducible test.

**Comment by arajasek** [comment]
Closing this based on conversations with the relevant integ partner that indicate that they are satisfied.
