### ISSUE TITLE
Update Cheggaaa's PB from v1 to v3

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#12433]
Version 3 of the progress bar library we use (Cheggaaa's "pb") was released  quite a while ago. We should update from `gopkg.in/cheggaaa/pb.v1` to `github.com/cheggaaa/pb/v3`, but will need to handle the breaking API changes.

**Comment by virajbhartiya** [comment]
Can I work on this?

**Comment by rvagg** [comment]
@virajbhartiya yep go for it, this should be fairly straightforward 🤞
