### ISSUE TITLE
Lotus Release v1.29.2

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#12464]
## 😶‍🌫 Meta
* Scope: Node PATCH
* Is this linked with a network upgrade, and thus mandatory? No

## 🚢 Estimated shipping date

[//]: # (If/when we know an exact date, remove the "week of".)
[//]: # (If a date week is an estimate, annotate with "estimate".)

| Candidate | Date | Release URL |
|-----------|------|-------------|
| rc1 | Week of 2024-09-23 | https://github.com/filecoin-project/lotus/releases/tag/v1.29.2-rc1 |
| Stable (non-RC) | Week of 2024-10-03 | https://github.com/filecoin-project/lotus/releases/tag/v1.29.2 |

## 🪢 Dependencies for releases
> [!NOTE]
> 1. This is the set of changes that need to make it in for a given RC.  This is effectively the set of changes to cherry-pick from master.  
> 2. They can be checked as done once they land in `master`.  
> 3. They are presented here for quick reference, but backporting is tracked in each `Release Checklist`.

[//]: # (Copy/paste this for each RC, and increment "X")
### rc1
- [x] https://github.com/filecoin-project/lotus/pull/12505
- [x] https://github.com/filecoin-project/lotus/pull/12511
- [x] https://github.com/filecoin-project/lotus/pull/12428

### Stable (non-RC)
- [x] https://github.com/filecoin-project/lotus/pull/12539
- [x] https://github.com/filecoin-project/lotus/pull/12540
   - [x] https://github.com/filecoin-project/lotus/pull/12459

### Before RC1
- [x] Open PR against [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) with title `docs(release): v1.29.2 release template improvements` for improving future releases.
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12479
   - There likely aren't any changes at this point, but this can be opened with a small whitespace change so the PR is open and we can more easily hold the standard of making improvements incrementally since improvements are usually better done by collecting changes/notes along the way rather than just thinking about it at the end.
   - This will get merged in a `Post Release` step.
- [x] (patch release) Fork a new branch (`release/v1.29.2` or `release/miner/v1.29.2`) from the last stable `release/vX.Y.x` or `release/miner/vX.Y.x` and make any further release-related changes to this branch.
- `master` branch Version string updates
   - Skip this set of steps if you are patching a previos minor release. 
   - [x] bump the version(s) in `build/version.go` to `v1.29.3-dev`. 
      - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
   - [x] Run `make gen && make docsgen-cli` before committing changes.
   - [x] Update the CHANGELOG
     - [x] Change the `UNRELEASED` section to `UNRELEASED v1.29.2` and set the section's content to be `See https://github.com/filecoin-project/lotus/blob/release/v1.29.2/CHANGELOG.md`
     - [x] Add a new `UNRELEASED` header to top.
   - [x] Create a PR with title `build: update Lotus Node version to v1.29.3-dev in master`
     - Link to PR: https://github.com/filecoin-project/lotus/pull/12483
   - [x] Merge PR

### RCs

[//]: # (Copy/paste this whole "rc1" section for each additional RC, and increment "X")
#### rc1
> [!IMPORTANT]
> These PRs should be done in and target the `release/v1.29.2` or `release/miner/v1.29.2` branch.

**Backport PR**

[//]: # (For RC1 there likely isn't any backporting to do and thus no PR which reduces the steps.)
[//]: # (We do need all these steps for RC2 onwards though.)
[//]: # (If steps are removed for the RC1 checklist, they need to be preserved for future RCs/stable.)
[//]: # (For RC1 we still need to make sure the tracked items land though.)
- [x] All explicitly tracked items from `Dependencies for releases` have landed
- [x] Backported [everything with the "backport" label](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+) 
- [x] Removed the "backport" label from all backported PRs (no ["backport" issues](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+))
- [x] Create a PR with title `build: backport changes for node|miner v1.29.2-rc1`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12515
- [x] Merge PR 

**Release PR**

- [x] Update the version string(s) in `build/version.go` to one ending with '-rc1'. 
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Create a draft PR with title `build: release Lotus node|miner v1.29.2-rc1`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12515
   - Opening a PR will trigger a CI run that will build assets, create a draft GitHub release, and attach the assets.
- [x] Changelog prep
   - [x] Go to the [releases page](https://github.com/filecoin-project/lotus/releases) and copy the auto-generated release notes into the CHANGELOG
   - [x] Perform editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas (where `YYYY-MM-DD` is the start search date): `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, .mergedAt, .author.login, .title] | @tsv' | sort -k4`
    - [x] Update the PR with the commit(s) made to the CHANGELOG
- [x] Mark the PR "ready for review" (non-draft)
- [x] Merge the PR
   - Merging the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
 - [x] Update `🚢 Estimated shipping date` table
 - [x] Comment on this issue announcing the RC
    - Link to issue comment: https://github.com/filecoin-project/lotus/issues/12464#issuecomment-2379538928 

**Testing**
> [!NOTE]
> Link to any special steps for testing releases beyond ensuring CI is green.  Steps can be inlined here or tracked elsewhere.

### Stable (non-RC) Release

**Backport PR**

[//]: # (For RC1 there likely isn't any backporting to do and thus no PR which reduces the steps.)
[//]: # (We do need all these steps for RC2 onwards though.)
[//]: # (If steps are removed for the RC1 checklist, they need to be preserved for future RCs/stable.)
[//]: # (For RC1 we still need to make sure the tracked items land though.)
- [x] All explicitly tracked items from `Dependencies for releases` have landed
- [x] Backported [everything with the "backport" label](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+) 
- [x] Removed the "backport" label from all backported PRs (no ["backport" issues](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+))
- [x] Create a PR with title `build: backport changes for node v1.29.2`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12541
- [x] Merge PR 

**Release PR**

- [x] Update the version string in `build/version.go` to one **NOT** ending with '-rc1'
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Create a PR with title `build: release Lotus node v1.29.2`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12541
   - Opening a PR will trigger a CI run that will build assets, create a draft GitHub release, and attach the assets.
- [x] Changelog prep
   - [x] Go to the [releases page](https://github.com/filecoin-project/lotus/releases) and copy the auto-generated release notes into the CHANGELOG
   - [x] Perform editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas (where `YYYY-MM-DD` is the start search date): `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, .mergedAt, .author.login, .title] | @tsv' | sort -k4`
    - [x] Update the PR with the commit(s) made to the CHANGELOG
- [x] Mark the PR "ready for review" (non-draft)
- [x] Merge the PR
   - Merging the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
 - [x] Update `🚢 Estimated shipping date` table
 - [x] Comment on this issue announcing the RC
    - Link to issue comment: https://github.com/filecoin-project/lotus/issues/12464#issuecomment-2391057825 

**Testing**
> [!NOTE]
> Link to any special steps for testing releases beyond ensuring CI is green.  Steps can be inlined here or tracked elsewhere.

### Post-Release

- [x] Open a pull request against `master` cherry-picking the CHANGELOG commits from the `release/v1.29.2` branch. 
   - Link to PR: 
   - Assuming we followed [the process of merging changes into `master` first before backporting to the release branch](https://github.com/filecoin-project/lotus/blob/master/LOTUS_RELEASE_FLOW.md#branch-and-tag-strategy), the only changes should be CHANGELOG updates.  
- [x] Finish updating/merging the [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) PR from `Before RC1` with any improvements determined from this latest release iteration.

## ❤️ Contributors

See the final release notes!

## ⁉️ Do you have questions?

Leave a comment in this ticket!

**Comment by BigLep** [comment]
I've renamed this to v1.29.2 since we're pushing a v1.29.1 imminently as part of resolving https://github.com/filecoin-project/lotus/issues/12467

**Comment by BigLep** [comment]
@rjan90 : FYI I populated this with the latest changes from https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md and I started the release template improvements PR: https://github.com/filecoin-project/lotus/pull/12479

**Comment by BigLep** [comment]
@rjan90 : I'm not sure if you were still planning to get a release this week, but it seems likely to me that the "open for RC1" items won't land this week:
* https://github.com/filecoin-project/lotus/pull/12478 - Still in code review process and @rvagg is out starting 2024-09-20.  Maybe it gets done 2024-09-19, but if not it will need to wait or have Aarsh jump in to help.
* https://github.com/filecoin-project/lotus/pull/12428 - Needs proper review per [here](https://github.com/filecoin-project/lotus/pull/12428#issuecomment-2359597505), but I assume with colos it won't happen this week.

**Comment by rjan90** [comment]
> @rjan90 : I'm not sure if you were still planning to get a release this week, but it seems likely to me that the "open for RC1" items won't land this week:

Yes, it seems likely that these will only be able to land in the `Week of 2024-09-23`. I have adjusted the Estimated Shipping Dates table for RC1 accordingly.

**Comment by rjan90** [comment]
### 2024-09-27 

The first release candidate for v1.29.2 has now been shipped: https://github.com/filecoin-project/lotus/releases/tag/v1.29.2-rc1

**Comment by rjan90** [comment]
## 2024-10-03

The stable release has now been shipped: https://github.com/filecoin-project/lotus/releases/tag/v1.29.2
