### ISSUE TITLE
ChainIndexer should be able to GC at a cadence of epochs instead of days

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#12465]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

This is for https://github.com/filecoin-project/lotus/pull/12421#discussion_r1760555985.

At present, `ChainIndexer` can only gc `eth_tx_hash` at a cadence of days. However, we should change this so it has a cadence of epochs.

### Describe the solution you'd like

Update the ChainIndex GC logic and DDL queries so it can remove entries from the `eth_tx_hash` table at a cadence of epochs.

**Comment by aarshkshah1992** [comment]
@akaladarshi Wanna pick up this one ?

**Comment by akaladarshi** [comment]
> @akaladarshi Wanna pick up this one ?

Yeah sure, I can pick this up.

**Comment by BigLep** [comment]
I updated the issue title to be more accurate (I think).  Please fix if I got it wrong.

**Comment by aarshkshah1992** [comment]
@akaladarshi Please feel free to raise a PR on top of https://github.com/filecoin-project/lotus/pull/12450.

**Comment by rjan90** [comment]
Closing ticket as completed by: https://github.com/filecoin-project/lotus/pull/12516
