### ISSUE TITLE
Lotus Release v1.29.1

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#12470]
# Lotus Node1.29.1 Release

[//]: # (Below are non-visible steps intended for the issue creator)
[//]: # (❗️ Complete the steps below as part of creating a release issue and mark them complete with an X or ✅ when done.)
[//]: # ([✅] Start an issue with title "[WIP] Lotus Node|Miner v1.29.1 Release" and adjust the title for whether it's a Node or Miner release.)
[//]: # ([✅] Copy in the content of https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md)
[//]: # ([✅] Find/Replace "1.29.2" with the actual values. This is intentionally done before the find/replace 1.29.1 step because that will also match.)
[//]: # ([✅] Find/Replace "1.29.1" with the actual values.)
[//]: # ([✅] If this isn't a release tied to a network upgrade, remove all items with "\(network upgrade\)")
[//]: # ([✅] If this is a patch release, remove all items with "\(minor release\)")
[//]: # ([✅] If this is a minor release, remove all items with "\(patch release\)")
[//]: # ([✅] Copy/paste the "Release Checklist > RCX" section to "Release Checklist > Stable \(non-RC\) Release" and apply the "diff" called out there.)
[//]: # ([✅] Find/Replace "RCX" with "RC1".)
[//]: # ([✅] Adjust the "Meta" section values.)
[//]: # ([✅] Apply the `tpm` label to the issue)
[//]: # ([✅] Create the issue)
[//]: # ([✅] Pin the issue on GitHub)

## 😶‍🌫 Meta
* Scope: Node PATCH
* Is this linked with a network upgrade, and thus mandatory? No
* Related network upgrade version: n/a

## 🚢 Estimated shipping date

[//]: # (If/when we know an exact date, remove the "week of".)
[//]: # (If a date week is an estimate, annotate with "estimate".)

| Candidate | Date | Release URL |
|-----------|------|-------------|
| Stable (non-RC) | 2024-09-16 | |

## 🪢 Dependencies for releases
> [!NOTE]
> 1. This is the set of changes that need to make it in for a given RC.  This is effectively the set of changes to cherry-pick from master.  
> 2. They can be checked as done once they land in `master`.  
> 3. They are presented here for quick reference, but backporting is tracked in each `Release Checklist`.

- [x] https://github.com/filecoin-project/lotus/pull/12469

### Before RC1
- [x] (patch release) Fork a new branch (`release/v1.29.1`) from the last stable `release/v1.29.0` and make any further release-related changes to this branch.

#### Stable (non-RC) Release
> [!IMPORTANT]
> These PRs should be done in and target the `release/v1.29.1` or `release/miner/v1.29.1` branch.

**Backport PR**

- [x] ~All explicitly tracked items from `Dependencies for releases` have landed~
- [x] Backported [everything with the "backport" label](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+) 
- [x] Removed the "backport" label from all backported PRs (no ["backport" issues](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+))
- [x] Create a PR with title `build: backport changes for node|miner v1.29.1-rcX`
   - Link to PR: this is happening in the Release PR below
- [x] ~Merge PR~: this is happening in the Release PR below

**Release PR**

- [x] Update the version string in `build/version.go` to one **NOT** ending with '-rcX'
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Changelog prep
   - [ ] ~Go to the [releases page](https://github.com/filecoin-project/lotus/releases) and copy the auto generated changelog into your release PR and adjust the changelog accordingly.~
   - [x] Editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas (where `YYYY-MM-DD` is the start search date): `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, .mergedAt, .author.login, .title] | @tsv' | sort -k4`
- [x] Create a PR with title `build: release v1.29.1`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12471
   - Opening a PR will trigger a CI run that will build assets, create a draft GitHub release, and attach the assets.

- [x] Merge the PR
   - Opening the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
- [x] Copy/paste changelog content into the release
- [x] Update `🚢 Estimated shipping date` table
- [x] Comment on this issue announcing the release
    - Link to issue comment: https://github.com/filecoin-project/lotus/issues/12470#issuecomment-2353770946

### Post-Release

- [ ] Open a pull request against `master` cherry-picking the CHANGELOG commits from the `release/v1.29.1` branch. 
   - Link to PR: 
   - Assuming we followed [the process of merging changes into `master` first before backporting to the release branch](https://github.com/filecoin-project/lotus/blob/master/LOTUS_RELEASE_FLOW.md#branch-and-tag-strategy), the only changes should be CHANGELOG updates.  
- [ ] Finish updating/merging the [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) PR from `Before RC1` with any improvements determined from this latest release iteration.

## ❤️ Contributors

See the final release notes!

## ⁉️ Do you have questions?

Leave a comment in this ticket!

**Comment by BigLep** [comment]
PR for this release: https://github.com/filecoin-project/lotus/pull/12471

**Comment by rjan90** [comment]
Lotus v1.29.1 release has now been published: https://github.com/filecoin-project/lotus/releases/tag/v1.29.1

**Comment by BigLep** [comment]
PR (that needs to be filled in) for updating the release process based on lessons learned: https://github.com/filecoin-project/lotus/pull/12473

**Comment by BigLep** [comment]
Closing since the release was released and the release template updates were meged: https://github.com/filecoin-project/lotus/pull/12473
