### ISSUE TITLE
Lotus Node & Miner Release v1.30.0 (nv24)

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#12480]
## 😶‍🌫 Meta
* Scope: Node & Miner
* Is this linked with a network upgrade, and thus mandatory? 
* (network upgrade) Related network upgrade version: nv24
   * (network upgrade) Scope, dates, and epochs: https://github.com/filecoin-project/community/discussions/74#discussioncomment-10807265
   * (network upgrade) Lotus changelog with Lotus specifics: <link to section in https://github.com/filecoin-project/lotus/blob/master/CHANGELOG.md with more details>

## 🚢 Estimated shipping date

[//]: # (If/when we know an exact date, remove the "week of".)
[//]: # (If a date week is an estimate, annotate with "estimate".)

| Candidate | Date | Release URL |
|-----------|------|-------------|
| RC1 | Week of 2024-10-08 |https://github.com/filecoin-project/lotus/releases/tag/v1.30.0-rc1 https://github.com/filecoin-project/lotus/releases/tag/miner%2Fv1.30.0-rc1 |
| RC2 | Week of 2024-10-14 | https://github.com/filecoin-project/lotus/releases/tag/v1.30.0-rc2 https://github.com/filecoin-project/lotus/releases/tag/miner%2Fv1.30.0-rc2 |
| RC3 | Week of 2024-10-28 | https://github.com/filecoin-project/lotus/releases/tag/v1.30.0-rc3 https://github.com/filecoin-project/lotus/releases/tag/miner%2Fv1.30.0-rc3 |
| Stable | Week of 2024-11-04 |  https://github.com/filecoin-project/lotus/releases/tag/v1.30.0 https://github.com/filecoin-project/lotus/releases/tag/miner%2Fv1.30.0 |

## 🪢 Dependencies for releases
> [!NOTE]
> 1. This is the set of changes that need to make it in for a given RC.  This is effectively the set of changes to cherry-pick from master.  
> 2. They can be checked as done once they land in `master`.  
> 3. They are presented here for quick reference, but backporting is tracked in each `Release Checklist`.

[//]: # (Copy/paste this for each RC, and increment "X")
### rc1
- [x] https://github.com/filecoin-project/lotus/pull/12531
- [x] https://github.com/filecoin-project/lotus/pull/12552
- [x] https://github.com/filecoin-project/lotus/pull/12561

### rc2
- [x] https://github.com/filecoin-project/lotus/pull/12556
- [x] https://github.com/filecoin-project/lotus/pull/12567
- [x] https://github.com/filecoin-project/lotus/pull/12572
- [x] https://github.com/filecoin-project/lotus/pull/12573
- [x] https://github.com/filecoin-project/lotus/pull/12574
- [x] https://github.com/filecoin-project/lotus/pull/12575
- [x] https://github.com/filecoin-project/lotus/pull/12576
- [x] https://github.com/filecoin-project/lotus/pull/12577
- [x] https://github.com/filecoin-project/lotus/pull/12578
- [x] https://github.com/filecoin-project/lotus/pull/12579
- [x] https://github.com/filecoin-project/lotus/pull/12580
- [x] https://github.com/filecoin-project/lotus/pull/12581
- [x] https://github.com/filecoin-project/lotus/pull/12585
- [x] https://github.com/filecoin-project/lotus/pull/12588
- [x] https://github.com/filecoin-project/lotus/pull/12589
- [x] https://github.com/filecoin-project/lotus/pull/12590
- [x] https://github.com/filecoin-project/lotus/pull/12592
- [x] https://github.com/filecoin-project/lotus/pull/12595

### rc3
- [x] https://github.com/filecoin-project/lotus/pull/12597
- [x] https://github.com/filecoin-project/lotus/pull/12602
- [x] https://github.com/filecoin-project/lotus/pull/12608
- [x] https://github.com/filecoin-project/lotus/pull/12615
- [x] https://github.com/filecoin-project/lotus/pull/12620
- [x] https://github.com/filecoin-project/lotus/pull/12621
- [x] https://github.com/filecoin-project/lotus/pull/12627
- [x] https://github.com/filecoin-project/lotus/pull/12634
- [x] https://github.com/filecoin-project/lotus/pull/12637
- [x] https://github.com/filecoin-project/lotus/pull/12640
- [x] https://github.com/filecoin-project/lotus/pull/12641
- [x] https://github.com/filecoin-project/lotus/pull/12647
- [x] https://github.com/filecoin-project/lotus/pull/12648
- [x] https://github.com/filecoin-project/lotus/pull/12649
- [x] https://github.com/filecoin-project/lotus/pull/12650
- [x] https://github.com/filecoin-project/lotus/pull/12651

### Stable (non-RC)
- [x] https://github.com/filecoin-project/lotus/pull/12617
- [x] https://github.com/filecoin-project/lotus/pull/12658
- [x] https://github.com/filecoin-project/lotus/pull/12660
- [x] https://github.com/filecoin-project/lotus/pull/12664
- [x] https://github.com/filecoin-project/lotus/pull/12665
- [x] https://github.com/filecoin-project/lotus/pull/12667
- [x] https://github.com/filecoin-project/lotus/pull/12669
- [x] https://github.com/filecoin-project/lotus/pull/12672
- [x] https://github.com/filecoin-project/lotus/pull/12673
- [x] https://github.com/filecoin-project/lotus/pull/12676

### Before RC1
- [x] (network upgrade) Make sure all [Lotus dependencies are updated to the correct versions for the network upgrade](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/Update_Dependencies_Lotus.md)
   - Link to Lotus PR: https://github.com/filecoin-project/lotus/pull/12526, https://github.com/filecoin-project/lotus/pull/12561
- [x] Open PR against [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) with title `docs(release): v1.30.0 release template improvements` for improving future releases.
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12563
   - There likely aren't any changes at this point, but this can be opened with a small whitespace change so the PR is open and we can more easily hold the standard of making improvements incrementally since improvements are usually better done by collecting changes/notes along the way rather than just thinking about it at the end.
   - This will get merged in a `Post Release` step.
- [x] (minor release) Fork a new branch (`release/v1.30.0` or `release/miner/v1.30.0`) from `master` and make any further release-related changes to this branch.
- `master` branch Version string updates
   - Skip this set of steps if you are patching a previous minor release. 
   - [x] bump the version(s) in `build/version.go` to `v1.30.1-dev`. 
      - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
   - [x] Run `make gen && make docsgen-cli` before committing changes.
   - [x] Update the CHANGELOG
     - [x] Change the `UNRELEASED` section header to `UNRELEASED v1.30.0`
     - [x] Set the `UNRELEASED v1.30.0` section's content to be "_See https://github.com/filecoin-project/lotus/blob/release/v1.30.0/CHANGELOG.md_"
     - [x] Add a new `UNRELEASED` header to top.
   - [x] Create a PR with title `build: update Lotus Node|Miner version to v1.30.1-dev in master`
     - Link to PR: https://github.com/filecoin-project/lotus/pull/12562
   - [x] Merge PR

### RCs

[//]: # (Copy/paste this whole "rcX" section for each additional RC, and increment "X")
#### rc1
> [!IMPORTANT]
> These PRs should be done in and target the `release/v1.30.0` or `release/miner/v1.30.0` branch.

**Release PR**

- [x] Update the version string(s) in `build/version.go` to one ending with '-rc1'. 
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Create a draft PR with title `build: release Lotus node|miner v1.30.0-rc1`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12564
   - Opening a PR will trigger a CI run that will build assets, create a draft GitHub release, and attach the assets.
- [x] Changelog prep
   - [x] Go to the [releases page](https://github.com/filecoin-project/lotus/releases) and copy the auto-generated release notes into the CHANGELOG
   - [x] Perform editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] (network upgrade) Specify whether the Calibration or Mainnet upgrade epoch has been specified or not yet.
      - Example where these weren't specified yet: [PR #12169](https://github.com/filecoin-project/lotus/pull/12169)
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas (where `YYYY-MM-DD` is the start search date): `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, .mergedAt, .author.login, .title] | @tsv' | sort -k4`
    - [x] Update the PR with the commit(s) made to the CHANGELOG
- [x] Mark the PR "ready for review" (non-draft)
- [x] Merge the PR
   - Merging the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
 - [x] Update `🚢 Estimated shipping date` table
 - [x] Comment on this issue announcing the RC
    - Link to issue comment: https://github.com/filecoin-project/lotus/issues/12480#issuecomment-2401454205

#### rc2
> [!IMPORTANT]
> These PRs should be done in and target the `release/v1.30.0` or `release/miner/v1.30.0` branch.

**Backport PR**

- [x] All explicitly tracked items from `Dependencies for releases` have landed
- [x] Backported [everything with the "backport" label](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+) 
- [x] Removed the "backport" label from all backported PRs (no ["backport" issues](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+))
- [x] Create a PR with title `build: backport changes for node|miner v1.30.0-rcX`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12598
- [x] Merge PR 

**Release PR**

- [x] Update the version string(s) in `build/version.go` to one ending with '-rc2'. 
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Create a draft PR with title `build: release Lotus node|miner v1.30.0-rc2`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12599
   - Opening a PR will trigger a CI run that will build assets, create a draft GitHub release, and attach the assets.
- [x] Changelog prep
   - [x] Go to the [releases page](https://github.com/filecoin-project/lotus/releases) and copy the auto-generated release notes into the CHANGELOG
   - [x] Perform editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] (network upgrade) Specify whether the Calibration or Mainnet upgrade epoch has been specified or not yet.
      - Example where these weren't specified yet: [PR #12169](https://github.com/filecoin-project/lotus/pull/12169)
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas (where `YYYY-MM-DD` is the start search date): `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, .mergedAt, .author.login, .title] | @tsv' | sort -k4`
    - [x] Update the PR with the commit(s) made to the CHANGELOG
- [x] Mark the PR "ready for review" (non-draft)
- [x] Merge the PR
   - Merging the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
 - [x] Update `🚢 Estimated shipping date` table
 - [x] Comment on this issue announcing the RC
    - Link to issue comment:  https://github.com/filecoin-project/lotus/issues/12480#issuecomment-2412053787
    
#### rc3
> [!IMPORTANT]
> These PRs should be done in and target the `release/v1.30.0` or `release/miner/v1.30.0` branch.

**Backport PR**

- [x] All explicitly tracked items from `Dependencies for releases` have landed
- [x] Backported [everything with the "backport" label](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+) 
- [x] Removed the "backport" label from all backported PRs (no ["backport" issues](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+))
- [x] Create a PR with title `build: backport changes for node|miner v1.30.0-rcX`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12598
- [x] Merge PR 

**Release PR**

- [x] Update the version string(s) in `build/version.go` to one ending with '-rc3'. 
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Create a draft PR with title `build: release Lotus node|miner v1.30.0-rc3`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12653
   - Opening a PR will trigger a CI run that will build assets, create a draft GitHub release, and attach the assets.
- [x] Changelog prep
   - [x] Go to the [releases page](https://github.com/filecoin-project/lotus/releases) and copy the auto-generated release notes into the CHANGELOG
   - [x] Perform editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] (network upgrade) Specify whether the Calibration or Mainnet upgrade epoch has been specified or not yet.
      - Example where these weren't specified yet: [PR #12169](https://github.com/filecoin-project/lotus/pull/12169)
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas (where `YYYY-MM-DD` is the start search date): `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, .mergedAt, .author.login, .title] | @tsv' | sort -k4`
    - [x] Update the PR with the commit(s) made to the CHANGELOG
- [x] Mark the PR "ready for review" (non-draft)
- [x] Merge the PR
   - Merging the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
 - [x] Update `🚢 Estimated shipping date` table
 - [x] Comment on this issue announcing the RC
    - Link to issue comment:  https://github.com/filecoin-project/lotus/issues/12480#issuecomment-2444061571

**Testing**
> [!NOTE]
> Link to any special steps for testing releases beyond ensuring CI is green.  Steps can be inlined here or tracked elsewhere.

### Stable (non-RC) Release

> [!IMPORTANT]
> These PRs should be done in and target the `release/v1.30.0` or `release/miner/v1.30.0` branch.

**Backport PR**

- [x] All explicitly tracked items from `Dependencies for releases` have landed
- [x] Backported [everything with the "backport" label](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+) 
- [x] Removed the "backport" label from all backported PRs (no ["backport" issues](https://github.com/filecoin-project/lotus/issues?q=label%3Arelease%2Fbackport+))
- [x] Create a PR with title `build: backport changes for node|miner v1.30.0-rcX`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12678
- [x] Merge PR 

**Release PR**

- [x] Update the version string(s) in `build/version.go` to one **NOT** ending with '-rcX'. 
    - Ensure to update the appropriate version string based on whether you are creating a node release (`NodeBuildVersion`), a miner release (`MinerBuildVersion`), or both.
- [x] Run `make gen && make docsgen-cli` to generate documentation
- [x] Create a draft PR with title `build: release Lotus node|miner v1.30.0`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12678
   - Opening a PR will trigger a CI run that will build assets, create a draft GitHub release, and attach the assets.
- [x] Changelog prep
   - [x] Go to the [releases page](https://github.com/filecoin-project/lotus/releases) and copy the auto-generated release notes into the CHANGELOG
   - [x] Perform editorial review (e.g., callout breaking changes, new features, FIPs, actor bundles)
   - [x] (network upgrade) Ensure the Mainnet upgrade epoch is specified.
   - [x] Ensure no missing content when spot checking git history
      - Example command looking at git commits: `git log --oneline --graph vA.B.C..`, where A.B.C correspond to the previous release. 
      - Example GitHub UI search looking at merged PRs into master: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+base%3Amaster+merged%3A%3EYYYY-MM-DD
      - Example `gh` cli command looking at merged PRs into master and sorted by title to group similar areas (where `YYYY-MM-DD` is the start search date): `gh pr list --repo filecoin-project/lotus --search "base:master merged:>YYYY-MM-DD" --json number,mergedAt,author,title | jq -r '.[] | [.number, .mergedAt, .author.login, .title] | @tsv' | sort -k4`
    - [x] Update the PR with the commit(s) made to the CHANGELOG
- [x] Mark the PR "ready for review" (non-draft)
- [x] Merge the PR
   - Merging the PR will trigger a CI run that will build assets, attach the assets to the GitHub release, publish the GitHub release, and create the corresponding git tag.
 - [x] Update `🚢 Estimated shipping date` table
 - [x] Comment on this issue announcing the release
    - Link to issue comment: https://github.com/filecoin-project/lotus/issues/12480#issuecomment-2461428691

### Post-Release

- [x] Open a PR against `master` cherry-picking the CHANGELOG commits from the `release/v1.30.0` branch. Title it `chore(release): cherry-pick v1.30.0 changelog back to master`
   - Link to PR: https://github.com/filecoin-project/lotus/pull/12683
   - Assuming we followed [the process of merging changes into `master` first before backporting to the release branch](https://github.com/filecoin-project/lotus/blob/master/LOTUS_RELEASE_FLOW.md#branch-and-tag-strategy), the only changes should be CHANGELOG updates.  
- [x] Finish updating/merging the [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) PR from `Before RC1` with any improvements determined from this latest release iteration.

## ❤️ Contributors

See the final release notes!

## ⁉️ Do you have questions?

Leave a comment in this ticket!

**Comment by rjan90** [comment]
### 2024-10-08

The first release candidates, v1.30.0-rc1 was shipped:
- https://github.com/filecoin-project/lotus/releases/tag/v1.30.0-rc1
- https://github.com/filecoin-project/lotus/releases/tag/miner%2Fv1.30.0-rc1

**Comment by rjan90** [comment]
The second release candidates, v1.30.0-rc2 has been shipped with upgrade epochs for the Calibration network set:

- https://github.com/filecoin-project/lotus/releases/tag/v1.30.0-rc2
- https://github.com/filecoin-project/lotus/releases/tag/miner%2Fv1.30.0-rc2

**Comment by rjan90** [comment]
The third release candidates, v1.30.0-rc3 has been shipped with - this release adds a couple of smaller fixes found during testing of rc2. This release candidate does NOT set the mainnet network upgrade epoch. It will be added in the final release (expected October 30th):

- https://github.com/filecoin-project/lotus/releases/tag/v1.30.0-rc3
- https://github.com/filecoin-project/lotus/releases/tag/miner%2Fv1.30.0-rc3

**Comment by rjan90** [comment]
The final release, v1.30.0 has been shipped - this release sets the mainnet network upgrade epoch to `4461240`, corresponding to `2024-11-20T23:00:00Z`.

- https://github.com/filecoin-project/lotus/releases/tag/v1.30.0
- https://github.com/filecoin-project/lotus/releases/tag/miner%2Fv1.30.0
