### ISSUE TITLE
Flaky F3 itests

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/lotus#12519]
Happening with some frequency, here's some recent examples:

* TestF3_PauseAndRebootstrap: https://github.com/filecoin-project/lotus/actions/runs/11046427121/job/30685760550?pr=12505
* TestF3_Rebootstrap: https://github.com/filecoin-project/lotus/actions/runs/11063981852/job/30741029746?pr=12518#step:9:25233

**Comment by rvagg** [comment]
🤞

**Comment by masih** [comment]
Reopening as it seem to continue to fail intermittently, though at a much lower failure rate. [Example](https://github.com/filecoin-project/lotus/actions/runs/11124775427/job/30911063790?pr=12537)

**Comment by Stebalien** [comment]
Ok, I think this is caused by #12557 and should be "fixed" on the latest master because we now forcibly align "catchup" instances to 1/2 block time.

**Comment by masih** [comment]
Still flakes [here](https://github.com/filecoin-project/lotus/actions/runs/11231683664/job/31222401167?pr=12531)

**Comment by Stebalien** [comment]
That one looks like a timeout that's just slightly too short.

**Comment by Stebalien** [comment]
Hm. No, it just never made progress after bootstrapping.
