### ISSUE TITLE
API address in config.toml seems to be ignored

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#1256]
**Describe the bug**
Changing the `ListenAddress` in the `config.toml` file doesn't seem to actually change where the API port is opened. Instead, it seems that whatever is specified here dictates where it opens: https://github.com/filecoin-project/lotus/blob/master/node/config/def.go#L70

**To Reproduce**
1. Change the `ListenAddress` in config.toml 
2. Run `lotus daemon`
3. Try connecting to the address specified in Step 1

**Expected behavior**
The API port should be opened at the address specified in config.toml

**Version (run `lotus --version`):**

0.2.7

**Additional context**
Originally reported by Scott on Slack: https://filecoinproject.slack.com/archives/CPFTWMY7N/p1581535198331200

**Comment by Kubuxu** [comment]
Just checked, cannot reproduce.

**Comment by arajasek** [comment]
Update: I'm a genius, apparently lines in `config.toml` won't have any effect if they're commented out 🙃 
There isn't a bug, closing the issue.
