### ISSUE TITLE
Health Endpoint

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/lotus#12587]
### Checklist

- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [x] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

The facilitate the High Availaibility design of a lotus node. 
The following design usually apply : HA-PRoxy in front of X lotus nodes

(feature also apply for node monitoring)

### Describe the solution you'd like

Implement a simple GET endpoint without Auth :  returning 200 if the node is heathy, available and onsync and a error code if not.

**Comment by Stebalien** [comment]
There's a health endpoint at `/health/livez` (and a readiness endpoint at `/health/readyz`. They both return 200 when ready/healthy. They'll mark the node as unhealthy if you fail to receive any blocks within 5 minutes (from what I can tell).

**Comment by Stebalien** [comment]
Specifically, these are designed for kubernetes: https://kubernetes.io/docs/reference/using-api/health-checks/.

**Comment by s0nik42** [comment]
Thanks !
