### ISSUE TITLE
ChainValidateIndex should validate the actual content of the events and not just match on the number of events

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#12594]
See https://github.com/filecoin-project/lotus/pull/12450#discussion_r1794502554.

The `ChainValidateIndex` currently only compares the counts of the events in the Index with the number of events for  the epoch in the Index to validate the Indexed events.

However, we should also compare the actual content of the events in the chain state AMT with the Indexed events for a more comprehensive check.

See https://github.com/filecoin-project/lotus/issues/12570 and https://github.com/filecoin-project/lotus/pull/12571 for exploration of more complete checking.

**Comment by BigLep** [comment]
@aarshkshah1992 : I'm not close to the details, but https://github.com/filecoin-project/lotus/pull/12571 is related right?

**Comment by rvagg** [comment]
yes, https://github.com/filecoin-project/lotus/pull/12571 is the implementation for lotus-shed, all the hard logic is explored in there so a lot of that code can just be copied, like the original counting code was copied from there

**Comment by aarshkshah1992** [comment]
Closed by https://github.com/filecoin-project/lotus/pull/12632.
