### ISSUE TITLE
Implement F3 CLI Subcommands for Informative and Diagnostic Purposes

### ISSUE THREAD

**Issue by masih** [filecoin-project/lotus#12607]
Add new `F3` subcommands to the Lotus CLI that will print detailed information about the current state of the `F3` system, as well as provide diagnostics functionality. These subcommands should allow users to:

- View various details regarding the current F3 state.
- Perform diagnostics on the manifest.
- Dump finality certificates.
- List participants in the F3 system.

The overall goal is to enhance the observability and debuggability of `F3` through the Lotus CLI.

The CLI will follow the structure `lotus f3 <subcommand>`. Some CLIs may need expansion of the current Lotus F3* APIs, e.g. listing current participants.

```[tasklist]
- [x] Implement F3 CLI command to list current participants (i.e. lease holders).
- [x] Implement F3 CLI command to dump the current manifest.
- [x] Implement F3 CLI command to get the current progress of GPBFT.
- [x] Implement F3 CLI command to dump finality certificates (latest or for a specific instance).
- [x] ~Implement F3 CLI command to dump F3 power table used by a given instance~ not really needed; skipping this one and will revisit if needed
- [x] Implement F3 CLI command to check the overall status of F3, i.e. whether it is running, manifest summary, progress summary.
```

**Comment by Kubuxu** [comment]
I would make it possible for the finality certs command to dump a range of certs.
