### ISSUE TITLE
StateTree Revert

### ISSUE THREAD

**Issue by turuslan** [filecoin-project/lotus#1267]
**Describe the bug**

**1. [`StateTree.Revert`](https://github.com/filecoin-project/lotus/blob/a34537ae9fa2027bfd5951c58cdcb44fcb29182a/chain/state/statetree.go#L184) does not "revert" anything.**

`StateTree.Revert` does not reset [`StateTree.actorCache`](https://github.com/filecoin-project/lotus/blob/a34537ae9fa2027bfd5951c58cdcb44fcb29182a/chain/state/statetree.go#L24), which is used by all other methods (`StateTree.SetActor`, `StateTree.GetActor`, `StateTree.Flush`, `StateTree.Snapshot`, `StateTree.MutateActor`).
`StateTree.actorCache` is a cache for [`StateTree.root`](https://github.com/filecoin-project/lotus/blob/a34537ae9fa2027bfd5951c58cdcb44fcb29182a/chain/state/statetree.go#L21) HAMT. If actor is in `StateTree.actorCache` then HAMT won't be accessed.
`StateTree.Flush` first inserts actors from `StateTree.actorCache` into HAMT, then flushed HAMT.

As a result, `StateTree.Revert` does not "revert" anything.

Is that an expected behavior?

**2. Possible funds leak in [`VM.ApplyMessage`](https://github.com/filecoin-project/lotus/blob/a34537ae9fa2027bfd5951c58cdcb44fcb29182a/chain/vm/vm.go#L418).**

`VM.ApplyMessage` may execute following sequence of actions:
| action | sender | temp | miner | total funds |
| --- | --- | --- | --- | --- |
| [call `StateTree.Snapshot`](https://github.com/filecoin-project/lotus/blob/a34537ae9fa2027bfd5951c58cdcb44fcb29182a/chain/vm/vm.go#L434) | A | 0 | B | A + B |
| [transfer funds from sender to temp actor](https://github.com/filecoin-project/lotus/blob/a34537ae9fa2027bfd5951c58cdcb44fcb29182a/chain/vm/vm.go#L456) | A - N | N | B | A + B |
| [call `StateTree.Revert`](https://github.com/filecoin-project/lotus/blob/a34537ae9fa2027bfd5951c58cdcb44fcb29182a/chain/vm/vm.go#L480) | A | **N** | B | A + B + **N** |
| [transfer funds from temp actor to miner](https://github.com/filecoin-project/lotus/blob/a34537ae9fa2027bfd5951c58cdcb44fcb29182a/chain/vm/vm.go#L500) | A | 0 | B + **N** | A + B + **N** |

In that case, `StateTree.Revert` will cancel fund transfer from sender to temporary actor and add them back to sender. `StateTree.Revert` will not change temporary actor balance.
Then funds will be transfered from temporary actor to miner.
These funds are leaked.

However `StateTree.Revert` does not "revert" (see point 1) and this bug does not occur.

Is that an expected behavior?

**Version:**
Code revision: [a34537ae9fa2027bfd5951c58cdcb44fcb29182a](https://github.com/filecoin-project/lotus/tree/a34537ae9fa2027bfd5951c58cdcb44fcb29182a)

**Comment by Kubuxu** [comment]
Was found in `https://github.com/filecoin-project/lotus/pull/1236#discussion_r378491011`, but good find either way.

**Comment by whyrusleeping** [comment]
This has been fixed, thank you for reporting!
