### ISSUE TITLE
Tag metrics with a network name/network tag

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#12715]
Tag exported metrics with a network dependent tag such that in metric collection we don't have to create host -> network mapping.

**Comment by rvagg** [comment]
Many of the metrics were completed in https://github.com/filecoin-project/lotus/pull/12733

Unfortunately we have a whole lot of `context.Background()` and `context.TODO()` that are stopping us getting at some important ones and they're not so simple to solve.

In https://github.com/filecoin-project/lotus/pull/12793 I started looking at getting contexts wired through to many of these places, or adding the tag to new contexts where it doesn't make sense, but it's tedious work and there's a lot more to do and a lot of localised reasoning that needs to be done to understand if a context should be detached or not.

So #12733's CHANGELOG entry said there would be follow-up work, this issue will remain as a tracker for that work.
