### ISSUE TITLE
Lotus nodes have significantly increased bandwidth usage.

### ISSUE THREAD

**Issue by yangyueqiangyy** [filecoin-project/lotus#12742]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.30.0+mainnet+git.9c1964e8a
```

### Repro Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

### Describe the Bug

Lotus nodes will see a significant increase in bandwidth usage starting from November 25th, 2024.

![22](https://github.com/user-attachments/assets/86e20e88-044b-4de2-84c6-e82c75930933)

![11](https://github.com/user-attachments/assets/75b71107-cfcc-4fed-9084-bc842092f736)

### Logging Information

```text
None
```

**Comment by yangyueqiangyy** [comment]
The same phenomenon occurs in Lotus nodes in Canada and the United States.

**Comment by rvagg** [comment]
Hi @yangyueqiangyy, what you're seeing here is a result of passive testing of F3, the new fast-finality protocol that will eventually be enabled full-time on mainnet. Currently there's passive testing going on which involves manually starting the protocol and having nodes coordinate to "bootstrap" the protocol to achieve finality agreement. Unfortunately this bootstrap phase can be network-intensive but once the protocol is operating normally it settles right down.

There's more info on F3 passive testing in this discussion thread, including details of the outcomes of the specific testing rounds that you're seeing in the spikes of traffic from your nodes: https://github.com/filecoin-project/lotus/discussions/12287 - there's lots of info in there about bandwidth utilisation and expectations and efforts to try and minimise the bootstrap time when it's finally actively enabled (hopefully in the next network upgrade).

**Comment by yangyueqiangyy** [comment]
> 你好@yangyueqiangyy，您在这里看到的是 F3 的被动测试结果，F3 是新的快速终结性协议，最终将在主网上全面启用。目前正在进行被动测试，包括手动启动协议并让节点协调以“引导”协议以实现终结性协议。不幸的是，这个引导阶段可能需要大量网络资源，但一旦协议正常运行，它就会稳定下来。
> 
> 该讨论线程中还有更多关于 F3 被动测试的信息，包括您在节点流量峰值中看到的特定测试轮次的结果详情：#12287 - 其中有很多关于带宽利用率和预期的信息，以及在最终主动启用时（希望在下一次网络升级中）尝试尽量减少引导时间的努力。


Okay, thank you for your answer。
