### ISSUE TITLE
Miner ID Generation: "Miner address must use BLS"

### ISSUE THREAD

**Issue by FactorYang** [filecoin-project/lotus#1283]
Describe the bug:
I run lotus in ubuntu 18.04, and use my wallet address t1ajidc7sqbhdtjiwggyqnuepcpnz5vj7bi2c5p5y to generate miner ID. 
However, the result is "Miner address must use BLS".

To Reproduce:
1. open the miner ID generation website: https://faucet.testnet.filecoin.io/miner.html
2. filling my wallet address t1ajidc7sqbhdtjiwggyqnuepcpnz5vj7bi2c5p5

Screenshots
![image](https://user-images.githubusercontent.com/15258174/74900552-2c09bb80-53db-11ea-860e-af1ff64685d1.png)

Version (run `lotus --version`):
lotus version 0.2.7+git4750f32a

**Comment by arajasek** [comment]
You need to create your address by running `lotus wallet new bls`.
