### ISSUE TITLE
Power is 0 for a new miner even the committed power has exceeded 512G.

### ISSUE THREAD

**Issue by maobisheng** [filecoin-project/lotus#1285]
![image](https://user-images.githubusercontent.com/3703197/75084569-d90b4200-555b-11ea-9802-7a5ffffe332c.png)

Power is 0 for a new miner even the committed power has exceeded 512G, we can reproduce this issue every time, and we didn't find any related error information in logs.

For now, the workaround for this problem is to restart lotus-storage-miner process.

This issue also reported in slack many times by other members before.

Thanks.

**Comment by whyrusleeping** [comment]
We probably don't schedule the first fallback post when moving over the threshold

**Comment by magik6k** [comment]
Not an issue in the interopnet
