### ISSUE TITLE
I can't add seal task

### ISSUE THREAD

**Issue by woshihanhaoniao** [filecoin-project/lotus#1286]
When I wanted to start a new sealing task, miner made this error. But I think my hard disk is sufficient.
One time I found that when I started the sealing task, my hard disk SSD would be filled rapidly, but my HHD was not used. I confirm that I have set the environment variable. Is there something wrong with my settings or something else.

`export LOTUS_STORAGE_PATH=/home/zhang/storage
export IPFS_GATEWAY="https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/"
export BELLMAN_CUSTOM_GPU="GeForce GTX 1080 Ti:2560"
export cache=/home/zhang/storage/cache
export PATH=$PATH:/home/zhang/lotus 
`

`ev             95G     0   95G    0% /dev
tmpfs            19G  2.3M   19G    1% /run
/dev/sda2       228G  105G  112G   49% /
tmpfs            95G   42M   95G    1% /dev/shm
tmpfs           5.0M  4.0K  5.0M    1% /run/lock
tmpfs            95G     0   95G    0% /sys/fs/cgroup
/dev/loop1      4.3M  4.3M     0  100% /snap/gnome-calculator/544
/dev/loop2       15M   15M     0  100% /snap/gnome-characters/296
/dev/loop0       92M   92M     0  100% /snap/core/8689
/dev/loop3      3.8M  3.8M     0  100% /snap/gnome-system-monitor/127
/dev/loop4      161M  161M     0  100% /snap/gnome-3-28-1804/116
/dev/loop5      1.0M  1.0M     0  100% /snap/gnome-logs/81
/dev/loop6       55M   55M     0  100% /snap/core18/1066
/dev/loop7       55M   55M     0  100% /snap/core18/1668
/dev/loop8       92M   92M     0  100% /snap/core/8592
/dev/loop9       45M   45M     0  100% /snap/gtk-common-themes/1440
/dev/loop10      15M   15M     0  100% /snap/gnome-characters/399
/dev/loop11      43M   43M     0  100% /snap/gtk-common-themes/1313
/dev/loop14     1.0M  1.0M     0  100% /snap/gnome-logs/61
/dev/loop15     150M  150M     0  100% /snap/gnome-3-28-1804/67
/dev/loop12     3.8M  3.8M     0  100% /snap/gnome-system-monitor/100
/dev/loop13     4.2M  4.2M     0  100% /snap/gnome-calculator/406
/dev/sda1       511M  6.1M  505M    2% /boot/efi
/dev/sdb        7.3T  296G  6.6T    5% /home/zhang/storage
tmpfs            19G   16K   19G    1% /run/user/121
tmpfs            19G   60K   19G    1% /run/user/1000
/dev/sdc4       7.5G   88K  7.5G    1% /media/zhang/Ubuntu 18.0
tmpfs            19G     0   19G    0% /run/user/0
`

`* failed to write and preprocess bytes

Caused by:
    No space left on device (os error 28)
	* failed to write and preprocess bytes

Caused by:
    No space left on device (os error 28)

github.com/filecoin-project/lotus/storage/sealing.(*Sealing).PledgeSector.func1
	/home/zhang/test/lotus/storage/sealing/garbage.go:136
2020-02-22T11:34:02.603+0800	ERROR	sectors	sealing/garbage.go:136	2 errors occurred:
	* failed to write and preprocess bytes

Caused by:
    No space left on device (os error 28)
	* failed to write and preprocess bytes

Caused by:
    No space left on device (os error 28)

github.com/filecoin-project/lotus/storage/sealing.(*Sealing).PledgeSector.func1
	/home/zhang/test/lotus/storage/sealing/garbage.go:136
2020-02-22T11:34:25.490+0800	ERROR	sectors	sealing/garbage.go:136	2 errors occurred:
	* failed to write and preprocess bytes

Caused by:
    No space left on device (os error 28)
	* failed to write and preprocess bytes
`

**Comment by magik6k** [comment]
This code was now mostly rewritten, please reopen if this happens again.

(You need ~400G of disk space for the sealing process for some temporary files, which are later removed)
