### ISSUE TITLE
[jsonrpc] High number of goroutines waiting for next message

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#1289]
**Describe the bug**
`nextMessage` appears to be leaking goroutines

**To Reproduce**
1. Run miner for a while
2. Run pprof trace

**Expected behavior**
There shouldn't be this many goroutines for `nextMessage`.

**Screenshots**
![Screen Shot 2020-02-24 at 12 49 59](https://user-images.githubusercontent.com/5924712/75190401-0f37f580-5705-11ea-81e4-d44466e8e08b.png)

**Version (run `lotus --version`):**
master

**Comment by magik6k** [comment]
There are some fixes / changes to related code in https://github.com/filecoin-project/lotus/pull/1221 (from https://github.com/filecoin-project/lotus/pull/1155), so any investigating should happen on the testnet/3 branch, or after it's merged

**Comment by ridewindx** [comment]
Why jsonrpc?
jsonrpc just looks like a "deprecated" rpc mechanism convention which comes from btc/eth.
New blockchain should consider grpc, it's more mature and featured, also appropriate for public api.

**Comment by magik6k** [comment]
Looks like this got fixed
