### ISSUE TITLE
Add signing and verification of arbitrary messages

### ISSUE THREAD

**Issue by ianjdarrow** [filecoin-project/lotus#1290]
To facilitate certain types of off-chain communications, it's useful to be able to verify that a message came from someone who controls a particular address. One way to do this (proposed by @whyrusleeping in response to some questions) is to implement two new commands:

`lotus wallet sign --from=<addr> <message>` should produce a valid signature over `<message>` signed by `<addr>`'s private key.
`lotus wallet verify --from=<addr> --sig=<signature> <message>` should verify whether the provided signature is valid over the given message and address.

**Comment by arajasek** [comment]
Done in #1292

**Comment by ButterflyChain** [comment]
t06266
