### ISSUE TITLE
Rounds skip when running miner with multi-addresses

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#1304]
**Describe the bug**
We support multiple addresses for one miner instance to mine blocks, see: 
https://github.com/filecoin-project/lotus/blob/master/miner/miner.go#L183-L192

However, when running [mineOne](https://github.com/filecoin-project/lotus/blob/master/miner/miner.go#L287) for each using the same base, the base.nullBlocks could be added multi-times if there are more than one addresses not winning in this round. That is, we run: 
`base.nullRounds++` 
multiple times, while we really expect only once for a round.

**Comment by magik6k** [comment]
Fixed by removing support for multiple miner addresses in the mining loop
