### ISSUE TITLE
Lotus daemon crash problem, may caused by "Garbege Collection"

### ISSUE THREAD

**Issue by Cyanglacier** [filecoin-project/lotus#1309]
This bug will occur if i running "`lotus daemon`" nearly 7 hours. It will let the daemon crash and "`lotus-storage-miner run`" report websocket error.

It is strange that another host which locate in a same network will not have this problem. 

Here is the Pic
![微信图片_20200228215449](https://user-images.githubusercontent.com/47769205/75678807-63287880-5cc9-11ea-85cd-f62ad300ca63.png)

Here is the crash log
[lotus daemon crash log.txt](https://github.com/filecoin-project/lotus/files/4275512/lotus.daemon.crash.log.txt)

My lotus version is  0.2.8+git0eeb6c16

**Comment by magik6k** [comment]
Please reopen if this can still be reproduced with latest code
