### ISSUE TITLE
lotus-storage-miner  panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#1310]
**Describe the bug**
run lotus in localnet. 

**To Reproduce**
1 lotus  daemon --lotus-make-genesis=dev.gen --genesis-template=localnet.json --bootstrap=false
2. lotus-storage-miner
3 lotus-seal-worker
4 kill the lotus-seal-worker process
5   the lotus and the miner shows this error 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb98fab]

goroutine 7857 [running]:
github.com/filecoin-project/lotus/lib/jsonrpc.(*wsConn).handleWsConn.func1(0xc01df708c0)
        /mnt/lotus/lotustest3/lib/jsonrpc/websocket.go:487 +0x5b
created by github.com/filecoin-project/lotus/lib/jsonrpc.(*wsConn).handleWsConn
        /mnt/lotus/lotustest3/lib/jsonrpc/websocket.go:482 +0x993

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**
lotus version 0.3.0+git47abf8e7

**Additional context**

**Comment by magik6k** [comment]
I'm pretty sure this is fixed now
