### ISSUE TITLE
Lotus testnet/3 randomness issue

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/lotus#1311]
Entropy fed into the randomness generation must be a CBor serialization of the underlying objects.

It seems like lotus is passing in simple byte representations (eg. https://github.com/filecoin-project/lotus/blob/testnet/3/chain/gen/gen.go#L552) which may not be the same.

Logical follow up to https://github.com/filecoin-project/lotus/pull/1295

**Comment by daviddias** [comment]
The logic here has changed significantly. Closing as non-issue anymore. Reopen if necessary
