### ISSUE TITLE
Expose an API to list all messages that cause account balances to change

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#1322]
One of our integ partners wants a way to associate every balance change in an account with a specific message. This can be a hard problem to solve in the general smart contract case (you pretty much need to be "watching" every message coming in and checking if its execution changes a balance in an account you're interested in).

For us, however, it's probably easier -- I assume an account, A, can only have its balance change if someone sends A a balance transfer, if A is the recipient of block rewards, and (I'm guessing) some other enumerable list of cases involving our actors.

**Comment by jennijuju** [comment]
@arajasek were you thinking an CLI or API?

**Comment by bonoyang** [comment]
@jennijuju any update?

**Comment by jennijuju** [comment]
related #5065 moving conversation there
