### ISSUE TITLE
lotuspond  rpc error: json: cannot unmarshal object into Go value of type []cid.Cid

### ISSUE THREAD

**Issue by cerasusland** [filecoin-project/lotus#1333]
seem like lotuspond `unsupported signer types:bls` has been sloved.

but I got an another problem `json: cannot unmarshal object into Go value of type []cid.Cid`

![image](https://user-images.githubusercontent.com/57336347/76051030-77f45d00-5fa4-11ea-86e2-0f8f405e6396.png)

**Comment by whyrusleeping** [comment]
This has been resolved
