### ISSUE TITLE
[testnet/3] sectors failing to move to proving set (pSet)

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#1358]
**Describe the bug**
Sectors that have been committed aren't moving to the proving set.

```
9: Proving       sSet: YES pSet: NO  tktH: 1081 seedH: 1609 deals: [0]
10: Proving      sSet: YES pSet: NO  tktH: 1081 seedH: 1609 deals: [0]
11: Proving      sSet: YES pSet: NO  tktH: 1081 seedH: 1609 deals: [0]
```
Chain height is now at 3367.

**Expected behavior**
Should move to pSet within ~500 blocks. Restarting the daemon and the miner did not trigger the sectors to move to the proving set.

**Comment by whyrusleeping** [comment]
Pretty sure this is fixed now, and if not the code has changed dramatically. So lets open a new issue if it happens again
