### ISSUE TITLE
failed to open stream to miner: routing: not found

### ISSUE THREAD

**Issue by jon277** [filecoin-project/lotus#1359]
I saw this error information when I was trying to use "lotus client query-ask <miner>" to get the requirements of a miner. I tried some of the top power miners ids and also tried my own miner id, and I got the same error.  Why could this happen? How can I do?

**Comment by whyrusleeping** [comment]
This happens when a miner can't be found in the dht. After the recent upgrade we did, this should be much less common.

**Comment by utgarda** [comment]
I can see this line for 2021 miners out of 2022 I asked so far, i.e. I have an answer from just 1 miner apart from my own. 
```
$ lotus state list-miners > ./miners
$ cat ask-miners.sh 
#!/bin/bash
while read in; do lotus client query-ask "$in"; done < miners

./ask-miners.sh &> ./ask-miners.log
```
[ask-miners.log](https://github.com/filecoin-project/lotus/files/4874909/ask-miners.log)
[miners.log](https://github.com/filecoin-project/lotus/files/4874910/miners.log)

**Comment by qiluge** [comment]
there are no one miner could be `query-ask`....

**Comment by panol** [comment]
you can query-ask your own miner and make deal with it with another lotus full node.

**Comment by qiluge** [comment]
> you can query-ask your own miner and make deal with it with another lotus full node.

I have no machine that meets mining requirements

**Comment by qiluge** [comment]
Oh I find a miner enable me upload file. but there is an error during of uploading:

```
DealCid                                                      DealId  Provider  State                     On Chain?  Slashed?  PieceCID                                                       Size     Price                  Duration  Message
bafyreibqpjp3bzecaxsix4y52x27nstnjiibvrrfvrtznvq4y3fdlcbhsa  0       t0120796  StorageDealError          N          N         bafk4chzai2epttm2pvgtc54iwgkx7w3d6zmsvnxxgxanchcw4ls4blodqehq  127 B    500000000              3314      unexpected deal status while waiting for data request: 7
```

**Comment by woshidama323** [comment]
The same issue as qiluge said

**Comment by adwulfran** [comment]
Same issue
