### ISSUE TITLE
Prometheus metrics for sector states in lotus-miner

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#1370]

**Comment by yuwenhui** [comment]
Will prometheus metrics for sector states be added in the future?  @magik6k

**Comment by jennijuju** [comment]
Hey @lanzafame, are you still working on this?

**Comment by lanzafame** [comment]
Nope

**Comment by upengs** [comment]
Currently lotus-miner lotus-worker debug/metrics are not available

**Comment by TippyFlitsUK** [comment]
Hi @magik6k 

This looks like a reminder. Should we close it or keep it open?
