### ISSUE TITLE
Typo in Error message: "diconnecting"

### ISSUE THREAD

**Issue by Shatnerz** [filecoin-project/lotus#1400]
**Describe the bug**
Typo in error: `failed to read hello message, diconnecting`

**To Reproduce**
No reliable reproduction, but you can just grep for the misspelling. I was messing around with the local dev net when I discovered this.

**Expected behavior**
Correct spelling: `failed to read hello message, disconnecting`

**Screenshots**
N/A

**Version (run `lotus --version`):**
lotus version 0.2.8+git41bf6681

**Additional context**
N/A

**Comment by arajasek** [comment]
Fixed, thanks :)
