### ISSUE TITLE
Nonces of reverted messages

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#1411]
What happens to the nonce of someone who sends an invalid message that gets reverted? I think we'll wind up reverting the nonce increment, even though the message lives on chain. That's probably not what we want?

**Comment by whyrusleeping** [comment]
Hrm... this is a great point. I think this was done correctly in the past (nonces werent reverted) but it could be different now. Definitely needs investigation

**Comment by arajasek** [comment]
(Indirectly) fixed in https://github.com/filecoin-project/lotus/commit/84fd96971016a61a43d5c7ee14c2d76cfab4907f
