### ISSUE TITLE
Feature req - create endpoint like StateWaitMsg, without waiting for confirmations

### ISSUE THREAD

**Issue by Schwartz10** [filecoin-project/lotus#1412]
Can we create a similar endpoint to StateWaitMsg, but if the message is not found, return `null` instead of listening to the chain (and waiting) for a receipt? The waiting of StateWaitMsg can become blocking on a node if too many calls are made simultaneously.

**Comment by whyrusleeping** [comment]
This has been added as `StateSearchMsg`
