### ISSUE TITLE
testnet/3 pledging sectors fails with a nil map error

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#1420]
![image](https://user-images.githubusercontent.com/6530144/77000295-893b5300-692e-11ea-9f9f-999e6c8528d1.png)

**Comment by travisperson** [comment]
I don't think this was on testnet/3 branch.

**Comment by NewMai** [comment]
This this the testnet2, @travisperson 

When i finish sealing one sector, 
![image](https://user-images.githubusercontent.com/9707303/77056526-7cd9f780-6a0d-11ea-94f9-a1de02b92147.png)

This error will occured,

BTW, my `config.toml` file just as the following one:

`
# Default config:
[API]
  ListenAddress = "/ip4/192.168.1.200/tcp/2345/http"
  Timeout = "30s"
#
[Libp2p]
#  ListenAddresses = ["/ip4/0.0.0.0/tcp/0", "/ip6/::/tcp/0"]
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[SectorBuilder]
#  Path = ""
#  WorkerCount = 2
    Storage = [
        
        #{ Path =  "/home/cs/disk_nvme1/fash_cache/", Cache = true, Weight = 5},
        { Path =  "/home/cs/disk_md0/testnet2/cache/", Cache = true, Weight = 5},
        { Path =  "/nfs/lotusstorage/testnet2/persistent_lotusstorage/", Cache = false, Weight = 2},
        
    ]

#  DisableLocalPreCommit = false
#  DisableLocalCommit = false
#

`

**Comment by NewMai** [comment]
![image](https://user-images.githubusercontent.com/9707303/77056825-feca2080-6a0d-11ea-8f52-353060a24a43.png)

**Comment by NewMai** [comment]
Before I change the `config.toml` file, everything goes fine.

**Comment by whyrusleeping** [comment]
Pretty sure this has since been resolved.

@NewMai please file a new issue if this happens again
