### ISSUE TITLE
Worker/Owner address shows as a t0 address

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#1430]
**Describe the bug**
It is expected to show an account address, which should be t3 or t1 type, but it shows a t0 address when run `state miner-info ` command. 

** commit ID**
interopnet branch: baeb09739aea9f335b66a44d69aeb178bd10730b

**Comment by magik6k** [comment]
On chain these addresses are now stored in their ID form. You can get the underlying key with `lotus state lookup --reverse t0..`
