### ISSUE TITLE
chainwatch err

### ISSUE THREAD

**Issue by johnli-helloworld** [filecoin-project/lotus#1432]
**Describe the bug**
pq: could not create unique index "state_heights_uindex"

**To Reproduce**
1. chainwatch run 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26270251/77075300-12d14a80-6a2d-11ea-8f1d-cf4b52d26179.png)

**Version (run `lotus --version`):**
psql (PostgreSQL) 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)

**Comment by johnli-helloworld** [comment]
ERROR : ERROR:  could not create unique index "state_heights_uindex"
DETAIL:  Key (height)=(2175) is duplicated.

**Comment by johnli-helloworld** [comment]
storage.go :   create index if not exists state_heights_uindex
	on state_heights (height);

**Comment by magik6k** [comment]
This got fixed
