### ISSUE TITLE
HTTP Authorization header not possible from browser JavaScript WebSockets API

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#1441]
I was a bit surprised to discover this, but apparently it's not possible to send the "Authorization: bearer <token>" HTTP header using the Javascript WebSocket API.

https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api

https://devcenter.heroku.com/articles/websocket-security

I can set headers using the Javascript fetch API and make the calls that require extra permissions using HTTP instead of WebSockets.

It would be nice if there was an additional mechanism to provide authorization tokens for the API so protected methods could be used with WebSockets from a web page.

**Comment by magik6k** [comment]
There is: https://github.com/filecoin-project/lotus/blob/3b34eba6124d16162b712e971f0db2ee108e0f67/lib/auth/handler.go#L26

Just pass it as a form value - `ws://127.0.0.1:1234/rpc/v0?token=[b64 token]`

**Comment by magik6k** [comment]
(this is how pond does it: https://github.com/filecoin-project/lotus/blob/master/lotuspond/front/src/NodeList.js#L38)

**Comment by jimpick** [comment]
Thanks! I should have checked there first. I'll try that out.
