### ISSUE TITLE
testnet/3 api_full.go StatePledgeCollateral  result fail

### ISSUE THREAD

**Issue by EricZ11** [filecoin-project/lotus#1443]
![BCC0A9F0-17E1-4D68-8B16-0BE1701DD37A](https://user-images.githubusercontent.com/40593042/77288950-e6128100-6d13-11ea-912e-ef8e96ba33b8.png)

obviously, this is not the result we want

https://github.com/filecoin-project/lotus/blob/testnet/3/api/api_full.go#L128

**Comment by EricZ11** [comment]
this interface used to be available . such as : https://filscan.io/#/   hone page Pledge Collateral

**Comment by EricZ11** [comment]
this interface used to be available . 
such as : https://filscan.io/#/ 
home page Pledge Collateral

**Comment by magik6k** [comment]
This function is now unused / removed
