### ISSUE TITLE
Why my commit is 0? Power: 0 B / 5.26 PiB (0.0000%)

### ISSUE THREAD

**Issue by Seongjae-lim** [filecoin-project/lotus#1449]
Miner: t033013
Sector Size: 32 GiB
Power: 0 B / 5.26 PiB (0.0000%)
	Committed: 0 B
	Proving: 0 B
Worker use:
	Local: 0 / 4 (+1 reserved)
	Remote: 0 / 0
Queues:
	AddPiece: 0
	PreCommit: 0
	Commit: 0
	Unseal: 0
Proving Period: Not Proving
Sectors:  map[Total:0]

I have 120gb Ssd and 8tb HDD , and i want to know why my commit power is 0.
I have done lotus-storage-miner pledge-sector. and nothing happened.

PLZ HELp me to solve this problem. 

why my power is 0 B / 5.26 PiB T_T

**Comment by Seongjae-lim** [comment]
sealing isn't going . When i type lotus-storage-miner pledge-sector, this is all i got.

	sectors	sealing/garbage.go:39	Pledge 23, contains []
2020-03-25T14:33:06.230+0900	WARN	nat	go-log@v1.0.1/log.go:191	failed to establish port mapping: goupnp: error performing SOAP HTTP request: Post "http://192.168.0.1:50930/ctl/IPConn": dial tcp 192.168.0.1:50930: i/o timeout

what is problem? T_T

**Comment by olegv1992** [comment]
Have the same problem


 lotus-storage-miner info
Miner: t033142
Sector Size: 32 GiB
Power: 0 B / 5.03 PiB (0.0000%)
	Committed: 0 B
	Proving: 0 B
Worker use:
	Local: 1 / 1 (+1 reserved)
	Remote: 0 / 0
Queues:
	AddPiece: 1
	PreCommit: 3
	Commit: 0
	Unseal: 0
Proving Period: Not Proving
Sectors:  map[Total:3 Unsealed:3]

**Comment by Seongjae-lim** [comment]
a@a-H310MHP:~$ lotus-storage-miner info
Miner: t033013
Sector Size: 32 GiB
Power: 0 B / 5.09 PiB (0.0000%)
	Committed: 0 B
	Proving: 0 B
Worker use:
	Local: 2 / 4 (+1 reserved)
	Remote: 0 / 2
Queues:
	AddPiece: 0
	PreCommit: 0
	Commit: 0
	Unseal: 0
Proving Period: Not Proving
Sectors:  map[Total:2 Unsealed:2]

**Comment by whyrusleeping** [comment]
You need to seal enough sectors to get over the minimum miner threshold, which is currently 1TiB.
