### ISSUE TITLE
lotus will sync from  height 0 every time when restart container if i install lotus in one container

### ISSUE THREAD

**Issue by past2017** [filecoin-project/lotus#1459]
**Describe the bug**
lotus will sync from  height 0 every time if lotus is installed in one container and container is restarted

**To Reproduce**
1. Run a container and intall lotus in it and wait lotus sync to certain height like height 10000
2.  kill lotus and restart container and then start lotus
3. will find lotus will sync from height 0 and not 10000

**Expected behavior**
lotus will sync from height 10000 if restart container just as the result i install lotus in a host machine.

**Version (run `lotus --version`):**
v0.2.10

**Comment by arajasek** [comment]
This shouldn't happen if you sync all the way to the tip.

If you interrupt sync before it reaches the tip, then yes, it will restart from genesis when launched again. We'll be improving this in a later release.
