### ISSUE TITLE
Lotus checks validity of messages at the sync stage

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#1464]
Afaic tell, nodes should only validate message signatures when syncing, and deal with invalid messahes when executing the message in the subsequent tipset. I think we *do* perform some message validity checks when syncing a block. Blocks with such invalid messages will not be added at all, which I believe is spec-incompliant. If true, this will obviously call interop issues.

Here is a non-exhaustive list of validity checks we seem to perform:

- Sender can be found (happens when validating nonces)
- Sender is an account (will only happen if sender address is an ID address)
- Expected nonces (side-note: how do we order multiple messages from the same sender?)

**Comment by schomatis** [comment]
> I think we _do_ perform some message validity checks when syncing a block.

Yes, for reference you can see (incomplete documents):
* https://github.com/filecoin-project/armadillo/pull/5
* https://github.com/filecoin-project/armadillo/pull/3

**Comment by whyrusleeping** [comment]
I think any discrepancies here have been resolved, right @arajasek ?

**Comment by arajasek** [comment]
Yup...Idk what the spec says we *should* do, but we do reasonable things
