### ISSUE TITLE
sudo make install     ERROR

### ISSUE THREAD

**Issue by lishuailibertine** [filecoin-project/lotus#1471]
**Describe the bug**
sudo make install     ERROR

**To Reproduce**
➜  lotus git:(master) sudo make install  
install -C ./lotus /usr/local/bin/lotus
install: ./lotus: No such file or directory
make: *** [install] Error 71

**Screenshots**

**Version (run `lotus --version`):**

**Additional context**
<img width="613" alt="image" src="https://user-images.githubusercontent.com/7145192/77882237-2bdec480-7293-11ea-8f3b-48790fd2469c.png">

**Comment by AllanOricil** [comment]
@lishuailibertine how did you solve this problem?
