### ISSUE TITLE
Actor call library on top of API

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#148]
To simplify basic things like getting a storage miner peerid, something like:

```
act := apiactor.StorageMiner(api) // Could also take options like tipset
peerid := act.GetPeerID()
```

We may also want a variant, which can commit messages to chain, but that can be done later.

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/lotus/blob/a5c05f87f15fdaa00a2b56472981f0a93c0de9df/api/api_common.go#L28

**Comment by jennijuju** [comment]
@magik6k are all the features 1-year-ago you thought about being addressed?

**Comment by magik6k** [comment]
`chain/actors` kind of does this
