### ISSUE TITLE
seal pre commit(2) in case miner and remote worker have same directory

### ISSUE THREAD

**Issue by ldoublewood** [filecoin-project/lotus#1486]
**Describe the bug**
seal pre commit(2) in case miner and remote worker have same directory

**To Reproduce**
1. Run miner and a remote worker as a private network
2. IMPORTANT: miner and remote worker use different directory, e.g. /home/miner for miner, /home/worker for worker
3. Run "sector pledge" in miner
4. Check worker log and run "sectors list"
5. See PreCommitFail in sectors list and disappear after a while
6. See the following log in worker
2020-03-31T10:51:59.971+0800    WARN    sectors sealing/fsm.go:288      sector 9 got error event sealing.SectorSealFailed: seal pre commit(2) failed: presealing sector 9 (): Missing store file: /home/miner/.lotusworker/cache/s-t01007-9/sc-02-data-layer-1.dat

**Expected behavior**
No error message and no Fail in sector list

**Screenshots**

**Version (run `lotus --version`):**
testnet/3, f2d90b83

**Additional context**

**Comment by magik6k** [comment]
This is now fixed
