### ISSUE TITLE
执行 lotus-storage-miner state sectors命令时lotus-storage-miner/main.go:76	(get sset) failed to load miner actor state: cbor input had wrong number of fields

### ISSUE THREAD

**Issue by wangkaikai12345** [filecoin-project/lotus#1499]
![image](https://user-images.githubusercontent.com/27424792/78233233-00b0db00-7508-11ea-8d7d-500ed08f37c2.png)

**Comment by flyworker** [comment]
I think it is better to use English in tittle since this is a globe project.

**Comment by arajasek** [comment]
This is likely a versioning issue -- were you trying to run the latest version with empty databases?

**Comment by magik6k** [comment]
This was likely caused by mismatched node versions, or old repo

**Comment by shenmingxing** [comment]
您好， 你这个问题后来是怎么解决的
