### ISSUE TITLE
websocket: bad handshake

### ISSUE THREAD

**Issue by lishuailibertine** [filecoin-project/lotus#1530]
**Describe the bug**
➜  ~ git:(master) ✗ lotus sync wait
2020-04-09T13:37:48.982+0800	WARN	main	lotus/main.go:81	websocket: bad handshake
**To Reproduce**
1. Run 'lotus sync wait'
2. 2020-04-09T13:37:48.982+0800	WARN	main	lotus/main.go:81	websocket: bad handshake
**Screenshots**
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/7145192/78861492-77e5f200-7a67-11ea-87d5-0a7925c3133c.png">

**Version (run `lotus --version`):**
lotus version 0.3.0+git257227b3

**Comment by lishuailibertine** [comment]
In the morning is normal, this kind of error occurs in the afternoon

**Comment by liangping** [comment]
@lishuailibertine  did you solve this issue? I had this error as well.

**Comment by ArseniiPetrovich** [comment]
I'm having the same issue too.

**Comment by qiluge** [comment]
hello, please, how to solve this problem?

**Comment by Drug0j** [comment]
WARN    main    lotus/main.go:81        websocket: bad handshake
