### ISSUE TITLE
interopnet: daemon crashed

### ISSUE THREAD

**Issue by pwconv** [filecoin-project/lotus#1531]
**Describe the bug**
on interopnet branch, lotus daemon crashed on memory allocation

**To Reproduce**
1. Run '...'
2. See error
2020-04-09T19:57:18.602+0800    ESC[33mWARNESC[0m       vm      vm/runtime.go:295       vmctx send failed: to: t04, method: 15: ret: [], err: failed to defer cron event (RetCode=1)
2020-04-09T19:57:19.491+0800    ESC[33mWARNESC[0m       pubsub  go-log@v1.0.3/log.go:175        opening new stream to peer: stream reset12D3KooWSoBVoLtYKHdtqS93qnCy4oKQcNe8BZm1dghwzF1rT5gy
2020-04-09T19:57:19.629+0800    ESC[33mWARNESC[0m       pubsub  go-log@v1.0.3/log.go:175        opening new stream to peer: stream reset12D3KooWN9ygXRs8W5j2EAjspdCAoSjhRFFJFvZE1JUrfnwkyfkA
2020-04-09T19:57:19.737+0800    ESC[33mWARNESC[0m       pubsub  go-log@v1.0.3/log.go:175        opening new stream to peer: stream reset12D3KooWN9ygXRs8W5j2EAjspdCAoSjhRFFJFvZE1JUrfnwkyfkA
2020-04-09T19:57:19.912+0800    ESC[33mWARNESC[0m       modules modules/services.go:41  failed to say hello     {"error": "stream reset"}
2020-04-09T19:57:19.912+0800    ESC[33mWARNESC[0m       modules modules/services.go:41  failed to say hello     {"error": "stream reset"}
2020-04-09T19:57:19.912+0800    ESC[33mWARNESC[0m       pubsub  go-log@v1.0.3/log.go:175        opening new stream to peer: stream reset12D3KooWN9ygXRs8W5j2EAjspdCAoSjhRFFJFvZE1JUrfnwkyfkA
panic: memory alloc error: cannot allocate memory

goroutine 1135980 [running]:
github.com/filecoin-project/filecoin-ffi/generated.allocFilPublicReplicaInfoMemory(0x31488, 0xc0524f7920)
        /usr/local/src/testnet3.bak/lotus/extern/filecoin-ffi/generated/cgo_helpers.go:3227 +0xcd
github.com/filecoin-project/filecoin-ffi/generated.unpackArgSFilPublicReplicaInfo(0xc077c00000, 0x31488, 0x31488, 0x7d90151ba69e6b, 0x7fd810003600)
        /usr/local/src/testnet3.bak/lotus/extern/filecoin-ffi/generated/cgo_helpers.go:3429 +0x167
github.com/filecoin-project/filecoin-ffi/generated.FilVerifyPost(0x40c4638f9e45e1f, 0x6ef17c09d72a641f, 0x1e4dad9cc0875864, 0x7d90151ba69e6b, 0x0, 0x0, 0x0, 0x1f8b, 0xc077c00000, 0x31488, ...)
        /usr/local/src/testnet3.bak/lotus/extern/filecoin-ffi/generated/generated.go:552 +0xac
github.com/filecoin-project/filecoin-ffi.VerifyPoSt(0xc02ed0ee80, 0x20, 0x20, 0xc02d34cf00, 0x1, 0x1, 0xc0425984c0, 0x1, 0x1, 0xc074918000, ...)
        /usr/local/src/testnet3.bak/lotus/extern/filecoin-ffi/proofs.go:78 +0x323
github.com/filecoin-project/sector-storage/ffiwrapper.verifyPost(0x21092a0, 0xc0548b00c0, 0xc02ed0ee80, 0x20, 0x20, 0xc02d34cf00, 0x1, 0x1, 0xc0425984c0, 0x1, ...)
        /root/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200406195014-a6d093838576/ffiwrapper/verifier_cgo.go:142 +0xfc
github.com/filecoin-project/sector-storage/ffiwrapper.proofVerifier.VerifyElectionPost(...)
        /root/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200406195014-a6d093838576/ffiwrapper/verifier_cgo.go:129
github.com/filecoin-project/lotus/chain.(*Syncer).VerifyElectionPoStProof(0xc01eda9bc0, 0x21092a0, 0xc0548b00c0, 0xc042564a80, 0xc031ebd340, 0x31, 0x571fd4, 0x53059a)
        /usr/local/src/testnet3.bak/lotus/chain/sync.go:769 +0xcac
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6(0xc024a49780, 0x8)
        /usr/local/src/testnet3.bak/lotus/chain/sync.go:638 +0x5b
github.com/Gurpartap/async.Err.func1(0xc031f01740, 0xc031f513c0, 0xc050b9a0c0)
        /root/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:29 +0x5b
created by github.com/Gurpartap/async.Err
        /root/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:27 +0x8a

**Version (run `lotus --version`):**
lotus version 0.3.0+gitfca3f3a8

seems like it is trying to use C.calloc to allocate memory larger than available memory.

**Comment by gavin-ygy** [comment]
last my lotus daemon crashed too.  version:0.3.0+gitfca3f3a.  the errors:
github.com/ipfs/go-bitswap/sessionpeermanager.(*SessionPeerManager).run(0xc02fb0dc20, 0x210d140, 0xc03313bfc0)
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:149 +0xfd
created by github.com/ipfs/go-bitswap/sessionpeermanager.New
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:72 +0x20d

goroutine 24658129 [select]:
github.com/ipfs/go-bitswap/sessionpeermanager.(*SessionPeerManager).run(0xc037aded20, 0x210d140, 0xc039b42140)
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:149 +0xfd
created by github.com/ipfs/go-bitswap/sessionpeermanager.New
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:72 +0x20d

goroutine 30526060 [select]:
github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).runQueue(0xc0196d04d0)
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:104 +0x101
created by github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).Startup
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:94 +0x98

goroutine 35984596 [IO wait]:
internal/poll.runtime_pollWait(0x7fe1e415dc60, 0x72, 0xffffffffffffffff)
        /home/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc022e8db18, 0x72, 0x9900, 0x9974, 0xffffffffffffffff)
        /home/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc022e8db00, 0xc01f756000, 0x9974, 0x9974, 0x0, 0x0, 0x0)
        /home/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc022e8db00, 0xc01f756000, 0x9974, 0x9974, 0x203011, 0x0, 0x572552)
        /home/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc02055b268, 0xc01f756000, 0x9974, 0x9974, 0x0, 0x0, 0x0)
        /home/go/src/net/net.go:184 +0x68
crypto/tls.(*atLeastReader).Read(0xc045665de0, 0xc01f756000, 0x9974, 0x9974, 0xc000154b00, 0xc04dc68600, 0xc027539bb8)
        /home/go/src/crypto/tls/conn.go:780 +0x60
bytes.(*Buffer).ReadFrom(0xc02c20a958, 0x20e2960, 0xc045665de0, 0x50df15, 0x1c0b660, 0x1da2140)
        /home/go/src/bytes/buffer.go:204 +0xb4
crypto/tls.(*Conn).readFromUntil(0xc02c20a700, 0x7fe1e408c438, 0xc05debad50, 0x5, 0xc05debad50, 0x176)
        /home/go/src/crypto/tls/conn.go:802 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc02c20a700, 0x0, 0x0, 0x55161a)
        /home/go/src/crypto/tls/conn.go:609 +0x124
crypto/tls.(*Conn).readRecord(...)
        /home/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0xc02c20a700, 0xc021ec0220, 0xc, 0xc, 0x0, 0x0, 0x0)
        /home/go/src/crypto/tls/conn.go:1255 +0x161
io.ReadAtLeast(0x7fe1ea1cead0, 0xc030f4f400, 0xc021ec0220, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
        /home/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /home/go/src/io/io.go:329
github.com/libp2p/go-yamux.(*Session).recvLoop(0xc01bc78620, 0x0, 0x0)
        /home/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.3.3/session.go:558 +0xe9
github.com/libp2p/go-yamux.(*Session).recv(0xc01bc78620)
        /home/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.3.3/session.go:537 +0x2b
created by github.com/libp2p/go-yamux.newSession
        /home/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.3.3/session.go:129 +0x3c2

goroutine 20250797 [select]:
github.com/ipfs/go-bitswap/sessionpeermanager.(*SessionPeerManager).run(0xc029d02000, 0x210d140, 0xc0502b4ec0)
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:149 +0xfd
created by github.com/ipfs/go-bitswap/sessionpeermanager.New
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:72 +0x20d

goroutine 35307339 [select]:
github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).runQueue(0xc03879b8c0)
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:104 +0x101
created by github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).Startup
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:94 +0x98

goroutine 35990347 [select]:
github.com/libp2p/go-yamux.(*Session).sendLoop(0xc0274d0380, 0x0, 0x0)
        /home/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.3.3/session.go:504 +0x9d5
github.com/libp2p/go-yamux.(*Session).send(0xc0274d0380)
        /home/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.3.3/session.go:413 +0x2b
created by github.com/libp2p/go-yamux.newSession
        /home/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.3.3/session.go:130 +0x3e4

goroutine 27794107 [select]:
github.com/ipfs/go-bitswap/sessionpeermanager.(*SessionPeerManager).run(0xc0301f3180, 0x210d140, 0xc047655080)
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:149 +0xfd
created by github.com/ipfs/go-bitswap/sessionpeermanager.New
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:72 +0x20d

rax    0x0
rbx    0x7fdf9441b6f0
rcx    0xffffffffffffffff
rdx    0x6
rdi    0xdd94
rsi    0xe1d0
rbp    0x0
rsp    0x7fdfb57f9468
r8     0x0
r9     0xf
r10    0x8
r11    0x202
r12    0x7fdf943beb90
r13    0x20
r14    0x7fdf943beba8
r15    0x7fdf941760b0
rip    0x7fe1e90942e7
rflags 0x202
cs     0x33
fs     0x0
gs     0x0

**Comment by ldoublewood** [comment]
I have the same is issue as below:

My lotus version is: 0.3.0+gitfc3b42df

panic: memory alloc error: cannot allocate memory

goroutine 20229631 [running]:
github.com/filecoin-project/filecoin-ffi/generated.allocFilPublicReplicaInfoMemory(0x30aee, 0xc041a542c0)
        /tank1/filcloud/src/lotus/extern/filecoin-ffi/generated/cgo_helpers.go:3227 +0xcd
github.com/filecoin-project/filecoin-ffi/generated.unpackArgSFilPublicReplicaInfo(0xc05fb26000, 0x30aee, 0x30aee, 0xdd6c4a145eb6ca, 0x7f4248f805a0)
        /tank1/filcloud/src/lotus/extern/filecoin-ffi/generated/cgo_helpers.go:3429 +0x167
github.com/filecoin-project/filecoin-ffi/generated.FilVerifyPost(0x8b806f62e7951d66, 0xd5133f4dc19247a3, 0x1e69575b42108, 0xdd6c4a145eb6ca, 0x0, 0x0, 0x0, 0x1f29, 0xc05fb26000, 0x30aee, ...)
        /tank1/filcloud/src/lotus/extern/filecoin-ffi/generated/generated.go:552 +0xac
github.com/filecoin-project/filecoin-ffi.VerifyPoSt(0xc021ef1460, 0x20, 0x20, 0xc027e266c0, 0x1, 0x1, 0xc01f1cb080, 0x1, 0x1, 0xc05f436000, ...)
        /tank1/filcloud/src/lotus/extern/filecoin-ffi/proofs.go:78 +0x336
github.com/filecoin-project/sector-storage/ffiwrapper.verifyPost(0x20b9940, 0xc0467f1620, 0xc021ef1460, 0x20, 0x20, 0xc027e266c0, 0x1, 0x1, 0xc01f1cb080, 0x1, ...)
        /home/gucloud/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200406195014-a6d093838576/ffiwrapper/verifier_cgo.go:142 +0xf7
github.com/filecoin-project/sector-storage/ffiwrapper.proofVerifier.VerifyElectionPost(...)
        /home/gucloud/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200406195014-a6d093838576/ffiwrapper/verifier_cgo.go:129
github.com/filecoin-project/lotus/chain.(*Syncer).VerifyElectionPoStProof(0xc000499200, 0x20b9940, 0xc0467f1620, 0xc01f1c1500, 0xc01c901480, 0x31, 0x5776d4, 0xc035eac0d0)
        /tank1/filcloud/src/lotus/chain/sync.go:769 +0xcaf
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6(0xc00061d4e0, 0x1f062f8)
        /tank1/filcloud/src/lotus/chain/sync.go:638 +0x5b
github.com/Gurpartap/async.Err.func1(0xc0296e34a0, 0xc028211200, 0xc02770b8d0)
        /home/gucloud/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:29 +0x53
created by github.com/Gurpartap/async.Err
        /home/gucloud/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:27 +0x8a

**Comment by whyrusleeping** [comment]
These all look like out of memory issues. I opened #1876 for this
