### ISSUE TITLE
lotus crash, interopnet v0.3.0+gitfca3f3a

### ISSUE THREAD

**Issue by gavin-ygy** [filecoin-project/lotus#1533]
**Describe the bug**
during sync the chain .

**To Reproduce**
1. Run '...'
2. See error
github.com/ipfs/go-bitswap/sessionmanager.(*SessionManager).NewSession.func1(0xc024a2ffc0, 0xc0003d1300, 0x210d700, 0xc027412200, 0x2110700, 0xc05aa94000, 0x2104180, 0xc0246cca20, 0x210d180, 0xc00003c0b0)
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionmanager/sessionmanager.go:86 +0x114
created by github.com/ipfs/go-bitswap/sessionmanager.(*SessionManager).NewSession
        /home/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionmanager/sessionmanager.go:84 +0x339

goroutine 2052520 [semacquire]:
sync.runtime_SemacquireMutex(0xc0006469bc, 0xc022ebfa00, 0x1)
        /home/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0006469b8)
        /home/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
        /home/go/src/sync/mutex.go:81
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).Add(0xc000646990, 0xc062848400, 0x0, 0x0)
        /home/lotus/chain/messagepool/messagepool.go:311 +0xe3
github.com/filecoin-project/lotus/chain/sub.(*MessageValidator).Validate(0xc04f234108, 0x210d140, 0xc049e5e100, 0xc05c73ea80, 0x26, 0xc0607ad380, 0xc000071900)
        /home/lotus/chain/sub/incoming.go:185 +0x34b
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg(0xc04f2a4720, 0x210d140, 0xc049e5e100, 0xc05c73ea80, 0x26, 0xc0607ad380, 0xc0350d4600)
        /home/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.2.6/validation.go:336 +0x98
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic(0xc049e67dd0, 0xc04f2a4720, 0xc05c73ea80, 0x26, 0xc0607ad380, 0xc0350d4600)
        /home/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.2.6/validation.go:317 +0xa6
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic(0xc049e67dd0, 0xc05b41a020, 0x1, 0x1, 0xc05c73ea80, 0x26, 0xc0607ad380, 0x1da2100)
        /home/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.2.6/validation.go:270 +0x3b3
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic(0xc049e67dd0, 0xc05b41a020, 0x1, 0x1, 0xc05c73ea80, 0x26, 0xc0607ad380)
        /home/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.2.6/validation.go:259 +0x80
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1(0xc049e67dd0, 0xc05b41a020, 0x1, 0x1, 0xc05c73ea80, 0x26, 0xc0607ad380)
        /home/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.2.6/validation.go:234 +0x67
created by github.com/libp2p/go-libp2p-pubsub.(*validation).validate
        /home/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.2.6/validation.go:233 +0x46d

rax    0x0
rbx    0x7fae95930af0
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x15ee0c
rsi    0x15f381
rbp    0x0
rsp    0x7faef17f9468
r8     0x0
r9     0xf
r10    0x8
r11    0x206
r12    0x7fae951675b0
r13    0x20
r14    0x7fae951675c8
r15    0x7fae958eb7a0
rip    0x7fb1cfb842e7
rflags 0x206
cs     0x33
fs     0x0
gs     0x0

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**

**Additional context**

**Comment by whyrusleeping** [comment]
Without seeing the full stack trace, i'm going to assume this is an out of memory bug. We are working on a number of improvements here. Please open a new issue with the full stack trace if this happens again
