### ISSUE TITLE
louts Use create-worker-key to create an error

### ISSUE THREAD

**Issue by hlb168** [filecoin-project/lotus#1536]
**Describe the bug**
louts Use create-worker-key to create an error

**To Reproduce**
1. ./lotus-storage-miner init --create-worker-key=true --owner=t3s3xpjdq3krwz6krlhaywi5e65b5ufckh6yh3tmd4eaq6sl44fyhvp45ouvg2xdqozxxsojfnpeilzuv45qqq --nosync 

See error：
ERROR main lotus-storage-miner/init.go:237 Failed to initialize lotus-storage-miner: creating miner failed:
    main.storageMinerInit
        /home/test/filecoin-project/lotus-source/cmd/lotus-storage-miner/init.go:492
  - create storage miner failed: exit code 16:
    main.createStorageMiner
        /home/test/filecoin-project/lotus-source/cmd/lotus-storage-miner/init.go:639
main.glob..func2
        /home/test/filecoin-project/lotus-source/cmd/lotus-storage-miner/init.go:237
gopkg.in/urfave/cli%2ev2.(*Command).Run
        /home/test/gocode/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:167
gopkg.in/urfave/cli%2ev2.(*App).Run
        /home/test/gocode/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/app.go:261
main.main
        /home/test/filecoin-project/lotus-source/cmd/lotus-storage-miner/main.go:79
runtime.main

the network reply:

Send actor error {"from": "t3s55v6xrff3yz7jty6sk5ni4tz3jjlf4a3565fxyiqqnhlu2n632zlk5hywlb75gtzf76memsa7e2s4gne6aq", "to": "t04", "nonce": 1, "method": "4", "height": "333", "error": "failed to init new actor (RetCode=16):\n github.com/filecoin-project/specs-actors/actors/builtin.RequireSuccess\n /home/test/gocode/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200324235424-aef9b20a9fb1/actors/builtin/shared.go:17"}

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**
lotus version 0.3.0+gitfca3f3a8.dirty

**Additional context**
Using create-worker-key  will generate a new wallet address

**Comment by skyhuihui** [comment]
I have the same problem.  What is the solution to this problem
