### ISSUE TITLE
Placeholder for market issues

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#1538]
Collect market-related issues here, ideally spin them into their own issues before putting time into investigating.

**Comment by arajasek** [comment]
1) Follow up with partners regarding offline deal workflow / commP issues

**Comment by arajasek** [comment]
Reported here: https://filecoinproject.slack.com/archives/CPFTWMY7N/p1585945303257400

laser Apr 3rd at 4:21 PM
I am running a 10 daemon dev network on EC2 + one daemon running on my laptop. All daemons and storage miners have been peered successfully.
When I propose a storage deal using my local daemon to the miners running in EC2, the lotus client list-deals command shows the deals progressing from StorageDealUnknown to StorageDealValidating and finally to StorageDealSealing. 9 of the 10 storage deals which I have proposed are stuck in the StorageDealSealing state, and one has made it to StorageDealActive.
Using the lotus-storage-miner deals list command (on each of the storage miners which have accepted my deal proposals), I see no problems. When I use lotus-storage-miner sectors status 0, I see that each sector has Status: Proving, and that its Deals output includes the storage deal proposed by my client.
Unfortunately, the client never sees 9 of the 10 deals progress from StorageDealSealing to StorageDealActive. Is this a known bug?
Note: I'm using CloudFormation to provision this dev network, so this issue can be reproduced somewhat trivially using a few CloudFormation templates and Bash scripts.
9 replies

laser  10 days ago
Here's what the client sees:
13:14 $ lotus client list-deals
DealCid                                                      Provider  State               PieceCID                                                       Size  Price    Duration  Message
bafyreia7lld42jej4pyreig7piqxmkbfcidhzpyh5icj5sxd7hnpkl36oq  t01016    StorageDealSealing  bafk4chza7qwcfdo2s3t5rzh3fcvylobgoujy42bjixs3mk4dt3n7ilpgbqna  2032  1000000  5
bafyreiamz5turke2vhgyfj3bhj4x3k2w4lp2hwieewhiaktqh3awbzeggm  t01000    StorageDealSealing  bafk4chza7qwcfdo2s3t5rzh3fcvylobgoujy42bjixs3mk4dt3n7ilpgbqna  2032  1000000  5
bafyreidbydlapszgvkm2cfjjgfbzimypacleaq5jsu4cxidp6lw7j524cy  t01012    StorageDealSealing  bafk4chza7qwcfdo2s3t5rzh3fcvylobgoujy42bjixs3mk4dt3n7ilpgbqna  2032  1000000  5
bafyreidsf67fuik6ilxcnjhuhzsxu7ywcbn67wmcfyynw7y4zz4zcrw72m  t01018    StorageDealSealing  bafk4chza7qwcfdo2s3t5rzh3fcvylobgoujy42bjixs3mk4dt3n7ilpgbqna  2032  1000000  5
bafyreiemhx4sfhowr4bmmet5e3ie3qhdnzgosppxncfbyhsi7b2fj6s3fm  t01004    StorageDealActive   bafk4chza7qwcfdo2s3t5rzh3fcvylobgoujy42bjixs3mk4dt3n7ilpgbqna  2032  1000000  5
bafyreiftfjgptfm6laeq4nlkgdj6xnmc4a3mukx6vpfr6qoyrba4sqwrkq  t01002    StorageDealSealing  bafk4chza7qwcfdo2s3t5rzh3fcvylobgoujy42bjixs3mk4dt3n7ilpgbqna  2032  1000000  5
bafyreigg477zj4iyck2mhbxql2245obbfotetdjtuxniqsr7brhd2s7qd4  t01014    StorageDealSealing  bafk4chza7qwcfdo2s3t5rzh3fcvylobgoujy42bjixs3mk4dt3n7ilpgbqna  2032  1000000  5
bafyreigydvy2nbs57335qphsgjiqnnptniheadyfucvcpjrzzcr6rfjgpu  t01006    StorageDealSealing  bafk4chza7qwcfdo2s3t5rzh3fcvylobgoujy42bjixs3mk4dt3n7ilpgbqna  2032  1000000  5
bafyreihgy6sbx5t4pmn6mhn4glxb2e3i25cllwmw2fhxs4w5xi24elesfa  t01010    StorageDealSealing  bafk4chza7qwcfdo2s3t5rzh3fcvylobgoujy42bjixs3mk4dt3n7ilpgbqna  2032  1000000  5
bafyreihtzaoa5m6snmihil7a4vfx6dt7u4gxumfnma6g25ramdeixt7f5i  t01008    StorageDealSealing  bafk4chza7qwcfdo2s3t5rzh3fcvylobgoujy42bjixs3mk4dt3n7ilpgbqna  2032  1000000  5

laser  10 days ago
Here's what a miner sees:
root@ip-10-0-10-11:/# lotus-storage-miner info
Miner: t01006
Sector Size: 2 KiB
Power: 2 KiB / 24 KiB (8.3333%)
        Committed: 2 KiB
        Proving: 2 KiB
PoSt Submissions:
        Fallback: Epoch 407 (in 134 blocks, ~13m 24s)
        Deadline: Epoch 427 (in 374 blocks, ~37m 24s)
        Consecutive Failures: 0
Sectors:  map[Proving:1 Total:1]
root@ip-10-0-10-11:/# lotus-storage-miner deals list
2020-04-03T20:15:42.648Z        WARN    rpc     jsonrpc/client.go:385   unmarshaling failed     {"message": "[{\"Proposal\":{\"PieceCID\":{\"/\":\"bafk4chza7qwcfdo2s3t5rzh3fcvylobgoujy42bjixs3mk4dt3n7ilpgbqna\"},\"PieceSize\":2048,\"Client\":\"t3uqqtf7acuyw7masdmf2s6ja7p365f3qavvsmxpt5yuuvugj7a5gghtqijd32heshk6a2bojuwegfidccmava\",\"Provider\":\"t01006\",\"StartEpoch\":10063,\"EndEpoch\":10068,\"StoragePricePerEpoch\":\"1000000\",\"ProviderCollateral\":\"2032\",\"ClientCollateral\":\"0\"},\"ClientSignature\":{\"Type\":2,\"Data\":\"ocTiHQQtjt6vsO3x1wG/ggTL2WzZwR+zTZ0Jn96vdIs+5dKaByLb3EUTkJwVKqy1Aa8DDedz1VJGg6bOgWWxOs8EWKnZA8xPFHNVR2Dik5bmM5diwFuTzzkG7RGoCIbD\"},\"ProposalCid\":{\"/\":\"bafyreigydvy2nbs57335qphsgjiqnnptniheadyfucvcpjrzzcr6rfjgpu\"},\"Miner\":\"\",\"Client\":\"12D3KooWQHcEGrqGTNHBiYFrknM6KGKCT8kgp5Jedr9Ce8oRjy11\",\"State\":5,\"PiecePath\":\"fstmp473842281\",\"Message\":\"\",\"Ref\":{\"TransferType\":\"graphsync\",\"Root\":{\"/\":\"bafkreictaj2jkgz7pkyqtm3x3fdzos5pr7xcwxgdwaotdzictvpa4njjre\"},\"PieceCid\":null,\"PieceSize\":0},\"DealID\":5}]"}
2020-04-03T20:15:42.648Z        WARN    main    lotus-storage-miner/main.go:80  RPC client error: unmarshaling result: failed to parse peer ID: cid too short

laser  10 days ago
root@ip-10-0-10-11:/# lotus state power
24576(24 KiB)

laser  10 days ago
root@ip-10-0-10-11:/# lotus state proving t01006
0: 6261666b3465687a6173726934797737736735617561777967636136776b636d6c34726179666275336a6932376565356a6864707764337168726e7361
I do have some software which reproduces this issue... but it's pretty complicated (probably doesn't fit the definition of "a script"). That said, if you have AWS credentials that are authorized to provision loads of virtualized network hardware and EC2 instances, then you can use it with minimal modification. It's just a couple of commands: something to bring up the network, something to run the test, and something to destroy the network.
https://github.com/laser/aws-filecoin
This set of scripts and CloudFormation templates provisions 150 EC2 instances, each running lotus storage miners. They all connect to each other, and then a storage client (running on your local host) attempts to make storage deals with each of them. Then the network is torn down, EC2 instances and VPC destroyed, yadda yadda. (edited)

**Comment by arajasek** [comment]
3) https://filecoinproject.slack.com/archives/CPFTWMY7N/p1586590716487500

Reported here:

When I execute. / Lotus client deal
bafkreigegv6sa6qm3n6eqzfqk7itv2xaijpfs6gc6hu5bfhi2mrcp24uu
t01000.0000000000000001 10, except for the first success, the rest will
inevitably fail
2020-04-11T15:37:05.516+0800	WARN	providerstates	providerstates/provider_states.go:292	deal bafyreigkcyiz7pyhn7wdleerrnkxn6xx3r44sl5ivofbvscvmvy75iod2y failed: error calling node: publishing deal: publishing deal failed: exit 1
r=&{Receipt:{ExitCode:SysErrSenderInvalid(1) Return:[] GasUsed:2368} TipSet:0xc01d981280}

**Comment by long568** [comment]
I got the same proplem...

**Comment by magik6k** [comment]
If any of this is still relevant I'd open this as new issues
