### ISSUE TITLE
ChainGetTipSetByHeight slow for low-value heights

### ISSUE THREAD

**Issue by jesseclay** [filecoin-project/lotus#1540]
**Describe the bug**
`ChainGetTipSetByHeight` method seems to be pretty slow for low value heights, looks like it’s just going from head all the way back. Possible to speed this up? Possibly throw more memory towards a cache or something?

**Comment by whyrusleeping** [comment]
should be resolved by #1915

**Comment by jesseclay** [comment]
thanks @whyrusleeping!
