### ISSUE TITLE
Lotus architecture document

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/lotus#1547]
We need a high-level document outlining the architecture of the code in this repository (in general but specifically) for the audit. I can get something started and pull things together but the meat of it will need to come from the developers.

**Comment by whyrusleeping** [comment]
@schomatis if you can handle drawing up a skeleton, we can help fill it in

**Comment by schomatis** [comment]
Great, thanks.

**Comment by schomatis** [comment]
First draft completed in https://github.com/filecoin-project/lotus/tree/master/documentation/en/architecture.
