### ISSUE TITLE
StateCall jsonrpc handler returns MsgRct with 0 GasUsed

### ISSUE THREAD

**Issue by Schwartz10** [filecoin-project/lotus#1548]
**Describe the bug**
The MsgRct returned from StateCall seems to always come back with GasUsed amount of "0". I am testing this on a local network, running interop network commit hash `fc3b42dfb6ed25676e097813945adbb66040b22e`

**To Reproduce**
1. Run a local net (not sure if this matters yet, haven't been able to sync up with the canonical interop chain)
2. Send a request to the `Filecoin.StateCall` jsonrpc handler (replace your token in the sample curl request, and make sure that you use a `From` address that exists on chain, or the call will fail):

```
curl --location --request POST 'http://127.0.0.1:1234/rpc/v0' \
--header 'Authorization: Bearer <TOKEN>
--header 'Content-Type: text/plain' \
--data-raw '{
"jsonrpc": "2.0",
"method": "Filecoin.StateCall",
"id": 1,
"params": [{
	"To": "t1hvuzpfdycc6z6mjgbiyaiojikd6wk2vwy7muuei",
	"From": "t3wsspmzh7rbetvblpe6opqnz2bomubibuygg234xdpnb7eqdokrnhy4yto2cl4x5czezc3mz5xl4gz524vh7a",
	"Nonce": 0,
	"Value": "1000",
	"Method": 0,
	"GasPrice": "1",
	"GasLimit": 1000,
	"Params": []
}, null]
}'
```

3. See the Message receipt come back with 0 gas used. 

**Expected behavior**
I would like to see a gas usage estimate in the response.

**Version (run `lotus --version`):**
lotus version 0.3.0+gitfc3b42df.dirty

**Additional context**
Here are the steps I took to run the local chain (a huge thanks to Aayush for the assist!):

0) make clean && make all && make debug && sudo make install
1) ./lotus-seed pre-seal --sector-size 2048 --num-sectors 10
2) ./lotus-seed genesis new lotusgen.json
3) ./lotus-seed genesis add-miner lotusgen.json ~/.genesis-sectors/pre-seal-t01000.json
4) ./lotus daemon --lotus-make-genesis=dev.gen --genesis-template=lotusgen.json --bootstrap=false
(in a separate tab)
5) ./lotus wallet import ~/.genesis-sectors/pre-seal-t01000.key
6) ./lotus-storage-miner init --genesis-miner --actor=t01000 --sector-size=2048 --pre-sealed-sectors=~/.genesis-sectors --pre-sealed-metadata=~/.genesis-sectors/pre-seal-t01000.json --nosync
7) ./lotus-storage-miner run --nosync

The local net appears healthy, I can send messages that get mined...etc

**Comment by magik6k** [comment]
Seems to still be the case

**Comment by Kubuxu** [comment]
Yeah, `StateCall` is using `State.Call` not `State.CallWithGas`.

**Comment by magik6k** [comment]
`StateCall` now returns gas used
