### ISSUE TITLE
initializing node error: cbor input had wrong number of fields

### ISSUE THREAD

**Issue by ohJohanZ** [filecoin-project/lotus#1553]
**Describe the bug**
2020-04-17T09:23:27.604Z        INFO    badger  v2@v2.0.1-rc1.0.20200120142413-c3333a5a830e/logger.go:46        All 0 tables opened in 0s

2020-04-17T09:23:27.608Z        WARN    chainstore      store/store.go:126     no previous chain state found
2020-04-17T09:23:27.612Z        WARN    main    lotus/main.go:81        initializing node:
    main.glob..func1
        /home/johan/lotus/cmd/lotus/daemon.go:182
  - starting node:
    github.com/filecoin-project/lotus/node.New
        /home/johan/lotus/node/builder.go:477
  - could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/johan/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.13/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.13/src/reflect/asm_amd64.s:12): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.13/src/reflect/asm_amd64.s:12): failed to build dtypes.AfterGenesisSet: function "reflect".makeFuncStub (/usr/lib/go-1.13/src/reflect/asm_amd64.s:12) returned a non-nil error: genesis func failed: decoding block failed: cbor input had wrong number of fields

**To Reproduce**
1. git checkout testnet/3
2. make all
1. Run 'lotus daemon'
2. See error

**Version (run `lotus --version`):**
lotus version 0.3.0+gitd56b5e2b

**Comment by magik6k** [comment]
This usually indicates an existing repository. Remove `~/.lotus` first, then retry

**Comment by ghoneycutt** [comment]
What specifically in LOTUS_PATH should be removed?

**Comment by ghoneycutt** [comment]
Removed the `.cbor` file from `$LOTUS_PATH/kvlog/metadata/` and then ran `lotus daemon` which caused it to sync as expected.
