### ISSUE TITLE
message sync issue when kill lotus daemon

### ISSUE THREAD

**Issue by fanyanjun** [filecoin-project/lotus#1561]
https://github.com/filecoin-project/lotus/issues/474
[One of my node was in the process of block synchronizing, and I just kill the lotus daemon and run it again, I found the block height of message sync from the very beginning, I think it should continue to sync from the block height before I kill the daemon process.]

 I also have this problem(lotus_v0.2.10_linux-amd64.tar.gz
). How can I do it?

**Comment by hayeah** [comment]
i ran into the same problem, fixed here: https://github.com/filecoin-project/lotus/pull/1560
