### ISSUE TITLE
make lotus-seal-worker   Issue 

### ISSUE THREAD

**Issue by klshe5** [filecoin-project/lotus#1567]
Hi, I have issue when i want to install Lotus-Seal-worker. 

Attached the error message, Any one have same issue, and how to fix it .Thanks 

![图片](https://user-images.githubusercontent.com/63886852/79856402-a53f8200-840f-11ea-969f-b871a5def3bf.png)

**Comment by Kubuxu** [comment]
You need to be in directory with lotus code.
