### ISSUE TITLE
DONOT use SPECIAL characters in filecoin-proof-parameters file names

### ISSUE THREAD

**Issue by vipally** [filecoin-project/lotus#1596]
In V25  filecoin-proof-parameters file list，include SPECIAL characters <,>  which maybe not supported by other OS.
eg:  Windows dose not support characters <>  as filepath，so if we download these files of V25 from Windows OS， and upload to linux server，the filenames doesn't match.

Upload snapshot fail. more details:
https://filecoinproject.slack.com/archives/CPFTWMY7N/p1587694983454200

**Comment by arajasek** [comment]
yeah, we'll avoid this in the next round
