### ISSUE TITLE
Lotus sync error

### ISSUE THREAD

**Issue by zh19910202** [filecoin-project/lotus#1601]
when I used the"lotus sync wait" command to check the block height, I got some message like that：
“Worker 1: Target: [bafy2bzacecbm6s3w7byehilpypcbulcxid2n36hqim4cj66gk6haercz42e6m bafy2bzaced23ccg3ox3c7f4c3cmamrrn6hvaedofcyv23ihelln25ypcvmjdi bafy2bzacecexf636okcca47yso6nrgdqbty52lqe6noazwyhxeomgbcizxpns]	State: error	Height:”
what does it mean if the State is error

**Comment by zh19910202** [comment]
does anybody how to fix it

**Comment by arajasek** [comment]
`lotus sync status` should give you more info about the error in question

**Comment by zh19910202** [comment]
yes, you are right, just repeat the same message again and again

**Comment by magik6k** [comment]
Can you paste the full output of `lotus sync status`, with the error message which will actually tell us what's wrong?

**Comment by zh19910202** [comment]
I guess, i solved this case

**Comment by metalsnail** [comment]
> 
> 
> I guess, i solved this case

can you tell me how to solve this issue?
