### ISSUE TITLE
Miner initalization Error 

### ISSUE THREAD

**Issue by klshe5** [filecoin-project/lotus#1608]
When i doing my Miner initalization never finish and have error message.

Is that any one know, what's the issue here. Thanks

attached the error message. 
![图片](https://user-images.githubusercontent.com/63886852/80269026-95fe5400-86ef-11ea-9b47-cb07ace53d60.png)

**Comment by magik6k** [comment]
Are you in China? Can you try following https://docs.lotu.sh/en+mining#note-using-the-lotus-storage-miner-from-china-107253 and seeing if it helps?

**Comment by klshe5** [comment]
Hi, Mate:

Thanks for your reply, I am not in China, I am in Australia. Cheers,

Regards.

Kai

________________________________

**Comment by jennijuju** [comment]
since SR, seems like folks in oceania no longer have trouble downloading params
