### ISSUE TITLE
lotus seal worker, can't get balance. 

### ISSUE THREAD

**Issue by ryan-kim21** [filecoin-project/lotus#1612]
**Describe the bug**

Hi dear team. 

I tried testnet for 3weeks. 
but I can't get the balance.. 
I don't know what's the problems.. 
I tried anything. but I can't get the balance. 
Could you help me?.. 

It has been stopped now. 
I get the message "Waiting for new task" for 1 day. 

I tried to restart 2 times. 
I get same issues.. 

and....... My Power is 0 Byte.....................................

Thanks,
Ryan.

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/63631441/80307514-858bcd80-8804-11ea-9dca-f2243d5824c1.png)

**Version (run `lotus --version`):**

**Additional context**

**Comment by magik6k** [comment]
Minimum power required to start miming blocks is 512G, so until you have sealed 512G, you won't see any power.

You can seal more sector by running `lotus-storage-miner pledge-sector` which will seal a bunch of random data (calling it once only seals 32G of data, you'll need to call it multiple times)

Please reopen in case of further issues
