### ISSUE TITLE
block service always get failed at  "stream reset" or "i/o deadline reached"

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/lotus#1614]
**Describe the bug**
lotus sync block failed and raised error as the below picture speaks.

**To Reproduce**
1. Run './lotus daemon' to join the interopnet
2. Run './lotus sync status'
3. Wait awhile and See error

**Expected behavior**
![image](https://user-images.githubusercontent.com/33315004/80378090-b9332a00-88ce-11ea-9b57-52053e3e2835.png)

**Screenshots**
as above.

**Version (run `lotus --version`):**
network : interopnet
commit : 1bfa2311d6931dc0c961d42f561ba0268dbd21c3

**Additional context**
not sure '5 * time.Second' is enough and how to sync recurrently when meet 'stream reset'.
lotus/chain/blocksync/blocksync_client.go:294
s.SetWriteDeadline(time.Now().Add(5 * time.Second))

**Comment by phil-andrews** [comment]
this might have to do with your open file limit - https://docs.lotu.sh/en+setup-troubleshooting

`ulimit -n 10000`

**Comment by magik6k** [comment]
We've rewritten big chocks of this sync code, I'm pretty sure it now handles timeouts correctly
