### ISSUE TITLE
branch iteropnet

### ISSUE THREAD

**Issue by AlfredZKY** [filecoin-project/lotus#1622]
Will your pool and mine be disconnected?I didn't do anything, too much time mining machine program died.
![2020-04-28 11-22-16屏幕截图](https://user-images.githubusercontent.com/32631293/80443829-b3772c00-8942-11ea-9427-f83c9c620ebe.png)

**Comment by magik6k** [comment]
Can you provide more information about your setup, and commands ran? What lotus version are you running?

**Comment by AlfredZKY** [comment]
I used the mine pool to match the remote miners. At the beginning, the mine pool and the miners were connected normally, and the mining task was also performed normally. However, after a short time, the progress of all the miners was inexplicably suspended.
