### ISSUE TITLE
prove commit sector number exceed 8192

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/lotus#1624]
**Describe the bug**
lotus interopnet network is halted by cbor bitfield MarshalCBOR.
vendor/github.com/filecoin-project/go-bitfield/bitfield.go:238
```
if len(rle) > 8192 {
		return xerrors.Errorf("encoded bitfield was too large (%d)", len(rle))
	}
```

that is caused by NewSectors exceed 8192.
```
// Sector numbers prove-committed since period start, to be added to Deadlines at next proving period boundary.
	NewSectors *abi.BitField
```
**To Reproduce**
dive into the current interopent:https://github.com/filecoin-project/lotus/commit/1bfa2311d6931dc0c961d42f561ba0268dbd21c3

**Expected behavior**
the chain is halted and all state related command get error :
```
2020-04-28T11:43:04.451+0800	WARN	main	lotus-storage-miner/main.go:95	computing tipset state failed: [from=t3vdmtplwzkxqtqa7et7izfupkzohf6ibjq5i2kpgrygbeolccrbyvl7olkynsypu3wvd4sjom65g2s6u3i4zq,to=t01268,n=150040,m=7,h=10878] fatal error: failed to put cbor object: encoded bitfield was too large (8193) (FATAL)
```

**Screenshots**
NA

**Version (run `lotus --version`):**
above.

**Additional context**
we should align the cbor/bitfield limitation with miner actors 's behavior.

**Comment by anorth** [comment]
@magik6k @Kubuxu just to confirm my understanding, the `8192` here is the number of bytes in the RLE-encoded bitset, rather than the number of items in the set, right? We do need to support bitfields of more than 8k near-contiguous entries

**Comment by Kubuxu** [comment]
Yes, it is number of bytes of the encoded bitset.
This means that in the worst case you will be able to encode "only" about 800 entires (if someone spreads their sectors like this: 1 set, 2^55 empty, 1set, 2^55 empty and so on).

It is many more in non-pathological cases.

**Comment by magik6k** [comment]
I think that the only thing we can / should address here is to make sure that the sector FSM won't commit additional sectors until NewSectors bitfield has more space (miner enters new proving period).

This will have the nice side effect of forcing people to assign continuous sector IDs, as not doing that will severely limit how many sectors they'll be able to commit per day

**Comment by magik6k** [comment]
I don't think this is an issue now
