### ISSUE TITLE
 failed to validate tipset: validating block

### ISSUE THREAD

**Issue by skyhuihui** [filecoin-project/lotus#1634]
The problem  ： Setup Local Devnet  ，Other nodes join

The log  ： 
`2020-04-29T19:08:01.708+0800    INFO    chain   chain/sync_manager.go:283       scheduling incoming tipset sync: [bafy2bzacecvh7ekmh7nryojp7623whkkrh5o3fs2kvxgrnurestqdespttpua]
2020-04-29T19:08:01.836+0800    INFO    chain   chain/sync.go:944       Got blocks: 730 500
2020-04-29T19:08:01.905+0800    WARN    chain   chain/sync.go:525       timestamp funtimes: 1588154088 1588154082 1 0
2020-04-29T19:08:01.905+0800    ERROR   chain   chain/sync.go:1039      failed to validate tipset: validating block bafy2bzacedqzrylidb7moxowodxcgdgaali3fxvoqb7ytd2xpoh5zkgt4llq2:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:457
  - block was generated too soon (h.ts:1588154088 < base.mints:1588154082 + BLOCK_DELAY:45 * deltaH:1):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:526
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:1039
github.com/filecoin-project/lotus/chain.(*Syncer).iterFullTipsets
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:1098
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:1036
github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:1172
github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:407
github.com/filecoin-project/lotus/chain.(*SyncManager).syncWorker
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync_manager.go:386
2020-04-29T19:08:01.905+0800    ERROR   chain   chain/sync_manager.go:388       sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:413
  - collectChain syncMessages:
    github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:1173
  - message processing failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:1040
  - validating block bafy2bzacedqzrylidb7moxowodxcgdgaali3fxvoqb7ytd2xpoh5zkgt4llq2:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:457
  - block was generated too soon (h.ts:1588154088 < base.mints:1588154082 + BLOCK_DELAY:45 * deltaH:1):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:526
github.com/filecoin-project/lotus/chain.(*SyncManager).syncWorker
        /root/gopath/src/github.com/filecoin-project/lotus/chain/sync_manager.go:388`

Operation command：
`
lotus daemon --genesis=gdev.gen --bootstrap=false
lotus net connect {genesis_node_id}
`

**Comment by arajasek** [comment]
Were the other nodes joining also being built with `make debug`? The devnet has a default block time of 2 seconds, but it looks like the other connecting node was expecting 45 seconds.
