### ISSUE TITLE
Properly charge gas for 'NOOP' messages

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#165]
Gas charging of them is a bit weird right now and IDK what should happen with them in general.

What I mean by NOOP is not invoking a method nor transferring funds.

**Comment by arajasek** [comment]
Having done some investigation, things look fine here. Specifically:

- You are charged for the on chain msg cost for "no-op" messages
- You *can* create a new account actor by sending it 0, and are appropriately charged for it
- You are charged correctly for sending 0 to yourself
