### ISSUE TITLE
miner proving info ---panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#1653]
**Describe the bug**
panic: runtime error: integer divide by zero when input miner proving info

**To Reproduce**
1. lotus daemon
2. miner run
3 miner  proving info

**Expected behavior**
cmd/lotus-storage-miner/proving.go:114
the  provenSectors is zero
fmt.Printf("Faults:      %d (%.2f%%)\n", faults, float64(faults*10000/provenSectors)/100)

**Screenshots**

**Version (run `lotus --version`):**

**Additional context**
miner proving info
Current Epoch:           161
Chain Period:            0
Chain Period Start:      0 (1h7m5s ago)
Chain Period End:        3456 (in 22h52m55s)

Proving Period Boundary: 2387
Proving Period Start:    2387 (in 15h27m30s)
Next Period Start:       5843 (in 39h27m30s)

panic: runtime error: integer divide by zero

goroutine 1 [running]:
main.glob..func6(0xc000502bd0, 0x0, 0x0)
        /mnt/lotus/marco/cmd/lotus-storage-miner/proving.go:114 +0x17a6
gopkg.in/urfave/cli%2ev2.(*Command).Run(0x352bd20, 0xc000502b40, 0x0, 0x0)
        /home/fil/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:167 +0x6f8
gopkg.in/urfave/cli%2ev2.(*App).RunAsSubcommand(0xc0003d3500, 0xc0004804b0, 0x0, 0x0)
        /home/fil/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/app.go:381 +0x99a
gopkg.in/urfave/cli%2ev2.(*Command).startApp(0x352bf60, 0xc0004804b0, 0x520235, 0xc0003dbd40)
        /home/fil/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:248 +0x646
gopkg.in/urfave/cli%2ev2.(*Command).Run(0x352bf60, 0xc0004804b0, 0x0, 0x0)
        /home/fil/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:85 +0xd19
gopkg.in/urfave/cli%2ev2.(*App).Run(0xc0005d2000, 0xc00003c0a0, 0x5, 0x5, 0x0, 0x0)
        /home/fil/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/app.go:261 +0x6e3
main.main()
        /mnt/lotus/marco/cmd/lotus-storage-miner/main.go:81 +0x621

**Comment by magik6k** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/1656/files#diff-b525e7cdef96d881a6ba50081cdbb0edR101-R119
