### ISSUE TITLE
Chain Events Called API never calls if confidence trigger falls on null tipset (causes storagemarket to miss deal activation)

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#1691]
**Describe the bug**

The chain events API has a Called function which takes:
- a match function which looks at messages on new tipsets, to look for a specific event to happen
- a called function that gets called if the tipset containing the matching message does not get reverted after a certain confidence level

However, if a match occurs at height H, with confidence C, if the tipset at height H+1+C is null (+1 for the message being applied), the called function is never called. This means to the user of the events Called API, it appears there are no matching messages that pass the confidence level.

**To Reproduce**
I created a test in the https://github.com/filecoin-project/lotus/tree/bugs/events-called-null-tipset branch to demonstrate the issue.

**Additional context**
Currently the only consumer of the Called API are the markets adapters, but this means the state for deals never leaves StorageDealSealing any time this happens.

**Comment by magik6k** [comment]
This is now fixed
