### ISSUE TITLE
StandaloneSealCommit error: Missing store file (or associated split paths)

### ISSUE THREAD

**Issue by liuchengxu** [filecoin-project/lotus#1698]
**Describe the bug**

Couldn't manage to make a storage deal after running `lotus client deal` command in the local dev net. Partial error logs:

```
2020-05-08T23:01:16.004+0800	WARN	ffiwrapper	ffiwrapper/sealer_cgo.go:274	StandaloneSealCommit error: Missing store file (or associated split paths): /Users/xuliucheng/.genesis-sectors/cache/s-t01000-3/sc-02-data-layer-1.dat
2020-05-08T23:01:27.999+0800	WARN	nat	go-libp2p-nat@v0.0.6/nat.go:186	failed to establish port mapping: goupnp: SOAP request got HTTP 500 Internal Server Error
2020-05-08T23:01:29.021+0800	WARN	sectors	storage-fsm@v0.0.0-20200427182014-01487d5ad3c8/fsm.go:308	sector 4 got error event sealing.SectorSealPreCommitFailed: seal pre commit(1) failed: presealing sector 4 (/Users/xuliucheng/.genesis-sectors/unsealed/s-t01000-4): pieces and comm_d do not match
```

**To Reproduce**

Using interopnet branch 8bea0e02:

First, follow the instructions from https://github.com/filecoin-project/lotus/blob/testnet/3/documentation/en/local-dev-net.md to run lotus and storage miner program.

Then start the deal process:

```bash
~/.../filecoin-project/lotus ❯❯❯ ./lotus wallet list
t3qsxrpy6in7qkadukcant7utooxpn4dl5l5ka37dcuzqwxeltov3ga3y2yll4kt6y3b2fpzzy3qigt2nrvjja
~/.../filecoin-project/lotus ❯❯❯ ./lotus wallet set-default t3qsxrpy6in7qkadukcant7utooxpn4dl5l5ka37dcuzqwxeltov3ga3y2yll4kt6y3b2fpzzy3qigt2nrvjja
~/.../filecoin-project/lotus ❯❯❯ ./lotus client import README.md
bafkreiapd5hxa56g4fjwir3ta5barbq2edcbu42el5uzqg54qlbtf4fwkq
~/.../filecoin-project/lotus ❯❯❯ ./lotus client local
bafkreiapd5hxa56g4fjwir3ta5barbq2edcbu42el5uzqg54qlbtf4fwkq src/github.com/filecoin-project/lotus/README.md 888 ok
~/.../filecoin-project/lotus ❯❯❯ ./lotus client query-ask t01000
Ask: t01000
Price per GiB: 0.0000000005
Max Piece size: 2048
~/.../filecoin-project/lotus ❯❯❯ ./lotus client deal bafkreiapd5hxa56g4fjwir3ta5barbq2edcbu42el5uzqg54qlbtf4fwkq t01000 0.0000000005 100
```

Now I can't reproduce this actually, but I did fail to make the deal for serveral times before, using the same steps described above. I'll update this thread if I see it again.

**Expected behavior**

The deal is able to be `StorageDealActive` finally.

**Screenshots**

![image](https://user-images.githubusercontent.com/8850248/81459934-c3a9c980-91d4-11ea-9a06-86508ec4efef.png)

**Version (run `lotus --version`):**

lotus version 0.3.0'+git8bea0e02'

**Additional context**

After I clear all the old data, `~/.lotus`, `~/.lotusstorage` and `~/.genesis-sectors`, and repeat the steps above, I finally succeed to make a deal. For the previous failed experinces, I didn't remove `~/.genesis-sectors`, not sure if it's related. [Related slack thread](https://app.slack.com/client/TEHTVS1L6/CPFTWMY7N/thread/CPFTWMY7N-1588949879.434600)

**Comment by magik6k** [comment]
I'm pretty sure that this got fixed few months ago, please reopen if you can still reproduce this
