### ISSUE TITLE
Why does my wallet FIL decrease?

### ISSUE THREAD

**Issue by 810106148** [filecoin-project/lotus#1700]
iose@iosels:~$ lotus wallet balance
2020／5／10
1.349999999876104447
2020／5／11  9：45
1.349999999874917254
2020／5／11 10:26
1.349999999874893765
2020／5／11 11:04
1.349999999874845677
2020／5／11 15:34
1.349999999874604553

iose@iosels:~$ lotus-storage-miner info
Miner: t045127
Sector Size: 32 GiB
Power: 832 GiB / 3.5 PiB (0.0226%)
	Committed: 832 GiB
	Proving: 832 GiB
Worker use:
	Local: 0 / 1 (+1 reserved)
	Remote: 0 / 0
Queues:
	AddPiece: 0
	PreCommit: 2
	Commit: 0
	Unseal: 0
PoSt Submissions:
	Previous: Epoch 227149 (32 block(s), ~24m 0s ago)
	Fallback: Epoch 227179 (in -2 blocks, ~-1m -30s)
	Deadline: Epoch 227349 (in 168 blocks, ~126m 0s)
Sectors:  map[CommitFailed:2 Proving:26 Total:30 Unsealed:2]
iose@iosels:~$ lotus-storage-miner sectors list
1: Proving       sSet: YES pSet: YES tktH: 194659 seedH: 195042 deals: [1199935]
2: Proving       sSet: YES pSet: YES tktH: 195919 seedH: 196323 deals: [1200227]
3: Proving       sSet: YES pSet: YES tktH: 196796 seedH: 197162 deals: [1200418]
4: Proving       sSet: YES pSet: YES tktH: 197926 seedH: 198266 deals: [1200659]
5: Proving       sSet: YES pSet: YES tktH: 198714 seedH: 199107 deals: [1200824]
6: Proving       sSet: YES pSet: YES tktH: 199663 seedH: 200082 deals: [1200985]
7: Proving       sSet: YES pSet: YES tktH: 200422 seedH: 200786 deals: [1201215]
8: Proving       sSet: YES pSet: YES tktH: 201079 seedH: 201462 deals: [1201368]
9: Proving       sSet: YES pSet: YES tktH: 201770 seedH: 202184 deals: [1201490]
10: Proving      sSet: YES pSet: YES tktH: 202491 seedH: 202865 deals: [1201701]
11: Proving      sSet: YES pSet: YES tktH: 203147 seedH: 203536 deals: [1201844]
12: Proving      sSet: YES pSet: YES tktH: 203836 seedH: 204244 deals: [1202032]
13: Proving      sSet: YES pSet: YES tktH: 204794 seedH: 205177 deals: [1202234]
14: Proving      sSet: YES pSet: YES tktH: 205484 seedH: 205871 deals: [1202472]
15: Proving      sSet: YES pSet: YES tktH: 206177 seedH: 206591 deals: [1202654]
16: Proving      sSet: YES pSet: YES tktH: 206867 seedH: 207256 deals: [1202850]
17: CommitFailed sSet: NO  pSet: NO  tktH: 209543 seedH: 209916 deals: [1203489]
18: Proving      sSet: YES pSet: YES tktH: 213961 seedH: 214460 deals: [1204585]
19: Proving      sSet: YES pSet: YES tktH: 216123 seedH: 217006 deals: [1204707]
20: Proving      sSet: YES pSet: YES tktH: 215130 seedH: 215597 deals: [1204862]
21: CommitFailed sSet: NO  pSet: NO  tktH: 216754 seedH: 0      deals: [1205125]
22: Proving      sSet: YES pSet: YES tktH: 217278 seedH: 217800 deals: [1205320]
24: Proving      sSet: YES pSet: YES tktH: 219836 seedH: 220462 deals: [1205802]
25: Proving      sSet: YES pSet: YES tktH: 220313 seedH: 220943 deals: [1205883]
26: Proving      sSet: YES pSet: YES tktH: 221906 seedH: 222335 deals: [1206332]
27: Proving      sSet: YES pSet: YES tktH: 222783 seedH: 223258 deals: [1206490]
28: Proving      sSet: YES pSet: YES tktH: 223987 seedH: 224869 deals: [1206782]
29: Proving      sSet: YES pSet: YES tktH: 223925 seedH: 224634 deals: [1206783]
30: Unsealed     sSet: NO  pSet: NO  tktH: 0      seedH: 0      deals: [1207020]
31: Unsealed     sSet: NO  pSet: NO  tktH: 0      seedH: 0      deals: [1207034]

**Comment by whyrusleeping** [comment]
because your miner has to pay collateral and message fees
