### ISSUE TITLE
"error": "failed to marshal cbor object encoded bitfield was too large (8195) (RetCode=21):

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#1704]
**Describe the bug**
I get this error when commiting ProveCommitSector.

**To Reproduce**
1. Run lotus run and miner run ----nosync=true, and then start lotus-seal-worker
2. lotus sync status , cannot synchronize to the latest block
3 kill lotus process
4 copy the datastore form other node
5 lotus run
6 lotus mpool stat, fond my wallet 's address with future: XX
7 ./lotus-shed noncefix --repo="/mnt/lotus/.lotus" --addr XXXXX --auto
8 lotus-storage-miner run
9 get this error

**Expected behavior**
May be It's associated with copy datastore. we wait messge use this function, err = m.events.ChainAt(func(ectx context.Context, tok TipSetToken, curH abi.ChainEpoch) error {
Maybe get Huge message because of chain growth is not continuous? 
But why  guess sector IDs are too spaced out lead this Error.

**Screenshots**
github.com/filecoin-project/lotus/chain/vm.(*Runtime).Put\n        /mnt/lotus/interopnet/chain/vm/runtime.go:127"}
2020-05-11T14:33:39.179+0800    WARN    vm      vm/vm.go:364    Send actor error        {"from": "t3wx2j4cifywb6btiqe2eduqesnfjgsqpw7y6xgpby6aecr674vn73sdlms533d4fvdgifv4wvgh5kgikrnhja", "to": "t010230", "nonce": 143466, "method": "7", "height": "14118", "error": "failed to marshal cbor object encoded bitfield was too large (8195) (RetCode=21):\n    github.com/filecoin-project/lotus/chain/vm.(*Runtime).Put\n        /mnt/lotus/interopnet/chain/vm/runtime.go:127

**Version (run `lotus --version`):**
lotus -v
lotus version 0.3.0'+git6827e3da'

**Additional context**
I change the sector id start index, It begin with 300000

**Comment by magik6k** [comment]
https://github.com/filecoin-project/lotus/issues/1624#issuecomment-718068022
