### ISSUE TITLE
about lotus-storage-miner pledge-sector

### ISSUE THREAD

**Issue by ryan-kim21** [filecoin-project/lotus#1718]
**Describe the bug**

Dear Team,

I have a several questions. 
First, about the lotus-storage-miner pledge-sector.

When I use lotus miner,
How many push this  lotus-storage-miner pledge-sector? 
I input the 22 times. 
then... Just 32G per 1 committing 
I still have a My hard Disk 167T capacity! 
So... If I want to use Full Harddisk, It need to input  520 times? (lotus-storage-miner pledge-sector)

???? 
It doesn't work automatically...?

Seconds,
When can I get the Coin.,..? 
I waited for 2days. But My wallet balance has been 0.005. 
How long do I have to wait?

I look forward to your valuable reply.
Thanks,
Ryan.

**To Reproduce**
1. Run '...'
2. See error

![image](https://user-images.githubusercontent.com/63631441/81763495-5c5c8400-950a-11ea-859c-d164bfa0537e.png)

![image](https://user-images.githubusercontent.com/63631441/81763531-6da59080-950a-11ea-89b9-38c2a327d855.png)

![image](https://user-images.githubusercontent.com/63631441/81764159-dfcaa500-950b-11ea-9647-ee7b870265e4.png)

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**

**Additional context**

**Comment by whyrusleeping** [comment]
You need to seal enough data to get above the minimum miner size, which is 1TB.
