### ISSUE TITLE
failed to connect to bootstrap peer: dial backoff

### ISSUE THREAD

**Issue by thiruholon** [filecoin-project/lotus#1725]
Suddenly storage miner stopped with run and unable to get it back running. Getting this below error in daemon 

> peermgr peermgr/peermgr.go:159  failed to connect to bootstrap peer: dial backoff

1. Run 'lotus daemon'
2. See error

and run 'lotus sync status'

**Screenshots**
![image](https://user-images.githubusercontent.com/64831492/81849650-68d3f180-9589-11ea-9251-673f40bd04ec.png)

![image](https://user-images.githubusercontent.com/64831492/81849492-2b6f6400-9589-11ea-9852-db269c5435f6.png)

**Comment by whyrusleeping** [comment]
sounds like a temporary failure of the bootstrap nodes or your internet connection. Please open a new issue if this happends again
