### ISSUE TITLE
 lotus-seal-worker run

### ISSUE THREAD

**Issue by chengwds** [filecoin-project/lotus#1760]
2020-05-16T09:39:34.525+0800	INFO	main	lotus-seal-worker/main.go:41	Starting lotus worker
2020-05-16T09:39:34.526+0800	WARN	main	lotus-seal-worker/main.go:75	--address flag is required:
    main.glob..func1
        /root/lotus/cmd/lotus-seal-worker/main.go:114

**Comment by chengwds** [comment]
The official source code cannot be used normally. It needs customization

**Comment by wxy0313** [comment]
大哥你联系方式是多少啊 能不能加个Q

**Comment by chengwds** [comment]
qq 372693586

**Comment by wxy0313** [comment]
已申请添加您QQ为好友&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chengwds"<notifications@github.com&gt;; 
发送时间: 2020年5月17日(星期天) 下午3:41
收件人: "filecoin-project/lotus"<lotus@noreply.github.com&gt;; 
抄送: "1811708666"<1811708666@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [filecoin-project/lotus]  lotus-seal-worker run (#1760)





 qq 372693586

**Comment by ryan-kim21** [comment]
I have same issue again again. Did you resolve it?

**Comment by bos162** [comment]
Same issue here. Anybody resolved it?

**Comment by hillbun** [comment]
how  to solve it , I meet this issue too.

**Comment by magik6k** [comment]
This flag is now guessed automatically
