### ISSUE TITLE
Implement storage market price discovery mechanism

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#177]
This has yet to be specced, but since asks are no longer on chain, we need a way to discover price info.

Since getting this specced is going to likely take a long time, we can implement this roughly as follows:

1. Define an 'ask' object that is signed by a miner, and includes price info, sector size, minimum piece size, the miner address, timestamp, sequence number, and a signature (pretty much an ipns record)
2. Implement a storage miner protocol that allows clients to ask a miner for their ask (ensure the request contains the miner address, for libp2p peers that may host multiple storage miners, or for aggregators). This gets them the signed ask object from that miner
3. Have miners gossip out their signed asks periodically. Listeners on this topic should validate the asks (make sure they come from valid miners) and cache them locally.
4. (optionally, with a flag) Allow responding to ask queries with signed asks for other miners, effectively an ask aggregator.

**Comment by magik6k** [comment]
We have a query protocol now
