### ISSUE TITLE
Changing filecoin-proof-parameters location

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#1773]
I'm trying to initially run a miner, and this requires me to run the `lotus-storage-miner init`.

Its stated that I have to point the `TMPDIR` somewhere else because it needs a lot of diskspace.

Running the command itself doesn work, because the SSD the OS is on (and the `TMPDIR` is set to) is very small.

I tried running `export TMPDIR=/mnt/raid && lotus-storage-miner init` but it still ends up in `/var/tmp`.

How can I change the location? Is theresome kind of config variable somewhere?

EDIT: Forgot to mention, this isnt high priority as its easily fixable by making a symlink in the temp directory, but would be nice to have this configurable.

**Comment by magik6k** [comment]
The env var is `FIL_PROOFS_PARAMETER_CACHE`, we probably should document it better

**Comment by RobQuistNL** [comment]
Thanks for the quick reply @magik6k!

Is this the same parameter for `lotus-storage-miner sectors pledge` or is that something else? The docs once again state `TMPDIR` but even with symlinking some directories to a different storage I get this message; `stores  stores/index.go:325     not allocating on [UUID], out of space (available: 28552867840, need: 34359738368)
`

I suppose there is some configuration somewhere to tell it where to make the stores? I'm having a hard time setting up the project on a freshly installed server. Would be happy to submit a PR to the docs once I get it fixed :)
