### ISSUE TITLE
miner stay precommit1 for a long time

### ISSUE THREAD

**Issue by simon4545** [filecoin-project/lotus#1775]
AMD EPYC 7401*2
512G DDR4
1T NVMe
seal only one sector.
It has take about 14 hours or more

lotus-storage-miner sectors status --log 1
SectorID:       1
Status: PreCommit1
CommD:          <nil>
CommR:          <nil>
Ticket:
TicketH:                0
Seed:
SeedH:          0
Proof:
Deals:          [0]
Retries:                0
--------
Event Log:
0.      2020-05-17 13:24:24 +0800 CST:  [event;sealing.SectorStart]     {"User":{"ID":1,"SectorType":1,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"bafk4chzaa57f7xrvyufjga5fkae6gsmkj27n7444ik3rbnzq3dwhvr5puy7a"}},"DealInfo":null}]}}
1.      2020-05-17 13:24:24 +0800 CST:  [event;sealing.SectorPacked]    {"User":{"FillerPieces":null}}

**Comment by simon4545** [comment]
In this period of time, CPU usage is low, only one core occupies 100%
lotus-storage-miner use about 120G memory

**Comment by sun-wenming** [comment]
same problem

**Comment by keeperlink** [comment]
same issue. Sealing running for more than 24 hours, I see new layer file added in /root/.lotusstorage/cache/ roughly every 4 hours. CPU at 5%. Is there any way to run layering faster?

**Comment by skysbird** [comment]
same issue

**Comment by magik6k** [comment]
This can be caused by many factors:
* Intel CPU
* Sealing on a HDD instead of SSD
* Building on a different machine (some compile time optimizations can be missing)

If non of the above applies, try building lotus with
```
FFI_BUILD_FROM_SOURCE=1 RUSTFLAGS='-C target-cpu=native' make clean deps all
```
(requires rustup and some other proof dependencies to be installed)

**Comment by anorth** [comment]
The problem for me was that proofs were not built from source.

**Comment by kernelogic** [comment]
How long is "normal"? 4 hours? 8 hours? 12 hours? 24 hours?
