### ISSUE TITLE
Error: mining block failed

### ISSUE THREAD

**Issue by hsienfu** [filecoin-project/lotus#1776]
Lotus-storage-miner hang Precommit1 on for 10 hours,  then report:

2020-05-18T00:56:11.072+0800    ERROR   miner   miner/miner.go:162  mining block failed: failed to get mining base info:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /usr/local/services/lotus/miner/miner.go:258
  - beacon entry request returned error: drand peer "linus.drand.fil-test.net:443" failed publicRand
request: rpc error: code = Unavailable desc = transport is closing

**Comment by simon4545** [comment]
have u finished precommit1?

**Comment by hsienfu** [comment]
> have u finished precommit1?

Still running, CPU used 100% and the ./lotusstorage/cache size is incremental
Elapsed 1187 minutes

**Comment by sun-wenming** [comment]
do you have resolve this?  i have been three day but don't finished precommit1.
  
![image](https://user-images.githubusercontent.com/22268505/82516098-876b5700-9b4c-11ea-9d2e-984f31a7a875.png)
