### ISSUE TITLE
SectorComputeProofFailed failure every one minute

### ISSUE THREAD

**Issue by mxz9102** [filecoin-project/lotus#1796]
**Describe the problem**

SectorComputeProofFailed happened when a remote worker is used to seal a sector. Pre-commit 1 and precommit-2 were completed successfully but then sealing.SectorComputeProofFailed.
Set up:
1 miner //Precommit 1 and 2, commit 2 are all disabled.
1 worker //All above actions are enabled.
Sectors pledge command was used to generate a sector and then the worker started to seal it. After Pre-commit 1/2 were done, sealing.SectorComputeProofFailed started to appear.

**Sectors list**

0: Proving             sSet: YES pSet: YES tktH: -441  seedH: 1058  deals: [0]
1: FailedUnrecoverable sSet: NO  pSet: NO  tktH: 3356  seedH: 1659  deals: [0]
2: Proving             sSet: YES pSet: YES tktH: 3353  seedH: 4800  deals: [1443 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
3: Proving             sSet: YES pSet: YES tktH: 2052  seedH: 3944  deals: [1448 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
4: FailedUnrecoverable sSet: NO  pSet: NO  tktH: 4857  seedH: 0     deals: [0]
5: Proving             sSet: YES pSet: YES tktH: 6103  seedH: 7295  deals: [0]
6: Proving             sSet: YES pSet: YES tktH: 6794  seedH: 8058  deals: [0]
7: Proving             sSet: YES pSet: YES tktH: 8178  seedH: 10184 deals: [0]
8: Proving             sSet: YES pSet: YES tktH: 8178  seedH: 10504 deals: [0]
10: Proving            sSet: YES pSet: YES tktH: 14540 seedH: 15787 deals: [0]
11: ComputeProofFailed sSet: NO  pSet: NO  tktH: 16829 seedH: 18149 deals: [0]

**Sectors status**
[11.log](https://github.com/filecoin-project/lotus/files/4655057/11.log)

**Lotus storage miner logs**

![image](https://user-images.githubusercontent.com/15658707/82414602-26e4f880-9a2c-11ea-9574-b20fc8732ac8.png)

**Version**

The output of `./lotus --version`.

lotus version 0.3.0'+git1ac6f3fa'

**Comment by kangqian623** [comment]
have you make it?

**Comment by mxz9102** [comment]
No. Using miner to do P2 can resolve this problem for now.

**Comment by magik6k** [comment]
Fixed in #1924
