### ISSUE TITLE
run "lotus daemon" error

### ISSUE THREAD

**Issue by zh19910202** [filecoin-project/lotus#1799]
when I run "lotus daemon", there is some error message like that:
2020-05-20T17:00:26.389+0800	WARN	main	lotus/main.go:83	initializing node:
    main.glob..func1
        /data1/lotus_phase2/cmd/lotus/daemon.go:199
  - starting node:
    github.com/filecoin-project/lotus/node.New
        /data1/lotus_phase2/node/builder.go:489
  - could not build arguments for function "github.com/filecoin-project/lotus/node/modules".RunHello (/data1/lotus_phase2/node/modules/services.go:31): failed to build *hello.Service: could not build arguments for function "reflect".makeFuncStub (/home/sr/go/src/reflect/asm_amd64.s:12): failed to build *chain.Syncer: could not build arguments for function "reflect".makeFuncStub (/home/sr/go/src/reflect/asm_amd64.s:12): failed to build beacon.RandomBeacon: function "reflect".makeFuncStub (/home/sr/go/src/reflect/asm_amd64.s:12) returned a non-nil error: failed to get group response from beacon peer: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing reading server HTTP response: unexpected EOF"

what should I do ??

**Comment by bronze1man** [comment]
I got similar result when build from next branch

**Comment by magik6k** [comment]
This should be fixed in master as we now use https endpoints
