### ISSUE TITLE
Compute state seems to disagree with one of the dashboards

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#1801]
This was reported by a community member. It could be

- compute state being used incorrectly (compute state confuses my small brain)
- something wrong with dashboard
- something fishy somewhere in compute state or the reward actor?

![image](https://user-images.githubusercontent.com/6530144/82472413-1ec1a300-9a96-11ea-898c-8e83f13fa571.png)
![image](https://user-images.githubusercontent.com/6530144/82472422-21bc9380-9a96-11ea-9894-083e57f6cefa.png)

**Comment by jennijuju** [comment]
Im pretty sure we had this convo with filfox and they fixed it  - either way not a lotus issue
