### ISSUE TITLE
Stream Error and sealworker Error

### ISSUE THREAD

**Issue by ryan-kim21** [filecoin-project/lotus#1809]
**Describe the bug**

I tried to run the storage miner. 
I got the this message and I can't get a coin. 
ㅡㅡ
and I can't open the  run sealworker. 

Could you help me plz...!! 

Thanks,

**To Reproduce**
1. Run '...'
2. See error
![image](https://user-images.githubusercontent.com/63631441/82526866-00c87100-9b70-11ea-9276-328b00a3a926.png)

![image](https://user-images.githubusercontent.com/63631441/82526998-500ea180-9b70-11ea-9137-888aad49d775.png)

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**

**Additional context**

**Comment by magik6k** [comment]
If you're still having issues with this, try following https://docs.filecoin.io/mine/lotus/seal-workers/#miner-and-worker-co-location
