### ISSUE TITLE
Suggestion: allow miners to set ActivationEpoch in ProveCommitSector

### ISSUE THREAD

**Issue by shannon-6block** [filecoin-project/lotus#1810]
# Background

When the PoRep proof of a sector is generated, the sector data is typically located at an SSD. After the proof is accepted by the blockchain, the miner has to move it to another storage device, like a hard disk, RAID, distributed filesystem. This process may take several minutes.

If the sector is activated immediately, it has a possibility to be demanded to generate Winning and Window PoSt proofs immediately. This is really easy to fail for generating proofs while the data is moving.

# Suggestion
In `ProveCommitSectorParams` [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/miner_actor.go#L503), add a parameter `delay`, and add the `delay` to `ActivationEpoch ` [here](https://github.com/filecoin-project/specs-actors/blob/0df536f7e461599c818231aa0effcdaccbb74900/actors/builtin/miner/miner_actor.go#L503)

**Comment by shannon-6block** [comment]
Believe it or not, my miner account t027999 has 14 TiB Faulty sectors because of this reason...

**Comment by magik6k** [comment]
This shouldn't ever happen because we're moving sectors into storage that can be reached by PoSt calls in commit1, before committing the sector on chain.

Did you modify this line - https://github.com/filecoin-project/sector-storage/blob/master/manager.go#L258, or any other code in sector-storage?

**Comment by shannon-6block** [comment]
Yes...
Using storage-miner to do Commit 1 is not that efficient. You have to transfer a big bunch of data from worker to miner...

**Comment by magik6k** [comment]
I believe this is fixed now (at least workers can run Commit1)
