### ISSUE TITLE
some miner not windowPost msg and not be punished

### ISSUE THREAD

**Issue by bary321** [filecoin-project/lotus#1812]
we can't corrent the windowPost and surprised to found some miner. t01102 and t01020 has not windowPost msg in chain for last two days and they have not been punished.
It's seem some problam in windowPost.

**Comment by magik6k** [comment]
The two miners not doing window post issue is tracked in https://github.com/filecoin-project/specs-actors/issues/391.

Any most post issues in the current testnet are now fixed in `next`. Please open a new issue if you'll still see PoSt issues after testnet reset
