### ISSUE TITLE
Sealing failed with sealing.SectorSealPreCommitFailed error.

### ISSUE THREAD

**Issue by bos162** [filecoin-project/lotus#1814]
Hi guys,
I ran the `lotus-storage-miner run` command. After waiting for a couple of hours, I tried to store a file on the miner using the `lotus client deal` command. I got a transaction id but I think the sealing failed.

By running `lotus-storage-miner info`, I got
![image](https://user-images.githubusercontent.com/12178960/82590798-2a26d400-9b53-11ea-8475-4575081cac5b.png)

Then I checked the sector log, and I saw the following:
![image](https://user-images.githubusercontent.com/12178960/82591033-8a1d7a80-9b53-11ea-8c92-a64260aa0e7c.png)

Below is the miner log:
![image](https://user-images.githubusercontent.com/12178960/82591855-d0270e00-9b54-11ea-8d84-a8084ff021a6.png)

I don't know what was out of space, because I had 8T hard drives and the file I tried to store is quite tiny.

My lotus version is 0.3.0'+gitcea7c410'

Please help.

**Comment by ryan-kim21** [comment]
What did you input? lotus-seal-miner run --address something?? I have a same error.

**Comment by bos162** [comment]
> What did you input? lotus-seal-miner run --address something?? I have a same error.
> Try to restart miner.
> 
> then I can't run next step. Just Precommit1 for 12hours.
> and then stream error.

Hi Ryan, I did not do anything special, and I did not even start a seal worker.  I thought seal workers are just for efficiency improvements.  Below is what I did:
Step 1: I ran lotus daemon, and I waited until syncing is done.
Step 2: I registered a new wallet and new miner in the faucet website.
Step 3: I ran `lotus-storage-miner init --actor=ACTOR_VALUE_RECEIVED --owner=OWNER_VALUE_RECEIVED` to initialize the miner.
Step 4: I ran `lotus-storage-miner run` to start the miner. 
Step 5: I ran `lotus-storage-miner sectors pledge` to start sealing sectors.
Step 6: After waiting for around 6 hours, I did not see any error, but I also did not see any byte power showing up, always ZERO. Then I tried to store some file manually. After waiting for another 10 minutes, I started seeing errors in the log.

That is all I have done. Anybody experienced can help? Thanks a lot.

**Comment by george012** [comment]
This problem has been troubled from the beginning of the test to the present, has not been solved

**Comment by ryan-kim21** [comment]
Everyone can't get FileCoin now? Have you been had still a problem? I have been stopped from Monday.

**Comment by magik6k** [comment]
How much free space do you have on your drive? You need ~400G free to seal a sector (for some temporary cache files)
