### ISSUE TITLE
lotus-storage-miner state power No help topic for 'state'

### ISSUE THREAD

**Issue by iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii** [filecoin-project/lotus#1818]
how to solve this problem?
I cant use this commend:lotus-storage-miner state power
It returns: No help topic for 'state'

**Comment by arajasek** [comment]
Use `lotus-storage-miner info` for now, this is being tracked here: https://github.com/filecoin-project/lotus/issues/1518#issuecomment-632383931
