### ISSUE TITLE
Sealing sectors takes forever.

### ISSUE THREAD

**Issue by bos162** [filecoin-project/lotus#1823]
Hi guys,

    I started the "**lotus-storage-miner run**" process yesterday. I waited for a whole day and I just checked the current status. By runing "**lotus-storage-miner info**", I got 
![image](https://user-images.githubusercontent.com/12178960/82735789-2ae97280-9cd9-11ea-8b4b-5b60513d1386.png)

By viewing the miner log, I got 
![image](https://user-images.githubusercontent.com/12178960/82735795-3ccb1580-9cd9-11ea-90b3-659eb3ec4e85.png)

It seems there is no apparent errors, but the whole sealing process seems to be toooo slow. 

Anybody can help? By the way, I have a 8T hard drive mounted.

Current version is 0.3.0 gitffd34008.

**Comment by magik6k** [comment]
Can you share some information about your hardware:
* CPU model
* Memory size
* Are you sealing on a hard drive, or on a SSD/NVMe?

**Comment by magik6k** [comment]
See https://github.com/filecoin-project/lotus/issues/1775#issuecomment-652350742
