### ISSUE TITLE
SectorSealPreCommitFailed

### ISSUE THREAD

**Issue by george012** [filecoin-project/lotus#1826]
event;sealing.SectorSealPreCommitFailed

ticket expired: ticket expired: seal height: xxxx, head: xxxx

··························································································
This error has been circulating, unable to submit sectors!!!

**Comment by mslovy** [comment]
same for me, any one can explain why?

**Comment by george012** [comment]
I don’t know where to troubleshoot

**Comment by george012** [comment]
> 对我一样，任何人都可以解释为什么？

您有哪些排除的方案？

**Comment by george012** [comment]
> same for me, any one can explain why?

What is your solution to this problem?

**Comment by mslovy** [comment]
make sealing fast

**Comment by magik6k** [comment]
This generally means that the sealing process took too long
