### ISSUE TITLE
Lotus stop command

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/lotus#1827]
Something like `lotus daemon stop` or `lotus stop` that checks if the daemon is running and sends it a stop signal, instead of depending on the command running in the foreground and killing it manually with a CTRL-C. This can also be done through `bash` commands but we should inlcude and standardize it in the node API as another RPC command..

**Comment by laser** [comment]
This was resolved in #1899. I suggest closing this issue.

**Comment by schomatis** [comment]
I'm assuming the "fixes" tag will take care of closing, thanks for the PR!
