### ISSUE TITLE
LOG Compact FAILED with error: too many open files

### ISSUE THREAD

**Issue by shao-shuai** [filecoin-project/lotus#1830]
**Describe the bug**
I was syncing the chain this morning with `lotus sync wait`, somehow it stuck at block 8994. Then I stopped the process and the daemon. After restarting daemon, the log message keeps reporting `LOG Compact FAILED with error: too many open files`. I couldn't run `lotus sync wait` since then, the error message is `2020-05-24T16:54:47.826-0700	WARN	main	lotus/main.go:81	dial tcp 127.0.0.1:1234: connect: connection refused`.

![image](https://user-images.githubusercontent.com/28980017/82767944-5905aa00-9de0-11ea-904b-a44730bfbcf9.png)

**To Reproduce**
1. Run 'lotus daemon'
2. See error

**Expected behavior**
Synchronized to the chain.

**Screenshots**

**Version (run `lotus --version`):**
`lotus version 0.3.0'+git92d58ab'`

**Additional context**

**Comment by magik6k** [comment]
Until we switch away from badger, the only way to 'fix' this is to increase file limits (`ulimit -n`, to something like 1000000)
