### ISSUE TITLE
GenerateWindowPoSt should subtract the faults sectors

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#1834]
Describe the bug
In runPost() of storage/wdpost_run.go:
	// TODO: Faults!
	postOut, err := s.prover.GenerateWindowPoSt(ctx, abi.ActorID(mid), ssi, abi.PoStRandomness(rand))
	if err != nil {
		return nil, xerrors.Errorf("running post failed: %w", err)
	}
ssi args should should subtract the faults sectors
see the spec miner-actor.go Line#659 
// Loads info for a set of sectors to be proven.
// If any of the sectors are declared faulty and not to be recovered, info for the first non-faulty sector is substituted instead.
// If any of the sectors are declared recovered, they are returned from this method.
func (st *State) LoadSectorInfosForProof(store adt.Store, provenSectors *abi.BitField) (sectorInfos []*SectorOnChainInfo, recoveries *bitfield.BitField, err error) {

To Reproduce
With one sector is faulted, it's easy to be reproduced. We can see many miners can't submit Window PoSt correctly.

Expected behavior
Window PoSt can be submitted without problems if all sector information is right.

Additional context
There are several issues for Window PoSt. This is one of such issues.

**Comment by magik6k** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/1838
