### ISSUE TITLE
Is this TestNet Project screwed up?!?!?!?!?!?!?!?!?!?!?!

### ISSUE THREAD

**Issue by ryan-kim21** [filecoin-project/lotus#1839]
**Describe the bug**

****

I stopped the miner server. 
It can't not resolve and No notice!
They don't respond.

I don't know what they're doing.

**Comment by arajasek** [comment]
Hey! Thanks for the issue! :)

Can you please provide:
```
A clear and concise description of what the bug is.
```

**Comment by ryan-kim21** [comment]
> Hey! Thanks for the issue! :)
> 
> Can you please provide:
> 
> ```
> A clear and concise description of what the bug is.
> ```

Hey! Thanks for the answer.

Then You Know This issue? 
2020-05-28T17:58:22.205+0900	ERROR	hello	hello/hello.go:107	failed to fetch tipset from peer during hello: blocksync req failed:
    github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).sendRequestToPeer
        /home/lts1004/lotus/chain/blocksync/blocksync_client.go:262
  - i/o deadline reached



I will wait your answer.

Thanks,

**Comment by arajasek** [comment]
Looks like network issues, unfortunately, which we can't really help with. I don't think the network was broken.
