### ISSUE TITLE
Lotus-storage-miner prints "not enough memory" debug info.

### ISSUE THREAD

**Issue by bos162** [filecoin-project/lotus#1844]
I ran my miner for a whole day but received nothing. I checked the miner log, finding one debug info saying: "sched: not scheduling on worker 0; not enough physical memory - need: 257661M, have 257637M". Could this be the reason making my miner get nothing? How could this happen since I have 256G ram. Please help. Thanks..

**Comment by arajasek** [comment]
yeah, that certainly would lead to your miner not sealing...what matters is how much memory was available at the moment, it looks like you just fell short

**Comment by littlekai999** [comment]
same issue, any one can help
