### ISSUE TITLE
Persistent audit log

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#186]
Basically a glorified logger with persistence for things that touch the chain / transactions in automated way.

Some notes:
* Should be stored outside of the main datastore (but probably still in repo)
* Easy cleanup / seeking
* Should be at least somewhat parse-able (+easy to filter)
  * `[LEVEL] subsystem: message string with info; type=tx; to=t01238; amount=9001`

**Comment by whyrusleeping** [comment]
This seems pretty easy to do, would love someone to pick it up. 

As for design, I think a simple rolling text file, in ndjson format, with a high level API inside lotus that looks something like:
```
journal.Logw("journal entry name", "field1, "value1", "field2", "value2")
```
