### ISSUE TITLE
Hooks for custom storage and retrieval logic

### ISSUE THREAD

**Issue by ianjdarrow** [filecoin-project/lotus#1874]
There are a bunch of reasons miners might want to inject custom logic into their consideration of storage and retrieval deals. For example:
- Giving better pricing to a nonprofit, represented as an allow-listed set of PeerIDs 
- Rejecting storage and retrieval requests for certain CIDs included on a list known to the miner

It's difficult to imagine all the possible permutations that users will want, so some sort of general-purpose hook for custom logic is desirable.

One way this could work (extremely non-prescriptive, just thoughts):
- Miners can optionally configure an endpoint for a service (local or remote) to serve as a `PreDealHook` to process storage and retrieval requests. An HTTP endpoint probably works well enough for starters.
- If a `PreDealHook` endpoint is specified, when the miner receives a storage or retrieval deal request, the `PreDealHook` receives the following information: `{ RequesterPeerID, CID, Price, Duration, [...others?] }` and returns one of `{NoOp, MustAccept, MustReject}`. 
- `MustAccept` and `MustReject` short-circuit the default deal logic; `NoOp` lets the request proceed through the normal flow.
- The `PreDealHook` endpoint itself can take the provided information and process it in arbitrary ways to arrive at the result – for example, checking against a database of allow-listed peers or a customer/price list, et cetera.

**Comment by ianjdarrow** [comment]
As we start adding things like verified client deal flags, et cetera, it might be nice to do it in a way that's compatible with this approach, so we don't have custom deal logic sprinkled in lots of different places.

**Comment by arajasek** [comment]
This is largely implemented in #2714
