### ISSUE TITLE
When a certain number of sectors are sealed in a window post period(one day), the window post is not load balanced

### ISSUE THREAD

**Issue by IPFSMain-Official** [filecoin-project/lotus#1881]
Describe the bug
Too many sectors are placed on the deadline 0:
./lotus-storage-miner proving deadlines
0: 11518 sectors
1: 2349 sectors
2: 0 sectors
3: 0 sectors
4: 0 sectors (current)
5: 0 sectors
6: 0 sectors
7: 0 sectors
8: 0 sectors
9: 0 sectors
10: 0 sectors
11: 0 sectors
12: 0 sectors
13: 0 sectors
14: 0 sectors
15: 0 sectors
16: 0 sectors
17: 0 sectors
18: 0 sectors
19: 0 sectors
20: 0 sectors
21: 0 sectors
22: 0 sectors
23: 0 sectors

To Reproduce
1、seal 2349 sectors per cycle （a window post period）
 or 
2、The total number of sectors sealed in several cycles is an integral multiple of 2349

Screenshots

Additional context

detail see the code
func AssignNewSectors(deadlines *Deadlines, partitionSize uint64, newSectors []uint64, seed abi.Randomness) error {
        nextNewSector := uint64(0)

        // Assigns up to `count` sectors to `deadline` and advances `nextNewSector`.
        assignToDeadline := func(count uint64, deadline uint64) error {
                countToAdd := min64(count, uint64(len(newSectors))-nextNewSector)
                sectorsToAdd := newSectors[nextNewSector : nextNewSector+countToAdd]
                err := deadlines.AddToDeadline(deadline, sectorsToAdd...)
                if err != nil {
                        return fmt.Errorf("failed to add %d sectors to deadline %d: %w", countToAdd, deadline, err)
                }
                nextNewSector += countToAdd
                return nil
        }
        // Iterate deadlines and fill any partial partitions. There's no great advantage to filling more- or less-
        // full ones first, so they're filled in sequence order.
        // Meanwhile, record the partition count at each deadline.
        deadlinePartitionCounts := make([]uint64, WPoStPeriodDeadlines)
        for i := uint64(0); i < WPoStPeriodDeadlines && nextNewSector < uint64(len(newSectors)); i++ {
                partitionCount, sectorCount, err := DeadlineCount(deadlines, partitionSize, i)
                if err != nil {
                        return fmt.Errorf("failed to count sectors in partition %d: %w", i, err)
                }
                deadlinePartitionCounts[i] = partitionCount

                gap := partitionSize - (sectorCount % partitionSize)
                if gap != partitionSize {
                        err = assignToDeadline(gap, i)
                        if err != nil {
                                return err
                        }
                }
        }

        // While there remain new sectors to assign, fill a new partition at each deadline in round-robin fashion.
        // TODO WPOST (follow-up): fill less-full deadlines first, randomize when equally full.
        targetDeadline := uint64(0)
        for nextNewSector < uint64(len(newSectors)) {
                err := assignToDeadline(partitionSize, targetDeadline)
                if err != nil {
                        return err
                }
                targetDeadline = (targetDeadline + 1) % WPoStPeriodDeadlines
        }
        return nil
}

When seal 2349 sectors per cycle,  assignToDeadline of the first  loop will not be called.And in the second for loop，the targetDeadline is slways  set to deadline 0.

The total number of sectors sealed in several cycles is an integral multiple of 2349, which also causes this problem. That's why I have 11518 sectors in dealine0

**Comment by anorth** [comment]
Thanks, this is https://github.com/filecoin-project/specs-actors/issues/402

**Comment by magik6k** [comment]
This is now done in interopnets
