### ISSUE TITLE
panic: runtime error: index out of range [24] with length 24

### ISSUE THREAD

**Issue by Dengminer** [filecoin-project/lotus#1883]
**Describe the bug**
After I failed to run window post the day before yesterday, I executed "lotus-storage-miner providing info" and got the error report in the screenshot.And miner didn't execute window post yesterday or today.My miner ID is t0234987.

**To Reproduce**
1. Run 'lotus-storage-miner proving info'

**Screenshots**
![image](https://user-images.githubusercontent.com/53812125/83408014-7a9c0c80-a444-11ea-901a-9a00d8bcbe01.png)
root@idc:~# lotus-storage-miner proving info
Current Deadline: &{CurrentEpoch:60712 PeriodStart:50245 Index:24 Open:53701 Close:53701 Challenge:53701 FaultCutoff:0}panic: runtime error: index out of range [24] with length 24

goroutine 1 [running]:
main.glob..func6(0xc000657380, 0x0, 0x0)
	/usr/local/lotus/cmd/lotus-storage-miner/proving.go:63 +0x1836
gopkg.in/urfave/cli%2ev2.(*Command).Run(0x4365740, 0xc0006572f0, 0x0, 0x0)
	/root/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:167 +0x6f8
gopkg.in/urfave/cli%2ev2.(*App).RunAsSubcommand(0xc000182600, 0xc000657230, 0x0, 0x0)
	/root/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/app.go:381 +0x99a
gopkg.in/urfave/cli%2ev2.(*Command).startApp(0x4365980, 0xc000657230, 0xc0006649c0, 0x1)
	/root/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:248 +0x646
gopkg.in/urfave/cli%2ev2.(*Command).Run(0x4365980, 0xc000657230, 0x0, 0x0)
	/root/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:85 +0xd19
gopkg.in/urfave/cli%2ev2.(*App).Run(0xc000001b00, 0xc00003c180, 0x3, 0x3, 0x0, 0x0)
	/root/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/app.go:261 +0x6e3
main.main()
	/usr/local/lotus/cmd/lotus-storage-miner/main.go:81 +0x621

![image](https://user-images.githubusercontent.com/53812125/83408111-a4edca00-a444-11ea-9e70-37e725772b36.png)
2020-05-30T08:49:24.394 INFO filcrypto::proofs::api > generate_window_post: finish
2020-05-30T08:49:24.396+0800    ^[[31mERROR^[[0m        storageminer    storage/wdpost_run.go:57        runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
        /usr/local/lotus/storage/wdpost_run.go:343
  - sanity check failed

       0: storage_proofs_core::compound_proof::CompoundProof::prove
       1: filecoin_proofs::api::post::generate_window_post
       2: filecoin_proofs_api::post::generate_window_post_inner
       3: filecoin_proofs_api::post::generate_window_post
       4: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
       5: ffi_toolkit::catch_panic_response
       6: fil_generate_window_post
       7: _cgo_66afc6c6cd88_Cfunc_fil_generate_window_post
                 at /tmp/go-build/cgo-gcc-prolog:446
       8: runtime.asmcgocall
                 at /usr/lib/go-1.14/src/runtime/asm_amd64.s:655
    github.com/filecoin-project/filecoin-ffi.GenerateWindowPoSt
        /usr/local/lotus/extern/filecoin-ffi/proofs.go:566
    github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).GenerateWindowPoSt
        /root/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200522011946-a59ca7536a95/ffiwrapper/verifier_cgo.go:34
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
        /usr/local/lotus/storage/wdpost_run.go:341
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).doPost.func1
        /usr/local/lotus/storage/wdpost_run.go:46
    runtime.goexit
        /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373

**Version (run `lotus --version`):**
lotus version 0.3.0'+gitc3916e3a.dirty'

**Comment by anorth** [comment]
This happens when the proving period has elapsed, but the cron has not yet updated state to start the next proving period (e.g. there was a null round, or the actor state is broken such that cron fails).

There is no "current" deadline if the [proving period has elapsed](https://github.com/filecoin-project/specs-actors/blob/8ab252fac3b79e5555d246f21151b45c8937a328/actors/builtin/miner/deadlines.go#L30). The command must not index the deadlines by `Index` if so.

**Comment by Leozhang404** [comment]
maybe it should be changed `[deadlineIdx := uint64(periodProgress / WPoStChallengeWindow)](https://github.com/filecoin-project/specs-actors/blob/8ab252fac3b79e5555d246f21151b45c8937a328/actors/builtin/miner/deadlines.go#L66)`
to _deadlineIdx := uint64(periodProgress % WPoStChallengeWindow)_

**Comment by Leozhang404** [comment]
maybe it should be changed [deadlineIdx := uint64(periodProgress / WPoStChallengeWindow)](https://github.com/filecoin-project/specs-actors/blob/8ab252fac3b79e5555d246f21151b45c8937a328/actors/builtin/miner/deadlines.go#L66)
to deadlineIdx := uint64(periodProgress % WPoStChallengeWindow)

**Comment by arajasek** [comment]
Fixed in #2303
