### ISSUE TITLE
Improve devnet UX / documentation

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#1891]
We've had a few people ask about how to run devnets, with multiple miners. Our documentation here is somewhat lacking, and we can also probably afford to improve the UX of creating new miners from the CLI.

**Comment by hsanjuan** [comment]
Added this to tutorials list (internal doc) for docs.filecoin.io

**Comment by magik6k** [comment]
https://docs.filecoin.io/build/local-devnet/#textile-s-lotus-devnet
