### ISSUE TITLE
StateSearchMsg returns address not found error

### ISSUE THREAD

**Issue by Schwartz10** [filecoin-project/lotus#1907]
**Describe the bug**
The `StateSearchMsg` jsonrpc handler will return the following error when the message in search is sent `From` a new wallet without any previous SENT on-chain transactions (`From` address `Nonce` is 0)

```
resolution lookup failed (t1ivf2iq3kgzgwgcza6tlxkep2kc3jozlfqwi2gfy): resolve address t1ivf2iq3kgzgwgcza6tlxkep2kc3jozlfqwi2gfy: address not found
```

**NOTE** - the same error occurs when trying to `MpoolGetNonce` for the same address, but the error in this context makes a little more sense.

**To Reproduce**
1. Spin up a new wallet 
2. Send the wallet some FIL
3. Send a message with the new wallet
4. Take the message's `Cid`, and use that in the request to `StateSearchMsg` - the error will persist

**Expected behavior**
We shouldn't see this error for searching messages

**Version (run `lotus --version`):**
lotus version 0.3.0'+gitfca09755.dirty'

**Additional context**
Haven't confirmed this is the line, but I _think_ this throws the error https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/stmgr.go#L608

**Comment by whyrusleeping** [comment]
Ah, this is embarassing. Should be a quick fix.
