### ISSUE TITLE
Potential race between storage miner and storage market

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/lotus#1916]
**Describe the bug**
The storage-fsm and storage provider both need to know when sectors have been proven. Storage-fsm needs to track the state of its sectors, and the storage market needs to know when deals become active because a piece has landed in a proven sector. Both systems wait for the ProoveCommitSector message to land on chain before proceeding to indicate that the sector is now in the proving set.

The problem is that as the storage provider is preparing to store the deal info, it calls `LocatePieceForDealWithinSector`, which then requests sectors from the miner and ignores any sector not in the `Proving` state. The correct sector will only be in the `Proving` state if the storage-fsm has already processed its `ProveCommitSector` message.

This is not currently failing because the provider uses the `Events` struct to wait for the message and it supports a confidence interval (currently set to 3). So it will always fire significantly after the miner. This timing delay is not an appropriate use of the confidence interval. Also with #1913 `StateWaitMsg` can also have a (much needed) confidence interval. In the current state, the provider's confidence interval will always need to be configured to be one greater than the storage-fsm to avoid a race.

Ideally the markets code could look directly on chain for the sector. Alternatively it could wait on the storage miner to tell it when the prove commit is done.

**Comment by dirkmc** [comment]
`LocatePieceWithinSector()` is no longer used. I've removed references to it in the code: https://github.com/filecoin-project/go-fil-markets/pull/518
