### ISSUE TITLE
Expose control over deal decision logic

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#1920]
We need to expose some controls for the storage miner over their deal decision logic. Namely, we should be able to configure some parameters about deal auto acceptance, setting an ask is already there, but some additional things we need are:

- [x] Ability to halt deal making (storage or retrieval independently) [ P0 ]
- [ ] #6750
- [x] Ability to decline all deals matching certain criteria (offline deals, for example) [ P1 ]
- [ ] #6751

**Comment by whyrusleeping** [comment]
Additionally, we should allow miners to have a list of content CIDs they won't store or serve retrieval requests for. This may be required for miners to comply with local law enforcement requests (note that which lists to respect and which items to block are entirely up to the miner operator)

**Comment by laser** [comment]
Note: [This PR](https://github.com/filecoin-project/go-fil-markets/pull/269) in go-fil-markets (now merged) adds a configuration option to the retrieval provider which allows the node to register a `DealDecider`, which is essentially a predicate to run on any `ProviderDealState` for [purposes of accepting/rejecting a retrieval proposal](https://github.com/filecoin-project/go-fil-markets/blob/095f786c70020734e88497d1f9b7353a36fdb22a/retrievalmarket/impl/providerstates/provider_states.go#L54).

**Comment by arajasek** [comment]
Hmm, for the CLI, I'd propose having a single command, call it `selection` (or a better name). It takes one input parameter, that can be "accept", "reject", or "manual". It also takes a series of flags, such as `--offline`. It can also take a `--all`, which would trigger all the options.

So, something like `./lotus-storage-miner market selection reject --offline` would set us to reject all offline deals, while `./lotus-storage-miner market selection manual --all` would set all incoming deals to need to be manually approved / rejected.

This would require some overhaul of the work in #1994, but not too much. Very much scope to be improved, I'm sure.

**Comment by laser** [comment]
> Additionally, we should allow miners to have a list of content CIDs they won't store or serve retrieval requests for. This may be required for miners to comply with local law enforcement requests (note that which lists to respect and which items to block are entirely up to the miner operator)

Note: This has been addressed [in this yet-to-be-merged PR](https://github.com/filecoin-project/lotus/pull/2069).

**Comment by laser** [comment]
@arajasek 

## Manipulating config

> Hmm, for the CLI, I'd propose having a single command, call it selection (or a better name).

I tweaked your proposal a little in hopes of making the various states straightforward (I eliminated the `--all` flag). To illustrate a potential UX, here's a table containing sequences of commands as well as the system's response to (after the commands have been run) receiving a storage deal proposal:

| Note | Command Seq. | Offline Deal | Online Deal |
| -- | -- | -- | -- |
| <sub>1 | <sub>./lotus-storage-miner market selection reset</sub> | consider | consider |
|  | <sub>./lotus-storage-miner market selection reject --online</sub> | consider | reject |
|  | <sub>./lotus-storage-miner market selection reject --offline</sub> | reject | consider |
|  | <sub>./lotus-storage-miner market selection reject --offline</sub><br><sub>./lotus-storage-miner market selection reject --online</sub> | reject | reject |
|  | <sub>./lotus-storage-miner market selection reject --offline</sub><br><sub>./lotus-storage-miner market selection manual --online</sub> | reject | manual |
|  | <sub>./lotus-storage-miner market selection reject --online</sub><br><sub>./lotus-storage-miner market selection manual --offline | manual</sub> | reject |
|  | <sub>./lotus-storage-miner market selection manual --online</sub><br><sub>./lotus-storage-miner market selection manual --offline</sub> | manual | manual |
| <sub>2</sub> | <sub>./lotus-storage-miner market selection manual --online</sub><br><sub>./lotus-storage-miner market selection reject --online</sub> | consider | reject |
| <sub>2</sub> | <sub>./lotus-storage-miner market selection reject --online</sub><br><sub>./lotus-storage-miner market selection manual --online</sub> | consider | manual |

1: The `selection reset` command reverts the storage miner to the "consider all storage proposals" (default) state.
2. The second command wins.

## Reading config 

We'll also need a `./lotus-storage-miner market selection show` command:

```
./lotus-storage-miner market selection show
offline deals: manual
online deals: reject
```

```
./lotus-storage-miner market selection show
offline deals: consider
online deals: manual
```

**Comment by arajasek** [comment]
@laser Yup, this sounds totally good to me! Thank youuuu :)

**Comment by TippyFlitsUK** [comment]
Hi @whyrusleeping 

This issue has not been updated in some time. Should we close it or keep it open?
