### ISSUE TITLE
Add ability for clients to ask miners to store an unsealed copy of their data for fast retrieval

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#1921]
The deal proposal should include a boolean field specifying whether or not the client is requesting that the miner store an extra unsealed copy of their data for fast retrieval. Miners cannot cryptographically prove they have done this, and so it is unenforceable, but clients can notice that miners take a long time to respond to their retrieval requests, and assume that their request was not respected.

Honest miners may choose to reject deals requesting this in order to keep prices very low.

We should also assume that any deal for verified data has this option set automatically.

**Comment by pooja** [comment]
Could we also enable a way for clients to "un-request" this later once a storage deal has been made? E.g. If they decide they no longer need the fast retrieval option for this file, and they don't want to pay extra for it...

**Comment by flyworker** [comment]
The use case can be something like content used for public accessible webpage, video?

**Comment by momack2** [comment]
@hannahhoward can you confirm if this is resolved by: https://github.com/filecoin-project/lotus/pull/2323 and https://github.com/filecoin-project/lotus/pull/2315?
