### ISSUE TITLE
Lotus seed needs a way to help reduce disk overhead for sealed sectors

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#1925]
For 32GB sectors we are provisioning disk space @ 4x the number of sectors we plan to store, and an additional 392GB  (12x sector size) of storage + some head room per worker process that writes to that volume. This results in a leftover 392GB of unused volume space when the sealing process is finished. When we parallelize the sealing operation out we end up with this extra disk space overhead of 392GB multiplied by the number of workers we are using (36 per miner). This results in a large amount of non utilized disk space when the sealing process is finished and resizing these volumes introduces a lot of risk to the operation.

Ideally we do not want to use the final sector storage for the presealing overhead.

There are two main solutions I believe for this problem

1) We don't seal on the final storage volume and instead move the final data after the process complete.
2) We write the finalized data to the final storage volume, but use a different volume for the temporary files.

I think either of these solution works, the second would probably result in a quicker process as the data only has to be written once.

For either of these fixes we need an additional flag to specify another directory.

**Comment by magik6k** [comment]
Done (I think)
