### ISSUE TITLE
Paych.Manager: how to handle when `waitForPaychCreateMsg` fails

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/lotus#1936]
### Description
Once we post a message to construct a paych.Actor, then call `waitForPaychCreateMsg`, if that message doesn't show up on the chain or it errors in any other way, there is nothing outside of `go-fil-market/retrievalmarket`'s API to deal with that; no timeout, no deal cancellation, etc. The code behaves as if this will always succeed, which is wrong as it already has failed on testnet (see #1611).

The  current behavior of a failure is simply that an error is logged and nothing is stored in the payment channel manager store. In a retrieval deal, such a failure is handled on the go-fil-markets side. [`WaitForPaymentChannelCreation`](https://github.com/filecoin-project/lotus/blob/e9eff8be5c4d6deb3c40ce414caff7ce32cbe74b/markets/retrievaladapter/client.go#L86) does return error, and lotus's implementation of this API function does handle error conditions. In this error case the deal fails. In this context, I don't think it's necessary to change this behavior, however, there could be a need in future by some other consumer of payment channels to handle such a  failure.

**Comment by TippyFlitsUK** [comment]
Hi @shannonwells 

This issue has not been updated in some time. Should we close it or keep it open?

**Comment by TippyFlitsUK** [comment]
Many thanks for the information @shannonwells!

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
