### ISSUE TITLE
nil pointer when lotus-storage-miner run again

### ISSUE THREAD

**Issue by chunqizhi** [filecoin-project/lotus#1956]
The error info:
`2020-06-09T13:55:25.308+0800	INFO	build	Parameter file /data1/filecoin-proof-parameters/v26-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-6babf46ce344ae495d558e7770a585b2382d54f225af8ed0397b8be7c3fcd472.params is ok
2020-06-09T13:55:25.308+0800	INFO	build	parameter and key-fetching complete
2020-06-09T13:55:25.310+0800	INFO	stores	New sector storage: 86efce4f-f62c-4846-a782-1aaf80a86fb5
2020-06-09T13:55:25.432+0800	INFO	storageminer	starting up miner t01888, worker addr t3u6wlv6frhovshvadb7tbwrxtbcfmag4wuo5cgobmq7w4xdyrp4dyeixqmnd2oigrtkqvryqhvg6nqbn4phua
2020-06-09T13:55:25.434+0800	INFO	sectors	Proving sector 1
2020-06-09T13:55:25.434+0800	INFO	sectors	Proving sector 0
2020-06-09T13:55:25.435+0800	INFO	sectors	Proving sector 10
2020-06-09T13:55:25.435+0800	INFO	sectors	Proving sector 11
2020-06-09T13:55:25.435+0800	INFO	sectors	Proving sector 12
2020-06-09T13:55:25.435+0800	INFO	sectors	Proving sector 13
2020-06-09T13:55:25.435+0800	INFO	sectors	Proving sector 14
2020-06-09T13:55:25.435+0800	INFO	sectors	Proving sector 15
2020-06-09T13:55:25.436+0800	INFO	sectors	Proving sector 2
2020-06-09T13:55:25.436+0800	INFO	sectors	Proving sector 3
2020-06-09T13:55:25.436+0800	INFO	sectors	Proving sector 4
2020-06-09T13:55:25.436+0800	INFO	sectors	Proving sector 5
2020-06-09T13:55:25.436+0800	INFO	sectors	Proving sector 6
2020-06-09T13:55:25.436+0800	INFO	sectors	Proving sector 7
2020-06-09T13:55:25.436+0800	INFO	sectors	Proving sector 8
2020-06-09T13:55:25.436+0800	INFO	sectors	Proving sector 9
2020-06-09T13:55:25.436+0800	INFO	miner	Time delta between now and our mining base: 20s (nulls: 0)
2020-06-09T13:55:25.436+0800	INFO	main	Remote version 0.4.0+git.96a5e579+api0.3.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xb620da]

goroutine 1256 [running]:
github.com/filecoin-project/storage-fsm.(*Sealing).checkCommit(0xc0001d2e80, 0x2aefcc0, 0xc0001ae008, 0xc0054e0520, 0xc, 0x13, 0x7, 0xc0004b7860, 0x1, 0x1, ...)
	/home/impool/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200605082304-aa405b2176aa/checks.go:112 +0x21a
github.com/filecoin-project/storage-fsm.(*Sealing).handleCommitFailed(0xc0001d2e80, 0x2aefcc0, 0xc0001ae008, 0xc0053fe1e0, 0xc0054e0520, 0xc, 0x13, 0x7, 0xc0004b7860, 0x1, ...)
	/home/impool/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200605082304-aa405b2176aa/states_failed.go:162 +0x44b
github.com/filecoin-project/storage-fsm.(*Sealing).Plan.func1(0x2aefcc0, 0xc0001ae008, 0xc0053fe1e0, 0xc0054e0520, 0xc, 0x13, 0x7, 0xc0004b7860, 0x1, 0x1, ...)
	/home/impool/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200605082304-aa405b2176aa/fsm.go:24 +0x81
reflect.Value.call(0x242fd40, 0xc0052872d0, 0x13, 0x2703360, 0x4, 0xc0053f4f70, 0x2, 0x2, 0x5270ff, 0x2517180, ...)
	/usr/lib/go-1.14/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x242fd40, 0xc0052872d0, 0x13, 0xc005232f70, 0x2, 0x2, 0x0, 0x0, 0xc0000fa700)
	/usr/lib/go-1.14/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc0052871f0, 0x2aefcc0, 0xc0001ae008, 0xc0053fe1e0, 0xc005287200, 0xc0004b3920)
	/home/impool/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200226041606-2074af6d51d9/machine.go:91 +0x2bf
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
	/home/impool/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200226041606-2074af6d51d9/machine.go:89 +0x3a0`
-----------------------------------------------------------------------------------------------------
my lotusstorage dir info:
── [4.0K]  cache
│   ├── [4.0K]  s-t01888-0
│   │   ├── [  64]  p_aux
│   │   ├── [9.1M]  sc-02-data-tree-r-last.dat
│   │   └── [ 425]  t_aux
│   ├── [4.0K]  s-t01888-14
│   │   ├── [  64]  p_aux
│   │   ├── [9.1M]  sc-02-data-tree-r-last.dat
│   │   └── [ 430]  t_aux
│   ├── [4.0K]  s-t01888-15
│   │   ├── [  64]  p_aux
│   │   ├── [9.1M]  sc-02-data-tree-r-last.dat
│   │   └── [ 430]  t_aux
│   ├── [4.0K]  s-t01888-16
│   │   ├── [  64]  p_aux
│   │   ├── [512M]  sc-02-data-layer-1.dat
│   │   ├── [512M]  sc-02-data-layer-2.dat
│   │   ├── [585M]  sc-02-data-tree-c.dat
│   │   ├── [1024M]  sc-02-data-tree-d.dat
│   │   ├── [9.1M]  sc-02-data-tree-r-last.dat
│   │   └── [ 430]  t_aux
│   ├── [4.0K]  s-t01888-17
│   │   ├── [  64]  p_aux
│   │   ├── [512M]  sc-02-data-layer-1.dat
│   │   ├── [512M]  sc-02-data-layer-2.dat
│   │   ├── [585M]  sc-02-data-tree-c.dat
│   │   ├── [1024M]  sc-02-data-tree-d.dat
│   │   ├── [9.1M]  sc-02-data-tree-r-last.dat
│   │   └── [ 430]  t_aux
│   ├── [4.0K]  s-t01888-18
│   │   ├── [  64]  p_aux
│   │   ├── [512M]  sc-02-data-layer-1.dat
│   │   ├── [512M]  sc-02-data-layer-2.dat
│   │   ├── [585M]  sc-02-data-tree-c.dat
│   │   ├── [1024M]  sc-02-data-tree-d.dat
│   │   ├── [9.1M]  sc-02-data-tree-r-last.dat
│   │   └── [ 430]  t_aux
│   ├── [4.0K]  s-t01888-19
│   │   ├── [  64]  p_aux
│   │   ├── [512M]  sc-02-data-layer-1.dat
│   │   ├── [512M]  sc-02-data-layer-2.dat
│   │   ├── [585M]  sc-02-data-tree-c.dat
│   │   ├── [1024M]  sc-02-data-tree-d.dat
│   │   ├── [9.1M]  sc-02-data-tree-r-last.dat
│   │   └── [ 430]  t_aux
├── [4.0K]  sealed
│   ├── [512M]  s-t01888-0
│   ├── [512M]  s-t01888-1
│   ├── [512M]  s-t01888-10
│   ├── [512M]  s-t01888-11
│   ├── [512M]  s-t01888-12
│   ├── [512M]  s-t01888-13
│   ├── [512M]  s-t01888-14
│   ├── [512M]  s-t01888-15
│   ├── [512M]  s-t01888-16
│   ├── [512M]  s-t01888-17
│   ├── [512M]  s-t01888-18
│   ├── [512M]  s-t01888-19
│   ├── [512M]  s-t01888-2
│   ├── [512M]  s-t01888-3
│   ├── [512M]  s-t01888-4
│   ├── [512M]  s-t01888-5
│   ├── [512M]  s-t01888-6
│   ├── [512M]  s-t01888-7
│   ├── [512M]  s-t01888-8
│   └── [512M]  s-t01888-9
├── [ 105]  sectorstore.json
├── [  82]  storage.json
├── [ 136]  token
└── [4.0K]  unsealed
    ├── [512M]  s-t01888-16
    ├── [512M]  s-t01888-17
    ├── [512M]  s-t01888-18
    └── [512M]  s-t01888-19
---------------------------------------
Look like the code：
![image](https://user-images.githubusercontent.com/23360623/84113079-8008e080-aa5c-11ea-8d2f-abc8de065484.png)

**Comment by magik6k** [comment]
Fixed in master
