### ISSUE TITLE
Add storage   （ storage attach --init --seal=true --store=true）

### ISSUE THREAD

**Issue by ytQiao** [filecoin-project/lotus#1967]
I use the command `lotus-storage-miner storage attach --init --seal=true --store=true /lotus/lotus2/` , Create another storage space, but I find it doesn't seem to work. So far, it has sealed 1T files.

```
84087182-2c3b-40ec-958b-462779101a79:
	[||                                                ] 1.82 TiB/36.2 TiB 5%
	Unsealed: 0; Sealed: 0; Caches: 0
	Weight: 10; Use: Seal Store
	Local: /lotus/lotus2/
	URL: http://192.168.1.124:2345/remote
```

lotus version
```
Daemon:  0.4.0+git.96a5e579+api0.3.0
Local: lotus version 0.4.0+git.96a5e579
```
sectors size
512M

@whyrusleeping @magik6k

**Comment by ytQiao** [comment]
In addition, can I directly store sector files on the seal-worker without saving them on storage-miner?

**Comment by sedasdas** [comment]
good idea

**Comment by Shekelme** [comment]
But your storage has been attached and it's roles you defined for it are visible bu lotus-miner. Use `lotus-miner sectors pledge` to seal test sectors.

**Comment by magik6k** [comment]
I'm not sure what the issue was here, it looks like it worked as expected. (please open a new issue if I'm missing something / it's still not working)
