### ISSUE TITLE
Storage issues

### ISSUE THREAD

**Issue by chengwds** [filecoin-project/lotus#1976]
To store some garbage data as effective computing power, customers really need to store important files without disk space. The disk size and online time length are important as effective computing power. This project goes against the original intention.

**Comment by chengwds** [comment]
These Americans don't understand it. They've been bragging for years. It's too hard to develop it.

**Comment by chengwds** [comment]
You can develop a read proof, write proof, Download proof. This is what you like

**Comment by chengwds** [comment]
The disk size and online time length are important as effective computing power. 1075 miners will not be so arrogant, 1075 is a formal development team。

**Comment by arajasek** [comment]
Thanks for the feedback! We're always striving to make Filecoin as true to the ideal of "storage = mining power", with as little hardware and computing power needed. Suggestions about how we can get closer to that ideal are *very* welcome.

PS: I'm Indian, we're not (all) Americans :')
