### ISSUE TITLE
This error is reported when executing Lotus Daemon (the latest master branch)

### ISSUE THREAD

**Issue by quickappdev** [filecoin-project/lotus#1997]
**Describe the bug**
Today, the lotus program built using the latest version of the master branch code on github. When executing Lotus Daemon, this error is reported, who can help solve it?

**To Reproduce**
1. Run'lotus daemon'
2. This error occurs intermittently when synchronizing blockchain data

**Expected behavior**
Start lotus normally and synchronize complete blockchain data.

**Screenshots**
![lotus-error](https://user-images.githubusercontent.com/37727233/84459601-6fde4480-ac9a-11ea-93df-5cae6205c199.jpg)

**Version (run `lotus --version`):
lotus version 0.3.0'+git9457df9'

**Comment by arajasek** [comment]
Does this error persist? I suspect this is just some network weirdness (that shouldn't always happen).

PS: Thanks for the well-crafted issue!

**Comment by quickappdev** [comment]
`**2020-06-12T14:37:50.584+0800 ERROR** hello hello/hello.go:107 failed to fetch tipset from peer during hello: blocksync req failed:
    github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).sendRequestToPeer
        /usr/local/lotus/chain/blocksync/blocksync_client.go:262
  -i/o deadline reached
**2020-06-12T14:38:01.764+0800 ERROR** hello hello/hello.go:107 failed to fetch tipset from peer during hello: blocksync req failed:
    github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).sendRequestToPeer
        /usr/local/lotus/chain/blocksync/blocksync_client.go:262
  -i/o deadline reached
**2020-06-12T14:48:02.164+0800 ERROR** hello hello/hello.go:107 failed to fetch tipset from peer during hello: blocksync req failed:
    github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).sendRequestToPeer
        /usr/local/lotus/chain/blocksync/blocksync_client.go:262
  -i/o deadline reached
**2020-06-12T15:07:46.996+0800 ERROR** hello hello/hello.go:107 failed to fetch tipset from peer during hello: blocksync req failed:
    github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).sendRequestToPeer
        /usr/local/lotus/chain/blocksync/blocksync_client.go:262
  -i/o deadline reached
**2020-06-12T15:09:05.551+0800 ERROR** hello hello/hello.go:107 failed to fetch tipset from peer during hello: blocksync req failed:
    github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).sendRequestToPeer
        /usr/local/lotus/chain/blocksync/blocksync_client.go:262
  -reading cid field t.Parents failed:
    github.com/filecoin-project/lotus/chain/types.(*BlockHeader).UnmarshalCBOR
        /usr/local/lotus/chain/types/cbor_gen.go:296
  -i/o deadline reached

**2020-06-12T15:20:35.146+0800 ERROR** rpc go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/websocket.go:120 handle me:websocket: close sent
`

I am still synchronizing the blockchain data, and the error still continues to appear, but it does not cause the program to quit. Yesterday, the same error caused lotus daemon to crash and quit frequently, unable to use normally.
![lotus-error1](https://user-images.githubusercontent.com/37727233/84477065-9fed0e00-acc1-11ea-9ce2-1acacd15ec9c.jpg)

**Comment by jackoelv** [comment]
the same. macOS Mojave,the latest version of master lotus. make with code.
waitting for solutions.

**Comment by jackoelv** [comment]
I have solved my problem, that was diffrent with yours.
wish good luck for you.
