### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by shishi614** [filecoin-project/lotus#1998]
When the program starts, Panic

![image](https://user-images.githubusercontent.com/20469171/84464150-50e5af80-aca6-11ea-85c7-9d3ddbc500be.png)

~/sealinterop/bin$ ./lotus-storage-miner -v
lotus-storage-miner version 0.4.0+git.96a5e579.dirty

**Comment by arajasek** [comment]
Did this just happen the once, or is it reproducible?

**Comment by shishi614** [comment]
it reproducible，It's gonna crash all the time

**Comment by whyrusleeping** [comment]
it looks like this has been resolved in a recent change to the storage-fsm

**Comment by daviddias** [comment]
Closing. @shishi614 let us know if you still find the issue and we will reopen if necessary
