### ISSUE TITLE
miner init erro

### ISSUE THREAD

**Issue by bluematrixcn** [filecoin-project/lotus#2002]
![image](https://user-images.githubusercontent.com/52840661/84468416-58f71c80-acb1-11ea-8f64-957026e97c17.png)
follow the message， I found PeerId not as usual ，witch like `12D3KooW9rF6nXyKBpJbhTgnWK...`
and also have  some `/`  at this parame,

**Comment by arajasek** [comment]
Thanks for the issue! What version are you using?

**Comment by bluematrixcn** [comment]
version is `lotus version 0.4.0+git.e473f629`

**Comment by magik6k** [comment]
Did you use matching versions of `lotus` and `lotus-storage-miner`?
