### ISSUE TITLE
syncing starts from height 0 every restart

### ISSUE THREAD

**Issue by kraymond37** [filecoin-project/lotus#2003]
**Describe the bug**
Every time I restart lotus daemon, the syncing starts from height 0 again.

**To Reproduce**
1. Run `lotus daemon`
2. Wait for a while
3. Run `lotus sync status`
```
worker 0:
	Base:	[bafy2bzacedajjxea4zfdef46bgqnntygqsmv6f2ntabrldkznpt7livxdmg6m]
	Target:	[bafy2bzacedamfk75xlvpooldbifoqkbu4luozw3g27tec3u473efrazozzuco] (70801)
	Height diff:	70801
	Stage: message sync
	Height: 398
	Elapsed: 7m24.145503147s
```
4. Stop lotus
5. Run `lotus daemon`

**Expected behavior**
Syncing starts from 398 instead of 0.

**Version (run `lotus --version`):**
lotus version 0.3.0'+git6d90f12b'

**Comment by arajasek** [comment]
This is intended behaviour -- you *must* start syncing from scratch unless you have already reached and validated until the tip.

However, you do remember which blocks you've already validated, so syncing forward to the last-validated block should be fairly quick.
