### ISSUE TITLE
Can not access the JSON RPC from remote

### ISSUE THREAD

**Issue by Ljzn** [filecoin-project/lotus#2004]
**Describe the bug**

Can not access the JSON RPC from remote, but works well in localhost.

**To Reproduce**
1. Run './lotus daemon'
2. Run in another shell, got the result.
```
curl -X POST \
     -H "Content-Type: application/json" \
     --data '{ "jsonrpc": "2.0", "method": "Filecoin.ChainHead", "params": [], "id": 3 }' \
     'http://127.0.0.1:1234/rpc/v0'
```

3. Run in a remote machine
```
curl -X POST \
     -H "Content-Type: application/json" \
     --data '{ "jsonrpc": "2.0", "method": "Filecoin.ChainHead", "params": [], "id": 3 }' \
     'http://[the IP of node machine]:1234/rpc/v0'
```
can not get any response.

**Expected behavior**
access the JSON RPC from remote

**Version (run `lotus --version`):**

lotus version 0.3.0'+git7d166fd7'

**Comment by jsign** [comment]
@Ljzn , by default Lotus bind to localhost. You can configure that in the `.toml` configuration file.

**Comment by schomatis** [comment]
See https://lotu.sh/en+api for more details.

**Comment by Ljzn** [comment]
Hi, @jsign @schomatis . Thanks for your advise.

I changed the `~/.lotus/config.toml` to 
```
[API]
  ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  RemoteListenAddress = "127.0.0.1:1234"
```

But still can not access over the internet.

**Comment by ricktian1226** [comment]
> @Ljzn , by default Lotus bind to localhost. You can configure that in the `.toml` configuration file.

resolve my problem! thanks

**Comment by jsign** [comment]
> Hi, @jsign @schomatis . Thanks for your advise.
> 
> I changed the `~/.lotus/config.toml` to
> 
> ```
> [API]
>   ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
>   RemoteListenAddress = "127.0.0.1:1234"
> ```
> 
> But still can not access over the internet.

`ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"` should bing the listening port to all your network interfaces of the host.

Accesing them from the internet is also related to other actions, such of port-forwarding if it's behind a router, firewall rules that might need to be created, etc.
