### ISSUE TITLE
Add `ChainHeight` field to block header

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#2010]
The research team has a 'must have' change for us. We need to distinguish between what 'round' the chain is at (which is what we're currently calling `Height`) and the 'Height' of the chain, which is the total number of non-null rounds in the chain. 

Related to this: https://github.com/filecoin-project/specs-actors/issues/408 but it really should have a specs PR first.

**Comment by arajasek** [comment]
I don't think this will be happening.
