### ISSUE TITLE
lotus daemon crashed with unknown reason

### ISSUE THREAD

**Issue by Cyanglacier** [filecoin-project/lotus#2022]
This bug occur when running lotus daemon approximately 3-5 min, reasons unknown. Maybe caused by the garbage collection or golang .
 

![image](https://user-images.githubusercontent.com/47769205/84617361-407d4100-af01-11ea-9bf7-c48ed63f0a6f.png)

Version: Interopnet lotus version 0.4.0+git.90665889

Here is the crashlog
[Crashlog.txt](https://github.com/filecoin-project/lotus/files/4777990/Crashlog.txt)

**Comment by Cyanglacier** [comment]
sorry, wrong pic.
here is the error codes
![image](https://user-images.githubusercontent.com/47769205/84617828-c51c8f00-af02-11ea-9ec1-add4a659e5d7.png)

**Comment by magik6k** [comment]
Can you share more info about your operating system, Golang version, and hardware specs (memory size)?

**Comment by Cyanglacier** [comment]
> Can you share more info about your operating system, Golang version, and hardware specs (memory size)?

No problem.
OS: Ubuntu 20.04LTS
Golang Version: 1.14.4
Hardware specs:
RAM: 32G DDR4 2666*4 (total 128G)
CPU: Ryzen 3700X
GPU: 2080Ti

**Comment by magik6k** [comment]
We've had some issues with FFI interface to proofs, which were fixed since, and were likely the cause here. Please open a new issue if you are still experiencing crashes.
