### ISSUE TITLE
badger LOG Compact FAILED with error: too many open files

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/lotus#2038]
**Describe the bug**
The chain is halted at height of 24598,and error log repeat print with `too many open files`.

**To Reproduce**
1. Run './lotus daemon'
2. See error as below

**Expected behavior**
The Chain should sync smoothly.

**Screenshots**
repeat printing:

2020-06-16T17:45:34.975+0800    ^[[33mWARN^[[0m badger  LOG Compact FAILED with error: open /Users/tshi/.lotus/datastore/chain/194079.sst: too many open files
While opening new table: 194079
github.com/dgraph-io/badger/v2.(*levelsController).compactBuildTables.func2
        /Users/tshi/code/go/src/github.com/filecoin-project/lotus/vendor/github.com/dgraph-io/badger/v2/levels.go:618
github.com/dgraph-io/badger/v2.(*levelsController).compactBuildTables.func3
        /Users/tshi/code/go/src/github.com/filecoin-project/lotus/vendor/github.com/dgraph-io/badger/v2/levels.go:642
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
While running compaction for: {elog:0xc00145a680 thisLevel:0xc000e9e5a0 nextLevel:0xc000e9e6c0 top:[0xc01a66c1a0 0xc0152852b0 0xc015285450 0xc015285ad0 0xc028373380 0xc028373450 0xc028373520 0xc01964bba0 0xc01930bd40 0xc040b2d6c0] bot:[0xc011cf81a0 0xc02e616410 0xc022d1ad00 0xc026c98270 0xc027e3a410 0xc0249351e0 0xc024935ad0 0xc0275b6820 0xc0275b69c0 0xc01e646dd0 0xc019bca270 0xc015284750 0xc019bcb1e0 0xc020de0270 0xc020de0410 0xc038aad1e0] thisRange:{left:[] right:[] inf:true} nextRange:{left:[33 98 97 100 103 101 114 33 104 101 97 100 0 0 0 0 0 0 0 0] right:[47 98 108 111 99 107 115 47 85 68 83 65 69 73 72 90 90 90 90 72 80 53 52 69 78 79 72 65 55 84 69 87 79 50 68 77 54 82 89 79 55 73 51 73 69 77 89 66 76 55 70 84 69 50 86 73 77 54 81 83 86 77 75 51 81 52 255 255 255 255 255 255 255 255] inf:false} thisSize:0 dropPrefix:[]}
github.com/dgraph-io/badger/v2.(*levelsController).compactBuildTables
        /Users/tshi/code/go/src/github.com/filecoin-project/lotus/vendor/github.com/dgraph-io/badger/v2/levels.go:674
github.com/dgraph-io/badger/v2.(*levelsController).runCompactDef
        /Users/tshi/code/go/src/github.com/filecoin-project/lotus/vendor/github.com/dgraph-io/badger/v2/levels.go:837
github.com/dgraph-io/badger/v2.(*levelsController).doCompact
        /Users/tshi/code/go/src/github.com/filecoin-project/lotus/vendor/github.com/dgraph-io/badger/v2/levels.go:906
github.com/dgraph-io/badger/v2.(*levelsController).runWorker
        /Users/tshi/code/go/src/github.com/filecoin-project/lotus/vendor/github.com/dgraph-io/badger/v2/levels.go:367
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373: {elog:0xc00145a680 thisLevel:0xc000e9e5a0 nextLevel:0xc000e9e6c0 top:[0xc01a66c1a0 0xc0152852b0 0xc015285450 0xc015285ad0 0xc028373380 0xc028373450 0xc028373520 0xc01964bba0 0xc01930bd40 0xc040b2d6c0] bot:[0xc011cf81a0 0xc02e616410 0xc022d1ad00 0xc026c98270 0xc027e3a410 0xc0249351e0 0xc024935ad0 0xc0275b6820 0xc0275b69c0 0xc01e646dd0 0xc019bca270 0xc015284750 0xc019bcb1e0 0xc020de0270 0xc020de0410 0xc038aad1e0] thisRange:{left:[] right:[] inf:true} nextRange:{left:[33 98 97 100 103 101 114 33 104 101 97 100 0 0 0 0 0 0 0 0] right:[47 98 108 111 99 107 115 47 85 68 83 65 69 73 72 90 90 90 90 72 80 53 52 69 78 79 72 65 55 84 69 87 79 50 68 77 54 82 89 79 55 73 51 73 69 77 89 66 76 55 70 84 69 50 86 73 77 54 81 83 86 77 75 51 81 52 255 255 255 255 255 255 255 255] inf:false} thisSize:0 dropPrefix:[]}
2020-06-16T17:45:34.975+0800    ^[[33mWARN^[[0m badger  While running doCompact: While running compaction for: {elog:0xc00145a680 thisLevel:0xc000e9e5a0 nextLevel:0xc000e9e6c0 top:[0xc01a66c1a0 0xc0152852b0 0xc015285450 0xc015285ad0 0xc028373380 0xc028373450 0xc028373520 0xc01964bba0 0xc01930bd40 0xc040b2d6c0] bot:[0xc011cf81a0 0xc02e616410 0xc022d1ad00 0xc026c98270 0xc027e3a410 0xc0249351e0 0xc024935ad0 0xc0275b6820 0xc0275b69c0 0xc01e646dd0 0xc019bca270 0xc015284750 0xc019bcb1e0 0xc020de0270 0xc020de0410 0xc038aad1e0] thisRange:{left:[] right:[] inf:true} nextRange:{left:[33 98 97 100 103 101 114 33 104 101 97 100 0 0 0 0 0 0 0 0] right:[47 98 108 111 99 107 115 47 85 68 83 65 69 73 72 90 90 90 90 72 80 53 52 69 78 79 72 65 55 84 69 87 79 50 68 77 54 82 89 79 55 73 51 73 69 77 89 66 76 55 70 84 69 50 86 73 77 54 81 83 86 77 75 51 81 52 255 255 255 255 255 255 255 255] inf:false} thisSize:0 dropPrefix:[]}: While opening new table: 194079: open /Users/tshi/.lotus/datastore/chain/194079.sst: too many open files

**Version (run `lotus --version`):**
./lotus version
Daemon:  0.4.0+api0.3.0
Local: lotus version 0.4.0

interopnet 90665889681f01b746a8f95a00232a26aa113693
**Additional context**
ls -l /Users/tshi/.lotus/datastore/chain/194079.sst
ls: /Users/tshi/.lotus/datastore/chain/194079.sst: No such file or directory

./lotus sync status
sync status:
worker 0:
	Base:	[bafy2bzaced2gwaof3c6nhgmehxlp47imjnxw7gphhfwh2xjrfd65fa32ztqug]
	Target:	[bafy2bzacedwzk63yqybzmmzlnkbkek2emzbgfjhnf6zfvlx6qkyaaozttdsoe bafy2bzacecjajprhjzjvkvot45h4nvnw4un4kszavqmu4y7adwlxdz2u4lazy bafy2bzacea737toxksmbrvm54yg35ngtrcexugzsmoe2n5g6bopxvwlyldww2] (25873)
	Height diff:	25873
	Stage: message sync
	Height: 24598
	Elapsed: 4h25m13.211115s
worker 1:
	Base:	[]
	Target:	[] (0)
	Height diff:	0
	Stage: <unknown: 0>
	Height: 0
worker 2:
	Base:	[]
	Target:	[] (0)
	Height diff:	0
	Stage: <unknown: 0>
	Height: 0

**Comment by magik6k** [comment]
I'd recommend netting `ulimit -n` to something high like 100000, I don't think there is an easy way to work around this.

We should probably warn the user is open file limits are low.

**Comment by f8-ptrk** [comment]
not a lotus issue 

#antidisestablishatarianism
