### ISSUE TITLE
storage miner should reject deals if it has too many queued sealing jobs

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#2049]
similar to 2048, we need to more accurately account for how much work a miner can actually do in a given amount of time, so we can limit incoming deals and prevent miners from losing funds due to not activating deals in time.

**Comment by arajasek** [comment]
The same thing needs to be done on the retrieval side if a lot of unsealing is already happening

**Comment by arajasek** [comment]
#2967 has a similar problem to report, should be considered when fixing this

**Comment by mishmosh** [comment]
Fixed via #3147
