### ISSUE TITLE
`lotus client cat`-like UX spec

### ISSUE THREAD

**Issue by ribasushi** [filecoin-project/lotus#2052]
( if there is already an issue open about this that I missed, please close this and point me in the right direction )

A request was surfaced to implement a `cat`-style retrieval command, within the lotus UI to go with the charismatic datasets effort. Piecing together the notes on this it seems like:

- The request is to augment `lotus client retrieve <cid>` to also understand something like `lotus client retrieve <commP> --car-path <pathspec to in-car file>`
- `-` or something similar needs to be supported as destination-spec to allow assembly of files spanning multiple car's

I will update the above when more data is gathered throughout the week.

/cc @mikeal @jnthnvctr

**Comment by jennijuju** [comment]
seems like `lotus client retrieve --car --pieceCid` may do the trick - reopen and implement it if not the case! @ribasushi
