### ISSUE TITLE
lotus daemon error: cbor input had wrong number of fields

### ISSUE THREAD

**Issue by jdyuankai** [filecoin-project/lotus#2061]
Describe the bug
![20200618123630的副本 2](https://user-images.githubusercontent.com/17009193/84979109-38234100-b161-11ea-9111-8a056c72a5ba.jpg)

$ git checkout master
$ make clean && make all && sudo make install
$ rm -rf ~/.lotus
$ lotus daemon
See error picture above

Version (run lotus --version):
lotus version 0.4.0+git.c7e3a5cf

**Comment by cryptokeeper1** [comment]
I'm having the same issue I think.
![Image 6-18-20 at 5 39 PM](https://user-images.githubusercontent.com/67127543/85079225-43dc2b00-b194-11ea-8e80-4dcd4268224b.jpg)

**Comment by cryptokeeper1** [comment]
Does anyone know how to fix this?

**Comment by arajasek** [comment]
This is likely versioning issues -- probably a newer version of Lotus being used on older databases. #2678 should help clarify.

BTW, @cryptokeeper1, `rm -rf` to delete directories.
