### ISSUE TITLE
Retrieval Error: reading deal response: stream reset

### ISSUE THREAD

**Issue by stefangeorgerobert** [filecoin-project/lotus#2066]
**Describe the bug**

lotus client retrieve fails.

**To Reproduce**

lotus client find QmYfGRGFpVgaT3dhMRScwiPGUvHkq1wgygUULRX9Pop3eH

_LOCAL
RETRIEVAL t01989@12D3KooWGsMLm2BziXWYf31pL7oqMRfd9nSuHVy1qLi6yzsznqVA-0.000000000266338304fil-127 MiB_

lotus client list-deals | grep bafyreibglngy3rpxykahmzmr7mubvchwa5gxfypihsovxnz3qjekrdzn5q

_bafyreibglngy3rpxykahmzmr7mubvchwa5gxfypihsovxnz3qjekrdzn5q  247  t02000  StorageDealActive   Y (epoch 3596)  N  bafk4chzayqch5ga44vgxcsx42jzjtaanbtktwoj7wwzx4hnib7h6i2745ufq  127 MiB  500000000  13181_

lotus client retrieve QmYfGRGFpVgaT3dhMRScwiPGUvHkq1wgygUULRX9Pop3eH r1.data

_2020-06-18T10:44:45.201Z	WARN	main	lotus/main.go:81	Retrieval Failed:
    github.com/filecoin-project/lotus/cli.glob..func19
        /root/lotus/cli/client.go:452
  - RetrieveUnixfs: Retrieval Error: reading deal response: stream reset_

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**
lotus version 0.4.0+git.bead3bf4.dirty

**Additional context**

**Comment by jennijuju** [comment]
Thanks for creating the ticket! Things got improved a lot since this ticket was open - please create a new issue if you are still running into it with the latest lotus release!
