### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2067]
This is something of a placeholder for the work we have to do (and is being requested of us) to improve our API documentation. Some initial thoughts include:

- GoDoc-ing our API, starting with the methods themselves in `api_full.go`. This will improve the autogenerated documentation we have too.
- Elaborating the data types that can come in/out of the API 
- Figuring out documentation for Markets and other shared components ("how to make a deal" documentation leading you into the spec was raised as a particular concern)
- GoDoc-ing the rest of the codebase?

**Comment by jennijuju** [comment]
duplicated #4544
