### ISSUE TITLE
lotus sync status shows only 1 worker is working.

### ISSUE THREAD

**Issue by jackoelv** [filecoin-project/lotus#2071]
**Describe the bug**

when I run lotus in Ubuntu server , only 1 worker is working.
when I run lotus in my macbookpro, all of the workers are working.
what`s the problem?

nl@nl-Tecal-RH2288H-V2-12L:~$ lotus sync status
sync status:
worker 0:
	Base:	[]
	Target:	[] (0)
	Height diff:	0
	Stage: <unknown: 0>
	Height: 0
worker 1:
	Base:	[bafy2bzacedajjxea4zfdef46bgqnntygqsmv6f2ntabrldkznpt7livxdmg6m]
	Target:	[bafy2bzacedamfk75xlvpooldbifoqkbu4luozw3g27tec3u473efrazozzuco] (70801)
	Height diff:	70801
	Stage: message sync
	Height: 34018
	Elapsed: 18h32m50.730030048s
worker 2:
	Base:	[]
	Target:	[] (0)
	Height diff:	0
	Stage: <unknown: 0>
	Height: 0
**To Reproduce**

1. Run '...'
2. See error

**Expected behavior**
It should be 3 workers all are working.

**Screenshots**

**Version (run `lotus --version`):**

**Additional context**

**Comment by jackoelv** [comment]
in Ubuntu:
nl@nl-Tecal-RH2288H-V2-12L:~/git/lotus$ lotus sync status
sync status:
worker 0:
	Base:	[bafy2bzacednghy3w2e42xqrgeisswleti2uf2dno4ffaieuge2wfrbigqwdv6]
	Target:	[bafy2bzaceb2alajnvienzy4yiaoqy34ytmqdlo5wfyolyxk2l7sor4xqxbuem bafy2bzaceae6s2xqj3scq2osgc3gvt5ckefpgxi37vve6uv7n7weexurh6mny bafy2bzaceb26w6c22x2vxtowg2n25vxv57knnd7pc2zekuxixlo6relpofqhq] (709)
	Height diff:	709
	Stage: message sync
	Height: 16
	Elapsed: 54.786961785s
worker 1:
	Base:	[]
	Target:	[] (0)
	Height diff:	0
	Stage: <unknown: 0>
	Height: 0
worker 2:
	Base:	[]
	Target:	[] (0)
	Height diff:	0
	Stage: <unknown: 0>
	Height: 0

in macOS:

jackmbp:lotus jack$ lotus sync status
sync status:
worker 0:
	Base:	[bafy2bzacednghy3w2e42xqrgeisswleti2uf2dno4ffaieuge2wfrbigqwdv6]
	Target:	[bafy2bzacebyh7ctae6o6kfkxuh5m64oov6xysw5ue6h3622a4qclwfefgz35w bafy2bzaceb6hi7b77uv37sg4gnaegtosj5ysyfwaxhp2prfabtyqgeznib7kw bafy2bzaced6hlns46xwvgoi2j5uzagpniohqo6hl7wllmd3ecpmsxuiaiddpi] (696)
	Height diff:	696
	Stage: message sync
	Height: 0
	Elapsed: 9.340562s
worker 1:
	Base:	[bafy2bzacednghy3w2e42xqrgeisswleti2uf2dno4ffaieuge2wfrbigqwdv6]
	Target:	[bafy2bzacec6s55vl5jmrf24k2ae3gst6imllwepp3xsd6rohkvvy52ie43glk bafy2bzacedmnzswroikytbbx27chekp34a2geh556vo4med5gsoywasusn2q6 bafy2bzacedrdfljg6ur6rljamifbevgghvmufunl3gvbklpwtqhckcjjxieoa] (699)
	Height diff:	699
	Stage: error
	Height: 0
	Elapsed: 5.712253s
	Error: collectChain syncMessages: message processing failed: GetChainMessages failed with all peers(1): blocksync req failed: failed to read uint64 for t.BlsMsgIncludes[i] slice: i/o deadline reached
worker 2:
	Base:	[bafy2bzacednghy3w2e42xqrgeisswleti2uf2dno4ffaieuge2wfrbigqwdv6]
	Target:	[bafy2bzacebjkxgky3n4yihjf5druanrhsmm3wazed252mvqqnvl2way4cjjoe bafy2bzacedauiydef7fzwqi2uzohaelkb4ez5gicopipigg5sszu5vnx4t5hw bafy2bzacedoydij5ntt2wf2luqhlujvjrwkslm2ml5qmiv6w4nqgoxl6p4qma] (700)
	Height diff:	700
	Stage: message sync
	Height: 0
	Elapsed: 9.340702s

**Comment by jackoelv** [comment]
jackmbp:lotus jack$ lotus --version
lotus version 0.4.0+git.ffa7be86.dirty

nl@nl-Tecal-RH2288H-V2-12L:~/git/lotus$ lotus --version
lotus version 0.4.0+git.ffa7be8.dirty

**Comment by jackoelv** [comment]
the problem is why 3 workers working in macOS,but ony 1 worker working in ubuntu.

**Comment by kraymond37** [comment]
the same problem

**Comment by jackoelv** [comment]
when restart , macOS have only 1 worker now.

**Comment by jackoelv** [comment]
my iMac successfuly synced within 30 minutes.
3 worker going. 
shows complete syncing.

BUT:
why my another macbookpro  in the same intranet cannot? 
why some other machine ubuntu 32 core cpu cannot?
strange

**Comment by jackoelv** [comment]
I have finished syncing in two computer.
just waitting with patience. 
sometimes in luck.
enjoy it.

**Comment by anneyking** [comment]
Could you tell me how to solve this problem?  （only 1 worker is working problem ）

**Comment by anneyking** [comment]
> the same problem

Could you tell me how to solve this problem?
