### ISSUE TITLE
Avoid reporting network timeouts as error in the logs

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/lotus#2072]
Catch when possible the `i/o deadline reached` error to discriminate it from internal errors and report it as a warning at the most. Repeated network timeouts could be escalated to errors.

**Comment by laser** [comment]
@schomatis - Would you mind pasting a few complete (line) examples of the errors you're referring to?

**Comment by schomatis** [comment]
I can do even better and give you the actual code lines, but first let me expand on the rationale of this issue because the request is too broad and I will settle with just resolving the most common cases. The `ERROR` log for me (very subjective) refers to internal errors that were not expected during normal operation. Any network error in my book should be expected because we cannot rely on any of our peers to behave, we may report an error if no one is behaving (or even responding) as we might be in the wrong network (or under attack), but other than that anything else in a decentralized network should be fair game and not alarm the user.

We cannot track _all_ errors coming from the rest of the stack and discriminate them here (that seems like a service `libp2p` should provide) but we should think what are the most common network errors we can recover from and not report them as such (except when happening on a constant basis).

-------------------------

Most of the errors I observed were related to the `BlockSync` service (I'm assuming graphsync would have similar ones but not sure if the the two share some standard).

In the `hello` protocol,

https://github.com/filecoin-project/lotus/blob/ffa7be86fe6ee738ab4b095469029b9fac51e090/node/hello/hello.go#L105-L109

Eventually calling this function which has timeouts all over the place,

https://github.com/filecoin-project/lotus/blob/ffa7be86fe6ee738ab4b095469029b9fac51e090/chain/blocksync/blocksync_client.go#L276

The error log in those cases looks like this:

```
ERROR	hello	hello/hello.go:107	failed to fetch tipset from peer during hello: blocksync req failed:
    github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).sendRequestToPeer
        /home/user/lotus/chain/blocksync/blocksync_client.go:262
  - i/o deadline reached
```

Similarly in the `sync` protocol (calling the same `fetchBlocksBlockSync`),

https://github.com/filecoin-project/lotus/blob/ffa7be86fe6ee738ab4b095469029b9fac51e090/chain/sync.go#L1088-L1093

**Comment by magik6k** [comment]
As far as I can tell this got fixed
