### ISSUE TITLE
filecoin data storage path

### ISSUE THREAD

**Issue by yzn5555** [filecoin-project/lotus#2074]
启动filecoin默认会在当前用户家目录下产生一个.lotus目录，数据都在该家目录下，我想请问没有办法指定数据存储目录吗，只能默认该存储路径吗？

**Comment by TroyWind** [comment]
> 启动filecoin默认会在当前用户家目录下产生一个.lotus目录，数据都在该家目录下，我想请问没有办法指定数据存储目录吗，只能默认该存储路径吗？

设置环境变量 LOTUS_PATH、LOTUS_STORAGE_PATH

**Comment by magik6k** [comment]
Looks like this was answered
