### ISSUE TITLE
Describe lotus bench on the website

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2079]
We fixed the link to lotus-bench in 2bf781d, but we should probably just actually talk about how to run the bench, instead of linking to code.

**Comment by arajasek** [comment]
Oh, and link to these benchmarks, I guess: https://github.com/filecoin-project/benchmarks

**Comment by magik6k** [comment]
https://docs.filecoin.io/mine/lotus/benchmarks/#installation
