### ISSUE TITLE
Lotus produces a confusing error message when a miner is offline

### ISSUE THREAD

**Issue by ghost** [filecoin-project/lotus#2081]
**Describe the bug**
When a miner offline or unreachable, the command `lotus client retrieve --miner <miner ID> <some CID> <local path>` gives a confusing error message:

```
$ lotus client retrieve --miner t01459 bafkreihw7zt2wgch7ixckwepti2ceqmqgbrp77eigt7opemarlaxrpcfsq ~/outfile.bin
2020-06-21T05:54:32.297Z	WARN	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/client.go:406	unmarshaling failed	{"message": "{\"Err\":\"stream reset\",\"Root\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"t01459\",\"MinerPeerID\":\"12D3KooWKmdU7gfG2EJCJi4qnXxmb12uUupxKbvjvSdvZU76yEMN\"}"}
2020-06-21T05:54:32.298Z	WARN	main	lotus/main.go:81	RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
```

This happens when t01459 has no addresses as indicated by `lotus net findpeer <peer ID of t01459>`:

```
$ lotus net findpeer 12D3KooWKmdU7gfG2EJCJi4qnXxmb12uUupxKbvjvSdvZU76yEMN
{12D3KooWKmdU7gfG2EJCJi4qnXxmb12uUupxKbvjvSdvZU76yEMN: []}
```

**To Reproduce**
1. Run `lotus client retrieve --miner tNNNNN <CID> <output path>` where `tNNNNN` is the miner id of a miner that is offline/unreachable (findpeer should return an empty array).  CID can be any well-formed CID.  <output path> can be any local path.  Example:  `lotus client retrieve --miner t01459  bafkreihw7zt2wgch7ixckwepti2ceqmqgbrp77eigt7opemarlaxrpcfsq ~/outfile.bin`
2. See the confusing error message

**Expected behavior**
"Error:  there are no addresses for miner t01459"
or
"Error:  miner t01459 is not reachable"

**Screenshots**
(Not necessary here)

**Version (run `lotus --version`):**
lotus version 0.4.0+git.596ed330

**Additional context**
None

**Comment by jennijuju** [comment]
was able to quickly repro with v1.10.0 TAT

**Comment by TippyFlitsUK** [comment]
Hi @ghost

This issue has not been updated in some time. Should we close it or keep it open?
