### ISSUE TITLE
The same message is packed into two different blocks at two different heights

### ISSUE THREAD

**Issue by shannon-6block** [filecoin-project/lotus#2083]
**Describe the bug**
On Testnet 0.4.0, the message `bafy2bzacectfye6n3pelmv7ez5hzihbsm6gz2qfhoey642xizpjwdvf4lomv2` is packed into block `bafy2bzacebxrjual3hqzqp5wjmnmukwn3lontjuwhy6ywwjl224c4vb3nzwfk` (6633) and `bafy2bzacebxq2katepkp6hfhxr6cq7zjrhoj4vh4vjvkjzhay2jhbhvldp7ce` (6634).

Although the exit code of the latter is `SysErrSenderStateInvalid`, it may have unknown effects on the blockchain.

**To Reproduce**
1. Run `lotus chain getblock bafy2bzacebxrjual3hqzqp5wjmnmukwn3lontjuwhy6ywwjl224c4vb3nzwfk`
2. See the message whose nonce is `5448`
3. Run `lotus chain getblock bafy2bzacebxq2katepkp6hfhxr6cq7zjrhoj4vh4vjvkjzhay2jhbhvldp7ce`
4. See the same message

**Comment by Kubuxu** [comment]
That is expected if miner selects a bad message for a block. The system caught that (the second message has the exit code `SysErrSenderStateInvalid`), and miner had to pay a penalty (which depends on gas).

**Comment by shannon-6block** [comment]
Oh, understood.
