### ISSUE TITLE
Aborting window PoSt logged for every deadline

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#2096]
This aborting window PoSt warning is printed for every deadline, this log needs more context. Currently it's overly concerning, and by it self doesn't provide enough context to understand if something went wrong.

https://github.com/filecoin-project/lotus/blob/596ed330dda83eac0f6e9c010ef7ada9e543369b/storage/wdpost_sched.go#L216

**Comment by kernelogic** [comment]
Does this mean anything at all?

**Comment by magik6k** [comment]
Pretty sure we now don't log this
