### ISSUE TITLE
sealing too lang

### ISSUE THREAD

**Issue by zhangwangjin** [filecoin-project/lotus#2105]
root@node8:/home/porser# lotus-storage-miner version
Daemon:  0.4.0+git.ffa7be86+api0.3.0
Local: lotus-storage-miner version 0.4.0+git.ffa7be86

env 1 loutus ** 1 lotus-storage-miner  &&

**Describe the problem**

I excute `lotus-storage-miner sectors pledge`, wait 20  hours, can't pass precommit1

**Sectors list**

root@node8:/home/porser# lotus-storage-miner sectors list
0: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]
1: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]

**Sectors status**

root@node8:/home/porser# lotus-storage-miner sectors status --log 0
SectorID:	0
Status:	PreCommit1
CommD:		<nil>
CommR:		<nil>
Ticket:		
TicketH:		0
Seed:		
SeedH:		0
Proof:		
Deals:		[0]
Retries:		0
--------
Event Log:
0.	2020-06-22 14:41:48 +0800 CST:	[event;sealing.SectorStart]	{"User":{"ID":0,"SectorType":3,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"bafk4chzaa57f7xrvyufjga5fkae6gsmkj27n7444ik3rbnzq3dwhvr5puy7a"}},"DealInfo":null}]}}
1.	2020-06-22 14:41:48 +0800 CST:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
2.	2020-06-23 09:39:42 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
3.	2020-06-23 09:39:42 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	seal pre commit(1) failed: maybeSchedRequest didn't find any good workers
4.	2020-06-23 09:40:42 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
5.	2020-06-23 09:40:42 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	seal pre commit(1) failed: maybeSchedRequest didn't find any good workers
6.	2020-06-23 09:41:42 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
root@node8:/home/porser# lotus-storage-miner sectors status --log 1
SectorID:	1
Status:	PreCommit1
CommD:		<nil>
CommR:		<nil>
Ticket:		
TicketH:		0
Seed:		
SeedH:		0
Proof:		
Deals:		[0]
Retries:		0
--------
Event Log:
0.	2020-06-23 09:50:15 +0800 CST:	[event;sealing.SectorStart]	{"User":{"ID":1,"SectorType":3,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"bafk4chzaa57f7xrvyufjga5fkae6gsmkj27n7444ik3rbnzq3dwhvr5puy7a"}},"DealInfo":null}]}}
1.	2020-06-23 09:50:15 +0800 CST:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}

**Lotus storage miner logs**
![image](https://user-images.githubusercontent.com/9051261/85353184-3b8c4300-b53a-11ea-9722-4b40dae25c84.png)

![image](https://user-images.githubusercontent.com/9051261/85353250-5e1e5c00-b53a-11ea-8f49-175cc2a14bc1.png)

2020-06-23T09:38:13.365+0800  I had  restart lotus-storage-miner . expand swap from 2G to 256G
This my machine config 
![image](https://user-images.githubusercontent.com/9051261/85353429-ca995b00-b53a-11ea-9a40-dfd0ad2d3fd2.png)

![image](https://user-images.githubusercontent.com/9051261/85353484-ea308380-b53a-11ea-93fd-1449b0e2b202.png)

**Version**

root@node1:/home/filecoin# lotus version
Daemon:  0.4.0+git.ffa7be86+api0.3.0
Local: lotus version 0.4.0+git.ffa7be86

lotus-storage-miner version
Daemon:  0.4.0+git.ffa7be86+api0.3.0
Local: lotus-storage-miner version 0.4.0+git.ffa7be86

**Comment by magik6k** [comment]
Can you share what you get from these commands:
```
lotus-storage-miner workers list
lotus-storage-miner storage list
```

**Comment by skysbird** [comment]
> Can you share what you get from these commands:
> 
> ```
> lotus-storage-miner workers list
> lotus-storage-miner storage list
> ```

same problem here:

![image](https://user-images.githubusercontent.com/38487/85395987-90a07700-b583-11ea-89e2-cc61df6334c3.png)

**Comment by sslazio2009** [comment]
> Can you share what you get from these commands:
> 
> ```
> lotus-storage-miner workers list
> lotus-storage-miner storage list
> ```



> Can you share what you get from these commands:
> 
> ```
> lotus-storage-miner workers list
> lotus-storage-miner storage list
> ```

![2020-06-24 19-51-01 的屏幕截图](https://user-images.githubusercontent.com/41941824/85551182-5357ea00-b654-11ea-8eef-56fd0311cef9.png)

same problem here:
cpu  3970x
ram  256g ddr4 3000mhz
nvme 2x2t raid0

it is spend over 30 hours p1
please  you help me  
it is make me crazy...

**Comment by WBQ1995** [comment]
> Can you share what you get from these commands:
> 
> ```
> lotus-storage-miner workers list
> lotus-storage-miner storage list
> ```

Same here, p1 never finished... cpu AMD 3700x
![Screenshot from 2020-06-25 06-07-04](https://user-images.githubusercontent.com/33942278/85700285-3817c980-b6aa-11ea-9079-11e5d1cbd273.png)
