### ISSUE TITLE
CC upgrading!

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2122]
We want to be able to upgrade a committed capacity sector to one with real data in it. In progress.

**Comment by magik6k** [comment]
Tasks:
- [ ] Support in actors - https://github.com/filecoin-project/specs-actors/pull/514
- [ ] A way to register CC sectors for upgrading in the FSM
- [ ] Watch for CC sectors being upgraded, auto remove
  - [ ] State watcher
  - [x] Sector removal support in storage - https://github.com/filecoin-project/sector-storage/pull/53
  - [ ] FSM states

**Comment by magik6k** [comment]
https://github.com/filecoin-project/lotus/pull/2220
