### ISSUE TITLE
missing port in address in seal worker 

### ISSUE THREAD

**Issue by ryan-kim21** [filecoin-project/lotus#2136]
Please provide all the information requested here to help us troubleshoot "commit failed" issues.
If the information requested is missing, we will probably have to just ask you to provide it anyway,
before we can help debug.

**Describe the problem**

I got the this message. So, I can't run seal worker. 

Could you help me please...? 

Everyday I got the fail.... 

I can't get the coin.. for 3months. 

...please.. again problems. always I got the problem..

![image](https://user-images.githubusercontent.com/63631441/85732496-63e09100-b736-11ea-92e7-6a3bf769a470.png)

A brief description of the problem you encountered while proving (sealing) a sector.

Including what commands you ran, and a description of your setup, is very helpful.

**Sectors list**

The output of `./lotus-storage-miner sectors list`.

**Sectors status**
![image](https://user-images.githubusercontent.com/63631441/85732595-78248e00-b736-11ea-8483-178d62f16ded.png)

The output of `./lotus-storage-miner sectors status --log <sectorId>` for the failed sector(s).

**Lotus storage miner logs**

Please go through the logs of your storage miner, and include screenshots of any error-like messages you find.

**Version**

The output of `./lotus --version`.

**Comment by magik6k** [comment]
Please follow https://docs.filecoin.io/mine/lotus/seal-workers/
