### ISSUE TITLE
Internal Error when ran command 'lotus-seal-worker'

### ISSUE THREAD

**Issue by metalsnail** [filecoin-project/lotus#2146]
It's my first time try to mining and after i build the lotus and ran steps by step as the 'https://docs.lotu.sh/en+lotus-seal-worker' instruction, I though i can begin my mining...but errors showed up.

it kept repeat the error
 '2020-06-26T10:35:37.131Z        WARN    nat     go-libp2p-nat@v0.0.6/nat.go:186 failed to establish port mapping: goupnp: SOAP request got HTTP 500 Internal Server Error'
seems like there are some connection issue. 

Please refer to the screenshot for more details.

Looking forward your reply and support!

thanks for your time and attention!
![20200626183537](https://user-images.githubusercontent.com/30164011/85848667-1f0f3580-b7dc-11ea-8382-c2eb0f7bb74e.png)

**Comment by metalsnail** [comment]
Can someone help me with this issue?

I don't think it was a local network problem - since it was sucessfuly download all updates and proof of replication and spacetime files ... therefore, i believe either there is some setting or missing part cause this issue.

once again, thanks for your time and attention.

**Comment by metalsnail** [comment]
Can someone help me plz?

**Comment by f8-ptrk** [comment]
should be resolved 

#antidisestablishatarianism
