### ISSUE TITLE
Testnet sync error due to "chain linked to block marked previously as bad"

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/lotus#2147]
**Describe the bug**
While sync the testnet node, it failed due to chain linked to block marked previously as bad 

**To Reproduce**
1. Run 'lotus daemon'
2. See error
2020-06-26T11:25:21.906Z	INFO	chain	chain/sync.go:1100	Got blocks: 25835 500
2020-06-26T11:25:21.909Z	ERROR	chain	chain/sync_manager.go:389	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /home/peware/code/lotus/chain/sync.go:428
  - chain contained block marked previously as bad ([bafy2bzacebxpa6nxeb7j7r2uzx5xfjq4srwlns7uumrpgaainn3hf4lrpscik bafy2bzacedn36dtge45drljsp6op7ahbwlsvtrlid3kabyob5xdjislqsfnjs], bafy2bzacedverubfqafzqqvpuspjyts4m3edrta4eghupvupryoo2ouzgukam) (reason: linked to bafy2bzacedhdeim2uxcskp5fxhdpxq24gr4k2zjc2rvysbxu4ftupp3hlyhxe):
    github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
        /home/peware/code/lotus/chain/sync.go:1112
2020-06-26T11:25:23.283Z	WARN	modules	modules/services.go:44	failed to say hello	{"error": "protocol not supported"}

3. run 'lotus sync status'
sync status:
worker 0:
	Base:	[bafy2bzaced3k3cx2474sdsljkpbe6xpanrvfhxrwzyehjt6fuigu77tmb2lr4]
	Target:	[bafy2bzacedabgigb2wcl5xt6gm3bvuxdy2ysaijriqtwcw4jq57p7rmm3pqpa bafy2bzacecbv4bykvcdj76wxhc45xjgfckmosrba5z4bkupm5t34tq4ykhxgs] (25842)
	Height diff:	15682
	Stage: error
	Height: 0
	Elapsed: 78.569µs
	Error: chain linked to block marked previously as bad ([bafy2bzacedabgigb2wcl5xt6gm3bvuxdy2ysaijriqtwcw4jq57p7rmm3pqpa bafy2bzacecbv4bykvcdj76wxhc45xjgfckmosrba5z4bkupm5t34tq4ykhxgs], bafy2bzacecxvsfbvwmjfer6oxc7ew4tobdj5mz2t7bsquenfyq7zpkipa6qzw) (reason: linked to bafy2bzaceb5ouwuvkwy4za32m6usxxs4s7asadfi3yfdbfd6much7ei6mw6fg)
worker 1:
	Base:	[bafy2bzaced3k3cx2474sdsljkpbe6xpanrvfhxrwzyehjt6fuigu77tmb2lr4]
	Target:	[bafy2bzacecsoa7pafblclgiuowtsdqqgwv5ltp4fzgif6swppsh55hl6kcvdw bafy2bzacebr27tshwnsu6anm3sxascqvuzojz52yycjggtinmgph5dcorosoi] (25844)
	Height diff:	15684
	Stage: error
	Height: 0
	Elapsed: 59.382µs
	Error: chain linked to block marked previously as bad ([bafy2bzacecsoa7pafblclgiuowtsdqqgwv5ltp4fzgif6swppsh55hl6kcvdw bafy2bzacebr27tshwnsu6anm3sxascqvuzojz52yycjggtinmgph5dcorosoi], bafy2bzacedqlrqwuyzgmme7mp7sg4fsv2bgzda5u66wjfopupebl75k6whig6) (reason: linked to bafy2bzacedabgigb2wcl5xt6gm3bvuxdy2ysaijriqtwcw4jq57p7rmm3pqpa)
worker 2:
	Base:	[bafy2bzaced3k3cx2474sdsljkpbe6xpanrvfhxrwzyehjt6fuigu77tmb2lr4]
	Target:	[bafy2bzacedqlrqwuyzgmme7mp7sg4fsv2bgzda5u66wjfopupebl75k6whig6 bafy2bzacebir5cwb2o7yaubmedh5e6djs32dljcc3hnhusjklwsulrlbeusuq] (25843)
	Height diff:	15683
	Stage: error
	Height: 0
	Elapsed: 57.329µs
	Error: chain linked to block marked previously as bad ([bafy2bzacedqlrqwuyzgmme7mp7sg4fsv2bgzda5u66wjfopupebl75k6whig6 bafy2bzacebir5cwb2o7yaubmedh5e6djs32dljcc3hnhusjklwsulrlbeusuq], bafy2bzacedabgigb2wcl5xt6gm3bvuxdy2ysaijriqtwcw4jq57p7rmm3pqpa) (reason: linked to bafy2bzacecxvsfbvwmjfer6oxc7ew4tobdj5mz2t7bsquenfyq7zpkipa6qzw)

**Version (run `lotus --version`):**
lotus version 0.4.0+git.ffa7be86

**Comment by RobQuistNL** [comment]
I've seen this command come along as a potential solution; but this might be towards a different bad block - maybe if you mark the one you have here in the following commands, you might be able to fix it? Sorry, not that familiar but this has been the solution in a previous similar issue;

```
lotus chain sethead --epoch 6000
[restart the daemon]
lotus sync mark-bad bafy2bzaceczr24uhkj3mn3lilxbco7xq3ds4ifjv2lhvhcmqay76hzo3pzp3i
```

**Comment by flyworker** [comment]
> I've seen this command come along as a potential solution; but this might be towards a different bad block - maybe if you mark the one you have here in the following commands, you might be able to fix it? Sorry, not that familiar but this has been the solution in a previous similar issue;
> 
> ```
> lotus chain sethead --epoch 6000
> [restart the daemon]
> lotus sync mark-bad bafy2bzaceczr24uhkj3mn3lilxbco7xq3ds4ifjv2lhvhcmqay76hzo3pzp3i
> ```

I run 'lotus chain head'
get 
bafy2bzaceb4pddx2ggyhpwykdz6cb2x4zspyajujwdz3nrhccnf2vzgm2symu
bafy2bzacebfxhlv267qbl23l3swqycl5rfyz4ji73th5pijnx4ky45dgo3vbg'

I think the sethead is not 6000 in my case?

**Comment by flyworker** [comment]
It seem continue doing his job now:
`lotus sync wait`
Worker 0: Target: [bafy2bzacebwzl4z7rzqm472ufqsijvnzpzfypphpfau4pryj5ghz3cvwj3rra bafy2bzacea6gzplydy2dwu532skvasatoqzakui5vtmi3callo3rwf3y7lxoc]	State: message sync	Height: 8806

**Comment by metalsnail** [comment]
> 
> 
> It seem continue doing his job now:
> `lotus sync wait`
> Worker 0: Target: [bafy2bzacebwzl4z7rzqm472ufqsijvnzpzfypphpfau4pryj5ghz3cvwj3rra bafy2bzacea6gzplydy2dwu532skvasatoqzakui5vtmi3callo3rwf3y7lxoc] State: message sync Height: 8806

hi, what did you do to make it normal again, can you tell me plz?

**Comment by flyworker** [comment]
> > It seem continue doing his job now:
> > `lotus sync wait`
> > Worker 0: Target: [bafy2bzacebwzl4z7rzqm472ufqsijvnzpzfypphpfau4pryj5ghz3cvwj3rra bafy2bzacea6gzplydy2dwu532skvasatoqzakui5vtmi3callo3rwf3y7lxoc] State: message sync Height: 8806
> 
> hi, what did you do to make it normal again, can you tell me plz?

I did it as Bob suggested.
```

lotus chain sethead --epoch 6000
[restart the daemon]
lotus sync mark-bad bafy2bzaceczr24uhkj3mn3lilxbco7xq3ds4ifjv2lhvhcmqay76hzo3pzp3i

```

**Comment by metalsnail** [comment]
> 
> 
> > > It seem continue doing his job now:
> > > `lotus sync wait`
> > > Worker 0: Target: [bafy2bzacebwzl4z7rzqm472ufqsijvnzpzfypphpfau4pryj5ghz3cvwj3rra bafy2bzacea6gzplydy2dwu532skvasatoqzakui5vtmi3callo3rwf3y7lxoc] State: message sync Height: 8806
> > 
> > 
> > hi, what did you do to make it normal again, can you tell me plz?
> 
> I did it as Bob suggested.
> 
> ```
> 
> lotus chain sethead --epoch 6000
> [restart the daemon]
> lotus sync mark-bad bafy2bzaceczr24uhkj3mn3lilxbco7xq3ds4ifjv2lhvhcmqay76hzo3pzp3i
> ```

thanks. but could you explain what happend and the meaning of those commands?
tks again!

**Comment by flyworker** [comment]
> > > > It seem continue doing his job now:
> > > > `lotus sync wait`
> > > > Worker 0: Target: [bafy2bzacebwzl4z7rzqm472ufqsijvnzpzfypphpfau4pryj5ghz3cvwj3rra bafy2bzacea6gzplydy2dwu532skvasatoqzakui5vtmi3callo3rwf3y7lxoc] State: message sync Height: 8806
> > > 
> > > 
> > > hi, what did you do to make it normal again, can you tell me plz?
> > 
> > 
> > I did it as Bob suggested.
> > ```
> > 
> > lotus chain sethead --epoch 6000
> > [restart the daemon]
> > lotus sync mark-bad bafy2bzaceczr24uhkj3mn3lilxbco7xq3ds4ifjv2lhvhcmqay76hzo3pzp3i
> > ```
> 
> thanks. but could you explain what happend and the meaning of those commands?
> tks again!

It will set the sync up from height 6000
then you manual set the bad harsh you want to abandon.

**Comment by metalsnail** [comment]
> 
> 
> > > > > It seem continue doing his job now:
> > > > > `lotus sync wait`
> > > > > Worker 0: Target: [bafy2bzacebwzl4z7rzqm472ufqsijvnzpzfypphpfau4pryj5ghz3cvwj3rra bafy2bzacea6gzplydy2dwu532skvasatoqzakui5vtmi3callo3rwf3y7lxoc] State: message sync Height: 8806
> > > > 
> > > > 
> > > > hi, what did you do to make it normal again, can you tell me plz?
> > > 
> > > 
> > > I did it as Bob suggested.
> > > ```
> > > 
> > > lotus chain sethead --epoch 6000
> > > [restart the daemon]
> > > lotus sync mark-bad bafy2bzaceczr24uhkj3mn3lilxbco7xq3ds4ifjv2lhvhcmqay76hzo3pzp3i
> > > ```
> > 
> > 
> > thanks. but could you explain what happend and the meaning of those commands?
> > tks again!
> 
> It will set the sync up from height 6000
> then you manual set the bad hash you want to abandon.

i did set the abandon hash, and run 'lotus sync wait' again, but it is still shows ; State: error

what should i do ?

thanks

**Comment by flyworker** [comment]
> > > > > > It seem continue doing his job now:
> > > > > > `lotus sync wait`
> > > > > > Worker 0: Target: [bafy2bzacebwzl4z7rzqm472ufqsijvnzpzfypphpfau4pryj5ghz3cvwj3rra bafy2bzacea6gzplydy2dwu532skvasatoqzakui5vtmi3callo3rwf3y7lxoc] State: message sync Height: 8806
> > > > > 
> > > > > 
> > > > > hi, what did you do to make it normal again, can you tell me plz?
> > > > 
> > > > 
> > > > I did it as Bob suggested.
> > > > ```
> > > > 
> > > > lotus chain sethead --epoch 6000
> > > > [restart the daemon]
> > > > lotus sync mark-bad bafy2bzaceczr24uhkj3mn3lilxbco7xq3ds4ifjv2lhvhcmqay76hzo3pzp3i
> > > > ```
> > > 
> > > 
> > > thanks. but could you explain what happend and the meaning of those commands?
> > > tks again!
> > 
> > 
> > It will set the sync up from height 6000
> > then you manual set the bad hash you want to abandon.
> 
> i did set the abandon hash, and run 'lotus sync wait' again, but it is still shows ; State: error
> 
> what should i do ?
> 
> thanks

I wait 1 hour then it works.

**Comment by metalsnail** [comment]
> 
> 
> > > > > > > It seem continue doing his job now:
> > > > > > > `lotus sync wait`
> > > > > > > Worker 0: Target: [bafy2bzacebwzl4z7rzqm472ufqsijvnzpzfypphpfau4pryj5ghz3cvwj3rra bafy2bzacea6gzplydy2dwu532skvasatoqzakui5vtmi3callo3rwf3y7lxoc] State: message sync Height: 8806
> > > > > > 
> > > > > > 
> > > > > > hi, what did you do to make it normal again, can you tell me plz?
> > > > > 
> > > > > 
> > > > > I did it as Bob suggested.
> > > > > ```
> > > > > 
> > > > > lotus chain sethead --epoch 6000
> > > > > [restart the daemon]
> > > > > lotus sync mark-bad bafy2bzaceczr24uhkj3mn3lilxbco7xq3ds4ifjv2lhvhcmqay76hzo3pzp3i
> > > > > ```
> > > > 
> > > > 
> > > > thanks. but could you explain what happend and the meaning of those commands?
> > > > tks again!
> > > 
> > > 
> > > It will set the sync up from height 6000
> > > then you manual set the bad hash you want to abandon.
> > 
> > 
> > i did set the abandon hash, and run 'lotus sync wait' again, but it is still shows ; State: error
> > what should i do ?
> > thanks
> 
> I wait 1 hour then it works.

didn't think will like this...i reinstalled lotus and syncing now....>_<!

thanks for ur reply.

**Comment by arajasek** [comment]
The issue itself might have been some nondeterminism in specs-actors. Since fixed!

**Comment by jennijuju** [comment]
reopening this issue since being reported a lot with 0.7.1 & 2

**Comment by wsczj** [comment]
I have the same problem, version 0.7.1, how can I deal with it...

**Comment by arajasek** [comment]
Two `chain linked to block marked previously as bad` failures are almost never related, unless it is the same block in question. I don't think there's any value in this issue, but we definitely should treat new state root mismatch issues as a high priority concern.

**Comment by 459047874** [comment]
2020-12-18T14:39:44.213+0800	ERROR	chain	chain/sync_manager.go:424	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /root/lotus/chain/sync.go:580
  - chain contained block marked previously as bad ([bafy2bzacedszhkmtmsp7nip7gwi4bffjimlssn7xha5swp327uzw73odi3xe4], bafy2bzacedtfmqdixcwdz4wyq3vawzf3owant3s2xvq7psdv6id3qbx6aaavi) (reason: change contained bafy2bzaceauolyag7gkku4vlrb2h6vwmfv5h4fmx2zd4ucsrazu7xo7d5wu6c caused by: [bafy2bzacec7frdjj24mvhpu5dookfhrj6rw57opxqjkmhfji2u5wmzycnczhk] fork past finality):
    github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
        /root/lotus/chain/sync.go:1386

How can this be resolved？

**Comment by cmartins88** [comment]
I started having this problem in the calibration network after restarting the server. I've done everything I read on the internet, but I've been trying to solve this for 3 days.  Does anyone have any tips they could give me?  Sometimes the daemon even starts loading blocks well, and sometimes the error is right at the beginning...it seems to be more of a network problem than software...at this point I'm already at version 1.10.1.  thanks
