### ISSUE TITLE
GetRandomness uses VRF chain instead of drand entries

### ISSUE THREAD

**Issue by nikkolasg** [filecoin-project/lotus#2148]
**Describe the bug**
For almost all purposes of drawing randomness in Filecoin, the spec [indicates](https://github.com/filecoin-project/specs/blob/48a87f09b7828a48a633ed772ea11452d98affce/src/algorithms/crypto/randomness.md#forming-randomness-seeds) to use the beacon entries as the basis to form the seed.

However, as noted [here](https://github.com/filecoin-project/research-private/issues/262), the `chain.GetRandomness` uses the `VRFProof` as its basis. From the spec, this should only be the case when using `Seal PreCommit`.

**Expected behavior**

Lotus should use the drand signature of the timestamp corresponding to the epoch requested. There are two ways to do that: either by doing a "blocking" call to fetch from a cache, or from the drand network, OR via looking at the chain. 
In the latter case, one must be careful of a potential vulnerability as described in this [issue](https://github.com/filecoin-project/research-private/issues/217).

There should ALSO be a `GetRandomnessFromVRFChain` to use for `SealPreCommit` (available to the VM probably as well?)

**Comment by anorth** [comment]
This probably requires a change to the actors runtime API, since the pre-commit seed is just one of the randomness calls made from actors.

**Comment by nikkolasg** [comment]
More of an addition rather than a change to the API I guess ? 
* `GetDrandRandomness`
* `GetVRFRandomness`

**Comment by whyrusleeping** [comment]
GetRandomness is used for PoRep and PoSts, and uses the ticket chain for randomness for these. If we don't do this, and use drand for the randomness there, then storage becomes replayable across forks, and filecoin becomes susceptible to long range attacks, and forking also becomes much easier (I can increase the apparent storage on my fork by simply including messages from other miners)

**Comment by nicola** [comment]
This is solved.
