### ISSUE TITLE
Lotus Tutorial steps force GO 1.13 install. Make requires 1.14

### ISSUE THREAD

**Issue by Luckst4r** [filecoin-project/lotus#2166]
**Describe the bug**
https://docs.lotu.sh/en+install-lotus-ubuntu

When the site describes initial dependencies install, the steps install 1.13.8.

The make file requires 1.14.

**Comment by RobQuistNL** [comment]
This was already fixed: https://github.com/filecoin-project/lotus/pull/1970 the new documentation just needs to be deployed
