### ISSUE TITLE
ERROR	miner	miner/miner.go:159	mining block failed: failed to get mining base info

### ISSUE THREAD

**Issue by chengwds** [filecoin-project/lotus#2167]
2020-06-29T11:50:44.082+0800	ERROR	miner	miner/miner.go:159	mining block failed: failed to get mining base info:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /root/lotus/miner/miner.go:263
  - beacon entry request returned error: drand failed Get request: Get https://pl-sin.testnet.drand.sh/public/118298: dial tcp: lookup pl-sin.testnet.drand.sh: invalid argument
2020-06-29T11:50:45.089+0800	ERROR	miner	miner/miner.go:159	mining block failed: failed to get mining base info:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /root/lotus/miner/miner.go:263
  - beacon entry request returned error: drand failed Get request: Get https://pl-sin.testnet.drand.sh/public/118298: dial tcp: lookup pl-sin.testnet.drand.sh: invalid argument

**Comment by Kubuxu** [comment]
What system are you running it on?

**Comment by chengwds** [comment]
xubuntu-20.04

**Comment by chengwds** [comment]
It's much easier to use than Ubuntu

**Comment by magik6k** [comment]
Please reopen if this still happens with latest master
