### ISSUE TITLE
how do  i make an api transfer accounts ？

### ISSUE THREAD

**Issue by wangbb-aaa** [filecoin-project/lotus#2173]
I know example， command line use      lotus wallet send addr amonut,
but  I donot know  use api params  for transfer,

EXAMPLE ：
1,WalletSign(context.Context, address.Address, []byte) (*crypto.Signature, error)  ？

2,PaychNewPayment(ctx context.Context, from, to address.Address, vouchers []VoucherSpec) (*PaymentInfo, error)  ？

curl -X POST      -H "Content-Type: application/json"      --data '{ "jsonrpc": "2.0", "method": "Filecoin.WalletSign", "params": ["t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq", 1], "id": 3 }'      'http://127.0.0.1:1234/rpc/v0'   ？？？

Can you give an example of the transfer steps and how to transfer the reference ？

thanks

**Comment by arajasek** [comment]
You'll first need to assemble the `Message` object:
```
{
	From:     fromAddr,
	To:       toAddr,
	Value:    val,
	GasLimit: limit,
	GasPrice: gp,
}
```

Then `WalletSign` and `MPoolPush` are the methods you'll need.

**Comment by wangbb-aaa** [comment]
Or not. Can you give me an example?
curl -X POST      -H "Content-Type: application/json"      --data '{ "jsonrpc": "2.0", "method": "Filecoin.WalletSignMessage", "params": ["t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq",[{"t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq","t1zct4qcmhxntze3ckn6alrhop2kgbuane4dpceoq",10,1,2}]], "id": 3 }'      'http://127.0.0.1:1234/rpc/v0'


curl -X POST      -H "Content-Type: application/json"      --data '{ "jsonrpc": "2.0", "method": "Filecoin.WalletSignMessage", "params": ["t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq",[{"From":"t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq","To":"t1zct4qcmhxntze3ckn6alrhop2kgbuane4dpceoq","Value":10,"GasLimit":1,"GasPrice":2}]], "id": 3 }'      'http://127.0.0.1:1234/rpc/v0'

**Comment by wangbb-aaa** [comment]
Or not. Can you give me an example?

curl -X POST      -H "Content-Type: application/json"      --data '{ "jsonrpc": "2.0", "method": "Filecoin.WalletSignMessage", "params": ["t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq",[{"t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq","t1zct4qcmhxntze3ckn6alrhop2kgbuane4dpceoq",10,1,2}]], "id": 3 }'      'http://127.0.0.1:1234/rpc/v0'


curl -X POST      -H "Content-Type: application/json"      --data '{ "jsonrpc": "2.0", "method": "Filecoin.WalletSignMessage", "params": ["t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq",[{"From":"t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq","To":"t1zct4qcmhxntze3ckn6alrhop2kgbuane4dpceoq","Value":10,"GasLimit":1,"GasPrice":2}]], "id": 3 }'      'http://127.0.0.1:1234/rpc/v0'
