### ISSUE TITLE
heightEvents locking

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/lotus#2174]
In `heightEvents` we unlock and then relock whenever we call the `HeightHandler` or `RevertHandler`. I believe this could cause issues if one thread calls `ChainAt()` and another thread calls `headChangeAt()` at the same time.

For example
- `headChangeAt()` unlocks then relocks while iterating over `e.htTriggerHeights`
- `ChainAt()` modifies `e.htTriggerHeights`

I'd suggest either
- Don't unlock / relock when calling callbacks
- If we're concerned about these callbacks being slow, call them in a go-routine

**Comment by dirkmc** [comment]
CC @magik6k @hannahhoward

**Comment by hunjixin** [comment]
@dirkmc which locker ,name ?

**Comment by jennijuju** [comment]
@dirkmc is this still needed or it can be closed?
