### ISSUE TITLE
runtime error when initiating miner

### ISSUE THREAD

**Issue by Luckst4r** [filecoin-project/lotus#2180]
**Describe the bug**

- Node is fully sync'd
- Daemon running

When i run `lotus-storage-miner run` it downloaded all the necessary proofs etc. and then throws a runtime error

`panic: runtime error: invalid memory address or nil pointer deference
signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11723d2
goroutine 241 (running)`
and then continues to barf some github links

**Comment by RobQuistNL** [comment]
You might be on an old version, can you drop the `lotus --version` output here? I suppose you have this bug, which was just fixed: https://github.com/filecoin-project/lotus/issues/2164

**Comment by Luckst4r** [comment]
> You might be on an old version, can you drop the `lotus --version` output here? I suppose you have this bug, which was just fixed: #2164

`lotus version 0.4.0+git.fbfe57cd`

**Comment by yu-val-cho** [comment]
@Luckst4r
 
how did u solve it? we r in china, with lots of issues. but right now stuck at the same place with the same error. did update to latest lotus?
