### ISSUE TITLE
lotus同步节点慢的问题

### ISSUE THREAD

**Issue by yzn5555** [filecoin-project/lotus#2181]
使用云服务器配置4核8G内存在同步期间总会出现内存溢出，就把配置改为4核16G了，磁盘之前使用普通的磁盘，发现磁盘IO跟不上就更换为高效云盘，3000IOPS的磁盘，发现只有在追最新块的时候才需要对磁盘大量的读写操作，就这样同步还是有点慢，和使用固态磁盘相比同步速度慢了将近12个小时，我想问下，内存还有大量的空余，能不能合理使用内存剩余空间，把数据缓存到内存中，这样就能避免实时往磁盘中写入大量操作，减少磁盘IO

**Comment by arajasek** [comment]
I don't know what this says :(
