### ISSUE TITLE
lotus-storage-miner init failed

### ISSUE THREAD

**Issue by kraymond37** [filecoin-project/lotus#2182]
lotus-storage-miner init --actor=t0118560 --owner=t3vp7lgbjnjud6s753onun4behyirkcttqe5ce5btr4e23kzpawb763escwdjxfga75d6rwgxd4gozucaeaanq
```
2020-06-30T13:40:12.164+0800	WARN	main	lotus-storage-miner/main.go:82	fetching proof parameters:
    main.glob..func2
        /home/circleci/project/cmd/lotus-storage-miner/init.go:133
  - the following errors occurred:
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.params failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.params, 0f7030d34e4cab38e9212920a6ea2434 != c909ea9e3fe25ab9b391a64593afdbba:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.params failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.params, 275a086e6b964e7f24438caba1602700 != a2844f0703f186d143a06146a04577d8:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.params failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.params, 839eb490bce7088213d8a1127438cdb0 != a16d6f4c6424fb280236739f84b24f97:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
```
lotus-storage-miner version 0.4.0+git.ffa7be86

**Comment by panol** [comment]
OS:ubuntu

interopnet

lotus repo tag interop.6.16.0 

After I lotus synced ,run 

`export IPFS_GATEWAY="https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/" `
`lotus-storage-miner init --actor=t05650 --owner=t3ux5htvjogrj3zzvxtrmgj5u6zyqhfq7girofxby5irk6fh6phchdzsbliywmvxzb5gxyltbxbmrinffo5bwq`

2020-07-02T11:13:20.465+0800	INFO	build	go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:158	Fetching /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0cfb4f178bbb71cf2ecfcd42accce558b27199ab4fb59cb78f2483fe21ef36d9.params from https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/
2020-07-02T11:13:20.465+0800	INFO	build	go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:176	GET https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/QmUeNKp9YZpiAFm81RV5KuxH1FDGJx2DuwcbU2XNSZLLSv
 322 B / ? [-----------------------------------------------------------------------------------------------=----------------------------------------------------------------------------------------------------------------]   3.22% 481.04 KiB/s 0s
2020-07-02T11:13:20.635+0800	INFO	build	go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:147	parameter and key-fetching complete
2020-07-02T11:13:20.636+0800	WARN	main	lotus-storage-miner/main.go:83	fetching proof parameters:
    main.glob..func2
        /root/develop/lotus/cmd/lotus-storage-miner/init.go:133
  - the following errors occurred:
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.vk, 9f38885048fa69ef09e2c543745b36e6 != caf900461e988bbf86dbcaca087b7864:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0cfb4f178bbb71cf2ecfcd42accce558b27199ab4fb59cb78f2483fe21ef36d9.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0cfb4f178bbb71cf2ecfcd42accce558b27199ab4fb59cb78f2483fe21ef36d9.vk, 31fdd577a2df78174c44d0a620191dfe != 3688c9eb256b7b17f411dad78d5ef74a:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-50c7368dea9593ed0989e70974d28024efa9d156d585b7eea1be22b2e753f331.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-50c7368dea9593ed0989e70974d28024efa9d156d585b7eea1be22b2e753f331.vk, 3db6bdfd85c97637a23bf4748ad326e1 != 94b6c24ac01924f4feeecedd16b5d77d:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-032d3138d22506ec0082ed72b2dcba18df18477904e35bafee82b3793b06832f.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-032d3138d22506ec0082ed72b2dcba18df18477904e35bafee82b3793b06832f.vk, cd00c0edcd1584d9822df99e2960b63a != fb59bd061c987eac7068008c44de346b:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0170db1f394b35d995252228ee359194b13199d259380541dc529fb0099096b0.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0170db1f394b35d995252228ee359194b13199d259380541dc529fb0099096b0.vk, f5d26718c05efc7319c7cefc898c56b2 != 398fecdb4b2de445125852bc3c080b35:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-ecd683648512ab1765faa2a5f14bab48f676e633467f0aa8aad4b55dcb0652bb.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-ecd683648512ab1765faa2a5f14bab48f676e633467f0aa8aad4b55dcb0652bb.vk, 0b4104d3a13acd025c105779a670b1a3 != ec62d59651daa5631d3d1e9c782dd940:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-2-sha256_hasher-96f1b4a04c5c51e4759bbf224bbc2ef5a42c7100f16ec0637123f16a845ddfb2.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-2-sha256_hasher-96f1b4a04c5c51e4759bbf224bbc2ef5a42c7100f16ec0637123f16a845ddfb2.vk, 65235bdc9fdb9f3db641e5755152bc36 != 62c366405404e60f171e661492740b1c:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-7d739b8cf60f1b0709eeebee7730e297683552e4b69cab6984ec0285663c5781.params failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-7d739b8cf60f1b0709eeebee7730e297683552e4b69cab6984ec0285663c5781.params, ce83d6645bbf28c2bda644b4fdf3cf58 != 7e6b2eb5ecbb11ac651ad66ebbb2075a:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-6babf46ce344ae495d558e7770a585b2382d54f225af8ed0397b8be7c3fcd472.params failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-6babf46ce344ae495d558e7770a585b2382d54f225af8ed0397b8be7c3fcd472.params, a00038c49948a107b974ad74c24499d4 != 36d465915b0afbf96bd08e7915e00952:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-3ea05428c9d11689f23529cde32fd30aabd50f7d2c93657c1d3650bca3e8ea9e.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-3ea05428c9d11689f23529cde32fd30aabd50f7d2c93657c1d3650bca3e8ea9e.vk, e6fe72ceacae1fd2ca42018a2126b143 != 142f2f7e8f1b1779290315cabfd2c803:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-7d739b8cf60f1b0709eeebee7730e297683552e4b69cab6984ec0285663c5781.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-7d739b8cf60f1b0709eeebee7730e297683552e4b69cab6984ec0285663c5781.vk, 1bd993fd30221f9110db367b005dfc1d != 94a8d9e25a9ab9674d339833664eba25:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-6babf46ce344ae495d558e7770a585b2382d54f225af8ed0397b8be7c3fcd472.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-6babf46ce344ae495d558e7770a585b2382d54f225af8ed0397b8be7c3fcd472.vk, 9b40c4cd625659b6fb756d5336d51c45 != 99d16df0eb6a7e227a4f4570c4f6b6f1:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk, a1cb568b7a49555e588600f907d93a1f != 7a139d82b8a02e35279d657e197f5c1f:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-2627e4006b67f99cef990c0a47d5426cb7ab0a0ad58fc1061547bf2d28b09def.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-2627e4006b67f99cef990c0a47d5426cb7ab0a0ad58fc1061547bf2d28b09def.vk, 5a223693d5107de0aa720125a389e995 != 0c9c423b28b1455fcbc329a1045fd4dd:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-5294475db5237a2e83c3e52fd6c2b03859a1831d45ed08c4f35dbf9a803165a9.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-5294475db5237a2e83c3e52fd6c2b03859a1831d45ed08c4f35dbf9a803165a9.vk, dba65db00565599573f0add1ac815332 != 56ae47bfda53bb8d22981ed8d8d27d72:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.vk, db0060b04fde2dbf40a2a58d1c535b02 != 2306247a1e616dbe07f01b88196c2044:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-b62098629d07946e9028127e70295ed996fe3ed25b0f9f88eb610a0ab4385a3c.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-b62098629d07946e9028127e70295ed996fe3ed25b0f9f88eb610a0ab4385a3c.vk, 144e9e1148e63b00b8d4347d180182eb != fc8c3d26e0e56373ad96cb41520d55a6:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0cfb4f178bbb71cf2ecfcd42accce558b27199ab4fb59cb78f2483fe21ef36d9.params failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0cfb4f178bbb71cf2ecfcd42accce558b27199ab4fb59cb78f2483fe21ef36d9.params, 7e66beeb8895e8dbd83f61564d79afc5 != 2b6d2972ac9e862e8134d98fb695b0c5:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132

I can't find any solution to the error yet.

**Comment by noprom** [comment]
@kraymond37 Same problem here.

**Comment by noprom** [comment]
Logs
```
2020-07-03T21:08:49.928+0800    INFO    build   go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:158    Fetching /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.params from https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/
2020-07-03T21:08:49.928+0800    INFO    build   go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:176    GET https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/QmY5yax1E9KymBnCeHksE9Zi8NieZbmwcpoDGoabkeeb9h
 322 B / ? [-------------------------------------------------------------------------------=------------------------------------------------------------------------------------------------------------------------]   3.22% 1.58 MiB/s 0s
2020-07-03T21:08:50.321+0800    INFO    build   go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:128    Parameter file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.params is ok
2020-07-03T21:08:50.322+0800    INFO    build   go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:147    parameter and key-fetching complete
2020-07-03T21:08:50.322+0800    WARN    main    lotus-storage-miner/main.go:84  fetching proof parameters:
    main.glob..func3
        /data2/filecoin/lotus/cmd/lotus-storage-miner/init.go:133
  - the following errors occurred:
     -  checking file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.params failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.params, b2240eeeb334535e317a8e9ec0d022b0 != a16d6f4c6424fb280236739f84b24f97:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.params failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:99
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.params, 716f901b165a034609e1eb38e172d890 != c909ea9e3fe25ab9b391a64593afdbba:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200605171344-fcac609550ca/paramfetch.go:132
```

**Comment by panol** [comment]
京东云下载的filecoin-proof-parameters有问题。

**Comment by kraymond37** [comment]
> 京东云下载的filecoin-proof-parameters有问题。

是的, 还是要翻墙下载

**Comment by arajasek** [comment]
Please open a fresh issue if similar problems arise!
