### ISSUE TITLE
ChainStore heaviestLk deadlock

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/lotus#2183]
Describe:
Anything related to heaviestLk cannot be executed.more likely to appear when the lotus network fluctuates.
$  ./lotus chain head
will always wait ...

func (cs *ChainStore) SetHead(ts *types.TipSet) error {
	cs.heaviestLk.Lock()
	defer cs.heaviestLk.Unlock()
	return cs.takeHeaviestTipSet(context.TODO(), ts)
}

Version: 0.4.0 branch:master

**Comment by hunjixin** [comment]
https://github.com/filecoin-project/lotus/pull/2211

**Comment by jennijuju** [comment]
closed by https://github.com/filecoin-project/lotus/pull/6526
