### ISSUE TITLE
lotus paych get never puts an entry in lotus paych list

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/lotus#2194]
**Describe the bug**

`lotus paych get <from> <to> <amount>` never results in a payment channel later appearing in `lotus paych list`, even after waiting 6 hours.

```
$ lotus wallet new
t1fbuuo6fz4yd5codj73gvqmirpavl77wflmbm37q  # <-- add 50 FIL to this one
$ lotus wallet new
t1vnc3ozfdlh5hh2garrzxvfzt7syzjg7azn5octq
$ lotus paych get t1fbuuo6fz4yd5codj73gvqmirpavl77wflmbm37q t1vnc3ozfdlh5hh2garrzxvfzt7syzjg7azn5octq 10
<empty>
```
(wait 30 minutes)
```
$ lotus paych list
$
```
(wait 6 hours)
```
$ lotus paych list
$
```

**To Reproduce**
Steps to reproduce the behavior: (above)

**Expected behavior**
Since the handlers for `lotus paych get` spawn a go routine for `waitForPaychCreateMsg()` or `waitForAddFundsMsg()`, both of which update the payment channel manager's state, I would expect that after a time delay of a few new tipsets, I would see the new payment channel in `lotus paych list`.  But nothing ever appears in the list.

**Version (run `lotus --version`):**
```
$ lotus version
Daemon:  0.4.0+git.a0e1d5f5.dirty+api0.5.0
Local: lotus version 0.4.0+git.a0e1d5f5.dirty
```

**Additional context**
Every time I run `lotus paych go` I see this in the logs:

```
2020-06-30T19:02:21.360Z        ^[[33mWARN^[[0m chainstore      store/store.go:656     unexpected error getting unsigned message: 'cbor input had wrong number of fields'
2020-06-30T19:02:21.360Z        ^[[33mWARN^[[0m chainstore      store/store.go:208      chain head sub exit loop
```

The errors are coming from [GetCMessage() in chain/store.go](https://github.com/filecoin-project/lotus/blob/master/chain/store/store.go#L646).  The return value of GetMessage() is bad.

**Additional context**
This is similar to, but not the same as, #2187.  I opened it as a separate issue because the root causes are not the same.

**Comment by hoffmabc** [comment]
@mgoelzer you mentioned running 

`Every time I run lotus paych go I see this in the logs:`

I don't see where `lotus paych go` is an option. Was this removed or is this a typo?

**Comment by dirkmc** [comment]
Closing as this issue should now be fixed

**Comment by mgoelzer** [comment]
I meant to type `lotus paych get` (not go).  But yes, I agree the problem seems to be resolved and its fine to close this.
