### ISSUE TITLE
`lotus client deal` can specify fast retrieval

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#2196]
As a lotus user, I would like to be able to specify whether I am requesting fast retrieval for my deal, so I can retrieve my data faster

Tasks:
- Add FastRetrieval bool to StartDealParams
- Pass FastRetrieval bool to ProposeStorageDeal in ClientStartDeal API
- Add command line flag to `lotus client deal` command (optional) to specify fast retrieval
- Default is yes for now

Caveats:
- Fast retrieval is exposed on the interface but NOT implemented in markets (or storage miner), which means we cannot test end to end

**Comment by magik6k** [comment]
Related PR in now merged \o/
