### ISSUE TITLE
`lotus client deal` can specify verified deal

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#2197]
As a lotus user, I would like to be able to specify that I'm requesting my storage deal be counted towards my verified client total, so the miner will be paid as such

Tasks:

Add VerifiedDeal bool to StartDealParams
Pass VerifiedDeal bool to ProposeStorageDeal in ClientStartDeal API
Add command line flag to lotus client deal command (optional) to specify verified deal
Default is yes for No

Caveats:

Verified Deal is exposed on the interface but NOT implemented in markets (or storage miner)

**Comment by magik6k** [comment]
Related PR in now merged \o/
