### ISSUE TITLE
Verifying WinningPoSt proofs is very expensive

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#2201]
When verifying winning post proofs, we enumerate the miners entire sector set, sans recoveries and faults, and then generates challenges (which requires the length of the sector set post filtering to compute), and then select the sectors from the sector set using the generated challenges.

This is extremely wasteful as we enumerate miners *entire* sector set (except for the faults and recoveries, which is normally zero) is loaded into memory, and then we pick the single sector from that set that we need to verify the challenge.

Fixing this is tricky because the challenge depend on the total number of sectors in the filtered set, and the challenge selects a sector positionally (not by sector ID, but by index within the filtered set).

One potential solution (that is described in a comment in the offending code) is to implement a filtered AMT traversal, that returns the 'Nth' item. This unfortunately still traverses most of the AMT, and is likely to still be rather expensive. Maybe theres no way around this?

**Comment by Kubuxu** [comment]
A solution might be to keep a bitfield of active sectors and implement `N-th` element lookup for bitfields.

**Comment by Stebalien** [comment]
> A solution might be to keep a bitfield of active sectors and implement N-th element lookup for bitfields.

This should already be possible. We should be able to subtract `Miner.Faults` from `Miner.Sectors`, then `Slice(nth, 1)`, then get the first element. That will give us the nth non-faulty sector.

**Comment by whyrusleeping** [comment]
@Stebalien no, because `miner.Sectors` is an AMT

**Comment by Stebalien** [comment]
Yeah, you're right. At the moment, we'd need to run:

```go
bf := bitfield.MultiMerge(append([]*bitfield.BitField{miner.NewSectors}, deadlines.Due...))
bf = bitfield.SubtractBitField(bf, miner.Faults)
bf = bf.Slice(nth, 1)
sectorNo := bf.First()
```

**Comment by anorth** [comment]
You could build up the set of sectors from the union of deadline proving sets, then subtract faults

**Comment by whyrusleeping** [comment]
@anorth Aha! That should do the trick, i'll give it a shot

**Comment by anorth** [comment]
Note: I do not think you should add `NewSectors` to the set. While currently those sectors have power, we'd generally prefer them not to (https://github.com/filecoin-project/specs-actors/issues/549). If you leave them out of the winning post for now, we won't have to coordinate if/when we delay their power.

This means a miner won't win a block until after PP starts, though (unless we do more, currently unplanned work, to allow earlier assignment to proving deadlines).

**Comment by Stebalien** [comment]
Skipping them in this calculation won't be sufficient, we'd need to avoid adding power to the power actor to make that chane.

**Comment by magik6k** [comment]
Merged in https://github.com/filecoin-project/lotus/pull/2209
