### ISSUE TITLE
Intermittent failures when running P2 and C2 with 2070SUPER GPU

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/lotus#2203]
**Describe the bug**
Intermittent failures when running P2 and C2 with `2070SUPER` GPU. 
About one-third of the failure rate

**Run Script**

```bash
lotus-seal-worker/lotus-seal-worker --workerrepo=/gamma/lotus-seal-worker/data \
--storagerepo=/gamma/lotus-seal-worker/storage run \
--address=192.168.1.102:2345 --precommit1=true --precommit2=true --commit=true
```

**Screenshots**

![image](https://user-images.githubusercontent.com/4746061/86194945-600f9d00-bb82-11ea-9bb7-fac3ea6d4469.png)

```bash
2020-06-30T12:37:46.066 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error:

################################ OPENCL ERROR ###############################

Error executing function: clEnqueueNDRangeKernel("radix_fft")

Status error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors

#############################################################################

2020-06-30T12:39:16.381 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error:

################################ OPENCL ERROR ###############################

Error executing function: clEnqueueNDRangeKernel("radix_fft")

Status error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors

#############################################################################

2020-06-30T12:40:06.164 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error:

################################ OPENCL ERROR ###############################

Error executing function: clEnqueueNDRangeKernel("radix_fft")

Status error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors

```

**Version (run `lotus --version`):**
0.4.0+git.ffa7be86

**Additional context**

My machine configure.

* CPU: AMD 3950x
* RAM: 128GB
* Swap: 128GB
* GPU: NVIDIA RTX 2070SUPER

**Comment by RobQuistNL** [comment]
I have the same GPU, and the same error messages - but from what I've been told, the messages are normal and are OK. The system does also still work, even with the error messages.

I do agree - would be nicer without them :)

**Comment by duxiaobai** [comment]
Meet the same problem with  NVIDIA RTX 2080 SUPER.

**Comment by kernelogic** [comment]
Same error on 1060 3GB

**Comment by callmestu** [comment]
Same issue here on an Nvidia Tesla K80 on AMD Threadripper 1900x 256GB RAM system. 


It is definitely using 1600% of CPU in top, but no GPU in nvidia-smi:


![image](https://user-images.githubusercontent.com/30323609/92692973-f2ff4d00-f312-11ea-9c5b-ea39ee4424f4.png)


`#############################################################################

2020-09-10T07:00:51.681 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error:

################################ OPENCL ERROR ###############################

Error executing function: clEnqueueWriteBuffer

Status error code: CL_OUT_OF_RESOURCES (-5)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueWriteBuffer.html#errors

#############################################################################

2020-09-10T07:01:24.983 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error:

################################ OPENCL ERROR ###############################

Error executing function: clEnqueueWriteBuffer

Status error code: CL_OUT_OF_RESOURCES (-5)

Please visit the following url for more information:

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueWriteBuffer.html#errors
`

**Comment by RobQuistNL** [comment]
@callmestu That (-5) is not the same error (-4)
