### ISSUE TITLE
Index out of range issue of lotus-storage-miner proving info

### ISSUE THREAD

**Issue by coder-lb** [filecoin-project/lotus#2204]
### Problems
This issue is related to https://github.com/filecoin-project/specs-actors/issues/569. After OnDeferredCronEvent  gets such an error, deadline index is 36. And then we can get proving info:
```
$ lotus-storage-miner proving info
panic: runtime error: index out of range [36] with length 36
```

### Possible Solutions
In lotus/cmd/lotus-storage-miner/proving.go (commit 24c7f47566c8e0e85e4611b0d50d620131767a74):
```
		deadlines, err := api.StateMinerDeadlines(ctx, maddr, head.Key())
		if err != nil {
			return xerrors.Errorf("getting miner deadlines: %w", err)
		}

		curDeadlineSectors, err := deadlines.Due[cd.Index].Count()
		if err != nil {
			return xerrors.Errorf("counting deadline sectors: %w", err)
		}
```
We can see deadlines.Due[cd.Index] will trigger out of range issue.

So we will change the code like this:

```
		deadlines, err := api.StateMinerDeadlines(ctx, maddr, head.Key())
		if err != nil || cd.Index >= (uint64(len(deadlines.Due))) {
			return xerrors.Errorf("getting miner deadlines: %w", err)
		}

		curDeadlineSectors, err := deadlines.Due[cd.Index].Count()
		if err != nil {
			return xerrors.Errorf("counting deadline sectors: %w", err)
		}
```

**Comment by hyunmoon** [comment]
Same issue here. [https://filecoinproject.slack.com/archives/CEGN061C5/p1593565514264800](url) I'll try your suggested solution and report back.

**Comment by hyunmoon** [comment]
Nope proving info and proving deadlines are still not working. I got 
WARN main main.go:84  getting miner deadlines: %!w(<nil>):

**Comment by Leozhang404** [comment]
possible reasons：
1. you have too many Faults sectors(>8192);
2. you restarts miner after one ProvingPeriod(I guess that handleProvingPeriod  has breakdown before set next periodStart) so you need not to submit WindowPost but keep power.

**Comment by Leozhang404** [comment]
> Same issue here. [https://filecoinproject.slack.com/archives/CEGN061C5/p1593565514264800](url). The suggested fix prevents panic-ing but I was hoping to figure out why my index is off and how I can correct it.

possible reasons：

you have too many Faults sectors(>8192);
you restarts miner after one ProvingPeriod(I guess that handleProvingPeriod has breakdown before set next periodStart) so you need not to submit WindowPost but keep power.

**Comment by magik6k** [comment]
This, and the underlying issue, was fixed
