### ISSUE TITLE
sudo make install error

### ISSUE THREAD

**Issue by renjun868** [filecoin-project/lotus#2207]
**Describe the bug**
Hi Pros, when I run the last step of lotus installation on ubuntu linux os, **sudo make install**, it shows 
- bash: go: command not found. 
   expr: syntax error
So, I check the **lotus version**, and it shows 
- WARN could not get API  info. 
Looking for the similar issue, but can't find the solution. Please help and thank you

**Screenshots**
<img width="990" alt="Screen Shot 2020-06-30 at 11 55 26 PM" src="https://user-images.githubusercontent.com/59547672/86201353-5576e880-bb2d-11ea-8268-0716030649be.png">

**Version (run `lotus --version`):**
ubuntu 18.04.4
lotus unknown 

**Additional context**
have checked the version of gcc bzr jq curl etc. They are the latest version. And have installed the latest version of go tool.

**Comment by leimao** [comment]
```
$ sudo make install
bash: go: command not found
expr: syntax error
install -C ./lotus /usr/local/bin/lotus
install -C ./lotus-storage-miner /usr/local/bin/lotus-storage-miner
install -C ./lotus-seal-worker /usr/local/bin/lotus-seal-worker
$ lotus --version
lotus version 0.4.1+git.e5fdae45
$ lotus
NAME:
   lotus - Filecoin decentralized storage network client
USAGE:
   lotus [global options] command [command options] [arguments...]
VERSION:
   0.4.1+git.e5fdae45
COMMANDS:
   daemon   Start a lotus daemon process
   version  Print version
   help, h  Shows a list of commands or help for one command
   basic:
     send    Send funds between accounts
     wallet  Manage wallet
     client  Make deals, store data, retrieve data
     msig    Interact with a multisig wallet
     paych   Manage payment channels
   developer:
     auth          Manage RPC permissions
     mpool         Manage message pool
     state         Interact with and query filecoin chain state
     chain         Interact with filecoin blockchain
     log           Manage logging
     wait-api      Wait for lotus api to come online
     fetch-params  Fetch proving parameters
   network:
     net   Manage P2P Network
     sync  Inspect or interact with the chain syncer
GLOBAL OPTIONS:
   --help, -h     show help (default: false)
   --version, -v  print the version (default: false)
```
This happens to me as well, but it seems that the lotus installation was successful. Since the installation is a black-box to me, I wonder what the consequence is for such error?

**Comment by renjun868** [comment]
I did the same thing which I skipped the error and joined the testnet anyway. So far it works. Thx for the replay.

**Comment by leimao** [comment]
@renjun868, I don't think it is a good idea to close this issue. After all, it is still a bug.

**Comment by RobQuistNL** [comment]
I'm guessing it happened right after installing `Go` and it is probably because the `go` executables are not in your path yet.

In your local user running `source ~/.profile` does the trick, and maybe when using `sudo` you should make sure that `go` is also in the `PATH` environment variable.

**Comment by leimao** [comment]
> I'm guessing it happened right after installing `Go` and it is probably because the `go` executables are not in your path yet.
> 
> In your local user running `source ~/.profile` does the trick, and maybe when using `sudo` you should make sure that `go` is also in the `PATH` environment variable.

I think I already appended the `PATH` to the `/etc/profile` and and `source` it. It did not work. But running the following command would still show that `go` can be found.

```
$ go version
```

Will try to append `PATH` to the `~/.profile` to see if it works or not.

**Comment by leimao** [comment]
> I'm guessing it happened right after installing `Go` and it is probably because the `go` executables are not in your path yet.
> 
> In your local user running `source ~/.profile` does the trick, and maybe when using `sudo` you should make sure that `go` is also in the `PATH` environment variable.

The problem still exists using exactly the same method you mentioned.

**Comment by RobQuistNL** [comment]
Yeah I looked at the make file and its pretty weid, the `make install` doesn't ever run `go`, it runs this;

```
install:
	install -C ./lotus /usr/local/bin/lotus
	install -C ./lotus-storage-miner /usr/local/bin/lotus-storage-miner
	install -C ./lotus-seal-worker /usr/local/bin/lotus-seal-worker
```

So I don't know where that error came from :thinking:

**Comment by kevinfreeman1101** [comment]
In my case, the `Go` install script from the Lotus instructions didn't add all the right locations to my path. Try:
```
$ whereis Go

go: /usr/local/go /usr/local/go/bin/go
```
Then make sure the printed directories are in your path (separate each directory with a `:`). I did this by adding them to `~/.bashrc` with:
```
echo "export PATH=/usr/local/go:/usr/local/go/bin/go" >> ~/.bashrc"
```
