### ISSUE TITLE
how do i make an api transfer accounts ？  thanks，

### ISSUE THREAD

**Issue by wangbb-aaa** [filecoin-project/lotus#2216]
I know example， command line use lotus wallet send addr amonut,
but I donot know use api params for transfer,

EXAMPLE ：
1，WalletSignMessage(context.Context, address.Address, *types.Message) (*types.SignedMessage, error)

{
	From:     fromAddr,
	To:       toAddr,
	Value:    val,
	GasLimit: limit,
	GasPrice: gp,
}
curl -X POST -H "Content-Type: application/json" --data '{ "jsonrpc": "2.0", "method": "Filecoin.WalletSignMessage", "params": ["t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq",[{"t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq","t1zct4qcmhxntze3ckn6alrhop2kgbuane4dpceoq",10,1,2}]], "id": 3 }' 'http://127.0.0.1:1234/rpc/v0'    ？？？

2,WalletSign(context.Context, address.Address, []byte) (*crypto.Signature, error) 

curl -X POST -H "Content-Type: application/json" --data '{ "jsonrpc": "2.0", "method": "Filecoin.WalletSign", "params": ["t1k5k5hzczwmjxctwojitmu4ai5a4naqyg3oghjdq", 1], "id": 3 }' 'http://127.0.0.1:1234/rpc/v0' ？？？

3，MpoolPush(context.Context, *types.SignedMessage) (cid.Cid, error) 
？？

Can you give an example of the transfer steps and how to transfer the reference ？
Detailed examples，

thanks，thanks，thanks，

**Comment by Wangmmx** [comment]
Is there any example you can refer to？online method is also availabledo you know how to generate an address, offline way

**Comment by magik6k** [comment]
Use `MpoolPushMessage`:
```
[
  {
    "To": "f01234",
    "From": "f01234",
    "Value": "0",
    "GasLimit": 0,
    "GasFeeCap": "0",
    "GasPremium": "0",
  },
  {
    "MaxFee": "0"
  }
]
```

**Comment by Shaikjani1994** [comment]
still not working

**Comment by Shaikjani1994** [comment]
tell me a library for failcoin api  npm which works properly
