### ISSUE TITLE
Is it necessary to run both miner and daemon together on the same machine?

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#2225]
Hello, as I don't see it being mentioned in the document. I wonder if it is necessary to run daemon while mining? I understand daemon is only for creating wallet address / send funds. It can be shutdown while running lotus-storage-miner?

I can for example have daemon running on a small machine and run miner on a mining machine without syncing the whole blockchain?

**Comment by magik6k** [comment]
`lotus-storage-miner` depends on `lotus daemon` for all interactions with the chain, so both need to be running

You can point the miner node to a full node on a separate machine by netting an env var - https://docs.lotu.sh/en+api-scripting-support

**Comment by kernelogic** [comment]
Thank you for your swift answer.
