### ISSUE TITLE
Execute cron for empty tipsets

### ISSUE THREAD

**Issue by anorth** [filecoin-project/lotus#2234]
I have filed https://github.com/filecoin-project/specs/issues/968 describing why we should consider executing cron for each empty tipset, in addition to the non-empty ones.

I'm filing this issue here because the essential work needs to happen in the Lotus VM in order for the actor code to be able to change take advantage of it (although the primary motivation is reducing errors, rather than optimizing code/state).

As discussed @whyrusleeping

**Comment by arajasek** [comment]
Closed in #2617
