### ISSUE TITLE
lotus daemon checksum mismatch in param file

### ISSUE THREAD

**Issue by panol** [filecoin-project/lotus#2237]
**Describe the bug**
Build lotus and then run lotus daemon,error occurs: checksum mismatch in param file

OS:Ubuntu 18.04
branch:master

export IPFS_GATEWAY="https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/"

**To Reproduce**
1. Run:
export IPFS_GATEWAY="https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/"

 lotus daemon

2. See error:
2020-07-02T17:23:49.531+0800    INFO    build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:173    Fetching /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-032d3138d22506ec0082ed72b2dcba18df18477904e35bafee82b3793b06832f.vk from https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/
2020-07-02T17:23:49.531+0800    INFO    build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:191    GET https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/QmNjvnvFP7KgovHUddULoB19fBHT81iz7NcUbzEHZUUPsm
 322 B / ? [-----------------------------------=----------------------------------------------------------------------------------------------------------------------------------------------]   3.22% 993.94 KiB/s 0s 
2020-07-02T17:23:49.675+0800    INFO    build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:162    parameter and key-fetching complete
2020-07-02T17:23:49.675+0800    WARN    main    lotus/main.go:81        fetching proof parameters:
    main.glob..func2
        /root/lotus/cmd/lotus/daemon.go:180
  - the following errors occurred:
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-2627e4006b67f99cef990c0a47d5426cb7ab0a0ad58fc1061547bf2d28b09def.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:102
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-2627e4006b67f99cef990c0a47d5426cb7ab0a0ad58fc1061547bf2d28b09def.vk, c532dfb151d6f077029369b589014830 != 0c9c423b28b1455fcbc329a1045fd4dd:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:147
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:102
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.vk, 6b4f138ea7b0ebd8f381f6ae005693a7 != 2306247a1e616dbe07f01b88196c2044:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:147
     -  checking file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:102
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk, 91eac4a902746538193c28fe904590c1 != 7a139d82b8a02e35279d657e197f5c1f:
            github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:147
     -  checking file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-3ea05428c9d11689f23529cde32fd30aabd50f7d2c93657c1d3650bca3e8ea9e.vk failed:
            github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
                /root/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:102
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-3ea05428c9d11689f23529cde32fd30aabd50f7d2c93657c1d3650bca3e8ea9e.vk, 0277c7b19160310475b7b21d8c42c7b9 != 142f2f7e8f1b1779290315cabfd2c803:

**Expected behavior**
Start lotus daemon normal and sync chain.

**Screenshots**
![image](https://user-images.githubusercontent.com/17547084/86342416-275aeb00-bc8a-11ea-9f92-9afcb62b7461.png)

**Version (run `lotus --version`):**

can't run lotus daemon normally

**Additional context**
`
cat /proc/cpuinfo | grep name | cut -f2 -d: |uniq -c

4  AMD EPYC 7K62 48-Core Processor
`

**Comment by panol** [comment]
I also try my lotus docker image(a clean ubuntu-18.04 environment) that used to works by running 
`lotus daemon`
but today I try it throw the same error as about:mismatch in param。
So.I guess it might be the problem of the contend downloaded from (Node are from China and I used the following env to speed up filecoin-proof-parameters)
`IPFS_GATEWAY="https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/"
`
If I use the default IPFS_GATEWAY it works ok。

**Comment by magik6k** [comment]
This was an issue with the mirror, it's now fixed
