### ISSUE TITLE
Computing WinningPoSt error when one sector error,all the time,loop

### ISSUE THREAD

**Issue by chunqizhi** [filecoin-project/lotus#2238]
![image](https://user-images.githubusercontent.com/23360623/86361815-f341f300-bca6-11ea-9006-63e411394ce2.png)

**Comment by chunqizhi** [comment]
only the genesis node

**Comment by Reiers** [comment]
Hi @chunqizhi 

Thanks for the report. The issue is outdated. 

Please upgrade Lotus.
Link to latest tags [here.](https://github.com/filecoin-project/lotus/tags)

If this is an issue in current release, **please open a new ticket.**
