### ISSUE TITLE
"runPost failed: running post failed: - Too many open files (os error 24)

### ISSUE THREAD

**Issue by Leozhang404** [filecoin-project/lotus#2247]
1. When my miner start do the WindowPost, it met the error:

`{"level":"error","ts":"2020-07-02T13:26:56.782+0800","logger":"storageminer","caller":"storage/wdpost_run.go:59","msg":"**runPost failed: running post failed**:\n    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost\n        /home/ipfs/ipfs_release/ipfs-lotus/storage/wdpost_run.go:496\n  - **Too many open files** (os error 24)\n    github.com/filecoin-project/filecoin-ffi.GenerateWindowPoSt\n    \t/home/ipfs/ipfs_release/ipfs-lotus/extern/filecoin-ffi/proofs.go:560\n    github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).GenerateWindowPoSt\n    \t/home/ipfs/ipfs_release/ipfs-lotus/extern/ipfs-sector-storage/ffiwrapper/verifier_cgo.go:39\n    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost\n    \t/home/ipfs/ipfs_release/ipfs-lotus/storage/wdpost_run.go:494\n    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).doPost.func1\n    \t/home/ipfs/ipfs_release/ipfs-lotus/storage/wdpost_run.go:48\n    runtime.goexit\n    \t/usr/bin/go/src/runtime/asm_amd64.s:1373"}
- Too many open files (os error 24)`

2. Before this error, I have set `ulimit -n`  as below:

![image](https://user-images.githubusercontent.com/38653654/86425768-97b04d80-bd18-11ea-8a12-a6fbcffe886f.png)

3. It took ～17 hours(about 9 deadlines will do WindowPost, ~19k sectors) from the start of Miner until the error, after I restarted the miner, the error did not occur again. After ~24 house, loop again...

4. During the WindowPost, 

- I run the cmd `lsof -p $pid|wc -l `, as following:

![image](https://user-images.githubusercontent.com/38653654/86428046-663a8080-bd1e-11ea-999d-652c22d6d021.png)

- run the cmd: `ls -l /proc/[miner pid]/fd`, as below:

![image](https://user-images.githubusercontent.com/38653654/86429569-8f5d1000-bd22-11ea-8c2b-7d990dc2bbb0.png)

5. when there is no WindowPost, I run `ls -l /proc/[miner pid]/fd`, as below:

![image](https://user-images.githubusercontent.com/38653654/86429903-67ba7780-bd23-11ea-891c-e32b78ee6769.png)

6. lotus version: 0.4.0+git.6ce9d0df
    github.com/filecoin-project/filecoin-ffi v0.26.1-0.20200508175440-05b30afeb00d

It seems that storage miner code has a bug? please check it. @waynewyang @magik6k

**Comment by wo4zhuzi** [comment]
> 1. When my miner start do the WindowPost, it met the error:
> 
> `{"level":"error","ts":"2020-07-02T13:26:56.782+0800","logger":"storageminer","caller":"storage/wdpost_run.go:59","msg":"**runPost failed: running post failed**:\n github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost\n /home/ipfs/ipfs_release/ipfs-lotus/storage/wdpost_run.go:496\n - **Too many open files** (os error 24)\n github.com/filecoin-project/filecoin-ffi.GenerateWindowPoSt\n \t/home/ipfs/ipfs_release/ipfs-lotus/extern/filecoin-ffi/proofs.go:560\n github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).GenerateWindowPoSt\n \t/home/ipfs/ipfs_release/ipfs-lotus/extern/ipfs-sector-storage/ffiwrapper/verifier_cgo.go:39\n github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost\n \t/home/ipfs/ipfs_release/ipfs-lotus/storage/wdpost_run.go:494\n github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).doPost.func1\n \t/home/ipfs/ipfs_release/ipfs-lotus/storage/wdpost_run.go:48\n runtime.goexit\n \t/usr/bin/go/src/runtime/asm_amd64.s:1373"}
> 
> * Too many open files (os error 24)`
> 
> 1. Before this error, I have set `ulimit -n`  as below:
> 
> ![image](https://user-images.githubusercontent.com/38653654/86425768-97b04d80-bd18-11ea-8a12-a6fbcffe886f.png)
> 
> 1. It took ～17 hours(about 9 deadlines will do WindowPost, ~19k sectors) from the start of Miner until the error, after I restarted the miner, the error did not occur again. After ~24 house, loop again...
> 2. During the WindowPost,
> 
> * I run the cmd `lsof -p $pid|wc -l `, as following:
> 
> ![image](https://user-images.githubusercontent.com/38653654/86428046-663a8080-bd1e-11ea-999d-652c22d6d021.png)
> 
> * run the cmd: `ls -l /proc/[miner pid]/fd`, as below:
> 
> ![image](https://user-images.githubusercontent.com/38653654/86429569-8f5d1000-bd22-11ea-8c2b-7d990dc2bbb0.png)
> 
> 1. when there is no WindowPost, I run `ls -l /proc/[miner pid]/fd`, as below:
> 
> ![image](https://user-images.githubusercontent.com/38653654/86429903-67ba7780-bd23-11ea-891c-e32b78ee6769.png)
> 
> 1. lotus version: 0.4.0+git.6ce9d0df
>    github.com/filecoin-project/filecoin-ffi v0.26.1-0.20200508175440-05b30afeb00d
> 
> It seems that storage miner code has a bug? please check it. @waynewyang @magik6k


我也遇到相同的问题，节点换成 0.4.1 同步就正常了
I also encounter the same problem. If the node is changed to 0.4.1, the synchronization will be normal

**Comment by Leozhang404** [comment]
@wo4zhuzi  It doesn't seem to be a synchronization problem

**Comment by f8-ptrk** [comment]
too many open fiels isn't a lotus issue

#antidisestablishatarianism
