### ISSUE TITLE
https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/ can't visit, say account arrear!!!

### ISSUE THREAD

**Issue by github-0paul** [filecoin-project/lotus#2248]
The website https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/ can't visit.
it shows:
`<Error>
<statusCode>403</statusCode>
<Code>AccountArrear</Code>
<Message>
There is an arrear problem with this OSS account that prevents the operation from completing successfully
</Message>
<Resource>/proof-parameters/ipfs/</Resource>
<RequestId>86866438FC70BDF8</RequestId>
</Error>`

**Comment by sywyn219** [comment]
It depends on luck，ah！

**Comment by travisperson** [comment]
We are aware of this. Currently working on resolving this issue.

Thanks!

**Comment by magik6k** [comment]
This was fixed
