### ISSUE TITLE
error validating deal published: getting deal pubsish message: blockstore: block not found

### ISSUE THREAD

**Issue by vyzo** [filecoin-project/lotus#2250]
**Describe the bug**
While stress testing storage and retrieval deals, we quite often hit this error when calling `ClientGetDealInfo`:
`error validating deal published: getting deal pubsish message: blockstore: block not found`

I don't know whether this is a transient or terminal state, as our code currently panics when it encouters it.

**To Reproduce**
https://github.com/filecoin-project/oni/pull/81

**Expected behavior**
Return the deal state luke!

**Version (run `lotus --version`):**
lotus master as of this morning: `lotus v0.4.2-0.20200703005127-9d56dabb316f`

**Comment by TippyFlitsUK** [comment]
Hi @vyzo 

This issue has not been updated in some time. Should we close it or keep it open?

**Comment by TippyFlitsUK** [comment]
Thanks @vyzo 

I can confirm that I haven't seen this error for months even with a very heavy deal load.
