### ISSUE TITLE
Multisig propose message seems to always return with exitcode 18 (party not a signer)

### ISSUE THREAD

**Issue by Schwartz10** [filecoin-project/lotus#2255]
UPDATE:

I got this to work by making the signer of the multisig an ID address, rather than a type1 or type2 address. This also seems problematic though, a "not-yet-onchain" address can't be the signer for a multisig? Am i brain farting?

**Describe the bug**
I'm trying to make a proposal to a multisig actor - the transaction gets confirmed in the network, but it always seems to return an ExitCode of 18.

**To Reproduce**
1. Go ahead and create a multisig actor with a single signer (an address that you have the private key of)
2. To be sure, `./lotus daemon inspect [actor address]`
From there, you'll see something like:

```
=> ./lotus msig inspect t01003
Balance: 0.000000000000005fil
Threshold: 1 / 1
Signers:
	t137sjdbgunloi7couiy4l5nc7pd6k2jmq32vizpy
Transactions:  0
```

Try an `MsigPropose`:

```
{
"jsonrpc": "2.0",
"method": "Filecoin.MsigPropose",
"id": 1,
"params": ["t01003", "t137sjdbgunloi7couiy4l5nc7pd6k2jmq32vizpy", "1", "t137sjdbgunloi7couiy4l5nc7pd6k2jmq32vizpy", 2, "hFUB3+SRhNRq3I+J1EY4vrRfePytJZBCAAEAQA=="]
}

result: bafy2bzaceauvm2sp35xo6iytdcydn3kmyhg5tybssebc3nx4ulxdxvflyit3i
```

**Expected behavior**
I should be able to propose a multisig transaction with the address that created the multisig wallet.

**Screenshots**

**Version (run `lotus --version`):**
`lotus version 0.4.1+2k+git.4759ed5d.dirty`

**Comment by arajasek** [comment]
I believe [this PR](https://github.com/filecoin-project/specs-actors/pull/588/files) is intended to fix this

**Comment by Schwartz10** [comment]
Sorry for posting a duplicate, closing for [this](https://github.com/filecoin-project/specs-actors/issues/587)

**Comment by rllola** [comment]
I have seen this has been merged yersterday in master.
I tested on my end using the latest `master` branch and I also get the 18 exit code.
