### ISSUE TITLE
Track DRAND outages 

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#2258]
Lotus nodes should track when drand is 'down' or not, so that they can potentially use this information to make decisions.

Initially, we probably want to log in the journal when we notice drand going down, and coming back.

More complicated, would be some piece of state on the drand beacon client object that we can query from other places in the lotus node, or over the api

**Comment by TippyFlitsUK** [comment]
Hi @whyrusleeping 

This looks like a reminder. Should we close it or keep it open?
