### ISSUE TITLE
Stay here forever

### ISSUE THREAD

**Issue by chengwds** [filecoin-project/lotus#2262]
Worker 0: Target: [bafy2bzaceadbf3qk7hbgjuycgjp4k4dzknpqpdkc3fkiokrl7glcwf4y6lzsw bafy2bzaceapzccyidn4ybykinkammyxwz4ozrere2iid5srlvpsmxqsefyhis]	State: message sync	Height: 29417

**Comment by mawang12** [comment]
same either
i tired  reset it serval times . But it seems not work for me.

**Comment by magik6k** [comment]
We need (at least some) logs to debug this issue. If this happens on mainnet, please open a new issue with daemon logs.
