### ISSUE TITLE
what is the minimum memory required to mine?

### ISSUE THREAD

**Issue by siyy123** [filecoin-project/lotus#2264]
What is the minimum memory required to mine?
For example can I mine with 16(absolutely not) or 32 or 64 or 128GB memory?
Or can I mine with little memory but very large swap space on SSD?
Because usually a platform can only have a certain amount of memory maximum(limited by DIMM slots and DIMM types, etc.), and large memory is very costly(maybe even more than half of the platform's total cost).
So please tell me what is the minimum memory required.

**Comment by jimpick** [comment]
128 GiB of RAM for 32GiB sectors

https://lotu.sh/en+hardware-mining
