### ISSUE TITLE
Internal errors exposed in deal failures

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#2266]
**Describe the bug**

I saw this error returned in my workshop client UI, returned via the ClientListDeals JSON-RPC API call:

```
deal failed: (State=7) generating piece committment: failed to build tree Caused by: 0: failed to create data store 1: No such file or directory (os error 2)
```

<img width="551" alt="Screenshot 2020-07-04 10 35 37" src="https://user-images.githubusercontent.com/20886/86518012-9f3c2900-bde2-11ea-84b4-becd73f9b173.png">

It's a bit of a nitpick, but I don't think it should be exposing internal operational details to the client. A more structured response (possibly with error codes) would be preferable. It should definitely be logging/tracking these and reporting them to the miner operator.

**Version (run `lotus --version`):**

```
Daemon:  0.4.1+git.5de7b62d.dirty+api0.5.0
Local: lotus version 0.4.1+git.5de7b62d.dirty
```

**Comment by TippyFlitsUK** [comment]
Hi @jimpick 

This issue has not been updated in some time. Should we close it or keep it open?
