### ISSUE TITLE
How to point Lotus to custom folders or paths for sealing and storing?

### ISSUE THREAD

**Issue by Shekelme** [filecoin-project/lotus#2271]
After some reading of Lotu.sh, Filecoin Slack and Telegram group  I found that there are no clear instructions (and no instructions at all) about specifying custom directories for the sealing cache and specifically for storing data. Each participant in the test network overcomes this situation by their own methods. Wouldn't it be better to bring specific methods and recommendations from developers in the official documentation?

**Comment by hsanjuan** [comment]
Fixed by #3431 I think, which explains how to set up separate storage locations.

**Comment by magik6k** [comment]
https://docs.filecoin.io/mine/lotus/custom-storage-layout/
