### ISSUE TITLE
RAIDx or just the disks itself?

### ISSUE THREAD

**Issue by Shekelme** [filecoin-project/lotus#2272]
In the absence of specificity in the official documentation for the lotus, in addition to the methodology of specifying custom directories itself, I am interested in the following question: is it worth combining several disks into an array or should I point the lotus to them separately as a space for storing filecoin data?

**Comment by hsanjuan** [comment]
Depends on your setup and your requirements wrt. data security. Since this is not an lotus-specific question, it might be better asked in the forums or slack.
