### ISSUE TITLE
Faulty rate 90% daily while proving

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/lotus#2273]
**Describe the problem**
My miner lost most of the proved sectors everyday ,Faulty rate ate 90%
lotus-storage-miner info
Miner: t0117917
Sector Size: 32 GiB
Byte Power:   64 GiB / 18.04 PiB (0.0003%)
Actual Power: 64 Gi / 16.9 Pi (0.0003%)
	Committed: 640 GiB
	Proving: 64 GiB (576 GiB Faulty, 90.00%)
Below minimum power threshold, no blocks will be won
Miner Balance: 0.004429954919671993
	PreCommit:   0
	Locked:      0.003924329318193781
	Available:   0.000505625601478212
Worker Balance: 49.995570045079126229
Market (Escrow):  0
Market (Locked):  0

Sectors:
	Total: 28
	Proving: 6
	PreCommit1: 5
	PreCommit2: 4
	FailedUnrecoverable: 13

**Sectors list**

0: FailedUnrecoverable  sSet: YES pSet: NO  tktH: 47833 seedH: 0     deals: [0]
1: FailedUnrecoverable  sSet: YES pSet: NO  tktH: 47833 seedH: 0     deals: [0]
2: Proving              sSet: YES pSet: NO  tktH: 47833 seedH: 51033 deals: [0]
3: Proving              sSet: YES pSet: NO  tktH: 47833 seedH: 50445 deals: [0]
4: Proving              sSet: YES pSet: YES tktH: 49157 seedH: 52288 deals: [0]
5: Proving              sSet: YES pSet: NO  tktH: 49157 seedH: 52184 deals: [0]
6: Proving              sSet: YES pSet: NO  tktH: 49158 seedH: 51958 deals: [0]
7: FailedUnrecoverable  sSet: YES pSet: NO  tktH: 49184 seedH: 0     deals: [0]
8: FailedUnrecoverable  sSet: YES pSet: NO  tktH: 50258 seedH: 0     deals: [0]
9: FailedUnrecoverable  sSet: YES pSet: NO  tktH: 50259 seedH: 0     deals: [0]
10: FailedUnrecoverable sSet: YES pSet: NO  tktH: 50273 seedH: 0     deals: [0]
11: FailedUnrecoverable sSet: YES pSet: NO  tktH: 50673 seedH: 0     deals: [0]
12: FailedUnrecoverable sSet: YES pSet: NO  tktH: 50674 seedH: 0     deals: [0]
13: FailedUnrecoverable sSet: YES pSet: NO  tktH: 51349 seedH: 0     deals: [0]
14: FailedUnrecoverable sSet: NO  pSet: NO  tktH: 43442 seedH: 0     deals: [0]
15: FailedUnrecoverable sSet: YES pSet: NO  tktH: 52014 seedH: 0     deals: [0]
16: FailedUnrecoverable sSet: YES pSet: NO  tktH: 52495 seedH: 0     deals: [0]
17: FailedUnrecoverable sSet: YES pSet: NO  tktH: 52496 seedH: 0     deals: [0]
18: Proving             sSet: YES pSet: YES tktH: 52496 seedH: 55373 deals: [0]
19: PreCommit1          sSet: NO  pSet: NO  tktH: 43442 seedH: 0     deals: [0]
20: PreCommit2          sSet: YES pSet: NO  tktH: 54094 seedH: 0     deals: [0]
21: PreCommit2          sSet: NO  pSet: NO  tktH: 43442 seedH: 0     deals: [0]
22: PreCommit2          sSet: NO  pSet: NO  tktH: 43442 seedH: 0     deals: [0]
23: PreCommit1          sSet: NO  pSet: NO  tktH: 43442 seedH: 0     deals: [0]
24: PreCommit2          sSet: YES pSet: NO  tktH: 54109 seedH: 0     deals: [0]
25: PreCommit2          sSet: NO  pSet: NO  tktH: 54109 seedH: 0     deals: [0]
26: PreCommit1          sSet: NO  pSet: NO  tktH: 0     seedH: 0     deals: [0]
27: PreCommit1          sSet: NO  pSet: NO  tktH: 0     seedH: 0     deals: [0]

**Sectors status**

lotus-storage-miner sectors status --log 6
SectorID:	6
Status:	Proving
CommD:		6261666b3463687a6161353766377872767975666a676135666b61653667736d6b6a32376e37343434696b3372626e7a71336477687672357075793761
CommR:		6261666b3465687a61376a79793437797868657671667132717a6633677772636135656c6a6775643632746f6173366b6b6e6c74673579687568757961
Ticket:		f6ad6827352e4758ec11c21cfd263fbaccb3a7ec867466ff2e3f1229f415f91e
TicketH:		49158
Seed:		e59217c1136decdf4fb5f74fcf9198ec7d120c341127968b628b9c408e4f423d
SeedH:		51958
Proof:		ac9251bc6649718ee0286c8de4e84fe5aa8df23cd9b230df3efc6d7e70443f8cb7027ce4e176839099d2e85e182dd3a3938096586cf55a4766952dc90342d18df2c92c7c807f50851ba86b1fdc15ef76f986f01f5683c41457ef09d7bfa026520365e3d0adb148ff9ea9e53b88d58650a5d5714c58a4124ebf7442d99e116cd5f170d587694c70bb2ce52ebe1bdb5d63a80fd1a20944b4dc781585832485d97141a8ce23f3f5a624568ff7389ad80f9b939f837e070f8d6ba8fe9d0e59b41e4bb07948d133de4aa4c8d35feeadf7cf2da7c4d66258f3b23ab4f99aeac53aba247d76af0e04af9f637c71b47ac8ff0538954c3f59e44d592567480316b6097158ffc1805a76d48ddc14457edb65307da0305d882d5c5f9f3f381f1eb966989a4b1009cea8cd4404f44e9e293b65dc198484811c961acce317f04fe3b1a3b6d42a0b6f0d82e17bb55a14d5bc5f286c07c88fa758a242f4399dfac07e266e1134e6df8f4dd048431ae130612f501b6fb12ed0c3521a323ab14fb80a29243aa6fdd0b4aa77d42f4c22858e1fcdd426c51d1c1f46f911cafc20792bb6aab8c7c75942f9e60a37f1ff3b5c663a20b7c7732c1d86b0342a411f1fb8ba7577bc3b07f2df50a835ac518b85cb4087f1b51290324504964e5402b9928899fde3576d57a7fa0790bc9b246bcccf3eb08b2b466b586bc2739242179fb527044126a6e12bcddd209304853c84ec51a7cf8d5d5830824191cebc2897deef7d1568255dadd76d81344c962003a47749ecabaed0b8af167b3bac7cf9c223da625ff68c71ccf8a4f0ac97e64f7bcb5c2ca81e8e4d58413623881b3fab4f412d80ccb5b486b05d506bfd751a7f0973deb95a3b9788aaec40f4803b100c83d787b486fdbf2ffdd5ce517f807af075503859658839774760fe4dc9317cfbaf0c585b19da1f4c843d644807ccc32fae32ef5697ddaa4d4f8add658d19484269cf0ce25ec107add880990fd0e20706c3d6732a23353617d18ba99b8398fb84248eff5531a73bbe3693f62014f918baee7be8f2f4cfdf4d1ced60bbe3ccb930338bb7a081e4788ceb907be389acb6a05c5cb2e512825b67474da4969d0f22e1fbd45e5f519d65901060cbaa0a5919e2f2889f03c02a48dddec471e4a46f04865233f1de68130a904064e6e3907a41780010c65ede31279debc965fb29d3a6cfbd8abc8af7b34dac7545e44702e54aae42e928d31a72d844394cf3b1d1879f3af9e3da59a0be5f50a2d3b535051dd72c351cc8a3e9da07ae0a53bd00b0173f7060eb357b3c295047daf0b8bb3272ff400252fe4e4fb044c9b95fdd8f6343e21e2f9bb4b4b6fb00bb0e5a4509835936d50c03300a5217b329b36880b7a9077db9be2233dbb18bc9104d5698018d60e2f7b7be21113ea5ac0b8c5b2c4c8c5dcd03cfb02bf863b76a6d04c4805500a9573331cb8d6d7e4a8355821b64b3f073368c5e55adb42bb29e7514350e4a11780027cd1a5cdb13ef0d9a988b54e30e88dde3e179587613503312884f2015cc0ad9491a5f1e0eb026779818b15c4c90991f4df018ccb2b3ab791f29214556238db4c4e9f19f556ed056955c9d36f2e22875dc6fe6abaef5cf6c388c499554b4d6563bd1cc22219249184299f97233059e3c256f72d6f9e27456c519dd593e95caa5b83d85eb5d8dfb66e6d70d2c80b2686ce246e9290f310b58d6ddf40d37ef8d7d3662d0a9cdbe38e8d07e63178ca0e5b961bc83b36de2a9ced1e1a3a7d70e0f077ca8e16c24858ed403e765399474eeb65b41deeddbbd92168f44c72c5bb00825e291684a862754253a5e6cc6fd843012c19af9e613601dccfd7517ad722816d0b7629d78c043af24669543bb3b64a0d0ce4fe028219f2f33fdae0add9cb74df17e59197c10187e2aaf7d0eda88195417cb014c8c61a0746d731dce97b8a996e9716a97bbe2bb6edbe96117fce993a4fa6faed9afd6bd438aa9095a5f7ae8511521668f36a975066fc59782437904185a17082c2de562a9e9d4835abb9000d49697e250c10e3653bd79c026654436064aa0408015d128231974b6dc300b01e55a3038320fb255846c3df43ea808a03d194c15fe7290b749a8bf2b9151c33d2b0407a8a06223ac93ca84d7854f63023d9a0f2a4e9477b3fb5f867553ec8f9645368dad27c0234809d4d51b6784001fa78545f120ad62eb789181d715264f84d71b2eb3d2db6e57f0b42cdfa2805b978bfe46c321f1a9d9d786e01b41ca95dc3232e7452e5cb49ac0b55265d3d84060abca59c66e5f6aecc1c98fc429aa85089665e7c987281560739d63c30f25404475d6506d2ce390afab6e936e413d5275196f426d95f3bbc35a23a12645ada7b3da034e721c81b5d9869220ffe5c018a7039154e070ca0c85ffec08b85f7935833a1dfbaca003c7eadd1ab59be58b188b97cbbdd444380eeed979a6376837e5aa688fdb2bf44cf92d222182e420361d8bd97b4a27b8a708f37e7fdd509bffb4af7e76761ea9052c29b85b79d08698e697dd6b61c5ed13e87768d3c91873492beb070802efe05d3d74181a6c6b5301a8128ad5f616334f3ce7c79d852b54cd04eff40f20c2b842e1c7b7114c6021444cfe40f4b304c82a0d52e66c16b3d34541b5f62dbeb07a74b66464ff9fd3afaa67d4fb4061c1062f45902182a774b16ba2d2a297823a27272a2a94701c559f7238
Deals:		[0]
Retries:		0
--------
Event Log:
0.	2020-07-03 11:37:25 +0000 UTC:	[event;sealing.SectorStart]	{"User":{"ID":6,"SectorType":3,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"bafk4chzaa57f7xrvyufjga5fkae6gsmkj27n7444ik3rbnzq3dwhvr5puy7a"}},"DealInfo":null}]}}
1.	2020-07-03 11:37:30 +0000 UTC:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
2.	2020-07-03 18:59:39 +0000 UTC:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjEiLCJsYWJlbHMiOnsiU3RhY2tlZERyZzMyR2lCVjEiOnsibGFiZWxzIjpbeyJwYXRoIjoiL2hvbWUvbmJmcy9sb3R1c3dvcmtlci9jYWNoZS9zLXQwMTE3OTE3LTYiLCJpZCI6ImxheWVyLTEiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9ob21lL25iZnMvbG90dXN3b3JrZXIvY2FjaGUvcy10MDExNzkxNy02IiwiaWQiOiJsYXllci0yIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9uYmZzL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxMTc5MTctNiIsImlkIjoibGF5ZXItMyIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2hvbWUvbmJmcy9sb3R1c3dvcmtlci9jYWNoZS9zLXQwMTE3OTE3LTYiLCJpZCI6ImxheWVyLTQiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9ob21lL25iZnMvbG90dXN3b3JrZXIvY2FjaGUvcy10MDExNzkxNy02IiwiaWQiOiJsYXllci01Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9uYmZzL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxMTc5MTctNiIsImlkIjoibGF5ZXItNiIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2hvbWUvbmJmcy9sb3R1c3dvcmtlci9jYWNoZS9zLXQwMTE3OTE3LTYiLCJpZCI6ImxheWVyLTciLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9ob21lL25iZnMvbG90dXN3b3JrZXIvY2FjaGUvcy10MDExNzkxNy02IiwiaWQiOiJsYXllci04Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9uYmZzL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxMTc5MTctNiIsImlkIjoibGF5ZXItOSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2hvbWUvbmJmcy9sb3R1c3dvcmtlci9jYWNoZS9zLXQwMTE3OTE3LTYiLCJpZCI6ImxheWVyLTEwIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9uYmZzL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxMTc5MTctNiIsImlkIjoibGF5ZXItMTEiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9XSwiX2giOm51bGx9fSwiY29uZmlnIjp7InBhdGgiOiIvaG9tZS9uYmZzL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxMTc5MTctNiIsImlkIjoidHJlZS1kIiwic2l6ZSI6MjE0NzQ4MzY0Nywicm93c190b19kaXNjYXJkIjo3fSwiY29tbV9kIjpbNywxMjYsOTUsMjIyLDUzLDE5NywxMCwxNDcsMywxNjUsODAsOSwyMjcsNzMsMTM4LDc4LDE5MCwyMjMsMjQzLDE1Niw2NiwxODMsMTYsMTgzLDQ4LDIxNiwyMzYsMTIyLDE5OSwxNzUsMTY2LDYyXX0=","TicketValue":"9q1oJzUuR1jsEcIc/SY/usyzp+yGdGb/Lj8SKfQV+R4=","TicketEpoch":49158}}
3.	2020-07-04 00:44:52 +0000 UTC:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bafk4ehza7jyy47yxhevqfq2qzf3gwrca5eljgud62toas6kknltg5yhuhuya"},"Unsealed":{"/":"bafk4chzaa57f7xrvyufjga5fkae6gsmkj27n7444ik3rbnzq3dwhvr5puy7a"}}}
4.	2020-07-04 00:44:52 +0000 UTC:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzacecgrahkyak3ejb57mmg2xfwzoyhppyolthmpoviw4ix25b7m7jwyk"}}}
5.	2020-07-04 00:47:30 +0000 UTC:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":"AXGg5AIg5kN7cyYibMJqWdfkmDlcOpFiVxqOtfID+URNas0R08UBcaDkAiDdxrxkERuqrrmjTTCxrZmiqoRBdSvZHnWgOZ3gZzPONQ=="}}
6.	2020-07-04 00:51:40 +0000 UTC:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"5ZIXwRNt7N9PtfdPz5GY7H0SDDQRJ5aLYoucQI5PQj0=","SeedEpoch":51958}}
7.	2020-07-04 02:05:26 +0000 UTC:	[event;sealing.SectorCommitted]	{"User":{"Message":{"/":"bafy2bzaceb2uxbsj4qdspfio3pfxwrqqzbc5hfc43y4hff6ete3gthacz2bnk"},"Proof":"rJJRvGZJcY7gKGyN5OhP5aqN8jzZsjDfPvxtfnBEP4y3Anzk4XaDkJnS6F4YLdOjk4CWWGz1WkdmlS3JA0LRjfLJLHyAf1CFG6hrH9wV73b5hvAfVoPEFFfvCde/oCZSA2Xj0K2xSP+eqeU7iNWGUKXVcUxYpBJOv3RC2Z4RbNXxcNWHaUxwuyzlLr4b211jqA/RoglEtNx4FYWDJIXZcUGoziPz9aYkVo/3OJrYD5uTn4N+Bw+Na6j+nQ5ZtB5LsHlI0TPeSqTI01/urffPLafE1mJY87I6tPma6sU6uiR9dq8OBK+fY3xxtHrI/wU4lUw/WeRNWSVnSAMWtglxWP/BgFp21I3cFEV+22UwfaAwXYgtXF+fPzgfHrlmmJpLEAnOqM1EBPROnik7ZdwZhISBHJYazOMX8E/jsaO21CoLbw2C4Xu1WhTVvF8obAfIj6dYokL0OZ36wH4mbhE05t+PTdBIQxrhMGEvUBtvsS7Qw1IaMjqxT7gKKSQ6pv3QtKp31C9MIoWOH83UJsUdHB9G+RHK/CB5K7aquMfHWUL55go38f87XGY6ILfHcywdhrA0KkEfH7i6dXe8Owfy31CoNaxRi4XLQIfxtRKQMkUElk5UArmSiJn941dtV6f6B5C8myRrzM8+sIsrRmtYa8JzkkIXn7UnBEEmpuErzd0gkwSFPITsUafPjV1YMIJBkc68KJfe730VaCVdrddtgTRMliADpHdJ7Kuu0LivFns7rHz5wiPaYl/2jHHM+KTwrJfmT3vLXCyoHo5NWEE2I4gbP6tPQS2AzLW0hrBdUGv9dRp/CXPeuVo7l4iq7ED0gDsQDIPXh7SG/b8v/dXOUX+AevB1UDhZZYg5d0dg/k3JMXz7rwxYWxnaH0yEPWRIB8zDL64y71aX3apNT4rdZY0ZSEJpzwziXsEHrdiAmQ/Q4gcGw9ZzKiM1NhfRi6mbg5j7hCSO/1Uxpzu+NpP2IBT5GLrue+jy9M/fTRztYLvjzLkwM4u3oIHkeIzrkHvjiay2oFxcsuUSgltnR02klp0PIuH71F5fUZ1lkBBgy6oKWRni8oifA8AqSN3exHHkpG8EhlIz8d5oEwqQQGTm45B6QXgAEMZe3jEnnevJZfsp06bPvYq8ivezTax1ReRHAuVKrkLpKNMacthEOUzzsdGHnzr549pZoL5fUKLTtTUFHdcsNRzIo+naB64KU70AsBc/cGDrNXs8KVBH2vC4uzJy/0ACUv5OT7BEyblf3Y9jQ+IeL5u0tLb7ALsOWkUJg1k21QwDMApSF7Mps2iAt6kHfbm+IjPbsYvJEE1WmAGNYOL3t74hET6lrAuMWyxMjF3NA8+wK/hjt2ptBMSAVQCpVzMxy41tfkqDVYIbZLPwczaMXlWttCuynnUUNQ5KEXgAJ80aXNsT7w2amItU4w6I3ePheVh2E1AzEohPIBXMCtlJGl8eDrAmd5gYsVxMkJkfTfAYzLKzq3kfKSFFViONtMTp8Z9VbtBWlVydNvLiKHXcb+arrvXPbDiMSZVUtNZWO9HMIiGSSRhCmflyMwWePCVvctb54nRWxRndWT6VyqW4PYXrXY37ZubXDSyAsmhs4kbpKQ8xC1jW3fQNN++NfTZi0KnNvjjo0H5jF4yg5blhvIOzbeKpztHho6fXDg8HfKjhbCSFjtQD52U5lHTutltB3u3bvZIWj0THLFuwCCXikWhKhidUJTpebMb9hDASwZr55hNgHcz9dRetcigW0LdinXjAQ68kZpVDuztkoNDOT+AoIZ8vM/2uCt2ct03xflkZfBAYfiqvfQ7aiBlUF8sBTIxhoHRtcx3Ol7iplulxape74rtu2+lhF/zpk6T6b67Zr9a9Q4qpCVpfeuhRFSFmjzapdQZvxZeCQ3kEGFoXCCwt5WKp6dSDWruQANSWl+JQwQ42U715wCZlRDYGSqBAgBXRKCMZdLbcMAsB5VowODIPslWEbD30PqgIoD0ZTBX+cpC3Sai/K5FRwz0rBAeooGIjrJPKhNeFT2MCPZoPKk6Ud7P7X4Z1U+yPlkU2ja0nwCNICdTVG2eEAB+nhUXxIK1i63iRgdcVJk+E1xsus9LbblfwtCzfooBbl4v+RsMh8anZ14bgG0HKldwyMudFLly0msC1UmXT2EBgq8pZxm5fauzByY/EKaqFCJZl58mHKBVgc51jww8lQER11lBtLOOQr6tuk25BPVJ1GW9CbZXzu8NaI6EmRa2ns9oDTnIcgbXZhpIg/+XAGKcDkVTgcMoMhf/sCLhfeTWDOh37rKADx+rdGrWb5YsYi5fLvdREOA7u2XmmN2g35apoj9sr9Ez5LSIhguQgNh2L2XtKJ7inCPN+f91Qm/+0r352dh6pBSwpuFt50IaY5pfda2HF7RPod2jTyRhzSSvrBwgC7+BdPXQYGmxrUwGoEorV9hYzTzznx52FK1TNBO/0DyDCuELhx7cRTGAhREz+QPSzBMgqDVLmbBaz00VBtfYtvrB6dLZkZP+f06+qZ9T7QGHBBi9FkCGCp3Sxa6LSopeCOicnKiqUcBxVn3I4"}}
8.	2020-07-04 02:08:20 +0000 UTC:	[event;sealing.SectorProving]	{"User":{}}
9.	2020-07-04 02:19:18 +0000 UTC:	[event;sealing.SectorFinalized]	{"User":{}}

**Lotus storage miner logs**

Please go through the logs of your storage miner, and include screenshots of any error-like messages you find.

**Version**
lotus --version
lotus version 0.4.1+git.5de7b62d

**Comment by flyworker** [comment]
I found it changes to pSet: YES after 3 Hours
Should be normal?

lotus-storage-miner sectors list
0: FailedUnrecoverable  sSet: YES pSet: NO  tktH: 47833 seedH: 0     deals: [0]
1: FailedUnrecoverable  sSet: YES pSet: NO  tktH: 47833 seedH: 0     deals: [0]
2: Proving              sSet: YES pSet: YES tktH: 47833 seedH: 51033 deals: [0]
3: Proving              sSet: YES pSet: YES tktH: 47833 seedH: 50445 deals: [0]
4: Proving              sSet: YES pSet: YES tktH: 49157 seedH: 52288 deals: [0]
5: Proving              sSet: YES pSet: YES tktH: 49157 seedH: 52184 deals: [0]
6: Proving              sSet: YES pSet: YES tktH: 49158 seedH: 51958 deals: [0]
7: FailedUnrecoverable  sSet: YES pSet: NO  tktH: 49184 seedH: 0     deals: [0]
8: FailedUnrecoverable  sSet: YES pSet: NO  tktH: 50258 seedH: 0     deals: [0]
9: FailedUnrecoverable  sSet: YES pSet: NO  tktH: 50259 seedH: 0     deals: [0]
10: FailedUnrecoverable sSet: YES pSet: NO  tktH: 50273 seedH: 0     deals: [0]
11: FailedUnrecoverable sSet: YES pSet: NO  tktH: 50673 seedH: 0     deals: [0]
12: FailedUnrecoverable sSet: YES pSet: NO  tktH: 50674 seedH: 0     deals: [0]
13: FailedUnrecoverable sSet: YES pSet: NO  tktH: 51349 seedH: 0     deals: [0]
14: FailedUnrecoverable sSet: NO  pSet: NO  tktH: 43442 seedH: 0     deals: [0]
15: FailedUnrecoverable sSet: YES pSet: NO  tktH: 52014 seedH: 0     deals: [0]
16: FailedUnrecoverable sSet: YES pSet: NO  tktH: 52495 seedH: 0     deals: [0]
17: FailedUnrecoverable sSet: YES pSet: NO  tktH: 52496 seedH: 0     deals: [0]
18: Proving             sSet: YES pSet: YES tktH: 52496 seedH: 55373 deals: [0]

**Comment by Leozhang404** [comment]
How did you change the sector status to FailedUnrecoverable？

**Comment by flyworker** [comment]
> How did you change the sector status to FailedUnrecoverable？

lotus-storage-miner sectors update-state --really-do-it 4 FailedUnrecoverable

**Comment by magik6k** [comment]
You shouldn't ever have to change the sector state to FailedUnrecoverable, it's almost guaranteed to break things. When sectors become faulty (e.g. after missing a PoSt), just leave them in the state they are in (currently they will show up as 'Proving'), and they will recover automatically
