### ISSUE TITLE
websocket: bad handshake

### ISSUE THREAD

**Issue by qupenghui** [filecoin-project/lotus#2274]
system os : Centos 8
lotus version: lotus version 0.4.1+git.e5fdae4.dirty
run lotus daemon , it`s working
then lotus sync wait ,return
2020-07-05T11:09:29.262-0400	WARN	main	lotus/main.go:81	websocket: bad handshake

**Comment by qupenghui** [comment]
token error

**Comment by qiluge** [comment]
hello, please, how to solve this problem?
