### ISSUE TITLE
Which folder should be in SSD and which folder should be in mechanical?

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#2275]
Hello currently I have 1TB nvme SSD and 16TB SATA RAID mechanical hard drive. I used the command **lotus-storage-miner storage attach --init=true --store=true /raidmountpoint** to store data on the RAID but the SSD still fills up to 100% after **sectors pledge** starts.

So I am confused by the following folders and which of them require to be reside in SSD and which can be in mechanical? And how much space do they need for start mining?
.lotus
.lotusstorage
.lotusworker
/var/tmp

**Comment by Shekelme** [comment]
./lotusminer should be definitely at SSD, with 600 GB of free space for sealing. Not sure about /var/tmp, probably filecoin data from there can be on HDD too, need to check.

What does `lotus-miner storage list` report to you?

**Comment by RobQuistNL** [comment]
By default a storage directory is used in your `~/.lotusstorage` folder. You can edit that default storage by changing the config file in there. Not sure about .lotusworker as I've never ran seperate workers (only daemon and miner on the same machine)

`~/.lotus` is from the daemon - it contains the chain data.

Your TMP folder contains the proof parameters and parents cache

**Comment by kernelogic** [comment]
This is what I have now. The lotusminer is on SSD and storage is on HDD.
068d4298-3943-418f-8bd6-de20b76a030c:
	[||                                                ] 778.5 GiB/14.44 TiB 5%
	Unsealed: 0; Sealed: 1; Caches: 1
	Weight: 10; Use: Store
	Local: /mnt/ipfs/storage
	URL: http://127.0.0.1:2345/remote

6bc85155-90c8-4e45-a574-495c3bfd4a34:
	[|||||||||                                         ] 293.5 GiB/1.557 TiB 18%
	Unsealed: 0; Sealed: 0; Caches: 0
	Weight: 10; Use: Seal 
	URL: http://127.0.0.1:3456/remote (latency: 600µs)

7e539f17-338e-41e1-b8e0-00bc0cf3609d:
	[||||||||||                                        ] 325.5 GiB/1.557 TiB 20%
	Unsealed: 0; Sealed: 0; Caches: 0
	Weight: 10; Use: Seal 
	Local: /root/.lotusminer
	URL: http://127.0.0.1:2345/remote

**Comment by magik6k** [comment]
This looks correct. I'm guessing the issue here was with incorrect storage space reservation, which got fixed since this was opened
