### ISSUE TITLE
Below minimum power threshold, no blocks will be won

### ISSUE THREAD

**Issue by christest123456** [filecoin-project/lotus#2279]
can anybody help me? why show "Below minimum power threshold, no blocks will be won"

**Comment by Leozhang404** [comment]
your power is too low （<1T）

**Comment by Leozhang404** [comment]
https://github.com/filecoin-project/lotus/blob/4f9c9072489ae83c78d5a9d6a61edb1d09d23434/cmd/lotus-storage-miner/info.go#L123

**Comment by christest123456** [comment]
what can I do?

**Comment by christest123456** [comment]
Is this a problem with the computer hardware configuration

**Comment by Leozhang404** [comment]
you just can not win a new block. just to continue to seal sectors and increase your power

**Comment by Leozhang404** [comment]
it is not a error

**Comment by christest123456** [comment]
ok, I know, thank you very much
