### ISSUE TITLE
How do I know `lotus sync wait` is finished?

### ISSUE THREAD

**Issue by leimao** [filecoin-project/lotus#2290]
Hello, I am a beginner. I wonder how I would know the progress of `lotus sync wait` and whether it is finished or not? Thank you.

**Comment by leimao** [comment]
It will print `Done` after it is finished.

**Comment by Snow-Sudo** [comment]
@leimao how long did it take for "lotus sync wait" to complete? I started today Aug 16 around 2 pm est and it still has not finished.

**Comment by gszep** [comment]
I would also like to how long it takes. My computer crashed already trying to sync. What does the output mean?
```State: header sync; Current Epoch: 596863; Todo: 133519```
