### ISSUE TITLE
runPost failed: getting paritions for deadline

### ISSUE THREAD

**Issue by vyzo** [filecoin-project/lotus#2293]
**Describe the bug**
During deals stress testing, the miner failed with this ominous ERROR:
```
ERROR   storageminer    storage/wdpost_run.go:58       runPost failed: getting partitions for deadline: 
  github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
  /go/pkg/mod/github.com/filecoin-project/lotus@v0.4.1-0.20200701153027-70d83784046b/storage/wdpost_run.go:353  {"req_id": "e0ccdfd6"}
 - invalid deadline index 36 for 36 deadlines 
 storage/wdpost_run.go:27
```

**To Reproduce**
See https://github.com/filecoin-project/oni/pull/81

**Expected behavior**
I want my deals to succeed damn it!

**Version (run `lotus version`):**
master, `v0.4.1-0.20200701153027-70d83784046b`

**Comment by magik6k** [comment]
This got fixed
