### ISSUE TITLE
Issues manifest from Deal Stress Testing

### ISSUE THREAD

**Issue by vyzo** [filecoin-project/lotus#2294]
## Context

We have set up a deal stress test in testground, where a number of clients execute a (large) number of deals with miners either serially or concurrently.
We have been running with this test for almost a week now, and we think it's a good time to summarize our findings so far as lotus seems to be having troubles in this scenario.
The code for the test is in https://github.com/filecoin-project/oni/pull/81

## Panic in the streets of Lotus

We have encountered 3 panics so far, that have been fixed:
- #2191 
- https://github.com/filecoin-project/go-fil-markets/issues/314
- https://github.com/filecoin-project/go-fil-markets/issues/301

## Observed failure in the serial test

In this mode, we run 3 clients and 2 miners, with the clients each picking a random miner and executing 300 deals serially (one after another).
What was observed, after a day of runtime in a c5.4xlarge instance in AWS, is that only one of the clients managed to finish all the deals. The other two clients got terminally stuck about halfway there in `StorageDealSealing`, failing with #2250 while the miner posted a failed window post as described in #2293

## Observed failures in the concurrent test

Initially we run in a c5.4xlarge with 3 clients and 2 miners, trying to do 300 concurrent deals; this failed with usual apparent behaviour as described in #2249 
After complete failure to ever finish the 300 deal test, we started to bisect and run with progressively fewer deals to see the limits of running in a single VM; **1, 2, 3, and 5 deals succeeded, but starting with 8 deals and higher the test would fail, in a variety of ways.**

We then moved to a Kubernetes cluster with a dedicated VM per miner, and run with progressively increasing number of deals; up to 25 deals it was successful, but then we had to switch to larger VMs.
Interesting observed behaviour is that deals get sealed but retrieval takes >2min.

When running 3 clients <-> 3 miners on `c5.9xlarge` with 200 deals per client and miner, we again ended up with stuck deals:

<img width="2481" alt="Screenshot 2020-07-06 at 22 54 31" src="https://user-images.githubusercontent.com/50459/86770794-900ee280-c051-11ea-9a0e-390755ba283f.png">

Logs and goroutine dumps:

[miners-0.txt](https://github.com/filecoin-project/lotus/files/4884350/miners-0.txt)
[miners-1.txt](https://github.com/filecoin-project/lotus/files/4884351/miners-1.txt)
[miners-2.txt](https://github.com/filecoin-project/lotus/files/4884352/miners-2.txt)

A collection of common issues encountered:
- #2249 
- #2250 
- #2291 
- #2292 
- #2293

## Further Work

We are still pushing the boundaries in the cluster to see how many deals we can run and in what kind of environment; eventually we want to get past the magic number of 256 concurrent deals -- we are targeting 300 concurrent deals _per client_, just like the Spartans.

cc @raulk @nonsense @yusefnapora

**Comment by TippyFlitsUK** [comment]
Hi @vyzo 

This issue has not been updated in some time. Should we close it or keep it open?

**Comment by vyzo** [comment]
dunno, presumably these issues have been fixed?

**Comment by TippyFlitsUK** [comment]
Many thanks @vyzo.
