### ISSUE TITLE
An error is reported when calling mpoolpush interface

### ISSUE THREAD

**Issue by wo4zhuzi** [filecoin-project/lotus#2296]
Return results:
missing permission to invoke 'MpoolPush' (need 'write')

How to solve this problem?

**Comment by wo4zhuzi** [comment]
> Return results:
> missing permission to invoke 'MpoolPush' (need 'write')
> 
> How to solve this problem?

I got it!

lotus auth create-token --perm create Command to increase write permission

But the result is returned:

`{
  "jsonrpc": "2.0",
  "result": {
    "/": "bafy2bzacedqd2umbqs3ied6bi4nswdvhbfabvqkmnzzv5qve3msxeiebrg5hc"
  },
  "id": 3
}`

The CID cannot be found in the browser

**Comment by lmxdawn** [comment]
I met the same problem, returned the cid but the browser could not find the cid
