### ISSUE TITLE
General ux improvements around binary names and configuration options

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#2304]
We have a pretty consistent prefix on a lot of things. The basics are that binaries start with `lotus-`, and environment vars start with `LOTUS_`. This doesn't hold true for a few things.

The following
- `stats`
- `fountain`
- `chainwatch`
- `bench`
- `health`

Binaries which follow this pattern
- `lotus`
- `lotus-storage-miner`
- `lotus-shed`
- `lotus-seed`
- `lotus-seal-worker`

`LOTUS_STORAGE_PATH` is a bit of an unfortunate name as "storage" is pretty generic and most people actually refer to running the `lotus-storage-miner` as just a miner. I think it gets a bit more confusing when seen on the `lotus-seal-worker`.

The `lotus-seal-worker` repo environment variable doesn't follow the same naming convention as both the lotus daemon or the miner, with `WORKER_PATH`.

------------------------

At a minimum I'd like to update the Makefile to prefix all binaries with `lotus-`. Renaming any binaries or updating the environment variables I don't have a solid proposal but I think a start might be:

| type | Old | New |
|---|---|---|
| binary | lotus-storage-miner | lotus-miner |
| env | LOTUS_STORAGE_PATH | LOTUS_MINER_PATH |
| env | WORKER_PATH | LOTUS_SEAL_WORKER_PATH |
| binary | stats | lotus-stats |
| binary | fountain | lotus-fountain |
| binary | chainwatch | lotus-chainwatch |
| binary | bench | lotus-bench |
| binary | health | lotus-health |

Along with these would come updates the the cli flags: most notably the seal worker `--storagerepo` flag would be `--minerrepo` or `--miner-repo`.

**Comment by jimpick** [comment]
Please please please rename WORKER_PATH at least.
