### ISSUE TITLE
Potential segfault when running Post

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2307]
The call to `StateMinerProvingDeadline` in `WindowPoStScheduler::update()` _could_ return a deadline with index `WPoStProvingPeriodDeadlines`*. The`deadlines` returned by `StateMinerDeadlines` in `WindowPoStScheduler::runPost()`, however, never has an entry at that index, which will cause our attempt to access `deadlines.Due[di.Index]` to fail. 

*This happens if the penultimate tipset in a proving period is null, causing the cron not to tick at the boundary itself. The problem should be solved if we start executing cron on null tipsets (see https://github.com/filecoin-project/lotus/issues/2234).

**Comment by magik6k** [comment]
Addressed
