### ISSUE TITLE
Sync keeps rolling back + OOM

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2308]
A partner has reported that they seem to be stuck in a "circular" sync that keeps rolling back and restarting the sync process from scratch. This is gonna be pretty hard to debug, but is also weird as hell. 

They also reported an OOM: 
![image](https://user-images.githubusercontent.com/6530144/86869287-4b606700-c0a4-11ea-9449-99f2f3359671.png)

**Comment by arajasek** [comment]
One other partner ran into this...it _might_ be Badger related, but we really don't know.

**Comment by hoffmabc** [comment]
Is this all we have to go on @arajasek? Are there any further logs or anything to provide?

**Comment by arajasek** [comment]
The problem seems to have been resolved with a Badger update, but we should be alert to similar reports.
