### ISSUE TITLE
Different miners have the same peer id

### ISSUE THREAD

**Issue by dnkai** [filecoin-project/lotus#2309]
**Describe the bug**
Different miners have the same peer id

**To Reproduce**

dengkai:lotus dnkai$ ./lotus state  power t0119320
315078800834560(286.6 TiB) / 20317291287609344(18.05 PiB) ~= 1.5507%
dengkai:lotus dnkai$ ./lotus state  power t0111990
0(0 B) / 20317428726562816(18.05 PiB) ~= 0.0000%
dengkai:lotus dnkai$ ./lotus state  miner-info t0111990
Owner:	t0111989
Worker:	t0111989
PeerID:	12D3KooWJpBNhwgvoZ15EB1JwRTRpxgM9D2fwq6eEktrJJG74aP6
SectorSize:	32 GiB (34359738368)
dengkai:lotus dnkai$ ./lotus state  miner-info t0119320
Owner:	t0119319
Worker:	t0119319
PeerID:	12D3KooWJpBNhwgvoZ15EB1JwRTRpxgM9D2fwq6eEktrJJG74aP6
SectorSize:	32 GiB (34359738368)

**Screenshots**
select * from lotus_messages as m where m.to = 't0111990' limit 100

No message found.

**Version (run `lotus version`):**
lotus version 0.4.1+git.9d56dabb

**Comment by travisperson** [comment]
I don't think this is technically an issue. If you think it is, can you explain why?

**Comment by magik6k** [comment]
Miners can do that if they really want to.
