### ISSUE TITLE
messagepool wrong check

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2327]
From a community member:

noticed the other day and forgot to mention but https://github.com/filecoin-project/lotus/blob/cd34d0237739b2006beeee5ceedb73521bb11f06/chain/messagepool/messagepool.go#L120 seems to have the else on the wrong if statement. The else is on the check for gas price but handles an incorrect nonce error. Hope this helps! (edited)

**Comment by magik6k** [comment]
This is correct. If you're adding a message with the same nonce, but GasPremium isn't high enough to trigger RBF, it's basically just an add with duplicate nonce
