### ISSUE TITLE
Consistency in pricing across various parts of lotus

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/lotus#2338]
**Describe the bug**
In various parts of lotus we've seen a few discrepancies in the specification of units. 
* When a miner is setting their  `set-ask --price` seems to take one unit (I believe an int)
* The offline deal proposal takes another (I believe a float)
* The *listed* deals show yet another price (Unclear what units we're in, but the decimal place seems to move). 

**To Reproduce**
More of just observing in those 3 paths.

**Expected behavior**
We'd expect all of these values to be consistent across the different flows. A float of some kind makes sense, but what order of magnitude I'd defer to others. Perhaps if you want to enable people to work with different units they can pass that in as a flag as needed. 

**Screenshots**
Sample deal proposal from @ribasushi : 
![image](https://user-images.githubusercontent.com/21000523/87060962-23265480-c1d9-11ea-8bf1-457eab242c35.png)

Sample output of deals, note the unit difference: 
![image](https://user-images.githubusercontent.com/21000523/87061089-4fda6c00-c1d9-11ea-88a8-41f090fab70e.png)

**Version (run `lotus version`):** 0.4.1

**Additional context**

**Comment by ribasushi** [comment]
Addition: the error on insufficient funds for retrieval currently reads ( verbatim )
```
./lotus client retrieve --car --miner t0120313 bafyreianh75a5gurwbqslabtj2cdw6mriyk6vqgxknkfvdcwvm74vilnqe /srv/lts/c1.car
2020-07-08T22:20:45.751Z        WARN    main    lotus/main.go:81        Retrieval Failed:
    github.com/filecoin-project/lotus/cli.glob..func19
        /home/ipfs/devel/lotus/cli/client.go:473
  - RetrieveUnixfs: Retrieval Error: get or create payment channel: initializing paych actor: mpool push: not enough funds: 0 < 1065353216
```

**Comment by ribasushi** [comment]
Additionally: it is not possible to set fractional pricing with lotus-miner `0.5.10`
```
lotus-miner storage-deals set-ask --price 0.0000001 --verified-price 0.0000001 --max-piece-size 32GiB --duration $(( 24 * 90 ))h
Incorrect Usage: invalid value "0.0000001" for flag -price: parse error
```

**Comment by magik6k** [comment]
I believe we've switched to using FIL everywhere in CLI now
