### ISSUE TITLE
Synchronicity of proposal / acceptance of deal is too fast for offline deals

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/lotus#2339]
**Describe the bug**
When attempting an end-to-end test with lotus 0.4.1 it was observed that when a deal is proposed on what will be “our side”, two things need to happen:
* A 1:1 p2p connection to the miner node needs to take place or the deal will fail
* The miner needs to start importing the prerequisite .car near instantly ( 30 seconds or something ) otherwise the proposer will mark the deal as failed on their `lotus client list-deals` list

This latter issue is a problem as it can make offline deals exceedingly difficult to set up properly at scale. 

**To Reproduce**
[filed on behalf on @ribasushi  who can supply repro steps when he's not heads down]

**Expected behavior**
We’d ideally like the proposer to specify how long a miner can take to confirm that they will store + that they have imported the data (not necessarily the sealing as well).

**Screenshots**

**Version (run `lotus version`):** 0.4.1

**Comment by ribasushi** [comment]
This issue may have been fixed since we last tested: I did not experience similar problems during the butterfly-net recreation of my steps. We really should retest this when the actor-refactor lands ( a week? ) from now.

**Comment by arajasek** [comment]
@ribasushi Curious to know if this is still an issue (the actor refactor has landed).

**Comment by ribasushi** [comment]
@arajasek I will try to retest this in the next ~36h on the live network, thanks for the reminder

**Comment by hoffmabc** [comment]
any updates on this @ribasushi ?

**Comment by ribasushi** [comment]
It *probably* is fixed now, but we never had a chance to run a stresstest of this in filecoin discover to be sure. Closing it for now, will circle back in ~2 weeks when we are ready to pick up stresstesting mega-dealing again.
