### ISSUE TITLE
When deals fail with one party, stale information exists with the other party

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/lotus#2341]
**Describe the bug**
When a deal fails on the proposer side, it is *still* listed as active on the miner, and does not change its status to invalid. 
![image](https://user-images.githubusercontent.com/21000523/87074500-f5e3a180-c1ec-11ea-9dd5-addf6f49215d.png)

This also appears in reverse - we [observed](https://filecoinproject.slack.com/archives/GPY1C3AJU/p1594029946285000) that when a failure appears on the miner side, the proposer (when querying the deal state) will see stale information (e.g. “sealing” even when the deal has failed awhile ago). 

Our first experiments with offline deals resulted in some sector errors that were not translated into the deal state. While the miner listed sectors with a state `CommitFailed`, the miner listed the deals in that sector as `Sealing`. The node client on our side also listed the deal as `Sealing`.

As it is, we'll need to wait for the deal to expire in order to assume the error, as it seems we have no feedback over these sealing errors. Also, maybe unrelated, our miner is currently unable to list its deals via the CLI, but lists them correctly via the JSON RPC API (This does not affect the onboarding flow, just added for the extra information).

**To Reproduce**
[tbd with @ribasushi  when he's no longer heads down]

**Expected behavior**
Chatting with @arajasek , I think we believe this is caused by lost information on the network (i.e. the other side does message out that there's a failure, but that message never reaches the client). 

**Screenshots**

**Version (run `lotus version`):** 0.4.1

**Comment by ribasushi** [comment]
@TippyFlitsUK you personally know this one hasn't been fixed... why close it?

**Comment by TippyFlitsUK** [comment]
@ribasushi 

Hey Peter :wave:

This is just the automated feature of the TSE triage system bringing old and stale tickets to the team's attention.

Thank you for your confirmation! I will make sure that this ticket is added to the correct project board for processing and assignment. :pray:

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
