### ISSUE TITLE
Lotus sync is too hard. It really doesn't work. I haven't synchronized one of my three computers in a month.

### ISSUE THREAD

**Issue by 810106148** [filecoin-project/lotus#2348]
NO:1
lo2@lo2:~$ lotus sync status 
sync status:
worker 0:
	Base:	[bafy2bzacecelmohnrbgkygzlzz6rckqd4cqcqmyrg5bfn6fkbfzcmvwii7l7a]
	Target:	[bafy2bzaceawd2xwbyxugjy47arwqzcbwdbvkdj756qkwukxdwoq3cnzvfi7li bafy2bzacedrmwz6ufaxgfovw3akbea7wp3vkfxpqaw6q6fd7qk5gaonhjg2f4] (69416)
	Height diff:	30619
	Stage: error
	Height: 66554
	Elapsed: 12.317509139s
	Error: chain contained block marked previously as bad ([bafy2bzaceawd2xwbyxugjy47arwqzcbwdbvkdj756qkwukxdwoq3cnzvfi7li bafy2bzacedrmwz6ufaxgfovw3akbea7wp3vkfxpqaw6q6fd7qk5gaonhjg2f4], bafy2bzacebevwgrxqqv5kr4fpl6dawqldwqmiypiuor4qvbf6zwcrndltlmig) (reason: fork past finality)
worker 1:
	Base:	[bafy2bzacecelmohnrbgkygzlzz6rckqd4cqcqmyrg5bfn6fkbfzcmvwii7l7a]
	Target:	[bafy2bzacedetcmn2r4ip754yakepq6jataa7yzxjo65rxejevzy7h6aohzpuc bafy2bzaceaejdde3aheg2a2nkwewej6wgfhpxidjvyv2k72tns56se434ew5w] (72916)
	Height diff:	34119
	Stage: error
	Height: 72916
	Elapsed: 426.815619ms
	Error: chain contained block marked previously as bad ([bafy2bzacedetcmn2r4ip754yakepq6jataa7yzxjo65rxejevzy7h6aohzpuc bafy2bzaceaejdde3aheg2a2nkwewej6wgfhpxidjvyv2k72tns56se434ew5w], bafy2bzaceavowslxnc7anxb7jssa66mr5ckk2vajz7vynmgoid2lrwgd57bg4) (reason: linked to bafy2bzacedrqgpwt4zlxpaifqri3oruubxl76chqflvaljzpl62qg55dctnqg)
worker 2:
	Base:	[bafy2bzacecelmohnrbgkygzlzz6rckqd4cqcqmyrg5bfn6fkbfzcmvwii7l7a]
	Target:	[bafy2bzacedetcmn2r4ip754yakepq6jataa7yzxjo65rxejevzy7h6aohzpuc bafy2bzaceaejdde3aheg2a2nkwewej6wgfhpxidjvyv2k72tns56se434ew5w] (72916)
	Height diff:	34119
	Stage: error
	Height: 72916
	Elapsed: 971.393067ms
	Error: chain contained block marked previously as bad ([bafy2bzacedetcmn2r4ip754yakepq6jataa7yzxjo65rxejevzy7h6aohzpuc bafy2bzaceaejdde3aheg2a2nkwewej6wgfhpxidjvyv2k72tns56se434ew5w], bafy2bzaceavowslxnc7anxb7jssa66mr5ckk2vajz7vynmgoid2lrwgd57bg4) (reason: linked to bafy2bzacedrqgpwt4zlxpaifqri3oruubxl76chqflvaljzpl62qg55dctnqg)
------------------------------------------------------------------------------------------------
NO:2
lo@lo:~$ lotus sync status
sync status:
worker 0:
	Base:	[bafy2bzacednghy3w2e42xqrgeisswleti2uf2dno4ffaieuge2wfrbigqwdv6]
	Target:	[bafy2bzaceasxjwp7xydcg5cmwniahxdppazk3mrybkbpqoxyuzj2ggpcspzku bafy2bzacebb6xf76vr5b2bfd4dltjztgdm5kube7h32accgsbabnjx4p3rl24 bafy2bzacedsaynlan4jvwumft3mklppgv2i47grfv7vhgzxq6ykon5sglunho bafy2bzaceczseini7oorecqpizdfigzbdhksmytd4ib6kzlgapfe5nwsraylk] (61562)
	Height diff:	61562
	Stage: message sync
	Height: 70
	Elapsed: 39h41m57.42449238s
worker 1:
	Base:	[bafy2bzacednghy3w2e42xqrgeisswleti2uf2dno4ffaieuge2wfrbigqwdv6]
	Target:	[bafy2bzaceasxjwp7xydcg5cmwniahxdppazk3mrybkbpqoxyuzj2ggpcspzku bafy2bzacebb6xf76vr5b2bfd4dltjztgdm5kube7h32accgsbabnjx4p3rl24 bafy2bzaceczseini7oorecqpizdfigzbdhksmytd4ib6kzlgapfe5nwsraylk] (61562)
	Height diff:	61562
	Stage: message sync
	Height: 4379
	Elapsed: 47h52m14.473465112s
worker 2:
	Base:	[bafy2bzacednghy3w2e42xqrgeisswleti2uf2dno4ffaieuge2wfrbigqwdv6]
	Target:	[bafy2bzacecxcztpfktajqbtufizqrqqb7vd7k3ohl23r56qzm37ysogpg4pkw bafy2bzacedtixzmr4oobtrqxfhsnmh74znrn6roinzsu23d3wemfkq6b2lxna] (61538)
	Height diff:	61538
	Stage: message sync
	Height: 70
	Elapsed: 39h41m47.228095355s
---------------------------------------------------------------------------------------------
NO:3
iose@lotus1:~$ lotus sync status
sync status:
worker 0:
	Base:	[bafy2bzaceddahaffdsmuap7porhd4tn4vrjca667gtwp5dqh2bowqwd2waumy bafy2bzacec2leygsece7i6tqrp63hpxiha3hjeoi5x3qie2lrqfkdkpkbh7t6 bafy2bzaceabk2zu4gyulj6knts5gv74ank4h3e63vmmqd42enzzmh5brafqm6]
	Target:	[bafy2bzaceakvdh6vs2lf52p3dm57gedzhsafuzkhnkkq4b77wjoatis6o6mla bafy2bzacecuxnlpffw3brzj3lbkv4f7jewwjyw435nwx6kxugrlfsivycf2n6] (70621)
	Height diff:	66121
	Stage: message sync
	Height: 55528
	Elapsed: 16h56m1.935831319s
worker 1:
	Base:	[]
	Target:	[] (0)
	Height diff:	0
	Stage: <unknown: 0>
	Height: 0
worker 2:
	Base:	[]
	Target:	[] (0)
	Height diff:	0
	Stage: <unknown: 0>
	Height: 0

**Comment by arajasek** [comment]
What Lotus version are you using?

**Comment by 810106148** [comment]
lotus version 0.4.0+git.ffa7be86

**Comment by 810106148** [comment]
ubuntu 18.04
cpu E5 Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
mem 256G
hdd 24T

**Comment by arajasek** [comment]
Yes, there was an issue discovered and fixed since then. I would suggest deleting your database and syncing using the latest `master`. It shouldn't take too long.

If you aren't a member of the public Slack channel, please join to stay up-to-date with critical announcements like [this one](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1593721046473700?thread_ts=1593721046.473700).

Thanks for your participation in the Filecoin network!

**Comment by kernelogic** [comment]
How to delete daemon database?
