### ISSUE TITLE
lotus-seal-worker和lotus-storage-miner的关系

### ISSUE THREAD

**Issue by yzn5555** [filecoin-project/lotus#2350]
一直不是特别明白这两者的关系，我理解起来是worker是矿工，storage-miner是存储池，但是矿工操作存储池是怎么操作的不理解，这两个服务器我是在一台机器上部署的，是不是这两个程序启动有先后顺序呀，我看到storage-miner启动使用的是2345端口，然后看到官网说worker启动需要添加参数--address 127.0.0.1:2345   那这两个程序的端口不会冲突吗？  如果我参数中--address 127.0.0.1:3456   用别的端口启动，程序可以启动起来，但是他们之间是通过什么来进行关联的

**Comment by kernelogic** [comment]
先启动miner再启动worker。2345是miner的端口。worker需要知道miner的端口是2345。

**Comment by magik6k** [comment]
See https://docs.filecoin.io/mine/lotus/seal-workers/
