### ISSUE TITLE
云服务器想测试挖矿是否可行

### ISSUE THREAD

**Issue by yzn5555** [filecoin-project/lotus#2351]
使用云服务器是否可以测试挖矿，主要是测试下整个流程，但是挖矿一直卡在密封扇区

**Comment by luozhanxin** [comment]
没有 GPU 计算加速，感觉是不太可行的，

**Comment by yzn5555** [comment]
云服务器看到有CPU实例，不知道是否可用

**Comment by magik6k** [comment]
You can see hardware requirements in https://docs.filecoin.io/mine/hardware-requirements/#general-hardware-requirements
