### ISSUE TITLE
Minimum piece size too large

### ISSUE THREAD

**Issue by ghost** [filecoin-project/lotus#2353]
**Describe the bug**
I think a common test case for new users may be to create a short text file (`Hello, world!`) and try to store it on the Filecoin network.  However, doing so fails with this error in the log:

```
2020-07-10T04:59:35.173Z	WARN	providerstates	providerstates/provider_states.go:355	deal bafyreiez4kqrtmitpqohrvjz3rn5a5xcufdl4bdv2la3eravarb6psbhuy failed: deal rejected: piece size less than minimum required size: 128 < 256
```

My suggestion is that we allow files as small as 1 byte.

**To Reproduce**
```
$ echo "Hello" > file.txt
$ lotus client import file.txt
bafkreifommc4ejsnl72yqeeluewnt2s6y7jfp7i7airh7lzeqssbp3erem
$ lotus client deal bafkreifommc4ejsnl72yqeeluewnt2s6y7jfp7i7airh7lzeqssbp3erem t01029 0.0000000010 30000
$ lotus client list-deals     # will go to failure status within a minute or so
```

**Expected behavior**
I expected lotus to successfully make a storage deal for a file less than 256 bytes.

**Version (run `lotus version`):**
```
$ lotus version
Daemon:  0.4.1+git.0a696f35.dirty+api0.5.0
Local: lotus version 0.4.1+git.0a696f35.dirty
```

**Comment by arajasek** [comment]
@whyrusleeping Will this be feasible / happening?

**Comment by whyrusleeping** [comment]
Best we can do is pad it to the minimum size with 0's. This shouldnt impact anyones hello worlding

**Comment by ribasushi** [comment]
Note: I did some exploration here and cryptolab was uneasy dropping things under 127: https://github.com/filecoin-project/rust-fil-proofs/issues/1231#issuecomment-663915253
I haven't had a chance to circle back into lotus-land to look at the various limits (complex UI is complex)

**Comment by whyrusleeping** [comment]
@mgoelzer ah, but wait a second, looking at your error, it seems that your file *is* getting padded to the minimum acceptable proofs size, but then the miners minimum size for a deal they will accept is set to 256

This feels like a tricky UX question, miners are free to reject deals for any reason they like, we have a field in the ask that specifies what their 'minimum' size is. When making a deal with a miner, should we automatically pad up to the minimum miner size for that miner? 

cc @hannahhoward for more thoughts

**Comment by TippyFlitsUK** [comment]
Hi @ghost

This issue has not been updated in some time. Should we close it or keep it open?
