### ISSUE TITLE
如何通过区块高度来获取相应的区块信息?

### ISSUE THREAD

**Issue by wshhz** [filecoin-project/lotus#2357]
我在rpc api接口中没有找到相关信息

**Comment by lcgogo** [comment]
curl --request POST \
  --url http://localhost:1234/rpc/v0 \
  --header 'content-type: application/json' \
  --data '{ "jsonrpc": "2.0", "method": "Filecoin.ChainGetTipSetByHeight", "params": [
 87392, null], "id": 0 }'

https://github.com/filecoin-project/lotus/blob/master/api/api_full.go

**Comment by rickiey** [comment]
> curl --request POST
> --url http://localhost:1234/rpc/v0
> --header 'content-type: application/json'
> --data '{ "jsonrpc": "2.0", "method": "Filecoin.ChainGetTipSetByHeight", "params": [
> 87392, null], "id": 0 }'
> 
> https://github.com/filecoin-project/lotus/blob/master/api/api_full.go

{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"wrong param count"}}

**Comment by lcgogo** [comment]
> > curl --request POST
> > --url http://localhost:1234/rpc/v0
> > --header 'content-type: application/json'
> > --data '{ "jsonrpc": "2.0", "method": "Filecoin.ChainGetTipSetByHeight", "params": [
> > 87392, null], "id": 0 }'
> > https://github.com/filecoin-project/lotus/blob/master/api/api_full.go
> 
> {"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"wrong param count"}}

你的区块同步完了么？

**Comment by rickiey** [comment]
> > > curl --request POST
> > > --url http://localhost:1234/rpc/v0
> > > --header 'content-type: application/json'
> > > --data '{ "jsonrpc": "2.0", "method": "Filecoin.ChainGetTipSetByHeight", "params": [
> > > 87392, null], "id": 0 }'
> > > https://github.com/filecoin-project/lotus/blob/master/api/api_full.go
> > 
> > 
> > {"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"wrong param count"}}
> 
> 你的区块同步完了么？
参数输入错误了, 现在 OK

**Comment by wshhz** [comment]
我直接使用sdk调接口，已经解决了
