### ISSUE TITLE
Can we specify the max parallel number of tasks for a worker?

### ISSUE THREAD

**Issue by liangping** [filecoin-project/lotus#2359]
Currently, the miner distribute tasks automatically, however, we don't want lotus-seal-worker to parallel process too many sectors. for example,  Miner distributed 4 sectors to one of my worker,  but I only want it to process at most 3 sectors.

I found there's way to set max usage of cpu/mem, but these are not what i wanted.

**Comment by hyunmoon** [comment]
I've always wished the feature was offered officially. 6Block's closed-source binary has been supporting it.

**Comment by jackoelv** [comment]
you can write a little codes to fix it.  it's easy

**Comment by liangping** [comment]
@jackoelv would you love to submit a PR?  since it's easy.

**Comment by askender** [comment]
Same here. I found 3 is fast, 4 is slow/unstable.  I am control it by hand now.

**Comment by liangping** [comment]
> Same here. I found 3 is fast, 4 is slow/unstable. I am control it by hand now.

How did you control it by hand.  if it works when you have 100+ workers.

**Comment by askender** [comment]
I use python.   If you have 100+ workers, I think you have a good programmer too.  
Of cource, make a pull-request to lotus is better.
I think this is a good feature.

**Comment by f8-ptrk** [comment]
i think the current scheduler covers this

#antidisestablishatarianism
