### ISSUE TITLE
websocket: bad handshake

### ISSUE THREAD

**Issue by qiluge** [filecoin-project/lotus#2360]
after I run a lotus daemon, the lotus cli cannot access it.

![image](https://user-images.githubusercontent.com/19525062/87144367-3836dc80-c2da-11ea-9fbd-5c3d546aed40.png)

**Comment by TroyWind** [comment]
check your api token?

**Comment by qiluge** [comment]
> check your api token?

how to check or clean and re-generate it?

**Comment by qiluge** [comment]
I can access my node by ```@filecoin-shipyard/lotus-client-rpc```
![image](https://user-images.githubusercontent.com/19525062/87263058-8d4b3c00-c4ee-11ea-98d5-fdead58a79cc.png)

**Comment by qiluge** [comment]
use `create-token` cmd didn't work too:
```
ubuntu@U-SP-FILECOIN-TEST01:/data/filecoin/lotus$ lotus auth create-token
2020-07-13T10:11:48.823+0800    WARN    main    lotus/main.go:81        websocket: bad handshake
```

**Comment by lcgogo** [comment]
@qiluge  How to solve the issue about 
lotus auth create-token --perm admin
2020-08-06T11:47:45.120Z	WARN	main	lotus/main.go:81	websocket: bad handshake

**Comment by qiluge** [comment]
> @qiluge How to solve the issue about
> lotus auth create-token --perm admin
> 2020-08-06T11:47:45.120Z WARN main lotus/main.go:81 websocket: bad handshake

modify `node/impl/common/common.go` source code, remove jwt verification code, then compile lotus:
![image](https://user-images.githubusercontent.com/19525062/89600961-ec099880-d895-11ea-9d2f-a1828c37b908.png)

**Comment by arielcodes** [comment]
@qiluge I'm experiencing the same issue. Did you add:

`payload.Allow = []auth.Permission{apistruct.PermRead, apistruct.PermWrite, apistruct.PermSign, apistruct.PermAdmin}` to `node/impl/common/common.go`? When I recompile I get `node/impl/common/common.go:49:36: undefined: apistruct`. Thanks!

**Comment by firesWu** [comment]
check your jwt-hmac-secret and token， maybe they don't match.

**Comment by lechatnieger** [comment]
hi how can i check jwt-hmac-secret and token? Thank you

**Comment by firesWu** [comment]
> hi how can i check jwt-hmac-secret and token? Thank you

you can delete token file, and restart you node, it will regenerate.

**Comment by lechatnieger** [comment]
Hi , thank you for your answer, but if I restart my node, my lotus miner
gives me an error, API token need permission admin

If I delete the token while my node is running , the miner starts , but
some command , give error about token permission.

Il giorno sab 31 ott 2020 alle 11:24 fires <notifications@github.com> ha
scritto:

**Comment by firesWu** [comment]
> I delete the token while my node is running , the miner starts , but some command , give error about token permission. Il giorno sab 31 ott 2020 alle 11:24 fires <notifications@github.com> ha

find 'jwt-hmac-secret' in you keystore and delete this file.

**Comment by lechatnieger** [comment]
Thank you very much , you solved my issue. Thank you again

Il giorno sab 31 ott 2020 alle 11:52 fires <notifications@github.com> ha
scritto:

**Comment by rrkltt** [comment]
你好，能告诉我是怎么删除jwt-hmac-secret 密钥库的吗？我遇到跟你一样的问题了

**Comment by rrkltt** [comment]
Hello, can you tell me how to delete the JWT-HMAC-secret keystore? I have the same problem as you

**Comment by noch3** [comment]
@rrkltt The keystore is a directory in `$LOTUS_PATH`. One of the files in there mentions `jwt-hmac-secret`.

**Comment by kordar** [comment]
remove $TMPDIR, all
