### ISSUE TITLE
Thoroughly test storage and retrieval

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2364]
We need to be confident this works if they're gonna be incentives

**Comment by arajasek** [comment]
Maybe includes: offline deals and / or fast-retrieval

**Comment by arajasek** [comment]
We also need a resolution on the blockstores being used on the provider-side (cc @hannahhoward)

**Comment by askender** [comment]
Another question:  do you know when will the feature(update the random-data sector with real-data)  be implemented?

Does that mean people can storage data quickly ?  That is great!      Because storaging data in the sealed sector doesn't need do the sealing again.

**Comment by arajasek** [comment]
@whyrusleeping @ribasushi @jimpick @hannahhoward @magik6k have all been working on this, and discovered a ton of issues along the way. We can keep this issue open for a while longer, but a lot of the work has been done.

**Comment by arajasek** [comment]
We've done a lot of testing, and @hannahhoward is continuing to do some more. We can consider this issue closed.
