### ISSUE TITLE
Test the sector lifecycle

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2365]
Especially newer stuff like CC upgrading

**Comment by arajasek** [comment]
@magik6k was able to successfully upgrade a CC sector -- the replacing sector is proving, and the old sector is on track to expire in ~1k epochs.

**Comment by ribasushi** [comment]
@arajasek @magik6k @mishmosh 

On my miners I am *not observing*
> the old sector is on track to expire in ~1k epochs.

The `OnTime:         1555857` in `sector status --on-chain-info N` stays the same is it was pre-deals. No expiration is forthcoming.

**Comment by ianjdarrow** [comment]
@arajasek can we please re-open this and not close it until a non-PL miner has gotten it to work and it's reflected on the competition dashboard?
