### ISSUE TITLE
Estimate of Sealing Time

### ISSUE THREAD

**Issue by William8Work** [filecoin-project/lotus#2379]
Please provide all the information requested here to help us troubleshoot "commit failed" issues.
If the information requested is missing, we will probably have to just ask you to provide it anyway,
before we can help debug.

**Describe the problem**

The "lotus-storage-miner run" command has been running over 10 hours already. No obvious error but some hello warning (see lotus daemon log below). However, the progress seems really slow on the sealing. How do I estimate the total it will take?

I follow the lotus installation here https://lotu.sh/en+install-lotus-ubuntu and didn't make other configuration or setting changes. Should I do something to optimize it?

*** configuration ***
* 2 CPUs (6 cores each), Intel Xeon E5-2670 @ 2.6GHz
* 192 GB memory, with 64 GB swap on M.2 nvme (total 512gb size)
* 1 GPU Nvidia GTX 1080 Ti
* 15 TB HDD

*** worker list ***
$ lotus-storage-miner workers list
Worker 0, host DX01
	CPU:  [||||||                                                          ] 3 core(s) in use
	RAM:  [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||      ] 92% 174.2 GiB/188.9 GiB
	VMEM: [|||||||||||||||||||||||||||||||||||||||||||||||||               ] 78% 198.2 GiB/252.9 GiB
	GPU: GeForce GTX 1080 Ti, not used

*** miner info ***
$ lotus-storage-miner info
Miner: t0121182
Sector Size: 32 GiB
Byte Power:   0 B / 21.96 PiB (0.0000%)
Actual Power: 0  / 19.7 Pi (0.0000%)
	Committed: 0 B
	Proving: 0 B
Below minimum power threshold, no blocks will be won
Miner Balance: 0
	PreCommit:   0
	Locked:      0
	Available:   0
Worker Balance: 50
Market (Escrow):  0
Market (Locked):  0

Sectors:
	Total: 10
	PreCommit1: 10

*** Storage list ***
$ lotus-storage-miner storage list
eb9156c4-fc9e-473f-a6e8-f55d4cb59e27:
	[|||||                                             ] 1.558 TiB/13.53 TiB 11%
	Unsealed: 10; Sealed: 0; Caches: 0
	Weight: 10; Use: Seal Store
	Local: /media/data1/lotusstorage
	URL: http://127.0.0.1:2345/remote

**Sectors list**

$ lotus-storage-miner sectors list
0: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]
1: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]
2: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]
3: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]
4: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]
5: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]
6: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]
7: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]
8: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]
9: PreCommit1 sSet: NO pSet: NO tktH: 0 seedH: 0 deals: [0]

**Sectors status**

The output of `./lotus-storage-miner sectors status --log <sectorId>` for the failed sector(s).

**Lotus storage miner logs**
2020-07-11T09:07:56.911-0700	INFO	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/client.go:204	rpc output message buffer	{"n": 2}
2020-07-11T09:07:56.912-0700	INFO	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/client.go:204	rpc output message buffer	{"n": 2}
2020-07-11T09:07:56.913-0700	INFO	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/client.go:204	rpc output message buffer	{"n": 2}
2020-07-11T09:13:20.515-0700	INFO	dht/RtRefreshManager	rtrefresh/rt_refresh_manager.go:265	starting refreshing cpl 0 with key  %� (routing table size was 96)

*** lotus daemon log ***
2020-07-11T09:03:23.794-0700	INFO	sub	sub/incoming.go:78	new block over pubsub	{"cid": "bafy2bzacedvmsml3k3mdwavhzc6dndxw2qskqjemgqoihxza2w7ppkfbg5x7s", "source": "12D3KooWRU5Y4nCinLkF1orLyM2hU7cdcUtt5HpjzpoyKG9aNaBB", "msgfetch": 0.000339784}
2020-07-11T09:03:24.095-0700	WARN	modules	modules/services.go:44	failed to say hello	{"error": "protocol not supported", "peer": "12D3KooWEdecLTF2Kq4mDcv179cgoNVrVqG5mYPBzWLWP7ckc2GX"}

**Version**
lotus version 0.4.1+git.8e46753e

**Comment by RobQuistNL** [comment]
You can run the benchmark command from here to figure out specific timings per part: https://github.com/filecoin-project/benchmarks

**Comment by RobQuistNL** [comment]
On Intel it is going to be very slow though. It took my dual E5-2680 v3 machine more than twice as long compared to my AMD 3900x

**Comment by William8Work** [comment]
Thanks. Your help is much appreciated.

So this machine has only 15TB. If I put it to 50TB or 100TB, it would probably never finish :-). So it seems like per machine, we shouldn't attach more than 10TB storage. In stead, maybe use multiple machine to form a cluster, one runs the daemon (daemon node) and run one worker on each machine with storage attached (worker node). Or each machine can run daemon + worker on its own 10 TB, I can build multiple of this 10 TB mining machine to have them run separately.

Which is this the recommended approach (single cluster with multiple worker machines, or multiple single machine as its own mining cluster)?, and also, is there benefit to run multiple workers in each worker node? Can't find any official mining cluster recommendation or materials.

**Comment by UltraVis** [comment]
I would use single cluster with multiple worker matchines. No need to waste RAM for the individual lotus-daemon, which can use 30GB+ RAM, running in worker machines. 
i.e. One machine running lotus-daemon, and the rest of your workers connect to the lotus-daemon machine for Filecoin network access.

**Comment by William8Work** [comment]
Makes sense. Does each worker need to have the GPU, and can it have multiple of worker instances running in the same machine or it's designed to max the parallel processes by itself?

**Comment by William8Work** [comment]
If there are significant storage also available in my other machines, would work be able to leverage those storages as well? Or I need to also run a miner in each of the machines?

**Comment by kernelogic** [comment]
How do you get 10 sectors? Did you run `lotus-storage-miner sectors pledge` 10 times?

**Comment by f8-ptrk** [comment]
i think this can be closed 

#antidisestablishatarianism
