### ISSUE TITLE
Got unexpected error from "Filecoin.StateChangedActors" RPC

### ISSUE THREAD

**Issue by huazhouwang** [filecoin-project/lotus#2382]
**Describe the bug**
I want to calculate the state difference between two blocks, then I found that maybe the RPC method "Filecoin.StateChangedActors" supports it. 
But when I call this method with two block cids, it returns an error, like `cbor input had wrong number of fields`

**To Reproduce**
1. Run 
```shell
curl --request POST \
  --url https://proxy.openworklabs.com/rpc/v0 \
  --header 'content-type: application/json' \
  --data '{
  "jsonrpc": "2.0",
  "method": "Filecoin.StateChangedActors",
  "params": [
    {
      "/": "bafy2bzacecixbzidawnbxvzq6tmbhgoxl64arpcqcqec46ullhqmwmbv6eqmw"
    },
    {
      "/": "bafy2bzacebexiux22rcqzav3hs6ciys66ynodftphvrhtlccj5uobgxz625kw"
    }
  ],
  "id": 0
}'
```
2. See error
```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "error": {
    "code": 1,
    "message": "cbor input had wrong number of fields"
  }
}
```

**Expected behavior**
List of balance differences between two given blocks

**Version (run `lotus version`):**
current version

**Comment by magik6k** [comment]
Those CIDs need to be state roots, which you cen get with `ChainGetBlock(blockCid).ParentStateRoot`
