### ISSUE TITLE
Account for power in small networks correctly

### ISSUE THREAD

**Issue by anorth** [filecoin-project/lotus#2388]
There's a minimum miner size (in power) for miner's to be eligible to win blocks. When no or few miners meet the size requirement, power accounting must ignore it else we might end up with zero or one eligible miners (despite many having at least some proven storage).

In https://github.com/filecoin-project/specs-actors/pull/615 the power actor accounts for power correctly both with and without miners meeting the minimum, providing both `TotalQABytesCommitted` and `TotalQualityAdjPower` (which only counts miners above the threshold). When enforcing the minimum miner size, a node needs to use the right denominator else the sum of the power of miners might not match the denominator used.

The actors provides the `power.State.MinerNominalPowerMeetsConsensusMinimum` function which encapsulates the decision logic of whether a miner is eligible at all (https://github.com/filecoin-project/specs-actors/pull/634). 

- check eligibility with MinerNominalPowerMeetsConsensusMinimum
- divide miner QA power by the right denominator, depending on whether `st.MinerAboveMinPowerCount > ConsensusMinerMinMiners`

Note: this code doesn't necessarily live in the actors project, so please let us know if you prefer to copy it out for rework so we can drop this copy.

FYI @ZenGround0

**Comment by anorth** [comment]
I used to think of this issue as being somewhat academic, but have now realised it's not at all academic if there's only one miner above the minimum in genesis state, and that might might fault.

**Comment by arajasek** [comment]
Closed in #2618
