### ISSUE TITLE
The debug output of a storage miner often corrupts terminal

### ISSUE THREAD

**Issue by ribasushi** [filecoin-project/lotus#2392]
**Describe the bug**
After running for a while, my tmux/screen sessions invariably get hit by the contents of the screenshot

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/356110/87320294-0ec0bf80-c52b-11ea-8200-b80b498bdc17.png">

**Version (run `lotus version`):**
( any branch I've run so far suffers from this )
Screenshot is from `lotus version 0.4.1+git.337c5709` => `337c5709 (HEAD, tag: ntwk-butterfly-7.10.0, origin/ntwk-butterfly) Butterfly network 7/10/2020`

**Comment by Kubuxu** [comment]
@ribasushi fixed in latest master. You can cherry-pick this comit to fix it: https://github.com/filecoin-project/lotus/commit/b0cf3d322896ee085bc072527f2105cf36841fcb
