### ISSUE TITLE
ClientRetrieve: failed to get block for cid

### ISSUE THREAD

**Issue by stefangeorgerobert** [filecoin-project/lotus#2394]
**Describe the bug**
lotus client retrieve fails on lotus version  0.4.1+git.337c5709.dirty

_2020-07-13T17:34:10.370Z	WARN	main	lotus/main.go:81	Retrieval Failed:
    github.com/filecoin-project/lotus/cli.glob..func20
        /root/lotus/cli/client.go:592
  - ClientRetrieve: failed to get block for bafk2bzacebdhzlwfojl3d3d2gfyzbb5c65nzkx5ljfsla5tnstxcuxcpjnb2k: 1 error occurred:
	* get (ds 1): open /root/import5.log: no such file or directory_

**To Reproduce**

1. lotus client import import5.log
_Import 1, Root bafk2bzacebdhzlwfojl3d3d2gfyzbb5c65nzkx5ljfsla5tnstxcuxcpjnb2k_

2. lotus client query-ask t01025
_Ask: t01025
Price per GiB: 0.0000000005
Max Piece size: 512 MiB_

3. lotus client deal bafk2bzacebdhzlwfojl3d3d2gfyzbb5c65nzkx5ljfsla5tnstxcuxcpjnb2k t01025 0.0000000005 30000
_bafyreiaugrgujrsqzq4dzzucyyourph2gddg6bwd2qeunop6mekxy6mtze_

4. lotus client list-deals
_DealCid                                                      DealId  Provider  State               On Chain?  Slashed?  PieceCID                                                       Size     Price      Duration  Message
bafyreiaugrgujrsqzq4dzzucyyourph2gddg6bwd2qeunop6mekxy6mtze  3381    t01025    StorageDealSealing  N          N         bafk4chzadg6ws55rsbwklgx5tsu57fce5acfc2fqtih4etykewnzcbcoxaka  508 KiB  500000000  31828_  
 
5. import5.log (remove local file)

6. lotus client retrieve bafk2bzacebdhzlwfojl3d3d2gfyzbb5c65nzkx5ljfsla5tnstxcuxcpjnb2k test2.out
_2020-07-13T17:34:10.370Z	WARN	main	lotus/main.go:81	Retrieval Failed:
    github.com/filecoin-project/lotus/cli.glob..func20
        /root/lotus/cli/client.go:592
  - ClientRetrieve: failed to get block for bafk2bzacebdhzlwfojl3d3d2gfyzbb5c65nzkx5ljfsla5tnstxcuxcpjnb2k: 1 error occurred:
	* get (ds 1): open /root/import5.log: no such file or directory_

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
lotus version 0.4.1+git.337c5709.dirty

**Additional context**

**Comment by stefangeorgerobert** [comment]
@mishmosh I've reproduced this issue on butterflynet.

**Comment by mishmosh** [comment]
Thanks for the report @stefangeorgerobert. Also tagging @arajasek @momack2.

**Comment by arajasek** [comment]
Thanks for the issue! We have a major overhaul of retrieval going in soon that should fix this.

I'll leave the issue open until then, but to get unblocked for now, can you please run `./lotus client drop <importId>` before you delete the file in step 5? That should work.

Also, can you please use the `ntwk-butterfly-fixups` branch (it's only one commit ahead of `ntwk-butterfly`, but has a retrieval fix in it).

**Comment by mishmosh** [comment]
@stefangeorgerobert has switched to `ntwk-butterfly-fixups` and is waiting for deals to seal. Then will test retrieval.

**Comment by stefangeorgerobert** [comment]
The original file was not deleted , I have the file locally and the retrieve command is failing :

**lotus client import imp1.txt**
Import 2323, Root bafkqajtlnrthg23mmrtgi43mnntg4zdmomfgm43mnntgezdmnntgi3akmzzxgzteomfa

**lotus client list-deals | grep bafyreicjo4oxym33q6qndfnpmgpsxfn2h5nnzhcdrpngfmytehslombjru**
bafyreicjo4oxym33q6qndfnpmgpsxfn2h5nnzhcdrpngfmytehslombjru 4154 t01154  StorageDealActive       Y (epoch 22685) N bafk4chzahulakfoyyorjqpiiw643eb2zgb5pjg2o7oae2jahtozbwihz5qfa 254 B   500000000 35092


**lotus client find bafkqajtlnrthg23mmrtgi43mnntg4zdmomfgm43mnntgezdmnntgi3akmzzxgzteomfa**
LOCAL
ERR t010652@12D3KooWMUY1nTtKVdRzCThjZ2GcYaQFHz1KrAYJqGnbRMviU9qh: retrieval query offer errored: get cid info: No state for /bafkqajtlnrthg23mmrtgi43mnntg4zdmomfgm43mnntgezdmnntgi3akmzzxgzteomfa: datastore: key not found
ERR t01004@12D3KooWAuhmFmTdMKsyKcyvpJ7Pr9cfZXrwAKGpbReKk5hv3L3V: retrieval query offer errored: get cid info: No state for /bafkqajtlnrthg23mmrtgi43mnntg4zdmomfgm43mnntgezdmnntgi3akmzzxgzteomfa: datastore: key not found
ERR t01118@12D3KooWQKeBtqn1SaFrKCn2RcL51c4CfTeWmBVhWnDHPVzWCMro: retrieval query offer errored: get cid info: No state for /bafkqajtlnrthg23mmrtgi43mnntg4zdmomfgm43mnntgezdmnntgi3akmzzxgzteomfa: datastore: key not found
RETRIEVAL t01153@12D3KooWGFWUyvKnwEqo1WXqgcSCR6J5rgrnY6MfGsWErm6WHshQ-0.000000000000000508fil-254 B
ERR t09309@12D3KooWC9HqbZVr4sfz6pekDipj2C5EC9u37ediGUHzjjxSa8ig: retrieval query offer errored: get cid info: No state for /bafkqajtlnrthg23mmrtgi43mnntg4zdmomfgm43mnntgezdmnntgi3akmzzxgzteomfa: datastore: key not found
ERR t09094@12D3KooWDBskLzoeDTutBdyH1acMTfuPXjqQJH2nonUmY9jrs5Ze: retrieval query offer errored: get cid info: No state for /bafkqajtlnrthg23mmrtgi43mnntg4zdmomfgm43mnntgezdmnntgi3akmzzxgzteomfa: datastore: key not found
ERR t09147@12D3KooWLmHFUhqtuzuf5Yw8BtpqmmUaEYG1oZJLsvknDxgdtw9t: retrieval query offer errored: get cid info: No state for /bafkqajtlnrthg23mmrtgi43mnntg4zdmomfgm43mnntgezdmnntgi3akmzzxgzteomfa: datastore: key not found
ERR t01200@12D3KooWBuZQwGe1sMVWRgTbSWqh5hmgKZPEg3vn5RsGadEHpkRD: failed to dial 12D3KooWBuZQwGe1sMVWRgTbSWqh5hmgKZPEg3vn5RsGadEHpkRD: all dials failed
 * [/ip4/127.0.0.1/tcp/35585] dial tcp4 127.0.0.1:35585: connect: connection refused
 * [/ip6/::1/tcp/45359] dial tcp6 [::1]:45359: connect: connection refused
 * [/ip4/113.107.201.166/tcp/35585] dial tcp4 113.107.201.166:35585: connect: connection refused
 * [/ip4/10.20.4.116/tcp/35585] dial tcp4 0.0.0.0:33757->10.20.4.116:35585: i/o timeout

**lotus client retrieve bafkqajtlnrthg23mmrtgi43mnntg4zdmomfgm43mnntgezdmnntgi3akmzzxgzteomfa out_123.data**
2020-07-16T16:16:26.913Z	WARN	main	lotus/main.go:81	The received offer errored: retrieval query offer errored: get cid info: No state for /bafkqajtlnrthg23mmrtgi43mnntg4zdmomfgm43mnntgezdmnntgi3akmzzxgzteomfa: datastore: key not found

**Comment by momack2** [comment]
@stefangeorgerobert - do you still see this issue on calibration net or is this fixed?

**Comment by stefangeorgerobert** [comment]
@momack2 - on calibration net I've found 2 error related to this: 

_2020/07/29:06:58:558  [ INFO ]   ClientFindData [bafk2bzaceas6eqmuvilbq6osgcmpg7cwtdv25gritoi2favb2dzq3y2mab6qe] {"jsonrpc":"2.0","result":[{"Err":"retrieval query offer errored: get cid info: No state for /bafk2bzaceas6eqmuvilbq6osgcmpg7cwtdv25gritoi2favb2dzq3y2mab6qe: datastore: key not found","Root":{"/":"bafk2bzaceas6eqmuvilbq6osgcmpg7cwtdv25gritoi2favb2dzq3y2mab6qe"},"Piece":null,"Size":0,"MinPrice":"0","UnsealPrice":"0","PaymentInterval":1048576,"PaymentIntervalIncrease":1048576,"Miner":"t01693","MinerPeerID":"12D3KooWN22Ysefcn5vxQB92eDXJkUN3uZMFyuQ9v928QqWRxHu3"}],"id":0}
2020/07/30:45:05:858  [ INFO ]   ClientFindData [bafk2bzacecndybvqvwt2biemgixdc7wyqo7xxi6f62yfofhcwv7lrlv2uiplo] {"jsonrpc":"2.0","result":[{"Err":"retrieval query offer errored: get cid info: No state for /bafk2bzacecndybvqvwt2biemgixdc7wyqo7xxi6f62yfofhcwv7lrlv2uiplo: datastore: key not found","Root":{"/":"bafk2bzacecndybvqvwt2biemgixdc7wyqo7xxi6f62yfofhcwv7lrlv2uiplo"},"Piece":null,"Size":0,"MinPrice":"0","UnsealPrice":"0","PaymentInterval":1048576,"PaymentIntervalIncrease":1048576,"Miner":"t01693","MinerPeerID":"12D3KooWN22Ysefcn5vxQB92eDXJkUN3uZMFyuQ9v928QqWRxHu3"}],"id":0}_

**Comment by arajasek** [comment]
This **may** be fixed by https://github.com/filecoin-project/sector-storage/pull/88

**Comment by arajasek** [comment]
Closing this issue, if it re-emerges, please re-open.
