### ISSUE TITLE
Option to suppress `InsecurePoStValidation` warnings logs

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/lotus#2397]
For testing purposes. The option should be as explicit as possible to make sure that this is suppressed only if the developer really knows what they are doing, and should be a different configuration channel (not another build flag), ideas? env.var?

**Comment by whyrusleeping** [comment]
not a perfect solution, but `lotus log set-level --system=chain error` should accomplish this, at the cost of muting all other non-error logs in the chain package

**Comment by schomatis** [comment]
Resolved in https://github.com/filecoin-project/lotus/pull/2415.
