### ISSUE TITLE
sectors remove command doesn't update the sector list output

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#2400]
**Describe the bug**
After removing a sector, `sectors list` continues to show the sector in the state that it was in before being removed.

**To Reproduce**
1. `lotus-storage-miner sectors pledge`
2. `lotus-storage-miner sectors remove --really-do-it 0` once the sector has reached PreCommit1
3. `lotus-storage-miner sectors list` will show output that suggests that the sector is still in PreCommit1, i.e.
```
$ lotus-storage-miner sectors list
0: PreCommit1 ....
```

**Expected behavior**
After removing the sector, `sectors list` output should either not show the sector at all or is should label it as removed, i.e.
```
$ lotus-storage-miner sectors list
0: Removed
```

**Screenshots**

**Version (run `lotus version`):**
Daemon:  0.4.1+git.5de7b62d+api0.5.0
Local: lotus version 0.4.1+git.5de7b62d

**Additional context**

**Comment by chunqizhi** [comment]
if the sector state is proving before, then the remove command is ok.
![image](https://user-images.githubusercontent.com/23360623/87405922-a6d5ac00-c5f2-11ea-9218-a28d57a80824.png)

**Comment by f8-ptrk** [comment]
resolved

#antidisestablishatarianism
