### ISSUE TITLE
Why the files stored in datastore/chain are different?

### ISSUE THREAD

**Issue by lcgogo** [filecoin-project/lotus#2402]
I have run 2 lotus daemon in 2 servers.

One has 56GB and the other has 36GB in datastore/chain folder. 
After printout the file name, there are diff files. 
And the files which have the same name have diff sizes.

**Comment by magik6k** [comment]
We've changed some badger settings recently which should result in what you're seeing - https://github.com/filecoin-project/lotus/pull/2319
