### ISSUE TITLE
[Bug report] websocket: bad handshake

### ISSUE THREAD

**Issue by qiluge** [filecoin-project/lotus#2403]
**Describe the bug**
After I run lotus daemon, I could not use lotus cli to connect it. The cli always log `websocket: bad handshake`.

**To Reproduce**
1. start lotus daemon, use environment variable ```export LOTUS_PATH=/data/filecoin/lotus/data```;
2. lotus sync to latest block;
3. modify ```/data/filecoin/lotus/data/config.toml```, set ```ListenAddress = "/ip4/0.0.0.0/tcp/20330/http"```;
4. restart lotus daemon;
5. the daemon listen at `20330` port: `tcp        0      0 0.0.0.0:20330           0.0.0.0:*               LISTEN      96108/lotus`;
6. use lotus cli to access lotus service, but it report `websocket: bad handshake`.

**Expected behavior**
lotus can be used normally

**Screenshots**
enrironment variable at `~/.bashrc`:
![image](https://user-images.githubusercontent.com/19525062/87394441-5fdfba80-c5e2-11ea-890d-a559fb4af2e2.png)
config.toml:
![image](https://user-images.githubusercontent.com/19525062/87394596-8f8ec280-c5e2-11ea-96ec-8268f94234da.png)

lotus cli output:
![image](https://user-images.githubusercontent.com/19525062/87394305-2d35c200-c5e2-11ea-8d0c-d82a909eff14.png)

**Version (run `lotus version`): lotus version 0.4.1+git.2836b521

**Additional context**

**Comment by qiluge** [comment]
refer: https://github.com/filecoin-project/lotus/issues/2360

**Comment by lcgogo** [comment]
same issue

**Comment by arajasek** [comment]
See #2360

**Comment by naiyoma** [comment]
I get the same error when I try `lotus wallet new bls`
