### ISSUE TITLE
1060 3GB not officially supported?

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#2420]
Getting this warning when sealing. But according to document there's no mention saying 3GB version of 1060 is NOT supported?

WARN bellperson::gpu::utils > Number of CUDA cores for your device (GeForce GTX 1060 3GB) is unknown! Best performance is only achieved when the number of CUDA cores is known! You can find the instructions on how to support custom GPUs here: https://lotu.sh/en+hardware-mining

**Comment by magik6k** [comment]
You need more than 4G of vram to run sealing operations on a GPU, the 3GB variant of this card likely won't work

**Comment by magik6k** [comment]
(We should probably remove this card from the supported list)

**Comment by liyunpeng** [comment]
Number of CUDA cores for your device (NVIDIA GeForce GTX 1080 Ti) is unknown! Best performance is only achieved when the number of CUDA cores is known!

**Comment by liyunpeng** [comment]
I also encounter this problem, use lutus 1.6,  Is the  GeForce GTX 1080 Ti card supported by lotus 1.6 ?

**Comment by kernelogic** [comment]
@liyunpeng you can use environment variable to force use it.

**Comment by liyunpeng** [comment]
# echo $BELLMAN_CUSTOM_GPU
GeForce GTX 1080 Ti:3584

**Comment by liyunpeng** [comment]
> @liyunpeng you can use environment variable to force use it.
I have set it :  
# echo $BELLMAN_CUSTOM_GPU
GeForce GTX 1080 Ti:3584

**Comment by liyunpeng** [comment]
> I also encounter this problem, use lutus 1.6, Is the GeForce GTX 1080 Ti card supported by lotus 1.6 ?



> @liyunpeng you can use environment variable to force use it.

I have set it  echo $BELLMAN_CUSTOM_GPU
GeForce GTX 1080 Ti:3584  what else need to set?

**Comment by f8-ptrk** [comment]
what @magik6k said and then i think this can be closed

#antidisestablishatarianism

**Comment by jennijuju** [comment]
@jennijuju double check the hardware support list
