### ISSUE TITLE
Where is --max-parallel option on miner?

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#2434]
Various online documents saying I could use command like this to specify how many tasks the miner can be running at the same time `lotus-storage-miner run --max-parallel 1`

However when I try it it says "lotus-storage-miner/main.go:94	flag provided but not defined: -max-parallel"

**Comment by jimpick** [comment]
I suspect this is a custom feature in the 6block lotus-miner fork.

https://github.com/shannon-6block/lotus-miner/blob/master/README_en.md

**Comment by kernelogic** [comment]
Thank you!
