### ISSUE TITLE
SealRandomness shouldn't be tied to the chain

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2435]
Blocked by #2148 

A second randomness function, `GetVRFRandomness` should be created, and used for `SealRandomness`.

**Comment by nicola** [comment]
SealRandomness must be tied to the chain and it is happening in specs actors (see https://github.com/filecoin-project/specs-actors/pull/679/files#diff-e47fb4c42d791672c9550edb1dc5f969R1887) and lotus serves the correct randomness here https://github.com/filecoin-project/lotus/blob/d552803f56d5102c20b7a10dc4d6505b1698b12c/chain/store/store.go#L1058-L1087
