### ISSUE TITLE
lotus-storage-miner sectors seal command does not work and cause sector list error

### ISSUE THREAD

**Issue by chunqizhi** [filecoin-project/lotus#2437]
lotus-storage-miner sectors seal 11
![image](https://user-images.githubusercontent.com/23360623/87645052-871fbe80-c77f-11ea-85c1-93a526a066ce.png)
lotus-storage-miner sectors list, sector 0 double!!!
![image](https://user-images.githubusercontent.com/23360623/87645115-9dc61580-c77f-11ea-8139-a50f03d699d9.png)

**Comment by f8-ptrk** [comment]
i think this is resolved
