### ISSUE TITLE
API documentation improvements

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#2445]
There is a tool in the Lotus source code for generating markdown documentation for the API methods from the Go source code:

https://github.com/filecoin-project/lotus/blob/master/api/docgen/docgen.go

Example output is here (temporarily):

https://filecoin-shipyard.github.io/js-lotus-client/api/full-node/state.html

The generated docs have example output and method-level comments from Go.

Presently, there is not parameter level documentation (names of parameters, descriptions, types, defaults).

The lack of parameter level documentation means it is difficult for developers to understand what they should be passing to the API. It is also difficult to understand if the implemented API is doing the right thing as the intention is documented in many different places currently (specs, internal design docs, etc.)

I'd like to move the API documentation to docs.filecoin.io -- it could live on lotu.sh, but we want docs.filecoin.io to be a "one stop shop" for developer documentation. Also, although there are going to be multiple Filecoin implementations, I think we should strive towards delivering a common API that works with any implementation.

**Comment by arajasek** [comment]
Thanks for the issue, there's definitely work to be done here!

The GoDocs also have a bit more info about API-specific params (all self-documenting), see, for instance: https://godoc.org/github.com/filecoin-project/lotus/api#StartDealParams.

> I think we should strive towards delivering a common API that works with any implementation.

There's definitely a conversation to be had here, but I am rather strongly opposed to this idea.

**Comment by jimpick** [comment]
Right now, Lotus is the main implementation. I imagine the newer implementations will try to maintain compatibility at the API level.

If each implementation has a different API, developers who want their code to work with multiple implementations will need to do more work to support each implementation one-by-one.

**Comment by jennijuju** [comment]
duplicated #4544
