### ISSUE TITLE
abi.SectorID.Number  has bug

### ISSUE THREAD

**Issue by gavin-ygy** [filecoin-project/lotus#2452]
**Describe the bug**
if the abi.SectorID.Number is a uint64 digit eg:1152921504606846980(0x1000 0000 0000 0004),  the  sealprecommit2 will fail.
At the same cluster , the abi.SectorID.Number =6  can finish proving.

**To Reproduce**
1.  change the sid in storage-fsm/garbage.go
func (m *Sealing) PledgeSector() error {
	go func() {
   //...
            headFlag := 1 << 60    
            sid +=abi.SectorNumber(headFlag)
            err = m.sealer.NewSector(ctx, m.minerSector(sid))
 //...
       }
}
2. See error
      sealprecommit1 can finish using the uint64 digit, but sealprecommit2  will fail  during handlePreCommitWait() (reporting: sector precommit failed: 20)
**Expected behavior**
a real uint64 abi.SectorID.Number should not report error, because the abi.SectorID.Number is defined uinit64 in the Spec.

**Screenshots**

**Version (run `lotus version`):**
lotus version 0.4.1+git.9d56dabb.dirty
**Additional context**

**Comment by whyrusleeping** [comment]
Valid sector IDs have typically been in the range of 2^48, this might be changing soon to be a bit higher, but it will not allow the full range of a uint64.

cc @Stebalien for more recent details.

**Comment by Stebalien** [comment]
The max range will likely be `2^63-1` (max int64, not max uint64). I've filed a bug to validate sector numbers: https://github.com/filecoin-project/specs-actors/issues/698.

**Comment by arajasek** [comment]
Resolved, see https://github.com/filecoin-project/specs-actors/issues/698
