### ISSUE TITLE
LockedFunds will be less than InitialPledgeRequirement

### ISSUE THREAD

**Issue by yangchuang123456** [filecoin-project/lotus#2454]
**Describe the problem**

The LockedFunds will be less than InitialPledgeRequirement in miner actor when many faulty sectors are recoveried because of the faulty penalty.  In this situation, my ProveCommitSector will always be failed, because the function verifyPledgeMeetsInitialRequirements can't pass. 

**Lotus storage miner logs**

![image](https://user-images.githubusercontent.com/33644450/87786495-9466a700-c86c-11ea-9e55-93aafe3b998c.png)

**Comment by rjan90** [comment]
Hi @yangchuang123456!

Thanks for the report. The issue is outdated, and not relevant anymore.

If this is a issue in current release please open a new ticket.

Thanks again !
