### ISSUE TITLE
go command not found using sudo make install

### ISSUE THREAD

**Issue by bbrout** [filecoin-project/lotus#2463]
**Describe the bug**

installed dependencies:
sudo apt update
sudo apt install mesa-opencl-icd ocl-icd-opencl-dev gcc git bzr jq pkg-config curl
sudo apt upgrade

Installed go from https://golang.org/doc/install
successfully ran test

placed go into path 
export PATH=$PATH:/usr/local/go/bin

cloned Lotus from home directory
git clone https://github.com/filecoin-project/lotus.git

cd to lotus/

ran make clean && make all
result:
Caution: you have an existing lotus binary in your PATH. This may cause problems if you don't run 'sudo make install'

All looks successful up to here. However, running sudo make install results in:

bash: go: command not found
expr: syntax error: unexpected argument ‘14’
install -C ./lotus /usr/local/bin/lotus
install -C ./lotus-storage-miner /usr/local/bin/lotus-storage-miner
install -C ./lotus-seal-worker /usr/local/bin/lotus-seal-worker

have retried the export PATH command and tried to find argument '14' with no luck.

I am using Ubuntu V20.04

can you help please?

**Comment by RobQuistNL** [comment]
It should actually still work (I see the same errors, but the binaries are installed and work), but the syntax error might be something that needs some investigation :mag:

**Comment by bbrout** [comment]
Thank you for your comment. It is only the make command which produces the binaries but they are objects and need to be linked and installed into the correct place. The sudo make install should simply work. The error is that go is not installed or cannot be found. Yet I can invoke go without any problem. It looks like an error in the MAKEFILE.

**Comment by kernelogic** [comment]
/etc/sudoers has restricted PATH environment variable.

**Comment by Shekelme** [comment]
Same here, exactly as described above, Ubuntu 20.04.

`bash: go: command not found
expr: syntax error: unexpected argument ‘14’`

**Comment by bbrout** [comment]
@kernelogic The install error occurs on line 14 of a particular bash command in MAKEFILE.  Your comment: _Need to add /usr/local/go/bin to the "safe" PATH in that file._ sounds completely correct. I am finding difficulty in knowing which file? I assume it was invoked by MAKEFILE. Or should the PATH be added prior to make install? I think that would work as a quick and dirty fix and a PATH command at the top of MAKFILE would do the trick. I'll try that.

**Comment by bbrout** [comment]
Update: didn't work. Where should the PATH variable be placed?

**Comment by arajasek** [comment]
Not an expert myself, but [this](https://www.jetbrains.com/help/go/configuring-goroot-and-gopath.html) might be helpful?

**Comment by kmikityuk** [comment]
The same error as described above today while attempting to update lotus. Any solution?

**Comment by bbrout** [comment]
I have installed Lotus and so far it is successful. I was trying to go
through this error and managed to mess up my chain and could not do
anything. So I deleted whatever I could and re-installed to get everything
to work. So far so good. Going back over the Makefile in the compile
section I believe there is a flag set with the variable GOFLAGS that is
used on lines 25 and 68 of the Makefile. I don't know yet what that flag is
supposed to do. It may be that the developers have failed to put a limit on
the number of flags and only 13 are needed and when it hits the 14th one,
it's hooped.

I also tried a sudo make uninstall which hits the same error of a variable
'14' needed. So there is not a clean uninstall. Also make check is not in
the Makefile. make check is just to make a target called check. It doesn't
do anything other than tell you what may be a problem in the compiles, like
missing dependencies. You have to do the make all since that is a target
for sudo make install.

It looks like this error is cosmetic but it creates problems if you try to
'fix' it. I'll continue to look at some way to debug this. So far, whoever
wrote the Makefile is probably busy doing other things and I don't really
know what is happening with the install. I'll keep at it.

So far, ignoring the error, I can get the faucet to work. Now to get the
miner to work.



 WWW.GreenNABR.com

**Comment by kernelogic** [comment]
@bbrout the filename I mentioned is in my comment, it's called "/etc/sudoers"

**Comment by kernelogic** [comment]
When I am in need of rebuilding lotus, I would 
1. rm /usr/local/bin/lotus*
2. delete cloned lotus source file and re-clone
3. make build with regular user (somehow when I build with root it fails)
4. make install with sudo

**Comment by bbrout** [comment]
Thanks to Kernelogic. Issue has a workaround but it is quite convoluted.
After installing go as per instructions.
cd  /etc
sudo visudo ****warning: DO NOT USE ANY OTHER EDITOR THAN VISUDO AND KNOW WHAT YOU ARE DOING!!!****
go to the line:
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
and append the line with :/usr/local/go/bin" to read:
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin"

Then save the file and exit.
Continue to install lotus according to directions. The error will be gone.

NOTE: before installing, kill the daemon and remove previous installation as per:

rm /usr/local/bin/lotus*
delete cloned lotus source file and re-clone
make build with regular user (somehow when I build with root it fails)
make install with sudo

as per instructions from kernelogic.

This issue is resolved from a rather dangerous workaround. If you do not use visudo you will crap out your sudo privileges and will need a major repair from the GRUB menu as root. I had to do that and it is not pretty.  Therefore I am not closing this issue since it keeps popping up with other users and a correction has to be made in Makefile to get around this bug.

**Comment by bbrout** [comment]
@kernelogic You also have to add

rm -rf .lotus

to remove the chain and virtual storage area.

**Comment by kernelogic** [comment]
I wouldn't delete the whole .lotus because it also contains the account private keys. Just delete .lotus/datastore should be fine.

**Comment by rmacinnis** [comment]
sudo env PATH=$PATH make clean all

The problem is sudo does -not- preserve the environment variables from the user's context, so even if you did the proper 'export PATH=$PATH:/usr/local/go/bin' once you call 'sudo make' those variables get blown away. To carry them along with you (without using 'visudo') just run the command as above.

**Comment by GlacierWalrus** [comment]
If you're a fish user your path won't be bash compatible (makefile invokes bash) so you'll need to convert your path like so:
```fish
sudo env PATH=(echo $PATH | sed 's/ /:/g') make clean all
```
