### ISSUE TITLE
Can woker1 be designated to sectors pledge?

### ISSUE THREAD

**Issue by 810106148** [filecoin-project/lotus#2470]
iose@lotus1:~$ lotus-storage-miner workers list
Worker 0, host lotus1
	CPU:  [||                                                              ] 2 core(s) in use
	RAM:  [|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||   ] 95% 119.9 GiB/125.7 GiB
	VMEM: [||||||||||||||||||||||||||||||||||||                            ] 57% 135.9 GiB/237.5 GiB
	GPU: GeForce RTX 2080 Ti, not used
	GPU: GeForce RTX 2080 Ti, not used
Worker 1, host amd
	CPU:  [                                                                ] 0 core(s) in use
	RAM:  [|                                                               ] 1% 2.199 GiB/125.7 GiB
	VMEM: [                                                                ] 0% 2.199 GiB/244.9 GiB

iose@lotus1:~$ lotus-storage-miner sectors pledge

2020-07-18T21:16:13.785+0800	DEBUG	advmgr	sector-storage@v0.0.0-20200630180318-4c1968f62a8f/sched.go:404	sched: not scheduling on worker 0; not enough physical memory - need: 156549M, have 128703M

Can woker1 be designated to sectors pledge?

**Comment by magik6k** [comment]
Yes, we've added support for this a while ago
