### ISSUE TITLE
After pulling the file from the remote end, it is prompted that the file cannot be found.

### ISSUE THREAD

**Issue by btcioner** [filecoin-project/lotus#2472]
**Describe the bug**
After pulling the file from the remote end, it is prompted that the file cannot be found.

**To Reproduce**
1. Run '...'
2. See error
`2020-07-18T21:32:38.355Z	INFO	stores	stores/remote.go:165	Fetch http://192.168.10.12:2345/remote/sealed/s-t0119698-64 -> /data/sealed/s-t0119698-64
2020-07-18T21:34:20.017Z	INFO	stores	stores/remote.go:251	Delete http://192.168.10.12:2345/remote/sealed/s-t0119698-64
2020-07-18T21:34:20.020Z	WARN	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/handler.go:226	error in RPC call to 'Filecoin.Fetch': allocate local sector for fetching:
    github.com/filecoin-project/sector-storage/stores.(*Remote).acquireFromRemote
        /home/test/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200630180318-4c1968f62a8f/stores/remote.go:138
  - couldn't find a suitable path for a sector:
    github.com/filecoin-project/sector-storage/stores.(*Local).AcquireSector
        /home/test/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200630180318-4c1968f62a8f/stores/local.go:279
`
**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
Local: lotus version 0.4.1+git.a87899dd.dirty
**Additional context**

**Comment by panol** [comment]
same problem

**Comment by GalaIO** [comment]
I get this error when run worker on other machine, how to fix it

**Comment by skyhuihui** [comment]
I get this error when run worker on other machine, how to fix it。   https://app.slack.com/client/TEHTVS1L6/C017CCH1MHB/thread/C017CCH1MHB-1596163143.140100?cdn_fallback=1

**Comment by magik6k** [comment]
This was an issue with storage reservation, which is now fixed
