### ISSUE TITLE
butterflynet: lotus client import returns a really long CID

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#2487]
**Describe the bug**

```
$ ./lotus client import /home/ubuntu/tmp/seal.jpg 
Import 10, Root bafyaa4asfyfcmakvudsaeiaxi25hifvrnuwwqh5kl3hn7zysxdimchuxnllbrvzbbhn2my7boijaageaqbabelqkeyavliheaiqoizfeekow64ww6ibex2q62au7dstwjrtjpjwih4yx357q3s5pvqasaamj3zjdbihaqaqytxswgieaqbacbhpfem
```

![seal](https://user-images.githubusercontent.com/20886/87984183-6d87bb00-ca8e-11ea-8315-d61cf20bfaba.jpg)

https://gateway.ipfs.io/ipfs/QmWhfrcFT6A9b245ttyFjDsr6uCzUDcdJ87vECcEzU8Rbi

**Version (run `lotus version`):**

```
$ ./lotus version
Daemon:  0.4.1+git.556ea9db+api0.8.0
Local: lotus version 0.4.1+git.556ea9db
```

**Comment by jimpick** [comment]
Discussion on Slack: https://filecoinproject.slack.com/archives/CP50PPW2X/p1595277326336300

**Comment by rjan90** [comment]
Hey @jimpick!

I´m going through some old issues to see if something can be closed. Did you ever find out if this was expected, or if it´s a bug? I tried to import the same jpg with the current lotus-version (lotus v1.15.0), and got the same long CID output as you.
