### ISSUE TITLE
Constraint Drand round time ≤ Filecoin blocktime not respected

### ISSUE THREAD

**Issue by nicola** [filecoin-project/lotus#2499]
**Describe the bug**
I originally saw (in [lotus code](https://github.com/filecoin-project/lotus/blob/master/build/params_shared_vals.go#L102)) and I read "period: 25", assuming that drand round is 25s.

Given our analysis there must be at least one drand entry per block (for the slow catchup mode to fully work). Having less than 1 drand per block allows miners to rush during catch-up on some epochs (e.g. if drand is 30 and lotus is 25, they can catch up every 5 blocks).

We do not have analysis that show that the impact of a single rush every few epochs is insecure nor that it insecure, however, we do know that one drand per round is secure.

Proposal:
- **Proposal 1: Change Filecoin blocktime:** Set Filecoin block time to ≥30s
- **Proposal 2: Change Filecoin blocktime:** Set Drand round time to ≤25s

**Comment by jsoares** [comment]
I left some comments in previous [slack](https://protocollabs.slack.com/archives/CV3QN4HGW/p1594728758496500?thread_ts=1594725710.494000&cid=CV3QN4HGW) [threads](https://protocollabs.slack.com/archives/CV3QN4HGW/p1594798799038100?thread_ts=1594763021.034900&cid=CV3QN4HGW):

> As a side note, and in regards to the LoE and selling this to partners, what is key is having sensible parameters. Even if it's the same technically, it's very different to set up the network with <period=30s, catch-up period=5s> or <period=25s, catch-up period=6s>, the second clearly not being in the best interest of the network and instead driven by someone else. There will need to be flexibility to tune FIL parameters to work with what drand can pragmatically provide.

> Unless there are strong reasons for it, I think we should stick with 30s. Going down to 15s will mean doubling the chain growth (to ~8GB/year) and sync time, and 25s is just a stupid number. Furthermore, anything other than 30s will require explanation.

The LoE mainnet has always been running with a period of 30s. There are no plans to change it but, if we were to do it, the _reasonable_ option would be 15s. The issue, of course, is that this increases resource usage for the partners (who, I remind you, are doing this voluntarily and with no financial return) and will make onboarding future partners more and more time-consuming. 

When faced with changing things in Filecoin or the LoE, the default should always be to change things on our end: we have to remember that the LoE is not a Filecoin component or PL project but a public service of which we're only one of many partners, with only so much influence to spend.

**Comment by hsanjuan** [comment]
> the reasonable option would be 15s

If slow catchup is a thing in the end, reducing the period means it will take more time to catch up in case of downtimes (unsure what is the period during catch up phases).

**Comment by jsoares** [comment]
Truth be told, 20s is _reasonable_ too. The constraint, in my view, is that the period aligns to the minute boundary so that we don't have a variable number of rounds each minute.

**Comment by nicola** [comment]
Any of these options will work:
- Filecoin 30s, Drand 30s
- Filecoin 25s, Drand 25s or 15s

**Comment by nicola** [comment]
We have agreed to move to Filecoin Blocktime 30s
