### ISSUE TITLE
Pick the network to connect to based on some CLI flag

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2503]
Once we actually have multiple networks running the same code, we should configure Lotus to receive some `--testnet` flag to connect to a test network (connecting to `mainnet` by default).

**Comment by rjan90** [comment]
Hey @arajasek!

Is connecting to a certain network based on a CLI flag still a desired feature we want? Or is the current `make calibnet`, `make butterflynet`, etc, sufficient?
