### ISSUE TITLE
Setting log level for lotus-miner changes the logging level of lotus daemon

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#2512]
**Describe the bug**
Setting log level for lotus-miner changes the logging level of lotus daemon

**To Reproduce**
1. Have both daemon and miner running
2. `lotus-miner log set-level debug`
3. Look at lotus daemon logs and see that it is now printing debug level logs.

**Expected behavior**
Only the subsystems of the binary that call `log set-level` should be changed.

**Screenshots**

**Version (run `lotus version`):**
lotus version 0.4.1+git.b84030b3

**Additional context**

**Comment by f8-ptrk** [comment]
should be resolved

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
