### ISSUE TITLE
Chainwatch high cpu usage and repeating actor change error.

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#2514]
We are seeing a high cpu utilization in chainwatch at the moment. It was a sudden spike in CPU activity from from ~8 to 100%

Wee see the same 3 logs repeated over and over. Two elapse timestamps followed by an error `Failed to handle message changes: pq: value \"2679838544\" is out of range for type integer`, `Failed to handle actor changes...retrying`.

https://gist.githubusercontent.com/travisperson/85b9fbe71d82131a6c3351cfa393cdfe/raw/52f1436c1505eaef15ba9814d2bfb187327fe2bf/gistfile1.txt

Seem to be due to missing err returns `HandleMinerChanges`

https://github.com/filecoin-project/lotus/blob/b84030b3bdf19b953cbf330710453d20f3f3abfd/cmd/lotus-chainwatch/processor/miner.go#L165-L179

It's part of an error group

https://github.com/filecoin-project/lotus/blob/b84030b3bdf19b953cbf330710453d20f3f3abfd/cmd/lotus-chainwatch/processor/processor.go#L136-L141

So I assume this results in the same block returned by over and over again by `unprocessedBlocks`

https://github.com/filecoin-project/lotus/blob/b84030b3bdf19b953cbf330710453d20f3f3abfd/cmd/lotus-chainwatch/processor/processor.go#L108

Additionally, when restarting the process, we see the issue immediately return.

**Comment by travisperson** [comment]
https://gist.githubusercontent.com/travisperson/373dd0c897498a7c5df4c979b3981da0/raw/b9e8aecdfdc88f6ecdf6a69f2a083633b4e7a35c/gistfile1.txt

**Comment by magik6k** [comment]
This got fixed in https://github.com/filecoin-project/lotus/pull/2501
