### ISSUE TITLE
How to recover after losing computing power.

### ISSUE THREAD

**Issue by 810106148** [filecoin-project/lotus#2518]
iose@lotus1:~$ lotus-miner sectors list
0: Proving       sSet: YES active: YES tktH: 59   seedH: 1123 deals: [0]
1: Proving       sSet: YES active: YES tktH: 118  seedH: 1181 deals: [0]
2: Proving       sSet: YES active: YES tktH: 118  seedH: 1183 deals: [0]
3: Proving       sSet: YES active: YES tktH: 168  seedH: 1231 deals: [0]
4: Proving       sSet: YES active: NO  tktH: 255  seedH: 1324 deals: [0]
5: Proving       sSet: YES active: NO  tktH: 256  seedH: 1325 deals: [0]
6: Proving       sSet: YES active: NO  tktH: 261  seedH: 1327 deals: [0]
7: Proving       sSet: YES active: NO  tktH: 261  seedH: 1328 deals: [0]
8: Proving       sSet: YES active: NO  tktH: 292  seedH: 1356 deals: [0]
9: Proving       sSet: YES active: NO  tktH: 292  seedH: 1357 deals: [0]
10: Proving      sSet: YES active: NO  tktH: 293  seedH: 1359 deals: [0]
11: Proving      sSet: YES active: NO  tktH: 306  seedH: 1380 deals: [0]
12: Proving      sSet: YES active: NO  tktH: 306  seedH: 1380 deals: [0]
13: Proving      sSet: YES active: NO  tktH: 316  seedH: 1381 deals: [0]
14: Proving      sSet: YES active: NO  tktH: 335  seedH: 1415 deals: [0]
15: Proving      sSet: YES active: NO  tktH: 336  seedH: 1426 deals: [0]
16: Proving      sSet: YES active: NO  tktH: 336  seedH: 1427 deals: [0]
17: Proving      sSet: YES active: NO  tktH: 337  seedH: 1429 deals: [0]
18: Proving      sSet: YES active: NO  tktH: 337  seedH: 1430 deals: [0]
19: Proving      sSet: YES active: NO  tktH: 337  seedH: 1431 deals: [0]
20: Proving      sSet: YES active: NO  tktH: 338  seedH: 1433 deals: [0]
21: Proving      sSet: YES active: NO  tktH: 338  seedH: 1436 deals: [0]
22: Proving      sSet: YES active: NO  tktH: 338  seedH: 1436 deals: [0]
23: Proving      sSet: YES active: NO  tktH: 338  seedH: 1438 deals: [0]
24: Proving      sSet: YES active: NO  tktH: 338  seedH: 1438 deals: [0]
25: Proving      sSet: YES active: NO  tktH: 338  seedH: 1441 deals: [0]
26: Proving      sSet: YES active: NO  tktH: 338  seedH: 1441 deals: [0]
27: Proving      sSet: YES active: NO  tktH: 338  seedH: 1443 deals: [0]
28: Proving      sSet: YES active: NO  tktH: 338  seedH: 1444 deals: [0]
29: Proving      sSet: YES active: NO  tktH: 338  seedH: 1445 deals: [0]
30: Proving      sSet: YES active: NO  tktH: 338  seedH: 1447 deals: [0]
31: Proving      sSet: YES active: NO  tktH: 349  seedH: 1448 deals: [0]
32: Proving      sSet: YES active: NO  tktH: 348  seedH: 1450 deals: [0]
33: Proving      sSet: YES active: NO  tktH: 349  seedH: 1451 deals: [0]
34: Proving      sSet: YES active: NO  tktH: 349  seedH: 1452 deals: [0]
35: Proving      sSet: YES active: NO  tktH: 349  seedH: 1455 deals: [0]
36: Proving      sSet: YES active: NO  tktH: 349  seedH: 1455 deals: [0]
37: Proving      sSet: YES active: YES tktH: 349  seedH: 1469 deals: [0]
38: Proving      sSet: YES active: NO  tktH: 349  seedH: 1457 deals: [0]
39: Proving      sSet: YES active: YES tktH: 349  seedH: 1473 deals: [0]
40: Proving      sSet: YES active: YES tktH: 349  seedH: 1472 deals: [0]
41: Proving      sSet: YES active: YES tktH: 349  seedH: 1470 deals: [0]
42: Committing   sSet: NO  active: NO  tktH: 807  seedH: 2237 deals: [0]
43: CommitFailed sSet: NO  active: NO  tktH: 807  seedH: 2237 deals: [0]
44: CommitFailed sSet: NO  active: NO  tktH: 807  seedH: 2237 deals: [0]
45: Committing   sSet: NO  active: NO  tktH: 809  seedH: 2237 deals: [0]
46: CommitFailed sSet: NO  active: NO  tktH: 894  seedH: 2349 deals: [0]
47: Committing   sSet: NO  active: NO  tktH: 968  seedH: 2894 deals: [0]
48: CommitFailed sSet: NO  active: NO  tktH: 968  seedH: 2894 deals: [0]
49: Committing   sSet: NO  active: NO  tktH: 968  seedH: 2894 deals: [0]
50: Committing   sSet: NO  active: NO  tktH: 968  seedH: 2894 deals: [0]
51: CommitFailed sSet: NO  active: NO  tktH: 968  seedH: 2894 deals: [0]
52: CommitFailed sSet: NO  active: NO  tktH: 969  seedH: 2894 deals: [0]
53: Committing   sSet: NO  active: NO  tktH: 1005 seedH: 2972 deals: [0]
54: CommitFailed sSet: NO  active: NO  tktH: 1005 seedH: 2972 deals: [0]
55: Committing   sSet: NO  active: NO  tktH: 1006 seedH: 2972 deals: [0]
56: Committing   sSet: NO  active: NO  tktH: 1006 seedH: 2972 deals: [0]
57: Committing   sSet: NO  active: NO  tktH: 1006 seedH: 2972 deals: [0]
58: Committing   sSet: NO  active: NO  tktH: 1006 seedH: 2972 deals: [0]
59: Committing   sSet: NO  active: NO  tktH: 1006 seedH: 2972 deals: [0]
60: Committing   sSet: NO  active: NO  tktH: 1007 seedH: 2972 deals: [0]
61: CommitFailed sSet: NO  active: NO  tktH: 1007 seedH: 2972 deals: [0]
62: CommitFailed sSet: NO  active: NO  tktH: 1007 seedH: 2972 deals: [0]
63: Committing   sSet: NO  active: NO  tktH: 1007 seedH: 2972 deals: [0]
64: CommitFailed sSet: NO  active: NO  tktH: 1007 seedH: 2972 deals: [0]
65: Committing   sSet: NO  active: NO  tktH: 1007 seedH: 2972 deals: [0]
66: CommitFailed sSet: NO  active: NO  tktH: 1007 seedH: 2972 deals: [0]
67: Committing   sSet: NO  active: NO  tktH: 1007 seedH: 2972 deals: [0]
68: Committing   sSet: NO  active: NO  tktH: 1007 seedH: 2972 deals: [0]
69: CommitFailed sSet: NO  active: NO  tktH: 1007 seedH: 2972 deals: [0]
70: Committing   sSet: NO  active: NO  tktH: 1067 seedH: 3170 deals: [0]
71: CommitFailed sSet: NO  active: NO  tktH: 1106 seedH: 3170 deals: [0]
72: Committing   sSet: NO  active: NO  tktH: 1161 seedH: 3202 deals: [0]
73: Committing   sSet: NO  active: NO  tktH: 1209 seedH: 3202 deals: [0]
74: CommitFailed sSet: NO  active: NO  tktH: 1257 seedH: 3241 deals: [0]
75: Committing   sSet: NO  active: NO  tktH: 1305 seedH: 3430 deals: [0]
76: Committing   sSet: NO  active: NO  tktH: 1353 seedH: 3430 deals: [0]
77: Committing   sSet: NO  active: NO  tktH: 1401 seedH: 3452 deals: [0]
78: Committing   sSet: NO  active: NO  tktH: 1449 seedH: 3457 deals: [0]
79: Committing   sSet: NO  active: NO  tktH: 1496 seedH: 3457 deals: [0]
80: Committing   sSet: NO  active: NO  tktH: 1544 seedH: 3457 deals: [0]
81: CommitFailed sSet: NO  active: NO  tktH: 1593 seedH: 3457 deals: [0]
82: CommitFailed sSet: NO  active: NO  tktH: 1641 seedH: 3457 deals: [0]
83: CommitFailed sSet: NO  active: NO  tktH: 1689 seedH: 3457 deals: [0]
84: Committing   sSet: NO  active: NO  tktH: 1737 seedH: 3457 deals: [0]
85: CommitFailed sSet: NO  active: NO  tktH: 1785 seedH: 3457 deals: [0]
86: CommitFailed sSet: NO  active: NO  tktH: 1833 seedH: 3457 deals: [0]
87: CommitFailed sSet: NO  active: NO  tktH: 1881 seedH: 3457 deals: [0]
88: CommitFailed sSet: NO  active: NO  tktH: 1929 seedH: 3457 deals: [0]
89: CommitFailed sSet: NO  active: NO  tktH: 1977 seedH: 3457 deals: [0]
90: Committing   sSet: NO  active: NO  tktH: 2025 seedH: 3457 deals: [0]
91: CommitFailed sSet: NO  active: NO  tktH: 2073 seedH: 3457 deals: [0]
92: CommitFailed sSet: NO  active: NO  tktH: 2121 seedH: 3457 deals: [0]
93: Committing   sSet: NO  active: NO  tktH: 2169 seedH: 3457 deals: [0]
94: CommitFailed sSet: NO  active: NO  tktH: 2217 seedH: 3457 deals: [0]
95: CommitFailed sSet: NO  active: NO  tktH: 2265 seedH: 3457 deals: [0]
96: CommitFailed sSet: NO  active: NO  tktH: 2313 seedH: 3458 deals: [0]
97: Committing   sSet: NO  active: NO  tktH: 2361 seedH: 3458 deals: [0]
98: CommitFailed sSet: NO  active: NO  tktH: 2409 seedH: 3493 deals: [0]

**Comment by f8-ptrk** [comment]
not a lotus issue and the miner would be dead by now anyways if not resolved - > resolved

#antidisestablishatarianism
