### ISSUE TITLE
Amendments to miner `asks` to enable verified client workflow

### ISSUE THREAD

**Issue by pooja** [filecoin-project/lotus#2553]
Verified clients will need to know if the miners they are proposing deals to are offering storage discounts to verified clients.

In [this document](https://docs.google.com/document/d/1sJftu0zxfR8uNXyov0OSWlldTG3uGO17ZVDXR5jPe8w/edit#) (and ensuing discussion), we agreed that exposing a `discount` for verified client data seemed an appropriate and doable amendment to provide this information to verified clients.

Concretely the request is: 
- make it possible for miners to set a `discount` (units need to be documented, but we are relatively agnostic from a product perspective, maybe % makes sense?) when creating storage asks
- when a client runs `lotus client query-ask <miner>`, please display this discount (ideally with units) in the response

There are other nuances to how we are expecting this workflow to work that are in the linked doc ([linked again here](https://docs.google.com/document/d/1sJftu0zxfR8uNXyov0OSWlldTG3uGO17ZVDXR5jPe8w/edit#)), so could implementers please sanity check against the human-readable workflow description and ack whether this is or isn't how we can expect the workflow to work?

Thanks!

If you don't have access to the document, here is a screenshot:

![Screen Shot 2020-07-23 at 11 55 00 AM](https://user-images.githubusercontent.com/5668171/88326868-5ab5f600-ccdb-11ea-9b45-78c0a9a261f6.png)

cc @jnthnvctr @ribasushi @arajasek @magik6k @hannahhoward @zixuanzh @jsign

**Comment by arajasek** [comment]
@pooja We ended up going with a simpler proposal that simply allows a second price for verified deals. Introduced to markets [here](https://github.com/filecoin-project/go-fil-markets/pull/347) and consumed into Lotus [here](https://github.com/filecoin-project/lotus/pull/2752/files).
