### ISSUE TITLE
Miners have a way to let clients know that they support fast retrieval

### ISSUE THREAD

**Issue by pooja** [filecoin-project/lotus#2554]
Clients may want to know whether miners explicitly advertise that they support the native fast-retrieval functionality. One place for miners to do this advertisement is in their `asks`.

But first, we should discuss how important this is. Since miners support fast-retrieval by default, what does this additional advertisement gain? Should we find some more explicit way to expose this information to clients?

cc @mishmosh @momack2 @arajasek

**Comment by jennijuju** [comment]
Is this still required from a product perspective?

**Comment by pooja** [comment]
I think we are aiming for clients to select miners on the basis of their reputation, as measured/computed by dealbots and reputation services which do measure retrieval latency and should include this in their reputation calculations. I think we can probably close this issue for now, since there will be other ways for clients to get the practical benefit of what this issue was aiming to surface.
