### ISSUE TITLE
Lotus panics when trying to gracefully shutdown it programatically

### ISSUE THREAD

**Issue by nonsense** [filecoin-project/lotus#2572]
**Describe the bug**
When trying to shutdown Lotus programatically with `fx.app.Stop()`, occasionally I get panics in the `go-ds-measure` package (see attached file for full stack trace)

**To Reproduce**
1. Run the `recovery` test plan from https://github.com/filecoin-project/oni/pull/95, for example with `testground run composition -f _compositions/recovery-k8s.toml`
2. I usually get the error on one run out of 2-3 runs.

**Expected behavior**
Lotus shuts down properly without panics, and is able to start back up when initialising a node with the same FS repo.

**Version (run `lotus version`):**
```
Lotus commit: 717728f33bc7
```

**Additional context**
[lotus-panic.txt](https://github.com/filecoin-project/lotus/files/4972299/lotus-panic.txt)

**Comment by rjan90** [comment]
Hey @nonsense! This issue seems outdated, can it be closed?

**Comment by nonsense** [comment]
Yes, closing, I think this issue is from before Filecoin mainnet, most probably this is no longer an issue.
