### ISSUE TITLE
Deal making logs with known miner

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#2577]
Some results about making deals with @ribasushi  miners.

- `bafyreifzq633b23id6olzlkk5mrjvshgdh6fznlbefhiqgmv47tluqkh5m`, t03360, 127Mib: Transferring ~2hs, confirmed slow live with @ribasushi.
- `bafyreigknqwbsiwgkefgr6osfekeytc4xwpdidyky4ij47ggz5lpvlihue`, t03361, 508Mib: Transferring 2hs.
- `bafyreial4s5ia66pk4qeuecdd32y5os4dntley7dst2mgd5wknnbp4o4ae`, t03360, 508Mib: Transferring ~2hs.
- `bafyreifvjgtgsstffxixw4wailfy3thwkew4pwa35zraaujjxxc5yilrku`, t03361, 127Mib: `Sealing` for more than 2hs (512Mib sector).

![image](https://user-images.githubusercontent.com/6136245/88433109-da26f080-cdd3-11ea-9274-5d19c2262700.png)
(Ignore the rejected deal)

I'll keep running these things, and make an update in some hours.

Running `ntwk-calibration-7.24.0`

**Comment by jimpick** [comment]
I have some active deals from earlier with those miners:

<img width="733" alt="Screen Shot 2020-07-24 at 1 40 33 PM" src="https://user-images.githubusercontent.com/20886/88433650-552bdf00-cdb3-11ea-8b60-9d7cf6024f0a.png">

I also have 2 more in-flight:

<img width="735" alt="Screen Shot 2020-07-24 at 1 42 31 PM" src="https://user-images.githubusercontent.com/20886/88433785-97552080-cdb3-11ea-9298-98f279129da5.png">

The longer sealing times might just be because there are several sectors queued up due to congestion.

**Comment by ribasushi** [comment]
The miner was specifically configured to start asp. Filed https://github.com/filecoin-project/lotus/issues/2578#issue-665427043 to track.

**Comment by jsign** [comment]
Screenshot now:
![image](https://user-images.githubusercontent.com/6136245/88444493-ba072980-cdf3-11ea-9707-08c6441527f5.png)

Same status as the original post.

**Comment by ribasushi** [comment]
Confirmed the above larger-deal is stuck on `34.223.52.127` with `StorageDealTransferring`
```
  {
    "Proposal": {
      "PieceCID": {
        "/": "baga6ea4seaqgzvi5gdrvskhd2bzqiwnf4qw4rx2efrex2hxmobmlaxpgkhyignq"
      },
      "PieceSize": 536870912,
      "VerifiedDeal": false,
      "Client": "t1wnovv2qq3fkifqkyzwkjrv37ndh3any72sdb4ji",
      "Provider": "t03361",
      "Label": "",
      "StartEpoch": 12330,
      "EndEpoch": 14594,
      "StoragePricePerEpoch": "1000000000",
      "ProviderCollateral": "532676608",
      "ClientCollateral": "0"
    },
    "ClientSignature": {
      "Type": 1,
      "Data": "mhVO77Qm28TtsMWvmu//yBTOjJ35qrnu6qI8SBqe8v5JkUB+0WrLn8xk8EUeDC40Nsc5cd+kijLF4tTPoT3VRQE="
    },
    "ProposalCid": {
      "/": "bafyreigknqwbsiwgkefgr6osfekeytc4xwpdidyky4ij47ggz5lpvlihue"
    },
    "AddFundsCid": null,
    "PublishCid": null,
    "Miner": "12D3KooWEqDVn8joi4Lqx4xW8tUhUFQLKJL2iSvVip2SsWLbXQ2g",
    "Client": "12D3KooWRYwBZ2TgpfHoWpRmp1DmLZYa2vNVfeMP7vLfwmq1PQzW",
    "State": 17,
    "PiecePath": "",
    "MetadataPath": "",
    "SlashEpoch": 0,
    "FastRetrieval": false,
    "Message": "",
    "Ref": {
      "TransferType": "graphsync",
      "Root": {
        "/": "bafykbzacecuu2fmsavkdirxunspc22wrszrtuiosgy5lfijwmv5dntep2ow62"
      },
      "PieceCid": null,
      "PieceSize": 0
    },
    "DealID": 0
  },
```

**Comment by ribasushi** [comment]
@jsign if you gave time today let's try to hit t024771 and t024768 a few times.

**Comment by jsign** [comment]
> @jsign if you gave time today let's try to hit t024771 and t024768 a few times.

Sure, will do.

**Comment by Reiers** [comment]
**Is this still a issue?** @jsign 
If not - let me know.

**Comment by jsign** [comment]
@Reiers, wow, this is an old one. :)
I haven't been doing online deals this year, and I know there has been a lot of work on them.

I'd vote to close this since probably won't reflect the current situation of transfers.
