### ISSUE TITLE
paych get returns "<empty>" - what does this mean?

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/lotus#2580]
**Describe the bug**
```
$ lotus paych get t14hsid4nwp724r6dxwgue5kvvzjqjrd6y4lalecq t3rbcytzb6t3vzeigkfi6oxg22iwpaeekaf7gbstovykkmskg2nglthnzpg777whuevo4loqu3vmthoxsvdkbq 5000000000
<empty>
```

(This to/from address pair does NOT already have an existing payment channel, so Lotus _should_ be taking the `createPaych` code path here.)

**To Reproduce**
See above.

**Expected behavior**
I'm not sure what `<empty>` means.  Is it an error?  Or is the CLI just returning immediately because this is a long running operation?  If the latter, how can I know when it is done?

**Version (run `lotus version`):**
```
$ lotus version
Daemon:  0.4.1+git.190882ee+api0.8.1
Local: lotus version 0.4.1+git.190882ee
```

**Comment by magik6k** [comment]
This should probably by the paych actor address

**Comment by dirkmc** [comment]
@mgoelzer this should be fixed - could you try again and let us know?

**Comment by dirkmc** [comment]
Closing - please reopen if you see the same issue
