### ISSUE TITLE
`lotus retrieval-deals list`: CLI to view in progress retrieval deals on miner side

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#2583]
# What

Command line via which a miner can view their current in progress retrieval deals.

# How

This data is accessible in `go-fil-markets` via RetrievalProvider.ListDeals(). (actually returns a map -- not sure if we want this)

Need to add:
- MarketListRetrievalDeals(ctx context.Context) []retrievalmarket.ProviderDealState, error to StorageMiner API
- Need to build CLI to access this.

**Comment by rjan90** [comment]
Hey! Closing this issue as the retrieval transfer progress is being tracked in `lotus-miner data-transfers list`.
