### ISSUE TITLE
paych voucher list shows extra "mystery voucher"

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/lotus#2585]
**Describe the bug**
I created a payment channel and two vouchers.  Then I did `lotus paych voucher  list` and it lists **three** vouchers.

The extra voucher is either getting randomly created, or else it is a "leftover" from a previous `lotus client retrieve` on this to/from address pair (which I suspect is what initially created the payment channel).

**To Reproduce**
I created the payment channel like this:

```
from $ lotus paych get t14hsid4nwp724r6dxwgue5kvvzjqjrd6y4lalecq t3schhtef3m5yshlop3ffwjk5lauaqryx2e67xayngbj5stvha6m6i5noqvtiswykqg5pel4wt5j6zlrbblxbq 5000000000
t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a
```

(*Note:*  `to $` means command was entered on the machine with the receiving wallet; `from $` is machine with the payer wallet.)

Then I immediately created two vouchers for (1e9 and 2e9 attofil, respectively):

```
from $ lotus paych voucher create t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a 1000000000
i1UC5p1RJZfUi1pfGcoDNwPXTRTlg0IAAED2AAJFADuaygAAgFhCAYdpWxcpIUos5ufI4MDLqvjV5SHwKuOOEfB-uaDeqIJHPtnh2A9dQ3qQL7GsDQxMDP8MX0PNy9F6RxoL0AqCQT4A
from $ lotus paych voucher create t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a 2000000000
i1UC5p1RJZfUi1pfGcoDNwPXTRTlg0IAAED2AANFAHc1lAAAgFhCAa-myCUZEEs-0UrsaTn7nLe6a-uDrvMJwOrc-Y0X8SJwB9XKaO3piTI1N37WEg1N-SfGHCt2gjy6qr37GJkR0fIB
```

Now I list vouchers for the channel:

```
from $ lotus paych voucher list t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a
Lane 0, Nonce 1: 1150
Lane 0, Nonce 2: 1000000000
Lane 0, Nonce 3: 2000000000
```

**Expected behavior**
I expected to see the `1000000000` and `2000000000` vouchers only.  The voucher for `1150` is not expected.

I did not create any voucher for 1150.  There has been no previous manual voucher creation on this payment channel.  However, the channel is (probably) being reused from a previous `lotus client retrieve` between this to/from address pair, so the 1150 mystery voucher might be left over from that?

**Version (run `lotus version`):**
```
from $ lotus version
Daemon:  0.4.1+git.190882ee+api0.8.1
Local: lotus version 0.4.1+git.190882ee
```

**Comment by mgoelzer** [comment]
The rest of the test was successful:
✅ a voucher was submitted by the `to` machine
✅  the channel was settled and collected 
✅ both wallets updated to the expected balance  

For future testing use, here are the rest of the steps used in the test procedure:

## Remainder of Test Procedure:

Following the commands shown in the issue description, we now:  manually add the 1000000000 attofil voucher on “to” machine:

```
to $ ./lotus paych voucher add t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a i1UC5p1RJZfUi1pfGcoDNwPXTRTlg0IAAED2AAJFADuaygAAgFhCAYdpWxcpIUos5ufI4MDLqvjV5SHwKuOOEfB-uaDeqIJHPtnh2A9dQ3qQL7GsDQxMDP8MX0PNy9F6RxoL0AqCQT4A
```

State of the “to” machine right BEFORE voucher submission:

```
to $ ./lotus wallet balance
50976.230659335644412602 FIL
to $ ./lotus paych voucher best-spendable t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a
i1UC5p1RJZfUi1pfGcoDNwPXTRTlg0IAAED2AAJFADuaygAAgFhCAYdpWxcpIUos5ufI4MDLqvjV5SHwKuOOEfB-uaDeqIJHPtnh2A9dQ3qQL7GsDQxMDP8MX0PNy9F6RxoL0AqCQT4A
Amount: 1000000000
```

Here’s the submit command:

```
to $ ./lotus paych voucher submit t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a i1UC5p1RJZfUi1pfGcoDNwPXTRTlg0IAAED2AAJFADuaygAAgFhCAYdpWxcpIUos5ufI4MDLqvjV5SHwKuOOEfB-uaDeqIJHPtnh2A9dQ3qQL7GsDQxMDP8MX0PNy9F6RxoL0AqCQT4A
channel updated successfully
```

State of “to” machine 15 MINUTES AFTER voucher submission completed:

```
to $ ./lotus wallet balance
50976.230659335635546829 FIL

to $ ./lotus paych voucher best-spendable t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a
ERROR: apply message failed: voucher has an outdated nonce, cannot redeem (RetCode=16)
```

Now we settle and collect the channel to see if wallet balance update as expected:

```
from $ lotus wallet balance
102399.999965752930108185 FIL
to $ ./lotus wallet balance
50976.230659335635546829 FIL

to $ ./lotus paych settle t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a
Settled channel t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a

from $ lotus wallet balance
102399.999965752930108185 FIL # unchanged
to $ ./lotus wallet balance
50976.230659335634349236 FIL # decreased 1e-12 (gas probably)

to $ ./lotus paych collect t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a

to $ ./lotus paych collect t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a
Collected funds for channel t242ovcjmx2sfvuxyzzibtoa6xjukola2cqjh7k6a

to $ ./lotus wallet balance
50976.230659336631655705 FIL # +0.000000000997306469 ~= +0.000000001
from $ lotus wallet balance
102399.999965756930110217 FIL # +0.000000004000002032 ~= +0.000000004
```

Final wallet values are as expected:
 ✅ “to” machine increased by 1e9 attofil = +0.000000001 which was the amount of the vooucher
 ✅ “from" got a refund of 4e9 attofil that was left unspent in the channel = +0.000000004

**Comment by dirkmc** [comment]
I believe this should be fixed in the latest next
