### ISSUE TITLE
MpoolPush and MpoolGetNonce without JWT token (feature request)

### ISSUE THREAD

**Issue by ghost** [filecoin-project/lotus#2588]
**Describe the feature request**

Some Lotus API endpoints require JWT tokens and some do not (e.g., ChainHead and ChainGetBlockMessages).  I was wondering whether `MpoolPush` and `MpoolGetNonce` truly need to have a JWT.

Here's my use case.  I want to run a public "cloud lotus" where anybody can call the `MpoolPush` RPC with a valid, signed message and have it submitted to the blockchain.  Imagine a reverse proxy in front of the API blocks all API calls except `MpoolPush`.  

If `MpoolPush` requires a JWT token, then this use case requires me to give out the JWT token to anyone who wants to use this "cloud lotus" instance.  That's fine, until I need to have multiple Lotus instances behind a load balancer.  Now each Lotus will have a separate JWT token, and clients won't know what token to use.  I'm stuck - any ideas?

**Comment by jimpick** [comment]
Maybe there could be a override flag or config file option to change the permission level on specific API calls?

**Comment by whyrusleeping** [comment]
I think what @jimpick proposes here could work, but the reason `MpoolPush` isnt marked "read" is because its fundamentally a 'writing' operation, and a malicious entity could use that to get your node kicked out of the gossip topic.
`MpoolGetNonce` could probably change to read perms though, that seems acceptable.

**Comment by LexLuthr** [comment]
https://github.com/filecoin-project/lotus/blob/285c9b9d4a5323fab35e6761c133f41d02a165e0/api/api_full.go#L274

`MpoolGetNonce` has already been modified to use read perm. As we are not going to change `MpoolPush` perms due to security considerations, I am closing this issue as fixed.
