### ISSUE TITLE
new release 0.4.2--lotus daemon init failed

### ISSUE THREAD

**Issue by jack2007** [filecoin-project/lotus#2589]
**Describe the bug**
new release 0.4.2--lotus daemon init failed

**To Reproduce**
Download 0.4.2 release binary from github and replace the 0.4.1 binary.
OS: Ubuntu 18.04
1. Run 'lotus daemon'
2. See error
2020-07-25T01:13:52.329Z	WARN	chainstore	store/store.go:143	no previous chain state found
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/circleci/project/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.AfterGenesisSet: function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12) returned a non-nil error: genesis func failed: decoding block failed: unmarshaling t.ElectionProof pointer: cbor input had wrong number of fields

**Expected behavior**
Init OK.

**Screenshots**

**Version (run `lotus version`):**
0.4.2

**Additional context**

**Comment by magik6k** [comment]
0.4.2 Doesn't support testnet. If you want to test this code, you may want to consider joining one of the devnets, like calibration (using the `ntwk-calibration` branch)
