### ISSUE TITLE
Lotus Worker being assigned disable sealing operations

### ISSUE THREAD

**Issue by ognots** [filecoin-project/lotus#2591]
**Describe the bug**
When setting a flag such as
```
lotus-worker run --precommit1=false
```
a local or remote worker will still be assigned a precommit1 job

**To Reproduce**
1. properly configure a `lotus-miner` 
2. configure a worker like `lotus-worker run --precommit1=false`
3. pledge a sector `lotus-miner sectors pledge`
4. check if precommit1 is running on worker

**Expected behavior**
precommit1 operations should not be scheduled on worker

**Version (run `lotus version`):**
 lotus-miner version 0.4.1+git.190882ee
lotus-worker version 0.4.1+git.190882ee

**Comment by magik6k** [comment]
This got fixed
