### ISSUE TITLE
miner pledge too much

### ISSUE THREAD

**Issue by yangchuang123456** [filecoin-project/lotus#2592]
Now the pledge of sector is more than twenty  days of expected earning, This may restrict the power growth. could consider to use the locked block reward as pledge ?

https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/monies.go#L9

**Comment by magik6k** [comment]
This should be fixed with https://github.com/filecoin-project/lotus/pull/2605, which fixes the circulating supply math

**Comment by daviddias** [comment]
Closing, follow up or reopen if necessary.
