### ISSUE TITLE
mark-for-upgrade again on the upgraded CC sector, resulting in the normal sector has been unable to seal successfully

### ISSUE THREAD

**Issue by TerenceClark** [filecoin-project/lotus#2595]
**Describe the problem**

When I execute the `lotus-miner sectors mark-for-upgrade` command again on an upgraded sector, no error is returned, and the `SectorPreCommitInfo` also contains information about the CC sector when sealing the ordinary sector, causing an error in `handleCommitWait`, and the state keeps retrying compute proof so that the ordinary sector can never be successfully sealed.

**Sectors status**

SectorID:	7
Status:		CommitFailed
CIDcommD:	baga6ea4seaqatdqgapa6jwfxcdwjh76u5k2cwywfvvdkue4nsg6ityvcrctfaiq
CIDcommR:	bagboea4b5abcarq35ejm23k7s2q6nmycxoxsbifvxksgx4ll5leluh2atpf3uc3t
Ticket:		8d8935019bca6cd7899179e88776d5922a84c64a402289fd59fc31badccf2813
TicketH:	-114
Seed:		8fd33d4e892deed6a92afe94b2de22ad6aec450d0bd3457bf0c1b5b1acfba3eb
SeedH:		938
Proof:		ad1a45ce134bda91b23a2158aae07a9cfbabedf362c99a9f6dee7a116d6cf2db6161a25b09669702976d84dcbc45035baea42b289a687d2994da4bf9c5ac6688b6a78b9f2653e4b418f0a43b200516f027a5ae2deb194f24f8108ee1075af860060d4040fca6c45c272cf78d3de1ee420bb777120bf41436e8a4195fc017ea463d6f05babe20922c224548ebbd95871b91798624cba6e93151ea3655d2c4de0d05a0e3cab31cf1ccc270e5be5ae51151e66f1aeb116c7515e2f02074426ad7e7
Deals:		[4 5 0 0]
Retries:	22

Event Log:
0.	2020-07-25 10:27:28 +0800 CST:	[event;sealing.SectorStart]	{"User":{"ID":7,"SectorType":0}}
1.	2020-07-25 10:27:28 +0800 CST:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":256,"PieceCID":{"/":"baga6ea4seaqmf3urfqivmpvpq2btozrydm64ntm5rpdsnojmu6giklkredlayly"}},"DealInfo":{"DealID":4,"DealSchedule":{"StartEpoch":50500,"EndEpoch":54225},"KeepUnsealed":true}}}}
2.	2020-07-25 10:27:36 +0800 CST:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":256,"PieceCID":{"/":"baga6ea4seaqmf3urfqivmpvpq2btozrydm64ntm5rpdsnojmu6giklkredlayly"}},"DealInfo":{"DealID":5,"DealSchedule":{"StartEpoch":50500,"EndEpoch":133713},"KeepUnsealed":true}}}}
3.	2020-07-25 10:38:34 +0800 CST:	[event;sealing.SectorStartPacking]	{"User":{}}
4.	2020-07-25 10:38:34 +0800 CST:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":[{"Size":512,"PieceCID":{"/":"baga6ea4seaqfpirydiugkk7up5v666wkm6n6jlw6lby2wxht5mwaqekerdfykjq"}},{"Size":1024,"PieceCID":{"/":"baga6ea4seaqb66wjlfkrbye6uqoemcyxmqylwmrm235uclwfpsyx3ge2imidoly"}}]}}
5.	2020-07-25 10:38:34 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzJLaUJWMSIsImxhYmVscyI6eyJTdGFja2VkRHJnMktpQlYxIjp7ImxhYmVscyI6W3sicGF0aCI6Ii9ob21lL2lwZnNtYWluL3dvcmtzcGFjZS9maWxlY29pbi9sb3R1cy1kZXYtZW52L2xvdHVzc3RvcmFnZS9jYWNoZS9zLXQwMTAwMC03IiwiaWQiOiJsYXllci0xIiwic2l6ZSI6NjQsInJvd3NfdG9fZGlzY2FyZCI6NX0seyJwYXRoIjoiL2hvbWUvaXBmc21haW4vd29ya3NwYWNlL2ZpbGVjb2luL2xvdHVzLWRldi1lbnYvbG90dXNzdG9yYWdlL2NhY2hlL3MtdDAxMDAwLTciLCJpZCI6ImxheWVyLTIiLCJzaXplIjo2NCwicm93c190b19kaXNjYXJkIjo1fV0sIl9oIjpudWxsfX0sImNvbmZpZyI6eyJwYXRoIjoiL2hvbWUvaXBmc21haW4vd29ya3NwYWNlL2ZpbGVjb2luL2xvdHVzLWRldi1lbnYvbG90dXNzdG9yYWdlL2NhY2hlL3MtdDAxMDAwLTciLCJpZCI6InRyZWUtZCIsInNpemUiOjEyNywicm93c190b19kaXNjYXJkIjo1fSwiY29tbV9kIjpbOSwxNDIsNiwzLDE5MywyMjgsMjE2LDE4MywxNiwyMzYsMTQ3LDI1NSwyMTIsMjM0LDE4MCw0Myw5OCwxOTcsMTczLDcwLDE3MCwxOSwxNDEsMTQ1LDE4OCwxMzcsMjI2LDE2MiwxMzYsMTY2LDgwLDM0XX0=","TicketValue":"jYk1AZvKbNeJkXnoh3bVkiqExkpAIon9WfwxutzPKBM=","TicketEpoch":-114}}
6.	2020-07-25 10:38:34 +0800 CST:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcarq35ejm23k7s2q6nmycxoxsbifvxksgx4ll5leluh2atpf3uc3t"},"Unsealed":{"/":"baga6ea4seaqatdqgapa6jwfxcdwjh76u5k2cwywfvvdkue4nsg6ityvcrctfaiq"}}}
7.	2020-07-25 10:38:34 +0800 CST:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzaceb6twg2ldqi5gajqgflz2edi7smzepfc6me372qfr5oobldkvuddg"},"PreCommitDeposit":"97735211329215810268516","PreCommitInfo":{"SealProof":0,"SectorNumber":7,"SealedCID":{"/":"bagboea4b5abcarq35ejm23k7s2q6nmycxoxsbifvxksgx4ll5leluh2atpf3uc3t"},"SealRandEpoch":-114,"DealIDs":[4,5],"Expiration":1260369,"ReplaceCapacity":true,"ReplaceSectorDeadline":1,"ReplaceSectorPartition":0,"ReplaceSectorNumber":2}}}
8.	2020-07-25 10:38:47 +0800 CST:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":"AXGg5AIga7k6jTY5tKlVDHxgIttHMkGLulftsu2ajcDlqtpJAkU="}}
9.	2020-07-25 10:43:30 +0800 CST:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"j9M9Tokt7tapKv6Ust4irWrsRQ0L00V78MG1saz7o+s=","SeedEpoch":938}}
10.	2020-07-25 10:44:13 +0800 CST:	[event;sealing.SectorCommitted]	{"User":{"Message":{"/":"bafy2bzaceal5btnewucfh2e7cwmuaxodjii4wjzqvhx6ftjs2gpxykoepyezo"},"Proof":"hAr1HON7u7R402+aVOvr97i8oX9/SoRIkbQ3MxiVcUxgLygYbEsUFiD7+j5B09T+ruoSC7W5IAoaOsZt2bilc/42qf5tM3FVoweCok/jSFH81D007gAiRkOWIbQaVpbhBkgeasEl7dJRjl1YVQELfLoY51tXa10/wcMrlMhJHROKwYiPGT4bMLfmNMjHCNCNhRBLJDIbxXfEEywDSstBbvdcrehHSryaLkWo98Scl32ErRqIZDOMCIm5BixBMczX"}}
11.	2020-07-25 10:44:25 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	proof validation failed, sector not found in sector set after cron: sector not found
12.	2020-07-25 10:45:25 +0800 CST:	[event;sealing.SectorRetryComputeProof]	{"User":{}}
...
76.	2020-07-25 11:26:34 +0800 CST:	[event;sealing.SectorCommitted]	{"User":{"Message":{"/":"bafy2bzaceaaiotdzsxs4dzdgwnwvrkzhjrxxkyry4wawzwj25bafp55v7cjj6"},"Proof":"rRpFzhNL2pGyOiFYquB6nPur7fNiyZqfbe56EW1s8tthYaJbCWaXApdthNy8RQNbrqQrKJpofSmU2kv5xaxmiLani58mU+S0GPCkOyAFFvAnpa4t6xlPJPgQjuEHWvhgBg1AQPymxFwnLPeNPeHuQgu3dxIL9BQ26KQZX8AX6kY9bwW6viCSLCJFSOu9lYcbkXmGJMum6TFR6jZV0sTeDQWg48qzHPHMwnDlvlrlEVHmbxrrEWx1FeLwIHRCatfn"}}
77.	2020-07-25 11:26:46 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	proof validation failed, sector not found in sector set after cron: sector not found
...

**Version**

lotus version 0.4.1+2k+git.190882ee.dirty

**Comment by ribasushi** [comment]
This has been since resolved definitively
