### ISSUE TITLE
StateGetReceipt returns error "found message with equal nonce" on some messages

### ISSUE THREAD

**Issue by astudnev** [filecoin-project/lotus#2596]
RuntimeError: Error response to Filecoin.StateGetReceipt request: 1  found message with equal nonce as the one we are looking for (F:bafy2bzacebtscfbp44byp7rd2rbrmfpvdby6athrxuxri3avzbjhrbz5e7imq n 11625, TS: bafy2bzacecda3akrebwevr6qf4rk3jphoreyh57akonnwivhnuf23avcpces2 n11625)

**Comment by magik6k** [comment]
* Which network is this?
* How were those messages sent?

**Comment by licornduan** [comment]
10.	2022-06-08 15:30:52 +0800 CST:	[event;sealing.SectorCommitSubmitted]	{"User":{"Message":{"/":"bafy2bzacedgaggotn27fd4jutieo3u7hklxaewdpdmdj2sbjunpiamt3slcoi"}}}
11.	2022-06-08 15:31:39 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	failed to wait for porep inclusion: found message with equal nonce as the one we are looking for that is NOT a valid replacement message (F:bafy2bzacedgaggotn27fd4jutieo3u7hklxaewdpdmdj2sbjunpiamt3slcoi n 67491, TS: bafy2bzaceabcgqcyiabelywgfs2kbp37b4nhm7qpvgblx4kmxsqjbfizeg5lu n67491)
12.	2022-06-08 15:32:39 +0800 CST:	[event;sealing.SectorRetryCommitWait]	{"User":{}}
