### ISSUE TITLE
Wrong block returned on StateGetTipSetByHeight

### ISSUE THREAD

**Issue by astudnev** [filecoin-project/lotus#2597]
StateGetTipSetByHeight 118535, nil

returns block with 118534 height

**Comment by magik6k** [comment]
In Filecoin some epochs can have no blocks, ('null blocks' / 'null tipsets'), in which case this function will return a tipset at lower height with blocks:

https://github.com/filecoin-project/lotus/blob/64e67df88127df3df11b543f930b3ef173db7d4a/api/api_full.go#L59-L62
