### ISSUE TITLE
Cannot create a new storage miner 

### ISSUE THREAD

**Issue by verynohair** [filecoin-project/lotus#2602]
I have got a new wallet address by running the command "lotus wallet new bls". Then I want to create a new miner for this address. Unfortunately, I was not able to get a correct miner id in the faucet site. 

The result just like this: **New storage miners address is: t**, it only display a character "t".

**Comment by hengic** [comment]
use below command to register a miner id:
lotus-miner init --owner=<your wallet address> --sector-size=32GiB

**Comment by anneyking** [comment]
> use below command to register a miner id:
> lotus-miner init --owner= --sector-size=32GiB

please help me 
I use the version of lotus is 0.4.1 +, 
execute :

Lotus-miner init-- owner=xxxxxxxxxxxxxxxxx  -- sector-size=32GiB. 

show:
Lotus-miner could not find the command

**Comment by verynohair** [comment]
> > use below command to register a miner id:
> > lotus-miner init --owner= --sector-size=32GiB
> 
> please help me
> I use the version of lotus is 0.4.1 +,
> execute :
> 
> Lotus-miner init-- owner=xxxxxxxxxxxxxxxxx -- sector-size=32GiB.
> 
> show:
> Lotus-miner could not find the command

Git pull the latest code and rebuild, then you'll find a new execution 'lotus-miner' in the lotus source directory.

**Comment by anneyking** [comment]
Thank you,
But,
Git pull the latest code and rebuild：
"make clean &amp;&amp; make build",


It stops in the middle of the operation. Do you know how to solve this problem?&nbsp;Thank you.









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "verynohair"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 下午3:32
收件人: "filecoin-project/lotus"<lotus@noreply.github.com&gt;; 
抄送: "22最热最火德州扑克投注"<523418624@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [filecoin-project/lotus] Cannot create a new storage miner  (#2602)





   
use below command to register a miner id:
 lotus-miner init --owner= --sector-size=32GiB
  
please help me
 I use the version of lotus is 0.4.1 +,
 execute :
 
Lotus-miner init-- owner=xxxxxxxxxxxxxxxxx -- sector-size=32GiB.
 
show:
 Lotus-miner could not find the command
  
Git pull the latest code and rebuild, then you'll find a new execution 'lotus-miner' in the lotus source directory.

**Comment by anneyking** [comment]
> > > use below command to register a miner id:
> > > lotus-miner init --owner= --sector-size=32GiB
> > 
> > 
> > please help me
> > I use the version of lotus is 0.4.1 +,
> > execute :
> > Lotus-miner init-- owner=xxxxxxxxxxxxxxxxx -- sector-size=32GiB.
> > show:
> > Lotus-miner could not find the command
> 
> Git pull the latest code and rebuild, then you'll find a new execution 'lotus-miner' in the lotus source directory.



> > > use below command to register a miner id:
> > > lotus-miner init --owner= --sector-size=32GiB
> > 
> > 
> > please help me
> > I use the version of lotus is 0.4.1 +,
> > execute :
> > Lotus-miner init-- owner=xxxxxxxxxxxxxxxxx -- sector-size=32GiB.
> > show:
> > Lotus-miner could not find the command
> 
> Git pull the latest code and rebuild, then you'll find a new execution 'lotus-miner' in the lotus source directory.

Git pull the latest code and rebuild，Is this version still 0.4.1? Do you know what the problem is?
lotus -v ：
lotus version 0.4.1+git.83e29b1c
