### ISSUE TITLE
Synchronization failure

### ISSUE THREAD

**Issue by littlekai999** [filecoin-project/lotus#2603]
root@hkgubm01:~# lotus sync status
sync status:
worker 0:
        Base:   [bafy2bzaceczb5gpwzmfihank53ba43h4rjl23k5pcx7z43xdmo4p5fofh22qa bafy2bzacedqopvxh452cn3quwua4qewpadmhlcciblpk653tsgni6grzatewi]
        Target: [bafy2bzaceb7dnnlwnivdxqeibvfzml2oz4frvrql5jxfvnqmal55orm76znaa] (127631)
        Height diff:    5262
        Stage: error
        Height: 127631
        Elapsed: 3.145378317s
        Error: chain contained block marked previously as bad ([bafy2bzaceb7dnnlwnivdxqeibvfzml2oz4frvrql5jxfvnqmal55orm76znaa], bafy2bzacebr2w2eog34lx4o7afe7m7holauagpg2j5ra5umeir2b7mutm3yna) (reason: failed to compute lookback tipset state: vm flush failed: copying tree: get bagboea4b5abcb6mghiqvjfcucp43etgn2noawk7q365qu74htlww7muwdipcuwcn failed: blockstore: block not found)
worker 1:
        Base:   [bafy2bzaceczb5gpwzmfihank53ba43h4rjl23k5pcx7z43xdmo4p5fofh22qa bafy2bzacedqopvxh452cn3quwua4qewpadmhlcciblpk653tsgni6grzatewi]
        Target: [bafy2bzacedbakmhufneg3asrsylfvn3uquyqhlcojdgotvorqzwmtalzuxpbq bafy2bzacedc4ibhs7s25egudsbsnfjvh33qutg5s4y2mphzxxsvmpq5e2azug bafy2bzacedyfz2uzeml5gxyuevgjvs7ufu6i3exeie4mkmlgqmhavjcf6lj7m] (126872)
        Height diff:    4503
        Stage: error
        Height: 126872
        Elapsed: 2.953203776s
        Error: chain contained block marked previously as bad ([bafy2bzacedbakmhufneg3asrsylfvn3uquyqhlcojdgotvorqzwmtalzuxpbq bafy2bzacedc4ibhs7s25egudsbsnfjvh33qutg5s4y2mphzxxsvmpq5e2azug bafy2bzacedyfz2uzeml5gxyuevgjvs7ufu6i3exeie4mkmlgqmhavjcf6lj7m], bafy2bzacebr2w2eog34lx4o7afe7m7holauagpg2j5ra5umeir2b7mutm3yna) (reason: failed to compute lookback tipset state: vm flush failed: copying tree: get bagboea4b5abcb6mghiqvjfcucp43etgn2noawk7q365qu74htlww7muwdipcuwcn failed: blockstore: block not found)
worker 2:
        Base:   [bafy2bzaceczb5gpwzmfihank53ba43h4rjl23k5pcx7z43xdmo4p5fofh22qa bafy2bzacedqopvxh452cn3quwua4qewpadmhlcciblpk653tsgni6grzatewi]
        Target: [bafy2bzaceb7s2hoxyn26tbfadidhjw2an5ww6ebkpguddtqrhc4qty3zevoc4 bafy2bzacecwym4dcobu7iuar6mwmv7y3kworkt527z2b5w3zjwx2mohaovr7m bafy2bzacedma33qryt2d3qawnuwc3wnlwyuo6buqaag6s6sx4hfzewtfhzp3m] (126649)
        Height diff:    4280
        Stage: error
        Height: 0
        Elapsed: 37.973µs
        Error: chain linked to block marked previously as bad ([bafy2bzaceb7s2hoxyn26tbfadidhjw2an5ww6ebkpguddtqrhc4qty3zevoc4 bafy2bzacecwym4dcobu7iuar6mwmv7y3kworkt527z2b5w3zjwx2mohaovr7m bafy2bzacedma33qryt2d3qawnuwc3wnlwyuo6buqaag6s6sx4hfzewtfhzp3m], bafy2bzacec3nxnnacnf7irr7tuzxlhxzi65lhohuimianq65v3hev4w5f4ypc) (reason: change contained bafy2bzacebr2w2eog34lx4o7afe7m7holauagpg2j5ra5umeir2b7mutm3yna caused by: [bafy2bzacebr2w2eog34lx4o7afe7m7holauagpg2j5ra5umeir2b7mutm3yna] failed to compute lookback tipset state: vm flush failed: copying tree: get bagboea4b5abcb6mghiqvjfcucp43etgn2noawk7q365qu74htlww7muwdipcuwcn failed: blockstore: block not found)
root@hkgubm01:~#

root@hkgubm01:~# lotus version
Daemon:  0.4.1+git.39216238+api0.6.0
Local: lotus version 0.4.1+git.39216238
root@hkgubm01:~#

What should I do?

**Comment by kelvinzhong** [comment]
same issue, anyone can help?

**Comment by magik6k** [comment]
This is already fixed, update to latest master
