### ISSUE TITLE
Error actor addr when use lotus-miner cli

### ISSUE THREAD

**Issue by GFZRZK** [filecoin-project/lotus#2607]
**Describe the bug**
When executing something like ./lotus-miner --actor=t01000 proving info, you will never get the right result.

**To Reproduce**
1. Run  ./lotus-miner --actor=t01000 proving info,
2. result is always current miner's proving info.

Just review this code [getActorAddress](https://github.com/filecoin-project/lotus/blob/ntwk-calibration/cmd/lotus-storage-miner/main.go#L101), you should directly return maddr, err when overrideMaddr != "".

**Comment by magik6k** [comment]
Potentially fixed in https://github.com/filecoin-project/lotus/pull/2407

**Comment by GFZRZK** [comment]
> Potentially fixed in #2407

actually ,I think this bug is right imported from the Potentially fixed #2252 , when you specific the actor address and get nil err from address.NewFromString(overrideMaddr), it will just go down and goto maddr, err = nodeAPI.ActorAddress(ctx) , it will shadow the true addr you want to return.

**Comment by GFZRZK** [comment]
if the flag --actor never work, how about just remove it from cli, since it really make things confused

**Comment by nonsense** [comment]
@GFZRZK the flag was faulty for a few commands, but not all. What you are reporting should be fixed in #2407 

We need the flag, in order to inspect state for all actors, even if they are not running, so removing is not a good option.

**Comment by GFZRZK** [comment]
@nonsense the problem isn't whether the flag is running or not, I suppose it is a logic mistake since the function I mentioned before, named getActorAddress, always returns current actor address bug, not the one I specific by --actor. Another word, the error don't happen in --actor, but happened in the function  [getActorAddress](https://github.com/filecoin-project/lotus/blob/ntwk-calibration/cmd/lotus-storage-miner/main.go#L101)

**Comment by GFZRZK** [comment]
@nonsense  when no err happened on [maddr, err = address.NewFromString(overrideMaddr)](https://github.com/filecoin-project/lotus/blob/ntwk-calibration/cmd/lotus-storage-miner/main.go#L103), the program will just goto [maddr, err = nodeAPI.ActorAddress(ctx)](https://github.com/filecoin-project/lotus/blob/ntwk-calibration/cmd/lotus-storage-miner/main.go#L109) then maddr will be overwritten , you can never get overrideMaddr, this function can never make sense

**Comment by nonsense** [comment]
@GFZRZK the fix linked in magik6k's comment is fixing this.

**Comment by arajasek** [comment]
The fix is now in `ntwk-calibration` and `next`.
