### ISSUE TITLE
DNS resolution issue in lotus

### ISSUE THREAD

**Issue by momack2** [filecoin-project/lotus#2613]
**Describe the bug**
DNS resolution issue in lotus

**To Reproduce**
1. run `lotus daemon`
2. get error: 

> 2020-07-27T14:31:33.237-0700	WARN	dht/RtRefreshManager	rtrefresh/rt_refresh_manager.go:191	failed when refreshing routing table	{"error": "2 errors occurred:\n\t* failed to query for self, err=failed to run refresh DHT query for key=\u0000$\u0008\u0001\u0012 w\ufffd\ufffd\ufffd\ufffdP&#\ufffd\u0016\u0004:Ҹ\ufffdd\ufffd\ufffdS-q\ufffds\u001d\ufffdV\ufffd\ufffd?[\u001cf, err=failed to find any peer in table\n\t* failed to refresh cpl=0, err=failed to run refresh DHT query for key=\u0012 \u0000\u0000m\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000, err=failed to find any peer in table\n\n"}
2020-07-27T14:31:33.843-0700	WARN	main	lotus/main.go:81	initializing node:
    main.glob..func2
        /Users/nala/lotus/cmd/lotus/daemon.go:249
>  - starting node:
    github.com/filecoin-project/lotus/node.New
        /Users/nala/lotus/node/builder.go:506
>  - could not build arguments for function "github.com/filecoin-project/lotus/node/modules".RunHello (/Users/nala/lotus/node/modules/services.go:31): failed to build *hello.Service: could not build arguments for function "reflect".makeFuncStub (/usr/local/Cellar/go/1.14.4/libexec/src/reflect/asm_amd64.s:12): failed to build *chain.Syncer: could not build arguments for function "reflect".makeFuncStub (/usr/local/Cellar/go/1.14.4/libexec/src/reflect/asm_amd64.s:12): failed to build beacon.RandomBeacon: could not build arguments for function "reflect".makeFuncStub (/usr/local/Cellar/go/1.14.4/libexec/src/reflect/asm_amd64.s:12): failed to build *pubsub.PubSub: could not build arguments for function "reflect".makeFuncStub (/usr/local/Cellar/go/1.14.4/libexec/src/reflect/asm_amd64.s:12): failed to build dtypes.DrandBootstrap: function "reflect".makeFuncStub (/usr/local/Cellar/go/1.14.4/libexec/src/reflect/asm_amd64.s:12) returned a non-nil error: lookup _dnsaddr.pl-us.testnet.drand.sh on 192.168.0.168:53: dial udp 192.168.0.168:53: i/o timeout

3. change `etc/resolv.cof` to comment out:
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
nameserver 192.168.0.168

4. and it works!

**Expected behavior**
It works the first time without commenting these things out

**Screenshots**
see error above

**Version (run `lotus version`):**
nerpanet
Daemon:  0.4.1+git.0a696f35+api0.5.0
Local: lotus version 0.4.1+git.0a696f35

**Additional context**
NA

**Comment by f8-ptrk** [comment]
not a lotus issue - the os should be responsible for dns resolution - not the application

#antidisestablishatarianism
