### ISSUE TITLE
The message with nonce option is always pending.

### ISSUE THREAD

**Issue by FHigher** [filecoin-project/lotus#2620]
**Describe the bug**
I was using command line calls. "lotus send address amount" is ok.  But using "lotus send --nonce=5 address amount", the message is always pending. The value of nonce is obtained from the "MpoolGetNonce" interface.

**To Reproduce**
1. In lotus cli, Run "lotus send --nonce=5 address amount"
2. Wait a minute, Run "lotus mpool pending | grep address", the pending message is still here
3. And, Run "lotus wallet balance address", the balance had never changed

**Expected behavior**

**Screenshots**
<img width="929" alt="image" src="https://user-images.githubusercontent.com/42735634/88608858-4f851080-d0b5-11ea-98e9-43dc132d0258.png">

**Version (run `lotus version`):**
Daemon:  0.4.1+git.190882ee+api0.8.1
Local: lotus version 0.4.1+git.190882ee

**Additional context**

**Comment by f8-ptrk** [comment]
is this resolved?

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket. This seems to be a user action issue, is 5 the next nonce issue? please open a new ticket if you are still facing the issue.
