### ISSUE TITLE
start 0.4.2 lotus failure

### ISSUE THREAD

**Issue by lcgogo** [filecoin-project/lotus#2624]
**Describe the bug**
docker run -d --name fil-test openworklabs/lotus:v0.4.2

**To Reproduce**
1. Run '...'
2. See error
docker logs fil-test
2020-07-28T03:57:00.098Z	INFO	badger	v2@v2.0.1-rc1.0.20200716180832-3ab515320794/levels.go:183	All 0 tables opened in 0s

2020-07-28T03:57:00.119Z	INFO	badger	v2@v2.0.1-rc1.0.20200716180832-3ab515320794/levels.go:183	All 0 tables opened in 0s

2020-07-28T03:57:00.133Z	INFO	badger	v2@v2.0.1-rc1.0.20200716180832-3ab515320794/levels.go:183	All 0 tables opened in 0s

2020-07-28T03:57:00.137Z	WARN	chainstore	store/store.go:143	no previous chain state found
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/go/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.AfterGenesisSet: function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12) returned a non-nil error: genesis func failed: decoding block failed: unmarshaling t.ElectionProof pointer: cbor input had wrong number of fields

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by lcgogo** [comment]
I think it's the docker build issue https://hub.docker.com/r/openworklabs/lotus/tags 0.4.2 has this issue.
I built https://github.com/openworklabs/filecoin-docker by the master branch and it's running now.

**Comment by arajasek** [comment]
@lcgogo can you please file this issue in  https://github.com/openworklabs/filecoin-docker instead?

Thanks!
