### ISSUE TITLE
Creating Storage miner  New storage miners address is: t

### ISSUE THREAD

**Issue by yfeing** [filecoin-project/lotus#2626]
1. Run 'input wallet to  https://faucet.testnet.filecoin.io/'
2. After waiting 5 minutes initialization command is received
 only received :
[CREATING STORAGE MINER]
Gas Funds:   bafy2bzacedzswulagnfnddmq6vemxs4eyokhd2dtryinsdglstqolqayow34w - OK
Miner Actor: bafy2bzacec2v2cqpmhagy54miujjqh7a2dz7vcpfxkk6r6zqajw63vr55ga2k - OK
New storage miners address is: t

**Comment by longmans** [comment]
same issue

**Comment by Dmoney626** [comment]
same issue is there a fix yet?

**Comment by ribasushi** [comment]
centralised miner creation does not work at present
you need to get funds into the wallet ( use the other link: send funds )
and then you do:
`./lotus-miner init  --owner $( ./lotus wallet list ) --sector-size XXX` ( XXX being `512MiB` or `32GiB` )
you will init a miner after a good ~3 minute wait

**Comment by Dmoney626** [comment]
i need to get fund into which wallet and where do i do that command ik in terminal do i have to be cd somewhere

**Comment by ribasushi** [comment]
**assuming** you have a fully synced lotus node ( `lotus sync status | grep Stage` says `Complete` ) you can init a new miner by executing (untested, might have a few typos):
```
FILNET=testnet.filecoin.io
FILSEC=32GiB
lotus wallet new bls
curl  https://faucet.$FILNET/send?address=$( lotus wallet list | grep -m1 '^t3' )
lotus-miner init  --owner $( lotus wallet list | grep -m1 '^t3' ) --sector-size $FILSEC 
```

**Comment by Dmoney626** [comment]
node is synced when i run the lotus miner says command not found

**Comment by ribasushi** [comment]
@Dmoney626 ah right, you are using `master` / testnet which are both pretty far behind and the command there is called `lotus-storage-miner` or something like that.

The latest network will experience a reset in the next ~24h or so, otherwise I would have pointed you there.
Apologies for the state of flux, a number of things are being worked on around the clock.

**Comment by Dmoney626** [comment]
yeah your good

**Comment by Dmoney626** [comment]
yay i got it

**Comment by Dmoney626** [comment]
@ribasushi i did it and it failed

**Comment by ribasushi** [comment]
The network is not well, a reset will happen in the next several hours. Please [join the filecoin slack](https://github.com/filecoin-project/community#chat) and look for an announcement there.

**Comment by longmans** [comment]
> The network is not well, a reset will happen in the next several hours. Please [join the filecoin slack](https://github.com/filecoin-project/community#chat) and look for an announcement there.

is ok now? is there another test net?

**Comment by anneyking** [comment]
> yay i got it

Excuse me, how did you get it?

Execute this
. / lotus-miner init-- owner $(. / lotus wallet list)-- sector-size XXX (XXX being 512MiB or 32GiB) 
to download something for a long time

**Comment by anneyking** [comment]
> centralised miner creation does not work at present
> you need to get funds into the wallet ( use the other link: send funds )
> and then you do:
> `./lotus-miner init --owner $( ./lotus wallet list ) --sector-size XXX` ( XXX being `512MiB` or `32GiB` )
> you will init a miner after a good ~3 minute wait

Excuse me, how did you get it?

Execute this
. / lotus-miner init-- owner $(. / lotus wallet list)-- sector-size XXX (XXX being 512MiB or 32GiB)
to download something for a long time，

Terminal shows that there is 1 day left in the download time.

**Comment by anneyking** [comment]
Excuse me, how did you get it?

Execute this：

lotus-storage-miner init-- owner $(. / lotus wallet list)-- sector-size 32GiB

to download something for a long time

**Comment by anneyking** [comment]
> same issue is there a fix yet?

Excuse me，
issue is there a fix yet?

**Comment by anneyking** [comment]
> > The network is not well, a reset will happen in the next several hours. Please [join the filecoin slack](https://github.com/filecoin-project/community#chat) and look for an announcement there.
> 
> is ok now? is there another test net?

Excuse me, did you succeed in getting the New storage miners address id?
