### ISSUE TITLE
lotus-miner stores sealed sectors regardless of configured storages roles.

### ISSUE THREAD

**Issue by Shekelme** [filecoin-project/lotus#2627]
**Describe the problem**

I have configured different storage paths for sealing (my NVME with OS and the rest) and for storage (Raidz array of 13 HDDs), their roles has been configured and are visible by lotus-miner. But why it continue to store sealed sectors on NVME? Those sectors which are at `/filecoin` now were moved there manually, newly sealed sectors are stored on NVME despite it has no "Store role".

![image](https://user-images.githubusercontent.com/26449500/88637988-1369a400-d0e5-11ea-8291-9a69373d16a9.png)

**Sectors list**

The output of `./lotus-miner sectors list`.
![image](https://user-images.githubusercontent.com/26449500/88638058-2bd9be80-d0e5-11ea-80fc-8ff929c58c08.png)

**Version**

Daemon:  0.4.1+git.190882ee+api0.8.1
Local: lotus version 0.4.1+git.190882ee
#2275

**Comment by Shekelme** [comment]
Later lotus-miner moved the sealed sector to it's storing destination.
![image](https://user-images.githubusercontent.com/26449500/88661762-40c54a80-d103-11ea-8c53-d3b07eab7c06.png)
Wonder why it took so much time, I guess sealed sector should be moved to directory intended as Store right after sealing finish.

**Comment by f8-ptrk** [comment]
resolved 

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
