### ISSUE TITLE
How to check the progress for sealing sector?

### ISSUE THREAD

**Issue by rocqina** [filecoin-project/lotus#2628]
The procedure is too long.

**Comment by magik6k** [comment]
`lotus-miner sectors list` for general sector list
`lotus-miner sectors status --log [sectorID]` for much more info on individual sectors
`lotus-miner sealing jobs` for in-progress jobs

**Comment by kernelogic** [comment]
You can get some ideas in the log see if there's any crashes. When it crashes it can stall.
