### ISSUE TITLE
lotus crashes when making many small deals

### ISSUE THREAD

**Issue by momack2** [filecoin-project/lotus#2634]
**Describe the bug**
`fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x28e57ea, 0x16)
 /usr/lib/go-1.14/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xd088000000, 0x8000000, 0x52c4bb8)
 /usr/lib/go-1.14/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x52ad780, 0x5400000, 0x52ad788, 0x299a)
 /usr/lib/go-1.14/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x52ad780, 0x299a, 0x0)
 /usr/lib/go-1.14/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x52ad780, 0x299a, 0x7fc45fff0100, 0x52c4bc8, 0xc00005cbc8)
 /usr/lib/go-1.14/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()`
[lotus-crash5.log](https://github.com/filecoin-project/lotus/files/4990463/lotus-crash5.log)

**To Reproduce**
1. bots tested running large number small of deals lotus was crashing

**Expected behavior**
Not crashing

**Screenshots**
see attached crashes
[lotus-crash5.log](https://github.com/filecoin-project/lotus/files/4990472/lotus-crash5.log)
[lotus-crash.log](https://github.com/filecoin-project/lotus/files/4990468/lotus-crash.log)
[lotus-crash2.log](https://github.com/filecoin-project/lotus/files/4990469/lotus-crash2.log)
[lotus-crash3.log](https://github.com/filecoin-project/lotus/files/4990471/lotus-crash3.log)

**Version (run `lotus version`):**
calibration devnet

**Additional context**

**Comment by Kubuxu** [comment]
@momack2 the version description there is misleading, it isn't from calibration. It is from the butterfly before calibration.
To be precise before 61f120222ff99e95c0663d2af654fc8ac3f7828a, after that there were many changes to badger so this may be fixed.

**Comment by arajasek** [comment]
May not be a problem anymore thanks to a Badger upgrade.

**Comment by momack2** [comment]
AFAIK this hasn't been repro'd in a while, so closing
