### ISSUE TITLE
Payment Channels Test seems to fail unpredictably

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2639]
The test failed on [this CI build](https://app.circleci.com/pipelines/github/filecoin-project/lotus/7063/workflows/c52f672c-5994-45ef-9431-a018663e9887/jobs/38591) with the following error:

```
Waiting for channel create
Confirmed channel create
    paych.go:107: channel not tracked
```
Passed when re-run.

**Comment by arajasek** [comment]
Update: This might've just been CI whoopsy-daisy-ing

**Comment by dirkmc** [comment]
I wasn't able to repro, so closing. Please reopen if you see this again.
