### ISSUE TITLE
Skip funding storage market for deals if we have enough available funds

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#2645]
Currently, we send a new transaction to add funds to the storage market per deal we make, even if we have enough funds available to cover it already in escrow. We should keep track of how much filecoin we're committing to unpublished deals, and then use that to check if we actually need to send more funds to the storagemarket.

We should also opt towards overfunding if we need to add more funds, often these deals are very little money, and we might as well have some sane default of adding more funds than is necessary for an individual deal, to make future deals faster.

**Comment by f8-ptrk** [comment]
should be resolved as the market actor can be pre funded via lotus command as by now

#antidisestablishatarianism
