### ISSUE TITLE
lotus get paych:  "CallWithGas failed: call raw get actor: resolution lookup failed"

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/lotus#2654]
**Describe the bug**
I get this error when trying to create a payment channel:  `ERROR: initializing paych actor: estimating gas limit: CallWithGas failed: call raw get actor: resolution lookup failed (t1jqla4iimaltyewonoljcqu3j4gjmjvhaacelq3q): resolve address t1jqla4iimaltyewonoljcqu3j4gjmjvhaacelq3q: address not found`

**To Reproduce**
```
$ lotus wallet new
t1jqla4iimaltyewonoljcqu3j4gjmjvhaacelq3q
$ lotus wallet set-default t1jqla4iimaltyewonoljcqu3j4gjmjvhaacelq3q
$ lotus paych get t1jqla4iimaltyewonoljcqu3j4gjmjvhaacelq3q t3schhtef3m5yshlop3ffwjk5lauaqryx2e67xayngbj5stvha6m6i5noqvtiswykqg5pel4wt5j6zlrbblxbq 5000000000
ERROR: initializing paych actor: estimating gas limit: CallWithGas failed: call raw get actor: resolution lookup failed (t1jqla4iimaltyewonoljcqu3j4gjmjvhaacelq3q): resolve address t1jqla4iimaltyewonoljcqu3j4gjmjvhaacelq3q: address not found
```

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
```
$ lotus version
Daemon:  0.4.1+git.190882ee.dirty+api0.8.1
Local: lotus version 0.4.1+git.190882ee.dirty
```
You can ignore the "dirty":  I added a single line `fmt.Printf("MpoolPush: smsg >>>>'\n  Message: %#v\n  Signature:  %#v'\n", smsg.Message, smsg.Signature);` in `func (c *FullNodeStruct) MpoolPush`.  lotus paych get worked last week with this same modification in place.

**Additional context**
I'm on `ntwk-calibration` @ `190882ee`

**Comment by mgoelzer** [comment]
Closing.  This was from being on the old `calibration` testnet after the reset.

**Comment by verynohair** [comment]
Help me, I still got this problem.

**Comment by verynohair** [comment]
Help me, I still got this issue.
When I run 
`./lotus-miner init  --owner $( lotus wallet list | grep -m1 '^t1' ) --sector-size $FILSEC`
to create a miner

the result is
```
2020-07-30T17:54:41.673+0800    ERROR   main    lotus-storage-miner/init.go:239Failed to initialize lotus-miner: creating miner failed:
    main.storageMinerInit
        /opt/lotus/cmd/lotus-storage-miner/init.go:502
  - estimating gas limit: CallWithGas failed: call raw get actor: resolution lookup failed (t1ksusx3x5idfx2zomki26kekveghu6tzl5khi6la): resolve address t1ksusx3x5idfx2zomki26kekveghu6tzl5khi6la: address not found
```
