### ISSUE TITLE
set-addrs gas limit too low

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#2656]
```
lotus --version
lotus version 0.4.1+git.7c775390
```

https://calibration.filfox.io/en/message/bafy2bzacedziavsdg575bv2d7cz7c4xhzecfs4wvgsiyg65v4z6w4ukdyurqi?block=bafy2bzacedvl3l25datzlpu3xoumon2z6addptbyt5trtfkizpimrjco2nlg2

https://github.com/filecoin-project/lotus/blob/477dd536b5b5824a411c24a710af8f8550eb8fdc/cmd/lotus-storage-miner/actor.go#L26-L34

**Comment by travisperson** [comment]
Should these messages get included in blocks and then rejected during execution for not enough gas? Having them sit in the mpool seems like an issue.

**Comment by Kubuxu** [comment]
Yeah, it has slipped.

**Comment by Kubuxu** [comment]
For now, you can manually specify the gas limit of 0: `--gas-limit 0`
