### ISSUE TITLE
Graphsync based retrieval

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#266]
Based on team week discussions, we'll be using graphsync for retrieval, most likely without using the 'data exchange' protocol.

* [ ] Make sure the spec team knows about this
* [ ] Extend go graphsync to support payments
* [ ] IPLD selectors for dag-pb and unixfsv0
* [ ] Integrate in go-lotus

cc @hannahhoward

**Comment by whyrusleeping** [comment]
I think we do this now?

cc @hannahhoward

**Comment by magik6k** [comment]
Done in https://github.com/filecoin-project/lotus/pull/2422
