### ISSUE TITLE
it failed to test the gpu well when using  ./bench sealing --sector-size=2KiB

### ISSUE THREAD

**Issue by rocqina** [filecoin-project/lotus#2661]
![image](https://user-images.githubusercontent.com/15166591/88778660-5eee8180-d1bb-11ea-9fef-7aaac2c9278e.png)

export BELLMAN_CUSTOM_GPU="GeForce GTX 1660 Ti:1536"
./bench sealing --sector-size=2KiB

lotus version
Daemon:  0.4.1+git.c1a814c2+api0.6.0
Local: lotus version 0.4.1+git.c1a814c2

I follow the doc https://docs.lotu.sh/en+mining-troubleshooting. And what means about the error ?

**Comment by f8-ptrk** [comment]
resolved - out of date version

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
