### ISSUE TITLE
Stuck in WaitSeed on calibration network

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#2662]
After precommit phase 2 my miner does nothing so far. It seems just stuck in WaitSeed state forever. This is the info output.

lotus-miner info
Miner: t04034
Sector Size: 32 GiB
Byte Power:   0 B / 73.41 TiB (0.0000%)
Actual Power: 0  / 721 Ti (0.0000%)
	Committed: 0 B
	Proving: 0 B
Below minimum power threshold, no blocks will be won
Miner Balance: 84.626799830870249302 FIL
	PreCommit:   82.13591533985536948 FIL
	Locked:      0 FIL
	Available:   2.490884491014879822 FIL
Worker Balance: 31915.373200169112646946 FIL
Market (Escrow):  0 FIL
Market (Locked):  0 FIL

Expected Seal Duration: 12h0m0s

Sectors:
	Total: 1
	WaitSeed: 1

**Comment by RobQuistNL** [comment]
I think this is supposed to take about an hour. How long did you wait?
