### ISSUE TITLE
retrieval (via slack): every piece which offset is not 0 can't retrieve

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#2665]
**Describe the bug**
"leviok" in Slack reports:

```
offset of piece which saved in piecestore is a padded size. but it used as unpadded size in retrieval. so every piece which offset is not 0 can't retrieve.
```

https://filecoinproject.slack.com/archives/CP50PPW2X/p1595831380044600

**Comment by Reiers** [comment]
Hi @jimpick 

Thanks for the report. The issue is outdated and no one followed up here and Slack. 

Is this an issue in current release? 

Thank you !
