### ISSUE TITLE
lotus deal problem 

### ISSUE THREAD

**Issue by coinmini** [filecoin-project/lotus#2679]
I use two lotus node. A is miner, another is only lotus node called B. I use command at B as follows: `lotus client import xxx `,then i get CID like bafykbzaceasrgc4tecrkvqk7xpbrd3pz6goyutb7cvuekin5rs5bzl2evh3y4; then using` lotus client deal  bafykbzaceasrgc4tecrkvqk7xpbrd3pz6goyutb7cvuekin5rs5bzl2evh3y4  t04030 0.0000000005 622080` . it return bafyreiby33exa2wbvgx47qkrczwm73xhrkr3vgemkqi2ohgbjl4aatcv4e.  

but always see the miner log: 
`
WARN	storagemarket_network	network/deal_status_stream.go:26	failed to read cid field t.Proposal: stream reset
2020-07-29T23:56:58.703+0800	ERROR	storagemarket_impl	impl/provider.go:428	failed to read DealStatusRequest from incoming stream: failed to read cid field t.Proposal: stream reset 
`. 
when i check `lotus client find  bafykbzaceasrgc4tecrkvqk7xpbrd3pz6goyutb7cvuekin5rs5bzl2evh3y4`  i got
```
LOCAL
ERR t03307@12D3KooWCGf55QV5KUDqkCG666msook3nijDnFsKz81a9ZAMkMb5: retrieval query offer errored: get cid info: No state for /bafykbzaceasrgc4tecrkvqk7xpbrd3pz6goyutb7cvuekin5rs5bzl2evh3y4: datastore: key not found
```

i use `lotus client list-deals ` return:
```
DealCid                                                      DealId  Provider  State                          On Chain?       Slashed?  PieceCID                                                          Size       Price             Duration  Message
bafyreiby33exa2wbvgx47qkrczwm73xhrkr3vgemkqi2ohgbjl4aatcv4e  0       t04030    StorageDealCheckForAcceptance  N               N         baga6ea4seaqjyktcpxxxo6sg5olpexeq7mbzt33ue4pn4tnekie7eiva6qjxufy  1.984 MiB  0.0003127985 FIL  625597
bafyreifazquhptxqwvhhklbofbm5pw5b7f6ki5ag7jncz3gvfeuuzyr2q4  6091    t06866    StorageDealActive              Y (epoch 2236)  N         baga6ea4seaqjyktcpxxxo6sg5olpexeq7mbzt33ue4pn4tnekie7eiva6qjxufy  1.984 MiB  0.000313042 FIL   626084
```
As you can see, deal with other peoples miner address t06866 success. My miner t04030 showed  StorageDealCheckForAcceptance for nearly 8 hours

My env: 

i use`dd if=/dev/zero of=~/test512 bs=1M count=512` to generate all zero file

Daemon:  0.4.1+git.477dd536+api0.8.1
Local: lotus version 0.4.1+git.477dd536

root@jj:~/lotus# lotus client query-ask t04030
Ask: t04030
Price per GiB: 0.0000000005 FIL
Max Piece size: 512 MiB

```
miner config.toml as follows:

# Default config:
#SealingDelay = "1h0m0s"
#
[API]
  ListenAddress = "/ip4/192.168.100.112/tcp/2345/http"
  RemoteListenAddress = "192.168.100.112:2345"
#  Timeout = "30s"
#
[Libp2p]
#  ListenAddresses = ["/ip4/0.0.0.0/tcp/0", "/ip6/::/tcp/0"]
ListenAddresses = ["/ip4/0.0.0.0/tcp/5472"]
#  AnnounceAddresses = []
AnnounceAddresses = ["/ip4/114.254.xxx.xxx/tcp/10240"]
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/ip4/147.75.67.199/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
[Dealmaking]
  ConsiderOnlineStorageDeals = true
  ConsiderOfflineStorageDeals = true
  ConsiderOnlineRetrievalDeals = true
  ConsiderOfflineRetrievalDeals = true
#  PieceCidBlocklist = []
# ExpectedSealDuration = "12h0m0s"
#
[Storage]
#  ParallelFetchLimit = 10
  AllowPreCommit1 = false
  AllowPreCommit2 = false
  AllowCommit = false
  AllowUnseal = true
#
```

**Comment by f8-ptrk** [comment]
is this resolved?

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
