### ISSUE TITLE
calibration net: adding market funds failed: estimating gas limit: message execution failed: exit 16, reason: balance to add must be greater than zero 

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#2683]
**Describe the bug**

When trying to make deals from my node, all deals are now failing and `lotus client list-deals` has the following error:

```
bafyreihxxfkny2f3bdxzlwkahf3zixk4d7772q2p2pmasqacueuygyxaum  0     t014805  StorageDealError N  N  baga6ea4seaqkgudy5spdtzcxfmamuxeydfdax5lby6u3tjmzq5go2emjg76syjy  127 KiB 0.000001385512 FIL  692756  adding market funds failed: estimating gas limit: message execution failed: exit 16, reason: balance to add must be greater than zero (RetCode=16)

bafyreihz5nkozi6mgsrppgj4mj4gdtpmspnvjdmfayw5xcrt3pzxcgwdwi  0     t05235   StorageDealError N  N  baga6ea4seaqkgudy5spdtzcxfmamuxeydfdax5lby6u3tjmzq5go2emjg76syjy  127 KiB   0.00000138829 FIL   694145  adding market funds failed: estimating gas limit: message execution failed: exit 16, reason: balance to add must be greater than zero (RetCode=16)
```

I added some logging to the EnsureAvailable method in `chain/market/fundmgr.go`:

https://github.com/filecoin-project/lotus/blob/a9866c757ecf9cb8c14ea561669061cf392d7d7a/chain/market/fundmgr.go#L37

I'm trying to ensure an amount of: 1383182000000

`avail, ok := fm.available[addr]`

`ok` is false, so it then tries:

`bal, err := fm.sm.MarketBalance(ctx, addr, nil)` 

bal.Escrow is 147127400000000
bal.Locked is 77786104000000

So it substracts `Locked` from `Escrow`, and the `avail` is now: 69341296000000

Finally, it substracts `amt` from `avail`, and the new avail is: 67958114000000

That's a positive number, so it sticks the the `toAdd` amount of: 0

So it pushes a message to add '0' funds, which trips the error:

https://github.com/filecoin-project/lotus/blob/a9866c757ecf9cb8c14ea561669061cf392d7d7a/chain/market/fundmgr.go#L68

I'm guessing that the fix is to simply not push a message to add funds if the value of `toAdd` is 0.

**Version (run `lotus version`):**

```
$ ./lotus version
Daemon:  0.4.1+git.a65849e2.dirty+api0.8.1
Local: lotus version 0.4.1+git.a65849e2.dirty
```

**Comment by Reiers** [comment]
Hey @jimpick 

Can you please confirm if this issue is still[ current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.0), or is it fixed?
Thank you!
