### ISSUE TITLE
Fund manager might get stale

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2685]
I think the fund manager has the potential to get into a bad state. For instance, if the deal that required the funds for which `EnsureAvailable` was called fails, then there'll be more available than the fund manager thinks there is.

I don't see anyway the fund manager can be informed "oh, nvm, deal failed, increase the available balance", but maybe this happens somehow?

**Comment by hannahhoward** [comment]
@arajasek it seems like ensure funds is keeping a cache of balances, but the only thing it's caching is reading from the StateManager which is not ... super long. Is there any reason not to just delete this cache and just read directly from the statemanager?

**Comment by hannahhoward** [comment]
@magik6k or anyone who has visibility into the rationale for that cache -- are you ok with this? If so I'll just do that.

**Comment by arajasek** [comment]
@hannahhoward I only discovered this exists yesterday, but I think this exists to provide some "foresight". If the order goes deal1 is processed, deal1's balance updates land on state, deal2 is processed, deal2 updates land in state, your proposal would be fine.

But what if it goes deal 1 is processed, deal 2 is processed, deal 1 lands in state, deal 2 lands in state? In that case, I'm guessing use state as your "source of truth" wouldn't work.

The question is how likely that is -- what happens between `EnsureAvailable` being called and the changes landing?

**Comment by hannahhoward** [comment]
ah ok makes sense.

**Comment by arajasek** [comment]
Update from @hannahhoward 

> after investigating the code for the fundmanager today, it looks like it was doing an extremely incomplete version of what we’re now doing in markets — tracking how much total is needed for deals. Now that we’re doing it in markets it’s not needed in fund manager — and we may actually see double adds of funds in the reset. But also, yes there was minimal tracking of on chain stuff and the value it tracks will get very stale. I’m working on an update across the board.

**Comment by jennijuju** [comment]
resolved in #4736
