### ISSUE TITLE
Integration test for multiple deals in a single sector

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#2686]
We want to verify that:
If two deals are put in a single sector,
So that one is located in the sector at offset > 0
A retrieval still works

Approach:
- add new test to api/tests/deals.go -- probably can reuse most of the code
- call from node/node_test.go TestAPIDealFlow test

Ambiguity:
- need to research how sector packing works to make sure both deals end up in the same sector

**Comment by hannahhoward** [comment]
This is P0 cause it helps debug other reported issues with multiple deals in a sector preventing retrieval

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
