### ISSUE TITLE
some code cannot enter execution in handlePreCommitFailed

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/lotus#2693]
https://github.com/filecoin-project/storage-fsm/blob/master/states_failed.go#L91
if pci, is := m.checkPreCommitted(ctx, sector); is && pci != nil {
        // do something
}

func (m *Sealing) checkPreCommitted(ctx statemachine.Context, sector SectorInfo) (*miner.SectorPreCommitOnChainInfo, bool) {
	tok, _, err := m.api.ChainHead(ctx.Context())
	if err != nil {
		log.Errorf("handleSealPrecommit1Failed(%d): temp error: %+v", sector.SectorNumber, err)
		return nil, true   // pci==nil && is ?
	}

	info, err := m.api.StateSectorPreCommitInfo(ctx.Context(), m.maddr, sector.SectorNumber, tok)
	if err != nil {
		log.Errorf("handleSealPrecommit1Failed(%d): temp error: %+v", sector.SectorNumber, err)
		return nil, true  // pci==nil && is ?
	}

	return info, false  // pci!=nil && !is
}

**Comment by arajasek** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/3445
