### ISSUE TITLE
Abstraction from concrete on-chain data types

### ISSUE THREAD

**Issue by anorth** [filecoin-project/lotus#2697]
The `SealingAPI` interface directly uses a few complex chain state types, including `miner.SectorPreCommitOnChainInfo`, `market.DealProposal`, and `miner.Deadlines`. Referencing the types directly like this makes it impossible to version the chain state as part of a protocol upgrade and have this interface keep working.

Replace the non-trivial chain types with structures containing only the information that the FSM module needs, even if this duplicates some structures. Then, when we have an upgrade, the node connector can interpret the pre- and post-upgrade chain state into the data structures required by the FSM.

CC @icorderi

**Comment by jennijuju** [comment]
@magik6k I feel like we are already doing this https://github.com/filecoin-project/lotus/blob/master/extern/storage-sealing/types.go#L51 can you please confirm?

**Comment by arajasek** [comment]
the actors abstraction handles this for the most part -- we do still use some of these types directly, but it's relatively simple to introduce abstracted types if their shape changes in the future
