### ISSUE TITLE
Serial Sector Scheduling Algorithm

### ISSUE THREAD

**Issue by ognots** [filecoin-project/lotus#2702]
**Current Scheduling Algorithm:**
Queue of unsealed sectors get scheduled for Precommit1 in serial order until all sectors finishing Precommit 1. Process repeats for Precommit2/Commit1/Commit2

**Proposed Additional Scheduling Algorithm**
First sector from queue is schedule to complete all available phases before scheduling next unsealed sector in queue. Sector queue weight is determined by order of arrival and capabilities of worker. Algorithm is in addition to existing algorithm. Could become the new default

**Reason**
* Lower scratch disk requirements 
* Permits larger unsealed queue

**Comment by rjan90** [comment]
Closing this issue as outdated!
