### ISSUE TITLE
Can we specify the max parallel number of tasks/sectors for a worker? 

### ISSUE THREAD

**Issue by liangping** [filecoin-project/lotus#2703]
Currently, the miner distribute tasks automatically, however, we don't want lotus-seal-worker to parallel process too many sectors. for example, Miner distributed 4 sectors to one of my workers, but I only want it to process at most 3 sectors.

Ideally, we want to set a `max_parallel_tasks` for each worker.  because each worker has different processing capability due to its hardwares.  

thanks

https://github.com/filecoin-project/lotus/issues/2359

**Comment by William8Work** [comment]
Is there update on this? As the storage and network grows, I am running multiple workers (probably most of the miners are by now). It would be great to have some fine grain control at per worker level.

**Comment by f8-ptrk** [comment]
i think the scheduler takes care of this with resource allocation checks right now

can this be closed?

#antidisestablishatarianism

**Comment by askender** [comment]
@f8-ptrk    For some machine, it is fast when running 3 task, and slow when running 4 task.
Yes, we can control the MaxSealingSectors in config.yml.    
And we have `lotus-worker set --enabled`  now. 
Maybe it is perfect for you, but maybe not perfect for others.

**Comment by rjan90** [comment]
Hey! Thanks for the issue report.

Closing this ticket now as the are multiple ways of limiting the tasks/sectors for a PC1-worker. First, the builtin scheduler show now be way more considerate about resources on the worker before it schedules something. If you still want a to set a limit, you can change the `PC1_32G_MAX_PARALLELISM=` variable. Set that number to the amount of cores you want the scheduler to use per PC1.

Say you have a 16core CPU, but only want to have 2 PC1-jobs on it - set `PC1_32G_MAX_PARALLELISM=8`.

Closing this issue.
