### ISSUE TITLE
Add a Makefile

### ISSUE THREAD

**Issue by anorth** [filecoin-project/lotus#2706]
As an occasional contributor trying to save maintainers some legwork by doing a dep upgrade, I found it difficult to work out how to build and run this code. I went diving into the CircleCI config.

Add a Makefile with basic rules for build (including externals) and test

**Comment by daviddias** [comment]
note: Add a Makefile to https://github.com/filecoin-project/sector-storage

**Comment by magik6k** [comment]
It's there now
