### ISSUE TITLE
miner error when exec “lotus-storage-miner run”

### ISSUE THREAD

**Issue by rocqina** [filecoin-project/lotus#2708]
![image](https://user-images.githubusercontent.com/15166591/88897346-b0f7db80-d27d-11ea-9a47-c836ed2b1e9d.png)

what means about this?

**Comment by whyrusleeping** [comment]
This looks like your firewall is preventing you from making requests to DRAND. 

@Kubuxu is the pubsub caching not working as expected?

**Comment by Kubuxu** [comment]
It should work, maybe the propagation of drand messages is bad.

**Comment by rocqina** [comment]
ok, thanks!
