### ISSUE TITLE
Gas limiting

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#2722]
The current design for gas limiting in Filecoin has a fairly annoying problem, since miners can't reliably execute messages when including them in a block, they cannot know how much gas they will actually use. Because of this, we are currently using a messages gas limit to enforce block gas limits. This means that if (for example) the block limit is 1000, and I craft two messages with a gas limit of 500, those two messages will fill the entire block, regardless of how much gas is actually used, and I will only be charged for the actual gas used. This last part is the crux of the issue, it becomes very low cost for me to fill the chain with mostly empty messages, and block out all other messages the chain needs to execute by spamming high gas price and high gas limit messages to the chain that end up costing me very little.

To resolve this, we have come up with two different approaches:

## Limit based on actual usage

The way that ethereum does gas limiting is by actually executing each message and not including any messages that would run over the limit for the block. Since we can't reliably do this, what we could do instead is to let miners include as many messages as they want (up to some maximum) and then penalize the miners for any messages that go over the actual gas limit during execution. This puts the onus of gas limit estimation on the miner, and sets up the incentives fairly nicely for miners to do a good job packing blocks. An interesting side effect here is that if we don't count gas from messages that were deduplicated out of a miners message set towards the limit, miners may choose to always include extra messages in their blocks, knowing that some of them will be deduplicated out (on expectation, unless the miner ends up with the lowest ticket), and the remainder of the extra messages would actually get executed, leading to more densely packed tipsets.

The downside of this approach is the added work and engineering effort required to propogate these changes around is very high, and the DX/UX implications are pretty funky. reasoning about message inclusion gets more complicated now, if i see my message included in a block, thats not necessarily meaning it was executed? These messages will need to have special receipts to mark them as not executed, and then we have to do work to ensure the invariant of being able to match up receipts with the canonical message set in a tipset without VM state execution remains stable. Theres a bunch of work here, and it does result in a more complicated system.

For the record, I personally think this is the 'more right' approach.

## Charge users for overestimation

If we don't want to deal with all of that, we could simply charge users for all of the gas represented by their gas limit. This would make the attack we are worried about here very expensive. Doing this naively however, presents some bad incentives, and some bad UX. From the user side, being charged for your whole gas limit is a very bad flow, if you over estimate, you pay too much, and if you underestimate, you still pay the full amount, you just don't get your transaction through. On the incentives side, miners will be very inclined to seek out messages that have over estimated their gas limit as the miner still gets all the funds, for less work. So a trick we can do is to charge users for the amount of gas used, plus burn a portion for overestimation proportional to how much the user overestimated by. For example, if the user estimated the gas would be 1100, but it was actually 1000, the user overestimated by 10%, and then should pay 10% of the difference. 10% of 100 is 10, so we burn 10 * gasPrice for that message. However if the user estimates it will be 1000, but the actual usage is only 100, the user over estimated by 90%, and then we will burn 90% of 900 = 810 gas (times the gas price).

This implies that miners still have to estimate the gas usage of a message in order to maximize profit, but they have an actual incentive to only include the most accurately estimated messages. clients also have an incentive to more accurately estimate their gas limits, but also arent penalized that bad for some mild overestimation.

This approach is simpler to implement, and does appropriately align incentives, the downside is that it doesnt result in as tightly packed blocks as the first approach, and therefore will result in lowered chain throughput. We can compensate for this by raising block gas limits to compensate for the overestimation, targeting some 'average block execution time including overestimation' factor.

**Comment by whyrusleeping** [comment]
The team has discussed this some, and prefers the second option, we will leave this open for discussion for a few days before moving forward on this.

**Comment by anorth** [comment]
As I recall, the thinking for the current approach was that if blocks are full, a miner is incentivised to include messages that will actually consume as much of their gas limit as possible. This sets the right incentives, on the assumption that miners actually care about gas fees. A rational miner wouldn't then include a limit=500 message that only consumes 10 if they have a better option (if they don't have a better option, the implication is that block's aren't full). 

I realise we can't know eventual gas consumption completely reliably, but I would still expect that a miner's estimation by executing the messages they are considering for a block would be pretty good most of the time. A miner could start with a set that would overshoot the block gas limit, execute them all, then remove the least-well-estimated ones to reach a set that fits in the limit.

Is the problem that the gas reward is not sufficient motivation early on? Is this just work that hasn't been done, or that has been done and demonstrated not to be effective?

**Comment by whyrusleeping** [comment]
@anorth miners can't predict actual gas usage very accurately, and really shouldnt be expected to (recall, we explicitly are designing for a system where we don't expect miners to execute transactions while crafting blocks?). Given complete control over the actors in the system, we can make more educated guesses (these guesses still have pretty significant variance) but once we get to real user programmable actors, it all goes out the window.
Setting up the incentives right here for clients to more accurately estimate their gas is important.

**Comment by satoshiquo** [comment]
Why can't Filecoin miners reliably execute messages like ETH miners do?

**Comment by whyrusleeping** [comment]
@satoshiquo because message execution in filecoin happens on a per tipset level. Messages across all blocks in a tipset are linearized, deduplicated, and then executed during the processing of the next block (its not until the next block that you know what the set of blocks in a given tipset will be)

**Comment by whyrusleeping** [comment]
Variant on the quadratic gas charging idea:
Allow messages to overestimate up to some percentage (say 15%) and burn everything over that limit.

So, for example, a message with a gas limit of 150, that ends up costing 100 gas, the miner would receive 100 gas, and we would burn 35.

I think this approach is slightly more effective, as attackers will lose all funds over the estimation allowance (as opposed to just losing a percentage) and normal users overestimating by a reasonable amount are not penalized at all.

**Comment by anorth** [comment]
> we explicitly are designing for a system where we don't expect miners to execute transactions while crafting blocks?

That's not the design goal I recall, though it's a subtle distinction. The design goal is that we don't expect validators to execute transaction in each block independently of the tipset (which would ~double validation time for everyone). But I do expect a block producer to evaluate the messages in _their_ block, which is a very small cost network-wide.

**Comment by arajasek** [comment]
We have since gone with the overestimation burn approach, implemented in https://github.com/filecoin-project/lotus/pull/2764
