### ISSUE TITLE
Can't run local devnet on `next` branch

### ISSUE THREAD

**Issue by Schwartz10** [filecoin-project/lotus#2723]
**Describe the bug**
Following the instructions in https://docs.lotu.sh/en+setup-local-dev-net, when i try to start up my miner i get:

`./lotus-storage-miner run --nosync`

```
2020-07-30T14:57:11.756-0400	WARN	main	lotus-storage-miner/main.go:94	lotus-daemon API version doesn't match: local: +api0.7.0:
    main.glob..func21
        /Users/jonathanschwartz/Documents/owl/fil/lotus/cmd/lotus-storage-miner/run.go:78
```

One clue, when i run:

`./lotus-storage-miner init --genesis-miner --actor=t01000 --sector-size=2KiB --pre-sealed-sectors=~/.genesis-sectors --pre-sealed-metadata=~/.genesis-sectors/pre-seal-t01000.json --nosync`
I get at the bottom of my logs:
```
2020-07-30T14:56:41.552-0400	WARN	main	lotus-storage-miner/main.go:94	Remote API version didn't match (local 0.7.0, remote 0.8.1):
    main.glob..func3
        /Users/jonathanschwartz/Documents/owl/fil/lotus/cmd/lotus-storage-miner/init.go:176
```

**To Reproduce**
Follow the steps in https://docs.lotu.sh/en+setup-local-dev-net

**Version (run `lotus version`):**
`lotus version 0.4.1+2k+git.c7627700.dirty`

**Additional context**
I'm running on MacOS Catalina Version 10.15.2

**Comment by whyrusleeping** [comment]
Are you sure no other lotus daemon or miner is running?

**Comment by Schwartz10** [comment]
I just restarted my machine to be safe, same result. This also happened to someone else I'm working with as well

**Comment by magik6k** [comment]
The `lotus-storage-miner` binary was renamed to `lotus-miner`, the docs site is based on master, so you're likely using the old miner binary - see https://github.com/filecoin-project/lotus/blob/next/documentation/en/local-dev-net.md for more up-to-date instructions
