### ISSUE TITLE
miner should keep a buffer of funds in the storage market

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#2727]
Miners should keep extra funds buffered in the storage market by default so that they can more quickly accept deals as they come in.

Currently, it seems like miners will push funds to the market on demand as deals come in, introduce an addition delay of a few minutes before the client gets confirmation the deal has really been accepted. This is easily avoidable.

**Comment by f8-ptrk** [comment]
this should be solved by prefunding - and no one should ever move funds for "no reason" anywhere anyways

**Comment by Reiers** [comment]
This has been solved in newer versions of Lotus. 

Closing ticket.
