### ISSUE TITLE
lotus-worker should be able to perform unseal task

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#2728]
This is a discussion issue. 

Reasons to do this are mostly around being able to control the resources that are used to perform the task, that the other responsibilities of the miner aren't neglected whilst it is unsealing a sector (a long process atm), making sure that the process that is unsealing has the appropriate hardware available to it.

//cc @ognots @whyrusleeping @magik6k

**Comment by magik6k** [comment]
Workers now support unsealing
