### ISSUE TITLE
`lotus-miner sealing workers list` and `lotus-miner storage list`,the he number of machines displayed is inconsistent

### ISSUE THREAD

**Issue by ytQiao** [filecoin-project/lotus#2729]
**Describe the bug**
`lotus-miner sealing workers list` and `lotus-miner storage list`,the he number of machines displayed is inconsistent

**To Reproduce**
The `lotus-worker`  is connected to the `lotus-miner` . The `lotus-worker` starts successfully. In the `lotus-miner` log, the connection log is seen. The storage space has been connected, but the `lotus-miner sealing workers list` cannot be detected

**Expected behavior**
After a worker joins the cluster, both the `lotus-miner sealing workers list` and `lotus-miner storage list` can retrieve the worker

**Screenshots**
![51FC53EE-63ED-4a6c-8301-82C374D05AD8](https://user-images.githubusercontent.com/49058885/88999911-89aa1880-d328-11ea-8389-5b4414e5dbcb.png)

**Version (run `lotus version`):**
Daemon:  0.4.1+git.477dd536+api0.8.1
Local: lotus version 0.4.1+git.477dd536

**Comment by ytQiao** [comment]
@magik6k @whyrusleeping

**Comment by anneyking** [comment]
Hello, can you show the lotus source directory, please? Mine is also 0.4.1, but I didn't find lotus-miner.

**Comment by ytQiao** [comment]
Source code directory ?

**Comment by anneyking** [comment]
> Source code directory ?

cd  lotus

run:
ls -al

Mine is also “lotus version 0.4.1+git.83e29b1c”, but I didn't find “lotus-miner”。

**Comment by RobQuistNL** [comment]
Note that counting lines makes no sense as the output is human readable;

Worker:
```
Worker 1, host sealer
        CPU:  [                                                                ] 0 core(s) in use
        RAM:  [                                                                ] 1% 1.847 GiB/125.8 GiB
        VMEM: [                                                                ] 0% 1.847 GiB/189.8 GiB
        GPU: GeForce GTX 1080 Ti, not used
```

Storage:
```
726e8daa-9e10-4a62-b4e8-91e43b153927:
        [|||||||||||||||||||||||||||||||||||||||||         ] 1.48 TiB/1.789 TiB 82%
        Unsealed: 3; Sealed: 6; Caches: 2
        Weight: 5; Use: Seal
        URL: http://192.168.2.101:4450/remote (latency: 800µs)
```

Also a single machine can have multiple storages

**Comment by ytQiao** [comment]
I understand what you mean. Yes, it is meaningless if you just count. What I want to express is that my `lotus-worker` storage space is connected to `lotus-miner`, but the `lotus-worker` is not displayed in `lotus-miner sealing workers list` @RobQuistNL

**Comment by yaohcn** [comment]
@ytQiao  "lotus-miner sealing sched-diag"  Is this command stuck?

**Comment by Reiers** [comment]
**Hi @ytQiao** 

Thanks for the report. The issue is outdated, and the cmd works as expected in the latest release.

Example ( I have removed some information, but it should show up correctly when you enter the cmd on your system)

**`lotus-miner sealing workers
`**
```
Worker 04211c84-0473-4fa7-9d39-0000, host worker0
	CPU:  [                                                                ] 0/64 core(s) in use
	RAM:  [|||                                                             ] 5% 12.69 GiB/251.5 GiB
	VMEM: [||||                                                            ] 5% 14.63 GiB/253.5 GiB
	GPU:  [                                                                ] 0% 0.00/1 gpu(s) in use
	GPU: NVIDIA GeForce RTX 3090, not used
Worker 09c9af7b-8ba6-4466-a979-0000 host worker1
	CPU:  [||||||||||||                                                    ] 6/32 core(s) in use
	RAM:  [||||||||                                                        ] 11% 17.67 GiB/125.8 GiB
	VMEM: [|||                                                             ] 3% 15 GiB/381.8 GiB
	GPU:  [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||] 100% 1.00/1 gpu(s) in use
	GPU: NVIDIA GeForce RTX 3090, used
Worker 1ae02d42-9923-42a0-a5fb-0000, host worker2
	CPU:  [                                                                ] 0/64 core(s) in use
	RAM:  [|||                                                             ] 4% 11.02 GiB/251.5 GiB
	VMEM: [|||                                                             ] 4% 12.1 GiB/253.5 GiB
	GPU:  [                                                                ] 0% 0.00/2 gpu(s) in use
	GPU: NVIDIA GeForce RTX 3090, not used
	GPU: NVIDIA GeForce RTX 3090, not used
```

`lotus-miner storage list
`
```
000000-0000:
	[##*                                               ] 1.04 TiB/14.44 TiB 7%
	Unsealed: 3; Sealed: 0; Caches: 0; Reserved: 259.2 GiB
	Weight: 10; Use: Seal 
	URL:(latency: 1ms)

000000-0000:
	[######**                                          ] 1.499 TiB/8.662 TiB 17%
	Unsealed: 2; Sealed: 1; Caches: 2; Reserved: 323.2 GiB
	Weight: 10; Use: Seal 
	URL:(latency: 1ms)

000000-0000:
	[######*                                           ] 1.145 TiB/7.218 TiB 15%
	Unsealed: 2; Sealed: 1; Caches: 1; Reserved: 195.2 GiB
	Weight: 10; Use: Seal 
	URL:(latency: 700µs)

000000-0000:
	[##                                                ] 186.4 GiB/3.581 TiB 5%
	Unsealed: 0; Sealed: 0; Caches: 0; Reserved: 0 B
	Weight: 10; Use: Seal 
	URL:(latency: 800µs)

```
If this is a issue in current release - please open a new ticket.

Thanks again !
