### ISSUE TITLE
While Sealing, provide a better error if there is an attempt to retrieve the data.

### ISSUE THREAD

**Issue by daviddias** [filecoin-project/lotus#2733]
From @whyrusleeping 

> Tried retrieving a file while is was being sealed got: 
> ```
> ERR t03415@12D3KooWKseJZkJJkh1t8VuQiQLdk6ihhEykv4wa3V3EkdGquNVA: retrieval query offer errored: get cid info: No  state for /bafk2bzaceczravmbodganhtqynfirdn6efs6a5vhaep6wbq2fmmuqiszzbgdu: datastore: key not found
> ```

Goal: Provide a better error (e.g. data being sealed)

Additionally, if a miner doesn’t have the data, it should return a better error than this (a simple ‘not found’ should do)

**Comment by arajasek** [comment]
This has been fixed by allowing data to be retrieved even while sealing. https://github.com/filecoin-project/sector-storage/pull/88/files
