### ISSUE TITLE
storage FSM just not tracking sector upgrades / expiration

### ISSUE THREAD

**Issue by daviddias** [filecoin-project/lotus#2735]
Issue reported by Josh and triaged by @magik6k 

Command: `./lotus-miner sectors mark-for-upgrade <sector ID to upgrade>`

> @Josh I tried this command and waited for significantly long time (during which I also accepted and processed quite a lot of deals from other nodes). However, these sectors marked for upgrade did not seem to change.
> @Magik6k: storage FSM just not tracking sector upgrades / expiration
> @mosh meaning, the upgrade was performed but the correct state is not available via CLI

**Comment by mishmosh** [comment]
Adding `goal/incentives` label since this will need to be fixed before competition start.

**Comment by ribasushi** [comment]
@daviddias @magik6k I don't think this ticket is accurate, please see https://github.com/filecoin-project/lotus/issues/2807

**Comment by ZenGround0** [comment]
With v15 and the deprecation of the old concept of CC upgrade this issue is no longer relevant
