### ISSUE TITLE
GPU is not used when running precommit2

### ISSUE THREAD

**Issue by rocqina** [filecoin-project/lotus#2737]
![image](https://user-images.githubusercontent.com/15166591/89028129-52565e80-d35e-11ea-9caa-26837a8e1061.png)

What is needed to config?

**Comment by magik6k** [comment]
Just setting `FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1 FIL_PROOFS_USE_GPU_TREE_BUILDER=1` env vars should be enough

Note that you'll need GPUs with more than 4GB of memory (=4G may not work)

**Comment by f8-ptrk** [comment]
should be resolved 

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
