### ISSUE TITLE
this will never "randomize interval by ~10%"

### ISSUE THREAD

**Issue by ricktian1226** [filecoin-project/lotus#2739]
**Describe the bug**
	// randomize interval by ~10%
	interval := (HeartbeatInterval*100_000 + time.Duration(rand.Int63n(10_000))) / 100_000

**To Reproduce**
NA

**Expected behavior**
    interval should be [HeartbeatInterval, HeartbeatInterval*(1.1)) 

**Screenshots**
NA

**Version (run `lotus version`):**

**Additional context**
maybe should be like this:
interval := HeartbeatInterval*time.Duration(100_000+rand.Int63n(10_000)))

**Comment by ricktian1226** [comment]
sector-storage/stores/local.go line 169

**Comment by Reiers** [comment]
Hi @ricktian1226 

Thanks for the report. The issue is outdated, and have gone stale. 

If this is a issue in current release?
