### ISSUE TITLE
Retrieval deals fail if running many in parallel

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/lotus#2743]
From @stefangeorgerobert:
> I’ve tried running parallel retrievals for approx 10 hours on our dev environment and most of the retrievals failed with timeout.

```
2020/07/31:43:23:984  [ INFO ]   RetrieveDeals: TOTAL : 61
2020/07/31:43:23:984  [ INFO ]   RetrieveDeals: SUCCESSFUL : 3
```

> - In order to run a retrieval bot that doesn't crash its lotus node, we are heavily constraining the retrieval volume. MAX_RETRIEVE_DEALS_RUNS is currently set to 2, that means the bot can request only 2 and wait for the result.
> - Serial retrievals seems more successful  as on calibration.spacerace dashboard the Average Retrieval Deal Success Rate is 26% at the moment

Based on @jimpick's manual testing:
> Based on manual testing with my custom testground instance, if I do a single retrieval, it completes in 1 minute. If I do 2 in parallel, each takes 2 minutes to complete. If I do 6 in parallel, each takes 7 minutes to complete.

@dirkmc has a PR that may address this, but not confirmed.
https://github.com/filecoin-project/lotus/pull/2640

**Comment by whyrusleeping** [comment]
Thanks for the report! I think this should be resolved by #2640 , but am not 100% sure.

@dirkmc what do you think?

**Comment by mishmosh** [comment]
This is causing delays to the retrieval deal-making rate from the Space Race bot.

**Comment by jimpick** [comment]
#2640 has landed and when I test parallel deals using my testground setup, they run as fast as single deals.
