### ISSUE TITLE
Update to latest CBOR

### ISSUE THREAD

**Issue by daviddias** [filecoin-project/lotus#2747]
Repos that need updating

* filecoin-project/lotus
* filecoin-project/go-fil-markets
* filecoin-project/specs-actors
* filecoin-project/go-amt-ipld
* filecoin-project/go-data-transfer

**Comment by magik6k** [comment]
- [ ] https://github.com/filecoin-project/go-data-transfer/pull/60

**Comment by magik6k** [comment]
- [ ] https://github.com/filecoin-project/go-amt-ipld/pull/28
