### ISSUE TITLE
GasPrice and GasLimit have global policies/configs

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#2759]
Allow setting GasPrice and GasLimit policies for all actions node does.

**Comment by lucas556** [comment]
me too

**Comment by raulk** [comment]
Given the terminology and the time of filing, this issue is prior to EIP-1559 being implemented. That said, the requirement to allow per-action adjustment of the fee cap still applies, and is being addressed in #5869.

**Comment by Reiers** [comment]
Hi folks 

Looks like everything talked about here is either merged or closed.
The conversation has been silent for almost a year, should we keep this open or close it? 

Thank you !
