### ISSUE TITLE
GPU workering ,  miner is stop

### ISSUE THREAD

**Issue by litai686** [filecoin-project/lotus#2770]
![image](https://user-images.githubusercontent.com/38679986/89112845-ba5e8f00-d49b-11ea-9bec-4d96e3cac12a.png)

**Comment by f8-ptrk** [comment]
resolved

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
