### ISSUE TITLE
Pubsub module is spamming the logs 

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#2771]
**Describe the bug**
Lotus log file is getting filled with lots of the following message, with repeats of the exact message every ~100 millisecond
```
{"level":"warn","ts":"2020-08-02T11:44:47.946+1000","logger":"pubsub","caller":"go-libp2p-pubsub@v0.3.4-0.20200731161531-2b5243c72f0d/gossipsub.go:1061","msg":"dropping message to peer 12D3KooWMxY3prbycpfDo8aw9XebXzArL2F6RntRnHMNtq2iU9X2: queue full"}
```
//cc @vyzo

**Comment by vyzo** [comment]
Yes, I am aware; perhaps we should drop this to INFO or DEBUG.
The point here is that messages are being dropped because the queue for this peer is full -- either because it is not reading fast enough or because we are not writing fast enough.

**Comment by rjan90** [comment]
I think this issue can be closed now, as the default lotus log is not logging the `dropping message to peer` anymore? #rengjøring
