### ISSUE TITLE
lotus client list-deals show error

### ISSUE THREAD

**Issue by chunqizhi** [filecoin-project/lotus#2772]
![image](https://user-images.githubusercontent.com/23360623/89120348-3252a680-d4e8-11ea-8150-4a8aa99700f3.png)

There were some deals, but others were not shown because of this problem.

**Comment by rjan90** [comment]
I think this issue can be closed, as this has not happend on newer versions of Lotus? #rengjøring

**Comment by Reiers** [comment]
**Issue solved in newer version of Lotus.**
Closing this ticket.
