### ISSUE TITLE
Create miner faild during the last 3 days

### ISSUE THREAD

**Issue by jack2007** [filecoin-project/lotus#2773]
**Describe the bug**

Following the guidance, create miner failed.
It only shows a "t" on the page.

_[CREATING STORAGE MINER]
Gas Funds:   bafy2bzacebap6mtc72fltgmfqavr7tsgn7wwnt6t4vylzuviv6rjzydedtdrq - OK
Miner Actor: bafy2bzacect7esxskltps3nqsv33wc6mmz7kz4gtgey22r5omjh4vgbpz56ts - OK
New storage miners address is: t_

**To Reproduce**
1  Following the guidance, create miner

**Expected behavior**

**Screenshots**
N/A

**Version (run `lotus version`):**
0.4.2

**Additional context**

**Comment by arajasek** [comment]
The previous network devolved into effective unusability due to a combination of spam messages and gas issues. We have since improved (though not solved this).

**Comment by LittleYYang** [comment]
The issue is still there, how to fix/work around this issue? Thanks.
