### ISSUE TITLE
JWT Verification failed

### ISSUE THREAD

**Issue by xfo-bits** [filecoin-project/lotus#2774]
lotus : version 0.4.1+git.5212db89

When I run 1 miner with 6 workers, all 6 workers are using the same miner token, and all 6 workers are  listening on their 2345/tcp.
4 of these worker get the warning information every 5 mircoseconds. These requests/warnings occupy lots of network resources ,the miner becomes very slow to do other worker.

When I changed these 4 workers' listening port to another port (3345,2360 or 2361), these warning messages disappeared.

 [https://filecoinproject.slack.com/archives/C017CCH1MHB/p1596421355244900](url)

![图片](https://user-images.githubusercontent.com/68815100/89151950-a77bb580-d594-11ea-86b5-273b262fb237.png)
![图片](https://user-images.githubusercontent.com/68815100/89151997-bebaa300-d594-11ea-878f-bbd88dcfc981.png)

![图片](https://user-images.githubusercontent.com/68815100/89152145-1822d200-d595-11ea-9b97-f18f6871c001.png)

**Comment by rjan90** [comment]
I think this issue can be closed, as the `JWT Verification failed` indicates that there is some other process trying to reconnect to the api with the old api key, and in that sense it is not an Lotus-issue per se! :smiley:  #rengjøring

**Comment by Reiers** [comment]
@rjan90 Correct. Closing the issue.
