### ISSUE TITLE
Randomness usage in Filecoin

### ISSUE THREAD

**Issue by nicola** [filecoin-project/lotus#2775]
- VM: GetRandomnessFromBeacon and GetRandomnessFromTickets: https://github.com/filecoin-project/lotus/issues/2148
  - Current randomness should not use VRF input.
  - Code: https://github.com/filecoin-project/lotus/blob/c8104a03e61f56f17c4a39d5efbf0ad23069dc07/chain/store/store.go#L962-L991
  - This is described in here: https://github.com/filecoin-project/specs/pull/967/files#diff-440d67a4748619ac846e6d07011156a7R79-R118
- SealRandomness should use GetRandomnessFromTickets, and all the other usages should be GetRandomnessFromBeacon
  - https://github.com/filecoin-project/lotus/issues/2435
  - https://github.com/filecoin-project/specs-actors/pull/679

Overall review and check the consistency of lotus with the spec PR: https://github.com/filecoin-project/specs/pull/967

**Comment by arajasek** [comment]
https://github.com/filecoin-project/lotus/issues/2435

**Comment by nicola** [comment]
Linking also this issue on VRF ticket chain: https://github.com/filecoin-project/lotus/issues/2778

**Comment by daviddias** [comment]
Next: @nicola & @arajasek  to review PR linked by @arajasek and ensure it conforms to the spec

**Comment by nicola** [comment]
Next steps:
- Review lotus PR that implements randomness changes
- Waiting for VRF ticket should be a chain https://github.com/filecoin-project/lotus/issues/2778

**Comment by nicola** [comment]
PR to check: https://github.com/filecoin-project/lotus/pull/2965/files

**Comment by nikkolasg** [comment]
Fetch randomness from chain https://github.com/filecoin-project/lotus/issues/3613

**Comment by nicola** [comment]
Closing this in favour of other specific issues
