### ISSUE TITLE
Replay attacks mitigation for ProveCommit and SubmitWindowedPoSt

### ISSUE THREAD

**Issue by nicola** [filecoin-project/lotus#2780]
Both  ProveCommit and SubmitWindowedPoSt require a chain reference.

- Issue in actors code: https://github.com/filecoin-project/specs-actors/issues/407
- PR in actors code: https://github.com/filecoin-project/specs-actors/pull/680

**Comment by daviddias** [comment]
note: chain reference -> ticket value
