### ISSUE TITLE
Miner should check local peer ID against chain state peer ID on startup

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#2781]
If someone attempts to transfer their miner to a different repo, or the keys change for some reason, the miner should pick up on this and alert the user. I'm not sure if it should automatically update the peer ID, but doing nothing right now isnt the right answer.

**Comment by Reiers** [comment]
Hi @whyrusleeping 

Thanks for the report. The issue is outdated, and have gone stale.

Is this something you still think we should add? Close or keep open?

Many thanks!
