### ISSUE TITLE
systemd improvements

### ISSUE THREAD

**Issue by PatrickDeuse** [filecoin-project/lotus#2782]
Hi,

i will split this in a "should be fixed" and a "discussion" part. We will be happy to fix the "should be fixed" part via merge request right away - but we do not want to make the deeper changes without further discussion.

### Should be fixed:
**A.** When running `make install-services`or `make install-chainwatch-service` the `*.service` files are being deployed to `/usr/local/lib/systemd/system/`. While this works on the latest versions of debian based systems (we tested debin 10  and ubuntu 2004) it should fail on the older but still suported versions (debian 8/9 and ubuntu 16.04/18.04). 

See:
https://manpages.debian.org/jessie/systemd/systemd.unit.5.en.html
https://manpages.debian.org/stretch/systemd/systemd.unit.5.en.html
https://manpages.debian.org/buster/systemd/systemd.unit.5.en.html
http://manpages.ubuntu.com/manpages/xenial/man5/systemd.unit.5.html
http://manpages.ubuntu.com/manpages/bionic/man5/systemd.unit.5.html
http://manpages.ubuntu.com/manpages/focal/man5/systemd.unit.5.html

In general there seems to be an agreement that only software installed via packet managers should move their `*.service` files to `/usr/local/lib/systemd/system/` and software installed by hand should use `/etc/systemd/system/`.

_As long as lotus is not properly packaged the path should be changed to `/etc/systemd/system/`._ 

See: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path

**B.** The make targets are inconsistent. `install-services` installs 2 services, `install-chainwatch-service` installs one service and `clean-services` removes all 3 together. The targets should 

Option 1.) be installed and removed via 3 install and 3 clean targets [EDIT]
or
Option 2.) collectively installed and removed via 1 install and 1 clean target [EDIT]
or
Option 3.) Option 1 and Option 2 [EDIT]

_We would go for option 3 since it provides maximum flexibility for the user._

**C.** The documentation needs to fixed: https://github.com/filecoin-project/lotus/blame/master/documentation/en/install-systemd-services.md#L7-L9 need to be worded accordingly to the above changes in **A+B** and the reason for `make install` needs to be run before using systemd is that systemd needs an absolute path for ExecStart and not that root cannot access the files if not run. In addition the logfile location should be mentioned (see discussion part **A**) and the config file location for `chainwatch` should also be mentioned (see discussion part **A**)

 _If there are no objections to these changes we would move forward and send a merge request._

### Discussion:

**A.** Systemd provides measures to sandbox applications.

See: https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Sandboxing

We think if using systemd lotus should make use of, at least some of these. Namely, for now:

- `LogsDirectory` (https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=)
- `ConfigurationDirectory` (at least for chainservice, it uses a config file in the expected location already, https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=)

Advantages: the directories would be cleaned properly if wanted via systemctl. (See: https://www.freedesktop.org/software/systemd/man/systemctl.html#clean%20PATTERN%E2%80%A6) and lotus could make use of the coresponding env vars (the logpath points to an expected location right now anyways - but still). Preperation for upcoming packaging of lotus for linux packet managers.

We put this under discussion because it will create "problems" in combination with the next topic.

**B.** The systemd daemons shouldn't be run as root. There should be a dedicated user for running the daemons. 

This will pose complications during install - creating the user, and getting access to the IPC for things like `lotus sync status` etc. But we still think it's worth it since using systemd shouldn't broaden the attack surface in comparison to running it manually with a non root user.

We are currently creating a non system user for that with a specific UID/GID to avoid inconsistencies between systems. 
`useradd -m -u "$USER_ID" -U  -s /usr/bin/nologin -b "$USER_HOME_BASE" -c "$USER_COMMENT" -k /bin/false "$USER_NAME` 
The user home is set to the directory the lotus daemon saves its stuff in. This would become irrelevant with proper implementation of Discussion topic **A.** 

**C.** Additional hardening measures
We are only running the daemon right now and are still testing the chainwatch tool. For the daemon systemd service we use

- `PrivateTmp=true` (https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateTmp=)
- `ProtectSystem=full` (https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectSystem=)
- `ProtectHome=true` (https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectHome=)
- `NoNewPrivileges=true` (https://www.freedesktop.org/software/systemd/man/systemd.exec.html#NoNewPrivileges=)
- `PrivateDevices=true` (https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateDevices=)

It's a p2p application - there seems to be no reason to not do it. As said before we only tested this for the daemon so far - we are not sure if the same values can be safely set for the chainwatch and miner (we expect no problems with the values for the chainwatch thou - the miner on the other hand...). Can someone with deeper insight into the miner code give some recommendations on this topic? It would save us some time since we do not run the miner nor plan to do so - but it might need access to devices in `/dev/` that `PrivateDevices=true` denies (they could then be listed via `DeviceAllow`)

Even `RootDirectory` (https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RootDirectory=) should be considered.

The daemon crashes when run via systemd with the `MemoryDenyWriteExecute=true` (https://www.freedesktop.org/software/systemd/man/systemd.exec.html#MemoryDenyWriteExecute=) option - we are not sure why it would need that kind of memory. If someone can give us a hint where to look for why it needs it - please do so (is there JIT stuff going on somewhere? is it the compiler?).

We would be happy to provide the community with a secure systemd configuration, documentation and maintenance for such - but we unfortunately do not have time for deep dives into the code right now - our main target is not having the p2p mob ravaging our bc node servers.

Thanks for your time!

**Comment by placer14** [comment]
@PatrickDeuse Thank you so much for putting this issue together! Will try to respond in a threaded fashion...

# To be fixed

> *A.* ...In general there seems to be an agreement that only software installed via packet managers should move their *.service files to /usr/local/lib/systemd/system/ and software installed by hand should use /etc/systemd/system/.

I'm not very familiar with systemd convensions and deferred to @Kubuxu for suggestions on service file location. Does this sound okay to you, @Kubuxu?

> *B.* The make targets are inconsistent.

Absolutely. I would like to see something along these lines, personally:
`install-services: install-lotus-daemon-service install-lotus-miner-service install-lotus-chainwatch-service`
`clean-services: clean-lotus-daemon-service clean-lotus-miner-service clean-lotus-chainwatch-service`

> *C.* The documentation needs to fixed

Agree with your assessment on ambiguities in the description. Might be worth including the [options](https://github.com/filecoin-project/lotus/blob/next/cmd/lotus-chainwatch/main.go#L23-L39) in a README at the root of https://github.com/filecoin-project/lotus/tree/next/cmd/lotus-chainwatch and referencing this chainwatch readme in those lotus docs.

# Discussion items

> *B.* The systemd daemons shouldn't be run as root. There should be a dedicated user for running the daemons.

Agreed. This is probably the more important discussion item of the three in the short term. The only concern I can think of here is when chainwatch starts up, it accesses `$LOTUS_PATH/token` for the JWT token to connect to the lotus API. In order to avoid user perms from being a thing here, chainwatch could optionally accept `$LOTUS_TOKEN` which will be used by chainwatch to skip the file access entirely.

@arajasek @magik6k @Kubuxu @whyrusleeping can you think of any other reasons we might want to avoid creating a dedicated user for a systemd-managed lotus-chainwatch (or even lotus-daemon/lotus-miner) service? Perhaps some other shed tools which might be affected?

> *A.* Systemd provides measures to sandbox applications.
> *C.* Additional hardening measures

Would need to read into these features to understand them before I can comment on adoption here. @Kubuxu @magik6k do you have strong opinions with these recommendations that you have time to share now? (I'd say these are low priority and could easily wait until after Space Race launch.)

> We would be happy to provide the community with a secure systemd configuration, documentation and maintenance for such - but we unfortunately do not have time for deep dives into the code right now - our main target is *not having the p2p mob ravaging our bc node servers*.

Please let us know if any of the discussion items above are critical or related to the above concern.

Thanks again for the thorough issue! 🤝

**Comment by PatrickDeuse** [comment]
>>    We would be happy to provide the community with a secure systemd configuration, documentation and maintenance for >such - but we unfortunately do not have time for deep dives into the code right now - our main target is not having the p2p >mob ravaging our bc node servers.

>Please let us know if any of the discussion items above are critical or related to the above concern.

Non of the discussion items is critical i think. Nontheless lotus has an extensive dependency tree - importing dozens, if not hundrets of other go modules - creating the risk of importing security issues that are way up the tree or even intetional malicious code. Locking in the binaries that have a network exposed surface would help to mitigate some of the risks that come with that exposure.

**Comment by PatrickDeuse** [comment]
closing this due to lack of interest in developing it
