### ISSUE TITLE
Ran setors pledge 1000 times, only ended up with ~450 sectors after a while of waiting

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#2786]
Everythings in the title, I have since deleted this miner unfortunately, will try to reproduce.

**Comment by whyrusleeping** [comment]
I was not using a seal worker, just the miner itself

**Comment by Reiers** [comment]
**The good old times.** 
For the record - do not attempt this with only one miner/worker. 

Closing this one.
