### ISSUE TITLE
Lotus test results based on ARM architecture

### ISSUE THREAD

**Issue by lin6461** [filecoin-project/lotus#2787]
Test results of Kunpeng 920 chip
With the development power of China Huawei and China wheat field cloud two companies, based on the ARM architecture running lotus test situation.Kunpeng 920 Model 7265 chip in their own lotus bench testing tools test, spreCommit phase 1 on the test results on Kunpeng 35.78 s, with the AMD 7nm 7302 chip 35.2 test results basically hold this.

[Lotus test results based on ARM architecture.pdf](https://github.com/filecoin-project/lotus/files/5017407/Lotus.test.results.based.on.ARM.architecture.pdf)

**Comment by RobQuistNL** [comment]
Those are fun numbers, but the 32GiB sector would be much more interesting :)

Also, no need to download the PDF, here are the 3 pages:
![image](https://user-images.githubusercontent.com/1442796/89225017-d10b0000-d5d9-11ea-8f4e-394b75648a8e.png)
![image](https://user-images.githubusercontent.com/1442796/89225046-dcf6c200-d5d9-11ea-81f6-767dae3ef01a.png)
![image](https://user-images.githubusercontent.com/1442796/89225067-e7b15700-d5d9-11ea-8393-f3b4bd742670.png)

Also don't think this really is an issue, and even so might be better off in flat plain-text format in this repo: https://github.com/filecoin-project/benchmarks

**Comment by arajasek** [comment]
^everything Rob said

**Comment by lin6461** [comment]
The data of the 32G sector is being tested and will be announced in the two days. @RobQuistNL
