### ISSUE TITLE
No any progress in this state  two days when run "lotus-storage-miner run"

### ISSUE THREAD

**Issue by rocqina** [filecoin-project/lotus#2798]
![image](https://user-images.githubusercontent.com/15166591/89244282-aac87d00-d638-11ea-9e77-6111c2ebf3a1.png)

**Comment by f8-ptrk** [comment]
10 month old

resolved

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
