### ISSUE TITLE
almost the sectors stuck at CommitWait

### ISSUE THREAD

**Issue by wellhealth** [filecoin-project/lotus#2800]
almost the sectors stuck at CommitWait ,And most of the time has more than 12 hours

 Miner: t04421 

**Screenshots**
Miner Balance: 51558.31189471963551463 FIL
        PreCommit:   6593.037877285368751553 FIL
        Locked:      0 FIL
        Available:   44965.274017434266763077 FIL
Worker Balance: 5351.461691436773725399 FIL
Market (Escrow):  0 FIL
Market (Locked):  0 FIL

Expected Seal Duration: 12h0m0s

Sectors:
        Total: 1690
        Removed: 76
        PreCommit1: 297
        PreCommit2: 75
        PreCommitWait: 618
        WaitSeed: 17
        Committing: 112
        CommitWait: 469
        PreCommitFailed: 1
        CommitFailed: 25

**Version (run `lotus version`):**
Daemon:  0.4.3+git.460723d2+api0.8.1
Local: lotus version 0.4.3+git.460723d2

**Additional context**

**Comment by yaohcn** [comment]
same problem

Miner: t022917
Sector Size: 512 MiB
Byte Power:   106.5 GiB / 1.151 PiB (0.0088%)
Actual Power: 106 Gi / 1.57 Pi (0.0064%)
        Committed: 107 GiB
        Proving: 107 GiB (512 MiB Faulty, 0.46%)
Expected block win rate: 0.9216/day (every 26h2m30s)

Miner Balance: 86.828563423991926362 FIL
        PreCommit:   36.472549534681804067 FIL
        Locked:      7.160261101790171221 FIL
        Available:   43.195752787519951074 FIL
Worker Balance: 49889.681949796953566249 FIL
Market (Escrow):  0 FIL
Market (Locked):  0 FIL

Expected Seal Duration: 12h0m0s

Sectors:
        Total: 403
        Proving: 213
        WaitSeed: 1
        CommitWait: 188
        CommitFailed: 1

**Comment by f8-ptrk** [comment]
should be resolved

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
