### ISSUE TITLE
Lost all storage power with a failed Window PoSt

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/lotus#2801]
@whyrusleeping @magik6k @travisperson 

We lost all the storge power with the error:

```
2020-08-04T00:04:31.208Z        ^[[31mERROR^[[0m        storageminer    storage/wdpost_run.go:487       
Submitting window post bafy2bzacedbnejhg6snqeg3kda37c52k64xpmq55ihga6ysiacirkpglldh6c failed: exit 16
```

![image](https://user-images.githubusercontent.com/4746061/89247384-cb480580-d63f-11ea-87b2-6563949a2747.png)

So, is there any ways to retry generate and submit window PoSt and recover the faulty sectors? 
After all, the data is not lost, maybe it's just computing failure or network reasons that cause the proof submission failed.

One more question is after we lost all the powers, all the sealings jobs were stoped and we can't make it start to work again.

![image](https://user-images.githubusercontent.com/4746061/89247500-1104ce00-d640-11ea-99ac-c76eb5c209a5.png)

**Comment by travisperson** [comment]
```
lotus state replay bafy2bzacedbnejhg6snqeg3kda37c52k64xpmq55ihga6ysiacirkpglldh6c
Replay receipt:
Exit code: 16
Return:
Gas Used: 2937477
Error message: "invalid deadline 0 at epoch 8299, expected 3 (RetCode=16)"
```

**Comment by madper** [comment]
any log like `can't acquire lock` when you losing all sectors?

**Comment by yangjian102621** [comment]
@madper Yep, i remember there also some logs like `can not aquire the sector lock`.

**Comment by madper** [comment]
Congratulations you reproduced the same issue as mine! https://github.com/filecoin-project/lotus/issues/2754

**Comment by madper** [comment]
Btw, @yangjian102621  8.78T, you are a large miner. Hopefully, you can feel the envy from my side. :1st_place_medal:
