### ISSUE TITLE
How do I safely shutdown a lotus-worker?

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#2802]
Marty the miner needs to apply security updates to their operating system and needs to restart their host. How does smarty stop the lotus-miner from scheduling additional jobs onto the worker so that they can safely reboot their hosts without foobaring their miner?

**Comment by raulk** [comment]
@magik6k is this a question, or is it a statement? Do we have a way to safely shutdown a Lotus worker?

**Comment by f8-ptrk** [comment]
you can't. just kill it.  duplicate issue 

#5227 

https://github.com/filecoin-project/lotus/issues?page=34&q=is%3Aopen+is%3Aissue
