### ISSUE TITLE
Unable to create new miner on Calibration faucet

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#2804]
**Describe the bug**
When I tried to create a new miner on calibration faucet, the faucet page threw an error that it could not.
I tried again and got the same error.
I tried from a different browser and got the same error.
When tried again it said my new wallet had been entered too many times.
When I tried with a new wallet address, it threw this error: "Too Many Requests: IP limit"

**To Reproduce**
1. Open browser at: https://faucet.calibration.fildev.network
2. Enter wallet address and 32 GiB sectors - press enter for create new miner
3. See error creating new miner

**Expected behavior**
I expected to get a miner ID

**Screenshots**

**Version (run `lotus version`):**
Daemon:  0.4.3+git.460723d2+api0.8.1
Local: lotus version 0.4.3+git.460723d2

**Additional context**
Initial wallet address:
t3u2sq5empwohc64e6k3ubef76iem5kbhrad6zpn6qtffrlblaytxlhdnu6v7kxr25mmlpab2ohvyvj3a6h3pa

Then newer address:
t3utgexdp24gb523czhufotwwfssqsqrfbi6pxyrmvs56prcjs57t77nmdoorhgbjhpxicdwqiqzq4owqkfhya

How can I get a miner ID and FIL now?

**Comment by stuberman** [comment]
BTW - This was using Brave Browser on MacOS 10.15.6
Brave Version: Version 1.13.54 Chromium: 84.0.4147.105 (Official Build) beta (64-bit)

When I retried on  VPN using Safari, I was able to get a miner ID

<img width="748" alt="Screen Shot 2020-08-03 at 11 26 32 PM" src="https://user-images.githubusercontent.com/49840642/89250582-12ec7400-d5e3-11ea-8903-39c30cff1054.png">

**Comment by arajasek** [comment]
Looks like the network / faucet may be having issues again, unfortunately

**Comment by wsfnk** [comment]
![image](https://user-images.githubusercontent.com/26306360/89365099-820eb900-d706-11ea-9b67-568d3740a0b9.png)
As shown in the figure, I also encountered the same problem, unable to obtain the miner id

**Comment by littlekai999** [comment]
Same issue, any one can help?

**Comment by stuberman** [comment]
Looks like this has been resolved with latest release
