### ISSUE TITLE
commit1 and finalize will never sched when miner and worker restart

### ISSUE THREAD

**Issue by yaohcn** [filecoin-project/lotus#2806]
**Describe the bug**
commit1 and finalize will never sched when miner and worker restart.
When miner restart, fsm restart sector immediately, but worker not yet connected, 
StorageFindSector(in newExistingSelector)return empty because commit1 and finalize not allow fetch,
these tasks were added to the queue, and will never sched(task.sel.Ok in trySched will always return false).

**To Reproduce**
when worker doing Committing and FinalizeSector tasks, restart miner and worker.

**Version (run `lotus version`):**
 ntwk-calibration

**Additional context**
after add some sleep in here https://github.com/filecoin-project/storage-fsm/blob/next/sealing.go#L110   
the problem is gone

**Comment by yaohcn** [comment]
@magik6k

**Comment by ytQiao** [comment]
The same question @magik6k
