### ISSUE TITLE
Retrive always timeout but store is ok

### ISSUE THREAD

**Issue by mostcute** [filecoin-project/lotus#2809]
**Describe the bug**
![image](https://user-images.githubusercontent.com/23225426/89276984-d8341b80-d676-11ea-8a0c-66b1fbca349a.png)

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by rjan90** [comment]
I think this issue can be closed now, since this was related to the SpaceRace dashboard/retrievals? #rengjøring

**Comment by Reiers** [comment]
**Issue outdated.**

Closing ticket.
