### ISSUE TITLE
Prevent miner / worker to distribute cached layers over network

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#2818]
**Describe the bug**
I have 2 identical machines - 1 is running the daemon + miner, the other is just running a worker.

If the miner machine has done AP and PC1, I would prefer the miner to also do PC2 (because it can). Now the scheduler decided to move all the files over to the worker, so that it can do PC2 there.

Even if the miner was busy, I'd rather have it wait until some place is available, instead of moving the files over the network.

A simple toggle to disable the sharing of unsealed sector data (so the 600 GB layer files) would be of great value.

```
5: Proving        sSet: YES active: NO  tktH: 2939 seedH: 4529 deals: [0]
6: Proving        sSet: YES active: NO  tktH: 1059 seedH: 2841 deals: [0]
7: Proving        sSet: YES active: NO  tktH: 1225 seedH: 2897 deals: [2845 2876 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
8: Empty          sSet: NO  active: NO  tktH: 0    seedH: 0    deals: []
9: FinalizeFailed sSet: YES active: NO  tktH: 3905 seedH: 5506 deals: [0]
10: CommitFailed  sSet: YES active: YES tktH: 3926 seedH: 5496 deals: [0]
11: Proving       sSet: YES active: YES tktH: 6331 seedH: 7998 deals: [0]
12: Proving       sSet: YES active: YES tktH: 6331 seedH: 8085 deals: [0]
13: Proving       sSet: YES active: YES tktH: 7494 seedH: 9706 deals: [0]
14: Proving       sSet: YES active: YES tktH: 7057 seedH: 8624 deals: [0]
19: WaitDeals     sSet: NO  active: NO  tktH: 0    seedH: 0    deals: [4141]
20: PreCommit2    sSet: NO  active: NO  tktH: 8791 seedH: 0    deals: [5062 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
21: WaitDeals     sSet: NO  active: NO  tktH: 0    seedH: 0    deals: [5423]
Worker 0, host filecoin
        CPU:  [                                                                ] 0 core(s) in use
        RAM:  [|                                                               ] 2% 2.857 GiB/125.7 GiB
        VMEM: [                                                                ] 1% 2.857 GiB/189.7 GiB
        GPU: GeForce RTX 2070 SUPER, not used
Worker 1, host sealer
        CPU:  [                                                                ] 0 core(s) in use
        RAM:  [                                                                ] 1% 1.864 GiB/125.8 GiB
        VMEM: [                                                                ] 0% 1.864 GiB/189.8 GiB
        GPU: GeForce GTX 1080 Ti, not used
ID   Sector  Worker  Hostname  Task  Time
921  20      1       sealer    GET   1h0m45.1s
```

**Version:**
```
Daemon:  0.4.3+git.e833eb56+api0.8.1
Local: lotus version 0.4.3+git.e833eb56
```

**Additional context**
This might have already been fixed by @magik6k's recent work on the storage / scheduler, but I'm not sure. A simple boolean config (such as `disableLayerCacheTransfer = false`) would be very nice to have.

**Comment by RobQuistNL** [comment]
The latest `ntwk-calibration` still sometimes sends the generated layers over the network. I would really prefer the system not doing that. If it had waited a few more minutes both the PC1's could've been done on the miner and the worker could have been done with its PC2 already.
```
0: PreCommit1 sSet: NO  active: NO  tktH: 0    seedH: 0    deals: [2306 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1: WaitSeed   sSet: NO  active: NO  tktH: -538 seedH: 0    deals: [0]
2: Committing sSet: NO  active: NO  tktH: -538 seedH: 1606 deals: [0]
3: PreCommit2 sSet: NO  active: NO  tktH: -538 seedH: 0    deals: [0]
4: Proving    sSet: YES active: YES tktH: -517 seedH: 1180 deals: [0]
5: Committing sSet: NO  active: NO  tktH: -478 seedH: 1744 deals: [0]
6: PreCommit1 sSet: NO  active: NO  tktH: 0    seedH: 0    deals: [2334 2335 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
7: PreCommit1 sSet: NO  active: NO  tktH: 0    seedH: 0    deals: [2341 2342 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
8: WaitDeals  sSet: NO  active: NO  tktH: 0    seedH: 0    deals: [2366]
9: WaitDeals  sSet: NO  active: NO  tktH: 0    seedH: 0    deals: [2371]
Worker 0, host filecoin
        CPU:  [                                                                ] 0 core(s) in use
        RAM:  [|                                                               ] 1% 2.128 GiB/125.7 GiB
        VMEM: [                                                                ] 0% 2.128 GiB/221.7 GiB
        GPU: GeForce RTX 2070 SUPER, not used
Worker 2, host sealer
        CPU:  [||||||||||                                                      ] 2 core(s) in use
        RAM:  [||||||||||||||||||||||||||||||||||||||||||||||||||||||||        ] 90% 113.8 GiB/125.8 GiB
        VMEM: [|||||||||||||||||||||||||||||||||||||||||||                     ] 68% 129.8 GiB/189.8 GiB
        GPU: GeForce GTX 1080 Ti, not used
ID  Sector  Worker  Hostname  Task  Time
13  0       2       sealer    PC1   1h20m28.3s
16  6       2       sealer    PC1   1h19m28.8s
79  3       0       filecoin  GET   1h6m35.7s
```

**Comment by lzyling** [comment]
Is there any improvement in this problem?

**Comment by RobQuistNL** [comment]
I'm afraid not

**Comment by f8-ptrk** [comment]
this is still not resolved!

**Comment by potato1992** [comment]
I also need this.
It is so stupid to transfer such a large cache storage among workers. What makes it worse is that, the transfer speed of lotus implementation is awfully slow. (I am using 10G lan but only get about 1-2G speed with all NVME disk SSD).

**Comment by RobQuistNL** [comment]
@potato1992 thats probably the difference between your 10GBit LAN and 1 GigaByte of data. (factor 8)

However, using a Go webserver to send files over TCP HTTP/GET is ... not optimal. :+)

**Comment by potato1992** [comment]
> y

I know the difference, I mean, I can only get 1-2 Gbit speed with 10Gbit port.(I observe that it's not continuously sending the data, but work for some time, and sleep for longer time, it takes almost an hour to transfer the 500 GB data).

More to mention, the same speed appears even if such data transfer is among the two docker container on the same machine. (iperf3 shows 30GB speed, I have also check the iostat/htop, SSD/CPU usage is pretty low).

**Comment by RobQuistNL** [comment]
Mjeh, unfortunately there's a lot of layers that add CPU load and slow down the process :( I can imagine it will be even slower if you're running everything through docker..

**Comment by potato1992** [comment]
> Mjeh, unfortunately there's a lot of layers that add CPU load and slow down the process :( I can imagine it will be even slower if you're running everything through docker..

Docker is a must in my situation as I have two GPUs.

I think the major reason is the poor efficient code, the official developers just do not how to write code without the go language (the http based transfer makes it even worse). I changed the code to utilize mounted samba folders to do the transfer instead. Everything works pretty, the data transfer thread only takes 30% of one core CPU in stable 10G full speed.

**Comment by f8-ptrk** [comment]
> Docker is a must in my situation as I have two GPUs.

why is docker a must? we run everything from 1-8 GPUs without docker without any problems.

**Comment by potato1992** [comment]
> > Docker is a must in my situation as I have two GPUs.
> 
> why is docker a must? we run everything from 1-8 GPUs without docker without any problems.

Are you sure the 8 GPUs are fully utilized? In my test, I found very frequently, two PC2 tasks are just racing to use the first GPU only. This sometimes get my PC2/C2 more than 40 minutes to complete with RTX3080. However, when I use docker to separate GPU resources apart, PC2/C2 of each worker all drop within 30 min.

**Comment by f8-ptrk** [comment]
yes i am sure. 

just use `CUDA_VISIBLE_DEVICES=0/1/2/3/4/5/6/7` and multiple workers and it works fine

**Comment by potato1992** [comment]
> yes i am sure.
> 
> just use `CUDA_VISIBLE_DEVICES=0/1/2/3/4/5/6/7` and multiple workers and it works fine

Thank you for your information. But docker still makes some sense in my case. 
* 1. I have a PC with 2CPU+2GPU+2T memory. With docker technique, I can assign CPU/GPU memory that attached to the same numa node, thus avoiding performance degrading in some cases resources are called across numa node.
* 2. PC1 phase are using fixed CPU core. Running multiple workers with PC1, they will race to use those cores, rather than use free cores, but with docker, I can assign PC1 worker 1 with CPU 0-31,64-95, PC1 worker 2 with CPU 32-63,96-127. 
* 3. Similar as 2, as PC1 phase uses fixed cores. When running PC2 on the same worker, PC2 will just race to use those fixed cores occupied by PC1, which will slow both PC2 and PC1. I have already tested and can confirm that both PC1 and PC2 will be significantly faster running in docker with separate CPU and GPU resources.

**Comment by f8-ptrk** [comment]
no need for docker to do any of this ;)

**Comment by potato1992** [comment]
> no need for docker to do any of this ;)

Do you know how to change the PC1 CPU core binding? It always uses the fixed cores. (it always, start from 0,1,2.....)
For example, if you are running one one PC1 worker, it takes about 3-4 hour to complete PC1, but if I runs 2 PC worker, it takes about 7 hours for them to complete PC1. They two just use the same core, rather than seeking other free cores.

**Comment by f8-ptrk** [comment]
you do not run more than 1 PC1 worker on a single box without modified code

**Comment by rjan90** [comment]
Hey! Thanks for this issue.

I´m closing this issue now since the original issue - avoiding unnecessarily moving data between multi-purpose workers has been fixed with [sector storage groups](https://lotus.filecoin.io/storage-providers/seal-workers/seal-workers/#sector-storage-groups).

Thanks again.
