### ISSUE TITLE
Expand tests around message selection into blocks

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#2828]
We should add tests around how messages are packed in blocks (see miner/miner_test.go). `TestMessageFiltering` and `TestMessageFilteringSenderHopping` are good starting points to build on./

**Comment by Reiers** [comment]
**Hi @arajasek** 

Looks like a dev reminder - and the issue is a bit outdated.
Do you want keep it open and we will triage it, or should we close this one?

Thank you !
