### ISSUE TITLE
Cocurrent generating windowPoSt happen within the same deadline

### ISSUE THREAD

**Issue by kikakkz** [filecoin-project/lotus#2837]
**Describe the bug**
3 window PoSt are started with interval about 15 seconds within the same deadline. Finally, two of them will be finished after 30 minutes, then fail to submit due to mismtched deadline. 

**To Reproduce**
1. Normally mining setup
2. Mining for a day
3. Check the log with key word "submitPost"

**Expected behavior**
Should only one windowPost is running within one deadline.

**Screenshots**
![image](https://user-images.githubusercontent.com/13128505/89371424-ea18cb80-d715-11ea-8a7a-88dd3c051345.png)
![image](https://user-images.githubusercontent.com/13128505/89371435-f00eac80-d715-11ea-9b36-e945c7f24b40.png)

**Version (run `lotus version`):**
Daemon: 0.4.3+git.460723d2.dirty+api0.8.1
Local: lotus version 0.4.3+git.460723d2.dirty

**Additional context**
N/A.

**Comment by kikakkz** [comment]
Check lotus log, for each window PoSt generating, tipset change happen at the same time.

**Comment by jennijuju** [comment]
Please open a new ticket if you are running into this issue on the latest version of lotus!
