### ISSUE TITLE
m.sealer.SealCommit1 never return or error for one sector

### ISSUE THREAD

**Issue by kikakkz** [filecoin-project/lotus#2842]
**Describe the bug**
A series sectors were sealed, one sector if stucked at Committing, check the log, m.sealer.SealCommit1 never return.

**To Reproduce**
1. Normal setup mining
2. Mining for a day
3. One sector is stucked at Committing for more than 24 hours

**Expected behavior**
The sector should goto next state.

**Screenshots**
To analyze the issue, I add some log to storage-fsm, for the error sector, m.sealer.SealCommit1 never returned.
![image](https://user-images.githubusercontent.com/13128505/89411359-dd1ccc00-d757-11ea-9a56-da3235b8f37d.png)
![image](https://user-images.githubusercontent.com/13128505/89411404-edcd4200-d757-11ea-8789-0472f08b3140.png)
After handle committing p ~, we should have handle committing ppppppppp ~, but it's not appear for a long while, and no error found.

**Version (run `lotus version`):**
Daemon:  0.4.3+git.460723d2.dirty+api0.8.1
Local: lotus version 0.4.3+git.460723d2.dirty

**Additional context**
N/A.

**Comment by rjan90** [comment]
I think this issue can be closed now, as this has not happened on newer versions of Lotus? #rengjøring

**Comment by kikakkz** [comment]
> I think this issue can be closed now, as this has not happened on newer versions of Lotus? #rengjøring

Seems everything is perfect now~

**Comment by Reiers** [comment]
**Issue solved in newer version of Lotus.** 

Closing ticket.
