### ISSUE TITLE
Cache drand entry validation

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#2845]
We currently verify the same drand entry multiple times (if it occurs in multiple blocks in a tipset, for example). We should cache validated entries and only run (expensive) bls signature verification for entries we havent seen yet

**Comment by Reiers** [comment]
Hello again @whyrusleeping 

The conversation stopped here, is this something you guys are still look into, if so I will triage it - if not we can close it.

Thanks again !
