### ISSUE TITLE
client query-ask doesn't use MinerInfo multiaddrs

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#2846]
As far as I can tell the `lotus client query-ask` does not use the MinerInfo multi-addrs that miners set, and only uses the dht.

This seams like something that should happen here: 

https://github.com/filecoin-project/lotus/blob/8458f04a6b73d06560b0a6fbe86a0f6f5fa67d61/node/impl/client/client.go#L519-L526

If no addresses are passed, then the storage market just tries to open a stream with it's libp2p host

https://github.com/filecoin-project/go-fil-markets/blob/cfbd86b77e8a8353d3ffb0781fbd6465e4bb9555/storagemarket/impl/client.go#L202-L209

The libp2p host doesn't seem to be anything special which should be able to figure this out on its own

https://github.com/filecoin-project/lotus/blob/8458f04a6b73d06560b0a6fbe86a0f6f5fa67d61/node/modules/client.go#L124-L141

**Comment by arajasek** [comment]
Fixed in #2849
