### ISSUE TITLE
initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p"

### ISSUE THREAD

**Issue by modytor** [filecoin-project/lotus#2854]
**Describe the bug**

**Can not start lotus.**

2020-08-06T09:39:30.617+0800    INFO    build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /root/filecoin-ee-poseidon_hasher-8-8-2-2627e4006b67f99cef990c0a47d5426cb7ab0a0ad58fc1061547bf2d28b09def.vk is ok
2020-08-06T09:39:30.617+0800    INFO    build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /root/filecoin-ee-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.vk is ok
2020-08-06T09:39:30.617+0800    INFO    build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:162    parameter and key-fetching com
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.fled to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): could not build value group []config.Option[group="libp2p"]: function "github.com/filecoin-(/data/sdd/lotus/node/modules/lp2p/libp2p.go:71) returned a non-nil error: failed to get bootstrap peers: failed to parse multiaddr "/dns4/bootstrap-1BDwyaruE1bfFsuekttD974arrkB4G4ZKWk6r\r": invalid value "12D3KooWQAKmfoAQBDwyaruE1bfFsuekttD974arrkB4G4ZKWk6r\r" for protocol p2p: failed to parse p2p  input isn't valid multihash

**To Reproduce**

root@ipfs_server:/data/sdd/lotus# git show
commit 460723d2e1348e6c98c603faa86432e626708663 (HEAD -> ntwk-calibration, origin/ntwk-calibration)
Merge: 5212db89 43491cb7
Author: Łukasz Magiera <magik6k@users.noreply.github.com>
Date:   Sun Aug 2 02:00:59 2020 +0200

    Merge pull request #2767 from filecoin-project/next

    Update calibration branch with some Gas improvements

root@ipfs_server:/data/sdd/lotus#
root@ipfs_server:/data/sdd/lotus#
root@ipfs_server:/data/sdd/lotus# git branch
  master
* ntwk-calibration

1. Run 'lotus daemon'
2. See error

**Expected behavior**
Success start.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/9621983/89495133-30d7f580-d7ea-11ea-937d-072df2078cdb.PNG)

**Version (run `lotus version`):**
root@ipfs_server:~# lotus -v
lotus version 0.4.3+git.460723d2.dirty

**Additional context**

**Comment by sbwtw** [comment]
same error with latest ntwk-calibration commit

**Comment by rjan90** [comment]
I think this issue can be closed, as this issue has not been seen on newer versions of Lotus? #rengjøring

**Comment by Reiers** [comment]
**@rjan90 Correct. Closing ticket.**

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
