### ISSUE TITLE
lotus cli read actor state

### ISSUE THREAD

**Issue by qiwu7** [filecoin-project/lotus#2855]
**Describe the bug**
lotus cli command `lotus state read-state` not showing locked vs. unlocked balance

**To Reproduce**
1. Run the following to create a msig actor with duration specified 
```
> lotus msig create --required 1 --value 10 --from t1in4ydzyyc6irm5srcgb52haksknbbqcm3otjfwq --duration 3732480 t1zdqprv6ryul3md3xiqpsczpui7xmqwjztvhirsy
= Created new multisig:  t0128015 t2kquzccrfy7kjyjhjz2cq26mexotoi5hoij4665q
```
2. Run `lotus state read-state t0128015` to read state of the actor
```
lotus state  read-state t0128015
{
  "InitialBalance": "10000000000000000000",
  "NextTxnID": 0,
  "NumApprovalsThreshold": 1,
  "PendingTxns": {
    "/": "bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay"
  },
  "Signers": [
    "t1zdqprv6ryul3md3xiqpsczpui7xmqwjztvhirsy"
  ],
  "StartEpoch": 139337,
  "UnlockDuration": 3732480
}
```

**Expected behavior**
I expect to see both locked and unlocked balance at the current epoch, which is not available. So I don't know if I have successfully specify the unlocking period (duration) or not.

**Screenshots**

**Version (run `lotus version`):**
lotus version
Daemon:  0.4.1+git.7d7496e1+api0.6.0
Local: lotus version 0.4.1+git.7d7496e1

**Additional context**

**Comment by arajasek** [comment]
The `UnlockDuration` being set to `3732480` confirms that you have successfully set the unlocking period. The locked/unlocked balance itself doesn't live in the state object, it's calculated on the fly as needed (if not, it would need a state update every epoch).

**Comment by qiwu7** [comment]
@arajasek Can you expose a cli method to check unlocked vs. locked balance for a multisig actor if this is not the correct method to use?
