### ISSUE TITLE
lotus-storage-miner run get nothing and saw error "not scheduling on worker 0; not enough physical memory" in log file

### ISSUE THREAD

**Issue by littlekai999** [filecoin-project/lotus#2860]
after I run command "lotus-storage-miner run", I saw the below error message in log file, any one can help me? Thanks

not scheduling on worker 0; not enough physical memory - need: 251138M, have 241809M

**Comment by rjan90** [comment]
I think this issue has been fixed on newer versions of Lotus, and can probably be closed now? #rengjøring

**Comment by Reiers** [comment]
**Issue has been solved in newer versions of Lotus.** 
Closing this ticket. 

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
