### ISSUE TITLE
How the start-epoch is set by bot in the testing? 

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#2862]
In the current calibration network, the bot is issuing some deal proposals to different providers. We found that the start epoch setting in deal proposal is kind of short, some of them are only 12 hours away from the proposing time, which is too short for some miners to complete all the steps, especially for some small miners whose machine is not powerful, and it does not allow any mistakes in the whole process. 

Anyone can clarify how the start-epoch is set, is it negotiable between the provider and the bot, or it is just fixed by the bot to 12 hours or 24hours away? Thanks. 

Talked with @daviddias , we think better to have an issue to track this and get clarification for all participants.

**Comment by mishmosh** [comment]
`StartEpoch` is part of the `DealProposal` (https://beta.spec.filecoin.io/systems/filecoin_markets/storage_market/storage_deal/). It is sent by the client (in this case, the bot) and according to the protocol is not negotiable between miner and client. 

The proposed switch to a later start epoch is a network performance question.

cc @momack2.

**Comment by steven004** [comment]
>  It is sent by the client (in this case, the bot) and according to the protocol is not negotiable between miner/provider and client.
A simple question is: in the test, how far the bot will set the start-epoch? the epoch at 12hours later from the proposing time, or 48hours? or any other number. The miners need to know the designed case.

**Comment by deltazxm** [comment]
12 hours is too short for seal.Should be set as long as the sector seal timeout.10000 epoch

**Comment by arajasek** [comment]
I believe it uses the Lotus default of 24 hours: https://github.com/filecoin-project/lotus/blob/a89c290f626885ade79ed33f104493356e72a87e/node/impl/client/client.go#L56
