### ISSUE TITLE
Bot deal test  - ClientQueryAsk failed : failed to open stream to miner: routing: not found 

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#2863]
**Describe the bug**
The deal success ratio is too low in calibration network deal test, there are too many `routing: not found` errors happened. This kind of error is not expected since you can also see lots of success deals, which means all configuration works. and it is an intermittent issue. 

check out this page: https://calibration.spacerace.filecoin.io/deals/t01119

**Expected behavior**
No `routing: not found` error when the provider is dial-able. 

**Workaround**
It is suggested to run `net connect provider-multi-address` before propose a deal, to make sure the connection is set first.

**Comment by arajasek** [comment]
We've confirmed that miners who [set their addresses on chain](https://docs.filecoin.io/mine/connectivity/#setting-multiaddresses) and have healthy networks can be dialled by the bot. The deal success ratio is low right now, we're [reaching out](https://filecoinproject.slack.com/archives/C017CCH1MHB/p1597115144044900) to miners to help debug connectivity issues.
