### ISSUE TITLE
next: miner crash when retrieving file

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#2872]
**Describe the bug**

While testing retrieval in my testground setup (using a very recent commit on `next`), one of the miners crashed. Here is the last output from the log file:

```
2020-08-06T18:19:20.953Z        INFO    markets loggers/loggers.go:28   retrieval event {"name": "ProviderEventDealAccepted", "deal ID": "3", "receiver": "12D3KooWCSjNzyktS6YJ4k7dhEbUGQyo9n6tzhyqGQPN46ysWmw1", "state": "DealStatusUnsealing", "message": ""}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1297ffb]

goroutine 58907 [running]:
github.com/filecoin-project/lotus/markets/retrievaladapter.(*retrievalProviderNode).UnsealSector.func1(0xc000617c50, 0x2d49980, 0xc0000c8038, 0xc00070f418, 0x3f0, 0x1, 0x7f0, 0x7f0, 0xc005d6de00)
        /lotus/markets/retrievaladapter/provider.go:60 +0x5b
created by github.com/filecoin-project/lotus/markets/retrievaladapter.(*retrievalProviderNode).UnsealSector
        /lotus/markets/retrievaladapter/provider.go:59 +0x315
```

I made similar requests against the other 5 miners in the testground setup for the same data, and they didn't crash.

**Version (run `lotus version`):**

```
# lotus version
Daemon:  0.4.3+debug+git.d2fc7c86.dirty+api0.8.1
Local: lotus version 0.4.3+debug+git.d2fc7c86.dirty
```

**Additional context**

**Comment by jimpick** [comment]
@hannahhoward This might be of interest...

**Comment by jimpick** [comment]
I can get more logs from the testground s3 bucket - run id `fdf755219198`

**Comment by jimpick** [comment]
I'm reseting the localnet and I'm doing more testing. I'll report back if it happens again.

**Comment by jimpick** [comment]
I started sealing some data on all 6 nodes without fast retrieval, and tried retrieving before they were finished sealing all 6 miners died ... so it appears to be reproducible.

**Comment by rjan90** [comment]
Hey! Are you still seeing this issue, or has it been fixed so this issue can be closed? #rengjøring

**Comment by jimpick** [comment]
I'll close this. It's over a year old! It looks like there was a fix.
