### ISSUE TITLE
Bizarre Storage deal error

### ISSUE THREAD

**Issue by ribasushi** [filecoin-project/lotus#2876]
**Describe the bug**
The deal-bot and one of my slow miners encountered a weird error I have not seen before:
```
StorageDealError ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreiemznvpitpwq3n3xdpcfton56vsgbui22zecyvwwzivy6hfybaeky"},"State":26,"Message":"error in deal activation: handling applied event: deal wasn't active: deal=9989, parentState=bafy2bzaceckjobixswmhm5lrkrkfv7f5vuwhkz2ggomduyn6t5cy7lrhdbyhc, h=16325","Provider":"t040955","DataRef":null,"PieceCID":{"/":"baga6ea4seaqpjv7ycj75jdphu56qxllcdx43acbm2fzdh2f4hagrvxrrq5myioq"},"Size":130048,"PricePerEpoch":"500000000","D...
```

Not sure if significant, but filing an issue before the reset wipes all evidence at https://calibration.spacerace.filecoin.io/deals/t040955

**Version (run `lotus version`):**
[593a7b62 (origin/next)](https://github.com/filecoin-project/lotus/tree/593a7b62) with the genesis rebased on top

**Additional context**

This is the same overloaded miner from https://github.com/filecoin-project/lotus/issues/2867

**Comment by ribasushi** [comment]
Ok got a similar one from a *non*-overloaded miner https://calibration.spacerace.filecoin.io/deals/t040978

The only thing in common is that they had upgraded sectors ( these were all part of the testing of https://github.com/filecoin-project/lotus/issues/2744 )

I will re-try / reevaluate the exact same steps after reset tomorrow

**Comment by hannahhoward** [comment]
so, I am not 100% sure this counts as a bug. This means, concretely, the client timed out watching the chain for the deal to seal. I'm not sure what our timeout value is. I think it should probably be the StartEpoch in the deal -- if the miner fails to seal in that time, then in-fact, they have failed the deal and the money will be returned by the storage market actor I believe.

**Comment by ribasushi** [comment]
@hannahhoward if that were the case: the miner should stop attempting to seal the sector no? It kept retrying and keeps failing...
I will have another test with these parameters after reset.

**Comment by ribasushi** [comment]
@hannahhoward also - all of this happened in way less than 24h ( more like 8), which is below [how the deals are made by default](https://github.com/filecoin-project/lotus/blob/ntwk-calibration/node/impl/client/client.go#L56)

**Comment by ribasushi** [comment]
Closing as the network was reset, will resurrect when I encounter this again.
