### ISSUE TITLE
About optimal BlockMessageLimit and BlockGasLimit parameters

### ISSUE THREAD

**Issue by KevinXiong2018** [filecoin-project/lotus#2886]
Currently our SelectMessages, it is mainly limited by the parameters BlockMessageLimit and BlockGasLimit. The following is the miner-select-msgs output information under the current default parameters:
./lotus-shed mpool miner-select-msgs
mempool input messages:  9207
filtered messages:  34
total gas limit of selected messages: 4331511475 / 7500000000 (57.75%)

https://github.com/filecoin-project/lotus/blob/ntwk-calibration/build/params_shared_vals.go#L91
// TODO: If this is gonna stay, it should move to specs-actors
const BlockMessageLimit = 512
const BlockGasLimit = 7_500_000_000
------------------------------------------------------
When we adjust the parameters BlockMessageLimit and BlockGasLimit appropriately, the following is the new miner-select-msgs output information ：
const BlockMessageLimit = 2560  //5 times higher
const BlockGasLimit = 3750_000_000_000  //500 times higher

./lotus-shed mpool miner-select-msgs
mempool input messages:  9028
filtered messages:  1988
total gas limit of selected messages: 197974719657 / 3750000000000 (5.28%)

So can we properly adjust the optimal BlockMessageLimit and BlockGasLimit parameters to clear congested messages?

**Comment by Kubuxu** [comment]
We cannot increase `BlockGasLimit` that high as the gas is based on the execution time of messages.
Too many messages in a block and block will be too slow to verify.

Although we increased `BlockGasLimit` and decreased gas used by many messages.

**Comment by arajasek** [comment]
More work coming on this (see https://github.com/filecoin-project/lotus/issues/2969#issuecomment-671714476)
