### ISSUE TITLE
deal rejected

### ISSUE THREAD

**Issue by Leozhang404** [filecoin-project/lotus#2887]
**Describe the bug**
My miner keeps the default setting, improving the connect using official  [report](https://docs.filecoin.io/mine/connectivity/#setting-multiaddresses), some deal will success, but some deals will be rejected.

reject reasons include:
1. `deal rejected: storage price per epoch less than asking price: 5000 < 7629"`
2. `deal rejected: cannot seal a sector before 17463"`

**To Reproduce**
1. open address to accept the deals without any private setting
2. See error:
![image](https://user-images.githubusercontent.com/38653654/89617075-20904b00-d8bc-11ea-9583-0917cefc8ae1.png)
![image](https://user-images.githubusercontent.com/38653654/89617219-66e5aa00-d8bc-11ea-8c8a-51b6fa5fff55.png)

**Version (run `lotus version`):**
ntwk-calibration+git460723d2

**Additional context**
in the space race, what should I do to guarantee  the deal success rate? such as **asking price** and **startEpoch**
@daviddias @whyrusleeping @magik6k

**Comment by whyrusleeping** [comment]
we need much better error messages here, but i think that

> deal rejected: cannot seal a sector before 17463"

means your start epoch is too early, and 

> deal rejected: storage price per epoch less than asking price: 5000 < 7629"

means your offer price is too low
