### ISSUE TITLE
FIL values should be pretty printed

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#289]
I suggest the following:
  - `X attoFIL` if `val < 0.01μFIL`
  - `X μFIL` if `val < 0.1mFIL`
  - `X mFIL` if `val < 0.1 FIL`
  - otherwise `X FIL`

All prints should use thousands separator `,`, and be printed with at least 6 fractional digits.
It should be done on CLI side, with a possible override to always use `attFIL`.

**Comment by whyrusleeping** [comment]
#420 pushes this in the right direction. Always more to be done though
