### ISSUE TITLE
[Bug] doesn't work wallet import 

### ISSUE THREAD

**Issue by qkrwnsgh1288** [filecoin-project/lotus#2893]
**Describe the bug**
encoding/decoding bug

**To Reproduce**
1. Run `lotus wallet import {fileName}`
2. See error
`WARN    main    lotus/main.go:81        encoding/hex: invalid byte: U+007B '{'`

**Version (run `lotus version`):**
lotus version 0.4.1+git.c459a13

**Comment by whyrusleeping** [comment]
where did you get the file in question from?

**Comment by qkrwnsgh1288** [comment]
I got the file by `lotus wallet new` command.
