### ISSUE TITLE
Executing event planner failed: running planner for state Packing failed

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#2914]
Please provide all the information requested here to help us troubleshoot "commit failed" issues.
If the information requested is missing, we will probably have to just ask you to provide it anyway,
before we can help debug.

**Describe the problem**

Unable to process past Packing phase.
All of these jobs but system idling:

` $ lotus-miner sealing jobs`

> ID  Sector  Worker  Hostname  Task  Time
> $

`lotus-miner sealing sched-diag`

> {
>   "OpenWindows": [
>     0,
>     0
>   ],
>   "Requests": null
> }
> 

**Sectors list**

`lotus-miner sectors list`

> 0: Proving    sSet: YES active: YES tktH: 12896 seedH: 14541 deals: [0]
> 1: Proving    sSet: YES active: YES tktH: 14922 seedH: 17643 deals: [0]
> 2: Proving    sSet: YES active: YES tktH: 15003 seedH: 17756 deals: [9661 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
> 3: Proving    sSet: YES active: YES tktH: 15056 seedH: 17867 deals: [9755 9754 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
> 4: WaitDeals  sSet: NO  active: NO  tktH: 0     seedH: 0     deals: [9967]
> 5: WaitDeals  sSet: NO  active: NO  tktH: 0     seedH: 0     deals: [10078 10264 10454]
> 6: Committing sSet: NO  active: NO  tktH: 17487 seedH: 19174 deals: [10593 10737 10866 11023 11177 11332 11493 11606 11756 11922 12201 12364 12485 12648 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
> 7: WaitSeed   sSet: NO  active: NO  tktH: 18135 seedH: 0     deals: [12813 13003 13163 13324 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
> 8: Packing    sSet: NO  active: NO  tktH: 0     seedH: 0     deals: [13469 13645 13790]
> 9: WaitDeals  sSet: NO  active: NO  tktH: 0     seedH: 0     deals: [14317 14457 14602]
> 

**Sectors status**

`lotus-miner sectors status --log 8`

> SectorID:	8
> Status:		Packing
> CIDcommD:	<nil>
> CIDcommR:	<nil>
> Ticket:		
> TicketH:	0
> Seed:		
> SeedH:		0
> Proof:		
> Deals:		[13469 13645 13790]
> Retries:	0
> --------
> Event Log:
> 0.	2020-08-07 16:51:31 +0000 UTC:	[event;sealing.SectorStart]	{"User":{"ID":8,"SectorType":3}}
> 1.	2020-08-07 17:23:38 +0000 UTC:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":131072,"PieceCID":{"/":"baga6ea4seaqehgbj4y74utormgtcr7ze62ii63ceh5yyasknpvaj26w5pxxrcny"}},"DealInfo":{"DealID":13469,"DealSchedule":{"StartEpoch":21828,"EndEpoch":725362},"KeepUnsealed":false}}}}
> 2.	2020-08-07 17:43:30 +0000 UTC:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":131072,"PieceCID":{"/":"baga6ea4seaqczmhfyf27ua6fnj7irlqbufzs2yvr6tuf4a2s7c4oijhwyv7ucmy"}},"DealInfo":{"DealID":13645,"DealSchedule":{"StartEpoch":21933,"EndEpoch":725362},"KeepUnsealed":false}}}}
> 3.	2020-08-07 18:42:00 +0000 UTC:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":131072,"PieceCID":{"/":"baga6ea4seaqfivvr7zsexbiky6cxp6w7s5tptjaaseywytusnijf67swgchdkdq"}},"DealInfo":{"DealID":13790,"DealSchedule":{"StartEpoch":22047,"EndEpoch":725362},"KeepUnsealed":false}}}}
> 4.	2020-08-07 20:51:31 +0000 UTC:	[event;sealing.SectorStartPacking]	{"User":{}}
> 
> 

**Lotus storage miner logs**

> 2020-08-08T00:35:06.240 INFO filcrypto::proofs::api > generate_data_commitment: start
> 2020-08-08T00:35:06.243 INFO filecoin_proofs::api::seal > compute_comm_d:start
> 2020-08-08T00:35:06.243 INFO filecoin_proofs::pieces > verifying 4096 pieces
> 2020-08-08T00:35:06.243 INFO filecoin_proofs::api::seal > compute_comm_d:finish
> 2020-08-08T00:35:06.243 INFO filcrypto::proofs::api > generate_data_commitment: finish
> 2020-08-08T00:35:06.244Z	ERROR	evtsm	go-statemachine@v0.0.0-20200730031800-c3336614d2a7/machine.go:83	Executing event planner failed: running planner for state Packing failed:
>     github.com/filecoin-project/storage-fsm.(*Sealing).plan
>         /home/stuart/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200730122205-d423ae90d8d4/fsm.go:161
>   - planner for state Packing only has a plan for a single event only, got [{User:{NewPiece:{Piece:{Size:131072 PieceCID:baga6ea4seaqazhuv4d7c6jgk3wygo4aouzc3ky33kl26se7teuugyvxoixd2yeq} DealInfo:0xc000627000}}} {User:{NewPiece:{Piece:{Size:131072 PieceCID:baga6ea4seaqlg6f4ziyh5fk7hmdioos74jddnzo7id5tyejhp4asuj5wifp26ga} DealInfo:0xc013a0e1a0}}} {User:{NewPiece:{Piece:{Size:131072 PieceCID:baga6ea4seaqhuordxch3xbwnvuilm72arejzt4bhjfwl4v6ynfkjgfu2v3floci} DealInfo:0xc0005e6a20}}} {User:{FillerPieces:[{Size:131072 PieceCID:baga6ea4seaqi5hreap5iqthwen7wbxzf7a7oidokt3mht23pmnjncuee6wwq2py} {Size:524288 PieceCID:baga6ea4seaqhaixwb57pnlp2c4ixuutbtyym5kbmnadvvxy4mz3yn3cqn3xs2gi} {Size:1048576 PieceCID:baga6ea4seaqntgehxfzvoouw4ejzgzcsg3axwh2moa2noi6hvgpxbg5u3jqrmky} {Size:2097152 PieceCID:baga6ea4seaqnbnjq3oylj4s4luxsukg752aiwu2bfibjghyyysm7lisubbvrgjq} {Size:4194304 PieceCID:baga6ea4seaqijqccdoqgqwqbx54vui2eazh6ijf5kku5eq3xwokp6tclivuoqei} {Size:8388608 PieceCID:baga6ea4seaqgl4u6lwmnerwdrm4iz7ag3mpwwaqtapc2fciabpooqmvjypweeha} {Size:16777216 PieceCID:baga6ea4seaqkejdvbaufquewln7dgszre6ymaqvr2bdnyvcaee3we7gypgoocoq} {Size:33554432 PieceCID:baga6ea4seaqnv7nlnwutmrctyjwtg4tlt7x6gq56r6awjhwabgvnh6x7kbqxkca} {Size:67108864 PieceCID:baga6ea4seaqnsqov4dldcsuzlqz77pkpxzurddlt2ts72lgtd4hxzbxl3ukoobq} {Size:134217728 PieceCID:baga6ea4seaqfctcdlq6qju2juu3f7pkz77drgyurcf4fteobupctv4rapf2buly} {Size:268435456 PieceCID:baga6ea4seaqk2bufhfu5g7ju74eobh2wsmfevum2rhppmdf75z7b2m4byhtryny} {Size:536870912 PieceCID:baga6ea4seaqdsvqopmj2soyhujb72jza76t4wpq5fzifvm3ctz47iyytkewnubq} {Size:1073741824 PieceCID:baga6ea4seaqmzq6acl23axubdiv37xipnaz3qqtvwr57ekoaauviescphqnfwpi} {Size:2147483648 PieceCID:baga6ea4seaqh34u3nf3tdgpi6k2aw54rtucikcpo25uofrzjpmprinydj7b4mla} {Size:4294967296 PieceCID:baga6ea4seaqgntqfunthkuwpixacxtcoqojjdg66vq254l7vmjyyjdu7pntvcby} {Size:8589934592 PieceCID:baga6ea4seaqnqyicdbbfvnpjlmokmi45fgroiigxa2uw6nz6f6ojveoxlhizwai} {Size:17179869184 PieceCID:baga6ea4seaqg2nsld34emra2ljfgrbrdcswmbjdpaftrpzjuipudt3w7qpbikpa}]}}]:
>     github.com/filecoin-project/storage-fsm.planOne.func1
>         /home/stuart/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200730122205-d423ae90d8d4/fsm.go:348

**Version**
`lotus version`

> Daemon: 0.4.3+git.460723d2+api0.8.1
> Local: lotus version 0.4.3+git.460723d2

**Comment by RobQuistNL** [comment]
(Possibly) related issues:
https://github.com/filecoin-project/lotus/issues/2867
https://github.com/filecoin-project/lotus/issues/2842
https://github.com/filecoin-project/lotus/issues/2800
https://github.com/filecoin-project/lotus/issues/2758
https://github.com/filecoin-project/lotus/issues/2742
https://github.com/filecoin-project/lotus/issues/2393

**Comment by stuberman** [comment]
Have not seen this issue in a long time
