### ISSUE TITLE
Calibration: clientMarketBalance.Available too small

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#2916]
**Describe the bug**

On tonight's calibration net reset, I made two deals, but most subsequent deals are failing with:

```
$ lotus client list-deals -v | grep 7pm
bafyreiewxvvupgsvm6a2o6u455vzbbztanbi7gldqggwhdao6yblltx7pm  0     t01183  StorageDealError    N  N  baga6ea4seaqckozxggn2yb6oc4gztpouaqwxryp4tvjkxajstmsfy7m7inrkopy  63.5 KiB  0.00000116278 FIL   581390  unexpected deal status while waiting for data request: 11 (StorageDealFailing). Provider message: deal rejected: clientMarketBalance.Available too small
```

Here's a screenshot from my client showing the same info:

<img width="690" alt="Screen Shot 2020-08-07 at 9 13 40 PM" src="https://user-images.githubusercontent.com/20886/89702215-9fed4100-d8f3-11ea-9f9c-b0f13e59dc77.png">

**Version (run `lotus version`):**

```
$ lotus version
Daemon:  0.4.3+git.2340742e.dirty+api0.9.0
Local: lotus version 0.4.3+git.2340742e.dirty
```

**Comment by jimpick** [comment]
I just kicked off 10 deals and 3/7 failed with this. It seems like it might be possible to retry to get the deals to go through.

**Comment by sansi2020** [comment]
If the customer fails to pay the market  in method EnsureClientFunds , then waiting for the payment message-cid to appear on the chain should not pass in method WaitForFunding

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏

**Comment by karlcecilio** [comment]
您好，您发的信件我已收到，感谢您的来信，我会尽快回复！ Best Regards!
