### ISSUE TITLE
calibration: retrieval errors with "merkledag: not found" if still sealing

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#2926]
**Describe the bug**

Retrievals will return an error "merkledag: not found" if the deal is still sealing.

Here's a screenshot from my retrieval client. One retrieval succeeded because the deal was in the active state. All the other deals were still sealing.

![calibration localhost_9021_retrieve](https://user-images.githubusercontent.com/20886/89717214-095b6700-d969-11ea-8591-a7eb6eb8a0ee.png)

Slack: https://filecoinproject.slack.com/archives/G0177CETSP9/p1596869220172100

**Version (run `lotus version`):**

```
$ lotus version
Daemon:  0.4.3+git.2340742e.dirty+api0.9.0
Local: lotus version 0.4.3+git.2340742e.dirty
```

**Comment by TippyFlitsUK** [comment]
Hi @jimpick 

This looks like a reminder. Should we close it or keep it open?
