### ISSUE TITLE
ERROR: dial tcp 127.0.0.1:2345: connect: connection refused

### ISSUE THREAD

**Issue by chenpi-cn** [filecoin-project/lotus#2927]
root@ran:/home/zs# lotus-miner info
ERROR: dial tcp 127.0.0.1:2345: connect: connection refused

**Comment by masumasu01** [comment]
same question .what reason
root@ran:/home/zs# lotus-miner info
ERROR: dial tcp 127.0.0.1:2345: connect: connection refused

**Comment by JONGTAEKPARK** [comment]
sudo ufw allow 1347/tcp
sudo ufw allow 2345/tcp
sudo ufw allow 1234/tcp

https://medium.com/@nad128668/comprehensive-guide-to-install-filecoin-mining-rig-8c95cb9613dc
