### ISSUE TITLE
Too much FIL burnt 

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#2931]
**Describe the bug**
More than **2.3 million FIL** is burnt while the epoch height is just *4242*, which means only one and half day past after the calibration net reset. 

It's insanely huge number, while the total block reward just comes up to about `136K FIL`. 

And if you check the faucet, it has unbelievable number of transactions to send money to miners. More than **40K** transactions to send millions of FIL when there are only a little more than *1K* accounts, in which less than **200 miners** in the network. 

What's behind all of these? 

**Expected behavior**
One time of faucet transaction to miner can support 3000 sectors sealing? Really!

**Version (run `lotus version`):**
```
$ lotus version
Daemon:  0.4.3+git.2340742e+api0.9.0
Local: lotus version 0.4.3+git.2340742e
```

**Comment by whyrusleeping** [comment]
Working as intended. A few things contributing to this:
- Money is free right now
- People are running 512MiB sectors, requiring 64x more messages on chain for the same power
- We don’t have user configurable ‘maximum limits per message’ that would prevent the escalating price competition

3000 sectors is 96TiB, if you seal 96TiB so quickly, i’d hope that you can start earning some block reward and deal rewards to post up for posting more sectors.

**Comment by steven004** [comment]
I guess you are confident for the IncentiNet on which only 32G and 64G sector-size is allowed, 
Or, you want to have a try before the IncentiNet by disabling 512M sector-size in the current calibration network, so that it can be ensured? 

Btw, in the current network, the top-power miner to maintain its power climing, there is over 1.7k transaction from the faucet to it's worker. You may want to check that. It's crazy, and, does the github authentication really work?

**Comment by deltazxm** [comment]
512M sector should be prohibited

**Comment by travisperson** [comment]
> Btw, in the current network, the top-power miner to maintain its power climing, there is over 1.7k transaction from the faucet to it's worker. You may want to check that. It's crazy, and, does the github authentication really work?

I'd assume these are coming from `t1hux5kgqtsllvho72i5krjeeegdlpvdtiznsz4oi`? That address is for the PreCommit reimbursement. You can find that code here: https://github.com/filecoin-project/lotus/blob/next/cmd/lotus-pcr/main.go

It s one small patch at the moment that I have not commited:

```
diff --git a/cmd/lotus-pcr/main.go b/cmd/lotus-pcr/main.go
index aed67408..48913bd2 100644
--- a/cmd/lotus-pcr/main.go
+++ b/cmd/lotus-pcr/main.go
@@ -272,7 +272,7 @@ func ProcessTipset(ctx context.Context, api processTipSetApi, tipset *types.TipS
                }

                if percentExtra > 0 {
-                       refundValue = types.BigAdd(refundValue, types.BigDiv(refundValue, types.NewInt(100*uint64(percentExtra))))
+                       refundValue = types.BigAdd(refundValue, types.BigDiv(types.BigMul(refundValue, types.NewInt(100)), types.NewInt(uint64(percentExtra))))
                }

                log.Infow("processing message", "from", m.From, "to", m.To, "value", m.Value.String(), "gas_fee_cap", m.GasFeeCap.String(), "gas_premium", m.GasPremium.String(), "gas_used", fmt.Sprintf("%d", recps[i].GasUsed), "refund", refundValue.String())
```

It's currently running with a `percent-extra of `100`. This is separate from the github oauth account which is `t13elvjyrcnaynxns57pvxpzlewr572ettf55ouma`.

Running this service is just a way to control the amount of FIL we introduce into the network.
