### ISSUE TITLE
ERROR	chain	chain/sync_manager.go:389	sync error: collectChain failed:

### ISSUE THREAD

**Issue by 815943555** [filecoin-project/lotus#2932]
0|lotus daemon  | 2020-08-09T23:57:01.492+0800	WARN	blocksync	blocksync/client.go:113	could not connect to peer 12D3KooWMBkgbYmEYf28gLaSszFRL8V3Ly1PFsow2T5wCF212Jda: stream reset
0|lotus daemon  | 2020-08-09T23:57:01.492+0800	ERROR	chain	chain/sync_manager.go:389	sync error: collectChain failed:
0|lotus daemon  |     github.com/filecoin-project/lotus/chain.(*Syncer).Sync
0|lotus daemon  |         /home/jack/go_workspace/c-net/lotus/chain/sync.go:509
0|lotus daemon  |   - failed to sync fork:
0|lotus daemon  |     github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
0|lotus daemon  |         /home/jack/go_workspace/c-net/lotus/chain/sync.go:1326
0|lotus daemon  |   - doRequest failed for all peers:
0|lotus daemon  |     github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).doRequest
0|lotus daemon  |         /home/jack/go_workspace/c-net/lotus/chain/blocksync/client.go:136
0|lotus daemon  | 2020-08-09T23:57:01.817+0800	INFO	hello	hello/hello.go:179	time offset	{"offset": 1.065898203, "peerid": "12D3KooWAwPG6R5E1nAgRaXkcZL4Td7F68ARMC7AsfMYDYwp78NT"}
0|lotus daemon  | 2020-08-09T23:57:03.439+0800	WARN	blocksync	blocksync/client.go:113	could not connect to peer 12D3KooWAwPG6R5E1nAgRaXkcZL4Td7F68ARMC7AsfMYDYwp78NT: failed to read cid field t.ParentStateRoot: i/o deadline reached
0|lotus daemon  | 2020-08-09T23:57:03.439+0800	ERROR	hello	hello/hello.go:109	failed to fetch tipset from peer during hello: doRequest failed for single peer 12D3KooWAwPG6R5E1nAgRaXkcZL4Td7F68ARMC7AsfMYDYwp78NT:
0|lotus daemon  |     github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).doRequest
0|lotus daemon  |         /home/jack/go_workspace/c-net/lotus/chain/blocksync/client.go:136
0|lotus daemon  | 2020-08-09T23:57:04.634+0800	WARN	blocksync	blocksync/peer_tracker.go:158	log failure called on peer not in trackerpeerid12D3KooWPjyL6JmmqSoigsGQ19NMfYjWNgedqHdU1cZzHEGUMZz2
0|lotus daemon  | 2020-08-09T23:57:04.634+0800	WARN	blocksync	blocksync/client.go:113	could not connect to peer 12D3KooWPjyL6JmmqSoigsGQ19NMfYjWNgedqHdU1cZzHEGUMZz2: unmarshaling t.Messages pointer: unmarshaling t.To: i/o deadline reached
0|lotus daemon  | 2020-08-09T23:57:04.634+0800	ERROR	hello	hello/hello.go:109	failed to fetch tipset from peer during hello: doRequest failed for single peer 12D3KooWPjyL6JmmqSoigsGQ19NMfYjWNgedqHdU1cZzHEGUMZz2:
0|lotus daemon  |     github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).doRequest
0|lotus daemon  |         /home/jack/go_workspace/c-net/lotus/chain/blocksync/client.go:136

**Comment by Weedshaker** [comment]
I had the same error:
`2020-08-30T12:34:01.967+0200	ERROR	chain	chain/sync_manager.go:389	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /home/silvan/lotus/chain/sync.go:523
  - collectChain syncMessages:
    github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /home/silvan/lotus/chain/sync.go:1560
  - message processing failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).iterFullTipsets
        /home/silvan/lotus/chain/sync.go:1444
  - no peers available:
    github.com/filecoin-project/lotus/chain/blocksync.(*BlockSync).doRequest
        /home/silvan/lotus/chain/blocksync/client.go:91
`

**Comment by shengzhou1216** [comment]
same error.

**Comment by shengzhou1216** [comment]
I have solved this problem. I was getting this error because I was using `make clean all` to compile the calibration branch.  The correct way is to compile with `make clean calibnet`. Hope this helps you guys.
