### ISSUE TITLE
[Blocking Issue] Failed to receive storage miner address/ID after the <Create Miner> action was completed

### ISSUE THREAD

**Issue by xuwenbin** [filecoin-project/lotus#2935]
**Describe the bug**
Miner address/ID is not properly displayed after a Create Miner action was completed. It should return something like **tXXXX** but the actual display is chopped.

**To Reproduce**
1. Goto [faucet](https://faucet.testnet.filecoin.io/) website
2. Click **Create Miner**
3. Enter my owner/worker address
4. Wait until the process is completely
5. Check out the display on the web page
6. Storage miner address/ID field is **incomplete** (see the screenshot#1 below)

**Expected behavior**
The result of my storage miner address should be delivered and displayed in a complete manner.

**Screenshots**
-- No.1 Incompleteness of storage miner address/ID
![image](https://user-images.githubusercontent.com/19218275/89748071-0d67c000-daf4-11ea-8f95-63f81209c938.png)

--No.2 Errors found in Chrome web browser
![image](https://user-images.githubusercontent.com/19218275/89748091-18225500-daf4-11ea-8cbf-cb45b8785f27.png)

--No.3 Errors found in Internet Explorer 11 web browser
![image](https://user-images.githubusercontent.com/19218275/89748099-21abbd00-daf4-11ea-80a4-88d087fdf050.png)

**Version (run `lotus version`):**
Daemon:  0.4.1+git.621bc3a+api0.6.0
Local: lotus version 0.4.1+git.621bc3a

**Additional context**
Server: Ubuntu 16.04
CPU: 8
Memory: 12GB
HDD: 2TB

**Comment by arajasek** [comment]
We have a shiny new authenticated faucet now! https://faucet.glif.io/
