### ISSUE TITLE
StandaloneSealCommit error: Rust panic: no unwind information

### ISSUE THREAD

**Issue by wellhealth** [filecoin-project/lotus#2936]
I use  Intel 2680V3 + 2080Ti seal sectors.

All sectors fail and an error is reported：Rust panic: no unwind information

**Screenshots**

![image](https://user-images.githubusercontent.com/51072254/89751050-1e6afe00-db01-11ea-8884-78b0c7382d5b.png)

**Version (run `lotus version`):**
   lotus-worker version 0.4.3+git.f57529b9.dirty
**Additional context**
root@fc8-03:/lotus_data/cache/s-t01515-984# ls -lrt
total 474633884
-rw-r--r-- 1 root root 68719476704 Aug 10 00:11 sc-02-data-tree-d.dat
-rw-r--r-- 1 root root 34359738368 Aug 10 02:28 sc-02-data-layer-1.dat
-rw-r--r-- 1 root root 34359738368 Aug 10 02:42 sc-02-data-layer-2.dat
-rw-r--r-- 1 root root 34359738368 Aug 10 02:55 sc-02-data-layer-3.dat
-rw-r--r-- 1 root root 34359738368 Aug 10 03:16 sc-02-data-layer-4.dat
-rw-r--r-- 1 root root 34359738368 Aug 10 03:47 sc-02-data-layer-5.dat
-rw-r--r-- 1 root root 34359738368 Aug 10 04:02 sc-02-data-layer-6.dat
-rw-r--r-- 1 root root 34359738368 Aug 10 04:27 sc-02-data-layer-7.dat
-rw-r--r-- 1 root root 34359738368 Aug 10 04:48 sc-02-data-layer-8.dat
-rw-r--r-- 1 root root 34359738368 Aug 10 05:01 sc-02-data-layer-9.dat
-rw-r--r-- 1 root root 34359738368 Aug 10 05:21 sc-02-data-layer-10.dat
-rw-r--r-- 1 root root 34359738368 Aug 10 05:36 sc-02-data-layer-11.dat
-rw-r--r-- 1 root root  4908534048 Aug 10 05:48 sc-02-data-tree-c-0.dat
-rw-r--r-- 1 root root  4908534048 Aug 10 05:59 sc-02-data-tree-c-1.dat
-rw-r--r-- 1 root root  4908534048 Aug 10 06:10 sc-02-data-tree-c-2.dat
-rw-r--r-- 1 root root  4908534048 Aug 10 06:21 sc-02-data-tree-c-3.dat
-rw-r--r-- 1 root root  4908534048 Aug 10 06:32 sc-02-data-tree-c-4.dat
-rw-r--r-- 1 root root  4908534048 Aug 10 06:44 sc-02-data-tree-c-5.dat
-rw-r--r-- 1 root root  4908534048 Aug 10 06:55 sc-02-data-tree-c-6.dat
-rw-r--r-- 1 root root  4908534048 Aug 10 07:06 sc-02-data-tree-c-7.dat
-rw-r--r-- 1 root root     9586976 Aug 10 07:15 sc-02-data-tree-r-last-0.dat
-rw-r--r-- 1 root root     9586976 Aug 10 07:16 sc-02-data-tree-r-last-1.dat
-rw-r--r-- 1 root root     9586976 Aug 10 07:17 sc-02-data-tree-r-last-2.dat
-rw-r--r-- 1 root root     9586976 Aug 10 07:18 sc-02-data-tree-r-last-3.dat
-rw-r--r-- 1 root root     9586976 Aug 10 07:19 sc-02-data-tree-r-last-4.dat
-rw-r--r-- 1 root root     9586976 Aug 10 07:20 sc-02-data-tree-r-last-5.dat
-rw-r--r-- 1 root root     9586976 Aug 10 07:21 sc-02-data-tree-r-last-6.dat
-rw-r--r-- 1 root root     9586976 Aug 10 07:22 sc-02-data-tree-r-last-7.dat
-rw-r--r-- 1 root root         992 Aug 10 07:22 t_aux
-rw-r--r-- 1 root root          64 Aug 10 07:22 p_aux

**Comment by jwjjgsnb** [comment]
hey,did you fix this? i meet same problem

**Comment by deni64k** [comment]
The same problem.

**Comment by Reiers** [comment]
**the issue has been solved in newer version of Lotus.**

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
