### ISSUE TITLE
support a p2p format addr in query-ask

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/lotus#2937]
**Describe the bug**
miner'sp2p format maddr is not support in query-ask

**To Reproduce**
1: set  miners addrs to /ip4/x.x.x.x/tcp/14567/p2p/peerid format
2: just run `lotus client query-ask t0xxxx`

report a no good peers here

**Expected behavior**
should be the same with just tcp format peerid

**Version (run `lotus version`):**
ntwk-calibration branch

**Comment by arajasek** [comment]
Details on how to set miner addresses can be found [here](https://docs.filecoin.io/mine/connectivity/#setting-multiaddresses). Note the format.
