### ISSUE TITLE
equal nonce error

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/lotus#2951]
First time seeing this nonce error. What would cause this?

StorageDealError PublishStorageDeals errored: found message with equal nonce as the one we are looking for

Source: https://calibration.spacerace.filecoin.io/deals/t02949
Initially reported by @ribasushi

**Comment by magik6k** [comment]
Did you run `lotus mpool replace`?

**Comment by ribasushi** [comment]
@magik6k no, I have not touched the `mpool` command on this miner
No restarts either
The client is the bot - I assume they are not touching anything around mpool either

**Comment by ribasushi** [comment]
This now affects all my miners that made deals. What is common amongst them is that they share an owner *and* a worker. Is this supposed to happen?
```
 for m in t02705 t02948 t02949 ; do ./lotus state miner-info $m; done
Owner:	t02629
Worker:	t02629
PeerID:	12D3KooWPAp2VbZThmjH6AfbxSPGNWuAtmELij1fZe1m8Wav1b6j
SectorSize:	512 MiB (536870912)
Multiaddrs: 	/ip4/54.201.86.31/tcp/28003 
Owner:	t02629
Worker:	t02629
PeerID:	12D3KooWQf2Zse6EvGoP4e89hZeK4MBBxwbjSWsWoTdu5zU99hxP
SectorSize:	512 MiB (536870912)
Multiaddrs: 	/ip4/54.201.187.126/tcp/28003 
Owner:	t02629
Worker:	t02629
PeerID:	12D3KooWQ3bX6vjFRpE6grNwnnrYUy1FqZqg4JTep1NuoBwLUfYQ
SectorSize:	512 MiB (536870912)
Multiaddrs: 	/ip4/34.221.81.17/tcp/28003 
```

**Comment by arajasek** [comment]
I do think we have some raciness in our messagepool that can lead to a node creating multiple messages with the same nonce. See this for a (potentially) related issue: https://filecoinproject.slack.com/archives/C017CCH1MHB/p1597120674067400?thread_ts=1597029581.376700&cid=C017CCH1MHB

**Comment by momack2** [comment]
For issues like: 
![image](https://user-images.githubusercontent.com/618519/89947416-46c62b80-dbd9-11ea-95e1-8b6b80b62c3f.png)
This means that the miner sent a **different** message from the _same_ sender, with the _same_ nonce. This likely happens if miners have the **same** key in multiple different lotus nodes. 

WE DO NOT RECOMMEND USING THE SAME MINER ACROSS MULTIPLE NODES FOR THIS REASON!

**Comment by ribasushi** [comment]
I am receiving reports from fil-slack with **only a SINGLE node involved**

https://filecoinproject.slack.com/archives/C017CCH1MHB/p1597827040370500?thread_ts=1597826968.369900&cid=C017CCH1MHB
```
{"code":1,"message":"Retrieve: Retrieval Error: wait for add funds: found message with equal nonce as the one we are looking for (F:bafy2bzaceanemmqooqy52mwr6p5rfhvluiwuoqfhkjvlnccs57nn542r7555m n 1499, TS: bafy2bzaceac63hbiakkerdakjs6a4kz7pxul22tql25vn4vwrpgfxvgpp3fls n1499)"} ClientMinerQueryOffer: {"jsonrpc":"2.0","result":{"Err":"","Root":{"/":"bafk2bzacebz3fswqs5uilxyxjh6rqwtsmowgua3bw6pnncquh6vcckpogyusw"},"Piece":null,"Size":131072,"MinPrice":"262144","UnsealPrice":"0","PaymentInterval
```

https://filecoinproject.slack.com/archives/C017CCH1MHB/p1597826679366700
```
"code":1,"message":"Retrieve: Retrieval Error: wait for add funds: found message with equal nonce as the one we are looking for (F:bafy2bzaced7po3wi5ivmefbpikvjmz3sidpwni64ii5h2phklgxwdgkeu2nrk n 1564, TS: bafy2bzacebttj4jlsl5sm4i5ndjo6ze2dbebqdesddnvk44u7uia3cckhcztw n1564)"} ClientMinerQueryOffer: {"jsonrpc":"2.0","result":{"Err":"","Root":{"/":"bafykbzacebzrwelzid3zvefkuqkygamm5ba67vivnlrma5fk5rxmmclrjcdpy"},"Piece":null,"Size":2147483648,"MinPrice":"4294967296","UnsealPrice":"0","Payment...
```

Something is fishy...

**Comment by arajasek** [comment]
This is a result of the bot sharing an address across 3 nodes. Behaviour is being changed.
