### ISSUE TITLE
Dedicated precommit2 worker does not take in concurrent tasks

### ISSUE THREAD

**Issue by benjaminh83** [filecoin-project/lotus#2960]
I having some problems with the lotus-miner scheduler, which is not really making full use of my setup:

lotus-miner: 256GiB mem, GPU, **no PC1/PC2/C**
worker 1+2: 512GiB mem, 8 threads AMD, **only PC1**
worker 3+4: 256GiB mem, 48 threads AMD, 2xGPU, **only PC2/C**

Scheduler nicely distributes sectors for PC1 between worker 1+2 and fills them up with concurrent tasks. Works PERFECT!

PROBLEM: Although worker 3+4 has loads of threads, which are not really utilized very much, and two GPUs, then they keep on processing only a single sector at a time. I get the info below again and again, as I have 6-12 sectors waiting for PC2, but they keep on denying to take more tasks in. Worker list shows all cores used, but in reality there is only work for 4-10 of the threads.. 

Is this expected behaviour? I would have liked it taking in 2 jobs, and pushing both GPUs harder. Only Commit seems to use multiple GPUs. 

**Worker list**
```
Worker 0, host ubuntu
        CPU:  [                                                                ] 0 core(s) in use
        RAM:  [|                                                               ] 2% 7.009 GiB/250.4 GiB
        VMEM: [|                                                               ] 2% 7.009 GiB/252.4 GiB
        GPU: GeForce GTX 1080, not used
Worker 1, host SealWorker1
        CPU:  [||||                                                            ] 2 core(s) in use
        RAM:  [||||||||||||||                                                  ] 23% 118.8 GiB/503.7 GiB
        VMEM: [||||||||                                                        ] 13% 134.8 GiB/980.6 GiB
Worker 2, host SealWorker2
        CPU:  [||||                                                            ] 1 core(s) in use
        RAM:  [|||||||                                                         ] 12% 62.67 GiB/503.7 GiB
        VMEM: [||||                                                            ] 7% 70.67 GiB/980.6 GiB
Worker 3, host SealWorker4
        CPU:  [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||] 48 core(s) in use
        RAM:  [|||||||||                                                       ] 14% 37.16 GiB/251.5 GiB
        VMEM: [||                                                              ] 5% 37.16 GiB/728.5 GiB
        GPU: TITAN V, not used
        GPU: TITAN V, not used
Worker 4, host SealWorker3
        CPU:  [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||] 48 core(s) in use
        RAM:  [|||||||||                                                       ] 14% 36.85 GiB/251.7 GiB
        VMEM: [|||||||||                                                       ] 14% 36.85 GiB/253.7 GiB
        GPU: GeForce GTX 1080, not used
        GPU: GeForce GTX 1080, not used
```

**Lotus Miner Info**
```
Miner: t02479
Sector Size: 32 GiB
Byte Power:   320 GiB / 3.966 PiB (0.0076%)
Actual Power: 320 Gi / 4.6 Pi (0.0066%)
        Committed: 448 GiB
        Proving: 448 GiB (128 GiB Faulty, 28.57%)
Below minimum power threshold, no blocks will be won
Miner Balance: 197.036632406768759677 FIL
        PreCommit:   32.647158002200662427 FIL
        Locked:      0 FIL
        Available:   164.38947440456809725 FIL
Worker Balance: 16986.174891902179069198 FIL
Market (Escrow):  0 FIL
Market (Locked):  0 FIL

Expected Seal Duration: 12h0m0s

Sectors:
        Total: 32
        Proving: 10
        PreCommit1: 3
        PreCommit2: 7
        PreCommitWait: 1
        WaitSeed: 3
        Committing: 4
```

**Lotus storage miner logs**
```
2020-08-10T21:58:26.274+0200	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched_resources.go:73	sched: not scheduling on worker 3; multicore process needs 48 threads, 48 in use, target 48
2020-08-10T22:00:42.943+0200	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched_resources.go:73	sched: not scheduling on worker 4; multicore process needs 48 threads, 48 in use, target 48
```

**Version**
lotus version 0.4.3+git.2340742e

**Comment by RobQuistNL** [comment]
Can you try running the workers 3 and 4 with this flag: `BELLMAN_CPU_UTILIZATION=0.5` ? or maybe a bit lower (0.45 or something) ?

**Comment by benjaminh83** [comment]
@RobQuistNL hmm, interesting, but the DEBUG message is pointing at the 48 CPU threads - like the scheduler has allocated all 48 treads, and therefore does not allow more jobs. I would probably more expect some kind of limit to 8 threads or something like that. The flag you mention would limit the process to use >=1 GPU in a 2 GPU setup right?

**Comment by RobQuistNL** [comment]
The flag I mentioned would make it use 50% of the cores, so maybe that helps. I think there's another config variable you can use to make 1 worker select just 1 GPU - so you could have 2 worker processes on 1 machine with 2 GPU's - each with 0.5 CPU affinity and 1 dedicated GPU.

Still would be nice if this was done automatically tho ^_^

**Comment by Reiers** [comment]
Hi @benjaminh83 

Thanks for the report. The issue is outdated. 

With [control groups](https://lotus.filecoin.io/storage-providers/advanced-configurations/workers/#control-groups) and the improved scheduler in [v1.15.2-rc1](https://github.com/filecoin-project/lotus/releases/tag/v1.15.2-rc1) . 
I think the issue is/will be resolved.  

If you still think this is an issue in the latest release - please open a new ticket, with new logs etc. 

Thank you !
