### ISSUE TITLE
All power lost with 100% Fauty and One PreCommitFailed. 

### ISSUE THREAD

**Issue by jjxx2021** [filecoin-project/lotus#2964]
**Describe the bug**

jjxx@fc02:~$ lotus-miner info
Miner: t01858
Sector Size: 32 GiB
Byte Power:   0 B / 3.987 PiB (0.0000%)
Actual Power: 0  / 4.62 Pi (0.0000%)
        Committed: 160 GiB
        Proving: 160 GiB (160 GiB Faulty, 100.00%)
Below minimum power threshold, no blocks will be won
Miner Balance: 34.355471803045988311 FIL
        PreCommit:   25.131296666800934244 FIL
        Locked:      0 FIL
        Available:   9.224175136245054067 FIL
Worker Balance: 9423.695450762262407347 FIL
Market (Escrow):  0.00000000576 FIL
Market (Locked):  0 FIL
Expected Seal Duration: 12h0m0s
Sectors:
        Total: 37
        Proving: 5
        PreCommit1: 15
        PreCommit2: 6
        PreCommitting: 3
        Committing: 7
        PreCommitFailed: 1
jjxx@fc02:~$ lotus-miner sectors list
0: Proving          sSet: YES active: NO tktH: 654  seedH: 2766 deals: [0]
1: Proving          sSet: YES active: NO tktH: 661  seedH: 2963 deals: [0]
2: Proving          sSet: YES active: NO tktH: 704  seedH: 2467 deals: [9114 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
3: Proving          sSet: YES active: NO tktH: 2355 seedH: 4975 deals: [0]
4: Proving          sSet: YES active: NO tktH: 2355 seedH: 4848 deals: [0]
5: Committing       sSet: NO  active: NO tktH: 2409 seedH: 5095 deals: [0]
6: Committing       sSet: NO  active: NO tktH: 2409 seedH: 5378 deals: [0]
7: Committing       sSet: NO  active: NO tktH: 2410 seedH: 5501 deals: [0]
8: Committing       sSet: NO  active: NO tktH: 2908 seedH: 5231 deals: [0]
9: Committing       sSet: NO  active: NO tktH: 3509 seedH: 7555 deals: [0]
10: PreCommit2      sSet: NO  active: NO tktH: 3510 seedH: 0    deals: [0]
11: PreCommitting   sSet: NO  active: NO tktH: 3646 seedH: 0    deals: [11735 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
12: PreCommitting   sSet: NO  active: NO tktH: 3766 seedH: 0    deals: [11929 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
13: Committing      sSet: NO  active: NO tktH: 3878 seedH: 7684 deals: [12054 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
14: PreCommit2      sSet: NO  active: NO tktH: 3990 seedH: 0    deals: [12186 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
15: PreCommit2      sSet: NO  active: NO tktH: 4108 seedH: 0    deals: [12459 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
16: Committing      sSet: NO  active: NO tktH: 4227 seedH: 7948 deals: [12631 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
17: PreCommitting   sSet: NO  active: NO tktH: 4347 seedH: 0    deals: [12783 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
18: PreCommit2      sSet: NO  active: NO tktH: 4471 seedH: 0    deals: [12921 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
19: PreCommitFailed sSet: NO  active: NO tktH: 4583 seedH: 0    deals: [13067 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
20: PreCommit2      sSet: NO  active: NO tktH: 4712 seedH: 0    deals: [13163 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
21: PreCommit2      sSet: NO  active: NO tktH: 4828 seedH: 0    deals: [13280 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
22: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [13482 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
23: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [13626 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
24: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [13891 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
25: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [14280 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
26: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [14559 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
27: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [14720 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
28: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [14844 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
29: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [14987 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
30: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [15089 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
31: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [15150 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
32: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [15330 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
33: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [15470 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
34: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [15587 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
35: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [15711 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
36: PreCommit1      sSet: NO  active: NO tktH: 0    seedH: 0    deals: [15872 0 0 0 0 0 0 0]

<<<< log in worker2
2020-08-10T13:27:20.230+0800    ^[[34mINFO^[[0m stores  stores/remote.go:221    Fetch http://192.168.0.102:2345/remote/unsealed/s-t01858-19 -> /cache/worker01/unsealed/fetching/s-t01858-19
2020-08-11T03:39:44.522+0800    ^[[34mINFO^[[0m stores  stores/http_handler.go:55       SERVE GET /remote/sealed/s-t01858-19
2020-08-11T03:43:05.504+0800    ^[[34mINFO^[[0m stores  stores/http_handler.go:120      SERVE DELETE /remote/sealed/s-t01858-19
2020-08-11T03:43:05.505+0800    ^[[34mINFO^[[0m stores  stores/local.go:513     remove /cache/worker01/sealed/s-t01858-19
<<<<< log in worker2
2020-08-11T03:39:44.518+0800    ^[[34mINFO^[[0m stores  stores/remote.go:221    Fetch http://192.168.0.101:3456/remote/sealed/s-t01858-19 -> /cache/worker02/sealed/fetching/s-t01858-19
2020-08-11T03:43:05.488+0800    ^[[35mDEBUG^[[0m        stores  stores/util_unix.go:28  move sector data        {"from": "/cache/worker02/sealed/fetching/s-t01858-19", "to": "/cache/worker02/sealed/s-t01858-19"}
2020-08-11T03:43:05.500+0800    ^[[34mINFO^[[0m stores  stores/remote.go:322    Delete http://192.168.0.101:3456/remote/sealed/s-t01858-19
2020-08-11T03:43:05.504+0800    ^[[34mINFO^[[0m stores  stores/remote.go:221    Fetch http://192.168.0.101:3456/remote/cache/s-t01858-19 -> /cache/worker02/cache/fetching/s-t01858-19
2020-08-11T04:22:21.860+0800    ^[[35mDEBUG^[[0m        stores  stores/util_unix.go:28  move sector data        {"from": "/cache/worker02/cache/fetching/s-t01858-19", "to": "/cache/worker02/cache/s-t01858-19"}
2020-08-11T04:22:21.865+0800    ^[[34mINFO^[[0m stores  stores/remote.go:322    Delete http://192.168.0.101:3456/remote/cache/s-t01858-19
2020-08-11T04:22:28.722+0800    ^[[35mDEBUG^[[0m        advmgr  sector-storage@v0.0.0-20200805173933-deec7a2658d4/localworker.go:75     acquired sector {1858 19} (e:6; a:0): {{0 0}  /cache/worker02/sealed/s-t01858-19 /cache/worker02/cache/s-t01858-19}
2020-08-11T04:49:15.513+0800    ^[[35mDEBUG^[[0m        advmgr  sector-storage@v0.0.0-20200805173933-deec7a2658d4/localworker.go:75     acquired sector {1858 19} (e:6; a:0): {{0 0}  /cache/worker02/sealed/s-t01858-19 /cache/worker02/cache/s-t01858-19}
2020-08-11T05:51:53.489 INFO storage_proofs_core::data > dropping data /cache/worker02/sealed/s-t01858-19

jjxx@fc02:~$ ls /cache/worker02/sealed/s-t01858-19
/cache/worker02/sealed/s-t01858-19
jjxx@fc02:~$ ls /cache/worker02/cache/s-t01858-19
p_aux                    sc-02-data-layer-3.dat  sc-02-data-layer-8.dat   sc-02-data-tree-c-3.dat  sc-02-data-tree-d.dat         sc-02-data-tree-r-last-4.dat
sc-02-data-layer-10.dat  sc-02-data-layer-4.dat  sc-02-data-layer-9.dat   sc-02-data-tree-c-4.dat  sc-02-data-tree-r-last-0.dat  sc-02-data-tree-r-last-5.dat
sc-02-data-layer-11.dat  sc-02-data-layer-5.dat  sc-02-data-tree-c-0.dat  sc-02-data-tree-c-5.dat  sc-02-data-tree-r-last-1.dat  sc-02-data-tree-r-last-6.dat
sc-02-data-layer-1.dat   sc-02-data-layer-6.dat  sc-02-data-tree-c-1.dat  sc-02-data-tree-c-6.dat  sc-02-data-tree-r-last-2.dat  sc-02-data-tree-r-last-7.dat
sc-02-data-layer-2.dat   sc-02-data-layer-7.dat  sc-02-data-tree-c-2.dat  sc-02-data-tree-c-7.dat  sc-02-data-tree-r-last-3.dat  t_aux

<<<< 
filfox show that the power lost after 8/11 3:49 China zone. The only message is SubmitWindowedPoSt, and the state is ErrIllegalArgument.

Message ID | Height | Time | From | To | Method | Value | Status
-- | -- | -- | -- | -- | -- | -- | --
bafy2bzacebysut3zarjagga2sd2jz7be6dkliek2djeizwrjx5yzp6ggmmbpq | 7934 | 2020-08-11 04:48:00 | t3sjn5ifhywpwmf3crzlxu2zhfqhybhw362yuiyfabafuuc23cooldsq2khg2tr3u2a5k4qxyfy7ncost5sdva | t01858 | SubmitWindowedPoSt | 1,000 attoFIL | ErrIllegalArgument
bafy2bzaceannmty7qqvmjeiiyin4jxo4h4glii3evsubwi4jvnfnsmp72j2se | 7798 | 2020-08-11 03:40:00 | t3sjn5ifhywpwmf3crzlxu2zhfqhybhw362yuiyfabafuuc23cooldsq2khg2tr3u2a5k4qxyfy7ncost5sdva | t01858 | PreCommitSector | 4.4827 FIL | OK

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**
No power should be lost.

**Screenshots**

**Version (run `lotus version`):**

jjxx@fc02:~$ lotus -v
lotus version 0.4.3+git.2340742e.dirty

**Additional context**

**Comment by arajasek** [comment]
Re-running your message, it failed because of the check [here](https://github.com/filecoin-project/specs-actors/blob/9d42fb163883f31325b08752c9f4e85d0b3ef22f/actors/builtin/miner/miner_actor.go#L293-L297).

This is almost definitely because of the current network's congestion issues: Messages are having a really hard time landing on chain, and so your PoSts are landing after the deadline has closed. We're working on a few fixes for the network congestion, will be out very soon!

**Comment by Shekelme** [comment]
I have two sectors in 

> Proving sSet: YES active: NO

 state too.
