### ISSUE TITLE
Mpool has been stucked for more than 24 hours

### ISSUE THREAD

**Issue by wellhealth** [filecoin-project/lotus#2971]
My Mpool has been stucked for more than 24 hours.

 "lotus mpool stat " on other daemon ,my node only  5 msgs for wait.
    **t3uqfujyqkbaekvssamjtp7l6f6ubfo7dxsahthsltbu23dqcdlcsbyiha5d4xnyck5xxwwchst7yxcftcu4ka: past: 0, cur: 5, future: 14_**

 "lotus mpool stat " on My lotus Node

**t3uqfujyqkbaekvssamjtp7l6f6ubfo7dxsahthsltbu23dqcdlcsbyiha5d4xnyck5xxwwchst7yxcftcu4ka: past: 0, cur: 1601, future: 0**
 ....
-----
**total: past: 0, cur: 1936, future: 1167**

**Comment by arajasek** [comment]
See https://github.com/filecoin-project/lotus/issues/2969#issuecomment-671714476
