### ISSUE TITLE
mpool problem

### ISSUE THREAD

**Issue by liuzhongzhu423** [filecoin-project/lotus#2972]
Message blocking mpool has no response, and the computing power has been lost in the log, but it has not been reflected
![image](https://user-images.githubusercontent.com/58395056/89856012-a701a100-dbca-11ea-8b3f-2e0f794f4783.png)
![image](https://user-images.githubusercontent.com/58395056/89856063-d1ebf500-dbca-11ea-8a7f-e2d82ce514d1.png)

![image](https://user-images.githubusercontent.com/58395056/89856332-8a199d80-dbcb-11ea-9780-b05396f038db.png)

**Comment by arajasek** [comment]
See https://github.com/filecoin-project/lotus/issues/2969#issuecomment-671714476
