### ISSUE TITLE
Scheduler delays PC2 start until all threads available on CPU

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#2973]
I am running two concurrent jobs at the same time for PC1. When one completes, PC2 does not start because "multicore process needs 24 threads, 1 in use, target 24"

Scheduler should not block next job when enough memory and enough CPU is available.

ENV is set **BELLMAN_CPU_UTILIZATION=0.8**

**Lotus-Miner logs**
> 2020-08-11T03:53:17.316Z	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched.go:286	SCHED 1 queued; 4 open windows
> 2020-08-11T03:53:17.330Z	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched.go:351	SCHED windows: [{allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]}]
> 2020-08-11T03:53:17.330Z	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched.go:352	SCHED Acceptable win: [[0 2]]
> 2020-08-11T03:53:17.330Z	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched.go:366	SCHED try assign sqi:0 sector 0 to window 0
> 2020-08-11T03:53:17.331Z	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched.go:373	SCHED ASSIGNED sqi:0 sector 0 to window 0
> 2020-08-11T03:53:17.331Z	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched.go:516	assign worker sector 0
> 2020-08-11T03:53:17.331Z	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched.go:286	SCHED 0 queued; 4 open windows
> 2020-08-11T03:53:17.331Z	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched.go:351	SCHED windows: [{allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]}]
> 2020-08-11T03:53:17.331Z	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched.go:352	SCHED Acceptable win: []
> 2020-08-11T03:53:17.338Z	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/sched_resources.go:73	sched: not scheduling on worker 2; multicore process needs 24 threads, 1 in use, target 24

**Lotus-Worker logs**
> 2020-08-11T03:53:17.278 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:finish
> 2020-08-11T03:53:17.282 INFO filcrypto::proofs::api > seal_pre_commit_phase1: finish
> 2020-08-11T03:53:17.336Z	DEBUG	advmgr	sector-storage@v0.0.0-20200805173933-deec7a2658d4/localworker.go:75	acquired sector {3236 0} (e:6; a:0): {{0 0}  /Lotus/worker/sealed/s-t03236-0 /Lotus/worker2/cache/s-t03236-0}

`lotus-miner sealing jobs`

> ID  Sector  Worker  Hostname  Task  Time
> 3   1       2       filecoin  PC1   4h56m26.1s

`lotus-miner sectors list`

> 0: PreCommit2 sSet: NO active: NO tktH: 7033 seedH: 0 deals: [0]
> 1: PreCommit1 sSet: NO active: NO tktH: 0    seedH: 0 deals: [0]
> 2: WaitDeals  sSet: NO active: NO tktH: 0    seedH: 0 deals: [16051]

`lotus-miner sealing sched-diag`

> {
>   "OpenWindows": [
>     0,
>     2,
>     0,
>     2
>   ],
>   "Requests": null
> }

`lotus-miner sealing workers`

> Worker 0, host filecoin
> 	CPU:  [                                                                ] 0 core(s) in use
> 	RAM:  [|                                                               ] 2% 3.371 GiB/125.7 GiB
> 	VMEM: [                                                                ] 1% 3.371 GiB/321.1 GiB
> 	GPU: GeForce GTX 1080 Ti, not used
> Worker 2, host filecoin
> 	CPU:  [||                                                              ] 1 core(s) in use
> 	RAM:  [||||||||||||||||||||||||||||||                                  ] 47% 60 GiB/125.7 GiB
> 	VMEM: [||||||||||||                                                    ] 21% 68 GiB/321.1 GiB
> 	GPU: GeForce GTX 1080 Ti, not used

`lotus-miner sectors list`

> 0: PreCommit2 sSet: NO active: NO tktH: 7033 seedH: 0 deals: [0]
> 1: PreCommit1 sSet: NO active: NO tktH: 0    seedH: 0 deals: [0]
> 2: WaitDeals  sSet: NO active: NO tktH: 0    seedH: 0 deals: [16051]

System - single server Ubuntu 20.04 - Ryzen 9 3900xt 128 GB RAM
Lotus version Daemon:  0.4.3+git.2340742e+api0.9.0 - Local: lotus version 0.4.3+git.2340742e

**Comment by kernelogic** [comment]
I was wondering about this too

**Comment by magik6k** [comment]
This is a limitation of the sealing scheduler resource allocator. Currently when a task is declared as multicore in the resource table - like https://github.com/filecoin-project/lotus/blob/next/extern/sector-storage/resources.go#L122 - we'll always require all cores for it to run:

https://github.com/filecoin-project/lotus/blob/next/extern/sector-storage/sched_resources.go#L71-L72

I guess the correct fix is to allow some % of cores to be in use when starting multicore processes, and the easiest way to do this would be to just make multicore tasks require only some % of the cpu (I feel like 85% is a good number, gives ~1 thread per 8)

((we could also do something more smart when we detect systems with multiple NUMA nodes, but that's probably out of scope for this PR))

**Comment by magik6k** [comment]
Fixed!
