### ISSUE TITLE
"Tie breaker rule": implement a method to decide between chains with the same weight

### ISSUE THREAD

**Issue by irenegia** [filecoin-project/lotus#2981]
**Background**
Two (or more) forks may have the same exact weight and in this case we need a rule to decide which one to extend. 

**Proposal**
Implement the following rule already described in the spec [link](https://filecoin-project.github.io/specs/#selecting-between-tipsets-with-equal-weight):

> When selecting between Tipsets of equal weight, a miner chooses the one with the smallest final ticket.
> 
> In the case where two Tipsets of equal weight have the same min ticket, the miner will compare the next smallest ticket (and select the Tipset with the next smaller ticket). This continues until one Tipset is selected.

Note: we should use the ticket used as election proof (`VRF(drand)`) for this ([updated spec](https://hackmd.io/@rCqYwHC7RQeS4hwgARV_tg/SJSOb7GyP#Tie-breaker-rules)).

CC @sa8 @Kubuxu

**Comment by nicola** [comment]
I propose that @sa8 writes this as an FIP in the FIP repo (https://github.com/filecoin-project/fips)

**Comment by sa8** [comment]
Link to FIP: https://docs.google.com/document/d/1VHm_0rh9XCcjJsrnpbLtbFpLNRmOgkEoNTNlt0NHiOQ/edit?usp=sharing

**Comment by nicola** [comment]
This was written up here: https://github.com/filecoin-project/FIPs/issues/22

**Comment by jennijuju** [comment]
FIP: https://github.com/filecoin-project/FIPs/pull/156/files
