### ISSUE TITLE
lotus daemon crash.

### ISSUE THREAD

**Issue by wellhealth** [filecoin-project/lotus#2997]
This morning the Lotus crashed.

Daemon:  0.4.3+git.2340742e+api0.9.0
Local: lotus version 0.4.3+git.2340742e

2020-08-12T04:33:47.206+0800    INFO    pubsub  go-libp2p-pubsub@v0.3.4-0.20200731161531-2b5243c72f0d/pubsub.go:927     received message from router graylisted peer 12D3KooWRF2FZsxSNa7WFm1YRnyQq7fos9jSEQ4mvVAqL3fsjd6H. Dropping RPC
2020-08-12T04:33:47.213+0800    INFO    messagepool     messagepool/pruning.go:42       message pruning took 177.23341ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x115389a]

goroutine 839 [running]:
github.com/filecoin-project/lotus/chain/messagepool.(*msgChain).Before(...)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/messagepool/selection.go:522
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).pruneMessages.func2(0x0, 0x3c, 0x0)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/messagepool/pruning.go:81 +0x4a
sort.doPivot_func(0xc0814d5800, 0xc0386be900, 0x0, 0x90, 0x18, 0xc0386be8e0)
        /usr/local/go/src/sort/zfuncversion.go:87 +0x44c
sort.quickSort_func(0xc0814d5800, 0xc0386be900, 0x0, 0x90, 0x10)
        /usr/local/go/src/sort/zfuncversion.go:143 +0x9a
sort.Slice(0x25adf40, 0xc0386be8e0, 0xc0814d5800)
        /usr/local/go/src/sort/slice.go:17 +0xf1
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).pruneMessages(0xc0004ff790, 0x2d6cda0, 0xc0000440b0, 0xc0a3516140, 0x0, 0x0)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/messagepool/pruning.go:80 +0x6c7
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).pruneExcessMessages(0xc0004ff790, 0x0, 0x0)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/messagepool/pruning.go:28 +0x11b
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).runLoop(0xc0004ff790)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/messagepool/messagepool.go:342 +0xa38
created by github.com/filecoin-project/lotus/chain/messagepool.New
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/messagepool/messagepool.go:249 +0x638

**Comment by arajasek** [comment]
This has been fixed in #2979
