### ISSUE TITLE
Common Retrieval Failure: "error: unmarshaling result: failed to parse big string"

### ISSUE THREAD

**Issue by momack2** [filecoin-project/lotus#2998]
Raw results from testing retrieval on 81 active deals here: https://github.com/jimpick/filecoin-wiki-test/tree/master/wiki-large-blocks/retrievals/2020-08-10-d

A lot of the failures look like this:
`2020-08-11T22:52:19.518Z	[33mWARN[0m	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/client.go:406	unmarshaling failed	{"message": "{\"Err\":\"EOF\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"t02275\",\"MinerPeer\":{\"Address\":\"t02275\",\"ID\":\"12D3KooWDo7BT5t2JfYrnsVYR96GvZG5V1T5Kt7yBLsh7Dv9aaMj\",\"PieceCID\":null}}"}
ERROR: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
Command exited with non-zero status 1
0.04user 0.00system 0:00.88elapsed 5%CPU (0avgtext+0avgdata 37200maxresident)k
0inputs+0outputs (0major+3520minor)pagefaults 0swaps`

https://raw.githubusercontent.com/jimpick/filecoin-wiki-test/master/wiki-large-blocks/retrievals/2020-08-10-d/wiki.zip.an-t02275-15483-1597186338.log

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
