### ISSUE TITLE
Fix up all places where we use random incorrect exit codes

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#3015]
There are a number of places where we use a random nonsense error code in an actorError in the VM. This causes some really hard to debug message failures. 

Example places where this happens (thanks @arajasek ):

- https://github.com/filecoin-project/lotus/blob/cad59b045be24f59a1ad952ae93327a4612701b7/chain/vm/invoker.go#L141
- https://github.com/filecoin-project/lotus/blob/fe2da35a45807576672b3376224de2345f594575/chain/vm/vm.go#L525
- https://github.com/filecoin-project/lotus/blob/ae634ef7dfd783ab2baf890aa6a7281163ca4998/chain/actors/params.go#L14
- https://github.com/filecoin-project/lotus/blob/fe2da35a45807576672b3376224de2345f594575/chain/vm/runtime.go#L123

**Comment by magik6k** [comment]
No longer relevant in the FVM world
