### ISSUE TITLE
Always set fast retrieval flag to "true" when creating deals

### ISSUE THREAD

**Issue by momack2** [filecoin-project/lotus#3017]
Reported by Jim:

If you are using the API, the default value for "fast retrieval" is false when creating a storage deal. For the CLI the default is true - as it should be. We should be consistent with our defaults and always set this to true to avoid confusing downstream API users!

**Comment by arajasek** [comment]
I'm not sure what this would require...changing go-jsonrpc to use `true` for omitted values?

**Comment by magik6k** [comment]
The method accepts params as
```
type StartDealParams struct {
	Data              *storagemarket.DataRef
	Wallet            address.Address
	Miner             address.Address
	EpochPrice        types.BigInt
	MinBlocksDuration uint64
	DealStartEpoch    abi.ChainEpoch
	FastRetrieval     bool
	VerifiedDeal      bool
}
```

I guess we could just invert the `FastRetrieval` param to be `NoFastRetrieval` / `SlowRetrieval`

**Comment by whyrusleeping** [comment]
Defaults in the CLI make sense, if youre sending a request over the wire, you should be expected to know what you are doing and specify all of the fields. I'm not sure we should actually change anything here

**Comment by whyrusleeping** [comment]
If we really want to make this change, i think adding a JSONUnmarshaler method to the struct in question that defaults the value to true seems more reasonable

**Comment by arajasek** [comment]
The CLI does this, the API does not.

**Comment by dineshshenoy** [comment]
I think this request is to change the API so it defaults to fast-retrieval.
