### ISSUE TITLE
PreCommit2Fails and InvalidProofs should be allowed to retry more times

### ISSUE THREAD

**Issue by Leozhang404** [filecoin-project/lotus#3019]
In the latest version, about sealing process, these two states just try once:

1. [sector.PreCommit2Fails](https://github.com/filecoin-project/lotus/blob/641eb3e2cf4b19f0b7adf3a904cd639a433f9ee1/extern/storage-fsm/states_failed.go#L59)

`if sector.PreCommit2Fails > 1 {`

2. [sector.InvalidProofs](https://github.com/filecoin-project/lotus/blob/641eb3e2cf4b19f0b7adf3a904cd639a433f9ee1/extern/storage-fsm/states_failed.go#L132)

`if sector.InvalidProofs > 1 {`

**Describe the problem**
The miner sealing process will failed due to many reasons, but the sector  so I think if the sector sealing  has `preCommitFailed` and `CommitFailed` , it should be allowed to retry more times. 

please check.

**Comment by Leozhang404** [comment]
@whyrusleeping @magik6k please check again.

**Comment by magik6k** [comment]
So given that a single operation here can take ~hours, we don't always want to retry more than 2-3 times.

I think that a reasonable thing to do here would be to record first failure time, and retry, let's say, max 20 times or for 4h

**Comment by Leozhang404** [comment]
yes, some operations may take a long time, but some just take a little time, so I think we can control the retry times by setting max retry times and failure time. it is a good idea.

**Comment by rjan90** [comment]
If I'm not mistaken I think it will retry PC2 multiple times now, if PC2 fails? So maybe this issue can be closed now? #rengjøring

**Comment by Reiers** [comment]
**If a PC2 ends in failure - it will try again.** 
This is solved in newer versions of Lotus. 

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
Closing this ticket.
