### ISSUE TITLE
submitPost failed with due to post commit randomness mismatched

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/lotus#3052]
**Describe the bug**
submitPost failed with due to post commit randomness mismatched

**Screenshots**
![image](https://user-images.githubusercontent.com/4746061/90252067-74c59d00-de71-11ea-9506-ec2d36314ba0.png)

This error reproduce many times.
![image](https://user-images.githubusercontent.com/4746061/90252135-9030a800-de71-11ea-902f-bddafa6d4dc7.png)

**Version (run `lotus version`):**

`lotus version 0.4.4+git.4c5e9614`

**Additional context**
```
Miner: t01332
Sector Size: 512 MiB
Byte Power:   261.5 GiB / 887.3 TiB (0.0287%)
Actual Power: 262 Gi / 1.29 Pi (0.0193%)
	Committed: 300.5 GiB
	Proving: 300.5 GiB (39 GiB Faulty, 12.97%)
Below minimum power threshold, no blocks will be won
Miner Balance: 841.983908216755174111 FIL
	PreCommit:   2.127275788493425793 FIL
	Locked:      0 FIL
	Available:   839.856632428261748318 FIL
Worker Balance: 356.681193034235498698 FIL
Market (Escrow):  0.00000936325583695 FIL
Market (Locked):  0.00000936325583695 FIL

Expected Seal Duration: 12h0m0s

Sectors:
	Total: 680
	Proving: 598
	PreCommit1: 1
	PreCommitWait: 4
	WaitSeed: 73
	Committing: 1
	CommitWait: 3

```

**Comment by leviok** [comment]
the same

**Comment by magik6k** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/3062, we'll merge the fix into `ntwk-calibration` soon
