### ISSUE TITLE
gas estimator fails during storage deals - calibration network

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#3054]
**Describe the bug**

> WARN	providerstates	providerstates/provider_states.go:442	deal bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a failed: error calling node: publishing deal: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr t01213: escrow balance 54282624895148295 < locked 54282624895148295 + required 51071071395141152 (RetCode=19)

**To Reproduce**
Other miners or bots try to send me a storage deal

**Expected behavior**
I accept deal - current FIL balances:

> Miner Balance: 8.113422447355587389 FIL
> 	PreCommit:   1.693789127258230287 FIL
> 	Locked:      0 FIL
> 	Available:   6.419633320097357102 FIL
> Worker Balance: 379.827644656011673498 FIL
> Market (Escrow):  0.054282624895148295 FIL
> Market (Locked):  0.054282624895148295 FIL

**Screenshots**
`lotus-miner storage-deals list`

> ProposalCid  DealId  State               Client                                                                                  Size    Price                     Duration
> ...ssrsodl4  2607    StorageDealSealing  t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               128KiB  0.00000000000351345 FIL   702690
> ...jebhdxxy  0       StorageDealError    t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               128KiB  0.00000000000351626 FIL   703252
> ...wbqkv3a4  2324    StorageDealSealing  t3xeix4c7qdxe3g6s2adj35u3dheqnrq5awjicz3lezvo2jxcw4zoefbk3su7yrmnhivs7yfrkrvjhpvn32uba  128KiB  0.000001160824 FIL        580412
> ...7uljt2du  0       StorageDealError    t1uwv4z5qpt4qcquczpplv757l26m47poi4egwqdq                                               128MiB  0.00000000175693 FIL      702772
> ...ohnzu6ym  0       StorageDealError    t1cietab64ttrspiyvhx5yoz3gdqsculetnzoviai                                               256B    6.11761 FIL               611761
> ...jy7k5g2a  0       StorageDealError    t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               2GiB    0.00000000000702288 FIL   702288
> ...o7sumt4i  3641    StorageDealSealing  t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               2GiB    0.00000000000702417 FIL   702417
> ...stzl7n4y  0       StorageDealError    t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               128KiB  0.000000000003514055 FIL  702811
> ...6xc5an64  0       StorageDealError    t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               128KiB  0.000000000003514635 FIL  702927
> ...vpzea7am  0       StorageDealError    t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               128KiB  0 FIL                     702306
> ...aisjct4e  3647    StorageDealSealing  t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               128MiB  0.000000000000702403 FIL  702403
> ...fc3aflru  0       StorageDealError    t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               128KiB  0.00000000000351403 FIL   702806
> ...yn5grzla  0       StorageDealError    t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               2GiB    0.00000000000351567 FIL   703134
> ...tx7iele4  0       StorageDealError    t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               128KiB  0.00000000000351562 FIL   703124
> ...ov3jxnke  0       StorageDealError    t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               128KiB  0.00000000000351466 FIL   702932
> ...7ts6bwdq  2608    StorageDealSealing  t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               128KiB  0.00000000000351345 FIL   702690
> ...yfhqbhw4  0       StorageDealError    t1cietab64ttrspiyvhx5yoz3gdqsculetnzoviai                                               256B    0.0000000000026126 FIL    522520
> ...6yfdlife  0       StorageDealError    t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               2GiB    0.000000000003516255 FIL  703251

**Version (run `lotus version`):**
`lotus version`

> Daemon:  0.4.4+git.002e972f+api0.10.0
> Local: lotus version 0.4.4+git.002e972f

**Additional context**
Miner log

> 2020-08-14T14:48:55.249Z	INFO	storagemarket_impl	impl/provider.go:195	Handling storage deal proposal!
> 2020-08-14T14:48:55.306Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventOpen", "proposal CID": "bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a", "state": "StorageDealValidating", "message": ""}
> 2020-08-14T14:48:55.334Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventDealDeciding", "proposal CID": "bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a", "state": "StorageDealAcceptWait", "message": ""}
> 2020-08-14T14:48:55.353Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventDataRequested", "proposal CID": "bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a", "state": "StorageDealWaitingForData", "message": ""}
> 2020-08-14T14:48:55.386Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventDataTransferInitiated", "proposal CID": "bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a", "state": "StorageDealTransferring", "message": ""}
> 2020-08-14T14:49:22.729Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventDataTransferCompleted", "proposal CID": "bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a", "state": "StorageDealVerifyData", "message": ""}
> 2020-08-14T14:49:26.624 INFO filecoin_proofs::api > generate_piece_commitment:start
> 2020-08-14T14:49:55.085 INFO filecoin_proofs::api > generate_piece_commitment:finish
> 2020-08-14T14:49:55.085Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventVerifiedData", "proposal CID": "bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a", "state": "StorageDealEnsureProviderFunds", "message": ""}
> 2020-08-14T14:49:55.146Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventFundsReserved", "proposal CID": "bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a", "state": "StorageDealEnsureProviderFunds", "message": ""}
> 2020-08-14T14:49:55.154Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventFunded", "proposal CID": "bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a", "state": "StorageDealPublish", "message": ""}
> 2020-08-14T14:49:55.162Z	INFO	storageadapter	storageadapter/provider.go:60	publishing deal
> 2020-08-14T14:49:55.168Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventNodeErrored", "proposal CID": "bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a", "state": "StorageDealFailing", "message": "error calling node: publishing deal: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr t01213: escrow balance 54282624895148295 < locked 54282624895148295 + required 51071071395141152 (RetCode=19)"}
> 2020-08-14T14:49:55.173Z	WARN	providerstates	providerstates/provider_states.go:442	deal bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a failed: error calling node: publishing deal: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr t01213: escrow balance 54282624895148295 < locked 54282624895148295 + required 51071071395141152 (RetCode=19)
> 2020-08-14T14:49:55.205Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventFundsReleased", "proposal CID": "bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a", "state": "StorageDealFailing", "message": "error calling node: publishing deal: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr t01213: escrow balance 54282624895148295 < locked 54282624895148295 + required 51071071395141152 (RetCode=19)"}
> 2020-08-14T14:49:55.216Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventFailed", "proposal CID": "bafyreidev65egadnem7ajiidxd4raioc4epqprlyb63rpultfljy7k5g2a", "state": "StorageDealError", "message": "error calling node: publishing deal: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr t01213: escrow balance 54282624895148295 < locked 54282624895148295 + required 51071071395141152 (RetCode=19)"}

**Comment by kernelogic** [comment]
same issue here

**Comment by stuberman** [comment]
Still a problem after the update:
`lotus version`

> Daemon:  0.4.5+git.7b70fad3.dirty+api0.11.0
> Local: lotus version 0.4.5+git.7b70fad3.dirty


2020-08-15T01:38:30.570Z	INFO	storagemarket_impl	impl/provider.go:197	Handling storage deal proposal!
2020-08-15T01:38:30.606Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventOpen", "proposal CID": "bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma", "state": "StorageDealValidating", "message": ""}
2020-08-15T01:38:30.919Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventDealDeciding", "proposal CID": "bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma", "state": "StorageDealAcceptWait", "message": ""}
2020-08-15T01:38:30.936Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventDataRequested", "proposal CID": "bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma", "state": "StorageDealWaitingForData", "message": ""}
2020-08-15T01:38:32.057Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventDataTransferInitiated", "proposal CID": "bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma", "state": "StorageDealTransferring", "message": ""}
2020-08-15T01:39:00.281Z	INFO	rpc	go-jsonrpc@v0.1.2-0.20200814233340-494a301dc59c/client.go:212	rpc output message buffer	{"n": 2}
2020-08-15T01:39:00.467Z	INFO	rpc	go-jsonrpc@v0.1.2-0.20200814233340-494a301dc59c/client.go:212	rpc output message buffer	{"n": 3}
2020-08-15T01:39:02.169Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventDataTransferCompleted", "proposal CID": "bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma", "state": "StorageDealVerifyData", "message": ""}
2020-08-15T01:39:03.105 INFO filecoin_proofs::api > generate_piece_commitment:start
2020-08-15T01:39:06.874 INFO filecoin_proofs::api > generate_piece_commitment:finish
2020-08-15T01:39:06.874Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventVerifiedData", "proposal CID": "bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma", "state": "StorageDealEnsureProviderFunds", "message": ""}
2020-08-15T01:39:07.055Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventFundsReserved", "proposal CID": "bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma", "state": "StorageDealEnsureProviderFunds", "message": ""}
2020-08-15T01:39:07.105Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventFunded", "proposal CID": "bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma", "state": "StorageDealPublish", "message": ""}
2020-08-15T01:39:07.160Z	INFO	storageadapter	storageadapter/provider.go:60	publishing deal
2020-08-15T01:39:07.167Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventNodeErrored", "proposal CID": "bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma", "state": "StorageDealFailing", "message": "error calling node: publishing deal: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr t01213: escrow balance 280565442861021753 < locked 280565442861021753 + required 6348494473011574 (RetCode=19)"}
2020-08-15T01:39:07.231Z	WARN	providerstates	providerstates/provider_states.go:442	deal bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma failed: error calling node: publishing deal: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr t01213: escrow balance 280565442861021753 < locked 280565442861021753 + required 6348494473011574 (RetCode=19)
2020-08-15T01:39:07.391Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventFundsReleased", "proposal CID": "bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma", "state": "StorageDealFailing", "message": "error calling node: publishing deal: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr t01213: escrow balance 280565442861021753 < locked 280565442861021753 + required 6348494473011574 (RetCode=19)"}
2020-08-15T01:39:07.433Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventFailed", "proposal CID": "bafyreign46c7kq7fah3o55sqmr76p4sn2xzepje6j5yvctflkfk2ecrcma", "state": "StorageDealError", "message": "error calling node: publishing deal: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr t01213: escrow balance 280565442861021753 < locked 280565442861021753 + required 6348494473011574 (RetCode=19)"}

**Comment by ribasushi** [comment]
This should be all fixed in latest ntwk-calibration https://github.com/filecoin-project/lotus/commit/bbb419b4f49356b63
Please update and retry

**Comment by irocn** [comment]
`StorageDealError ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreihesyjfbfzuufpikxplg2jhlbl7vtk5bgwsxpfcnqvwvssfccs7ra"},"State":26,"Message":"deal failed: (State=26) error calling node: publishing deal: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr t01607: escrow balance 70061966869374444 < locked 8764283786075286 + required 70017846372317968 (RetCode=19)","Pro...`

miner id: t01607
lotus version 0.4.6+git.009e14b6.dirty
Miner: t01607
Sector Size: 32 GiB
Byte Power:   4.281 TiB / 22.58 PiB (0.0185%)
Actual Power: 4.28 Ti / 23.2 Pi (0.0180%)
        Committed: 4.594 TiB
        Proving: 4.594 TiB (320 GiB Faulty, 6.80%)
Expected block win rate: 2.5920/day (every 9h15m33s)

Miner Balance: 1453.33117547862660899 FIL
        PreCommit:   53.900284926558759688 FIL
        Locked:      1.731859780765937082 FIL
        Available:   1397.69903077130191222 FIL
Worker Balance: 13430.006355241061770948 FIL
Market (Escrow):  0.291757883464482146 FIL
Market (Locked):  0.291757883464482146 FIL

**Comment by thecreation** [comment]
publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr f023855: escrow balance 65122279311830274 < locked 65037763494742796 + required 121945236599334 (RetCode=19)

**Comment by gh3990** [comment]
Yes, I'm getting a lot of these too :

/root/lotus-miner.log:2020-10-19T04:30:55.429+0200      INFO    markets loggers/loggers.go:19   storage event   {"name": "ProviderEventFailed", "proposal CID": "bafyreibvhxrqd5wjjnackgpoysydmj4mzcbabyxeocgtjw6yf5a5jdxlee", "state": "StorageDealError", "messag                                              e": "error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr f010446: escrow balance 602301964                                              3211520 < locked 6016812665149948 + required 20111880827358 (RetCode=19)"}
/root/lotus-miner.log:2020-10-19T05:06:05.564+0200      INFO    markets loggers/loggers.go:19   storage event   {"name": "ProviderEventFailed", "proposal CID": "bafyreiesgpdyxyws75zdk3jmqeqvjgad4q36hzlumyeuv7mxmafggqerra", "state": "StorageDealError", "messag                                              e": "error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr f010446: escrow balance 596060408                                              1545932 < locked 5953420251922760 + required 20146191394186 (RetCode=19)"}
/root/lotus-miner.log:2020-10-19T05:38:37.223+0200      INFO    markets loggers/loggers.go:19   storage event   {"name": "ProviderEventFailed", "proposal CID": "bafyreia622znvqmctkhh5seyxuvq2gqbogpmnfh46nrrd5berdhtylwupe", "state": "StorageDealError", "messag                                              e": "error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr f010446: escrow balance 596269710                                              8954572 < locked 5953420251922760 + required 80642241546916 (RetCode=19)"}
/root/lotus-miner.log:2020-10-19T06:04:11.723+0200      INFO    markets loggers/loggers.go:19   storage event   {"name": "ProviderEventFailed", "proposal CID": "bafyreihi6plg7y4h5jnkaerfqrjcnauqrj4td2pissxffhosdxsovg4tia", "state": "StorageDealError", "messag                                              e": "error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr f010446: escrow balance 596411446                                              5047692 < locked 5958471134058714 + required 80705134109326 (RetCode=19)"}

**Comment by hawkinggg** [comment]
this issue  happened again, now no deal can be done.

> Oct 18 16:21:48  bafyreie7vnqh3gzeu76vcmpcwrmyguc2nh6ilhvdalmjlcjqjkzdy4qv7m  0       StorageDealError           f1xlpzyo3lsejyafjhv6jc76r3jpfsampttbm4y4a                                               4GiB    0.0000000002136624 FIL    534156   error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr f034258: escrow balance 109011523809471996 < locked 109011064347465292 + required 305056207581832 (RetCode=19)
> Oct 18 16:25:05  bafyreieb7p3nofocyo2uvjdmnejo74gietirl52uljrlxocob54svcj2da  0       StorageDealError           f1xlpzyo3lsejyafjhv6jc76r3jpfsampttbm4y4a                                               4GiB    0.0000000002136588 FIL    534147   error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr f034258: escrow balance 109011523809535350 < locked 109011064347465292 + required 305108606937468 (RetCode=19)
> Oct 18 16:29:39  bafyreidtlaph52a2jvs3lcfnu62askzikenltm3d7cwxy4kktwxh7mc3ou  0       StorageDealError           f1xlpzyo3lsejyafjhv6jc76r3jpfsampttbm4y4a                                               4GiB    0.0000000002136552 FIL    534138   error calling node: publishing deal: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: failed to lock balance: failed to lock provider funds: not enough balance to lock for addr f034258: escrow balance 109011523809535350 < locked 109011064347465292 + required 305175837596854 (RetCode=19)

**Comment by stuberman** [comment]
I think this specific issue has been fixed a long time ago.
