### ISSUE TITLE
Scheduler wants more physical memory....

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#3056]
**Describe the bug**

> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 0; not enough physical memory - need: 130768M, have 128757M

**To Reproduce**
After completing several seals and then getting ready for C2 phase, the machine idles as the scheduler will not allow more tasks.

**Expected behavior**
Tasks should be scheduled as the machine has 128 GB ram and 200 GB swap

**Screenshots**
**Miner log:**
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched.go:352	SCHED Acceptable win: [[] []]
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched.go:286	SCHED 2 queued; 4 open windows
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 0; not enough physical memory - need: 130768M, have 128757M
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 0; not enough physical memory - need: 130768M, have 128757M
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 3; not enough physical memory - need: 143466M, have 128757M
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 3; not enough physical memory - need: 143466M, have 128757M
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 0; not enough physical memory - need: 130768M, have 128757M
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 0; not enough physical memory - need: 130768M, have 128757M
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 3; not enough physical memory - need: 143466M, have 128757M
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 3; not enough physical memory - need: 143466M, have 128757M
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched.go:351	SCHED windows: [{allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]}]
> 2020-08-14T16:41:36.983Z	DEBUG	advmgr	sector-storage/sched.go:352	SCHED Acceptable win: [[] []]

**Version (run `lotus version`):**
`lotus version`

> Daemon:  0.4.4+git.002e972f+api0.10.0
> Local: lotus version 0.4.4+git.002e972f

**Additional context**
`lotus-miner sealing sched-diag`

> {
>   "OpenWindows": [
>     0,
>     0,
>     3,
>     3
>   ],
>   "Requests": [
>     {
>       "Priority": 1024,
>       "Sector": {
>         "Miner": 1213,
>         "Number": 1
>       },
>       "TaskType": "seal/v0/commit/2"
>     },
>     {
>       "Priority": 0,
>       "Sector": {
>         "Miner": 1213,
>         "Number": 3
>       },
>       "TaskType": "seal/v0/precommit/2"
>     }
>   ]
> }
>

**Comment by stuberman** [comment]
Machine is a Ryzen 9 3900xt, 128 GB ram, 200 GB swap partition, x570 mobo, 1080 Ti GPU, 2 TB NVMe, 500 GB NVMe, 50 TB HDD pool with ZFS all processes run on this single machine, including lotus-workers

**Comment by stuberman** [comment]
After reboot on starting miner:

> 2020-08-14T17:08:14.111 INFO filecoin_proofs::api::seal > seal_commit_phase1:finish
> 2020-08-14T17:08:14.156 INFO filcrypto::proofs::api > seal_commit_phase1: finish
> 2020-08-14T17:08:14.172Z	DEBUG	advmgr	sector-storage/sched.go:286	SCHED 2 queued; 2 open windows
> 2020-08-14T17:08:14.172Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 0; not enough physical memory - need: 130929M, have 128757M
> 2020-08-14T17:08:14.173Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 0; not enough physical memory - need: 130929M, have 128757M
> 2020-08-14T17:08:14.173Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 0; not enough physical memory - need: 130929M, have 128757M
> 2020-08-14T17:08:14.173Z	DEBUG	advmgr	sector-storage/sched_resources.go:60	sched: not scheduling on worker 0; not enough physical memory - need: 130929M, have 128757M
> 2020-08-14T17:08:14.173Z	DEBUG	advmgr	sector-storage/sched.go:351	SCHED windows: [{allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]}]
> 2020-08-14T17:08:14.173Z	DEBUG	advmgr	sector-storage/sched.go:352	SCHED Acceptable win: [[] []]
>

**Comment by kernelogic** [comment]
same issue here. i'm guessing it's trying to parallel doing too many sectors.

**Comment by mgoelzer** [comment]
This has been a known issue for a while (eg, #2860, #1844, #2165).  

Empirically, I've found that the physical memory requirement for Lotus to seal a 64 GB sector is around 130-140 GB of physical RAM.  I think maybe this could be a docs fix to clarify what the memory requirements are for sealing.

**Comment by stuberman** [comment]
@mgoelzer 

I am now successfully sealing two 32GiB sectors concurrently with 128GB DDR4 and 200 GB Swap.
I did this by hacking the memory requirements in the scheduler

> ~lotus/extern/sector-storage/sched_resources.go

This line:

> minNeedMem := res.MemReserved + a.memUsedMin + needRes.MinMemory + needRes.BaseMinMemory

**Comment by mgoelzer** [comment]
Good thinking @stuberman!  This is a good tip and I'll point people to this issue the next time I see the question come up.

**Comment by funktafide** [comment]
Im starting to have this issue after upgrading to 0.8.1.  I was previously sealing 2 32GB sectors with 128GB of DDR4 RAM and 200GB swap on v0.8.0.  After upgrading I have started to run in to this issue.  Is the fix still modifying sched_resources.go?

**Comment by f8-ptrk** [comment]
is this resolved?

**Comment by stuberman** [comment]
I have not seen this in a while, so closing.
