### ISSUE TITLE
Miner keeps panic when committing a specific sector

### ISSUE THREAD

**Issue by junyaoren** [filecoin-project/lotus#3057]
**Describe the bug**
Something wrong happens when committing a sector, which causes a panic (shutdown) of the miner. Then it restarts (since we use systemctl start lotus-miner). And the miner would do something (like windowPoSt) and then it tries to commit that sector again. But still, it will panic once again as the previous time. And this goes on and on forever.

And a side effect of this problem is that every-time the miner restarts, it will do a new windowedPoSt, over and over again. My miner ID is t01105, you might be able to see that it submit way too many windowedPoSt on chain (once or twice on each tipset height).

**To Reproduce**
No sure, happened to me three times already, also seen other people having the same problem

**Expected behavior**
1. We should have a way to save the miner from repeating panic (either declare the sector as faulty or remove the sector would be good, but currently neither of them works).  

2. The miner should not do repeating windowedPoSt whenever it restarts (though this issue is minor)

**Screenshots**
2020-08-14T22:06:48.218+0800    DEBUG   stores  stores/index.go:310     not selecting on 1d328abd-826c-4777-a6ea-746ca5480a51, out of space (available: 0, need: 8106750771)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x116ea36]
goroutine 56779 [running]:
github.com/filecoin-project/storage-fsm.(*Sealing).handleCommitting(0xc0120deb00, 0x2da1bc0, 0xc000040090, 0xc02d9d0c10, 0xc0297de270, 0xa, 0x86c, 0x2, 0xc0205c8860, 0x1, ...)
        /root/lotus/extern/storage-fsm/states_sealing.go:324 +0xda6
github.com/filecoin-project/storage-fsm.(*Sealing).Plan.func1(0x2da1bc0, 0xc000040090, 0xc02d9d0c10, 0xc0297de270, 0xa, 0x86c, 0x2, 0xc0205c8860, 0x1, 0x1, ...)
        /root/lotus/extern/storage-fsm/fsm.go:24 +0x81
reflect.Value.call(0x269cc40, 0xc02039a500, 0x13, 0x298de5b, 0x4, 0xc0123c9f70, 0x2, 0x2, 0x540dcf, 0x27925e0, ...)
        /usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x269cc40, 0xc02039a500, 0x13, 0xc02c9d7f70, 0x2, 0x2, 0xc02af7de22, 0xc, 0x1e)
        /usr/local/go/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc02039a450, 0x2da1bc0, 0xc000040090, 0xc02d9d0c10, 0xc02039a460, 0xc0205ca960)
        /root/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200730031800-c3336614d2a7/machine.go:102 +0x2bf
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
        /root/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200730031800-c3336614d2a7/machine.go:100 +0x3da

**Version (run `lotus version`):**
4c5e9614 of ntwk-calibration

**Additional context**

**Comment by yablu** [comment]
Same in 7b70fad.

**Comment by yablu** [comment]
Issue persists in `bfc8f9b`

**Comment by httpservlet** [comment]
I have the same issue with `bfc8f9b`

**Comment by magik6k** [comment]
Should be fixed in https://github.com/filecoin-project/lotus/pull/3101

**Comment by yablu** [comment]
No luck with #3101. Same error.

**Comment by magik6k** [comment]
@yablu Can you share the error message you're getting? It may be a different issue.

**Comment by yablu** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x101d356]
goroutine 949 [running]:
github.com/filecoin-project/storage-fsm.(*Sealing).handleCommitting(0xc011294d10, 0x2da6300, 0xc0001b0d60, 0xc0111229f0, 0xc0003b9e60, 0xa, 0x0, 0x2, 0xc011138a00, 0x1, ...)
	/home/tippyflits/lotus/extern/storage-fsm/states_sealing.go:324 +0xda6
github.com/filecoin-project/storage-fsm.(*Sealing).Plan.func1(0x2da6300, 0xc0001b0d60, 0xc0111229f0, 0xc0003b9e60, 0xa, 0x0, 0x2, 0xc011138a00, 0x1, 0x1, ...)
	/home/tippyflits/lotus/extern/storage-fsm/fsm.go:24 +0x81
reflect.Value.call(0x269f700, 0xc0111229d0, 0x13, 0x29917e9, 0x4, 0xc0009b2f70, 0x2, 0x2, 0x540dcf, 0x2795900, ...)
	/usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x269f700, 0xc0111229d0, 0x13, 0xc01110d770, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc011122850, 0x2da6300, 0xc0001b0d60, 0xc0111229f0, 0xc011122860, 0xc011118a20)
	/home/tippyflits/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200813232949-df9b130df370/machine.go:102 +0x2bf
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
	/home/tippyflits/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200813232949-df9b130df370/machine.go:100 +0x3da``

**Comment by magik6k** [comment]
Looking at lines, it looks like you're running the old code:

https://github.com/filecoin-project/lotus/blob/4c5e961439f75dcb8ddda53174514d333c8c9751/extern/storage-fsm/states_sealing.go#L324

With the new code it should be this - https://github.com/filecoin-project/lotus/blob/next/extern/storage-sealing/states_sealing.go#L332

**Comment by yablu** [comment]
can you describe how to apply this patch in Git? Pretty sure I'm doing it right but would appreciate the confirmation. Thanks!!

**Comment by yablu** [comment]
Sorry... Lotus version is lotus version 0.4.5+git.bfc8f9b7.dirty

**Comment by yablu** [comment]
Quick note...  My directory structure is different you suggest https://github.com/filecoin-project/lotus/blob/next/extern/storage-sealing/states_sealing.go#L332 but my directory structure is https://github.com/filecoin-project/lotus/blob/next/extern/**storage-fsm**/states_sealing.go#L332

**Comment by yablu** [comment]
Should I be checking out the NEXT branch?

**Comment by magik6k** [comment]
A bunch of changes which should address this landed recently
