### ISSUE TITLE
feature: “raw” retrieval method

### ISSUE THREAD

**Issue by mikeal** [filecoin-project/lotus#3060]
**Describe the bug**

Currently, the retrieval protocol in lotus uses Graphsync/Selectors. This is [problematic for retrieving partial graphs](https://github.com/filecoin-project/go-fil-markets/issues/365#issuecomment-673666434) and the most realistic solution is to add a retrieval method that returns the raw piece data which can then be validated by commp.

**Additional context**

This is probably not a launch priority, but that prioritization isn’t my decision to make. One the one hand, this means we can’t retrieve the bitcoin chain data we prepared for launch. At the same time, if use cases involving partial graphs were a high priority for launch then you’d expect to be able to create deals for them using the regular dealflow, but you can’t. The only way to even get this data into the network is using the offline flow.

**Comment by hannahhoward** [comment]
Pieces can potentially be verified incrementally -- the problem is defining some sort of IPLD format to encompass raw piece data. There is an underlying merkle tree there -- it's implicit, but we can I think define some sort of format that can verify it.

**Comment by mikeal** [comment]
> the problem is defining some sort of IPLD format to encompass raw piece 

Every block in the CAR file is already an IPLD structure since it’s a block, we just can’t assume that the links in every block will be sent/traversed. If you just read the CAR file in-order you can re-construct the contents to match. The only sticking point is the CAR header, which is a `dag-cbor` block but doesn’t have its CID encoded in the actual CAR file (yes, this sucks, we already intend to fix it but its a breaking change so it won’t happen until after launch). So all you’d need to do is agree that the first block is the header and should be written as such, and every block after that must be encoded in-order and never traversed.

We can easily re-construct the CAR file if we’re given the header and blocks in order, and then if you have a way to verify piece data incrementally we could just read each increment out of the CAR file as it’s being reconstructed in the client. We shouldn’t need to create an additional IPLD structure over that raw piece data unless I’m missing something (which is absolutely possible).

We’re in the process of documenting how inline blocks are currently encoded into CAR files so we can ensure determinism, but it’s worth noting here just so that when it comes time to implement this we make sure we are consistent.

**Comment by mikeal** [comment]
I think my last message may have layered on some confusion.

What I think you’re saying, is that we have a structure we can use for incremental verification of the raw data, we just need a way to send it. What I’m saying is, you don’t need to send that structure, you just need to send the data to recreate the original file and the client can derive this structure as it re-creates the CAR file.

**Comment by magik6k** [comment]
booster-http now offers raw piece retrieval. Separately, graphsync retrievals now don't really care about retrieving data from pieces exactly as stored, just verify the IPLD dag.
