### ISSUE TITLE
feature: “skip CIDs” in retrieval query

### ISSUE THREAD

**Issue by mikeal** [filecoin-project/lotus#3061]
**Describe the bug**

Graphsync can take a list of CID’s to skip but we haven’t exposed/enabled this feature in the retrieval protocol. This would help with retrieval of certain types of partial graphs, [although not the most common](https://github.com/filecoin-project/go-fil-markets/issues/365#issuecomment-673666434), and could also gain a little efficiency when the client has a known cache state of the graph.

**Additional context**

A few things.

First of all, this is unlikely to be a launch priority since the only way to put partial graphs into the network is by using the offline dealflow. Furthermore, the top use cases we have for partial graphs wouldn’t be solved with this feature, so again, highly unlikely to be a launch priority.

We should think about the best place to put this. Ideally, I’d like to create a schema for a “Selector Query” which encompasses a selector **and** the additional information we tend to use in Graphsync queries like this because we could leverage this for a future version of the CAR format that would create deterministic CAR files of partial graphs by embedding the query used to create them in the CAR header. We could then extend Selectors to be able to query the selector embedded in the CAR file itself, removing the need for out-of-band information in these queries.

Once we know what the timeline would be for lotus to enable this we can figure out how much time we may have for these other improvements and coordinate the work.

**Comment by hannahhoward** [comment]
@mikeal 

A clarification just to make sure we're on the same page -- the skip CIDs list in graphsync just tells the other party not to send the block for a given CID, but it does not stop selector traversal. It's primary intended use is when you want to say "I want you to send me this graph, but I already have this part, so don't send me the blocks in this part". So it's not the way you would deal with missing CIDs in the remote peer (i.e. cause they are absent from the piece).

Graphsync also does have the ability to complete a selector traversal where some CIDs are missing (just not following those paths). However, currently, this will fail a retrieval deal (it's considered "up to the consumer" to determine if missing CIDs represent an actual error -- currently both retrieval and data transfer due treat an incomplete response as an error)

**Comment by mikeal** [comment]
> the skip CIDs list in graphsync just tells the other party not to send the block for a given CID, but it does not stop selector traversal

oh that’s interesting, i had asked about this feature in the context of the selector engine and was told the opposite :)
