### ISSUE TITLE
Make StateAllMinersFaults work again

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#3063]
The `StateAllMinersFaults` API was [commented out](https://github.com/filecoin-project/lotus/blob/002e972f7535a57b615ce138f068bc21a55f2dc4/node/impl/full/state.go#L182) with a "fixme" message.

I guess most probably because of some internal change that made the logic stale, or similar.

We relied on this API for building a Fault index of miners.

**Comment by ribasushi** [comment]
@anorth / @Kubuxu this seems to have been disabled during the [last actors upgrade](https://github.com/filecoin-project/lotus/commit/faebc4c948bf28ce248e0e518dc789c1d9ab5f9d#diff-c47ea93f4cd4e226251ab948791c5d1cR130) . Just flagging you in case it is cheap to bring it back during the current actor-rewire.

**Comment by magik6k** [comment]
This API no longer exists. Actor wrappers can be used to get this information (`chain/actors/..`)
