### ISSUE TITLE
failed to fill whole buffer

### ISSUE THREAD

**Issue by IPFSUnion** [filecoin-project/lotus#3069]
This error occurs many times, please have a check.

{"level":"error","ts":"2020-08-15T08:10:40.508+0800","logger":"sectors","caller":"storage-fsm/fsm.go:26","msg":"unhandled sector error (4095): checkCommit sanity check error (*xerrors.wrapError):\n    github.com/filecoin-project/storage-fsm.(*Sealing).handleCommitFailed\n        /home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/states_failed.go:190\n  - verify seal:\n    github.com/filecoin-project/storage-fsm.(*Sealing).checkCommit\n        /home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/checks.go:158\n  - failed to fill whole buffer\n    github.com/filecoin-project/filecoin-ffi.VerifySeal\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/ipfsunion_filecoin_ffi/proofs.go:52\n    github.com/filecoin-project/sector-storage/ffiwrapper.proofVerifier.VerifySeal\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/sector-storage/ffiwrapper/verifier_cgo.go:97\n    github.com/filecoin-project/storage-fsm.(*Sealing).checkCommit\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/checks.go:148\n    github.com/filecoin-project/storage-fsm.(*Sealing).handleCommitFailed\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/states_failed.go:166\n    github.com/filecoin-project/storage-fsm.(*Sealing).Plan.func1\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/fsm.go:24\n    reflect.Value.call\n    \t/usr/local/go/src/reflect/value.go:460\n    reflect.Value.Call\n    \t/usr/local/go/src/reflect/value.go:321\n    github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3\n    \t/home/ipfsunion/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200730031800-c3336614d2a7/machine.go:102\n    runtime.goexit\n    \t/usr/local/go/src/runtime/asm_amd64.s:1373"} | {"level":"error","ts":"2020-08-15T08:10:40.508+0800","logger":"sectors","caller":"storage-fsm/fsm.go:26","msg":"unhandled sector error (4095): checkCommit sanity check error (*xerrors.wrapError):\n    github.com/filecoin-project/storage-fsm.(*Sealing).handleCommitFailed\n        /home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/states_failed.go:190\n  - verify seal:\n    github.com/filecoin-project/storage-fsm.(*Sealing).checkCommit\n        /home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/checks.go:158\n  - failed to fill whole buffer\n    github.com/filecoin-project/filecoin-ffi.VerifySeal\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/ipfsunion_filecoin_ffi/proofs.go:52\n    github.com/filecoin-project/sector-storage/ffiwrapper.proofVerifier.VerifySeal\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/sector-storage/ffiwrapper/verifier_cgo.go:97\n    github.com/filecoin-project/storage-fsm.(*Sealing).checkCommit\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/checks.go:148\n    github.com/filecoin-project/storage-fsm.(*Sealing).handleCommitFailed\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/states_failed.go:166\n    github.com/filecoin-project/storage-fsm.(*Sealing).Plan.func1\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/fsm.go:24\n    reflect.Value.call\n    \t/usr/local/go/src/reflect/value.go:460\n    reflect.Value.Call\n    \t/usr/local/go/src/reflect/value.go:321\n    github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3\n    \t/home/ipfsunion/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200730031800-c3336614d2a7/machine.go:102\n    runtime.goexit\n    \t/usr/local/go/src/runtime/asm_amd64.s:1373"}
{"level":"error","ts":"2020-08-15T08:10:40.508+0800","logger":"sectors","caller":"storage-fsm/fsm.go:26","msg":"unhandled sector error (4095): checkCommit sanity check error (*xerrors.wrapError):\n    github.com/filecoin-project/storage-fsm.(*Sealing).handleCommitFailed\n        /home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/states_failed.go:190\n  - verify seal:\n    github.com/filecoin-project/storage-fsm.(*Sealing).checkCommit\n        /home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/checks.go:158\n  - failed to fill whole buffer\n    github.com/filecoin-project/filecoin-ffi.VerifySeal\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/ipfsunion_filecoin_ffi/proofs.go:52\n    github.com/filecoin-project/sector-storage/ffiwrapper.proofVerifier.VerifySeal\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/sector-storage/ffiwrapper/verifier_cgo.go:97\n    github.com/filecoin-project/storage-fsm.(*Sealing).checkCommit\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/checks.go:148\n    github.com/filecoin-project/storage-fsm.(*Sealing).handleCommitFailed\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/states_failed.go:166\n    github.com/filecoin-project/storage-fsm.(*Sealing).Plan.func1\n    \t/home/ipfsunion/ipfsunion_release/ipfsunion_lotus_3/extern/storage-fsm/fsm.go:24\n    reflect.Value.call\n    \t/usr/local/go/src/reflect/value.go:460\n    reflect.Value.Call\n    \t/usr/local/go/src/reflect/value.go:321\n    github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3\n    \t/home/ipfsunion/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200730031800-c3336614d2a7/machine.go:102\n    runtime.goexit\n    \t/usr/local/go/src/runtime/asm_amd64.s:1373"}

**Comment by ribasushi** [comment]
This appears to be fixed in the latest ntwk-calibration branch. I'll close this ticket as a duplicate, @IPFSUnion if the problem persists please comment on https://github.com/filecoin-project/lotus/issues/2929 instead ( which I will keep open )
