### ISSUE TITLE
a error happen when user retrieves find

### ISSUE THREAD

**Issue by IPFSUnion** [filecoin-project/lotus#3073]
**Describe the bug**
This errors occurs all the time,please have a check
./lotus client retrieve bafk2bzaceb2zsawibo5bobddqxxrouso6dyardtd6ok6zyx2x54h44vsorou2 ~/a.out
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
> Recv: 0 B, Paid 0 FIL, ClientEventDealProposed (DealStatusWaitForAcceptance)
> Recv: 0 B, Paid 0 FIL, ClientEventDealAccepted (DealStatusAccepted)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelCreateInitiated (DealStatusPaymentChannelCreating)
> Recv: 1.589 KiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusPaymentChannelCreating)
> Recv: 1.589 KiB, Paid 0 FIL, ClientEventLastPaymentRequested (DealStatusPaymentChannelCreating)
> Recv: 1.589 KiB, Paid 0 FIL, ClientEventAllBlocksReceived (DealStatusPaymentChannelCreating)
> Recv: 1.589 KiB, Paid 0 FIL, ClientEventPaymentChannelReady (DealStatusOngoing)
> Recv: 1.589 KiB, Paid 0 FIL, ClientEventLastPaymentRequested (DealStatusFundsNeededLastPayment)
> Recv: 1.589 KiB, Paid 0 FIL, ClientEventSendFunds (DealStatusSendFundsLastPayment)
> Recv: 1.589 KiB, Paid 0.000000000000003254 FIL, ClientEventPaymentSent (DealStatusFinalizing)
> Recv: 1.589 KiB, Paid 0.000000000000003254 FIL, ClientEventComplete (DealStatusCompleted)
2020-08-15T15:16:51.147+0800	ERROR	rpc	ipfsunion_go_jsonrpc/client.go:238	error unmarshaling chan response: failed to parse big string: '"\u003cnil\u003e"'
> Recv: 0 B, Paid %!s(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference), ClientEventOpen (DealStatusNew)
Success

**To Reproduce**
1. Run "lotus client deal ..."
2. Run "lotus client retrieve ..."
2. See the error

**Screenshots**
![image](https://user-images.githubusercontent.com/68763845/90308319-31bb0680-df11-11ea-9b80-f61216597b61.png)

**Version (run `lotus version`):**
Local: lotus version 0.4.5+debug+git.fcd67282.dirty

**Comment by f8-ptrk** [comment]
out dated version

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
