### ISSUE TITLE
panic: strings: negative Repeat count

### ISSUE THREAD

**Issue by caiqingfeng** [filecoin-project/lotus#3074]
when running the cmd "lotus-miner sealing workers", a panic raised:
$ lotus-miner sealing workers
Worker 0, host lotus-miner
	CPU:  [                                                                ] 0 core(s) in use
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat(0x298d140, 0x1, 0xfffffffffffffffc, 0x0, 0x0)
	/usr/local/go/src/strings/strings.go:533 +0x5a9
main.glob..func29(0xc0000cee40, 0x0, 0x0)
	/home/xg/vendors/new/lotus/cmd/lotus-storage-miner/sealing.go:88 +0x8f2
github.com/urfave/cli/v2.(*Command).Run(0x5221a60, 0xc0000ced40, 0x0, 0x0)
	/home/xg/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000682600, 0xc0000cec00, 0x0, 0x0)
	/home/xg/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:427 +0xa68
github.com/urfave/cli/v2.(*Command).startApp(0x5221dc0, 0xc0000cec00, 0x7ffd9f9753e8, 0x7)
	/home/xg/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x68c
github.com/urfave/cli/v2.(*Command).Run(0x5221dc0, 0xc0000cec00, 0x0, 0x0)
	/home/xg/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0xa12
github.com/urfave/cli/v2.(*App).RunContext(0xc000682480, 0x2da1b80, 0xc000130030, 0xc00011a150, 0x3, 0x3, 0x0, 0x0)
	/home/xg/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/home/xg/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc000682480)
	/home/xg/vendors/new/lotus/cli/helper.go:34 +0x7c
main.main()
	/home/xg/vendors/new/lotus/cmd/lotus-storage-miner/main.go:102 +0xa03

$ lotus-miner -v
lotus-miner version 0.4.4+git.4c5e9614

It happens when my miner is in heavy job. The hint of the bug is very clearly pointed to the source code "sealing.go:88":
			ramBar := color.YellowString(strings.Repeat("|", ramBarsRes)) +
				color.GreenString(strings.Repeat("|", ramBarsUsed)) +
				strings.Repeat(" ", int(barCols)-ramBarsUsed-ramBarsRes)
A range protection of string.Repeat parameter is needed here.

**Comment by jennijuju** [comment]
closing this one cuz still happens with v0.7.0.
