### ISSUE TITLE
Error when I entering in "sudo make install" 

### ISSUE THREAD

**Issue by Snow-Sudo** [filecoin-project/lotus#3076]
After entering in make clean && make all, I type in sudo make install which gave me this error: 
           " bash:` go: command not found>
expr: syntax error: unexpected argument ‘14’
install -C ./lotus /usr/local/bin/lotus
install -C ./lotus-storage-miner /usr/local/bin/lotus-storage-miner
install -C ./lotus-seal-worker /usr/local/bin/lotus-seal-worker"

**Comment by oopos** [comment]
you need to install go 1.14 + first.

**Comment by Snow-Sudo** [comment]
> 
> 
> you need to install go 1.14 + first.

I am running go 1.15 and have the error still

**Comment by oopos** [comment]
> > you need to install go 1.14 + first.
> 
> I am running go 1.15 and have the error still

please try with this cmd:  export PATH=$PATH:$(dirname `which go`)

**Comment by oopos** [comment]
export PATH=$PATH:$(dirname \`which go\`)

**Comment by oopos** [comment]
please try with this cmd:  sudo export PATH=$PATH:$(dirname \`which go\`)

> > you need to install go 1.14 + first.
> 
> I am running go 1.15 and have the error still

please try with this cmd:     sudo export PATH=$PATH:$(dirname \`which go\`)

**Comment by oopos** [comment]
> > you need to install go 1.14 + first.
> 
> I am running go 1.15 and have the error still
please try with this cmd:
sudo -s
godir=[YOUR go exec PATH]  for eg. /usr/local/go/bin
# godir=$(dirname \`which go\`)
export PATH=$PATH:$godir
make install

**Comment by Snow-Sudo** [comment]
> > > you need to install go 1.14 + first.
> > 
> > 
> > I am running go 1.15 and have the error still
> > please try with this cmd:
> > sudo -s
> > godir=[YOUR go exec PATH]  for eg. /usr/local/go/bin
> 
> # godir=$(dirname `which go`)
> 
> export PATH=$PATH:$godir
> make install

Seems like this error is a bug based on this post with the same issue https://github.com/filecoin-project/lotus/issues/2207. Now I am trying to join the testnet, but there are no steps listed on how to set the environment variables for 
>IPFS_GATEWAY="https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/"
Sorry I'm not familiar with using Linux

**Comment by dkkapur** [comment]
This seems to still be an issue - ran into the problem today and its seems to be because `go` is installed as a user, but running `make install` as sudo fails when root doesn't know where `go` is. Thanks for your help so far @ribasushi, any suggestions on where to go from here?

**Comment by dkkapur** [comment]
Viable workarounds for people that may hit this in the future: 

- run the `sudo make install` as a `sudo env PATH-"$PATH" make install` in case your $PATH is updated and includes the `go` dir.
- add `go` to `/root/.bashrc` with `export PATH-/usr/local/go/bin::$PATH`
