### ISSUE TITLE
How to setup environment variable 

### ISSUE THREAD

**Issue by Snow-Sudo** [filecoin-project/lotus#3080]
I'm trying to join the testnet and it says to put in 

>IPFS_GATEWAY="https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/"
>
and set it as the environment variable. The guide has no steps to set it up. 
Is there someone who can provide a guide?

**Comment by arajasek** [comment]
How about [this](https://askubuntu.com/questions/58814/how-do-i-add-environment-variables)?

We'll add a step to the documentation, though.

**Comment by Snow-Sudo** [comment]
> How about [this](https://askubuntu.com/questions/58814/how-do-i-add-environment-variables)?
> 
> We'll add a step to the documentation, though.

Thanks I figured out how to set it as the environment variable but in the next it says to 

Start the daemon using the default configuration in ./build.

I thought the line below says lotus daemon which I thought was a command you type into the terminal but the terminal outputted
> panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.2()
	/home/miner1/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.17.3/internal/handshake/unsafe.go:26 +0x205
>

I don't have a clue where to go from there. Sorry, I'm not familiar with Linux.
﻿

**Comment by arajasek** [comment]
Can you share the output of `go version`?

**Comment by Snow-Sudo** [comment]
>miner1@miner1:~/lotus$ go version 
  go version go1.15 linux/amd64
>
here it is

**Comment by johnnymatthews** [comment]
I'm getting a similar panic:

```bash
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState
goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.2()
	/home/infra/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.17.3/internal/handshake/unsafe.go:26 +0x205
```

Also running Go 1.15:

```bash
$ go version
go version go1.15 linux/amd64
```

Running through a completely clean install. Fresh Ubuntu installation, installed the [dependencies listed](https://lotu.sh/en+setup-troubleshooting).

**Comment by ribasushi** [comment]
@Snow-Sudo @johnnymatthews I believe this is a go1.15 bug, for the time being please downgrade to go 1.14.7

Reference: https://github.com/ipfs/go-ipfs/issues/7597 / https://github.com/syncthing/syncthing/issues/6889

**Comment by johnnymatthews** [comment]
You read my mind @ribasushi! Downgrading now.

**Comment by Snow-Sudo** [comment]
Downgraded go and now 
>lotus daemon
>
works.
