### ISSUE TITLE
precommit2 panic after restart

### ISSUE THREAD

**Issue by yaohcn** [filecoin-project/lotus#3087]
miner restart when one sector doing precommit2(already generate sc-02-data-tree-c data), the sector will panic and never return, hang there all the time.
```shell
[2020-08-16][14:17:18.353958205][INFO] seal_pre_commit_phase2: start
[2020-08-16][14:17:18.354062241][INFO] replicate_phase2
[2020-08-16][14:17:18.354165220][INFO] generating tree c using the GPU
[2020-08-16][14:17:18.354184434][INFO] Building column hashes
[2020-08-16][14:21:12.354232570][INFO] persisting base tree_c 2/8 of length 153391689
thread '<unnamed>' panicked at 'failed to flatten and write store: Bad file descriptor (os error 9)', /root/.cargo/git/checkouts/rust-fil-proofs-e4bb77f794f84c40/4bcf735/storage-proofs/porep/src/stacked/vanilla/proof.rs:1465:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2020-08-16][14:21:14.972882285][INFO] persisting base tree_c 1/8 of length 153391689
thread '<unnamed>' panicked at 'failed to flatten and write store: Bad file descriptor (os error 9)', /root/.cargo/git/checkouts/rust-fil-proofs-e4bb77f794f84c40/4bcf735/storage-proofs/porep/src/stacked/vanilla/proof.rs:1465:29
```
```shell
root@miner1:~# lm sealing jobs|grep -w PC2
3   12094   11     ACZH_001  PC2   2h10m56.1s
1   12168   22     ACZH_002  PC2   2h10m50.4s
1   12179   44     ACZH_009  PC2   2h10m49.7s
3   12183   33     ACZH_017  PC2   2h10m49.4s
1   12222   44     ACZH_011  PC2   2h10m45.1s
```
after remove sc-02-data-tree-c data, and restart worker, it get back normal.

**Comment by yaohcn** [comment]
There are two problems:
1. if there are old sc-02-data-tree-c data, precommit2 will panic
2. when rust side panic, it never returns to go side.

**Comment by icodeface** [comment]
same issue

**Comment by yydfjt** [comment]
We got the same issue，need clean before start pc2

**Comment by magik6k** [comment]
Please reopen if you are able to reproduce this with latest code

**Comment by William8Work** [comment]
Just upgraded from v1.1.2 to v1.1.3 and got this problem.

2020-11-15T14:52:20.308-0800	INFO	stores	stores/remote.go:221	Fetch http://10.0.0.153:3456/remote/cache/s-t08399-274 -> /media/lotus/worker/cache/fetching/s-t08399-274
thread '<unnamed>' panicked at 'failed to flatten and write store: Bad file descriptor (os error 9)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.3.0/src/stacked/vanilla/proof.rs:580:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.3.0/src/stacked/vanilla/proof.rs:502:34
