### ISSUE TITLE
`lotus-miner --actor XXX info` shows incorrect sector information

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/lotus#3091]
**Describe the bug**
This is a fairly minor bug, but I noticed that running `lotus-miner info` locally gives different results than running `lotus-miner --actor XXX info` on a different lotus node.  The sector count is always zero in the latter case.

**To Reproduce**
From `t01309` node:

```
$ lotus-miner info
Miner: t01309
[..deleted...]

Sectors:
	Total: 3
	Proving: 3
```

From a different lotus-miner node:

```
$ lotus-miner --actor t01309 info
Miner: t01309
[...deleted...]

Sectors:
	Total: 0
```

**Expected behavior**
Output of `lotus-miner --actor t01309 info` should show 3 sectors instead of 0.

**Version (run `lotus version`):**
Both nodes are running the same version:

```
$ lotus version
Daemon:  0.4.4+git.4c5e9614+api0.10.0
Local: lotus version 0.4.4+git.4c5e9614
```

**Comment by f8-ptrk** [comment]
is this resolved? `lotus-miner --actor t01309 info
Chain: [sync ok] [basefee 574.646 pFIL]
Miner: f01309 (32 GiB sectors)
Power: 0  / 6.48 Ei (0.0000%)
	Raw: 0 B / 6.481 EiB (0.0000%)
	Committed: 0 B
	Proving: 0 B
Below minimum power threshold, no blocks will be won
Deals: 0, 0 B
	Active: 0, 0 B (Verified: 0, 0 B)

Miner Balance:    0
      PreCommit:  0
      Pledge:     0
      Vesting:    0
      Available:  0
Market Balance:   0
       Locked:    0
       Available: 0
Worker Balance:   19.076 FIL
Total Spendable:  19.076 FIL

Sectors:
	Total: 4138
	Proving: 3854
	GetTicket: 4
	PreCommit1: 3
	PreCommit2: 24
	WaitSeed: 11
	Committing: 5
	CommitWait: 1
	FinalizeSector: 3
	Removed: 233
`

resolved

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
