### ISSUE TITLE
Possibly spurious reachability error message

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/lotus#3092]
**Describe the bug**
`lotus-miner info all` gives this error:

```
#: Reachability
2020-08-17T01:36:22.970Z	WARN	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/client.go:406	unmarshaling failed	{"message": "{\"Reachability\":1,\"PublicAddr\":\"/ip4/3.214.216.90/tcp/44365\"}"}
ERROR: RPC client error: unmarshaling result: json: cannot unmarshal string into Go struct field NatInfo.PublicAddr of type multiaddr.Multiaddr
```

It doesn't look like a reachability problem; looks more like a string just needs to be parsed into a multiaddr somewhere before setting a struct field.

**To Reproduce**
I just ran `lotus-miner info all` on a normal, working miner node.

**Expected behavior**
The WARN message in `lotus-miner info all` output was unexpected.

**Version (run `lotus version`):**
```
$ lotus version
Daemon:  0.4.4+git.4c5e9614+api0.10.0
Local: lotus version 0.4.4+git.4c5e9614
```

**Comment by rjan90** [comment]
The `lotus-miner info all` is working properly on newer version of Lotus, so I think this issue can be closed now? #rengjøring

**Comment by Reiers** [comment]
**Issue is solved in newer versions of Lotus.**

Closing this ticket.
