### ISSUE TITLE
PoSt chain commitment xxx too far in the past

### ISSUE THREAD

**Issue by wellhealth** [filecoin-project/lotus#3095]
what happed about this error ，i lost all power. 

Daemon:  0.4.5+git.5dd5bfd6.dirty+api0.11.0
Local: lotus version 0.4.5+git.5dd5bfd6.dirty

2020-08-17T07:35:11.947+0800    INFO    storageminer    storage/wdpost_run.go:429       submitting window PoSt  {"elapsed": 1690.080855603}
2020-08-17T07:35:11.950+0800    ERROR   storageminer    storage/wdpost_run.go:54        submitPost failed: pushing message to mpool:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).submitPost
        /root/golang/gopath/src/github.com/filecoin-project/my-lotus/storage/wdpost_run.go:472
  - estimating gas used: message execution failed: exit 16, reason: PoSt chain commitment 9415 too far in the past, must be after 9417 (RetCode=16)
2020-08-17T07:35:11.950+0800    ERROR   storageminer    storage/wdpost_run.go:28        TODO

**Comment by rjan90** [comment]
Setting a seperate addres for windowPoSt's messages should fix this error: https://filecoinproject.slack.com/archives/C0179RNEMU4/p1599588010095400. So this issue can probably be closed now #rengjøring

**Comment by Reiers** [comment]
**Solution provided by @rjan90** 
Read more about control addresses here: https://lotus.filecoin.io/docs/storage-providers/addresses/

Closing ticket. 

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
