### ISSUE TITLE
Handle errors in PoST submission

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#310]
I've hit this (probably because PoST was submitted right at the edge of proving period and after being finally processed, it fell into next proving period).

It causes the post submission to go completly out of wack.

https://github.com/filecoin-project/lotus/blob/0c6fcde9c4a3ed177f2be9f94740bbd0e29f0a99/storage/post.go#L156-L159

**Comment by magik6k** [comment]
New logic handles this
