### ISSUE TITLE
How to open ~/.lotusstorage/config.toml 

### ISSUE THREAD

**Issue by Snow-Sudo** [filecoin-project/lotus#3116]
I'm looking at this guide https://docs.lotu.sh/en+lotus-seal-worker#setting-up-the-storage-miner-43280 and it says to open up ~/.lotusstorage/config.toml but doesn't tell you how to actually open it. Is there like a command I put in order to find the API Field ?

[API] ListenAddress = "/ip4/127.0.0.1/tcp/2345/http" RemoteListenAddress = "127.0.0.1:2345"

This was the API Field listed on the guide

**Comment by stuberman** [comment]
use a text editor like `nano ~/.lotusstorage/config.toml`

**Comment by arajasek** [comment]
`vi`

**Comment by Snow-Sudo** [comment]
I get this error when trying to save ~/.lotusstorage/config.toml using vi 

>"~/.lotusstorage/config.toml" E212: Can't open file for writing
