### ISSUE TITLE
~/.lotusstorage/config.toml can't be saved with vi

### ISSUE THREAD

**Issue by Snow-Sudo** [filecoin-project/lotus#3121]
I'm trying to set up the storage miner and when typing in 
>miner@miner:~/lotus$ vi ~/.lotusstorage/config.toml
>
it opens the editor and I paste in 
>[API]
>ListenAddress = "/ip4/127.0.0.1/tcp/2345/http"
>RemoteListenAddress = "127.0.0.1:2345"
>
but it won't let me save the edits. 

**Version**

The output of `./lotus --version`.
>miner@miner:~/lotus$ lotus --version
>lotus version 0.4.1+git.8c516df8

**Comment by stuberman** [comment]
What is the ownership of the file?

`ls -Alh ~/lotus$ vi ~/.lotusstorage/config.toml`

If root - then `sudo nano ~/lotus$ vi ~/.lotusstorage/config.toml`

Then Control-o to save and Control-x to exit

**Comment by Snow-Sudo** [comment]
@stuberman 
>miner@miner:~$ ls -Alh ~.lotusstorage/config.toml
ls: cannot access '~.lotusstorage/config.toml': No such file or directory
> 
File apparently does not exist. Is there a way to get the file?

**Comment by stuberman** [comment]
If you initialized your lotus-miner it should be created.
I like to use `locate -i config.toml` to find all of them maybe in a different path

**Comment by arajasek** [comment]
@Snow-Sudo If you're running on `ntwk-calibration`, this file will be called `~/.lotusminer/config.toml`. The documentation on lotu.sh is for the `master` branch, and will be updated when space race goes live.
