### ISSUE TITLE
Reserving too much space

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#3124]
My miner seems reserving too much space and it's causing errors like
ERROR	advmgr	sector-storage/sched.go:309	trySched(1) req.sel.Ok error: finding best alloc storage:
    github.com/filecoin-project/sector-storage.(*allocSelector).Ok
        /mnt/ipfs/lotus_src/extern/sector-storage/selector_alloc.go:49
  - no good path found:
    github.com/filecoin-project/sector-storage/stores.(*Index).StorageBestAlloc
        /mnt/ipfs/lotus_src/extern/sector-storage/stores/index.go:405

The output of storage list has this
8d0798d1-5bfa-418a-875f-543795485cc6:
	[##################################****************] 1.557 TiB/1.557 TiB 100%
	Unsealed: 2; Sealed: 1; Caches: 1; Reserved: 483.2 GiB
	Weight: 10; Use: Seal 
	URL: http://127.0.0.1:3456/remote (latency: 600µs)

And the sectors list has these (3 in PC1, which I think it's too many).
0: Proving    sSet: YES active: YES tktH: 5072  seedH: 6662  deals: [0]
1: Proving    sSet: YES active: YES tktH: 6381  seedH: 7972  deals: [0]
2: Proving    sSet: YES active: YES tktH: 7234  seedH: 8827  deals: [0]
3: Proving    sSet: YES active: YES tktH: 8074  seedH: 9667  deals: [0]
4: Proving    sSet: YES active: YES tktH: 8915  seedH: 10509 deals: [0]
5: Proving    sSet: YES active: YES tktH: 9756  seedH: 11345 deals: [0]
6: Committing sSet: NO  active: NO  tktH: 10595 seedH: 12193 deals: [0]
7: PreCommit1 sSet: NO  active: NO  tktH: 0     seedH: 0     deals: [5974 0 0 0 0 6004 0 0 0]
8: PreCommit1 sSet: NO  active: NO  tktH: 0     seedH: 0     deals: [6195 6215 0 0 0 0 0 0 0]
9: PreCommit1 sSet: NO  active: NO  tktH: 0     seedH: 0     deals: [6441 0 0 0 0 0 0 0 0 0 0 6513 0 0 0 0 0 0 0]

**Comment by cwhiggins** [comment]
there is definitely something here that needs to be addressed some how, this might not be an issue under normal operation, with good planning on part of the miner, but as soon as something goes wrong and there is any sort of bottleneck, miners get locked up. Then I have not even been able to get the miner to complete tasks again, as to many PC1 tasks are sent to a worker at once and the harddrive runs out space. Miner becomes useless

**Comment by kernelogic** [comment]
Still seeing this error after a day. No way to control PC1 sectors.
