### ISSUE TITLE
deadlock in the scheduler

### ISSUE THREAD

**Issue by BigOceanGG** [filecoin-project/lotus#3128]
The state of all tasks of the miners have been stagnated, and the data cannot be continued to be sealed at present,Looks like it's deadlock in the scheduler

Daemon: 0.4.5+git.bbb419b4+api0.11.0

**Comment by arajasek** [comment]
Fixed in #3112

**Comment by BigOceanGG** [comment]
This deadlock is a little different
(https://app.slack.com/client/TEHTVS1L6/C017CCH1MHB/thread/C017CCH1MHB-1597643221.375900)

**Comment by BigOceanGG** [comment]
@arajasek This deadlock is a little different
(https://app.slack.com/client/TEHTVS1L6/C017CCH1MHB/thread/C017CCH1MHB-1597643221.375900)
