### ISSUE TITLE
deadlock in the scheduler

### ISSUE THREAD

**Issue by BigOceanGG** [filecoin-project/lotus#3133]
The state of all tasks of the miners have been stagnated, and the data cannot be continued to be sealed at present,Looks like it's deadlock in the scheduler

Daemon: 0.4.5+git.bbb419b4+api0.11.0

This deadlock is a little different
(https://app.slack.com/client/TEHTVS1L6/C017CCH1MHB/thread/C017CCH1MHB-1597643221.375900)

**Comment by BigOceanGG** [comment]
@magik6k Has this problem been solved?

**Comment by f8-ptrk** [comment]
people would have experienced this since august if it still were an issue - resolved?

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
