### ISSUE TITLE
Got expired ticket, sector stucked

### ISSUE THREAD

**Issue by IPFSMain-Official** [filecoin-project/lotus#3141]
in `handlePreCommit1 -> getTicket`:
```golang
pci, err := m.api.StateSectorPreCommitInfo(ctx.Context(), m.maddr, sector.SectorNumber, tok)
if err != nil {
	return nil, 0, xerrors.Errorf("getting precommit info: %w", err)
}

if pci != nil {
	ticketEpoch = pci.Info.SealRandEpoch
}
```
Always get the PreCommit message on the chain to get the ticket, but if the ticket has expired, can I get a new ticket?

**Sectors status**

9.	2020-08-14 21:33:41 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	commit check error: invalid proof (compute error?)
10.	2020-08-15 10:17:13 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
11.	2020-08-17 08:56:52 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
12.	2020-08-17 10:40:35 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
13.	2020-08-17 14:15:58 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
14.	2020-08-17 14:16:00 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	verify seal: failed to fill whole buffer
15.	2020-08-17 14:17:00 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
16.	2020-08-17 17:51:34 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
17.	2020-08-17 18:01:54 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
18.	2020-08-17 23:52:01 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"...","TicketValue":"bCB5VrEOZ79Mg9L+u1s/UgtQShbNOIwQjgMwOE2A8AA=","TicketEpoch":377}}
19.	2020-08-18 02:02:35 +0800 CST:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcb53gzu4cf2c23jx5tlmur73cbpw73g7rkk5nmvbajq7mngac4biw"},"Unsealed":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}}
20.	2020-08-18 02:02:35 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired: ticket expired: seal height: 1277, head: 11691
21.	2020-08-18 02:03:35 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
22.	2020-08-18 07:39:18 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"...","TicketValue":"bCB5VrEOZ79Mg9L+u1s/UgtQShbNOIwQjgMwOE2A8AA=","TicketEpoch":377}}
23.	2020-08-18 09:09:42 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
24.	2020-08-18 11:10:32 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
25.	2020-08-18 11:45:45 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
26.	2020-08-18 12:00:04 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
27.	2020-08-18 12:02:22 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
28.	2020-08-18 14:51:30 +0800 CST:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcb53gzu4cf2c23jx5tlmur73cbpw73g7rkk5nmvbajq7mngac4biw"},"Unsealed":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}}
29.	2020-08-18 14:51:30 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired: ticket expired: seal height: 1277, head: 13229
30.	2020-08-18 14:52:30 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
31.	2020-08-18 14:52:30 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated
32.	2020-08-18 14:53:30 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
33.	2020-08-18 14:53:30 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated
34.	2020-08-18 14:54:30 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
35.	2020-08-18 14:54:30 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated
36.	2020-08-18 14:55:30 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
37.	2020-08-18 14:55:30 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated
...always: sectorNumber is allocated

**Comment by f8-ptrk** [comment]
looped sectors due to expired tickets should be resolved

#antidisestablishatarianism
