### ISSUE TITLE
Error received when typing in lotus-storage-miner-info

### ISSUE THREAD

**Issue by Snow-0** [filecoin-project/lotus#3148]
I typed in 
> lotus-storage-miner-info 
>
I received this error 
>2020-08-18T15:43:16.218-0400	INFO	main	lotus-storage-miner/run.go:81	Checking full node sync status
Worker 0: Target: [bafy2bzacedjyz6luf7do7pfm3uldfekz5pshmtejqqq55ot653qloacgt4ih4]	State: complete	Height: 210199
Done!
2020-08-18T15:43:16.220-0400	WARN	main	lotus-storage-miner/main.go:94	repo at '~/.lotusstorage' is not initialized, run 'lotus-storage-miner init' to set it up:
    main.glob..func21
        /home/miner/lotus/cmd/lotus-storage-miner/run.go:100

>
Lotus Version
>miner@miner:~$ Lotus Version 
>Daemon:  0.4.1+git.8c516df8+api0.6.0
>Local: lotus version 0.4.1+git.8c516df8

**Comment by rjan90** [comment]
I think this issue can be closed, as there is no `lotus-storage-miner-info` command in the stock lotus? #rengjøring
