### ISSUE TITLE
Disallow naked sends/transfers (method num = 0) to singleton builtin accounts

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#3149]
Right now it's possible for account actors to perform naked sends (method num = 0) to singleton actors (e.g. system, market, power, etc.), from which the funds will never be rescued (unless a future fork/protocol change unlocks/returns them).

At least in Ethereum there is the *minuscule* chance that one can crack the private key for account `0x000000...00`

But in Filecoin, singleton actors don't even have private keys associated to them. So these funds have nil chance of being released, ever.

Is there a use case behind allowing method_num = 0 messages to singleton actors? If not, I suggest we explicitly reject these messages.

Fun fact: [account `0x000000....00`](https://etherscan.io/address/0x0000000000000000000000000000000000000000) in Eth1 has 3M USD in balance from transfers made, most certainly, by mistake (or poor UX of wallets). Let's remove this footgun from our system.

**Comment by anorth** [comment]
This issue really belongs in https://github.com/filecoin-project/specs/issues. I happened to see it here by chance. The discussion is not localised to Lotus implementers. If/when the spec changes, then we can task Lotus with updating to match.

**Comment by anorth** [comment]
Moved to https://github.com/filecoin-project/specs/issues/1069
