### ISSUE TITLE
How to control the size of .lotusworker folder?

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#3153]
Currently my .lotusworker folder is on NVME but the cache folder inside keeps growing. It is at 1.1TB now and my NVME is 97% full.

How does it manage the disk usage? Or should I move this folder to the much bigger mechanical HDD raid?

**Comment by BATTLEROYALXS** [comment]
Hello same problem here...

**Comment by f8-ptrk** [comment]
not a lotus issue, the worker needs as much space as it needs to process sectors

#antidisestablishatarianism
