### ISSUE TITLE
Getting tx's method name

### ISSUE THREAD

**Issue by raynaudoe** [filecoin-project/lotus#3173]
For an integration project I need to get a method's name corresponding to the value in `Message.Method`. 

If I do: 

First, get the actor:
`actor, _ := api.StateGetActor(context.Background(), msg.Message.From, filTypes.EmptyTSK)`

Then by using `actor.Code` I switch-case between the available methods that match to the actor's code.
```
switch actor.Code {
	case builtin.InitActorCodeID:
		method = builtin.MethodsInit
	case builtin.CronActorCodeID:
		method = builtin.MethodsCron
	case builtin.AccountActorCodeID:
		method = builtin.MethodsMultisig
...
}
```
I get the information I need but is very slow.

Since this procedure must be done for every message on a TipSet, this leads to timeout errors (from the integration project side) when requesting such information. 

Maybe there's another way on FileCoin's api to get the corresponding method string that is actually faster ?

**Comment by arajasek** [comment]
I don't think there is, unfortunately -- Any Filecoin API that returned the string would have to do the same thing you're already doing, I think.
