### ISSUE TITLE
[calibration] misleading import

### ISSUE THREAD

**Issue by fadeAce** [filecoin-project/lotus#3188]
https://github.com/filecoin-project/lotus/blob/885f357c5980fb3f403bcc9595c4b8fb69090b62/extern/storage-sealing/nullreader.go#L7

why import storage-fsm here, storage-sealing is storage-fsm itself , use source tree to replace mod & use mod again ?

**Comment by fadeAce** [comment]
AND here : https://github.com/filecoin-project/lotus/blob/885f357c5980fb3f403bcc9595c4b8fb69090b62/go.mod#L41
why quote unused mod in go.mod

**Comment by fadeAce** [comment]
what I do suggest is to put storage-fsm to submodule of calibration lotus mod , if still go with that how to do with new fresh functional upgrade , will it be appears in filecoin-project/storage-fsm repo or appears here , how to do with future comparision or reflict

**Comment by fadeAce** [comment]
if I wrote an application to use ffiwrapper, it means that I have to import lotus first , because it's related to sector-storage/ffiwrapper and now it's source code of lotus/extern , this change may has breaked the principle of decoupling

**Comment by f8-ptrk** [comment]
is this resolved?

**Comment by rjan90** [comment]
Closing this issue since the first question seems like it has been resolved.
