### ISSUE TITLE
P1 shouldn't be restarted after failure to retry C2 several times.

### ISSUE THREAD

**Issue by DecentralTech** [filecoin-project/lotus#3195]
**Describe the bug** 
`We found that if one sector has not completed commit2 for too long, the seed it obtained in commit1 will expire. So it will retry commit2 multiple times, but each time it fails. Then this sector will do precommit again, but then it will prompt "sector number is allocated". We tried to declare these sectors as faults, but it didn't work. These sectors keep retrying commit and precommit. This may be some flaws in the process design.` 

**To Reproduce** 
`Steps to reproduce the behavior: when you fail to finish C2 and retry several times, P1 will be restarted. However, it is impossible to redo P1 at this moment. And the status of sector cannot be altered, either. `

**Expected behavior** **Version (run `lotus version`):** 
`lotus version 0.4.6+git.5c6b99c9`

**Comment by f8-ptrk** [comment]
duplicate #3194

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
