### ISSUE TITLE
Extend deal filtering to retrieval deals

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#3204]
Miners should be able to reject retrieval deals based on filtering logic too.

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and is being completely removed from the code here:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
