### ISSUE TITLE
Setting the level of log systems is broken

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#3216]
**Describe the bug**
Calling `lotus log set-level --system <system_name> <level>` does not actually change the level. This is the same for `lotus-miner`.

**Expected behavior**
The system log level should change.

**Version (run `lotus version`):**
Daemon:  0.4.6+git.a60c6e0b+api0.11.0
Local: lotus version 0.4.6+git.a60c6e0b

**Comment by whyrusleeping** [comment]
Works for me for lotus, i know lotus-miner has some issues though. I think it ends up setting the levels on the lotus daemon instead of the miner right now
