### ISSUE TITLE
Failed with message  Failed: bls signature failed to verify when using a QueryAsk to check miner connectivity.

### ISSUE THREAD

**Issue by ffteng46** [filecoin-project/lotus#3217]
**Describe the bug**
when using a QueryAsk to check my miner connectivity of t01694,the result is Failed: bls signature failed to verify,My lotus-miner daemon receives this remote QueryAsk clearly.But it's good when i run command "lotus client query-ask t01694" locally.
**To Reproduce**
1. Run 'Send QueryAsk in https://calibration.spacerace.filecoin.io/check with miner id t01694'
2. See error
Failed: bls signature failed to verify
Follow these guidelines to improve your connectivity

**Expected behavior**
With the response message of success.
**Screenshots**
![image](https://user-images.githubusercontent.com/17234469/90862871-ac2bd080-e3c0-11ea-939e-f37e8e9e3bb9.png)
![image](https://user-images.githubusercontent.com/17234469/90863208-412ec980-e3c1-11ea-9b88-1740d1aa0b5e.png)
![image](https://user-images.githubusercontent.com/17234469/90863388-84893800-e3c1-11ea-9b63-31e2372d1976.png)
![image](https://user-images.githubusercontent.com/17234469/90863440-9d91e900-e3c1-11ea-8274-0d2a63ced07b.png)
when i click Send QueryAsk button,lotus-miner daemon receives this invokation 
![image](https://user-images.githubusercontent.com/17234469/90863657-06796100-e3c2-11ea-8cb5-ad50506c3bf6.png)

**Version (run `lotus version`):**
Daemon:  0.4.6+git.5c6b99c9+api0.11.0
Local: lotus version 0.4.6+git.5c6b99c9
**Additional context**

**Comment by ffteng46** [comment]
A few people meet this bug.Tt's not response to connectivity.

**Comment by Reiers** [comment]
Hi @ffteng46 

Thanks for the report. The issue is outdated, space race was a long time ago. 

If you are still experiencing problems - please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you !

**Comment by Shekelme** [comment]
s1@s1:~$ lotus client query-ask f01222595
ERROR: bls signature failed to verify
-_-
