### ISSUE TITLE
The chain cannot synchronize new blocks

### ISSUE THREAD

**Issue by shishi614** [filecoin-project/lotus#3224]
Chain shows that synchronization is complete. New blocks have not been synchronized.  Ok after restarting. Then again
![image](https://user-images.githubusercontent.com/20469171/90914922-4451a600-e411-11ea-97e1-ea28f731dfe4.png)
![image](https://user-images.githubusercontent.com/20469171/90914979-56cbdf80-e411-11ea-8719-40ff4a2ea5dd.png)
![image](https://user-images.githubusercontent.com/20469171/90915170-a8746a00-e411-11ea-8895-8285a994bc1c.png)
![image](https://user-images.githubusercontent.com/20469171/90915191-b2966880-e411-11ea-9cb1-5109937c4f28.png)
I had that problem in multiple versions.One version is Lotus Version 0.4.6+ Gt.49898824, I've been struggling with this question for days

**Comment by rjan90** [comment]
I think this issue can be closed now, as the fixed has been merged. #rengjøring

**Comment by Reiers** [comment]
**Fix Merged.**

Closing ticket.
