### ISSUE TITLE
Retrieval Deals all went to error state upon reboot

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#3228]
**Describe the bug**
I had to reboot my Ubuntu 20.04 server (Lotus down for 10 minutes) and when Lotus came back up all retrieval deals were in error state

**To Reproduce**
1. Rebooted server and ran `make clean deps all install` to update the scheduler file "sched_resources.go"
2. See error

**Expected behavior**
I expected the retrieval deals to remain in prior state (DealStatusUnsealing) or update to "DealStatusActive?"

**Screenshots**
`lotus-miner retrieval-deals list`

> Receiver                       DealID Payload   State       PricePerByte BytesSent Message
> 12D3KooWF4wwHVz4QGye3Q59gMHutx9ir1J9CpfyDhgNZGv9c2bw 696   ...goz3m436 DealStatusErrored 2       0     Context Cancelled
> 12D3KooWF4wwHVz4QGye3Q59gMHutx9ir1J9CpfyDhgNZGv9c2bw 760   ...y6hwsagq DealStatusErrored 2       0     Context Cancelled
> 12D3KooWF4wwHVz4QGye3Q59gMHutx9ir1J9CpfyDhgNZGv9c2bw 764   ...dj3l4epa DealStatusErrored 2       0     Context Cancelled
> 12D3KooWF4wwHVz4QGye3Q59gMHutx9ir1J9CpfyDhgNZGv9c2bw 569   ...6h6k6nu2 DealStatusErrored 2       0     Context Cancelled
> 12D3KooWF4wwHVz4QGye3Q59gMHutx9ir1J9CpfyDhgNZGv9c2bw 635   ...si4oit4o DealStatusErrored 2       0     Context Cancelled
> 12D3KooWF4wwHVz4QGye3Q59gMHutx9ir1J9CpfyDhgNZGv9c2bw 637   ...ioic2xzq DealStatusErrored 2       0     Context Cancelled
> 12D3KooWF4wwHVz4QGye3Q59gMHutx9ir1J9CpfyDhgNZGv9c2bw 689   ...ayz3fyog DealStatusErrored 2       0     Context Cancelled

**Version (run `lotus version`):**
`lotus version`

> Daemon:  0.4.6+git.5c6b99c9.dirty+api0.11.0
> Local: lotus version 0.4.6+git.5c6b99c9.dirty

**Additional context**

See this thread https://filecoinproject.slack.com/archives/CEGN061C5/p1597983755055100?thread_ts=1597983710.055000&cid=CEGN061C5 
And this thread https://filecoinproject.slack.com/archives/CEGN061C5/p1598032670078500

**Unsealed repo in sealing worker path**
`ls -Alh /Lotus/worker/unsealed`

> total 225G
> drwxr-xr-x 2 stuart stuart 4.0K Aug 20 00:37 fetching
> 
> -rw-r--r-- 1 stuart stuart  33G Aug 20 15:02 s-t01306-2
> -rw-r--r-- 1 stuart stuart  33G Aug 21 03:30 s-t01306-3
> -rw-r--r-- 1 stuart stuart  33G Aug 21 04:58 s-t01306-4
> -rw-r--r-- 1 stuart stuart  33G Aug 21 16:14 s-t01306-5
> -rw-r--r-- 1 stuart stuart  33G Aug 21 17:00 s-t01306-6
> -rw-r--r-- 1 stuart stuart  33G Aug 21 16:11 s-t01306-7
> -rw-r--r-- 1 stuart stuart  33G Aug 21 16:56 s-t01306-8

**Comment by Reiers** [comment]
Hi @stuberman Stu

Thanks for the report. The issue is outdated, things are much better now with the indexer and Boost incoming. 

If this is an issue in the [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1) - please open a new ticket, with fresh logs.

Thank you !
