### ISSUE TITLE
Storage-deals failed: deal wasn't active

### ISSUE THREAD

**Issue by WBQ1995** [filecoin-project/lotus#3234]
**Describe the bug**
Storage-deals marked failed on the dashboard while still in the StorageDealSealing phase.

**Version (run `lotus version`):**
Daemon:  0.4.6+git.a60c6e0b+api0.11.0
Local: lotus version 0.4.6+git.a60c6e0b

**Additional context**
Link to the dashboard: https://calibration.spacerace.filecoin.io/deals/t01300

```
StorageDealError ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreih3trgme2gibcyilmerehng45upcoomqa6frrup5etzmjke6rkg4a"},"State":26,"Message":"error in deal activation: handling applied event: deal wasn't active: deal=4246, parentState=bafy2bzacea6xhd2ijwabc2q75wgoji5cvdhzlbai6kqjww4igosvjobuyfhum, h=5131","Provider":"t01300","DataRef":null,"PieceCID":{"/":"baga6ea4seaqhyd6yv2xeunqk7vgeib4ssftncwaiaxc6txcpfoyonu4w52bwcjq"},"Size":2130706432,"PricePerEpoch":"1000000000"...
```

```
...ke6rkg4a  4246    StorageDealSealing  t12heuwfbg654jgdnctywyafxrqbmcidwj6osecha                                               2GiB    0.00070105 FIL            701050
```

**Comment by flyworker** [comment]
we just got this issue again.  
l
otus version:0.5.3

https://spacerace.filecoin.io/deals/t02401%20t02387%20t01276

` 100	StorageDealError ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreibo23clkqbl4cgiuzr7od5gszaognomwzljex22zapwr2jy3uygvq"},"State":26,"Message":"error in deal activation: handling applied event: deal wasn't active: deal=4977, parentState=bafy2bzaced6pchmi4adoos74z6bwtfutvmpf2bbv42put5f5ginmmwab3mut4, h=5020","Provider":"t01276","DataRef":null,"PieceCID":{"/":"baga6ea4seaqfjqtqd6uuh6sdpphkruw7ckif364lytcdcedgodhqeg353vedycy"},"Size":130048,"PricePerEpoch":"61035","Duratio...`

**Comment by ozhtdong** [comment]
I have the same problem.

**Comment by deltazxm** [comment]
me too

**Comment by 15012700225** [comment]
Same Issue:

StorageDealError ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreiey7bxw2fcsdnxt52fwxideuev33jhb6lzulg3l7l4rhe5ayczfpi"},"State":26,"Message":"error in deal activation: handling applied event: deal wasn't active: deal=18157, parentState=bafy2bzaceapqbdrowpipna7cyvcwzeu5qvwmmqjwkr74dqfik6bx45czmvlj2, h=10014","Provider":"t02416","DataRef":null,"PieceCID":{"/":"baga6ea4seaqecioq5n3a6a2xpcylprfqofvfwheeca74advtun2rpnyg3bd5gnq"},"Size":133169152,"PricePerEpoch":"62500000",...

**Comment by joshyoonchoi** [comment]
I also have this problem
```
2020-09-07T10:10:02.344Z	ERROR	events	events/events_called.go:252	chain trigger (@H 38894, triggered @ 38900) failed: deal wasn't active: deal=79797, parentState=bafy2bzacedl2tvkbv6y5sj46bhcnnisexce3dkqygmxrvejfwwsjipgry5e5i, h=38894
2020-09-07T10:10:03.368Z	ERROR	events	events/events_called.go:252	chain trigger (@H 38894, triggered @ 38900) failed: deal wasn't active: deal=79797, parentState=bafy2bzacedl2tvkbv6y5sj46bhcnnisexce3dkqygmxrvejfwwsjipgry5e5i, h=38894
2020-09-07T10:10:30.981Z	ERROR	events	events/events_called.go:252	chain trigger (@H 38894, triggered @ 38900) failed: deal wasn't active: deal=79797, parentState=bafy2bzacedl2tvkbv6y5sj46bhcnnisexce3dkqygmxrvejfwwsjipgry5e5i, h=38894
```

**Comment by rjan90** [comment]
I think this issue can be closed as it it's related to the SpaceRace Dashboard. #rengjøring

**Comment by Reiers** [comment]
**Issue outdated.**

Closing ticket.
