### ISSUE TITLE
WebSocket Has been shut down

### ISSUE THREAD

**Issue by shishi614** [filecoin-project/lotus#3242]
Why there are so many WebSocket relational bugs. At this point, The WindowPost didn't do it, causing the power to drop,CommitFailed and PreCommitFailed

version:
xjgw@ya-cx-2fi0207-008:~$ /home/xjgw/calibration_work/bin/lotus-miner -v
lotus-miner version 0.4.6+git.5c6b99c9.dirty

![image](https://user-images.githubusercontent.com/20469171/90951170-e792d180-e48a-11ea-9bba-796a970cb7f8.png)

**Comment by magik6k** [comment]
Is your `lotus daemon` running?
