### ISSUE TITLE
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

### ISSUE THREAD

**Issue by 815943555** [filecoin-project/lotus#3243]
[root@localhost lotus]# ./lotus daemon
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.2()
	/root/go_workspace/pkg/mod/github.com/lucas-clemente/quic-go@v0.17.3/internal/handshake/unsafe.go:26 +0x205

**Comment by magik6k** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/3272
