### ISSUE TITLE
SealCommit2 local verify success, chain check failed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by wyblyf** [filecoin-project/lotus#3245]
**Describe the problem**

There is a small probability that a SealCommit2 local check will succeed and a chain check will fail:

![image](https://user-images.githubusercontent.com/6084318/90953165-ac4cce80-e49b-11ea-9211-1dba57379c12.png)

**Version**

lotus version 0.4.6+git.e195c86.dirty

**Comment by f8-ptrk** [comment]
is this resolved?

**Comment by Reiers** [comment]
**If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.**

Closing ticket.
