### ISSUE TITLE
WARN when typing in Lotus Daemon 

### ISSUE THREAD

**Issue by Snow-Sudo** [filecoin-project/lotus#3248]
Type
>sudo lotus daemon 
>
The terminal outputted this 
>2020-08-22T10:41:25.584-0400	WARN	chainstore	store/store.go:156	no previous chain state found
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/miner2/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/snap/go/6274/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/snap/go/6274/src/reflect/asm_amd64.s:12): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/snap/go/6274/src/reflect/asm_amd64.s:12): failed to build dtypes.AfterGenesisSet: function "reflect".makeFuncStub (/snap/go/6274/src/reflect/asm_amd64.s:12) returned a non-nil error: genesis func failed: No genesis block provided, provide the file with 'lotus daemon --genesis=[genesis file]'

**Comment by magik6k** [comment]
Use latest master or the `0.5.4` tag (or newer)
