### ISSUE TITLE
RPC call to 'Filecoin.AddPiece': pieceCid error:

### ISSUE THREAD

**Issue by 815943555** [filecoin-project/lotus#3258]
2020-08-24T06:47:20.024Z        DEBUG   advmgr  sector-storage/localworker.go:75        acquired sector {175332 6} (e:0; a:1): {{0 0} /nvme0n1/worker/unsealed/s-t0175332-6  }
2020-08-24T06:47:20.038Z        WARN    rpc     go-jsonrpc@v0.1.2-0.20200817153016-2ea5cbaf5ec0/handler.go:241  error in RPC call to 'Filecoin.AddPiece': pieceCid error:
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).AddPiece
        /root/go_workspace/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:141
  - generating piece commitment:
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).pieceCid
        /root/go_workspace/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:190
  - failed to build tree

    Caused by:
        0: failed to create data store
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GeneratePieceCIDFromFile
        /root/go_workspace/lotus/extern/filecoin-ffi/proofs.go:190
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).pieceCid
        /root/go_workspace/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:188
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).AddPiece
        /root/go_workspace/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:139
    github.com/filecoin-project/lotus/extern/sector-storage.(*LocalWorker).AddPiece
        /root/go_workspace/lotus/extern/sector-storage/localworker.go:113
    reflect.Value.call
        /usr/local/go/src/reflect/value.go:460
    reflect.Value.Call
        /usr/local/go/src/reflect/value.go:321
    github.com/filecoin-project/go-jsonrpc/auth.PermissionedProxy.func1
        /root/go_workspace/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200817153016-2ea5cbaf5ec0/auth/auth.go:62
    reflect.callReflect
        /usr/local/go/src/reflect/value.go:549
    reflect.makeFuncStub
        /usr/local/go/src/reflect/asm_amd64.s:20
    github.com/filecoin-project/lotus/api/apistruct.(*WorkerStruct).AddPiece
        /root/go_workspace/lotus/api/apistruct/struct.go:1170
    reflect.Value.call
        /usr/local/go/src/reflect/value.go:460
    reflect.Value.Call
        /usr/local/go/src/reflect/value.go:321
    github.com/filecoin-project/go-jsonrpc.doCall
        /root/go_workspace/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200817153016-2ea5cbaf5ec0/handler.go:130
    github.com/filecoin-project/go-jsonrpc.(*RPCServer).handle
        /root/go_workspace/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200817153016-2ea5cbaf5ec0/handler.go:221
    runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373

**Comment by magik6k** [comment]
Not sure if this can still happen, please reopen if you are able to reproduce this with the latest code
