### ISSUE TITLE
Error when initializing lotus miner 。 Help children！

### ISSUE THREAD

**Issue by wq969453423** [filecoin-project/lotus#3260]
**Describe the bug**
Error when initializing lotus miner：
I follow the document process and tutorial：
lotus-miner init --actor=t01023 --owner=t3。。。。

**To Reproduce**
2020-08-24T15:45:10.354+0800	ERROR	main	lotus-storage-miner/init.go:242Failed to initialize lotus-miner: failed to configure miner:
    main.storageMinerInit
        /home/ps/code/community/lotus/cmd/lotus-storage-miner/init.go:508
  - getWorkerAddr returned bad address:
    main.configureStorageMiner
        /home/ps/code/community/lotus/cmd/lotus-storage-miner/init.go:558
  - (get ssize) failed to load miner actor state: read actor head: cbor input had wrong number of fields
2020-08-24T15:45:10.354+0800	INFO	main	lotus-storage-miner/init.go:247Cleaning up /root/.lotusminer after attempt...
ERROR: Storage-miner init failed

**Comment by f8-ptrk** [comment]
`lotus-miner init --actor=t01023 --owner=t3`

actor and owner cannot be set at the same time

resolved i think - 8+ month old

lotus-miner init --actor=t01023 --owner=t3

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
