### ISSUE TITLE
StrorageDeal: failed to negotiate security protocol: context deadline exceeded

### ISSUE THREAD

**Issue by dispensable1988** [filecoin-project/lotus#3270]
I Configure config.toml according to the following：
https://docs.filecoin.io/mine/connectivity/
All checks passed：
https://ping.eu/ping/ 
https://ping.eu/port-chk/ 
https://calibration.spacerace.filecoin.io/check 

But still some errors：
1：
`ClientQueryAsk failed : failed to open stream to miner: failed to dial 12D3KooWRGnNJdAoF7kEMJwq2FtbsyGQZd6PyFfQa797anYNHfQa: all dials failed * [/ip4*******/tcp/31432] dial tcp4 0.0.0.0:1235->*****:31432: i/o timeout * [/ip4/******/tcp/31432] failed to negotiate security protocol: context deadline exceeded`
2：
`StorageDealError ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreicxkxqee57abpgfktojqtwvmmn44n6xpue7ul2vnycdghobzqyg5i"},"State":26,"Message":"sending proposal to storage provider failed: failed to dial 12D3KooWHMAGXCZ7o8Eg5PBi3rw4pgNY86TAUg1jvg8KwE4vP6vd: all dials failed\n * [/ip4/*******/tcp/31432] dial tcp4 0.0.0.0:1235->*****:31432: i/o timeout\n * [/ip4/******/tcp/31432] failed to negotiate security protocol: context deadline exceeded","Pro...`

1. config.toml:

2. lotus-miner  actor set-addrs

**Comment by jennijuju** [comment]
Please open a new ticket if you are running into this issue on the latest version of lotus!
