### ISSUE TITLE
ERROR: initializing node

### ISSUE THREAD

**Issue by vonhenry** [filecoin-project/lotus#3279]
1. Run 
' ./lotus daemon --lotus-make-genesis=devgen.car --genesis-template=localnet.json --bootstrap=false' 
following description at https://docs.lotu.sh/en+setup-local-dev-net

2. See error
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/Users/song/Code/Golang/src/github.com/filecoin-project/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.AfterGenesisSet: function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12) returned a non-nil error: getting genesis block failed: cbor input had wrong number of fields

git commit is a085b3b5f314b92b541f5171ba08029c1515cc57

**Comment by whyrusleeping** [comment]
To run a local devnet, please ensure you have rebuilt recently, and that your existing lotus repo has either been moved or deleted.
