### ISSUE TITLE
There is NO [Create Miner] in faucet

### ISSUE THREAD

**Issue by hextrump** [filecoin-project/lotus#3285]
**Describe the bug**
There is NO [Create Miner] in faucet.
**To Reproduce**
1. Run '...'
login in https://spacerace.faucet.glif.io/ by chrome or firefox, but there is only 

(1)REQUEST    Enter an address to request FIL

(2)CHECK    Enter an address to check its balance

I followed the lotu.sh guide and got 100FIL after inputed my t1yoi7ra4cnwbkposnb2ehxqrmzggvr75uz6owktq address and request, 

but I can't find a button to Create Miner.

Then, I ran lotus wallet new bls I got a  t3qz27erno4lyvjyrfmczaoswntpkjgpub3lhzv7xvaojbqjecxcvhwtlgmns4w3ux2ggm7npu7yodfv74mhta,

However, when I request with this address it warned: User account is too new
![image](https://user-images.githubusercontent.com/70214356/91192554-a3246180-e728-11ea-8452-b9101a285276.png)

2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by whyrusleeping** [comment]
To create a miner, run `lotus-miner init` after you have received your funds. You don't need to use a faucet for this. Please see: https://lotu.sh/en+mining#get-started-41720

**Comment by hsjw12** [comment]
I had the same problem, did you solve this problem?
