### ISSUE TITLE
Consider limiting active peer connections to prevent DoS

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/lotus#3286]
https://github.com/filecoin-project/lotus/blob/80e6e56a824599e7b8a71241197a7dfa04d14cfc/lib/peermgr/peermgr.go#L134-L136

**Comment by vyzo** [comment]
We already have connection manager limits afaict.

**Comment by vyzo** [comment]
We start pruning connections if we exceed 180:
https://github.com/filecoin-project/lotus/blob/master/node/config/def.go#L123
