### ISSUE TITLE
Sign permission error with admin token

### ISSUE THREAD

**Issue by rllola** [filecoin-project/lotus#3288]
**Describe the bug**
I am trying to create a payment channel using RPC calls. I have an admin token but I get a permission error when trying to call method `Filecoin.PaychGet`. 

**To Reproduce**
1. Run a node
2. Get token from `~/.lotus/token`
3. Call `Filecoin.PaychGet`
4. Get `"error":{"code":1,"message":"missing permission to invoke 'PaychGet' (need 'sign')"}`

**Expected behavior**
As an admin I should have the "sign" permission.

**Version (run `lotus version`):**
version tag v0.5.3

**Comment by Kubuxu** [comment]
I cannot reproduce:
```
> token=$(cat $LOTUS_PATH/token)
> runAPI() {
  curl -X POST \
    -H "Content-Type: application/json" \
    --data '{"jsonrpc":"2.0","id":2,"method":"Filecoin.'"$1"'","params":'"${2:-null}"'}' \
    'http://127.0.0.1:1234/rpc/v0?token='"$token"
}
> runAPI PaychGet '["t01", "t01", "100"]'
{"jsonrpc":"2.0","id":2,"error":{"code":1,"message":"initializing paych actor: getting key address: address t01 was not for an account actor (RetCode=4)"}

**Comment by rllola** [comment]
I am so sorry. I was using Postman and I had the token but the `Authorization` header was unchecked. Closing this.

**Comment by rllola** [comment]
Maybe a better error message would help. Like "missing token" instead of "missing permission to invoke".
