### ISSUE TITLE
Doc: Setup and usage of logstash log aggregation

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#329]
We're doing this with our own nodes, and its not too difficult to set up it seems. Let's have a document detailing how this works both for ourselves, and others wanting to run a lotus node

**Comment by f8-ptrk** [comment]
move this to the docs repo 

#antidisestablishatarianism

**Comment by jennijuju** [comment]
create the first draft in https://github.com/filecoin-project/lotus/discussions/categories/tutorials

**Comment by TippyFlitsUK** [comment]
Hi @whyrusleeping 

This looks like a reminder. Should we close it or keep it open?
