### ISSUE TITLE
Implement a command to "follow checkpoint"

### ISSUE THREAD

**Issue by nicola** [filecoin-project/lotus#3290]
We would like to have a command called `follow checkpoint HASH`.

Given the hash of a block (or a tipset), lotus will make sure to follow a fork that contains that checkpoint HASH.

In case of social consensus, miners can force follow a particular chain.

**Comment by nicola** [comment]
From previous conversations, we agreed that this is higher in priority (cc @momack2 )

**Comment by momack2** [comment]
fixed by https://github.com/filecoin-project/lotus/pull/3680
