### ISSUE TITLE
Blocksync should use limited parallelism when querying peers after a failure

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#3291]
If we fail to get data from a peer over blocksync, we simply switch to the next peer and attempt to fetch from them. This is sequential process and take take quite a while to get to a good peer.

Instead, once we experience a failure (or two, maybe) we should make smaller requests, but in parallel, to hopefully find a better peer faster.

**Comment by vyzo** [comment]
this is addressed by #3887 -- it uses a parallel fetch for all sync requests, regardless of failure.
