### ISSUE TITLE
Feature request: Check proof parameter files while waiting to sync

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#3306]
When running `lotus-miner` against a node that's behind (start it after a night's downtime), the miner will block until the chain syncs up to head, and then will waste a lot of time verifying the proof parameter files. Would be nice to start verification on startup in the background while waiting for sync.

**Comment by Reiers** [comment]
Hi @karalabe 

Thanks for the report. 

`lotus-miner run --nosync`
"don't check full-node sync status"
