### ISSUE TITLE
rpc	go-jsonrpc@v0.1.2-0.20200817153016-2ea5cbaf5ec0/handler.go:241	error in RPC call to 'Filecoin.StorageStat': fsstat: 

### ISSUE THREAD

**Issue by 815943555** [filecoin-project/lotus#3309]
WARN	rpc	go-jsonrpc@v0.1.2-0.20200817153016-2ea5cbaf5ec0/handler.go:241	error in RPC call to 'Filecoin.StorageStat': fsstat: path not found:
1|lotus miner  |     github.com/filecoin-project/lotus/extern/sector-storage/stores.init
1|lotus miner  |         /root/go_workspace/v051/lotus/extern/sector-storage/stores/local.go:578

**Comment by jennijuju** [comment]
duplicate #4686
