### ISSUE TITLE
Sector storage (store) on remote worker doesn't get proofs in miner

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#3312]
**Describe the bug**
Some sectors I have are stored on a remote worker. They failed the post.

**To Reproduce**
Have remote worker + regular miner, both with a sector store directory. See that windowed post will fail on all sectors that are in the remote workers' store.

**Expected behavior**
On Windowed Post, all sectors succeed

**Screenshots**
36836-2020-08-26T04:27:29.793Z	INFO	storageminer	storage/wdpost_sched.go:208	at 3655, doPost for P 890, dd 46
36837:2020-08-26T04:27:29.799Z	WARN	advmgr	sector-storage/faults.go:54	CheckProvable Sector FAULT: cache an/or sealed paths not found	{"sector": {"Miner":2388,"Number":0}, "sealed": "", "cache": ""}
36838:2020-08-26T04:27:29.834Z	WARN	advmgr	sector-storage/faults.go:54	CheckProvable Sector FAULT: cache an/or sealed paths not found	{"sector": {"Miner":2388,"Number":2}, "sealed": "", "cache": ""}
36839:2020-08-26T04:27:29.834Z	WARN	advmgr	sector-storage/faults.go:54	CheckProvable Sector FAULT: cache an/or sealed paths not found	{"sector": {"Miner":2388,"Number":4}, "sealed": "", "cache": ""}
36840:2020-08-26T04:27:29.834Z	WARN	advmgr	sector-storage/faults.go:54	CheckProvable Sector FAULT: cache an/or sealed paths not found	{"sector": {"Miner":2388,"Number":6}, "sealed": "", "cache": ""}
36841:2020-08-26T04:27:29.834Z	WARN	advmgr	sector-storage/faults.go:54	CheckProvable Sector FAULT: cache an/or sealed paths not found	{"sector": {"Miner":2388,"Number":7}, "sealed": "", "cache": ""}
36842-2020-08-26T04:27:29.834Z	WARN	storageminer	storage/wdpost_run.go:102	Checked sectors	{"checked": 8, "good": 3}
36843:2020-08-26T04:27:29.834Z	ERROR	storageminer	storage/wdpost_run.go:251	DETECTED FAULTY SECTORS, declaring faults	{"count": 5}

**Comment by irocn** [comment]
Yes, I also found this issue! @magik6k 
If it is true I have to store all sectors sealed on miner. it is not a good solution.

**Comment by KaptinLin** [comment]
The sector files didn't move to the storage before the window post.

**Comment by Reiers** [comment]
The issue is solved.

For the record:
Edit storage.json in your .lotusminer and add the path to the second storage.
or
`lotus-miner storage attach --init --store <PATH_FOR_LONG_TERM_STORAGE>`

For similar problems - Please visit our discussion forum or ask for help in Slack #fil-lotus-help.
