### ISSUE TITLE
Couldn't get a few gas from faucet because account is too new

### ISSUE THREAD

**Issue by hextrump** [filecoin-project/lotus#3319]
**Describe the bug**
Couldn't get a few gas from faucet because account is too new
**To Reproduce**
1. Run '...'

I'm new in Filecoin and I tried to work as a lotus miner, but when I

Run /lotus-miner init --owner=t3udpmms2r3q6wk47ysudm2o6gvjmob6kw33hsy4nwg4cvembu6ybr76oqdwlkdemozf64dzn4xhjmww46jzdq --worker=t3udpmms2r3q6wk47ysudm2o6gvjmob6kw33hsy4nwg4cvembu6ybr76oqdwlkdemozf64dzn4xhjmww46jzdq

It showed "CallWithGas failed"

So I followed the guide and Visit the faucet, but I couldn't request some FIL, because account is too new.

Could somebody send me a few coin for testing? Much appreciated!!!

2. See error
GasEstimateMessageGas error: estimating gas used: CallWithGas failed: call raw get actor: resolution lookup failed (t3udpmms2r3q6wk47ysudm2o6gvjmob6kw33hsy4nwg4cvembu6ybr76oqdwlkdemozf64dzn4xhjmww46jzdq): resolve address t3udpmms2r3q6wk47ysudm2o6gvjmob6kw33hsy4nwg4cvembu6ybr76oqdwlkdemozf64dzn4xhjmww46jzdq: actor not found
2020-08-26T23:02:43.912+0800	INFO	main	lotus-storage-miner/init.go:251Cleaning up /root/.lotusminer after attempt...
ERROR: Storage-miner init failed

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
Daemon:  0.5.4+git.d4fef1b5+api0.12.0
**Additional context**

**Comment by hsjw12** [comment]
Have you solved this problem? I had the same problem.

**Comment by hsjw12** [comment]
I finally succeeded. Thank you for your help.

**Comment by arajasek** [comment]
Not a Lotus issue.
