### ISSUE TITLE
GasEstimateFee (or something like that) exposed in the API

### ISSUE THREAD

**Issue by Schwartz10** [filecoin-project/lotus#3326]
Client applications, like wallets and exchanges, will want to be able to retrieve and estimate the total transaction fees paid by a message sender.

Requested feature discussed with @Kubuxu in [slack](https://filecoinproject.slack.com/archives/GRT37S147/p1598472548014500?thread_ts=1598024725.000700&cid=GRT37S147) - an API handler for computing the total afil fee paid by the message sender: `GasLimit*FeeCap - GasOutput.Refund`. 

In an ideal world, this handler would also be able to accept not-yet-sent messages and run them without persisting any changes, much like `StateCall`, so applications can estimate fees for their users. Alternatively, we could have a `GasEstimateMaxSpend` handler that computes `Y`, where `Y = GasLimit*FeeCap` and `FeeCap = BaseFee*1.125^5+GasPremium`

**Comment by firmianavan** [comment]
As I see, according to `ApplyMessage` in `vm.go`, sometimes a none-zero `ExitCode` does not trigger the fee cost, while the others does.

**Comment by Kubuxu** [comment]
Only one of these cases is in effect (for the rest block is invalid) and it doesn't cause message receipt production.
In essence the message was not applied, there is no exit code, no gas is used.

**Comment by arajasek** [comment]
Detailed gas costs can be acquired from the `StateReplay` API endpoint. Doesn't work for unsent messages, though.
