### ISSUE TITLE
Unable to initialize a new miner with a worker key generated by the the miner itself.

### ISSUE THREAD

**Issue by Wondertan** [filecoin-project/lotus#3331]
### Reproducing
1. Run `lotus-miner init --create-worker-key`. It does not matter if there are other options or not.
2. Wait till params are loaded/verified while wasting your youth.
3. See an error msg:
`GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: failed to init new actor (RetCode=16)`

### Version
Daemon:  0.5.4+git.d4fef1b5+api0.12.0
Local: lotus version 0.5.4+git.d4fef1b5

**Comment by magik6k** [comment]
This got fixed
