### ISSUE TITLE
The StartEpoch of deal from the BOT

### ISSUE THREAD

**Issue by shannon-6block** [filecoin-project/lotus#3338]
**Describe the bug**
The StartEpoch of a deal is odd

**To Reproduce**
When I pack a sector contains deal 6300, it shows an error message
```
sector 3032 got error event sealing.SectorPackingFailed: expired dealIDs in sector: piece 0 (of 19) of sector 3032 refers expired deal 6300 - should start at 5364, head 6133
```

As you can see, the create time of deal 6300 is 2020-08-26 02:47:30
https://filfox.info/zh/deal/6300

The StartEpoch of it is hight 5364, time 2020-08-27 02:42:00

Only one day is left to me for sealing the deal. Is it too short?

**Comment by f8-ptrk** [comment]
is this resolved?

#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
