### ISSUE TITLE
Upgrade blst to fix cross cpu architecture binary incompatibilities 

### ISSUE THREAD

**Issue by ognots** [filecoin-project/lotus#3339]
**Describe the bug**
A SIGILL error occurs in lotus daemon when running a `lotus` binary compiled on an AMD CPU based machine but ran on an Intel CPU machine.

**To Reproduce**
1. Build lotus on an AMD machine `make clean deps build`
2. Run `lotus daemon` on an Intel based machine

**Expected behavior**
`lotus` binary is compatible on Intel and AMD CPUs, regardless of architecture of build machine.

**Version (run `lotus version`):**
v0.5.3

**Proposed Solution**
Error caused by C compile flag `-march=native` in `blst`
Update `blst` to https://github.com/supranational/blst/commit/6a70e25baaec711287fc23a2c99a0af04be3f7f2 or later

**Comment by ognots** [comment]
Upgrading to https://github.com/supranational/blst/releases/tag/v0.2.0 should fix this issue

**Comment by magik6k** [comment]
Pretty sure this is fixed now
