### ISSUE TITLE
Sync slow and high resource consumption

### ISSUE THREAD

**Issue by hfmhx** [filecoin-project/lotus#3342]
**Describe the bug**
Sync slow and high resource consumption

**To Reproduce**
1. Run 'lotus-daemon lotus-miner'
2. Occasionally

**Expected behavior**
Usually the sync of a block is completed in milliseconds
When this kind of problem occurs, the sync time of the block becomes significantly longer, and the CPU &Mem resource consumption is very large.

**Screenshots**
![image](https://user-images.githubusercontent.com/44537744/91382396-3e6a2380-e85c-11ea-8213-6fee6a18d4f2.png)

![image](https://user-images.githubusercontent.com/44537744/91382283-fb0fb500-e85b-11ea-9e6f-aea77fe123a7.png)

debug.log.1 records the lotus daemon log when there is a problem, the number of messages in one hour is twice the positive time
![image](https://user-images.githubusercontent.com/44537744/91383356-8a1dcc80-e85e-11ea-866b-8418fbabbece.png)
There are many messages from these ids
12D3KooWKw6rCMCZqWrBG84dWPGYAvvzdNtfSyEsEaurJsxjB4ec
12D3KooWADVi3JbKkbG8YjeJM2ZqTbGmJUE3Jn2U7i2KoavKAtQj
![image](https://user-images.githubusercontent.com/44537744/91384005-2b595280-e860-11ea-859f-41446768e92b.png)

**Version (run `lotus version`):**
Daemon:  0.4.6+git.5c7618f.dirty+api0.11.0
Local: lotus version 0.4.6+git.5c7618f.dirty

**Additional context**

**Comment by rjan90** [comment]
Resource consumption for syncing has been greatly improved since this verison, so I think this issue can probably can be closed? #rengjøring

**Comment by Reiers** [comment]
Issue solved in newer version of Lotus.
_Closing ticket._ 

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
