### ISSUE TITLE
retrieval deals : time out

### ISSUE THREAD

**Issue by hfmhx** [filecoin-project/lotus#3344]
**Describe the bug**
A lot of retrieval deals timed out at the same time

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44537744/91414435-235cdb00-e87f-11ea-8b45-f27cac6e9f6f.png)

**The deals list**
`Receiver                                              DealID  Payload      State                             PricePerByte  BytesSent  Message
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  303     ...o7hf36ba  DealStatusErrored                 2             65536      deal data transfer failed: routing: not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  411     ...6kxa34zm  DealStatusFundsNeededLastPayment  2             65536      
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  475     ...gpxylm6i  DealStatusFundsNeeded             2             1053786    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  514     ...mkpgobwi  DealStatusFundsNeeded             2             1101835    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  943     ...6fgklvlw  DealStatusFundsNeeded             2             1101835    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1042    ...7lclg5t6  DealStatusFundsNeeded             2             1101835    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  882     ...mkpgobwi  DealStatusFundsNeeded             2             1101835    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  273     ...ewvmps5e  DealStatusFundsNeeded             2             1101835    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  510     ...r7vw3bii  DealStatusFundsNeeded             2             1101835    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  838     ...mmdhayha  DealStatusFundsNeededLastPayment  2             65536      
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  879     ...ffr7hj2e  DealStatusFundsNeededLastPayment  2             65536      
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  925     ...nil4dl5o  DealStatusFundsNeededLastPayment  2             65536      
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  418     ...ewvmps5e  DealStatusFundsNeeded             2             1101835    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  202     ...gpxylm6i  DealStatusFundsNeeded             2             1053786    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  399     ...6kxa34zm  DealStatusFundsNeededLastPayment  2             65536      
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  504     ...ffr7hj2e  DealStatusFundsNeededLastPayment  2             65536      
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  519     ...d47eukt2  DealStatusFundsNeeded             2             1101835    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  668     ...mmdhayha  DealStatusFundsNeededLastPayment  2             65536      
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  885     ...d47eukt2  DealStatusFundsNeeded             2             1101835    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  886     ...6kxa34zm  DealStatusFundsNeededLastPayment  2             65536      
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1074    ...mlplybl2  DealStatusFundsNeeded             2             1053786    
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  888     ...ewvmps5e  DealStatusFundsNeeded             2             1101835   `

The state "DealStatusFundsNeeded" means that the sector has been successfully unsealed， So is the timeout due to payment issues?
 

**Version (run `lotus version`):**
Daemon:  0.5.4+git.ceef149.dirty+api0.12.0
Local: lotus version 0.5.4+git.ceef149.dirty

**Additional context**

**Comment by rjan90** [comment]
I think this issue can be closed, as it was only relevant to the SpaceRace
#antidisestablishatarianism
