### ISSUE TITLE
Failed to request test FIL, and HOW can I get a miner ID???

### ISSUE THREAD

**Issue by heyasjack** [filecoin-project/lotus#3345]
**Describe the bug**

**To Reproduce**
1. Run '...'
Followed the guide https://lotu.sh/en+mining, they told me to request some FIL from faucet, it succeed. 

But when I delete the former Ubuntu and try another CPU with another ubuntu system, I can't request some FIL...

"This GitHub account has already used the faucet with a non-miner Filecoin address. Please try again with your Miner ID."

"MinersYou can reuse this faucet by entering in your miner ID"

lotus lotus-miner init --owner=t3udpmms2r3q6wk47ysudm2o6gvjmob6kw33hsy4nwg4cvembu6ybr76oqdwlkdemozf64dzn4xhjmww46jzdq --worker=t3udpmms2r3q6wk47ysudm2o6gvjmob6kw33hsy4nwg4cvembu6ybr76oqdwlkdemozf64dzn4xhjmww46jzdq

Can I request some FIL for testing?

How can I get a miner ID?

Thank you!

2. See error
This GitHub account has already used the faucet with a non-miner Filecoin address. Please try again with your Miner ID.
**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by magik6k** [comment]
If you still have the old account, you can send some tokens to the other account with `lotus send [t3.. address] [amount to send]`

If you've lost the keys, you have to use other Github account in the faucet.
