### ISSUE TITLE
submit ProveCommitSector message successfully, but sector is not in the sector set of the miner

### ISSUE THREAD

**Issue by shannon-6block** [filecoin-project/lotus#3349]
**Describe the bug**
The ProveCommitSector message of a sector can be sent successfully to the blockchain, but the sector is still not in the sector set of the miner

**To Reproduce**
`lotus-miner sectors status --log 12802` shows the following
![image](https://user-images.githubusercontent.com/65558170/91434041-d2f17780-e896-11ea-8443-4f18d8f189eb.png)

The message can be found here
https://filfox.info/zh/message/bafy2bzacecl7y25hfzdqnvnjfor64qcnssp6yugzazv5ryuqap5zlegie23o4

But when you call `lotus state sectors t02514`, the sector number 12802 is not inside.

**Comment by Reiers** [comment]
Hi @shannon-6block 

Thanks for the report. The issue is outdated, and have gone stale.

If this is a issue in the [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1) - please open a new ticket.

Thank you !
