### ISSUE TITLE
When i limit memory in Docker, some OOM error

### ISSUE THREAD

**Issue by btcioner** [filecoin-project/lotus#3351]
**Describe the bug**

**To Reproduce**
1. Run '...'
2. 
https://fabianlee.org/2020/01/18/docker-placing-limits-on-container-memory-using-cgroups/

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by arajasek** [comment]
Sounds like it ran out of memory.
