### ISSUE TITLE
stores  stores/http_handler.go:114      %+vwrite tcp 192.168.6.19:3456->192.168.6.13:40292: write: broken pipe

### ISSUE THREAD

**Issue by 815943555** [filecoin-project/lotus#3353]
stores  stores/http_handler.go:114      %+vwrite tcp 192.168.6.19:3456->192.168.6.13:40292: write: broken pipe

**Comment by rjan90** [comment]
Is this issue resolved?
#antidisestablishatarianism

**Comment by jennijuju** [comment]
Thank you for creating the ticket! Lotus has been improved a lot since this ticket was created, please update your lotus to the latest release, and open a new ticket if you are still facing the issue.
