### ISSUE TITLE
systemd services Environment variables are useless RUST_BACKTRACE RUST_LOG

### ISSUE THREAD

**Issue by nickboot** [filecoin-project/lotus#3358]
**Describe the bug**
systemd services Environment variables are useless RUST_BACKTRACE RUST_LOG

**To Reproduce**
1. # cat /etc/systemd/system/lotus-miner.service
[Unit]
Description=Lotus Miner
After=network.target
After=lotus-daemon.service
Requires=lotus-daemon.service
[Service]
ExecStart=/usr/local/bin/lotus-miner run
Environment=GOLOG_FILE=“/cephfs/miner.log”
Environment=GOLOG_LOG_FMT=“json”
[Install]
WantedBy=multi-user.target
2. # cat /etc/systemd/system/lotus-miner.service.d/override.conf
[Service]
Environment=“FIL_PROOFS_PARAMETER_CACHE=/cephfs/filecoin-proof-parameters-v28”
Environment=“LOTUS_PATH=/cephfs/lotuswork/lotus”
Environment=“LOTUS_STORAGE_PATH=/cephfs/lotuswork/lotusstorage”
Environment=“WORKER_PATH=/cephfs/lotuswork/lotusworker”
Environment=“TMPDIR=/cephfs/lotuswork/tmpdir”
Environment=“FIL_PROOFS_PARENT_CACHE=/cephfs/lotuswork/filecoin-parents”
Environment=“IPFS_GATEWAY=https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/”
Environment=“FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1"
Environment=“FIL_PROOFS_USE_GPU_TREE_BUILDER=1”
Environment=“FIL_PROOFS_MAXIMIZE_CACHING=1"
Environment=RUST_BACKTRACE=“full”
Environment=RUST_LOG=“debug”

**Expected behavior**
RUST LOG

**Version (run `lotus version`):**
# lotus --version
lotus version 0.5.4+git.d4fef1b5

**Comment by PatrickDeuse** [comment]
> Environment=“FIL_PROOFS_MAXIMIZE_CACHING=1"
> Environment=RUST_BACKTRACE=“full”
> Environment=RUST_LOG=“debug”

are they quoted corretly?
