### ISSUE TITLE
No secure API access over Internet

### ISSUE THREAD

**Issue by nad010286** [filecoin-project/lotus#3362]
It is not secured if sending API calls over Internet without HTTPS

curl -X POST      -H "Content-Type: application/json"      -H "Authorization: Bearer TOKEN"      --data '{ "jsonrpc": "2.0", "method": "Filecoin.ChainHead", "params": [], "id": 3 }'      'http://IP:port/rpc/v0'

**Comment by Kubuxu** [comment]
The API is not designed for exposing on the internet. The token can be sniffed and spoofed.
