### ISSUE TITLE
RPC client error

### ISSUE THREAD

**Issue by long568** [filecoin-project/lotus#3370]
**Describe the bug**
When I restart a lotus-worker, it shows a RPC client error.
I removed the "lotusworker" and try again, then it shows the same error.

**To Reproduce**
1. Run 
`lotus-worker run --parallel-fetch-limit=3 --addpiece=false`
2. See error
```
Aug 28 03:04:34 w004 systemd[1]: Stopped Lotus Worker.
Aug 28 03:04:34 w004 systemd[1]: Started Lotus Worker.
Aug 28 03:04:34 w004 lotus-worker[3165]: 2020-08-28T03:04:34.502Z        INFO        main        lotus-seal-worker/main.go:49        Starting lotus worker
Aug 28 03:04:34 w004 lotus-worker[3165]: 2020-08-28T03:04:34.504Z        INFO        main        lotus-seal-worker/main.go:190        Remote version 0.5.4+git.d4fef1b5+api0.12.0
Aug 28 03:04:34 w004 lotus-worker[3165]: 2020-08-28T03:04:34.505Z        WARN        main        lotus-seal-worker/main.go:87        RPC client error: sendRequest failed: websocket routine exiting
```

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
`lotus-worker version 0.5.4+git.d4fef1b5`

**Additional context**

**Comment by jsign** [comment]
From a client POV, I've seen this `sendrequest failed: websocket routine existing` too. Seems like after that, that client instance is unusable and a new one should be created.
I was running `v0.5.10`.

**Comment by jennijuju** [comment]
duplicate with #4063
