### ISSUE TITLE
Implement MinerEligibleForElection in block validation

### ISSUE THREAD

**Issue by nicola** [filecoin-project/lotus#3378]
We should use the current epoch to perform this actors check.
Miner should not be allowed to mine if not eligible

cc @Stebalien

**Comment by anorth** [comment]
Wait, what? Should't it be at WinningPoStSectorSetLookback? We've been gathering the election requirements together into one MinerEligibleForElection function on the assumption that it's all using the same lookback. I don't think you meant to say that, e.g., the power meeting consensus minimum check is made at the current epoch.

I think something might have been lost here in the change to consensus fault penalisation. Previously, when a miner was terminated, that check _was_ made at the current epoch. But everything else was at the election lookback. Now it's got complicated.

@nicola could you please lay out all of the election criteria and which epoch they should be evaluated at? The actors will then need to break apart MinerEligibleForElection into two functions, one intended for the state at each of the epochs.

**Comment by nicola** [comment]
I am currently adding clarity by writing this into this [spec draft](https://github.com/filecoin-project/specs/blob/light/content/protocol/_index.md#mining-requirements).

All the checks for MinerEligibleForElection are for the same epoch and this epoch is the epoch of election.

**Comment by nicola** [comment]
Just to clarify what is written in the spec here:

Lotus should do three checks:
- Eligibility check (consensus fault fee, consensus fault active, debt) using `MinerEligibleForElection` at current epoch
- Miner validity check (check if miner exists ) at current epoch
  - Note: this is currently done in lotus with `minerIsValid`
- Minimum power check (check that miner has min miner size) at WinningPoStLookback 
  - Note: this is currently done in lotus with `MinerNominalPowerMeetsConsensusMinimum`

So, in practice, the actions to take in lotus are:
- Make sure that `minerIsValid`, `MinerNominalPowerMeetsConsensusMinimum` are called at correct epochs
- Add `MinerEligibleForElection` check

**Comment by anorth** [comment]
Actors intends to give you two functions: one to execute at parent state, and one with the lookback state.

**Comment by anorth** [comment]
The state inspection methods for the election eligibility predicates are now available at https://github.com/filecoin-project/specs-actors/blob/master/actors/states/election.go

**Comment by arajasek** [comment]
Fixed in #4188
