### ISSUE TITLE
Removing a sector doesnt remove it from the worker

### ISSUE THREAD

**Issue by ec2** [filecoin-project/lotus#3395]
**Describe the bug**
I have a sector that i removed by doing `lotus-miner sectors update-state --really-do-it 56 Removing`. This marks it as `Removed` but it doesnt delete it from my remote lotus-worker.

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**
0. Set up a lotus-miner and a lotus-worker on different machines
1. Pledge a sector and let it do PC1. 
2. Run `lotus-miner sectors update-state --really-do-it <SNUM> Removing`
3. You should see the sector in .lotusworker/sealed and ./lotusworker/cache still. 
**Screenshots**

**Version (run `lotus version`):**
lotus version 0.5.6+git.606a58bc
**Additional context**

**Comment by hyunmoon** [comment]
No need to do that anymore. `sectors remove` works on a sector in most states (except that's Finalizing).

**Comment by rjan90** [comment]
I think this issue can be closed now? #rengjøring

**Comment by Reiers** [comment]
## How to Remove a sector:
Running sectors/sealing:
```
lotus-miner sealing abort <ID>
lotus-miner sectors remove --really-do-it <sectornumber>
```

Active sectors:
```
lotus-miner sectors remove --really-do-it <sectornumber>
lotus-miner sectors terminate --really-do-it <sectornumber>
```

Expired sectors:
`lotus-miner sectors remove --really-do-it <sectornumber>`

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
_Closing ticket._
