### ISSUE TITLE
MaxSealingSectorsForDeals cause Storage deal success rate to drop

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#3396]
My only miner has 128GB RAM and 2T NVME so I want to limit the parallel to 1. However set MaxSealingSectorsForDeals = 1 will make space race dashboard shows errors and my success rate is only 20%. Why can't it just reject deals rather than accepting them and failing them?

**Comment by hyunmoon** [comment]
Raise your WaitDealsDelay to how long it takes your machine to finish a full cycle (say 8 hours).

**Comment by kernelogic** [comment]
set ExpectedSealDuration = WaitDealsDelay = 8h?

**Comment by cwhiggins** [comment]
set waitDealsDelay in ~/.lotusminer/config.toml

**Comment by rjan90** [comment]
I think this issue can be closed as it was only relevant to the SpaceRace?

**Comment by Reiers** [comment]
Hi @kernelogic 

Thanks for the report. This issue is outdated and should be fixed in the latest releases. 

Closing Lotus issue ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)
