### ISSUE TITLE
lotus-miner info all results in a stacktrace

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#3397]
**Describe the bug**
See attached file for output (too big for github issue)

**To Reproduce**
1. `lotus-miner info all`

**Expected behavior**
No stacktrace

**Version (run `lotus version`):**
Daemon:  0.5.6+git.606a58bc+api0.13.0
Local: lotus version 0.5.6+git.606a58bc

[lotus-miner-info-all.txt](https://github.com/filecoin-project/lotus/files/5146140/lotus-miner-info-all.txt)

**Comment by rjan90** [comment]
I think this issue has been fixed on newer versions of Lotus? At least it's working on `lotus version 1.11.1-m1.3.5+mainnet+git.3ff8e256b` #rengjøring
