### ISSUE TITLE
StorageDealError with Error Reading Response Message

### ISSUE THREAD

**Issue by William8Work** [filecoin-project/lotus#3406]
**Describe the bug**
After the miner seals and proves the sectors, the sector shows deal error.

**To Reproduce**
1. Pledge and Seal a Sector
During the spacerace, there are sectors completed sealing but the deal making errors out.

2. See error in the https://spacerace.filecoin.io/deals/t08399:

StorageDealError ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreifx7lomkvw3lmgw7ficbsdbitpkoo5hogruu2ut4y3oneu3nsuaoq"},"State":26,"Message":"error reading Response message: stream reset","Provider":"t08399","DataRef":null,"PieceCID":{"/":"baga6ea4seaqb6kb4isme2ncz7em6t3ejc4afmshwoy3jr3c2mlqihx6ckaf5ofy"},"Size":133169152,"PricePerEpoch":"62500000","Duration":701475,"DealID":0,"CreationTime":"2020-08-29T18:05:07.844816892Z"},"id":0}

**Expected behavior**
The deal should be success. 

1. I checked the connectivity: https://spacerace.filecoin.io/check, all good. the web site shows miner connectivity is success.
2. Run the lotus net peers | wc -l, the results is 438
3. Run the lotus-miner net peers | wc -l, the results is 358

**Screenshots**

**Version (run `lotus version`):**
lotus version 0.5.6+git.606a58bc

**Additional context**

**Comment by Reiers** [comment]
Hi @William8Work 

This issue is outdated.

Closing.
