### ISSUE TITLE
2020-08-30T15:59:03.544-0400	ERROR	storageminer	storage/wdpost_run.go:60	runPost failed: running post failed:

### ISSUE THREAD

**Issue by 815943555** [filecoin-project/lotus#3408]
2020-08-30T15:59:03.544-0400	ERROR	storageminer	storage/wdpost_run.go:60	runPost failed: running post failed:
1|lotus miner  |     github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
1|lotus miner  |         /root/go_workspace/v056/lotus/storage/wdpost_run.go:409
1|lotus miner  |   - Rust panic: no unwind information
1|lotus miner  |     github.com/filecoin-project/filecoin-ffi.GenerateWindowPoSt
1|lotus miner  |     	/root/go_workspace/v056/lotus/extern/filecoin-ffi/proofs.go:579
1|lotus miner  |     github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).GenerateWindowPoSt
1|lotus miner  |     	/root/go_workspace/v056/lotus/extern/sector-storage/ffiwrapper/verifier_cgo.go:41
1|lotus miner  |     github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
1|lotus miner  |     	/root/go_workspace/v056/lotus/storage/wdpost_run.go:407
1|lotus miner  |     github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).doPost.func1
1|lotus miner  |     	/root/go_workspace/v056/lotus/storage/wdpost_run.go:49
1|lotus miner  |     runtime.goexit
1|lotus miner  |     	/usr/local/go/src/runtime/asm_amd64.s:1373

**Comment by rjan90** [comment]
Are you still seeing this issue, or can this issue be closed now? #rengjøring

**Comment by Reiers** [comment]
**If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.**

Closing the ticket.
