### ISSUE TITLE
chain sync issue

### ISSUE THREAD

**Issue by Icarus9913** [filecoin-project/lotus#3409]
2: Target: [bafy2bzaceasksv7omlevggu3cl2aead447oxbuaggdq7653bwpoildkjtksji bafy2bzacedlqi4asxvwagbtmgocdtkzlumpsyojf5lmqjt3z3sfvd2kl5uvjm bafy2bzacebxunx47mgcxaaopevrhka77g4ldqyvsd77fg7sp5tninrggbm2x4 bafy2bzacecwcyscau525gezynzr7wlqcvgo3glsgzlgo4vrflsbfqoyjqetga bafy2bzacedpecbeaqj5qnwlxv74ewga7b42jrb6grbdwobjqWorker 
2: Target: [bafy2bzaceasksv7omlevggu3cl2aead447oxbuaggdq7653bwpoildkjtksji bafy2bzacedlqi4asxvwagbtmgocdtkzlumpsyojf5lmqjt3z3sfvd2kl5uvjm bafy2bzacebxunx47mgcxaaopevrhka77g4ldqyvsd77fg7sp5tninrggbm2x4 bafy2bzacecwcyscau525gezynzr7wlqcvgo3glsgzlgo4vrflsbfqoyjqetga bafy2bzacedpecbeaqj5qnwlxv74ewga7b42jrb6grbdwobjqWorker 
2: Target: [bafy2bzaceasksv7omlevggu3cl2aead447oxbuaggdq7653bwpoildkjtksji bafy2bzacedlqi4asxvwagbtmgocdtkzlumpsyojf5lmqjt3z3sfvd2kl5uvjm bafy2bzacebxunx47mgcxaaopevrhka77g4ldqyvsd77fg7sp5tninrggbm2x4 bafy2bzacecwcyscau525gezynzr7wlqcvgo3glsgzlgo4vrflsbfqoyjqetga bafy2bzacedpecbeaqj5qnwlxv74ewga7b42jrb6grbdwobjqikwtona5x3qzy]	State: error	Height: 17722^C
Exit by user

**Comment by arajasek** [comment]
There's not enough info to help here, unfortunately
