### ISSUE TITLE
Data transfer can resume a transfer on restart

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#3417]
Currently, when a node shuts down, if data transfers are in progress at that time -- either piece data being transferred for a storage deal or in progress retrievals -- they do not resume when the node restarts.

The end goal of this task is as follows: when I restart my node, any data transfers that were going prior to the node shutdown resume, without resending data already sent from one node to another.

This ticket involves several steps, and a fairly deep knowledge of [go-graphsync](https://github.com/ipfs/go-graphsync), [go-data-transfer](https://github.com/filecoin-project/go-data-transfer), and [go-fil-markets](https://github.com/filecoin-project/go-fil-markets). It's also probably good to familiarize yourself with the relevant portions of the spec to understand theoretical concepts (https://beta.spec.filecoin.io/#systems__filecoin_files__data_transfer , https://beta.spec.filecoin.io/#systems__filecoin_markets -- though please be careful as these specs may be out of date).

I'll outline the approach here, though it's probably best to do in separate pieces and may require some collaboration to get up and running.

What we have so already:
1. The underlying protocol for data transfer is [Graphsync](https://github.com/ipld/specs/blob/master/block-layer/graphsync/graphsync.md). A normal Graphsync request is expressed as a root CID and an IPLD selector (in the broadest sense IPLD selectors are a query language for IPLD graphs, similar to how a SQL is a query language for a relational database).The go-graphsync library has a mechanism to perform a request where the responder is told to not send back certain data the requestor already has. This is the [`graphsync/do-no-send-cids` extension](https://github.com/ipld/specs/blob/master/block-layer/graphsync/known_extensions.md#do-not-send-cids). This extension is already supported in the `go-graphsync` library. 
2. The state of every data transfer is persisted to disk at a high level in the `go-data-transfer` library which uses [go-statemachine](https://github.com/filecoin-project/go-statemachine) to manage state. You can see the existing data transfer state machine definition here (https://github.com/filecoin-project/go-data-transfer/blob/master/channels/channels_fsm.go)

What we need:
1. We need to record data transfer state at a fined grain level in `go-data-transfer`, for the side that is receiving data, in terms the actual CIDs already received, so that we can create a Graphsync request that includes all the CIDs we already have when we restart the transfer.
2. Upon restart of a node, we need to send an event to all tracked data transfers that are not in a terminal state to restart.
3. We need to send a network message to the other end of a data transfer that our node shut down and we need to restart the transfer. The node that shut down could be the receiver of data or the sender of data. If we are the receiver, we can probably just create a new Graphsync request with the relavant CIDs to ignore (plus we'll need to find a way to make sure the request is still validated -- see how data transfer requests are validated in the spec). As sender of data, the receiver will still need to send a new graphsync request, so we'll need to send a seperate message over the data transfer libp2p protocol from sender to receiver to communicate we need a new graphsync request.
4. We'll need to make sure request validators in both storage and retrieval markets in `go-fil-markets` will revalidate a resuming request as well as a new request.

**Comment by TippyFlitsUK** [comment]
Hi Hannah 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks :pray:
