### ISSUE TITLE
Retrieval Client can restart deals on relaunch

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#3418]
As a client, I would like my open retrieval deals to last between restarts, so that they resume when my node comes back online

--

In:

- Retrieval Deals Are Persisted To Disk On Client As they change state
- On restart, in progress deals resume at their most recent state transition

--

Acceptance Criteria:
- Make a retrieval deal
- Shut down client
- Restart client
- Verify deal completes assuming no timeout

**Comment by jennijuju** [comment]
duplicated and tracked in #5442
