### ISSUE TITLE
Retrieval Provider Can Restart In Progress Deals When Relaunched

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#3419]
As a provider, I would like my open retrieval deals to last between restarts, so that they resume when my node comes back online

--

In:

- Retrieval Deals Are Persisted To Disk On Provider As they change state
- On restart, in progress deals resume at their most recent state transition

--

Acceptance Criteria:
- Make a retrieval deal
- Shut down provider
- Restart Provider
- Verify deal completes assuming no timeout

**Comment by jennijuju** [comment]
duplicated #5442
