### ISSUE TITLE
Consider adding a way to unset a miner's on chain addresses

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#3429]
As in title (perhaps something like `lotus-miner actor unset-addrs`).

**Comment by gh3990** [comment]
Any updates here? Please have a look here : https://filecoinproject.slack.com/archives/C0179RNEMU4/p1611103553345000
I changed ISP and this seems a "to have" command to change the on chain public IP, or does it overwrite the current one?
Thank you,
Angelo

**Comment by arajasek** [comment]
@gh3990 It overwrites the current one -- this should just be a "nice to have".

**Comment by gh3990** [comment]
> @gh3990 It overwrites the current one -- this should just be a "nice to have".

Hahahaha, thanks for your reply .... It is a "nice to have" in that case ...

Thanks again

**Comment by rjan90** [comment]
I think this feature has been implemented? At least there is an `--unset` option in the `lotus-miner actor set-addrs`

```
lotus-miner actor set-addrs -h
NAME:
   lotus-miner actor set-addrs - set addresses that your miner can be publicly dialed on

USAGE:
   lotus-miner actor set-addrs [command options] [arguments...]

OPTIONS:
   --gas-limit value  set gas limit (default: 0)
   --unset            unset address (default: false)
   --help, -h         show help (default: false)
```

**Comment by rjan90** [comment]
Looks like the unset overwrites the current addrs with an empty address-string:
https://github.com/filecoin-project/lotus/blob/cafb110f420e453b26b19a5a025d5520d5087ee9/cmd/lotus-miner/actor.go#L74-L76

So I guess this issue can be closed now! 📪
