### ISSUE TITLE
0.5.6 doesn't assign PC1 / AP to worker if its already doing 1 PC1

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#3432]
**Describe the bug**
I think this speaks for itself:
```
ID  Sector  Worker  Hostname  Task  State        Time
51  61      2       sealer2   C2    running      49m15.7s
59  59      0       filecoin  GET   running      35m17.2s
5   58      3       sealer    PC1   running      17m29.8s
0   64      0       filecoin  AP    assigned(0)  30.1s
0   65      0       filecoin  AP    assigned(0)  24.2s
0   66      0       filecoin  AP    assigned(0)  22s
0   67      0       filecoin  AP    assigned(0)  19.8s
0   68      0       filecoin  AP    assigned(0)  16.4s
```

`sealer` can perfectly handle 2 PC1's at the same time. It used to work.

**To Reproduce**
Pledge sector
Wait 20 minutes
Pledge sector

**Expected behavior**
2 PC1's being done at worker 3

**Version (run `lotus version`):**
0.5.6

**Comment by RobQuistNL** [comment]
Restarted worker 3 and weird stuff now happens:
```
       GPU: GeForce GTX 1080 Ti, not used
ID  Sector  Worker  Hostname  Task  State        Time
51  61      2       sealer2   C2    running      54m46.7s
60  67      0       filecoin  AP    running      2m32.9s
61  64      0       filecoin  AP    running      2m32.9s
62  68      0       filecoin  AP    running      2m32.9s
63  66      0       filecoin  AP    running      2m32.9s
64  65      0       filecoin  AP    running      2m32.9s
0   59      4       sealer    GET   running      33.1s
0   58      4       sealer    PC1   assigned(0)  33.1s
```

worker 0 can only handle 2 PC1's at the same time so I have no idea why its doing AP 5 times.

Worker 3 now got assigned a PC2 which its first going to fetch (the files are already on that machine)
Worker 3 has a PC1 assigned for the future 
Doing another pledge added the following:
```
0   69      4       sealer    AP    assigned(0)  17.3s
```

**Comment by RobQuistNL** [comment]
PC1 and AP can be done during the `GET`, because its going to take > 1h the worker is basically just wasting time

**Comment by rjan90** [comment]
I think this issue has been fixed with the newer lotus versions, or are you still seeing these? #rengjøring

**Comment by RobQuistNL** [comment]
No idea, not sealing on this machine anymore. Closing the issue here - if someone else has it feel free to comment or reopen a new one :)
