### ISSUE TITLE
Feature: PaychAPI: PayChFundsNeededForVoucher

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#3435]
We need an API we can use to determine if we have enough funds in the channel to create a voucher in the given lane for the given amount:

```golang
PayChFundsNeededForVoucher(ctx context.Context, pch address.Address, amt types.BigInt, lane uint64) abi.TokenAmount
```

This can probably be implemented by:
- creating a voucher
- running totalRedeemedWithVoucher
- loading the actor state
- comparing it to Balance for the actor state

This is essentially the same logic run by CheckVoucherValid but just runs the section comparing act.Balance to totalRedeemedWithVoucher and returns the actual difference, if totalRedeemedWithVoucher > act.Balance (it can return zero otherwise).

**Comment by dirkmc** [comment]
https://github.com/filecoin-project/lotus/pull/3448 should provide equivalent functionality to the proposal here
