### ISSUE TITLE
Nodes falling behind

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/lotus#3452]
@schwartz10 has confirmed the PL space race node that backs the faucet has fallen behind --> it reports a Height of 20545, where the right height (seems like) ~ 22180 (as he send this message).

**Comment by mishmosh** [comment]
May be related to #3454

**Comment by ArseniiPetrovich** [comment]
Can confirm we are experiencing this on _ALL_ of our hosted endpoints.

**Comment by mishmosh** [comment]
Via @arajasek: This is under investigation. https://github.com/filecoin-project/lotus/pull/3457 from @Kubuxu may help, but still looking for root cause.

**Comment by symanovich-a** [comment]
I found this unusual errors in logs. The cpu usage was decreased after this, but memory increased. time utc+0, 1 september. 
```
- temporal error
[31mERROR[0m	chain	chain/sync_manager.go:389	sync error: collectChain failed:
- temporal error

```
![image](https://user-images.githubusercontent.com/30037350/91967428-e62f9780-ed1b-11ea-9e27-b79abed4e332.png)

**Comment by Kubuxu** [comment]
@symanovich-a the only reason for this error is that you got a block with timestamp in the future. Make sure your local clock is in sync (ntp).

**Comment by jennijuju** [comment]
latest release should have this improved, create new ticket if the issue still exists with latest version
