### ISSUE TITLE
Massive amounts of disk I/O on daemon

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#3454]
**Describe the bug**
The daemon process uses more and more disk I/O until it freezes the system or breaks down entirely. Eventually it will lag behind - a restart helps. (related: https://github.com/filecoin-project/lotus/issues/3452)

**To Reproduce**
Run daemon

**Expected behavior**
Daemon using a normal amount of disk I/O

**Screenshots**
Logs are filled with:
```
2020-09-01T16:22:14.713Z	INFO	pubsub	go-libp2p-pubsub@v0.3.5/pubsub.go:927	received message from router graylisted peer 12D3KooWGMkTrSqAkqAwkT1rpKzRJ9BFZDKY6svL5Xmd36XNKVD3. Dropping RPC
```
and
```
2020-09-01T16:22:14.769Z	WARN	pubsub	go-libp2p-pubsub@v0.3.5/score.go:686	unexpected rejection trace: message from 12D3KooWRv7pMTAJLK9mUhJCrbBCDWn7J7UDiBxTEjFnGQ1QNY8q was first seen 2m10.187623127s ago and has delivery status 1
```
(thousands per minute)

Disk I/O;
![image](https://user-images.githubusercontent.com/1442796/91880070-77513080-ec80-11ea-981f-120daa51c795.png)
![image](https://user-images.githubusercontent.com/1442796/91880473-9223a500-ec80-11ea-9999-7feaba72e9c1.png)
![image](https://user-images.githubusercontent.com/1442796/91880582-994ab300-ec80-11ea-8bdf-504da540be92.png)
![image](https://user-images.githubusercontent.com/1442796/91880757-c6976100-ec80-11ea-9dac-1b15fb929778.png)

Other people having issues:
![image](https://user-images.githubusercontent.com/1442796/91880211-80420200-ec80-11ea-81cd-93acb95484fc.png)

Mostly .vlog and .sst files are opened by the millions of processes

**Version** 0.5.6

**Comment by Meatball13** [comment]
Same issue here.  Have been able to limit some of the impact by not logging the daemon to disk and `lotus-miner log set-level warn` but it doesn't mean the huge amount of traffic still isn't hitting the box.  I'm finding PC1's on the box with the Daemon are taking 5.5 hours compared to 3.5-4 hours on a machine that has the exact same hardware, but is just running a worker process.  So there's definitely some impact to the daemon/lotus-miner box.

**Comment by whyrusleeping** [comment]
@RobQuistNL Are you by chance writing your logs to disk?

**Comment by vyzo** [comment]
fix in https://github.com/libp2p/go-libp2p-pubsub/pull/383

**Comment by Kubuxu** [comment]
For now try calling `lotus log set-level --system pubsub error` it might help.

**Comment by RobQuistNL** [comment]
@whyrusleeping yes, but the writes are not the problem - there's an insane amount of disk reads on datastore / block / vlog files.

**Comment by Kubuxu** [comment]
Hmm, it might be the GC but not sure. As we don't free any space in badger right now, we can try disabling it.

**Comment by Kubuxu** [comment]
You can try: https://github.com/filecoin-project/lotus/pull/3457 to check if it helps

**Comment by jennijuju** [comment]
@RobQuistNL did #3457 helped? Are we ready to close the ticket?

**Comment by RobQuistNL** [comment]
Don't know, not sure either, because I solved it by blocking a ton of IP's. So I'll unblock those and maybe it won't happen again.. I mean it could be that they stopped sending messages because SR1 is over though 🤷

**Comment by RobQuistNL** [comment]
Just checked, and this is still happening. Caused my miner to be REALLY slow and the chain started to lag behind. Just restarted and its catching up 400 epochs ..

**Comment by rjan90** [comment]
I think this issue has been fixed on the newer versions of Lotus? #rengjøring

**Comment by RobQuistNL** [comment]
I don't think I've ever seen this happen again, so it might very well be fixed. Allthough I have to say the miner that had these issues is not sealing anymore and is just proving now :)
