### ISSUE TITLE
Scheduler deadlocking

### ISSUE THREAD

**Issue by hyunmoon** [filecoin-project/lotus#3460]
**Describe the bug**

**To Reproduce**
1. Connect all workers to lotus-miner (200+ of them)
2. Run `lotus-miner sectors pledge`
3. Find out all workers stay idle.
4. Run `lotus-miner sealing sched-diag`.
5. Process hangs indefinitely
6. I press ctrl+z.
7. There are 2 PIDs for `lotus-miner`.
8. `lotus-miner` does nothing no matter how long I wait.
9. `lotus-miner stop` doesn't work either. The processes have to be killed.

**Expected behavior**
NO JAMMING when calling `sealing jobs list`, `sealing workers list`, and `sealing sched-diag`. Please!
Jamming after running these commands seems to be the byproduct of sched deadlocking not the cause.

**Screenshots**
![report](https://user-images.githubusercontent.com/2242149/91904767-6df7b080-ece0-11ea-979a-dd78e9204e5a.JPG)

**Version (run `lotus version`):**
`0.5.7+git.b8bbbf3e`
(Compiled on latest mater and applied PR #3445.

**Additional context**
Sched has never been reliable from testnet phase 2 (when I started mining).
I've suffered from deadlocking issue for a long long time. Version 0.5.7 is bad enough to finally make me file a bug report.
The most reliable one I've tried was version 0.5.3. 0.5.7 is worst I've ever used.

**Comment by jennijuju** [comment]
[comment](https://filecoinproject.slack.com/archives/CP50PPW2X/p1598981676057300) from another miner that is related to this issue

**Comment by magik6k** [comment]
Can you get a goroutine dump when this happens (`lotus-miner pprof goroutines > goroutines`), and send it here?

**Comment by hyunmoon** [comment]
@magik6k 
[goroutines.log](https://github.com/filecoin-project/lotus/files/5158973/goroutines.log)

I'll collect more dumps whenever I experience it from now on.
