### ISSUE TITLE
[Chain Sync Error] Chain linked to block marked previously as bad

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3462]
- Lotus version: 0.5.7

- Some miner is having issue with syncing due to the following error:

```bash
Error: chain contained block marked previously as bad ([bafy2bzaceaelesu4e745l4ihv45vg4mrcsvx5jy6y5j7hd62w6m3eqqbiwf4q bafy2bzacea3da4n34ty4snlorc3w2wzcuom5bpqasvoj6on2ytxdkrdw6mnxy bafy2bzacecr2njzvs6guogez7dityjfyfsztmarhpeuuv7cvsco6cpjsmj6mq bafy2bzacedchr3adsoi4wflz3iemhurl46asxg36qbjdtkch7omey4xhbvu4u], bafy2bzacealwmvpfwy73k3h63iolh3abghekute2s33f2rphi2p3vlhufdym6) (reason: 1 error occurred:
	* invalid election post:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func10
        /root/lotus/chain/sync.go:854
  - getting winning post sector set:
    github.com/filecoin-project/lotus/chain.(*Syncer).VerifyWinningPoStProof
        /root/lotus/chain/sync.go:936
  - getting partition array:
    github.com/filecoin-project/lotus/chain/stmgr.GetSectorsForWinningPoSt.func1.1
        /root/lotus/chain/stmgr/utils.go:199
  - failed to load partitions: failed to root: EOF
```

and

```bash
Error: chain linked to block marked previously as bad ([bafy2bzacedwwvghqtg56jb3ylvfrp577esmh2xr54cbyulnfocxa3pihpl4lw], bafy2bzacedn4xe2e5tmq5fbrecixtnfrxlfkllvivqccpodvo4woxjbdhoda6) (reason: linked to bafy2bzacedfwiyzgmoziz46xeuqhlbsxwhobvjyy36cl7t7qaqgvbp5lzggls caused by: [bafy2bz
acebfbqpf3k4kz72p4zlmcidmo2dnfz5ja6rgxrjtzck4m4ii
2q4geu] 1 error occurred:
        * invalid election post:
    github.com/filecoin-project/lotus/chain.(*Syn
cer).ValidateBlock.func10
        /root/lotus/chain/sync.go:871
  - failed to verify election post:
    github.com/filecoin-project/lotus/chain.(*Syn
cer).VerifyWinningPoStProof
        /root/lotus/chain/sync.go:963
  - Rust panic: no unwind information
    github.com/filecoin-project/filecoin-ffi.Veri
fyWinningPoSt
        /root/lotus/extern/filecoin-ffi/proofs.go
:90
    github.com/filecoin-project/lotus/extern/sect
or-storage/ffiwrapper.proofVerifier.VerifyWinning
```

**Comment by lionsoul2014** [comment]
Seams like no one care about this serious problem.....
How to keep things going if the lotus daemon crash ????? How to keep going with the spacerace ???

@jennijuju @mburns @vyzo 

https://github.com/filecoin-project/lotus/issues/3404

**Comment by jennijuju** [comment]
> #3404
> 
> Seams like no one care about this serious problem.....
> How to keep things going if the lotus daemon keep crashing ?????
> 
> @jennijuju @mburns @vyzo
> 
> @whyrusleeping How should we keep going with the spacerace, because of we are not lucky enough ?
> 
> hundreds of sectors After the PreCommit2 are waiting to land on the chain and hundreds of of sectors After the SealCommit2 are waiting for the landing confirm from the chain. but the lotus daemon were crash and stop synchronize blocks. i've try restart it for many times and this fucking problems comes again and again soon.
> 
> Should we keep restart the lotus daemon or quit the game ?



> #3404
> 
> Seams like no one care about this serious problem.....
> How to keep things going if the lotus daemon keep crashing ?????
> 
> @whyrusleeping @travisperson How should we keep going with the spacerace ?
> 
> hundreds of sectors After the PreCommit2 are waiting to land on the chain and hundreds of of sectors After the SealCommit2 are waiting for the landing confirm from the chain. but the lotus daemon were crash and stop synchronize blocks. i've try restart it for many times and this fucking problems comes again and again soon.
> 
> Should we keep restart the lotus daemon or quit the game ?

**(not related to the issue)** I understand your frustration, however saying `Seems like no one care about` is really NOT necessary, our team is working really hard on improving FIlecoin and definitely take community's feedback seriously. Please have some patience and give the team more time to get to the ticket. Thanks for your understanding!

**Comment by jennijuju** [comment]
Another error message

**Comment by jennijuju** [comment]
> Another miner is facing the same issue
> 
> * error message
> 
> ```shell
> 2020-09-02T11:50:08.320+0900	ERROR	chain	chain/sync_manager.go:389	sync error: collectChain failed:
>     github.com/filecoin-project/lotus/chain.(*Syncer).Sync
>         /home/filecoin/lotus/chain/sync.go:526
>   - chain linked to block marked previously as bad ([bafy2bzaceaibrs5xqes4a2wl3yt4ujd6n6pynkh7bxkce7kezp3p56de2jcae bafy2bzacealeeftuvlygu4zfn3fqwnzn3vay6e3xtouxg3w3vjp62hscehqjs], bafy2bzaceaxtbkt7m5hvq2k6s333j7q2366xcevseym3esdmri7mv4j4mrkc6) (reason: linked to bafy2bzaced6coble5th3x6zt54l4mvoc5ei33uoxbb4jqyqvquoviyah2md4e caused by: [bafy2bzaced56regll2itetldnzbs2up4putgjjtdshwdtzybtjjbkif3ebm6s] parent state root did not match computed state (bafy2bzaceara724adngtlhu2cxpmaxmsjldbnx6iduf4i7wwkozudncg7tnim != bafy2bzaceaseslukmrl2qfbc7ovbdknlfuxc2kwqxj54fih4xfuwdtslxrqwi)):
>     github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
>         /home/filecoin/lotus/chain/sync.go:1194
> ```

Update: restarting the daemon resolve it for this miner.

**Comment by axzmin** [comment]
restarting the daemon will fine a  few minutes !

**Comment by lionsoul2014** [comment]
This usually happen when there are to much pending messages in the mpool since i won't saw anything like this when the daemon running with no api interactive with miner.

@axzmin @jennijuju 
Running the daemon on a separate machine and provide a better network env will help.

for the daemon machine, open the /etc/sysctl.conf and the /etc/security/limits.conf to increase the default max socket connects and the max open files limits will also help.

i've troubled with problem for over 4 days and it now workers much better.

**Comment by axzmin** [comment]
@lionsoul2014 
How to set the  /etc/sysctl.conf and the /etc/security/limits.conf ?
Can you tell me? thanks!

**Comment by hengic** [comment]
Hi, guys:
My sync problem is different than yours. I finally solved it by changing NVMe SSD. I see many issues were caused by chain data inconsistent or corrupted. So, I guess it may an issue of storage hardware. It looks stable now after replacing it.
