### ISSUE TITLE
Filecoin.ClientRetrieve timeout 43200 Seconds

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3466]
Quite a few of people reported this issue, and this is affecting their deal success.

> Note: people who has updated to 0.5.7 is also still having the issue.

**Comment by johnli-helloworld** [comment]
I have the same problem

**Comment by Reisen** [comment]
To help with debugging, my miner is currently experiencing dealbot problems for both retrieval and deals that did not happen pre-upgrade. I think this problem is also related to the `DealStatusFundsNeeded` error state for retrievals. Below I'll include logs for both.

### Miner Details
Miner ID: t02533
Miner Page: https://spacerace.filecoin.io/deals/t02533

I've seen a drop from 45% Deal and 50% retrieval to 37% Deal and 5% retrieval over the last 6 hours, with my retrieval rate experiencing a huge drop almost instantly almost purely due to this error. Here are the failed Data CIDs of the failed retrievals:

### Failing Retrievals with 43200 timeout
```
bafk2bzacea73b5xesuf7clpf64hxky7335minkri2s47zf2ofxclewn2t6f2u
bafykbzacebyyypnmhp27s7qwjufoe73lcwtucjb3la2kxwhn7hllzfhq675ri
bafykbzacedcmgo4fdwm2d6q6nencts7aozk3cfvkzcmlrtjkgpdvkpzkzaxso
bafk2bzacea333mcfawjcmlyjfsrahwb5s3tefrsxem327e5lfojuo5sljfndq
bafykbzacedr4p7x2vuikplvlk5t77q5byir6purk5pukf5eraoy6sx5kko46q
bafk2bzacecmcbzbll64xsw4fqy5fzovjoyssfmidb3piigansku26cgleou2m
bafk2bzacecuvnyqgtqcuay6bsak3zkgllgtz2ayrbpqcpxplvws6q5mavewuy
bafk2bzacedjpffhvwicbwcbzasapk5r6sbq5alqyxtcsc7yi5vfjuczeospiq
bafykbzacedpaqyzhr2r7bqnxot25qlyjehym2wptpt7bybg74vauszaip6dk6
bafykbzaceb6hd53nxiibi3enzzbdmo6xhaiiopbndrwhbodgqeprsm2py47wc
bafk2bzacebhbla7oyoyjyyesjwlvdcngmxsrv5vzdxmuyyndmk2akurmyjkhc
bafk2bzacea7muxkk3i7lrgt4tp3vhwhvq7ptmoqm5vl652rdlkmlzety4jf2k
bafykbzaced77gnnjr5guoboficabxpybtsic4kmrtt2ler4ozlxdwr5u5mfae
bafykbzacedmwns3w2r2wscaj6nw6cdyj4mghhzwna2mt2jyfevmlonag3qd3q
bafykbzaceakoj2hrvioww2hbbtdkemza6etixour3xsdnwqwsoabxiycyskbq
bafykbzacebacwsry7ljxpg5dwac7ndkbzoc2fxtxluj7dhbzvlnu6dwikmjl2
bafykbzacea3oyw4cxpg52a6f6h2ssurip7woce3d23xntbmrsehlngmtb7wcc
```

### Failed Retrieval Status from Miner
And here is the output of `lotus-miner retrieval-deals list`:

```
Receiver                                              DealID  Payload      State                  PricePerByte  BytesSent  Message
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1785    ...gmtb7wcc  DealStatusFundsNeeded  2             1053786
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1787    ...dwikmjl2  DealStatusFundsNeeded  2             1053786
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1790    ...iycyskbq  DealStatusFundsNeeded  2             1053786
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1792    ...nag3qd3q  DealStatusFundsNeeded  2             1053786
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1860    ...r5u5mfae  DealStatusFundsNeeded  2             1053786
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1862    ...ety4jf2k  DealStatusErrored      2             65536      deal data transfer failed: routing: not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1864    ...urmyjkhc  DealStatusErrored      2             65536      deal data transfer failed: routing: not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1867    ...m2py47wc  DealStatusFundsNeeded  2             1053786
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2519    ...zaip6dk6  DealStatusFundsNeeded  2             1053786
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2521    ...czeospiq  DealStatusErrored      2             65536      deal data transfer failed: routing: not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2591    ...5mavewuy  DealStatusErrored      2             65536      deal data transfer failed: routing: not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2594    ...cgleou2m  DealStatusErrored      2             65536      deal data transfer failed: routing: not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2633    ...x5kko46q  DealStatusFundsNeeded  2             1053786
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2639    ...5sljfndq  DealStatusErrored      2             65536      deal data transfer failed: routing: not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2646    ...pzkzaxso  DealStatusFundsNeeded  2             1053786
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2654    ...fhq675ri  DealStatusFundsNeeded  2             1053786
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2657    ...wn2t6f2u  DealStatusErrored      2             65536      deal data transfer failed: routing: not found
```

If there's any more information I can provide, let me know, I can include it.

**Comment by std** [comment]
t08285
I have the same issues (43200 seconds timeout) 
In fact I have no single succesfull retrieval deal.
output of lotus-miner retrieval-deals list:

`12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2627    ...cshg7v7e  DealStatusErrored    2             0          channel not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  282     ...hr6evkzy  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  3776    ...5kuspubc  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1655    ...rqnhmdba  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  3731    ...7wnjvoaa  DealStatusErrored    2             0          channel not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2064    ...5d72jevs  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  4865    ...4boikxn4  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5222    ...ztz7bffy  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1826    ...yhbq7bjc  DealStatusErrored    2             0          channel not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2002    ...ma6qaybi  DealStatusErrored    2             0          channel not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2135    ...v52zpvqg  DealStatusErrored    2             0          channel not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  3684    ...g26q3xyq  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  3800    ...m7hd3xsg  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1645    ...47jmmudm  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  3979    ...pgvpreh2  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5079    ...vnyv3vne  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1892    ...wncsyefo  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  6011    ...rfuxeua2  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1996    ...w2cgns6y  DealStatusErrored    2             0          channel not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2136    ...hfw3h6km  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5710    ...hkl7i4au  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1910    ...lmidibd4  DealStatusErrored    2             0          channel not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  3806    ...xqym37w4  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  949     ...ggyccgqo  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1905    ...ifa3dcno  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  3555    ...ldrcze6q  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5711    ...lqk5f44q  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  577     ...w4y22wx6  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  729     ...5grgzg6q  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  796     ...cco5hnky  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1912    ...r3pbr5uy  DealStatusErrored    2             0          channel not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  273     ...b6ixche4  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  3675    ...yk7ise6q  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5174    ...b6ixche4  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1898    ...njcyf4lm  DealStatusErrored    2             0          channel not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  547     ...hkl7i4au  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  3803    ...pn62a7cm  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1547    ...hywt44mk  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1748    ...hc5nx64m  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  3984    ...6yhsxzcq  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5725    ...omla35bq  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5794    ...cco5hnky  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  4301    ...o3erssb2  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  4195    ...ldrcze6q  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  4347    ...j4gtdqsi  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  491     ...57ibk7bg  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  544     ...lqk5f44q  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  2972    ...hfw3h6km  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  3702    ...3tcb4fx4  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5198    ...crbjeugg  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1986    ...e4wt4hyo  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  807     ...5grgzg6q  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2005    ...nlwck44q  DealStatusErrored    2             0          channel not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  40      ...uavqpxdy  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  4196    ...zexaouzi  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  4203    ...hmimhrb4  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1095    ...7wnjvoaa  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1640    ...gqvhzu2c  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  2881    ...w2cgns6y  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1990    ...h47y52qs  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5210    ...uavqpxdy  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5785    ...jiyeg3vk  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  2979    ...v52zpvqg  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  3678    ...6oqtu34i  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  634     ...hywt44mk  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1019    ...3tcb4fx4  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5085    ...wjrw77pc  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  875     ...w4y22wx6  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1901    ...hh6ocw4s  DealStatusErrored    2             0          channel not found
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  3680    ...oxpwfcvi  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  803     ...jiyeg3vk  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1740    ...p3p3j3zg  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1755    ...jhyutvsy  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5170    ...hr6evkzy  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5895    ...5odrozvy  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  3668    ...crvibgaw  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  486     ...omla35bq  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  3551    ...zexaouzi  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  419     ...ztz7bffy  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  4293    ...sttn2dv4  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1183    ...vrlhha5w  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  2859    ...nudkdtgs  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5090    ...zh3dirbk  DealStatusUnsealing  2             0          
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5698    ...hywt44mk  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  101     ...crbjeugg  DealStatusErrored    2             0          Context Cancelled
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  2007    ...hhq2ioek  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  1553    ...lqk5f44q  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  3585    ...j4gtdqsi  DealStatusErrored    2             0          Context Cancelled
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  3664    ...ggyccgqo  DealStatusErrored    2             0          channel not found
12D3KooWHBabDYNPgk8ZYZvF6Bc68N5DY6oajQsU9862QABnHJsd  5723    ...57ibk7bg  DealStatusUnsealing  2             0          
12D3KooWBCrD2N1oPskRH1L3LZGVnUU5up4t7QjRt4bPbus23XTU  1013    ...s55bu2n2  DealStatusErrored    2             0          channel not found`

**Comment by coder-lb** [comment]
This issue also occurs for some people. All storage deals are successful. Some of retrieval deals are successful, while some report such erros:   
`
Filecoin.ClientRetrieve timeout 43200 Seconds
`

Has it been sovled?

**Comment by danny-wu** [comment]
Confirm I am experiencing this issue, however my retrievals are stuck at Unsealing. 
```

miner@miner0:~$ lotus-miner retrieval-deals list
Receiver                                              DealID  Payload      State                PricePerByte  BytesSent  Message
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  2267    ...ytbscciq  DealStatusUnsealing  2             0          
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  25      ...4wua6oeo  DealStatusUnsealing  2             0          
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  663     ...fqj6wf7y  DealStatusUnsealing  2             0          
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  1277    ...fqj6wf7y  DealStatusUnsealing  2             0          
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  1498    ...hpslzjds  DealStatusUnsealing  2             0          
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  1749    ...cekes2au  DealStatusUnsealing  2             0          
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  1961    ...i75djpnk  DealStatusUnsealing  2             0          
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  2162    ...2l57h3ni  DealStatusUnsealing  2             0          
```

Miner: t014365

Version: 0.5.10

**Comment by danny-wu** [comment]
Root cause and fix:

https://github.com/filecoin-project/lotus/issues/3616#issuecomment-688382442

Thanks to @meatball13 for identifying the fix

**Comment by jennijuju** [comment]
People are experiencing the issue even with Danny's work around above after 0.6.0.

check out this [thread](https://filecoinproject.slack.com/archives/C0179RNEMU4/p1599679141200300)

**Comment by jennijuju** [comment]
Track in #3762
