### ISSUE TITLE
ClientQueryAsk failed to open stream to miner: failed to dial 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3467]
After the bot restarted yesterday, some miners are getting more `ClientQueryAsk failed errors`

lotus version: 0.5.6 & 0.5.7

- Errors:
1. ClientQueryAsk failed : failed to open stream to miner: failed to dial 12D3KooWHGA8SpRtc1aVfhKQk3odRQBCpouUGY1kBWjGLZRPFAZJ: all dials failed * [/ip4/221.228.238.110/tcp/23456] dial tcp4 0.0.0.0:1235->221.228.238.110:23456: i/o timeout
2. ClientQueryAsk failed : failed to open stream to miner: failed to dial 12D3KooWHS66EuJ6WpgadiJWeuqkYmECavDsy8jUZ6aWpBd3taX7: all dials failed * [/ip4/70.182.142.218/tcp/6139] failed to negotiate security protocol: read tcp4 10.66.62.247:1235->70.182.142.218:6139: read: connection reset by peer
3. ClientQueryAsk failed : failed to open stream to miner: failed to dial 12D3KooWQ3c9CscaFyBbZcVYreTDCQAttS4g5NxomEDiSV7ZHStV: all dials failed * [/ip4/27.50.142.61/tcp/2349] dial tcp4 27.50.142.61:2349: connect: connection refused * [/ip4/8.210.89.98/tcp/2347] failed to negotiate security protocol: read tcp4 10.66.62.247:1235->8.210.89.98:2347: read: connection reset by peer

- Some of the miner Ids for checking logs:
[t01280](https://spacerace.filecoin.io/deals/t01280)
[t03482](https://spacerace.filecoin.io/deals/t03482)
[t03328](https://spacerace.filecoin.io/deals/t03328)
[t09848](https://spacerace.filecoin.io/deals/t09848)

Note:
Most of them [checked connectivity](https://spacerace.filecoin.io/check ) and it returns  successful.

**Comment by yablu** [comment]
Same error with https://spacerace.filecoin.io/deals/t08403

**Comment by yablu** [comment]
This appears to be happening to many miners today. Is there anything we can do?

**Comment by jennijuju** [comment]
was connection issue - not lotus related
