### ISSUE TITLE
resolve address t1663mtewy2pxia5donfgobialxc5ufdn2hlhbcwa: actor not found

### ISSUE THREAD

**Issue by yangwb** [filecoin-project/lotus#3468]
miner@Miner_10140:~$ lotus client deal bafk2bzacecytz2hgboi5obt4mno22dbu6ojt37cj3qwcoddiec3jip5a7kn7s t016359 0.0000000005 518400
ERROR: resolve address t1663mtewy2pxia5donfgobialxc5ufdn2hlhbcwa: actor not found

anyone can tell me why please?

**Comment by jimpick** [comment]
Did you send funds to that address? If you just use `lotus wallet new ...` but don't send any funds to it, it doesn't exist on chain yet.

**Comment by yangwb** [comment]
lotus send t1663mtewy2pxia5donfgobialxc5ufdn2hlhbcwa 50
ERROR: GasEstimateMessageGas error: estimating gas used: CallWithGas failed: call raw get actor: resolution lookup failed (t1663mtewy2pxia5donfgobialxc5ufdn2hlhbcwa): resolve address t1663mtewy2pxia5donfgobialxc5ufdn2hlhbcwa: actor not found

**Comment by arajasek** [comment]
@yangwb You need to use `lotus send --from=<address that already has some funds> t1663mtewy2pxia5donfgobialxc5ufdn2hlhbcwa 50`.

You can get some funds from the faucet: https://spacerace.faucet.glif.io/
