### ISSUE TITLE
Markets: Flaky Tests

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#3471]
https://app.circleci.com/pipelines/github/filecoin-project/go-fil-markets/1043/workflows/1fe43185-f370-4dc1-bd83-d82336d37038/jobs/5074

### Flaky Tests So Far

Storage Integration

- [ ] TestMakeDealOffline
- [ ] TestMakeDealNonBlocking

Retrieval Integration

- [ ] TestClientCanMakeDealWithProvider - impl
- [ ] TestClientCanMakeDealWithProvider - impl

**Comment by Stebalien** [comment]
@aarshkshah1992 thinks we can close this (we've fixed a bunch of bugs here and haven't noticed any more issues)
