### ISSUE TITLE
ReadPiece return ???

### ISSUE THREAD

**Issue by phantom-rabbit** [filecoin-project/lotus#3477]
![image](https://user-images.githubusercontent.com/49083897/91956807-c73efe80-ed37-11ea-8892-ffff484d81c8.png)

github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go 409
maybe retun true nil

**Comment by Reiers** [comment]
Hi @phantom-rabbit 

Thanks for the report. The issue is outdated and have gone stale.

If this is not resolved in [latest release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1) - please open a new ticket - Thank you !
