### ISSUE TITLE
cant listen extern ip while set api port

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/lotus#3506]
cant listen extern ip while set api port

![image](https://user-images.githubusercontent.com/41407352/92076834-d1bbcf80-eded-11ea-963e-5214baa2b46a.png)

do not fix 127.0.0.1 when set api flag
version: master

**Comment by Reiers** [comment]
Hi @hunjixin 

Thanks for the report. The issue is outdated. 

If this is an issue in [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1) - please open a new ticket.

Thanks again !
