### ISSUE TITLE
Will nerpa officially go live?

### ISSUE THREAD

**Issue by woody-yang** [filecoin-project/lotus#3509]
My machine only has 2G memory. I am waiting for nerpa to go online because it only uses 512mb of memory. When will nerpa go online?

**Comment by mishmosh** [comment]
Hi @woody-yang, the nerpa devnet is currently live. 

- Use Lotus release tag ntwk-nerpa-8.28.0.
- Tools: https://stats.nerpa.interplanetary.dev & https://faucet.nerpa.interplanetary.dev.
- If you are a storage developer, miners t01000, t01001, t01002 are currently auto-accepting storage deals.
- More details at network.filecoin.io

If you have any other questions, please join the #fil-net-nerpa channel in Slack.
