### ISSUE TITLE
lotus-lite mode

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#3532]
Adding light client functionality to lotus should be pretty straightforward. 

Functionality changes:
- start up daemon with `lotus daemon --lite`
- Don't sync the chain
- Fetch current chain head from some public API (trusted)
- make chainstore and statemanager be backed by bitswap
- opt out of gossipsub topics (could also stay subscribed to blocks topic, potentially useful)

**Comment by whyrusleeping** [comment]
The first thing we need to do here is to actually just get that public API set up. I think this can just be a lotus node with the ChainNotify rpc exposed (though we need to take care to not lock up everything if the other end doesnt process the updates)

**Comment by 362228416** [comment]
Can be used?

**Comment by arajasek** [comment]
Status update from @dirkmc:

Currently the lite client work is behind a hidden flag (lotus daemon --lite). You can:
- Do wallet / multisig operations
- Make markets CLI / API calls as a client
