### ISSUE TITLE
ShimCall error handling is full of dragons

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#3548]
We should not be using numerical exit codes there
https://github.com/filecoin-project/lotus/blob/a081dc7674727b774adbfb5778157fffc3911aa7/chain/vm/runtime.go#L111-L148

**Comment by arajasek** [comment]
@Kubuxu Duplicate of / subsumed by https://github.com/filecoin-project/lotus/issues/3015 maybe?

**Comment by raulk** [comment]
@alanshaw is tackling this one, in the context of the test failures he found. @alanshaw, mind elaborating on what you're doing here?

**Comment by raulk** [comment]
@Kubuxu also, mind quickly listing the dragons here (besides the numerical exit code use)?

**Comment by Kubuxu** [comment]
Yeah, it is mostly the numerical exit codes that are completely wrong.
We will also need to figure out an exit code for the non-actor panic.

**Comment by alanshaw** [comment]
I'm hoping that https://github.com/filecoin-project/lotus/pull/3697 is an ok solution for one of these numerical exit codes 🤞

**Comment by magik6k** [comment]
No longer relevant in the FVM world
