### ISSUE TITLE
Do not re-compute window PoSt on revert

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#3560]
Currently, lotus will re-compute a window PoSt whenever it sees the chain revert back to the previous deadline. However, this isn't necessary as the window PoSt randomness is based on _drand_ (which won't change).

Instead, we should:

1. Split the window PoSt process into two parts: proof generation, and message generation.
2. On revert, do _not_ restart the proof generation.
3. If we revert past the ChainCommitEpoch, re-generate the window PoSt message with the new randomness, and re-submit it.

**Comment by dirkmc** [comment]
Proposed implementation:
- Split the window PoST process as suggested above:
  1. Proof generation
  2. Getting beacon randomness & Submitting message to chain
- Start Proving once we're at the deadline start height (with zero confidence)
- Start Beacon randomness + submit to chain once both
  - Proving is complete
  - We're at the deadline start height + confidence

I propose integrating the [Finite State Machine](https://github.com/filecoin-project/go-statemachine/tree/master/fsm) library into the `WindowPoStScheduler` with states:
- Start
- Proving (proof generation)
- ProvingComplete (waiting for proof + deadline start height + confidence)
- Submitting (getting beacon randomness & submitting message to chain)
- Complete

State changes would be triggered by changes in the chain height.

If the chain reverts to the previous deadline while we're in the `Proving` state, a state change would not be triggered. When the proof completes the scheduler would remain in `ProvingComplete` until the chain reached the required height.
