### ISSUE TITLE
NOT WORK FAUCET

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#3573]
**Describe the bug**
Couldn't get a few gas from faucet because account is too new.  My github account has been created more than two days ago.
What else can I check?
My Wallet is t3qsfhccnnrolpihfqtmzv7rxnwwdtvv5tlorsvdvhdo72h5q5kfohhgrvphjh4v75dcnucolqqu47573n54ja
**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**
![toonew](https://user-images.githubusercontent.com/70571701/92300573-0a4add00-ef97-11ea-81ae-ea52921f3928.png)

**Version (run `lotus version`):**
Daemon:  0.5.8+git.5426ef0b+api0.14.0
Local: lotus version 0.5.8+git.5426ef0b

**Additional context**

**Comment by shepf** [comment]
I have the same problem. FAUCET is not work now ?

**Comment by hsjw12** [comment]
Exactly I don't know . When I find the cause, I'll let you know about that.

**Comment by shepf** [comment]
![图片](https://user-images.githubusercontent.com/25335472/92315181-f6de5700-f014-11ea-91ba-98e8fb0d7895.png)

it look good，today！@hsjw12

**Comment by hsjw12** [comment]
I can't, what's the problem?

**Comment by hsjw12** [comment]
Please can I check your wallet with my github ID?  Is there a problem with my gihub id?

**Comment by hsjw12** [comment]
Have you ever had anything to change my browser settings? For example if I use chrome
Or maybe the github ID I use is the problem.

**Comment by hsjw12** [comment]
the version of my chrome  is  85.0.4183.83(공식 빌드) (64비트)

**Comment by shepf** [comment]
i don't change browser settings, i use Firfox.  you can try Firfox！

**Comment by hsjw12** [comment]
Okay I will do that

**Comment by hsjw12** [comment]
Still not work....
![제목 없음-1](https://user-images.githubusercontent.com/70571701/92320706-59a81080-f05e-11ea-8277-8473834ff070.png)

**Comment by hsjw12** [comment]
No matter how much I think about it, my GitHub ID seems to be the problem. Someone, please help me.
2 days have passed since all my GitHub IDs were created.

**Comment by hsjw12** [comment]
I've been authenticated with my Github account, but why keep saying "User account is too new." Will only the message appear? I even created and tested the Github ID several times, and the results were always the same.

**Comment by hsjw12** [comment]
> i don't change browser settings, i use Firfox. you can try Firfox！
I've been authenticated with my Github account, but why keep saying "User account is too new." Will only the message appear? I even created and tested the Github ID several times, and the results were always the same.
Of course the lotus synchronization is over, why not? Did you get certification on the linux system where lotus is running when you get faucet certification?

**Comment by hsjw12** [comment]
> i don't change browser settings, i use Firfox. you can try Firfox！

I've been authenticated with my Github account, but why keep saying "User account is too new." Will only the message appear? I even created and tested the Github ID several times, and the results were always the same.
Of course the lotus synchronization is over, why not? Did you get certification on the linux system where lotus is running when you get faucet certification?

**Comment by jennijuju** [comment]
not lotus realted
