### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err`

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/lotus#3584]
**Describe the bug**
020-09-05T19:47:07.025 INFO filcrypto::proofs::api > seal_commit_phase1: finish
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bellperson-0.9.2/src/gpu/locks.rs:48:13
2020-09-05T19:56:34.124Z        WARN    rpc     go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:241  error in RPC call to 'Filecoin.SealCommit2': Rust panic: no unwind information
github.com/filecoin-project/filecoin-ffi.SealCommitPhase2
        /root/lotus/extern/filecoin-ffi/proofs.go:401
github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealCommit2
        /root/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:519
github.com/filecoin-project/lotus/extern/sector-storage.(*LocalWorker).SealCommit2
        /root/lotus/extern/sector-storage/localworker.go:169
reflect.Value.call
        /usr/local/go/src/reflect/value.go:460
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:321
github.com/filecoin-project/go-jsonrpc/auth.PermissionedProxy.func1
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/auth/auth.go:62
reflect.callReflect
        /usr/local/go/src/reflect/value.go:549
reflect.makeFuncStub
        /usr/local/go/src/reflect/asm_amd64.s:20
github.com/filecoin-project/lotus/api/apistruct.(*WorkerStruct).SealCommit2
        /root/lotus/api/apistruct/struct.go:1225
reflect.Value.call
        /usr/local/go/src/reflect/value.go:460
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:321
github.com/filecoin-project/go-jsonrpc.doCall
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:130
github.com/filecoin-project/go-jsonrpc.(*RPCServer).handle
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:221
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373

**To Reproduce**
Running lotus-worker v0.5.10

**Version (run `lotus version`):**
0.5.10

**Additional context**
Running lotus-worker as root , so the permissions problem cannot be user related.

**Comment by RobQuistNL** [comment]
If I'm not mistaken this error didn't come from the worker, but from the miner (the RPCServer in the miner). Anything in the logs there?

**Comment by cryptowhizzard** [comment]
Nope.

**Comment by s0nik42** [comment]
same error here. @cryptowhizzard  How did you solve it ?

**Comment by cryptowhizzard** [comment]
I run the miner as user root now.

**Comment by s0nik42** [comment]
@cryptowhizzard thank you , only the miner or both miner and workers ?

**Comment by cryptowhizzard** [comment]
Both untill resolved.

**Comment by s0nik42** [comment]
thanks !

**Comment by s0nik42** [comment]
@cryptowhizzard I resolved it. the lock file were owned by root. I can now run it under a standard user

**Comment by William8Work** [comment]
I ran into this when switching the worker into service unit:

Dec 27 09:21:39 g1wrk05 lotus-worker[110921]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/bellperson-0.12.1/src/gpu/locks.rs:49:18
