### ISSUE TITLE
Can't continue after precommit1 for about 1day

### ISSUE THREAD

**Issue by yangwb** [filecoin-project/lotus#3587]
After sending “lotus-miner sectors pledge” 24 times yesterday,  15 sectors became PC1 status in about 1 hour.  But then, none of them moved any more.  what is the problem? may I keep waiting?  thank you.

lotus version 0.5.10+git.c573310c

lotus-miner sealing jobs:

ID  Sector  Worker  Hostname     Task  State        Time
17  0       0       Miner_10140  PC1   running      24h58m0.8s
20  1       0       Miner_10140  PC1   running      23h58m22.9s
0   4       0       Miner_10140  PC1   assigned(0)  24h51m5.9s
0   5       0       Miner_10140  PC1   assigned(1)  24h50m55.8s

lotus-miner sectors list:

0: PreCommit1  sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
1: PreCommit1  sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
2: PreCommit1  sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
3: PreCommit1  sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
4: PreCommit1  sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
5: PreCommit1  sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
6: PreCommit1  sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
7: PreCommit1  sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
8: PreCommit1  sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
9: PreCommit1  sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
10: PreCommit1 sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
11: PreCommit1 sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
12: PreCommit1 sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
13: PreCommit1 sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
14: PreCommit1 sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false
15: PreCommit1 sSet: NO active: NO tktH: 0 seedH: 0 deals: [0]  toUpgrade:false

**Comment by jennijuju** [comment]
not enough info provided(hardware spec..) also the lotus version looks a bit too out dated now
