### ISSUE TITLE
Windows PoSt Failures - Missing Window on Ryzen 3600X

### ISSUE THREAD

**Issue by Meatball13** [filecoin-project/lotus#3591]
**Describe the bug**
Last two days I've lost all my proving power based on what I think is timing issues of the post calculations.

**To Reproduce**
1) Seal multiple sectors (30+)
2) Wait for PoSt check with a Ryzen 3600X/128GB/1070Ti machine that is not doing any sealing.  Only running daemon and lotus-miner/scheduler.

**Expected behavior**
I'd expect the hardware to be able to handle a PoSt check for the small number of sectors (30'ish) I'm proving.

**Screenshots**

**Version (run `lotus version`):**
lotus version
Daemon:  0.5.10+git.38cb2601+api0.14.0
Local: lotus version 0.5.10+git.38cb2601

**Additional context**

- AMD Ryzen 3600X CPU / 128 GB RAM / 2 TB NVME with 1 TB NVME Swap / GTX 1070Ti GPU

- Machine set false to all sealing activities and is only running lotus daemon and lotus-miner (for scheduling of 2 external workers)

- Based on logs (attached), all sectors are being checked and marked good, but it looks like the calculation may be taking over 30 minutes to complete and is missing the deadline.

[postLogs.txt](https://github.com/filecoin-project/lotus/files/5179381/postLogs.txt)

- Marius thinks it might have to do with the the node falling behind the chain during the post window because it's being spammed during that time and you miss the window **(https://filecoinproject.slack.com/archives/C0179RNEMU4/p1599383229167100)**

**Comment by Meatball13** [comment]
So, quick update on this one.  Had a chance to wait for the next cycle to run and kept a good eye on things.  Also, in the meantime I swapped a 3900X (12C/24T vs 6/12 on the 3600X) into the machine, hoping to give it enough horsepower to push through everything in 30 minutes.  Once the PoSt kicked off, I did noticed about 3-4 minutes where I ran into GPU lock issues

2020-09-06T21:41:27.921 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error: 

```
################################ OPENCL ERROR ############################### 

Error executing function: clEnqueueNDRangeKernel("radix_fft")  

Status error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  

Please visit the following url for more information: 

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  

############################################################################# 
```

After that point it did finally let the GPU get locked, though the CPU still pretty much seemed to hammer every core/thread with not a lot of GPU usage.  I also monitored lotus sync status, and just about the whole time I did see the worker was a bit behind, showing 'Height diff: 1' and even once it showed 2. 

Snark proof appeared to finish up in about 18 minutes total from start to finish, so I think it's a combination of not having a powerful enough GPU / CPU that takes the PoSt beyond the 30 minute window.  I do worry that this could be a general problem for folks that may be using their 'miners' to also do sealing and if this may possibly be a problem as there's more sectors to check every PoSt period.

```
020-09-06T21:37:30.314-0400	INFO	storageminer	storage/wdpost_run.go:394	running windowPost	{"chain-random": "KEZmyl4JbC2wyxF/jutjqPg3eos5mFQ9TIs0orkqJvY=", "deadline": {"CurrentEpoch":37875,"PeriodStart":37870,"Index":0,"Open":37870,"Close":37930,"Challenge":37850,"FaultCutoff":37800}, "height": "37875", "skipped": 0}
2020-09-06T21:37:30.314 INFO filcrypto::proofs::api > generate_window_post: start
2020-09-06T21:37:30.338 INFO filecoin_proofs::api::post > generate_window_post:start
2020-09-06T21:37:30.339 INFO filecoin_proofs::caches > trying parameters memory cache for: Window_POST[34359738368]
2020-09-06T21:37:30.339 INFO filecoin_proofs::caches > no params in memory cache for Window_POST[34359738368]

2020-09-06T21:37:40.493 INFO storage_proofs_core::compound_proof > vanilla_proof:finish
2020-09-06T21:37:40.655 INFO storage_proofs_core::compound_proof > snark_proof:start
2020-09-06T21:37:40.745 INFO bellperson::groth16::prover > Bellperson 0.9.2 is being used!


2020-09-06T21:55:33.970 DEBUG bellperson::gpu::locks > GPU lock released!
2020-09-06T21:55:33.970 DEBUG bellperson::gpu::locks > Priority lock released!
2020-09-06T21:55:34.143 INFO storage_proofs_core::compound_proof > snark_proof:finish
2020-09-06T21:55:34.144 INFO filecoin_proofs::api::post > generate_window_post:finish
2020-09-06T21:55:34.145 INFO filcrypto::proofs::api > generate_window_post: finish
2020-09-06T21:55:34.146-0400	INFO	storageminer	storage/wdpost_run.go:432	submitting window PoSt	{"elapsed": 1083.831901714} 
```

At this point though, it appears I've got my power back, so not really a bug, but maybe need better clarification on the horsepower needed to complete this PoSt every day, or maybe spread it out throughout the day in smaller chunks so it never risks rolling past that 30 minute window.

**Comment by William8Work** [comment]
Thanks @Meatball13. I still lost my power and I ran it on 3970x with 256GB, 1080 Ti. However I also run a worker in this machine so I'll turn off the worker to see if it helps the situation.

I heard some miner just run one single machine which would be daemon + miner (full workload). So if they hope to have success WindowPost, it must be really powerful machine. Totally agree that we need better clarification on the horsepower needed for the PoSt everyday.

**Comment by Shekelme** [comment]
I'm running Ryzem 7 3700X with 128 GB and 2080Ti. So far all of the power losses has been caused by internet outages or problems with the machine in general, but not the lack of performance. And yes, it's "daemon + miner" machine.
@Meatball13 Is there a way for you to check whether your machine is able to handle a PoSt check with Ryzen 5 3600X? Maybe some improvements in latest Lotus versions will make it possible? I'm about to assemble a separate machine based on that CPU and I wonder if it's enough for handling the daemon only...

**Comment by Meatball13** [comment]
Unfortunately not able to test it anymore.  Replaced the 3600X with a 3900X and no longer have access to the 3600X.

**Comment by jennijuju** [comment]
Please open a new ticket if you are running into this issue on the latest version of lotus!
