### ISSUE TITLE
Clarify which sectors have been upgraded and by which new sector

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#3596]
TODO
**Describe the bug**

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by rjan90** [comment]
Hey!

Since `lotus-miner sectors mark-for-upgrade` has been depreciated as of Lotus 1.14.0, I´m closing this issue. SnapDeals creates a much cleaner view of which sector is being upgraded, since it only fills the CC-sector you are marking, and not replacing it by a new sector.
