### ISSUE TITLE
	go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:241	error in RPC call to 'Filecoin.MpoolPushMessage': GasEstimateMessageGas error:

### ISSUE THREAD

**Issue by jack815943555** [filecoin-project/lotus#3600]
2020-09-07T12:30:27.018+0800	WARN	rpc	go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:241	error in RPC call to 'Filecoin.MpoolPushMessage': GasEstimateMessageGas error:
0|lotus daemon  |     github.com/filecoin-project/lotus/node/impl/full.(*MpoolAPI).MpoolPushMessage
0|lotus daemon  |         /home/jack/go_workspace/v0510/lotus/node/impl/full/mpool.go:134
0|lotus daemon  |   - estimating gas used:
0|lotus daemon  |     github.com/filecoin-project/lotus/node/impl/full.(*GasAPI).GasEstimateMessageGas
0|lotus daemon  |         /home/jack/go_workspace/v0510/lotus/node/impl/full/gas.go:187
0|lotus daemon  |   - message execution failed: exit 16, reason: failed to allocate sector id 563: sector number 563 has already been allocated (RetCode=16):
0|lotus daemon  |     github.com/filecoin-project/lotus/node/impl/full.(*GasAPI).GasEstimateGasLimit
0|lotus daemon  |         /home/jack/go_workspace/v0510/lotus/node/impl/full/gas.go:159

**Comment by jennijuju** [comment]
what lotus version on you on?

**Comment by jennijuju** [comment]
Closing since no respond
