### ISSUE TITLE
Optionally hide removed sectors from lotus-miner sectors list

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#3605]
As in the title. From a community member:

```
Admittedly not an "urgent" issue... but is there any way to clear up the lotus-miner sectors list (i.e. remove the removed)? My scrolling is running out
```

**Comment by yablu** [comment]
This seems to work as a temporary workaround `watch -n 5 'lotus-miner sectors list | grep -v Remov'`

Appreciate you drawing attention to my question. Very kind of you :-)
