### ISSUE TITLE
Expose mechanism to DeclareFault manually

### ISSUE THREAD

**Issue by ribasushi** [filecoin-project/lotus#3612]
## Edited by @jennijuju 

Spec actors allow for [known fault declaration](https://beta.spec.filecoin.io/#systems__filecoin_mining__storage_mining__mining_cycle__index__faults)

Aside from using it to declare actual storage faults, this mechanism is invaluable for upgrades. This is especially important in the case of big miners, where every single 30 minute proving partition is occupied and there is no possibility to restart the miner without incurring a (currently undeclared, thus higher) penalty.

### Proposed Solution:
1. Expose an API ep for declare faults manually
2. Create an CLI:
`lotus-miner sectors declarefault {{num}}` ( probably accompanied by `--really-do-it` )
The call should check whether the declaration is timely, and post it to the network, returning 0. It should return an error in all other cases ( too late to DF / sector already faulty )

/cc @zixuanzh

**Comment by zcqzcg** [comment]
Any chance that sanity check return wich sector is already faulty?

Or let the sanity check join CheckProvable function?

**Comment by hyunmoon** [comment]
We definitely need this.

**Comment by ribasushi** [comment]
@jennijuju any luck on that one?

**Comment by jennijuju** [comment]
> @jennijuju any luck on that one?

moved to our backlog

**Comment by ZenGround0** [comment]
Note: Declaring faults explicitly is "economically deprecated" because missing a post is cheaper than declaring a fault.  Adding an endpoint for this seems like a footman.

**Comment by arajasek** [comment]
^Until that changes, this should not be considered for work

**Comment by zixuanzh** [comment]
> Note: Declaring faults explicitly is "economically deprecated" because missing a post is cheaper than declaring a fault. Adding an endpoint for this seems like a footgun

this is not 100% true, it depends on the proportion of sectors that are at fault in a partition. There is a more detailed explanation in FIP2 iirc.
