### ISSUE TITLE
RROR   sectors storage-sealing/garbage.go:65   add piece:

### ISSUE THREAD

**Issue by jack815943555** [filecoin-project/lotus#3617]
2020-09-07T22:34:12.455+0800    ERROR   sectors storage-sealing/garbage.go:65   add piece:
    github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).pledgeSector
        /home/jack/go_workspace/v0510/lotus/extern/storage-sealing/garbage.go:22
  - pieceCid error: generating piece commitment: failed to build tree

Caused by:
    0: failed to create data store
    1: No such file or directory (os error 2)

**Comment by jennijuju** [comment]
not enough info for reproducing the bug or debug.

**Comment by xiaomdong** [comment]
I have the same error.
