### ISSUE TITLE
ForceSectorState is not doing sanity check with valid states.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3626]
After executing command ```lotus-miner sectors update-state --really-do-it 0 -h```,  the sector is updated to status `-h`
![image](https://user-images.githubusercontent.com/42981373/92415342-7c056100-f126-11ea-8d0a-dee3de6e2871.png)

[sectorsUpdateCmd](https://github.com/filecoin-project/lotus/blob/2080458f0d1235cc0cc255405c13e3c086de0e3f/cmd/lotus-storage-miner/sectors.go#L423) takes the arg string as it is and passes it to [ForceSectorState](https://github.com/filecoin-project/lotus/blob/master/extern/storage-sealing/fsm.go) and send status as it is

**Comment by madper** [comment]
Congratulations! I have one sector with `--help` state.   :-L

**Comment by askender** [comment]
yes. many miner meet the problem.
Such as input a typo:  commiting (should be commi**tting**)       ` lotus-miner sectors update-state --really-do-it 0 commiting`
It can be P2 maybe.
