### ISSUE TITLE
lotus-miner proving info improvements

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#3630]
1) the epochTime included with Deadline Open and Deadline Close are measured from the deadline's CurrentEpoch (instead of the chain's current epoch), which is...confusing

2) would be nice to include whether a post has been submitted already for current deadline

**Comment by rjan90** [comment]
I think this issue can be closed now? As some of these improvements has been implemented! #rengjøring

**Comment by jennijuju** [comment]
please create new feature requests/enhancement tickets if you still have specific ideas!
