### ISSUE TITLE
[Bug] make build doesn't work properly in version 0.6.0

### ISSUE THREAD

**Issue by qkrwnsgh1288** [filecoin-project/lotus#3639]
**Describe the bug**
in v0.5.10, `make build` worked fine. but today in v0.6.0, `make build` doesn't work properly.

**To Reproduce**
1. Run 'make build'
2. See error
```
$ make build
git submodule update --init --recursive
Submodule path 'extern/filecoin-ffi': checked out '40569104603407c999d6c9e4c3f1228cbd4d0e5c'
fatal: reference is not a tree: ef5dba45b810d7090e029167cc66911ef8c42a07
Unable to checkout 'ef5dba45b810d7090e029167cc66911ef8c42a07' in submodule path 'extern/test-vectors'
Makefile:48: recipe for target 'build/.update-modules' failed
make: *** [build/.update-modules] Error 1
```

**Version (run `lotus version`):**
commit 60cae87bfaeaa46d9e6fe53ed1f68158780aef3b

**Additional context**
and in v0.5.10, `make clean` worked fine without cargo, rust. but in v0.6.0, `make clean` doesn't work properly without cargo, rust.
In my specific server, cargo and rust are not installed. but It worked fine. but in v0.6.0, these libraries are required.

**Comment by arajasek** [comment]
Thanks for the issue! Temp fixed this by holding that commit in a branch, real fix is in #3645.
