### ISSUE TITLE
Lotus Sync will fallback to a lower block height

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/lotus#3640]
**Describe the bug**
After upgrade to 0.6.0. the lotus sync stucks, even after it completed the sync, it might fall back to lower block hight

**To Reproduce**
1. Run ' lotus sync wait'
2. See error

Worker 2: Target Height: 40958	Target: [bafy2bzaceaoda4rspg5nzxfaftq257jlwc7ma5bmtc36dkxa3fieb5dz2xlxs bafy2bzacedti7bupwgmygbjrqvsnr65nlx7equivsw627cqigcsakddohkrbi bafy2bzacebihv3akixhie47mpnne4idsnmeww5huh37lcwzyme6x2u3x5tlns bafy2bzacedvsjvwbx6vkvtjftnxw3sdis64xzjr

Worker 0: Target Height: 40959	Target: [bafy2bzacecvelsiyov2ty74nfoqxrgkoekfka6rdc7lazo53x5f2rajc5ssmo bafy2bzacedfzn5m7ailpkrenuv7owyj4pxrm6q246go2hsk7astmxgia466w4 bafy2bzacebulnjx6vfkiqbuzkq62ssgb3t44faf2ggsqx3uw5ecb7tv7b3juu]	State: complete	Height: 40959

**Expected behavior**
It should sync to the current height  Block Height
40,969 

**Screenshots**

**Version (run `lotus version`):**
 lotus -v
lotus version 0.6.0+git.60cae87b
**Additional context**

**Comment by rickiey** [comment]
{"level":"info","ts":"2020-09-07T23:28:31.303-0400","logger":"blocksync","caller":"blocksync/server.go:62","msg":"block sync request","start":[{"/":"bafy2bzacecgyklxbdauhy257e65mxrn6f4k54s3ypz7wqalhunei6kpynopry"},{"/":"bafy2bzacedhrj2gzobv5s4x7ndpaurozq5opaz5wlac6wlkxbbz7r6nzqrnzc"}],"len":900}
{"level":"info","ts":"2020-09-07T23:28:31.304-0400","logger":"blocksync","caller":"blocksync/server.go:62","msg":"block sync request","start":[{"/":"bafy2bzacecgyklxbdauhy257e65mxrn6f4k54s3ypz7wqalhunei6kpynopry"},{"/":"bafy2bzacedhrj2gzobv5s4x7ndpaurozq5opaz5wlac6wlkxbbz7r6nzqrnzc"}],"len":900}
{"level":"warn","ts":"2020-09-07T23:28:31.304-0400","logger":"blocksync","caller":"blocksync/server.go:159","msg":"block sync request: collectChainSegment failed: failed loading tipset {bafy2bzacecgyklxbdauhy257e65mxrn6f4k54s3ypz7wqalhunei6kpynopry,bafy2bzacedhrj2gzobv5s4x7ndpaurozq5opaz5wlac6wlkxbbz7r6nzqrnzc}: get block bafy2bzacecgyklxbdauhy257e65mxrn6f4k54s3ypz7wqalhunei6kpynopry: blockstore: block not found"}
{"level":"warn","ts":"2020-09-07T23:28:31.304-0400","logger":"blocksync","caller":"blocksync/server.go:159","msg":"block sync request: collectChainSegment failed: failed loading tipset {bafy2bzacecgyklxbdauhy257e65mxrn6f4k54s3ypz7wqalhunei6kpynopry,bafy2bzacedhrj2gzobv5s4x7ndpaurozq5opaz5wlac6wlkxbbz7r6nzqrnzc}: get block bafy2bzacecgyklxbdauhy257e65mxrn6f4k54s3ypz7wqalhunei6kpynopry: blockstore: block not found"}
{"level":"warn","ts":"2020-09-07T23:28:31.304-0400","logger":"blocksync","caller":"blocksync/server.go:159","msg":"block sync request: collectChainSegment failed: failed loading tipset {bafy2bzacecgyklxbdauhy257e65mxrn6f4k54s3ypz7wqalhunei6kpynopry,bafy2bzacedhrj2gzobv5s4x7ndpaurozq5opaz5wlac6wlkxbbz7r6nzqrnzc}: get block bafy2bzacecgyklxbdauhy257e65mxrn6f4k54s3ypz7wqalhunei6kpynopry: blockstore: block not found"}

**Comment by jennijuju** [comment]
Hasn't been reported since 0.7.0. Closing now.
