### ISSUE TITLE
May be shoud check the network of the deal robot

### ISSUE THREAD

**Issue by waynewyang** [filecoin-project/lotus#3661]
**Describe the bug**
We can receive the robot(I guess) (18.191.250.158) message, but it seems haven’t received our message. So there’s robot retransmission and our retransmission. At the same time, the Robot RST the TCP connection causes the stream reset to finally occur.

This will affect the success rate of miners deals.

![image](https://user-images.githubusercontent.com/25957795/92493448-19e05500-f227-11ea-89a4-1b5cef44c78b.png)

**Version (run `lotus version`):**
0.5.6~0.6.1

**Additional context**

**Comment by waynewyang** [comment]
@ianjdarrow This is the storage deals for t02503 deals failure caused by the above reasons perherps.Pls help me check, thanks

|deal ID|createTime|Deal CID|Deal State|
| :--: | :--: | :--: | :--: |
|2020-09-03T00:31:00.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: dial backoff|
|2020-09-02T23:25:36.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T19:03:36.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T17:56:18.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T16:18:24.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T15:53:19.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T15:08:06.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T14:51:19.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T14:05:06.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T13:46:19.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T12:58:48.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T12:41:55.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T11:41:36.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T10:57:50.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: dial backoff|
|2020-09-02T10:42:00.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T09:58:06.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T09:36:28.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T08:57:23.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: dial backoff|
|2020-09-02T08:32:47.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T07:58:06.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T07:32:55.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T06:57:22.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: dial backoff|
|2020-09-02T06:31:41.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T05:54:39.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: failed to dial 12D3KooWEvy6gDEmVj8P6rE5HvzSyZzXkeezu6EV3nDcNpDG142T: all dials failed* [/ip4/103.210.21.98/tcp/31432] dial tcp4 0.0.0.0:1235-&amp;gt;103.210.21.98:31432: i/o timeout* [/ip4/36.159.57.6/tcp/31432] dial tcp4 0.0.0.0:1235-&amp;gt;36.159.57.6:31432: i/o timeout|
|2020-09-02T05:23:48.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: failed to dial 12D3KooWEvy6gDEmVj8P6rE5HvzSyZzXkeezu6EV3nDcNpDG142T: all dials failed* [/ip4/36.159.57.6/tcp/31432] dial tcp4 0.0.0.0:1235-&amp;gt;36.159.57.6:31432: i/o timeout* [/ip4/103.210.21.98/tcp/31432] failed to negotiate security protocol: context deadline exceeded|
|2020-09-02T04:54:43.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: failed to dial 12D3KooWEvy6gDEmVj8P6rE5HvzSyZzXkeezu6EV3nDcNpDG142T: all dials failed* [/ip4/36.159.57.6/tcp/31432] dial tcp4 0.0.0.0:1235-&amp;gt;36.159.57.6:31432: i/o timeout* [/ip4/103.210.21.98/tcp/31432] dial tcp4 0.0.0.0:1235-&amp;gt;103.210.21.98:31432: i/o timeout|
|2020-09-02T04:22:37.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T03:54:49.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T03:22:47.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: failed to dial 12D3KooWEvy6gDEmVj8P6rE5HvzSyZzXkeezu6EV3nDcNpDG142T: all dials failed* [/ip4/36.159.57.6/tcp/31432] dial tcp4 0.0.0.0:1235-&amp;gt;36.159.57.6:31432: i/o timeout* [/ip4/103.210.21.98/tcp/31432] failed to negotiate security protocol: context deadline exceeded|
|2020-09-02T02:54:54.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: dial backoff|
|2020-09-02T02:20:55.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T01:54:55.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: dial backoff|
|2020-09-02T01:21:37.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-02T00:55:21.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: failed to dial 12D3KooWEvy6gDEmVj8P6rE5HvzSyZzXkeezu6EV3nDcNpDG142T: all dials failed* [/ip4/36.159.57.6/tcp/31432] dial tcp4 0.0.0.0:1235-&amp;gt;36.159.57.6:31432: i/o timeout* [/ip4/103.210.21.98/tcp/31432] dial tcp4 0.0.0.0:1235-&amp;gt;103.210.21.98:31432: i/o timeout|
|2020-09-02T00:20:55.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T23:55:11.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T23:21:23.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T22:55:06.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T22:21:19.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T21:54:47.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T21:21:37.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T20:55:06.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T20:20:37.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T19:54:42.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: dial backoff|
|2020-09-01T19:20:37.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T18:54:47.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T18:21:06.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T17:54:56.000Z|n/a|n/a|ClientQueryAsk failed : failed to open stream to miner: dial backoff|
|2020-09-01T17:20:55.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T14:26:12.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T12:56:11.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T11:40:29.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T10:41:11.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T09:42:06.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T08:40:30.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|
|2020-09-01T07:40:53.000Z|n/a|n/a|ClientQueryAsk failed : failed to read ask response: stream reset|

**Comment by jennijuju** [comment]
not lotus related
