### ISSUE TITLE
failed to get blocks: doRequest failed for all peers

### ISSUE THREAD

**Issue by limulidae** [filecoin-project/lotus#3662]
**Describe the bug**
lotus sync failed.
failed to get blocks: doRequest failed for all peers

**To Reproduce**
1. Run 'lotus sync wait'
2. See error
sync status:
worker 0:
        Base:   [bafy2bzacecnamqgqmifpluoeldx7zzglxcljo6oja4vrmtj7432rphldpdmm2]
        Target: [bafy2bzaceazohywajiltqfvg6wimd4ualwwtvvuczs6mivjwjfvnrtieam3rq bafy2bzacecu3a4hdqwn2sbkleq67ygmudzwwamxhmr45qe5mggcmvmcitasm4] (32289)
        Height diff:    32289
        Stage: error
        Height: 29213
        Elapsed: 1m0.914307895s
        Error: failed to get blocks: doRequest failed for all peers
worker 1:
        Base:   []
        Target: [] (0)
        Height diff:    0
        Stage: <unknown: 0>
        Height: 0
worker 2:
        Base:   []
        Target: [] (0)
        Height diff:    0
        Stage: <unknown: 0>
        Height: 0

**Comment by Reiers** [comment]
If you are still experiencing problems, please ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thanks!
