### ISSUE TITLE
iron out the dependency cycles between lotus, test-vectors, and statediff

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#3666]
This is what we're planning to do:

- [x] test vector schema versioned as a separate go module (it will evolve very little), removing its dependencies on `abi` and `exitcode` packages, by replacing the types with their underlying (int64s and big.Int), and type converting on the driver.
    - This way we derisk the schema inadvertently forcing specific dependencies on lotus.
- [x] chaos actor moved into the Lotus codebase, and owned by the Oni team via CODEOWNERS.
    - This is how it should've been from day 1, but the chaos actor was in incubation and we needed to iterate on it rapidly. CODEOWNERS will solve the maintenance/PR approval problem.
    - With this, and the above checkbox, Lotus no longer will depend on test-vectors in the go.mod.
- [x] statediff not imported as a go package, but rather called as a CLI tool, if available in the host's path.
    - We built statediff as a standalone CLI tool that can take a CAR with two roots and perform the diff.
    - We will use that run mode of statediff, because it's also how other implementations (Forest and Fuhon) will call out to statediff.
    - This way we check two extra boxes: (1) we serve as a proper reference implementation without unfair advantage (being able to call statediff as a go module), and (2) we test the CLI mode of statediff.
- [ ] CODEOWNERS to streamline maintenance within the respective packages.

**Comment by raulk** [comment]
cc @willscott @nonsense @alanshaw does this capture what we discussed today?

**Comment by alanshaw** [comment]
SGTM 🚀

Just to clarify, the scope for CODEOWNERS will be everything in the `conformance` package and it will require at least 1 member of the Oni team to have write access to the repo. The implication is that the Oni member(s) with write access will have the freedom to approve and merge PRs to the `conformance` package.
