### ISSUE TITLE
[Request] add flag to specify the location of the config.toml file

### ISSUE THREAD

**Issue by qiwu7** [filecoin-project/lotus#3674]
Current behavior: The Lotus daemon uses whatever config is in the `$LOTUS_PATH/config.toml`, and `$LOTUS_PATH` is `~/.lotus` by default.

Request: enable to specify the path to the config file via cli. The desired way for this to be done is to run `lotus --config=/some/path.toml`.

**Comment by daviddias** [comment]
@qiwu7 got back from the team. Given your timeline. Would creating a symlink to the right path create the feature that you want?

**Comment by qiwu7** [comment]
How is the symlink going to work? Can you provide a little bit more details here?

**Comment by qiwu7** [comment]
@daviddias got some more information. I don't think symlink will work for us. So a cli param would be the preferred way.

**Comment by daviddias** [comment]
@qiwu7 I'm curious, wouldn't you be able to symlink the config file you want into the volume that you mount?

**Comment by almindor** [comment]
We need to render the config file into place before (out of context) of the volume mount. We also want to avoid any hacky "runtime checks" like one to see if the file exists in the mount and to create the symlink each time after mounting.

Symlinking would work but it'd be a hack we need to add on top of standard functionality, something we want to avoid for anything production level. The standard behavior is we render the config from a template into main volume and then `--config=/path` send that info to the node.
