### ISSUE TITLE
Messages are piling up in the mempool.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3675]
Quite a few miners reported that, after updating to 0.6.1 the messages are piling up in the mempool and constantly stuck.

for example, one miner(t02500) has  replaced one of the messages that was blocking the mempool which leads 144 messages in the local mempool

20-25 min later, he has ~150 messages waiting in the mempool and has to do a replace again..

**Comment by jennijuju** [comment]
@vyzo could you please take a look at this issue?

**Comment by vyzo** [comment]
well, if the baseFee is rising they might have to constantly ReplaceByFee the head message to get through -- or wait for the baseFee to drop and the republish to send it automatically.

**Comment by jennijuju** [comment]
Roughly 6:00 CST over 200 messages were discovered in local mpool. Tried to raise message price to get processed, yet the messages were being processed too slowly. We had to stop workers to avoid further accumulation. Yet, we still have over 100 message in the pool six hours later.

**Comment by vyzo** [comment]
We think we have bug in the optimal selection -- see https://github.com/filecoin-project/lotus/pull/3685 for the fix.

**Comment by vyzo** [comment]
Closing, as this has been fixed in v0.7.0 release.
