### ISSUE TITLE
Still NOT not  faucet

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#3683]
**Describe the bug**
Couldn't get a few gas from faucet because account is too new. My github account has been created more than two days ago.
What else can I check? 
I even tested it with my 4 GitHub IDs and the results were the same. "User account is too new."
**To Reproduce**
1. Run '...'
2. See error
![제목 없음](https://user-images.githubusercontent.com/70571701/92581356-8e200480-f2ca-11ea-99a5-9c527ef0e549.png)

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
Daemon:  0.6.1+git.867469e9.dirty+api0.14.0
Local: lotus version 0.6.1+git.867469e9.dirty

**Additional context**

**Comment by kelvinzhong** [comment]
I try to use faucet to transfer some gas to my new wallet, few days pass still not sucess
![image](https://user-images.githubusercontent.com/24283772/92591119-e3aae000-f2cf-11ea-91a8-26d5895b6278.png)
anyone can help?

**Comment by hsjw12** [comment]
I finally succeeded. Thank you for your help.

**Comment by sredni44** [comment]
Hello, 
I have the same problem "account to new" - can you share what the solution was?
Thanks in advance.

**Comment by hsjw12** [comment]
Accounts signed up for Github must be over a year to be authenticated. If certified, you will receive 5FIL. It's too small to mine.
