### ISSUE TITLE
lotus-miner config.toml default suggestions

### ISSUE THREAD

**Issue by Meatball13** [filecoin-project/lotus#3692]
**Describe the bug**
No real bugs here, just some thoughts on what might be some better 'defaults' in the lotus-miner config.toml.

**To Reproduce**
N/A

**Expected behavior**

- 'WaitDealsDelay' should be bumped up from 1h0m0s default as this is way too fast for the miner to be start packing up new sectors with deals.  With it set this fast, many miners are having problems because their machines are getting backed up with PC1's since they aren't able to seal that fast.  Suggest it's set to 8h0m0s by default.
- 'MaxWindowPoStGasFee = 50' - Again, seems way too high.  Considering that at currently pre-market prices 1 FIL = ~$18USD, should people really be willing to spend upwards of $900US to do one PoSt? :)  Same could be said for even the 0.05's for MaxPreCommitGasFee and MaxCommitGasFee.  Certainly you want people to get their messages through, but message costs should be in cents range, not dollars range.

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by jennijuju** [comment]
https://filecoinproject.slack.com/archives/C0179RNEMU4/p1599687998261800
