### ISSUE TITLE
If the CommitFailed is caused by 'unlocked balance does not cover pledge requirements', it should just wait for next commit retry but sealing.SectorRetryComputeProof

### ISSUE THREAD

**Issue by EntropyPool** [filecoin-project/lotus#3693]
**Describe the bug**
When a sector goto CommitFailed due to lack of FIL, the sector will retry to compute proof again.

**To Reproduce**
1. Seal a sector
2. Burn some fee in worker to let the amount below 0

**Expected behavior**
The sector will fail to commit, then wait for next commit, until timeout.

**Screenshots**
![image](https://user-images.githubusercontent.com/69444208/92612881-e36d0d80-f2ec-11ea-85f6-ad156e093b8d.png)

**Version (run `lotus version`):**
Daemon:  0.6.1+git.7c5b8286.dirty+api0.14.0
Local: lotus version 0.6.1+git.7c5b8286.dirty

**Additional context**
N/A

**Comment by Reiers** [comment]
Hi @EntropyPool 

Thanks for the report. The issue is outdated, and this behavior is expected.
Remember to have enough FIL in all control addresses, before dealmaking or sectors pledge. 
https://lotus.filecoin.io/docs/storage-providers/addresses/
