### ISSUE TITLE
Q's about Msig balances

### ISSUE THREAD

**Issue by Schwartz10** [filecoin-project/lotus#3699]
Create a multisig wallet with a non zero `duration`, and then use the `MsigGetAvailableBalance` to check the "avail" balance periodically throughout the day - you'll notice the number decreases over time - meaning (i think?) that it's actually showing the locked amount. 

FWIW - I think this is equally as helpful, could just change the name unless this is a more nasty bug

1. Is `MsigGetAvailableBalance` returning the locked balance instead of the available? 

Create a multisig wallet with a non zero `duration`, and then use the `MsigGetAvailableBalance` to check the "avail" balance periodically throughout the day - you'll notice the number decreases over time - meaning (i think?) that it's actually showing the locked amount. 

2. If the answer to #1 ^^^ is that MsigGetAvailableBalance is _actually_ returning Locked (non vested) balance, would you get the available balance by doing:

`Balance` (as returned in [ActorState](https://github.com/filecoin-project/lotus/blob/master/api/api_full.go#L527) from `StateReadState`) - lockedBalance (as returned from `MsigGetAvailableBalance`)

**Comment by rjan90** [comment]
Hey @Schwartz10!

Did you ever find answers to this? Since this ticket seems a bit outdated, and is more of a question rather then a issue, I´m closing this for now.

If this is a issue in current release please open a new ticket.

Thanks again !
