### ISSUE TITLE
2020-09-09T22:19:29.284+0800    WARN    rpc     go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:241  error in RPC call to 'Filecoin.SealCommit2': Rust panic: nounwind information

### ISSUE THREAD

**Issue by jack815943555** [filecoin-project/lotus#3700]
ry/src/github.com-1ecc6299db9ec823/bellperson-0.9.2/src/gpu/locks.rs:48:13
2020-09-09T22:19:29.284+0800    WARN    rpc     go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:241  error in RPC call to 'Filecoin.SealCommit2': Rust panic: nounwind information
github.com/filecoin-project/filecoin-ffi.SealCommitPhase2
        /home/jack/go_workspace/lotus/extern/filecoin-ffi/proofs.go:402
github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealCommit2
        /home/jack/go_workspace/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:519
github.com/filecoin-project/lotus/extern/sector-storage.(*LocalWorker).SealCommit2
        /home/jack/go_workspace/lotus/extern/sector-storage/localworker.go:169
reflect.Value.call
        /usr/local/go/src/reflect/value.go:460
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:321
github.com/filecoin-project/go-jsonrpc/auth.PermissionedProxy.func1
        /home/jack/go_workspace/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/auth/auth.go:62
reflect.callReflect
        /usr/local/go/src/reflect/value.go:549
reflect.makeFuncStub
        /usr/local/go/src/reflect/asm_amd64.s:20
github.com/filecoin-project/lotus/api/apistruct.(*WorkerStruct).SealCommit2
        /home/jack/go_workspace/lotus/api/apistruct/struct.go:1246
reflect.Value.call
        /usr/local/go/src/reflect/value.go:460
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:321
github.com/filecoin-project/go-jsonrpc.doCall
        /home/jack/go_workspace/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:130
github.com/filecoin-project/go-jsonrpc.(*RPCServer).handle
        /home/jack/go_workspace/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:221
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373

**Comment by Reiers** [comment]
**Hi @jack815943555** 

Thanks for the report. The issue is outdated.

If this is a issue in [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.14.4) - please open a new ticket.
