### ISSUE TITLE
Cannot ctrl-C during chain list to cancel operation

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#3707]
**Describe the bug**
Running a chain list from a height which is very far back from the chain head will not cancel when interrupted.

**To Reproduce**
Take a currently synced testnet node (or any node that has more than ~20,000 ish blocks synced, in this case ~43000) and list the chain at some low chain height then issue a ctrl-c / SIGINT
```
lotus chain list --count 1 --height 500
```

**Expected behavior**
Command should exit in some amount of time.

**Version (run `lotus version`):**
lotus --version
lotus version 0.6.1+git.8a8f0ab3

**Additional context**
```
lotus chain list --count 1 --height 500
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C500: (Aug 25 02:10:00) [ bafy2bzaceb4oapl74y4oujr3ssyll6q6otu7jchztlccc2qug65exsb7b2e2c: t01000,bafy2bzaceauoo4ztwdy57y2mforboerwlly64jsvssfagmml6dupmfvlp7kqc: t01002, ]
```

**Comment by Reiers** [comment]
Hi @travisperson 

Can confirm that this is still a issue in the current release [v1.15.1+](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)

```
reiers@M1Max-protocol ~ % lotus chain list --count 1 --height 500
^C^C^C^C^C^C^C^C^C^C^C

reiers@M1Max-protocol ~ % lotus version
Daemon:  1.15.2-rc1+mainnet+git.dcf6f6414+api1.5.0
Local: lotus version 1.15.3-dev+mainnet+git.02a6176bd
```

**Comment by rjan90** [comment]
Closing as completed - I´m unable to repro this on a node with Lotus v1.26.2:

```
lotus chain list --count 1 --height 500
^Croot@Ubuntu-2204-jammy-amd64-base ~ # 
```
