### ISSUE TITLE
faucet not work 

### ISSUE THREAD

**Issue by xihucuyu888** [filecoin-project/lotus#3719]
**Describe the bug**
![image](https://user-images.githubusercontent.com/41260909/92674691-6e332400-f350-11ea-9685-3d30b24d8770.png)

![image](https://user-images.githubusercontent.com/41260909/92674678-670c1600-f350-11ea-9433-546c6ac44e48.png)

bafy2bzaceasvqsjl25jkahqhjgp6kryt66ykjiqxwb3hcjpuevhuv5bqg6wdi

it has been in this state for a long time , about 12 hours....

**To Reproduce**
1. click
2. See error

**Comment by oopos** [comment]
me, too.

**Comment by kelvinzhong** [comment]
me too

**Comment by jennijuju** [comment]
not lotus realed
