### ISSUE TITLE
 miner attempting to prove commit over 200 sectors in epoch

### ISSUE THREAD

**Issue by IPFS-grandhelmsman** [filecoin-project/lotus#3731]
**Describe the bug**
When upgrading the miner, the custom seal worker retry the task, and got a lot commit messages to commit, but it seems the specs protocol can't accept more then 200 prove.

**To Reproduce**
Restart the lotus, then restart the miner.
in my scene, the worker also goto restart by the miner restarted, when the miner restarted, the commit tasks will retry at the same time or in a epoch.

**Expected behavior**
all prove messages should go and on chain.
maybe need queue the prove message to package, or pack the prove message not more then 200. 

**Screenshots**

**Version (run `lotus version`):**
lotus version 0.6.2+git.c31356fbe.dirty(custom from v0.6.2)
**Additional context**
```
2020-09-10T05:06:31.667-0400    ^[[33mWARN^[[0m vm      vm/runtime.go:119       VM.Call failure: miner t03176 attempting to prove commit over 200 sectors in epoch (RetCode=32):
    github.com/filecoin-project/specs-actors/actors/builtin/power.Actor.SubmitPoRepForBulkVerify.func1
        /root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.7/actors/builtin/power/power_actor.go:299
2020-09-10T05:06:31.667-0400    ^[[33mWARN^[[0m vm      vm/runtime.go:358       vmctx send failed: to: t04, method: 8: ret: [], err: miner t03176 attempting to prove commit over 200 sectors in epoch (RetCode=32)
```

**Comment by Reiers** [comment]
Hi @IPFS-grandhelmsman 

Thanks for the report. Old issue and this is fixed in the [latest release.](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)

Closing ticket.

If you are still experiencing problems, please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you!
