### ISSUE TITLE
worker referenced by windowRequest not found

### ISSUE THREAD

**Issue by lionsoul2014** [filecoin-project/lotus#3734]
the latest 0.6.2 and the old version, some workers were offline:

![2020-09-10_18-38](https://user-images.githubusercontent.com/7111577/92718933-123ebe80-f395-11ea-9f4a-aa00b9c3ad23.png)

![2020-09-10_18-42](https://user-images.githubusercontent.com/7111577/92719188-621d8580-f395-11ea-8958-d81dc7b7f8ad.png)

**Comment by jennijuju** [comment]
duplicated #3705
