### ISSUE TITLE
v1 (mainnet): remove deprecated blocksync protocol ID `/fil/sync/blk/0.0.1`

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#3737]
Before producing v1 (mainnet release), remove the deprecated blocksync protocol ID `/fil/sync/blk/0.0.1`.

See https://github.com/filecoin-project/lotus/pull/3624#discussion_r484544394.

**Comment by rjan90** [comment]
Closing this issue since the old BlockSyncProtocolID has been removed now.
