### ISSUE TITLE
Drowning in retrieval failures

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/lotus#3740]
**Describe the bug**
Occasionally, miners are getting many retrieval failures in quick succession. Error message is `exhausted 5 attempts but failed to open stream`.

This is also nicknamed "machine gun retrievals" by Slack users. 

@ianjdarrow observes that it tends to happen after a miner restarts (i.e. after upgrade). They immediately get 10-20 failed retrieval deals. Possible theory: there are “hidden” retrieval deals hanging on specific miners, which would also explain why retrieval throughput from the bot seems to go down over time.

**Screenshots**
1. From user `Chris` in [Slack](https://filecoinproject.slack.com/archives/C019KBJ6Q11/p1599691860109800):
![image](https://user-images.githubusercontent.com/1306020/92771700-1c4ac800-f369-11ea-8eb7-e4009e489ebe.png)

2. From user `Tung` in [Slack](https://filecoinproject.slack.com/archives/C0179RNEMU4/p1599603875161900) on Sept 8th:
![image](https://user-images.githubusercontent.com/1306020/92772042-5f0ca000-f369-11ea-8f99-e2879e8ef605.png)

3. Report from `askender` in [Slack](https://filecoinproject.slack.com/archives/C0179RNEMU4/p1599583806083400)
```
To everyone shoot by “machine gun retrieval” problem 1 hours after the 09.02 bot reboot,  it seems that the gun hurt will not disappear.   (it will not clear?)
It shoot 13 times in 1 hour after reboot to my miner, didn’t believe it speedup 100x without any announcement.
```

**Version (run `lotus version`):**
0.6.0 & above

cc @jennijuju

**Comment by mishmosh** [comment]
`gstefan` has found the edge case here, the dealbot retrieval proposal algorithm is:

> If the miner has a pending a proposal the bot will wait at least one hour, if nothing is pending will propose a new retrieval. In this case the retrieval deals fails fast, so the bot will propose a new one. Combined with retrieval prioritised by the number of deals (the miners with less completed retrievals have higher priority) is leading to this case. When a miner with less retrievals goes offline it will get more deals.

- We can implement an 1 hour constraint on retrieval even if the miner has nothing in progress to address this.
- Still need to figure out why the initial failure happens (simply due to restart/offline?)

**Comment by ozhtdong** [comment]
miner t03485, 20 retriever deals in 9 minutes, all failed, in other time of period, everything is fine for this miner. Would really like to have those deals to be deleted.
![Screenshot from 2020-09-14 13-19-52](https://user-images.githubusercontent.com/69976222/93046850-86c37700-f68d-11ea-918e-7d6f5dc30304.png)

**Comment by rjan90** [comment]
`SimultaneousTransfers = xx` in the config-file allows you to set the amount of simultaneous retrieval-deals on the newer Lotus-versions. So this issue can probably be closed now? #rengjøring
