### ISSUE TITLE
ClientRetrieve timeout 43200 Seconds - Wrong / non-existing dealid being requested

### ISSUE THREAD

**Issue by Storage-Hive** [filecoin-project/lotus#3745]
None of the deal numbers request actually exist on my miner and the deal numbers are really low compared to what I have, the deal retievals are 9xxx range yet the smallest actual deal I have is > 50000
lotus-miner retrieval-deals list
Receiver                                              DealID  Payload      State                             PricePerByte  BytesSent  Message
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  9805    ...pncao5p6  DealStatusFundsNeeded             2             1053786
12D3KooWCPhRaEqok86amrgCzx2edFqQLABCzByWBPMyFWZeRWrE  1375    ...bzkefgoc  DealStatusErrored                 2             0          deal data transfer failed: Unable to send cancel message: routing: not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  2545    ...6tcmtxj4  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  349     ...ohhaelso  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  6760    ...b7u6munk  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  8534    ...qxaie2lk  DealStatusFundsNeededLastPayment  2             65536
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  8739    ...2ye6ofj4  DealStatusFundsNeededLastPayment  2             65536
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  9316    ...pncao5p6  DealStatusFundsNeeded             2             1053786
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  3668    ...b7u6munk  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  4859    ...v4qhk7nw  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  7373    ...6tcmtxj4  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  9513    ...qp4cykyk  DealStatusFundsNeeded             2             1053786
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  5494    ...ayx3qg5i  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  6270    ...v4qhk7nw  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  7178    ...w47ayvqg  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  7795    ...2ye6ofj4  DealStatusCancelled               2             65536      Client cancelled retrieval
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  8238    ...2ye6ofj4  DealStatusFundsNeededLastPayment  2             65536
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  2355    ...ayx3qg5i  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  2459    ...w47ayvqg  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  2596    ...ayx3qg5i  DealStatusErrored                 2             0          channel not found
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  8090    ...qxaie2lk  DealStatusFundsNeededLastPayment  2             65536
12D3KooWNvDJE1PVFxEQY2kmF5Y92YgLb3pBgpkBJy65DH1TaFNo  9015    ...iwpthefa  DealStatusErrored                 2             0          Context Cancelled
lotus-miner storage-deals list
ProposalCid  DealId  State               Client                                                                                  Size    Price               Duration
...ff7lhcty  52874   StorageDealActive   t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i                                               128KiB  0 FIL               704134
...pfphafju  53153   StorageDealActive   t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i                                               128KiB  0 FIL               704013
...l6gjf2iy  53379   StorageDealActive   t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i                                               128MiB  0 FIL               703900
...nkvugq5i  53615   StorageDealActive   t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i                                               128KiB  0 FIL               703779
...a6fxvpv4  53846   StorageDealActive   t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i                                               128KiB  0 FIL               703601
......

**Comment by Storage-Hive** [comment]
allinfo
[allinfo.txt](https://github.com/filecoin-project/lotus/files/5204434/allinfo.txt)

**Comment by jennijuju** [comment]
closing since seems like a bot issue not lotu's?
