### ISSUE TITLE
Not try to send messages from addresses with 0 balance.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3749]
A miner was trying to perform a `lotus-miner actor withdraw` with miner available balance being 3 FIL and worker address = 0 and got `ERROR: GasEstimateMessageGas error: estimating gas used: message execution failed: exit SysErrSenderStateInvalid(2), reason: actor balance less than needed: 0 FIL < 0.00000101 FIL (RetCode=2)`

We think the issue was b/c the first message is sent by worker address and in this case, gas cannot be paid with 0 FIL worker.

The error message is a little bit misleading here. Also, @arajasek suggested that we should improve our ux to not even  try to send messages from addresses with 0 balance.

**Comment by arajasek** [comment]
Digging a little further, it looks like we already do have this check (the `checkBalance` method), it's just that the `GasEstimateMessageGas` check gets triggered and fails first. I think that's fine, a change isn't needed here.
