### ISSUE TITLE
Retrying PC1 failed due to sector number is allocated but PC info wasn't found on chain

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3751]
- full error message

```bash
sector 1606 got error event sealing.SectorSealPreCommit1Failed: getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
```

- Expected behaviour: not run into this error when retrying PC1 for a sector

**Comment by jennijuju** [comment]
related slack [thread](https://filecoinproject.slack.com/archives/CP50PPW2X/p1599729610263200?thread_ts=1599602585.215500&cid=CP50PPW2X)

**Comment by shaodan** [comment]
[sector-1723.log](https://github.com/filecoin-project/lotus/files/5205780/sector-1723.log)
sectors fall into this error-retry loop when restarted to P1 after commit fail, first P1 can be found on chain https://filfox.info/en/message/bafy2bzaced5oznabkjfkg7wyjmi7pmqvao5meybdnwuadcivvrzhsn2bgqq7e

**Comment by jennijuju** [comment]
full [log](https://filecoinproject.slack.com/files/U014845B12L/F01AEB7RZQA/sector-1723.log?origin_team=TEHTVS1L6&origin_channel=CP50PPW2X)

**Comment by yablu** [comment]
SectorID:	12
Status:		Removing
CIDcommD:	<nil>
CIDcommR:	<nil>
Ticket:		
TicketH:	0
Seed:		
SeedH:		0
Precommit:	<nil>
Commit:		<nil>
Proof:		
Deals:		[0]
Retries:	0

Sector On Chain Info
SealProof:		3
Activation:		23656
Expiration:		1574369
DealWeight:		0
VerifiedDealWeight:		0
InitialPledge:		532019489456735273

Expiration Info
OnTime:		0
Early:		0
--------
Event Log:
0.	2020-09-11 18:28:51 +0100 BST:	[event;sealing.SectorStartCC]	{"User":{"ID":12,"SectorType":3,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}},"DealInfo":null}]}}
1.	2020-09-11 18:28:51 +0100 BST:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
2.	2020-09-11 18:28:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
3.	2020-09-11 18:29:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
4.	2020-09-11 18:29:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
5.	2020-09-11 18:30:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
6.	2020-09-11 18:30:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
7.	2020-09-11 18:31:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
8.	2020-09-11 18:31:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
9.	2020-09-11 18:32:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
10.	2020-09-11 18:32:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
11.	2020-09-11 18:33:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
12.	2020-09-11 18:33:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
13.	2020-09-11 18:34:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
14.	2020-09-11 18:34:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
15.	2020-09-11 18:35:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
16.	2020-09-11 18:35:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
17.	2020-09-11 18:36:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
18.	2020-09-11 18:36:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
19.	2020-09-11 18:37:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
20.	2020-09-11 18:37:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
21.	2020-09-11 18:38:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
22.	2020-09-11 18:38:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
23.	2020-09-11 18:39:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
24.	2020-09-11 18:39:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
25.	2020-09-11 18:40:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
26.	2020-09-11 18:40:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
27.	2020-09-11 18:41:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
28.	2020-09-11 18:41:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
29.	2020-09-11 18:42:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
30.	2020-09-11 18:42:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
31.	2020-09-11 18:43:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
32.	2020-09-11 18:43:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
33.	2020-09-11 18:44:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
34.	2020-09-11 18:44:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
35.	2020-09-11 18:45:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
36.	2020-09-11 18:45:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
37.	2020-09-11 18:46:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
38.	2020-09-11 18:46:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
39.	2020-09-11 18:47:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
40.	2020-09-11 18:47:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
41.	2020-09-11 18:48:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
42.	2020-09-11 18:48:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
43.	2020-09-11 18:49:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
44.	2020-09-11 18:49:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
45.	2020-09-11 18:50:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
46.	2020-09-11 18:50:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
47.	2020-09-11 18:51:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
48.	2020-09-11 18:51:51 +0100 BST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
49.	2020-09-11 18:52:51 +0100 BST:	[event;sealing.SectorRemove]	{"User":{}}
50.	2020-09-11 18:52:51 +0100 BST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}

**Comment by arajasek** [comment]
From @ZenGround0 

```
A quick look at the code tells me that sector numbers are allocated during precommit and can never be unallocated or reallocated.  So if you precommit and fail to prove commit so your precommit times out then you end up in this state.  One of the comments mentions this happens after commit fail.
My guess is this allocation on pre commit as opposed to prove commit is news to lotus software. 
```

**Comment by yablu** [comment]
Also noticed that the message:

`insufficient funds for pre-commit deposit`

... appears frequently in the lotus-miner log despite having enough funds available.

**Comment by jennijuju** [comment]
> Also noticed that the message:
> 
> `insufficient funds for pre-commit deposit`
> 
> ... appears frequently in the lotus-miner log despite having enough funds available.

@yablu interesting, I have been seeing this a lot lately. Mind telling me whcih version of lotus are you using?

**Comment by yablu** [comment]
Not at all @jennijuju 

`lotus version 0.7.0+git.232cc320`
`lotus-miner version 0.7.0+git.232cc320`

I had to endure 12 hours with this issue yesterday (after a totally fresh install) and ended up with 42 `SealPreCommitFailed` sectors in a row before it just suddenly started working.

I monitored the miner screen for the majority of the 12 hours and the `insufficient funds for pre-commit deposit` was noticeable in every one and frequently repeated.

It doesn't seem to be occurring now at all since it has started working

My miner had adequate available funds for the entire 12 hours.

I have seen a few comments speculating that it might be something to do with Deadlines but nobody was sure. I must admit that the way my system just suddenly started committing yesterday  without any  changes from me made me wonder if they might be on to something.

**Comment by jennijuju** [comment]
> Not at all @jennijuju
> 
> `lotus version 0.7.0+git.232cc320`
> `lotus-miner version 0.7.0+git.232cc320`
> 
> I had to endure 12 hours with this issue yesterday (after a totally fresh install) and ended up with 42 `SealPreCommitFailed` sectors in a row before it just suddenly started working.
> 
> I monitored the miner screen for the majority of the 12 hours and the `insufficient funds for pre-commit deposit` was noticeable in every one and frequently repeated.
> 
> It doesn't seem to be occurring now at all since it has started working
> 
> My miner had adequate available funds for the entire 12 hours.
> 
> I have seen a few comments speculating that it might be something to do with Deadlines but nobody was sure. I must admit that the way my system just suddenly started committing yesterday without any changes from me made me wonder if they might be on to something.

@yablu do you  have enough funds in your worker address too?

**Comment by yablu** [comment]
I did have enough funds. I backed up all my wallets before the wipe and reinstall. The wallets had exactly the same balances as they did before the wipe.

**Comment by yablu** [comment]
also @jennijuju, my logs from the failed commits yesterday looked exactly the same as the ones that have already been posted in this thread. The `insufficient funds for pre-commit deposit` isn't mentioned in the logs but it is definitely featuring in the live feeds.

**Comment by yablu** [comment]
I only mention it @jennijuju because maybe the `insufficient funds for pre-commit deposit` error is the reason the PreCommit's aren't making it on to the chain??

**Comment by jennijuju** [comment]
> I only mention it @jennijuju because maybe the `insufficient funds for pre-commit deposit` error is the reason the PreCommit's aren't making it on to the chain??

Makes sense! Could you please provide your miner id here too? Thanks a lot

**Comment by yablu** [comment]
> > I only mention it @jennijuju because maybe the `insufficient funds for pre-commit deposit` error is the reason the PreCommit's aren't making it on to the chain??
> 
> Makes sense! Could you please provide your miner id here too? Thanks a lot

Of course `t08403`

**Comment by yablu** [comment]
@jennijuju Quick update ... just looking through logs for the 3 times this has happened to me and noticed that the commit's suddenly started working at 22:00 UTC every time.

**Comment by jennijuju** [comment]
In [miner_actor](https://github.com/filecoin-project/specs-actors/blob/c50e8c1aa39b3e623e1ae42042b7b87cea67e610/actors/builtin/miner/miner_actor.go#L473), successfully [allocated sector number](https://github.com/filecoin-project/specs-actors/blob/c50e8c1aa39b3e623e1ae42042b7b87cea67e610/actors/builtin/miner/miner_actor.go#L551), but failed [PutPreCommittedSector](https://github.com/filecoin-project/specs-actors/blob/c50e8c1aa39b3e623e1ae42042b7b87cea67e610/actors/builtin/miner/miner_actor.go#L582).

Which leads to handlePrecommit1 -> getTicket failed [StateSectorPreCommitInfo](https://github.com/filecoin-project/lotus/blob/d3ddd3bff94fcc2b418df97627c8408c544ea0dc/storage/adapter_storage_miner.go#L212)

**Comment by jennijuju** [comment]
I noticed that in most cases, there is a restarting miner involved

**Comment by jennijuju** [comment]
To reproduce:
- Have a sector proceed to any state after Committing (I think it should be any state after PreCommitting, but hard to simulate in devnet)
- update the state to to any state before PC1(include PC1)
- Then the sector is stuck with ```storage-sealing/fsm.go:475	sector 4 got error event sealing.SectorSealPreCommit1Failed: getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn’t found on chain```
- If sector is somehow proceeded or stayed in PC1/Packing fine, restart the miner, it will be stuck with the above error again.

**Comment by jennijuju** [comment]
I was also able to recover some of the sectors.

When the sector has `Commit` id in `sectors status`, force update it to SubmitCommit and restart the miner can successfully move the sectors to Proving

**Comment by jennijuju** [comment]
Seems like pledged collateral is locked  too

**Comment by William8Work** [comment]
unfortunately my miner bumped into this problems several times in the last day or two. Had to remove the sectors. Hope this could be fixed soon.

**Comment by jennijuju** [comment]
why this is happening: so there is an upper bound limit between you finished precommits and send the commit message to the network. if it exceeds that. for security reason, the network wont accept it again
For now, we recommend miners to remove the sector
