### ISSUE TITLE
Clear cache and unused files

### ISSUE THREAD

**Issue by nad010286** [filecoin-project/lotus#3757]
I believe the miner need to do a better job to clear cache and unused files on both workers + storage location or a lot of space will be wasted.
I have many issues with workers doing nothing as there is no space available and one of the main reasons are nvme is filled with unused/cached files.

Recently I have many sectors stuck at FinalizeSector and finally I found out it is because my storage location is filled with files in cache and unsealed folders.

**Comment by Reiers** [comment]
Hi @nad010286 

Thanks for the report. The issue is outdated. If you still think that Lotus need to do a better job clear files in the [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)  - please open a new ticket.

Thank you !
