### ISSUE TITLE
Balance drop from 200 FIL to 0 but no related messages observed

### ISSUE THREAD

**Issue by zlhwdsz** [filecoin-project/lotus#3760]
**Describe the bug**
Two messages saying transfer of 100 FIL from the faucet to the address yet the balance is 0.

**To Reproduce**
https://filfox.info/en/address/t3v5hwdkgfcvjfeqykmqxdviwv7iobtx26nhphgqk3y464kmpnzwuihsh36mklbnpiwxx3vdi5qehjjyzmyf2a

**Expected behavior**
200 FIL balance

**Screenshots**
![image](https://user-images.githubusercontent.com/67892702/92861311-ecb0c400-f42b-11ea-9adc-7e65703a0c57.png)

**Version (run `lotus version`):**
0.7.0

**Comment by arajasek** [comment]
Balances were updated in a network upgrade on the 8th of September. See https://github.com/filecoin-project/lotus/pull/3632.
