### ISSUE TITLE
NOT work "lotus sync" and Not work lotus-miner too

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#3770]
**Describe the bug**
Because lotus-miner did not work because of the attached error message, I restarted the lotus daemon, but lotus does not work.

**To Reproduce**
1. Run 'lotus-miner'
2. See error
----------------------------------------------------------------------------------------------------------------------------------------------
 github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
        /mnt/filecoin/nyzell/lotus/chain/sync.go:1222
2020-09-12T00:20:00.597+0900    INFO    sub     sub/incoming.go:83      new block over pubsub   {"cid": "bafy2bzaceb5zn3zz24bytyyjquyygfd7tplq2b5a5bu3j6qvvzjn2rmkp7622", "source": "12D3KooWMaChtj8D3XpNSc45p4g2K41PNrptwjX12F4qi3dV6Aed", "msgfetch": 0.316818956}
2020-09-12T00:20:00.598+0900    INFO    sub     sub/incoming.go:83      new block over pubsub   {"cid": "bafy2bzacecvgmbceopm3mpqxbtar6it5vvssmosl7honmxgmigzgiprwwcptg", "source": "12D3KooWSTTwVXcNhMpH4PLhkxns4V3zuE9kHCw92KghVH3GG3pw", "msgfetch": 0.166460831}
2020-09-12T00:20:01.082+0900    ERROR   chain   chain/sync_manager.go:389       sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /mnt/filecoin/nyzell/lotus/chain/sync.go:554
  - chain linked to block marked previously as bad ([bafy2bzaceb5zn3zz24bytyyjquyygfd7tplq2b5a5bu3j6qvvzjn2rmkp7622], bafy2bzacec4tggwk5bnushymwmjhavx252z7tsqcede2wpyxrtus2eyjsuxtg) (reason: linked to bafy2bzacedbbtulqembg542qyj3gsulhfm7excz46azywhj25iwyj7gxntuvg caused by: [bafy2bzacedxlqbe6hbhdcsheotw6dpm2s3joznmnpddwsrhx33abgzfafyu7i] 1 error occurred:
        * failed to validate blocks random beacon values:
        github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func8
            /mnt/filecoin/nyzell/lotus/chain/sync.go:867
      - expected final beacon entry in block to be at round 132085, got 146844:
        github.com/filecoin-project/lotus/chain/beacon.ValidateBlockValues
            /mnt/filecoin/nyzell/lotus/chain/beacon/beacon.go:46

    ):
    github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
        /mnt/filecoin/nyzell/lotus/chain/sync.go:1222
2020-09-12T00:20:01.082+0900    INFO    sub     sub/incoming.go:83      new block over pubsub   {"cid": "bafy2bzacebb6zndot3uajsdzjvmj5xuhqp3fxax3owvttc5wj3xorimwzxl3e", "source": "12D3KooWER7YukyyWq5jXpbvrfXt3UewMWhU7KSZiNjrykWFiT1C", "msgfetch": 0.717747567}
2020-09-12T00:20:01.266+0900    ERROR   chain   chain/sync_manager.go:389       sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /mnt/filecoin/nyzell/lotus/chain/sync.go:554
  - chain linked to block marked previously as bad ([bafy2bzacecvgmbceopm3mpqxbtar6it5vvssmosl7honmxgmigzgiprwwcptg], bafy2bzacec4tggwk5bnushymwmjhavx252z7tsqcede2wpyxrtus2eyjsuxtg) (reason: linked to bafy2bzacedbbtulqembg542qyj3gsulhfm7excz46azywhj25iwyj7gxntuvg caused by: [bafy2bzacedxlqbe6hbhdcsheotw6dpm2s3joznmnpddwsrhx33abgzfafyu7i] 1 error occurred:
        * failed to validate blocks random beacon values:
        github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func8
            /mnt/filecoin/nyzell/lotus/chain/sync.go:867
      - expected final beacon entry in block to be at round 132085, got 146844:
        github.com/filecoin-project/lotus/chain/beacon.ValidateBlockValues
            /mnt/filecoin/nyzell/lotus/chain/beacon/beacon.go:46

    ):
    github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
        /mnt/filecoin/nyzell/lotus/chain/sync.go:1222
2020-09-12T00:20:01.827+0900    ERROR   chain   chain/sync_manager.go:389       sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /mnt/filecoin/nyzell/lotus/chain/sync.go:554
  - chain linked to block marked previously as bad ([bafy2bzacebb6zndot3uajsdzjvmj5xuhqp3fxax3owvttc5wj3xorimwzxl3e], bafy2bzacec4tggwk5bnushymwmjhavx252z7tsqcede2wpyxrtus2eyjsuxtg) (reason: linked to bafy2bzacedbbtulqembg542qyj3gsulhfm7excz46azywhj25iwyj7gxntuvg caused by: [bafy2bzacedxlqbe6hbhdcsheotw6dpm2s3joznmnpddwsrhx33abgzfafyu7i] 1 error occurred:
        * failed to validate blocks random beacon values:
        github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func8
            /mnt/filecoin/nyzell/lotus/chain/sync.go:867
      - expected final beacon entry in block to be at round 132085, got 146844:
        github.com/filecoin-project/lotus/chain/beacon.ValidateBlockValues
            /mnt/filecoin/nyzell/lotus/chain/beacon/beacon.go:46

    ):
----------------------------------------------------------------------------------------------------------------------------------------------
And lotus daemon stop and lotus daemon 

sync status:
worker 0:
        Base:   [bafy2bzaceb7tcboiorzkrfzhav2npd4js456o5lp3nkj5dcf2xruftqapmul4 bafy2bzacebjvchvcr327zroigcuh4uqenqwf
mofwrrenet3ws26vl22xpn2xi]
        Target: [bafy2bzacebvpbwief4h4jiu4oiigjowwkctmye5b54opkq2bhgmpew6vfb6g6] (51055)
        Height diff:    56
        Stage: error
        Height: 51055
        Elapsed: 4.703709293s
        Error: chain contained block marked previously as bad ([bafy2bzacebvpbwief4h4jiu4oiigjowwkctmye5b54opkq2bhgmp
ew6vfb6g6], bafy2bzacea2ats2tq5355k4m4vyfn5mmgvkexwo4jlrecun2dxikmhwytlbga) (reason: change contained bafy2bzacearr3o
3mxav5c2jbvyef7pfnklsrqjdjer5bvejmd2i4ghiad7ik4 caused by: [bafy2bzacedxlqbe6hbhdcsheotw6dpm2s3joznmnpddwsrhx33abgzfa
fyu7i] 1 error occurred:
        * failed to validate blocks random beacon values:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func8
        /mnt/filecoin/nyzell/lotus/chain/sync.go:867
  - expected final beacon entry in block to be at round 132085, got 146844:
    github.com/filecoin-project/lotus/chain/beacon.ValidateBlockValues
        /mnt/filecoin/nyzell/lotus/chain/beacon/beacon.go:46

)
worker 1:
        Base:   [bafy2bzaceb7tcboiorzkrfzhav2npd4js456o5lp3nkj5dcf2xruftqapmul4 bafy2bzacebjvchvcr327zroigcuh4uqenqwf
mofwrrenet3ws26vl22xpn2xi]
        Target: [bafy2bzacec4znq2cjbmpss6afkh2wsnimhmzfcnxky6l3lymszurvrljowbjk] (51079)
        Height diff:    80
        Stage: error
        Height: 0
        Elapsed: 68.328µs
        Error: chain linked to block marked previously as bad ([bafy2bzacec4znq2cjbmpss6afkh2wsnimhmzfcnxky6l3lymszur
vrljowbjk], bafy2bzacedve4pjsqmwhd2rj6qish2igbiqjgml74otxac4snzmysfy2l7aje) (reason: linked to bafy2bzacecyjpeiyqmvym
ywpwf7uez37bs7zigvduv6drhrtuwjaw4fekjhh4 caused by: [bafy2bzacedxlqbe6hbhdcsheotw6dpm2s3joznmnpddwsrhx33abgzfafyu7i]
1 error occurred:
        * failed to validate blocks random beacon values:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func8
        /mnt/filecoin/nyzell/lotus/chain/sync.go:867
  - expected final beacon entry in block to be at round 132085, got 146844:
    github.com/filecoin-project/lotus/chain/beacon.ValidateBlockValues
        /mnt/filecoin/nyzell/lotus/chain/beacon/beacon.go:46

)
worker 2:
        Base:   [bafy2bzaceb7tcboiorzkrfzhav2npd4js456o5lp3nkj5dcf2xruftqapmul4 bafy2bzacebjvchvcr327zroigcuh4uqenqwf
mofwrrenet3ws26vl22xpn2xi]
        Target: [bafy2bzaceckxcxqvizfexgs3wcsnookb7j2wjwqnd7n5hgarkzhbrcpfllqey] (51055)
        Height diff:    56
        Stage: error
        Height: 51055
        Elapsed: 1.811245333s
        Error: chain contained block marked previously as bad ([bafy2bzaceckxcxqvizfexgs3wcsnookb7j2wjwqnd7n5hgarkzhb
rcpfllqey], bafy2bzacea2ats2tq5355k4m4vyfn5mmgvkexwo4jlrecun2dxikmhwytlbga) (reason: change contained bafy2bzacearr3o
3mxav5c2jbvyef7pfnklsrqjdjer5bvejmd2i4ghiad7ik4 caused by: [bafy2bzacedxlqbe6hbhdcsheotw6dpm2s3joznmnpddwsrhx33abgzfa
fyu7i] 1 error occurred:
        * failed to validate blocks random beacon values:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func8
        /mnt/filecoin/nyzell/lotus/chain/sync.go:867
  - expected final beacon entry in block to be at round 132085, got 146844:
    github.com/filecoin-project/lotus/chain/beacon.ValidateBlockValues
        /mnt/filecoin/nyzell/lotus/chain/beacon/beacon.go:46

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
Daemon:  0.6.1+git.867469e9.dirty+api0.14.0
Local: lotus version 0.6.1+git.867469e9.dirty

**Additional context**

**Comment by hsjw12** [comment]
I finally succeeded. Thank you for your help.

**Comment by creaz79** [comment]
Hello!
Have same error while syncing chain. What I have to do to fix it?
lotus version 0.6.2+git.8b2862a1

**Comment by hsjw12** [comment]
Since I stopped the lotus service and upgraded lotus to 0.7.0, no sync error occurred.

**Comment by creaz79** [comment]
Thank you, but 0.7.0 one version crashed and other not syncing at all on my server, waiting until they fix it.
Can you write exact build of 0.7.0

**Comment by creaz79** [comment]
You give me an idea, I always built with native support, I have tried rebuild without native support 0.7.0 and all become fine.
Error gone and sync restored. Thank you!
