### ISSUE TITLE
lotus-miner id

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#3782]
**Describe the bug**
Why is the miner id in the lotus-miner actor control list result different from the miner id in the lotus-miner or lotus-miner proving info result?

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
Daemon: 0.7.0
Local: lotus version 0.7.0

Additional context

**Additional context**

**Comment by hsjw12** [comment]
$lotus-miner actor control list
name    ID       key           use         balance
owner   t019545  t3rttu3of...  other post  4.237232674589560668 FIL
worker  t019545  t3rttu3of...  other post  4.237232674589560668 FIL

####################################################

$lotus-miner info
Miner: t019660
Sector Size: 32 GiB
Byte Power:   0 B / 192.7 PiB (0.0000%)
Actual Power: 0  / 193 Pi (0.0000%)
        Committed: 0 B
        Proving: 0 B
Below minimum power threshold, no blocks will be won
Deals: 46, 344.1 MiB
        Active: 0, 0 B (Verified: 0, 0 B)

Miner Balance: 0 FIL
        PreCommit:   0 FIL
        Pledge:      0 FIL
        Locked:      0 FIL
        Available:   0 FIL
Worker Balance: 4.237232674589560668 FIL
Market (Escrow):  0 FIL
Market (Locked):  0 FIL

Expected Seal Duration: 12h0m0s

Sectors:
        Total: 6
        PreCommit1: 6

OR

$lotus-miner proving info
Miner: t019660
Current Epoch:           52729
Proving Period Boundary: 2256
Proving Period Start:    51216 (12h36m30s ago)
Next Period Start:       54096 (in 11h23m30s)

Faults:      0 (0.00%)
Recovering:  0
Deadline Index:       25
Deadline Sectors:     0
Deadline Open:        52716 (6m30s ago)
Deadline Close:       52776 (in 23m30s)
Deadline Challenge:   52696 (16m30s ago)
Deadline FaultCutoff: 52646 (41m30s ago)

**Comment by jennijuju** [comment]
You can find the definition of the actor, miner info, worker and owner [here](https://github.com/filecoin-project/lotus/blob/c074c8d0ca0d9907099343250224fa3aed7b48d5/documentation/en/dev/create-miner.md)
