### ISSUE TITLE
After upgrading lotus versions, WaitDeals will not progress

### ISSUE THREAD

**Issue by danny-wu** [filecoin-project/lotus#3785]
**Describe the bug**
If there is a pending `WaitDeals` before an upgrade of lotus, it will not progress after restarting lotus and lotus-miner.

This has been observed from `0.5.x` -> `0.6.0` as well as `0.6.2` -> `0.7.0`.

**To Reproduce**
1. Have a sector in `WaitDeals`
2. Upgrade `lotus` and `lotus-miner`
3. The sector will continue to be in `WaitDeals` forever, way after the WaitDealsDelay, and it will never seal unless it is manually started.

**Expected behavior**
`WaitDeals` automatically seals.

**Comment by jennijuju** [comment]
Does it only happen when performing a restart after an upgrade or always happened after any restart?

**Comment by danny-wu** [comment]
I only restart after upgrades unfortunately so I'm not able to answer, sorry :(
