### ISSUE TITLE
some messages in mpool disappeared

### ISSUE THREAD

**Issue by NealLiu-Test2** [filecoin-project/lotus#3789]
**Describe the bug**
in space race, my miner id is **t02490,** 
worker address is **t3qlp7se6vaw6yg3sjm2pme3xbfw7avhjng2ilmkejujbmxrsv7v5netdonvcrj5rez5epawkxpnzaei27esna**.  
messages in mpool is begin from 69011, but  in filfox.io and other explorer， the biggest Nonce i can found is 68980. the messages with Nonce 68981-69010 were disappeared , neither on the chain nor in the mpool.  messages in mpool cannot go to the chain now. because there is no messages with 68981.....................

**To Reproduce**
1. I used `lotus mpool replace` to increase the gas of some message , so let them go to the chain.
2. after running some `lotus mpool replace`  commands, i found messages with Nonce 68981-69010 were disappeared.

**Expected behavior**
is this a bug ? how can i find the disappeared messages back?

**Screenshots**
https://filecoinproject.slack.com/files/U0197DEDKLN/F01AKC1H1T4/image.png

**Version (run `lotus version`):**
lotus version 0.7.0+git.232cc320

**Additional context**

**Comment by NealLiu-Test2** [comment]
after restarting the daemon, the lost messages finally go to the chain, but several hours have passed since them disappeared. if i dont restart the daemon, it will never go to the chain. this must be a bug!

**Comment by vyzo** [comment]
it's a bug, and it has been fixed in https://github.com/filecoin-project/lotus/pull/3772 (it's merged in master).
