### ISSUE TITLE
[Feature Request] Be able to seal the deals that are still valid in a WaitDeals sector while there is invalid deals

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3790]
related: #3595  #3594 

When do `sectors seal` on a WaitDeals sector with deals to be removed and fresh deals, all deals are removed.

Expected to keep the valid deals and proceed to seal.

**Comment by arajasek** [comment]
I'm not sure why all the deals would be removed in this case, but we need to fix that
