### ISSUE TITLE
[ feature request ] make fast-retrieval really fast! (UX related)

### ISSUE THREAD

**Issue by leviok** [filecoin-project/lotus#3791]
in current implemention, pieces can only be retrieved after declaring sector in sector index store. i think it can be much more earlier.

i hope it can be retrieved after piece recieved. after piece recieved, piece data can be found in miner storage, and it will not be deleted before sealing completed.

if this is implemented. filecoin will more useable. storing and retrieving on filecoin will be much more faster. it only spent some more time on communicate with chain. dont need waiting for sealing at all.

@hannahhoward @whyrusleeping

**Comment by ribasushi** [comment]
@leviok you mean like this? https://github.com/filecoin-project/lotus/pull/3778
😜

**Comment by magik6k** [comment]
This was a bug, mostly, fixed in #3778
