### ISSUE TITLE
StorageDeal too early

### ISSUE THREAD

**Issue by Storage-Hive** [filecoin-project/lotus#3795]
Got storagedeal error on dealid which didn't exist yet. Deal from bot was requested at Sat, 12 Sep 2020 21:31:20 GMT, however miner only built it 6 minutes later at: Sat, 12 Sep 2020 21:38:29 GMT, which resulted in "failed to lookup deal on chain" from bot as it didn't exist yet when the bot requested it.

store |  x  |
bafk2...l3y7e | bafyr...zzisq | 100 | StorageDealError | ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreidrxgzcaqnzkj4m32uogtqo2ovvs2t72xs6axons2lvymlqrzzisq"},"State":26,"Message":"error in deal activation: failed to set up called handler: called check error (h: 54666): client: failed to look up deal on chain: deal 125228 not found","Provider":"t010438","DataRef":null,"PieceCID":{"/":"baga6ea4seaql4pgzzagnfbxaeububnmdks7tle2dq3j5dalwsfptkljxc7y5mca"},"Size":130048,"PricePerEpoch":"0","Duration":705423,"DealID":125228,"CreationTime":"2020-09-12T21:31:20.234619464Z"},"id":0} | 
Sat, 12 Sep 2020 21:31:20 GMT

grep 125228 /logs/miner.log (EST time zone)
2020-09-12T17:38:29.614-0400	INFO	sectors	storage-sealing/sealing.go:144	Adding piece for deal 125228 (publish msg: bafy2bzaceasdfluwsgvkz7enoqd5to3vp27oqgt4lrwniah6jfnp7jy6zzesk)
2020-09-12T17:38:29.798-0400	WARN	storageadapter	storageadapter/provider.go:106	New Deal: deal 125228

lotus version 0.7.0+git.aa83a4c1

**Comment by jennijuju** [comment]
Duplicated #3461
