### ISSUE TITLE
Bot reports storage deal error when status is actually pending

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#3796]
**Describe the bug**
My dashboard logs show a StorageDealError when true status is StorageDealStaged
Deal seen at 2020-09-12T21:41:59.296 error reported at 2020-09-12T21:35:51

**To Reproduce**
Automatic results  - miner is running stock code, single miner no remote workers

**Expected behavior**
Looks like timeout for error is too fast.
The miner will update chain when AP job runs in 4 hours after PC1 completes.

**Screenshots**
**Dashboard status** [Dashboard log](https://spacerace.filecoin.io/deals/t01278) 

> bafk2...wr5ve | bafyr...nlfka | 100 | StorageDealError | ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreifoeny2mfsc2zdkxgsrv5m2yexrwf2s3gfhiwdnyqt4a2z6hnlfka"},"State":26,"Message":"error in deal activation: failed to set up called handler: called check error (h: 54670): client: failed to look up deal on chain: deal 125262 not found","Provider":"t01278","DataRef":null,"PieceCID":{"/":"baga6ea4seaqguqqgnwjpbykchx7cm4yjuku243uhbtkgu7zlrd2iyblawwg74di"},"Size":130048,"PricePerEpoch":"0","Duration":704797,"DealID":125262,"CreationTime":"2020-09-12T21:35:51.005264993Z"},"id":0} | Sat, 12 Sep 2020 21:35:51 GMT
> -- | -- | -- | -- | -- | --

**Miner status in logs and deal list**

`lotus-miner storage-deals list |grep 125262`

> ...z6hnlfka  125262  StorageDealStaged        t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i                                               128KiB  0 FIL                     704797

`grep 125262 /mypool/logs/miner.log`

> 2020-09-12T21:41:59.296Z	INFO	sectors	storage-sealing/sealing.go:144	Adding piece for deal 125262 (publish msg: bafy2bzacedtftydp56tmoqufawmcjbny6yjgp3ve4ioq4heb7luewhwjvrhlq)

**Version (run `lotus version`):**
`lotus-miner version`

> Daemon:  0.7.0+git.232cc320+api0.14.0
> Local: lotus-miner version 0.7.0+git.232cc320

**Additional context**
![WaitDeal assigned to AP](https://user-images.githubusercontent.com/49840642/93006982-27e8eb00-f531-11ea-81b1-6dd6a93c20fd.png)

![Sectors list screenshot](https://user-images.githubusercontent.com/49840642/93007005-68486900-f531-11ea-8e41-781feb8c1ecc.png)

Using Ryzen 9 3900x 128GB RAM Ubuntu 20.04 server 1080Ti GPU NVMe disks for all but long term storage

**Comment by mxz9102** [comment]
I just see this storage deal failure in both of my miners. It doesn't look like an error on my side.
![image](https://user-images.githubusercontent.com/15658707/93007150-32e45100-f51a-11ea-99e0-84d1becade9b.png)

 I checked the list of storage deals and this deal is still sealing.
![image](https://user-images.githubusercontent.com/15658707/93007140-ffa1c200-f519-11ea-8ad9-9be53009ac36.png)

**Comment by yablu** [comment]
ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreifzgreugr6jozurljn32qxcsdmjcumvrjrapp5v2te5uoueezy3hq"},"State":26,"Message":"error in deal activation: failed to set up called handler: called check error (h: 55248): client: failed to look up deal on chain: deal 126453 not found","Provider":"t08403","DataRef":null,"PieceCID":{"/":"baga6ea4seaqcspc45laa2m4dqx6sifnpodm7lx2hgnqkwnclyysyjtujk5pjooq"},"Size":130048,"PricePerEpoch":"61035","Duration":704075,"DealID":126453,"CreationTime":"2020-09-13T02:27:14.344371505Z"},"id":0}

**Comment by jennijuju** [comment]
Closing since this is space race bot related - not lotus related. and any potential lotus issue caused these error msg has their own ticket already.
