### ISSUE TITLE
lotus-miner sectors mark-for-upgrade 0 won't upgrade sectors 

### ISSUE THREAD

**Issue by Snow-Sudo** [filecoin-project/lotus#3797]
**Describe the Bug**
lotus-miner sectors list shows sector zero 

> 0: Proving    sSet: YES active: YES tktH: 48243 seedH: 51073 deals: [0]  toUpgrade:true
>
The active is still set to yes 24 hours after the running the command lotus-miner sectors mark-for-upgrade 0. 

**To Reproduce**
run `lotus-miner sectors mark-for-upgrade 0`
wait 24 hours
run 'lotus-miner sectors list' to see if active has change from YES to NO 

**Sector Logs** 

> miner@miner-MS-7C37:~$ lotus-miner sectors status --log 0
SectorID:	0
Status:		Proving
CIDcommD:	baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq
CIDcommR:	bagboea4b5abcai3zvet3rds5oiy223lv77uahkohpjtatr6ognhd2hcgki6fmpiq
Ticket:		fedbec264910f722d84124fcfad72dd82c87da8fbb29ae7f6a88fb49263bc908
TicketH:	48243
Seed:		b801b41ab538654e91ef07fae4b01c683289c9747a4a424bcd6510b3e839a507
SeedH:		51073
Precommit:	bafy2bzaceamz24ug4gjxdpmih4gnkwbs7a7lch2p6hb4l23rkbe255jl3jjcw
Commit:		bafy2bzacecfptnmsugyv4gkwme7po4262cdmaoiaapvlh7vkwaerxsaseze6e	

> --------
> Event Log:
> 0.	2020-09-10 19:31:56 -0400 EDT:	[event;sealing.SectorStartCC]	{"User":{"ID":0,"SectorType":3,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}},"DealInfo":null}]}}
> 1.	2020-09-10 19:31:56 -0400 EDT:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
> 2.	2020-09-10 23:36:17 -0400 EDT:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjEiLCJsYWJlbHMiOnsiU3RhY2tlZERyZzMyR2lCVjEiOnsibGFiZWxzIjpbeyJwYXRoIjoiL21lZGlhL21pbmVyL1NTRC9jYWNoZS9zLXQwMTk0NTktMCIsImlkIjoibGF5ZXItMSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL21pbmVyL1NTRC9jYWNoZS9zLXQwMTk0NTktMCIsImlkIjoibGF5ZXItMiIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL21pbmVyL1NTRC9jYWNoZS9zLXQwMTk0NTktMCIsImlkIjoibGF5ZXItMyIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL21pbmVyL1NTRC9jYWNoZS9zLXQwMTk0NTktMCIsImlkIjoibGF5ZXItNCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL21pbmVyL1NTRC9jYWNoZS9zLXQwMTk0NTktMCIsImlkIjoibGF5ZXItNSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL21pbmVyL1NTRC9jYWNoZS9zLXQwMTk0NTktMCIsImlkIjoibGF5ZXItNiIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL21pbmVyL1NTRC9jYWNoZS9zLXQwMTk0NTktMCIsImlkIjoibGF5ZXItNyIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL21pbmVyL1NTRC9jYWNoZS9zLXQwMTk0NTktMCIsImlkIjoibGF5ZXItOCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL21pbmVyL1NTRC9jYWNoZS9zLXQwMTk0NTktMCIsImlkIjoibGF5ZXItOSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21lZGlhL21pbmVyL1NTRC9jYWNoZS9zLXQwMTk0NTktMCIsImlkIjoibGF5ZXItMTAiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9tZWRpYS9taW5lci9TU0QvY2FjaGUvcy10MDE5NDU5LTAiLCJpZCI6ImxheWVyLTExIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fV0sIl9oIjpudWxsfX0sImNvbmZpZyI6eyJwYXRoIjoiL21lZGlhL21pbmVyL1NTRC9jYWNoZS9zLXQwMTk0NTktMCIsImlkIjoidHJlZS1kIiwic2l6ZSI6MjE0NzQ4MzY0Nywicm93c190b19kaXNjYXJkIjo3fSwiY29tbV9kIjpbNywxMjYsOTUsMjIyLDUzLDE5NywxMCwxNDcsMywxNjUsODAsOSwyMjcsNzMsMTM4LDc4LDE5MCwyMjMsMjQzLDE1Niw2NiwxODMsMTYsMTgzLDQ4LDIxNiwyMzYsMTIyLDE5OSwxNzUsMTY2LDYyXX0=","TicketValue":"/tvsJkkQ9yLYQST8+tct2CyH2o+7Ka5/aoj7SSY7yQg=","TicketEpoch":48243}}
> 3.	2020-09-11 07:52:26 -0400 EDT:	[event;sealing.SectorRestart]	{"User":{}}
> 4.	2020-09-11 09:45:56 -0400 EDT:	[event;sealing.SectorRestart]	{"User":{}}
> 5.	2020-09-11 10:20:24 -0400 EDT:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcai3zvet3rds5oiy223lv77uahkohpjtatr6ognhd2hcgki6fmpiq"},"Unsealed":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}}
> 6.	2020-09-11 10:20:24 -0400 EDT:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzaceamz24ug4gjxdpmih4gnkwbs7a7lch2p6hb4l23rkbe255jl3jjcw"},"PreCommitDeposit":"369839545961990962","PreCommitInfo":{"SealProof":3,"SectorNumber":0,"SealedCID":{"/":"bagboea4b5abcai3zvet3rds5oiy223lv77uahkohpjtatr6ognhd2hcgki6fmpiq"},"SealRandEpoch":48243,"DealIDs":[],"Expiration":1602307,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}
> 7.	2020-09-11 10:24:30 -0400 EDT:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":"AXGg5AIgPqJjyeIss29v5mI2hffKp7pPfhKq9a215wTR3dyT1eIBcaDkAiBjV23xfQiQ2xQhJC7aSs2JcTt/QuqDJnCfeSTbGJTP4AFxoOQCIH820jcdQ1OGsqDU+GoyaKPIcyfbIBiDpxxiG6B8Gb6JAXGg5AIgr0QxDkTDmf4fwUUpaXIXaI9DrE7UonrsUaGPI1WpqJQBcaDkAiAHQci4FEwK1yiudtf4gjPSVlVoOCVRhhhR1CFVDsB6cwFxoOQCINmid0mjTrQ5D+ffKVawf+hntpJrCmkoN20gNI4dZd0d"}}
> 8.	2020-09-11 11:39:30 -0400 EDT:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"uAG0GrU4ZU6R7wf65LAcaDKJyXR6SkJLzWUQs+g5pQc=","SeedEpoch":51073}}
> 9.	2020-09-11 13:33:23 -0400 EDT:	[event;sealing.SectorCommitted]	{"User":{"Proof":"i+f54gfPpmVwIpBjSURs+dvGg4oBSYv/G/jBSnVvcURkyRQgzhxNzl/TR3tZJAMtsC7b84Mhi606mHyt1SsjHZi/yQyPMNj69LdvdfCp4pDk1ElyHJUfr7QYJOw/f2EfEq+T+mYQB8mgoTxf7HLQOiPFWnmFBpmZkBvdL/z4IUIbkhn/BNs+AwfOphqoAdvrlS35ApGiLINfRSMKSxlgGQUfvNwMn6Mn1Y7VZ7FRWuk5uTzqzAwK/mmce4n/f5XLswC7PWGMNKyYhcuXjSFMU34cT+KRlgj6QpMwHAyW6vKJvw9zo+kS4f4MGLFYwKN1st9nW0vjoie13Zc4/7c7HuOyCrGOFATlrFZg0DmcAugFS9m+kd92DYEa4AT2QKGYAaKuFIGXjBhMX59/YWw49p9HClTJD/UE7eki+vKTfstQQYGYEpfEttIZT0c4nURxsPSFWXyVlTV3KlKqMEbkxONnPCyVtj50DK8vcom671dpBKbFKl9RUmro9r+1UccbiC4txfiVC8RcOifT1bnMQqT0HSnFa22y30jl0M+o6/Yt0gIYctC9eeBJeADfa5F3svGxA+7xsSenX86LoZ3gwcZ1rszdJgYYwXJEXAQDnm9oglqnBrN6cW5Qf5AFS4IvDBFQQ/anMTGinbUdOm56fLtemdi8TJwKLFu9yaTw2WFJNY1vDnlvu/1aRD+WsWrFkMb5jRgTIh7HJLduPhd08d5VTlQ1W5iA1WIbnm2olBCeqLr0YnTYUAXjgTy1+rc7q4L6VML07JQC5nbdqZ+4n5Vk1xGZwjkpbIfxUavhFdex0FVoMc9U4erIEiF6thkZgbvlNeq7LOkWuVxWKom4E8x61ntbZCbl0RPIKEFJoDl6O/hyYhiO4ybYvYX5oHr2EYdODAotS/pcwZAZXxDiDabjkwWSIOr8B+JSTRyyaveUgAUVtO3rPzFjm6fUYJRYtAYGaCjlm+qgKCaIC+WnAoF3Nx54IXm4yzePeFSwBM4ObG4h4uJZPwnAGZZn+aszpPzyQOtAOA4anh1rm52AaOb+W2KKtoiSCJEGqDi49T+m7LJNKWz0q9+WQ2GPF70JkYtfvnOtH3ktfjrJo4f2OqrPW9x2wdMtg74E+jtfrcozDCBqrK9Cjsb2M3FjBQJjEwAzEOG/XX9HbGkMLLwyn2nDwM1ha6Stq2A8gFJYj9xQaZbEjasRlw/WO95D6/qArJ3RAYIAhee4GTMIGYB7uwI975S4DNPjR7U4XROqMj4f7ds1P4EmJE6m5ryM0nm8kHbvhqb/A9oN/KXaLAfZ/DCxYdyUKWzmFAAp94bxH7DR7+wA2X6XwoUzfO9MLP+atxWxhm5peE64s0zXfwtkJBPxspvSDqQX6Q+aVXOky1OesSZp5hzpNUN+BjrSeigmE4ip1qp7ArG8Skhm9r5TS0/HfDNfg1wF5nA83aQgWIUxdQb0moG+sY3T4pehG9u3oF7XP82jwFi3DYXNOrSTGrR7jlBsfNDMwHU8TJfFMcF+b5Pe/OC8rFYyHC2ulmULkh+eZsMYtA+Pfaf4bdjJbX2mOuiZDW4tpPR53ZJYch5FCLv0u2zntLbhTvOY2CMtrhT0Y7JVo5oSieCTgmlKeCJtwr/bwxnu/7ejE1YzCEm6EbtIm8pno4FYNPA4115wCs6ayjaFtCHmmpqwmb1zfqtjVdupj1DO5H5I9CDBe1Woc5j3FlxTPo5y26tipfLjjlmt1ZbWNfSeZeVIwTGSvAHA0ZLqPKVwXuZ45WQq9bB53eG7yz5aZgYp8xKfoPFKgtor2w8ON4LWx+L97XVFfn3mWtRvWRjOISfwGcO4Ct9dV2kUI3tlI7IF30c2vVibrWsyCaeZCTuQom7BLgEJG4ScsfwFP5TxyaZo1N2rkcpmavEqIxmy2bT9rfzeXy6xB0SISP5Mryw+kPfzIxQ2QY3DfiyXOVCmrqf5zgL4L8hdDQ5O39M5VR/EyTlmBCx9k8fXOH4HKv8Eoj4K/jCqeDBLOE9CUtQqaU13kiS6TQr0tkPoXY+5BpHi4a2XuZdXoq9dK3darpmMycIcwabYZZib1jzmM4lA1t5IXbyNuTNIdhz+dePxsxde4k7p18X4gzkuJKSiKr8U17zNW4EXqr9JIettvcVIqozj/z4W0rAbvQ+fIKw9ob34dnbjsiwZCv7RXQoscesJrxrofSqcUeOhSgIZYIaCJnYMoQeBiDqU2L4DYQCjlp5f5TJuGswjtd939NEi8LCLC10BA6LD9J5GjCnrSe+9szRABMGD4sN/VfOlvlCbRDLdKLuQZgNLr6NyZfZeckjzg8S+WJIpEZ4LideSp2Gs/mB3d6gW98ScFTqJuVdFYwmZW7Fbfl64j2Qb2xzvW3NHqXqy+GAZXIFnOUA/yXxYsaPwE3xIOdNzx/XN/UiRv4RsWO1hZgcdARnr+Ckpnge4G8wBEG28VpI7x5khIpJ8popp2FXJ98uJu+0drb0GtjNX48IwKEf0o87kPM8lTvSDwskYuLibD9qMm+rt6Vldz/aOqRYjPokp8Piok/XYjtZWFulY9cYs"}}
> 10.	2020-09-11 13:33:23 -0400 EDT:	[event;sealing.SectorCommitSubmitted]	{"User":{"Message":{"/":"bafy2bzacecfptnmsugyv4gkwme7po4262cdmaoiaapvlh7vkwaerxsaseze6e"}}}
> 11.	2020-09-11 13:42:30 -0400 EDT:	[event;sealing.SectorProving]	{"User":{}}
> 12.	2020-09-11 13:43:53 -0400 EDT:	[event;sealing.SectorFinalized]	{"User":{}}

>
**Lotus Version** 

> miner@miner-MS-7C37:~$ lotus version
> Daemon:  0.7.0+git.232cc320+api0.14.0
> Local: lotus version 0.7.0+git.232cc320

**Comment by jennijuju** [comment]
linked in #3834 for investigation
