### ISSUE TITLE
Lotus daemon crashed in the application launch.

### ISSUE THREAD

**Issue by harrisonhjc** [filecoin-project/lotus#3799]
lotus crashed  in the launch .

$lotus daemon
2020-09-13T10:29:30.427+0800	WARN	sub	sub/incoming.go:300	cannot validate block message; unknown miner or miner that doesn't meet min power in unsynced chain
2020-09-13T10:29:30.427+0800	WARN	sub	sub/incoming.go:300	cannot validate block message; unknown miner or miner that doesn't meet min power in unsynced chain
2020-09-13T10:29:30.628+0800	WARN	sub	sub/incoming.go:300	cannot validate block message; unknown miner or miner that doesn't meet min power in unsynced chain
2020-09-13T10:29:30.711+0800	INFO	hello	hello/hello.go:180	time offset	{"offset": -0.001655402, "peerid": "12D3KooWDMBQLHNfoHX9PXhkxDQW2xjR1JAa4ziizp3cybK7DzGF"}
SIGILL: illegal instruction
PC=0x17efe6e m=13 sigcode=2
instruction bytes: 0xf3 0x4c 0xf 0x38 0xf6 0xcf 0x66 0x4c 0xf 0x38 0xf6 0xd5 0xc4 0xe2 0xc3 0xf6

goroutine 0 [idle]:
runtime: unknown pc 0x17efe6e
stack: frame={sp:0x7f772affc8b8, fp:0x0} stack=[0x7f772a7fcec8,0x7f772affcac8)
00007f772affc7b8:  000000c0006e8000  000000c0006ea000 
00007f772affc7c8:  000000c012ade510  000000c012adf000 
00007f772affc7d8:  000000c012ade000  000000c012ade000 
00007f772affc7e8:  000000c012adf000  ffffffffedc0b000 
00007f772affc7f8:  00000000017772c5 <github.com/filecoin-project/lotus/chain/sub.(*MessageValidator).Validate+869>  00000007009cf765 
00007f772affc808:  0000000000000000  0000000000000000 
00007f772affc818:  0000000000000000  0000000000000000 
:
:
created by github.com/multiformats/go-multistream.(*lazyClientConn).Write.func1
	/home/harrison/go/pkg/mod/github.com/multiformats/go-multistream@v0.1.2/lazyClient.go:131 +0x8f

rax    0x0
rbx    0x2f60240
rcx    0x2f60460
rdx    0xa76e6a609d104f1
rdi    0xf7fef8ab8afa89af
rsi    0x7f772affc8d0
rbp    0x98a8eaaa3729119
rsp    0x7f772affc8b8
r8     0x59f6a6a8c8113292
r9     0x59f0241e544d4761
r10    0x32b64ddab66f586a
r11    0x2fbf7bcd694b9085
r12    0x11a49d3516443bfe
r13    0xb44863c0819ca440
r14    0x12f33167b534029e
r15    0x0
rip    0x17efe6e
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0

[lotus-crash-log.txt](https://github.com/filecoin-project/lotus/files/5213536/lotus-crash-log.txt)

lotus version: 
lotus version 0.7.0+git.aa83a4c1

Please see the attachment for more detais.

**Comment by yang-woody** [comment]
me too , Will anyone solve it?

**Comment by D4708** [comment]
I have the same issue

**Comment by XIAOYAOSHUJU** [comment]
I have the same issue

**Comment by gongruihua** [comment]
I have the same issue

**Comment by littlekai999** [comment]
I have the same issue

**Comment by arajasek** [comment]
Hey, anyone having this issue: What platform are you running on? Can you share your CPU/GPU details?

**Comment by D4708** [comment]
Desktop Linux)

**Comment by D4708** [comment]
Just testing

**Comment by gongruihua** [comment]
> Hey, anyone having this issue: What platform are you running on? Can you share your CPU/GPU details?

 Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz / GeForce RTX 2070 SUPER      lotus version: lotus version 0.7.0+git.d4a7732d

**Comment by gongruihua** [comment]
> > Hey, anyone having this issue: What platform are you running on? Can you share your CPU/GPU details?
> 
> Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz / GeForce RTX 2070 SUPER lotus version: lotus version 0.7.0+git.d4a7732d

Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-39-generic x86_64)

**Comment by symanovich-a** [comment]
We have the same error if build docker container on docker hub, but if we build on server with the same cpu family, it works normal
```
SIGILL: illegal instruction
PC=0x1752fab m=13 sigcode=2

goroutine 0 [idle]:
runtime: unknown pc 0x1752fab
```

**Comment by yangwb** [comment]
I have the same error
lscpu：
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              40
On-line CPU(s) list: 0-39
Thread(s) per core:  2
Core(s) per socket:  10
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               62
Model name:          Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
Stepping:            4
CPU MHz:             3357.170
CPU max MHz:         3600.0000
CPU min MHz:         1200.0000
BogoMIPS:            5586.40
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            25600K
NUMA node0 CPU(s):   0-9,20-29
NUMA node1 CPU(s):   10-19,30-39
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d

**Comment by yangwb** [comment]
What is the problem？

**Comment by 1618employment** [comment]
Same or similar, crashed with 7k lines of output within 30 secs of startup, tried different drivers (mesa vs nvidia), linux distros, precompiled vs compiled, problem is definitely tied to the hardware (maybe the 2070 super?) because I don't get the same issue on my laptop with an Intel CPU/GPU combo. Why does the basic client need hardware accelleration to sync the blockchain? Best troubleshoot source I could find for setting up hardware acceleration in linux is this kali hashcat post, [here](https://www.kali.org/docs/general-use/install-nvidia-drivers-on-kali-linux/) my rig benchmarked hashcat just fine!


> 2020-09-22T11:36:52.885-0700	INFO	hello	hello/hello.go:121	Got new tipset through Hello: [bafy2bzacea6xfbiv66z5zrr7ccuyr65iqeeihy4lax62sy73z4hpbkg5hybro bafy2bzaceaz2t7akbjtas265u3yizwcmu5ptl7xl635z3xzyimsbldf7n6mb4 bafy2bzaceb6woprw2ii7sbiq723phoeaa7ieuy676uenxki45m6hurltybv4q bafy2bzaceavwixz4cmfdxgqafz3xkrfzinwqnk6l27ir7ttzmw3tky3t6obmw] from 12D3KooWGMkTrSqAkqAwkT1rpKzRJ9BFZDKY6svL5Xmd36XNKVD3
> SIGILL: illegal instruction
> PC=0x176612e m=18 sigcode=2
> 
> goroutine 0 [idle]:
> runtime: unknown pc 0x176612e
> stack: frame={sp:0x7fce1fffe8c8, fp:0x0} stack=[0x7fce1f7feec8,0x7fce1fffeac8)
> 00007fce1fffe7c8:  0000000000000016  0000000000000af0 
> 00007fce1fffe7d8:  000000c012bf8000  000000c012bfa000 
> 00007fce1fffe7e8:  000000c012c00510  000000c012c01000 
> 00007fce1fffe7f8:  000000c012c00000  000000c012c00000 
> 00007fce1fffe808:  000000c012c01000  ffffffffffff9000 
> 00007fce1fffe818:  0000000000bec394 <github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic+916>  0000000f005119ee 
> 00007fce1fffe828:  0000000000000000  0000000000000000 
> 00007fce1fffe838:  0000000000000000  0000000000000000 
> 00007fce1fffe848:  000000000109dc53 <github.com/filecoin-project/lotus/chain/messagepool.sigCacheKey+99>  000000000080cae3 <crypto/x509.parsePublicKey+2083> 
> 00007fce1fffe858:  0000000000000000  0000000000000000 
> 00007fce1fffe868:  0000000000000000  0000000000000000 
> 00007fce1fffe878:  0000000000bec485 <github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic+165>  0000000300511b4c 
> 00007fce1fffe888:  0000000000740241 <github.com/filecoin-project/go-state-types/abi.cidBuilder.Sum+113>  00000001002126fb 
> 00007fce1fffe898:  0000000000bf0878 <github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1+120>  0000000400514d16 
> 00007fce1fffe8a8:  0000000000bec67b <github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg+251>  0000000600511cc6 
> 00007fce1fffe8b8:  0000000000bebc1d <github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic+141>  00000001005117e0 
> 00007fce1fffe8c8: <00000000017660ab  89f3fffcfffcfffd 
> 00007fce1fffe8d8:  53880f709939d912  000000010080c946 
> 00007fce1fffe8e8:  00007fce1fffe950  0000000002fb6340 
> 00007fce1fffe8f8:  00007fce1fffe980  0000000002fb65e0 
> 00007fce1fffe908:  000000c00054e900  0000000000000092 
> 00007fce1fffe918:  000000000175abaa  b8f890eb9c32a9e3 
> 00007fce1fffe928:  7e408b6449852ea9  46662a0a7fe42099 
> 00007fce1fffe938:  77786986c9b2ac7b  943ce6687b9010ba 
> 00007fce1fffe948:  15a7c462ea92d0e2  b8f890eb9c32a9e3 
> 00007fce1fffe958:  7e408b6449852ea9  46662a0a7fe42099 
> 00007fce1fffe968:  77786986c9b2ac7b  943ce6687b9010ba 
> 00007fce1fffe978:  15a7c462ea92d0e2  1ad8ec6daf38eef6 
> 00007fce1fffe988:  f8f099cd27e4e5fe  c835e65fff08a18a 
> 00007fce1fffe998:  70f1d35610d54e36  5e106f5f0cd2ad62 
> 00007fce1fffe9a8:  123234c1b8d22fca  0000000004aa4850 
> 00007fce1fffe9b8:  0000000000000049  0000000004aa4850 
> runtime: unknown pc 0x176612e
> stack: frame={sp:0x7fce1fffe8c8, fp:0x0} stack=[0x7fce1f7feec8,0x7fce1fffeac8)
> 00007fce1fffe7c8:  0000000000000016  0000000000000af0 
> 00007fce1fffe7d8:  000000c012bf8000  000000c012bfa000 
> 00007fce1fffe7e8:  000000c012c00510  000000c012c01000 
> 00007fce1fffe7f8:  000000c012c00000  000000c012c00000 
> 00007fce1fffe808:  000000c012c01000  ffffffffffff9000 
> 00007fce1fffe818:  0000000000bec394 <github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic+916>  0000000f005119ee 
> 00007fce1fffe828:  0000000000000000  0000000000000000 
> 00007fce1fffe838:  0000000000000000  0000000000000000 
> 00007fce1fffe848:  000000000109dc53 <github.com/filecoin-project/lotus/chain/messagepool.sigCacheKey+99>  000000000080cae3 <crypto/x509.parsePublicKey+2083> 
> 00007fce1fffe858:  0000000000000000  0000000000000000 
> 00007fce1fffe868:  0000000000000000  0000000000000000 
> 00007fce1fffe878:  0000000000bec485 <github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic+165>  0000000300511b4c 
> 00007fce1fffe888:  0000000000740241 <github.com/filecoin-project/go-state-types/abi.cidBuilder.Sum+113>  00000001002126fb 
> 00007fce1fffe898:  0000000000bf0878 <github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1+120>  0000000400514d16 
> 00007fce1fffe8a8:  0000000000bec67b <github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg+251>  0000000600511cc6 
> 00007fce1fffe8b8:  0000000000bebc1d <github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic+141>  00000001005117e0 
> 00007fce1fffe8c8: <00000000017660ab  89f3fffcfffcfffd 
> 00007fce1fffe8d8:  53880f709939d912  000000010080c946 
> 00007fce1fffe8e8:  00007fce1fffe950  0000000002fb6340 
> 00007fce1fffe8f8:  00007fce1fffe980  0000000002fb65e0 
> 00007fce1fffe908:  000000c00054e900  0000000000000092 
> 00007fce1fffe918:  000000000175abaa  b8f890eb9c32a9e3 
> 00007fce1fffe928:  7e408b6449852ea9  46662a0a7fe42099 
> 00007fce1fffe938:  77786986c9b2ac7b  943ce6687b9010ba 
> 00007fce1fffe948:  15a7c462ea92d0e2  b8f890eb9c32a9e3 
> 00007fce1fffe958:  7e408b6449852ea9  46662a0a7fe42099 
> 00007fce1fffe968:  77786986c9b2ac7b  943ce6687b9010ba 
> 00007fce1fffe978:  15a7c462ea92d0e2  1ad8ec6daf38eef6 
> 00007fce1fffe988:  f8f099cd27e4e5fe  c835e65fff08a18a 
> 00007fce1fffe998:  70f1d35610d54e36  5e106f5f0cd2ad62 
> 00007fce1fffe9a8:  123234c1b8d22fca  0000000004aa4850 
> 00007fce1fffe9b8:  0000000000000049  0000000004aa4850 
> 

7000+ more lines here

[haswell-e-2070super-illegal-instruction-crash-dump.txt](https://github.com/filecoin-project/lotus/files/5263483/haswell-e-2070super-illegal-instruction-crash-dump.txt)

> user@storage:~$ dpkg -l |  grep -i icd
> ii  libnvidia-gl-450:amd64                     450.51.06-0ubuntu1                    amd64        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
> ii  ocl-icd-dev:amd64                          2.2.11-1ubuntu1                       amd64        Development files to build a ICD Loader
> ii  ocl-icd-libopencl1:amd64                   2.2.11-1ubuntu1                       amd64        Generic OpenCL ICD Loader
> ii  ocl-icd-opencl-dev:amd64                   2.2.11-1ubuntu1                       amd64        OpenCL development files

> user@storage:~$ lscpu
> Architecture:                    x86_64
> CPU op-mode(s):                  32-bit, 64-bit
> Byte Order:                      Little Endian
> Address sizes:                   46 bits physical, 48 bits virtual
> CPU(s):                          16
> On-line CPU(s) list:             0-15
> Thread(s) per core:              2
> Core(s) per socket:              8
> Socket(s):                       1
> NUMA node(s):                    1
> Vendor ID:                       GenuineIntel
> CPU family:                      6
> Model:                           63
> Model name:                      Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
> Stepping:                        2
> CPU MHz:                         1200.072
> CPU max MHz:                     3500.0000
> CPU min MHz:                     1200.0000
> BogoMIPS:                        5999.51
> Virtualization:                  VT-x
> L1d cache:                       256 KiB
> L1i cache:                       256 KiB
> L2 cache:                        2 MiB
> L3 cache:                        20 MiB
> NUMA node0 CPU(s):               0-15
> Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
> Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
> Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
> Vulnerability Meltdown:          Mitigation; PTI
> Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
> Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
> Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
> Vulnerability Srbds:             Not affected
> Vulnerability Tsx async abort:   Not affected
> Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqd
>                                  q dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flex
>                                  priority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear flush_l1d





[haswell-e-2070super-illegal-instruction-clinfo-nvidia-smi.txt](https://github.com/filecoin-project/lotus/files/5263494/haswell-e-2070super-illegal-instruction-clinfo-nvidia-smi.txt)

**Comment by qiukeren** [comment]
E5-2620 v3 also



```

SIGILL: illegal instruction
PC=0x179cb6e m=17 sigcode=2

goroutine 0 [idle]:
runtime: unknown pc 0x179cb6e
stack: frame={sp:0x7f4803ffe8c8, fp:0x0} stack=[0x7f48037feec8,0x7f4803ffeac8)
00007f4803ffe7c8:  0000000000000016  0000000000000af0 
00007f4803ffe7d8:  000000c011694000  000000c011696000 
00007f4803ffe7e8:  000000c012b44510  000000c012b45000 
00007f4803ffe7f8:  000000c012b44000  000000c012b44000 
00007f4803ffe808:  000000c012b45000  fffffffffeb51000 
00007f4803ffe818:  0000000000beb614 <github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic+916>  0000000f00514e46 
00007f4803ffe828:  000000000073fdf1 <github.com/filecoin-project/go-state-types/abi.cidBuilder.Sum+113>  0000000100215fcb 
00007f4803ffe838:  0000000001743186 <github.com/filecoin-project/lotus/chain/sub.(*MessageValidator).Validate+870>  0000000c00cb2bdf 
00007f4803ffe848:  0000000000000000  0000000000000000 
00007f4803ffe858:  0000000000000000  0000000000000000 
00007f4803ffe868:  0000000000beb705 <github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic+165>  0000000300514fa4 
00007f4803ffe878:  0000000000000000  0000000000000000 
00007f4803ffe888:  00000000010d1247 <github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).checkMessage+615>  000000010083fbf0 
00007f4803ffe898:  0000000000befaf8 <github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1+120>  000000040051816e 
00007f4803ffe8a8:  0000000000000000  0000000000000000 
00007f4803ffe8b8:  00000000010d1438 <github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).Add+88>  000000010083fda6 
00007f4803ffe8c8: <000000000179caeb  89f3fffcfffcfffd 
00007f4803ffe8d8:  875a62b81b5481f4  00000000008400c3 <github.com/gogo/protobuf/proto.(*marshalInfo).appendMessageSet+771> 
00007f4803ffe8e8:  00007f4803ffe960  00007f4803ffe960 
00007f4803ffe8f8:  0000000002fc8200  000000c0126a6240 
00007f4803ffe908:  00000000000000a4  0000000002fc84a0 
00007f4803ffe918:  0000000001792213  00007f4803ffeab0 
00007f4803ffe928:  00007f4803ffe960  2c7c9b3ae4adcabe 
00007f4803ffe938:  e744f017bdea4abd  db5cc399b6ba78aa 
00007f4803ffe948:  8ac442dda8035bae  ee19f2ce0cc8ace1 
00007f4803ffe958:  0e942fd4c7ebc2dc  2c7c9b3ae4adcabe 
00007f4803ffe968:  e744f017bdea4abd  db5cc399b6ba78aa 
00007f4803ffe978:  8ac442dda8035bae  ee19f2ce0cc8ace1 
00007f4803ffe988:  0e942fd4c7ebc2dc  cd213148928316bf 
00007f4803ffe998:  1fb3f6b378225263  17977394aa573e7c 
00007f4803ffe9a8:  0bdf1766a5380151  6a41d840da312350 
00007f4803ffe9b8:  04273a9b8ed50335  0000000004aea630 
runtime: unknown pc 0x179cb6e
stack: frame={sp:0x7f4803ffe8c8, fp:0x0} stack=[0x7f48037feec8,0x7f4803ffeac8)
00007f4803ffe7c8:  0000000000000016  0000000000000af0 
00007f4803ffe7d8:  000000c011694000  000000c011696000 
00007f4803ffe7e8:  000000c012b44510  000000c012b45000 
00007f4803ffe7f8:  000000c012b44000  000000c012b44000 
00007f4803ffe808:  000000c012b45000  fffffffffeb51000 
00007f4803ffe818:  0000000000beb614 <github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic+916>  0000000f00514e46 
00007f4803ffe828:  000000000073fdf1 <github.com/filecoin-project/go-state-types/abi.cidBuilder.Sum+113>  0000000100215fcb 
00007f4803ffe838:  0000000001743186 <github.com/filecoin-project/lotus/chain/sub.(*MessageValidator).Validate+870>  0000000c00cb2bdf 
00007f4803ffe848:  0000000000000000  0000000000000000 
00007f4803ffe858:  0000000000000000  0000000000000000 
00007f4803ffe868:  0000000000beb705 <github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic+165>  0000000300514fa4 
00007f4803ffe878:  0000000000000000  0000000000000000 
00007f4803ffe888:  00000000010d1247 <github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).checkMessage+615>  000000010083fbf0 
00007f4803ffe898:  0000000000befaf8 <github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1+120>  000000040051816e 
00007f4803ffe8a8:  0000000000000000  0000000000000000 
00007f4803ffe8b8:  00000000010d1438 <github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).Add+88>  000000010083fda6 
00007f4803ffe8c8: <000000000179caeb  89f3fffcfffcfffd 
00007f4803ffe8d8:  875a62b81b5481f4  00000000008400c3 <github.com/gogo/protobuf/proto.(*marshalInfo).appendMessageSet+771> 
00007f4803ffe8e8:  00007f4803ffe960  00007f4803ffe960 
00007f4803ffe8f8:  0000000002fc8200  000000c0126a6240 
00007f4803ffe908:  00000000000000a4  0000000002fc84a0 
00007f4803ffe918:  0000000001792213  00007f4803ffeab0 
00007f4803ffe928:  00007f4803ffe960  2c7c9b3ae4adcabe 
00007f4803ffe938:  e744f017bdea4abd  db5cc399b6ba78aa 
00007f4803ffe948:  8ac442dda8035bae  ee19f2ce0cc8ace1 
00007f4803ffe958:  0e942fd4c7ebc2dc  2c7c9b3ae4adcabe 
00007f4803ffe968:  e744f017bdea4abd  db5cc399b6ba78aa 
00007f4803ffe978:  8ac442dda8035bae  ee19f2ce0cc8ace1 
00007f4803ffe988:  0e942fd4c7ebc2dc  cd213148928316bf 
00007f4803ffe998:  1fb3f6b378225263  17977394aa573e7c 
00007f4803ffe9a8:  0bdf1766a5380151  6a41d840da312350 
00007f4803ffe9b8:  04273a9b8ed50335  0000000004aea630 

```

**Comment by harrisonhjc** [comment]
check it out : 
https://docs.filecoin.io/get-started/lotus/installation/#build-and-install-lotus
export CGO_CFLAGS="-D__BLST_PORTABLE__"

**Comment by ifurther** [comment]
I used the `export CGO_CFLAGS="-D__BLST_PORTABLE__"` and the lotus version is 0.8.0 has this error.
