### ISSUE TITLE
UnsealPiece fail on remote worker

### ISSUE THREAD

**Issue by ldoublewood** [filecoin-project/lotus#3803]
**Describe the bug**
UnsealPiece fail on remote worker

**To Reproduce**
1. Run remote worker with miner
2. Make an store deal from client with --fast-retrieval = false
3. Make an retrieval deal after store deal completed

**Expected behavior**
Retrieval deal succeed

**Screenshots**

**Version (run `lotus version`):**
v0.7.0

**Additional context**
"stores.PathStorage"  below caused the following error mesage in retrieval deals list: "unsealing sector: acquire unsealed sector path (existing): allocate local sector for fetching: couldn't find a suitable path for a sector"
 because the remote worker (not miner) has only 'Sealing' store and hasn't 'Storage' store. 

func (sb *Sealer) UnsealPiece(ctx context.Context, sector abi.SectorID, offset storiface.UnpaddedByteIndex, size abi.UnpaddedPieceSize, randomness abi.SealRandomness, commd cid.Cid) error {
	maxPieceSize := abi.PaddedPieceSize(sb.ssize)

	// try finding existing
	unsealedPath, done, err := sb.sectors.AcquireSector(ctx, sector, stores.FTUnsealed, stores.FTNone, stores.PathStorage)
	var pf *partialFile

	switch {
	case xerrors.Is(err, storiface.ErrSectorNotFound):
...

**Comment by Reiers** [comment]
Hi @ldoublewood 

Thanks for the report. Unable to repro in the [latest release.](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)
Please upgrade Lotus.

`Tip: let your PC1 workers do the unseal.
`

If you are still experiencing problems, please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you!
