### ISSUE TITLE
wdpost failed

### ISSUE THREAD

**Issue by std** [filecoin-project/lotus#3804]
**Describe the bug**
wdpost failure
miner t08285
stander
`
2020-09-13T00:26:35.513+0300    ERROR    storageminer    storage/wdpost_run.go:59    submitPost failed: pushing message to mpool:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).submitPost
        /home/stander/lotus7/lotus/storage/wdpost_run.go:523`

**Version (run `lotus version`):**
`stander@miner1:~/lotus7$ lotus-miner version
Daemon:  0.7.0+git.aa83a4c1+api0.14.0
Local: lotus-miner version 0.7.0+git.aa83a4c1`
[wdpost-fail-13-sep.log](https://github.com/filecoin-project/lotus/files/5213845/wdpost-fail-13-sep.log)

**Comment by jennijuju** [comment]
duplicated #3808
