### ISSUE TITLE
 FIL is too small to mine

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#3805]
**Describe the bug**
I received 100 FIL after receiving a seal at first, but I reinstalled the system and recently certified by faucet and got 5 FIL, which is too small to mine. Is there a way to get a little more FIL?

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by jennijuju** [comment]
Not lotus related.
