### ISSUE TITLE
Feature Request: Better Sealing Phase Timeline/Logging

### ISSUE THREAD

**Issue by yallahh** [filecoin-project/lotus#3806]
It'd be really helpful for optimising sealing schedules and seeing how different settings affect durations of the various sealing phases. Atm I have to calculate the durations in my head using the timestamps :( 

Could look something like this:

**Sector 1**
AP -- PC1 ------  PC2 -- CW - WS - C1 -- C2 --  CW -- FS - PS
3:55  4:00           9:00   10:00 11:00 12:00 14:00 17:00 17:15 17:20 

AP: 5 mins
PC1: 5 hours
PC2: 1 hour
CW: 1 hour
WS: 1 hour
C1: 2 hours
C2: 3 hours
CW: 15 mins
FS: 5 mins

Also being able to see how averages of durations for both the whole sector sealing and each phase, and how those change over time would be great.

**Comment by Reiers** [comment]
**Hi @yallahh** 

Thanks for the ticket about a feature request.

With monitor tools like:
`lotus-miner sealings jobs 
`
`lotus-miner sealing workers
`
`export RUST_LOG=debug
`

I think that the Storage Provider have enough information to go on, and can calculate how much throughput based on that alone.

**If you want a monitoring tool, I recommend farcaster - it will show you timestamps, durations and avg. times:**
https://github.com/s0nik42/lotus-farcaster

Also update to the latest tag to get more goodies: 
*Link to latest tags [here.](https://github.com/filecoin-project/lotus/tags)*

Closing ticket.
