### ISSUE TITLE
github.com/libp2p/go-libp2p@v0.11.0/p2p/host/basic/basic_host.go:416 +0x63c

### ISSUE THREAD

**Issue by 815943555** [filecoin-project/lotus#3810]
/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc01b247fb8 sp=0xc01b247fb0 pc=0x5a2891
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
	/home/jack/go_workspace/pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/host/basic/basic_host.go:416 +0x63c

goroutine 1 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f762000f320, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc018f95198, 0x72, 0x0, 0x0, 0x2ad21f0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc018f95180, 0x0, 0x0, 0x0, 0x0, 0x0
[miner.log](https://github.com/filecoin-project/lotus/files/5214147/miner.log)

**Comment by Reiers** [comment]
If you are still experiencing problems - please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you !
