### ISSUE TITLE
Unexpected circumstances caused failed storage and retrieval orders

### ISSUE THREAD

**Issue by a8159236** [filecoin-project/lotus#3811]
We have some problems and need help. Our miner number is t010035. We have a high success rate in the first two weeks.
We have successfully stored 142 orders, but only 20 retrieval orders have been received, and in the third week of the upgrade process caused some failed storage and retrieval orders, making our retrieval success very low.
Hope to send us more search orders, or delete some failed orders in the third week, after all, these are abnormal.

**Comment by jennijuju** [comment]
Not enough information to determine there is a bug in lotus. Closing as it seems like space race specific.
