### ISSUE TITLE
ClientQueryAsk failed - dial backoff

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/lotus#3816]
This is a holding bin for reports of new ClientQueryAsk dial backoff failures (began in past ~24h). 

If you have started getting this error only recently (after already following the "Improving connectivity" steps and previously successful deals), add a comment here and include:
- link to your miner's Space Race detail page (with miner id)
- paste of your `config.toml` settings for your multiaddrs

**Comment by hyunmoon** [comment]
[https://spacerace.filecoin.io/deals/t02500](url)

```
[Libp2p]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/32344"]
  AnnounceAddresses = ["/ip4/221.163.91.162/tcp/32344"]
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
```

```
lotus-miner net listen
/ip4/221.163.91.162/tcp/32344/p2p/12D3KooWAGXQoCRKaxCVUS9c1xFbGYeWiNbbVeohdH1bNcHXnBU5
```

**Comment by mishmosh** [comment]
Possible changes to local/regional networking settings?

**Comment by Leozhang404** [comment]
The message is from [slack](https://filecoinproject.slack.com/archives/C0179RNEMU4/p1600041375339500?thread_ts=1600040184.336300&cid=C0179RNEMU4)
During Past 24 hours, I have many error -

1. `"Message":"sending proposal to storage provider failed: exhausted 4 attempts but failed to open stream, err: failed to dial`

2. `
ClientQueryAsk failed : failed to open stream to miner: exhausted 4 attempts but failed to open stream, err: dial backoff`

My config: `run ~/.lotusminer$ cat config.toml `

> [API]
  ListenAddress = “/ip4/0.0.0.0/tcp/52345/http”
  RemoteListenAddress = “172.17.202.32:52345"
  Timeout = “30s”
[Libp2p]
  ListenAddresses = [“/ip4/0.0.0.0/tcp/10241"]
  AnnounceAddresses = [“/ip4/170.33.12.94/tcp/10241”]
  NoAnnounceAddresses = []
  ConnMgrLow = 150
  ConnMgrHigh = 180
  ConnMgrGrace = “20s”
[Pubsub]
  Bootstrapper = false
  RemoteTracer = “/ip4/147.75.67.199/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX”
[Dealmaking]
  ConsiderOnlineStorageDeals = true
  ConsiderOfflineStorageDeals = true
  ConsiderOnlineRetrievalDeals = true
  ConsiderOfflineRetrievalDeals = true
  PieceCidBlocklist = []
  ExpectedSealDuration = “12h0m0s”
  Filter = “jq -e ‘.Proposal.Client == \“t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i\” or .Proposal.Client == \“t1stghxhdp2w53dym2nz2jtbpk6ccd4l2lxgmezlq\” or .Proposal.Client == \“t1mcr5xkgv4jdl3rnz77outn6xbmygb55vdejgbfi\” or .Proposal.Client == \“t1qiqdbbmrdalbntnuapriirduvxu5ltsc5mhy7si\” or .Proposal.Client == \“t3rmtwjnpwtiklvurmi5i47aquk3tbdznat4qrctmjgbvnhtm6tbjz7jxghwqi43qzibwjjhp6yvq7woy5r4pq\” or .Proposal.Client == \“t3w46pmnxhefqg65lhnm5puyhizfomrtbo5wiuzmo3bp3ptlrjd22t444w6i47asmusczzahlylwiag7h6fd3a\” or .Proposal.Client == \“t3rbdiirw4mw2esqtzlnxgyguqc5abd57lqcnujogdc6u4st65qtnpmrjaysg3vuot73lv5hr6arlm45m3y5rq\” ’”
[Sealing]
  MaxWaitDealsSectors = 2
  MaxSealingSectors = 0
  MaxSealingSectorsForDeals = 0
  WaitDealsDelay = “3h0m0s”
[Storage]
  ParallelFetchLimit = 10
  AllowAddPiece = true
  AllowPreCommit1 = false
  AllowPreCommit2 = true
  AllowCommit = true
  AllowUnseal = true
[Fees]
  MaxPreCommitGasFee = “0.05 FIL”
  MaxCommitGasFee = “0.05 FIL”
  MaxWindowPoStGasFee = “50 FIL” 


miner dealInfo link: [t01231, t016398](https://spacerace.filecoin.io/deals/t016398%20t01231), please check again @mishmosh

**Comment by mishmosh** [comment]
From `olive888` on Slack: We met the same problem with you yesterday. We forwarded the order through Nginx. Since we have configured many hosts of reverse proxy in Nginx, I solved it by reducing the host of directional proxy and then restarting the Nginx service

**Comment by litianc** [comment]
We meet the same problem earlier since Fri, 11 Sep 2020 16:16:39 GMT.
https://spacerace.filecoin.io/deals/t02619
error message:
1. ClientQueryAsk failed : failed to open stream to miner: exhausted 4 attempts but failed to open stream, err: dial backoff
2. sending proposal to storage provider failed: exhausted 4 attempts but failed to open stream
my miner config.toml
```
[API]
  ListenAddress = "/ip4/192.168.0.35/tcp/2345/http"
  RemoteListenAddress = "192.168.0.35:2345"
  Timeout = "30s"

[Libp2p]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/10240"]
  NoAnnounceAddresses = []
  ConnMgrLow = 150
  ConnMgrHigh = 180
  ConnMgrGrace = "20s"

[Pubsub]
  Bootstrapper = false
  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"

[Dealmaking]
  ConsiderOnlineStorageDeals = true
  ConsiderOfflineStorageDeals = true
  ConsiderOnlineRetrievalDeals = true
  ConsiderOfflineRetrievalDeals = true
  PieceCidBlocklist = []
  ExpectedSealDuration = "12h0m0s"
  Filter = "jq -e '.Proposal.Client == \"t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i\" or .Proposal.Client == \"t1stghxhdp2w53dym2nz2jtbpk6ccd4l2lxgmezlq\" or .Proposal.Client == \"t1mcr5xkgv4jdl3rnz77outn6xbmygb55vdejgbfi\" or .Proposal.Client == \"t1qiqdbbmrdalbntnuapriirduvxu5ltsc5mhy7si\" or .Proposal.Client == \"t3vsl7jl542qcpfrfp5wgfh6mjzdsstozzf3uyueldbc4toa2zhbnjysyhhxtihw2kygp5yxf4lohdrpx22sla\" or .Proposal.Client == \"t3uq4duvavwpjnhmvpm3qxmmikwovkjgenohqjm37g7mqmm3wbwpin47tefnt2j7dcddm6diohw5gxkbhekaxq\" '"

[Sealing]
  MaxWaitDealsSectors = 2
  MaxSealingSectors = 0
  MaxSealingSectorsForDeals = 0
  WaitDealsDelay = "1h0m0s"

[Storage]
  ParallelFetchLimit = 8
  AllowAddPiece = true
  AllowPreCommit1 = false
  AllowPreCommit2 = false
  AllowCommit = false
  AllowUnseal = true

[Fees]
  MaxPreCommitGasFee = "0.05 FIL"
  MaxCommitGasFee = "0.05 FIL"
  MaxWindowPoStGasFee = "50 FIL"
```

**Comment by zhouyi820** [comment]
Have the same problem, it looks periodic to me.
https://spacerace.filecoin.io/deals/t03519

[API]
  ListenAddress = "/ip4/127.0.0.1/tcp/3345/http"
  RemoteListenAddress = "127.0.0.1:3345"
  Timeout = "30s"

[Libp2p]
  ListenPort = 7000
  #ListenPort = 17008
  AnnounceAddresses = ["/ip4/66.115.149.245/tcp/7000"]
  NoAnnounceAddresses = []
  BootstrapPeers = []
  ProtectedPeers = []
  ConnMgrLow = 150
  ConnMgrHigh = 2048
  ConnMgrGrace = "20s"

**Comment by waynewyang** [comment]
@mishmosh We meet the same problem earlier since Tue, 01 Sep 2020 
- t02303
https://spacerace.filecoin.io/deals/t02303
```
[Libp2p]
   ListenAddresses = ["/ip4/0.0.0.0/tcp/48921", "/ip6/::/tcp/0"]
   #AnnounceAddresses = ["/ip4/183.213.25.93/tcp/31432","/ip4/185.232.59.182/tcp/31432","/ip4/154.91.39.67/tcp/31432"]
   AnnounceAddresses = ["/ip4/185.232.59.182/tcp/48921","/ip4/154.91.39.67/tcp/48921","/ip4/103.72.166.221/tcp/48921","/ip4/8.209.76.63/tcp/48921"]
   #AnnounceAddresses = ["/ip4/154.91.39.67/tcp/48921"]
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/ip4/147.75.67.199/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
```

2. t02503
We meet the same problem earlier since Tue, 01 Sep 2020 
https://spacerace.filecoin.io/deals/t02503
```
[Libp2p]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/31432", "/ip6/::/tcp/0"]
  AnnounceAddresses = ["/ip4/36.159.57.6/tcp/31432","/ip4/103.210.21.98/tcp/31432","/ip4/8.209.71.125/tcp/31432"]
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/ip4/147.75.67.199/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#

**Comment by antina** [comment]
t019362

**Comment by bingcongam** [comment]
t03365  https://filfox.info/zh/address/t03365
We meet the same problem.  

# Default config:
GenesisTimestamp = 0
MinerMode = "pool"

[API]
  ListenAddress = "/ip4/172.31.84.2/tcp/2345/http"
  RemoteListenAddress = "172.31.84.2:2345"
  Timeout = "30s"

[Libp2p]
  ListenPort = 7000
  AnnounceAddresses = ["/ip4/58.215.43.84/tcp/7000","/ip4/116.211.58.172/tcp/7004"]
  NoAnnounceAddresses = []

**Comment by bingcongam** [comment]
Have the same problem, it looks periodic to me.
https://filfox.info/zh/address/t03365

[API]
  ListenAddress = "/ip4/172.31.84.2/tcp/2345/http"
  RemoteListenAddress = "172.31.84.2:2345"
  Timeout = "30s"

[Libp2p]
  ListenPort = 7000
  AnnounceAddresses = ["/ip4/58.215.43.84/tcp/7000","/ip4/116.211.58.172/tcp/7004"]

**Comment by waynewyang** [comment]
![image](https://user-images.githubusercontent.com/25957795/93105190-57d6f080-f6e1-11ea-8451-db6eb2a93ea2.png)
![image](https://user-images.githubusercontent.com/25957795/93105348-8bb21600-f6e1-11ea-88a6-fa7a07024e1a.png)
At the beginning of the space-race, my t02303/t02503 have always been successful

**Comment by hyunmoon** [comment]
I really doubt all ClientQueryAsk failures should be blamed on the miners or their network stability.
I feel doing so is especially unfair for those who are located further away from the bots but didn't rely on a VPN server that's setup closer to the bots.

**Comment by mishmosh** [comment]
Via @daviddias:
> I don’t find anything obvious right away, however, there is one guess. The way that golang binds to TCP ports is sometimes wonky and lets two processes bind to the same port (happens with me using hugo all the time). If they happen to have a previous zombie lotus process, they might be sharing the port and ultimately dropping the packets. One quick check is to make sure that all lotus processes are killed and then restarted. Yes, this is a “have you tried to turn off and on again” solution, not great, but might improve things

> that said, I find it off that so many miners are now getting this problem

> I know that Hannah and Aarsh have been pushing a lot of fixes there and that lotus definitely upgraded to the latest go-libp2p, so there might be some regression

@hannahhoward @aarshkshah1992 can you take a look?

**Comment by askender** [comment]
https://spacerace.filecoin.io/deals/t07998.   @mishmosh   getting into this problem too. This is never happen before. Network is the same and well.

**Comment by mishmosh** [comment]
The same error code appeared early on (in calibration period) for miners that had never correctly followed the [Improving Connectivity](https://docs.filecoin.io/mine/connectivity/) steps and set their multiaddrs. However, we saw a recent spike of these among miners who had previously configured correctly. We’ll still investigating but wanted to acknowledge those miners. Therefore, we are removing these failures that occurred on or after 7 Sept, for miners with >5 successful deals previously.

**Comment by TippyFlitsUK** [comment]
Hey @mishmosh 

Is this holding bin still required?

Many thanks!

**Comment by mishmosh** [comment]
@TippyFlitsUK No longer needed, I'll go ahead and close. Thanks for keeping this repo organized!
