### ISSUE TITLE
Space Race Dashboard is not updating pending storage deals

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#3817]
**Describe the bug**
After the bot sends a storage deal to a miner the status changes from `n/a - Proposed` to `StorageDealSealing - (ClientGetDealInfo: ...)` but **now** does not change to status: `StorageDealActive - success`

**To Reproduce**
1. Go to [My dashboard](https://spacerace.filecoin.io/deals/t01278)
2. View "DealID":123009 on Sat, 12 Sep 2020 16:33:53 GMT

**Expected behavior**
Status should have changed to `StorageDealActive - success` after 2020-09-13T07:47:34.330Z

**Screenshots**
`grep 123009 /mypool/logs/miner.log`

> 2020-09-12T16:40:00.534Z	INFO	sectors	storage-sealing/sealing.go:144	Adding piece for deal 123009 (publish msg: bafy2bzacecxe4gzgf55qibf77jk2litbw5iykplp7myht7glmvypukyxvpsco)
> 2020-09-12T19:41:48.775Z	WARN	storageadapter	storageadapter/provider.go:106	New Deal: deal 123009
> 2020-09-13T07:47:34.330Z	INFO	storageadapter	storageadapter/provider.go:284	Storage deal 123009 activated at epoch 55888

**Version (run `lotus version`):**
` lotus-miner version`

> Daemon:  0.7.0+git.232cc320+api0.14.0
> Local: lotus-miner version 0.7.0+git.232cc320

**Additional context**
This was working well prior to Sat, 12 Sep 2020 11:00 GMT
My miner is accepting all bot deals and sealing them within 24 hours and with no failures on miner.
Others are experiencing the same issue.

**Comment by stuberman** [comment]
> lotus-miner sectors list
> 0: Proving     sSet: YES active: NO  tktH: -805  seedH: 1354  deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 1: Proving     sSet: YES active: NO  tktH: -458  seedH: 1457  deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 2: Proving     sSet: YES active: YES tktH: 902   seedH: 2570  deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 3: Proving     sSet: YES active: YES tktH: 1973  seedH: 3634  deals: [5023 0 0 0 0 0 0 0 0 0 0 5333 5565 0 0 0 0 0 0 0 0 0 0 6138 0 0 0 0 0 0]                                                                                                                                                                                                  toUpgrade:false
> 4: Proving     sSet: YES active: YES tktH: 3654  seedH: 5330  deals: [7534 8159 0 0 0 0 0 0 0 0 0 0 8705 0 0 0 9036 0 0 0]                                                                                                                                                                                                                      toUpgrade:false
> 5: Removed     sSet: NO  active: NO  tktH: 0     seedH: 0     deals: [9226 9571 9859 0 0 0 0 0 0 0 0 0 10189 0 0 0 10506 10848 11268 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                                                                             toUpgrade:false
> 6: Proving     sSet: YES active: YES tktH: 4736  seedH: 6685  deals: [11504 11975 12317 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                                                                                                                      toUpgrade:false
> 7: Proving     sSet: YES active: YES tktH: 5715  seedH: 7599  deals: [13361 0 0 0 0 0 0 0 0 0 0 14123 14544 14938 15288 15851 0 0 0 0 0 0 0 0 0 16353 16680 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                                                    toUpgrade:false
> 8: Proving     sSet: YES active: YES tktH: 6675  seedH: 8628  deals: [17039 0 0 0 0 0 0 0 0 0 0 17418 17845 0 0 0 0 0 0 0 0 0 0 18369 18767 18811 19176 0 0 0 0 0 0 0 0 0 19267 19668 19734 0 0 0 0 0 0 0 0 0 0 20053 20088 0 0 0 0 0 0 0 0 0 0 20420 0 0 0 0 0]                                                                                toUpgrade:false
> 9: Proving     sSet: YES active: YES tktH: 7635  seedH: 9501  deals: [20442 0 0 0 0 0 0 0 0 0 0 20750 20837 21135 21156 0 0 0 0 0 0 0 0 0 21470 21544 22505 22513 23017 23071 0 0 0 0 0 0 0 0 0 23442 23579 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                    toUpgrade:false
> 10: Removed    sSet: NO  active: NO  tktH: 9510  seedH: 0     deals: [24040 24123 24591 24609 0 0 0 0 0 0 0 0 0 25261 25318 25904 25980 0 0 0 0 0 0 0 0 0 26515 26564 27004 27037 27471 27638 0 0 0 0 0 0 0 0 28233 28234 0 0 0 0 0 0]                                                                                                          toUpgrade:false
> 11: Proving    sSet: YES active: YES tktH: 9689  seedH: 11716 deals: [29403 29404 29890 0 0 0 0 0 0 0 0 0 0 29946 30566 30606 31075 0 0 0 0 0 0 0 0 0 31108 31494 31566 31973 0 0 0 0 0 0 0 0 0 0 32001 32385 32399 32751 32808 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                  toUpgrade:false
> 12: Proving    sSet: YES active: YES tktH: 11205 seedH: 12870 deals: [33150 0 0 0 0 0 0 0 0 0 0 33194 33497 33526 33893 33912 34260 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                                                                                toUpgrade:false
> 13: Removed    sSet: NO  active: NO  tktH: 0     seedH: 0     deals: [37092 0 0 0 0 0 0 0 0 0 0 37600 37607 0 0 0 0 0 0 0 0 0 0 38083 38107 38461 38520 38924 0 0 0 0 0 0 0 0 0 39001 0 0 0 0 0]                                                                                                                                                toUpgrade:false
> 14: Proving    sSet: YES active: YES tktH: 12201 seedH: 13889 deals: [39349 39387 39764 39809 40135 40205 40565 40666 0 0 0 0 0 0 0 0 41245 41321 41824 41966 42475 42558 0 0 0 0 0 0 0 0 0 42986 43065 0 0 0 0 0 0]                                                                                                                            toUpgrade:false
> 15: Proving    sSet: YES active: YES tktH: 13219 seedH: 14887 deals: [43493 0 0 0 0 0 0 0 0 0 0 43561 43868 43952 44233 44376 44696 0 0 0 0 0 0 0 0 44806 45331 45700 0 0 0 0 0 0 0 0 0 0 45802 46088 46201 46410 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                              toUpgrade:false
> 16: Proving    sSet: YES active: YES tktH: 14220 seedH: 15891 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 17: Proving    sSet: YES active: YES tktH: 15912 seedH: 17570 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 18: Proving    sSet: YES active: YES tktH: 17001 seedH: 18664 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 19: Proving    sSet: YES active: YES tktH: 18229 seedH: 19924 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 20: Proving    sSet: YES active: YES tktH: 18952 seedH: 20778 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 21: Proving    sSet: YES active: YES tktH: 19819 seedH: 21656 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 22: Proving    sSet: YES active: YES tktH: 22033 seedH: 24094 deals: [52879 53158 0 0 0 0 0 0 0 0 0 53387 53620 53842 54067 0 0 0 0 0 0 0 0 0 54256 0 0 0 0 0 0]                                                                                                                                                                                toUpgrade:false
> 23: Proving    sSet: YES active: YES tktH: 21043 seedH: 22968 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 24: Proving    sSet: YES active: YES tktH: 21062 seedH: 23069 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 25: Proving    sSet: YES active: YES tktH: 23059 seedH: 24925 deals: [54471 54780 55001 0 0 0 0 0 0 0 0 0 55241 55510 55763 56016 0 0 0 0 0 0 0 0 0 56288 56551 57054 57442 0 0 0 0 0 0 0 0 0 0 57795 58160 58494 0 0 0 0 0 0 0 0 0 0 58758 59030 59416 59673 59977 0 0 0 0 0 0 0 0 60293 60589 60868 61191 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]  toUpgrade:false
> 26: Proving    sSet: YES active: YES tktH: 24019 seedH: 25915 deals: [61456 61753 62069 62452 62969 63293 63832 64033 0 0 0 0 0 0 0 0 64330 64606 65110 0 0 0 0 0 0 0 0 0 0 65355 65705 65892 66156 66349 0 0 0 0 0 0 0 0 66619 0 0 0 0 0 0 0]                                                                                                  toUpgrade:false
> 27: Proving    sSet: YES active: YES tktH: 24880 seedH: 26755 deals: [66802 67133 67589 0 0 0 0 0 0 0 0 0 67786 68098 0 0 0 0 0 0 0 0 0 0 68707 69073 0 0 0 0 0 0 0 0 0 0 69225 69501 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                          toUpgrade:false
> 28: Proving    sSet: YES active: YES tktH: 25720 seedH: 27579 deals: [70331 71043 0 0 0 0 0 0 0 0 0 0 71627 72442 0 0 0 0 0 0]                                                                                                                                                                                                                  toUpgrade:false
> 29: Proving    sSet: YES active: YES tktH: 27177 seedH: 29070 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 30: Proving    sSet: YES active: YES tktH: 27177 seedH: 29210 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 31: Proving    sSet: YES active: YES tktH: 28176 seedH: 30137 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 32: Proving    sSet: YES active: YES tktH: 28985 seedH: 30872 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 33: Proving    sSet: YES active: YES tktH: 29846 seedH: 31659 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 34: Proving    sSet: YES active: YES tktH: 30631 seedH: 32424 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 35: Proving    sSet: YES active: YES tktH: 31389 seedH: 33185 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 36: Proving    sSet: YES active: YES tktH: 32545 seedH: 34576 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 37: Proving    sSet: YES active: YES tktH: 32879 seedH: 34674 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 38: Proving    sSet: YES active: YES tktH: 34924 seedH: 37097 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 39: Empty      sSet: NO  active: NO  tktH: 0     seedH: 0     deals: []                                                                                                                                                                                                                                                                         toUpgrade:false
> 40: Proving    sSet: YES active: YES tktH: 36062 seedH: 37868 deals: [78771 79086 0 0 0 0 0 0 0 0 0 0 79407 79723 80089 0 0 0 0 0 0 0 0 0 80482 0 0 0 0 0 0 0]                                                                                                                                                                                  toUpgrade:false
> 41: Proving    sSet: YES active: YES tktH: 36822 seedH: 38621 deals: [80811 81150 81459 0 0 0 0 0 0 0 0 0 81761 82069 82365 82633 82954 0 0 0 0 0 0 0 0 0 83360 83754 84121 0 0 0 0 0 0 0 0 0 84478 0 0 0 0 0 0 0]                                                                                                                              toUpgrade:false
> 42: Proving    sSet: YES active: YES tktH: 37580 seedH: 39384 deals: [84832 0 0 0 0 0 0 0 0 0 0 85230 85483 85986 86613 0 0 0 0 0 0 0 0 0 87045 0 0 0 0 0 0 0]                                                                                                                                                                                  toUpgrade:false
> 43: Proving    sSet: YES active: YES tktH: 38370 seedH: 40182 deals: [87357 87658 88017 88304 0 0 0 0 0 0 0 0 0 0 88721 0 0 0 0 0 0 0]                                                                                                                                                                                                          toUpgrade:false
> 44: Proving    sSet: YES active: YES tktH: 39158 seedH: 40962 deals: [88988 89288 0 0 0 0 0 0 0 0 0 0 89592 89969 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                                                                                              toUpgrade:false
> 45: Proving    sSet: YES active: YES tktH: 39963 seedH: 41743 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 46: Proving    sSet: YES active: YES tktH: 41045 seedH: 42684 deals: [92307 0 0 0 0 0 0 0 0]                                                                                                                                                                                                                                                    toUpgrade:false
> 47: Proving    sSet: YES active: YES tktH: 41632 seedH: 43485 deals: [92594 0 0 0 0 0 0 0 0 0 0 92900 93171 0 0 0 0 0 0 0 0 0 0 93526 0 0 0 0 0 0]                                                                                                                                                                                              toUpgrade:false
> 48: Proving    sSet: YES active: YES tktH: 42384 seedH: 44176 deals: [93842 0 0 0 0 0 0 0 0 0 0 94096 94385 94730 95080 0 0 0 0 0 0 0 0 0 0 95347 95679 0 0 0 0 0 0]                                                                                                                                                                            toUpgrade:false
> 49: Proving    sSet: YES active: YES tktH: 43123 seedH: 44973 deals: [95932 96260 0 0 0 0 0 0 0]                                                                                                                                                                                                                                                toUpgrade:false
> 50: Proving    sSet: YES active: YES tktH: 43861 seedH: 45689 deals: [96725 96895 0 0 0 0 0 0 0 0 0 97246 98097 0 0 0 0 0 0 0 0 0 0 98341 98783 0 0 0 0 0 0 0 0 0 0 99366 0 0 0 0 0 0]                                                                                                                                                          toUpgrade:false
> 51: Proving    sSet: YES active: YES tktH: 44652 seedH: 46430 deals: [100053 0 0 0 0 0 0 0 0 0 0 100054 100379 100378 100573 100746 0 0 0 0 0 0 0 0 0 0 101096 101371 0 0 0 0 0 0 0 0 0 0 101679 0 0 0 0 0 0 0]                                                                                                                                 toUpgrade:false
> 52: Proving    sSet: YES active: YES tktH: 45445 seedH: 47227 deals: [102001 102364 102838 103421 0 0 0 0 0 0 0 0 0 103787 104062 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                                                                              toUpgrade:false
> 53: Proving    sSet: YES active: YES tktH: 46315 seedH: 48292 deals: [104733 105156 106068 106216 106714 0 0 0 0 0 0 0 0 0 0 106989 0 0 0 0 0 0]                                                                                                                                                                                                toUpgrade:false
> 54: Proving    sSet: YES active: YES tktH: 47200 seedH: 48884 deals: [107553 107896 108531 108874 0 0 0 0 0 0 0 0 0 0 109079 0 0 0 0 0 0 0]                                                                                                                                                                                                     toUpgrade:false
> 55: Proving    sSet: YES active: YES tktH: 48301 seedH: 50413 deals: [109621 0 0 0 0 0 0 0 0 0 0 109620 109682 110354 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                                                                                          toUpgrade:false
> 56: Proving    sSet: YES active: YES tktH: 48763 seedH: 50516 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 57: Proving    sSet: YES active: YES tktH: 49839 seedH: 51483 deals: [0]                                                                                                                                                                                                                                                                        toUpgrade:false
> 58: Proving    sSet: YES active: YES tktH: 50448 seedH: 52234 deals: [114866 0 0 0 0 0 0 0 0]                                                                                                                                                                                                                                                   toUpgrade:false
> 59: Proving    sSet: YES active: YES tktH: 51207 seedH: 52992 deals: [115174 115623 0 0 0 0 0 0 0 0 0 115999 116362 116739 117601 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                                                                              toUpgrade:false
> 60: Proving    sSet: YES active: YES tktH: 52000 seedH: 53837 deals: [118101 118428 0 0 0 0 0 0 0 0 0 119144 119518 0 0 0 0 0 0 0 0 0 0 119834 0 0 0 0 0 0]                                                                                                                                                                                     toUpgrade:false
> 61: Proving    sSet: YES active: YES tktH: 52761 seedH: 54594 deals: [120766 121193 121463 0 0 0 0 0 0 0 0 0 121768 0 0 0 0 0 0 0]                                                                                                                                                                                                              toUpgrade:false
> 62: Proving    sSet: YES active: YES tktH: 53559 seedH: 55358 deals: [122211 0 0 0 0 0 0 0 0 0 0 122276 122571 0 0 0 0 0 0 0 0 0 0 123009 123919 0 0 0 0 0 0 0]                                                                                                                                                                                 toUpgrade:false
> 63: Proving    sSet: YES active: YES tktH: 54333 seedH: 56138 deals: [124771 125262 125625 0 0 0 0 0 0 0 0 0 125976 0 0 0 0 0 0 0]                                                                                                                                                                                                              toUpgrade:false
> 64: Proving    sSet: YES active: YES tktH: 55104 seedH: 56902 deals: [126267 127109 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                                                                                                                          toUpgrade:false
> 65: Committing sSet: NO  active: NO  tktH: 55887 seedH: 57694 deals: [127880 128212 128536 0 0 0 0 0 0 0 0 0 128879 0 0 0 0 0 0 0]                                                                                                                                                                                                              toUpgrade:false
> 66: PreCommit1 sSet: NO  active: NO  tktH: 0     seedH: 0     deals: [129205 129537 129893 130255 0 0 0 0 0 0 0 0 0 0 130682 131209 0 0 0 0 0 0]                                                                                                                                                                                                toUpgrade:false
> 67: WaitDeals  sSet: NO  active: NO  tktH: 0     seedH: 0     deals: [132027 132794]

**Comment by stuberman** [comment]
`lotus-miner sectors status --on-chain-info --log 62`

[Sector status.txt](https://github.com/filecoin-project/lotus/files/5215581/Sector.status.txt)

**Comment by maruoshui** [comment]
pls see the proving deals as blew, they are all pending status on dashboard:
```

432: Proving       sSet: YES active: YES tktH: 54790 seedH: 56572 deals: [115265 115712 116080 0 0 0 0 0 0 0 0 0 0 116433 117701 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                                                                                                                                       toUpgrade:false

440: Proving       sSet: YES active: YES tktH: 52349 seedH: 55826 deals: [118154 118560 119187 119554 119906 120812 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                                                                                                                                                         toUpgrade:false

441: Proving       sSet: YES active: YES tktH: 54772 seedH: 56866 deals: [121291 0 0 0 0 0 0 0 0 0 0 121825 122299 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

442: Proving       sSet: YES active: YES tktH: 55574 seedH: 57374 deals: [127937 0 0 0 0 0 0 0 0]
```

**Comment by Leozhang404** [comment]
**New Deal Issue 1**: in my local miner, there are seven deals have been successful **StorageDealActive**, but they are failed on the dashboard. Yesterday, these deals has been removed:joy:, I think they should be mark as successful. Please review~ 

**t016398 deals:**

1. Sep 13 08:12:45 bafyreibl5ndlxewpr5vm2gweaxvutmjmamxcgqe2qborcgmn2xuytw4764 125769 StorageDealActive  t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i 128KiB 0 FIL 703234  
2. Sep 13 09:39:20 bafyreiejmyechpshfg3vnvc2sk3nqcj3mohdr6ci6lmwcpmudg7uaed7ba 126130 StorageDealActive  t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i 128KiB 0 FIL 703061  
3. Sep 13 10:59:18 bafyreieqrwcqd6euxzzxwuubtenaziekxwfqsqcu6tt3sthrvu7ves32ui 126710 StorageDealActive  t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i 128MiB 0 FIL 702901

  

**t01231 deals:**

1. Sep 13 03:20:15 bafyreidfuncdsmiqx6cbxrmvwpw36gcp6ol7cavxxrfu535mqmpheqj2ou 125776 StorageDealActive  t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i                        128MiB 0 FIL      702383  
2. Sep 13 04:59:09 bafyreie4vragmza5jvdjos2g4do6lyilwdvjavbyidrrdts5jrmuds67nq 125780 StorageDealActive  t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i                        128KiB 0 FIL      705065  
3. Sep 13 06:37:56 bafyreihef3jj5qv72hyc4hqwmi24uuqm6eakeggkfkkh4vrxukfejkivlq 125779 StorageDealActive  t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i   
4. Sep 13 09:37:21 bafyreiecbxkauoqsckl3ckaidvch3eyfo4kswn6otx2oxyzwhgo5kuifti 126309 StorageDealSealing t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i

![image](https://user-images.githubusercontent.com/38653654/93040755-5247bf00-f67d-11ea-901c-45b1f04bbaa0.png)
![image](https://user-images.githubusercontent.com/38653654/93040768-58d63680-f67d-11ea-9432-9965505058cb.png)


**New Deal Issue 2:** 
this three deals(dealID:121653, 121939, 122233) has **Proving**  in my local miner(sector number: 227566), but they are failed in the dashboard and has been removed from dashboard, as following, please review：
![image](https://user-images.githubusercontent.com/38653654/93040804-6ee3f700-f67d-11ea-827b-88339417dc5f.png)
![image](https://user-images.githubusercontent.com/38653654/93040812-760b0500-f67d-11ea-811a-cf5c96c6425a.png)

**Comment by KIMQI001** [comment]
![image](https://user-images.githubusercontent.com/24293349/93042036-aa33f500-f680-11ea-911d-84dcd4321e3f.png)
![image](https://user-images.githubusercontent.com/24293349/93042048-aef8a900-f680-11ea-8689-8ef7660a1b17.png)
![image](https://user-images.githubusercontent.com/24293349/93042051-b1f39980-f680-11ea-81ae-a1f53c1a8b27.png)
![image](https://user-images.githubusercontent.com/24293349/93042056-b61fb700-f680-11ea-89ab-2f8d3b316af4.png)
![image](https://user-images.githubusercontent.com/24293349/93042061-b91aa780-f680-11ea-9aba-1e6f82cbec57.png)
![image](https://user-images.githubusercontent.com/24293349/93042067-bb7d0180-f680-11ea-8ea8-b5253cb7a8fe.png)
![image](https://user-images.githubusercontent.com/24293349/93042071-be77f200-f680-11ea-9295-964d62f910d4.png)
![image](https://user-images.githubusercontent.com/24293349/93042077-c041b580-f680-11ea-92ea-faf52dd12180.png)
![image](https://user-images.githubusercontent.com/24293349/93042081-c2a40f80-f680-11ea-9f81-843400c47c09.png)
![image](https://user-images.githubusercontent.com/24293349/93042087-c5066980-f680-11ea-8a14-e866c5665711.png)
![image](https://user-images.githubusercontent.com/24293349/93042092-c8015a00-f680-11ea-8ea5-f8cd21c0bfe9.png)
![image](https://user-images.githubusercontent.com/24293349/93042098-ca63b400-f680-11ea-8b93-4a0862ed29a4.png)
![image](https://user-images.githubusercontent.com/24293349/93042103-ccc60e00-f680-11ea-8f02-c5f4bde50256.png)
![image](https://user-images.githubusercontent.com/24293349/93042108-d0599500-f680-11ea-913e-f52aea3e5e5c.png)
![image](https://user-images.githubusercontent.com/24293349/93042114-d3548580-f680-11ea-8955-25bd71a0667f.png)
![image](https://user-images.githubusercontent.com/24293349/93042119-d6e80c80-f680-11ea-8acd-9edd8acf7177.png)
![image](https://user-images.githubusercontent.com/24293349/93042126-d94a6680-f680-11ea-95d0-7f878d921cfd.png)
![image](https://user-images.githubusercontent.com/24293349/93042129-dc455700-f680-11ea-8317-6a37811c3dd7.png)

t016412

**Comment by yuwenhui** [comment]
After i updated to 0.7.0, there is no retrieval deals received.
I have stoped my sealing workers and just let miner running, however, my miner still received some deals, and now with `StorageDealSealing` state, and have no retrieval deals. Could you please help me check what happened?
MinerID: t014634  https://spacerace.filecoin.io/deals/t014634

**Comment by leekueha** [comment]
It is the same problem.
Much of it is in [Pending] [StorageDealSealing] state.
It has been updated to the latest version.

https://spacerace.filecoin.io/deals/t015655

**Comment by jennijuju** [comment]
We are aware of this dashboard error and closing this ticket b/c not lotus related.

**Comment by fanfu13** [comment]
![image](https://user-images.githubusercontent.com/5567234/93046916-b4a8bb80-f68d-11ea-8aa8-3bf24cccb5b3.png)
![image](https://user-images.githubusercontent.com/5567234/93046990-e9b50e00-f68d-11ea-85da-7f1a4c9c0f65.png)
![image](https://user-images.githubusercontent.com/5567234/93047023-081b0980-f68e-11ea-9832-212e1e4ce58d.png)
![image](https://user-images.githubusercontent.com/5567234/93047068-2254e780-f68e-11ea-9b10-5e6978d4fd4a.png)
Several storage deals have been already finished, while the dashboard think they are under sealing.

**Comment by yablu** [comment]
**t08403**

`62: Proving              sSet: YES active: YES tktH: 56844 seedH: 59078 deals: [128951 129623 129277 131400 128633 0 0 0 0 0 0 0 0 0 129989 130358 130771 132149 0 0 0 0 0 0 0] `

Many thanks
