### ISSUE TITLE
Add tag for each key in the api package

### ISSUE THREAD

**Issue by yuwenhui** [filecoin-project/lotus#3820]
When i develop a lotus JSON RPC provider using JavaScript, I found that all keys in JSON RPC output named using upper camel-case. However, almost all the frontend framework are used to lower camel-case styled as object key name. I suggest add a tag for each key with lower camel-case styled name. Like this:
```go
type Version struct {
	Version string `json:"version"`

	// APIVersion is a binary encoded semver version of the remote implementing
	// this api
	//
	// See APIVersion in build/version.go
	APIVersion build.Version `json:"apiVersion"`

	// TODO: git commit / os / genesis cid?

	// Seconds
	BlockDelay uint64 `json:"blockDelay"`
}
```

**Comment by whyrusleeping** [comment]
Agree, we should do this. Thank you for the issue!

**Comment by TippyFlitsUK** [comment]
Hi @yuwenhui 

This looks like a reminder. Should we close it or keep it open?
