### ISSUE TITLE
Unsealed Sectors staying on worker at the end of sealing ==> Retrieval deals timeout.

### ISSUE THREAD

**Issue by std** [filecoin-project/lotus#3827]
Unsealed Sectors staying on worker at the end of sealing ==> Retrieval deals timeout.

At the end of the sealing process, sector’s unsealed file is not transferred to the long term storage but stay on the worker unsealed folder.
Retrieval of deals stored on that sector timeout because the unsealed folder is not available on the miner.
_____________
In order to investigate this case
I created tool, which can gather all information of retrieval deals linked together - including sector where retrieval is requested from ..
( RetrieveDealID,  dataCid, pieceCid, StorageDealID, SectorID, sectorState, sectorActive, Size, Status, result, Message)
And discovered:
now all my pending deals query data in sector 903
which is stored in two locations:
cache and sealed files in long term storage.
unsealed file in pc2/c2 worker storage.
sector 903 is finalized and healthy
but I cannot retrieve from it even locally

p.s I can retrieve data from many other sectors both locally or over network

**To Reproduce**
lotus client retrieve --miner t08285 --pieceCid baga6ea4seaqa6we2ne2t7imwjvz2f4xdwwhzma54pzjs7iiuzhhgqj5ab6h6wiy bafk2bzacebhqseaio5f7ieqzwnyhdiadryijyslgltovnd5cza7d5fuyaiizs /tmp/output55

where dataCid is in the sector , which unsealed file stored in worker's storage ( not miner's storage)

2. See error

**Expected behavior**
sucessful retrieval

**Version (run `lotus version`):**
Local: lotus-miner version 0.7.0+git.aa83a4c1

[bot-deals (2).txt](https://github.com/filecoin-project/lotus/files/5217906/bot-deals.2.txt)

[bot-pending-deals.json.txt](https://github.com/filecoin-project/lotus/files/5217947/bot-pending-deals.json.txt)

**Comment by NSC-FIL** [comment]
I have seen this issue as well.

**Comment by Reiers** [comment]
Hi @std 
Thanks for the report. The issue is stale and outdated. 
Is this a issue in current release (v1.15.1) ?
