### ISSUE TITLE
Sector upgrade not working

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/lotus#3834]
Several miners are reporting that they have run the sector upgrade command (including twice), but it's not working correctly locally. Reports in comments.

Some may be related to clogged mempool.

**Comment by mishmosh** [comment]
From `Snow-Sudo` ([Slack thread](https://filecoinproject.slack.com/archives/C019KBJ6Q11/p1599948429298400)):
> I did lotus-miner sectors mark-for-upgrade 0 yesterday but my sector zero is still this: 0:
Proving    sSet: YES active: YES tktH: 48243 seedH: 51073 deals: [0]  toUpgrade:true. The active should be set to NO but it's still set to YES

> I started it at 3:00 EST on Friday so it should be done by now [Sunday]

`stuberman` suggested checking mempool & increasing gas premium if stuck messages.

Their miner is no longer visible on competition dashboard so may have been slashed and lost all power. https://spacerace.filecoin.io/?search=t019459

**Comment by mishmosh** [comment]
From `Paul` (Slack thread):

I've also been unable to upgrade a sector, t016056.

![image](https://user-images.githubusercontent.com/1306020/93099517-152bfe80-f676-11ea-82c4-9944635fce2c.png)

**Comment by mishmosh** [comment]
From `HuangHao` ([thread](https://filecoinproject.slack.com/archives/C0179RNEMU4/p1600080724107000)):
> It's been many days. why?  we had marked for upgraded with 6 sectors: 0,1,3333,3334.

Miner t017229.

![image](https://user-images.githubusercontent.com/1306020/93099646-40165280-f676-11ea-9a58-3ea2d3c710ad.png)

**Comment by WBQ1995** [comment]
Same issue

Miner: t019104
```
$ lotus mpool pending —local | grep Nonce | wc -l
342
```

**Comment by xingjirw** [comment]
same issue ,miner id   T010501

**Comment by ribasushi** [comment]
@WBQ1995 @xingjirw can both of you run these 2 commands and respond back with the text they return ( if any ). Thank you!
```
for s in $( lotus-miner sectors list | grep -v 'deals:\s\[0\]' | cut -d ':' -f 1 ) ; do lotus-miner sectors status --log $s | grep -oE '\b2020-.*ReplaceCapacity":true.*'; done
```
```
for s in $( lotus-miner sectors list | grep 'Proving\s*sSet:\s*YES\s*active:\s*YES' | grep -v 'deals:\s\[0\]' | cut -d ':' -f 1 ) ; do lotus-miner sectors status --log $s | grep -oE '\b2020-.*ReplaceCapacity":true.*'; done
```

**Comment by WBQ1995** [comment]
> for s in $( lotus-miner sectors list | grep 'Proving\s*sSet:\s*YES\s*active:\s*YES' | grep -v 'deals:\s\[0\]' | cut -d ':' -f 1 ) ; do lotus-miner sectors status --log $s | grep -oE '\b2020-.*ReplaceCapacity":true.*'; done

Both of the commands returns nothing.

**Comment by WBQ1995** [comment]
> @WBQ1995 @xingjirw can both of you run these 2 commands and respond back with the text they return ( if any ). Thank you!
> 
> ```
> for s in $( lotus-miner sectors list | grep -v 'deals:\s\[0\]' | cut -d ':' -f 1 ) ; do lotus-miner sectors status --log $s | grep -oE '\b2020-.*ReplaceCapacity":true.*'; done
> ```
> 
> ```
> for s in $( lotus-miner sectors list | grep 'Proving\s*sSet:\s*YES\s*active:\s*YES' | grep -v 'deals:\s\[0\]' | cut -d ':' -f 1 ) ; do lotus-miner sectors status --log $s | grep -oE '\b2020-.*ReplaceCapacity":true.*'; done
> ```

Both of the commands returns nothing.

**Comment by jackoelv** [comment]
same as t08094.

**Comment by jackoelv** [comment]
`for s in $( lotus-miner sectors list | grep -v 'deals:\s\[0\]' | cut -d ':' -f 1 ) ; do lotus-miner sectors status --log $s | grep -oE '\b2020-.*ReplaceCapacity":true.*'; done`

nothing output.

**Comment by jackoelv** [comment]
same as @WBQ1995

**Comment by jackoelv** [comment]
Same issue

Miner: t08094

root@miner0:~# lotus mpool pending --local | wc -l
0

I confirmed have run the command `lotus-miner` sectors mark-for-upgrade 2820
and some other sectors.

**Comment by jennijuju** [comment]
#3797
