### ISSUE TITLE
Syncing issue after v0.7.0

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3837]
This is a ticket to collect various syncing issue from miners.

Information to provide:
- What's your machine spec?
- What issue did you run into? Do you see any error message, if so, which error message(s) did you see?
- Did it happen before 0.7.0?

Feel free to add anything that you think can be helpful!

**Comment by jimpick** [comment]
I just experienced a node sync issue in the past hour. It's a 16MB machine for making deals - I'm not running a miner. After upgrading to `master` at `86607452d7bbe139520aebcb1b9abb81f1a8aac6`, it appeared to be stuck. Two other identical nodes I upgraded at the same time did manage to sync. After restarting the node, it synced again.

**Comment by mishmosh** [comment]
The protofire team noticed their 10 client nodes falling out of sync when out of diskspace. via @magik6k:

> oof, we really need to make sure running out of disk space isn't breaking the chainstore.

**Comment by kenshyx** [comment]
Every time when I submit a message there is a high chance that my chain gets corrupted.This was happening also before the version v0.7 but now it's more often.
I'm running the lotus node and the miner on a dual intel cpu with 32 cores/512gb ram and for storage I have a couple of seagate exos x16.

**Comment by zelin4913** [comment]
my miner id is t07919 
https://filfox.info/en/address/t07919

After using the lotus-miner sectors remove command to delete the wrong sectors, the lost computing power will not be recovered, and it will still prompt `sanity check failed` when doing a window post.
The version where this problem first appeared was 0.6.0,
After upgrading to 0.7.0, the problem still exists, but the error message has changed

![remove](https://user-images.githubusercontent.com/69831083/93157125-2fc8ab00-f73c-11ea-9381-60c9f9426e6e.png)

Generate window PoSt skipped sectors jiēduàn chénggōng de tiàoguòle sān gè cuòwù shàn qū, dànshì zài submitting window PoSt jiēduàn yòu jiāng cuòwù shàn qū bāokuò jìnlái, cǐ wèntí dǎozhì suàn lì wúfǎ huīfù
104/5000
Three error sectors were successfully skipped in the generate window PoSt skipped sectors stage, but the error sectors were included in the submitting window PoSt stage. This problem caused the computing power to be unrecoverable.

**Comment by zelin4913** [comment]
[window-post-bug.txt](https://github.com/filecoin-project/lotus/files/5222090/window-post-bug.txt)
[window-post-skipped.txt](https://github.com/filecoin-project/lotus/files/5222091/window-post-skipped.txt)

**Comment by jennijuju** [comment]
related : #3840

**Comment by jennijuju** [comment]
> The protofire team noticed their 10 client nodes falling out of sync when low on diskspace. via @magik6k:
> 
> > oof, we really need to make sure running out of disk space isn't breaking the chainstore.



> my miner id is t07919
> https://filfox.info/en/address/t07919
> 
> After using the lotus-miner sectors remove command to delete the wrong sectors, the lost computing power will not be recovered, and it will still prompt `sanity check failed` when doing a window post.
> The version where this problem first appeared was 0.6.0,
> After upgrading to 0.7.0, the problem still exists, but the error message has changed
> 
> ![remove](https://user-images.githubusercontent.com/69831083/93157125-2fc8ab00-f73c-11ea-9381-60c9f9426e6e.png)
> 
> Generate window PoSt skipped sectors jiēduàn chénggōng de tiàoguòle sān gè cuòwù shàn qū, dànshì zài submitting window PoSt jiēduàn yòu jiāng cuòwù shàn qū bāokuò jìnlái, cǐ wèntí dǎozhì suàn lì wúfǎ huīfù
> 104/5000
> Three error sectors were successfully skipped in the generate window PoSt skipped sectors stage, but the error sectors were included in the submitting window PoSt stage. This problem caused the computing power to be unrecoverable.

This is not a syncing issue.

**Comment by jennijuju** [comment]
from 可祤 AMD 7452 ,566G Mem， 2T SSD, the error is chain linked to block marked previously as bad   and  chain linked to block marked previously as bad

**Comment by creaz79** [comment]
I have noticed, that if i run as systemd service (default service file) - there is a change - * failed to validate blocks random beacon values and after it - block linked to block marked as bad...
But after it if i stop service and run "lotus daemon" - no error, sync go further, but as service it will never pass this block
