### ISSUE TITLE
Lotus Node Running out of Space corrupts datastore

### ISSUE THREAD

**Issue by Meatball13** [filecoin-project/lotus#3840]
**Describe the bug**
Drive hosting lotus daemon and lotus-miner ran out of space and the miner / daemon had errors.  lotus-miner will not longer start with the following error.

`ERROR: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/tbtminer/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.MetadataDS: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): opening datastore /metadata: leveldb/journal: block/chunk corrupted: chunk length overflows block (3280 bytes) [file=000145.log]`

**To Reproduce**
1. Run lotus daemon/lotus-miner.
2. Run out of space on drive.
3. Daemon/miner will start throwing errors.  Kill them and then restart.

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
lotus version 0.7.0+git.232cc320

**Additional context**
Log file referenced is attached.
[000145.log](https://github.com/filecoin-project/lotus/files/5220341/000145.log)

**Comment by Meatball13** [comment]
Quick update.  On a hunch I renamed that 00145.log file and restarted lotus-miner and it appears to have restarted without a problem.  Log file must get corrupted and then lotus-miner can't restart.  So, still a bug there, but seems to have a workaround.

**Comment by RobQuistNL** [comment]
Related: https://github.com/filecoin-project/lotus/issues/1958

**Comment by RobQuistNL** [comment]
More: https://github.com/filecoin-project/lotus/issues/3837

**Comment by jennijuju** [comment]
You can find some level db recovery via google, for example

```
$ python
…
>>> import leveldb
>>> leveldb.RepairDB(“)
``

**Comment by jennijuju** [comment]
Moving this to discussion for folks to share solutions
