### ISSUE TITLE
Proposal: error codes

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#3847]
It might be useful to have codes associated with the various errors subsystems of Lotus can produce. This came up when thinking about the dealbot, where it would've been useful to say "all Lotus 700 errors are of _this_ nature, and should therefore be treated in _this_ way".

**Comment by andrewxhill** [comment]
this is already limiting our ability to uncover issues in lotus. so we are strong proponents. 

the current lotus error reporting mostly takes the form: `{error category}: {template message}`. on our infrastructure we see ~10 categories of error in our logs. the template messages then include dynamic information such as FIL amounts involved, addresses, etc., that make them near impossible to group in a meaningful way.

**Comment by TippyFlitsUK** [comment]
Hi @arajasek 

This looks like a reminder. Should we close it or keep it open?
