### ISSUE TITLE
Diversification of drand distribution nodes

### ISSUE THREAD

**Issue by nikkolasg** [filecoin-project/lotus#3853]
To prevent a case where PL distribution nodes are down while drand is still creating randomness, we want to diversify the list of distribution servers.
First easy step is to add https://drand.cloudflare.com to the list of HTTP endpoints that Lotus can fetch from.

**Comment by dineshshenoy** [comment]
This was completed earlier.

**Comment by arajasek** [comment]
Easy step done in https://github.com/filecoin-project/lotus/pull/4125
