### ISSUE TITLE
Faucet always "My account is too new"

### ISSUE THREAD

**Issue by yjj2** [filecoin-project/lotus#3863]
Faucet not working.
Could someone send me some fil 
my address : t3s7uvbrvn4xhiyor5kdaxhivtdakjrfezahpeo62yzg2uuicizne3fztwtmaj7rqiydfgejjhrq2dj23vflga

Please help me 😢😢

Faucet always say to me " User account is too new"

**Comment by arajasek** [comment]
This is not an issue with the Lotus codebase.

**Comment by yjj2** [comment]
> This is not an issue with the Lotus codebase.

I'm sorry, but I didn't know where to say this.😢😢
