### ISSUE TITLE
StateSearchMsg Hangs

### ISSUE THREAD

**Issue by Schwartz10** [filecoin-project/lotus#3866]
**Describe the bug**
StateSearchMsg JSON RPC handler hangs 

**To Reproduce**
On latest space race, try and `StateSearchMsg` `{"/": "bafy2bzaceayobuf42cq3w7rzrqaxenyvupeurgxsfbqyzd4kx3jyytyjwrh64"}`, the call never seems to resolve (although it times out for me before I get any response back from the daemon)

The actual message is not _too_ far back in the chain, so I'd expect this to resolve within someone of a reasonable time frame https://filscout.io/en/pc/message/bafy2bzaceayobuf42cq3w7rzrqaxenyvupeurgxsfbqyzd4kx3jyytyjwrh64

Lotus node version (from jsonrpc)
```
{"jsonrpc":"2.0","result":{"Version":"0.7.0+git.232cc32","APIVersion":3584,"BlockDelay":30},"id":1}
````

**Comment by crossle** [comment]
Same problem, too slow

**Comment by Ljzn** [comment]
Same problem, hang forever for history message. New messages seem faster.

**Comment by Ljzn** [comment]
Same problem, hang forever for history message. New messages seem faster.

**Comment by Reiers** [comment]
Hi @Schwartz10 

Thanks for the report. The issue is outdated, and spacerace was a long time ago. 

If this is a issue in the [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1) - please open a new ticket.

Thank you !
