### ISSUE TITLE
Data Transfer: Cleanup graphsync requests that time out in the FSM

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#3878]
Once https://github.com/filecoin-project/go-data-transfer/pull/78 goes in, we will receive callbacks in `go-data-transfer`  when graphsync requests we have opened to receive data time out.

We should remove these timed out requests/channels from the channel state machine to reclaim the go-routines we have running for them as these requests will NOT terminate.

cc @hannahhoward

**Comment by aarshkshah1992** [comment]
@hannahhoward 's comment here:

https://github.com/filecoin-project/go-data-transfer/pull/78#discussion_r489745514

should also be incorporated into this work.

**Comment by rjan90** [comment]
Hey! 😄 It seems like this issue has been fixed & merged. So closing this now.
