### ISSUE TITLE
lotus sync break every 1-2 hours with error `parent state root did not match computed state`

### ISSUE THREAD

**Issue by HuaZhuangNan** [filecoin-project/lotus#3879]
**Describe the bug**
In lotus v0.7.0 we still meet the problem that every 1-2 hours ,the sync get break . We have used a shell to restart daemon ,and the problem could be solved temporary ， and will not inference the miner and retrieval works . But we still don't know what causes this problem. OS,filesystem ,or other settings?   

**To Reproduce**
1. Run `lotus daemon`
2. ` Error: collectChain syncMessages: message processing failed: validating block bafy2bzaceaxssgvlctgopfkldgc5x6uveekbbrvuvs6foh7hdkq2k7eyq4sse: parent state root did not match computed state (bafy2bzaceccrrgxtq5rwcdhfwr4sdibziksjiwlrkwdiyasrs5cjqwcmff3zi != bafy2bzaced3extqrgimhljrglpgcc6dayevzmmqb4n4yiznj4mfi74eexrj4o)
`

**Expected behavior**
The error occur every 1-2 hours 

**Version (run `lotus version`):**
V0.7.0

**Comment by HuaZhuangNan** [comment]
![image](https://user-images.githubusercontent.com/46070704/93308847-63d3c700-f835-11ea-8be7-19185df007a6.png)

**Comment by HuaZhuangNan** [comment]
![image](https://user-images.githubusercontent.com/46070704/93411413-b660c200-f8cd-11ea-8654-c17e2eeb2499.png)

**Comment by samhuyi** [comment]
we have the same problem.No idea how to solve it.

**Comment by HuaZhuangNan** [comment]
how much server did you run in one sever ,and what kind of CPU is in your server?

**Comment by HuaZhuangNan** [comment]
how much CPU did you run in one sever ,and what kind of CPU is in your server?

**Comment by jennijuju** [comment]
Hey sorry for the late reply - we were looking into this issue and just wondering, do you ever have blst on with the daemon terminal? And do you see any rust panics in your log?

**Comment by HuaZhuangNan** [comment]
@jennijuju  yes, I think it is the problem of our dual CPU. We only use one CPU for a long time to have this problem. The dual CPU lasts for an hour at most

**Comment by jennijuju** [comment]
From TEHTVS1, have been had issue since 0.7.0 7262 x2 / 1TB RAM / 30TB HDD Lotus was installed on the HDD.
Log after updating to 0.8.0: https://drive.google.com/file/d/1cFA5HTcyKh2NXVieGKnliM-trS3F__m0/view?usp=sharing

**Comment by jennijuju** [comment]
Troubleshooting step:
1. Check hard disk drive and ram status.
2. How do they stop the process.

**Comment by jennijuju** [comment]
one miner suggested he's node is alway syncing fine until a miner is connected to it. and got two miners connect to t he same node

**Comment by HuaZhuangNan** [comment]
I used to be a dual CPU, now I have a single CPU, and there is no disconnection anymore @jennijuju

**Comment by Richardszwz** [comment]
Do you have any solution for the problem?

2021-04-27T21:28:06.639+0800    INFO    chain   chain/sync.go:713       block validation    {"took": 8.571564089, "height": "851", "age": 21198156.639234234}
2021-04-27T21:28:06.639+0800    ERROR   chain   chain/sync_manager.go:424       sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /opt/lotus/chain/sync.go:577
  - collectChain syncMessages:
    github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /opt/lotus/chain/sync.go:1719
  - message processing failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
        /opt/lotus/chain/sync.go:1495
  - validating block bafy2bzacebhd37223imqcsemdkvdd2rmmzns5fwcfd4moffpnxwj3ohcz4aek:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet.func1
        /opt/lotus/chain/sync.go:627
  - 1 error occurred:
        * parent state root did not match computed state (bafy2bzaceay7ksnarclsjm57kki7jevypkj222o54qlfuvdpvf7ysqclo74mm != bafy2bzaced4camdhxwdurrauyzzogj7aa3ogtzb4qqet6lp3hatorbvswwqmu):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /opt/lotus/chain/sync.go:812

**Comment by TippyFlitsUK** [comment]
Hi @HuaZhuangNan 

Thanks for the report. The issue is outdated. 

If this is a issue in the current release - please open a new ticket.

Thank you !
