### ISSUE TITLE
lotus [signal SIGSEGV: segmentation violation] on lotus daemon stop

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/lotus#3882]
**Describe the bug**
i've got a `
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x103f380]`
right after running 
lotus daemon stop command.

**To Reproduce**

I tried to reproduce the issue 2 times after . But wasn't  being able to reproduce it.

1. lotus daemon stop
2. See error : 

2020-09-16T12:08:32.479+0200	WARN	chainxchg	exchange/client.go:111	could not connect to peer 16Uiu2HAmKLNy99C6mmZg11dz5voqh9oM8GoB9x9AKSH9WvcHActr: peer 16Uiu2HAmKLNy99C6mmZg11dz5voqh9oM8GoB9x9AKSH9WvcHActr does not support protocols [/fil/sync/blk/0.0.1 /fil/chain/xchg/0.0.1]
2020-09-16T12:08:32.480+0200	ERROR	chain	chain/sync_manager.go:389	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /home/s0nik42/lotus/chain/sync.go:570
  - failed to sync fork:
    github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
        /home/s0nik42/lotus/chain/sync.go:1389
  - doRequest failed for all peers:
    github.com/filecoin-project/lotus/chain/exchange.(*client).doRequest
        /home/s0nik42/lotus/chain/exchange/client.go:134
2020-09-16T12:08:32.558+0200	INFO	badger	v2@v2.0.1-rc1.0.20200716180832-3ab515320794/levels.go:975	Got compaction priority: {level:0 score:1.73 dropPrefixes:[]}
2020-09-16T12:08:32.559+0200	INFO	badger	v2@v2.0.1-rc1.0.20200716180832-3ab515320794/levels.go:991	Running for level: 0

2020-09-16T12:08:34.612+0200	INFO	badger	v2@v2.0.1-rc1.0.20200716180832-3ab515320794/levels.go:953	LOG Compact 0->1, del 5 tables, add 4 tables, took 2.053253773s

2020-09-16T12:08:34.612+0200	INFO	badger	v2@v2.0.1-rc1.0.20200716180832-3ab515320794/levels.go:1000	Compaction for level: 0 DONE
2020-09-16T12:08:34.612+0200	INFO	badger	v2@v2.0.1-rc1.0.20200716180832-3ab515320794/db.go:537	Force compaction on level 0 done
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x103f380]

goroutine 971543 [running]:
github.com/ipfs/go-ds-measure.(*measuredBatch).Put(0xc0f6106f40, 0xc0d25380a0, 0x42, 0xc04a09b200, 0x3aa, 0x466, 0x0, 0x0)
	/home/s0nik42/go/pkg/mod/github.com/ipfs/go-ds-measure@v0.1.0/measure.go:327 +0x110
github.com/ipfs/go-datastore/keytransform.(*transformBatch).Put(0xc0f6106f60, 0xc05016a5c0, 0x3b, 0xc04a09b200, 0x3aa, 0x466, 0xb220, 0x71)
	/home/s0nik42/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/keytransform/keytransform.go:224 +0x8a
github.com/ipfs/go-ipfs-blockstore.(*blockstore).PutMany(0xc0007945a0, 0xc0fd490030, 0x1, 0x1, 0x0, 0x0)
	/home/s0nik42/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.1/blockstore.go:169 +0x1f2
github.com/ipfs/go-ipfs-blockstore.(*idstore).PutMany(0xc068fc2330, 0xc0fd490020, 0x1, 0x1, 0x1, 0xc0fd490020)
	/home/s0nik42/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.1/idstore.go:82 +0x124
github.com/ipfs/go-ipfs-blockstore.(*arccache).PutMany(0xc05413bdc0, 0xc0fd490000, 0x1, 0x1, 0x1, 0x71)
	/home/s0nik42/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.1/arc_cache.go:148 +0x137
github.com/ipfs/go-ipfs-blockstore.(*bloomcache).PutMany(0xc068fc8840, 0xc0fd490000, 0x1, 0x1, 0x0, 0x0)
	/home/s0nik42/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.1/bloom_cache.go:176 +0x56
github.com/ipfs/go-ipfs-blockstore.(*idstore).PutMany(0xc068fc2370, 0xc10fc75ff0, 0x1, 0x1, 0x0, 0x0)
	/home/s0nik42/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.1/idstore.go:82 +0x124
github.com/filecoin-project/lotus/chain/store.(*ChainStore).PersistBlockHeaders(0xc000170b00, 0xc13f4fc370, 0x1, 0x1, 0x0, 0x0)
	/home/s0nik42/lotus/chain/store/store.go:576 +0x151
github.com/filecoin-project/lotus/chain.(*Syncer).InformNewHead(0xc0001bf930, 0xc0d944c210, 0x26, 0xc044813ef0, 0x0)
	/home/s0nik42/lotus/chain/sync.go:262 +0x618
github.com/filecoin-project/lotus/chain.(*Syncer).InformNewBlock(...)
	/home/s0nik42/lotus/chain/sync.go:382
github.com/filecoin-project/lotus/chain/sub.HandleIncomingBlocks.func1(0x2ecef20, 0xc000407830, 0xc0eb574f00, 0xc1201e7500, 0x26, 0xc0ea403830, 0xc0001bf930, 0x2ed47e0, 0xc000443b00)
	/home/s0nik42/lotus/chain/sub/incoming.go:88 +0x853
created by github.com/filecoin-project/lotus/chain/sub.HandleIncomingBlocks
	/home/s0nik42/lotus/chain/sub/incoming.go:67 +0x152

**Version (run `lotus version`):**

lotus -v
lotus version 0.7.0+git.232cc320

**Additional context**

the only particularity of my setup is that I moved .lotus to another disk (/mnt/data/lotus/.lotus) doing : 
```
rsync -arv 
ln -s /mnt/data/lotus.lotus ~/

```
This is discussed on slack with @ribasushi here : 
https://filecoinproject.slack.com/archives/C0179RNEMU4/p1600251232288700?thread_ts=1600248057.260000&cid=C0179RNEMU4

**Comment by jennijuju** [comment]
Another one 
When I build a new node I run the lotus daemon, I got the below error😂, do any body have a solution? ❤️
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x683aa0]

goroutine 103889 [running]:
math/big.(*Int).Add(0xc07eb44500, 0xc07eb443a0, 0x0, 0xc0880e4b30)
  /usr/local/go/src/math/big/int.go:118 +0x40
github.com/filecoin-project/go-state-types/big.Add(0xc07eb443a0, 0x0, 0xc07d9ab890)
  /root/go/pkg/mod/github.com/filecoin-project/go-state-types@v0.0.0-20200911004822-964d6c679cfc/big/int.go:86 +0x67
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).ApplyBlocks(0xc01c7e4600, 0x2ed2220, 0xc04a2381b0, 0x30b7, 0xc069eb8ba0, 0x26, 0xc034864900, 0x6, 0x8, 0x30b8, ...)
  /root/fc/lotus/chain/stmgr/stmgr.go:236 +0x168a
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).computeTipSetState(0xc01c7e4600, 0x2ed2220, 0xc04a2381b0, 0xc07b8c99c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /root/fc/lotus/chain/stmgr/stmgr.go:353 +0x638
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).TipSetState(0xc01c7e4600, 0x2ed2220, 0xc052401d40, 0xc07b8c99c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /root/fc/lotus/chain/stmgr/stmgr.go:118 +0x6ec
github.com/filecoin-project/lotus/chain.(*Syncer).checkBlockMessages(0xc01f1f84e0, 0x2ed2220, 0xc033cadc80, 0xc0952a4b40, 0xc07b8c99c0, 0x588926, 0xc03ca055a9)
  /root/fc/lotus/chain/sync.go:1049 +0x516
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func3(0xc03ca055cc, 0x1)
  /root/fc/lotus/chain/sync.go:757 +0x55
github.com/Gurpartap/async.Err.func1(0xc07604c120, 0xc08193e720, 0xc091b47db0)
  /root/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:29 +0x53
created by github.com/Gurpartap/async.Err
  /root/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:27 +0x8a

**Comment by jennijuju** [comment]
Duplicate #3823

**Comment by jennijuju** [comment]
ADM Rezen7 3800x 8core + Geforce GTX 1660Ti + 128G + 1T SSD + 8T storage

**Comment by Reiers** [comment]
Hi @s0nik42 Julien 

Thanks for the report. The issue is outdated, and not able to reproduce her.
If this is a issue in current release - please open a new ticket.

Thank you!
