### ISSUE TITLE
my lotus node crashed after launch

### ISSUE THREAD

**Issue by yangwb** [filecoin-project/lotus#3891]
after run the commande “lotus daemon”， output：

......

goroutine 1369 [select]:
github.com/ipfs/go-bitswap/internal/decision.(*Engine).nextEnvelope(0xc0801d1080, 0x2ee2680, 0xc000409b90, 0x1, 0x0, 0x0)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:409 +0x128
github.com/ipfs/go-bitswap/internal/decision.(*Engine).taskWorker(0xc0801d1080, 0x2ee2680, 0xc000409b90)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:381 +0x1be
github.com/ipfs/go-bitswap/internal/decision.(*Engine).StartWorkers.func1(0x2efa580, 0xc0836b9d40)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:221 +0x3c
github.com/jbenet/goprocess.(*process).Go.func1(0xc083055640, 0xc0836b9d40, 0xc0836b9da0)
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:134 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:133 +0x1fe

goroutine 1372 [select]:
github.com/ipfs/go-bitswap/internal/decision.(*Engine).nextEnvelope(0xc0801d1080, 0x2ee2680, 0xc000409b90, 0x1, 0x0, 0x0)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:409 +0x128
github.com/ipfs/go-bitswap/internal/decision.(*Engine).taskWorker(0xc0801d1080, 0x2ee2680, 0xc000409b90)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:381 +0x1be
github.com/ipfs/go-bitswap/internal/decision.(*Engine).StartWorkers.func1(0x2efa580, 0xc0836b9e00)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:221 +0x3c
github.com/jbenet/goprocess.(*process).Go.func1(0xc083055660, 0xc0836b9e00, 0xc0836b9e60)
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:134 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:133 +0x1fe

goroutine 121 [syscall]:
github.com/supranational/blst/bindings/go._Cfunc_blst_p1_uncompress(0xc083788000, 0xc07efcc1b0, 0x7f8200000000)
	_cgo_gotypes.go:512 +0x4d fp=0xc083801e20 sp=0xc083801df0 pc=0x115562d
github.com/supranational/blst/bindings/go.(*_Ctype_struct___4).Uncompress(0xc083788000, 0xc07efcc1b0, 0x30, 0x30, 0x548db8)
	/app/ipfs/lotus/extern/fil-blst/blst/bindings/go/blst.go:1392 +0x48 fp=0xc083801e48 sp=0xc083801e20 pc=0x115bae8
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).AggregateVerifyCompressed.func2(0x0, 0xc083788000, 0x2b, 0x2b, 0xc0835a6000, 0x18f)
	/app/ipfs/lotus/extern/fil-blst/blst/bindings/go/blst.go:374 +0x13f fp=0xc083801ea0 sp=0xc083801e48 pc=0x115e3bf
github.com/supranational/blst/bindings/go.coreAggregateVerifyPkInG1.func1(0xc07efc2199, 0xc07efcc1e0, 0x2b, 0x2b, 0xc07efc21a8, 0xc07efc21ac, 0x1, 0x28, 0xc07efc21a0, 0xc07efc21b0, ...)
	/app/ipfs/lotus/extern/fil-blst/blst/bindings/go/blst.go:438 +0x25b fp=0xc083801f68 sp=0xc083801ea0 pc=0x115e69b
created by github.com/supranational/blst/bindings/go.coreAggregateVerifyPkInG1
	/app/ipfs/lotus/extern/fil-blst/blst/bindings/go/blst.go:420 +0x254

goroutine 1375 [select]:
github.com/ipfs/go-bitswap/internal/decision.(*Engine).nextEnvelope(0xc0801d1080, 0x2ee2680, 0xc000409b90, 0x1, 0x0, 0x0)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:409 +0x128
github.com/ipfs/go-bitswap/internal/decision.(*Engine).taskWorker(0xc0801d1080, 0x2ee2680, 0xc000409b90)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:381 +0x1be
github.com/ipfs/go-bitswap/internal/decision.(*Engine).StartWorkers.func1(0x2efa580, 0xc0836b9ec0)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:221 +0x3c
github.com/jbenet/goprocess.(*process).Go.func1(0xc083055680, 0xc0836b9ec0, 0xc0836b9f20)
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:134 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:133 +0x1fe

goroutine 1378 [select]:
github.com/ipfs/go-bitswap/internal/decision.(*Engine).nextEnvelope(0xc0801d1080, 0x2ee2680, 0xc000409b90, 0x1, 0x0, 0x0)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:409 +0x128
github.com/ipfs/go-bitswap/internal/decision.(*Engine).taskWorker(0xc0801d1080, 0x2ee2680, 0xc000409b90)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:381 +0x1be
github.com/ipfs/go-bitswap/internal/decision.(*Engine).StartWorkers.func1(0x2efa580, 0xc0836b9f80)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/engine.go:221 +0x3c
github.com/jbenet/goprocess.(*process).Go.func1(0xc0830556a0, 0xc0836b9f80, 0xc083810000)
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:134 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:133 +0x1fe

goroutine 1379 [chan receive]:
github.com/ipfs/go-bitswap.New.func6(0x2efa580, 0xc083037080, 0xc0126fa400, 0xc0830532e0, 0x2ed5f80, 0xc000409dd0)
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/bitswap.go:199 +0x48
created by github.com/ipfs/go-bitswap.New
	/home/miner/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/bitswap.go:198 +0xe35

goroutine 1380 [select]:
github.com/jbenet/goprocess/context.CloseAfterContext.func1(0x2ee2680, 0xc000409b90, 0x2efa580, 0xc083037080)
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/context/context.go:65 +0xda
created by github.com/jbenet/goprocess/context.CloseAfterContext
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/context/context.go:64 +0xba

goroutine 1381 [select]:
github.com/libp2p/go-libp2p-pubsub.(*Subscription).Next(0xc01c3ad2c0, 0x2ee25c0, 0xc01c3ad280, 0x0, 0x0, 0x0)
	/home/miner/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.3.6-0.20200910093904-f7f33e10cc18/subscription.go:24 +0xe5
github.com/filecoin-project/lotus/chain/sub.HandleIncomingBlocks(0x2ee25c0, 0xc01c3ad280, 0xc01c3ad2c0, 0xc0004f8f70, 0x2ef6120, 0xc0836fade0, 0x2efa680, 0xc00038ad00)
	/app/ipfs/lotus/chain/sub/incoming.go:49 +0x5a
created by github.com/filecoin-project/lotus/node/modules.HandleIncomingBlocks
	/app/ipfs/lotus/node/modules/services.go:100 +0x39d

goroutine 1382 [chan receive]:
github.com/whyrusleeping/pubsub.(*PubSub).start(0xc083053f20)
	/home/miner/go/pkg/mod/github.com/whyrusleeping/pubsub@v0.0.0-20131020042734-02de8aa2db3d/pubsub.go:106 +0x1c5
created by github.com/whyrusleeping/pubsub.New
	/home/miner/go/pkg/mod/github.com/whyrusleeping/pubsub@v0.0.0-20131020042734-02de8aa2db3d/pubsub.go:42 +0x95

goroutine 1385 [select]:
github.com/ipfs/go-datastore/query.(*resultsIter).useLegacyResults.func1(0x2efa580, 0xc0838106c0)
	/home/miner/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/query/query.go:415 +0x21c
github.com/jbenet/goprocess.(*process).Go.func1(0xc083055b00, 0xc0838106c0, 0xc083810720)
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:134 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:133 +0x1fe

goroutine 1386 [chan receive]:
github.com/jbenet/goprocess.(*process).CloseAfterChildren(0xc083810660, 0xc0838106c0, 0x0)
	/home/miner/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:294 +0xd9
created by github.com/ipfs/go-datastore/query.(*resultsIter).useLegacyResults
	/home/miner/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/query/query.go:423 +0x12b

rax    0x71a30865124a21b3
rbx    0x2f40fe0
rcx    0x2f41200
rdx    0xf4df1f341c341746
rdi    0xae0bbd3a76f8d6d0
rsi    0x7f7c8334d8d0
rbp    0x91b650aac27d46e
rsp    0x7f7c8334d8d0
r8     0x89f3fffcfffcfffd
r9     0x209ebfba660035e6
r10    0x71a30865124a21b3
r11    0x992103faa42b7ad5
r12    0x992103faa42b7ad5
r13    0x2f40fe0
r14    0x3c6b830cf1ba907d
r15    0x209ebfba660035e6
rip    0x1817361
rflags 0x10286
cs     0x33
fs     0x0
gs     0x0

1. Run 'lotus daemon'
2. See error

run the node normally.

I juest upgraded the lotus code from github

lotus version 0.7.0+git.c66ebc50

I installed my GPU driver and reboot my computer before that,  my GPU infomation is:  NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0 

anyone can tell me  why?   thank you very much!

**Comment by jennijuju** [comment]
Another one 
When I build a new node I run the lotus daemon, I got the below error😂, do any body have a solution? ❤️
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x683aa0]

goroutine 103889 [running]:
math/big.(*Int).Add(0xc07eb44500, 0xc07eb443a0, 0x0, 0xc0880e4b30)
  /usr/local/go/src/math/big/int.go:118 +0x40
github.com/filecoin-project/go-state-types/big.Add(0xc07eb443a0, 0x0, 0xc07d9ab890)
  /root/go/pkg/mod/github.com/filecoin-project/go-state-types@v0.0.0-20200911004822-964d6c679cfc/big/int.go:86 +0x67
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).ApplyBlocks(0xc01c7e4600, 0x2ed2220, 0xc04a2381b0, 0x30b7, 0xc069eb8ba0, 0x26, 0xc034864900, 0x6, 0x8, 0x30b8, ...)
  /root/fc/lotus/chain/stmgr/stmgr.go:236 +0x168a
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).computeTipSetState(0xc01c7e4600, 0x2ed2220, 0xc04a2381b0, 0xc07b8c99c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /root/fc/lotus/chain/stmgr/stmgr.go:353 +0x638
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).TipSetState(0xc01c7e4600, 0x2ed2220, 0xc052401d40, 0xc07b8c99c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /root/fc/lotus/chain/stmgr/stmgr.go:118 +0x6ec
github.com/filecoin-project/lotus/chain.(*Syncer).checkBlockMessages(0xc01f1f84e0, 0x2ed2220, 0xc033cadc80, 0xc0952a4b40, 0xc07b8c99c0, 0x588926, 0xc03ca055a9)
  /root/fc/lotus/chain/sync.go:1049 +0x516
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func3(0xc03ca055cc, 0x1)
  /root/fc/lotus/chain/sync.go:757 +0x55
github.com/Gurpartap/async.Err.func1(0xc07604c120, 0xc08193e720, 0xc091b47db0)
  /root/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:29 +0x53
created by github.com/Gurpartap/async.Err
  /root/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:27 +0x8a

**Comment by aphelionz** [comment]
I'm getting the same problem, a `SIGILL` from the docker container. Both locally and in CI

```
lotus_1_2fed7b5c8ee7 | SIGILL: illegal instruction
lotus_1_2fed7b5c8ee7 | PC=0x1700197 m=0 sigcode=2
lotus_1_2fed7b5c8ee7 | 
lotus_1_2fed7b5c8ee7 | goroutine 0 [idle]:
lotus_1_2fed7b5c8ee7 | runtime: unknown pc 0x1700197
lotus_1_2fed7b5c8ee7 | stack: frame={sp:0x7ffc5d7959b8, fp:0x0} stack=[0x7ffc5cf96c28,0x7ffc5d795c60)
lotus_1_2fed7b5c8ee7 | 00007ffc5d7958b8:  00000000016eabb9 <main.main+713>  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d7958c8:  0000000000000000  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d7958d8:  0000000000000000  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d7958e8:  0000000000000000  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d7958f8:  0000000000000000  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d795908:  0000000000000000  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d795918:  0000000000000000  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d795928:  0000000000000000  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d795938:  0000000000000000  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d795948:  0000000000000000  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d795958:  0000000000000000  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d795968:  0000000000000000  0000000000000000 
lotus_1_2fed7b5c8ee7 | 00007ffc5d795978:  0000000000000000  00007ffc5d795a30 
lotus_1_2fed7b5c8ee7 | 00007ffc5d795988:  00007ffc5d795ae0  00007ffc5d795b20 
lotus_1_2fed7b5c8ee7 | 00007ffc5d795998:  00007ffc5d795a30  0000000000000318 
lotus_1_2fed7b5c8ee7 | 00007ffc5d7959a8:  0000000000000002  00007ffc5d795a2d 
lotus_1_2fed7b5c8ee7 | 00007ffc5d7959b8: <00000000017000b9  00007ffc5d795ae0 
```

Heres my lscpu:

```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
Stepping:                        12
CPU MHz:                         1990.367
CPU max MHz:                     4900.0000
CPU min MHz:                     400.0000
BogoMIPS:                        4599.93
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Mitigation; TSX disabled
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acp
                                 i mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_per
                                 fmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64
                                  monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic mov
                                 be popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_
                                 fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriorit
                                 y ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx s
                                 map clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_
                                 notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
```

**Comment by yangwb** [comment]
requred https://api.drand.sh/ and https://pl-eu.incentinet.drand.sh/,  got the result: Forbidden

**Comment by yangwb** [comment]
the message "illegal instruction" after that:

2020-09-17T13:08:00.542+0800    ^[[34mINFO^[[0m p2pnode lp2p/addrs.go:114       Swarm listening at: [/ip4/127.0.0.1/tcp/36373 /ip4/192.168.1.13/tcp/36373 /ip6/::1/tcp/35729 /ip6/2408:821b:7618:480:697c:6e40:9676:d93e/tcp/35729 /ip6/2408:821b:7618:480:a0c6:e8b8:a762:b978/tcp/35729 /ip6/2408:821b:7618:480:6fc2:d575:b34:19af/tcp/35729]
2020-09-17T13:08:00.569+0800    ^[[34mINFO^[[0m drand   log/log.go:109          {"level": "info", "optimizing_client": "watching on client", "client": "HTTP(\"https://pl-eu.incentinet.drand.sh/\").(+verifier)"}
2020-09-17T13:08:00.570+0800    ^[[34mINFO^[[0m drand   log/log.go:109          {"level": "info", "optimizing_client": "watching on client", "client": "HTTP(\"https://api.drand.sh/\").(+verifier)"}
SIGILL: illegal instruction
PC=0x1817361 m=29 sigcode=2
instruction bytes: 0xc4 0x42 0xbb 0xf6 0xce 0xe8 0x35 0x0 0x0 0x0 0x4c 0x8b 0x7c 0x24 0x18 0x4c

goroutine 0 [idle]:
runtime: unknown pc 0x1817361
stack: frame={sp:0x7f89b131a8d0, fp:0x0} stack=[0x7f89b0b1aec8,0x7f89b131aac8)
00007f89b131a7d0:  000000c01e589000  000000c01e588000
00007f89b131a7e0:  000000c01e588000  000000c01e589000
00007f89b131a7f0:  000000006107b000  0000000000b23226 <github.com/ipfs/go-datastore/query.(*resultsIter).useLegacyResults.func1+166>

**Comment by yangwb** [comment]
Can not requring these two addresses is the reason?

**Comment by ryderkun** [comment]
need to use the AMD machine

**Comment by yangwb** [comment]
> need to use the AMD machine

Is this the reason?

**Comment by icodeface** [comment]
same issue, crash on intel

**Comment by icodeface** [comment]
make with `CGO_CFLAGS="-D__BLST_PORTABLE__"` works for me

**Comment by jennijuju** [comment]
related #3920

**Comment by jennijuju** [comment]
You can work around this by building lotus with
`CGO_CFLAGS="-D__BLST_PORTABLE__" make all`

Please reopen the ticket if it doesn't work for you

**Comment by aphelionz** [comment]
Will the docker container be updated with a fix?
