### ISSUE TITLE
MaxSealingSectors setting seemingly ignored

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#3896]
I've set `MaxSealingSectors = 4` (because I've queued up too many PCs and it OOMs my node). However, even like this, lotus starts all of the 7 PCs queued up. Is there a way to make it only do 3-4 concurrently without removing some of them and leaving the gap in the sector list?

**Comment by kenshyx** [comment]
This setting has effect only on `pledge` command at the moment from what I saw.

**Comment by TippyFlitsUK** [comment]
Hi @karalabe 

Thanks for the report. The issue is outdated. 

If this is a issue in the current release - please open a new ticket.

Thank you !
