### ISSUE TITLE
Hardware wallet integration

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#39]
Users should be able to use their hardware wallet to sign transactions. We should investigate how much effort it would be to add support for this directly in lotus (given some past experiments, I think its pretty straightforward).

**Comment by whyrusleeping** [comment]
We can use this: https://github.com/Zondax/ledger-filecoin-go

**Comment by magik6k** [comment]
https://github.com/filecoin-project/lotus/pull/4290
