### ISSUE TITLE
No block mined  for Raw Byte Power above 10T for 5 days

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/lotus#3902]
**Describe the bug**
We have a miner t02401 get Raw Byte Power above 10T  since September 12th, we suppose to get 1 block Mined per day, but now 5 days pass we still get 0 block Mined.

**To Reproduce**
1. Run 'lotus-miner info'
2. Miner: t02401
Sector Size: 32 GiB
Byte Power:   17.19 TiB / 240.4 PiB (0.0069%)
Actual Power: 17.2 Ti / 240 Pi (0.0069%)
	Committed: 17.22 TiB
	Proving: 17.19 TiB
**Expected block win rate: 0.9936/day (every 24h9m16s)**

but here 
https://filfox.info/en/address/t02401 Power Growth: 1.50 TiB

Daily Power Growth: 1.50 TiB / day
Miner Equivalent
tip: 10.77
**Blocks Mined tip: 0
Rewards: 0 FIL**
Rewards Ratio: 0.00%
Win Count tip: 0
Mining Efficiency: 0 FIL/TiB
Lucky Value
tip: 0.00% 

**Expected behavior**

**Version (run `lotus version`):**
Daemon:  0.7.0+git.232cc320+api0.14.0
Local: lotus version 0.7.0+git.232cc320
**Additional context**

**Comment by jennijuju** [comment]
@flyworker mentioned on [slack](https://filecoinproject.slack.com/archives/C0179RNEMU4/p1600550695287200?thread_ts=1600239857.231200&cid=C0179RNEMU4) the issue is resolved after updating to 0.7.1
