### ISSUE TITLE
lotus-miner run cannot modify the default port 2345

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#3912]
lotus-miner run --api=5432
ERROR: could not get API info: failed to parse multiaddr "5432": must begin with /

**Comment by zgfzgf** [comment]
https://github.com/filecoin-project/lotus/blob/4121063ca45cedb766c963f360522efa285bd23b/cli/cmd.go#L133
func GetAPIInfo(ctx *cli.Context, t repo.RepoType) (APIInfo, error) {
	// Check if there was a flag passed with the listen address of the API
	// server (only used by the tests)
	apiFlag := flagForAPI(t)
	if ctx.IsSet(apiFlag) {
		strma := ctx.String(apiFlag)
		strma = strings.TrimSpace(strma)

		apima, err := multiaddr.NewMultiaddr(strma)
		if err != nil {
			return APIInfo{}, err
		}
		return APIInfo{Addr: apima}, nil
	}

**Comment by rjan90** [comment]
I think this issue can be closed now, since we have the `--miner-api` flag on the newer versions of Lotus. #rengjøring
