### ISSUE TITLE
Implement mining with multiple miner instances

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#392]
Currently we handle only 1 full node - 1 miner.

**Comment by sprwig** [comment]
It would be better if you allowed multiple full nodes and multiple miners to work together. When there is a problem with a full-node sync block, you can switch to another one.

**Comment by whyrusleeping** [comment]
@sprwig Yes, we definitely plan on adding that functionality.

**Comment by sprwig** [comment]
Can I ask which time the plan will be implemented?      @whyrusleeping

**Comment by magik6k** [comment]
Done
