### ISSUE TITLE
PreCommit can't be completed because of marshal error

### ISSUE THREAD

**Issue by coder-lb** [filecoin-project/lotus#3928]
### Problems
PreCommit can't be completed because of marshal error. Then the power can't be increased as planned because of this bug. 

### Lotus Version 
0.7.1

### Call Trace

```
2020-09-19T14:15:55.041+0800    WARN    vm      vm/runtime.go:120       VM.Call failure: failed to marshal cbor object encoded bitfield was too large (32771) (RetCode=21):
    github.com/filecoin-project/lotus/chain/vm.(*Runtime).StorePut
        /home/lotus/chain/vm/runtime.go:107
2020-09-19T14:15:55.041+0800    WARN    vm      vm/vm.go:459    Send actor error        {"from": "t01095", "to": "t02614", "nonce": 665566, "method": "6", "height": "72992", "error": "failed to marshal cbor object encoded bitfield was too large (32771) (RetCode=21):\n    github.com/filecoin-project/lotus/chain/vm.(*Runtime).StorePut\n        /home/lotus/chain/vm/runtime.go:107"}
2020-09-19T14:15:55.041+0800    WARN    rpc     go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:241  error in RPC call to 'Filecoin.MpoolPushMessage': GasEstimateMessageGas error:
    github.com/filecoin-project/lotus/node/impl/full.(*MpoolAPI).MpoolPushMessage
        /home/lotus/node/impl/full/mpool.go:136
  - estimating gas used:
    github.com/filecoin-project/lotus/node/impl/full.(*GasAPI).GasEstimateMessageGas
        /home/lotus/node/impl/full/gas.go:193
  - message execution failed: exit 21, reason: failed to marshal cbor object encoded bitfield was too large (32771) (RetCode=21):
    github.com/filecoin-project/lotus/node/impl/full.(*GasAPI).GasEstimateGasLimit
        /home/lotus/node/impl/full/gas.go:165

```

**Comment by embedSky** [comment]
version 7.1 commit:4121063ca45cedb766c963f360522efa285bd23b
had the same error
```
sector 1543589 got error event sealing.SectorChainPreCommitFailed: pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 21, reason: failed to marshal cbor object encoded bitfield was too large (32772) (RetCode=21)
```

**Comment by anorth** [comment]
My first instinct here is that the [AllocatedSectors](https://github.com/filecoin-project/specs-actors/blob/b2db0eea9bec078a7eab9fe80f0d9f31b79a50e2/actors/builtin/miner/miner_state.go#L50) bitfield has grown too large due to sparsity, although I can't tell exactly which bitfield is at fault from the log.

Miners must provision sectors with reasonably dense sector numbers, to preserve on-chain state space. You should be able to pre-commit a sector with a number that is adjacent to an already-allocated number without hitting this problem. Alternatively, you can [CompactSectorNumbers](https://github.com/filecoin-project/specs-actors/blob/b2db0eea9bec078a7eab9fe80f0d9f31b79a50e2/actors/builtin/miner/miner_actor.go#L1414) to exclude a large range, but reduce the serialized size. (I am not sure whether or how Lotus makes this accessible to the operator).

**Comment by anorth** [comment]
I've looked at the state for miner `t02614` and confirmed that the AllocatedSectors bitfield (CID `bafy2bzacecod3iz77qt4qbclqoike4h2tx7kfwwwqco27tchbkqfwpn4oyqlw`) is giant.

**Comment by embedSky** [comment]
@anorth You mean the sectorNumber is too big?
if decrease the sector number maybe can resolve the problem?

**Comment by embedSky** [comment]
@anorth I had found the error is cause by [MaxEncodedSize](https://github.com/filecoin-project/go-bitfield/blob/master/bitfield.go#L22)may add the MaxEncodedSize resolve it?

**Comment by magik6k** [comment]
The bitfield size limit should be enough, it does require miners to assign sector numbers in continuous ranges, for example `[2,3,4,5,6]` will take much, much less space than `[2,4,6,8,10]`.

You can look at the bitfiled in your miner actor in more detail with `lotus-shed bitfield` tools:
```
lotus chain get bafy2bzacecod3iz77qt4qbclqoike4h2tx7kfwwwqco27tchbkqfwpn4oyqlw | xargs lotus-shed bitfield stat
Raw length: 262144 bits (32768 bytes)
Decoded length: 1600386 bits
        Ones:  359389
        Zeros: 1240997
Runs: 70575
        One Runs:  35288
        Zero Runs: 35287
Invalid runs: 0
```

Note many, many short runs:
```
./lotus chain get bafy2bzacecod3iz77qt4qbclqoike4h2tx7kfwwwqco27tchbkqfwpn4oyqlw | xargs ./lotus-shed bitfield runs
...
@905013 TRUE  * 3
@905016 FALSE * 1
@905017 TRUE  * 2
@905019 FALSE * 2
@905021 TRUE  * 7
@905028 FALSE * 1
@905029 TRUE  * 3
@905032 FALSE * 1
@905033 TRUE  * 1
@905034 FALSE * 3
@905037 TRUE  * 2
@905039 FALSE * 1
@905040 TRUE  * 14
...
```
Invoking CompactSectorNumbers anorth mentioned above is one way to fix this problem, it allows you to 'merge' those runs into a single run, but at the cost of marking those sector IDs as allocated, making it impossible to use them in the future (so you need to be very careful to not mark too much as allocated, as you technically can mark all sector IDs as allocated, which will essentially make it impossible to seal any sectors)

**Comment by embedSky** [comment]
I still don't quite understand what I should do to solve this problem, please help me

**Comment by TippyFlitsUK** [comment]
Hi @coder-lb 

Thanks for the report. The issue is outdated. 

If this is a issue in the current release - please open a new ticket.

Thank you !
