### ISSUE TITLE
Mimer call problem

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#3930]
https://github.com/filecoin-project/lotus/blob/6050401652af41a8f5e4b3505d958dc6b274c634/node/builder.go#L349
It can be understood as fx.Provide(modules.SetupBlockProducer)
https://github.com/filecoin-project/lotus/blob/6050401652af41a8f5e4b3505d958dc6b274c634/node/builder.go#L385
https://github.com/filecoin-project/lotus/blob/6050401652af41a8f5e4b3505d958dc6b274c634/node/impl/storminer.go#L51
call SetupBlockProducer here

It can be understood as ExtractApiKey call SetupBlockProducer

Best for:

  Override(new(*miner.Miner), modules.NewMiner),        // fx.Provide
  Override(BlockProducerKey, modules.BlockProducer),  // fx.Invoke

func NewMiner(ds dtypes.MetadataDS, api lapi.FullNode, epp gen.WinningPoStProver, sf *slashfilter.SlashFilter) (*miner.Miner, error) {

        minerAddr, err := minerAddrFromDS(ds)
        if err != nil {
              return nil, err
       }

        m := miner.NewMiner(api, epp, minerAddr, sf)

        return m, nil
}

func BlockProducer(lc fx.Lifecycle, m *miner.Miner)  {

        lc.Append(fx.Hook{
                OnStart: func(ctx context.Context) error {
                        if err := m.Start(ctx); err != nil {
                                return err
                        }
                        return nil
                },
                OnStop: func(ctx context.Context) error {
                        return m.Stop(ctx)
                },
        })
}

**Comment by TippyFlitsUK** [comment]
Resolved in #3943
