### ISSUE TITLE
ERROR rpc	go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/websocket.go:121	handle me:write tcp xx.xx.xx.xx:2345->xx.xx.xx.xx:36640: i/o timeout still not fixed

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/lotus#3932]
**Describe the bug**
ERROR rpc	go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/websocket.go:121	handle me:write tcp xx.xx.xx.xx:2345->xx.xx.xx.xx:36640: i/o timeout still not fixed

**To Reproduce**
1. Run 'Lotus-worker'
2. See error

**Expected behavior**
Retry the transaction.

**Version (run `lotus version`):**
V0.7.1

**Additional context**
The worker dies after this error message.

**Comment by jennijuju** [comment]
duplicated #3585
