### ISSUE TITLE
Feature request: pad sector ids on disk

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#3934]
Currently the sector storage is `<minerid>-<sectorid>`. However since sector ids are just sequential numbers, they will get a weird alphabetical sort order on directory listing. Would it be possible to pad them to say 8 characters, so sector `12` would become `00000012`?

**Comment by Reiers** [comment]
Hi

Thanks for the report. The issue is outdated, and not that relevant anymore.
Sectors are spread out over different storage servers anyway.

`lotus-miner storage find <sectornumb>
`
and you will find exactly where the sector is. 

Thank you for the feature request !
