### ISSUE TITLE
Fix GetSectorsForWinningPoSt

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#3935]
As currently implemented in `stmgr/utils.go`, this is incorrect. It will need to be fixed in an upgrade:

```
 // TODO: This is wrong, as it can contain faaults, change to just ActiveSectors in an upgrade
```

**Comment by Reiers** [comment]
Hi @arajasek 

This looks like a reminder. But Im reluctant to just close it because of the tags. 
Should I triage it again, or is this something we can close? Thank you.
