### ISSUE TITLE
ulimit error

### ISSUE THREAD

**Issue by abnernat** [filecoin-project/lotus#3937]
**Describe the bug**
Lotus daemon stop after trying to start.

**To Reproduce**
1. build from source on an 2014-mid MacBook Pro. OS Version 10.15.6. Go version 1.15.2
2. sudo make install
3. command "lotus daemon"

**Expected behavior**
Daemon start instantly.

**Screenshots**
Nuh.

**Version (run `lotus version`):**
Can't start the daemon. Can't print the version.

**Additional context**
The first error log is: 
2020-09-21T22:47:03.358+0800	ERROR	main	lotus/daemon.go:138	setting file descriptor limit: error setting: ulimit: invalid argument

**Comment by jennijuju** [comment]
@abnernat  have your tried to manually set it? something like maybe `ulimit -n 1048576`

**Comment by abnernat** [comment]
> @abnernat have your tried to manually set it? something like maybe `ulimit -n 1048576`

The max up limit is 10240. But it seems not enough. It's quite complicated to manually set the max limit.

**Comment by jennijuju** [comment]
> > @abnernat have your tried to manually set it? something like maybe `ulimit -n 1048576`
> 
> The max up limit is 10240. But it seems not enough. It's quite complicated to manually set the max limit.

Interesting. Is your lotus version 0.7.1^? Cuz I have a mid-2014 MBP too and I just tested it out it can be run fine.

**Comment by abnernat** [comment]
> > > @abnernat have your tried to manually set it? something like maybe `ulimit -n 1048576`
> > 
> > 
> > The max up limit is 10240. But it seems not enough. It's quite complicated to manually set the max limit.
> 
> Interesting. Is your lotus version 0.7.1^? Cuz I have a mid-2014 MBP too and I just tested it out it can be run fine.

IDK really, `lotus version` command seem to connect to a running daemon. I clone directly from master branch. I'll try the 0.7.1 branch later.

**Comment by abnernat** [comment]
> > > @abnernat have your tried to manually set it? something like maybe `ulimit -n 1048576`
> > 
> > 
> > The max up limit is 10240. But it seems not enough. It's quite complicated to manually set the max limit.
> 
> Interesting. Is your lotus version 0.7.1^? Cuz I have a mid-2014 MBP too and I just tested it out it can be run fine.

It is. I thought it might because some build related issue because I built from source. But the error still appears after I switch to the release binary. 

I think this might be cause by this ulimit issue, but after I change the max number of the parameter in `daemon.go` file, the error go but it still crashes. 

I'll try tomorrow on my 2018 mbp to see if it's a hardware specific problem.

**Comment by jennijuju** [comment]
> > > > @abnernat have your tried to manually set it? something like maybe `ulimit -n 1048576`
> > > 
> > > 
> > > The max up limit is 10240. But it seems not enough. It's quite complicated to manually set the max limit.
> > 
> > 
> > Interesting. Is your lotus version 0.7.1^? Cuz I have a mid-2014 MBP too and I just tested it out it can be run fine.
> 
> It is. I thought it might because some build related issue because I built from source. But the error still appears after I switch to the release binary.
> 
> I think this might be cause by this ulimit issue, but after I change the max number of the parameter in `daemon.go` file, the error go but it still crashes.
> 
> I'll try tomorrow on my 2018 mbp to see if it's a hardware specific problem.

Was it crushing due to SIGILL like #3891 ? cuz I had that too, and t he proposed work around in that ticket worked for me.

**Comment by abnernat** [comment]
Thank you! I'll try later. This might be the answer.

**Comment by abnernat** [comment]
It works!

**Comment by jennijuju** [comment]
> It works!

yeah! Thanks for report back
