### ISSUE TITLE
lotus daemon crash...

### ISSUE THREAD

**Issue by dayou5168** [filecoin-project/lotus#3938]
**Describe the bug**
Use the master branch. compile the lotus. then run lotus daemon in the comand line.
it's crash immediately .

**To Reproduce**
1. Run ' lotus daemon'
2. See error
SIGILL: illegal instruction
PC=0x1817b21 m=22 sigcode=2
instruction bytes: 0xc4 0x42 0xbb 0xf6 0xce 0xe8 0x35 0x0 0x0 0x0 0x4c 0x8b 0x7c 0x24 0x18 0x4c
goroutine 0 [idle]:
runtime: unknown pc 0x1817b21
stack: frame={sp:0x7f56df7fd8d0, fp:0x0} stack=[0x7f56deffdec8,0x7f56df7fdac8)

**Expected behavior**
lotus deamon run. and become sync the block

**Screenshots**
no

**Version (run `lotus version`):**
v0.7.1
**Additional context**
os: ubuntu18.04 cpu:Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz

**Comment by jennijuju** [comment]
duplicated with #3891 , #3920 
See suggested solution [here](https://github.com/filecoin-project/lotus/issues/3891#issuecomment-694954712)
