### ISSUE TITLE
Cannot easily download proof parameters in china

### ISSUE THREAD

**Issue by IPFS-grandhelmsman** [filecoin-project/lotus#394]
Can paramcache be provided? It is difficult to generate this in China.

![image](https://user-images.githubusercontent.com/53922818/66982345-6e975080-f0e8-11e9-81fc-b58214661496.png)

**Comment by whyrusleeping** [comment]
No. parameters cannot be generated, they must be downloaded. What is a good service to use to download files in China? We can try to mirror them somewhere that is more accessible to you

**Comment by IPFS-grandhelmsman** [comment]
China's domestic Internet policy requires data to be stored in China, and downloading it won't be a problem. In the test stage, we can solve it by ourselves, but if the commercial part is unapproved, even the mirror image of China may be related to the risk of suspension.

If it is a download package, it can be put on github like go-filecoin binary at present. Github is 
 available in China, and there are also relevant CDN. But in the end I think it would be more reliable to provide paramcache in locally.

**Comment by whyrusleeping** [comment]
Github doesnt let you upload files over 1Gb, so that’s not exactly an option, and like i said before, the parameters cannot be generated, so paramcache is not an option. Can you
Recommend a chinese hosting service?

We can also use ipfs to fetch the parameters, but then people have to download ipfs, which may also be blocked in China.

**Comment by ridewindx** [comment]
@whyrusleeping Why the parameters can not be generated?

**Comment by whyrusleeping** [comment]
Because the randomness used to generate the parameters can be used to fake proofs, so if you could generate them yourselves, you could make fake proofs.

**Comment by IPFS-grandhelmsman** [comment]
@whyrusleeping 

Hosting service you can use [Aliyun](https://account.alibabacloud.com/login/login.htm?spm=5176.12901015.ahjq0uaqt.exp-location-1.4edb525cy1sBjV) or [Tencent cloud](https://intl.cloud.tencent.com/login?s_url=https%3A%2F%2Fintl.cloud.tencent.com%2F), file service can use [Qiniu cloud](https://www.qiniu.com/en), or [Amazonaws](https://amazonaws-china.com/free/?nc1=h_ls&all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc)，but I had no experience with Amazonaws in China. 

But I think this is only a temporary solution. If you ultimately want to provide influential services in China, I think it is better for you to launch a commercial server approved in China or seek local partners to obtain stable services, or you can first try to build related hosting service for testing.

Now I use the server in Hong Kong to generate, and then copy back, but the server in Hong Kong is not very stable to provide services in mainland China.

**Comment by BEIDAHUANG** [comment]
将源码中的下载地址（`/usr/local/src/lotus/build/paramfetch.go`文件中的`const gateway` ）改为本机的ipfs网关地址，然后重新编译可以解决这个问题，前提是本机已安装运行ipfs节点。

**Comment by magik6k** [comment]
cc @travisperson

**Comment by travisperson** [comment]
We are working on providing a way to download params from servers within China. As mentioned by @BEIDAHUANG you can also change the gateway used, though you don't have to recompile. You can use the environment variable `IPFS_GATEWAY` to set the http gateway. If you are running a local IPFS node:

```
IPFS_GATEWAY=http://localhost:8080 lotus fetch-params
```

**Comment by magik6k** [comment]
We now host the parameters in JDCloud - https://s3.cn-south-1.jdcloud-oss.com/proof-parameters/filecoin-proof-parameters-v20.tar.gz - you'll want to unpack them in `/var/tmp/filecoin-proof-parameters`

**Comment by sniperpr** [comment]
> We now host the parameters in JDCloud - https://s3.cn-south-1.jdcloud-oss.com/proof-parameters/filecoin-proof-parameters-v20.tar.gz - you'll want to unpack them in `/var/tmp/filecoin-proof-parameters`

md5 is what?  Thanks a lot.
