### ISSUE TITLE
about normal shutdown of state machine？

### ISSUE THREAD

**Issue by alison-man** [filecoin-project/lotus#3956]
how can i remove or updatre-state these error state sectors ？
![image](https://user-images.githubusercontent.com/39581688/93893953-c854c180-fd20-11ea-881f-ca13f864a656.png)
![image](https://user-images.githubusercontent.com/39581688/93895550-87f64300-fd22-11ea-999f-db8166414b31.png)

**Comment by alison-man** [comment]
![Uploading image.png…]()

**Comment by Reiers** [comment]
Hi @alison-man 

Just edit it back to a correct state:
`lotus-miner sectors update-state --really-do-it <sectornumb> <correctstate>`

Closing Lotus issue ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)
