### ISSUE TITLE
[Client] Set StartDealEpoch correctly base on miner's configuration

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#3958]
Currently, if when starting a deal the _DealStartEpoch_ isn't set, by default Lotus sets a 24hs deadline to let the deal be active on-chain.

Depending on how full is the miner's pending-deals queue, it might:
- Accept the deal, but fail to seal in time thus wasting time/resources
- Reject the deal.

From the client side, if I'd like to configure _DealStartEpoch_  with the correct value, I should be able to have the information about the minimum _DealStartEpoch_ that the miner can accept, since that depends on how full his/her queue is. As a workaround, the client can set a "high" value but that will affect miners payments.

A possible idea is including this information in the `QueryAsk` response.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
