### ISSUE TITLE
[Feature Request ] Allow user to specify pledge sector number.

### ISSUE THREAD

**Issue by TippyFlitsUK** [filecoin-project/lotus#3960]
It would be a very useful feature if the user was able to specify the the number of the sector that they wish to pledge. For example:

`lotus-miner sectors pledge 25`

**Comment by jennijuju** [comment]
@yablu Why is it helpful? what's the use case?

**Comment by yablu** [comment]
Primarily for fixing faults. When sealed sectors are lost due to storage failures etc. the user could reduce fault counts by essentially re-pledging the faulted sector.

**Comment by rjan90** [comment]
Hey!

Closing this issue as I think we have landed on that this is easier to script on the Storage Provider side, then to bring in as a feature of Lotus itself.
