### ISSUE TITLE
Storage Market: Edge cases that cause deal completion on restarts to fail

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#3966]
As discussed with @hannahhoward , once https://github.com/filecoin-project/go-fil-markets/pull/407 goes in, we still have the following edge cases (documented in `TestRestartClient`) that can cause deal completion to fail in the storage markets.

----

Client restarts in the `StorageDealTransferring` state but the Provider data transfer channel has already completed.

**Sequence**

* Both Client and Provider start/accept the data transfer and client moves to `StorageDealTransferring` state.
* Provider receives all the data, sends a `Complete` response to the Client and the provider channel enters the `Completed` state.
* Client crashes before seeing the `Complete` from the Provider.
* Client restarts and sends a `Restart` message to the Provider channel but since the since the Provider channel has already completed, Provider will reject the restart request.

----

Client Restarts in the `ClientEventFundsEnsured` state but the Provider has already recorded the channel in it's FSM.

**Sequence**

* Client enters the `ClientEventFundsEnsured` state and sends a  deal to the client on the `DealProtocolID` stream.
* `HandleDealStream` on the Provider begings tracking the deal in it's FSM using the proposalCid as the FSM identifier/key.
*  Client crashes before it sees the Provider's response on the `DealProtocolID` stream it opened.
* Client restarts and sends the same deal again on the `DealProtocolID` stream.
* However, since the Provider is already tracking the deal in it's FSM, the call to `provider.deals.Begin` will fail now for the same proposalCid as the FSM is not idempotent.

**Comment by ingar** [comment]
Similar to the first case above:

Provider restarts in the `StorageDealTransferring` state but the data transfer has already completed.

Sequence

Both Client and Provider start/accept the data transfer.
Provider receives all the data, sends a Complete response to the Client and the Client starts `StorageDealCheckForAcceptance`.
Provider crashes before entering `StorageDealVerifyData`
Client restarts and polls for deal acceptance, but the provider is still in the transferring state.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks :pray:
