### ISSUE TITLE
Need garbage collection on sectors that did not get deleted properly

### ISSUE THREAD

**Issue by hyunmoon** [filecoin-project/lotus#3969]
**Describe the bug**
Sectors that should have been deleted does not get deleted automatically even after restarting the worker multiple times.
This leads to reduced performance of the worker due to lack of reservable disk space.

**To Reproduce**
Remove some sectors due to various reasons such as PreCommit1Failed or something else.
Later find out some of them didn't get deleted from the actual file system.

**Expected behavior**
lotus-miner or lotus-worker should actively check the current status of the sectors it obtains and try to delete the ones that should have been deleted in the past.
A command to trigger garbage collection on the entire system would be the second best option.
Manually tracking down these ghost sectors is frustrating on a large scale setup.

**Screenshots**
![report_reserve](https://user-images.githubusercontent.com/2242149/94037242-1ee4fd00-fe00-11ea-8f23-b06121f9a917.JPG)

**Version (run `lotus version`):**
Daemon:  0.7.1+git.4121063c.dirty+api0.14.0
Local: lotus-miner version 0.7.1+git.4121063c.dirty

**Comment by RobQuistNL** [comment]
Some very easy win here would be to check if there's any (partial) sector data in any `fetching` folder, while it is already in `proving`. Its far from efficient but its a manual process I'm doing now and has very little negative impact.

**Comment by hyunmoon** [comment]
![report_2](https://user-images.githubusercontent.com/2242149/94187911-9c356e00-fee3-11ea-96b5-7166f162cd61.JPG)
About half of these files are in Proving state and I have a few dozens of servers that have this may garbage files. I can't delete all of these because some of are legit where they should be.

**Comment by hyunmoon** [comment]
@RobQuistNL Thanks for the advice rob. I just realized I have many garbage files in fetching directories.
Removing all of them gave me some space back and got stuck workers (100% full disk) going again.

**Comment by hyunmoon** [comment]
https://github.com/filecoin-project/lotus/pull/4834
