### ISSUE TITLE
Expose a way to call CompactSectorNumbers

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3973]
This is to resolve #3928 

Suggestion by @magik6k:

Implement an explicit cli call, like lotus-miner actor compact-allocated [--auto] [--really-do-it] [b64 bitfield] , with the auto mode probably just marking removed / failed sectors as allocated, as that's likely what's creating discontinuous ranges.

**Comment by embedSky** [comment]
Hi,teams When will the issue be fixed ?

**Comment by jennijuju** [comment]
> Hi,teams When will the issue be fixed ?

This is a feature to add, so relatively a lower priority rn. Or do you have any specific reason for  this to be more urgent?

**Comment by embedSky** [comment]
@jennijuju we are t02420, current raw power is 1.88P because of this problem, there have been ten days can not increase the power, so I hope you can help me solve this problem.

**Comment by frankffenn** [comment]
@embedSky how did you solve it ?
