### ISSUE TITLE
Be able to remove sectors that are in invalid state.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3982]
This is for removing the sectors caused by #3626 

Sectors that are being updated to a invalid state via `updated-state` due to a typo in the new status/mis-usage, they cannot be removed or updated to a right state (both operation lead state machine shutdown).

It will be really nice if we can have a CLI to delete the sector and its data regardless the fsm.

**Comment by jennijuju** [comment]
Note: miners can removed the data and free up the space and pledge new sectors. These sectors are not verified so doesnt really hurt.

**Comment by alison-man** [comment]
I met the same trouble, why lab do not fix it!

**Comment by hengic** [comment]
could the Filecoin team implement this feature in  the near future? I really need it to handle my invalid sectors.

**Comment by arajasek** [comment]
If we can't get a trace of how this fails, we could always re-create the problem by reverting #3881, and then investigate further

**Comment by TippyFlitsUK** [comment]
This occurred prior to the spell checking safety feature when doing `lotus-miner sectors update-state`.

As an example I have 2 sectors with a status of `SealPreCommitFailed` which I created by mistake during Space Race 1.

The sectors are terminated but when I try to remove or update the state again I receive the following messages:

```
lotus-miner sectors update-state --really-do-it 90 Removed
ERROR: normal shutdown of state machine

```
```
lotus-miner sectors remove --really-do-it 90
ERROR: normal shutdown of state machine

```
Many thanks!!

**Comment by arajasek** [comment]
Okay, so this is likely failing because a planner cannot be found for the current meaningless state we're stuck in. We can special-case to not fail for update states, and then we should be good.

**Comment by jburnett** [comment]
Another use case: Terminating sector w/o message on chain.

```json
{"level":"warn","ts":"2021-04-08T09:04:56.041-0400","logger":"sectors","caller":"storage-sealing/fsm.go:509","msg":"sector 19 got error event sealing.SectorTerminateFailed: checking precommit presence: sectorNumber is allocated, but PreCommit info wasn't found on chain"}
```
