### ISSUE TITLE
Failed to PreComit2 insufficient funds for pre-commit

### ISSUE THREAD

**Issue by creaz79** [filecoin-project/lotus#3985]
Cant precomit sectors with insufficient funds error.
`
root@Tamm:/home/sysadm/lotus# lotus-miner sectors status --log 22
SectorID:       22
Status:         PreCommitFailed
CIDcommD:       baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq
CIDcommR:       bagboea4b5abcbvn6e77mb3n2dwykgtbjhn4mnua4yscej2ffjy7izgndxmt27iz5
Ticket:         9bdd5a915f161ee2e8531b1aca6dc14764cdb95e66f3d55b43ab575591d7c45b
TicketH:        84904
Seed:
SeedH:          0
Precommit:      <nil>
Commit:         <nil>
Proof:
Deals:          [0]
Retries:        0
--------
Event Log:
0.      2020-09-23 20:02:00 +0300 MSK:  [event;sealing.SectorStartCC]   {"User":{"ID":22,"SectorType":3,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}},"DealInfo":null}]}}
1.      2020-09-23 20:02:00 +0300 MSK:  [event;sealing.SectorPacked]    {"User":{"FillerPieces":null}}
2.      2020-09-24 02:18:49 +0300 MSK:  [event;sealing.SectorPreCommit1]        {"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjEiLCJsYWJlbHMiOnsiU3RhY2tlZERyZzMyR2lCVjEiOnsibGFiZWxzIjpbeyJwYXRoIjoiL2RhdGEyL2xvdHVzLnNlYWwvY2FjaGUvcy10MDIwNjA4LTIyIiwiaWQiOiJsYXllci0xIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YTIvbG90dXMuc2VhbC9jYWNoZS9zLXQwMjA2MDgtMjIiLCJpZCI6ImxheWVyLTIiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhMi9sb3R1cy5zZWFsL2NhY2hlL3MtdDAyMDYwOC0yMiIsImlkIjoibGF5ZXItMyIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEyL2xvdHVzLnNlYWwvY2FjaGUvcy10MDIwNjA4LTIyIiwiaWQiOiJsYXllci00Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YTIvbG90dXMuc2VhbC9jYWNoZS9zLXQwMjA2MDgtMjIiLCJpZCI6ImxheWVyLTUiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhMi9sb3R1cy5zZWFsL2NhY2hlL3MtdDAyMDYwOC0yMiIsImlkIjoibGF5ZXItNiIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEyL2xvdHVzLnNlYWwvY2FjaGUvcy10MDIwNjA4LTIyIiwiaWQiOiJsYXllci03Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YTIvbG90dXMuc2VhbC9jYWNoZS9zLXQwMjA2MDgtMjIiLCJpZCI6ImxheWVyLTgiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhMi9sb3R1cy5zZWFsL2NhY2hlL3MtdDAyMDYwOC0yMiIsImlkIjoibGF5ZXItOSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEyL2xvdHVzLnNlYWwvY2FjaGUvcy10MDIwNjA4LTIyIiwiaWQiOiJsYXllci0xMCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEyL2xvdHVzLnNlYWwvY2FjaGUvcy10MDIwNjA4LTIyIiwiaWQiOiJsYXllci0xMSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N31dLCJfaCI6bnVsbH19LCJjb25maWciOnsicGF0aCI6Ii9kYXRhMi9sb3R1cy5zZWFsL2NhY2hlL3MtdDAyMDYwOC0yMiIsImlkIjoidHJlZS1kIiwic2l6ZSI6MjE0NzQ4MzY0Nywicm93c190b19kaXNjYXJkIjo3fSwiY29tbV9kIjpbNywxMjYsOTUsMjIyLDUzLDE5NywxMCwxNDcsMywxNjUsODAsOSwyMjcsNzMsMTM4LDc4LDE5MCwyMjMsMjQzLDE1Niw2NiwxODMsMTYsMTgzLDQ4LDIxNiwyMzYsMTIyLDE5OSwxNzUsMTY2LDYyXX0=","TicketValue":"m91akV8WHuLoUxsaym3BR2TNuV5m89VbQ6tXVZHXxFs=","TicketEpoch":84904}}
3.      2020-09-24 07:11:51 +0300 MSK:  [event;sealing.SectorPreCommit2]        {"User":{"Sealed":{"/":"bagboea4b5abcbvn6e77mb3n2dwykgtbjhn4mnua4yscej2ffjy7izgndxmt27iz5"},"Unsealed":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}}
4.      2020-09-24 07:11:51 +0300 MSK:  [event;sealing.SectorChainPreCommitFailed]      {"User":{}}
        pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: insufficient funds for pre-commit deposit: 299866088733790258 (RetCode=19)
5.      2020-09-24 07:12:51 +0300 MSK:  [event;sealing.SectorRetryPreCommit]    {"User":{}}
6.      2020-09-24 07:12:51 +0300 MSK:  [event;sealing.SectorChainPreCommitFailed]      {"User":{}}
        pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: insufficient funds for pre-commit deposit: 299840978839994315 (RetCode=19)
`

`
2020-09-24T10:01:23.016+0300    INFO    sectors storage-sealing/states_sealing.go:228   submitting precommit for sector 22 (deposit: 325324786294814887):
2020-09-24T10:01:23.020+0300    WARN    sectors storage-sealing/fsm.go:475      sector 22 got error event sealing.SectorChainPreCommitFailed: pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: insufficient funds for pre-commit deposit: 295738628533337674 (RetCode=19)
`

Miner: t020608
Sector Size: 32 GiB
Byte Power:   64 GiB / 307.1 PiB (0.0000%)
Actual Power: 64 Gi / 307 Pi (0.0000%)
        Committed: 64 GiB
        Proving: 64 GiB
Below minimum power threshold, no blocks will be won
Deals: 131, 1002 MiB
        Active: 0, 0 B (Verified: 0, 0 B)

Miner Balance: 0.330091673319011684 FIL
        PreCommit:   0 FIL
        Pledge:      0.662300894977245842 FIL
        Vesting:     0 FIL
        Available:   -0.332209221658234158 FIL
Worker Balance: 1.023265787193827522 FIL
Market (Escrow):  0 FIL
Market (Locked):  0 FIL

lotus version 0.7.2+git.efd2dff0.dirty

Its enough funds on worker balance, but miner didn't use it
And what is pledge balance, looks like it gives negative available miner balance.

**Comment by creaz79** [comment]
Sorry, found how to directly send funds to miner actor.

**Comment by hsjw12** [comment]
Please let me know how you found iㅅ.

**Comment by hsjw12** [comment]
Please let me know how you found it

**Comment by creaz79** [comment]
you can send directly to miner with "lotus send --from <wallet with funds> fxxxxxx <amount>"
found in docs or forums, dont remember now, it was almost month ago :)
