### ISSUE TITLE
lotus-chainwatch 不能运行

### ISSUE THREAD

**Issue by yzn5555** [filecoin-project/lotus#3989]
之前版本总会异常退出，更新版本到最新版本：v0.7.2版本，启动直接报错退出了
![image](https://user-images.githubusercontent.com/36029121/94133357-21dcfd80-fe93-11ea-9493-507d0290a3b6.png)

程序停止提示信息：
2020-09-24T17:23:10.963+0800	INFO	processor	processor/processor.go:383	Gathered Blocks to Process	{"start": "1", "end": "40"}
2020-09-24T17:23:11.373+0800	INFO	processor	processor/processor.go:136	Collected Actor Changes	{"MarketChanges": 32, "MinerChanges": 32, "RewardChanges": 32, "AccountChanges": 8, "nullRounds": 1}
panic: TODO

goroutine 335217 [running]:
github.com/filecoin-project/lotus/cmd/lotus-chainwatch/processor.(*Processor).diffMinerPartitions(0xc00053c6f0, 0x242ba80, 0xc00443de40, 0xc006950360, 0x16, 0xc006952480, 0x26, 0x0, 0xc006931e60, 0xc005aede30, ...)
	/data/lotus/cmd/lotus-chainwatch/processor/miner.go:694 +0x131
github.com/filecoin-project/lotus/cmd/lotus-chainwatch/processor.(*Processor).getMinerPartitionsDifferences.func1(0x0, 0x3b6a2002e4a07101)
	/data/lotus/cmd/lotus-chainwatch/processor/miner.go:538 +0xc5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0046caf30, 0xc0046cb080)
	/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:54 +0x66

**Comment by zgfzgf** [comment]
This program is not available now
9.18  add code 

	panic("TODO")

	// FIXME: This code doesn't work.
	// 1. We need to diff all deadlines, not just the "current" deadline.
	// 2. We need to handle the case where we _add_ a partition. (i.e.,
	// where len(newPartitions) != len(oldPartitions).

**Comment by jennijuju** [comment]
Please open a new ticket if you are running into this issue on the latest version of lotus!
