### ISSUE TITLE
handle me:write tcp io timeout

### ISSUE THREAD

**Issue by bobjiang** [filecoin-project/lotus#3990]
**Describe the bug**

There are separate workers from miner, let's say worker1 for PC1, worker2 for PC2/C.
In worker2, there are sometimes errors for io timeout.

Error log from worker as following:

```
2020-09-24T05:56:46.367Z	ERROR	rpc	go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/websocket.go:121	handle me:write tcp 192.168.200.140:3456->192.168.200.201:53768: i/o timeout
x
```

**To Reproduce**
1. Fetch error log from worker.
2. See error

**Expected behavior**
When io timeout error, the worker cannot connect to miner. 

Expectation: the worker could reconnect miner automatically after timeout.

**Screenshots**

**Version (run `lotus version`):**
v0.7.1

**Additional context**

**Comment by jennijuju** [comment]
Related + Duplicate with #3597 #3585 , and is being worked on

**Comment by BigOceanGG** [comment]
@jennijuju Has this problem been solved?
