### ISSUE TITLE
Selecting between Tipsets with equal weight

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#3992]
**Describe the bug**
In Lotus, it looks the implementation does not strictly follow the definition in [spec](https://spec.filecoin.io/#algorithms__expected_consensus__selecting-between-tipsets-with-equal-weight). It just compare the weight of two tipset, If the later one is not heavier, the system will keep the previous one. 

In go-filecoin, there is a IsHeavier function implemented to follow the spec, then, there could be different tipset is selected if two implementations working in the same network. 
Even only Lotus, the selection could be different too on different node.

**Comment by TippyFlitsUK** [comment]
Hi @steven004 

Thanks for the report. The issue is outdated. 

If this is a issue in the current release - please open a new ticket.

Thank you !
