### ISSUE TITLE
Lotus client interactive deal workflow could include verified data info

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#4001]
Along with balance update, provide a data cap update if verified deal?

cc @jnthnvctr

**Comment by jnthnvctr** [comment]
Yeah - I think if you pass in the verified deal flag, you'd expect to see: 
- Starting verified data cap
- Expected data cap expense 
- (maybe would be nice to also ahve then) - end state if deal proceeds (Starting data cap minus expense)

**Comment by TippyFlitsUK** [comment]
Hi @arajasek 

This looks like a reminder. Should we close it or keep it open?
