### ISSUE TITLE
Support deterministic auth token

### ISSUE THREAD

**Issue by roynalnaruto** [filecoin-project/lotus#4006]
This issue is a feature request for supporting deterministic auth tokens.

### Present Setting
Lotus daemon creates a random auth token with `admin` privilege and writes it into `${LOTUS_PATH}/token`. An auth token (with at least a `sign` privilege) is required for pushing a message to Lotus' mempool. In a test environment, especially an automated environment (eg. continuous integration), it would be very convenient for the tests to know the auth token.

Every fresh boot of `lotus daemon` assigns a randomly created auth token, hence it becomes very difficult to run the tests in an automated environment. Additionally, the following command:
lotus auth create-token --perm sign
does not allow to specify a token value, or a seed value to generate a deterministic token.

Simply overwriting the `~/.lotus/token` contents throws an invalid HMAC leading to a handshake error.

In the present setting, the only way to initialise a lotus client with an auth token, is for us to query lotus (from our code/tests) and fetch the auth token:
lotus auth api-info --perm sign
which is extremely inconvenient, especially when we run lotus within a containerised environment.

In addition, we would like to run and maintain lotus nodes for testnet as well as mainnet (in the near future). Frequent restart of lotus daemon and scheduled maintenance/upgrade of the nodes from time to time make it tough for us to configure the appropriate auth token in our services.

We also use our Lotus node to provide Filecoin API access to a wide range of nodes not necessarily owned by us. It is not feasible to distribute new tokens to them at any kind of frequent interval, so it is important that we can configure the token to be something known in advance.

### Request
Allow passing in an optional argument `--auth-seed` to the `lotus daemon` command. This would create a deterministic auth token (preferably for the `admin` privilege) when the argument is present.

The same argument can also be added to `lotus auth create-token` API.

This would make it very convenient for us to configure our test environments as well as staging/production services.

**Comment by travisperson** [comment]
Is the crux of your issue that the jwt token is generated when the daemon runs and not prior? If you were able to provide a jwt secret to the daemon at startup would that resolve this issue?

The lotus shed tool can generate jwt secrets as well as sign token with any permissions you want. Importing them is a little involved but we can add additional tooling to make that easier.

-----------------
**For example**

You can create a jwt secret and the AllPermissions token using lotus shed.

```shell
name="node"
$ lotus-shed jwt new $name
```

This results in two files

1. `jwt-$name.jwts` - the contents of this file is a base16 encoded json structure which lotus uses to encode all of the keystore files.
2. `jwt-$name.token` - the contents of this file are the jwt token, no additional encoding is done

You can also create additional tokens with any permissions you need.

```
name="node"
$ lotus-shed jwt token --output jwt-sign-only-$name.token --sign jwt-$name.jwts
```

As I mentioned previously, importing the jwt secret is a bit involved, but we can create additional tooling. Basically it just involves creating the keystore directory and placing files inside of it.

To start you must be able to modify the $LOTUS_PATH contents as we need to make a `keystore` directory with the correct permissions.

```
$ mkdir $LOTUS_PATH/keystore
$ chmod 0600 $LOTUS_PATH/keystore
```

To import the jwt secret we need to properly encoded the keyname, and decode the contents for the jwts file.

```
$ name=$(echo 'auth-jwt-private' | lotus-shed base32)
$ touch $LOTUS_PATH/keystore/$name
$ lotus-shed base16 -decode < jwts-$name.jwts > $LOTUS_PATH/keystore/$name
$ chmod 0600 $LOTUS_PATH/keystore/$name
$ cp jwt-$name.token $LOTUS_PATH/token
```

**Comment by travisperson** [comment]
The one limitation of this approach is that you must be able to modify the lotus repository prior to the container starting. This generally means that you must be able to create a volume and mount it into your container. If this alone is a limitation we can probably find a solution to help with this. that is more aligned with your proposal, but wanted to see if the above would help.

**Comment by roynalnaruto** [comment]
@travisperson Thanks a lot for the detailed instructions you've provided. I will try this out and get back to you this week!
