### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by zhp1254** [filecoin-project/lotus#4008]
Describe the bug
runtime panic

To Reproduce

Run 'lotus daemon'
See error

free -h
![image](https://user-images.githubusercontent.com/18046237/94220282-39f85f80-ff1b-11ea-91a5-2f3c15319c20.png)

version  lotus version 0.7.1+git.4121063.dirty

`fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x2ae745a, 0x16)
        /root/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc36c000000, 0xc000000, 0x55fded8)
        /root/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x55e6980, 0x8400000, 0x55e6988, 0x4118)
        /root/go/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x55e6980, 0x4118, 0x0)
        /root/go/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x55e6980, 0x4118, 0x550100, 0x55fdee8, 0x200000001)
        /root/go/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
        /root/go/src/runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x55e6980, 0x4118, 0x7f25212e0101, 0x542d80)
        /root/go/src/runtime/mheap.go:865 +0x81
runtime.largeAlloc(0x822fbfe, 0x570101, 0xc36898e000)
        /root/go/src/runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()
        /root/go/src/runtime/malloc.go:1047 +0x46
runtime.systemstack(0x7f2735853770)
        /root/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /root/go/src/runtime/proc.go:1041

goroutine 7515942 [running]:
runtime.systemstack_switch()
        /root/go/src/runtime/asm_amd64.s:330 fp=0xc0c13b2b38 sp=0xc0c13b2b30 pc=0x580e20
runtime.mallocgc(0x822fbfe, 0x2751760, 0xc0c13b2c01, 0xe430de)
        /root/go/src/runtime/malloc.go:1046 +0x895 fp=0xc0c13b2bd8 sp=0xc0c13b2b38 pc=0x528035
runtime.makeslice(0x2751760, 0x822fbfe, 0x822fbfe, 0xee7a2b)
        /root/go/src/runtime/slice.go:49 +0x6c fp=0xc0c13b2c08 sp=0xc0c13b2bd8 pc=0x567d3c
bytes.makeSlice(0x822fbfe, 0x0, 0x0, 0x0)
        /root/go/src/bytes/buffer.go:229 +0x73 fp=0xc0c13b2c48 sp=0xc0c13b2c08 pc=0x626893
bytes.(*Buffer).grow(0xc174ee6e10, 0x219fe2, 0xc16146e220)
                                                          `

**Comment by zhp1254** [comment]
when restart  `lotus daemon` ,  free ram run up but  available is enough
free -h
![image](https://user-images.githubusercontent.com/18046237/94222459-f9e7ab80-ff1f-11ea-9f2e-35af34b3487c.png)

**Comment by rjan90** [comment]
I think the OOM-issues on newer versions of Lotus has been reduced. Are you still seeing experiencing this? #rengjøring
