### ISSUE TITLE
DevNet 6 Planning

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#401]
The next devnet will run some slightly tweaked parameters to start testing out different aspects of the codebase. The following changes should be implemented:

- New proofs code updated
- storage miners sector size selection
- block time to 15 seconds
- EC 'e' parameter set to 2

**Comment by deltazxm** [comment]
Is the new proofs mean use stacked drg?What is the largest sector size that storage miners can selection?1GB?

**Comment by whyrusleeping** [comment]
Yeah, it should mean switching to SDR, we will likely support a maximum of 1GB sectors for DN6, considering 8GB, but not sure if that will be worth the effort to get it in in the next few days
