### ISSUE TITLE
The scheduler is omitting old sectors

### ISSUE THREAD

**Issue by hyunmoon** [filecoin-project/lotus#4012]
**Describe the bug**
Some sectors have been stuck in PreCommit1 state for a few days but they're not getting picked up by the scheduler.
The workers just keep holding unsealed sectors and don't process them while they can.
Some of my workers have up to 45 unsealed sectors that are sitting idle.
The workers with such sectors keep degrading in performance as they run out of disk space.
Some workers keep taking tasks and end up with 100% full disk while other workers are available.

**To Reproduce**
- Have about 45 workers dedicated for PreCommit1 (1TB RAM on each)
- Pledge every minute.
- After a few days, notice lots of these 'spilled' sectors that did not get processed in time.
- These sectors are just sitting at the workers, taking up the disk space, and not going forward until both the worker and the miner get restarted.

**Expected behavior**
- The scheduler should not be omitting sectors. It should actively discover sectors in the workers and try to process them periodically.
- The scheduler should not keep giving tasks to the same worker. Even distribution is the keyword.
- If a worker got too many sectors somehow, the scheduler should re-assign them to balance it out.

**Screenshots**

Spreadsheet showing unsealed sectors each worker has.
![unsealed_report_1](https://user-images.githubusercontent.com/2242149/94251478-8b294300-ff5d-11ea-87a4-f2903b8985c3.JPG)

My attempt to re-balance these sectors manually (colored cells were transferred from other workers that had too many).
![unsealed_report_2](https://user-images.githubusercontent.com/2242149/94264652-04cb2c00-ff72-11ea-955b-fcce0aab60e8.JPG)

**Version (run `lotus version`):**
Daemon:  0.7.1+git.4121063c.dirty+api0.14.0
Local: lotus-miner version 0.7.1+git.4121063c.dirty

**Additional context**
Possibly related to:
https://github.com/filecoin-project/lotus/issues/3969

**Comment by ericnjin** [comment]
Same to me.. pls refer to the below


**[ lotus version ]**
Daemon:  0.7.1+git.4121063c+api0.15.0
Local: lotus version 0.7.1+git.4121063c



**[H/W SPEC]**
one miner server1(AMD Ryzen Threadripper 3990X 64-Core Processor , 256G MEM,  3TB NVMe)   
+  one sealing worker ( Intel(R) Core(TM) i7-10700, 128G MEM,  2TB NVMe)


**lns@lns-TRX40-AORUS-XTREME:~$ lotus-miner sectors list**
0: PreCommit1     sSet: YES active: NO  tktH: 71737 seedH: 74942 deals: [0]      <== this guy                                                                                                                                                        toUpgrade:false
1: PreCommit1     sSet: YES active: NO  tktH: 72235 seedH: 75453 deals: [0]       <== this guy                                                                                                                                                        toUpgrade:false
2: RecoverDealIDs sSet: NO  active: NO  tktH: 73486 seedH: 0     deals: [149339 149408 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]                                                                                                                toUpgrade:false
3: RecoverDealIDs sSet: NO  active: NO  tktH: 73633 seedH: 0     deals: [149430 149456 149478 149479 149521 149575 149579 149589 149644 149656 149685 149731 149767 149773 149797 149828 149851 149861 149889 149906 0 0 0 0 0 0 0 0 0]  toUpgrade:false
4: RecoverDealIDs sSet: NO  active: NO  tktH: 73907 seedH: 0     deals: [149946 149963 150012 150029 150091 150135 0 0 0 0 0 0 0 0 0 0]                                                                                                  toUpgrade:false
5: Removed        sSet: NO  active: NO  tktH: 74027 seedH: 0     deals: [150176 150217 150256 150296 0 0 0 0 0 0 0 0 0 0]                                                                                                                toUpgrade:false
6: Proving        sSet: YES active: YES tktH: 79200 seedH: 82396 deals: [152311 0 0 0 0 0 0 152335 152374 152402 0 0 0 0 0 0 0 0 0 0] 

**lns@lns-TRX40-AORUS-XTREME:~$lotus-miner sectors status --log 1 > aa**
1737.   2020-09-25 17:15:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1738.   2020-09-25 17:15:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1739.   2020-09-25 17:16:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1740.   2020-09-25 17:16:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1741.   2020-09-25 17:17:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1742.   2020-09-25 17:17:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1743.   2020-09-25 17:18:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1744.   2020-09-25 17:18:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1745.   2020-09-25 17:19:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1746.   2020-09-25 17:19:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1747.   2020-09-25 17:20:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1748.   2020-09-25 17:20:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1749.   2020-09-25 17:21:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1750.   2020-09-25 17:21:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1751.   2020-09-25 17:22:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
:
1737.   2020-09-25 17:15:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1738.   2020-09-25 17:15:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1739.   2020-09-25 17:16:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1740.   2020-09-25 17:16:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1741.   2020-09-25 17:17:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1742.   2020-09-25 17:17:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1743.   2020-09-25 17:18:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1744.   2020-09-25 17:18:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1745.   2020-09-25 17:19:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1746.   2020-09-25 17:19:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1747.   2020-09-25 17:20:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1748.   2020-09-25 17:20:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1749.   2020-09-25 17:21:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
1750.   2020-09-25 17:21:27 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        getting ticket failed: getting precommit info: sectorNumber is allocated, but PreCommit info wasn't found on chain
1751.   2020-09-25 17:22:27 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}


**du -h  (in sealing worker)**

453G	./DATA4/worker4/cache/s-t020904-1
453G	./DATA4/worker4/cache/s-t020904-0

**Comment by jennijuju** [comment]
related #3500

**Comment by jennijuju** [comment]
@ericnjin's issue is more related to #3751

**Comment by hyunmoon** [comment]
According to my findings so far, I suspect the followings attribute to this issue:
- Auto pledging at a fixed speed
- Some proving sectors not cleaned up from all workers
- Some partially fetched sectors in fetch directory not cleaned up

Garbage sectors reduce reserve-able disk space in workers and degrades their sealing performance (max parallel).
Now the miner is pledging faster than how fast the workers can seal as the result.
Unsealed sectors get piled up but most of them can't be sealed because there're many in the line.

If this goes on for long enough, I suspect it breaks the scheduler somehow.

**Comment by jennijuju** [comment]
Another case: 
```
lotus and lotus-miner in a mechine ,miner only does add pieces, PC1 in another mechine, PC2 C1 C2 in another mechine,   forgot to run PC1's  lotus-worker,  and got 42 sector stuck in 41 and never got picked up
```

**Comment by rjan90** [comment]
Hey!

Thanks for this report. The issue is outdated and I suspect that these issues don´t happen on newer versions of Lotus, as the scheduler has got some large improvements. If you still see this issue on newer versions of Lotus, please file a new report and we will triage it.

Thanks again.
