### ISSUE TITLE
Some sectors don't get acquired by lotus-worker at first try

### ISSUE THREAD

**Issue by hyunmoon** [filecoin-project/lotus#4016]
**Describe the bug**
I always get some sectors stuck in FinalizeSector until the miner and the worker get restarted.
It appears the scheduler was too busy and missed handling them somehow.
To get the sectors to be processed, the worker must be restarted (sometimes needs to be rebooted).

What's more problematic here is that sometimes the worker doesn't acquire every sector it has.
It takes multiple reboots to get every leftover sector acquired and processed.

**To Reproduce**
- Have some sectors stuck in FinalizeSector state.
- Notice they never get picked up by the scheduler.
- Stop pledging so the scheduler isn't busy.
- Kill lotus-worker, reboot, and restart lotus-worker.
- lotus-worker acquires lots of sectors.
- lotus-worker serves GET on the sectors, and eventually they get deleted and the sectors' status turn to Proving.
- Notice there are some caches and sealed sectors remaining on the worker.
- Check the sector numbers and notice they're currently in FinalizeSector state.
- Check the network traffic, nothing is getting transferred.
- Kill lotus-worker, and restart lotus-worker.
- Nothing is happening.
- Kill lotus-worker and reboot the server.
- Restart lotus-worker and notice the left-over sectors get acquired and processed.
- Often times, it takes multiple reboots to get all sectors get processed.

**Expected behavior**
Sectors should not be stuck in FinalizeSector state in the first place.
If they somehow got omitted, the scheduler should periodically check for sectors in the workers and try to process them.
When lotus-worker starts, it should always acquire every sector it has, not a part of it.

**Screenshots**
![finalizesector_report](https://user-images.githubusercontent.com/2242149/94256396-b6636080-ff64-11ea-93e1-2c40b40ed8da.JPG)

**Version (run `lotus version`):**
Daemon: 0.7.1+git.4121063c.dirty+api0.14.0
Local: lotus-miner version 0.7.1+git.4121063c.dirty

**Additional context**
Possibly related to:
https://github.com/filecoin-project/lotus/issues/3969
https://github.com/filecoin-project/lotus/issues/4012

**Comment by Reiers** [comment]
Hi @hyunmoon 

Thanks for the report. This issue has been resolved in a [upcoming release.](https://github.com/filecoin-project/lotus/releases/tag/v1.15.2-rc1)

Fix: https://github.com/filecoin-project/lotus/pull/8447

Closing Lotus issue ticket.
