### ISSUE TITLE
for unsafe in func (sh *scheduler) trySched() in sched.go

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4017]
https://github.com/filecoin-project/lotus/blob/e5873d5dea327cd3ecd05c8d2674895e058d570f/extern/sector-storage/sched.go#L457

    421         for sqi := 0; sqi < sh.schedQueue.Len(); sqi++ {
    422                 task := (*sh.schedQueue)[sqi]
    423                 needRes := ResourceTable[task.taskType][sh.spt]
    424 
    425                 selectedWindow := -1
    426                 for _, wnd := range acceptableWindows[task.indexHeap] {
    427                         wid := sh.openWindows[wnd].worker
    428                         wr := sh.workers[wid].info.Resources
    429 
    430                         log.Debugf("SCHED try assign sqi:%d sector %d to window %d", sqi, task.sector.Number, wnd)
    431 
    432                         // TODO: allow bigger windows
    433                         if !windows[wnd].allocated.canHandleRequest(needRes, wid, "schedAssign", wr) {
    434                                 continue
    435                         }
    436 
    437                         log.Debugf("SCHED ASSIGNED sqi:%d sector %d task %s to window %d", sqi, task.sector.Number, task.taskType, wnd)
    438 
    439                         windows[wnd].allocated.add(wr, needRes)
    440                         // TODO: We probably want to re-sort acceptableWindows here based on new
    441                         //  workerHandle.utilization + windows[wnd].allocated.utilization (workerHandle.utilization is used in all
    442                         //  task selectors, but not in the same way, so need to figure out how to do that in a non-O(n^2 way), and
    443                         //  without additional network roundtrips (O(n^2) could be avoided by turning acceptableWindows.[] into heaps))
    444 
    445                         selectedWindow = wnd
    446                         break
    447                 }
    448 
    449                 if selectedWindow < 0 {
    450                         // all windows full
    451                         continue
    452                 }
    453 
    454                 windows[selectedWindow].todo = append(windows[selectedWindow].todo, task)
    455 
    456                 sh.schedQueue.Remove(sqi)
    457                 sqi--
    458                 scheduled++
    459         }

for var sqi in for statement 
Poor code control
And it's not very readable
unsafe

**Comment by hyunmoon** [comment]
Related to trySched: [https://filecoinproject.slack.com/archives/C0179RNEMU4/p1600847614059700](url)

**Comment by hyunmoon** [comment]
Related to trySched issue: https://filecoinproject.slack.com/archives/C0179RNEMU4/p1600847614059700

**Comment by zgfzgf** [comment]
sorry, sign in error " Something went wrong and we weren’t able to send you an email. Please try again." in chinese

**Comment by hyunmoon** [comment]
@zgfzgf 
![image (5)](https://user-images.githubusercontent.com/2242149/94267845-3397d100-ff77-11ea-9d10-e87024289aeb.png)
![image (6)](https://user-images.githubusercontent.com/2242149/94267843-3266a400-ff77-11ea-87d0-c768439ff29a.png)

I get a lot of `trySched(1) req.sel.Ok` error every ~15 minutes.

**Comment by zgfzgf** [comment]
I'm going to optimize this code right now
Don't change the current logic

**Comment by zgfzgf** [comment]
now test ok 
It didn't happen what you said

**Comment by Reiers** [comment]
Hi guys

Thanks for the report. Seems like the conversation died out after the merge and now the issue is a bit outdated.

A new and improved scheduler is being tested in the [latest RC. ](https://github.com/filecoin-project/lotus/releases/tag/v1.15.2-rc1)

If this is a issue after the new improvements - please open a new ticket.

Thank you!
