### ISSUE TITLE
opptimize miner code use functions whenever possible

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4018]
https://github.com/filecoin-project/lotus/blob/e5873d5dea327cd3ecd05c8d2674895e058d570f/miner/miner.go#L293

    291                 
    292                         select {
    293                         case <-build.Clock.After(build.Clock.Until(nextRound)):
    294                         case <-m.stop:
    295                                 stopping := m.stopping
    296                                 m.stop = nil
    297                                 m.stopping = nil
    298                                 close(stopping)
    299                                 return
    300                         }
optimize code         

                        if !m.niceSleep(build.Clock.Until(nextRound)) {
                                continue minerLoop
                        }

    137 func (m *Miner) niceSleep(d time.Duration) bool {
    138         select {
    139         case <-build.Clock.After(d):
    140                 return true
    141         case <-m.stop:
    142                 log.Infow("received interrupt while trying to sleep in mining cycle")
    143                 return false
    144         }
    145 }

    155                 case <-m.stop:
    156                         stopping := m.stopping
    157                         m.stop = nil
    158                         m.stopping = nil
    159                         close(stopping)
    160                         return

**Comment by rjan90** [comment]
Hey!

Thank you so much for this ticket, but it seems like the PR for this ticket has been discussed and closed by the devs. So I´m closing the ticket now.

Thanks again !
