### ISSUE TITLE
lotus-miner sectors set-seal-delay resets the MaxSealingSectorsForDeals variable

### ISSUE THREAD

**Issue by Meatball13** [filecoin-project/lotus#4023]
**Describe the bug**
If you set a custom value for MaxSealingSectorsForDeals in the lotus-miner config.toml file and then run `lotus-miner sectors set-seal-delay <mins>` it resets the MaxSealingSectorsForDeals value to 0 (unlimitied)

**To Reproduce**
1. Edit lotus-miner config.toml to any non-zero value for MaxSealingSectorsForDeals 
2. Run `lotus-miner sectors set-seal-delay <mins>`
3. Check lotus-miner config.toml and it'll have the new WaitDealsDelay value, but the MaxSealingSectorsForDeals value will be reset to 0.

**Expected behavior**
This might be by design, but some people may want to have a set value for MaxSealingSectorsForDeals and may not want 0/Unlimited.   Either don't reset that value to 0, or create a command that let's people modify the MaxSealingSectorsForDeals (and possibly MaxWaitDealsSectors and/or MaxSealingSectors values), real time similar to the `lotus-miner sectors set-seal-delay <mins>` command

**Screenshots**

**Version (run `lotus version`):**
lotus version 0.7.1+git.4121063c
(Have noticed the same in previous versions as well)

**Additional context**

**Comment by rjan90** [comment]
Is this issue still present on newer versions of Lotus, or can this be closed now? #rengjøring

**Comment by jennijuju** [comment]
Confirmed can be closed
