### ISSUE TITLE
Optimize miner strategy for fault declaration after FIP2

### ISSUE THREAD

**Issue by irenegia** [filecoin-project/lotus#4025]
We could improve the fee reduction effort of [FIP0002](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0002.md) by adding a way for which a node chooses whether to go with `SubmitWindowedPoSt` or nothing (and miss the deadline) depending on the number of skipped faults it needs to declare if it goes with the first option. 

More precisely:

For each partition in it, if the number(*) of active sectors that would need a fault declaration (skipped faults) in `SubmitWindowedPoSt` is larger than
Recovering + [PartitionSize - (AlreadyFaulty+Recovering)]/4.51,
then do not call `SubmitWindowedPoSt` for this partition

Indeed, it is not rational to declare so many skipped faults. The miner loses less going for missing this deadline.

(*)computing the number of skipped faults could be done after having seen the challenges. In this case, for sector that are partially missing, the miner can be lucky (ie, getting challenges on the part that is not missing) and doesn't require the declaration. 

CC @nicola @lucaniz @magik6k @arajasek

**Comment by jennijuju** [comment]
No product requirement from miner POV so far - we won’t improve this but would be happy to review the pr if anyone from the community submit it.

**Comment by Reiers** [comment]
https://github.com/filecoin-project/lotus/issues/7865

**Comment by magik6k** [comment]
This is done by simply skipping faulty sectors in PoSt submission now; Faults are never declared early now, as that is never rational.
