### ISSUE TITLE
[Feature Request] make sync faster by using the lotus daemon node in the same network which is fast or using trusted high quality node

### ISSUE THREAD

**Issue by askender** [filecoin-project/lotus#4037]
Some Background info:
As talked in the thread: https://filecoinproject.slack.com/archives/C0179RNEMU4/p1600622389349900
many people are suffer from the lotus sync problem.  We know sync is improving, such as: https://github.com/filecoin-project/lotus/pull/3980
Move the raw issue:https://github.com/filecoin-project/FIPs/issues/10  to here.

Info:
Two server running lotus daemon which use same network. One is vary fast in sync.   The other one is always slow in sync.
We wish to speedup the slow one using the fast one by `add reward/score` to the trusted fast daemon manually.

Similar to `adding penalty`, maybe there will be a `adding score`:
```
INFO	pubsub	go-libp2p-pubsub@v0.3.6-0.20200910093904-f7f33e10cc18/gossipsub.go:1499	peer 16Uiu2HAmRH6MMzsPXNRWzQvFyQgV8CVe3e6hsffjNBm5FavWDhJJ 
didn’t follow up in 1 IWANT requests; adding penalty
```
expose the API of peer score will be better.

Fast sync will make the Filecoin network more stronger.  Thanks.

**Comment by jennijuju** [comment]
relevant: filecoin-project/lotus#3532

**Comment by askender** [comment]
➜  ~ cat log.lotus_0825_v800_001|grep ’sent too many dont haves’|wc -l
44371483
➜  ~ cat log.lotus_0825_v800_001|wc -l
51444254
I guess I have got DDoS,  hard to sync…    
50 peers send 36373343 msgs in 3 days,  36373343/44371483=81.97%

**another server in same network, very quick in sync:**
➜  ~ cat log.lotus_0825_v800|grep ’sent too many dont haves’|wc -l
386279
➜  ~ cat log.lotus_0825_v800|wc -l
2194152

the msgs are like this:
```
2020-09-29T22:13:54.705+0800	INFO	bs:sess	session/sessionwantsender.go:458	peer 12D3KooWMYYJjkoWdbkPCaRDgFS4mdNRcMfLvUwnVRdcgQy8RDSw sent too many dont haves, removing from session 18359
```
