### ISSUE TITLE
lotus advance-block panic

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4047]
lotus advance-block
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x178602f]

goroutine 1 [running]:
main.init.0.func1(0xc000522440, 0x0, 0x0)
	/home/zgf/work/gopath/src/github.com/filecoin-project/lotus/cmd/lotus/debug_advance.go:84 +0x9cf
github.com/urfave/cli/v2.(*Command).Run(0xc000524000, 0xc000522380, 0x0, 0x0)
	/home/zgf/work/gopath/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc000104780, 0x2f53f60, 0xc00011a000, 0xc000124020, 0x2, 0x2, 0x0, 0x0)
	/home/zgf/work/gopath/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/home/zgf/work/gopath/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc000104780)
	/home/zgf/work/gopath/src/github.com/filecoin-project/lotus/cli/helper.go:34 +0x7c
main.main()
	/home/zgf/work/gopath/src/github.com/filecoin-project/lotus/cmd/lotus/main.go:73 +0x631
### problem:
https://github.com/filecoin-project/lotus/blob/2c1d96bcaa1233d1671658250248d4524d5dfee6/chain/stmgr/utils.go#L496

**Comment by zgfzgf** [comment]
**other problem:**
ERROR: sync to submitted block failed: collectChain failed: collectChain syncMessages: message processing failed: validating block bafy2bzacedyotosplxav7ihvkzmubnagedfews2fa3hpar4lmfo2gj7bnd6my: 1 error occurred:
	* miner claims wrong number of wins: miner: 9, computed: 0:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /home/zgf/work/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:863

**Comment by rjan90** [comment]
Hi @zgfzgf!

Thanks for the report. The issue is outdated, and not relevant anymore.

If this is a issue in current release please open a new ticket.

Thanks again !
