### ISSUE TITLE
insufficient funds for pre-commit deposit

### ISSUE THREAD

**Issue by jogsunzhao** [filecoin-project/lotus#4055]
**Describe the problem**

insufficient funds for pre-commit deposit

**Sectors status**

1582.	2020-09-27 08:30:30 +0800 CST:	[event;sealing.SectorRetryPreCommit]	{"User":{}}
1583.	2020-09-27 08:30:30 +0800 CST:	[event;sealing.SectorChainPreCommitFailed]	{"User":{}}
	pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: insufficient funds for pre-commit deposit: 0 (RetCode=19)
1584.	2020-09-27 08:31:30 +0800 CST:	[event;sealing.SectorRetryPreCommit]	{"User":{}}
1585.	2020-09-27 08:31:30 +0800 CST:	[event;sealing.SectorChainPreCommitFailed]	{"User":{}}
	pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: insufficient funds for pre-commit deposit: 0 (RetCode=19)
1586.	2020-09-27 08:32:30 +0800 CST:	[event;sealing.SectorRetryPreCommit]	{"User":{}}
1587.	2020-09-27 08:32:30 +0800 CST:	[event;sealing.SectorChainPreCommitFailed]	{"User":{}}
	pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: insufficient funds for pre-commit deposit: 0 (RetCode=19)
1588.	2020-09-27 08:33:30 +0800 CST:	[event;sealing.SectorRetryPreCommit]	{"User":{}}
1589.	2020-09-27 08:33:30 +0800 CST:	[event;sealing.SectorChainPreCommitFailed]	{"User":{}}
	pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: insufficient funds for pre-commit deposit: 0 (RetCode=19)

**Lotus miner logs**

{"level":"info","ts":"2020-09-27T08:32:30.022+0800","logger":"sectors","caller":"storage-sealing/states_sealing.go:212","msg":"submitting precommit for sector 67 (deposit: 0): "}
{"level":"warn","ts":"2020-09-27T08:32:30.028+0800","logger":"sectors","caller":"storage-sealing/fsm.go:475","msg":"sector 67 got error event sealing.SectorChainPreCommitFailed: pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: insufficient funds for pre-commit deposit: 0 (RetCode=19)"}
{"level":"info","ts":"2020-09-27T08:33:30.019+0800","logger":"sectors","caller":"storage-sealing/states_sealing.go:212","msg":"submitting precommit for sector 67 (deposit: 0): "}
{"level":"warn","ts":"2020-09-27T08:33:30.024+0800","logger":"sectors","caller":"storage-sealing/fsm.go:475","msg":"sector 67 got error event sealing.SectorChainPreCommitFailed: pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: insufficient funds for pre-commit deposit: 0 (RetCode=19)"}

**Lotus miner diagnostic info**

Please collect the following diagnostic information, and share a link here

* lotus-miner diagnostic info `lotus-miner info all > allinfo`

Below minimum power threshold, no blocks will be won
Deals: 282, 4.586 GiB
	Active: 0, 0 B (Verified: 0, 0 B)

Miner Balance: 0.816550921477348094 FIL
	PreCommit:   0 FIL
	Pledge:      1.948219616420109461 FIL
	Locked:      0 FIL
	Available:   -1.131668694942761367 FIL
Worker Balance: 39.487420199820009494 FIL
Market (Escrow):  0 FIL
Market (Locked):  0 FIL

Expected Seal Duration: 16h0m0s

Sectors:
	Total: 71
	Proving: 4
	WaitDeals: 1
	PreCommit1: 3
	PreCommit2: 1
	PreCommitting: 1
	Removed: 14
	SealPreCommit1Failed: 1
	PreCommitFailed: 7
	RecoverDealIDs: 39

**Version**

Daemon:  0.7.1+git.4121063c+api0.15.0
Local: lotus version 0.7.1+git.4121063c

**Comment by jennijuju** [comment]
You have a negative miner balance, you can  transfer funds from your worker to miner using lotus send.

Also your lotus version seems not upgraded to 0.8.0 yet, you are probably on a side chain.
