### ISSUE TITLE
proposal MinerPower return

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4060]
https://github.com/filecoin-project/lotus/blob/2c1d96bcaa1233d1671658250248d4524d5dfee6/chain/actors/builtin/power/power.go#L42
more **found bool**, The code is not easy to maintain

should be:
MinerPower(address.Address) (Claim, error)

**Comment by TippyFlitsUK** [comment]
Hi @zgfzgf 

This looks like a reminder. Should we close it or keep it open?
