### ISSUE TITLE
Lotus daemon panic

### ISSUE THREAD

**Issue by RustMan88** [filecoin-project/lotus#4062]
**Describe the bug**
`6/::1/tcp/23915]
2020-09-27T10:13:07.333-0400	INFO	basichost	basic/natmgr.go:91	DiscoverNAT error:no NAT found
2020-09-27T10:13:07.817-0400	INFO	badger	v2@v2.2007.2/levels.go:1000	[Compactor: 1] Running compaction: {level:2 score:1.0250702679157258 dropPrefixes:[]} for level: 2

2020-09-27T10:13:09.234-0400	INFO	drand	log/log.go:109		{"level": "info", "optimizing_client": "watching on client", "client": "HTTP(\"https://pl-eu.incentinet.drand.sh/\").(+verifier)"}
2020-09-27T10:13:09.235-0400	INFO	drand	log/log.go:109		{"level": "info", "optimizing_client": "watching on client", "client": "HTTP(\"https://api.drand.sh/\").(+verifier)"}
SIGILL: illegal instruction
PC=0x187696e m=25 sigcode=2
instruction bytes: 0xf3 0x4c 0xf 0x38 0xf6 0xcf 0x66 0x4c 0xf 0x38 0xf6 0xd5 0xc4 0xe2 0xc3 0xf6

goroutine 0 [idle]:
runtime: unknown pc 0x187696e
stack: frame={sp:0x7f1aad7f98c8, fp:0x0} stack=[0x7f1aacff9ec8,0x7f1aad7f9ac8)
00007f1aad7f97c8:  0000000000000000  0000000000000000 
00007f1aad7f97d8:  0000000000000000  0000000000000000 
00007f1aad7f97e8:  0000000000000000  0000000000000000 
00007f1aad7f97f8:  0000000000000000  0000000000000000 
00007f1aad7f9808:  0000000000000000  00007f1aad7f98d8 
00007f1aad7f9818:  000000000056746d <runtime.(*pageAlloc).update+621>  00007f1b14b83380 
00007f1aad7f9828:  0000000000000008  0000000001fcfd90 
00007f1aad7f9838:  0000000000000009  000000000ac00000 
00007f1aad7f9848:  00007fffbab0ec30  0000000004800000 
00007f1aad7f9858:  0000000100000000  0000000000000000 
00007f1aad7f9868:  0000000000000009  0000000000000003 
00007f1aad7f9878:  0000000000000003  000000000040604e 
00007f1aad7f9888:  000000000040604f  0000000000000009 
00007f1aad7f9898:  000000000040604f  0000000000567745 <runtime.(*pageAlloc).update+1349> 
00007f1aad7f98a8:  00007f1b02704880  0000000000000000 
00007f1aad7f98b8:  0000000002030271  000080c09c700000 
00007f1aad7f98c8: <00000000018768eb  89f3fffcfffcfffd 
00007f1aad7f98d8:  b8b4dabb9a8e6c1a  0000000000567b4b <runtime.(*pageAlloc).allocRange+747> 
00007f1aad7f98e8:  00007f1aad7f9920  00007f1aad7f9950 
00007f1aad7f98f8:  0000000002f49260  0000000002f49500 
00007f1aad7f9908:  000000c000558180  0000000000000089 
00007f1aad7f9918:  000000000186b94a  d115cd17a705d28f 
00007f1aad7f9928:  8c11ea74cac2703b  c607d076cdfd0d14 
00007f1aad7f9938:  90492cbccb808236  d98a437ab5dc1204 
00007f1aad7f9948:  10c3bdc7997573bf  d115cd17a705d28f 
00007f1aad7f9958:  8c11ea74cac2703b  c607d076cdfd0d14 
00007f1aad7f9968:  90492cbccb808236  d98a437ab5dc1204 
00007f1aad7f9978:  10c3bdc7997573bf  aabd8b9a9d82b107 
00007f1aad7f9988:  745e2f73717e3f81  eedc7c993728779b 
00007f1aad7f9998:  4549a8488bb5cc5e  5bd0e49f3c3e5f1c 
00007f1aad7f99a8:  092721f9ecd1ac73  0000000000000049 
00007f1aad7f99b8:  00000000048ac220  00000000048ac220 
runtime: unknown pc 0x187696e
stack: frame={sp:0x7f1aad7f98c8, fp:0x0} stack=[0x7f1aacff9ec8,0x7f1aad7f9ac8)
00007f1aad7f97c8:  0000000000000000  0000000000000000 
00007f1aad7f97d8:  0000000000000000  0000000000000000 
00007f1aad7f97e8:  0000000000000000  0000000000000000 
00007f1aad7f97f8:  0000000000000000  0000000000000000 
00007f1aad7f9808:  0000000000000000  00007f1aad7f98d8 
00007f1aad7f9818:  000000000056746d <runtime.(*pageAlloc).update+621>  00007f1b14b83380 
00007f1aad7f9828:  0000000000000008  0000000001fcfd90 
00007f1aad7f9838:  0000000000000009  000000000ac00000 
00007f1aad7f9848:  00007fffbab0ec30  0000000004800000 
00007f1aad7f9858:  0000000100000000  0000000000000000 
00007f1aad7f9868:  0000000000000009  0000000000000003 
00007f1aad7f9878:  0000000000000003  000000000040604e 
00007f1aad7f9888:  000000000040604f  0000000000000009 
00007f1aad7f9898:  000000000040604f  0000000000567745 <runtime.(*pageAlloc).update+1349> 
00007f1aad7f98a8:  00007f1b02704880  0000000000000000 
00007f1aad7f98b8:  0000000002030271  000080c09c700000 
00007f1aad7f98c8: <00000000018768eb  89f3fffcfffcfffd 
00007f1aad7f98d8:  b8b4dabb9a8e6c1a  0000000000567b4b <runtime.(*pageAlloc).allocRange+747> 
00007f1aad7f98e8:  00007f1aad7f9920  00007f1aad7f9950 
00007f1aad7f98f8:  0000000002f49260  0000000002f49500 
00007f1aad7f9908:  000000c000558180  0000000000000089 
00007f1aad7f9918:  000000000186b94a  d115cd17a705d28f 
00007f1aad7f9928:  8c11ea74cac2703b  c607d076cdfd0d14 
00007f1aad7f9938:  90492cbccb808236  d98a437ab5dc1204 
00007f1aad7f9948:  10c3bdc7997573bf  d115cd17a705d28f 
00007f1aad7f9958:  8c11ea74cac2703b  c607d076cdfd0d14 
00007f1aad7f9968:  90492cbccb808236  d98a437ab5dc1204 
00007f1aad7f9978:  10c3bdc7997573bf  aabd8b9a9d82b107 
00007f1aad7f9988:  745e2f73717e3f81  eedc7c993728779b 
00007f1aad7f9998:  4549a8488bb5cc5e  5bd0e49f3c3e5f1c 
00007f1aad7f99a8:  092721f9ecd1ac73  0000000000000049 
00007f1aad7f99b8:  00000000048ac220  00000000048ac220 

goroutine 1 [syscall]:
runtime.cgocall(0x1862100, 0xc000905b78, 0xc0e70f0000)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000905b48 sp=0xc000905b10 pc=0x54037b
github.com/supranational/blst/bindings/go._Cfunc_blst_p2_uncompress(0xc000558180, 0xc00014a3f1, 0xc000000000)
	_cgo_gotypes.go:695 +0x4d fp=0xc000905b78 sp=0xc000905b48 pc=0x1190fcd
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).Uncompress(0xc000558180, 0xc00014a3f1, 0x60, 0x60, 0x28f42a0)
	/var/workspace/lotus/extern/fil-blst/blst/bindings/go/blst.go:1598 +0x48 fp=0xc000905ba0 sp=0xc000905b78 pc=0x11975e8
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).AggregateVerifyCompressed.func1(0x28f42a0)
	/var/workspace/lotus/extern/fil-blst/blst/bindings/go/blst.go:357 +0xc5 fp=0xc000905be8 sp=0xc000905ba0 pc=0x1199365
github.com/supranational/blst/bindings/go.coreAggregateVerifyPkInG1(0xc000905d70, 0xc00b6fc120, 0xc0006385e0, 0x1, 0x1, 0xc00b6fa330, 0x2b, 0x2b, 0xc000905d6f, 0x1, ...)
	/var/workspace/lotus/extern/fil-blst/blst/bindings/go/blst.go:461 +0x2a2 fp=0xc000905d08 sp=0xc000905be8 pc=0x11935c2
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).AggregateVerifyCompressed(0xc000905ed8, 0xc00014a3f1, 0x60, 0x60, 0xc000638540, 0x1, 0x1, 0xc0006385e0, 0x1, 0x1, ...)
	/var/workspace/lotus/extern/fil-blst/blst/bindings/go/blst.go:383 +0x1a5 fp=0xc000905da0 sp=0xc000905d08 pc=0x11932a5
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).VerifyCompressed(0xc000905ed8, 0xc00014a3f1, 0x60, 0x60, 0xc00b6fa300, 0x30, 0x30, 0xc00b6fa2d0, 0x26, 0x30, ...)
	/var/workspace/lotus/extern/fil-blst/blst/bindings/go/blst.go:296 +0x225 fp=0xc000905e40 sp=0xc000905da0 pc=0x1192d65
github.com/filecoin-project/lotus/lib/sigs/bls.blsSigner.Verify(0xc00014a3f1, 0x60, 0x60, 0xc00b6fe080, 0x31, 0xc00b6fa2d0, 0x26, 0x30, 0x0, 0xc0004fe320)
	/var/workspace/lotus/lib/sigs/bls/init.go:53 +0x1db fp=0xc000905fb0 sp=0xc000905e40 pc=0x119bdfb
github.com/filecoin-project/lotus/lib/sigs/bls.(*blsSigner).Verify(0x534d558, 0xc00014a3f1, 0x60, 0x60, 0xc00b6fe080, 0x31, 0xc00b6fa2d0, 0x26, 0x30, 0x30, ...)
	<autogenerated>:1 +0x9d fp=0xc000906010 sp=0xc000905fb0 pc=0x119c29d
github.com/filecoin-project/lotus/lib/sigs.Verify(0xc000115270, 0xc00b6fe080, 0x31, 0xc00b6fa2d0, 0x26, 0x30, 0xc00027df38, 0x1)
	/var/workspace/lotus/lib/sigs/sigs.go:48 +0xf9 fp=0xc000906088 sp=0xc000906010 pc=0xdbf239
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).VerifyMsgSig(0xc0006306e0, 0xc000115200, 0x1, 0x0)
	/var/workspace/lotus/chain/messagepool/messagepool.go:587 +0xd6 fp=0xc0009060e8 sp=0xc000906088 pc=0x1146f76
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).checkMessage(0xc0006306e0, 0xc000115200, 0xc000906228, 0xce0117)
	/var/workspace/lotus/chain/messagepool/messagepool.go:533 +0x267 fp=0xc000906198 sp=0xc0009060e8 pc=0x1146827
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).addLoaded(0xc0006306e0, 0xc000115200, 0x0, 0x0)
	/var/workspace/lotus/chain/messagepool/messagepool.go:650 +0x6d fp=0xc000906238 sp=0xc000906198 pc=0x114784d
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).loadLocal(0xc0006306e0, 0xc09ae112b0, 0xc0e6ac4d40)
	/var/workspace/lotus/chain/messagepool/messagepool.go:1302 +0x31d fp=0xc0009063d0 sp=0xc000906238 pc=0x114d5fd
github.com/filecoin-project/lotus/chain/messagepool.New(0x2efb3c0, 0xc09ae11260, 0x7f092e2650d8, 0xc0001e0c00, 0x2b541e7, 0xa, 0xc09bcdb4a0, 0x60, 0xc000906668)
	/var/workspace/lotus/chain/messagepool/messagepool.go:358 +0x7c6 fp=0xc000906578 sp=0xc0009063d0 pc=0x11451a6
github.com/filecoin-project/lotus/node/modules.MessagePool(0x2eae940, 0xc0006cb500, 0xc0f3b1a880, 0xc00be05200, 0x7f092e2650d8, 0xc0001e0c00, 0x2b541e7, 0xa, 0x0, 0x0, ...)
	/var/workspace/lotus/node/modules/chain.go:56 +0xa6 fp=0xc0009065e8 sp=0xc000906578 pc=0x17ff8e6
runtime.call128(0xc0006515f0, 0x2d07640, 0xc09bcdb4a0, 0x4000000058)
	/usr/local/go/src/runtime/asm_amd64.s:542 +0x59 fp=0xc000906678 sp=0xc0009065e8 pc=0x5ab759
reflect.Value.call(0x28c9680, 0x2d07640, 0x13, 0x2b49f1b, 0x4, 0xc000656500, 0x5, 0x5, 0x203000, 0xc01e1e6290, ...)
	/usr/local/go/src/reflect/value.go:475 +0x8c7 fp=0xc000906890 sp=0xc000906678 pc=0x600d27
reflect.Value.Call(0x28c9680, 0x2d07640, 0x13, 0xc000656500, 0x5, 0x5, 0x8, 0x10, 0xc09ae11250)
	/usr/local/go/src/reflect/value.go:336 +0xb9 fp=0xc000906910 sp=0xc000906890 pc=0x600219
github.com/filecoin-project/lotus/node.as.func2(0xc000656500, 0x5, 0x5, 0xc000656500, 0x29561a0, 0xc000906b28)
	/var/workspace/lotus/node/options.go:140 +0xf0 fp=0xc0009069e0 sp=0xc000906910 pc=0x18181d0
reflect.callReflect(0xc000651680, 0xc000906b40, 0xc000906b28)
	/usr/local/go/src/reflect/value.go:564 +0x32a fp=0xc000906b10 sp=0xc0009069e0 pc=0x601bca
reflect.makeFuncStub(0x2eae940, 0xc0006cb500, 0xc0f3b1a880, 0xc00be05200, 0x7f092e2650d8, 0xc0001e0c00, 0x2b541e7, 0xa, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/asm_amd64.s:20 +0x42 fp=0xc000906b40 sp=0xc000906b10 pc=0x60d002
runtime.call128(0xc0006515f0, 0xc000651680, 0xc09bcdb440, 0x4000000058)
	/usr/local/go/src/runtime/asm_amd64.s:542 +0x59 fp=0xc000906bd0 sp=0xc000906b40 pc=0x5ab759
reflect.Value.call(0x28c9680, 0xc000651680, 0x13, 0x2b49f1b, 0x4, 0xc000656480, 0x5, 0x5, 0x10, 0xc09ae11220, ...)
	/usr/local/go/src/reflect/value.go:475 +0x8c7 fp=0xc000906de8 sp=0xc000906bd0 pc=0x600d27
reflect.Value.Call(0x28c9680, 0xc000651680, 0x13, 0xc000656480, 0x5, 0x5, 0x294f4e0, 0x2a96101, 0xc09ae11220)
	/usr/local/go/src/reflect/value.go:336 +0xb9 fp=0xc000906e68 sp=0xc000906de8 pc=0x600219
go.uber.org/dig.defaultInvoker(0x28c9680, 0xc000651680, 0x13, 0xc000656480, 0x5, 0x5, 0xc00014c1e0, 0xc000656480, 0x5)
	/root/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:284 +0x65 fp=0xc000906ec0 sp=0xc000906e68 pc=0x115f745
go.uber.org/dig.(*node).Call(0xc0006408c0, 0x2efb960, 0xc00014c1e0, 0x2f0ce40, 0x2b22360)
	/root/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:710 +0x27b fp=0xc000907038 sp=0xc000906ec0 pc=0x1162f3b
go.uber.org/dig.paramSingle.Build(0x0, 0x0, 0x0, 0x2f0ce40, 0x2b22360, 0x2efb960, 0xc00014c1e0, 0x2b119a0, 0xc0d8ac60a8, 0x96, ...)
	/root/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:245 +0x2e2 fp=0xc000907168 sp=0xc000907038 pc=0x11696e2
go.uber.org/dig.(*paramSingle).Build(0xc09bf4d4a0, 0x2efb960, 0xc00014c1e0, 0x2b119a0, 0xc0d8ac60a8, 0x96, 0x0, 0x0)
	<autogenerated>:1 +0xa5 fp=0xc000907200 sp=0xc000907168 pc=0x1175a85
go.uber.org/dig.paramList.BuildList(0x2f0ce40, 0x28b5e80, 0xc09bcdb3e0, 0x6, 0x6, 0x2efb960, 0xc00014c1e0, 0x0, 0x0, 0x5b8a25, ...)
	/root/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:201 +0xb8 fp=0xc000907278 sp=0xc000907200 pc=0x1169198
go.uber.org/dig.(*Container).Invoke(0xc00014c1e0, 0x28b5e80, 0x2d07628, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:432 +0x2c6 fp=0xc0009073f0 sp=0xc000907278 pc=0x1160a86
go.uber.org/fx.(*App).executeInvokes(0xc0003a08f0, 0x27f44a0, 0xc0001213d0)
	/root/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:547 +0x35f fp=0xc0009074a8 sp=0xc0009073f0 pc=0x117b17f
go.uber.org/fx.New(0xc0004736b8, 0x3, 0x3, 0xc000153700)
	/root/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:345 +0x490 fp=0xc0009075b8 sp=0xc0009074a8 pc=0x1179c90
github.com/filecoin-project/lotus/node.New(0x2ee5be0, 0xc00039eed0, 0xc0006c4140, 0x8, 0x8, 0x0, 0x0, 0x0)
	/var/workspace/lotus/node/builder.go:545 +0x496 fp=0xc000907758 sp=0xc0009075b8 pc=0x18159f6
main.glob..func2(0xc0006c4000, 0x0, 0x0)
	/var/workspace/lotus/cmd/lotus/daemon.go:238 +0xea5 fp=0xc000907a10 sp=0xc000907758 pc=0x185e785
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc00058cd80, 0xc0000f4c00, 0x0, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:432 +0x9bf fp=0xc000907b48 sp=0xc000907a10 pc=0xd1b1ff
github.com/urfave/cli/v2.(*Command).startApp(0x51acd80, 0xc0000f4c00, 0x2b4cd80, 0x7fffbaaf655e)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x6bb fp=0xc000907bf0 sp=0xc000907b48 pc=0xd1df5b
github.com/urfave/cli/v2.(*Command).Run(0x51acd80, 0xc0000f4c00, 0x0, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0x9cd fp=0xc000907cd0 sp=0xc000907bf0 pc=0xd1d0cd
github.com/urfave/cli/v2.(*App).RunContext(0xc00058cc00, 0x2ee5b60, 0xc000044088, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x81f fp=0xc000907df8 sp=0xc000907cd0 pc=0xd1a23f
github.com/urfave/cli/v2.(*App).Run(...)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc00058cc00)
	/var/workspace/lotus/cli/helper.go:34 +0x7c fp=0xc000907e90 sp=0xc000907df8 pc=0x1252c1c
main.main()
	/var/workspace/lotus/cmd/lotus/main.go:73 +0x631 fp=0xc000907f88 sp=0xc000907e90 pc=0x185cd51
runtime.main()
`

**To Reproduce**
1.FFI_BUILD_FROM_SOURCE=1 RUSTFLAGS='-C target-cpu=native' make clean deps all
2. Run 'lotus daemon'
3. SIGILL: illegal instruction

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
lotus v0.8.0

**Additional context**

**Comment by Reiers** [comment]
Hi @RustMan88 

Thanks for the report. This is fixed.
Please upgrade Lotus.

*Link to latest tags [here.](https://github.com/filecoin-project/lotus/tags)*

Closing ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)
