### ISSUE TITLE
[Feature Request] Version update check before launch daemon

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4066]
I noticed that some of the miner missed 0.8.0 upgrade notice which leads to various of syncing/api issue. Most of them would try to restart their daemon when an issue occurs, so It will bel nice if we can check the lotus version after launch, then if there is a mandatory update and the version doesnt match, we kill the process and output an upgrade notification.

**Comment by arajasek** [comment]
I don't think I understand the proposal -- how would an old version of Lotus know that there was a mandatory update?

**Comment by jennijuju** [comment]
> I don't think I understand the proposal -- how would an old version of Lotus know that there was a mandatory update?

I don’t know if it’s possible or not 😢maybe impossible for the mandatory check? Tho should be feasible to detect a new version from a peer?and we can add an option for miner to decide if they want the process to be killed if a new version is detected ?
