### ISSUE TITLE
Same message with different CID on filfox and filscan

### ISSUE THREAD

**Issue by hulajesus** [filecoin-project/lotus#4073]
**Describe the bug**

I use the latest snapshot to launch a lotus node, and run chainwatch to pull data into pg.
Two different message CID with same content find on lotus

- bafy2bzaceaygblumo5vye4kjccx6cre2bifol6h6ha4oxidrx7v7d7mfuwerg (only exist in pg generate by chainwatch and filscan)
- bafy2bzacecpmy5zwseh4pbfw535f3oayb42etwqtekmymrxysf7cizfopkqfi (only exist on filfox)

but I can query both of them through rpc, and response are exactly the same

```
# curl --location --request POST 'http://localhost:1234/rpc/v0' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "Filecoin.ChainGetMessage",
    "params": [
        {
            "/": "bafy2bzacecpmy5zwseh4pbfw535f3oayb42etwqtekmymrxysf7cizfopkqfi"
        }
    ]

{
  "jsonrpc": "2.0",
  "result": {
    "Version": 0,
    "To": "t1h2o3pjc4eg2j22yectryye6qqu3thyxlkteabwq",
    "From": "t1k7yhkb42jhgrsx4nhr7rfkxfiahmkyxq5cw74ry",
    "Nonce": 27,
    "Value": "10000000000000000",
    "GasLimit": 10000000,
    "GasFeeCap": "101390",
    "GasPremium": "100336",
    "Method": 0,
    "Params": null
  },
  "id": 2
}'
```
```
# curl --location --request POST 'https://localhost:1234/rpc/v0' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "Filecoin.ChainGetMessage",
    "params": [
        {
            "/": "bafy2bzaceaygblumo5vye4kjccx6cre2bifol6h6ha4oxidrx7v7d7mfuwerg"
        }
    ]
}'

{
  "jsonrpc": "2.0",
  "result": {
    "Version": 0,
    "To": "t1h2o3pjc4eg2j22yectryye6qqu3thyxlkteabwq",
    "From": "t1k7yhkb42jhgrsx4nhr7rfkxfiahmkyxq5cw74ry",
    "Nonce": 27,
    "Value": "10000000000000000",
    "GasLimit": 10000000,
    "GasFeeCap": "101390",
    "GasPremium": "100336",
    "Method": 0,
    "Params": null
  },
  "id": 2
}
```

however different response when run lotus chain get
```
# lotus chain get --as-type=smessage bafy2bzaceaygblumo5vye4kjccx6cre2bifol6h6ha4oxidrx7v7d7mfuwerg
ERROR: failed to unmarshal as "smessage"
```
```
# lotus chain get --as-type=smessage bafy2bzacecpmy5zwseh4pbfw535f3oayb42etwqtekmymrxysf7cizfopkqfi
{
	"Message": {
		"Version": 0,
		"To": "t1h2o3pjc4eg2j22yectryye6qqu3thyxlkteabwq",
		"From": "t1k7yhkb42jhgrsx4nhr7rfkxfiahmkyxq5cw74ry",
		"Nonce": 27,
		"Value": "10000000000000000",
		"GasLimit": 10000000,
		"GasFeeCap": "101390",
		"GasPremium": "100336",
		"Method": 0,
		"Params": null
	},
	"Signature": {
		"Type": 1,
		"Data": "3hKPAZAXdtIQe9W5mk8zzX+53k5p9jb9p0dyvcYEfP9GVPaTOWZ9GRrhvaJtdXLRTZAAqIcYKNJt2BFyBIaFWAA="
	}
}
```
**To Reproduce**
Use latest snapshot to launch a lotus node and run chainwatch

**Expected behavior**
Every message has a unique CID, right?

**Screenshots**
[Filscan](https://testnet.filscan.io/#/tipset/message-detail?cid=bafy2bzaceaygblumo5vye4kjccx6cre2bifol6h6ha4oxidrx7v7d7mfuwerg)
[Filfox](https://filfox.info/en/message/bafy2bzacecpmy5zwseh4pbfw535f3oayb42etwqtekmymrxysf7cizfopkqfi)

![WeChatc241925e3b5fca6b3274afd032ced8ba](https://user-images.githubusercontent.com/5176425/94437150-f37f5b00-01cf-11eb-99a3-f17f97377a41.png)
![WeChat54e34b6ee511ed72a35ca580f0a7286e](https://user-images.githubusercontent.com/5176425/94437159-f5e1b500-01cf-11eb-84ee-7eaea24b889d.png)

**Version (run `lotus version`):**
Import snapshot: 0.7.0
Now: 0.8.0

**Comment by Kubuxu** [comment]
`bafy2bzaceaygblumo5vye4kjccx6cre2bifol6h6ha4oxidrx7v7d7mfuwerg` is CID of just the message (not signed). For secp messages, non-signed message is not really used. Filscan should not use it for message identification.

**Comment by jennijuju** [comment]
This is not a lotus issue.

**Comment by hulajesus** [comment]
> This is not a lotus issue.

it looks like lotus-chainwatch store the non-signed message CID, is it  the expected behavior?

**Comment by Kubuxu** [comment]
It is probably storying both for ease of lookup.

**Comment by hulajesus** [comment]
> It is probably storying both for ease of lookup.

is there a way to convert these two format, so I can query it in pg whichever format I get.
or anyone can add a new field to store it, thanks
