### ISSUE TITLE
Use of duration of a storage deal set ask

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4076]
For `lotus-miner storage-deals set ask`, there is an `duration` param option with description `Set duration of ask (a quantity of time after which the ask expires) DURATION (default: 720h0m0s)`.

By the sounds of it, it gives the expression that the miner will stop accepting deals in 720 hr(by default)(like the miner only asking for deals with this price in the next 720hr)

However from @hannahhoward , while we have a notion of an expiration, we actually don't do anything with it (miner will be still accepting deals after the duration passes.

We should figure out what we want to do with it.

**Comment by arajasek** [comment]
Update from a quick convo: We should probably get rid of the idea of duration, for now, let's hide this option from the CLI.

**Comment by jennijuju** [comment]
For now - we decided to remove that option from the CLI
