### ISSUE TITLE
Build error - fatal: Invalid object name '@'.

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#408]
In my centos compiling environment, this error happens when running make in lotus:
```
[root@localhost lotus]# make
make -C extern/go-bls-sigs/ libbls_signatures.a libbls_signatures.pc libbls_signatures.h
make[1]: Entering directory `/root/go/src/github.com/filecoin-project/lotus/extern/go-bls-sigs'
./install-bls-signatures
fatal: Invalid object name '@'.
acquiring release @ @:bls-signatures
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129  100   129    0     0    102      0  0:00:01  0:00:01 --:--:--   102
jq: error (at <stdin>:4): Cannot iterate over null (null)
failed to download release (tag URL: https://api.github.com/repos/filecoin-project/bls-signatures/releases/tags/@:bls-signatures, response: {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name"
})
./install-bls-signatures: line 20: [: =: unary operator expected
build failed: could not obtain precompiled assets for bls-signatures - contact @laser or @dignifiedquire
make[1]: *** [.install-bls] Error 1
make[1]: Leaving directory `/root/go/src/github.com/filecoin-project/lotus/extern/go-bls-sigs'
make: *** [build/.bls-install] Error 2
```

The same error happened in go-filecoin early version, but it's gone in 0.5. One way to fix this is to change the related scripts, but I do not think it is the best way. Any one has better idea?

**Comment by IPFS-grandhelmsman** [comment]
GCC had better be 7.4. I tried 6 and 8 versions but they didn't work.

**Comment by Kubuxu** [comment]
@steven004 Can you try running:
```
make clean
make build
```

**Comment by steven004** [comment]
> @steven004 Can you try running:
> 
> ```
> make clean
> make build
> ```

@Kubuxu , it does not work. This only happens in my centOS system. The build is fine with Ubuntu and MacOS. It could be a compliance issue of the scripts.

**Comment by Kubuxu** [comment]
Can you update to latest master, run `git submodule update --recursive` and then:
```
make clean
make build
```
and post the whole output.

**Comment by steven004** [comment]
The root cause had been found. 
In the installation scripts in submodules, the command `git rev-parse @directory` is used to figure out the commit id. However, it is not supported well by git lower version (in my centos 7, it is 1.8.3.1). The solution is to upgrade git to 2.x if we do not want to change the code. 

My suggestion is putting this requirement in the doc.
