### ISSUE TITLE
Miner's memory rising quickly and unable to free allocated memory

### ISSUE THREAD

**Issue by AlexNiny** [filecoin-project/lotus#4087]
**Describe the bug**
When miner receive many deals,the memory will rising quickly and unable to free allocated memory.finally,the miner thread will kill cause 'out of memory'

**To Reproduce**
1. Run  local devnet use 512MiB sector size
2. send 10 deals,each deal size is 300MiB
3.use 'top' to see memory of lotus-miner,get result as follow
![image](https://user-images.githubusercontent.com/19648780/94527717-fe86c980-0269-11eb-8b33-7d294102bb03.png)
4.use 'go tool pprof -alloc_space http://127.0.0.1:2345/debug/pprof/heap' 
![image](https://user-images.githubusercontent.com/19648780/94527806-2118e280-026a-11eb-9371-a5b8385ec305.png)
5.use 'go tool pprof -inuse_space http://127.0.0.1:2345/debug/pprof/heap'
![image](https://user-images.githubusercontent.com/19648780/94527916-4a397300-026a-11eb-8718-7368a23b0476.png)
6.the 'dead machine' info use 'go tool pprof -inuse_space http://127.0.0.1:2345/debug/pprof/heap'
![image](https://user-images.githubusercontent.com/19648780/94535404-1bc09580-0274-11eb-978c-d613871e5299.png)

**Expected behavior**
the memory will be freed normally

**Version (run `lotus version`):**
0.8.0

**Comment by AlexNiny** [comment]
i guess cause by 
![image](https://user-images.githubusercontent.com/19648780/94534370-e49db480-0272-11eb-9e38-9133edf318b7.png)

**Comment by rjan90** [comment]
The issue with rising memory due to deals has been fixed on newer versions of Lotus, I think this issue can be closed now! #rengjøring

**Comment by jennijuju** [comment]
Please open a new ticket if you are running into this issue on the latest version of lotus!
