### ISSUE TITLE
sync break when Node evil

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4090]
when injectNulls=-1   Node evil

Normal node
lotus chain list
0: (Sep 29 15:26:26) [ bafy2bzacec6zka46q3fheob4o653qssv5oj7b752w53qlqlgjgn4wrgogu4em: t00, ]
1: (Sep 29 15:26:30) [ bafy2bzacecgnt67z3ysfnlxop7lzcw2esyooeupw2zycyzyb3dtanhouzcq24: t01000, ]
2: (Sep 29 15:26:34) [ bafy2bzaceacr4txs3id5sypyrvkl6bqadv2x7hulbhgl2hbehkcsoypoys5si: t01000, ]
3: (Sep 29 15:26:38) [ bafy2bzacedl7gvg6xmjxsnf3nxayfzkny4l5zdxgmidtp5walru3tvhu74wei: t01000, ]
4: (Sep 29 15:26:42) [ bafy2bzacebecdfpwusao3hrvliuod2tm7wpufil6zl6hmgmmzbw4qc2kfbhja: t01000, ]
5: (Sep 29 15:26:46) [ bafy2bzacebll3bshvdgp4nw3tncauzj4xromwx7nwbw2fpgspdbumlo7tguiu: t01000, ]
6: (Sep 29 15:26:50) [ bafy2bzacedlmsicysy42l4otvjezsgpnvwz3nrh5ahf5w5t6hu34cwbq3yvrs: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzacedc6mpml3ggykfevwmbilzo6aiizle2jqbi3dtjcxe65n7uodjjxc: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzacebgwkj4izaa3nenjruafy56icnjeo46v47uop7e5uf75njukavnic: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzaced6owft5drj2ny7fazbhoedzjkjkapdjwugrko5lcs3ef5ju52cny: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzaced5m5quovypbp5z4a4wdnsifinovipfan7pm6awvmumjqvetn5kwe: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzaceawt2wbpgq5ib6svuhxoxbl6hhlwt32lvrrnxjytegjxwxpc7cs4u: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzaced7h6dabtop5udrpuhhcwcwknugbwyhba636yazvm7bfjoho4dxuo: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzaced7krxxy7namyyj4aamllq4jmopoycjs2chbextstiylvtju7pq5g: t01000, ]
https://github.com/filecoin-project/lotus/blob/14791420478a14bd7181af2d590697fd7968e135/chain/sync.go#L737-L740

**Comment by schomatis** [comment]
As mentioned in https://github.com/filecoin-project/lotus/pull/4091#issuecomment-704433124, this is an issue only for the same miner that creates this fake block. (Please feel free to reopen if you observe otherwise, that is, the fake block being accepted by an external node that didn't create it.)
