### ISSUE TITLE
Create protocol config files for upgrade heights (and more)

### ISSUE THREAD

**Issue by exp0nge** [filecoin-project/lotus#4099]
Typically, we have long running devnet nodes that we would like to maintain chain state on. Things like forks, eg `UpgradeLiftoffHeight`, would make a lot more sense to be runtime driven via config file provided to lotus to provide the flexibility of different usages of devnet. For example, Zcash handles this via config file with `nuparams` where we specify the heights in our config file: https://github.com/zcash/zcash/commit/6f9b281ef7a5bc28a99d56e97106489b6314fd6b (example: https://github.com/zcash/zcash/issues/4705)

Additionally, we tweak `BlockDelaySecs` for local development because we don't need blocks to be produced so rapidly. On one hand, we increase to make local integration tests easier _but_ for automated tests, we _would_ like to produce blocks much faster. 

We can't do these without rebuilding the whole codebase which is a pain point for us.

**Comment by arajasek** [comment]
(We should just do this for all the params files)

**Comment by arajasek** [comment]
The task is probably to create a "protocol config" file that lives in the repos, and defaults for each of the networks we support

**Comment by magik6k** [comment]
related to this issue, `debug`/`2k` builds now support setting upgrade epochs through env vars - https://github.com/filecoin-project/lotus/blob/master/build/params_2k.go#L62-L75
