### ISSUE TITLE
StateCompute inefficient payload size  

### ISSUE THREAD

**Issue by raynaudoe** [filecoin-project/lotus#4109]
**Describe the bug**
`StateCompute` api function returns an extremely large payload resulting on slow remote calls.

**To Reproduce**
1. Run from a remote terminal:
```
curl -X POST  -H "Content-Type: application/json"  --data '{ "jsonrpc": "2.0", "method":"Filecoin.StateCompute", "params": [1000, [ ], [ ] ], "id": 0
    }'     'http://<NODE_IP>:1234/rpc/v0'
```
2. Output takes about 3m to complete

**Expected behavior**
Seems that `GasTrace` field is cluttering the output. Maybe adding an option to skip retrieving that field ?

**Version (run `lotus version`):**
0.8.0

**Comment by magik6k** [comment]
Gas traces are now disabled by default on latest master

**Comment by raynaudoe** [comment]
Great! Will try again with latest master
