### ISSUE TITLE
AddPieceToAnySector holds a lock while calling AddPiece

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#4110]
https://github.com/filecoin-project/lotus/blob/master/extern/storage-sealing/sealing.go#L172

This means that only one AddPiece can be runnig at any given time, and that when it is running (which can take 10+min in some cases), some API calls like `StartPacking`, or deal operations will be blocked

**Comment by liuyongmingeth** [comment]
I just heard that my partner’s implementation of "lotus-miner sectors update-state --really-do-it 32 Packing" results in stuck, how do I do it now to make the subsequent deals continue to be sealed?
