### ISSUE TITLE
sync issue and new future request

### ISSUE THREAD

**Issue by ncgege** [filecoin-project/lotus#4113]
sometimes the lotus  daemon has a lot of peers but can't get the right epoch. so it stuck at  a certain epoch and lose sync. 
so can the dev team check it and add new futures list each peers epoch .and the sync from the highest epoch peer.
**lotus net peers**
add a column to  show each peers epoch.

**Comment by jennijuju** [comment]
@ncgege we discussed about this briefly and this might be a little trick to do - we will take a look later(maybe post-mainnet)

**Comment by ncgege** [comment]
thank you . now i update to lotus v0.9.0 now .it's really better than before now.
