### ISSUE TITLE
[Sync Problem]86% of lotus daemon logs are `sent too many dont haves, removing from session` make sync stuck

### ISSUE THREAD

**Issue by askender** [filecoin-project/lotus#4118]
➜  ~ lotus version
Daemon:  0.8.0+git.2c1d96b.dirty+api0.16.0
Local: lotus version 0.8.0+git.2c1d96b.dirty

**INFO:**
➜  ~ cat log.lotus_0825_v800_001|grep ’sent too many dont haves’|wc -l
44371483
➜  ~ cat log.lotus_0825_v800_001|wc -l
51444254
I guess I have got DDoS,  hard to sync…    
50 peers send 36373343 msgs in 3 days,  36373343/44371483=81.97%

**another server in same network, very quick in sync:**
➜  ~ cat log.lotus_0825_v800|grep ’sent too many dont haves’|wc -l
386279
➜  ~ cat log.lotus_0825_v800|wc -l
2194152

the spam msgs are like this:
```
2020-09-29T22:13:54.705+0800	INFO	bs:sess	session/sessionwantsender.go:458	
peer 12D3KooWMYYJjkoWdbkPCaRDgFS4mdNRcMfLvUwnVRdcgQy8RDSw 
sent too many dont haves, removing from session 18359
```

**Comment by dirkmc** [comment]
Context on the error message:

Bitswap sessions are used to group many requests for blocks in the same file.

When Bitswap is asked to fetch a block, it sends a "want-have" request to all connected peers. Any peer that has the block responds with "HAVE". Bitswap adds peers that have the block to the session.

From then on, each time Bitswap is asked to fetch a block for that file, it only sends the "want-have" to peers that are in the session. If a peer responds with "DONT_HAVE" many times in a row, Bitswap outputs `sent too many dont haves, removing from session` and removes the peer from the session. This is to avoid sending "want-have" to peers which don't have any more blocks that the session is interested in.

**Comment by jennijuju** [comment]
> Context on the error message:
> 
> Bitswap sessions are used to group many requests for blocks in the same file.
> 
> When Bitswap is asked to fetch a block, it sends a "want-have" request to all connected peers. Any peer that has the block responds with "HAVE". Bitswap adds peers that have the block to the session.
> 
> From then on, each time Bitswap is asked to fetch a block for that file, it only sends the "want-have" to peers that are in the session. If a peer responds with "DONT_HAVE" many times in a row, Bitswap outputs `sent too many dont haves, removing from session` and removes the peer from the session. This is to avoid sending "want-have" to peers which don't have any more blocks that the session is interested in.

This is not an issue as it is a log designed to be printout as mentioned above. And it is also attached to the linked ticket, so closing.

**Comment by askender** [comment]
Thanks.     Before 0.8.1 this msg is really too much(86%), and mess up the logs.
In 0.8.1,  the sync is really fast!  Thanks for your great work.      @jennijuju  I like your code and other great works too.  
Happy festivals!

`Time delta between now and our mining base: 6s (nulls: 0)`  6s is super fast!  Haven't been so fast for a long time.

**Comment by jennijuju** [comment]
> Thanks. Before 0.8.1 this msg is really too much(86%), and mess up the logs.
> In 0.8.1, the sync is really fast! Thanks for your great work. @jennijuju I like your code and other great works too.
> Happy festivals!
> 
> `Time delta between now and our mining base: 6s (nulls: 0)` 6s is super fast! Haven't been so fast for a long time.

Aw thank you for the kind words, and glad to know that things are performing better for you now! And thank you for keep flagging issue with us and providing detailed description, they are all super helpful to us! And happy festivals to you too!
