### ISSUE TITLE
Have an option to set timeout for cancel a deal that is stuck in transferring data.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4119]
We have #4093 to give the client/miner an option to cancel a deal in transferring process.

This request is about to have this done automatically if a timeout is set by miner, and the data transferring takes longer than the timeout, make the deal go to one of the error state.

**Comment by hannahhoward** [comment]
@jennijuju this is actually fixed in 0.10.1 -- if we stall out or encounter network errors transfering data, after 1 hour the transfer will error. there will be an informational message letting people know the transfer is stalled before then.

Let me know if I can close this
