### ISSUE TITLE
Miner use too many RAM

### ISSUE THREAD

**Issue by mostcute** [filecoin-project/lotus#4121]
**Describe the bug**
my miner use too many ram, killed by OOM once,i have to add some swap.

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/23225426/94773221-eb9d0200-03ed-11eb-82e3-9d56615ec251.png)

**Version (run `lotus version`):**
v0.8.0

**Additional context**

**Comment by mostcute** [comment]
i will upload the svg in slack

**Comment by jennijuju** [comment]
> i will upload the svg in slack

It will be better if you can host your svg somewhere and have a link here. Info sent in slack may be lost later.

**Comment by jennijuju** [comment]
slack dump: https://filecoinproject.slack.com/archives/CP50PPW2X/p1601531904128000?thread_ts=1601531814.127400&cid=CP50PPW2X

about 300MiB/deal. and 100desls/hour

**Comment by woshidama323** [comment]
Same issue 
 ```
ROUTINE ======================== github.com/ipfs/go-merkledag/pb.(*PBNode).Unmarshal in /data2/code/pkg/mod/github.com/ipfs/go-merkledag@v0.3.2/pb/merkledag.pb.go
  108.79GB   108.79GB (flat, cum) 76.37% of Total
         .          .    911:				return ErrInvalidLengthMerkledag
         .          .    912:			}
         .          .    913:			if postIndex > l {
         .          .    914:				return io.ErrUnexpectedEOF
         .          .    915:			}
  108.79GB   108.79GB    916:			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
         .          .    917:			if m.Data == nil {
         .          .    918:				m.Data = []byte{}
         .          .    919:			}
         .          .    920:			iNdEx = postIndex
```

pprof shows the position of the big ram used

**Comment by Yarkin** [comment]
![image](https://user-images.githubusercontent.com/1072921/96604446-b5d1a600-1327-11eb-953f-2d46516cab33.png)
