### ISSUE TITLE
Lotus to show the correct deal state when a data transfer has failed due to node shutdown

### ISSUE THREAD

**Issue by pooja** [filecoin-project/lotus#4136]
**Describe the bug**
Related to #3417 and #4093 

We have a ton of people in Slingshot who are starting deals, miners accept them, and then the deal will get stuck in transferring state. One of the big causes of this is that the client node goes offline, and the data transfer will stop, but lotus still thinks the data is “transferring” even though the deal has effectively failed. Clients do not have a good way to know which data transfers are actually transferring and which say they’re transferring but have actually failed. So people think their data is transferring and their deal is succeeding, but it’s not. They don’t retry these deals because they don’t know that they should. According to @hannahhoward, this status never gets updated — it stays stuck in transferring state forever. This is a huge issue for Slingshot and for the mainnet client experience.

**Expected behavior**
When a data transfer has stopped (and won't be resumed), please change the deal status to failed and output the appropriate error message for both clients and miners.

It would be lovely to have a fix to #3417 , but if not, even just providing the correct deal state would be very useful so that clients and miners know what is happening and can react accordingly.

**Comment by pooja** [comment]
Hannah mentioned: just for clarification, when a node shuts down, the other node notices it when they simply stop seeing traffic go through. we obviously want to make space for temporary network drops, so it’s likely that the “other side shut down” won’t show up for a bit.

**Comment by pooja** [comment]
@jennijuju How are we determining the priority label of this? P2 is pretty low for something that should happen asap. Just because it's a UX issue doesn't mean it's not a critical issue for mainnet success.

**Comment by hannahhoward** [comment]
Fixed in 0.10.1 though Pooja I'm going to wait till you get confirmation from people using 0.10.1 before I close the issue

**Comment by pooja** [comment]
@jsign Can you confirm this behavior now works as intended?

**Comment by jsign** [comment]
What I confirm is that after a restart, some deals switch to the "StorageDealRestartTransfer" (or similarish). I haven't followed behavior at the network level, but looks like trying to restart transfers.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks :pray:
