### ISSUE TITLE
PreCommit2 uses only 1 core

### ISSUE THREAD

**Issue by creaz79** [filecoin-project/lotus#4154]
**Describe the bug**
I got server with 2xAMD EPYC 7452 32 cores (128 cores total with HT)+ 384GB Memory + NVMe disk for sealing + 2 Tesla T4
And long time can't understand why full cycle take about 14h, but lesser hardware shows better result.
I moved start of lotus daemon and lotus miner to systemd  with set of cpuaffinity and this helps partialy understand the reason:
lotus-daemon - CPUAffinity=32-63,96-127 (physical cpu 1)
lotus-miner - CPUAffinity=0-31,64-95 (physical cpu 0)
htop shows that daemon uses all dedicated cores, but miner and on PreCommit1 and on PreCommit2 uses only 1 core
but if i look through workers -
Worker 0, host 
        CPU:  [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||      ] 58 core(s) in use
        RAM:  [|||                                                             ] 6% 26.35 GiB/377.8 GiB
        VMEM: [|                                                               ] 2% 26.35 GiB/881.4 GiB
        GPU: Tesla T4, used
        GPU: Tesla T4, used
Worker 1, host 
        CPU:  [                                                                ] 0 core(s) in use
        RAM:  [|||                                                             ] 5% 20.59 GiB/377.8 GiB
        VMEM: [|                                                               ] 2% 20.59 GiB/881.4 GiB
        GPU: Tesla T4, not used
        GPU: Tesla T4, not used

ID  Sector  Worker  Hostname  Task  State    Time
1   43      0       Hostname      PC2   running  33m4.9s

Second problem that workers shows, that it used both GPU, but in fact:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage |===============================+======================+======================|
|   0  Tesla T4            Off  |   97C    P0    43W /  70W |   6744MiB / 15109MiB |   100%    
|   1  Tesla T4            Off  |   35C    P8    10W /  70W |      3MiB / 15109MiB |      0%      +-------------------------------+----------------------+----------------------+
|    0   N/A  N/A     25788      C   /usr/local/bin/lotus-miner       6741MiB |
+-----------------------------------------------------------------------------+

What I am doing wrong or this is a bug?

1. Run 'services daemon, miner'
2. See problem
![htop_screen](https://user-images.githubusercontent.com/25491906/94988834-cdafd880-0578-11eb-9b5a-5a81785c26f4.png)
![nvtop_screen](https://user-images.githubusercontent.com/25491906/94988842-d7394080-0578-11eb-9725-74a4c429d75e.png)

**Expected behavior**
Full utilization of hardware.

**Screenshots**

**Version (run `lotus version`):**
lotus version 0.8.1+git.4631cee5
This kind perfomance problem from 7.0

**Comment by rjan90** [comment]
I think this issue can be closed now? #rengjøring
