### ISSUE TITLE
To perform precommit1 (PC1) takes too long(17 hours)

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#4162]
I use 1Gbps internet and it takes about 17 hours to perform precommit1 (PC1). I think it takes too long. Is there anything wrong with the settings?

**Describe the problem**

A brief description of the problem you encountered while proving (sealing) a sector.

Including what commands you ran, and a description of your setup, is very helpful.

**Sectors status**

The output of `lotus-miner sectors status --log <sectorId>` for the failed sector(s).

**Lotus miner logs**

Please go through the logs of your miner, and include screenshots of any error-like messages you find.

Alternatively please upload full log files and share a link here

**Lotus miner diagnostic info**

Please collect the following diagnostic information, and share a link here

* lotus-miner diagnostic info `lotus-miner info all > allinfo`

** Code modifications **

If you have modified parts of lotus, please describe which areas were modified,
and the scope of those modifications

**Version**

The output of `lotus --version`.

**Comment by hsjw12** [comment]
lotus-miner sectors status --log 
SectorID:       36
Status:         PreCommit1
CIDcommD:       <nil>
CIDcommR:       <nil>
Ticket:
TicketH:        0
Seed:
SeedH:          0
Precommit:      <nil>
Commit:         <nil>
Proof:
Deals:          [0]
Retries:        0
--------
Event Log:
0.      2020-10-15 02:16:12 +0900 KST:  [event;sealing.SectorStartCC]   {"User":{"ID":36,"SectorType":3,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}},"DealInfo":null}]}}
1.      2020-10-15 02:16:12 +0900 KST:  [event;sealing.SectorPacked]    {"User":{"FillerPieces":null}}
2.      2020-10-15 09:02:01 +0900 KST:  [event;sealing.SectorRestart]   {"User":{}}
3.      2020-10-15 09:04:34 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        seal pre commit(1) failed: acquiring sector paths: local acquire error: couldn't find a suitable path for a sector
4.      2020-10-15 09:05:34 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
5.      2020-10-15 12:05:37 +0900 KST:  [event;sealing.SectorRestart]   {"User":{}}
6.      2020-10-15 12:11:15 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        seal pre commit(1) failed: acquiring sector paths: local acquire error: couldn't find a suitable path for a sector
7.      2020-10-15 12:12:15 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
8.      2020-10-15 12:30:47 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        seal pre commit(1) failed: acquiring sector paths: local acquire error: finding best storage for allocating : no good path found
9.      2020-10-15 12:31:47 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
10.     2020-10-15 14:38:40 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        seal pre commit(1) failed: acquiring sector paths: local acquire error: couldn't find a suitable path for a sector
11.     2020-10-15 14:39:40 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
12.     2020-10-15 15:01:36 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        seal pre commit(1) failed: acquiring sector paths: reserving storage space: can't reserve 484472310988 bytes in '/work/SEAL' (id:42675026-97d0-4673-affb-23b30da7b8da), only 160523002676 available
13.     2020-10-15 15:02:36 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
14.     2020-10-16 03:01:00 +0900 KST:  [event;sealing.SectorRestart]   {"User":{}}
15.     2020-10-16 04:11:09 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        seal pre commit(1) failed: acquiring sector paths: local acquire error: couldn't find a suitable path for a sector
16.     2020-10-16 04:12:09 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
17.     2020-10-16 04:53:13 +0900 KST:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        seal pre commit(1) failed: acquiring sector paths: local acquire error: finding best storage for allocating : no good path found
18.     2020-10-16 04:54:13 +0900 KST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
19.     2020-10-17 21:09:11 +0900 KST:  [event;sealing.SectorRestart]   {"User":{}}
20.     2020-10-17 21:23:10 +0900 KST:  [event;sealing.SectorRestart]   {"User":{}}
21.     2020-10-17 22:03:04 +0900 KST:  [event;sealing.SectorRestart]   {"User":{}}
22.     2020-10-17 22:07:37 +0900 KST:  [event;sealing.SectorRestart]   {"User":{}}
23.     2020-10-17 22:29:03 +0900 KST:  [event;sealing.SectorRestart]   {"User":{}}
24.     2020-10-18 16:11:06 +0900 KST:  [event;sealing.SectorRestart]   {"User":{}}


lotus --version
lotus version 0.10.2+git.0f5aa9ba

**Comment by rjan90** [comment]
This issue can be closed since it is not an Lotus-issue, but rather hardware-issue. #rengjøring
