### ISSUE TITLE
Various problems on arm64(aarch64)

### ISSUE THREAD

**Issue by YLinXin** [filecoin-project/lotus#4163]
**Describe the bug**
cannot build on arm64(aarch64) at least once.

**To Reproduce**
1. Run 'git checkout v0.8.1;export RUSTFLAGS="-C target-cpu=native -g";export FFI_BUILD_FROM_SOURCE=1
;make clean deps all'
2. See error

**Expected behavior**
build success.

**Version (run `lotus version`):v0.8.1**

**Additional context**
I have resovle so many problems when build on arm64(aarch64).but it still comes out one by one.Why there is no binary official for arm64?Storage node is more suitable running on arm but x86.

```CoreELEC:/media/sda1/Lotus/lotus # make deps all
make: Nothing to be done for 'deps'.
rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.1ebad94d.dirty" -o lotus ./cmd/lotus
go build github.com/supranational/blst/bindings/go: build constraints exclude all Go files in /media/sda1/Lotus/lotus/extern/fil-blst/blst/bindings/go
go build github.com/ipsn/go-secp256k1: build constraints exclude all Go files in /storage/go/pkg/mod/github.com/ipsn/go-secp256k1@v0.0.0-20180726113642-9d62b9f0bc52
# github.com/filecoin-project/go-fil-markets/pieceio
/storage/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v0.7.0/pieceio/pieceio.go:215:19: undefined: ffi.GeneratePieceCIDFromFile
# github.com/filecoin-project/lotus/extern/sector-storage
extern/sector-storage/localworker.go:98:9: undefined: ffiwrapper.New
extern/sector-storage/localworker.go:266:15: undefined: ffi.GetGPUDevices
extern/sector-storage/manager.go:98:17: undefined: ffiwrapper.New
# github.com/filecoin-project/lotus/chain/vm
chain/vm/syscalls.go:66:16: undefined: ffiwrapper.GenerateUnsealedCID
make: *** [Makefile:68: lotus] Error 2```

**Comment by PatrickDeuse** [comment]
there is no official binary for any architecture.

**Comment by hwnahm** [comment]
when make lotus v0.10.2 on my Mac...

rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.1401efb1" -o lotus ./cmd/lotus
go build github.com/supranational/blst/bindings/go: build constraints exclude all Go files in /Users/peter/devel/FileCoin/lotus/extern/fil-blst/blst/bindings/go
go build github.com/ipsn/go-secp256k1: build constraints exclude all Go files in /Users/peter/go/pkg/mod/github.com/ipsn/go-secp256k1@v0.0.0-20180726113642-9d62b9f0bc52
# github.com/filecoin-project/lotus/extern/sector-storage
extern/sector-storage/localworker.go:98:9: undefined: ffiwrapper.New
extern/sector-storage/localworker.go:266:15: undefined: ffi.GetGPUDevices
extern/sector-storage/manager.go:98:17: undefined: ffiwrapper.New
# github.com/filecoin-project/lotus/chain/vm
chain/vm/syscalls.go:66:16: undefined: ffiwrapper.GenerateUnsealedCID
# github.com/filecoin-project/go-fil-markets/pieceio
../../../go/pkg/mod/github.com/filecoin-project/go-fil-markets@v0.7.1/pieceio/pieceio.go:215:19: undefined: ffi.GeneratePieceCIDFromFile
make: *** [lotus] Error 2

**Comment by twl4587** [comment]
make[1]: Leaving directory '/root/lotus/extern/filecoin-ffi'
rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.bb25eb980.dirty" -o lotus ./cmd/lotus
# github.com/filecoin-project/lotus/chain/vm
chain/vm/syscalls.go:79:16: undefined: ffiwrapper.GenerateUnsealedCID
# github.com/dgraph-io/badger/v2
/usr/local/go/bin/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/value.go:50:5: constant 4294967295 overflows int
# github.com/filecoin-project/lotus/extern/sector-storage
extern/sector-storage/manager.go:114:17: undefined: ffiwrapper.New
extern/sector-storage/worker_local.go:148:9: undefined: ffiwrapper.New
extern/sector-storage/worker_local.go:473:15: undefined: ffi.GetGPUDevices
go build github.com/supranational/blst/bindings/go: build constraints exclude all Go files in /root/lotus/extern/blst/bindings/go
go build github.com/ipsn/go-secp256k1: build constraints exclude all Go files in /usr/local/go/bin/pkg/mod/github.com/ipsn/go-secp256k1@v0.0.0-20180726113642-9d62b9f0bc52
# github.com/filecoin-project/go-commp-utils/ffiwrapper
/usr/local/go/bin/pkg/mod/github.com/filecoin-project/go-commp-utils@v0.0.0-20201119054358-b88f7a96a434/ffiwrapper/ffiwrapper.go:69:19: undefined: ffi.GeneratePieceCIDFromFile
make: *** [Makefile:68: lotus] Error 2

**Comment by twl4587** [comment]
lotus 1.2.1 for ubuntu20.04

**Comment by ribasushi** [comment]
@twl4587 `bb25eb980` is current master, could you go back to the v1.2.1 tag and retry there? Thanks!

**Comment by twl4587** [comment]
What do I have to do?Thanks!

**Comment by ribasushi** [comment]
```
git clean -fxd
git checkout v1.2.1
git submodule update --init --recursive
git status
```
stop here if `git status` show anything ( changed / untracked files ) - show me the output here

if `git status` doesn't show anything after the above:
```
make all
```

**Comment by twl4587** [comment]
root@iZj6cgyz9kdtkc30wtxauwZ:~/lotus# git status
HEAD detached at v1.2.1
nothing to commit, working tree clean
root@iZj6cgyz9kdtkc30wtxauwZ:~/lotus# make all
git submodule update --init --recursive
touch build/.update-modules
make -C extern/filecoin-ffi/ .install-filcrypto
make[1]: Entering directory '/root/lotus/extern/filecoin-ffi'
make[1]: '.install-filcrypto' is up to date.
make[1]: Leaving directory '/root/lotus/extern/filecoin-ffi'
rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.df66f48f6" -o lotus ./cmd/lotus
go: downloading github.com/filecoin-project/go-fil-markets v1.0.5-0.20201113164554-c5eba40d5335
go: downloading github.com/ipld/go-car v0.1.1-0.20200923150018-8cdef32e2da4
go: downloading github.com/filecoin-project/go-fil-commcid v0.0.0-20200716160307-8f644712406f
go: downloading github.com/sirupsen/logrus v1.6.0
go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: downloading github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d
go: downloading github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
# github.com/filecoin-project/lotus/chain/vm
chain/vm/syscalls.go:79:16: undefined: ffiwrapper.GenerateUnsealedCID
# github.com/dgraph-io/badger/v2
/usr/local/go/bin/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/value.go:50:5: constant 4294967295 overflows int
# github.com/filecoin-project/lotus/extern/sector-storage
extern/sector-storage/manager.go:110:17: undefined: ffiwrapper.New
extern/sector-storage/worker_local.go:148:9: undefined: ffiwrapper.New
extern/sector-storage/worker_local.go:473:15: undefined: ffi.GetGPUDevices
go build github.com/supranational/blst/bindings/go: build constraints exclude all Go files in /root/lotus/extern/blst/bindings/go
go build github.com/ipsn/go-secp256k1: build constraints exclude all Go files in /usr/local/go/bin/pkg/mod/github.com/ipsn/go-secp256k1@v0.0.0-20180726113642-9d62b9f0bc52
# github.com/filecoin-project/go-fil-markets/pieceio
/usr/local/go/bin/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.0.5-0.20201113164554-c5eba40d5335/pieceio/pieceio.go:215:19: undefined: ffi.GeneratePieceCIDFromFile
# github.com/filecoin-project/lotus/lib/commp
lib/commp/writer.go:42:17: undefined: ffiwrapper.GeneratePieceCIDFromFile
lib/commp/writer.go:65:13: undefined: ffiwrapper.GeneratePieceCIDFromFile
lib/commp/writer.go:103:12: undefined: ffi.GenerateUnsealedCID
Makefile:67: recipe for target 'lotus' failed
make: *** [lotus] Error 2

**Comment by ribasushi** [comment]
@twl4587 ah I see
you need an extra `make clean` so that the ffi rebuilds :(

```
git clean -fxd
make clean all
```

**Comment by twl4587** [comment]
# github.com/filecoin-project/lotus/lib/commp
lib/commp/writer.go:42:17: undefined: ffiwrapper.GeneratePieceCIDFromFile
lib/commp/writer.go:65:13: undefined: ffiwrapper.GeneratePieceCIDFromFile
lib/commp/writer.go:103:12: undefined: ffi.GenerateUnsealedCID
Makefile:67: recipe for target 'lotus' failed
make: *** [lotus] Error 2

**Comment by twl4587** [comment]
root@iZj6cgyz9kdtkc30wtxauwZ:~/lotus# git clean -fxd
Removing build/.filecoin-install
Removing build/.update-modules
root@iZj6cgyz9kdtkc30wtxauwZ:~/lotus# git checkout v1.2.1
HEAD is now at df66f48f6 Merge pull request #4937 from filecoin-project/asr/changelog
root@iZj6cgyz9kdtkc30wtxauwZ:~/lotus# git submodule update --init --recursive
root@iZj6cgyz9kdtkc30wtxauwZ:~/lotus# git status
HEAD detached at v1.2.1
nothing to commit, working tree clean
root@iZj6cgyz9kdtkc30wtxauwZ:~/lotus# git clean -fxd
root@iZj6cgyz9kdtkc30wtxauwZ:~/lotus#

**Comment by twl4587** [comment]
I'm using Ubuntu 18.04

**Comment by twl4587** [comment]
Do you have any hardware requirements for installing this software? I installed it on a virtual machine？

**Comment by ribasushi** [comment]
There shouldn't be anything special hardware-wise. Earlier you said https://github.com/filecoin-project/lotus/issues/4163#issuecomment-732637487 you are on 20.04

I am able to build and run lotus 1.2.1 on https://aws.amazon.com/ec2/instance-types/r6/ just fine...

**Comment by ribasushi** [comment]
@twl4587 can you try with ubuntu 20.04 please?
also give me your complete `lscpu` output

**Comment by twl4587** [comment]
root@iZj6cgyz9kdtkc30wtxauwZ:~/lotus# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
Stepping:            4
CPU MHz:             2500.020
BogoMIPS:            5000.04
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1

**Comment by ribasushi** [comment]
Wait... this is a Xeon. Aren't you trying to build on arm64/aarch64 ?

**Comment by twl4587** [comment]
No, I want to build on Xeon

**Comment by twl4587** [comment]
I use Xeon，What should be done?

**Comment by ribasushi** [comment]
@twl4587 this is entirely thr wrong issue for your problem :( 
Please follow the instructions as per https://docs.filecoin.io/get-started/lotus/installation/#build-and-install-lotus, especially point `#4`

**Comment by ribasushi** [comment]
@YLinXin your original issues has been resolved as per https://github.com/filecoin-project/lotus/issues/4111#issuecomment-731906092
Closing

**Comment by twl4587** [comment]
Please wait. I did it according to the instructions

**Comment by ribasushi** [comment]
@twl4587 find me on https://filecoin.io/slack, `@ribasushi - PLFD`
