### ISSUE TITLE
Re-run gas simulations for VerifyPoSt and PoRep

### ISSUE THREAD

**Issue by nicola** [filecoin-project/lotus#4164]
I am not 100% sure if the latest improvement to BLST are making it into the gas calculation.
We should rerun gas simulations and adjust numbers in a network upgrade

**Comment by nicola** [comment]
From @porcuquine 

> I got 7.703002ms using FIL_PROOFS_USE_FIL_BLST.  For comparison, using the same code but without fil-blst, I got 77.457872ms. These are both for verify window post proof (hot).

From @Kubuxu 
> VerifyPost, it is 77ms flat + 8.5us per sector on average, so 770M gas + 85k per sector.

I see that with BLST there is a 10x gas cost reduction (in the flat cost and likely more) that is not accounted for in windowpost.

**Comment by Kubuxu** [comment]
BLST was never delivered in state that would allow it to sync the whole chain (AFAIK).

**Comment by nicola** [comment]
Understood. I think this issue should be taken into consideration when that happens then!

**Comment by TippyFlitsUK** [comment]
Hi @nicola 

Thanks for the report. The issue is outdated. 

If this is a issue in the current release - please open a new ticket.

Thank you !
