### ISSUE TITLE
Add paging to deal list

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4185]
For clients have huge amount of deals, `list-deals` takes a long time to load(related #4131), also is hard to read when the list is too long. Adding paging when querying may help.

Idea:

`lotus client list-deal --startEpoch=<> --endEpoch=<>`
`lotus client list-deal --afterCreationTime=<>`

Required steps:
- [ ] Determine filter parameter for go-fil-markets retrieval list deals.
- [ ] Add filtering and pagination to go-fil-markets storage list deals endpoints https://github.com/filecoin-project/go-fil-markets/pull/512
- [ ] Add filtering and pagination to go-fil-markets retrieval list deals endpoints
- [ ] Update lotus CLI to use the endpoints https://github.com/filecoin-project/lotus/pull/5886

**Comment by dineshshenoy** [comment]
This probably needs to be changed in the API to add paging?  Should we expand the scope to add paging for all "list" API calls?
  
https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-methods.md#clientlistdeals

**Comment by vyzo** [comment]
We should do this after the v1 api is a thing, so it is _blocked_.

**Comment by aarshkshah1992** [comment]
@dirkmc For now, we need this ONLY for storage & clients, right ?
Don't need to support this for Providers for now.

**Comment by Fatman13** [comment]
Would be nice to alias the start and end epoch too. Say, `list-deal --slingshot2.2`.

**Comment by s0nik42** [comment]
and by status and from

--status StorageDealActive,StorageDealWaitingForData 
--from f3rmy6c7zoefq3bb4thhvmv35ihe4t35hyaivoxdrzzmtt5zx6hrdp4ltgzccndggynjkc3joxxok3quv5mg2a,f144zep4gitj73rrujd3jw6iprljicx6vl4wbeavi

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
