### ISSUE TITLE
Terminated after CommitFailed

### ISSUE THREAD

**Issue by KIM-IMHONG** [filecoin-project/lotus#4187]
**Describe the problem**

**Sectors status**

lotus-miner sectors status --log 420

![커밋실패1](https://user-images.githubusercontent.com/70502768/95179575-c6e4c800-07fb-11eb-8967-bd9c1c899837.PNG)

**Lotus miner logs**

Miner log not found due to restart.

I wanted to restart the sector through the commands

Error..

In filfox, it is considered complete and the number of faults increases.

You need a way to force restart or move files manually.

lotus-miner sectors remove --really-do-it 420

lotus-miner sectors status-update --really-do-it 420 CommitFailed

![커밋실패2](https://user-images.githubusercontent.com/70502768/95179831-217e2400-07fc-11eb-9fc6-65b3ae1430cb.PNG)

**Version**

lotus version 0.8.1+git.97087fe5

**Comment by rjan90** [comment]
Are you still seeing this issue? #rengjøring

**Comment by kimimhong** [comment]
After deleting the sector folder in the workers due to bad workers, if update-state is performed in the miner, the command is not heard.

**Comment by rjan90** [comment]
Ah! That is because it the miner does not find the sector on the worker. You can create a dummy sector in your /sealworker/sealed, touch s-t0xxxxx (replace xxx with the correct number)!

Then you can remove it 😄
