### ISSUE TITLE
ticket expired

### ISSUE THREAD

**Issue by nickboot** [filecoin-project/lotus#4191]
**Describe the bug**
ticket expired

**To Reproduce**

97.	2020-10-06 18:51:12 +0800 CST:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcaxg6xgxo3onrujtnqfv5xr2o3jir4spgxyfzqpam7woj447wdecp"},"Unsealed":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}}
98.	2020-10-06 18:51:12 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired: ticket expired: seal height: 111372, head: 122502
99.	2020-10-06 18:52:12 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}

**Version (run `lotus version`):**
lotus --version
lotus version 0.8.1+git.1ebad94d.dirty
lotus-miner --version
lotus-miner version 0.8.1+git.1ebad94d.dirty

**Comment by rjan90** [comment]
The issue with expired tickets has been fixed on newer versions of Lotus. This issue can be closed! #rengjøring
