### ISSUE TITLE
typo of output of 'lotus-miner info'

### ISSUE THREAD

**Issue by jjxx2021** [filecoin-project/lotus#4204]
**Describe the bug**
"Miner: f09569" should be "Miner: t09569"

jjxx@fc02:~/bin$ ./lotus-miner --miner-repo /data/miner2/ info
Miner: f09569
Sector Size: 32 GiB
Byte Power:   0 B / 458.7 PiB (0.0000%)
Actual Power: 0  / 459 Pi (0.0000%)
        Committed: 5.25 TiB
        Proving: 5.25 TiB (5.25 TiB Faulty, 100.00%)
Below minimum power threshold, no blocks will be won
Deals: 450, 220.8 GiB
        Active: 65, 1.257 GiB (Verified: 0, 0 B)

Miner Balance: 71.149177099908599673 FIL
        PreCommit:   0 FIL
        Pledge:      68.284889030549734574 FIL
        Vesting:     0 FIL
        Available:   2.864288069358865099 FIL
Worker Balance: 2.392012631262358916 FIL
Market (Escrow):  0.000048200504773235 FIL
Market (Locked):  0 FIL

Expected Seal Duration: 24h0m0s

Sectors:
        Total: 209
        Proving: 171
        WaitDeals: 1
        PreCommit2: 6
        PreCommitWait: 17
        WaitSeed: 2
        Removed: 4
        SealPreCommit1Failed: 4
        RecoverDealIDs: 4

**To Reproduce**
1. Run './lotus-miner --miner-repo /data/miner2/ info'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

jjxx@fc02:~/bin$ ./lotus-miner version
Daemon:  0.8.1+git.2bf42d53+api0.15.0
Local: lotus-miner version 0.8.1+git.2bf42d53

**Additional context**

**Comment by jennijuju** [comment]
haha this is definitely not a bug! It’s just another sign that we are approaching mainnet! On mainnet, addresses will be started with f instead of t . Two addresses are interchangeable tho.

**Comment by jjxx2021** [comment]
Got it.
