### ISSUE TITLE
It has been unable to complete synchronously. The latest block height cannot be synchronized

### ISSUE THREAD

**Issue by shihuajin111** [filecoin-project/lotus#4206]
**Describe the bug**
This Lotus node has more than two hundred remote client connections. it can synchronize to the latest if disconnect all remote clients. If reconnect. It's out of sync again

**Version (run `lotus version`):**
0.8.1

ram 256G cpu 3970

xjgw@ya-cx-2fi0301-010:~$ lotus sync wait
Worker: 2; Base: 123426; Target: 123586 (diff: 160)
State: message sync; Current Epoch: 123550; Todo: 36
Validated 425525 messages (0 per second)

**Comment by lcgogo** [comment]
same issue, the validated count increases more than 1M now.

docker exec -it fil-test-0.8.1-dev lotus sync wait
Worker: 0; Base: 95190; Target: 135360 (diff: 40170)
State: message sync; Current Epoch: 105065; Todo: 30295
Validated 1264414 messages (0 per second)

**Comment by lcgogo** [comment]
@shihuajin111  Try 0.9.1, I reinit one by 0.9.1 and validated very quickly.

**Comment by rjan90** [comment]
I think this issue can be closed now? #rengjøring
