### ISSUE TITLE
Sync State Error on Sync Completition

### ISSUE THREAD

**Issue by Geo25rey** [filecoin-project/lotus#4207]
**Describe the bug**
After running `lotus daemon` as a normal user on Linux and waiting for syncing to finish, once the "current epoch" reaches the "target", as described in `lotus sync wait`, the "current epoch" is set to 0 and the sync "state" becomes "error" with "todo" being the same as "target".

**To Reproduce**
1. `lotus daemon`
2. `lotus sync wait`
3. Wait until sync is complete
4. Observe the described behavior in the output of the sync wait command

**Expected behavior**
Lotus daemon periodically checks for newer target epcochs.

**Version (run `lotus version`):**
Daemon:  0.8.1+git.2bf42d531+api0.16.0
Local: lotus version 0.8.1+git.2bf42d531

**Additional context**
It may be worth noting that I'm using an "old" Intel CPU (i5 2500k).
Also, after restarting the Lotus daemon, the sync seems to continue where it left off.

Edit:
Here is the error that keeps showing up in the log.
```
2020-10-07T11:07:21.337-0400	INFO	sub	sub/incoming.go:93	new block over pubsub	{"cid": "bafy2bzacedofnnrwubwfwxao4mxjkvtcxkbcjixjlh7htnco6rhl6y2tbhj6c", "source": "12D3KooWKPMG3wJreSHHvaLieR2VYgLBQ1He1RXuRG1suCXbhUg7", "msgfetch": 20.226033942}
2020-10-07T11:07:21.337-0400	WARN	sub	sub/incoming.go:95	Received block with large delay 21 from miner f02528
2020-10-07T11:07:21.338-0400	INFO	sub	sub/incoming.go:93	new block over pubsub	{"cid": "bafy2bzacec7mj2ne7xi5i5lo5gav4uaez6aitv6gfsnsyvrgegsd3hqn5adf6", "source": "12D3KooWPuHFxfGz49aRwWyyie3DPBdtpg7pHxB3ACh7bF16AEhB", "msgfetch": 17.707178366}
2020-10-07T11:07:21.338-0400	WARN	sub	sub/incoming.go:95	Received block with large delay 21 from miner f01248
2020-10-07T11:07:21.597-0400	ERROR	chain	chain/sync_manager.go:421	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        github.com/filecoin-project/lotus/chain/sync.go:570
  - chain linked to block marked previously as bad ([bafy2bzacedofnnrwubwfwxao4mxjkvtcxkbcjixjlh7htnco6rhl6y2tbhj6c], bafy2bzaceaclyvm6xox2jvu4e664g3ygtynnaysfyreadecks4dgmrzsv7l6o) (reason: linked to bafy2bzacedcjl55w4ppgude6uttpzv5msrwbo64437enx4xcy4jf4jrr42qay caused by: [bafy2bzacea4urnifxta6itjgqh36r5g2rirl22xf4gqkk4yv2rdxueszk6zm6] 1 error occurred:
    	* block had invalid messages:
        github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func3
            github.com/filecoin-project/lotus/chain/sync.go:754
      - bls aggregate signature was invalid:
        github.com/filecoin-project/lotus/chain.(*Syncer).checkBlockMessages
            github.com/filecoin-project/lotus/chain/sync.go:1046
      - bls aggregate signature failed to verify:
        github.com/filecoin-project/lotus/chain.(*Syncer).verifyBlsAggregate
            github.com/filecoin-project/lotus/chain/sync.go:1185

    ):
    github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
        github.com/filecoin-project/lotus/chain/sync.go:1248
```

**Comment by Reiers** [comment]
Hi @Geo25rey 

Thanks for the report. The issue is outdated, and Im not seeing this in the [current version. ](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)

Read more about chain management here: https://lotus.filecoin.io/lotus/manage/chain-management/

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)
