### ISSUE TITLE
Feature request: list current proving tasks in lotus-miner sealing jobs?

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#4225]
This may be a bit unorthodox, so feel free to close if you think so. It would be nice though to have the proving tasks listed in the sealing jobs section to see how long it takes, when it was started, which node it's running on, etc.

**Comment by Reiers** [comment]
Hi
Thanks for the feature request. 
The current `lotus-miner sealing jobs` display all the above.
```
reiers@M1Max-protocol ~ % lotus-miner sealing jobs
ID        Sector  Worker    Hostname            Task  State    Time
```

Closing Lotus Issue Ticket.
