### ISSUE TITLE
  runPost failed: running window post failed:

### ISSUE THREAD

**Issue by 815943555** [filecoin-project/lotus#4228]
2020-10-06T03:48:44.639+0800    INFO    storageminer    storage/wdpost_run.go:579       computing window post   {"batch": 0, "elapsed": 13.376432883}
2020-10-06T03:48:44.639+0800    ERROR   storageminer    storage/wdpost_run.go:102       runPost failed: running window post failed:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
        /home/yuanyang/v081/lotus/storage/wdpost_run.go:591
  - sanity check failed
    github.com/filecoin-project/filecoin-ffi.GenerateWindowPoSt
        /home/yuanyang/v081/lotus/extern/filecoin-ffi/proofs.go:586
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).GenerateWindowPoSt
        /home/yuanyang/v081/lotus/extern/sector-storage/ffiwrapper/verifier_cgo.go:47
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
        /home/yuanyang/v081/lotus/storage/wdpost_run.go:576
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runGeneratePoST
        /home/yuanyang/v081/lotus/storage/wdpost_run.go:100
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).startGeneratePoST.func1
        /home/yuanyang/v081/lotus/storage/wdpost_run.go:84
    runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
2020-10-06T03:48:44.639+0800    ERROR   storageminer    storage/wdpost_run.go:46        Got err %!w(*xerrors.wrapError=&{running window post failed 0xc06d5d00a0 {[9261355 19515291 19497925]}}) - TODO handle errors
2020-10-06T03:48:44.639+0800    WARN    storageminer    storage/wdpost_changehandler.go:249     Aborted window post Proving (Deadline: &{CurrentEpoch:120697 PeriodStart:120705 Index:0 Open:120705 Close:120765 Challenge:120685 FaultCutoff:120635 WPoStPeriodDeadlines:48 WPoStProvingPeriod:2880 WPoStChallengeWindow:60 WPoStChallengeLookback:20 FaultDeclarationCutoff:70})

maybeSchedRequest didn't find any good workers
86.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
87.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
88.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
89.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemove]	{"User":{}}
90.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
91.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
92.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
93.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
94.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
95.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
96.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
97.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
98.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
99.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers
100.	2020-10-08 05:18:09 +0800 CST:	[event;sealing.SectorRemoveFailed]	{"User":{}}
	maybeSchedRequest didn't find any good workers

**Comment by jennijuju** [comment]
Please open a new ticket if you are running into this issue on the latest version of lotus!
