### ISSUE TITLE
The problem of pool synchronization

### ISSUE THREAD

**Issue by caokun8008** [filecoin-project/lotus#4239]
Found a problem: v0.8.1
Our account: "t3um2k7gqmpr5pg5jo4bbs2olk2sbkcoplgcouz6mc24vycocyfqnayuzs6jyjizbnnnrtdtbu7iqo6sterg3q" to send the transfer message. After the message enters the mpool, it will only be in the local mpool and will not be synchronized to other peers's mpool.
excuse me, can you tell me the reason?
We cleaned up the mpool once before, there was a gap in Nonce. Is it because of this reason? How can I solve this problem?

**Comment by rjan90** [comment]
This issue is related to having a too low gas-fee, so the message does not get included. This issue can probably be closed. #rengjøring
