### ISSUE TITLE
[Create Miner] on faucet page with "Too Many Requests" error

### ISSUE THREAD

**Issue by maobisheng** [filecoin-project/lotus#424]
It always failed when I use [Create Miner] on faucet page(https://lotus-faucet.kittyhawk.wtf/), I have tried many times and the got the same error message "Too Many Requests" about one or two minutes after I click sent fund button.
I also tried it again after one hour later with previous one, my destination address is t3wleig32pwixppfivc2rz3own34aht73moui34nlnokt2wqxtfnqq4f3mgk4pmbuwqv33jlhsha43hrpwn72q.

![image](https://user-images.githubusercontent.com/3703197/67146959-0486d300-f2c3-11e9-9dc5-9e0463b22df7.png)

**Comment by magik6k** [comment]
This is probably the browser trying to be too smart.

**Comment by maobisheng** [comment]
My browser version for your reference:

![image](https://user-images.githubusercontent.com/3703197/67147485-df489380-f2c7-11e9-8242-1f2cf30abfc7.png)

**Comment by eshon** [comment]
Is this a browser issue? I've tried this with Postman and curl with no timeout or really long timeouts and still get the same response.

**Comment by maobisheng** [comment]
> Is this a browser issue? I've tried this with Postman and curl with no timeout or really long timeouts and still get the same response.

Maybe, you can reproduce this issue with Chrome.

**Comment by jacktang** [comment]
same problem here

**Comment by eshon** [comment]
Was able to get it working using Firefox as someone mentioned in Slack

**Comment by travisperson** [comment]
Closing to track in #517
