### ISSUE TITLE
Can't get fil from https://spacerace.faucet.glif.io

### ISSUE THREAD

**Issue by gongruihua** [filecoin-project/lotus#4242]
![image](https://user-images.githubusercontent.com/8190878/95467671-5337ec00-09b0-11eb-8f44-195dfb8048c4.png)

**Comment by jennijuju** [comment]
Sorry that glif faucet is not working for you, however, this is not a lotus issue.

**Comment by gongruihua** [comment]
> Sorry that glif faucet is not working for you, however, this is not a lotus issue.

where do I need to get fil now?
