### ISSUE TITLE
About update releases - FR not important...

### ISSUE THREAD

**Issue by PatrickDeuse** [filecoin-project/lotus#4244]
ignore this issue if there is critical stuff to implement before the mainnet launch. it's just a feature request!

As background reference:

https://filecoinproject.slack.com/archives/C019UFEACBT/p1602131880371900?thread_ts=1602131186.370200&cid=C019UFEACBT

As mentioned in the slack thread it would be nice to have a centralized point to get all the information that is needed to comprehend the full range of changes when an update is released in a machine readable form.

i currently have an almost 2 month old todo on my list that says: go version marker file

the idea was to have a file in the lotus repo that basically defines the go version that is needed to build the lotus software components. over the last 2 month it became clear that this could be "implemented" for rust too, and so on. all the tools that need to be up to version XY before building lotus. 

thats the background. now i realize that it would be even better to not only have files for the tools but for the release itself. i have a json file in mind that holds all the information needed to update in time and have the right tools available without the need to stalk slack, commit comments etc. 

> {
> "id": "somekinfofhashorsomethingthatmakesthisreleaseid-able",
> "newVersion" : "2.6.7",
> "releaseDate" : "eitherEpoch or date",
> "frozenAtCommit" :"sfjhsbdkfjsdkg99384",
> "mustHaveUpdate" : true,
> "minBaseVersion": "1.3.4",
> "changesBuildProcess" : false,
> "epochs" : {
>     "notBefore": "epochABC", 
>    "notAfter": "epochXYZ"
> },
> "updates": {
>    "miner" : false,
>     "daemon" : false,
>     "worker" : true
> },
> "restarts": {
>    "miner" : true,
>     "daemon" : true,
>     "worker" : true
> },
> "tools" : {
>     "golang" : {
>         "minV" : "1.14.1",
>         "maxV" : "1.15.2",
>         "recommended" : "1.15.1"
>     }
> [....cut...same for all the tools...]
> }
> [...there might be more...]
> }

just as an example of what is in my mind. still a bit cloudy what exact information is "must have" and what is just "nice to have". names choosen for clarity, i when implementing there might be nicer ways to name the objects... 

Why? Some of the miners are running massive systems and automated updates will save a lot of work/time. 

I mentioned it quite a few times now in the slack conversations about updates: A proper planable release cycle for non critical updates would be nice! Is there already anything in the making @ filecoin team?

We would build a system to provide the file ourselves - but we are obviously missing the information before the actual release to build a file acompanying an update...

thanks for the time

**Comment by dineshshenoy** [comment]
I like this idea but simplify to a single golang version and base version?  Ideally, we'd have less permutations out in the field.
