### ISSUE TITLE
Miner should handle full disk space issue

### ISSUE THREAD

**Issue by maobisheng** [filecoin-project/lotus#425]
First, I start mining with command:
`nohup lotus-storage-miner run > mining.log 2>&1 &`

Then I prepare a simple shell script named 'mining-lotus.sh'.
`
while true
do
	echo ============$(date "+%Y-%m-%d %H:%M:%S")============
	lotus-storage-miner store-garbage
	lotus-storage-miner info
	sleep 10
done
`
Last, run the shell script:
`nohup ./mining-lotus.sh > mining-lotus.log 2>&1 &`

And the node has stop mining with below exception about 8 hours about I start mining. 
![image](https://user-images.githubusercontent.com/3703197/67152845-98cb5700-f310-11e9-9e9d-72c7049435f1.png)

When I try to execute `lotus-storage-miner run` command on the exception node, it return fault result with:
2019-10-19T23:23:36.140Z	[34mINFO[0m	badger	badger@v1.6.0-rc1/logger.go:46	Compaction for level: 0 DONE
2019-10-19T23:23:36.140Z	[34mINFO[0m	badger	badger@v1.6.0-rc1/logger.go:46	Force compaction on level 0 done
2019-10-19T23:23:36.141Z	[33mWARN[0m	main	lotus-storage-miner/main.go:71	miner.Register called more than once for actor 't0384'.

My question is:
1. Is it a bug for "lotus-storage-miner/main.go:71	handler: websocket connection closed"?
2. How to resume mining on the same node when the node has exception?

**Comment by whyrusleeping** [comment]
This looks like the lotus-storage-miner process exited unexpectedly. Can you check your mining.log file and see if there is anything there?

To restart mining please restart your lotus daemon and try the mining process again

**Comment by maobisheng** [comment]
mining.log was lost when I re-run the start mining command.

**Comment by maobisheng** [comment]
I try to restart lotus daemon and try the mining process again.
The mining process dump again, below is the detail log for reference.
[mining.log](https://github.com/filecoin-project/lotus/files/3747495/mining.log)

**Comment by maobisheng** [comment]
The root cause was found.
Thanks.
![image](https://user-images.githubusercontent.com/3703197/67155280-8536e500-f33e-11e9-886a-42838bc1e34c.png)

**Comment by whyrusleeping** [comment]
@dignifiedquire got a panic coming from rust here

**Comment by maobisheng** [comment]
> @dignifiedquire got a panic coming from rust here

Lotus mining program should works well even the disk is full.
I just reopen the bug.

**Comment by linmuqin** [comment]
> The root cause was found.
> Thanks.
> ![image](https://user-images.githubusercontent.com/3703197/67155280-8536e500-f33e-11e9-886a-42838bc1e34c.png)

Hello! I get the problem as you,What should i do now?

**Comment by jennijuju** [comment]
Things got improved a lot since this ticket was open - please create a new issue if you are still running into it with the latest lotus release!
