### ISSUE TITLE
Miner.lastWork should be Miner.work

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4257]
https://github.com/filecoin-project/lotus/blob/2d3b61675b93b977b299eae29945599c26f38cd2/miner/miner.go#L94
https://github.com/filecoin-project/lotus/blob/2d3b61675b93b977b299eae29945599c26f38cd2/miner/miner.go#L284
base.NullRounds++  namely lastWork.NullRounds++

**Comment by TippyFlitsUK** [comment]
Hi @zgfzgf 

Thanks for the report. We need more information about the issue before taking action. 
Please provide (miner logs, daemon log, worker logs) and repro steps.

Thank you !
