### ISSUE TITLE
The daemon load is high, causing synchronization abnormalities

### ISSUE THREAD

**Issue by abortrao** [filecoin-project/lotus#4259]
**Describe the bug**

 sometimes the load of my daemon is very high, and then the daemon becomes abnormal and has to be restarted to solve it.

lotus version

    lotus version 0.9.0+git.94beb5c34.dirty

load image

![image](https://user-images.githubusercontent.com/45277734/95540280-09d4b480-0a23-11eb-9c26-c13c6654325c.png)

slack info
[Detailed Description is here ](https://filecoinproject.slack.com/archives/C0179RNEMU4/p1602213444322000)

**Comment by rjan90** [comment]
I think this issue can be closed since the daemon on newer versions of Lotus is not experiencing this load jump. #rengjøring

**Comment by jennijuju** [comment]
Please open a new ticket if you are running into this issue on the latest version of lotus!
