### ISSUE TITLE
How to query the deal's status?

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/lotus#426]
I got a problem when post a deal to the miner.

I made a deal with the following script:

```bash
~$ lotus client query-ask t0394
Ask: t0394
Price per Byte: 3
~$ echo "Hi my name is $USER" > hello.txt
~$ lotus client import ./hello.txt 
bafkreifgxbfutlcrbfnwpk5gx6o5of4mpleqvbkt5thphvbnsg6mnasp3q
~$ lotus client local
bafkreifgxbfutlcrbfnwpk5gx6o5of4mpleqvbkt5thphvbnsg6mnasp3q hello.txt 23 ok
~$ lotus client deal bafkreifgxbfutlcrbfnwpk5gx6o5of4mpleqvbkt5thphvbnsg6mnasp3q t0394 3 10
bafyreibcvxlzzfqgwic3tyuayndgctzszttnnyemlbn4e7us6iimcd3mvi
```
It looks like the deal is submit successfully. But i got an error in miner's console.

```bash
2019-10-20T06:52:17.187+0800	INFO	deals	deals/handler.go:165	Deal bafyreibcvxlzzfqgwic3tyuayndgctzszttnnyemlbn4e7us6iimcd3mvi updated state to 2
2019-10-20T06:52:17.196+0800	INFO	deals	deals/handler_states.go:155	waiting for channel message to appear on chain
2019-10-20T06:52:17.217+0800	INFO	deals	deals/handler.go:165	Deal bafyreibcvxlzzfqgwic3tyuayndgctzszttnnyemlbn4e7us6iimcd3mvi updated state to 5
2019-10-20T06:52:17.217+0800	ERROR	deals	deals/handler.go:167	deal bafyreibcvxlzzfqgwic3tyuayndgctzszttnnyemlbn4e7us6iimcd3mvi failed: minimum price: 690
github.com/filecoin-project/lotus/chain/deals.(*Handler).onUpdated
	/var/www/go/src/lotus/chain/deals/handler.go:167
github.com/filecoin-project/lotus/chain/deals.(*Handler).Run.func1
	/var/www/go/src/lotus/chain/deals/handler.go:135
2019-10-20T06:52:17.219+0800	ERROR	deals	deals/handler_utils.go:30	deal bafyreibcvxlzzfqgwic3tyuayndgctzszttnnyemlbn4e7us6iimcd3mvi failed: minimum price: 690
github.com/filecoin-project/lotus/chain/deals.(*Handler).failDeal
	/var/www/go/src/lotus/chain/deals/handler_utils.go:30
github.com/filecoin-project/lotus/chain/deals.(*Handler).onUpdated
	/var/www/go/src/lotus/chain/deals/handler.go:168
github.com/filecoin-project/lotus/chain/deals.(*Handler).Run.func1
	/var/www/go/src/lotus/chain/deals/handler.go:135
```

Obviously, the deal creation failed, due to the lower price.
My questions are:
1. Since minimum price is 690, why the `lotus client query-ask t0394` got `Price per Byte: 3`?  what the meaning of `Price per Byte: 3`?
2. I want to know how to get the deal's status if i don't watch the console log. Is any tools or command to do it?

**Comment by magik6k** [comment]
There is an API call for that: https://github.com/filecoin-project/lotus/blob/1bf713cb0aeee78367f9bfeb30d9365a4c215e65/api/api.go#L105
but there is no command which exposes it on the cli

(the pond UI uses that api to show deal statuses)

**Comment by magik6k** [comment]
for now you can call the api manually with `curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0","method":"Filecoin.ClientListDeals","params":[],"id":0}' "http://127.0.0.1:1234/rpc/v0?token=$(./lotus auth create-admin-token)"`

**Comment by yangjian102621** [comment]
@magik6k 
Thanks.
Will `Filecoin.ClientListDeals` api return all deals of the chain? 
Is there an api that can return the specified deal by the message hash?

**Comment by magik6k** [comment]
`ClientListDeals` only returns deals made by the node you are calling this method on. Currently deals are off-chain, so there is no easy way to list deals across the network right now.

That said, we are moving deals on-chain - https://github.com/filecoin-project/lotus/pull/415 - so that will change relatively soon.

**Comment by yangjian102621** [comment]
@magik6k 
Okay, i got it. Thank you.
