### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wellhealth** [filecoin-project/lotus#4264]
Daemon:  0.9.0+git.f08c04f6.dirty+api0.16.0

**Screenshots**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xdc1e86]

goroutine 44135593 [running]:
github.com/filecoin-project/lotus/chain/types.(*SignedMessage).Cid(0x0, 0x0, 0x0)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/types/signedmessage.go:31 +0x26
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateMsgMeta(0xc14243a410, 0xc1152fc840, 0xc20b0c2e00, 0x0)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:327 +0x23b
github.com/filecoin-project/lotus/chain.(*Syncer).InformNewHead(0xc14243a410, 0xc1d4bdffb0, 0x26, 0xc0d218fed0, 0xc0d218feb0)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:236 +0x24a
github.com/filecoin-project/lotus/chain.(*Syncer).InformNewBlock(...)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/sync.go:378
github.com/filecoin-project/lotus/chain/sub.HandleIncomingBlocks.func1(0x3498560, 0xc14f90a4c0, 0x861c46800, 0x34b31c0, 0xc150ec44b0, 0xc19b16e6c0, 0xc1d590d0e0, 0x26, 0xc21d363980, 0xc14243a410, ...)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/sub/incoming.go:99 +0x91f
created by github.com/filecoin-project/lotus/chain/sub.HandleIncomingBlocks
        /root/golang/gopath/src/github.com/filecoin-project/lotus/chain/sub/incoming.go:71 +0x187

**Version (run `lotus version`):**
Daemon:  0.9.0+git.f08c04f6.dirty+api0.16.0
**Additional context**

**Comment by rjan90** [comment]
Hi @wellhealth!

Thanks for the report. The issue is outdated now, and not relevant anymore.

If this is a issue in current release please open a new ticket.

Thanks again !
