### ISSUE TITLE
Failed getting beacon entry: drand failed Get request: no valid clients 

### ISSUE THREAD

**Issue by coder-lb** [filecoin-project/lotus#4267]
## Problems

Sometimes it's hard to connect drand servers. Today after upgrading to 0.9.0, it takes about two hours to connect drand servers. 

`failed getting beacon entry: drand failed Get request: no valid clients - doing request: Get "https://api.drand.sh/public/226302": context deadline exceeded - doing request: Get "https://api2.drand.sh/public/226302": context deadline exceeded - doing request: Get "https://api3.drand.sh/public/226302": context deadline exceeded`

## Version
0.9.0

**Comment by deeptuuk** [comment]
same error, Do you have a solution now?

**Comment by jennijuju** [comment]
@deeptuuk could you please share the exact error logs?
