### ISSUE TITLE
Add --chain cli feature to support between chains

### ISSUE THREAD

**Issue by mFarghaly** [filecoin-project/lotus#4277]
Please add a CLI flag for `--chain` to switch between networks instead of compiling multiple binaries and building Docker images for each network.

```
$ lotus # connect by default to mainnet
$ lotus --chain testnet
$ lotus --chain nerpa
$ lotus --chain butterfly
```

Most blockchain protocols clients like Ethereum and Bitcoin has a flag or CLI option for switching between different networks.

**Comment by dineshshenoy** [comment]
This seems like it could be a dangerous operation.  Do we need to reset the node or should it be in a config file?

**Comment by rjan90** [comment]
I think this issue can be closed now as this has been merged? #rengjøring
