### ISSUE TITLE
lotus-miner logs "proposal doesn't exist in state store"

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4279]
With lotus 0.9.0, many miners see the following error in the log

```
2020-10-09T02:39:37.614+0200 ERROR storagemarket_impl impl/provider.go:450 proposal doesn't exist in state store: No state for /bafyreibdlxaxbyvdsie7ejamlgjxfbtc4llhv2yseoelbphprxsezkfqk4: datastore: key not found
```

I've confirmed that miners who has never removed any repo or datastore is also seeing this issue.

Also I think that `/` before the CID is a little bit concerning.

**Comment by kernelogic** [comment]
I'd really like to know how to repair a error message like this (but I admit I have removed datastore before). I still have the CID.

**Comment by PatrickDeuse** [comment]
this ends in an infinite loop of whatever trying to find the proposals...

**Comment by dineshshenoy** [comment]
Patrick - can you clarify in what situations you're seeing this issue today?

**Comment by PatrickDeuse** [comment]
data corruption. ~40 lost sectors with deals. lost like in: they were on chain and in the store storage - the miner dropped them after getting back online (and pledging to sync up the "sector number"), see https://github.com/filecoin-project/lotus/issues/5358 

now the log is looping 

`{"level":"error","ts":"2025-01-18T28:67:79.241Z","logger":"storagemarket_impl","caller":"impl/provider.go:466","msg":"proposal doesn't exist in state store: No state for /bafyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: datastore: key not found"}`

messages. by the thousands...

**Comment by jennijuju** [comment]
@raulk @aarshkshah1992 @nonsense Do you think this can be closed with the improvements in the newer lotus and dagstore?

**Comment by TippyFlitsUK** [comment]
Hey @raulk @aarshkshah1992 @nonsense

Would you mind responding to @jennijuju's message above?

Many thanks!

**Comment by f8-ptrk** [comment]
With lotus 0.9.0,......................
