### ISSUE TITLE
Reimported wallet cannot be deleted

### ISSUE THREAD

**Issue by cerblue** [filecoin-project/lotus#4283]
**Describe the bug**
A Lotus wallet cannot be deleted if the same wallet address has been present in Lotus. 'lotus wallet delete' fails with the following message:

`ERROR: failed to mark key f3BLAHBLAH as trashed: checking key before put 'trash-f3BLAHBLAH': key already exists`

**To Reproduce**
1. Create a new wallet: `lotus wallet new bls`
2. Export the key:` lotus wallet export (wallet address) > wallet-key`
3. Delete the wallet: `lotus wallet delete (wallet address)`
4. Import the key: `lotus wallet import wallet-key`
5. Delete the wallet again: `lotus wallet delete (wallet address)`

**Expected behavior**
The wallet is deleted from Lotus.

**Screenshots**
\-

**Version (run `lotus version`):**
Daemon:  0.9.0+git.8f35a5c03.dirty+api0.16.0
Local: lotus version 0.9.0+git.8f35a5c03.dirty

**Additional context**
\-

**Comment by cerblue** [comment]
Related: https://github.com/filecoin-project/lotus/issues/1939

**Comment by arajasek** [comment]
Closed by #4589
