### ISSUE TITLE
GenerateSingleVanillaProof Occur Bug

### ISSUE THREAD

**Issue by RustMan88** [filecoin-project/lotus#4284]
**Describe the bug**
occur one bug when test GenerateSingleVanillaProof. 

**To Reproduce**
1. integration test GenerateSingleVanillaProof
2. See error
`2020-10-10T08:51:44.459 INFO filcrypto::proofs::api > generate_single_vanilla_proof: start
2020-10-10T08:51:44.464 INFO filecoin_proofs::api::post > generate_single_vanilla_proof:start: SectorId(8000256)
2020-10-10T08:51:44.718 INFO filecoin_proofs::api::post > generate_single_vanilla_proof:finish: SectorId(8000256)
2020-10-10T08:51:44.718 INFO filcrypto::proofs::api > generate_single_vanilla_proof: finish
unexpected fault address 0x6100
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6100 pc=0x58e625]

goroutine 194 [running]:
runtime.throw(0x267c756, 0x5)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000e71110 sp=0xc000e710e0 pc=0x557412
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:727 +0x405 fp=0xc000e71140 sp=0xc000e71110 pc=0x56d045
runtime.memmove(0xc0135e1500, 0x0, 0x6180)
	/usr/local/go/src/runtime/memmove_amd64.s:332 +0x3c5 fp=0xc000e71148 sp=0xc000e71140 pc=0x58e625
runtime.gostringn(0x0, 0x6180, 0x0, 0x93cbf5d49a1e5a05)
	/usr/local/go/src/runtime/string.go:334 +0x74 fp=0xc000e71198 sp=0xc000e71148 pc=0x573034
github.com/filecoin-project/filecoin-ffi._Cfunc_GoStringN(...)
	_cgo_gotypes.go:67
github.com/filecoin-project/filecoin-ffi.toGoStringCopy(...)
	/var/.workspace/lotus/extern/filecoin-ffi/proofs.go:1011
github.com/filecoin-project/filecoin-ffi.GenerateSingleVanillaProof(0x3, 0x7a1300, 0xc012d1dbf0, 0x28, 0xc0131b8450, 0x2d, 0x8, 0xc0131b8420, 0x2e, 0xc012ed4cd0, ...)
`

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
lotus v0.9.0
**Additional context**

**Comment by rjan90** [comment]
Closing this issue as outdated.
