### ISSUE TITLE
miner crashed with out of memory because of badger?

### ISSUE THREAD

**Issue by jackoelv** [filecoin-project/lotus#4288]
**Describe the bug**
miner machine with 256GB memory.
when start miner, I saw the memory of miner grows up from 0.1% continuously to 80% of the machine. hours later ,it crashed because out of memory.
this happened in the version 0.9.0.

I find some logs like this:
![截屏2020-10-10 上午10 07 19](https://user-images.githubusercontent.com/10348409/95643298-ef611080-0ae0-11eb-9bde-f119b6b9f5b0.png)

when badger continously writes vlog to memtable, miner`s memory continously grows up to 80% from 0.1%.
what is the problem?

crashed log:
![截屏2020-10-10 上午10 10 27](https://user-images.githubusercontent.com/10348409/95643282-da847d00-0ae0-11eb-924f-dc2267271704.png)

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
lotus-miner version 0.9.0

**Additional context**

**Comment by jackoelv** [comment]
![截屏2020-10-10 下午6 11 45](https://user-images.githubusercontent.com/10348409/95652624-06c1ed00-0b25-11eb-9901-3898ff5d50d0.png)

**Comment by jackoelv** [comment]
256GB memory and 256GB Swap. 94% memory used. 
Is there some cache mechanism to maximize use of memory?
miner crashed last night because of out of memory. This never happened before upgrade to miner 0.9.0.

**Comment by rjan90** [comment]
I think this issue has been fixed on newer versions of Lotus? #rengjøring

**Comment by jennijuju** [comment]
Please open a new ticket if you are running into this issue on the latest version of lotus!
