### ISSUE TITLE
Block synchronization State: error

### ISSUE THREAD

**Issue by HYHRainman** [filecoin-project/lotus#4292]
sync status:
worker 0:
	Base:	[bafy2bzaceagfiivtofkon2awfpk2boes2q7ku6kr4ezvx4byzcg27tvbxfr7q bafy2bzaceczh263ieouemn7amyndeux7yxlfazqahwgudhpzwxapprvvfhbqw bafy2bzacec4cyf2ile6wnmoyovdybt76xcumfbgzxomm3fndmdnaytxptu6xq]
	Target:	[bafy2bzacebaiec6rg43j5de6ayedlyievwtvpcn2dvbnrz3z65wva4zcbcids bafy2bzacect435tyahk5fbgonbgxcp5mnlmbh3jejmanntwz624xjj5jwbbaw] (116366)
	Height diff:	59365
	Stage: error
	Height: 116366
	Elapsed: 28.091824772s
	Error: chain contained block marked previously as bad ([bafy2bzacebaiec6rg43j5de6ayedlyievwtvpcn2dvbnrz3z65wva4zcbcids bafy2bzacect435tyahk5fbgonbgxcp5mnlmbh3jejmanntwz624xjj5jwbbaw], bafy2bzaceb5itcbvuu6mqz4th26mngrdis4kcpv4ypw7nlsijesdtkq4on23m) (reason: change contained bafy2bzacecoorklpheylwuebirivtilhqpebh2f47z7zt6chbvq2afoan2ubg caused by: [bafy2bzaceasgvrbuhl5ciqes6zqeawv5lptoo4z6nrghveqeihr5rhuqz6rmk] failed to compute lookback tipset state: failed to look up from actor: address resolution: loading init actor state: blockstore: block not found)
worker 1:
	Base:	[bafy2bzaceagfiivtofkon2awfpk2boes2q7ku6kr4ezvx4byzcg27tvbxfr7q bafy2bzaceczh263ieouemn7amyndeux7yxlfazqahwgudhpzwxapprvvfhbqw bafy2bzacec4cyf2ile6wnmoyovdybt76xcumfbgzxomm3fndmdnaytxptu6xq]
	Target:	[bafy2bzacecykcim5k2xdsfrxftuxhibtzwzypqelha7letaxhywuzlgrpaj3k bafy2bzacebfbqnisrzyz65v2jqk3gdcncaiqm6mmbwpjepenzt6myvwbnz542 bafy2bzacebrpwi6dh6wtgyvkvtf7r6b3lslfwcsdanfakkiwh7zsgff2qd3kq bafy2bzacedxnofy5adaygjoqyoe3fv3cki7ne64lw5x37qgrnokxricaw2nug bafy2bzaceazhjuul4zksa423mihwgq437igbvguiz63t7aclhk4fzzhezpkiw] (103849)
	Height diff:	46848
	Stage: error
	Height: 103849
	Elapsed: 14.821004555s
	Error: chain contained block marked previously as bad ([bafy2bzacecykcim5k2xdsfrxftuxhibtzwzypqelha7letaxhywuzlgrpaj3k bafy2bzacebfbqnisrzyz65v2jqk3gdcncaiqm6mmbwpjepenzt6myvwbnz542 bafy2bzacebrpwi6dh6wtgyvkvtf7r6b3lslfwcsdanfakkiwh7zsgff2qd3kq bafy2bzacedxnofy5adaygjoqyoe3fv3cki7ne64lw5x37qgrnokxricaw2nug bafy2bzaceazhjuul4zksa423mihwgq437igbvguiz63t7aclhk4fzzhezpkiw], bafy2bzacedzvj7eni7xqoupkuedx5uxxnczcj3bk4u4qx2mhbub76hh6er7z4) (reason: linked to bafy2bzacedm7ysujr4ijs7xwwp6bdj2gjstpbrpjyedylh6xwytscr5qyug7y caused by: [bafy2bzaceasgvrbuhl5ciqes6zqeawv5lptoo4z6nrghveqeihr5rhuqz6rmk] failed to compute lookback tipset state: failed to look up from actor: address resolution: loading init actor state: blockstore: block not found)
worker 2:
	Base:	[bafy2bzaceagfiivtofkon2awfpk2boes2q7ku6kr4ezvx4byzcg27tvbxfr7q bafy2bzaceczh263ieouemn7amyndeux7yxlfazqahwgudhpzwxapprvvfhbqw bafy2bzacec4cyf2ile6wnmoyovdybt76xcumfbgzxomm3fndmdnaytxptu6xq]
	Target:	[bafy2bzacecf6k4h3p4j2xr635m5dikz66sqhd7cmxe34ijjrruj4mvzc273qy bafy2bzacedyef5qvnclv6fsaybgn4ki2exx2kuk4onjc4xn4hklp6gjckpxrg bafy2bzacedwph7k3ezs3bd4zlppulv7ykp55xvyqev3mtyr2d2dims2qj3rb4 bafy2bzacebufuxz2pyprjpkd3mxold4bflzhqoxyb7wjqrxlqg7nnauykzosm bafy2bzaced7wmunozlfmfirxkbnfoyigcuvgxrm2ii6r3zwdn6x2m3t42phjy] (70231)
	Height diff:	13230
	Stage: error
	Height: 70231
	Elapsed: 3.118315023s
	Error: chain contained block marked previously as bad ([bafy2bzacecf6k4h3p4j2xr635m5dikz66sqhd7cmxe34ijjrruj4mvzc273qy bafy2bzacedyef5qvnclv6fsaybgn4ki2exx2kuk4onjc4xn4hklp6gjckpxrg bafy2bzacedwph7k3ezs3bd4zlppulv7ykp55xvyqev3mtyr2d2dims2qj3rb4 bafy2bzacebufuxz2pyprjpkd3mxold4bflzhqoxyb7wjqrxlqg7nnauykzosm bafy2bzaced7wmunozlfmfirxkbnfoyigcuvgxrm2ii6r3zwdn6x2m3t42phjy], bafy2bzaceasgvrbuhl5ciqes6zqeawv5lptoo4z6nrghveqeihr5rhuqz6rmk) (reason: failed to compute lookback tipset state: failed to look up from actor: address resolution: loading init actor state: blockstore: block not found)

**Comment by zhangsj** [comment]
same status
