### ISSUE TITLE
After lotus send,canot find this cid in the chain

### ISSUE THREAD

**Issue by jlinzhou** [filecoin-project/lotus#4295]

**Comment by DreamHackchosenone** [comment]
请问下你在哪里领取的测试网代币？
https://spacerace.faucet.glif.io/这个网站一直是”Processing your Filecoin transaction“
https://faucet.nerpa.interplanetary.dev/funds.html
https://faucet.butterfly.fildev.network/
这两个网站没用

**Comment by jlinzhou** [comment]
> 请问下你在哪里领取的测试网代币？
> https://spacerace.faucet.glif.io/ 这个网站一直是”Processing your Filecoin transaction“
> https://faucet.nerpa.interplanetary.dev/funds.html
> https://faucet.butterfly.fildev.network/
> 这两个网站没用

**Comment by jlinzhou** [comment]
> 请问下你在哪里领取的测试网代币？
> https://spacerace.faucet.glif.io/ 这个网站一直是”Processing your Filecoin transaction“
> https://faucet.nerpa.interplanetary.dev/funds.html
> https://faucet.butterfly.fildev.network/
> 这两个网站没用

我9月30号领的，但今天又尝试了一下领不了了，不知道是什么问题。然后我本地的钱包也转账上不了链。

**Comment by DreamHackchosenone** [comment]
> > 请问下你在哪里领取的测试网代币？
> > https://spacerace.faucet.glif.io/ 这个网站一直是”Processing your Filecoin transaction“
> > https://faucet.nerpa.interplanetary.dev/funds.html
> > https://faucet.butterfly.fildev.network/
> > 这两个网站没用
> 
> 我9月30号领的，但今天又尝试了一下领不了了，不知道是什么问题。然后我本地的钱包也转账上不了链。

好的，多谢回复

**Comment by DreamHackchosenone** [comment]
> > 请问下你在哪里领取的测试网代币？
> > https://spacerace.faucet.glif.io/ 这个网站一直是”Processing your Filecoin transaction“
> > https://faucet.nerpa.interplanetary.dev/funds.html
> > https://faucet.butterfly.fildev.network/
> > 这两个网站没用
> 
> 我9月30号领的，但今天又尝试了一下领不了了，不知道是什么问题。然后我本地的钱包也转账上不了链。

我测试能在链上找到，用的这两个方法WalletSignMessage, MpoolPush，如果返回cid了是不是gas太低没被打包，或者还没到高度？

**Comment by jlinzhou** [comment]
今天我更新了一下，转账可以了😄



---Original---

**Comment by DreamHackchosenone** [comment]
> 今天我更新了一下，转账可以了😄
> […](#)
> ---Original--- From: "钟浩"<notifications@github.com&gt; Date: Mon, Oct 12, 2020 18:06 PM To: "filecoin-project/lotus"<lotus@noreply.github.com&gt;; Cc: "State change"<state_change@noreply.github.com&gt;;"jlinzhou"<772945866@qq.com&gt;; Subject: Re: [filecoin-project/lotus] After lotus send,canot find this cid in the chain (#4295) 请问下你在哪里领取的测试网代币？ https://spacerace.faucet.glif.io/ 这个网站一直是”Processing your Filecoin transaction“ https://faucet.nerpa.interplanetary.dev/funds.html https://faucet.butterfly.fildev.network/ 这两个网站没用 我9月30号领的，但今天又尝试了一下领不了了，不知道是什么问题。然后我本地的钱包也转账上不了链。 我测试能在链上找到，用的这两个方法WalletSignMessage, MpoolPush，如果返回cid了是不是gas太低没被打包，或者还没到高度？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

你用什么来判断一笔交易的状态呢？我用StateGetReceipt这个方法，但是我传message_id和父区块的所有id一直返回给我null

**Comment by xw332** [comment]
@jlinzhou @DreamHackchosenone 
你们节点都是自己搭在本地吗，有没有公用的节点支持转账的？

**Comment by jlinzhou** [comment]
我也是nil，我现在交易又发不出去了，mpoolpush有返回cid

---Original---

**Comment by DreamHackchosenone** [comment]
> 我也是nil，我现在交易又发不出去了，mpoolpush有返回cid
> […](#)
> ---Original--- From: "钟浩"<notifications@github.com&gt; Date: Tue, Oct 13, 2020 12:54 PM To: "filecoin-project/lotus"<lotus@noreply.github.com&gt;; Cc: "State change"<state_change@noreply.github.com&gt;;"jlinzhou"<772945866@qq.com&gt;; Subject: Re: [filecoin-project/lotus] After lotus send,canot find this cid in the chain (#4295) 今天我更新了一下，转账可以了😄 … ---Original--- From: "钟浩"<notifications@github.com&gt; Date: Mon, Oct 12, 2020 18:06 PM To: "filecoin-project/lotus"<lotus@noreply.github.com&gt;; Cc: "State change"<state_change@noreply.github.com&gt;;"jlinzhou"<772945866@qq.com&gt;; Subject: Re: [filecoin-project/lotus] After lotus send,canot find this cid in the chain (#4295) 请问下你在哪里领取的测试网代币？ https://spacerace.faucet.glif.io/ 这个网站一直是”Processing your Filecoin transaction“ https://faucet.nerpa.interplanetary.dev/funds.html https://faucet.butterfly.fildev.network/ 这两个网站没用 我9月30号领的，但今天又尝试了一下领不了了，不知道是什么问题。然后我本地的钱包也转账上不了链。 我测试能在链上找到，用的这两个方法WalletSignMessage, MpoolPush，如果返回cid了是不是gas太低没被打包，或者还没到高度？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. 你用什么来判断一笔交易的状态呢？我用StateGetReceipt这个方法，但是我传message_id和父区块的所有id一直返回给我null — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

昨天又发了个0.10的版本，你下载试试，同行加个微信能不能交流下？我主页有邮箱
