### ISSUE TITLE
Benchmarks for chain processing

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#43]
We should construct a set of synthetic benchmarks for chain processing.

Some initial ones i'd like to see:

1. process a 100,000 block chain, with no messages
2. process a 100,000 block chain, with N={1,10,100,1000,10000} messages per block
  - messages just moving money to random accounts
  - different benchmarks for messages signed with BLS vs secp256k1 vs some mixture
3. process a chain with N={1,10,100,1000} sector commitments messages per block
4. process a chain with N={1,10,100,1000} payment channel operations (opens/updates/closes)

More later for sure, but this is a good start.

**Comment by jennijuju** [comment]
might be stale, but could need a review before closing.
