### ISSUE TITLE
Lotus daemon crached with "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by rshellnet** [filecoin-project/lotus#4303]
Lotus daemon crashed with error.

Reproduce:
1. Run "lotus daemon"

**Expected behavior**
To work

**Version (run `lotus version`):**
lotus version 0.9.0+git.8f35a5c0

**Additional context**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xde17a6]

goroutine 12873434 [running]:
github.com/filecoin-project/lotus/chain/types.(*SignedMessage).Cid(0x0, 0xc047cc3ec0, 0x26)
        /usr/src/lotus/chain/types/signedmessage.go:31 +0x26
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateMsgMeta(0xc03238eb60, 0xc10c4802c0, 0xc0859c1220, 0x0)
        /usr/src/lotus/chain/sync.go:327 +0x23b
github.com/filecoin-project/lotus/chain.(*Syncer).InformNewHead(0xc03238eb60, 0xc07198ff50, 0x26, 0xc1c4d93ed0, 0xc06ca3deb0)
        /usr/src/lotus/chain/sync.go:236 +0x24a
github.com/filecoin-project/lotus/chain.(*Syncer).InformNewBlock(...)
        /usr/src/lotus/chain/sync.go:378
github.com/filecoin-project/lotus/chain/sub.HandleIncomingBlocks.func1(0x30fe300, 0xc02d524e40, 0x861c46800, 0x3117120, 0xc03651b800, 0xc0786d04c0, 0xc04c182f90, 0x26, 0xc08d8d9b90, 0xc03238eb60, ...)
        /usr/src/lotus/chain/sub/incoming.go:99 +0x91f
created by github.com/filecoin-project/lotus/chain/sub.HandleIncomingBlocks
        /usr/src/lotus/chain/sub/incoming.go:71 +0x187

**Comment by Kubuxu** [comment]
Update to 0.9.1
This issue is resolved there.
