### ISSUE TITLE
Error when deleting wallet

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#4306]
**Describe the bug**
Error when trying to delete a wallet address

**To Reproduce**
1. lotus wallet delete "t3-address"
2. Get error-message: "ERROR: failed to mark key  "t3-address"  as trashed: checking key before put 'trash- "t-3address" ': key already exists
3. Wallet address still in lotus wallet list.

**Expected behavior**
Expected the command to remove the address from my wallet.

**Version (run `lotus version`):**
Daemon:  0.9.0+git.8f35a5c0+api0.16.0
Local: lotus version 0.9.0+git.8f35a5c0

**Comment by KaptinLin** [comment]
It didn't working on 0.10.2
