### ISSUE TITLE
PreCommit2 worker does not use or respect GPU lock

### ISSUE THREAD

**Issue by cerblue** [filecoin-project/lotus#4309]
**Describe the bug**
PreCommit2 worker does not use GPU lock, which Commit2 worker and miner (for PoSt) use to synchronize GPU usage. As a result, PC2 task will not relinquish GPU to PoSt task, and the latter gets slowed down. For WindowPoSts, this may cause mining power loss.

**To Reproduce**
1. Run Lotus miner and PC2 worker on the same machine
2. Have the miner to schedule a PC2 task to the worker, 10~15 minutes before proving deadline window opens.
3. Wait for proving deadline window open.
4. Miner logs will show memory allocation failure errors, and WindowPoSt task runs slow.

**Expected behavior**
PC2 task relinquishes the GPU so that WindowPoSt task alone can utilize the GPU.

**Screenshots**

**Version (run `lotus version`):**
`Daemon:  0.9.0+git.8f35a5c03.dirty+api0.16.0`
`Local: lotus version 0.9.0+git.8f35a5c03.dirty`

**Additional context**

**Comment by jennijuju** [comment]
should be resolved with the correct flags set using the latest lotus.
