### ISSUE TITLE
Lotus node does not sync and API does not start when running daemon

### ISSUE THREAD

**Issue by tchardin** [filecoin-project/lotus#4326]
**Describe the bug**
I closed my node to upgrade it to the latest version (0.9.1+git.8fd9b5f2) and when I run `lotus daemon`, the daemon and peer discovery runs but the api doesn't start anymore and the node doesn't appear to be syncing. All I see are drand logs. I've been using my local node for months now and the api always starts even before the node is fully synced. Any idea what I might have done wrong?
Another note, I also upgraded my remote node on an Azure instance and this one works as expected.

**To Reproduce**
Steps to reproduce the behavior: (On MacBook Pro (16-inch, 2019))
1. Close lotus node (graceful shutdown)
2. Upgrade lotus node to latest
3. Run `lotus daemon`
4. Run `lotus version`
5. Get `ERROR: could not get API info: could not get api endpoint: API not running (no endpoint)`

**Expected behavior**
Running `lotus version` should display the latest version if the api is running. Running `lotus daemon` should start the API and start syncing the node.

**Version (run `lotus version`):** 
Doesn't work but my branch is at 0.9.1+git.8fd9b5f2

**Additional context**
I am not using a custom repo path or anything like that. My node was fully synced before I upgraded.

**Comment by tchardin** [comment]
**Update:** After an hour or so in that state my lotus node started syncing and the api started. It seems syncing on my local node was just very slow to begin. Closing this issue. For anyone facing this in the future: just wait for it. 🤷‍♂️

**Comment by marsoln** [comment]
That is very helpful! Thanks a lot.
