### ISSUE TITLE
Make Authorization header compliant with HTTP spec

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#433]
Auth tokens in URL are in general a bad idea.

We should move toward an `Authorization` header in the request.

**Comment by magik6k** [comment]
We support both, defaulting to the header - https://github.com/filecoin-project/lotus/blob/e4212f2f1d3c56980459fd2eb8d8026f41b28db2/lib/auth/handler.go#L22-L24

**Comment by Kubuxu** [comment]
Cool, let's make it spec compliant, the header should have value: `Bearer <b64encoded>`.

It will make compatibility with different libs easier.

**Comment by magik6k** [comment]
I can't find anything that says putting jwt tokens into that header isn't fine, and jwt page even suggests that - https://jwt.io/introduction/
