### ISSUE TITLE
Committ fail 

### ISSUE THREAD

**Issue by weforu** [filecoin-project/lotus#4332]
**Describe the bug**
`sector prove-commit proof of size 1920 exceeds max size of 1024 (RetCode=16)`

**To Reproduce**
1. Run '.2020-10-12T17:52:59.155 INFO filcrypto::proofs::api > seal_commit_phase2: start
2020-10-12T17:52:59.240 INFO filecoin_proofs::api::seal > seal_commit_phase2:start
.......'
2. See error
`2020-10-12T18:38:18.779+0900	WARN	sectors	storage-sealing/fsm.go:475	sector <> got error event sealing.SectorCommitFailed: pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: sector prove-commit proof of size 1920 exceeds max size of 1024 (RetCode=16)`

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

Daemon:  0.10.0+git.a6b21807+api0.15.0
Local: lotus-miner version 0.10.0+git.a6b21807

**Additional context**

**Comment by jennijuju** [comment]
Will be fixed after v0.10.0 upgrade

**Comment by weforu** [comment]
thank you~!!

2020년 10월 13일 (화) 오전 1:33, Jennifer <notifications@github.com>님이 작성:
