### ISSUE TITLE
make clean && make all error

### ISSUE THREAD

**Issue by qixiuyuan** [filecoin-project/lotus#4333]
**Describe the bug**
make[1]: Leaving directory '/root/lotus/extern/filecoin-ffi'
rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.443131b" -o lotus ./cmd/lotus
# github.com/filecoin-project/filecoin-ffi/generated
extern/filecoin-ffi/generated/../libfilcrypto.a(fil_blst.o): In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::~_State_impl()':
fil_blst.cpp:(.text._ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEED2Ev[_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEED5Ev]+0xf): undefined reference to `std::thread::_State::~_State()'
extern/filecoin-ffi/generated/../libfilcrypto.a(fil_blst.o): In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::~_State_impl()':
fil_blst.cpp:(.text._ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEED0Ev[_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEED5Ev]+0x13): undefined reference to `std::thread::_State::~_State()'
extern/filecoin-ffi/generated/../libfilcrypto.a(fil_blst.o): In function `threadpool_init':
fil_blst.cpp:(.text.threadpool_init+0x39e): undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())'
extern/filecoin-ffi/generated/../libfilcrypto.a(fil_blst.o):(.data.rel.ro._ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEEE[_ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEEE]+0x10): undefined reference to `typeinfo for std::thread::_State'
collect2: error: ld returned 1 exit status
Makefile:67: recipe for target 'lotus' failed
make: *** [lotus] Error 2

**Version (run `lotus version`):**
master

**Comment by samjhill** [comment]
also getting this error

**Comment by samjhill** [comment]
```
+ eval '__tarball_path='\''/tmp/filecoin-ffi-Linux-standard_25342164.tar.gz'\'''
++ __tarball_path=/tmp/filecoin-ffi-Linux-standard_25342164.tar.gz
++ mktemp -d
+ local __tmp_dir=/tmp/tmp.fDrppnfHIi
+ tar -C /tmp/tmp.fDrppnfHIi -xzf /tmp/filecoin-ffi-Linux-standard_25342164.tar.gz
+ find -L /tmp/tmp.fDrppnfHIi -type f -name filcrypto.h -exec cp -- '{}' . ';'
+ find -L /tmp/tmp.fDrppnfHIi -type f -name libfilcrypto.a -exec cp -- '{}' . ';'
+ find -L /tmp/tmp.fDrppnfHIi -type f -name filcrypto.pc -exec cp -- '{}' . ';'
+ check_installed_files
+ [[ ! -f ./filcrypto.h ]]
+ [[ ! -f ./libfilcrypto.a ]]
+ [[ ! -f ./filcrypto.pc ]]
+ echo '[install-filcrypto/main] successfully installed prebuilt libfilcrypto'
[install-filcrypto/main] successfully installed prebuilt libfilcrypto
+ exit
make[1]: Leaving directory '/home/sam/lotus/extern/filecoin-ffi'
rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.0f5aa9b" -o lotus ./cmd/lotus
# github.com/filecoin-project/filecoin-ffi/generated
extern/filecoin-ffi/generated/../libfilcrypto.a(fil_blst.o): In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::~_State_impl()':
fil_blst.cpp:(.text._ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEED2Ev[_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEED5Ev]+0xf): undefined reference to `std::thread::_State::~_State()'
extern/filecoin-ffi/generated/../libfilcrypto.a(fil_blst.o): In function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::~_State_impl()':
fil_blst.cpp:(.text._ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEED0Ev[_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEED5Ev]+0x13): undefined reference to `std::thread::_State::~_State()'
extern/filecoin-ffi/generated/../libfilcrypto.a(fil_blst.o): In function `threadpool_init':
fil_blst.cpp:(.text.threadpool_init+0x39e): undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())'
extern/filecoin-ffi/generated/../libfilcrypto.a(fil_blst.o):(.data.rel.ro._ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEEE[_ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEEE]+0x10): undefined reference to `typeinfo for std::thread::_State'
collect2: error: ld returned 1 exit status
Makefile:67: recipe for target 'lotus' failed
make: *** [lotus] Error 2
sam@plutus:~/lotus$ go version
go version go1.14.7 linux/amd64
```

**Comment by hunjixin** [comment]
same error

**Comment by hunjixin** [comment]
@qixiuyuan @samjhill  how to fix this problem?

**Comment by rjan90** [comment]
Is this still an issue? #rengjøring
