### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by weforu** [filecoin-project/lotus#4349]
**Describe the bug**

panic: runtime error: invalid memory address or nil pointer dereference
Daemon: 0.10.0+git.a6b218075+api0.16.0
Local: lotus version 0.10.0+git.a6b218075

**To Reproduce**

1. Run 
'lotus-miner run'

2. See error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11964ce]goroutine 31251 [running]:
github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).handleRecoverDealIDs(0xc0118efc00, 0x311b6e0, 0xc00003e0e0, 0xc0192b0b60, 0xc02109d010, 0xe, 0x86f, 0x3, 0xc0127e2200, 0x4, ...)
	/root/lotus/extern/storage-sealing/states_failed.go:344 +0x43e
github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).Plan.func1(0x311b6e0, 0xc00003e0e0, 0xc0192b0b60, 0xc02109d010, 0xe, 0x86f, 0x3, 0xc0127e2200, 0x4, 0x4, ...)
	/root/lotus/extern/storage-sealing/fsm.go:26 +0x81
reflect.Value.call(0x29741a0, 0xc01aec67b0, 0x13, 0x2cb5db9, 0x4, 0xc02b68ff70, 0x2, 0x2, 0x52251f, 0x2a819a0, ...)
	/usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x29741a0, 0xc01aec67b0, 0x13, 0xc011844770, 0x2, 0x2, 0xc0134c19e0, 0xc01d1c9980, 0xc01d1c9a08)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc01aec6710, 0x311b6e0, 0xc00003e0e0, 0xc0192b0b60, 0xc01aec6720, 0xc02b1a2ba0)
	/root/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:102 +0x2bf
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
	/root/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:100 +0x3da

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
Daemon: 0.10.0+git.a6b218075+api0.16.0
Local: lotus version 0.10.0+git.a6b218075

**Additional context**

**Comment by weforu** [comment]
solved it

**Comment by yangmiok** [comment]
But how did you solved it?
