### ISSUE TITLE
lotus make error

### ISSUE THREAD

**Issue by qizukanshijie** [filecoin-project/lotus#435]
![QQ截图20191022114641](https://user-images.githubusercontent.com/46711275/67258084-86dce600-f4c1-11e9-9417-d66ab62b13a9.png)
verifying github.com/GeertJohan/go.incremental@v1.0.0: github.com/GeertJohan/go.incremental@v1.0.0: Get https://sum.golang.org/lookup/github.com/!geert!johan/go.incremental@v1.0.0: dial tcp 216.58.200.241:443: i/o timeout

**Comment by IPFS-grandhelmsman** [comment]
Golang module is in the firewall.

Set the GOPROXY with:
```shell
export GOPROXY=https://goproxy.io
```

Reference:
http://docs.studygolang.com/doc/go1.13

![image](https://user-images.githubusercontent.com/53922818/67261986-a847cd00-f4d5-11e9-802b-722a43633a71.png)

**Comment by magik6k** [comment]
Please reopen if that's still an issue
