### ISSUE TITLE
[Bug] After snapshot syncing, a state error occurs.

### ISSUE THREAD

**Issue by qkrwnsgh1288** [filecoin-project/lotus#4357]
**Describe the bug**
After snapshot syncing, a state error occurs.
And then, the sync does not proceed anymore.

**To Reproduce**
1. Run `lotus daemon --import-snapshot https://very-temporary-spacerace-chain-snapshot.s3-us-west-2.amazonaws.com/Spacerace_pruned_stateroots_snapshot_latest.car --halt-after-import`
2. See error
```
Worker: 2; Base: 141020; Target: 141455(diff: 435)
State: error; Current Epoch: 0; Todo: 141455
Validated 0 messages (0 per second)
```

**Version (run `lotus version`):**
`lotus version 0.10.0+git.a6b2180`

**Comment by rshellnet** [comment]
Same error...

**Comment by rjan90** [comment]
Is this still an issue? #rengjøring
