### ISSUE TITLE
So few test coins are obtained from the faucet? is this normal?

### ISSUE THREAD

**Issue by chenxiaolin0105** [filecoin-project/lotus#436]
Why are you getting so few test coins? is this normal?
My wallet address:`t3qcqm4bfw2tqsirm2krf3qxrbgdroqddjir3duaqs63mvnbhgi4p7sflycl5rdpy5ygpyxme2dwnkm6wvq6bq`
![image](https://user-images.githubusercontent.com/50695407/67258433-26e73f00-f4c3-11e9-9779-6cbaece8c589.png)

**Comment by magik6k** [comment]
Yes, this is a low fixed amount for now. For creating miners you can use the create miner endpoint which pays for the collateral for you. After you mine a block you'll get a pretty large block reward
