### ISSUE TITLE
sync status error

### ISSUE THREAD

**Issue by zhangsj** [filecoin-project/lotus#4364]
sync status:
worker 0:
	Base:	[bafy2bzacebipobijcumviiejlpgdc3gukw4nlwqetdlvkoa66usbhfgjcxet6 bafy2bzaced3kpquwno353gylw3irdrqbws4modsglqumrt7v7m4yiaajmkka6 bafy2bzacecnq5xs7u6rd2zev6wbyqh5sipnvgkifzomco3jgikrcm63ycdg7s]
	Target:	[bafy2bzacedn7zuubkcqmvuukxtkeuq3dx7kbwahi6ng3qbtpqtc4pvopz2rjm] (142166)
	Height diff:	3386
	Stage: message sync
	Height: 141418
	Elapsed: 3h19m37.76470723s
worker 1:
	Base:	[bafy2bzacedcikms52xlkunrg5s26kbxfqibbgs2u4kpmtn7ykzphgpsondygi bafy2bzaceclc5kxf5u75xzqkuspujaxgcgsjywyxuqg2wrlw4z3eeceughcty bafy2bzacedta7lzssjikkdk3loylzfvoi2qzzvzsgo4kap6qblc5cbniksxa6 bafy2bzaceb4qf2lbfwwtd63vks6docxcnt6qfjjmqjhd2bjy4v4loklf7e6m2]
	Target:	[bafy2bzacebl6yaw6n5gc2gcescdonv2hzwiucf4bpd56emuuqo4obvyuws4le] (142671)
	Height diff:	3571
	Stage: error
	Height: 0
	Elapsed: 71.356µs
	Error: chain linked to block marked previously as bad ([bafy2bzacebl6yaw6n5gc2gcescdonv2hzwiucf4bpd56emuuqo4obvyuws4le], bafy2bzacecv4trqk5slbzkaq5daqjymfr2gger7fwpn5knqjqcfdtrollmqrk) (reason: linked to bafy2bzaced4zend4uv3lxho5v2waforwdpufrndigpybmk3epiu6iplacrcqk caused by: [bafy2bzacedvk6wufpvjbinr6jz5iuq4m6f3aq2hlwckmnqzqapli2xmsv4vao] 1 error occurred:
	* block had invalid messages:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func3
        /home/circleci/project/chain/sync.go:764
  - bls aggregate signature was invalid:
    github.com/filecoin-project/lotus/chain.(*Syncer).checkBlockMessages
        /home/circleci/project/chain/sync.go:1056
  - bls aggregate signature failed to verify:
    github.com/filecoin-project/lotus/chain.(*Syncer).verifyBlsAggregate
        /home/circleci/project/chain/sync.go:1195

)
worker 2:
	Base:	[bafy2bzacedcikms52xlkunrg5s26kbxfqibbgs2u4kpmtn7ykzphgpsondygi bafy2bzaceclc5kxf5u75xzqkuspujaxgcgsjywyxuqg2wrlw4z3eeceughcty bafy2bzacedta7lzssjikkdk3loylzfvoi2qzzvzsgo4kap6qblc5cbniksxa6 bafy2bzaceb4qf2lbfwwtd63vks6docxcnt6qfjjmqjhd2bjy4v4loklf7e6m2]
	Target:	[bafy2bzacedgeut5hfm4lxsthimpsyj3hd6gztrkdxrffzi4xrunxsgvjso3m6] (142671)
	Height diff:	3571
	Stage: error
	Height: 0
	Elapsed: 65.77µs
	Error: chain linked to block marked previously as bad ([bafy2bzacedgeut5hfm4lxsthimpsyj3hd6gztrkdxrffzi4xrunxsgvjso3m6], bafy2bzacecv4trqk5slbzkaq5daqjymfr2gger7fwpn5knqjqcfdtrollmqrk) (reason: linked to bafy2bzaced4zend4uv3lxho5v2waforwdpufrndigpybmk3epiu6iplacrcqk caused by: [bafy2bzacedvk6wufpvjbinr6jz5iuq4m6f3aq2hlwckmnqzqapli2xmsv4vao] 1 error occurred:
	* block had invalid messages:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func3
        /home/circleci/project/chain/sync.go:764
  - bls aggregate signature was invalid:
    github.com/filecoin-project/lotus/chain.(*Syncer).checkBlockMessages
        /home/circleci/project/chain/sync.go:1056
  - bls aggregate signature failed to verify:
    github.com/filecoin-project/lotus/chain.(*Syncer).verifyBlsAggregate
        /home/circleci/project/chain/sync.go:1195

)

**Comment by wo4zhuzi** [comment]
Same error

**Comment by ericnjin** [comment]
same error. i can solve it by restarting demon but still error

**Comment by zhangsj** [comment]
who care

**Comment by rjan90** [comment]
I think this issue can be closed, as the syncing on newer versions of Lotus are working properly! #rengjøring
