### ISSUE TITLE
New sectors mined as inactive

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#4365]
My miner ID is `f019100`

All the new sectors my miner is mining are published on chain successfully and marked as Proving, but at the same time not accounted for in the storage power and marked as inactive. Not sure what details to provide:

```
# lotus-miner info
Miner: f019100
Sector Size: 32 GiB
Byte Power:   6.062 TiB / 527 PiB (0.0011%)
Actual Power: 6.06 Ti / 527 Pi (0.0011%)
	Committed: 6.219 TiB
	Proving: 6.094 TiB (32 GiB Faulty, 0.50%)
```

^ i.e. 6.219TB committed, but proving way less?

```
# lotus-miner proving deadlines
Miner: f019100
deadline  partitions  sectors (faults)  proven partitions
0         1           191 (1)           0
1         1           9 (0)             0
2         1           1 (0)             0
3         0           0 (0)             0
[...]
```

^ 200 sectors proving which should be 6.4TB (or 6.25TiB), but I'm only at 6.094?

All my latest sectors are mined as inactive:

```
217  Proving     YES      NO      1695922 (in 1 year 24 weeks)  CC                 
218  Proving     YES      NO      1695922 (in 1 year 24 weeks)  CC                 
219  PreCommit2  NO       NO      n/a                           CC                 
220  Proving     YES      NO      1695922 (in 1 year 24 weeks)  CC                 
221  Proving     YES      NO      1695922 (in 1 year 24 weeks)  CC 
```

E.g. here's the tx for sector 220 https://filscan.io/#/tipset/message-detail?cid=bafy2bzacediusp6kytylwuryel7avp7djbmftjdhj5dox3am5l2zlswworwdm

**Comment by magik6k** [comment]
After the V2 actors upgrade, power for newly committed sectors is only added after those sectors are proven in a WindowPoSt for the first time

**Comment by karalabe** [comment]
Ah, good to know. Any place to keep up to date with these changes?

**Comment by karalabe** [comment]
Upgraded to active after post.
