### ISSUE TITLE
[CREATING STORAGE MINER]  Too Many Requests  

### ISSUE THREAD

**Issue by chengzhigen** [filecoin-project/lotus#437]
https://lotus-faucet.kittyhawk.wtf/mkminer?address=
When creating a storage miner, the website returns to too many requests

**Comment by maobisheng** [comment]
The same bug was reported at https://github.com/filecoin-project/lotus/issues/424

**Comment by yangjian102621** [comment]
I got the same bug.

**Comment by travisperson** [comment]
Closing to track in #517
