### ISSUE TITLE
Memory usage close to 95% after received 1TB data deals

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/lotus#4370]
**Describe the bug**
My miners received about 1000 deals and 1TB in total, the memory usasage is alway keep at 92%-95% which caused the crash at the winpost

 **To Reproduce**
1. open the filter of the miner
2. You get deals come in for 1 day
3. Miner memory usage close to 95%

**Expected behavior**
Memory usage should around 20%

**Screenshots**
![image](https://user-images.githubusercontent.com/8363795/95894273-d6fa2b80-0d56-11eb-89c2-e7a9e073af59.png)

**Version (run `lotus version`):**
0.10.0

**Additional context**

**Comment by KaptinLin** [comment]
```
(pprof) list pb\.\(\*Message_Block\)\.Unmarshal
Total: 580.21GB
ROUTINE ======================== github.com/ipfs/go-graphsync/message/pb.(*Message_Block).Unmarshal in /root/go/pkg/mod/github.com/ipfs/go-graphsync@v0.2.1/message/pb/message.pb.go
  572.20GB   572.20GB (flat, cum) 98.62% of Total
         .          .   1538:        return ErrInvalidLengthMessage
         .          .   1539:      }
         .          .   1540:      if postIndex > l {
         .          .   1541:        return io.ErrUnexpectedEOF
         .          .   1542:      }
  572.20GB   572.20GB   1543:      m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
         .          .   1544:      if m.Data == nil {
         .          .   1545:        m.Data = []byte{}
         .          .   1546:      }
         .          .   1547:      iNdEx = postIndex
         .          .   1548:    default:
```

**Comment by Stebalien** [comment]
Next time this happens, could you take and upload a full heap profile:

```
curl "http://localhost:5001/debug/pprof/goroutine?debug=2" > stacks.txt
curl "http://localhost:1234/debug/pprof/heap" > heap.pprof
```

Then upload these here.

**Comment by Yarkin** [comment]
bytes:  264kB
  375.15GB   github.com/ipfs/go-merkledag/pb.(*PBNode).Unmarshal
             github.com/ipld/go-ipld-prime-proto.(*_PBNode__Builder).DecodeDagProto
             github.com/ipld/go-ipld-prime-proto.PBDecoder
             github.com/ipld/go-ipld-prime/linking/cid.Link.Load
             github.com/ipld/go-ipld-prime/traversal.Progress.loadLink
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.WalkAdv
             github.com/ipfs/go-graphsync/ipldutil.(*traverser).start.func1

**Comment by Yarkin** [comment]
Showing nodes accounting for 375.38GB, 98.83% of 379.82GB total
Dropped 514 nodes (cum <= 1.90GB)
      flat  flat%   sum%        cum   cum%
  375.38GB 98.83% 98.83%   375.38GB 98.83%  github.com/ipfs/go-merkledag/pb.(*PBNode).Unmarshal
         0     0% 98.83%   376.97GB 99.25%  github.com/ipfs/go-graphsync/ipldutil.(*traverser).start.func1
         0     0% 98.83%   375.61GB 98.89%  github.com/ipld/go-ipld-prime-proto.(*_PBNode__Builder).DecodeDagProto
         0     0% 98.83%   375.61GB 98.89%  github.com/ipld/go-ipld-prime-proto.PBDecoder
         0     0% 98.83%   375.61GB 98.89%  github.com/ipld/go-ipld-prime/linking/cid.Link.Load
         0     0% 98.83%   376.97GB 99.25%  github.com/ipld/go-ipld-prime/traversal.Progress.WalkAdv
         0     0% 98.83%   375.67GB 98.91%  github.com/ipld/go-ipld-prime/traversal.Progress.loadLink
         0     0% 98.83%   376.97GB 99.25%  github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
         0     0% 98.83%   376.97GB 99.25%  github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll

**Comment by Reiers** [comment]
Hi @flyworker 

Thanks for the report. This is memory leak is fixed a long time ago. 
Not seen this in the [current release. ](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)

Closing ticket.

If you are still experiencing problems, please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you !
