### ISSUE TITLE
Retrieval failing in v0.10.0

### ISSUE THREAD

**Issue by ghost** [filecoin-project/lotus#4371]
**Describe the bug**
`lotus client retrieve` commands are failing in v0.10.0.  Error is:

```
ERROR: The received offer errored: retrieval query offer errored: get cid info: No state for /QmQdjrhmAQTMtwWWsfpGtWBZQeM4xvTj6SByXiC4Hbsruu: datastore: key not found
```

**To Reproduce**

Find a storage deal id like this:
```
$ lotus-miner storage-deals list | grep StorageDealActive
...jgbxquya  170915  StorageDealActive        f3vp7m3244tjtxrvg4n2lfedtqnnnzhyno3ym6vnl4wzozztik4f2kvzfbfbgzcga7g3mckddw6x4ahp5n4iwa  8MiB    0.000075276 FIL      602208
```

We'll use deal id 170915 for retrieval.  Let's get the Payload CID + Piece CID:

```
$ lotus state get-deal 170915
{
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqn6ofdr3lqhvsev5ukjpw5zcvwp4uebyjlq2qmdfpor7534whwsna"
    },
    "PieceSize": 8589934592,
    "VerifiedDeal": false,
    "Client": "f021693",
    "Provider": "f016563",
    "Label": "QmQdjrhmAQTMtwWWsfpGtWBZQeM4xvTj6SByXiC4Hbsruu",
    "StartEpoch": 96986,
    "EndEpoch": 1137436,
    "StoragePricePerEpoch": "4000000000",
    "ProviderCollateral": "0",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorStartEpoch": 96156,
    "LastUpdatedEpoch": 140881,
    "SlashEpoch": -1
  }
}
```

And plug them into a `lotus client retrieve` command, along with the miner id (`f019243`):
```
$ lotus client retrieve --pieceCid baga6ea4seaqn6ofdr3lqhvsev5ukjpw5zcvwp4uebyjlq2qmdfpor7534whwsna --miner f019243 QmQdjrhmAQTMtwWWsfpGtWBZQeM4xvTj6SByXiC4Hbsruu ~/somefile.bin
ERROR: The received offer errored: retrieval query offer errored: get cid info: No state for /QmQdjrhmAQTMtwWWsfpGtWBZQeM4xvTj6SByXiC4Hbsruu: datastore: key not found
```

**Expected behavior**
I expected the `lotus client retrieve` command above to retrieve the file and write it to `~/somefile.bin`.
I did not expect the error message shown above.

**Version (run `lotus version`):**
```
Daemon:  0.10.0+git.a6b218075+api0.16.0
Local: lotus version 0.10.0+git.a6b218075
```

**Additional context**
 - I tried converting the Payload CID `QmQdjrhmAQTMtwWWsfpGtWBZQeM4xvTj6SByXiC4Hbsruu` to a V1 CID using cid.ipfs.io.  But I still get the same error when I try to retrieve with that:
```
$ lotus client retrieve --pieceCid baga6ea4seaqn6ofdr3lqhvsev5ukjpw5zcvwp4uebyjlq2qmdfpor7534whwsna --miner f019243 bafybeibcdaizpqaoncf5vdrhdxzofwn2rnhhwny2smmwtplnd2536pb5ca ~/somefile.bin
ERROR: The received offer errored: retrieval query offer errored: get cid info: No state for /bafybeibcdaizpqaoncf5vdrhdxzofwn2rnhhwny2smmwtplnd2536pb5ca: datastore: key not found
```

 - Here's what the miner log shows for the above retrieve command:
```
2020-10-13T18:51:10.572Z        ^[[31mERROR^[[0m        retrieval       impl/provider.go:318    Retrieval query: GetRefs: get cid info: No state for /QmQdjrhmAQTMtwWWsfpGtWBZQeM4xvTj6SByXiC4Hbsruu: datastore: key not found
```

 - Error in log is the same using the V1 CID:
```
2020-10-13T18:52:26.470Z        ^[[31mERROR^[[0m        retrieval       impl/provider.go:318    Retrieval query: GetRefs: get cid info: No state for /bafybeibcdaizpqaoncf5vdrhdxzofwn2rnhhwny2smmwtplnd2536pb5ca: datastore: key not found
```

**Comment by mgoelzer** [comment]
@ribasushi suggested asking you, @hannahhoward

**Comment by hannahhoward** [comment]
hi @mgoelzer -- do we have direct access to this miner?

**Comment by chidawen** [comment]
I have the same problem 
`retrieval query offer errored: get cid info: No state for /bafk2bzaceaaheaumoqecazja26ux6riagqqz3thzlrk6qffbgysjti76spzw4: datastore: key not found`

**Comment by funktafide** [comment]
Im seeing this issue as well MinerID f014768
Retrieval query: GetRefs: get cid info: No state for /bafykbzacecw54obuzpvtm452t7y4zxlqrtcod7xl7hqvg6rrfvdmbqczwdklm: datastore: key not found
For some reason when I woke up this morning and tried doing a lotus-miner sector list. I was getting a connection refused.  Miner did not seem to be running.  Shut down Daemon and restarted everything.  This error shows up when I start running the miner again.  I have two sectors stuckin PreCommit1.  One sector has deals the other is a pleged sector.

**Comment by Reiers** [comment]
Thanks for the report. The issue is outdated.

If this is a issue in the [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1) - please open a new ticket.

Thank you !
