### ISSUE TITLE
Add data transfer restart for the miner

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#4380]
Similar to code in https://github.com/filecoin-project/lotus/pull/4363/files,

It would be nice to have a command for lotus-miner that restarted datatransfers from the provider side.

Just needs:
- a MarketRestartDataTransfer on the api_storage api
- an implementation (should be almost identical to ClientRestartDataTransfer)
- a cli command - can model off the command for `lotus client restart-transfer` but should probably be called `lotus-miner data-transfers restart` to maintain naming consistency.

**Comment by jennijuju** [comment]
resolved by https://github.com/filecoin-project/lotus/pull/5553

**Comment by dirkmc** [comment]
I think this was actually fixed by https://github.com/filecoin-project/lotus/pull/4387
