### ISSUE TITLE
daemon sync error

### ISSUE THREAD

**Issue by alingb** [filecoin-project/lotus#4385]
After I execute "Lotus sync wait" successfully, a sync error appears for a while

Run “lotus sync wait”

root@trusme-Horsea:~# lotus sync wait
Worker: 0; Base: 144042; Target: 144044 (diff: 2))))
State: complete; Current Epoch: 144044; Todo: 0
Validated 1405424 messages (0 per second)

Done!

Run “lotus sync status”

root@trusme-Horsea:~# lotus sync status
sync status:
worker 0:
	Base:	[bafy2bzacedavbxkh4glwwc4gdpc7qn4rppeforgwrrjffrnocnwfiqqw25jmu bafy2bzaceaxpfyywh53bt362jd2rlduutbt56453d4ej62mfxsvt2wnssmfns bafy2bzacedvxzsvrxmdizagevduaphrjkavg4xe7oysmwsp5mf2i7xg4r2jk6 bafy2bzacecccbtogq5dchbv6njaedcvimibcnuxyavn4mgnjc4swy33bpt67i bafy2bzacebldjch4jkud3s7e7sg4glpjhvdghlf3wnrxw5gl3sphsvqaqtd2m bafy2bzaceatufxccnhjlnqmk3axfkmbliov7vvyegl6lucdrrzwruewzy47ru bafy2bzacedpyzl3d456ef7ikqoolxape6zhjbapt3akc5kujyouho2s3rqgta bafy2bzaceaczm7vcnwgqeoqk2uaa5lsudvfnv34yfdsgmxnh2ql2pvzx7so2u bafy2bzacecevuhnkxgslowyxcpfkcmq6esjrp75sdyvvhupz477klhhruq42c bafy2bzaced4aol4uy4ohnq6vta24ogxhmevqlo77vt2m562jy7utwq7hg7aaa bafy2bzacedb3cxwhppcftwygilemzyh2xk3b37d6akfsgbmo23atbibpe7ypu bafy2bzaceap2ye33w322eihnynonwv437ih3gqz3dpek5jk77fwl3urzzh5dw]
	Target:	[bafy2bzaceazos5ztkvzrig7n52acdxmxkqbqxbzhs2shfgvjen2anquxwh6lw] (144511)
	Height diff:	323
	Stage: error
	Height: 0
	Elapsed: 64.661μs
	Error: chain linked to block marked previously as bad ([bafy2bzaceazos5ztkvzrig7n52acdxmxkqbqxbzhs2shfgvjen2anquxwh6lw], bafy2bzacebluwffqq2lbiu4dypveljip7avhrx7kea7wtfcyqskkcy2cetqjm) (reason: linked to bafy2bzacecsa2fphseibwxms47z7fw6xhsxdhnyeaj5j2gumj6nriggkysuia caused by: [bafy2bzacebnl3x4ecsl6k75q7aty7ola5rp3bo7cjeqykgdkqzjv5m47sb4k2] 1 error occurred:
	* parent state root did not match computed state (bafy2bzaceazplhys7w5eawkh3tucm6z63f6m3elxmmnwqou7oynu3cgklhxq4 != bafy2bzacebirzp7sqfr3t4vz4mfrmlfbojgjunok7xhzo2uvmbhplxs4urqyw):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /root/lotus/chain/sync.go:815

)
worker 1:
	Base:	[bafy2bzacedavbxkh4glwwc4gdpc7qn4rppeforgwrrjffrnocnwfiqqw25jmu bafy2bzaceaxpfyywh53bt362jd2rlduutbt56453d4ej62mfxsvt2wnssmfns bafy2bzacedvxzsvrxmdizagevduaphrjkavg4xe7oysmwsp5mf2i7xg4r2jk6 bafy2bzacecccbtogq5dchbv6njaedcvimibcnuxyavn4mgnjc4swy33bpt67i bafy2bzacebldjch4jkud3s7e7sg4glpjhvdghlf3wnrxw5gl3sphsvqaqtd2m bafy2bzaceatufxccnhjlnqmk3axfkmbliov7vvyegl6lucdrrzwruewzy47ru bafy2bzacedpyzl3d456ef7ikqoolxape6zhjbapt3akc5kujyouho2s3rqgta bafy2bzaceaczm7vcnwgqeoqk2uaa5lsudvfnv34yfdsgmxnh2ql2pvzx7so2u bafy2bzacecevuhnkxgslowyxcpfkcmq6esjrp75sdyvvhupz477klhhruq42c bafy2bzaced4aol4uy4ohnq6vta24ogxhmevqlo77vt2m562jy7utwq7hg7aaa bafy2bzacedb3cxwhppcftwygilemzyh2xk3b37d6akfsgbmo23atbibpe7ypu bafy2bzaceap2ye33w322eihnynonwv437ih3gqz3dpek5jk77fwl3urzzh5dw]
	Target:	[bafy2bzaceck4sq7o4ygr2w2mg5nkgo7v2pz5agpukt5av3lw3fuomjse3wgie] (144511)
	Height diff:	323
	Stage: error
	Height: 0
	Elapsed: 47.309μs
	Error: chain linked to block marked previously as bad ([bafy2bzaceck4sq7o4ygr2w2mg5nkgo7v2pz5agpukt5av3lw3fuomjse3wgie], bafy2bzacebluwffqq2lbiu4dypveljip7avhrx7kea7wtfcyqskkcy2cetqjm) (reason: linked to bafy2bzacecsa2fphseibwxms47z7fw6xhsxdhnyeaj5j2gumj6nriggkysuia caused by: [bafy2bzacebnl3x4ecsl6k75q7aty7ola5rp3bo7cjeqykgdkqzjv5m47sb4k2] 1 error occurred:
	* parent state root did not match computed state (bafy2bzaceazplhys7w5eawkh3tucm6z63f6m3elxmmnwqou7oynu3cgklhxq4 != bafy2bzacebirzp7sqfr3t4vz4mfrmlfbojgjunok7xhzo2uvmbhplxs4urqyw):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /root/lotus/chain/sync.go:815

)
worker 2:
	Base:	[bafy2bzacedavbxkh4glwwc4gdpc7qn4rppeforgwrrjffrnocnwfiqqw25jmu bafy2bzaceaxpfyywh53bt362jd2rlduutbt56453d4ej62mfxsvt2wnssmfns bafy2bzacedvxzsvrxmdizagevduaphrjkavg4xe7oysmwsp5mf2i7xg4r2jk6 bafy2bzacecccbtogq5dchbv6njaedcvimibcnuxyavn4mgnjc4swy33bpt67i bafy2bzacebldjch4jkud3s7e7sg4glpjhvdghlf3wnrxw5gl3sphsvqaqtd2m bafy2bzaceatufxccnhjlnqmk3axfkmbliov7vvyegl6lucdrrzwruewzy47ru bafy2bzacedpyzl3d456ef7ikqoolxape6zhjbapt3akc5kujyouho2s3rqgta bafy2bzaceaczm7vcnwgqeoqk2uaa5lsudvfnv34yfdsgmxnh2ql2pvzx7so2u bafy2bzacecevuhnkxgslowyxcpfkcmq6esjrp75sdyvvhupz477klhhruq42c bafy2bzaced4aol4uy4ohnq6vta24ogxhmevqlo77vt2m562jy7utwq7hg7aaa bafy2bzacedb3cxwhppcftwygilemzyh2xk3b37d6akfsgbmo23atbibpe7ypu bafy2bzaceap2ye33w322eihnynonwv437ih3gqz3dpek5jk77fwl3urzzh5dw]
	Target:	[bafy2bzacedeoybf3bvy3x7a3n7f6ci472y7vfdtdaftym5dqkutggwpxy6226] (144512)
	Height diff:	324
	Stage: error
	Height: 0
	Elapsed: 67.707μs
	Error: chain linked to block marked previously as bad ([bafy2bzacedeoybf3bvy3x7a3n7f6ci472y7vfdtdaftym5dqkutggwpxy6226], bafy2bzacecpnjhhbjz7pyunvynrbstmyuwmaml7nxwd7xtpef55n4brbcykww) (reason: linked to bafy2bzacebluwffqq2lbiu4dypveljip7avhrx7kea7wtfcyqskkcy2cetqjm caused by: [bafy2bzacebnl3x4ecsl6k75q7aty7ola5rp3bo7cjeqykgdkqzjv5m47sb4k2] 1 error occurred:
	* parent state root did not match computed state (bafy2bzaceazplhys7w5eawkh3tucm6z63f6m3elxmmnwqou7oynu3cgklhxq4 != bafy2bzacebirzp7sqfr3t4vz4mfrmlfbojgjunok7xhzo2uvmbhplxs4urqyw):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /root/lotus/chain/sync.go:815

)

Run “lotus --version”

root@trusme-Horsea:~# lotus --version
lotus version 0.9.1+git.a9d8bc7c

It's been tried so many times. How can I keep the synchronization working?

**Comment by kernelogic** [comment]
You are still on version 0.9.1 now it should be 0.10.1

**Comment by alingb** [comment]
> You are still on version 0.9.1 now it should be 0.10.1

I upgraded to 0.10.1, but the synchronization is still wrong

root@trusme-Horsea:/data# lotus --version
lotus version 0.10.1+git.41bfeb56

root@trusme-Horsea:~# lotus sync wait
Worker: 2; Base: 140252; Target: 141727 (diff: 1475)
State: error; Current Epoch: 140761; Todo: 966
Validated 162098 messages (0 per second)


root@trusme-Horsea:~# lotus sync status
sync status:
worker 0:
	Base:	[bafy2bzacecaeuhqm6bloqsmny6gmodi7wz5scku35d4aqn7eyx6nhymhb35p2 bafy2bzacedf5xxdvxawu62yzqkfqkvcle3egrmy32mmgcya5fo7pnkq5eqfic bafy2bzacebkgjhhweegwqfrkrqvprbhj5ard53sgzg2po5tmdgtcjespejee6 bafy2bzacebud3v2cb3m6olb3h2hrr7lkqaul2p3y6oip4qylaqkawdhsrzgvc bafy2bzacec6sfs7fhhbdlpl5yfgwscq5xqn5tjy3tdtbnrltr72q2a2pkmumg]
	Target:	[bafy2bzacebe7kl72rtj3s5nq4u5wa66sfh5aygkgkpzdymoixlkhgdw5bk5uy bafy2bzacebemjwp327olssgveg6dtcx5qlamqiix7j4feuhtklzxecvo6ic5q bafy2bzaceamjmw4z7dksppf2qwxnlaij4f3ymo5dn6vz24f33u537ukaynlcq] (142573)
	Height diff:	2321
	Stage: message sync
	Height: 140272
	Elapsed: 2m51.46160152s
worker 1:
	Base:	[]
	Target:	[] (0)
	Height diff:	0
	Stage: <unknown: 0>
	Height: 0
worker 2:
	Base:	[]
	Target:	[] (0)
	Height diff:	0
	Stage: <unknown: 0>
	Height: 0
root@trusme-Horsea:~# watch lotus sync status
root@trusme-Horsea:~# watch lotus sync status
root@trusme-Horsea:~# lotus sync status
sync status:
worker 0:
	Base:	[bafy2bzacecaeuhqm6bloqsmny6gmodi7wz5scku35d4aqn7eyx6nhymhb35p2 bafy2bzacedf5xxdvxawu62yzqkfqkvcle3egrmy32mmgcya5fo7pnkq5eqfic bafy2bzacebkgjhhweegwqfrkrqvprbhj5ard53sgzg2po5tmdgtcjespejee6 bafy2bzacebud3v2cb3m6olb3h2hrr7lkqaul2p3y6oip4qylaqkawdhsrzgvc bafy2bzacec6sfs7fhhbdlpl5yfgwscq5xqn5tjy3tdtbnrltr72q2a2pkmumg]
	Target:	[bafy2bzacedjlvfnalnn7lji3lhguf5h6mljpacc5nebmydxiizjzqia5aothc] (145110)
	Height diff:	4858
	Stage: error
	Height: 145110
	Elapsed: 5.066052409s
	Error: chain contained block marked previously as bad ([bafy2bzacedjlvfnalnn7lji3lhguf5h6mljpacc5nebmydxiizjzqia5aothc], bafy2bzacebq5kezw3o6sytkqpd6pqpmu6imvjfbuhruhzdrcj2ponx5mwsl3g) (reason: change contained bafy2bzacedjtq4hz7egq6isbyqzvsgmffxwyvpscfoevvb42vfmhiuxqwbqhs caused by: [bafy2bzaceblq54ah3oezkhgro7wad2gb77vw7cj6uno44i7ccelohlejwi3zk] 1 error occurred:
	* parent state root did not match computed state (bafy2bzacecs6ztztkp7ruitigiriydvl7rgppvoy25pojto6wq25x37uzobgy != bafy2bzacechel2dalaanrk7o3akgum65in6fenpy5da4yjlsvtjgrz5k7o2v6):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /root/lotus/chain/sync.go:815

)
worker 1:
	Base:	[bafy2bzacecaeuhqm6bloqsmny6gmodi7wz5scku35d4aqn7eyx6nhymhb35p2 bafy2bzacedf5xxdvxawu62yzqkfqkvcle3egrmy32mmgcya5fo7pnkq5eqfic bafy2bzacebkgjhhweegwqfrkrqvprbhj5ard53sgzg2po5tmdgtcjespejee6 bafy2bzacebud3v2cb3m6olb3h2hrr7lkqaul2p3y6oip4qylaqkawdhsrzgvc bafy2bzacec6sfs7fhhbdlpl5yfgwscq5xqn5tjy3tdtbnrltr72q2a2pkmumg]
	Target:	[bafy2bzacea7wyb6oxc2llyxdgkvtyibyu3utc434xe5rgzeh7kfelmyj5fxrk] (145149)
	Height diff:	4897
	Stage: error
	Height: 145149
	Elapsed: 5.081491019s
	Error: chain contained block marked previously as bad ([bafy2bzacea7wyb6oxc2llyxdgkvtyibyu3utc434xe5rgzeh7kfelmyj5fxrk], bafy2bzacebq5kezw3o6sytkqpd6pqpmu6imvjfbuhruhzdrcj2ponx5mwsl3g) (reason: change contained bafy2bzacedjtq4hz7egq6isbyqzvsgmffxwyvpscfoevvb42vfmhiuxqwbqhs caused by: [bafy2bzaceblq54ah3oezkhgro7wad2gb77vw7cj6uno44i7ccelohlejwi3zk] 1 error occurred:
	* parent state root did not match computed state (bafy2bzacecs6ztztkp7ruitigiriydvl7rgppvoy25pojto6wq25x37uzobgy != bafy2bzacechel2dalaanrk7o3akgum65in6fenpy5da4yjlsvtjgrz5k7o2v6):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /root/lotus/chain/sync.go:815

)
worker 2:
	Base:	[bafy2bzacecaeuhqm6bloqsmny6gmodi7wz5scku35d4aqn7eyx6nhymhb35p2 bafy2bzacedf5xxdvxawu62yzqkfqkvcle3egrmy32mmgcya5fo7pnkq5eqfic bafy2bzacebkgjhhweegwqfrkrqvprbhj5ard53sgzg2po5tmdgtcjespejee6 bafy2bzacebud3v2cb3m6olb3h2hrr7lkqaul2p3y6oip4qylaqkawdhsrzgvc bafy2bzacec6sfs7fhhbdlpl5yfgwscq5xqn5tjy3tdtbnrltr72q2a2pkmumg]
	Target:	[bafy2bzaceabmxlbghckdby6bp2crx5roo2buvy7cs2wto463qkbjhvg3q4two] (141727)
	Height diff:	1475
	Stage: error
	Height: 140761
	Elapsed: 10.727178218s
	Error: collectChain syncMessages: message processing failed: validating block bafy2bzacea7stawjx3x25t4wxhs2yhox4nbmb7gqrb4zxz4ge74nups6bm3qq: 1 error occurred:
	* parent state root did not match computed state (bafy2bzacecyutgsyarzctnccqjs67ehsiigfffoiuahokzbdnrbg7oxh6b77a != bafy2bzaceau3nnf55hismkdsriztyfigpzm6zqkg6ud3hr2q5vad2wuxai5ig):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /root/lotus/chain/sync.go:815

**Comment by arajasek** [comment]
This was caused because you did not upgrade to Lotus v0.10.1 (the upgrade was at 140760, at which point your sync failed). If you haven't already resolved this, consider [syncing from a snapshot](https://docs.filecoin.io/get-started/lotus/chain/#syncing) or running `lotus chain sethead --epoch=140750` and restarting your node.

**Comment by satonz** [comment]
I am using version 1.1.3 and this error also occurs

**Comment by satonz** [comment]
@arajasek

**Comment by Elhorses** [comment]
+1

**Comment by Elhorses** [comment]
+1
