### ISSUE TITLE
make clean all error

### ISSUE THREAD

**Issue by prettyCoders** [filecoin-project/lotus#4388]
![图片](https://user-images.githubusercontent.com/36216120/95969985-00dc4c80-0e42-11eb-94ea-c2461ba783c9.png)

**Comment by prettyCoders** [comment]
![图片](https://user-images.githubusercontent.com/36216120/95975023-400d9c00-0e48-11eb-80ce-541a260b338a.png)

**Comment by rjan90** [comment]
I would reccomend reinstalling Go. I think this issue can be closed since it is not a Lotus-related issue. #rengjøring
