### ISSUE TITLE
download snapshot

### ISSUE THREAD

**Issue by 362228416** [filecoin-project/lotus#4389]
Where can I download snapshot data ？ synchronization block is too slow

**Comment by 362228416** [comment]
Or there is no public node, can query the latest block data, broadcast transactions

**Comment by dineshshenoy** [comment]
You should be able to retrieve it from here: 
https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car

As documented from this page: 
https://docs.filecoin.io/get-started/lotus/installation/#start-the-lotus-daemon-and-sync-the-chain
