### ISSUE TITLE
lotus-storage-miner failed to run if the db file is corrupted

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#439]
## Description:
Once .lotusstorage/meta/db file is corrupted, the `lotus-storage-miner run` will fail.

## Expectation: 
The storage issue should not fail the program. 
meta info should be only for local use, which might lead unsealed data stop sealing, but not critical to impact the proving services. 

## Version:
The first version of Lotus devnet.

**Comment by laser** [comment]
This issue duplicates [an upstream rust-fil-sector-builder issue](https://github.com/filecoin-project/rust-fil-sector-builder/issues/13).

**Comment by magik6k** [comment]
We now don't relay on this metadata
