### ISSUE TITLE
all workers exit by websocket routine exiting

### ISSUE THREAD

**Issue by ffteng46** [filecoin-project/lotus#4390]
**Describe the bug**
all workers exist with same error.First in lotus daemon,get this unknown actor code bafkqadlgnfwc6mrpmfrwg33vnz2a,then in miner daemon receives message that all workers connection timeout and disconnect from miner.All the miners have the same log RPC client error: sendRequest failed: websocket routine exiting,all workers exit but lotus and miner still work.
**To Reproduce**
1. Run '...'
2. See error
restart all workers with lotus-worker run --*** --**
**Expected behavior**
all workers works fine for sealing.
**Screenshots**
![image](https://user-images.githubusercontent.com/17234469/95976632-66343b80-0e4a-11eb-97a3-b9d74cb12803.png)
![image](https://user-images.githubusercontent.com/17234469/95976655-6fbda380-0e4a-11eb-9384-7ebd5b04263f.png)
![image](https://user-images.githubusercontent.com/17234469/95976671-764c1b00-0e4a-11eb-9d06-d02d1d408c37.png)
![image](https://user-images.githubusercontent.com/17234469/95976700-7d732900-0e4a-11eb-99c9-94d884fd395a.png)

**Version (run `lotus version`):**
Daemon:  0.10.0+git.a6b218075.dirty+api0.16.0
Local: lotus version 0.10.0+git.a6b218075.dirty
**Additional context**

**Comment by TroyWind** [comment]
I also encountered `websocket routine exiting` because it took me too long to restart Miner, but the API connection timeout was 30s, so it would not be reconnected after the timeout, resulting in `websocket routine exiting` being reported all the time. By lengthening the timeout, it will keep retrying to connect to Miner until Miner is started.
```golang
nodeApi, closer, err = lcli.GetStorageMinerAPI(cctx,
	jsonrpc.WithTimeout(30*time.Minute))
```
