### ISSUE TITLE
Add --watch and --local flags to mpool stat

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#4401]

**Comment by raulk** [comment]
@Kubuxu mind adding a description here?

**Comment by Kubuxu** [comment]
I would need to ask myself from October last year. Will do.

**Comment by Reiers** [comment]
@Kubuxu *bump

**Comment by Reiers** [comment]
@Kubuxu bumpity bump - is this something you are still planning to do/add?
