### ISSUE TITLE
Actor not found error

### ISSUE THREAD

**Issue by rshellnet** [filecoin-project/lotus#4404]
Error message from lotus-miner:

2020-10-14T22:36:32.530+0100    ERROR   miner   miner/miner.go:228      mining block failed: failed to get mining base info:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /usr/src/lotus/miner/miner.go:363
  - failed to load miner actor: actor not found

Error message from lotus dameon log:

handler.go:241  error in RPC call to 'Filecoin.MinerGetBaseInfo': failed to load miner actor:

1. Run 'lotus daemon run' and 'lotus-miner run'

Daemon:  0.10.0+git.a6b21807+api0.16.0
Everything is synced.

**Comment by verynohair** [comment]
I got the same issue. Have it solved?

**Comment by jennijuju** [comment]
see #4324  and #4508
