### ISSUE TITLE
Multiple sector 0

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/lotus#4405]
**Describe the bug**
I've got multiple sector 0 on my node from the beginning of Spacerace 1:

```
 s0nik42@keats:~$ miner sectors list 
ID   State       OnChain  Active  Expiration                      Deals  DealWeight  
0    Proving     YES      NO      1566516 (in 1 year 18 weeks)    CC                 
0    Proving     YES      NO      1566516 (in 1 year 18 weeks)    CC                 
1    Proving     YES      YES     1566516 (in 1 year 18 weeks)    2      116KiB      
2    Proving     YES      YES     1569396 (in 1 year 18 weeks)    CC                 
3    Proving     YES      YES     1569396 (in 1 year 18 weeks)    CC                 
4    Proving     YES      YES     1569396 (in 1 year 18 weeks)    CC            
[...]
```

**To Reproduce**
I don't know :/

**Expected behavior**
Is there any risk of any side effect when the sector will reach expiration 

**Screenshots**

**Version (run `lotus version`):**
s0nik42@keats:~$ lotus version
Daemon:  0.10.0+git.a6b21807+api0.16.0
Local: lotus version 0.10.0+git.a6b21807

**Additional context**
The sector(s) is not present in the datastore.

s0nik42@keats:$ miner storage find 0
s0nik42@keats:$

**Comment by travisperson** [comment]
Can you provide your miner id?

**Comment by s0nik42** [comment]
f010479
