### ISSUE TITLE
Makefile debug

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4412]
ubuntu 20.4
sudo make install
**bash: go: command not found
expr: syntax error: unexpected argument ‘14’**
install -C ./lotus /usr/local/bin/lotus
install -C ./lotus-miner /usr/local/bin/lotus-miner
install -C ./lotus-worker /usr/local/bin/lotus-worker

go version
go version go1.15.2 linux/amd64

**Comment by iEddie-cmd** [comment]
ME 2

**Comment by k178613133** [comment]
try it

step1:
  make clean
step2:
  make
step3:
  make install

**Comment by k178613133** [comment]
another way

sudo vim /etc/sudoers

Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

add ":/usr/local/go/bin"

Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin"

**Comment by zgfzgf** [comment]
3k @k178613133

**Comment by Kubuxu** [comment]
The orginal issue was missing Golang installation.

**Comment by zgfzgf** [comment]
@Kubuxu  

add ":/usr/local/go/bin"   in  /etc/sudoers
Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin"

test ok
