### ISSUE TITLE
Devnet epoch durations do not reflect changes to BlockDelaySecs

### ISSUE THREAD

**Issue by ribasushi** [filecoin-project/lotus#4413]
**Describe the bug**

Devnet is built with the following modification to block-minting times: https://github.com/filecoin-project/lotus/blob/master/build/params_2k.go#L42

Yet none of the constants here follow https://github.com/filecoin-project/specs-actors/blob/v0.9.12/actors/builtin/network.go#L9-L21

This, among other effects, prevents deal-making in a local devnet.

**Comment by rjan90** [comment]
The deal making command now gets block delay specific to the build: https://github.com/filecoin-project/lotus/pull/8896. So I guess this issue can be closed now?

**Comment by ribasushi** [comment]
Probably!
