### ISSUE TITLE
how to get fee of a transaction

### ISSUE THREAD

**Issue by xihucuyu888** [filecoin-project/lotus#4417]
I wonder how to get the fee of a transfer Tx of filecoin from JSON-RPC API?
I used method 'StateGetReceipt'  but only got 'GasUsed' of a specific Tx.

**Comment by jennijuju** [comment]
StateMsgGasCost

**Comment by crossle** [comment]
> StateMsgGasCost

Thanks, the TotalCost is the transaction cost fee? burn+miner tip ?

**Comment by xihucuyu888** [comment]
![image](https://user-images.githubusercontent.com/41260909/96419610-f4336c00-1226-11eb-9f22-4ad5f2713e3a.png)

**Comment by xihucuyu888** [comment]
> StateMsgGasCost

![image](https://user-images.githubusercontent.com/41260909/96419650-031a1e80-1227-11eb-8f96-b7c0aecc9a82.png)

**Comment by crossle** [comment]
Move to StateReplay on master branch

**Comment by xihucuyu888** [comment]
> Move to StateReplay on master branch
but using sateReplay got error 
{"jsonrpc":"2.0","id":1,"error":{"code":1,"message":"given message not found in tipset"}}

**Comment by xihucuyu888** [comment]
{
    "jsonrpc": "2.0",
    "method": "Filecoin.StateReplay",
    "params": [
        [{"/":"bafy2bzacecxtevb7pvvynedzav2s74eeupvqmd6zi756yk7gzvyoawnidnsim"},{"/":"bafy2bzacedz4c3d3k7he57pajq5zr5xvcdq6i67vxzng5lracwbqfywykhqki"},{"/":"bafy2bzacecltvmi3aqku63kf6zmbxgjuwz5rb7mv7yv63qgxnlrcq7lk5s2ia"},{"/":"bafy2bzacecqeyefc6xwtupbx46not6wlgnvojsnyeaubrjxpzyvsgnvicjjgo"},{"/":"bafy2bzacecxrdim6gbcfiompbmqkpkb36m7orjbqna64hmfd2m7j7ltyr3ceq"},{"/":"bafy2bzaced6dgibxyzaqwgqycmonpdujszghxneygrlz5pbdhsigrmqzimqc4"},{"/":"bafy2bzacedihac3der2ut26jrbpnenpexdqplwkwhmbsqkaemzwfyjmrs2qle"}],
        {
            "/": "bafy2bzacebzqikmf6ltjrf7h6ic5jwwj6jlkucbfci35xmpikuiwgwdpyusj4"
        }
    ],
    "id": 1
}

**Comment by crossle** [comment]
Where you got the tipset?

**Comment by xihucuyu888** [comment]
> Where you got the tipset?

StateSearchMsg

**Comment by xihucuyu888** [comment]
tipset use null can work...

**Comment by crossle** [comment]
> > Where you got the tipset?
> 
> StateSearchMsg

StateSearchMsg is the next tipset, you can check the height.

**Comment by xihucuyu888** [comment]
> > > Where you got the tipset?
> > 
> > 
> > StateSearchMsg
> 
> StateSearchMsg is the next tipset, you can check the height.

use the right tipset also return error

**Comment by crossle** [comment]
> > > > Where you got the tipset?
> > > 
> > > 
> > > StateSearchMsg
> > 
> > 
> > StateSearchMsg is the next tipset, you can check the height.
> 
> use the right tipset also return error

Really？trying
