### ISSUE TITLE
Sync stalling

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#4427]
**Describe the bug**

After the initial bootstrap sync, node will stop syncing to incoming tipsets ... but seems to resume after a while.

I'm still looking at the code ... when the node is in the stuck state, it appears incoming tipsets are being flagged as "relatedToActiveSync" here:

https://github.com/filecoin-project/lotus/blob/7245ac2b699263d91321c4286f9b1a51eac4a91c/chain/sync_manager.go#L339

But I don't see an active sync when doing `watch lotus sync status`

**Version (run `lotus version`):**

```
$ lotus version
Daemon:  0.10.2+git.c56ef260d.dirty+api0.17.0
Local: lotus version 0.10.2+git.c56ef260d.dirty
```

**Comment by jimpick** [comment]
Looks like this was the original commit:

https://github.com/filecoin-project/lotus/commit/7a308b60a629c3bcc5fff3217f4b3fc0bfbccefb

**Comment by jimpick** [comment]
I commented out line 339 above and that fixes my sync issues.

**Comment by jimpick** [comment]
Here's a screen recording of the sync behaviour on an unpatched node (left) vs. patched (right) where I commented out the line above.

https://gateway.pinata.cloud/ipfs/QmRKFtDC9MffVbv9vLhH3PSkHbR7djjrHF9uhLWD2t4yzr/sync-head-to-head.mp4

**Comment by jimpick** [comment]
Here's a `lotus pprof goroutines` from the first node in the video above when it was stuck...

[lotus-pprof-go-routines-stuck.log](https://github.com/filecoin-project/lotus/files/5418794/lotus-pprof-go-routines-stuck.log)

**Comment by Kubuxu** [comment]
@jimpick are you able to reproduce it. Or is it one of?

**Comment by jimpick** [comment]
@Kubuxu Yes, it's happening constantly. I've observed it on multiple nodes.
