### ISSUE TITLE
dangling `reorgWorker` after snapshot import

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/lotus#4428]
https://github.com/filecoin-project/lotus/blob/151577f04ef264a63bedb86ef6bf527a64743c5d/chain/store/store.go#L190

Normally not an issue because the repo/store is not closed until the node stops but when importing we open/close the repo and the dangling thread fails with `datastore closed` error.

**Comment by raulk** [comment]
Oh, I actually noticed this independently and fixed it in https://github.com/filecoin-project/lotus/pull/4872.
