### ISSUE TITLE
lotus-miner storage-deals ask price not work.

### ISSUE THREAD

**Issue by ncgege** [filecoin-project/lotus#4430]
**Describe the bug**
It seems the setting of "Price per GiB/Epoch" doesn't work we can make deal with the miner even the price is less than what the miner set. my set is 0.00000001FIL
but we can deal with it with the price 0.000000001FIL
lotus client deal bafk2bzacecqco7bfne6ijox4dfyxzahepbhzetsp3gbys7aumz6qjpdr4zc46 f022566 0.000000001 518400
![image](https://user-images.githubusercontent.com/25341303/96210427-824bf000-0fa4-11eb-9a56-04b83a7b5797.png)
![image](https://user-images.githubusercontent.com/25341303/96210440-8841d100-0fa4-11eb-88a2-822f63bb7202.png)

![image](https://user-images.githubusercontent.com/25341303/96210415-7a8c4b80-0fa4-11eb-8962-07e16ef3e38e.png)
![image](https://user-images.githubusercontent.com/25341303/96210452-8ed04880-0fa4-11eb-84eb-1b19c9c1ddca.png)

**Comment by rjan90** [comment]
I think this issue can be closed? As the ask-price is working correctly on `lotus version 1.11.1-rc1+mainnet+git.193cb9134` #rengjøring

**Comment by jennijuju** [comment]
Please open a new ticket if you are running into this issue on the latest version of lotus!
