### ISSUE TITLE
message RequiredFunds error!!!

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4431]
https://github.com/filecoin-project/lotus/blob/17fcf30edd4af7df9154858b82b0158ba205c698/chain/types/message.go#L124-L126
lotus wallet list
Address                                                                                 Balance                        Nonce  Default  
t15tcg5ttp6czxvubfryhfgjmdanua24nhzfg2boi                                               **0.49999978027468768** FIL        2

twice send  **0.4**  
lotus mpool find
[
  {
    "Message": {
      "Version": 0,
      "To": "t1wi66adh3fcxw5xb4eai2iktgmc4qgvnm3u3uevy",
      "From": "t15tcg5ttp6czxvubfryhfgjmdanua24nhzfg2boi",
      "Nonce": 2,
      "Value": "**400000000000000000**",
      "GasLimit": 220000,
      "GasFeeCap": "101",
      "GasPremium": "10",
      "Method": 0,
      "Params": null,
      "CID": {
        "/": "bafy2bzacedooawj2hh5jkseuvbd3flyyu7u3l2klnqpreyider26ncokpn4ui"
      }
    },
    "Signature": {
      "Type": 1,
      "Data": "28+/79hS08b6B6J6BoLzX5aYX1VpX8vhGUy1sI2ZWNROw31XP95DZPZSGu6GvauEvmehzkA39+IflDfvWOQdBAA="
    },
    "CID": {
      "/": "bafy2bzacecjwv753ha7jccwkizuyabqrjjxjfxkmwi2flccmglu6zdfkca3vw"
    }
  },
  {
    "Message": {
      "Version": 0,
      "To": "t1wi66adh3fcxw5xb4eai2iktgmc4qgvnm3u3uevy",
      "From": "t15tcg5ttp6czxvubfryhfgjmdanua24nhzfg2boi",
      "Nonce": 3,
      "Value": "**400000000000000000**",
      "GasLimit": 220000,
      "GasFeeCap": "101",
      "GasPremium": "10",
      "Method": 0,
      "Params": null,
      "CID": {
        "/": "bafy2bzacecy7xelcqakhlfktg4gzglzcyilv5ihoinkpbiwsnfx6dq6fwflzw"
      }
    },
    "Signature": {
      "Type": 1,
      "Data": "E/qZyYcMxJH51AWPOu30wO9izyZ+rMdovpaJYofHKTYpd1Fe3izXtlMhd0ZOnca4uGcTEhMdEBEgGDuyIqlUUgA="
    },
    "CID": {
      "/": "bafy2bzacec6cragf4ulqkkrez6ujl6ib3bcmri6iszxwc2dounxinw5jq3bsm"
    }
  }
]

Orders like this
lotus send --from t1cvljqo7kvfgieuyhdwti5rqjwxpqpuvxoqqtdsy --gas-limit=542835 --gas-feecap=101957 --gas-premium=100903 t1gysw3km7bze6aldxdzbcr4yz5uxqyxrpk3au2aq  3

**Comment by rjan90** [comment]
I think this issue can be closed, as the fix has been merged! #rengjøring
