### ISSUE TITLE
StateSearchMsg not return the message correct tipset 

### ISSUE THREAD

**Issue by crossle** [filecoin-project/lotus#4436]
**Describe the bug**
I use StateSearchMsg query the message, but return the tipset not include the message, it's the messsage's next tipset

**To Reproduce**
StateSearchMsg RPC

**Expected behavior**
Return the tipset is the message tipset

**Version (run `lotus version`):**
0.10.2

**Additional context**

**Comment by Kubuxu** [comment]
`StateSearchMsg` returns the tipset where the message was executed, not included.

**Comment by crossle** [comment]
If i wanna to query the message's tipset height, i must use the tipset height-1

**Comment by Kubuxu** [comment]
What API are you using for that?

**Comment by arajasek** [comment]
Yes, the message would've been included in the parent of the tipset returned by `StateSearchMsg`. To find out exactly which block(s) included the message, use `ChainGetBlockMessages` on each block in the parent tipset.
