### ISSUE TITLE
 ChainGetTipSetByHeight method synchronization lacks message

### ISSUE THREAD

**Issue by yuzhongrong** [filecoin-project/lotus#4438]
![image](https://user-images.githubusercontent.com/7382234/96226266-fd250300-0fc4-11eb-98ef-baf65fe03f2d.png)

The ChainGetTipSetByHeight method cannot synchronize the messages under all miners and there are references
bug i used the ChainGetTipSetByHeight rpc 
Can't sync to that transaction

the method is  follow img:
![image](https://user-images.githubusercontent.com/7382234/96226485-4a08d980-0fc5-11eb-8357-d7ed8e68f336.png)

**Comment by yuzhongrong** [comment]
my transation in  blockid is  :bafy2bzacecjsjcw5qkptuy4ams62zefuw4cgkbsahnpuqofwwop7cw7e6zwwu

The third from last on page 10  in https://filfox.info/

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/96227158-47f34a80-0fc6-11eb-91bb-f4e0817d8e52.png)


5 missing

![Uploading image.png…]()

**Comment by crossle** [comment]
You use use the block cid get the message

**Comment by yuzhongrong** [comment]
use the block cid get the message?

**Comment by yuzhongrong** [comment]
First use the height to get the block cid and then use the blck cid to get the messages?

**Comment by crossle** [comment]
> First use the height to get the block cid and then use the blck cid to get the messages?

Yes

**Comment by yuzhongrong** [comment]
to get all message? in that block

**Comment by yuzhongrong** [comment]
ok  i  try  thanks

**Comment by yuzhongrong** [comment]
Get which rpc method used by blockcid

**Comment by yuzhongrong** [comment]
？

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/96228183-cb616b80-0fc7-11eb-8ffa-a079f7523d25.png)
this is the method

**Comment by yuzhongrong** [comment]
My usage is correct

**Comment by yuzhongrong** [comment]
I first get the miner cid on the block and then get the cids under each miner

**Comment by crossle** [comment]
> ![image](https://user-images.githubusercontent.com/7382234/96228183-cb616b80-0fc7-11eb-8ffa-a079f7523d25.png)
> this is the method

YES

**Comment by yuzhongrong** [comment]
no  
The total number of messages obtained by this method is incomplete

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/96229072-031ce300-0fc9-11eb-9c61-61475122d971.png)

Correct is 197  but  i get the count is  192  by ChainGetBlockMessages

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/96229463-876f6600-0fc9-11eb-9ecf-3af1e3d96d10.png)
![image](https://user-images.githubusercontent.com/7382234/96229499-92c29180-0fc9-11eb-9269-2e0afb925489.png)

**Comment by yuzhongrong** [comment]
This rpc method is too slow to get data

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/96235052-da96e800-0fcc-11eb-8853-50d5c116900f.png)

**Comment by yuzhongrong** [comment]
why?

**Comment by yuzhongrong** [comment]
My transaction cid is bafy2bzacebv7h5xsceyz6aqa4robpcjitdmldzkwydklmqzdvhw76d5zikono. Blockchain can be found, but rpc can’t.

**Comment by yuzhongrong** [comment]
come on

**Comment by crossle** [comment]
> My transaction cid is bafy2bzacebv7h5xsceyz6aqa4robpcjitdmldzkwydklmqzdvhw76d5zikono. Blockchain can be found, but rpc can’t.

You mean ChainGetBlockMessages not return your transaction? `bafy2bzacebv7h5xsceyz6aqa4robpcjitdmldzkwydklmqzdvhw76d5zikono`

**Comment by yuzhongrong** [comment]
yes

**Comment by yuzhongrong** [comment]
yes  yes

**Comment by yuzhongrong** [comment]
This transaction can be checked on the browser but rpc cannot be returned

**Comment by crossle** [comment]
No, the transaction can be return, i got it. you can send some code snippet to here

**Comment by yuzhongrong** [comment]
// 根据高度遍历区块所有交易
func TestClient_ChainGetTipSetByHeight(t *testing.T) {
	c := testClient()
	ts, err := c.ChainGetTipSetByHeight(context.Background(), 148936, nil)
	if err != nil {
		t.Error(err)
	}
	for _, n := range ts.Cids {
		t.Log(n)
		bm, err := c.ChainGetBlockMessages(context.Background(), n)
		if err != nil {
			t.Error(err)
		}
		len:=len(bm.BlsMessages)
		t.Log(len)

		for index, _ := range bm.BlsMessages {
			t.Log(bm.Cids[index])
		}
	}
}

**Comment by yuzhongrong** [comment]
i used the method  but cannot the cid of  bafy2bzacebv7h5xsceyz6aqa4robpcjitdmldzkwydklmqzdvhw76d5zikono

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/96249174-5dc13980-0fdf-11eb-854d-2db8a2206d28.png)

**Comment by crossle** [comment]
> BlsMessages

You transaction not BlsMessages, it's SecpkMessage

**Comment by yuzhongrong** [comment]
thi is go language  need to  

import (
	"context"
	"github.com/ipfs/go-cid"
	"testing"
)

**Comment by yuzhongrong** [comment]
What's the difference?

**Comment by yuzhongrong** [comment]
i need to  get the SecpkMessages?

**Comment by yuzhongrong** [comment]
![Uploading image.png…]()

**Comment by crossle** [comment]
> i need to get the SecpkMessages?

YES

**Comment by yuzhongrong** [comment]
![Uploading image.png…]()

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/96250865-1be5c280-0fe2-11eb-9e7c-89653c215b39.png)

**Comment by yuzhongrong** [comment]
but the cid  Incorrect，   the cid  shoud be  follow:


第1个 高度：148,936
 mpool_test.go:44: &{0 t1356myoubs6kexyp2hmxujwei6w5c27dggyyekgi t12sn74glfh34c2vbhff7hqwk76yekcqnff6tmtzy 1 1000000000000 539085 151785 150731 0 []}
    mpool_test.go:56: 1
    mpool_test.go:57: bafy2bzacebv7h5xsceyz6aqa4robpcjitdmldzkwydklmqzdvhw76d5zikono

**Comment by yuzhongrong** [comment]
![Uploading image.png…]()

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/96276711-f10d6580-1005-11eb-9ade-766b874d882d.png)
this transation no  cid

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/96276937-3467d400-1006-11eb-81be-b1fe30dd0972.png)

**Comment by yuzhongrong** [comment]
you can provide the code to me

**Comment by yuzhongrong** [comment]
anyone there

**Comment by crossle** [comment]
bm.Cids[index] is the message id, like other blockchains's transaction hash

**Comment by zhp1254** [comment]
jsonStr := []byte(fmt.Sprintf(`{ "jsonrpc": "2.0", "method": "Filecoin.StateReplay", "params": [[{"/":"%s"}],{"/":"%s"}], "id": 3 }`, blockHash, cid))

用这个接口

**Comment by EmilyCaoHong** [comment]
ChainGetBlockMessages returns BlsMessages and SecpkMessage, which is tranfer  not miner
