### ISSUE TITLE
lotus-miner storage-deals not holding Max Piece Size

### ISSUE THREAD

**Issue by Meatball13** [filecoin-project/lotus#4440]
**Describe the bug**
Similar to issue #4220, on a restart the lotus-miner is resetting the Max Piece Size down to 1 MiB.

```
Price per GiB/Epoch  Verified       Min. Piece Size (padded)  Max. Piece Size (padded)  Expiry (Epoch)  Expiry (Appx. Rem. Time)  Seq. No.
0.0000001 FIL        0.0000001 FIL  128 MiB                   1 MiB                     237661          719h59m0s                 79
```

**To Reproduce**
1. Run `lotus-miner storage-deals set-ask --price 0.0000001 --verified-price 0.0000001 --min-piece-size 128MiB --max-piece-size 32GiB`
2. Stop Miner
3. Restart Miner
4. Run `lotus-miner storage-deals get-ask` and check Min/Max Piece Size

**Expected behavior**
Miner should store set-ask values between restarts.

**Screenshots**

**Version (run `lotus version`):**
lotus version 0.10.2+git.8bb84acbc

**Additional context**

**Comment by KaptinLin** [comment]
We have the same issue. 

See the error and get ask config below:

![image](https://user-images.githubusercontent.com/999331/96311509-3187d600-103c-11eb-8a3d-719593a619de.png)


![image](https://user-images.githubusercontent.com/999331/96311463-1b7a1580-103c-11eb-91d0-e9987fa78040.png)
