### ISSUE TITLE
cannot initiate a state for identifier when make deals on miner

### ISSUE THREAD

**Issue by KaptinLin** [filecoin-project/lotus#4443]
**Describe the bug**
we have a client, which tries to make a deal with a miner
and you get this error at the miner side .

**To Reproduce**
See error
in miner we got
```
2020-10-15T08:34:32.615+0800  [34mINFO[0m  markets  loggers/loggers.go:19  storage event  {"name": "ProviderEventDataRequested", "proposal CID": "bafyreihgdrgul7bs6mpl5cnqemrgkqfv2juybggtca6w7t4jnghgk2olyu", "state": "StorageDealWaitingForData", "message": ""}
2020-10-15T08:34:32.629+0800  [33mWARN[0m  dt-impl  impl/receiver.go:24  Begin: cannot initiate a state for identifier `12D3KooWPe1HeKw6pbRqUZCCyUWMEV8qahWwEgtS9mPZbsQ1tLri-12D3KooWNCgSYULLYxeb89hJvWM8sEnCetPvpDus7AgS5i2fCfwF-288` that already exists
```
in the client side
```
./lotus/lotus_daemon.2020-10-15_08_45_01.gz:2020-10-15T08:34:32.632+0800        INFO    markets loggers/loggers.go:14   storage event   {"name": "ClientEventFailed", "proposal CID": "bafyreihgdrgul7bs6mpl5cnqemrgkqfv2juybggtca6w7t4jnghgk2olyu", "state": "StorageDealError", "message": "failed to initiate data transfer: deal data transfer failed: response rejected"}
```

**Version (run `lotus version`):**
v0.10.2

**Comment by ribasushi** [comment]
@KaptinLin are both client **and** miner running 0.10.2 ?

**Comment by KaptinLin** [comment]
yes, they are both 0.10.2

**Comment by hannahhoward** [comment]
@KaptinLin this happens multiple times in a row?

**Comment by KaptinLin** [comment]
It doesn't happens on every miners. But if happened on one miner, then almost all deals in this miner have this issues.

**Comment by stuberman** [comment]
I get this every few days as well...

> 2020-10-19T17:47:47.852Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventDataTransferInitiated", "proposal CID": "bafyreiero2o65iwt2psef2azf4a6ovuxizxvaiwqvwpayzamspzhkx2nr4", "state": "StorageDealTransferring", "message": ""}
> 2020-10-19T17:57:23.347Z	ERROR	storagemarket_impl	dtutils/dtutils.go:152	attempting to configure data store: %!w(*errors.errorString=&{already registerd a persistence option with this name})
> 2020-10-19T17:57:23.357Z	INFO	markets	loggers/loggers.go:19	storage event	{"name": "ProviderEventDataTransferRestarted", "proposal CID": "bafyreiero2o65iwt2psef2azf4a6ovuxizxvaiwqvwpayzamspzhkx2nr4", "state": "StorageDealTransferring", "message": ""}
> 2020-10-19T17:57:23.367Z	WARN	dt_graphsync	graphsync/graphsync.go:154	graphsync request context cancelled, channel Id: 12D3KooWM4nWYvTdsMpkneWWCo75PuyBg1PnXZWSCDbRL4LkyPMF-12D3KooWQvdhZSSArWTSBiyjVZa3mAmzoLHXV2QS9nFoaGLv3fL7-18
> 2020-10-19T17:57:23.367Z	WARN	dt-impl	impl/events.go:166	channel 12D3KooWM4nWYvTdsMpkneWWCo75PuyBg1PnXZWSCDbRL4LkyPMF-12D3KooWQvdhZSSArWTSBiyjVZa3mAmzoLHXV2QS9nFoaGLv3fL7-18 has timed out
> 2020-10-19T17:59:47.113Z	INFO	badger	v2@v2.2007.2/db.go:1030	Storing value log head: {Fid:515 Len:35 Offset:1073506845}
> 
> 2020-10-19T17:59:47.469Z	INFO	badger	v2@v2.2007.2/levels.go:1000	[Compactor: 0] Running compaction: {level:0 score:1 dropPrefixes:[]} for level: 0
> 
> 2020-10-19T17:59:47.919Z	INFO	badger	v2@v2.2007.2/levels.go:962	LOG Compact 0->1, del 6 tables, add 1 tables, took 449.232846ms
> 
> 2020-10-19T17:59:47.919Z	INFO	badger	v2@v2.2007.2/levels.go:1010	[Compactor: 0] Compaction for level: 0 DONE
> 2020-10-19T18:00:02.768Z	ERROR	evtsm	go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:83	Executing event planner failed: Slice value in field t.ReceivedCids was too long:
>     github.com/filecoin-project/go-data-transfer/channels/internal.(*ChannelState).MarshalCBOR
>         /home/stuart/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v0.9.0/channels/internal/internalchannel_cbor_gen.go:342
> 2020-10-19T18:00:02.772Z	WARN	dt_graphsync	graphsync/graphsync.go:167	graphsync error: normal shutdown of state machine
> 2020-10-19T18:00:02.774Z	ERROR	dt_graphsync	graphsync/graphsync.go:171	normal shutdown of state machine

**Comment by KaptinLin** [comment]
We still get this issue. Any update?

**Comment by Reiers** [comment]
Hi @KaptinLin 

Thanks for the report. The issue is outdated.

If this is a issue in the [current release ](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)- please open a new ticket.

Thank you !
