### ISSUE TITLE
无法获取转账交易 转账交易在SecpkMessages 集合中可以获取 但是如果取SecpkMessages交易是没有cid的

### ISSUE THREAD

**Issue by yuzhongrong** [filecoin-project/lotus#4446]
Unable to get the transfer transaction The transfer transaction can be obtained in the SecpkMessages collection, but there is no cid if the SecpkMessages transaction is taken

**Comment by yuzhongrong** [comment]
![Uploading image.png…]()

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/96328320-5009c380-1074-11eb-9a94-6678e39df11b.png)

**Comment by yuzhongrong** [comment]
how to get the cid  of secpkmessage?

**Comment by jennijuju** [comment]
The response of ChainGetBlockMessages has the CIDs and the messages already, for the bls messages, the indexes line up, for the secpk messages, you have to index them beyond the length of the bls messages

so if theres 10 bls messages and 15 secp messages, there will be a list of 25 cids, the first 10 for the bls messages and the second 15 for the secp

**Comment by yuzhongrong** [comment]
ok  thanks
