### ISSUE TITLE
Need too much gas  to init a new miner. And the price is expensive. How could I create a new miner?

### ISSUE THREAD

**Issue by verynohair** [filecoin-project/lotus#4450]

**Comment by verynohair** [comment]
I bought 103 FIL and run the command `lotus-miner init --owner=<owner> and --worker=<worker>` to initialize a new miner. But it shows ' GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: failed to init new actor (RetCode=16)'

**Comment by verynohair** [comment]
![image](https://user-images.githubusercontent.com/12292635/96329397-ee028b80-107e-11eb-83e5-6e3ffd31f750.png)

**Comment by jennijuju** [comment]
As the screenshot shown that there are two accounts, one of them has 0 FIL.

I was able to reproduced the error when i tried  to use the 0 balance account as my worker address, and i believe this is whats happening here.

use `lotus send --from=<account has balance> <worker address> <amount, can even be 0.00000001FIL>` to fund the desired worker address, then you should be able to initiate a new miner.

Please reopen the issue if the above  doesnt work.

**Comment by cyberdoy** [comment]
same issue for me.
there are funds on addresses since 24h.
![Screenshot from 2021-04-22 08-44-22](https://user-images.githubusercontent.com/78981610/115669347-74f33200-a348-11eb-9cde-9a0f6ae8ee6b.png)
![Screenshot from 2021-04-22 08-47-5](https://user-images.githubusercontent.com/78981610/115669350-758bc880-a348-11eb-8400-197d9814c275.png)
Thanks for your help

**Comment by armio** [comment]
I am having the same issue on the Nerpa network. 

<img width="1115" alt="Screen Shot 2021-04-30 at 2 56 29 PM" src="https://user-images.githubusercontent.com/5133318/116741533-41f21380-a9c4-11eb-9e51-94bb4e6a5050.png">

Both of my wallet adresses have 1000FIL.

**Comment by zhangrui231** [comment]
I am having the same issue on the Calibration network.

**Comment by Araquiel** [comment]
> I am having the same issue on the Calibration network.

have a same problem on calibnet

**Comment by Flare183** [comment]
Having the same issue here
