### ISSUE TITLE
 lotus state call ….   panic with error info : panic: reflect: NumField of non-struct type

### ISSUE THREAD

**Issue by vonhenry** [filecoin-project/lotus#4451]
lotus version v0.10.2

----------------
# lotus state call --value 0.01  f05  2  f035784
panic: reflect: NumField of non-struct type *address.Address
goroutine 1 [running]:
reflect.(*rtype).NumField(0x2c25bc0, 0xc0005a4240)
	/go/go-1.14.4/src/reflect/type.go:973 +0xb7
github.com/filecoin-project/lotus/cli.parseParamsForMethod(0xc00053e100, 0x17, 0x2, 0xc0002922c0, 0x1, 0x1, 0x0, 0xc000292030, 0x0, 0x0, ...)
	/nvme_data/Code/gitlab.com/vchengsong/lotus/cli/state.go:1639 +0x159
github.com/filecoin-project/lotus/cli.glob..func106(0xc000553e00, 0x0, 0x0)
	/nvme_data/Code/gitlab.com/vchengsong/lotus/cli/state.go:1545 +0x8a0
github.com/urfave/cli/v2.(*Command).Run(0x55d6a40, 0xc000553c80, 0x0, 0x0)
	/go/path/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000702480, 0xc0005539c0, 0x0, 0x0)
	/go/path/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:427 +0xa68
github.com/urfave/cli/v2.(*Command).startApp(0x55d6fe0, 0xc0005539c0, 0x7ffea5b3f5f4, 0x5)
	/go/path/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x68c
github.com/urfave/cli/v2.(*Command).Run(0x55d6fe0, 0xc0005539c0, 0x0, 0x0)
	/go/path/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0xa12
github.com/urfave/cli/v2.(*App).RunContext(0xc000702300, 0x3185ba0, 0xc000122000, 0xc000138000, 0x8, 0x8, 0x0, 0x0)
	/go/path/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/go/path/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc000702300)
	/nvme_data/Code/gitlab.com/vchengsong/lotus/cli/helper.go:34 +0x7c
main.main()
	/nvme_data/Code/gitlab.com/vchengsong/lotus/cmd/lotus/main.go:74 +0x649

**Comment by rjan90** [comment]
Hi!

Thanks for the report. The issue seems to be outdated / there has come a fix for the panic. When I tried to reproduce the issue, it only errored out.

```
lotus state call --value 0.01 f05 2 t01064
ERROR: decoding base64 value: illegal base64 data at input byte 4
```

If this is a issue in current release please open a new ticket.

Thanks again!
