### ISSUE TITLE
lotus daemon init failed 

### ISSUE THREAD

**Issue by k178613133** [filecoin-project/lotus#4453]
**Describe the bug**
lotus daemon init failed

**To Reproduce**
1.  Run 'lotus daemon'
2.  See error

ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/usr/local/lotus/node/modules/lp2p/addrs.go:98): 
failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12):
 failed to build lp2p.RawHost: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): could not build value group []config.Option[group="libp2p"]: received non-nil error from function "github.com/filecoin-project/lotus/node/modules/lp2p".ConnectionManager.func1 (/usr/local/lotus/node/modules/lp2p/libp2p.go:71): 
failed to get bootstrap peers: failed to parse multiaddr "/dns4/bootstrap-0.testnet.fildev.network/tcp/1347/p2p/12D3KooWJTUBUjtzWJGWU1XSiY21CwmHaCNLNYn2E7jqHEHyZaP7\r":
 invalid value "12D3KooWJT input isn't valid multihashn2E7jqHEHyZaP7\r" for protocol p2p: failed to parse p2p addr: 12D3KooWJTUBUjtzWJGWU1XSiY21CwmHaCNLNYn2E7jqHEHyZaP7

**Version (run lotus version):**
v0.10.2

**Comment by k178613133** [comment]
原来还是墙的问题。

**Comment by daring5920** [comment]
> 原来还是墙的问题。
你好，挂代理就解决了吗？还是要怎么弄，麻烦解惑下，我这里挂了香港的代理，还是报同样的错误，用的是测试网calibration

**Comment by jitash** [comment]
@k178613133 同问
