### ISSUE TITLE
Actor not found

### ISSUE THREAD

**Issue by verynohair** [filecoin-project/lotus#4455]
Run 'lotus-miner run', but the miner works incorrect. The error display below:

2020-10-17T17:31:54.518+0800    ERROR   miner   miner/miner.go:228      mining block failed: failed to get mining base info:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /opt/upload/all/lotus/miner/miner.go:363
  - failed to load miner actor: actor not found

So we cannnot continue to mine.

**Comment by arsenikt** [comment]
It is a network problem, trying change firewall / ports configuration, set port in config file and IP and reboot system (it really importable), after disable firewalls.

**Comment by Kubuxu** [comment]
@verynohair did you create the miner in the last 5h. Did it yresolve itself after 5h?

**Comment by theBigChups** [comment]
@arsenikt @Kubuxu Hi, guys. We got the same
```
2020-10-16T17:21:56.388Z        ERROR   miner   miner/miner.go:228      mining block failed: failed to get mining base info:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /home/ubuntu/lotus/miner/miner.go:363
  - failed to load miner actor: actor not found
```
Is there a way to be sure, that miner is working correctly? Something like a hashrate on PoW mining pool or maybe we can find our available disk sectors somewhere?

**Comment by Kubuxu** [comment]
@theBigChups did it resolve itself by now? For winning blocks we look 900 epochs back, so if your miner is a new account it will print this error. We should make it cleaner.

**Comment by xuhanyu-love** [comment]
> @theBigChups did it resolve itself by now? For winning blocks we look 900 epochs back, so if your miner is a new account it will print this error. We should make it cleaner.

It seems the problem has been solved.

**Comment by jennijuju** [comment]
duplicate #4324

**Comment by theBigChups** [comment]
> @theBigChups did it resolve itself by now? For winning blocks we look 900 epochs back, so if your miner is a new account it will print this error. We should make it cleaner.

@Kubuxu Thanks for the response! Yes, we don't see this error anymore, but we're getting this instead
```
2020-10-20T08:56:40.296Z        ERROR   advmgr  sector-storage/sched.go:370     trySched(1) req.sel.Ok error: finding best alloc storage:
    github.com/filecoin-project/lotus/extern/sector-storage.(*allocSelector).Ok
        /home/ubuntu/lotus/extern/sector-storage/selector_alloc.go:49
  - no good path found:
    github.com/filecoin-project/lotus/extern/sector-storage/stores.(*Index).StorageBestAlloc
        /home/ubuntu/lotus/extern/sector-storage/stores/index.go:406
2020-10-20T08:56:40.296Z        ERROR   advmgr  sector-storage/sched.go:370     trySched(1) req.sel.Ok error: finding best alloc storage:
    github.com/filecoin-project/lotus/extern/sector-storage.(*allocSelector).Ok
        /home/ubuntu/lotus/extern/sector-storage/selector_alloc.go:49
  - no good path found:
    github.com/filecoin-project/lotus/extern/sector-storage/stores.(*Index).StorageBestAlloc
        /home/ubuntu/lotus/extern/sector-storage/stores/index.go:406
2020-10-20T08:56:40.296Z        DEBUG   advmgr  sector-storage/sched.go:415     SCHED windows: [{allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]}]
2020-10-20T08:56:40.296Z        DEBUG   advmgr  sector-storage/sched.go:416     SCHED Acceptable win: [[] [] []]
```
Idk, does it relate to the previous error or not. Could you please tell any way to be sure, that miner is working correctly?

**Comment by jennijuju** [comment]
> > @theBigChups did it resolve itself by now? For winning blocks we look 900 epochs back, so if your miner is a new account it will print this error. We should make it cleaner.
> 
> @Kubuxu Thanks for the response! Yes, we don't see this error anymore, but we're getting this instead
> 
> ```
> 2020-10-20T08:56:40.296Z        ERROR   advmgr  sector-storage/sched.go:370     trySched(1) req.sel.Ok error: finding best alloc storage:
>     github.com/filecoin-project/lotus/extern/sector-storage.(*allocSelector).Ok
>         /home/ubuntu/lotus/extern/sector-storage/selector_alloc.go:49
>   - no good path found:
>     github.com/filecoin-project/lotus/extern/sector-storage/stores.(*Index).StorageBestAlloc
>         /home/ubuntu/lotus/extern/sector-storage/stores/index.go:406
> 2020-10-20T08:56:40.296Z        ERROR   advmgr  sector-storage/sched.go:370     trySched(1) req.sel.Ok error: finding best alloc storage:
>     github.com/filecoin-project/lotus/extern/sector-storage.(*allocSelector).Ok
>         /home/ubuntu/lotus/extern/sector-storage/selector_alloc.go:49
>   - no good path found:
>     github.com/filecoin-project/lotus/extern/sector-storage/stores.(*Index).StorageBestAlloc
>         /home/ubuntu/lotus/extern/sector-storage/stores/index.go:406
> 2020-10-20T08:56:40.296Z        DEBUG   advmgr  sector-storage/sched.go:415     SCHED windows: [{allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]}]
> 2020-10-20T08:56:40.296Z        DEBUG   advmgr  sector-storage/sched.go:416     SCHED Acceptable win: [[] [] []]
> ```
> 
> Idk, does it relate to the previous error or not. Could you please tell any way to be sure, that miner is working correctly?
> 
> The problem is I don't understand, how miner must publish its capacity. In documents that's said
> 
> > the Lotus Miner can run every of the sealing phases itself (and is configured to do so by default)
> 
> But I see nothing in the block explorer https://filfox.info/en/address/f045801, so miner didn't start do anything itself, as I understand.

It does not. This normally means the scheduler cannot find the resources to do the work. You can check that by lotus-miner sealing jobs. Open a discussion if you have more question!

**Comment by theBigChups** [comment]
@jennijuju Thanks. But I got this is log after I turned on the workers. Without workers, there is nothing in miner's cli at all, miner's output is not really helpful. It's better to add some logs (like a hashrate for PoW algorythms) or any other clear metrics, that can help understand that miner is working properly.
