### ISSUE TITLE
storage-deal maximum piece size set to 1MiB upon miner restart

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#4458]
**Describe the bug**
Since v0.10.2 when the lotus-miner restarts the maximum storage-deal piece size is set to 1MiB

**To Reproduce**

1. Run 'lotus-miner run'
2. See lotus-miner storage-deals get-ask
3. max-piece-size reset to 1MiB

**Expected behavior**
Expect former state (--max-piece-size 32GiB) to remain intact and not change to 1MiB

**Screenshots**
lotus-miner storage-deals get-ask
Price per GiB/Epoch  Verified          Min. Piece Size (padded)  Max. Piece Size (padded)  Expiry (Epoch)  Expiry (Appx. Rem. Time)  Seq. No.
0.000000002 FIL      0.0000000005 FIL  100 KiB                   1 MiB                    241345          710h55m0s                 37

**Version (run `lotus version`):**
Daemon:  0.10.2+git.8bb84acb+api0.15.0
Local: lotus-miner version 0.10.2+git.8bb84acb

**Additional context**
Only appeared from v0.10.2 - after deal duration option was removed

**Comment by kernelogic** [comment]
1MB?!!

**Comment by hsanjuan** [comment]
@magik6k maybe you do want to take https://github.com/filecoin-project/lotus/pull/4334, given #4384 did not fix it.

**Comment by William8Work** [comment]
got the same problem:

2020-10-18T21:04:09.830-0700	WARN	providerstates	providerstates/provider_states.go:501	deal bafyreicoyg64r4od6vw6boxzvvmz66v2vfza6n35awu6i4uo5uloso2wuu failed: deal rejected: piece size more than maximum allowed size: 134217728 > 1048576

**Comment by CD-oursoft** [comment]
Use the command：lotus-miner storage-deals set-ask --price=0.0000000005 --verified-price= 0.00000000005 --min-piece-size=256B --max-piece-size=32GiB

**Comment by CD-oursoft** [comment]
Use the command：lotus-miner storage-deals set-ask --price=0.0000000005FIL --verified-price=0.00000000005FIL --min-piece-size=256B --max-piece-size=32GiB  ，Can solve your problem

**Comment by stuberman** [comment]
Manually setting the prices does not fix the problem - the problem is that when you restart the miner the maximum prices changes to 1MiB.

**Comment by stuberman** [comment]
Same issue as  reported here: [4440](https://github.com/filecoin-project/lotus/issues/4440)

**Comment by pooja** [comment]
@stuberman Did #4480 fix this issue?

**Comment by stuberman** [comment]
Yes! Works great now
