### ISSUE TITLE
lotus同步问题

### ISSUE THREAD

**Issue by yzn5555** [filecoin-project/lotus#4459]
lotus同步数据通过lotus ysnc wait 命令，查看到在同步的时候获取到一个Target高度，然后Current Epoch追这个高度，追上了，然后又重新获取新的高度，current Epoch又从0开始追这个高度，造成了一个循环，为什么会出现这个情况，不应该是应该从之前target高度之后开始追最新的高度吗？
区块同步往后越来越慢了，同步到10万左右很慢了，磁盘占用空间490G
![image](https://user-images.githubusercontent.com/36029121/96357569-35952000-1130-11eb-9f4c-e40a4296d3d8.png)

**Comment by jennijuju** [comment]
hmm this is the first time that such behaviour is reported, can you tell us how we can reproduce it?
For example, which version are you on, did you use a snapshot,  did you restart the daemon in the process and so on.

**Comment by yzn5555** [comment]
程序版本是一路升级过来的，当前版本为：v0.10.2，之前是使用的v0.10.0 v0.10.1版本，数据没有动，是直接替换程序，然后启动程序的，启动程序方法为：nohup ./lotus daemon >/var/log/lotus.log 2>&1 &   没有使用快照，在程序期间有过重新启动守护进程，

**Comment by yzn5555** [comment]
之前有一种守护进程方法是systemctl start lotus-daemon 这种方法好像会自动重启守护进程，当current Epoch高度达到target的时候会自动重启程序

**Comment by rjan90** [comment]
I think this issue can be closed now as there has been done some great improvements in syncing since this issue? #rengjøring
