### ISSUE TITLE
in the err != nil branch of computePost, miss scheduling Next Post

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/lotus#446]
I think here is bug : in the err != nil branch, miss scheduling Next Post:
![image](https://user-images.githubusercontent.com/33315004/67291865-bf59df80-f514-11e9-936e-39bf633293be.png)

**Comment by whyrusleeping** [comment]
@taoshengshi this one should be resolved now, want to take a look at the code again?

**Comment by magik6k** [comment]
That was fixed, and now this code is completely rewritten, in a way more resilient way

**Comment by taoshengshi** [comment]
copy that.
