### ISSUE TITLE
通过快照导入

### ISSUE THREAD

**Issue by yzn5555** [filecoin-project/lotus#4460]
通过官网car文件导入全节点这种方法，导入成功后，正常启动lotus，查询当前高度，为什么会从0开始，程序运行了一晚上高度才打到：10546,这也太慢了吧

**Comment by jennijuju** [comment]
Close this issue as it is mostly duplicated with #4459 . 
FYI - it took me ~2.5 hr to dowanload the snapshot, performs a `lotus daemon --import-snapshot --halt-after-import` and finish a full sync on my 8gb ram laptop.

**Comment by yzn5555** [comment]
加载快照到完全同步耗时多久？

> Close this issue as it is mostly duplicated with #4459 .
> FYI - it took me ~2.5 hr to dowanload the snapshot, performs a `lotus daemon --import-snapshot --halt-after-import` and finish a full sync on my 8gb ram laptop.

快照导入到完全同步耗时多久？
