### ISSUE TITLE
 Can't go from step pc2 to step c1

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#4463]
Can't go from step pc2 to step c1.  After a few days, the packing operation hasn't changed

lotus-miner sealing jobs
ID  Sector  Worker  Hostname  Task  State  Time

lotus-miner sectors list
ID  State           OnChain  Active  Expiration                    Deals
1   Proving         YES      YES     1688986 (in 1 year 23 weeks)  CC
6   RecoverDealIDs  NO       NO      n/a                           3
**7   Packing              NO       NO      n/a                           2**
19  PreCommit2      NO       NO      n/a                           CC
20  PreCommit2      NO       NO      n/a                           CC
23  PreCommit2      NO       NO      n/a                           CC
24  PreCommit2      NO       NO      n/a                           CC
25  PreCommit1      NO       NO      n/a                           CC
**33  Packing              NO       NO      n/a                           2**
34  PreCommit1      NO       NO      n/a                           CC
35  PreCommit1      NO       NO      n/a                           CC
36  PreCommit1      NO       NO      n/a                           CC
38  PreCommit2      NO       NO      n/a                           CC
39  PreCommit1      NO       NO      n/a                           1

**Version**
Daemon:  0.10.2+git.0f5aa9ba+api0.17.0
Local: lotus version 0.10.2+git.0f5aa9ba

**Comment by rjan90** [comment]
This sounds like you don't have a worker that can do C2. This issue can probably be closed now! #rengjøring
