### ISSUE TITLE
run `lotus daemon ` got `SIGILL illegal instruction`

### ISSUE THREAD

**Issue by toolmanlife** [filecoin-project/lotus#4467]
**Describe the bug**
run `lotus daemon ` got `SIGILL illegal instruction`.

**To Reproduce**
1. Run 'lotus daemon'
2. crash with `illegal instruction`

**Expected behavior**
run lotus sycn normally

**Screenshots**
![image](https://user-images.githubusercontent.com/64573434/96395908-6e98c780-11f8-11eb-9885-ffc360851154.png)
![image](https://user-images.githubusercontent.com/64573434/96396105-f383e100-11f8-11eb-86d8-c1a367287e21.png)

**Version (run `lotus version`):**
lotus version 0.10.0
**Additional context**
I built the lotus in the same cpu model with running machine.Intel E5-2678,one machine can run normal,but this crash.

**Comment by ryderkun** [comment]
you can add the environment variable to compile
export CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
export CGO_CFLAGS="-D__BLST_PORTABLE__"
