### ISSUE TITLE
the miner's memory  will  increase continually  when more deal is received.

### ISSUE THREAD

**Issue by 15012700225** [filecoin-project/lotus#4468]
**Describe the bug**
the miner's memory  will  increase continually  when more deal is received.

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by 15012700225** [comment]
[
![Screenshot from 2020-09-14 09-24-52](https://user-images.githubusercontent.com/57610562/96402778-52515680-1209-11eb-8107-c08740bea205.png)

](url)

**Comment by 15012700225** [comment]
[](url)

![Uploading Screenshot from 2020-10-19 12-52-24.png…]()

**Comment by 15012700225** [comment]
![Screenshot from 2020-10-19 12-52-24](https://user-images.githubusercontent.com/57610562/96403158-2f737200-120a-11eb-962a-4cd69a3719f8.png)

**Comment by Stebalien** [comment]
Next time this happens, could you take and upload a full heap profile:

```
curl "http://localhost:5001/debug/pprof/goroutine?debug=2" > stacks.txt
curl "http://localhost:1234/debug/pprof/heap" > heap.pprof
```

Then upload these here.

**Comment by Yarkin** [comment]
bytes:  264kB
  375.15GB   github.com/ipfs/go-merkledag/pb.(*PBNode).Unmarshal
             github.com/ipld/go-ipld-prime-proto.(*_PBNode__Builder).DecodeDagProto
             github.com/ipld/go-ipld-prime-proto.PBDecoder
             github.com/ipld/go-ipld-prime/linking/cid.Link.Load
             github.com/ipld/go-ipld-prime/traversal.Progress.loadLink
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv_iterateAll
             github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv
             github.com/ipld/go-ipld-prime/traversal.Progress.WalkAdv
             github.com/ipfs/go-graphsync/ipldutil.(*traverser).start.func1

**Comment by rjan90** [comment]
This issue has been fixed in the newer versions of Lotus, can be closed now! #rengjøring
