### ISSUE TITLE
Submitted several sectors. But the byte power is still 0

### ISSUE THREAD

**Issue by verynohair** [filecoin-project/lotus#4469]
The miner has been committed 5 sectors. But the byte power shows 0. Detail shows below:

Sector Size: 32 GiB
Byte Power:   0 B / 597.5 PiB (0.0000%)
Actual Power: 0  / 598 Pi (0.0000%)
        Committed: 160 GiB
        Proving: 0 B
Below minimum power threshold, no blocks will be won
Deals: 0, 0 B
        Active: 0, 0 B (Verified: 0, 0 B)

Miner Balance: 1.107392279255823913 FIL
        PreCommit:   0 FIL
        Pledge:      0.937906674901726137 FIL
        Vesting:     0 FIL
        Available:   0.169485604354097776 FIL
Worker Balance: 78.892580529479338954 FIL
Market (Escrow):  0 FIL
Market (Locked):  0 FIL

Expected Seal Duration: 24h0m0s

Sectors:
        Total: 12
        Proving: 5
        PreCommit1: 3
        SealPreCommit1Failed: 4

And I run command 'lotus-miner sectors list', it display:

ID  State                 OnChain  Active  Expiration                    Deals  
0   Proving               YES      NO      1709575 (in 1 year 24 weeks)  CC     
1   PreCommit1            NO       NO      n/a                           CC     
2   PreCommit1            NO       NO      n/a                           CC     
3   SealPreCommit1Failed  NO       NO      n/a                           CC     
4   SealPreCommit1Failed  NO       NO      n/a                           CC     
5   Proving               YES      NO      1709575 (in 1 year 24 weeks)  CC     
6   Proving               YES      NO      1709575 (in 1 year 24 weeks)  CC     
7   Proving               YES      NO      1712455 (in 1 year 24 weeks)  CC     
8   Proving               YES      NO      1709575 (in 1 year 24 weeks)  CC     
9   PreCommit1            NO       NO      n/a                           CC     
10  SealPreCommit1Failed  NO       NO      n/a                           CC     
11  SealPreCommit1Failed  NO       NO      n/a                           CC 

It seems all status of the proving sectors are not Active. Why?
Or should I do something to help to change status? 

The miner id is f042498.

lotus-miner version 0.10.2+git.4a057d84b.dirty

**Comment by RobQuistNL** [comment]
It takes 24 hours. Once your sectors in proving hit the first proving window they will count as you power.

**Comment by rjan90** [comment]
This issue can be closed! #rengjøring

**Comment by raulk** [comment]
This miner never submitted their first WindowPoSt, that's the reason they never acquired power.
