### ISSUE TITLE
StateReplay returns result very slow

### ISSUE THREAD

**Issue by Victoryfan** [filecoin-project/lotus#4473]
I use the StateReplay to get transaction totalCost, but it return very slow through the http request. It takes 10 secondes. How can I make it quick. Or other way to get totalCost.
My command is:`curl -X POST 'http://127.0.0.1:1234/rpc/v0' --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0","method":"Filecoin.StateReplay","id":2,"params": [null,{"/":"bafy2bzacebmaxy3lbmo4m6pilxmojvsdyzvu667ox3ohlkgdtjw72sb6cgd72" }]}'`

Please help me. Thank you in advance.

**Comment by jennijuju** [comment]
Pass in the tipset keys to avoid going through the chain state to find the message will make the response time faster.

**Comment by crossle** [comment]
Still slow when pass tipset key use on StateReplay
