### ISSUE TITLE
Miner ID cannot be searched  in filfox

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#4474]
Search miner account on the filfox site and click Cliam account next to the account address, and the message Address fxxxxxx not exits appears.

**Describe the problem**

A brief description of the problem you encountered while proving (sealing) a sector.

Including what commands you ran, and a description of your setup, is very helpful.

**Sectors status**

The output of `lotus-miner sectors status --log <sectorId>` for the failed sector(s).

**Lotus miner logs**
2020-10-19T20:39:40.103+0900    ERROR   miner   miner/miner.go:228      mining block failed: failed to get mining base info:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /home/coinuser/lotus/miner/miner.go:363
  - failed to load miner actor: actor not found
2020-10-19T20:39:41.109+0900    ERROR   miner   miner/miner.go:228      mining block failed: failed to get mining base info:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /home/coinuser/lotus/miner/miner.go:363
  - failed to load miner actor: actor not found
2020-10-19T20:39:42.116+0900    ERROR   miner   miner/miner.go:228      mining block failed: failed to get mining base info:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /home/coinuser/lotus/miner/miner.go:363
  - failed to load miner actor: actor not found
![20201019_203900](https://user-images.githubusercontent.com/70571701/96445739-58682700-124b-11eb-84ff-510b2061a799.png)

Please go through the logs of your miner, and include screenshots of any error-like messages you find.

Alternatively please upload full log files and share a link here

**Lotus miner diagnostic info**

Please collect the following diagnostic information, and share a link here

* lotus-miner diagnostic info `lotus-miner info all > allinfo`

** Code modifications **

If you have modified parts of lotus, please describe which areas were modified,
and the scope of those modifications

**Version**
Daemon:  0.10.2+git.0f5aa9ba+api0.17.0
Local: lotus version 0.10.2+git.0f5aa9ba

**Comment by jennijuju** [comment]
the error cause see #4324 
and future filfox issue should not be reported in lotus.
