### ISSUE TITLE
Command to determine current market balance

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#4479]
As a client or miner, I would like to be able to see information about funds I have in the storage market actor.

How:
create `lotus wallet market-balance` API which should show how much funds I have in the storage market actor, both Locked and Escrow.
if first argument passed, use that as wallet address, otherwise use default (not an optional flag, just a numbed argument)

Should be straight forward to just call StateMarketBalance and produce sensible output (can use the miner-info command from Lotus Storage Miner as a model)

**Comment by ingar** [comment]
This is already implemented in `./lotus state market balance <address>`, without the default address convenience.
