### ISSUE TITLE
Rename price to total price in list-deals output 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4483]
Show ask-price in `lotus client list-deals` and `lotus-miner storage-deals list` and rename `price` to total price to provide more clarity.

**Comment by jennijuju** [comment]
@ribasushi  if the total price doesnt have anything to do with the miner's asked price precisely, does it still make sense to add this column?

**Comment by ingar** [comment]
`total price` makes sense, although we don't have any information about the ask that this deal might have been based on.
