### ISSUE TITLE
"parent-grinding fault" filter in block producing

### ISSUE THREAD

**Issue by leviok** [filecoin-project/lotus#4492]
In mine function, there is a SlashFilter to prevent consensus breaking. there is a parent-grinding fault checking. [code line](https://github.com/filecoin-project/lotus/blob/1c6ea75f4b37cfb8aba7e3854918be68a7bc8024/chain/gen/slashfilter/slashfilter.go#L56)

but i found that "parent-grinding fault" checking in actor is that, blockA and blockC both have the same parents, blockB's parents include A but not include C. it's not the same as the checking in mine function.

now, the filter cause that if i produced a block on a side chain(due to less weight parents or something else, it isn't on chain). In next round,  GetBestMiningCandidate will return a mining base which doesn't include my previous block, the block I produced will not be on chain too. i don't think it's normal.

Is there any reason I don't know? Is it related to mpool?

**Comment by whyrusleeping** [comment]
@Kubuxu could you look into this?

**Comment by leviok** [comment]
#4622

**Comment by rjan90** [comment]
Hey @leviok! If you followed the discussion in https://github.com/filecoin-project/lotus/pull/7834 this issue would need a FIP for it and I will therefore close this issue for now. That said, winning two consecutive blocks where the first block is invalid is very rare, so it´s not something that would happen often.

> Moving discussion of the actual problem to https://github.com/filecoin-project/FIPs/discussions/402. Closing this down because the path forward won't involve code like this: its either going to be to do nothing, or remove this type of consensus fault from fault checking.
