### ISSUE TITLE
Chain sync exception: the syncer status is complete, but the chain does not grow

### ISSUE THREAD

**Issue by hfmhx** [filecoin-project/lotus#4518]
**Describe the bug**
After lotus daemon is started, it runs for more than ten minutes, the chain does not continue to grow, the execution of "lotus chain list" will block or the list will not update, the execution of "lotus sync status" will display Stage: complete, but the height will no longer increase

**To Reproduce**
1. Run 'lotus daemon'
2. Wait some time，Chain stops growing

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44537744/96716282-6b0f6700-13d7-11eb-94c0-b94101238968.png)
![image](https://user-images.githubusercontent.com/44537744/96716319-795d8300-13d7-11eb-8d96-05398d6ed380.png)

**Version (run `lotus version`):**
Daemon:  1.1.0+git.420ec18.dirty+api0.17.0
Local: lotus version 1.1.0+git.420ec18.dirty

**Additional context**
When the lotus chain list command is blocked, there is no more log "new block over pubsub", all blocks are obtained through hello, but the chain does not grow
[debug.log](https://github.com/filecoin-project/lotus/files/5415653/debug.log)

Sometimes the lotus chain list is not blocked after lotus is started, but the chain still does not grow. At this time, the log keeps printing "sync target bucket was nil when heaviestTipSet got called on it"（I modified some printing for debugging）
![image](https://user-images.githubusercontent.com/44537744/96717180-a78f9280-13d8-11eb-88d8-28325dfacc07.png)

**Comment by jimpick** [comment]
Sounds like it could be this #4427 ... I was able to fix it by commenting out a single line of code

**Comment by Kubuxu** [comment]
`sync target bucket was nil when ...` is just noise
