### ISSUE TITLE
lotus daemon --lite: StateNetworkVersion is always 0

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#4519]
This prevents the multisig creation from working.

**Comment by dirkmc** [comment]
This should be fixed when https://github.com/filecoin-project/lotus/pull/4497 is merged.
However if we need it sooner it's an easy change

**Comment by Geo25rey** [comment]
@whyrusleeping Should this issue be closed since #4263 was merged?

**Comment by Kubuxu** [comment]
Resolved in #4263
