### ISSUE TITLE
log splitting future request

### ISSUE THREAD

**Issue by ncgege** [filecoin-project/lotus#4530]
**the lotus daemon and miner log file will be bigger and bigger.
when the lotus daemon and miner is runnig we can't remove the log .
we need some function ,when the log reach to a fixed size rename it by date.log and write new logs to a fresh log file.**

**Comment by rjan90** [comment]
Has this issue been resolved, if not please file this as an [Feature Request]? #rengjøring

**Comment by ncgege** [comment]
not resolved ,yet.

**Comment by rjan90** [comment]
Hey @ncgege. Check this [https://github.com/filecoin-project/lotus/issues/6984#issuecomment-895772761](https://github.com/filecoin-project/lotus/issues/6984#issuecomment-895772761). It should help you to rotate logs :smile:
