### ISSUE TITLE
lost balance, show 'ERROR: GasEstimateMessageGas error: estimating gas used: CallWithGas failed: call raw get actor'

### ISSUE THREAD

**Issue by verynohair** [filecoin-project/lotus#4531]
I have bought 20 FIL with 600 USDT. Then I create a new miner to mine. But the daemon sync very slowly after I run 'lotus-miner sectors pledge'. Even the tipset height cannot grow. I shutdown all the daemon progress and restart them. But when I run 'lotus wallet list'. The address is empty?

Why? 

ERROR: GasEstimateMessageGas error: estimating gas used: CallWithGas failed: call raw get actor: resolution lookup failed (f3vv6id5jkwqsbnes43meuptp5orue5jfgg7dzszugvqkglszrlwy44j563rl3ncjjyxlel2a425h55jzbn6eq): resolve address f3vv6id5jkwqsbnes43meuptp5orue5jfgg7dzszugvqkglszrlwy44j563rl3ncjjyxlel2a425h55jzbn6eq: actor not found

I want to get my money?????????????

I'm very ungry. Why there are so many bugs. I had confidence of this project ago. But now It takes me a great deficit.

**Comment by verynohair** [comment]
@magik6k @whyrusleeping @arajasek @Stebalien

**Comment by rjan90** [comment]
I think this issue can be closed?  #rengjøring
