### ISSUE TITLE
节点迁移

### ISSUE THREAD

**Issue by yzn5555** [filecoin-project/lotus#4532]
当前有一个filecoin全节点，现在需要重新搭建一个filecoin全节点，可以通过拷贝节点完整数据到新的服务器，在新的服务器上启动程序实现迁移吗，还有别的方法吗？快照方法试验了不可行，自定义快照生成的文件只有1M不知道是怎么回事，使用的命令是：lotus chain export 快照文件名  ；使用：lotus export --skip-old-msgs --recent-stateroots=900 <filename>  提示没有export参数

**Comment by tinshen** [comment]
用官方的快照可以迁移。

lotus daemon --import-snapshot https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car

**Comment by yzn5555** [comment]
这种快照方法我测试过来，不行，这种快照还原不是全节点的，历史数据没有，起始块数据不是从0开始的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/lotus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午3:59
收件人:&nbsp;"filecoin-project/lotus"<lotus@noreply.github.com&gt;;
抄送:&nbsp;"1076813060"<1076813060@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [filecoin-project/lotus] 节点迁移 (#4532)





 
用官方的快照可以迁移。
 
lotus daemon --import-snapshot https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car

**Comment by xiaoshoulin** [comment]
那个快照是minimal的，全节点的快照是 lotus daemon --import-chain https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/complete_chain_with_finality_stateroots_latest.car

**Comment by yzn5555** [comment]
这个全节点我之前也在别的机器上使用了，感觉数据下载大约需要两个小时，导入成功后启动程序，速度也很慢，显示起始块是从0开始，但是速度很慢，程序运行两天，才同步到两万多


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/lotus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午4:17
收件人:&nbsp;"filecoin-project/lotus"<lotus@noreply.github.com&gt;;
抄送:&nbsp;"1076813060"<1076813060@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [filecoin-project/lotus] 节点迁移 (#4532)





 
那个快照是minimal的，全节点的快照是 lotus daemon --import-chain https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/complete_chain_with_finality_stateroots_latest.car

**Comment by xuhanyu-love** [comment]
deamon的块文件尺寸会越来越大，我的几个2TB的SSD可能都不够用，如果满了，你们一般是怎么迁移的？

**Comment by rjan90** [comment]
Has this been resolved? #rengjøring
