### ISSUE TITLE
怎么通过api获取消息的确认数量

### ISSUE THREAD

**Issue by qq71151461** [filecoin-project/lotus#4534]
![image](https://user-images.githubusercontent.com/464274/96848714-5a1e2e80-1487-11eb-98e0-a1e37f646bc0.png)

**Comment by zgfzgf** [comment]
现在最新高度 - 区块高度

**Comment by qq71151461** [comment]
原来如此，谢谢啦

**Comment by rjan90** [comment]
This issue can be closed since it has been resolved how you get the # of confirmations. #rengjøring
