### ISSUE TITLE
Scheduler does not run after FinalizeSector

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#4537]
After a sector is done sealing and is moved to permanent storage, the scheduler does not run. This results in my scratch disk remaining partially empty until something triggers it again and it starts doing the next PC1. E.g. a manual pledge will trigger a new PC1 to be started too, but it's not realistic to baby sit it. Could we have it trigger on a successful FinalizeSector to see if there's new work that can be done?

**Comment by rjan90** [comment]
Hey!

Closing this issue as it´s outdated and numerous scheduling improvements has been made since this issue were reported. If you still are seeing issues with the scheduler not running on the newer versions of Lotus, please add a new report.

Thanks again for this report 😄
