### ISSUE TITLE
sectorID restart from 2 once meta is reset

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#455]
## Description: 
The sectorID for `store-garbage` restarted from 2 after I restart `lotus-storage-miner run` after deleted all data in meta folder. 

## Why doing this
I am trying to recover the lotus-storage-miner after doing the test described in #439. The workaround is to clean all data in meta directory and restart it. It works well, except of some local meta info loss.

## Reproduce
0. run `lotus-storage-miner run`, and run `lotus-storage-miner store-garbage`  to get some power
1. stop `lotus-storage-miner run` process
2. delete all data in .lotusstorage/meta/ 
3. restart `lotus-storage-miner run`
4. run `lotus-storage-miner store-garbage`

**Comment by whyrusleeping** [comment]
this has been fixed
