### ISSUE TITLE
lotus send problem

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4550]
Find the amount first
Then transfer the money
No recurrence

wallet list call GetActor success
send  call GetActor fail

It could be problem mp.curTs 
pending, ts := mpool.PendingFor(fromA) in /full/gas.go L217

zgf@server:/run/first_lotus$ lotus wallet list
Address                                                                                 Balance                          Nonce  Default  
t1s2ct77b2mbns5nyfiaxs5fuwf2fxkmusn4tfgqy                                               300 FIL                          0               
t3rwdzn6rzyyhzwnv3rmhv2xxvlrb3le5i2rgazu2y7mku2idpf2h436o2glf6uxazz6btul35mx553mie54va  49997879.999745597473780648 FIL  5      X        
t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq  1000 FIL                         0               
t3vj4gc4v3sjqwzopbhjinhwmvpszxxmjhoplzdqd3zfhrptm6mhwvqglgo334tmqshg2fqeygzjkx7sl3gudq  820 FIL                          0               
zgf@server:/run/first_lotus$ lotus send --from t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq t1s2ct77b2mbns5nyfiaxs5fuwf2fxkmusn4tfgqy 1
ERROR: GasEstimateMessageGas error: estimating gas used: CallWithGas failed: call raw get actor: resolution lookup failed (t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq): resolve address t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq: actor not found

2020-10-23T11:13:29.405+0800	WARN	rpc	go-jsonrpc@v0.1.2-0.20201008195726-68c6a2704e49/handler.go:241	error in RPC call to 'Filecoin.MpoolPushMessage': GasEstimateMessageGas error:
    github.com/filecoin-project/lotus/node/impl/full.(*MpoolAPI).MpoolPushMessage
        /home/zgf/gopath/src/github.com/zgfzgf/lotus/node/impl/full/mpool.go:157
  - estimating gas used:
    github.com/filecoin-project/lotus/node/impl/full.(*GasModule).GasEstimateMessageGas
        /home/zgf/gopath/src/github.com/zgfzgf/lotus/node/impl/full/gas.go:273
  - CallWithGas failed:
    github.com/filecoin-project/lotus/node/impl/full.gasEstimateGasLimit
        /home/zgf/gopath/src/github.com/zgfzgf/lotus/node/impl/full/gas.go:236
  - call raw get actor:
    github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).CallWithGas
        /home/zgf/gopath/src/github.com/zgfzgf/lotus/chain/stmgr/call.go:195
  - resolution lookup failed (t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq):
    github.com/filecoin-project/lotus/chain/state.(*StateTree).GetActor
        /home/zgf/gopath/src/github.com/zgfzgf/lotus/chain/state/statetree.go:285
  - resolve address t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq:
    github.com/filecoin-project/lotus/chain/state.(*StateTree).lookupIDinternal
        /home/zgf/gopath/src/github.com/zgfzgf/lotus/chain/state/statetree.go:250

**Comment by gaozhengxin** [comment]
> Find the amount first
> Then transfer the money
> No recurrence
> 
> wallet list call GetActor success
> send call GetActor fail
> 
> It could be problem mp.curTs
> pending, ts := mpool.PendingFor(fromA) in /full/gas.go L217
> 
> zgf@server:/run/first_lotus$ lotus wallet list
> Address Balance Nonce Default
> t1s2ct77b2mbns5nyfiaxs5fuwf2fxkmusn4tfgqy 300 FIL 0
> t3rwdzn6rzyyhzwnv3rmhv2xxvlrb3le5i2rgazu2y7mku2idpf2h436o2glf6uxazz6btul35mx553mie54va 49997879.999745597473780648 FIL 5 X
> t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq 1000 FIL 0
> t3vj4gc4v3sjqwzopbhjinhwmvpszxxmjhoplzdqd3zfhrptm6mhwvqglgo334tmqshg2fqeygzjkx7sl3gudq 820 FIL 0
> zgf@server:/run/first_lotus$ lotus send --from t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq t1s2ct77b2mbns5nyfiaxs5fuwf2fxkmusn4tfgqy 1
> ERROR: GasEstimateMessageGas error: estimating gas used: CallWithGas failed: call raw get actor: resolution lookup failed (t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq): resolve address t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq: actor not found
> 
> 2020-10-23T11:13:29.405+0800 WARN rpc go-jsonrpc@v0.1.2-0.20201008195726-68c6a2704e49/handler.go:241 error in RPC call to 'Filecoin.MpoolPushMessage': GasEstimateMessageGas error:
> github.com/filecoin-project/lotus/node/impl/full.(*MpoolAPI).MpoolPushMessage
> /home/zgf/gopath/src/github.com/zgfzgf/lotus/node/impl/full/mpool.go:157
> 
>     * estimating gas used:
>       github.com/filecoin-project/lotus/node/impl/full.(*GasModule).GasEstimateMessageGas
>       /home/zgf/gopath/src/github.com/zgfzgf/lotus/node/impl/full/gas.go:273
> 
>     * CallWithGas failed:
>       github.com/filecoin-project/lotus/node/impl/full.gasEstimateGasLimit
>       /home/zgf/gopath/src/github.com/zgfzgf/lotus/node/impl/full/gas.go:236
> 
>     * call raw get actor:
>       github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).CallWithGas
>       /home/zgf/gopath/src/github.com/zgfzgf/lotus/chain/stmgr/call.go:195
> 
>     * resolution lookup failed (t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq):
>       github.com/filecoin-project/lotus/chain/state.(*StateTree).GetActor
>       /home/zgf/gopath/src/github.com/zgfzgf/lotus/chain/state/statetree.go:285
> 
>     * resolve address t3uedxzwdvzqnksduqt77zzdpzt5fsa7no3wbo6hnzrvxzpiezvxtzo3y7kb335gsarqp3kxgwesmj7y5fmwuq:
>       github.com/filecoin-project/lotus/chain/state.(*StateTree).lookupIDinternal
>       /home/zgf/gopath/src/github.com/zgfzgf/lotus/chain/state/statetree.go:250

俺也一样

**Comment by rjan90** [comment]
Are you still having problems with lotus send, or can this issue be closed? It seems like this issue was related to the wrong GasFee settings. #rengjøring

**Comment by Reiers** [comment]
Issue outdated, and solved in newer versions of Lotus.

Closing this ticket. 

**If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.**
