### ISSUE TITLE
Add an API/CLI to return deal status

### ISSUE THREAD

**Issue by pooja** [filecoin-project/lotus#4551]
Is there some way to indicate to a user when the sectors containing their deal has been terminated? We're running into a lot of people wondering what's going on with their lost deals.

Ideally if we can allow people to see aggregate stats on their deals by stage, that would be helpful. For example, a command that allows a user to see how many deals and how much unpadded and padded data is at each deal stage, including terminated deals. Lmk if this needs more clarification

**Comment by jennijuju** [comment]
To return if the sector that a deal(s) in is currently active, non-active, expired or terminated.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
