### ISSUE TITLE
filecoin内存溢出

### ISSUE THREAD

**Issue by yzn5555** [filecoin-project/lotus#4552]
filecoin程序重启后，扫描历史块，达到138721高度，服务器内存溢出，服务器配置：8核 32G内存   我想问下怎么避免内存占用过高导致服务器内存溢出
![image](https://user-images.githubusercontent.com/36029121/96963092-9c547800-153a-11eb-97ca-a6ba038e4eb8.png)

**Comment by rjan90** [comment]
Since this is an issue related to the worker not having enough memory, and not an Lotus-issue, I think this issue can be closed. #rengjøring
