### ISSUE TITLE
CAN NOT SEARCH my Adjusted Power in filfox.info

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#4570]
Please help me.  I have three proving sectors but I can't search my adjusted power in filefox.info.
please let me know about this.
![lotus-miner_info](https://user-images.githubusercontent.com/70571701/97063573-7206c700-15db-11eb-9b54-6da7d4c9bfc8.png)

![filfox info](https://user-images.githubusercontent.com/70571701/97063576-78953e80-15db-11eb-9a1d-8ea3dc7232f6.png)

**Version**
Daemon:  1.1.0+git.c767399fc+api0.15.0
Local: lotus-miner version 1.1.0+git.c767399fc

**Comment by karalabe** [comment]
Sectors are activated on chain only after they pass their first windows post. You can check `lotus-miner proving deadlines` for when that happens.

**Comment by hsjw12** [comment]
lotus-miner proving deadlines

Miner: f047978
deadline  partitions  sectors (faults)  proven partitions
0         1           3 (0)             0
1         0           0 (0)             0
2         0           0 (0)             0
3         0           0 (0)             0
4         0           0 (0)             0
5         0           0 (0)             0
6         0           0 (0)             0
7         0           0 (0)             0
8         0           0 (0)             0
9         0           0 (0)             0
10        0           0 (0)             0
11        0           0 (0)             0
12        0           0 (0)             0
13        0           0 (0)             0
14        0           0 (0)             0
15        0           0 (0)             0
16        0           0 (0)             0
17        0           0 (0)             0
18        0           0 (0)             0
19        0           0 (0)             0  (current)
20        0           0 (0)             0
21        0           0 (0)             0
22        0           0 (0)             0
23        0           0 (0)             0
24        0           0 (0)             0
25        0           0 (0)             0
26        0           0 (0)             0
27        0           0 (0)             0
28        0           0 (0)             0
29        0           0 (0)             0
30        0           0 (0)             0
31        0           0 (0)             0
32        0           0 (0)             0
33        0           0 (0)             0
34        0           0 (0)             0
35        0           0 (0)             0
36        0           0 (0)             0
37        0           0 (0)             0
38        0           0 (0)             0
39        0           0 (0)             0
40        0           0 (0)             0
41        0           0 (0)             0
42        0           0 (0)             0
43        0           0 (0)             0
44        0           0 (0)             0
45        0           0 (0)             0
46        0           0 (0)             0
47        0           0 (0)             0

What else should I check?  please let me know that.

**Comment by hsjw12** [comment]
Is there any way to get my Adjusted Power to be retrieved from filfox.info?

**Comment by hsjw12** [comment]
>lotus-miner proving  deadline 0
Deadline Index:           0
Partitions:               1
Proven Partitions:        0
Current:                  false

Partition Index:          0
Sectors:                  3
Sector Numbers:           [0 2 3]
Faults:                   0
Faulty Sectors:           []

lotus-miner proving  faults 1

Miner: f047978
deadline  partition  sectors
lotus-miner proving  faults 0
Miner: f047978
deadline  partition  sectors
lotus-miner proving  faults 2
Miner: f047978
deadline  partition  sectors

**Comment by karalabe** [comment]
That `current` marker keeps going downwards (1 slot every 30 minutes), and when it reaches the end it will loop back to the beginning. When it hits a partition which contains sectors (`#0` for you), it will crunch a proof for those sectors and send it to the chain. After that, your miner will get updated to include these sectors.

**Comment by hsjw12** [comment]
Thanks for your answer. So if I just wait, is it automatically updated my Adjusted Power?

**Comment by hsjw12** [comment]
Please help me. My Adjusted Power is still not searchable in filfox.info. My two newly created miners of Adjusted Power are also not searchable in filfoc.info. Is there anything I am not good at? Or is it just waiting? How can I fix this?

![1](https://user-images.githubusercontent.com/70571701/97095190-6082f500-1697-11eb-8fa6-15626b6211ed.png)

![2](https://user-images.githubusercontent.com/70571701/97095195-6678d600-1697-11eb-9585-3705b4dbb8df.png)

**Comment by rjan90** [comment]
Since this issue is not related to Lotus, but related to Filfox, this can be closed. #rengjøring
