### ISSUE TITLE
DELETED  .lotus directory by accident!!!

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#4571]
Please help me.
I accidentally deleted the ".lotus" directory. I didn't even get a backup of my wallet and keystore, but I only know the wallet address. Is there any way to restore my FIL?

Daemon:  1.1.0+git.c767399fc+api0.15.0
Local: lotus-miner version 1.1.0+git.c767399fc

**Comment by karalabe** [comment]
Take your hard drive out of the machine (don't write on it!) and try to recover deleted files with another machine and some recovery program. The keys are fairly small, so if you deleted the entire gigantic chain and immediately stopped the machine, there's some small chance that it never got to overwrite the key data on disk. It is however paramount to stop using the disk immediately.

If you lose the keys, you lose your funds, there's no way to recover.

**Comment by magik6k** [comment]
To add to the above, with many data recovery programs, you can instruct them to look for specific things. In case of lotus keys:
* File paths starting with `~/.lotus/keystore/O5QWY3DFOQW...`
* File content like `{"Type":"secp256k1","PrivateKey":"[...]"}` or `{"Type":"bls","PrivateKey":"[...]"}`

**Comment by hsjw12** [comment]
Thank you~~~
