### ISSUE TITLE
PC2 on GPU may crash, leaks out GPU RAM and worker

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#4578]
I've opened this issue originally against the rust-fil-proofs repo because the root cause seem to originate from there, but I'd venture to say there's also an interfacing bug at play between the prover and lotus too: https://github.com/filecoin-project/rust-fil-proofs/issues/1326

**Comment by rjan90** [comment]
Since the tree building has been re-written and issues like this haven't come up in a while. I think this issue can be closed now. #rengjøring
