### ISSUE TITLE
Old sending transfers status

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#4581]
Here's the log of `list-transfers` from a Lotus node:
- [All transfers](https://gist.github.com/jsign/c45d6a72a498c426f543f31acfbc3113)
- [Failed transfers](https://gist.github.com/jsign/a3a361271c37fcdb30ab965cda7cfbb4): This is a subset of above list; might only worth looking at this list.

Some questions:
1. Transfers with ID 372, 380...384 are _weeks_ old. Shouldn't these transfers be considered _failed_? 
2. What does `  Message: Response Rejected` mean?
3. 385 is in _Requested_ status and its also weeks old, is that correct?
4. What does `deal data transfer failed: channel removed due to inactivity` mean? (Is there any other interpretation of that error that: "Nothing is happening, let's fail"?)

Running v1.1.1.

**Comment by Reiers** [comment]
Hi @jsign 👋 

Thanks for the report. The issue is a bit outdated.
We have come a long way since the issue was created, with separate markets node(soon Boost) and the indexer etc.😄 

Keep open, or close ? thank you

**Comment by jsign** [comment]
> Hi @jsign wave
> 
> Thanks for the report. The issue is a bit outdated. We have come a long way since the issue was created, with separate markets node(soon Boost) and the indexer etc.smile
> 
> Keep open, or close ? thank you

Yep, this one is quite old. Sounds good to close it.
