### ISSUE TITLE
Restarting Lotus node resumed stalled transfers

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#4582]
I've been noticing that when the Lotus node gets restarted, since was updated or any other reason, pending/stalled transfers resume successfully and start making progress again.

I'd imagine there's already some retry logic, but maybe there's a bug or can be a bit more aggressive in trying stalled transfers.

Here's a picture of a node that was stalled in sending transfers. After it was restarted, it started to send a lot of data again to miners:
![image](https://user-images.githubusercontent.com/6136245/97084667-16decf80-15ef-11eb-934d-c11787e4639d.png)

That bump in upload speed was exactly when the node was restarted. Those upload speeds kept that speed for some minutes before kind of stalling again.

I know that data transfers are a hairy thing since also depends on miners, but just finding curious that a lotus restart looks to make immediate progress for some time for transfers which were stalled; just if may justify taking a look. If not, feel free to close this issue.

**Comment by Reiers** [comment]
Hello again @jsign 

Thanks for the report. The issue is also outdated.
 - Im not seeing that here now (v1.15.2-rc1)

If this is a issue in the [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1) - please open a new ticket.

Thank you !
