### ISSUE TITLE
invalid PoSt

### ISSUE THREAD

**Issue by hfmhx** [filecoin-project/lotus#4590]
**Describe the bug**
The PoSt calculation process of some indexes seems to be normal, no error is reported, and the result is invalid PoSt when submitting the message

**To Reproduce**
1. Run 'lotus-miner run'
2. Some indexes sometimes invalid PoSt

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44537744/97104198-ec733c00-16ec-11eb-85d7-8db0adeca35d.png)

**Version (run `lotus version`):**
Daemon:  1.1.2+git.d4cdc6d.dirty+api0.17.0
Local: lotus version 1.1.2+git.d4cdc6d.dirty

**Additional context**
I intercepted PoSt related logs
[debug.log](https://github.com/filecoin-project/lotus/files/5434484/debug.log)

**Comment by rjan90** [comment]
Are still having issues with the windowPoSt? Or can this issue be closed now? #rengjøring

**Comment by Reiers** [comment]
**If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.**

Closing this ticket.
