### ISSUE TITLE
Network could not be recovered after disconnect for a while

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#460]
## Description: 
The `lotus` could not connect to peers any more once it disconnected from the network for a while and recovered. This happens when connected with `lotus-storage-miner`. 
It always shows one connection like this: 
```
 $ lotus net peers
{12D3KooWKpV3WXCFoWtY4zNc8MERJmBnLt5GPhribQzcTKTzH7qk: [/ip4/127.0.0.1/tcp/49994]}
```

## How to reproduce
1. run `lotus daemon` normally
2. run `lotus-storage-miner run` on the same machine
3. check `lotus net peers` to see there are many peers connected
4. disconnect your network for time long enough, until you see only one connection exists, which is showing the peer with address like `ipv4/127.0.0.1` or `ipv6/::1` ... 
5. recover the network to the Internet
6. Just wait ... 

## Possible cause: 
The connection between `lotus` and `lotus-storage-miner` are also through libp2p. Once the network to Internet disconnected, the two machines are still connected since they are on the same machine. After the network is recovered, the `lotus` thinks it should get information from the connected peer - lotus-storage-miner, which actually does not know any others than `lotus`. 

## Workaround: 
Just stop `lotus-storage-miner` and wait until there are other peers connected to `lotus`, then restart `lotus-storage-miner`. 

## Possible solution: 
1. Set a threshold for `lotus`, e.g 3, once the connected peers is lower than the threshold, it should actively connect to bootstrap nodes and ask more peers information for connection;  (preferred)
2. Use tcp links between the two programs, instead of libp2p.

**Comment by magik6k** [comment]
Related PR: https://github.com/filecoin-project/lotus/pull/397

**Comment by magik6k** [comment]
That's now fixed
