### ISSUE TITLE
Feature request: Suspend and resume scheduling new sealing tasks

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#4602]
Currently the miner keeps crunching through available tasks, and the moment resources free up due to some task completing, another takes its place. This makes it a bit hard to gracefully shut down the worker/miner without losing progress (there's always that one PC in 5h) and it also makes it a bit hard to diagnose leaks (e.g. I'm certain there's a GPU RAM leak, but it's hard to pinpoint because there's always a new task scheduled). Last but not least, I almost always end up with "bad file descriptors" if I pull te run from underneath a PC2 and need to go back all the way to PC1 to regenerate the layers.

Wondering if it would be possible to support suspending the scheduling of new tasks, without interrupting currently running ones (and of course resuming the whole thing).

**Comment by karalabe** [comment]
Alternatively, would be sweet if I could change the tasks allowed for a worker dynamically without needing to restart the worker. That way I could turn certain tasks off and then back on later.

**Comment by magik6k** [comment]
This will be very easy to implement after we land https://github.com/filecoin-project/lotus/pull/3618, where we can just mark the worker as 'disabled'

**Comment by rjan90** [comment]
Closing this issue since these features are implemented.

You can enable/disable tasks with: `lotus-woker set`
```
lotus-worker set -h
NAME:
   lotus-worker set - Manage worker settings

USAGE:
   lotus-worker set [command options] [arguments...]

OPTIONS:
   --enabled  enable/disable new task processing (default: true)
```

And you can change tasks that are allowed dynamically with: `lotus-worker tasks`
```
lotus-worker tasks
NAME:
   lotus-worker tasks - Manage task processing

USAGE:
   lotus-worker tasks command [command options] [arguments...]

COMMANDS:
   enable   Enable a task type
   disable  Disable a task type
   help, h  Shows a list of commands or help for one command

OPTIONS:
   --help, -h  show help (default: false)
```
