### ISSUE TITLE
TestBatchDealInput randomly hangs

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#4611]
https://app.circleci.com/pipelines/github/filecoin-project/lotus/11093/workflows/5716db76-1252-4142-b84a-aae3a0264388/jobs/83821

```
goroutine 48560 [chan receive, 29 minutes]:
github.com/filecoin-project/lotus/api/test.testRetrieval(0xc0011d2c60, 0x34b96c0, 0xc00019e010, 0x3501ac0, 0xc001d32600, 0xc004bcc480, 0x26, 0xc001631870, 0x3501a00, 0xc0059ec000, ...)
	/home/circleci/project/api/test/deals.go:410 +0x680
github.com/filecoin-project/lotus/api/test.MakeDeal(0xc0011d2c60, 0x34b96c0, 0xc00019e010, 0x7, 0x3501ac0, 0xc001d32600, 0x34fd740, 0xc003dcc1a0, 0x0, 0x0, ...)
	/home/circleci/project/api/test/deals.go:127 +0x441
github.com/filecoin-project/lotus/api/test.TestDoubleDealFlow(0xc0011d2c60, 0x31c6310, 0x989680)
	/home/circleci/project/api/test/deals.go:101 +0x488
github.com/filecoin-project/lotus/node_test.TestAPIDealFlow.func3(0xc0011d2c60)
	/home/circleci/project/node/node_test.go:48 +0x40
testing.tRunner(0xc0011d2c60, 0x31c6330)
	/usr/local/go/src/testing/testing.go:1039 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1090 +0x372
```

**Comment by magik6k** [comment]
Looking at logs, last retrieval log is
```
2020-10-27T11:22:13.855Z	�[34mINFO�[0m	markets	loggers/loggers.go:24	retrieval event	{"name": "ClientEventLaneAllocated", "deal ID": "1", "state": "DealStatusOngoing", "message": ""}
```

**Comment by dirkmc** [comment]
More examples:
https://app.circleci.com/pipelines/github/filecoin-project/lotus/11124/workflows/09f81bd1-2462-4395-b1a5-48256e66d2c2/jobs/84286
https://app.circleci.com/pipelines/github/filecoin-project/lotus/11124/workflows/09f81bd1-2462-4395-b1a5-48256e66d2c2/jobs/84296

**Comment by dirkmc** [comment]
https://app.circleci.com/pipelines/github/filecoin-project/lotus/11141/workflows/f7728cf3-1d40-431e-89b1-b8ffdea9e655/jobs/84572

The error message is:
```
Deal State %!s(uint64=15): deal is not a in a state where deals are accepted
2020-10-28T15:59:27.117Z	storagemarket_impl	clientstates/client_states.go:310	deal bafyreifolbep4kw26yyofeanyiyfvgymceyrkcu6h3dipidrxdgmiygll4 failed: failed to initiate data transfer: deal data transfer failed: response rejected
```

**Comment by nonsense** [comment]
Having run this locally many times today, it appears that the problem is with `TestAPIDealFlow/TestBatchDealInput` - once I disable this test, the rest pass fine multiple times locally. `TestAPIDealFlow/TestBatchDealInput` is also failing locally with a timeout "sometimes", so I am focusing on it.

**Comment by Stebalien** [comment]
I've renamed this issue to record the fact that the flakiness has been moved into TestBatchDealInput. But it's still flaky (90% pass rate).

**Comment by magik6k** [comment]
Re-enabled in https://github.com/filecoin-project/lotus/pull/8291
