### ISSUE TITLE
Bug: Wallet doesn't let you delete, import, then delete again

### ISSUE THREAD

**Issue by EntropyPool** [filecoin-project/lotus#4621]
**Describe the bug**
I export the private key firstly, then i delete the wallet address, then import the address again, and then, i want to delete the wallet address again. At last i fail to delete the wallet address.

**To Reproduce**
1. Run 'lotus wallet export f1xxxxxxx > f1xxxxxx.keyinfo'
2. Run 'lotus wallet delete f1xxxxxx', this time the address is deleted as expected
3. Run 'lotus wallet import f1xxxxxx.keyinfo'
4. Run 'lotus wallet delete f1xxxxxx'
5. Cannot delete the wallet address any more
root@241:/home/test# lotus wallet delete f1xxxxxx
ERROR: failed to mark key f1xxxxxx as trashed: checking key before put 'trash-f1xxxxxx': key already exists

**Expected behavior**
The wallet address should be deleted as expected.

**Screenshots**
N/A

**Version (run `lotus version`):**
lotus version 1.1.2+git.009f0962

**Additional context**
N/A.

**Comment by whyrusleeping** [comment]
Ah nice, thats a bug. We never truly delete keys, we always just rename them so you don't accidentally do a bad thing. Deleting it twice would fail for the same reason that overwriting a key would fail.

**Comment by EntropyPool** [comment]
Ah~ the use case is something like that: before i have a cold wallet, i use a separate address to store my money(looooooooot of money, hahahahaha). so i cannot leave the wallet in a online fullnode. when i need to transfer money, i import the key. after than, i delete it. i think we can have an offline method, just like the cold wallet of bitcoin. i generate the message with offline PC with my key, and broadcast it with an online node without my key.
