### ISSUE TITLE
Terms of Service for Storage Providers!

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/lotus#4631]
In the deal flow, when a client is going to propose a deal with the miner, a miner's "Terms of Service" should be available for them to review, which allow the miner to specify what (type of) content they will/will not store. This will enable miners who have limitations on content they want to store, e.g., national laws in their country of residence, to make a client aware of these prior to the deal being made. 

Specific requirements:

- Miners should be able to define a terms of service regarding what content they will/will not allow to be stored with them
- Miners need that terms of service to be discoverable, such that clients are able to reasonably* consent to having seen/acknowledged the miner’s terms of service
- Clients need to explicitly ack that they have reviewed and agreed to the miners terms of service prior to making a deal. 

Details for how this will be implemented are still WIP.

**Comment by dineshshenoy** [comment]
Initial design discussions [here](https://docs.google.com/document/d/15K2O_3YBtBnARoK8qp7DZ9k843jEicDqi0oF_eIXNjY/edit)

**Comment by dineshshenoy** [comment]
Targeting EOY for initial version of publishing miner ToS

Dependency on first 3 miner ToS for Dec. 10.

**Comment by dineshshenoy** [comment]
ToS: https://github.com/filecoin-project/notary-governance/issues/8
