### ISSUE TITLE
通过 lotus cli 最多可以查询到多少的区块数据呢？

### ISSUE THREAD

**Issue by ddzyan** [filecoin-project/lotus#4647]
我在 lotus 节点通过 `lotus chain getblock [cid]` 进行区块信息获取，但是在获取比较早的区块（例如33高度的区块）会报错 `blockstore: block not found` ，我想了解如何通过设置 lotus 来获取这些区块数据呢

**Comment by jennijuju** [comment]
If you are syncing from snapshots then you may lose some states. However, if you are syncing from scratch, then you should be able to retrieve all historical chain data.

Also two thing:
- This is not an issue, but a question and  `Discussions` is a better place for it.
- Please file the tickets in English if you want to get a response from the team.
