### ISSUE TITLE
cli: `lotus client list-deals` Active deals disappearing

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#4648]
I've noticed in two Lotus nodes that running: `lotus client list-deals | grep Active | wc -l` on two consecutive days, makes the value decrease.

Apparently, the missing _Active_ deals haven't moved to _Slashed_ or _Error_ statuses which seems weird... looks like they simply disappeared. I've never seen this situation before, but the only recent event in these nodes was a v1.1.0 -> v.1.1.2 upgrade. No snapshot reimported or similar.

**Comment by hannahhoward** [comment]
most likely an error occurred with the deal. By default, failed deals are not displayed. You can `lotus client list-deals --show-failed` to see what happened.

**Comment by jsign** [comment]
@hannahhoward, can a deal pass from _Active_ to _Error_? In which case that can happen?

**Comment by jsign** [comment]
Found [this](https://raw.githubusercontent.com/filecoin-project/go-fil-markets/master/docs/storageclient.mmd.svg) state machine.

From what I can understand, if from two consecutive days I see _Active_ deals decreasing, and not moving to _Slashed_ and obviously not being expired since min deal duration is 6 month, the only option is that a `ClientEventDealCompletion` happened, which means: `... when a client cannot verify a deal expired or was slashed`.

These "disappearing" deals were _Active_ for days... does this event explain that?  _StorageDealError_ is a final state, so I guess there is no retry?

What's exactly about "client cannot verify"? Isn't reading on-chain data deterministic about a deal status?

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
