### ISSUE TITLE
cannot trigger  sectors pledge 

### ISSUE THREAD

**Issue by coinmini** [filecoin-project/lotus#4655]
Please provide all the information requested here to help us troubleshoot "commit failed" issues.
If the information requested is missing, we will probably have to just ask you to provide it anyway,
before we can help debug.

**Describe the problem**

cannot trigger  sectors pledge after update master branch  (commit : c3d00b0ac)

**Lotus miner logs**

here is what the log after ```
lotus-miner sectors pledge  : {"level":"warn","ts":"2020-10-29T22:52:23.296+0800","logger":"advmgr","caller":"sector-storage/manager.go:319","msg":"stub NewSector"}
{"level":"info","ts":"2020-10-29T22:52:23.296+0800","logger":"sectors","caller":"storage-sealing/garbage.go:16","msg":"Pledge {55658 192}, contains []"}
{"level":"debug","ts":"2020-10-29T22:52:23.296+0800","logger":"advmgr","caller":"sector-storage/sched.go:356","msg":"SCHED 29 queued; 2 open windows"}
{"level":"debug","ts":"2020-10-29T22:52:23.296+0800","logger":"advmgr","caller":"sector-storage/sched.go:450","msg":"SCHED windows: [{allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:false cpuUse:0 cond:<nil>} todo:[]}]"}
{"level":"debug","ts":"2020-10-29T22:52:23.296+0800","logger":"advmgr","caller":"sector-storage/sched.go:451","msg":"SCHED Acceptable win: [[] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] []]"}
```




**Lotus miner diagnostic info**

Please collect the following diagnostic information, and share a link here

* lotus-miner diagnostic info `lotus-miner info all > allinfo`

** Code modifications **

 no modifications

**Version**

 1.1.2+git.c3d00b0ac

**Comment by Reiers** [comment]
If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
