### ISSUE TITLE
sectors remove doesn't work with PreCommit1  & RecoverDealIDs sectors

### ISSUE THREAD

**Issue by ghost** [filecoin-project/lotus#4665]
**Describe the bug**
I am trying to remove sectors like this:  `lotus-miner sectors remove --really-do-it 16` but the command does not work.  The status of sector 16 in `lotus-miner sectors list` is unchanged.  Here is the error I get in the log file:

```
2020-10-30T13:26:32.979Z        ^[[31mERROR^[[0m        evtsm   go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:83        Executing event planner failed: running planner for state Removed failed:
    github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).plan
        /home/mwg/lotus2/extern/storage-sealing/fsm.go:212
  - didn't expect any events in state Removed, got [{User:{}}]:
    github.com/filecoin-project/lotus/extern/storage-sealing.final
        /home/mwg/lotus2/extern/storage-sealing/fsm.go:446
```

**To Reproduce**
Just type `lotus-miner sectors remove --really-do-it 16` on 1.1.2 where 16 is a pledged "CC" sector in `PreCommit1` or `RecoverDealIDs`.  For me, it happens 100% of the time.

Restarting the miner does not help.  If I manually delete the sector's files on disk (sealed/, unsealed/ and cache/), I can force it into an error state, but it's still not removed.

**Expected behavior**
I expect that sector to be removed from `lotus-miner sectors list` and for all on-disk artifacts associated with that sector to be deleted.

**Screenshots**

**Version (run `lotus version`):**
```
Daemon:  1.1.2+git.7d02cd667+api0.17.0
Local: lotus version 1.1.2+git.7d02cd667
```

**Additional context**
I build with this environment:

```
export RUSTFLAGS="-C target-cpu=native -g"
export FFI_BUILD_FROM_SOURCE=1
```

**Comment by jennijuju** [comment]
similar: #4086

**Comment by Reiers** [comment]
Hi "Ghost"

Thanks for the report. This is fixed in the [latest release.](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)
(and Im not able to repro the issue here.)

If you encounter this is issue again - please open a new ticket.

Thank you !
