### ISSUE TITLE
Gas calculation issue

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#4673]
**Describe the bug**
There are two simple transfer messages in the same block with same gas setting, one succeed while another failed with SyserrOutOfGas error. 

Please see these two messages:
[Message 1](https://filfox.info/zh/message/bafy2bzaceamhe3nkm7763ku3gkey47lzemwprhxmclerxoiqvyoivwylp6ap6) succeed with only 436,268 gas used;
[Message 2](https://filfox.info/zh/message/bafy2bzacebdzgtn2htiyzkaveuvjiri3nyzlj45dpkezfcscifvurhwxcddcw) failed and 1,090,670 (gasLimit) burnt.  

This does easily happen when transferring FIL in parallel. 

**Expected behavior**
There should be same (or only a little difference) gas required for same method, especially for transferring method, which has the same computing and storage resource requirement.

**Comment by Kubuxu** [comment]
The Message 2 was creating a new account actor. That is why it needed more gas to execute.
