### ISSUE TITLE
websocket routine exiting

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#4674]
My worker and miner is unusable, getting stuck in `websocket routine exiting` errors. This is latest master (after the fix landed).

**Comment by corviato1** [comment]
Same

**Comment by jennijuju** [comment]
@karalabe @corviato1 could you please provide lotus version or which commits are you on?

**Comment by hsjw12** [comment]
Same

**Comment by hsjw12** [comment]
Mys lotus version is 
Daemon:  1.1.2+git.a5c05f87f+api0.17.0
Local: lotus version 1.1.2+git.a5c05f87f

**Comment by powerboy11** [comment]
same

**Comment by cryptowhizzard** [comment]
Same
