### ISSUE TITLE
是否只有等deamon高度追上了之后，worker才能正常工作？

### ISSUE THREAD

**Issue by k178613133** [filecoin-project/lotus#4680]
1. 追上高度，初始化钱包之后，启动miner，启动一个worker，监听 3456端口，未添加启动参数，正常工作。
  miner配置：
  AllowAddPiece = false
  AllowPreCommit1 = false
  AllowPreCommit2 = false
  AllowCommit = false
  AllowUnseal = false

2. 之后又启动了一个worker，监听 3459端口，worker启动参数，--precommit2=true，其余设置为false,一直处于等待任务的状态。

3. 又启动了一个worker，监听3460端口，worker启动参数：--commit=true，其余设置为false，一直处于等待任务的状态。

 运行：lotus-miner sectors list

ID  State       OnChain  Active  Expiration  Deals
0   WaitSeed    NO       NO      n/a         CC
0   WaitSeed    NO       NO      n/a         CC
1   WaitSeed    NO       NO      n/a         CC
6   WaitSeed    NO       NO      n/a         CC
7   PreCommit1  NO       NO      n/a         CC
8   PreCommit1  NO       NO      n/a         CC
9   PreCommit2  NO       NO      n/a         CC

lotus-miner sealing jobs

ID  Sector  Worker  Hostname  Task  State    Time
0   9       1       smart681  GET   running  2h43m19.5s
3   8       1       smart681  PC1   running  2h31m13.8s
4   7       1       smart681  PC1   running  2h31m9.2s

**Comment by jennijuju** [comment]
yes. If the task involves onchain activity, then your node needs to be synced,
