### ISSUE TITLE
To be able to define what's a burn fee for given a miner id

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4694]
Funds burnt during cron come from three places.  Precommits expiring, new and ongoing faults, and sector terminations.  Metadata about these events can be gathered before and after an epoch along with data indicating fee values.

Concretely in miner state can look at total sectors faulty in the current deadline before and after a transition to see how many fault fees are being paid.  We can look at PrecommitedSectorsExpiry queue to measure precommit expiries.  And we can look at the deadline's partition ExpirationEpochs queue to measure terminations.
Measuring the fees is a bit harder but we can read state from the miner actor in question, the reward actor and the power actor to get exact measures of what the fees are

**Comment by arajasek** [comment]
Sounds like a nice util to add to lotus-shed. Per @ZenGround0:

```
Funds burnt during cron come from three places.  Precommits expiring, new and ongoing faults, and sector terminations.  Metadata about these events can be gathered before and after an epoch along with data indicating fee values.
```.

This can be sniffed out from state by:

```
Concretely in miner state can look at total sectors faulty in the current deadline before and after a transition to see how many fault fees are being paid.  We can look at PrecommitedSectorsExpiry queue to measure precommit expiries.  And we can look at the deadline's partition ExpirationEpochs queue to measure terminations.
Measuring the fees is a bit harder but we can read state from the miner actor in question, the reward actor and the power actor to get exact measures of what the fees are
```
