### ISSUE TITLE
Add a "compact" command

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#4701]
Inspired by #4547, our docs currently say:

```
## Compacting the chain data

It is possible to "prune" the current chain data used by Lotus to reduce the disk footprint of a Lotus node by resyncing from a minimal snapshot. This is a quick overview of the steps:

1. Stop the lotus daemon, i.e. `lotus daemon stop`)
2. Remove the contents of the `datastore/chain/` folder in the Lotus path, i.e. `rm -rf ~/.lotus/datastore/chain/*`.
3. Start the daemon using a minimal snapshot as explained above, i.e. `lotus daemon --import-snapshot https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car`.
```

We probably shouldn't be telling people to directly delete folders. Adding some `lotus compact` command that does this in one step is probably the best thing to do.

**Comment by jennijuju** [comment]
Another solution is actually have an option to trigger regular chain datastore pruning

**Comment by arajasek** [comment]
This _should_ largely get implemented by #4992

**Comment by jennijuju** [comment]
Add documentation for split blockstore, which implements this feature by nature.

**Comment by vyzo** [comment]
Note that as part of #5808 I am adding a `lotus-shed` command to gc the hotstore.
We can do this as an additional command in that vein, that garbage collects the coldstore.
We will have to finish #5808 first however, it still has a couple of small issues with hotstore misses.

**Comment by parkan** [comment]
running the daemon with ` --import-snapshot` a second time appears to blow away the chain data and restart the sync, would that be equivalent?

**Comment by arajasek** [comment]
Splitstore is the correct way to do this, we can close this.
