### ISSUE TITLE
It take too long time when write ldb (> 7m) 

### ISSUE THREAD

**Issue by irocn** [filecoin-project/lotus#4702]
Hello, 

I found miner take more than 7 minutes to put data into ldb from miner log and cause it mine a new block but can't get reward.
I have a miner with >200T power but more than two weeks can't get block reward. 

If is this an issue to impact the new block mined? Thanks!

<img width="906" alt="WechatIMG3085" src="https://user-images.githubusercontent.com/19788429/97958224-bff3aa00-1de7-11eb-9973-0d53475135d2.png">

**Comment by jennijuju** [comment]
Whats your lotus version and do you run any customized software?

**Comment by jennijuju** [comment]
Also, whats your hardware spec?

**Comment by irocn** [comment]
@jennijuju It used official version only added some printing information. and hardware spec is amd 3990x, 256G RAM.
lotus version is v1.1.2.

**Comment by whyrusleeping** [comment]
@irocn is your disk full?

**Comment by arajasek** [comment]
@irocn Have you seen this pattern a few times (taking a really long time to get to `SyncSubmitBlock`)?

**Comment by irocn** [comment]
@whyrusleeping I am sure that disk space is enough.

@arajasek yes, I miss many winning block rewards chance, so I trace cid to find this issue. now I don't know how to solve it. don't winning the new block still now.

**Comment by xgbxxb** [comment]
@whyrusleeping @arajasek @jennijuju If you need anything for further analysis, we can provide. Please help look at this issue. We have been experiencing this issue for almost 3 weeks. If there is any workaround please let us know.
Thank you.

**Comment by Kubuxu** [comment]
Can you check the size of `datastore/metadata` both in the miner repo and lotus daemon repo?

**Comment by xgbxxb** [comment]
@Kubuxu 

Miner:
adminroot@3990x-1:/opt/nvm/miner_repo/datastore/metadata$ ls *.ldb | wc -l
2543
adminroot@3990x-1:/opt/nvm/miner_repo/datastore/metadata$ du -sh
8.8G    .

Daemon:
roots@7402-12:/opt/data/race2/lotus/datastore/metadata$ ls *.ldb | wc -l
6
roots@7402-12:/opt/data/race2/lotus/datastore/metadata$ du -sh
17M     .

We found the large delay seem related to leveldb put operations in MinedBlock(), so we skipped it. Yesterday we successfull got 4 blocks. Not sure if it is safe to skip this.

**Comment by Kubuxu** [comment]
@magik6k any idea why miner's metadata store would be 8.8GB?

@xgbxxb it is a part of two line defence against publishing consensus slashable blocks, the second like of defense is on the side of lotus daemon.

**Comment by Reiers** [comment]
Hi @irocn and everyone. 

Thanks for the report. The issue is outdated, and have not seen any reports of it recently. 

Is this a issue in the in [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)?

Thank you !
