### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by satonz** [filecoin-project/lotus#4707]
![image](https://user-images.githubusercontent.com/38401802/97972761-fccb9b00-1dff-11eb-9b15-b155b5e424b5.png)

**Comment by satonz** [comment]
I use centos7

**Comment by satonz** [comment]
![image](https://user-images.githubusercontent.com/38401802/98003221-6e6c0f00-1e29-11eb-8491-1490c5f63af9.png)

**Comment by jennijuju** [comment]
which commit are you on?

**Comment by satonz** [comment]
what mean

**Comment by satonz** [comment]
master

**Comment by jennijuju** [comment]
provide your `lotus version`?

**Comment by satonz** [comment]
1.1.2

**Comment by ceruleannn** [comment]
same error in centos7

**Comment by ceruleannn** [comment]
> same error in centos7 , any solution?

ubuntu is fine
