### ISSUE TITLE
Lotus Node consumes all available memory and won't release it

### ISSUE THREAD

**Issue by peterVG** [filecoin-project/lotus#4714]
**Describe the bug**
Lotus has been causing fatal Out Of Memory crashes for many Powergate users. 

As an example: between 28 October and 31 October I uploaded 55 1GiB CIDs, 5 or 10 CIDs at a time. My Lotus Node runs as a Docker container as part of a Powergate deployment on AWS which has 8vCPU / 60GB RAM / 120GB Swap.

At Nov 2, 19:00 UTC, I had 192 final deals and 195 pending deals for these 55 CIDs. From October 28 onward, RAM and Swap usage spiked and never went down. RAM continued to max out at 59GB. Swap hovered at 60GB over 3 days and then actually went up to 80 GB on the fourth day. All without addding any new CIDs.

<img width="1233" alt="3-days-after-last-CID-upload" src="https://user-images.githubusercontent.com/672121/98039933-58802f00-1dd4-11eb-9888-f9dce93f7256.png">

To see if a restart would help, I rebooted all Powergate containers, including Lotus Node. At 6 hours and 19 hours after the Docker container restarts memory was at half the usage it was previously and no Swap was getting used. So that had helped.

<img width="1457" alt="6hours-after-container-restart" src="https://user-images.githubusercontent.com/672121/98040274-d93f2b00-1dd4-11eb-8576-4abb2c9a0852.png">
<img width="1008" alt="19-hours-after-container-restart" src="https://user-images.githubusercontent.com/672121/98040285-dcd2b200-1dd4-11eb-814a-c92f67f9f06d.png">

However, I then uploaded 10 new 1 GiB files and three hours later I'm seeing maxed out memory again:

<img width="1693" alt="3-hours-after-new-uploads" src="https://user-images.githubusercontent.com/672121/98040372-055aac00-1dd5-11eb-8536-38d2c927ea48.png">

From previous experience I know that uploading more files at this point will lead to a OOM crash of the Lotus node with a likelihood of permanent database corruption.

**To Reproduce**
1. Deploy a Lotus Node with minimum requirements: https://docs.filecoin.io/get-started/lotus/installation/
2. Upload 100 GIBs
3. Watch memory rise and run out.

**Expected behavior**
Lotus releases memory as it finishes tasks and waits for new jobs.

**Screenshots**
See `htop` graphs above.

**Version (run `lotus version`):**
lotus version 1.1.2*git.d4cdc6d (shipped with Powergate as a Docker container)

**Additional context**
I have only been able to upload 65 GiBs of data to Filecoin in just under a week. A serious scalability problem IMHO.

**Comment by jennijuju** [comment]
Have you tried https://github.com/filecoin-project/lotus/pull/4619

**Comment by peterVG** [comment]
@jennijuju no because it was only merged to master 11 hours ago and hasn't hit a release yet but this sounds very encouraging! thanks for the heads-up.

**Comment by jennijuju** [comment]
> @jennijuju no because it was only merged to master 11 hours ago and hasn't hit a release yet but this sounds very encouraging! thanks for the heads-up.

ah ofc, try it out and let us know how it  goes!

**Comment by jennijuju** [comment]
@peterVG some people has tested the pr and confirms that it was working, so I will close this ticket for now. It will be included in a coming release soon, if you still face issue then please reopen this ticket.

**Comment by peterVG** [comment]
Better late than never? Forgot to come back to this issue and report that yes, this issue, is resolved on my server as well. Congratulations! This is a major production blocker that is now resolved. Thanks.
