### ISSUE TITLE
Github - Please make sure you have the correct access rights and the repository exists

### ISSUE THREAD

**Issue by Vapiano** [filecoin-project/lotus#4715]
**Describe the bug**
Following the install guide https://docs.filecoin.io/get-started/lotus/installation/#build-and-install-lotus
step "make clean all" fails to GitHub access 

**To Reproduce**

1. Run 'make clean all'

2. pino@miner:~/test/lotus$ make clean all
rm -rf  build/.filecoin-install build/.update-modules  lotus lotus-miner lotus-worker lotus-shed lotus-gateway lotus-seed lotus-pond lotus-townhall lotus-fountain lotus-chainwatch lotus-bench lotus-stats lotus-pcr lotus-health lotus-wallet testground
make -C extern/filecoin-ffi/ clean
make[1]: Entering directory '/home/pino/test/lotus/extern/filecoin-ffi'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory '/home/pino/test/lotus/extern/filecoin-ffi'
make: [Makefile:289: clean] Error 2 (ignored)
git submodule update --init --recursive
Submodule 'extern/blst' (git@github.com:supranational/blst.git) registered for path 'extern/blst'
Submodule 'extern/filecoin-ffi' (https://github.com/filecoin-project/filecoin-ffi.git) registered for path 'extern/filecoin-ffi'
Submodule 'extern/oni' (https://github.com/filecoin-project/oni) registered for path 'extern/oni'
Submodule 'extern/serialization-vectors' (https://github.com/filecoin-project/serialization-vectors) registered for path 'extern/serialization-vectors'
Submodule 'extern/test-vectors' (https://github.com/filecoin-project/test-vectors.git) registered for path 'extern/test-vectors'
Cloning into '/home/pino/test/lotus/extern/blst'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])?

3. 
Press yes

4. 
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:supranational/blst.git' into submodule path '/home/pino/lotus/extern/blst' failed
Failed to clone 'extern/blst' a second time, aborting
make: *** [Makefile:48: build/.update-modules] Error 1

**Expected behavior**
To connect

**Version (run `lotus version`):**
~/test/lotus$ lotus version
ERROR: dial tcp 127.0.0.1:1234: connect: connection refused

but downloaded today 

Tuesday, 03 Nov 2020 10:36 PM
--
Standard Time Zone: GMT/UTC + 01:00 hour

**Comment by jennijuju** [comment]
This is fixed in #4713
