### ISSUE TITLE
ubantu seal verify in batch failed 

### ISSUE THREAD

**Issue by EmilyCaoHong** [filecoin-project/lotus#4720]
nohup lotus daemon --import-chain https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/complete_chain_with_finality_stateroots_latest.car & to start lotus node, but

early, I use lotus daemon --import-chain https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/complete_chain_with_finality_stateroots_latest.car to start, but it can not daemon thread

**Comment by EmilyCaoHong** [comment]
![11111](https://user-images.githubusercontent.com/43725403/98060008-896b6d00-1e83-11eb-8518-ea9aa31476db.png)

**Comment by jennijuju** [comment]
Whats your lotus version?

**Comment by jennijuju** [comment]
closing since havent heard back from author and the issue hasnt been reported by others.
