### ISSUE TITLE
Sectors ar allways in SectorFinalizor status, and How can I force clean the tasks.

### ISSUE THREAD

**Issue by verynohair** [filecoin-project/lotus#4722]
Some sectors have completed sealing then commit to Post. But they are blocked in the SectorFinalizor status.

Then all the seal progress are still running, but I could not stop them. Even I restart the miner, all the progress will restart again by sched to many valid window.

**Comment by verynohair** [comment]
![微信图片_20201104192201](https://user-images.githubusercontent.com/12292635/98105489-0bcf4d80-1ed3-11eb-9747-83496cb5cb57.png)
They have stay in FinalizeSector for a long time. It can't change the status to Proving. And the tasks are all pending on 'GET'.
![微信图片_20201104192437](https://user-images.githubusercontent.com/12292635/98105811-69fc3080-1ed3-11eb-8aa4-7fe32fda6cc9.png)

**Comment by jennijuju** [comment]
could you provide your `lotus-miner info all`?

**Comment by verynohair** [comment]
> could you provide your `lotus-miner info all`?

It's not a bug. I found it's caused by being set the ParallelFetchLimit = 0 in the config.toml.
