### ISSUE TITLE
snapshot lotus with version 1.1.2, i get 'remote connection lost', when i import the snapshot, it gives me 

### ISSUE THREAD

**Issue by EntropyPool** [filecoin-project/lotus#4725]
**Describe the bug**
i want to snapshot lotus repo then i can used to recover another fullnode, but at the end of command 'lotus chain export --tipset @$( lotus chain list --count 50 --format "<height>" | head -n1 ) --recent-stateroots 900 snapshot.car', i got 'remote connection lost'. then i import the generated snapshot anyway, i got '2020-11-04T12:29:07.313Z        INFO    badger  v2@v2.2007.2/levels.go:1010     [Compactor: 173] Compaction for level: 0 DONE
2020-11-04T12:29:07.313Z        INFO    badger  v2@v2.2007.2/db.go:553  Force compaction on level 0 done
ERROR: fillCache walkback: get block bafy2bzacec4bhm2p7lf5c5b6ta2ynk6fzofgosotulzv3bfgqp5q5gfoktd2c: blockstore: block not found'

**To Reproduce**
1. Run 'lotus chain export --tipset @$( lotus chain list --count 50 --format "<height>" | head -n1 ) --recent-stateroots 900 snapshot.car'
2. See 'ERROR: incomplete export (remote connection lost?)'

**Expected behavior**
I should have snapshot.car generated rightly without any error.

**Screenshots**
N/A.

**Version (run `lotus version`):**
root@192-168-3-11:/home/test# lotus version
Daemon:  1.1.2+6block+git.88d860fbf.dirty.1603544548+1+api0.17.0
Local: lotus version 1.1.2+git.d4cdc6d3

**Additional context**
N/A.

**Comment by ribasushi** [comment]
That would indicate the *source* node you are runnng this on *does not* have the full chain. You can only run the above command from a full node.

Alternatively you can pass `--skip-old-msgs` which will create another truncated snapshot.

**Comment by arajasek** [comment]
^Resolution above, feel free to reopen if more assistance is needed.
