### ISSUE TITLE
is there two chains?  

### ISSUE THREAD

**Issue by iMiamas** [filecoin-project/lotus#473]
my miner : t0731 
UTC+8:00

$ lotus chain list
22920: (Oct 25 07:55:46) [ bafy2bzaceand7lrhgoborihagxbhy4upmtq7ipc27rmbgguadv44rrmxa2vvu: t0731, ]
22931: (Oct 25 08:01:16) [ bafy2bzacedh3iob7r6kujfamem7xeicdpyy2bsrjtyfre622hauuvsl2bu3tu: t0309, ]
22932: (Oct 25 08:01:46) [ bafy2bzacebofcoq3sset2r6qmolyz4ib32y7etrvib77ok7m5xznhm6zhx6ic: t0731, ]
22937: (Oct 25 08:04:16) [ bafy2bzacecal6p2aia3mm5rporxfcm7rjo5es4ca4ktuamewgmte3yea5r34m: t0176, ]
22941: (Oct 25 08:06:16) [ bafy2bzacedhely4t2um3iayhkbgwey4rtazsr7jfdahd556q6tz5ykrydixk6: t0309, ]
22958: (Oct 25 08:14:46) [ bafy2bzacecag4c4mbsxashl4nntbf5rnwl355ux7ul4sov67ktc2zqdo4qhy2: t0731, ]
22962: (Oct 25 08:16:46) [ bafy2bzacedbkanansdx6iwqjkm7jhlxo6yqziiegxmhd24ceib6silechcikc: t0176, ]
22980: (Oct 25 08:25:46) [ bafy2bzacechvuvmnwy645crnfb5enw3puzoqznqj5cvxo4fyo6iexirt2zoeu: t0731, ]
22984: (Oct 25 08:27:46) [ bafy2bzacedtwebfmnjagkudjhe3kh3moxb2unorkmxzg4dhkpel7bwvufxuc2: t0731, ]
22989: (Oct 25 08:30:16) [ bafy2bzaceaqhnrg7r433fc5oslvhfrd4lxofqifbtqsgxf4nuid46zwlcx46i: t0176, ]
22991: (Oct 25 08:31:16) [ bafy2bzaced5xejj7fmro6epq42sy7smdb7kizcq7wjhkqmzuvaoxjg3cde3pw: t0309, ]
22996: (Oct 25 08:33:46) [ bafy2bzacedffyq5bq7veeq7mbut3svkj5k3obwjvmzs6rsh6rqpezsuxn6bhm: t0309, ]
23005: (Oct 25 08:38:16) [ bafy2bzaceccsim6yqr4wtqdjckfv4vawutl4gspymg5jdpxo246szpph63nk2: t0309, ]
23009: (Oct 25 08:40:16) [ bafy2bzacednn5yywymvlvzbe67efknr3hnraamjfnigldf7rgsliaf7g6qlwu: t0731,bafy2bzaceccrwvntzqjombyoyd2his5pnrxhagb2zis3lah3d5nvuy4ijht7y: t0309, ]
23015: (Oct 25 08:43:16) [ bafy2bzacedlv6xkxzez6rva6tuuazguwf3uwab6l5t7khqzwzuasjiqka2wri: t0731, ]
23016: (Oct 25 08:43:46) [ bafy2bzacecye3tayefvymfnftlvtulnbygkq3bzsiro5q7jqcnnag2objrxiw: t0309, ]
23038: (Oct 25 08:54:46) [ bafy2bzacec4rdotvh53p4nt7qzql4233qjkpww6jjp2zkxmo62djjafz6nd4e: t0176, ]
23042: (Oct 25 08:56:46) [ bafy2bzaced6grr73vyiaiwkxg643mqvd6bk26n6mzlqgrs7ej5kjukog2a5zc: t0731, ]
23053: (Oct 25 09:02:16) [ bafy2bzaceasu64wwypiccgnfrlgkbql4duqwjvfxchwby3zvmwoawkzkq3rdo: t0309, ]
23055: (Oct 25 09:03:16) [ bafy2bzacebcpzo4okdbxkkjyc7jmfyjhuwfqyl362awf3n5nwplotextmdw5s: t0731,bafy2bzacebcngdyyg6jemtrhqq7jixqe244pvkblsorm3yfk2pg7rpxbugj72: t0309, ]
23056: (Oct 25 09:03:46) [ bafy2bzacedbtkzwgmwzn6ixkwqhtki7wh4is4sdfkb6b3rf4ctgetirixuwyg: t0176, ]
23102: (Oct 25 09:26:46) [ bafy2bzacecfxruyi4qhea4nbe4w6vkwmplhqtc5qrj7v33nyagossnas4plgm: t0176, ]
23103: (Oct 25 09:27:16) [ bafy2bzacedee47ihyven5yo3v6wtgscawfwtwss7e4imc55owflw6x252bao6: t0731, ]
23106: (Oct 25 09:28:46) [ bafy2bzacedwomggrg5v3wzdidjxdff5tpvzhvasy3me2kzgkqvh7l4pgrfln4: t0731, ]
23120: (Oct 25 09:35:46) [ bafy2bzacebq3v7kon3z5jbvqfz6rshwww5zfi7pu2izvhhthrw4bsdh67x46m: t0731, ]
23123: (Oct 25 09:37:16) [ bafy2bzaceatellyp4yk5xevbkkulf62ynx5xmq2j2dleklspvshb3md7rhgae: t0731, ]
23133: (Oct 25 09:42:16) [ bafy2bzacecktnlo6qi67bujmg66twrlyyfxqakswf4jibelsbpzwnfwiehfei: t0731, ]
23138: (Oct 25 09:44:46) [ bafy2bzacebmyorz6oata4pdukcqwhordg4k4c3gp2ab2nzqz37vihr3q4rauc: t0731, ]
23143: (Oct 25 09:47:16) [ bafy2bzacectuxqjvwdwusnr7kvrmrgyyxoxqox3l3ykqelsu5kf3gxsgnwwlk: t0176, ]
23153: (Oct 25 09:52:16) [ bafy2bzacedrmdfvr7n2gqjgibdhox6od2t6ohqocpb73c33a4b2if2lxrkprq: t0731, ]

on the web   Oct 25  09:56
https://lotus-metrics.kittyhawk.wtf/

![image](https://user-images.githubusercontent.com/10190342/67537392-c566e080-f70d-11e9-9e87-c0b54e81c54d.png)

**Comment by iMiamasJohano** [comment]
Time maybe appears： when my power about 
![image](https://user-images.githubusercontent.com/10190342/67537526-5938ac80-f70e-11e9-8368-acc248edb043.png)



I have not modified go-lotus codes

**Comment by travisperson** [comment]
[Here is a `lotus chain list --count 1024`](https://gist.githubusercontent.com/travisperson/ef787c1d496ae6dc093ffa0a639bed16/raw/df0f14ede4c7bd5da5be4116123a054c87416c10/gistfile1.txt) from the node sourcing that chain info.

Blocks you mined:

```
21555: (Oct 24 12:33:16) [ bafy2bzacednqauelo5w73kk7a6jwmwivrk2dnfxef3jkjgks35h6nmmlr6ido: t0731, ]
21613: (Oct 24 13:02:16) [ bafy2bzacea6bkns7rbd26uhlpkgd6ak3wfvbj4c6dhqqtgnnybbitcglqkvqe: t0731, ]
21617: (Oct 24 13:04:16) [ bafy2bzacediecqebfvxg2gt2crbz76ubrwwcy4h7hf2bgt5oif4vbeyny5sjm: t0731, ]
21855: (Oct 24 15:03:16) [ bafy2bzacebs7i2k4e43x6va6zijvjdoxq7f3s4k3bolk4nwswui4vqfyoobgc: t0731, ]
```

Looks like you might be on another fork. With the list above you might be able to find where things forked.

**Comment by iMiamasJohano** [comment]
forked at  height 21889

Why are there two chains at the same time?

![image](https://user-images.githubusercontent.com/10190342/67539730-a66c4c80-f715-11e9-8920-7a383b916339.png)

**Comment by whyrusleeping** [comment]
You can get forked if you lose connectivity to other nodes while mining. I'll open an issue to discuss this particular issue, and close this one
