### ISSUE TITLE
lotus-worker storage space Error

### ISSUE THREAD

**Issue by alingb** [filecoin-project/lotus#4733]
**Describe the bug**
Worker storage space size identification error

**To Reproduce**
1. Run 'lotus-miner storage list'
2. See error

root@trusme-Horsea:~# lotus-miner storage list
b71f0296-55d2-45e0-a0c0-643bc75ddd59:
	[##                                                ] 841.3 GiB/14.44 TiB 5%
	Unsealed: 0; Sealed: 3; Caches: 3; Reserved: 0 B
	Weight: 10; Use: Store
	Local: /storage/PATH_FOR_LONG_TERM_STORAGE/
	URL: http://192.168.1.13:2345/remote

4c5479eb-0f00-4d34-a1f7-f84eec246434:
	[##########**                                      ] 2.745 TiB/10.83 TiB 25%
	Unsealed: 1; Sealed: 0; Caches: 0; Reserved: 483.2 GiB
	Weight: 10; Use: Seal
	URL: http://192.168.1.12:1125/remote (latency: 1.2ms)

f88cb020-b9d3-4911-a82e-5bf538a4f6ab:
	[##########**                                      ] 2.745 TiB/10.83 TiB 25%
	Unsealed: 1; Sealed: 0; Caches: 0; Reserved: 483.2 GiB
	Weight: 10; Use: Seal
	URL: http://192.168.1.12:1127/remote (latency: 1.3ms)
…………

Lotus worker process：
root       13992  200 26.2 90599644 69274372 pts/2 SLl 16:11 110:00 lotus-worker --worker-repo=/nvme/LOTUS_WORKER_PATH/ run --listen=0.0.0.0:1125 --addpiece=false --precommit1=true --unseal=true --precommit2=false --commit=false
root       13996  168 26.2 90895344 69277856 pts/2 SLl 16:11  92:30 lotus-worker --worker-repo=/nvme/LOTUS_WORKER_PATH1/ run --listen=0.0.0.0:1127 --addpiece=false --precommit1=true --unseal=true --precommit2=false --commit=false

root@trusme-Horsea:/nvme# df -Th
Filesystem     Type      Size  Used Avail Use% Mounted on
…………
/dev/nvme0n1   ext4      3.6T  1.1T  2.4T  32% /nvme
/dev/sdd       ext4      1.8T   77M  1.7T   1% /data1
/dev/sde       ext4      1.8T   77M  1.7T   1% /data2
/dev/sdf       ext4      1.8T   77M  1.7T   1% /data3
…………

**Expected behavior**
Get the right storage space

**Screenshots**
N/A

**Version (run `lotus version`):**
Daemon:  1.1.2+git.a5c05f87f.dirty+api0.17.0
Local: lotus version 1.1.2+git.a5c05f87f.dirty

**Additional context**
N/A

**Comment by magik6k** [comment]
We calculate the used space by looking at `total - available`, which includes reserved space. Some filesystems like ext4 reserve a few percent (by default 5%) for root. Lotus will also reserve storage space for tasks in progress.

**Comment by jennijuju** [comment]
Please reopen the ticket if the above comment doesnt answer your question.
