### ISSUE TITLE
StorageDealClientTransferRestart deal vs Cancelled sending transfer

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#4737]
The situation is easily explained by this output:
```
azureuser@spaceracetwo30:/data/pltest$ lotus client list-deals | grep -A1 prpy
...cqzlprpy  0        f021346   StorageDealClientTransferRestart  N                 N         ...uzhyayiy  31.75 GiB  0.008344672 FIL           521542    false
  Message: data transfer appears to be stalled. attempt restart
azureuser@spaceracetwo30:/data/pltest$ lotus client list-transfers --show-failed | grep prpy
61   Cancelled           ...SmojWCto  ...e3Y5UkV1  Y           3.399GiB     ...ukd5yyyztpi27kszmx6jaurgixcqzlprpy"}}
azureuser@spaceracetwo30:/data/pltest$
```

How should a client make sense of this situation?
In particular:
- What does `StorageDealClientTrasnferRestart` mean? Is the restart going to be automatically triggered, or is waiting for a client action to be restarted?
- I see other deals (not shown in output here) in `StorageDealClientTransferRestart` that doesn't have the _Message_ `Message: data transfer appears to be stalled. attempt restart`. How is that different from the above case that has the message? What should the client do?
- Considering that the deal is on `StorageDealClientTransferRestart` status, looks like its corresponding transfer is `Cancelled`; so it will be in `StorageDealCleintTransferRestart` forever?
- I tried doing `lotus client restart-transfer 61`, but after waiting (and retrying), if I execute again the commands  mentioned in the top of this post, I'll get the same results. So it seems the deal is stuck in this state?

Version (~master):
```
Daemon:  1.1.2+git.c966054bf.dirty+api0.17.0
Local: lotus version 1.1.2+git.c966054bf.dirty
```

cc @hannahhoward

**Comment by hannahhoward** [comment]
hey, there's actually a bug underneath this that is solved here and should be in Lotus shortly: https://github.com/filecoin-project/go-data-transfer/pull/112

**Comment by jsign** [comment]
@hannahhoward , so the TL;DR is that client shouldn't be responsible for deal transfers retries? That is, there will be automatic retries up to a point in which the deal will *always* reach some final status (Active or Error).

**Comment by hannahhoward** [comment]
the client manual restart should only be required for a networking problem -- i.e. the miner didn't shutdown but for some reason the two got disconnected on the network for a while. (there are some seperate things currently causing this some of which may be bugs vs changing network conditions)

**Comment by jsign** [comment]
@hannahhoward, I see but I'll reframe my question since is quite important and maybe I failed to explained correctly.
Let's assume a 0 bug situation, so I'm mostly interested in the designed solution.

Can a deal reach a status in which will be stuck unless the client triggers a manual/proactive action?

I want to be sure that watching a deal is always waiting for "Active" or "Error", *or* it need proactive actions from the client to "unstuck" other situations. If that's the case, which are those situations, and how they're are detected (say, only watching a particular status, or status + error message, etc).

**Comment by arajasek** [comment]
Closed by #4730

**Comment by jsign** [comment]
I'm still interested in my last question answer!. May be better to create a new issue just with the question?

**Comment by pooja** [comment]
@jsign Yep, I would maybe just suggest creating a new issue and making sure to tag @dineshshenoy as well for tracking!

**Comment by jsign** [comment]
> @jsign Yep, I would maybe just suggest creating a new issue and making sure to tag @dineshshenoy as well for tracking!

Cool, done. #4852.
