### ISSUE TITLE
message sync issue when kill lotus daemon

### ISSUE THREAD

**Issue by maobisheng** [filecoin-project/lotus#474]
One of my node was in the process of block synchronizing, and I just kill the lotus daemon and run it again, I found the block height of message sync from the very beginning, I think it should continue to sync from the block height before I kill the daemon process.

**Comment by whyrusleeping** [comment]
No, the sync process is working as intended. Until the sync completes to the chosen target, we can't know that we are syncing to the correct chain, and therefore should not accept any intermediates.

What we can do to make this better would be to have a persistent cache of the validation of tipsets, that way on node restart we can skip revalidating things we've already computed.

**Comment by fanyanjun** [comment]
What we can do to make this better would be to have a persistent cache of the validation of tipsets, that way on node restart we can skip revalidating things we've already computed. 
-------》 I also have this problem. How can I do it?
