### ISSUE TITLE
Sync block problem

### ISSUE THREAD

**Issue by 90hacker** [filecoin-project/lotus#4741]
I keep getting this error when synchronizing blocks,
Has not been synced successfully。

![image](https://user-images.githubusercontent.com/15024497/98312393-96679800-200c-11eb-84dd-b73a913db7e7.png)

CPU info

![image](https://user-images.githubusercontent.com/15024497/98312512-e181ab00-200c-11eb-808d-055fa237e938.png)

**Comment by jennijuju** [comment]
Did you use a snapshot,. if so, when? whats your lotus version?

**Comment by 90hacker** [comment]
yes, Snapshot import。 
--import https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/complete_chain_with_finality_stateroots_latest.car

version ：lotus_v1.1.2

**Comment by EmilyCaoHong** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/43725403/98338343-0560e300-2045-11eb-9bbf-636bd0943907.png)
When synchronizing data, updates are often stopped automatically without error

**Comment by EmilyCaoHong** [comment]
and Start again and synchronize data from 0

**Comment by jennijuju** [comment]
> I have the same problem
> ![image](https://user-images.githubusercontent.com/43725403/98338343-0560e300-2045-11eb-9bbf-636bd0943907.png)
> When synchronizing data, updates are often stopped automatically without error
> and Start again and synchronize data from 0

duplicate #4723

**Comment by jennijuju** [comment]
duplicated #4723

**Comment by EmilyCaoHong** [comment]
I had my api key，I start my node，it is down every night without nothing tips

**Comment by 90hacker** [comment]
> 我有我的api密钥，我启动了节点，它每晚都关闭，没有任何提示

I also have this phenomenon。
I have to restart once a day。

**Comment by EmilyCaoHong** [comment]
I had my api key，I start my node，it is down every night without nothing

**Comment by jennijuju** [comment]
does the issue still exist with v1.1.3？

**Comment by cryptnotiq** [comment]
same issue as well. Has it been solved anywhere? I don't understand why all the related issues are being closed without any answers.

**Comment by 90hacker** [comment]
Sorry。I forgot to explain why。
After this problem occurred.
I deleted all my local files and recompiled lotus.
Use again
lotus - import filename

**Comment by zhangsj** [comment]
how fix it

**Comment by jitash** [comment]
+1

**Comment by filecoinprince** [comment]
I have got the same result, how can I get it fix?  Please advise.  And also, if I am using internal network, how can I set the remote listen address?

**Comment by ArseniiPetrovich** [comment]
@filecoinprince @zhangsj @jitash 
The tricky thing here is that sometimes the snapshot created might be broken. That is why it is very important to have alternatives. Here in Glif nodes (https://api.node.glif.io) we provide a publicly-available snapshots of the Calibration network and the mainnet. Here is the link with the documentation on how to fetch the snapshot for the Mainnet: https://gist.github.com/openworklabbot/d03393d1f6e70e089e9e8d18922474f6

Hope this helps ;)
