### ISSUE TITLE
frequently truncating sector log

### ISSUE THREAD

**Issue by zzx234234** [filecoin-project/lotus#4746]
fsm.go:193:
		if len(state.Log) > 8000 {
			log.Warnw("truncating sector log", "sector", state.SectorNumber)
			state.Log[2000] = Log{
				Timestamp: uint64(time.Now().Unix()),
				Message:   "truncating log (above 8000 entries)",
				Kind:      fmt.Sprintf("truncate"),
			}

			state.Log = append(state.Log[:2000], state.Log[:6000]...)     //<---------is this sth wrong???
		}

**Comment by magik6k** [comment]
We're truncating the middle part of the log, as the events at the beginning/end are usually the ones worth looking at when fixing issues
