### ISSUE TITLE
lotus chain decode params  should be add base64 format 

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4747]
lotus chain decode params 
Cannot parse at this time
hQCBggBAgYIIWMCnqyXVWilX65H9ENUaH7MxMufF6qZrV0QlVdzFzmnsAXfQiQ5Q7Ej8gpPf4G1qZomLLbVm93OWTOiPalepUyt0xYU3dasIExC4eg1ozHeFeFxFaxr8/+8ZKF2vx/SMBigLjTY9Ff4quc+KHiYaweo6hq9k0K0PeXyENwVR5ydZtvJRgJfERUa29MS3ATXaCuuogn7tXQrylVasssD02jjZWezYxkJZ+MiDzHYC01CR0abzzMKg92fyCsVdkBVHv1YaAAMrclggYr6QjOhoalkhIk7nNkA6BrQhXAV8eAUtdb+S+g6k6zE=

**Comment by jennijuju** [comment]
duplicate #4748
