### ISSUE TITLE
Improve storage deal success rate

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#4749]
The current storage deal success rate is not good, which isn't too surprising -- it's a workflow that requires various modules to stay on their happy paths (markets, data transfer, the mining process itself, etc.)

We need to exercise this workflow a bunch, discover issues in these various subsystems, and iron out the wrinkles.

Issues discovered:

- [ ] https://github.com/filecoin-project/lotus/issues/4731
- [x] https://github.com/libp2p/go-yamux/pull/35

**Comment by arajasek** [comment]
Related graphsync issues: https://github.com/filecoin-project/lotus/issues/4749

**Comment by dineshshenoy** [comment]
Related #4789  and #4790

**Comment by dineshshenoy** [comment]
Added #4805

**Comment by jennijuju** [comment]
tickets are captured in [Graphsync improvements](https://github.com/filecoin-project/lotus/milestone/8) and [Storage Deal Success](https://github.com/filecoin-project/lotus/milestone/7)
