### ISSUE TITLE
Graphsync Transfer Failures

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#4755]
I'm noticing a lot of graphsync transfer failures for a number of different reasons (known and unknown).

- [ ] The first issue is that yamux will periodically time out and close the whole connection, this is actually a bug and should be resolved in https://github.com/libp2p/go-yamux/pull/35
- [ ] data transfers appear to fail rather often when restarted with 'message too large'
- [ ] data transfer doesnt appear to automatically restart anything (we probably should, some limited number of times)
- [ ] counting of data sent and received appears to be incorrect around restarts
- [ ] data transfers appear to fail due to inactivity somewhat often, for inexplicable reasons
- [ ] data transfers get removed due to some timeout, but it appears to be different between client and server. I think I had a transfer get removed by the miner side while the client was still transferring data

**Comment by jennijuju** [comment]
defined tasks are now created in https://github.com/filecoin-project/lotus/milestone/8
