### ISSUE TITLE
Bug contingency fund for miners.

### ISSUE THREAD

**Issue by TippyFlitsUK** [filecoin-project/lotus#4759]
I have lost a large amount of money this week primarily as a result of snapshot sync irregularities and deal completion failures.

We are very much still in the early stages of Filecoin mainnet and there will obviously be bugs and obstacles to navigate. As early miners we fully accept this but it is also crucial to remember that we are now dealing with real money and livelihoods at a time of great economic instability.

I for one am sincerely grateful to the developer team for their considerable efforts and excellent communication in these early days but the fact remains that bugs are an inevitability.

I would respectfully like to propose that a contingency fund be established that will allow miners to apply for reimbursement in the unfortunate event of unavoidable financial loss.

**Comment by momack2** [comment]
Hey @TippyFlitsUK! I like this idea - the motivations are similar to the "Filecoin Recovery Proposals" intended to be part of the  [FIP Process](https://github.com/filecoin-project/FIPs), and our existing [bug bounty program](https://security.filecoin.io/bug-bounty/), which rewards miners for discovering and helping patch issues with the Filecoin network. 

However, such a program would be difficult to manage **fairly** and **objectively** with minimal resources. As we saw during Space Race, a whole host of factors can contribute to a miner being faulted (which are highly influenced by individual miner circumstances) and automatic processes to help compensate for these issues frequently end up being abused or perceived as unfair.

I'm curious how you'd propose structuring the application and review process of such a "miner insurance program" to avoid miner abuse, perceived unfairness, and unsustainable maintenance overhead? An objective, conservative framework for diagnosing miners that should or shouldn't qualify would help greatly!

**Comment by TippyFlitsUK** [comment]
Hi Molly. Thank you for taking the time to respond so quickly!!

One of Filecoin's greatest assets is it's strong and thriving community. I believe one potential solution would be to process proposals through community governance. This would address many issues in what is admittedly a very tricky topic to navigate:

1. Eliminate the majority of spurious proposals as miners would be submitting to a public forum of their peers.
2. Reviews would be undertaken by a community of peers with a vested interest in avoiding FIL allocation discrepancies.
3. Produces a minimal maintenance overhead footprint.
4. Minimises instances of proposal abuse or perceptions of unfair decisions through community consensus.
5. Subscribes to the decentralisation model.

My overriding concern is the potential for a bug to be inadvertently introduced that would result in revenue interruption for a great number of miners. In this event there is currently no contingency in place to address the financial implications.

**Comment by jennijuju** [comment]
> Hi Molly. Thank you for taking the time to respond so quickly!!
> 
> One of Filecoin's greatest assets is it's strong and thriving community. I believe one potential solution would be to process proposals through community governance. This would address many issues in what is admittedly a very tricky topic to navigate:
> 
> 1. Eliminate the majority of spurious proposals as miners would be submitting to a public forum of their peers.
> 2. Reviews would be undertaken by a community of peers with a vested interest in avoiding FIL allocation discrepancies.
> 3. Produces a minimal maintenance overhead footprint.
> 4. Minimises instances of proposal abuse or perceptions of unfair decisions through community consensus.
> 5. Subscribes to the decentralisation model.
> 
> My overriding concern is the potential for a bug to be inadvertently introduced that would result in revenue interruption for a great number of miners. In this event there is currently no contingency in place to address the financial implications.

Thanks @TippyFlitsUK , i will make sure this is  passed to the team and im going to close this ticket for now since it's not a lotus issue. Feel free to convert it to discussion if you want to keep it live!
