### ISSUE TITLE
cmd：lotus client import xxx

### ISSUE THREAD

**Issue by johnli-helloworld** [filecoin-project/lotus#476]
1. The relative path of a file cannot be used; it must be an absolute path
2.File must be in /root directory, ortherwise report error：cannot add filestore references outside ipfs root

**Comment by magik6k** [comment]
This error comes from https://github.com/ipfs/go-filestore/blob/87b7259b5615ca10a0cbf805bd70f24d4d099055/fsrefstore.go#L285.

I think the original point of it was to ensure only files within one filesytem are added, but the way it's implemented, it only checks if files are under the same directory `.lotus` repo is in - which is not the best way of doing that. It should probably be possible to disable it, or make it actually check the filesystem

**Comment by magik6k** [comment]
This is fixed now
