### ISSUE TITLE
geting the same blocks through different block height in 211159 and 211160，by json-rpc.

### ISSUE THREAD

**Issue by Reskorey** [filecoin-project/lotus#4768]
I get the same blocks through diffent blockheight  in 211159 and 211160? 
version v1.1.2 (mainnet)

![image](https://user-images.githubusercontent.com/43715382/98506977-9fb86500-2297-11eb-9637-502da66e19e7.png)

![image](https://user-images.githubusercontent.com/43715382/98506992-a9da6380-2297-11eb-831c-1664fe400a97.png)

without blocks, geting the blocks maybe return [ ] or null,I think.

**Comment by arajasek** [comment]
That's because 211160 was a "null" tipset, there were no blocks in it. In this case:

```
	// ChainGetTipSetByHeight looks back for a tipset at the specified epoch.
	// If there are no blocks at the specified epoch, a tipset at an earlier epoch
	// will be returned.
```
