### ISSUE TITLE
Lotus upgrade command

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#4772]
Related to: #4547 

In our docs, we advise users to use the 'rm' command when upgrading [Lotus](https://docs.filecoin.io/get-started/lotus/upgrades/#frontmatter-title).  It would be better if we provide a lotus command to make this safer.  If a user chooses the wrong directory or attempts this manually, they could lose client data or result in an unrecoverable state.

The "lotus upgrade" command should:
- Retrieve the latest stable release from github.com/filecoin-project/lotus (tag: "latest")
- Backup appropriate directories in case a revert is needed (i.e. "lotus_backup_20201108_1645")
- Move the latest release code into the right place
- Run a check that the system starts-up correctly.
- Remove the backup directory

If the process fails - enable a revert

**Comment by magik6k** [comment]
There will never be a reason to remove lotus data during an upgrade on mainnet, the correct fix is to remove this section from docs

**Comment by magik6k** [comment]
https://github.com/filecoin-project/filecoin-docs/pull/572
