### ISSUE TITLE
How to get enough fund from faucet?

### ISSUE THREAD

**Issue by jacktang** [filecoin-project/lotus#478]
Hello,

I just setup lotus and want to play it. And I get the fund from faucet twice (from the README doc)

```
lotus wallet balance t3rf3qhj5tqrkkexzalhwyf6lvdjbxvhva56vzy674ysyapfqfkrc37mibjkklcbwe5sdqjzj3xwgq7qlekqea
0.0000000015
```
And I want to init `lotus-storage-miner`, it throws error:
```
ERROR: failed to initialize lotus-storage-miner: mpool push: not enough funds: 1500000000 < 15698733068862645859
```
That means I have to spend a lot of time to get enough fund from faucet?

**Comment by jacktang** [comment]
I am going to `create miner` and it returns `too many requests`

**Comment by lau741288** [comment]
Can you solve this problem? I also encountered the same

**Comment by chenlvqing** [comment]
Can you solve this problem? I also encountered the same question，I only got 0.0000000005

**Comment by magik6k** [comment]
Updated the readme with more accurate instructions
