### ISSUE TITLE
Filecoin.ChainGetMessage       Field is lack of

### ISSUE THREAD

**Issue by satonz** [filecoin-project/lotus#4781]
I use the Filecoin.ChainGetMessage   method，  There is no field inside the return value to indicate the successful status of the transaction 。   How can I tell if a deal is a success

**Comment by satonz** [comment]
What's the difference between SecpkMessages and BlsMessages

**Comment by arajasek** [comment]
Thanks for the questions!

`StateGetReceipt` indicates whether a transaction (message) was successful.

Secp messages are signed by secp keys, BLS messages are signed by BLS keys.

You might find the [Filecoin Docs](https://docs.filecoin.io/) helpful.
