### ISSUE TITLE
Deal stuck in StorageDealClientTransferRestart state

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#4789]
**Describe the bug**
A deal from Textile has been stuck in StorageDealClientTransferRestart for 5 days, even though the Lotus version was recently upgraded.  This is happening with a PL'miner (run by Marcus) - f02665

DealDate: Nov  5 21:22:44  
DealCid: bafyreih7ayfw3kdhwxavriwbt5lnv3xdtvuhocd5y4zgu7jg3wlaxfd7oa
DealId: 0 
Provider: f02665
State: StorageDealClientTransferRestart
On Chain? N
Slashed? N
PieceCID: baga6ea4seaqdqskn6z4sfnnkxluokxfcvkhkhd6szowspnumsmc5j5zrwlkluaa
Size: 7.938 GiB
Price: 0.00208142 FIL
Duration: 520355
Verified: false 

**Version (run `lotus version`):**
lotus version 1.1.2+git.f225b7b92

**Additional context**
Deals are being tracked here: http://13.68.239.146:9090/deals.txt and updated every 10 minutes

**Comment by hannahhoward** [comment]
@dineshshenoy I believe this will be fixed with the new data transfer release, though it may not unstick previous deals. The new data transfer release will be merged here: #4730

**Comment by dineshshenoy** [comment]
Terrific - @jsign this sounds consistent to what you've experienced.  When you ran another deal, we presumably didn't encounter #4789 but got blocked on #4790

**Comment by dineshshenoy** [comment]
@jsign  - can you retry the same payload for the DeaalCid above to verify?

**Comment by jsign** [comment]
I'd think I need to wait for #4730 to get merged to master, right?

**Comment by jsign** [comment]
Looks merged, will give it a try.

**Comment by jennijuju** [comment]
@jsign could you please update the status of this tickets after you give it a try?

**Comment by jsign** [comment]
After updating, those deals still have in the same status. I'm not sure if the update should unblock existing deals, or may fix this in new ones.

Creating a new one lead to another situation #4805 .

**Comment by dineshshenoy** [comment]
Closing since I don't think it's happening anymore.  @hannahhoward said old deals may not restart but new deals now experience #4805

**Comment by kernelogic** [comment]
All my new deals are stuck at StorageDealCheckForAcceptance state. No progress for 2 days. Using the latest lotus 1.2.1.

**Comment by dirkmc** [comment]
@kernelogic When deals are in `StorageDealCheckForAcceptance` on the client side, it means the client is waiting for the provider to publish the deal. The client periodically sends a message to the provider asking for the deal status.
On the provider side it needs to:
- Verify that the data matches the expected CID
- Reserve funds for the deal
- Publish the deal
- Wait for the published deal to appear on chain

If there is chain congestion it could mean the provider takes longer than usual to be able to send out messages (eg for reserving funds / publishing).

Have you seen any progress on these deals you mentioned that are stuck in `StorageDealCheckForAcceptance`?
