### ISSUE TITLE
Fast Retrieval defaults to true in the CLI and false in the API

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#4791]
This is confusing behavior for the user.  Preference is to make the API default to fast-retrieval as well.

There's discussion [here](https://github.com/filecoin-project/lotus/pull/3026) about a potential an internal rename as well which may be why this got deferred.

**Comment by jennijuju** [comment]
change the one in CLI to fault

**Comment by dineshshenoy** [comment]
I think the intent is to promote fast-retrieval.  Is this technically hard?

**Comment by jennijuju** [comment]
fixed in #4998
duplicated #3017
