### ISSUE TITLE
ERROR: replay call failed: searching for msg bafy2bzacebrowsx47sfgkqycmjtb2sdsqnfbynkx5k3cxj5sgzo4xdgp6c2fo: checking for message execution during lookback: amt load: failed to root: blockstore: block not found

### ISSUE THREAD

**Issue by cyjdlxd** [filecoin-project/lotus#4801]
**Describe the bug**
i installed lotus soft on ubuntu system, then i import the full car file. i used "lotus chain list" "lotus chain getblock" and they ware all ok, but when i used "lotus state replay" the error occurred, i don't know why and how to solve the problem.

**To Reproduce**
1. Run 'lotus state replay --detailed-gas --show-trace bafy2bzacebrowsx47sfgkqycmjtb2sdsqnfbynkx5k3cxj5sgzo4xdgp6c2fo'
2. ERROR: replay call failed: searching for msg bafy2bzacebrowsx47sfgkqycmjtb2sdsqnfbynkx5k3cxj5sgzo4xdgp6c2fo: checking for message execution during lookback: amt load: failed to root: blockstore: block not found

**Expected behavior**
i want to get the full details about the message.

**Screenshots**

**Version (run `lotus version`):**
1.1.2+git.3ec25cbec
**Additional context**

**Comment by phantom-rabbit** [comment]
我也遇到了同样的问题，相同的版本
 computing tipset state failed: making vm: failed to load hamt node: blockstore: block not found

**Comment by jennijuju** [comment]
whats the block cid you get?

**Comment by cyjdlxd** [comment]
The block cid which i used is `bafy2bzaceb3pqjpltvecebojkuv2gh3pisvtqgdmjtxr2yzateesiyfsknzy4`, and the message cid is `bafy2bzaceawx7wy6alon5ay2b3ezmfxdebufhvxnjuiqjlxmjihkes2w5wkfe`,the message is included in this block.

**Comment by cyjdlxd** [comment]
The snapshot which i used is `complete_chain_with_finality_stateroots_latest.car`

**Comment by cyjdlxd** [comment]
I found that these older messages can not be searched, but the newest messages can be found. I need to search for all the messages to find out the messages about our miner accounts.

**Comment by jennijuju** [comment]
it means that the snapshot you used did not have the historical states you are looking for. Note that our snapshots only contains current heaviest tipset back to 2000 epochs ago.

**Comment by weaming** [comment]
> I found that these older messages can not be searched, but the newest messages can be found. I need to search for all the messages to find out the messages about our miner accounts.

same error
```
2020-12-08T03:27:41.117-0500    ERROR   processor       processor/messages.go:324       amt load: failed to root: blockstore: block not found
2020-12-08T03:27:41.117-0500    ERROR   processor       processor/messages.go:324       amt load: failed to root: blockstore: block not found
2020-12-08T03:27:41.118-0500    ERROR   processor       processor/messages.go:324       amt load: failed to root: blockstore: block not found
2020-12-08T03:27:41.119-0500    ERROR   processor       processor/messages.go:324       amt load: failed to root: blockstore: block not found
2020/12/08 03:27:41 blockstore: block not found {"/":"bafy2bzacealawlw6wix5lcfd5pepj2yuvpgzg7btdzqybelhbkxfq4mrnsw36"}
2020/12/08 03:27:41 blockstore: block not found {"/":"bafy2bzacebb625yrn2afr4kr3r3tzlckjuwjj3h7npiova5cac2tpyxrwnwlg"}
2020/12/08 03:27:41 blockstore: block not found {"/":"bafy2bzaceaiufv5ntew7ji43oyk33cr7dvbyavs45d5ra3nqvd4uq2qg3zt7m"}
2020/12/08 03:27:41 blockstore: block not found {"/":"bafy2bzaceavprupooqxgp4db2flxnbkjzfl3pu7a3nltl3ne2b66273dterkq"}
2020/12/08 03:27:41 blockstore: block not found {"/":"bafy2bzacedymsl27d3uqvmudl2wwwzbzpips5tsdcb4mqbouze4hnxfaxzius"}
```

I setup lotus from full snapshot via `https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/complete_chain_with_finality_stateroots_latest.car`
