### ISSUE TITLE
Deal making stuck at StorageDealTransferring

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#4805]
Describe the bug
A deal from Textile has been stuck in StorageDealTransferring for 1 day, even though the Lotus version was recently upgraded. This is happening with a PL'miner (run by Marcus) - f02665

It appears that we're no longer encountering #4789 but haven't gotten to success.

DealDate: Nov 10 21:49:11 
DealCid: bafyreihmb6q7624jz6axs3tb53rhfdflj6sc7wows6rusy7codtywjjvpi
DealId: 0
Provider: f02665
State: StorageDealTransferring
On Chain? N
Slashed? N
PieceCID: baga6ea4seaqfsgmrp2iyo4tpfy5o62rfcpgixy74z5a6jqru34sdeqr4ovoxkei
Size: 7.938 GiB
Price: 002081212 FIL
Duration: 520303
Verified: false

Version (run lotus version):
This commit: [ab7ee2f8](https://github.com/filecoin-project/lotus/commit/ab7ee2f8a97a9b20ed309f1727367d9d8bbec2c3)

Additional context
Deals are being tracked here: http://13.68.239.146:9090/deals.txt and updated every 10 minutes

**Comment by jehunter5811** [comment]
We are also experience this. We had a deal transfer interrupted. Auto-restart did not happen until our most-recent lotus upgrade. And now that deal is stuck in the StorageDealTransferring state. 

Details: 

Version: `lotus version 1.1.2+git.d4cdc6d33`
Deal Info: 
```
{
  "DealInfo: ": {
    "ProposalCid": {
      "/": "bafyreifjb3n5tcfutm3wzb22eod4vndbckpwhcbajgh4qphdwef7sbs5m4"
    },
    "State": 28,
    "Message": "",
    "Provider": "f015927",
    "DataRef": null,
    "PieceCID": {
      "/": "baga6ea4seaqkdmlh67eqp67cbv3z3wdt6wekfxbzwmdagsilvjf4ummmqcufycq"
    },
    "Size": 8522825728,
    "PricePerEpoch": "20000000000",
    "Duration": 521472,
    "DealID": 0,
    "CreationTime": "2020-10-22T22:21:19.66659894Z",
    "Verified": false
  }
}
```

**Comment by dirkmc** [comment]
Fixed by https://github.com/filecoin-project/lotus/pull/5032
