### ISSUE TITLE
lotus chain目录越来越大，导致硬盘存储空间不足，请问如果缩减，或删除无用的历史记录

### ISSUE THREAD

**Issue by qq71151461** [filecoin-project/lotus#4815]
如果删除，重新获取快照，进行同步，又太慢了

**Comment by lcgogo** [comment]
你现在有多大了，我有2个节点，一个节点快700GB，一个500GB，不清楚差的200GB有没有意义

**Comment by jennijuju** [comment]
This is not an issue per-se, can be a good discussion topic tho. 

Currently, you can remove the chain datastore folder and re-import from a latest snapshot and you should be able to be fully synced around 30 min.

This [pr](https://github.com/filecoin-project/lotus/pull/4629) is also a good option to try.
