### ISSUE TITLE
lotus daemon --import-snapshot  ERROR 

### ISSUE THREAD

**Issue by andy-github-info** [filecoin-project/lotus#4818]
lotus daemon --import-snapshot /data2/minimal_finality_stateroots_latest.car error

lotus version: lotus version 1.1.2+git.d525acded

`
 lotus daemon --import-snapshot /data2/minimal_finality_stateroots_latest.car
`

`
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/data/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *store.ChainStore: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.ChainBlockstore: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.ChainRawBlockstore: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to open badger blockstore: Cannot acquire directory lock on "/data2/lotus-data/datastore/chain".  Another process is using this Badger database.: resource temporarily unavailable
`

**Comment by jennijuju** [comment]
Feels like the error says it all already,  ```Another process is using this Badger database.: resource temporarily unavailable``` check your processes and datastore location

**Comment by andy-github-info** [comment]
Only the lotus process is using this resource

`
root@iZj6c1u64hvs1m1qurld89Z:~# lsof  /data2/lotus-data/datastore/chain
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
lotus   23298 root    9rW  DIR 252,49     4096 8912902 /data2/lotus-data/datastore/chain
`

**Comment by arayalways** [comment]
> Feels like the error says it all already, `Another process is using this Badger database.: resource temporarily unavailable` check your processes and datastore location

It not solved.Why closed?
