### ISSUE TITLE
github.com/filecoin-project/specs-actors/v2@v2.1.0/actors/builtin/sector.go:88:14: p.RegisteredSealProof undefined (type abi.RegisteredPoStProof has no field or method RegisteredSealProof)

### ISSUE THREAD

**Issue by oldkingclub** [filecoin-project/lotus#4820]
github.com/filecoin-project/specs-actors/v2@v2.1.0/actors/builtin/sector.go:88:14: p.RegisteredSealProof undefined (type abi.RegisteredPoStProof has no field or method RegisteredSealProof)

**Comment by jennijuju** [comment]
Whats your lotus version and when  do you see it?

**Comment by anorth** [comment]
`RegisteredPoStProof.RegisteredSealProof` was removed in https://github.com/filecoin-project/go-state-types/pull/19. It sounds like you've somehow ended up with that latest commit on go-state-types without upgrading actors. You want to roll back your dependency on go-state-types to the prior commit.

Note: actors `v2.1.0` is old, not compatible with mainnet at the moment.
