### ISSUE TITLE
The test code was not deleted

### ISSUE THREAD

**Issue by cyjdlxd** [filecoin-project/lotus#4821]
**Describe the bug**
The test code was not deleted in file cli/chain.go:138, so that when i run a command about chain, it gived some warning messages.

**To Reproduce**
1. Run 'lotus chain list'
2. See  "WARN    cli     cli/chain.go:138        amt load: failed to root: blockstore: block not found"

**Expected behavior**
no warning message to show

**Screenshots**

**Version (run `lotus version`):**
1.1.2+git.3ec25cbec
**Additional context**

**Comment by jennijuju** [comment]
this looks like a valid warning to me, according to the line that threw the warning, i assume you are calling `lotus chain getblock`? then seems like your chain datastore doesnt have the state of the block you are asking for thus the warning.

**Comment by cyjdlxd** [comment]
yes,it is a valid warning, but i think it's more appropriate for it to appear in the log file. I got the warning when i was calling `lotus chain list` the command `lotus chain getblock` is ok.

**Comment by cyjdlxd** [comment]
The command `lotus chain list` is working, it me the right information and a few more warnings，i just don't need the warning in here. Reading the source code, i think it is like someone's testing code. `
![image](https://user-images.githubusercontent.com/6711464/99019779-10ad9480-2598-11eb-9efd-d7ec2cfa7959.png)
`

**Comment by cyjdlxd** [comment]
sorry,i made a mistake, i truly used `lotus chain getblock`, and i got the blockinfomation and a warning, so i just want the blockinfo without the warning.

**Comment by jennijuju** [comment]
This is a valid warning and there won't be warning if the state exists in the datastore.
