### ISSUE TITLE
MaxSealingSectrosForDeals is set to 0 upon miner restart

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4833]
The title says it all😅

**Comment by arajasek** [comment]
What problem does this fix (what's the current impact)? And why do we want it in 1.2.0?

**Comment by jennijuju** [comment]
> What problem does this fix (what's the current impact)? And why do we want it in 1.2.0?

This affects miners' config so we'd like to get it fixed sooner than later

**Comment by arajasek** [comment]
I'd rather keep this milestone to mandatory issues only (if it doesn't get into 1.2.0, it has to wait until the next network upgrade).

**Comment by PatrickDeuse** [comment]
@arajasek the impact is:

- people have no idea what config is running in their miner
- the miner does not apply the config value anymore --> no sectors can enter WaitDeal state

is is not a restart issue. it gets set to 0 when setting the deal delay. as said in #4867 it affects might other values too - i am quite sure about the [Fees] section

**Comment by jennijuju** [comment]
@PatrickDeuse please see #4879
