### ISSUE TITLE
Sector state mismatched 

### ISSUE THREAD

**Issue by yydfjt** [filecoin-project/lotus#4839]
**Describe the bug**
A sector is commited on chain， but when : 1. lotus daemon crash on that point, or 2. miner restart on that point or 3. worker is offline for a while; its local state may be  in wrong state: PreCommit1 again or stuck on Finalized. This sector will be challenged in WindowPost, but its local state never goes right again.  Then this sector will terminated.

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by jennijuju** [comment]
Missing lotus version, sector status —log and minor logs for investigation

**Comment by jennijuju** [comment]
please reopen the ticket when providing required info.
