### ISSUE TITLE
import snapshot failed

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/lotus#4846]
**Describe the bug**

lotus daemon report failed use snapshot

**To Reproduce**
random 

**Expected behavior**
lotus daemon should no error when using snapshot

**Additional context**
 the reason may be due to data changed . so could support add version tag(version ,epoch, etc)

**Comment by hunjixin** [comment]
@whyrusleeping

**Comment by ribasushi** [comment]
@hunjixin there already are version tags: if you run a `HEAD` request on the download you will see a stable url:

```
~$ curl -I https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car
HTTP/1.1 200 OK
x-amz-id-2: ByFtpxJ4FM6g+SZUdtLi9Uhdfbw2RpHimIWsck5495sgXJ5VKcOl6kvMdRsWvYv8bjfaAn3tl0c=
x-amz-request-id: 9EB7F09F52BE1B21
Date: Fri, 13 Nov 2020 14:09:17 GMT
Last-Modified: Fri, 13 Nov 2020 13:21:23 GMT
ETag: "02c805fb17ce37e13f4f1db9f9a34c7b-1578"
x-amz-website-redirect-location: https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_232181_2020-11-13_13-00-00.car
```
^^^ this header, the url is stable

The snapshot situation is temporary, as it will become harder and harder to import them going forward. We are working on a set of alternative solutions, more in the coming week(s).

**Comment by hunjixin** [comment]
tks
