### ISSUE TITLE
Log files are getting bigger

### ISSUE THREAD

**Issue by 90hacker** [filecoin-project/lotus#4847]
I found a lot of vlog files under the path `datastore/chain`, can I delete it?
These files take up a lot of space.
How can i optimize it

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/lotus/pull/4629

**Comment by jennijuju** [comment]
and no, very confusingly that file is not a typical log file with human text for debugging
it's part of how the db operates and has the raw data it receives (later formated and compacted in other files)
