### ISSUE TITLE
Client actions in intermediate deal status?

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#4852]
Moving here a side question from #4737

Can a deal reach a status in which will be stuck unless the client triggers a manual/proactive action?

The main intention of this question is figuring out if a client, after starting a deal, should only expect to wait the deal to reach a final status, or it might be responsible for proactive actions in some edge-case status (like, restarting transfers or similar).

cc @dineshshenoy

**Comment by arajasek** [comment]
Stale
