### ISSUE TITLE
Move `mpool clear`  to lotus-shed or hide it

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4854]
Many people uses `lotus mpool clear` wrongly/without knowing what they should do with it. Normally they will use it to clear the mpool when the mpool is stuck and then get message issues. 

We should limit hide this cmd so that people dont use it randomly.

**Comment by PatrickDeuse** [comment]
you should not hide a command that is available. you should clearly explain what it's doing and what the consequences are and let people decide if they want to use it or not.

**Comment by arajasek** [comment]
Moving this to lotus-shed is probably the right thing to do.

**Comment by arajasek** [comment]
Make hidden / mark as deprecated initially when it moves to lotus-shed, delete later?
