### ISSUE TITLE
sectors update-state Removed broken on v1.1.3

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#4863]
Every now and again I needed to drop an old sector (e.g. this time because there's a bug in GPU handling in v1.1.3 an all my PC2's got stuck for 3 days, then they just loop between PC1 and PC2). In lotus 1.1.2, I could do a `lotus-miner sectors update-state --really-do-it X Removed` and the miner would drop the sector. This stopped working in 1.1.3.

**Comment by PatrickDeuse** [comment]
it works for me 1.1.3

**Comment by magik6k** [comment]
`Removing` is the state in which we drop the sector data.

Also, `lotus-miner sectors remove --really-do-it 123` is the command you want to use to remove sectors (even though, at least for now it's just updating the state to Removing under the hood)

**Comment by karalabe** [comment]
Tried that too and that didn't work either. FYI

**Comment by shaodan** [comment]
@karalabe have you fixed it, my miner has some old sectors cannot be remove too. lotus-miner 1.2.1
