### ISSUE TITLE
[Bug] State error

### ISSUE THREAD

**Issue by qkrwnsgh1288** [filecoin-project/lotus#4864]
**Describe the bug**
I'm just using `lotus daemon` version 1.1.2.
It suddenly stops working.. It has occurred very frequently  since before.
It is similar to the time when the 1.1.3 version was released. 
But 1.1.3 version is just optional release.
Even this wasn't prepared for compiled assets.

**To Reproduce**
1. Run `lotus daemon`
2. See error
Worker: 2; Base:237324; Target: 238903 (diff: 1579)
State: error; Current Epoch: 237323; Todo: 1580
Another core was completely jammed.

**Version (run `lotus version`):**
1.1.2

**Comment by arajasek** [comment]
What's the actual error you're getting? The output of `lotus sync status` might be helpful.

**Comment by qkrwnsgh1288** [comment]
After upgrading the version to 1.1.3, I solved it by just erasing all data and syncing again.
Thanks.
