### ISSUE TITLE
Lotus wallet import ignores SIGINT

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#4866]
**Describe the bug**
when running `lotus wallet import` and the `Enter private key:` prompt is active the SIGINT signal is ignored

**To Reproduce**
1. Run `lotus wallet import` and press ctrl+c

**Expected behavior**
Interrupted command

**Version (run `lotus version`):**
v1.1.3

**Comment by PatrickDeuse** [comment]
i add `lotus daemon --import-snapshot` to the list of commands that cannot be aborted with ctrl+c
