### ISSUE TITLE
lotus-miner overrides config values in config.toml

### ISSUE THREAD

**Issue by PatrickDeuse** [filecoin-project/lotus#4867]
**Describe the bug**
when running `lotus-miner sectors set-seal-delay XYZ` values in the config file, i witnessed it with `MaxSealingSectorsForDeals` and i am pretty sure it does it with the [Fee] section too, get changed. 

it might even override values in the config.toml when it starts up - i am not sure right now. this is happening on a live miner, i will test it later on our test miner and give more input

**To Reproduce**
1. Run `vim config.toml` set `MaxSealingSectorsForDeals` 
2. startup lotus-miner
3. `lotus-miner sectors set-seal-delay XYZ`
4. `cat config.toml`

i have a running lotus miner right now that has sectors in waitdeal state, the config file said `MaxSealingSectorsForDeals = 10` before starting up and the config.toml now shows `MaxSealingSectorsForDeals = 0` . sadly i cannot ask the miner to print out the running config it has loaded, but i cannot trust the config.toml either

**Expected behavior**
i expected that non affected config values are being untouched. it is bad enough that `lotus-miner sectors set-seal-delay XYZ` overrides the config.toml value WaitDealsDelay  in the file - i can kind of understand that, but other values???

It kills any chance of automated restarts if i have to manually check the config file for changes lotus-miner made to it beforehand...

**Version (run `lotus version`):**
1.1.3

**Additional context**
Please let the lotus-miner load the config file at startup and then leave it alone! if the file does not represent a running config then there is no reason to make any changes to it. is the reason to write it that you want to save running config somewhere?

**Comment by PatrickDeuse** [comment]
it does it constantly. 

it always resets `MaxSealingSectorsForDeals = 0` when setting the seal delay. i have no clue what config the miner is running right now.  is it reading the config that is set when starting the miner? is it running the config that is in the file after running the seal delay command? i have no clue

**Comment by jennijuju** [comment]
duplicated #4833

**Comment by PatrickDeuse** [comment]
#4879 <-- does this fix the `set-seal-dealy` problem too. i just tested it again and it's straight to 0 again

**Comment by magik6k** [comment]
#4879 Should fix this issue, just make sure to restart your lotus-miner after upgrading

**Comment by PatrickDeuse** [comment]
i will close this after updating to 1.2.0 if it's resolved.

testing on calibration right now

**Comment by PatrickDeuse** [comment]
no idea if it works or not. haven't tested.
