### ISSUE TITLE
go-filecoin can read net node data by parameter （"--cmdapiaddr=<cmdapiaddr>"） lotus ? how to  do?

### ISSUE THREAD

**Issue by fsysamme** [filecoin-project/lotus#489]
go-filecoin can read net node data by parameter （"--cmdapiaddr=<cmdapiaddr>"）
lotus ? how to  do?

**Comment by magik6k** [comment]
Nope, we use jsonrpc, not go-ipfs-cmds, and don't support this feature. For looking at api calls I'd recommend using wireshark or similar software.
