### ISSUE TITLE
Increase granularity when a deal is in the sealing process

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#4892]
As a client, I only see "StorageDealSealing" in the deal state which can stay for hours at best (and sometimes days).  It would be helpful to know if it's:
1) Still in the queue on the miner's side and waiting for sealing capacity to be available.
2) Past the Pre-commit phase (which shows up on-chain?)
3) Other stages so client has realistic expectations

**Comment by dineshshenoy** [comment]
We are seeing sealing complete in 72 hours.   Nov. 16th deals appear to have completed successfully.

Nov 17 00:01:27  bafyreihuvwo3wc5z4sgfxgglikfoai26pb6qvlhnn55neim4toh5fwok6a  1317153  f02665   StorageDealSealing                N                 N  baga6ea4seaqabzpxqctstejmmppctarsnevcsyu2vnogtrmhxmaads352kv6iga  1.984 GiB  0.000522902 FIL   522902  false  
Nov 17 01:02:30  bafyreiell2ihpopkkbqq2ofs2dz44od2vb5gu6cx4dsxrh5tsi6gywsove  1317295  f02665   StorageDealSealing                N                 N  baga6ea4seaqjvpoowbdjwxlurb52a6izybzhhwodkdxmhenvj527qmyetqoz4bi  1.984 GiB  0.00052278 FIL    522780  false  
Nov 17 02:01:26  bafyreia7tbuqjcko24ke5alalrjutxvkhkv4bebttku32jrmjuhgaruyp4  1317438  f02665   StorageDealSealing                N                 N  baga6ea4seaqkaq6nlrmklb7t4dwox7wdnsjnhtuiw5tdhdyotaz5c5rtrvzraha  1.984 GiB  0.000522662 FIL   522662  false  
Nov 17 03:01:19  bafyreicbfkqmmeb5zqz36wdyd2mqx4qrknd65e7jgxpdnzugjspk4utwwq  1317669  f02665   StorageDealSealing                N                 N  baga6ea4seaqinevgp5qiresdzav56t2zf2wa6qgwxigum2st6xunatgubfphapi  1.984 GiB  0.000522542 FIL   522542  false

**Comment by dineshshenoy** [comment]
We thought these were "stuck" but they appear to have completed: 

Nov 16 17:32:58  bafyreigfuphv2usab6wpxcg37iacna3odjvtd4txo3wttnyy3t42wygnd4  1315823  f02665   StorageDealSealing                N                 N  baga6ea4seaqcrokczweyoh4qr6cdfcx3iym7yxgxh2p7euipmorheu7p4t5p6ky  1.984 GiB  0.000520799 FIL   520799  false  
Nov 16 17:34:09  bafyreif5cv3j4o2yop2k7vlzumhhovpxhuxonuqxx5m4q6xepbrs4olgta  1315811  f02665   StorageDealSealing                N                 N  baga6ea4seaqibkp6ltjotopm5eimsvrzwjswqzor6yunyw2eznktrtj57s4aeoq  1.984 GiB  0.000520796 FIL   520796  false  
Nov 16 17:34:41  bafyreidc4rvlftr7jt7w2szwmeg7bmtqqssnzfefqiojxucgwvsppyw6hq  1315807  f02665   StorageDealSealing                N                 N  baga6ea4seaqmhibucnhyewgwekkdzwyqtt5d5ijyi6shp2baxixr36avz6gfmky  1.984 GiB  0.000520795 FIL   520795  false  
Nov 16 18:22:57  bafyreihtuobpfp6tcuc2aiy6zgnnvfgooog5646u6x42zcng6k5hri4fhi  1315904  f02665   StorageDealSealing                N                 N  baga6ea4seaqhkv62crph2nfa3r2aeq5eqokg6ergguve7opvurypwhj5jmkngki  1.984 GiB  0.000520699 FIL   520699  false

**Comment by dineshshenoy** [comment]
https://github.com/filecoin-project/lotus/pull/4945#

**Comment by dirkmc** [comment]
Fixed by https://github.com/filecoin-project/lotus/issues/4900
