### ISSUE TITLE
Remove temporary piece file generation from go-fil-markets for ONLINE deals

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#4898]
# What

Currently when we verify CommP on the provider side, we read the data for the piece out of the blockstore and write the CAR file as a temporary file to disk for the piece, stored in the .lotusminer directory, and feed it later to the sector storage interface, deleting it only later. This can cause problems for miners who only have large storage allocated towards the sectors themselves.

It would be better to:
1. Just write to an OS pipe like we do on the client side when generating commP.
2. When we handoff to the sector storage interface, regenerate the CAR file, writing to an OS pipe again but this time feeding the reader to the sector storage interface.

# Things to consider

- The rarely used feature to write an index of all CIDs in a piece, and their offsets in the CAR file, using hooks in writing the car file on each new block (future ticket: remove this feature unless someone is going to use it)
- We need to still enable the filestore flow for offline deals, at least for the moment

**Comment by hannahhoward** [comment]
Implemented as draft in https://github.com/filecoin-project/go-fil-markets/pull/449

Also requires https://github.com/ipld/go-car/pull/37
^^^ though beware issues around having to continue to maintain a fork for filestore support :(

**Comment by dineshshenoy** [comment]
https://github.com/filecoin-project/go-fil-markets/pull/449

**Comment by dirkmc** [comment]
Fixed by filecoin-project/go-fil-markets#449
