### ISSUE TITLE
Breakup StorageDealSealing and OnDealSectorCommitted in go-fil-markets

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#4900]
# What

Currently, one a deal is published, it goes to StorageDealSealing and OnDealSectorCommitted is called that monitors and waits for the sealing process is complete. This gives very non-granular information about the status of sealing. Moreover, there's a bug in the logic of OnDealSectorCommitted as it relates to restarts: OnDealSectorCommitted works through the EventsAPI.Called interface and relies on seeing two seperate chain messages: the pre-commit and the prove-commit. If the pre-commit occurs, and then the node is restarted, because the code relies on seeing both messages, and after restart pre-commit has already occurred, the OnDealSectorCommitted will never see that message, meaning it can't interpret the prove-commit correctly (as it relies on extracting the sector ID from the pre-commit)

# How

Breakup StorageDealSealing into two seperate states with two seperate state entry funcs (break up VerifyDealActivated on both client and miner side). Two potential state names:

StorageDealAwaitingPreCommit
StorageDealSealing
(just rough, feel free to arrive at better ones)

Breakup OnDealSectorCommitted into OnDealSectorPreCommitted and OnDealSectorCommitted

The callback for OnDealSectorPreCommitted should take a sector ID and should save the sector ID on the stored deal.

The new OnDealSectorCommitted should take a SectorID as well as the other parameters (not sure if all or only some are needed)

There will need to be a seperate PR to break these up in Lotus

**Comment by dineshshenoy** [comment]
This will
Fix a bug where after a restart the client might not notice that the miner has started sealing a deal
Give the client insight into an extra state before the miner actually starts sealing: pre-com
