### ISSUE TITLE
lotus state list-messages shows no help with missing params

### ISSUE THREAD

**Issue by PatrickDeuse** [filecoin-project/lotus#4906]
**Describe the bug**
when running `lotus state list-messages` the output is `ERROR: must specify at least To or From in message filter`

not sure if  `To` or `From` actually work or if they need to be `to` and `from`

**To Reproduce**
1. Run `lotus state list-messages`
2. See error

**Expected behavior**
Expected to get the help page printed out

**Version (run `lotus version`):**
lotus version 1.1.3+git.15fe726e6

**Comment by PatrickDeuse** [comment]
`lotus state list-messages  --To 1234
Incorrect Usage: flag provided but not defined: -To`

the error message printed is therefore giving out false infos

**Comment by PatrickDeuse** [comment]
`lotus state replay`

leads to 

`must provide cid of message to replay`

expected again: the help page

**Comment by jennijuju** [comment]
> `lotus state list-messages --To 1234`
> 
> gives
> 
> `Incorrect Usage: flag provided but not defined: -To`
> 
> the error message printed is therefore giving out false infos
> 
> edit:
> 
> > lotus state list-messages --help
> > NAME:
> > lotus state list-messages - list messages on chain matching given criteria
> > USAGE:
> > lotus state list-messages [command options] [arguments...]
> 
> as far as i can see `lotus state list-messages` has no arguments, only options

the helper menu clearly stated the option to be `--to` and `--from`

**Comment by jennijuju** [comment]
> `lotus state replay`
> 
> leads to
> 
> `must provide cid of message to replay`
> 
> expected again: the help page
> 
> the output behavior seems to be inconsistent. one prints `ERROR`, the other doesn't. others print the help

`state replay` must take one message CID thus the message.

**Comment by PatrickDeuse** [comment]
> > `lotus state list-messages --To 1234`
> > gives
> > `Incorrect Usage: flag provided but not defined: -To`
> > the error message printed is therefore giving out false infos
> > edit:
> > > lotus state list-messages --help
> > > NAME:
> > > lotus state list-messages - list messages on chain matching given criteria
> > > USAGE:
> > > lotus state list-messages [command options] [arguments...]
> > 
> > 
> > as far as i can see `lotus state list-messages` has no arguments, only options
> 
> the helper menu clearly stated the option to be `--to` and `--from`
> 
> ```
> OPTIONS:
>    --to value        return messages to a given address
>    --from value      return messages from a given address
>    --toheight value  don't look before given block height (default: 0)
>    --cids            print message CIDs instead of messages (default: false)
>    --help, -h        show help (default: false)
> ```

yes,but the error message names them To and From
