### ISSUE TITLE
Option for lotus client list-asks show all miners

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#4908]
lotus client list-asks shows a filtered list of miners that meet the minimum power constraint ("HasMinPower" = true).   This results in showing only miners above 10 TiB.

Ideally, we'd be able to set our own criteria as a user for miners that meet our specific requirements.

### Edit (@jennijuju)

`lotus client list-asks --all` to show all connected miners

**Comment by jennijuju** [comment]
FYI - this could be a very large number and takes long time to run.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
