### ISSUE TITLE
lotus-miner wants 15.1 * [sector size] available to store a sector

### ISSUE THREAD

**Issue by PatrickDeuse** [filecoin-project/lotus#4920]
**Describe the bug**
We are running a test miner on the calibration network. 512MB sectors. we have 5 store storage drives attached. we made sure they all can hold exactly 500 512MB sectors. (fallocate -l 256G ....). all files mounted as loop devices, nfs to the miner, etx4.

now we ran 2500 pledges and waited until they finished - we thought. in the end we were left with 156 512MB sectors not stored, 51 in FinalizeSector state (MaxSealingSectors=50) and 105 failed pledges. the sectors are pledged with a 2 minutes gap - they do not overlap besides waitseed.

Why?

someIP:/opt/filecoin/storage/s0  251G  251G     0 100% /opt/filecoin/calibration/storage/s0
someIP:/opt/filecoin/storage/s1  251G  232G  7.1G  98% /opt/filecoin/calibration/storage/s1
someIP:/opt/filecoin/storage/s2  251G  232G  7.1G  98% /opt/filecoin/calibration/storage/s2
someIP:/opt/filecoin/storage/s3  251G  232G  7.1G  98% /opt/filecoin/calibration/storage/s3
someIP:/opt/filecoin/storage/s4  251G  232G  7.1G  98% /opt/filecoin/calibration/storage/s4

s0 got copied by hand, 500 512MB sectors. proves fine - no problem at all with 0 space left. 

224326cc-5756-4bb1-ae29-48badfcc647c:
        [##################################################] 251 GiB/251 GiB 100%                                 
        Unsealed: 0; Sealed: 500; Caches: 500; Reserved: 0 B                                                      
        Weight: 10; Use: Store
        Local: /opt/filecoin/calibration/storage/s0
        URL: http://someIP/remote

271d2cac-e416-4621-9015-a5222506447c:
        [################################################  ] 243.9 GiB/251 GiB 97%                                
        Unsealed: 0; Sealed: 461; Caches: 460; Reserved: 0 B                                                      
        Weight: 10; Use: Store
        Local: /opt/filecoin/calibration/storage/s1
        URL: http://someIP/remote

693dae39-645c-48cd-a0ff-311c8d0391a8:
        [################################################  ] 243.9 GiB/251 GiB 97%                                
        Unsealed: 0; Sealed: 461; Caches: 459; Reserved: 0 B                                                      
        Weight: 10; Use: Store
        Local: /opt/filecoin/calibration/storage/s2
        URL: http://someIP/remote

93246500-b464-4050-9a34-0ca76bcf1b0f:
        [################################################  ] 243.9 GiB/251 GiB 97%                                
        Unsealed: 0; Sealed: 461; Caches: 462; Reserved: 0 B                                                      
        Weight: 10; Use: Store
        Local: /opt/filecoin/calibration/storage/s3
        URL: http://someIP/remote

5cc6540d-7a74-4d55-9a00-6acf13a178fd:
        [################################################  ] 243.9 GiB/251 GiB 97%                                
        Unsealed: 0; Sealed: 461; Caches: 463; Reserved: 0 B                                                      
        Weight: 10; Use: Store
        Local: /opt/filecoin/calibration/storage/s4
        URL: http://someIP/remote

so s1/2/3/4 each have space for 39 more 512MB sectors. 

first this logs in a loop while sealing from 500 tp 2394 sectors.

{"level":"debug","ts":"2020-11-19T00:17:00.174+0100","logger":"stores","caller":"stores/index.go:388","msg":"not allocating on 224326cc-5756-4bb1-ae29-48badfcc647c, out of space (available: 0, need: 536870912)"}
{"level":"debug","ts":"2020-11-19T00:17:00.174+0100","logger":"stores","caller":"stores/index.go:388","msg":"not allocating on 224326cc-5756-4bb1-ae29-48badfcc647c, out of space (available: 0, need: 7569879859)"}
{"level":"debug","ts":"2020-11-19T00:19:00.117+0100","logger":"stores","caller":"stores/index.go:388","msg":"not allocating on 224326cc-5756-4bb1-ae29-48badfcc647c, out of space (available: 0, need: 8106750771)"}
{"level":"debug","ts":"2020-11-19T00:19:00.117+0100","logger":"stores","caller":"stores/index.go:388","msg":"not allocating on 224326cc-5756-4bb1-ae29-48badfcc647c, out of space (available: 0, need: 8106750771)"}

filling he other 4 storage path with data. ~512MB, then testing 7Gb, then testing 8GB.

ending in an endless loop of:

{"level":"debug","ts":"2020-11-19T08:23:30.178+0100","logger":"stores","caller":"stores/index.go:388","msg":"not allocating on 224326cc-5756-4bb1-ae29-48badfcc647c, out of space (available: 0, need: 8106750771)"}
{"level":"debug","ts":"2020-11-19T08:23:30.178+0100","logger":"stores","caller":"stores/index.go:388","msg":"not allocating on 93246500-b464-4050-9a34-0ca76bcf1b0f, out of space (available: 7609516032, need: 8106750771)"}
{"level":"debug","ts":"2020-11-19T08:23:30.178+0100","logger":"stores","caller":"stores/index.go:388","msg":"not allocating on 5cc6540d-7a74-4d55-9a00-6acf13a178fd, out of space (available: 7607418880, need: 8106750771)"}
{"level":"debug","ts":"2020-11-19T08:23:30.178+0100","logger":"stores","caller":"stores/index.go:388","msg":"not allocating on 271d2cac-e416-4621-9015-a5222506447c, out of space (available: 7611613184, need: 8106750771)"}
{"level":"debug","ts":"2020-11-19T08:23:30.178+0100","logger":"stores","caller":"stores/index.go:388","msg":"not allocating on 693dae39-645c-48cd-a0ff-311c8d0391a8, out of space (available: 7612661760, need: 8106750771)"}

what does the miner wants that storage for? does this translate to 32GB sectors? 

is this behavior wanted? and what is it good for? it wastes everything <= 15.1 * [sector size] on every storage path.

**To Reproduce**
1. not quite sure

**Expected behavior**
All sectors stored

**Version (run `lotus version`):**
appeared in 1.1.0 and didn't get resolved with 1.2.0

**Comment by hyunmoon** [comment]
https://github.com/filecoin-project/lotus/blob/dc3d17c9eae5b9acfe587541d0e6ef3245537a33/extern/sector-storage/storiface/filetype.go#L30

**Comment by PatrickDeuse** [comment]
thsi is not sealing storage but store storage
