### ISSUE TITLE
v1.2.0 build fail

### ISSUE THREAD

**Issue by satonz** [filecoin-project/lotus#4934]
[Log.txt](https://github.com/filecoin-project/lotus/files/5570948/Log.txt)

**Comment by satonz** [comment]
this is log

**Comment by Stebalien** [comment]
I'd try again with v1.2.1. Unfortunately, this docker image is not maintained by this team so if you have any further problems, you'll need to report them upstream: https://github.com/glifio/filecoin-docker.
