### ISSUE TITLE
lotus-seed error!!! 2k test fail

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4939]
https://github.com/filecoin-project/lotus/blob/df66f48f6431129ad0359b5d66ca0ee8ee14f592/cmd/lotus-seed/main.go#L130
lotus daemon --lotus-make-genesis=devgen.car --genesis-template=localnet.json --bootstrap=false

publishing 2 storage deals on miner t01000 with worker t3qxrdbq764yhpf4npbzupe5xgmhvt4nn3wtygnfg35pov5xve5czhnekudapsu2yn4h2irbdurpfdwvwpmjkq
0.000001621003269618 FIL
2020-11-20T15:03:02.647+0800	WARN	vm	vm/runtime.go:331	Abortf: unsupported seal proof type: %!s(abi.RegisteredSealProof=5)
2020-11-20T15:03:02.647+0800	WARN	vm	vm/runtime.go:144	VM.Call failure: unsupported seal proof type: %!s(**abi.RegisteredSealProof=5**) (RetCode=16):
    github.com/filecoin-project/specs-actors/actors/builtin/miner.Actor.PreCommitSector
        /home/zgf/gopath/src/github.com/filecoin-project/specs0913/actors/builtin/miner/miner_actor.go:473
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/zgf/gopath/src/github.com/filecoin-project/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.AfterGenesisSet: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): genesis func failed: make genesis block: setup miners failed: failed to confirm presealed sectors: doExec apply message failed: unsupported seal proof type: %!s(abi.RegisteredSealProof=5) (RetCode=16)

**Comment by magik6k** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/4911/files
