### ISSUE TITLE
Gas price suggestion seems to not work in 1.2.0

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#4941]
I've updated to 1.2.0 yesterday. Ever since I did that, all my messages get stuck in the pool and I need to manually replace them via `mpool replace --auto`. Now this might be unrelated to 1.2.0, I just find it odd that it started happening at the same time.

**Comment by jennijuju** [comment]
likely it was caused by rising base fee.

**Comment by jennijuju** [comment]
(please reopen the issue when more specific details are available.. like one message example in question and the tipset + base ffee
