### ISSUE TITLE
PreCommit2 stunks on generate tree_r_last using GPU within docker 

### ISSUE THREAD

**Issue by yydfjt** [filecoin-project/lotus#4951]
Describe the bug

GPU is NVIDIA 2060s; lotus-worker runs in docker container;
Since 1.2.0, sometimes GPU fails on generate tree_r_last, then it stucks there.
dmesg shows the following info:
[ 609.751833] NVRM: Xid (PCI:0000:01:00): 13, pid=3309, Graphics SM Warp Exception on (GPC 1, TPC 0, SM 0): Out Of Range Address [ 609.751912] NVRM: Xid (PCI:0000:01:00): 13, pid=3309, Graphics Exception: ESR 0x50c730=0xc01000e 0x50c734=0x20 0x50c728=0x4c1eb72 0x50c72c=0x174 [ 609.752733] NVRM: Xid (PCI:0000:01:00): 43, pid=3265, Ch 00000008

I tried without docker, lotus-worker works fine on PreCommit2.
Update to lates drivers is not always works.

**This issue caused by neptune 1.2.0(and after); However, docker works fine  with 1.1.1.**

So, how can I fix this issue?

To Reproduce

Run lotus-worker in docker conatiner
See dmesg
Expected behavior

Screenshots

Version (run lotus version):
1.2.0

Additional context

**Comment by porcuquine** [comment]
Please see whether the problem persists once this is being used https://github.com/filecoin-project/rust-fil-proofs/pull/1335.

**Comment by yydfjt** [comment]
I thinks they are not related. From my tests, rust-fil-proofs 5.4.0 has less chance to encounter this err.
