### ISSUE TITLE
lotus-shed rpc terminates on bad input

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#4958]
Calling a method with bad arguments terminates the shell, which seems undesirable:

```
# /work/lotus/lotus-shed rpc
Daemon:  1.2.0+git.dc3d17c9e.dirty+api1.0.0
Local: lotus-shed version 1.2.0
Usage: > Method [Param1, Param2, ...]
> StateMinerFaults [f019100, null]
2020-11-21T19:41:14.946+0200	WARN	lotus-shed	lotus-shed/main.go:84	json: error calling MarshalJSON for type json.RawMessage: invalid character '0' in literal false (expecting 'a')
```

**Comment by rjan90** [comment]
Hi!

Thanks for the report. I tried to reproduce the error but could not recreate it with the exact same commands as you, so this seems to have been fixed in newer versions of Lotus.

If this is a issue in current release please open a new ticket.

Thanks again !
