### ISSUE TITLE
Replace expired wdpost messages with messages will cost less gas

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4959]
When there is a mpool congestion, a wdpost message has a high chance to be landed on chain too late(miss the deadline) which makes miner has to pay for both gas and penalty. 
Replace it with another message so that miner can save some gas in this case.

**Comment by nicola** [comment]
We could do the same for ProveCommit that passed their deadline.

**Comment by jennijuju** [comment]
closed by #5936
