### ISSUE TITLE
FailedUnrecoverable sectors not remove

### ISSUE THREAD

**Issue by 2019jack** [filecoin-project/lotus#4965]
lotus-miner sectors remove --really-do-it 0

ERROR: normal shutdown of state machine

Daemon: 1.2.1+git.375b7a1c4+api1.0.0
Local: lotus version 1.2.1+git.375b7a1c4

please tell me how to remove FailedUnrecoverable sectors, thanks

**Comment by jennijuju** [comment]
have you  tried to update-status to removing？

**Comment by 2019jack** [comment]
lotus-miner sectors update-state --really-do-it 373 Removed
ERROR: normal shutdown of state machine

2020-11-26T19:07:17.134+0800    WARN    rpc     go-jsonrpc@v0.1.2-0.20201116213214-f4b2d34247f0/handler.go:273  error in RPC call to 'Filecoin.SectorsUpdate': normal shutdown of state machine:
    github.com/filecoin-project/go-statemachine.init
        /root/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:16
