### ISSUE TITLE
lotus send from == to problem

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4969]
![aa73d1603b665244c7d6d689965908d](https://user-images.githubusercontent.com/48779939/99930355-c1cbe000-2d8b-11eb-853e-70fb02b44944.png)

**Comment by zgfzgf** [comment]
lotus chain getmessage bafy2bzacedwqp6jssnvf3kzx7rfbj6qe7mlemxsjzn7tyk5gam3ja2bfphbjo
{
  "Version": 0,
  "To": "f3sbpphqgekiz6z3w4i4j5hwcslwlmymp53vhf6n3d47364wdiq7zuw6ny7qwlius2cs2oua7zx7scfxk72j7q",
  "From": "f3sbpphqgekiz6z3w4i4j5hwcslwlmymp53vhf6n3d47364wdiq7zuw6ny7qwlius2cs2oua7zx7scfxk72j7q",
  "Nonce": 104,
  "Value": "1000000000000",
  "GasLimit": 1857804256,
  "GasFeeCap": "23222553210",
  "GasPremium": "23222553210",
  "Method": 0,
  "Params": null,
  "CID": {
    "/": "bafy2bzacedwqp6jssnvf3kzx7rfbj6qe7mlemxsjzn7tyk5gam3ja2bfphbjo"
  }
}

**Comment by jennijuju** [comment]
A sender can chose to do a self transfer if one choses to, nothing wrong about that.
