### ISSUE TITLE
[Create Miner] getWorkerAddr returned exit code 255

### ISSUE THREAD

**Issue by rosenjiang** [filecoin-project/lotus#498]
Create Miner stage in the web, return "Run lotus-storage-miner init --actor=t01** --owner=t3***", it's working fine.
But run command in CLI, got "getWorkerAddr returned exit code 255".

thx

**Comment by steven004** [comment]
This happens too when I just run `lotus daemon` on my macbook.

**Comment by rosenjiang** [comment]
i think, becouse of devnet unstable, this issue did'nt happen again. so close it.

**Comment by yaephin** [comment]
I think , may be your proof-parameters corrupted,check 

> lotus fetch-params

to see whether the checksums correct.
