### ISSUE TITLE
Repeated invocations of lotus sync lead to different results

### ISSUE THREAD

**Issue by ghost** [filecoin-project/lotus#4993]
**Describe the bug**
When I run `lotus sync wait` several times in a row, I get conflicting output.  It seems to depend on which worker is picked.  Here's an example:

```
$ lotus sync wait
Worker: 32; Base: 264438; Target: 264438 (diff: 0)
State: complete; Current Epoch: 264438; Todo: 0

Done!
$ lotus sync wait
Worker: 33; Base: 0; Target: 0 (diff: 0)
State: <unknown: 0>; Current Epoch: 0; Todo: 0

Done!
$ lotus sync wait
Worker: 56; Base: 0; Target: 0 (diff: 0)
State: <unknown: 0>; Current Epoch: 0; Todo: 0

Done!
$ lotus sync wait
Worker: 73; Base: 0; Target: 0 (diff: 0)
State: <unknown: 0>; Current Epoch: 0; Todo: 0

Done!
```

Worker 32 is correct.  But workers 33, 56, and 73 are all reporting `<unknown 0>;`

**To Reproduce**
1.  Install lotus v1.2.1
2.  Stop the old daemon gracefully
3.  `rm -rf ~/.lotus/datastore/chain/`
4.  Restart lotus:  `nohup lotus daemon --import-snapshot https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car > ~/lotus-daemon.log &`
5.  After download finishes, the API will come up and then run `lotus sync wait` a few times.  I observe different results depending on which worker is chosen.

**Expected behavior**
1.  All the workers should agree on the chain state.
2.  Or, if some workers can't read the database (can't get a read lock or whatever causes this), they should return some error state like "Cannot determine chain state (worker ##)".
3.  Send all `lotus sync wait` queries to a single worker that is known to have the current database lock.

**Version (run `lotus version`):**
```
$ lotus version
Daemon:  1.2.1+git.df66f48f6+api1.0.0
Local: lotus version 1.2.1+git.df66f48f6
```

**Comment by rjan90** [comment]
Hey! Thanks for the issue, I tried to reproduce this today but where unable to get the `<unknown 0>` when invoking `lotus sync wait`.

Repro steps I did:
- Compact chain & import an older snapshot (halting after import)
- Start up the Lotus node
- Run `while true; do lotus sync wait ; sleep 1; done` until it was finished syncing

Closing this issue as fixed on newer versions of Lotus. Thanks again!
