### ISSUE TITLE
Log error message if SimultaneousTransfers parameter is too low

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#5009]
Log an error message so that the issue is discoverable when the queue is "full" (WARN). It could trigger the client to increase the SimultaneousTransfers parameter in or invest in more hardware or something else.

First option would be to show it in the "deal list" view, but if that's complex to bubble up to teh UI, a client log entry would help the client fix the issue.

Pulled from #4946

**Comment by dirkmc** [comment]
This is actually not as straight-forward as it sounds. The limit exists in graphsync, which is a few layers down from lotus.
Ideally we would add a new event to graphsync that tells us when a new transfer request is queued up, with a parameter stating the number of transfers that are queued up.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
