### ISSUE TITLE
Improve Deal Packing to allow Sectors to be fully utilized. Current setup results in probability of unfull sectors.

### ISSUE THREAD

**Issue by cwhiggins** [filecoin-project/lotus#5020]
Depending on how deals arrive, it is possible to have space in a sector, but system starts a new wait deals sector anyway.

Info from discussion with ribasushi - PLFD 

right... this kinda makes sense, though I agree it is suboptimal
sectors are written out eagerly, as deals come
so the packing is linear
since everything in a sector must be part of a balanced tree, zeroes are inserted to pad things up to the correct boundaries
in order of arrival:
1. 1GiB incoming == 1381454/1GiB
2. 8GiB incoming == 1381454/1GiB  0/1GiB  0/2GiB  0/4GiB  1381539/8GiB
3. 8GiB incoming == 1381454/1GiB  0/1GiB  0/2GiB  0/4GiB  1381539/8GiB  1382008/8GiB
4. 2GiB incoming == 1381454/1GiB  0/1GiB  0/2GiB  0/4GiB  1381539/8GiB  1382008/8GiB   1382298/2GiB
5. 8GiB incoming, nowhere to put it, close above sector => 1381454/1GiB  0/1GiB  0/2GiB  0/4GiB  1381539/8GiB  1382008/8GiB   1382298/2GiB  0/2GiB  0/4GiB

lotus-miner sectors status 798
SectorID:	798
Status:		Committing
CIDcommD:	baga6ea4seaqehbx7mxhvn5lktawzwlinwvhedmbtvrdv6zaeqf3fn6klr7auola
CIDcommR:	bagboea4b5abcbtuzytla3emrqghkix46io5vmqizea35t746bw5qtzuzhmqz3usd
Ticket:		26e721482e0bb7dde47c5f845e9836ee24205338758f12ef28af00af8ffb2714
TicketH:	267832
Seed:		baaba536ebb8704f65424dc2b56be0a491dd60c9697b3f473d44bcff9a5082b8
SeedH:		269652
Precommit:	bafy2bzaceaacfy4jz2zibtayo4dagmzajhszgtcfeixbllejtafzxakemhdki
Commit:		<nil>
Proof:		
Deals:		[1381454 0 0 0 1381539 1382008 1382298 0 0]

...ctvfgl7q  1381454  StorageDealSealing       f3s5cv232rveavpaopi.................kwiz3kyg23pwbdzdtec6a  1GiB    0.0051595434 FIL          521166
...63up5sfe  1381539  StorageDealSealing      f3rab4mhsr7f2gdg6oz..................6fh2o3wff4yfrzag4lge2r2q  8GiB    0.0412735752 FIL          521131
...ttc4w6sq  1382008  StorageDealSealing       f3rab4mhsr7f2gdg6...............fh2o3wff4yfrzag4lge2r2q  8GiB    0.0412641504 FIL          521012
...6vw7y24y  1382298  StorageDealSealing       f3s5cv232rveav................j5jkwiz3kyg23pwbdzdtec6a  2GiB    0.0103140378 FIL          520911
...sleurwsa  1382349  StorageDealSealing        f3rab4mhsr7f2gdg6ozgj4..............h2o3wff4yfrzag4lge2r2q  8GiB    0.0412546464 FIL          520892

deal 1382349 started a new sector, though I believe it should have fit in  sector 798?

**Comment by jennijuju** [comment]
@dirkmc mind taking a look at this?

**Comment by Reiers** [comment]
**Issue solved in newer versions of Lotus.**

I tested with 32 x 1GB deals, all got packed into 1 x 32GiB sector.  
Lotus version:
`lotus version 1.13.2-rc4+mainnet+git.e05fdf892`

Closing ticket.
