### ISSUE TITLE
constant 4294967295 overflows int     AND   undefined: ffi.GeneratePieceCIDFromFile

### ISSUE THREAD

**Issue by twl4587** [filecoin-project/lotus#5026]
ubuntu20.04   
go1.15.5

git clone https://github.com/filecoin-project/lotus.git
cd lotus/
export RUSTFLAGS="-C target-cpu=native -g"
export FFI_BUILD_FROM_SOURCE=1
make clean all

   Compiling filecoin-proofs-api v5.4.1
note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -lhwloc -lOpenCL -lOpenCL -lOpenCL -lgcc_s -lc -lm -lrt -lpthread -lutil -ldl -lutil

    Finished release [optimized] target(s) in 5m 24s
++ cat /tmp/tmp.FyCB3Og9Oh
++ grep native-static-libs:
++ head -n 1
++ cut -d : -f 3
+ local '__linker_flags= -lhwloc -lOpenCL -lOpenCL -lOpenCL -lgcc_s -lc -lm -lrt -lpthread -lutil -ldl -lutil'
++ git rev-parse HEAD
+ sed -e 's;@VERSION@;1d9cb3e8ff53f51f9318fc57e5d00bc79bdc0128;' -e 's;@PRIVATE_LIBS@; -lhwloc -lOpenCL -lOpenCL -lOpenCL -lgcc_s -lc -lm -lrt -lpthread -lutil -ldl -lutil;' filcrypto.pc.template
+ find -L . -type f -name filcrypto.h
+ read
+ find -L . -type f -name libfilcrypto.a
+ read
+ exit
+ rm -f /tmp/tmp.FyCB3Og9Oh
+ popd
~/lotus/extern/filecoin-ffi
+ find -L rust/target/release -type f -name filcrypto.h -exec cp -- '{}' . ';'
+ find -L rust/target/release -type f -name libfilcrypto.a -exec cp -- '{}' . ';'
+ find -L rust -type f -name filcrypto.pc -exec cp -- '{}' . ';'
+ check_installed_files
+ [[ ! -f ./filcrypto.h ]]
+ [[ ! -f ./libfilcrypto.a ]]
+ [[ ! -f ./filcrypto.pc ]]
+ echo '[install-filcrypto/main] successfully built and installed libfilcrypto from source'
[install-filcrypto/main] successfully built and installed libfilcrypto from source
+ exit
make[1]: Leaving directory '/root/lotus/extern/filecoin-ffi'
rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.53c39b117" -o lotus ./cmd/lotus
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
# github.com/filecoin-project/lotus/extern/sector-storage
extern/sector-storage/manager.go:114:17: undefined: ffiwrapper.New
extern/sector-storage/worker_local.go:148:9: undefined: ffiwrapper.New
extern/sector-storage/worker_local.go:473:15: undefined: ffi.GetGPUDevices
go build github.com/supranational/blst/bindings/go: build constraints exclude all Go files in /root/lotus/extern/blst/bindings/go
go build github.com/ipsn/go-secp256k1: build constraints exclude all Go files in /usr/local/go/pkg/mod/github.com/ipsn/go-secp256k1@v0.0.0-20180726113642-9d62b9f0bc52
# github.com/dgraph-io/badger/v2
/usr/local/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/value.go:50:5: constant 4294967295 overflows int
# github.com/filecoin-project/go-fil-markets/pieceio
/usr/local/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.0.5/pieceio/pieceio.go:177:19: undefined: ffi.GeneratePieceCIDFromFile
# github.com/filecoin-project/lotus/lib/commp
lib/commp/writer.go:42:17: undefined: ffiwrapper.GeneratePieceCIDFromFile
lib/commp/writer.go:65:13: undefined: ffiwrapper.GeneratePieceCIDFromFile
lib/commp/writer.go:103:12: undefined: ffi.GenerateUnsealedCID
# github.com/filecoin-project/lotus/chain/vm
chain/vm/syscalls.go:79:16: undefined: ffiwrapper.GenerateUnsealedCID
make: *** [Makefile:68: lotus] Error 2
root@utserver:~/lotus# 

Why do I report mistakes and how should I correct them? thank you!
我不懂英文，最好能用中文交流！

**Comment by Reiers** [comment]
Hi @twl4587 

Thanks for the report. Please double check your dependencies and please upgrade Lotus.
*Link to latest tags [here.](https://github.com/filecoin-project/lotus/tags)*


I can see that your Go version is below 1.16.4 and make sure that Rust is active in current shell when installing:

Docs:
https://lotus.filecoin.io/lotus/install/linux/#building-from-source

Closing issue ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)
