### ISSUE TITLE
chain sync err  and can not re import

### ISSUE THREAD

**Issue by haheihou5** [filecoin-project/lotus#5028]
loadcar failed:mismach in content integrity, name:xxxxxx.data:xxxxxxx

**Comment by Reiers** [comment]
Hi @haheihou5 

Thanks for the report. The issue you are experiencing lies elsewhere.

Please follow the guide: https://lotus.filecoin.io/docs/set-up/chain-management/

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)
