### ISSUE TITLE
constant 4294967295 overflows int AND undefined: ffi.GeneratePieceCIDFromFile

### ISSUE THREAD

**Issue by twl4587** [filecoin-project/lotus#5030]
constant 4294967295 overflows int AND undefined: ffi.GeneratePieceCIDFromFile:
###############################################################
github.com/filecoin-project/lotus/extern/sector-storage
extern/sector-storage/manager.go:114:17: undefined: ffiwrapper.New
extern/sector-storage/worker_local.go:148:9: undefined: ffiwrapper.New
extern/sector-storage/worker_local.go:473:15: undefined: ffi.GetGPUDevices
go build github.com/supranational/blst/bindings/go: build constraints exclude all Go files in /root/lotus/extern/blst/bindings/go
go build github.com/ipsn/go-secp256k1: build constraints exclude all Go files in /usr/local/go/pkg/mod/github.com/ipsn/go-secp256k1@v0.0.0-20180726113642-9d62b9f0bc52
github.com/dgraph-io/badger/v2
/usr/local/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/value.go:50:5: constant 4294967295 overflows int
github.com/filecoin-project/go-fil-markets/pieceio
/usr/local/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.0.5/pieceio/pieceio.go:177:19: undefined: ffi.GeneratePieceCIDFromFile
github.com/filecoin-project/lotus/lib/commp
lib/commp/writer.go:42:17: undefined: ffiwrapper.GeneratePieceCIDFromFile
lib/commp/writer.go:65:13: undefined: ffiwrapper.GeneratePieceCIDFromFile
lib/commp/writer.go:103:12: undefined: ffi.GenerateUnsealedCID
github.com/filecoin-project/lotus/chain/vm
chain/vm/syscalls.go:79:16: undefined: ffiwrapper.GenerateUnsealedCID
make: *** [Makefile:68: lotus] Error 2

##############################################################

ubuntu20.04     ////         go1.15.5      /////        lotus --1.2.1

git clone https://github.com/filecoin-project/lotus.git
cd lotus/
export RUSTFLAGS="-C target-cpu=native -g"
export FFI_BUILD_FROM_SOURCE=1
make clean all

**Comment by Reiers** [comment]
**Hi @twl4587** 

Thanks for reporting- it appears that you have an issue open about this.
https://github.com/filecoin-project/lotus/issues/5026

Closing duplicate ticket.
