### ISSUE TITLE
When creating a deal and the initial data transfer fails, Lotus should resolve the situation

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#5038]
Canceling a deal locally by the client is already captured by: #4093 

When creating a deal, if the data transfer doesn't initiate correctly, Lotus asks clients whether we should restart a deal or cancel an existing deal.

For example:
552   Requested           ...U3cRpimY  ...rqfxzklq  Y           0B           ...oyvxyxr3ckoqq2ry7triy223lv6je75k7e"}}  
  Message: other peer appears to have hung up. restart Channel

Ideal Behavior:
Lotus should automatically cancel the deal so that there isn't a burden on the client.

**Comment by dineshshenoy** [comment]
cc: @dirkmc

**Comment by dirkmc** [comment]
This `other peer appears to have hung up` message appears in `lotus client list-transfers`.
However it seems that the deal state reported by `lotus client list-deals` is `StorageDealError`.
