### ISSUE TITLE
When client cancels a data transfer and there's no network connectivity, let miner exit the deal gracefully

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#5039]
When a client initiates a cancel of a data transfer, the miner may not be notified because they're offline or there's a network error.

If there is no network connectivity, the other party in the data transfer will not detect the deal cancellation (because it's not possible for the party that cancels the transfer to send a "cancel" message across the wire).

Potentially add a timeout for the miner if the client never dials them back to continue the data transfer?

https://github.com/filecoin-project/go-fil-markets/pull/457

**Comment by dineshshenoy** [comment]
cc: @dirkmc

**Comment by TippyFlitsUK** [comment]
Hi @dineshshenoy

This looks like a reminder. Should we close it or keep it open?
