### ISSUE TITLE
all messages were stuck in the mpool

### ISSUE THREAD

**Issue by alingb** [filecoin-project/lotus#5042]
**Describe the bug**
After upgrading v1.21 yesterday, all the messages were stuck in the mpool and all the computing power was offline. After executing "lotus mpool replace --auto" for more than 10 times, there was no effect。All are in the waiting phase。

**To Reproduce**
1. Run '...'
2. See error

oot@lotus-master:~# lotus-miner sectors list
ID   State         OnChain  Active  Expiration                    Deals  DealWeight
0    Proving       YES      NO      1749038 (in 1 year 20 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
1    Proving       YES      NO      1774958 (in 1 year 22 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
2    Proving       YES      NO      1763438 (in 1 year 21 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
3    Proving       YES      NO      1757678 (in 1 year 21 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
6    Proving       YES      NO      1757678 (in 1 year 21 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
38   Packing       NO       NO      n/a                           1
39   Proving       YES      NO      1763438 (in 1 year 21 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
40   Proving       YES      NO      1763438 (in 1 year 21 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
41   Proving       YES      NO      1780718 (in 1 year 22 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
42   Proving       YES      NO      1766318 (in 1 year 21 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
43   Proving       YES      NO      1769198 (in 1 year 21 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
44   Proving       YES      NO      1786478 (in 1 year 22 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
53   Proving       YES      NO      1783598 (in 1 year 22 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
55   Proving       YES      NO      1777838 (in 1 year 22 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
58   Proving       YES      NO      813038 (in 26 weeks 4 days)   1      126.7KiB
  RecoveryTimeout: 311978 (in 1 week 5 days)
65   Proving       YES      NO      1780718 (in 1 year 22 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
66   Proving       YES      NO      1786478 (in 1 year 22 weeks)  CC
  RecoveryTimeout: 311978 (in 1 week 5 days)
………………
217  CommitWait    NO       NO      n/a                           CC
218  CommitWait    NO       NO      n/a                           CC
219  CommitWait    NO       NO      n/a                           CC
220  CommitWait    NO       NO      n/a                           CC

root@lotus-master:~# lotus mpool pending --local
{
  "Message": {
    "Version": 0,
    "To": "f05",
    "From": "f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq",
    "Nonce": 396,
    "Value": "0",
    "GasLimit": 67768463,
    "GasFeeCap": "1475612631",
    "GasPremium": "21057839",
    "Method": 4,
    "Params": "gYGCi9gqWCgAAYHiA5IgICEZER+TBhgoVRBP3njFz+r3MXlVoluZXxSSZVT+dy41GgACAAD0WDEDq/7N65yaZ3jU3G6WUg5wa1uT4a7eGeq1fLZdnM0K4XSq5KEoTZEYHzbYJQx29fgDRAD6wAN4NG1BVldnNUFJZzJRZDNuVjE2RHQ5VG5LT0VIODYzbndWMDF2RWVDaEl0aGhGbHRTbEdIbm8aAARFHRoADRvuRQABMS0ARgAI363NWkBYYQKzyFId7o6p1CCuIV+knsRkwHkYgWlL/5hkRl9+6JBGZpIMZJSYzWvzzdwxwaD4M3sALKRuwplsfgAZuv2qiswdg4bkFqYppy6w2OQMtfT+PV+onwKSOeI3YCg85FiSUs0=",
    "CID": {
      "/": "bafy2bzaceaaphqqjfluno5yvuunlec7kc6vdeo2e7mfkxg73uawi7hkyjj422"
    }
  },
  "Signature": {
    "Type": 2,
    "Data": "oluLfFSJQRqvXOUpkomrN5839n2FH9g+XFemgAlXubXNEMk23sWd4MhF0dSvJ9InBaTOlBGMedI1N7HzGNJca9lzmRvrqR8ZNsCVFt+CEUuKG/YfIwAgOEaZYYIylbaJ"
  },
  "CID": {
    "/": "bafy2bzaceaaphqqjfluno5yvuunlec7kc6vdeo2e7mfkxg73uawi7hkyjj422"
  }
}
{
  "Message": {
    "Version": 0,
    "To": "f05",
    "From": "f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq",
    "Nonce": 397,
    "Value": "0",
    "GasLimit": 64909446,
    "GasFeeCap": "770303909",
    "GasPremium": "99248",
    "Method": 4,
    "Params": "gYGCi9gqWCgAAYHiA5IgIIeudBuddhDMaF9lK4X3VGynU6o+MH8Bhu/Fg+YHta8bGoAAAAD0WDEDkuhhFUKcilFZlrFoQVwpvPBVVIINdILS6QOaTrp7PMaRGkWuXNylZjdbPv/1Gn38RAD6wAN4NG1BWENnNUFJZ2U5ZjNZdFhGd0Vlb3FBcVBEREdZR24zcUhMNFZuWFZFeTdlbzRHQi9BOWMaAAREDBoADFFuRQA7msoASAACN2k7JACSQFhhArYHA+HR4K5oc+WJe6XYYXkFxdq2nXlgeSsgRLhesMPhDt4lxD2+Eq3x/dgorQHIMA7EgrM4ShGtV2OyyJLq4Mvj/eMBkfyIcr21Fpk5wOMnU6u8JCeflIOlscTrvsWEEw==",
    "CID": {
      "/": "bafy2bzacedsxvjhxanng2p6ccohwylsy74y53ctoztsc4plue7doh3ag6oh6a"
    }
  },
  "Signature": {
    "Type": 2,
    "Data": "p7Y3Tz76wxy+TI+XjDVpH5TZN2jRtk8rbvuGdJYHAWy/XhfmKikAXNxqVcbDH6ErBjRZE4Az+6JU8/tSbxVNOHIbsrAb0Edhe5C5NGA/t8IsXsYPAu5CCwd3WoOI/kHM"
  },
  "CID": {
    "/": "bafy2bzacedsxvjhxanng2p6ccohwylsy74y53ctoztsc4plue7doh3ag6oh6a"
  }
}
{
  "Message": {
    "Version": 0,
    "To": "f057466",
    "From": "f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq",
    "Nonce": 398,
    "Value": "0",
    "GasLimit": 11181425,
    "GasFeeCap": "21220533620",
    "GasPremium": "100491",
    "Method": 11,
    "Params": "gYGDAABTlJSAaOKVmhSJXJSlld0KMModBw==",
    "CID": {
      "/": "bafy2bzacebrb6xetrbksnrfjbelxmbh5k4obz3elgyjnx2qx5bolos5al4v4c"
    }
  },
  "Signature": {
    "Type": 2,
    "Data": "sNKAyAtUc6fAXvqbwyDlikaqeVAgzfhWivHxeqxwlX+9W0SIMohiOFtPyxd5QsfbGeTut/EWOybKDJHrY4Ow0XRudgs+2eQMfWDJkFDOSEHK24+E3HGWw89QOL+jTu4n"
  },
  "CID": {
    "/": "bafy2bzacebrb6xetrbksnrfjbelxmbh5k4obz3elgyjnx2qx5bolos5al4v4c"
  }
}
{
  "Message": {
    "Version": 0,
    "To": "f057466",
    "From": "f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq",
    "Nonce": 399,
    "Value": "0",
    "GasLimit": 7739936,
    "GasFeeCap": "23420704945",
    "GasPremium": "100300",
    "Method": 11,
    "Params": "gYGDAgBEoCgqAQ==",
    "CID": {
      "/": "bafy2bzacebrudbkdlhmcf2hul65fddbm2t2fjxyqh2k7chlrpe4tziyts4l3u"
    }
  },
  "Signature": {
    "Type": 2,
    "Data": "j9bPKtpYaBdquUXnKXMnou7WefuOnKsU9m0brz1Hyqh40w/Xx4WxvOd1FdWTbvL5DkZbVX0BSpLU6OpFGTlY/3q5BdPcrvHTSdlQPd4zL8sMJpvLIIlZmgOMVsDYR6PQ"
  },
  "CID": {
    "/": "bafy2bzacebrudbkdlhmcf2hul65fddbm2t2fjxyqh2k7chlrpe4tziyts4l3u"
  }
}
{
  "Message": {
    "Version": 0,
    "To": "f057466",
    "From": "f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq",
    "Nonce": 400,
    "Value": "0",
    "GasLimit": 172613062,
    "GasFeeCap": "22628993587",
    "GasPremium": "99464",
    "Method": 5,
    "Params": "hQCBggBAgYIIWMCVjlD+c73fZElfsF7CiJJXtcDRte5Bvdn7LjKMo8uglBIQ0D8+70I/tw7iIlZ/9dGJ+p45I4gp41HO9I/PSbU6zl2XCAbflNtWo8Vowkop00JqnSnkt1oUrcpA6lEINjMRvhfG5z/wAdml8qFJBpPi8nRf8DlSFUFwx+FQ4CrH4U3d7c7UZmJBtT0ZYjufAOCoz8GTbnvKfbN5CSgEGIj2L17KwzHuBoheYRzMstb5FxX0153Ys/Qtu68bpZEsnSEaAAQwG1ggwY2AeiI/lPW095FAeRoQqK33TSembR/P4AsQ4p3FKio=",
    "CID": {
      "/": "bafy2bzacebf3jsvgjvvyspwo2tdcaiaolhkb7jaixftkk72ah4awrubzazb2a"
    }
  },
  "Signature": {
    "Type": 2,
    "Data": "hDTI9oPOkkZOkUmVlAWrJzdJGECn0HYJHjUO6fQ1Zz8olxXNJqcorL3PTbc640euAiBTqCYk5NRbTPgPkjuVysXftYZqVBSd3qFFkZGRYWk6oxfBeE7WqvBC+7n7v5/W"
  },
  "CID": {
    "/": "bafy2bzacebf3jsvgjvvyspwo2tdcaiaolhkb7jaixftkk72ah4awrubzazb2a"
  }
}
{
  "Message": {
    "Version": 0,
    "To": "f057466",
    "From": "f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq",
    "Nonce": 401,
    "Value": "160436963194133524",
    "GasLimit": 54367528,
    "GasFeeCap": "919666606",
    "GasPremium": "100629",
    "Method": 7,
    "Params": "ghjZWQeAtnIHWyad978IBWwtGeqUvgFlg6c+sjYyF0LJnYPBX064GZCDvwRRUYgK3GNmUKWbhN6ivEDhXWyZCQh12cWvfYJESfp4ET8eOilA0U9BTC6wU/4KZpZqi/aIwV8+2OZBC2Q+CK47ZrEPrDs1VNEi0hYKXIK0sVItVEa/l69bPPMLXC251jaIQhsoa9bcXYQKq8LQ0XOnf+S/MS2xRDbfq1HTGMsXzPpYK1fZZCgE1iXJWpdUTtls+gV9LR/0DSqDk+gEAIAQGzds1mh+mu58yruYNx+5d3SDDaHdIpqqILzEaUPCYm8cq1VoggZEkhCTgo1Ld6RwmZhDuZ4em+z301AoGlYD1PqPttWUOpZ61LTdjhUo13vKBswLu2FsnlE9FeSxMJDm9DcMxogcq5kOn1X1nZyY3385LFUG6yROFkdvARWpXBgFi7tmUkhnoZcwmXmeZGJYPRNQwsHS1jnIiBblfy/cxX8KWnLTnvMCUQgAVukp+rNry0M+xuItkBJOlDdQY6petW83OKM8RjZzOVOqL9wSriLSPKNS4QhGRRBdo/u4SYDl1KQXkndifBIFkQZ4q4LwmwWGUDGWGcwpz4YCAFL5r+0vdsIJSeqTFgoA/Pjpzx3tuT0y+LeheXRwEq2vfzF3f+QLmxx66m3PDq0FOFW528hiczlU5QIusDt24JMsyY/J3Smeb+jDzeCMpNI7x7C6Cosi14/H7TteRxwzoo9QnIolTQHtQ9x0/qEbvNDyOZdTwP4Lq9Oyc5rtqX2KfvIyw5AOj6HXUBfSWmwwziwnBfoE1jeqIDVm0mndv/mGGwHZj0opbudaqO6Pp3tNcQRJu36nc4gE00VJ7OilhjBN/JxVH8UHsZxcleTJLBxyBvVUI/6cwpFtDeeOBrB4gaYG/a59fl+G8Dp/58N5bPWYyGkuNk5ZoNLzr1/d/ZtXCfDxQnh4B9XYFnPks9gWLXQP8yYpOmO2dWw+SJSP6TXbpEmPmpBR07uRd8reQCo1OBcNwqpAgPkQYQV0rAPUx2SvFymgFyvQ59N4+lkuBmQ9VhUEaYomwCcR98poMIzD1leZC6i72/NKh/tko/ZgLT0sUsoj58LgKOjFA80j8Pl86g4JLCojfSwXdpfFREF09Cn8RMSGjYlNEjLZEYo+72F4XhM6zmO42xO31apaHQ1gbzp3WiB0hvkK6oxPtxt3pr1f13pnp8zE6/iXoAcRzmSCTjO6TiUqypTWcGrM7M1wnYkfGDajYPV+/qOA6O5FcmnA7nrPP6H5PudUtTqxYvk2/Pv1/ZTigI4GTqh35PJN0WrtEeF2s+qRsuT5rNtb9RHZq+4AaPwjmZCIl30CjYrLXkz33nADvBngjcxao2Wbx+7jFMnau46DcDbjWftPuMcKQZB2uJDhqy+dEYLCaGXUkW1gd3eTo7sesxK375XhG8IdjWN4IWGA57JjXrzcUKyjzIZHn1YFyUGhsGaqw29rze24S/TBshwdb7nHTD2MdmO+/3s8jHfdtq7e0XIAMISnpQTD33eLa8sXhYED9/l7nCZVvqHcToQIWOx6bN+TfDOfDEaBQi8Ea5KMeLIeX4l9xqbsp/aKunq+i7/VQ7UqWu3sl6gRDsLqHGLj3d8bAXvlcN3qROfayJlM2LMpVkjtS6Kk9NZCLH0OB9Fr6tei5WGaAg/hDJ8XPEUEEyMqhSC7KNpL9cN/73qo1p2vRYijn1hJbeLgyLQtro9bm+Zf7o94oh9Wxblo1GEXy6IDqalJ6jAY5Vkf6ZhI/BjUiOLjgfTLXxiSLZi/hOgk0yiezz0MghDLztI/FhSFXuVkpgCi+cDwPxFVDyc7vfspegFUxUTHJcKVK2qAqy2AV/g4NoL/Lf6rsc7cAC2up2CI5hS2eg4FJygmjriI6CYZPIJKIhkgVYfkculeGVJUioUBEEwm0QabjpQJ3T3al4qHiuLzkZtCqUF1vSGTGlamiGf6SATUaZTNjY33g6fhtN85TvakW7FB562bE/p5ucXWZ6eItpEIXetqn7J66rDl0iKHMEp810xqXxIUrQwDmTovqTyDLMYol9W5juiVqPeHij6eBjap6YXTqFYkzl8CZB7j2N5Frp7HY54OpRs+jl95FvmyrqVAky5NVn6FGomXhY415QDhAr2trrTivbVFNMECkJgXE5FI1XB0B9kQ/5ykM60eMYFWj4y7rODniPXKwAordyZTlwfNUcmsOEAqawSem25aINCw+6rRlHYlEMJ7SIfxCb8kL6pvW18r+U2byf1TDRHrMPMg20yxkfK/Dta+JQvEBM2R47E4rpHjCvNWu1ZGpreMokq+IuqxAmcKm/UmSEgOwVr9LLNypjvNSHwgzf4aZUkXsyhkgY9ZAAP5Wsun0F94mpx7EcAA3xgg5Hh0vOkpnGZ9xB3qG2RB6cnHr7BuXJerbjZ3B3voVgZFn1K5BzrvSFjvKpVHy5HqLQs4MdgZXJFdYWfa22p9bkeBaxwSPxNEXLiisbQluKYZCKt6uv5tBAATMiiQ1RQ/f8rpw0deizjcnIPXRSpQqtrZ+upz3IiNgTzy",
    "CID": {
      "/": "bafy2bzacecdzwlag5xjeavsdabhlaqy35bqkbydfuwq7fapbqxco5cj5acrcw"
    }
  },
  "Signature": {
    "Type": 2,
    "Data": "jsZghGc7PLooUjYJZuFRiOw10ZEzOI9V34lYoVlpe3vlVxyDcH0rc4dTKi6GenWBCjZfmOjSriO0ytdvWbo5xJRSTqIkL1Cvj/rpGWMXxCXehPr371aiuMX9R3MMnuYR"
  },
  "CID": {
    "/": "bafy2bzacecdzwlag5xjeavsdabhlaqy35bqkbydfuwq7fapbqxco5cj5acrcw"
  }
}

root@lotus-master:~# lotus mpool gas-perf
f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq	396	1427057383131457	210578390000000000.000000
f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq	397	6442132696608	992480000000000.000000
f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq	398	212530914342159675	190074980910000013312.000000
f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq	399	164146003988997376	212076694159999991808.000000
f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq	400	3524061034054953596	204159580580000006144.000000
f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq	401	5470949975112	1006290000000000.000000

**Expected behavior**
Normal submission of information

**Screenshots**
N/A

**Version (run `lotus version`):**

root@lotus-master:~# lotus version
Daemon:  1.2.1+git.d15d9b0fb.dirty+api1.0.0
Local: lotus version 1.2.1+git.aa278443d.dirty

**Additional context**

**Comment by urugang** [comment]
same here. 
my lotus report:
```
2020-11-28T17:48:27.765 INFO filcrypto::proofs::api > generate_data_commitment: start
2020-11-28T17:48:27.765 INFO filecoin_proofs::api::seal > compute_comm_d:start
2020-11-28T17:48:27.765 INFO filecoin_proofs::pieces > verifying 1 pieces
2020-11-28T17:48:27.765 INFO filecoin_proofs::api::seal > compute_comm_d:finish
2020-11-28T17:48:27.765 INFO filcrypto::proofs::api > generate_data_commitment: finish
2020-11-28T17:48:27.766+0800    WARN    vm      vm/runtime.go:331       Abortf: miner f02420 attempting to prove commit over 200 sectors in epoch
2020-11-28T17:48:27.766+0800    WARN    vm      vm/runtime.go:144       VM.Call failure: miner f02420 attempting to prove commit over 200 sectors in epoch (RetCode=32):
    github.com/filecoin-project/specs-actors/v2/actors/builtin/power.Actor.SubmitPoRepForBulkVerify.func1
        /home/userx/go/pkg/mod/github.com/filecoin-project/specs-actors/v2@v2.3.2/actors/builtin/power/power_actor.go:284
2020-11-28T17:48:27.766+0800    WARN    vm      vm/runtime.go:375       vmctx send failed: to: f04, method: 8: ret: [], err: miner f02420 attempting to prove commit over 200 sectors in epoch (RetCode=32)
2020-11-28T17:48:27.766+0800    WARN    vm      vm/runtime.go:331       Abortf: failed to submit proof for bulk verification
2020-11-28T17:48:27.766+0800    WARN    vm      vm/runtime.go:144       VM.Call failure: failed to submit proof for bulk verification (RetCode=32):
    github.com/filecoin-project/specs-actors/v2/actors/builtin.RequireSuccess
        /home/userx/go/pkg/mod/github.com/filecoin-project/specs-actors/v2@v2.3.2/actors/builtin/shared.go:49
2020-11-28T17:48:27.766+0800    WARN    vm      vm/vm.go:528    Send actor error        {"from": "f01088", "to": "f02420", "nonce": 275111, "method": "7", "height": "275017", "error": "failed to submit proof for
 bulk verification (RetCode=32):\n    github.com/filecoin-project/specs-actors/v2/actors/builtin.RequireSuccess\n        /home/userx/go/pkg/mod/github.com/filecoin-project/specs-actors/v2@v2.3.2/actors/builtin
/shared.go:49"}
2020-11-28T17:48:27.766+0800    WARN    rpc     go-jsonrpc@v0.1.2-0.20201008195726-68c6a2704e49/handler.go:241  error in RPC call to 'Filecoin.MpoolPushMessage': GasEstimateMessageGas error:
    github.com/filecoin-project/lotus/node/impl/full.(*MpoolAPI).MpoolPushMessage
        /home/userx/lwc/off-new/lotus/node/impl/full/mpool.go:157
  - estimating gas used:
    github.com/filecoin-project/lotus/node/impl/full.(*GasModule).GasEstimateMessageGas
        /home/userx/lwc/off-new/lotus/node/impl/full/gas.go:283
  - message execution failed: exit 32, reason: failed to submit proof for bulk verification (RetCode=32):
    github.com/filecoin-project/lotus/node/impl/full.gasEstimateGasLimit
        /home/userx/lwc/off-new/lotus/node/impl/full/gas.go:249

```

**Comment by urugang** [comment]
what can i do for this situation？

**Comment by urugang** [comment]
maybe gas estimated by miner for your first message is lower than estimated by mpool. my miner encounter this situation. 
you can follow issue #5044

**Comment by alingb** [comment]
> maybe gas estimated by miner for your first message is lower than estimated by mpool. my miner encounter this situation.
> you can follow issue #5044

@urugang I have used the instruction "lotus mpool replace --auto" to adjust the price more than 10 times, but I still can't submit it after the adjustment. The information was submitted successfully after several hours. In this case, windows post always fails. I'm not sure how far to adjust the price?

**Comment by jennijuju** [comment]
Looks like the messages are now landed on chain. You can manually increase the gas fees, make sure fee cap is > network base fee and gas premium is 25% higher than the old message.
