### ISSUE TITLE
Run lotus-storage-miner init error:unexpected EOF

### ISSUE THREAD

**Issue by linmuqin** [filecoin-project/lotus#505]
lotus-storage-miner/main.go:73	fetching proof parameters: fetching file /var/tmp/filecoin-proof-parameters/v14-stacked-proof-of-replication-d01cd22091627b721c60a3375b5219af653fb9f6928c70aa7400587d396bc07a.params: stream error: stream ID 1; PROTOCOL_ERROR; fetching file /var/tmp/filecoin-proof-parameters/v14-proof-of-spacetime-rational-c2ae2b440e693ee69fd6da9e85c4294c5c70c1a46d5785ca5f2a676d6cd4c8de.params: unexpected EOF; fetching file /var/tmp/filecoin-proof-parameters/v14-stacked-proof-of-replication-0c0b444c6f31d11c8e98003cc99a3b938db26b77a296d4253cda8945c234266d.params: unexpected EOF

**Comment by rosenjiang** [comment]
got similar error:
lotus-storage-miner/main.go:73  fetching proof parameters: fetching file /var/tmp/filecoin-proof-parameters/v14-stacked-proof-of-replication-967b11bb59be11b7dc6f2b627520ba450a3aa50846dbbf886cb8b735fe25c4e7.params: unexpected EOF; fetching file /var/tmp/filecoin-proof-parameters/v14-proof-of-spacetime-rational-b99f15d0bdaaf4ffb68b2ca72b69ea8d915f66a2a56f667430ad69d87aa5febd.params: stream error: stream ID 1; INTERNAL_ERROR

**Comment by rosenjiang** [comment]
how to resolve the error, can you give me some hints? thx

**Comment by Kubuxu** [comment]
@rosenjiang retry and retry. It is downloading 15GB total files (about 2GB) each from outside of china. I'm guessing chinese firewall interferes.

**Comment by rosenjiang** [comment]
> 
> 
> @rosenjiang retry and retry. It is downloading 15GB total files (about 2GB) each from outside of china. I'm guessing chinese firewall interferes.

thanks a lot.
