### ISSUE TITLE
Creating "tracked" addresses and tooling  for tracking miner account activities.

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#5065]
Miners brought up that it could be nice if there is a way to track where all the money goes. burned/minerfees/gas vs collateral, and eventually earnings for tax purpose. This is to create an address so that related operations can be easily tracked

The solution should be able to track a regular wallet account as well.

**Comment by Kubuxu** [comment]
So the idea is to have `lotus track add <address>` and all changes in value from/to that address (even sub-transactions and burns, everything) would get saved and could be exported instantly for audit purposes.
The system would work only after you enabled tracking for a given address.

**Comment by jennijuju** [comment]
feel like a tool can be built on top of lotus. might be a good grant or bounty option
