### ISSUE TITLE
Set retrieval price to 0 for storage miner causes the retrieval miner process to exit.

### ISSUE THREAD

**Issue by waynewyang** [filecoin-project/lotus#5071]
**Describe the bug**
When the retrieval miner sets the retrieval price to 0 through the command, the retrieval client to obtain data will cause the retrieval miner process to exit.

**To Reproduce**
1. The retrieval miner executes the command `lotus-miner retrieval-deals set-ask --price 0.000000000000000002` to set the price. At this time, the price is set to 0, but there is no prompt.
2. The retrieval client executes the command `lotus client retrieve` to obtain data. At this time, the storage server has set the price to 0, causing the retrieval miner process to exit.

**pected behavior**

1. Fail when the set price is 0.
2. Modify the code that caused the crash (as shown below).

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/25957795/100823596-71d9d100-348f-11eb-9144-1c3c9a0ef24e.png">

**reenshots**

**Version (run `lotus version`):**
lotus-miner version 1.2.1+git.d2da17c.dirty

**Comment by dirkmc** [comment]
Thanks for the bug report 👍 

> Modify the code that caused the crash (as shown below)

Was there something missing from the issue?

**Comment by waynewyang** [comment]
Yes, I added the screenshot

**Comment by TippyFlitsUK** [comment]
Hi @waynewyang 

Thanks for the report. I'm unable to reproduce the issue here with v1.15.1.

If you encounter the issue again in current release, please open a new ticket and provide new logs. 

Thanks !
