### ISSUE TITLE
deals without --verified-deal parameters are also regarded as Verified Deal

### ISSUE THREAD

**Issue by imageorbit** [filecoin-project/lotus#5073]
**Describe the bug**
deal without --verified-deal parameters are also regarded as Verified Deal

**To Reproduce**
1. Run 'lotus client deal <data CID> <miner> <price> <duration>' to submit deal
2. the parameters:
 --verified-deal              indicate that the deal counts towards verified client total (default: false)
So I didn't add it.  But the submitted deals are in status of 'verified'

**Expected behavior**
the submitted deals should be in status of 'not verified'

**Screenshots**
<img width="1338" alt="屏幕快照 2020-12-01 上午10 56 37" src="https://user-images.githubusercontent.com/72195144/100728436-8459f900-3402-11eb-9efd-2aa1c513f7eb.png">

**Version (run `lotus version`):**
lotus version 1.2.1+git.375b7a1c4.dirty

**Additional context**
I use this verified  address to send deal:

Your Datacap Allocation Request has been approved by the Notary
Message sent to Filecoin Network
bafy2bzaceaatcccylxlvavnxwzasajzhtitg3ncv57s3po35wru7dfym7oode
Address
f3vsg65k7fs365uueavmfnwcd2wzxq62vdhh7ydgws6oi2xliwjenyp75cg4ynxjez3i2migafpgv26iyee74q
Datacap Allocated
1 TiB

**Comment by magik6k** [comment]
Also appears as verified on-chain:
```
$ lotus state get-deal 1404983

{
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqnt46rt7ra73dhs4g5se46o57awrkoq7la34onvfwnwqx7u2a42aa"
    },
    "PieceSize": 17179869184,
    "VerifiedDeal": true,
    "Client": "f042612",
    "Provider": "f048135",
    "Label": "mAXCg5AIg4ZiigtmuGgio7hy6gdD4nBuEvkQdwF+CD8QNPa+ey5Q",
    "StartEpoch": 284472,
    "EndEpoch": 805791,
    "StoragePricePerEpoch": "8000000000",
    "ProviderCollateral": "5077138586530522",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorStartEpoch": -1,
    "LastUpdatedEpoch": -1,
    "SlashEpoch": -1
  }
}

```

**Comment by magik6k** [comment]
Were you using the interactive deal CLI (`lotus client deal` with no arguments), or did you call that command with arguments (data cid/miner/etc.?)

**Comment by magik6k** [comment]
Looks like the helptext for that command was wrong, fixed in https://github.com/filecoin-project/lotus/pull/5074
