### ISSUE TITLE
Canary deployment infra for Lotus nodes

### ISSUE THREAD

**Issue by nonsense** [filecoin-project/lotus#5078]
Following conversations with @raulk , @dineshshenoy , @magik6k and @dirkmc , here is an initial set of tasks to provide developers with functionality to trigger canary deployments of Lotus nodes.

Most of the work on this issue happens at https://github.com/filecoin-project/tweety

## Add Kubernetes helm apps for Lotus nodes
- [x] Add `lotus-fullnode-minimal` helm chart, which supports: a) creating a new node from snapshot (`install-snapshot` rpc), and b) updating an existing node with a different version of lotus (i.e. using the existing state) (`upgrade` rpc)

## Tweety - Go microservice
- [x] Add `create`, `delete` RPC - these install Lotus on a given host within a Kubernetes namespace.
- [x] Add `acquire`, `release` RPC - developers use these to claim a given deployment for test purposes and release it when they are done testing and evaluating.
- [x] Add `install-snapshot` and `upgrade` RPC - developers use these to install a specific version of Lotus on a given deployment that they've claimed

## Tweety - Kubernetes resources
- [x] Kubernetes deployment of Tweety (with all relevant permissions)

## Monitoring
- [ ] Update `lotus-fullnode-minimal` to export metrics to InfluxDB / Grafana
- [ ] Update RPC to submit an annotation when a command is triggered, so that it is clear when a specific deployment was updated/reset;

## Slack / Github bot
- [ ] Add command to update a specific lotus node from the cluster with a version of lotus based on that branch;
- [ ] Add command to stop a specific lotus node, clear its datadir, update it to a specific version and start sync from snapshot;

## Logs
- [x] Developers should have access to the cluster to review logs of nodes.
- [x] Logs should be forwarded to a centralised logging system such as https://logz.io if deemed necessary.

## Ingress / domain
- [x] Tweety service should be publicly exposed so that Slack / Github can trigger its RPCs.

## Access to developers
- [x] Developers should have access to the cluster (Dev Kubernetes cluster) to inspect their nodes

## Images for deployments
- [ ] ~~We need some kind of build process for PRs / commits, which it out-of-scope for the Tweety service. For now I use my personal `nonsens3` Docker Hub, but we probably want a Github Action building a Docker image for every commit of Lotus.
Being addressed at: https://github.com/filecoin-project/lotus/pull/5394~~  I want to make sure the images we use here are the same as what infra deploys, so I have a trigger for this here https://github.com/filecoin-project/lotus-infra/pull/311/files

**Comment by nonsense** [comment]
Having spoken with @travisperson and @ognots about this, here is a more concrete proposal on how to move forward with this functionality: https://docs.google.com/document/d/1ohYQvRpwwojjcaX35MucPesxGWHhmOWvUM2rNLf9Ubk/edit

cc @placer14

**Comment by nonsense** [comment]
Issue description has been updated to reflect the progress of this effort.

**Comment by arajasek** [comment]
@nonsense Is there a status update on this? Are you still owning it?

**Comment by nonsense** [comment]
@arajasek sorry for not updating this ticket. After the latest company re-org, I handed over this to the infra team. I believe @coryschwartz started working on this, but he is also working on a few other projects, so I am not sure what the status is right now.

@coryschwartz could you maybe give a short update here?

I think this ticket served its purpose to enumerate the features we wanted for the canaries in the first iteration, but we should probably close it now, and continue with more structured approach for the next iterations.

The work done for the first iteration is available at https://github.com/filecoin-project/tweety and this is probably a good placeholder to continue iterating and listing issues/feature requests with respect to the Canaries for Lotus.

**Comment by coryschwartz** [comment]
Thanks.

I'm going to try to get tweety wired in this week. The code is still a little messy and there are some simple ways to improve it, but we need something. In the mean time, I adjusted tweety to use the lotus helm charts and have it installing into the "canaries" namespace in mainnet-us-east-2-dev-eks

**Comment by jennijuju** [comment]
This ticket was hand off to the infra team. @coryschwartz is this ticket still be used for tracking the work? If not, could you please close it?

**Comment by coryschwartz** [comment]
Let me keep this open for now, sorry I haven't made too many updates here, but I can switch focus to this this week. 

Currently the tweety service is up and running.

To make it easier to submit jobs, I wrote a basic client that can deal with the authenticated request and submits jobs. There's a basic CI PR here https://github.com/filecoin-project/lotus/pull/6068/files. People can submit canaries to it now using the CLI. The only missing part of the integration is the docker build, which can be done easily enough, and I can take care of the rest of these requirements. I'll make sure the tick-boxes are updated with what is there currently, and I'll make a more comprehensive update to this ticket tomorrow.

**Comment by coryschwartz** [comment]
I just added a small improvement to allow canaries to have increased volume sizes (previously, they were being created with 10G volumes only, which is far too small) and I just makred that PR ready for review.

**Comment by jennijuju** [comment]
> I just added a small improvement to allow canaries to have increased volume sizes (previously, they were being created with 10G volumes only, which is far too small) and I just makred that PR ready for review.

thanks! which pr is it?
