### ISSUE TITLE
creat miner  fail  code 504

### ISSUE THREAD

**Issue by woshihanhaoniao** [filecoin-project/lotus#508]
I made this mistake when I created    

> https://lotus-faucet.kittyhawk.wtf

   my miner identity.

> 504 Gateway Time-out
> nginx/1.14.0 (Ubuntu)

**Comment by rosenjiang** [comment]
pls try again, it looks like dev team resolved it yesterday.

**Comment by woshihanhaoniao** [comment]
yes,the problem disappeared ,but, i creat miner still fail .
i use chrome or ie or firefox still fail.
Too Many Requests
problem for me  or lotus?
thanks !

**Comment by linmuqin** [comment]
I have the same problem，Have you solved it @rosenjiang

**Comment by ElonJelinek** [comment]
I have the same problem，Gateway Time-out and Too Many Requests.

**Comment by travisperson** [comment]
The timeout has been increased to 60m.

**Comment by ocean00** [comment]
I have the same problem，Gateway Time-out and Too Many Requests.

**Comment by zhang-dong-dong** [comment]
I have the same problem，Gateway Time-out and Too Many Requests. It seems that the problem still exists
