### ISSUE TITLE
Message stuck in mpool when the balance cannot cover gas cost + value to be transferred

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#5084]
For example, this [message](https://filfox.info/en/message/bafy2bzacedomthhn7i5xqnxjukw4wx6k45jm7drsphqk3ma7uhj3rasyt7sui) was stuck in mpool for a long time, where the value to transfer is 0.2FIL, the gas will be ~0.009 fil and the balance at time was 0.20483FIL

expected this message to be sent and fail, otherwise it blocks later messages as well

**Comment by jimpick** [comment]
Suggestion: Perhaps there could be some sort of a debugging tool in `lotus mpool` ... eg. `lotus mpool why` - that might suggest why the mpool is stuck - eg. limits too low, chain congestion, insufficient balance, etc.

**Comment by jimpick** [comment]
Another thought ... `lotus send` should calculate the expected gas price (+ maybe a little extra?) and not allow sending the entire balance with nothing left over to pay the gas (perhaps allow it with a --force option?).

**Comment by jennijuju** [comment]
`lotus mpool manage` exists and can resolve this issue
