### ISSUE TITLE
BaseFee Compute

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#5087]
Basefee should express the **change** of gasLimit,
The calculation should be as follows:
averageGasLimit=gasLimitUsed / noOfBlocks
parent_averageGasLimit=parent_gasLimitUsed / parent_noOfBlocks
delta=averageGasLimit/parent_averageGasLimit 
nextBaseFee=baseFee*delta
https://github.com/filecoin-project/lotus/blob/3196b2cfd577907d871cd5de662206407d906577/chain/store/basefee.go#L14-L46

**Comment by Kubuxu** [comment]
This does not have market properties we want out of base fee.
One critical property is that base fee regulates chain congestion. Meaning if the chain is overfilled the base fee should rise.
Please see numerous materials about EIP-1559: https://eips.ethereum.org/EIPS/eip-1559

**Comment by zgfzgf** [comment]
https://cryptonews.com/news/eip-1559-won-t-lower-high-ethereum-fees-on-its-own-professor-8492.htm

**Comment by zgfzgf** [comment]
hi:@Kubuxu 
proposal: where SysErrOutOfGas
gasLimit*gasCap - out.MinerTip  to burn
It can be understood as  out.Refund==0

**Comment by Kubuxu** [comment]
I don't see a benefit in it, as the majority of SysErrOutOfGas are issues with GasEstimation which needs to be fixed, not penalized.

**Comment by zgfzgf** [comment]
Now, I agree

**Comment by zgfzgf** [comment]
now proposal: ComputeGasOverestimationBurn 1.1 change to 1.25
or config 1.25 change to 1.1

**Comment by zgfzgf** [comment]
type node struct {
	// these may both be nil if the node is empty (a root node)
	links  []*link
	values []*cbg.Deferred
}
add  bitWidth uint

**Comment by Kubuxu** [comment]
1.1 is the target, we will keep on improving things until config can be brought down to 1.1

**Comment by jennijuju** [comment]
Seems like the original topic has been disclosed.
