### ISSUE TITLE
failed to fetch tipset from peer during hello: doRequest failed for single peer 12D3KooWScFR7385LTyR4zU1bYdzSiiAb5rnNABfVahPvVSzyTkR

### ISSUE THREAD

**Issue by Cristiyi** [filecoin-project/lotus#5089]
my louts branch is master
I  run command as 
lotus daemon --import-chain "my download mainnet file path"
and then get the error 
lotus daemon --import-chain <filename>
	hello	hello/hello.go:113	failed to fetch tipset from peer during hello: doRequest failed for single peer 12D3KooWScFR7385LTyR4zU1bYdzSiiAb5rnNABfVahPvVSzyTkR:
    github.com/filecoin-project/lotus/chain/exchange.(*client).doRequest
        /home/local/go/lotus/chain/exchange/client.go:142

which detail went wrong?please help

**Comment by galaxy0x** [comment]
我也遇到了这个问题 试了各种版本 加各种环境变量都不行 求解

**Comment by Reiers** [comment]
If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thanks!
