### ISSUE TITLE
Sealing P1,P2, once ticket expire, It must to do SectorTicket again before to do RetrySealPreCommit1

### ISSUE THREAD

**Issue by qiusugang** [filecoin-project/lotus#5093]
**Problem description:**
After Sealing P1,P2, once ticket expire, It must to do SectorTicket again before to do RetrySealPreCommit1, because old ticket already expired, even you finish this sector, it still expire. look below log:

lotus-miner version: 1.2.1

lotus-miner sectors status --log 57
Event Log:
0. 2020-12-01 09:45:19 +0800 CST:  [event;sealing.SectorStartCC]   {"User":{"ID":57,"SectorType":8,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}},"DealInfo":null}]}}
1. 2020-12-01 09:45:19 +0800 CST:  [event;sealing.SectorPacked]    {"User":{"FillerPieces":null}}
**2. 2020-12-01 09:45:20 +0800 CST:  [event;sealing.SectorTicket]    {"User":{"TicketValue":"0xDnH6L8mnQa99wPVUCjCMEG6F+sa5Sl3PW/WswxDio=","TicketEpoch":281790}}**
3. 2020-12-01 20:02:35 +0800 CST:  [event;sealing.SectorRestart]   {"User":{}}
4. 2020-12-01 20:02:35 +0800 CST:  [event;sealing.SectorSealPreCommit1Failed] {"User":{}}
   seal pre commit(1) failed: storage call error 101: worker restarted
5. 2020-12-01 20:03:35 +0800 CST:  [event;sealing.SectorRetrySealPreCommit1]  {"User":{}}
6. 2020-12-01 21:15:12 +0800 CST:  [event;sealing.SectorRestart]   {"User":{}}
7. 2020-12-01 21:27:15 +0800 CST:  [event;sealing.SectorRestart]   {"User":{}}
8. 2020-12-01 21:44:05 +0800 CST:  [event;sealing.SectorSealPreCommit1Failed] {"User":{}}
   seal pre commit(1) failed: storage call error 101: worker restarted
9. 2020-12-01 21:45:05 +0800 CST:  [event;sealing.SectorRetrySealPreCommit1]  {"User":{}}
10.2020-12-01 23:15:52 +0800 CST:  [event;sealing.SectorSealPreCommit1Failed] {"User":{}}
   seal pre commit(1) failed: storage call error 101: worker restarted
11.2020-12-01 23:16:52 +0800 CST:  [event;sealing.SectorRetrySealPreCommit1]  {"User":{}}
12.2020-12-02 09:10:41 +0800 CST:  [event;sealing.SectorPreCommit1]   {"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjFfMSIsImxhYmVscyI6eyJTdGFja2VkRHJnMzJHaUJWMSI6eyJsYWJlbHMiOlt7InBhdGgiOiIvaG9tZS9pcGZzLy5sb3R1c3dvcmtlci9jYWNoZS9zLXQwODU4OTktNTciLCJpZCI6ImxheWVyLTEiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9ob21lL2lwZnMvLmxvdHVzd29ya2VyL2NhY2hlL3MtdDA4NTg5OS01NyIsImlkIjoibGF5ZXItMiIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2hvbWUvaXBmcy8ubG90dXN3b3JrZXIvY2FjaGUvcy10MDg1ODk5LTU3IiwiaWQiOiJsYXllci0zIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9pcGZzLy5sb3R1c3dvcmtlci9jYWNoZS9zLXQwODU4OTktNTciLCJpZCI6ImxheWVyLTQiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9ob21lL2lwZnMvLmxvdHVzd29ya2VyL2NhY2hlL3MtdDA4NTg5OS01NyIsImlkIjoibGF5ZXItNSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2hvbWUvaXBmcy8ubG90dXN3b3JrZXIvY2FjaGUvcy10MDg1ODk5LTU3IiwiaWQiOiJsYXllci02Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9pcGZzLy5sb3R1c3dvcmtlci9jYWNoZS9zLXQwODU4OTktNTciLCJpZCI6ImxheWVyLTciLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9ob21lL2lwZnMvLmxvdHVzd29ya2VyL2NhY2hlL3MtdDA4NTg5OS01NyIsImlkIjoibGF5ZXItOCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2hvbWUvaXBmcy8ubG90dXN3b3JrZXIvY2FjaGUvcy10MDg1ODk5LTU3IiwiaWQiOiJsYXllci05Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9pcGZzLy5sb3R1c3dvcmtlci9jYWNoZS9zLXQwODU4OTktNTciLCJpZCI6ImxheWVyLTEwIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9pcGZzLy5sb3R1c3dvcmtlci9jYWNoZS9zLXQwODU4OTktNTciLCJpZCI6ImxheWVyLTExIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fV0sIl9oIjpudWxsfX0sImNvbmZpZyI6eyJwYXRoIjoiL2hvbWUvaXBmcy8ubG90dXN3b3JrZXIvY2FjaGUvcy10MDg1ODk5LTU3IiwiaWQiOiJ0cmVlLWQiLCJzaXplIjoyMTQ3NDgzNjQ3LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LCJjb21tX2QiOls3LDEyNiw5NSwyMjIsNTMsMTk3LDEwLDE0NywzLDE2NSw4MCw5LDIyNyw3MywxMzgsNzgsMTkwLDIyMywyNDMsMTU2LDY2LDE4MywxNiwxODMsNDgsMjE2LDIzNiwxMjIsMTk5LDE3NSwxNjYsNjJdfQ=="}}
13.2020-12-02 13:56:58 +0800 CST:  [event;sealing.SectorPreCommit2]   {"User":{"Sealed":{"/":"bagboea4b5abcbxzvnbueflwlues52xwa6txwapsqwqxfxqiw7lwegzpd3lg7x2y2"},"Unsealed":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}}
14.2020-12-02 13:56:58 +0800 CST:  [event;sealing.SectorSealPreCommit1Failed] {"User":{}}
   ticket expired: ticket expired: seal height: 282690, head: 286073
**15.2020-12-02 13:57:58 +0800 CST:  [event;sealing.SectorRetrySealPreCommit1]  {"User":{}}**

**Comment by shaodan** [comment]
Agree

**Comment by qiusugang** [comment]
The problem is sloved on Version 1.2.2
