### ISSUE TITLE
`wallet market withdraw` should use FundManager.Withdraw()

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/lotus#5100]
`wallet market withdraw` currently attempts to withdraw funds from the storage market actor regardless of how much is reserved by ongoing deals.

It should instead use [`FundManager.Withdraw()`](https://github.com/filecoin-project/lotus/blob/master/chain/market/fundmanager.go#L128) so as to not withdraw an amount that would cause deals to run into funding issues.

Probably it make sense to add a `WalletWithdraw(ctx, from, addr, amt)` API endpoint, implemented in https://github.com/filecoin-project/lotus/blob/master/node/impl/full/wallet.go

**Comment by hannahhoward** [comment]
Thumbs up on my end.
