### ISSUE TITLE
Sector upgrade fails after PC2 task

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#5106]
**Describe the problem**

I ran the command `lotus-miner sectors mark-for-upgrade 0` in order to upgrade sector 0  from CC to include deals.
After the PC2 task finished on sector 344, I received this error:

> sector 344 got error event sealing.SectorChainPreCommitFailed: pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 17, reason: failed to replace sector 0: sector 0 of partition 0, deadline 0 is terminated (RetCode=17)

My solution was to restart the miner so that sector 0 no longer was marked for upgrade:
`lotus-miner sectors list`

> ID   State            OnChain  Active  Expiration                      Deals  DealWeight  
> 0    Proving          YES      NO      1554348 (in 1 year 10 weeks)    CC  

**Sectors status**

######  --------

Event Log:
0.	2020-12-02 14:13:34 +0000 UTC:	[event;sealing.SectorStart]	{"User":{"ID":344,"SectorType":8}}
1.	2020-12-02 14:24:02 +0000 UTC:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqkelrqodxpo5xxjvxpafz24xf5mlbnlm2owccrzal3yqaarhesahy"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacedd2aedb5gbzojkiazvyrybvwkbpuotbvqncpy33cmwereauu3oru"},"DealID":1410392,"DealSchedule":{"StartEpoch":293887,"EndEpoch":817068},"KeepUnsealed":true}}}}
2.	2020-12-02 20:11:12 +0000 UTC:	[event;sealing.SectorRestart]	{"User":{}}
3.	2020-12-02 20:12:53 +0000 UTC:	[event;sealing.SectorStartPacking]	{"User":{}}
4.	2020-12-02 20:12:53 +0000 UTC:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
5.	2020-12-02 20:12:53 +0000 UTC:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"400394ABFJ//QUlFhBqzdcT4Y3++kl/vvCDA+dYTSXQ=","TicketEpoch":286885}}
6.	2020-12-03 00:04:16 +0000 UTC:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjFfMSIsImxhYmVscyI6eyJTdGFja2VkRHJnMzJHaUJWMSI6eyJsYWJlbHMiOlt7InBhdGgiOiIvTG90dXMvd29ya2VyL2NhY2hlL3MtdDAxMjc4LTM0NCIsImlkIjoibGF5ZXItMSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL0xvdHVzL3dvcmtlci9jYWNoZS9zLXQwMTI3OC0zNDQiLCJpZCI6ImxheWVyLTIiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9Mb3R1cy93b3JrZXIvY2FjaGUvcy10MDEyNzgtMzQ0IiwiaWQiOiJsYXllci0zIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvTG90dXMvd29ya2VyL2NhY2hlL3MtdDAxMjc4LTM0NCIsImlkIjoibGF5ZXItNCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL0xvdHVzL3dvcmtlci9jYWNoZS9zLXQwMTI3OC0zNDQiLCJpZCI6ImxheWVyLTUiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9Mb3R1cy93b3JrZXIvY2FjaGUvcy10MDEyNzgtMzQ0IiwiaWQiOiJsYXllci02Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvTG90dXMvd29ya2VyL2NhY2hlL3MtdDAxMjc4LTM0NCIsImlkIjoibGF5ZXItNyIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL0xvdHVzL3dvcmtlci9jYWNoZS9zLXQwMTI3OC0zNDQiLCJpZCI6ImxheWVyLTgiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9Mb3R1cy93b3JrZXIvY2FjaGUvcy10MDEyNzgtMzQ0IiwiaWQiOiJsYXllci05Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvTG90dXMvd29ya2VyL2NhY2hlL3MtdDAxMjc4LTM0NCIsImlkIjoibGF5ZXItMTAiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9Mb3R1cy93b3JrZXIvY2FjaGUvcy10MDEyNzgtMzQ0IiwiaWQiOiJsYXllci0xMSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N31dLCJfaCI6bnVsbH19LCJjb25maWciOnsicGF0aCI6Ii9Mb3R1cy93b3JrZXIvY2FjaGUvcy10MDEyNzgtMzQ0IiwiaWQiOiJ0cmVlLWQiLCJzaXplIjoyMTQ3NDgzNjQ3LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LCJjb21tX2QiOlsxNjIsNDYsNDgsMTEyLDIzOCwyNDcsMTE4LDI0Nyw3NywxMTAsMjQwLDIzLDU4LDIyOSwyMDMsMjE0LDQ0LDQ1LDkxLDUyLDIzNSw4LDgxLDIwMCwyMywxODgsNjQsMCwxMzcsMjAxLDMyLDMxXX0="}}
7.	2020-12-03 00:53:22 +0000 UTC:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcbmzqkrfkohe2n6yzwuzhkc3c536gqyf2jysaxttcfmqmbvlkn73i"},"Unsealed":{"/":"baga6ea4seaqkelrqodxpo5xxjvxpafz24xf5mlbnlm2owccrzal3yqaarhesahy"}}}
8.	2020-12-03 00:53:22 +0000 UTC:	[event;sealing.SectorChainPreCommitFailed]	{"User":{}}
	pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 17, reason: failed to replace sector 0: sector 0 of partition 0, deadline 0 is terminated (RetCode=17)
9.	2020-12-03 00:54:22 +0000 UTC:	[event;sealing.SectorRetryPreCommit]	{"User":{}}
10.	2020-12-03 00:54:22 +0000 UTC:	[event;sealing.SectorChainPreCommitFailed]	{"User":{}}
	pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 17, reason: failed to replace sector 0: sector 0 of partition 0, deadline 0 is terminated (RetCode=17)
11.	2020-12-03 00:55:22 +0000 UTC:	[event;sealing.SectorRetryPreCommit]	{"User":{}}
... (same error repeats)
92.	2020-12-03 01:35:23 +0000 UTC:	[event;sealing.SectorChainPreCommitFailed]	{"User":{}}
	pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 17, reason: failed to replace sector 0: sector 0 of partition 0, deadline 0 is terminated (RetCode=17)
93.	2020-12-03 01:42:08 +0000 UTC:	[event;sealing.SectorRestart]	{"User":{}}
94.	2020-12-03 01:43:08 +0000 UTC:	[event;sealing.SectorRetryPreCommit]	{"User":{}}
95.	2020-12-03 01:43:08 +0000 UTC:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzaceapar4xfnrfwztbyszcuptcfbuqqlwr2a5lmhljid5vmpeuzqkdfw"},"PreCommitDeposit":"109874799389382636","PreCommitInfo":{"SealProof":8,"SectorNumber":344,"SealedCID":{"/":"bagboea4b5abcbmzqkrfkohe2n6yzwuzhkc3c536gqyf2jysaxttcfmqmbvlkn73i"},"SealRandEpoch":286885,"DealIDs":[1410392],"Expiration":819948,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}

**Lotus miner logs**

This repeats every minute:

2020-12-03T01:03:22.037Z	INFO	sectors	storage-sealing/states_failed.go:26	PreCommitFailed(344), waiting 59.962766957s before retrying
2020-12-03T01:03:36.210Z	INFO	miner	miner/miner.go:384	Time delta between now and our mining base: 6s (nulls: 0)
2020-12-03T01:04:06.335Z	INFO	miner	miner/miner.go:384	Time delta between now and our mining base: 6s (nulls: 0)
2020-12-03T01:04:22.019Z	INFO	sectors	storage-sealing/upgrade_queue.go:71	replacing sector 0 with 344
2020-12-03T01:04:22.020Z	INFO	sectors	storage-sealing/states_sealing.go:270	submitting precommit for sector 344 (deposit: 999999984306749440): 
2020-12-03T01:04:22.023Z	WARN	sectors	storage-sealing/fsm.go:511	sector 344 got error event sealing.SectorChainPreCommitFailed: pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 17, reason: failed to replace sector 0: sector 0 of partition 0, deadline 0 is terminated (RetCode=17)
2020-12-03T01:04:22.041Z	INFO	sectors	storage-sealing/states_failed.go:26	PreCommitFailed(344), waiting 59.958727074s before retrying
2020-12-03T01:04:36.044Z	INFO	miner	miner/miner.go:384	Time delta between now and our mining base: 6s (nulls: 0)
2020-12-03T01:05:06.039Z	INFO	miner	miner/miner.go:384	Time delta between now and our mining base: 6s (nulls: 0)
2020-12-03T01:05:22.021Z	INFO	sectors	storage-sealing/upgrade_queue.go:71	replacing sector 0 with 344
2020-12-03T01:05:22.022Z	INFO	sectors	storage-sealing/states_sealing.go:270	submitting precommit for sector 344 (deposit: 999999984306749440): 
2020-12-03T01:05:22.026Z	WARN	sectors	storage-sealing/fsm.go:511	sector 344 got error event sealing.SectorChainPreCommitFailed: pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 17, reason: failed to replace sector 0: sector 0 of partition 0, deadline 0 is terminated (RetCode=17)

** Code modifications **

NONE

**Version**
Most recent Master
`lotus-miner version`
Daemon:  1.2.1+git.3196b2cfd+api1.0.0
Local: lotus-miner version 1.2.1+git.3196b2cfd

**Comment by Stebalien** [comment]
It appears that sector 0 was terminated (either manually, due to faults, or because it has been already upgraded). The sealing subsystem should detect this case and "unmark" for upgrade.

**Comment by stuberman** [comment]
I ran the upgrade attempt on sector, which had already been 'upgraded' as part of the original SpaceRace contest in order to qualify.
I will retry on a sector that is active when 1.5.0 releases and report on the results. Thanks!

**Comment by jennijuju** [comment]
I think this is resolved Please open a new ticket if you are running into this issue on the latest version of lotus!
