### ISSUE TITLE
max-fee cannot be set as a decimal

### ISSUE THREAD

**Issue by wenzhenxiang** [filecoin-project/lotus#5108]
**Describe the bug**
lotus mpool replace --auto --maxfee command, maxfee uint is FIL, but can't be set as a deciml

**To Reproduce**
see Screenshots

**Screenshots**
![image](https://user-images.githubusercontent.com/18651846/100978984-23efc680-357e-11eb-9dc7-236a8f47ea0a.png)

**Version (run `lotus version`):**
v1.2.1

**Comment by TippyFlitsUK** [comment]
Hi @wenzhenxiang 

Thanks for the report. The issue is outdated. 

If this is a issue in the current release - please open a new ticket.

Thank you !
