### ISSUE TITLE
CREATING STORAGE MINER:Too Many Requests

### ISSUE THREAD

**Issue by herodfb** [filecoin-project/lotus#511]
How long should I wait for next try?

**Comment by litianc** [comment]
the same issue

**Comment by ElonJelinek** [comment]
the same issue，from morning to now.

**Comment by ElecRoastChicken** [comment]
same issue

**Comment by whyrusleeping** [comment]
This is an issue with the faucet where we have a global rate limit implemented, one person spamming the faucet can cause this for everyone. A fix is in progress

**Comment by travisperson** [comment]
Closing to track in #517

**Comment by litianc** [comment]
Solved. Thanks
