### ISSUE TITLE
1.2.1 version sync error at height 166538/210769

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/lotus#5110]
1.2.1 version sync error at height 166538/210769
description：
map delete failed in node &{4294967295 [0xc1dbf0dcb0 0xc1dbf0dce0 0xc1dbf0dd10 0xc1dbf0dd40 0xc1dbf0dd70 0xc1dbf0dda0 0xc1dbf0ddd0 0xc1dbf0de00 0xc1dbf0de30 0xc1dbf0de60 0xc1dbf0de90 0xc1dbf0dec0 0xc1dbf0def0 0xc1dbf0dfb0 0xc1dbd50000 0xc1dbd50030 0xc1dbd50060 0xc1dbd50090 0xc1dbd500f0 0xc1dbd50120 0xc1dbd50150 0xc1dbd50180 0xc1dbd501b0 0xc1dbd501e0 0xc1dbd50210 0xc1dbd50240 0xc1dbd50270 0xc1dbd502a0 0xc1dbd502d0 0xc1dbd50300 0xc1dbd50330 0xc1dbd50360] 5 0xd681e0 0xc1fa6bd980} key ��: not found

Code location：
https://github.com/filecoin-project/lotus/blob/v1.2.1/chain/state/statetree.go#L347

Supplement：
key not found is f047745 & f065735

Version:  v1.2.1

**Comment by Reiers** [comment]
Hi @diwufeiwen 

Thanks for the report. 
Please upgrade Lotus: https://github.com/filecoin-project/lotus/releases/tag/v1.13.1

Closing ticket.

If you are still experiencing problems, open a new ticket or ask for help in our Discussions [forum.](https://github.com/filecoin-project/lotus/discussions)
