### ISSUE TITLE
Expose data transfer progress in the list-deals view for clients

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#5121]
It's helpful when monitoring deals to know much of the data transfer block has completed.  We have this information on the client side but are not exposing it in the UX.

Suggestion:  Append a percentage when doing a deal transfer.

Deal Transfer [56%]

**Comment by NSC-FIL** [comment]
This would be nice for the miners to see as well.

**Comment by dirkmc** [comment]
Should we show the percentage in list-deals or in list-transfers?

**Comment by NSC-FIL** [comment]
Can it be in both?  It's good for miners to know which are verified client deals to prioritize them if needed.

**Comment by dineshshenoy** [comment]
make it easier to cross-reference deals with transfers.
- add the transfer ID to list-deals
- add the deal ID to list-transfers
Prefer both - List transfers is used more for debugging.

Also add percentage in list-deals UX.

**Comment by dirkmc** [comment]
Outputting the transferred percentage is blocked by https://github.com/ipfs/go-graphsync/issues/126

**Comment by dineshshenoy** [comment]
Related to #5133
