### ISSUE TITLE
Lotus using extra 25% gas cap even no network congestion

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/lotus#5123]
**Describe the bug**
While my lotus send a message with a much higher gas cap than current basefee?  4.854533891 height 293155  nanoFIL  vs  2.025 at height 293165
message id
https://filfox.info/en/message/bafy2bzacebbqljqhfmm2zxx4z2ntyifm32rujylvpco3jdy5ij4hygukzhyp4
  Gas Fee Cap tip:
    4.854533891 nanoFIL 

Gas Premium tip :
    100,315 attoFIL 
 
Gas Limit tip:
    10,299,650 

Base fee history 
https://filfox.info/api/v1/stats/base-fee?duration=24h&samples=48
  {
    “height”: 293124,
    “timestamp”: 1607100120,
    “baseFee”: “2025893537"
  },
  {
    “height”: 293184,
    “timestamp”: 1607101920,
    “baseFee”: “2041509849"
  },

If this is the default behavior of lotus sending message mechanism, it might cause everyone increase gas fee unconsciously.

**To Reproduce**

1. open https://filfox.info/en/message/bafy2bzacebbqljqhfmm2zxx4z2ntyifm32rujylvpco3jdy5ij4hygukzhyp4
2. open https://filfox.info/api/v1/stats/base-fee?duration=24h&samples=48

**Expected behavior**
Gas cap should be equivalent or slightly higher than base fee.

**Screenshots**

**Version (run `lotus version`):**
lotus version
Daemon:  1.2.1+git.df66f48f6+api1.0.0

**Additional context**

**Comment by jennijuju** [comment]
as kubus mentioned, 25% is for gas limit overestimation not for gas fee cap. And gas estimation improvements are discussed in https://github.com/filecoin-project/specs-actors/issues/1319
