### ISSUE TITLE
Can not set-owner to a Ledger address, ERROR: mpool push: failed to sign message: Unexpected method

### ISSUE THREAD

**Issue by ohJohanZ** [filecoin-project/lotus#5127]
**Describe the bug**
Can not set-owner to a Ledger address, sign error with Ledger-Nano-X.

**To Reproduce**
$ lotus wallet new secp256k1-ledger
f1xxxxxxxxxxxxxxxxxxxxxxxxxxx

$ lotus-miner actor set-owner --really-do-it f1xxxxxxxxxxxxxxxxxxxxxxxxxxx
Propose Message CID: baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
ERROR: mpool push: failed to sign message: Unexpected method

**Comment by hyunmoon** [comment]
Happened to me as well.
https://filecoinproject.slack.com/archives/C0179RNEMU4/p1606998228055300?thread_ts=1606094007.397300&cid=C0179RNEMU4

**Comment by Kubuxu** [comment]
You need to enable `Expert Mode` on Ledger in Filecoin app.

**Comment by hyunmoon** [comment]
I did enable Export Mode.

**Comment by hyunmoon** [comment]
I did enable Export Mode.
But I'll try it one more time just in case and let you know.

**Comment by hyunmoon** [comment]
I did enable Export Mode per Magik6k's suggestion.
But I'll try it one more time just in case and let you know.

**Comment by hyunmoon** [comment]
Yes, not working even with export mode enabled.

**Comment by Stebalien** [comment]
@hyunmoon by "not working", do you mean that it failed with the same error, or a different error.

@ohJohanZ's initial issue was definitely not enabling Expert Mode. Unfortunately, changing the owner key requires two messages:

1. A message from the original owner to propose the change.
2. A message from the new owner to accept the change.

This ensures that target owner actually works.

Unfortunately, lotus attempts to _send_ this second confirmation message from the new owner address, which doesn't work because it's a multisig address. This command needs to be fixed to support multisig confirmations.

**Comment by hyunmoon** [comment]
@Stebalien Failed with the same error. It failed to process the second confirmation message.

**Comment by hyunmoon** [comment]
Changing the owner to a normal (non-Ledger) SECP key worked.

**Comment by hyunmoon** [comment]
But Ledger key isn't a multi-sig key, is it?
My suspicion is the Ledger filecoin app has trouble signing the change owner address message.
Am I correct?

**Comment by hyunmoon** [comment]
Failing to process the second message with `ERROR: mpool push: failed to sign message: Unexpected method`

**Comment by jennijuju** [comment]
> But Ledger key isn't a multi-sig key, is it?
> My suspicion is the Ledger filecoin app has trouble signing the change owner address message.
> Am I correct?

It’s not.

**Comment by Stebalien** [comment]
Ah, I'm sorry. I'm getting my issues confused (this one is about the ledger, not the multisig...).

This is a bug in the ledger code. For some reason, ledger only allows up to method number 7 in "expert" mode. It needs to allow _all methods_.

https://github.com/Zondax/ledger-filecoin/issues/65

**Comment by cwhiggins** [comment]
Is there an ETA on when Ledger will support owner address?

**Comment by arajasek** [comment]
Not really a Lotus issue, but let's keep this issue around to track. [This](https://github.com/Zondax/ledger-filecoin/pull/60) or some version of it needs to land.

**Comment by oricot** [comment]
I have a similar problem. My owner is on secp256k1-ledger wallet. I received the same error when I try do withdraw or set a different owner. Should I open a new issue?

**Comment by Araquiel** [comment]
try to change owner to ledger wallet and have a same error.
did you found solution?

**Comment by oricot** [comment]
I m able to withdraw but I don't think their is a solution to change the owner. I didn't try for a while

**Comment by Zboi04** [comment]
I just tried making my owner address a secp256k1-ledger as well, and I'm getting the same error as ohJohanZ. I'm surprised this issue has been open for this long.

**Comment by rjan90** [comment]
Hey!

I changed the owner-address of a storage provider to a Ledger-backed wallet (secp256k1-ledger) successfully on Lotus version `1.15.1-dev+2k+git.4c94ae45d` today. So closing this issue as it seems to have been fixed on newer versions.

I just followed the regular steps documented in the docs. [You can see the repro here: ](https://github.com/filecoin-project/lotus/issues/8459#issuecomment-1116592038)
