### ISSUE TITLE
The program logic is really bad, please improve it

### ISSUE THREAD

**Issue by qiusugang** [filecoin-project/lotus#5132]
**Describe the problem**
The system is really bad. Sectors with expired tickets keep retrying old processes.
The mpool blockage is so serious, why not expire.
When ticket was expired, the income that getting from owner for finish PreCommitSector is be destroyed, 
What shit logic is?

If miner and worker are running on the same computer, and files of different jobs need to be copied and copied, Cloud you design it to share the folder and files

lotus version: 1.2.2

**Comment by rjan90** [comment]
The issue with expired tickets / looping sectors has been fixed in newer versions of Lotus. I think this issue can be closed now! #rengjøring
