### ISSUE TITLE
The file size transferred during the deal is much larger than the actual file size.

### ISSUE THREAD

**Issue by chaopengliu** [filecoin-project/lotus#5133]
**Describe the bug**
The file size transferred during the deal is much larger than the actual file size.

![image](https://user-images.githubusercontent.com/75250193/101718976-4ed99d80-3add-11eb-9cd4-dcad7019dc61.png)

```
louts  client list-deals -v 
root@10-8-78-110:/data/deal_scripts# lc list-deals -v
Created          DealCid                                                      DealId   Provider  State                             On Chain?  Slashed?  PieceCID                                                          Size       Price              Duration  Verified  Message
Dec  8 22:16:12  bafyreifwbnnu7tzqccfrmevrwcxnx6ipoctwnzjtefymtiujimvjx7gtym  1436539  f085710   StorageDealAwaitingPreCommit      N          N         baga6ea4seaqicfrhqddzqb33kly4otpymvzfrviiiybe75aibpk5ud2xsoqpmey  1.984 GiB  0.000520669 FIL    520669    false
Dec  8 23:25:15  bafyreieo3v6k3qh7p3iig64kbsc5nfupoblfktnthslarhmdq45jhzwjaq  0        f023868   StorageDealCheckForAcceptance     N          N         baga6ea4seaqicfrhqddzqb33kly4otpymvzfrviiiybe75aibpk5ud2xsoqpmey  1.984 GiB  0.00001041416 FIL  520708    false     Provider state: StorageDealUnknown
Dec  9 10:46:25  bafyreifwgfmm2aq544cgmjjdcwnfqhjvcnmedcdjpogsjvjwzkikblroky  0        f034545   StorageDealClientTransferRestart  N          N         baga6ea4seaqicfrhqddzqb33kly4otpymvzfrviiiybe75aibpk5ud2xsoqpmey  1.984 GiB  0 FIL              522043    false
Dec  9 11:58:56  bafyreibhfr2pah3ha26yddngdgv22o4aktafq2ucghizfol6nqqe66a6pu  1439889  f044160   StorageDealAwaitingPreCommit      N          N         baga6ea4seaqicfrhqddzqb33kly4otpymvzfrviiiybe75aibpk5ud2xsoqpmey  1.984 GiB  0.000522358 FIL    522358    false
Dec  9 14:04:19  bafyreiekxxbplgm26xd6onihe3wk7wgrljrzoqjk3foike2na5w2pejto4  1438964  f063869   StorageDealAwaitingPreCommit      N          N         baga6ea4seaqdvheocjffe6nppls2i7yxfvxr52em43xg3drr4i4iknxbxxn2ugq  1.984 GiB  0 FIL              521264    false
Dec  9 17:56:25  bafyreibvi7hjqmtwlb7h35mkkbmvpe2zuntv5n3q72c2nyoddiysq4ffjy  0        f010493   StorageDealCheckForAcceptance     N          N         baga6ea4seaqdvheocjffe6nppls2i7yxfvxr52em43xg3drr4i4iknxbxxn2ugq  1.984 GiB  0.000521296 FIL    521296    false     Provider state: StorageDealReserveProviderFunds
```

**Comment by chaopengliu** [comment]
OS：root@10-8-78-110:/data/deal_scripts# cat /proc/version
Linux version 5.4.0-53-generic (buildd@lcy01-amd64-007) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020

Please let me know if you need to provide any other information.

**Comment by dirkmc** [comment]
Yesterday a [PR was merged](https://github.com/filecoin-project/lotus/pull/5150) into master so that `lotus client list-deals -v` will include the transfer channel ID, which you can cross-reference with `lotus client list-transfers`. To use it you will need to build lotus from source or wait till the next lotus release. This should make it easier to see which transfers apply to which deals.

Please let us know if you still see a discrepancy when comparing `list-deals` to `list-transfers` for a particular deal/transfer.

Note that `list-transfers` shows the padded size of the data transferred, whereas `list-data` shows the original (unpadded) size of the data.
https://docs.filecoin.io/store/lotus/store-data/#importing-data

**Comment by dirkmc** [comment]
May have the same underlying cause as https://github.com/filecoin-project/lotus/issues/5225

**Comment by dineshshenoy** [comment]
Blocked on https://github.com/ipfs/go-graphsync/issues/141

**Comment by dirkmc** [comment]
Resolved by https://github.com/filecoin-project/go-data-transfer/pull/140 (once it's been bubbled up to lotus)
