### ISSUE TITLE
Storage data of sector 0 is deleted when trying to remove a sector not exists

### ISSUE THREAD

**Issue by shaodan** [filecoin-project/lotus#5136]

**Comment by Reiers** [comment]
**How to remove it, after manually deleted a sector**

Create a dummy sector in your/storage/sector/path `touch s-t0xxxxx-sectornumb`
Restart the miner
`lotus-miner sectors remove --really-do-it <sectorNR>
`
After that: 
`lotus-miner sectors terminate --really-do-it <sectorNR>`

Closing Lotus issue ticket.
