### ISSUE TITLE
Log settings not persistent

### ISSUE THREAD

**Issue by shawnp0wers** [filecoin-project/lotus#5138]
**Describe the bug**
When adjusting which events appear in the log (using lotus-miner log set-level --system xxx), the settings only persist until the miner is restarted. If they could be set in config, or persisted in some other way, it would be ideal.

**To Reproduce**
Change log setting. Restart miner. Log settings revert to default.

**Expected behavior**
Settings stick, or another method to set desired log levels.

**Version (run `lotus version`):**
Daemon:  1.2.2+git.b13226bc2.dirty+api1.0.0
Local: lotus version 1.2.2+git.b13226bc2.dirty

**Comment by Kubuxu** [comment]
I would like to avoid adding a persistent state to logging it can be problematic.
We could consider adding per-system log level via env-vars.

**Comment by PatrickDeuse** [comment]
while on it: it would be great if we could not only set but query the levels of a system

**Comment by Stebalien** [comment]
See https://github.com/ipfs/go-log/issues/100.
