### ISSUE TITLE
markets: Confusing error message when cancelling transfer and other party unreachable

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/lotus#5146]
When a miner or client cancels a data transfer through the CLI:
`lotus-miner data-transfers cancel 12345`
`lotus client data-transfers cancel 12345`
They receive
`ERROR: Unable to send cancel message: context canceled`

The reason is that
- the local node tries to send a "cancel" message to the other party
- the other party to the data-transfer is not reachable

Note that the local data transfer (and deal) will still be cancelled, but the user sees the confusing error message.

The error message comes from go-data-transfer [CloseDataTransferChannel](https://github.com/filecoin-project/go-data-transfer/blob/0ecc981acf0ce509186e287390df1f991931e4fa/impl/impl.go#L268).

Suggested changes:
- Improve the error message to make it clearer that it happened because there was a timeout trying to reach the other party to send a cancel message
- Also indicate that the local data transfer was successfully moved to the cancel state. This change could be in go-data-transfer or in lotus CLI (or both)

**Comment by kernelogic** [comment]
When a deal is canceled, does the client get any penalty or the FIL is fully refunded?

**Comment by dirkmc** [comment]
When the client proposes a deal, if the client does not have enough funds for the deal in escrow (with the Storage Market Actor), lotus adds funds to escrow.

If the deal transfer is cancelled, the funds remain there until
- a subsequent deal makes use of the same funds
- the client withdraws the funds (eg with `lotus wallet market withdraw`)

**Comment by askender** [comment]
strange thing:
I run `lotus-miner data-transfers cancel theID` and return `ERROR: Unable to send cancel message: context canceled`
these IDs disappear in `lotus-miner data-transfers list`

when I restart lotus-miner,  I found these IDs appear in `lotus-miner data-transfers list` again.

This is maybe related to behavior in the issue https://github.com/filecoin-project/lotus/issues/5168

**Comment by dirkmc** [comment]
Once https://github.com/filecoin-project/lotus/issues/5038 has been released there will no longer be the message: `Message: other peer appears to have hung up. restart Channel`

Instead lotus will attempt the restart the channel automatically, and if it's not able to restart the channel after several attempts it will error out the deal.
