### ISSUE TITLE
the cost of message pooling is too high

### ISSUE THREAD

**Issue by alingb** [filecoin-project/lotus#5152]
**Describe the bug**

Now I have to pay a lot of miners' fees every day for my f099 account. The cost of message pool for 35 orders is about 5.25 fil, but the cost of these orders is not enough to meet the cost of message pool. Is the cost of message pooling too high?

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**
![dealMsg](https://user-images.githubusercontent.com/38687618/101566676-58de9c00-3a0a-11eb-921a-95e7bfb9e984.png)
![sectors](https://user-images.githubusercontent.com/38687618/101566680-5aa85f80-3a0a-11eb-83a8-fcbf2c30962f.png)

**Version (run `lotus version`):**

root@lotus-master:~# lotus version
Daemon:  1.2.1+git.aa278443d.dirty+api1.0.0
Local: lotus version 1.2.1+git.aa278443d.dirty

**Additional context**

**Comment by qiusugang** [comment]
**Yes, The cost is too high!** 
The project team need slove this problem. Is it because the bad architecture design of then mpool?

**Comment by rjan90** [comment]
Improvements to allow for higher chain-throughput has been put in place since this, and the BaseFee is much lower these days. This issue can probably be closed! #rengjøring
