### ISSUE TITLE
/usr/bin/ld: cannot find -lhwloc

### ISSUE THREAD

**Issue by oldkingclub** [filecoin-project/lotus#5155]
**Describe the bug**

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by raulk** [comment]
Please follow the installation instructions here: https://docs.filecoin.io/get-started/lotus/installation/#software-dependencies. They include the commands to install hwloc for your OS.

Reopen if issue persists.
