### ISSUE TITLE
storage deals error remove

### ISSUE THREAD

**Issue by alingb** [filecoin-project/lotus#5165]
**Describe the problem**

Yesterday, I paid a 5.25fil information pool fee and accepted the storage transaction. The sector was also sealed normally. However, after `ErrNotFound` in the sector submission today, the sector was removed. So now I paid for it, but nothing was done?

**Sectors status**

root@lotus-master:~# lotus-miner sectors status -log 395
SectorID:	395
Status:		Removed
CIDcommD:	baga6ea4seaqbgguce55rhzbjurzwgoo5hmudrxshitfg7t75ghlww6k7abgxwii
CIDcommR:	bagboea4b5abcaab5ytlhlgwcnh74qgqyslrz245wet2f774npwypwrm2otjmxbdm
Ticket:		3a4aa2d382248f7d62bd87d44cc4547d7af4688a94fb9e6f91db87284c44876c
TicketH:	304905
Seed:		03179e175b3f373c880446d9fe44f3ff05a616988c3a302195fe10f634f51c1f
SeedH:		307709
Precommit:	bafy2bzaceammayzmaobhcvtcgerufjwdzmz4xs64oc76g6nchieral3au3jxg
Commit:		bafy2bzacea4icizogq42nnrm6orvauwdmvftkfy5sskptcwajsdd75z32bi6w
…………
29.	2020-12-10 09:01:30 +0800 CST:	[event;sealing.SectorDealsExpired]	{"User":{}}
	sector deals expired: piece 0 (of 16) of sector 395 refers expired deal 1437178 - should start at 308316, head 308523
30.	2020-12-10 09:01:30 +0800 CST:	[event;sealing.SectorRemove]	{"User":{}}
31.	2020-12-10 09:01:43 +0800 CST:	[event;sealing.SectorRemoved]	{"User":{}}

root@lotus-master:~# lotus-miner sectors status -log 396
SectorID:	396
Status:		Removed
CIDcommD:	baga6ea4seaqil4x6zbtvqjcaqauumyhebj3jbimr3fmytcjodmtnejrro5bs2mi
CIDcommR:	bagboea4b5abcavdjehka2nj53mctmalukejnichs3b3hyv5hhy3na7pg634p7us2
Ticket:		2cf87167d056ff749f98d05f2194489b266532f44e9c8fdf27b870fa174d925e
TicketH:	304836
Seed:
SeedH:		0
Precommit:	bafy2bzacec7hrrjqhvahfzux7tik4rccqhvbmyaci34bx7nbmx22qvdkywvcm
Commit:		<nil>
Proof:
Deals:		[1437183 1437177 1437175 1437170 1437222 0 1437215 1437207 1437206 1437213 1437216 1437223 0 1437214 1437226 1437225 1437227 0 1437224 1437228]
…………
26.	2020-12-09 18:18:12 +0800 CST:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzacec7hrrjqhvahfzux7tik4rccqhvbmyaci34bx7nbmx22qvdkywvcm"},"PreCommitDeposit":"105094696502508682","PreCommitInfo":{"SealProof":8,"SectorNumber":396,"SealedCID":{"/":"bagboea4b5abcavdjehka2nj53mctmalukejnichs3b3hyv5hhy3na7pg634p7us2"},"SealRandEpoch":304836,"DealIDs":[1437183,1437177,1437175,1437170,1437222,1437215,1437207,1437206,1437213,1437216,1437223,1437214,1437226,1437225,1437227,1437224,1437228],"Expiration":867758,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}
27.	2020-12-10 00:30:25 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
28.	2020-12-10 01:02:30 +0800 CST:	[event;sealing.SectorChainPreCommitFailed]	{"User":{}}
	sector precommit failed: 16
29.	2020-12-10 01:02:30 +0800 CST:	[event;sealing.SectorDealsExpired]	{"User":{}}
	sector deals expired: piece 19 (of 20) of sector 396 refers expired deal 1437228 - should start at 307539, head 307565
30.	2020-12-10 01:02:30 +0800 CST:	[event;sealing.SectorRemove]	{"User":{}}
31.	2020-12-10 01:03:06 +0800 CST:	[event;sealing.SectorRemoved]	{"User":{}}

**Lotus miner logs**

Please go through the logs of your miner, and include screenshots of any error-like messages you find.

Alternatively please upload full log files and share a link here

Yesterday's sector list
![sectors](https://user-images.githubusercontent.com/38687618/101710627-d539b380-3acc-11eb-8876-568748c1c1d9.png)

Today's sector list
![sectors1](https://user-images.githubusercontent.com/38687618/101710655-e387cf80-3acc-11eb-9d3e-baf60b1a8544.png)

![proving](https://user-images.githubusercontent.com/38687618/101710754-18942200-3acd-11eb-9764-ef661fd13bfa.png)

**Lotus miner diagnostic info**

* lotus-miner diagnostic info `lotus-miner info all > allinfo`

** Code modifications **

If you have modified parts of lotus, please describe which areas were modified,
and the scope of those modifications

**Version**

root@lotus-master:~# lotus version
Daemon:  1.2.2+git.a999e4167+api1.0.0
Local: lotus version 1.2.2+git.a999e4167

**Comment by alingb** [comment]
Now I have purchased 150 fil pledge sectors. Now the amount of pledge sector and the amount in the local wallet are only 94.5 fil, and the information cost is 37%? This is unreasonable.

**Comment by Reiers** [comment]
Hi @alingb 

Thanks for the report. The issue you are experiencing lies elsewhere and is outdated.

You need to Terminate the sector:
`lotus-miner sectors terminate --really-do-it <sectorNR>
`

Closing Lotus issue ticket.
