### ISSUE TITLE
ChainGetTipSetByHeight   “looking for tipset with height greater than start point”

### ISSUE THREAD

**Issue by togiter** [filecoin-project/lotus#5170]
How to solve this problem?
Use the API  `cli.ChainGetTipSetByHeight(context.Background(), abi.ChainEpoch(blockNo), types.EmptyTSK)` to get the same error。
<img width="1666" alt="WeChat6b2944fd2ec05ad4f88d2138b8af8c91" src="https://user-images.githubusercontent.com/18685332/101759867-1950a680-3b15-11eb-9fc0-c5b1f1bce5dc.png">

**Comment by togiter** [comment]
node error

**Comment by randyortonx** [comment]
set latest chain head  block cid
