### ISSUE TITLE
When lotus-miner data-transfers list gets too long, miner stops spawning WaitDeals sectors.

### ISSUE THREAD

**Issue by NSC-FIL** [filecoin-project/lotus#5184]
**Describe the bug**
When too many (in my case 500+) deals are stuck in the transferring state (i.e. lotus-miner data-transfer shows too many lines with deals "Ongoing" but "Initiated" = N), the miner will stop accepting deals because no WaitDeals sectors are spawned to accept them.

**To Reproduce**
1. Flood the miner with deals that will not transfer or stop during transfer
2. Check the lotus-miner sectors list stops creating WaitDeals sectors

Expected behavior**
Miner should be able to handle deals and spawn WaitDeals sectors to accept deals regardless of how many ongoing deals are stuck in transferring.

**Screenshots**

**Version (run `lotus version`):**
lotus version 1.2.2+git.93d26195f
**Additional context**

**Comment by dirkmc** [comment]
Thanks for the bug report.

Note that as a workaround it may help to cancel deals that are stuck in transferring:
`lotus-miner data-transfers cancel <transfer ID>

**Comment by Reiers** [comment]
This should be fixed in newer versions of lotus. 
If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help
