### ISSUE TITLE
lotus-miner calculates window post without sectors in deadline - master branch

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#5186]
**Describe the bug**
the miner keeps on calculating wdPosts even if there is not a single sector in the deadline

**To Reproduce**
no idea

**Expected behavior**
to not do that

**Screenshots**
{"level":"info","ts":"2020-12-10T08:10:18.300Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":1337.339468066}
{"level":"info","ts":"2020-12-10T08:30:46.574Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":826.304097265}
{"level":"info","ts":"2020-12-10T09:00:34.905Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":814.567201266}

-------------------------------- 3

{"level":"info","ts":"2020-12-11T08:10:51.715Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":1430.218346623}
{"level":"info","ts":"2020-12-11T08:31:09.135Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":848.890973183}
{"level":"info","ts":"2020-12-11T09:01:32.559Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":872.184586644}

------------------------------3

{"level":"info","ts":"2020-12-12T08:09:10.303Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":1328.367132083}
{"level":"info","ts":"2020-12-12T08:30:47.466Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":827.007032971}
{"level":"info","ts":"2020-12-12T09:01:11.923Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":851.567741145}

--------------------------------3

{"level":"info","ts":"2020-12-13T08:37:09.663Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":3006.973872956}
{"level":"info","ts":"2020-12-13T08:50:43.802Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":1423.439303576}
{"level":"info","ts":"2020-12-13T09:04:17.445Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":1607.146109402}
{"level":"info","ts":"2020-12-13T09:18:09.292Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":1628.85618541}
{"level":"info","ts":"2020-12-13T09:31:19.599Z","logger":"storageminer","caller":"storage/wdpost_run.go:594","msg":"computing window post","batch":0,"elapsed":1609.152057059}

----------------------------------5

for today there are more than 3 posts calculated. thats totally wrong. not sure what else did go wrong - but it missed the major post because it was too slow.

deadlines with sectors: 0 1 2 

**Version (run `lotus version`):**

2 days ago master

**Additional context**

there are 3 deadlines with sectors. after the missed post it was just going on and going on an... yeah then i killed it and rolled back to 1.2.2

**Comment by PatrickDeuse** [comment]
1.2.2 no problems. seems to have been the master branch checkout
