### ISSUE TITLE
Filecoin cannot be sent to another address

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#5187]
Filecoin cannot be sent to another address. Please help me.

$ lotus mpool replace --pending --local
{
  "Message": {
    "Version": 0,
    "To": "f3wsgs6xgaevotif22qobqkwklbrcuqgakigxudrjortkvkmyniv3dy7c4ipl6dnut5p6vpgpjwncmc4knsf6a",
    "From": "f3rqtn4dijj3hoajnecrirw446db4w7d5njg6vr7dd66lb5vg2voe7kdsfxw5gtvrohkszckj4ehf6zlce4iaq",
    "Nonce": 7,
    "Value": "2800000000000000000",
    "GasLimit": 592085,
    "GasFeeCap": "46967012427",
    "GasPremium": "130894",
    "Method": 0,
    "Params": null,
    "CID": {
      "/": "bafy2bzacedevzd3qawtivc5mosty66gdyycply7hn7ygce6eeyp75tcrhpupu"
    }
  },
  "Signature": {
    "Type": 2,
    "Data": "gJ0IuAUHPG6/DI/ZHUFFvkYPkbEErcfMTaSgbTbL4x49XsXwJ6sDgGJdiJtLWCV4FuRggDRMb5j95LwdpyCC6ZbNVPr5N2TkqYXKOq7o24W7TK8yddB1QjAVW                                                                                                                                         1cah2ve"
  },
  "CID": {
    "/": "bafy2bzacedevzd3qawtivc5mosty66gdyycply7hn7ygce6eeyp75tcrhpupu"
  }
}

Daemon:  1.2.2+git.b13226bc2+api1.0.0
Local: lotus version 1.2.2+git.b13226bc2

**Comment by hsjw12** [comment]
Filecoins from other nodes cannot be sent to other accounts.
What is the problem? Please help me.

$lotus mpool pending --local
{
  "Message": {
    "Version": 0,
    "To": "f3qa7tvuwbhgoxswfgcxemgr4xl3ui54gefhyoyb265tv266aqwb2yvnqjjrjbi2cjsl4dtq5vmwzf5zduqkra",
    "From": "f3vfdn3iwypb3zcloi4oalc5qnxin5ecdlfhtgby3paunc53q4u2qprjnscrxvsng2c4dzzwj5fpvdyhfdoztq",
    "Nonce": 39,
    "Value": "1683000000000000000",
    "GasLimit": 593710,
    "GasFeeCap": "43416383466",
    "GasPremium": "103636",
    "Method": 0,
    "Params": null,
    "CID": {
      "/": "bafy2bzacedwi223veb554ewvizftfvufpc7lwpsvgveqs4oqzsncenkidcyvo"
    }
  },
  "Signature": {
    "Type": 2,
    "Data": "rmxsmIclwmtuvBYTbrdJ8qRm0V45kKo3v03ahfUHWMQ+7bP0UT2jFBi0rz5uLPp2DlcNpywVkM2oEzifXTJ/8y8i/Vi2ihxOhUgSYIRP0hoK+TlkvlwmnWRsaRK8LaGQ"
  },
  "CID": {
    "/": "bafy2bzacedwi223veb554ewvizftfvufpc7lwpsvgveqs4oqzsncenkidcyvo"
  }
}
{
  "Message": {
    "Version": 0,
    "To": "f3qa7tvuwbhgoxswfgcxemgr4xl3ui54gefhyoyb265tv266aqwb2yvnqjjrjbi2cjsl4dtq5vmwzf5zduqkra",
    "From": "f3xeym4wjr4zwxox3zweowpja6kwjiyke3okcul4wbqmjjxpeuulwpapjwwjfqauvxsxujewja5ohp5ltzve7q",
    "Nonce": 9,
    "Value": "1478800000000000000",
    "GasLimit": 592085,
    "GasFeeCap": "43055361854",
    "GasPremium": "103828",
    "Method": 0,
    "Params": null,
    "CID": {
      "/": "bafy2bzacedvl7c5zhvcbvimftbl6kizeuxpzcf7j3c7i7yn4aqmi5jgy23b5q"
    }
  },
  "Signature": {
    "Type": 2,
    "Data": "o+ysPP/T8JlwokpYoz9D8hlan0ItsIZSOb1WWX/cZSiwvJDYQ6d7Hp2ZSev5H3jgAai5i/Xtlzb53++oqGAT32KDxjrwit8u126zWFWxy027WOD7qO6iJIw1EbGIr7uD"
  },
  "CID": {
    "/": "bafy2bzacedvl7c5zhvcbvimftbl6kizeuxpzcf7j3c7i7yn4aqmi5jgy23b5q"
  }
}

Daemon:  1.2.2+git.b13226bc2+api1.0.0
Local: lotus version 1.2.2+git.b13226bc2

**Comment by hsjw12** [comment]
Even if we run the command like this(lotus mpool replace --auto), the result is the same

lotus mpool replace --auto f3vfdn3iwypb3zcloi4oalc5qnxin5ecdlfhtgby3paunc53q4u2qprjnscrxvsng2c4dzzwj5fpvdyhfdoztq 39

**Comment by rjan90** [comment]
To replace the message:

- Get the current base-fee: lotus chain head | xargs lotus chain getblock | jq -r .ParentBaseFee

- lotus mpool replace --gas-premium <previous GasPremium * 1.25> --gas-feecap <Output of 1.> <address> <nonce> 

This issue can probably be closed! #rengjøring
