### ISSUE TITLE
lotus miner init stucked at "Waiting for message"

### ISSUE THREAD

**Issue by hysci** [filecoin-project/lotus#5198]
**Describe the bug**
The command "lotus-miner init --sector-size=32GiB" stucked at Waiting for message bafy2bzaceck6lcczfj4wisulcggab5ew7rclytwjlb3vgt6seqsujw4wyc: 
```
INFO    main    lotus-storage-miner/init.go:166 Checking if repo exists
INFO    main    lotus-storage-miner/init.go:182 Checking full node version
INFO    main    lotus-storage-miner/init.go:193 Initializing repo
INFO    repo    repo/fsrepo.go:121      Initializing repo at '/vmshare/appdata/lotus/miner'
INFO    main    lotus-storage-miner/init.go:407 Initializing libp2p identity
INFO    badger  v2@v2.2007.2/levels.go:183      All 0 tables opened in 0s
INFO    badger  v2@v2.2007.2/levels.go:183      All 0 tables opened in 0s
INFO    main    lotus-storage-miner/init.go:589 Waiting for message: bafy2bzaceck6lcczfj4wisulcggab5ew7rclytwjlb3vgt6seqsujw4wyc
```

I've waited for an hour, there is no more message any more.

**To Reproduce**
1. Run `lotus daemon&`
2. `lotus sync wait`, wait until the sychrnoization finished 
3. `lotus wallet new bls`， send 1FIL to the address
4. Run `lotus-miner init --sector-size=32GiB --no-local-storage&`

**Expected behavior**
The init process should be finished normally.

**Screenshots**
![figure](https://user-images.githubusercontent.com/6468488/102290541-39042680-3f7c-11eb-9665-55dd5b2a2e5c.png)

**Version (run `lotus version`):**
lotus version 1.2.2+git.65b921c62

**Additional context**
lotus daemon looks normal, the log messages are:

```
INFO filcrypto::proofs::api > verify_seal: finish
INFO filecoin_proofs::api::seal > verify_seal:finish: SectorId(102513)
INFO filcrypto::proofs::api > verify_seal: finish
INFO filecoin_proofs::api::seal > verify_seal:finish: SectorId(338390)
INFO filcrypto::proofs::api > verify_seal: finish
INFO filecoin_proofs::api::seal > verify_seal:finish: SectorId(338643)
INFO filcrypto::proofs::api > verify_seal: finish
INFO filecoin_proofs::api::seal > verify_seal:finish: SectorId(102159)
INFO filcrypto::proofs::api > verify_seal: finish
INFO filecoin_proofs::api::seal > verify_seal:finish: SectorId(96035)
INFO filcrypto::proofs::api > verify_seal: finish
INFO filcrypto::proofs::api > verify_seal: start
INFO filecoin_proofs::api::seal > verify_seal:start: SectorId(504945)
INFO filecoin_proofs::caches > trying parameters memory cache for: STACKED[34359738368]-verifying-key
INFO filecoin_proofs::caches > found params in memory cache for STACKED[34359738368]-verifying-key
INFO filecoin_proofs::api::seal > got verifying key (34359738368) while verifying seal
INFO filecoin_proofs::api::seal > verify_seal:finish: SectorId(349238)
INFO filcrypto::proofs::api > verify_seal: finish
INFO filcrypto::proofs::api > verify_seal: start
INFO filecoin_proofs::api::seal > verify_seal:start: SectorId(99814)
INFO filecoin_proofs::caches > trying parameters memory cache for: STACKED[34359738368]-verifying-key
INFO filecoin_proofs::caches > found params in memory cache for STACKED[34359738368]-verifying-key
INFO filecoin_proofs::api::seal > got verifying key (34359738368) while verifying seal
```

lotus daemon and lotus-miner init were tested on the same host with a default configuration, the port opened as expected.
```
tcp        0      0 0.0.0.0:39595           0.0.0.0:*               LISTEN      907/lotus
tcp        0      0 127.0.0.1:1234          0.0.0.0:*               LISTEN      907/lotus
tcp6       0      0 :::40051                :::*                    LISTEN      907/lotus
```

The environment:
```
export FIL_PROOFS_PARAMETER_CACHE=/vmshare/appdata/lotus/proofs
export FIL_PROOFS_PARENT_CACHE=/vmshare/appdata/lotus/cache/proofs
export BELLMAN_CPU_UTILIZATION=0.875
export FIL_PROOFS_MAXIMIZE_CACHING=1
export FIL_PROOFS_USE_GPU_COLUMN_BUILDER=0 # when having GPU
export FIL_PROOFS_USE_GPU_TREE_BUILDER=0   # when having GPU
export FIL_PROOFS_USE_MULTICORE_SDR=1
export TMPDIR=/vmshare/appdata/lotus/cache/tmpdir
export LOTUS_PATH=/vmshare/appdata/lotus/node
export LOTUS_MINER_PATH=/vmshare/appdata/lotus/miner
export LOTUS_WORKER_PATH=/vmshare/appdata/lotus/worker
source "$HOME/.cargo/env"
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
export PATH=/usr/local/go/bin:$PATH
export GOROOT=/usr/local/go
export GOPATH=/vmshare/appdata/gopath
go env -w GO111MODULE=on

export RUSTFLAGS="-C target-cpu=native -g"
export FFI_BUILD_FROM_SOURCE=1
export RUST_BACKTRACE=full
export RUST_LOG=debug
export FIL_PROOFS_SDR_PARENTS_CACHE_SIZE=1073741824
export FULLNODE_API_INFO=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.h_cRjCLv0yeJMo95HTlguVh_2WYON1-bcZB32kj8:/ip4/127.0.0.1/tcp/1234/http
```

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.h_cRjCLv0yeJMo95HTlguVh_2WYON1-bcZB32kj8` is got from token file and `/ip4/127.0.0.1/tcp/1234/http` is obtained from api file in LOTUS_PATH.

**Comment by wordpy** [comment]
Almost the same here.
BOTH owner and worker addresses has > 1 FIL.  `lotus sync wait` finished/

```
lotus-miner init --owner=f3we3*****uiya  --worker=f3ui******jd5ga  --sector-size=32GiB
    Worker: 711; Base: 332070; Target: 332070 (diff: 0)
    State: complete; Current Epoch: 332070; Todo: 0

    Done!
```
also tried different variations:
```
lotus-miner init --owner=f3we3*****uiya  --worker=f3ui******jd5ga  --sector-size=32GiB  --no-local-storage
    Worker: 46; Base: 331972; Target: 331974 (diff: 2)
    State: message sync; Current Epoch: 331974; Todo: 0
    Validated 0 messages (0 per second)
    Done!
```

tail miner.log
```
{"level":"info","ts":"2020-12-18T05:15:32.379Z","logger":"main","caller":"lotus-storage-miner/init.go:699","msg":"Pushed CreateMiner message: bafy2bzacedzsluzykmixszrto2bhkehtzsji7m5ojgps7uvvqj2nwnnaaefqu"}
{"level":"info","ts":"2020-12-18T05:15:32.379Z","logger":"main","caller":"lotus-storage-miner/init.go:700","msg":"Waiting for confirmation"}
```

All attempts hang at the above "Waiting for confirmation" miner.log for hours, until I pressed 'Control-c', and miner.log returns:
```
{"level":"error","ts":"2020-12-18T05:13:46.217Z","logger":"main","caller":"lotus-storage-miner/init.go:253","msg":"Failed to initialize lotus-miner: creating miner failed:\n    main.storageMinerInit\n        ***/lotus/cmd/lotus-storage-miner/init.go:524\n  - waiting for createMiner message:\n    main.createStorageMiner\n        ***/lotus/cmd/lotus-storage-miner/init.go:704\n  - context canceled"}
{"level":"info","ts":"2020-12-18T05:13:46.217Z","logger":"main","caller":"lotus-storage-miner/init.go:258","msg":"Cleaning up ***/.lotusminer/ after attempt..."}
```

I have 2 miners machines both stuck at "Waiting for confirmation".  Tried searching, other than source code of `lotus-storage-miner/init.go`, couldn't find what `lotus-miner init` has been waiting for.

**Comment by wordpy** [comment]
Finally got a New miners address, after > dozen tries. Each try of "lotus-miner init" costs ~0.0055 FIL?!
Maybe "lotus-miner init" was hanging due to the filecoin outage during the last

**Comment by blueforest-pro** [comment]
the same happened to me ,```lotus-storage-miner/init.go:700 Waiting for confirmation``` ,I am waiting for 3 days ,have no progress，Why??????

**Comment by killelder** [comment]
I already wait 900 epochs, still got  

> lotus-storage-miner/init.go:700 Waiting for confirmation

I have 2 FIL in my wallet

**Comment by huangmeibao** [comment]
I have the same problem. Has anyone solved it

lotus-storage-miner/init.go:700 Waiting for confirmation

**Comment by cryptocamtech** [comment]
I'm seeing the same as the above. Creating a miner appears to be a difficult problem.

**Comment by killelder** [comment]
Last night, my miner-init all approved
now I got 18 miners

**Comment by cryptocamtech** [comment]
> Last night, my miner-init all approved
> now I got 18 miners

You've gotta be kidding me. I have 14 of them now.

**Comment by SZarella** [comment]
I have this same problem today with filecoin.
`2021-02-08T16:20:52.768-0600    INFO    main    lotus-storage-miner/init.go:701 Waiting for confirmation`

Everything is successful above this.
![image](https://user-images.githubusercontent.com/34774267/107289579-df275680-6a2a-11eb-9554-b75de7b85663.png)

This is a local miner with local node that is in sync as I can get balances on all (4) of my wallets including the BLS and "Coinbase" type.

**Comment by cryptocamtech** [comment]
I've tried around 20 times without success. I've got 3 other block chains to work - FileCoin has been the most challenging so far and ready to sell my FileCoin and move on. Not a good start for your community guys.

**Comment by SZarella** [comment]
Same, I got my Prysm beacon ready to launch soon as I buy 32 ETH at
sub-$1000/coin. My original purpose for the AMD Ryzen 3950X was to reach
this point in the FileCoin game with mining. I burn through the ETH
blockchain in about 16 hours when it's slow. We'll see if I get lucky day
after day.

**Comment by Reiers** [comment]
Hi 

Thanks for the report. 

Solution to the issue can be found here: https://lotus.filecoin.io/docs/storage-providers/message-pool/#replacing-messages-in-the-pool

Please upgrade Lotus: https://github.com/filecoin-project/lotus/releases/tag/v1.13.1

Closing ticket.

If you are still experiencing problems, open a new ticket or ask in our Discussions [forum.](https://github.com/filecoin-project/lotus/discussions)
