### ISSUE TITLE
"lotus-miner backup"  processes path incorrectly

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#5199]
**Describe the bug**
when running `lotus-miner backup ./path/to/file` the lotus-miner messes up the path

**To Reproduce**
1. `export LOTUS_BACKUP_BASE_PATH=/some/prefix/path/to` in the miner processes environment
2.  `cd /some/prefix`
3. ` lotus-miner backup ./path/to/file`

**Expected behavior**
being able to detect that ./path/to/file is in /some/prefix

**Screenshots**
```
filecoin [~]$ pwd
/opt/filecoin
filecoin [~]$lotus-miner backup ./calibration/backup/miner_bu.car                    
ERROR: backup file name (/calibration/backup/miner_bu.car) must be inside base path (/opt/filecoin/calibration/backup)
```

**Version (run `lotus version`):**
Local: lotus-miner version 1.2.1+git.fc8424d73

lotus-miner running with filecoin:filecoin via systemd. $HOME is /opt/filecoin for the filecoin user.

**Comment by PatrickDeuse** [comment]
it looks like ./ is not expanded to the full path before handing it over to the lotus-miner process. looks like it's just cutting the . off the beginning and passes the rest to the API - that then in return complains, rightfully

**Comment by PatrickDeuse** [comment]
exists in lotus-miner version 1.2.2+git.93d26195f

**Comment by TippyFlitsUK** [comment]
Hi @f8-ptrk 

Thanks for the report. The issue is outdated. 

If this is a issue in the current release - please open a new ticket.

Thank you !
