### ISSUE TITLE
Some "Messages" seems packed in a block but not have a result

### ISSUE THREAD

**Issue by mostcute** [filecoin-project/lotus#5206]
**Describe the bug**
some message like `bafy2bzacedwxxzlw77qqxqeogvjsivdfw3cnij4fxpqt56gbvvh4xf5numau4` don't have a result. what happned?

**To Reproduce**
1. open a explorer and search  the message id `bafy2bzacedwxxzlw77qqxqeogvjsivdfw3cnij4fxpqt56gbvvh4xf5numau4`
2. See no result of the message
3. [this is the link](https://filfox.info/zh/message/bafy2bzacedwxxzlw77qqxqeogvjsivdfw3cnij4fxpqt56gbvvh4xf5numau4)

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by Reiers** [comment]
https://filfox.info/en/message/bafy2bzacedwxxzlw77qqxqeogvjsivdfw3cnij4fxpqt56gbvvh4xf5numau4

The message shows up here, and the message that was sent was a: `ProveCommitSector`

Closing issue.
