### ISSUE TITLE
I have a question: about the lotus wallet export command

### ISSUE THREAD

**Issue by Reallyone** [filecoin-project/lotus#5207]
I have a question: about the lotus wallet export command
        When I use the client command: lotus wallet export address
        Return: 7bxxxxxx7d This is indeed the result I want

But I use the rpc command to access:
curl -X POST \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer xxxxxxxxxxxxx"\
     --data '{
       "jsonrpc":"2.0",
       "method":"Filecoin.WalletExport",
       "params":[
          "f1uefhzyegzqthtj5ezehw3u23yvrr4tlj6n7iyyi"
       ],
       "id":7878
     }' \
     http://127.0.0.1/rpc/v0

What is returned is: T1zzz+oCd6+xxxx=  !  It bothers me a lot, please answer this question!
I also did not find any information about creating a wallet and private key in java on the website, thank you!

**Comment by 90hacker** [comment]
There is currently no official SDK provided by Java. If you need a Java signature, you can refer to this one.
https://www.jianshu.com/p/8fb3520387c8
I am currently signing offline based on this.

**Comment by wenqinchao** [comment]
I encountered the same problem, did you solve it？

**Comment by wenqinchao** [comment]
The command result seems base16 encoding of rpc result. 
`python
rpc_result = {'Type': 'secp256k1', 'PrivateKey': '3E36Z...KnkKoUYc='} 
 j_res = json.dumps(res).replace(" ", "")
command_result =  base64.b16encode(j_res.strip().encode()).decode().lower()
`

**Comment by wenqinchao** [comment]
The command result seems base16 encoding of rpc result.

`rpc_result = {'Type': 'secp256k1', 'PrivateKey': '3E36Z...KnkKoUYc='} 
j_res = json.dumps(res).replace(" ", "") 
command_result = base64.b16encode(j_res.strip().encode()).decode().lower()`

**Comment by wenqinchao** [comment]
The command result seems base16 encoding of rpc result.
```
rpc_result = {'Type': 'secp256k1', 'PrivateKey': '3E36Z...KnkKoUYc='}
 j_res = json.dumps(rpc_result ).replace(" ", "") 
command_result = base64.b16encode(j_res.strip().encode()).decode().lower()
```

**Comment by wenqinchao** [comment]
The command result seems base16 encoding of rpc result.
``` python
rpc_result = {'Type': 'secp256k1', 'PrivateKey': '3E36Z...KnkKoUYc='}
 j_res = json.dumps(rpc_result ).replace(" ", "") 
command_result = base64.b16encode(j_res.strip().encode()).decode().lower()
```

**Comment by wenqinchao** [comment]
The command result seems base16 encoding of rpc result.
``` python
# python
rpc_result = {'Type': 'secp256k1', 'PrivateKey': '3E36Z...KnkKoUYc='}
j_res = json.dumps(rpc_result ).replace(" ", "") 
command_result = base64.b16encode(j_res.strip().encode()).decode().lower()
```

**Comment by Reiers** [comment]
If you still have questions and want to continue the conversation - checkout our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions). 

Closing lotus issue ticket, instead of transferring due to old creation date ! 

Thanks!
