### ISSUE TITLE
Filecoin.MpoolPush failed: nonce 1 already in mpool: validation failure

### ISSUE THREAD

**Issue by xianggy** [filecoin-project/lotus#5209]
Filecoin.MpoolPush get error:

```
{"jsonrpc":"2.0","id":23,"error":{"code":1,"message":"message from f3q5vabtphr65id7zfhi7ynzefrndyxqkko2aszcyjyorrqplmcxn7d2ys4njfvonouohqem6q6xhbf5z2bjza with nonce 1 already in mpool: validation failure"}}
"}
```

request params:
`[{"Message":{"Version":0,"To":"f3xcn7f46l4dn75fkcir5cuod3f6w4o7wfyyk7szivdig45icgd5uzvbbfzdqi2xmqpdnufdrfpubhygb34osa","From":"f3q5vabtphr65id7zfhi7ynzefrndyxqkko2aszcyjyorrqplmcxn7d2ys4njfvonouohqem6q6xhbf5z2bjza","Nonce":1,"Value":"291900000000000000","GasLimit":3000000,"GasFeeCap":"5000000","GasPremium":"200000","Method":0,"Params":null,"CID":{"/":"bafy2bzacebnvobplgtsdmeh4csoi47h4flhkca6rh42ntouv7lyb4hrlbdxqu"}},"Signature":{"Type":2,"Data":"oHg1rLsoO4ywxJiE4KKJEMYWpvXwNYudEOwEgA/QidyyHpUGVLYmZT6ZXYjfGVzvAYA8g1Sm+ZdjZQ26NorjyRt5KSh+ovqagfw9PICb0ZLyPvQPklzm+L6sbhIpMY4T"},"CID":{"/":"bafy2bzacebnvobplgtsdmeh4csoi47h4flhkca6rh42ntouv7lyb4hrlbdxqu"}}]`

How to fix it.
Thanks.

**Comment by 90hacker** [comment]
nonce 1 already in mpool,You need to replace the previous message, but the parameters cannot be changed。
Only `GasLimit`, `GasFeeCap`, `GasPremium` These can change。
Only in this way can the previous transaction message be replaced。
I am Chinese. need my help

**Comment by Reiers** [comment]
The problem seems to be solved/answered.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you!

**Comment by xianggy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
