### ISSUE TITLE
Set a timeout in the client so that if provider doesn't respond to initiate data transfer, deal creation should fail.

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#5211]
When the client creates a deal with the provider:

    The go-data-transfer client sends a "push" request
    The go-data-transfer provider receives the "push" request and opens a go-graphsync query to the client
    The go-graphsync client receives the query and responds with the data for the file

I believe the root cause of this issue is that the provider does not open a graphsync query to the client in step 2. This could be because

    there was a network error
    the provider went down

Proposed fix:
In go-data-transfer, when opening a push request, set a timeout by which the provider must begin the data transfer, and fail the transfer if the timeout expires.

**Comment by dirkmc** [comment]
Fixed by https://github.com/filecoin-project/lotus/pull/5210
