### ISSUE TITLE
events API StateChanged handler calls back with nil newTs

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/lotus#5218]
The events API StateChanged method takes a StateChangeHandler:
https://github.com/filecoin-project/lotus/blob/c11803ad55a70986c39b0d2132579ecb1a9d5b21/chain/events/events_called.go#L433
https://github.com/filecoin-project/lotus/blob/c11803ad55a70986c39b0d2132579ecb1a9d5b21/chain/events/events_called.go#L401

It seems that the StateChangeHandler may sometimes be called with a nil `newTs`:
https://github.com/filecoin-project/lotus/issues/5212
We should investigate why this happens and ensure that the tipsets are always non-nil.

Also the documentation refers to `oldState` and `newState` which no longer exist. It should be updated:
https://github.com/filecoin-project/lotus/blob/c11803ad55a70986c39b0d2132579ecb1a9d5b21/chain/events/events_called.go#L418-L423

**Comment by TippyFlitsUK** [comment]
Hi @dirkmc 

This looks like a reminder. Should we close it or keep it open?
