### ISSUE TITLE
sector commit error

### ISSUE THREAD

**Issue by alingb** [filecoin-project/lotus#5221]
**Describe the problem**

There are three sectors that commit abnormally in a few days, and other sectors commit normally. I don't know what is caused by the problem?

**Sectors status**
root@lotus-master:~# lotus-miner sectors list
…………
414  Proving               YES      NO      1872878 (in 1 year 24 weeks)   CC
  RecoveryTimeout: 363818 (in 1 week 3 days)
415  Proving               YES      YES     1875758 (in 1 year 24 weeks)   CC
416  Proving               YES      YES     1872878 (in 1 year 24 weeks)   CC
417  Proving               YES      YES     1872878 (in 1 year 24 weeks)   CC
418  Proving               YES      YES     1872878 (in 1 year 24 weeks)   CC
419  Proving               YES      YES     1867118 (in 1 year 23 weeks)   CC
420  Proving               YES      YES     1867118 (in 1 year 23 weeks)   CC
421  Proving               YES      YES     1867118 (in 1 year 23 weeks)   CC
422  Proving               YES      YES     1867118 (in 1 year 23 weeks)   CC
423  Proving               YES      YES     1867118 (in 1 year 23 weeks)   CC
424  Proving               YES      YES     1875758 (in 1 year 24 weeks)   CC
425  Proving               YES      NO      1872878 (in 1 year 24 weeks)   CC
  RecoveryTimeout: 363818 (in 1 week 3 days)
426  Proving               YES      YES     1878638 (in 1 year 24 weeks)   CC
…………

root@lotus-master:~# lotus-miner sectors status -log 414
………………
697.	2020-12-14 10:16:30 +0800 CST:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":"AXGg5AIgpwXAkMpf/9r4l+HdlanJf27f9fGbTrS4qv+Phwjl+zEBcaDkAiCEhlvpc5hB1IC5gZJ1Q3xRhrOiEX6yZrX+JoBlrCUQGgFxoOQCIJN2CaGwt/dFIk7OfBlfzFZ27MYcH/sDryXcN2m669WzAXGg5AIgW3oMZg3D2UnpcsWPlGZb0Q7n1jD26TBF9aHs+IORb+0BcaDkAiAFotFQjGLuhALEMEYOErTV0PxqftpmU9WD7gnpnkD5dQFxoOQCICmaI4W6MYPu+i09i26y6ZyZutw8fNU6Q9o1fK6lwqKS"}}
698.	2020-12-14 11:31:30 +0800 CST:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"aQW3N/NO8nhxuHJ+KhtjOZiQ2/k3ua5fJrSanpwWjW8=","SeedEpoch":320337}}
699.	2020-12-14 19:33:50 +0800 CST:	[event;sealing.SectorCommitted]	{"User":{"Proof":"mEqRKH3D9TdwcHomkotVYbMKXO5cCf1Qc3lg9u5sVhXCUeT/Pikste8TKLuzn8WAom2HIzKE1PvYoVGXkhjPGY2gvtrMCvKCmP7ErhMfXJj+59vZg42ogUWk/SK2wt/+CRImI1/krXkNgFVS6aW/SL4T0oQ9+vl7O+JfWixDuIMjMU3f0hpkCCc7xK9uwX6bl+tulBFm/a01/h+0VceoqDEIS4Uvyfn3+cUk5KkxdUjVWKif3DV4aPTqHa6go5MmiGAKhyxhEnzYkLgH+qKQjWaNsP8UKm5am3dYMaZM7MC75nVWga6Lbrkie9G7zb0PmX+WQWYFEf6noxmMAEKHPVLbQqQuo2TNAuMUljCom4b1yBVCFwOQ/rYQ7job/T9ZD9Lo10cDNaWS87FUFQgUlyt7mvkMCZlFjIpmbFr9XHEttb+F85pvgXys954+Sl63mGVWrVkgKheJuJyMZLg1UVoTpdmQtF4baKoLRkrjRHqmmUgQyrT1QSpYgHScVG9Lo1PjvJLeN/R2vAFuR3Ncfdo7lk/rFY8oyYcnmNPn5bqVLUu6EHGhW+tFCxFfVsmRjRvBwleHOhY+rIkn/7rjq1i5yaNsg0+HoEPq6tt/y3F+iS8B7/LeFbjbTuYxZ5guD8NNuoWR9QjPouRKpkBRmQ4OxUhVRW5M4QbtYqCecMiWUZr9bRuOYXuOe2e9+sF6qDcR2W+lSuTMeuoEIzxBOXODrqAdGRSDSGnwd8HwQbLBKfYRK+p42Fb5uWKEnSYfhVwCxrc5g3I9jO/jyS6mTPWhFqhUiXiP6giBK8ZfMb+GtvWaKr5HGKX7uPxcGSFspBn0/i29G//zaJzwr3+ePhF09K+roghqu7j6RBgOrfW0RI90HQ06EqzDMint2UymDg7tA6QtiGXDrG6dUVSe/c/uD1xn++hbCL24QCdf+M3iSMDM8zoZ3pdK+Q1WqG79slhRZPFgqIT1ndWoqxVTshwnaOREp7RMJRh/1QackNcHsEsRED58phMbxJY4dWBercmEtPSxk/fguhKNmSFwPjLj9RlRegbAdKqyyhJwJrmbHk3uK5H51zEaX4qokdOfoN2pXxRaAlCgntuuCGNC/3bk328CMeO9fYzQkdd/jeJwXz1THHOW2SxSNCLAbZB+EzJeHjEouLsQYdpVoEJlIvph7AW4wYLybRW8PILY3NW5qgL6sXDzki6mq7fRHqRrgsCQ1qevJhjq469Z5POc7esGhzYApnt7U5ecd1r3toJ52vOHUvNOMtoRsntxo+GAqsuT2/Nb9lXOuaFh5qBIsvcGc2IXin9oNux+RyRABMcd4RgwuhNt4VrKmoCvNETFh19sB64v2w0GdTOtgcMjlCmIkilJ9C/efoW0OMrir4ZnNDi1i1XQD9Nlgv+Fg7jxBS3dNeOFGANsfOeDlA3ciEH74GMI22mRlSZ/VlDxrBE/sASb9dBOXljrVzTOmvpHomSScYB0B7KT76NQaZbKtvdAgJs8Xjusbe/2G+GT4bJvYC3QGzaOIR59O0ic/9wImRri2TsxD2+lj8ynsToq0pOfG9a4NAwmkKHB8Jore5tv1KbNAHMXWcrMleXEacUXhmMvRVrp1pXmSDccHLRqk+1UKZfZvN83UbTRHPH12JDpIiZI0BgyNGbP8Egcd8VGE/b5KTEp8T0Rdpnz9Bdrhe0Zv5hMrsc7AP69MfiZWJdDswD/bmQ5WJobnE8b0Bj6jg4RLWvs5vftptSK6VIO1GDejajxhguq1JPc5FqeTB1c9Wlmsj843i9U9+XNcQ8usO036QvnHITSsjy7qLtzwtyglCJuhktQGRv4ojba2USg60M+RdD7zQ6x09okIe7HtBTtK7HwKHAhnGTME1W9ZDsDlhmRMtpRrAM3eupLfPJKuGkQXdCQV8bANmQsS7nsD6weFT5KA5F7nSILTpC9YeJqfLObt2shLy2aI+ARbIaHWktBNKI6U8r7waPmEhgPkbE1D5I/v2NjoEd24YQTsz0rmUMex0R1mhbiwkyGKzUnE1DmUkDFTbqXDUcKTH83l2nM2NNzgPGd+tVCJ5j29NzXqeH7vcc2TXN8F/dLw2YWNMUNv2/0rRlIdGVWY2iPuImfZxzkUf/UqMrvkFWqj7r7hexSu4EH+o0xh8y9Vqm6+hC6RCLQjza98tJP0MHbEr6F+7bXoTH9zysLhA27iUdP7km2cijrP13Q4JuTZX+HDx6klnRNBG1/Sbawq/5nig8Y6M4FtF90TonryOzxDXgEqBe0GScjCP2OsuWaSy6WHWbD17LnsIQPbwiYPrSCrduCGLiedOD6S0jhvsl/n696/tFR+z+/X/Fctxh39tJaMMtH7VYIt/25HQCCK1LZjsN/MXVL2a0ojjeqzCoSD7UMtDBfHYhmGw3MzHZyooRV1smZD9yj4KKUHpCBqtNiF5iBJYy+fvN+9Vti6RmM2Y7/ucH8roAiXVKhY/HmUoU4RQm9jcZ/x9Y+FJIluIRtsapfD8whUkhi/gee3kIDscLV/86RqbRosGjGYcYXg9DuLyV+a04huepsSL80TNeQ"}}
700.	2020-12-14 19:33:51 +0800 CST:	[event;sealing.SectorCommitSubmitted]	{"User":{"Message":{"/":"bafy2bzacecbjgwprmtkhisaj6jsye6pgb7f7hw6cn7a4lvpv7lid5hem5yvlg"}}}
701.	2020-12-14 20:03:00 +0800 CST:	[event;sealing.SectorProving]	{"User":{}}
702.	2020-12-14 20:19:51 +0800 CST:	[event;sealing.SectorFinalized]	{"User":{}}
703.	2020-12-17 15:17:24 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}

root@lotus-master:~# lotus-miner sectors status -log 414
………………
991.	2020-12-14 20:02:16 +0800 CST:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzacecfmepo2qyov2irzgqqxi3gf4bdqptvdgbujuqt37h5pka7jsb7gy"},"PreCommitDeposit":"101640152018568631","PreCommitInfo":{"SealProof":8,"SectorNumber":425,"SealedCID":{"/":"bagboea4b5abcbjkrufnphslryosoprxeuvlf5k4mi2v33jpd3vr4qdvxu4ivcwyv"},"SealRandEpoch":319801,"DealIDs":[],"Expiration":1872878,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}
992.	2020-12-14 20:29:00 +0800 CST:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":"AXGg5AIganJW98XYP9GWVqRdazqbkgI+qrkZ/d1Pg46bk6rAvMwBcaDkAiCeFfYjDEg/db0sPC+jo4LEAtWgZKMTdsNB0aER7tgdQQFxoOQCIBnUCEh5icCp0KZhkT5pPlrsAVLXUbyaQtTIF8AQjbx4AXGg5AIgsQuzBOcHazCFd89dU2vRgk9rD3jlbZBxodw1zcy1J2MBcaDkAiDkNQ7JD0+WLZ7ukbX+kpyX+bTPoStlsZ+22uGE/3W1LAFxoOQCIKzzCs0xDiKvLzj/vM4nxvJzEru44/d3B78rB3O2QRpIAXGg5AIgF62g8lmPIWDjv7yE7k2EidhuD1UfGjQNvRn8Tn6n/9MBcaDkAiDA9TvVq9vpRsNB0BStruO5i45aeKVhpncTgDkoyXDOKQFxoOQCIABNpSk9R9bqKtg8gB0LmOPEzz1pvDK4HICYLzPS9InxAXGg5AIg+oA/b0Bciwn4sDqH0oJX/9QGcFyxAi0C2zD7HVkjIo0BcaDkAiCcos7vEx44AT/8SKUhVU2g1+G58UhfUbl9OZkWtGDFsg=="}}
993.	2020-12-14 21:44:00 +0800 CST:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"zykIkQj/AauYaA43irm4TsQI4tuTwIhk57OJn2QGSnQ=","SeedEpoch":321562}}
994.	2020-12-14 23:17:25 +0800 CST:	[event;sealing.SectorCommitted]	{"User":{"Proof":"lJA2EVN4ndN/i+mha2BofzgnugLptwmfiFxl+FjSNaxaSpIL3pIDShxpcS1Uu0RBo76VcY5X1H5U3Km1Peb7yyuZzGcD3cGlajbAlI+KIPWG8PO3IgETmmiSKkp+kYlIFkcEZ5opgaEerHOeMuOaYc+WnLIhq/bUFIURu5fVTgp9HLrFf4VhAixA+5nvkeQuiqgmQo+JSPzTcbuOIgh4MPLB7WzQ19wNkaJUXPzdaITET7FpoVvjM4kKTFp0NeJbhal370Zp6bdkGioQpJqC0LKAPUdm1xrj3c2SsekIZ538cER/yw3+h9mh/DPFPi/ArZQvu9spFqoeFQLnF9UYVY+JaGP93zVx3mlBWjc3DjM8c1hwTNz7i+1h6VV2rValBlHj/fUfs2GWMRaS1Vi2LUNTfgS7bZpNg3C1EpmteFWwy+Wtpql2QVGhJYn9vgCll/sG9rGIQwZT4A8X0N3WQMxQFoCMsc6S1bxC/XnEaz5gVNi6N/fockyyxHPBrjxBhZcSKuWNZ8pS/THDPFVV14rNctQ48xaaubHPSZxXJAGrttT/ysEHJp7Aa65RTDOhsxXDBAchZlVIrQTQYdueUw3Mc98IfrVYyZ4h0vZRBkc6aQCu6COzob5IYIDP1i6hBI5AhkDlukpAG9skjOiP9ErDsMcorzhaSI4u4dPmkbxx36STx335OqTLgUWFxogXleQePFcOzGIo1t+iVQyU87CilR56CWEmx5b/2+9OV/Zb7s23LwFTfL68447QIXprjrJHUtIyABFDrmriip9SpX397SqYMUUXffckyrDkvRen1IgVJ+OdPV7GfRK19/t7sPfBEnBIMtAkNeTvyppbX+cQ6729jjedaFkHYgi4DvopQLVElG5EHUxBJchY0ITqCHLM4gEU9ftQkCZy7UAyivcJOg4qSMBaUBFrIlkD6vqmeRYuqF1Zuxk2bmjR7jeIoc+T+u/vxhOut3w4EM/vGzyIOKGKBumoZt/YFv5CAQ1LNTS7l/+qk//r3S+d700zrQUkHtkWPS+Y2KXE63YZq9DwMPWGOrrFl8guk26w1l2zeeKnKfRlTP01ax1uOj/ymMvUww5OidgKf7dkVpNsKqkPBRDSOzdbPDZcQGQc9ra4d7/OcXUsTHtkBmIf59FSAHpPzm7cFdz3kOXZ0V8c/CnzW1LLWo8C0/rrK5UcTE2GUrUhvdFCZNSzFj3HC+6zoWG7P++6d2PIbZquaJSL1uYHQ+8qAnoL7QTwch35ccssvS3jWXudlmadTVCYs6Qvkftncn3kMqaJeHvjoiiTFVXETEaDv1Ap2SwR9+7MgEJbaYALVMjbY68PcTyQfEOdr8UCZEp3YwCaamV8VplfrxdiwZg0JNEkQyDUwZ/f+JGLCrK/z+r0d97+OUG51OtOCLUP/dvXbQhZrdugBfgoXkLAU+wtZoNucqPtFFkW0aq6Ll4cBsZaWPiychn+oqufhEvfvAfS30AnSS49E0k7BPcXyMHJuJBOhnfm2aHDTqYazkLaG2Sr88zXdDVqnOdNj6q0nk6p169nkbm0zqAZsIbtjkAlX5HU84FGKisX5E+Z2z8qrmsWffghC7Br6UVJitpcBNQ2/Pt2jXVdzcfBVqU8DCAb7hM8ZweztGXKvsFk4jEc1g+jBU3HVq4Jvs+IBaGSXq/QnNFzoWAC2L3px6whenUJHkZrat5ZDb/oa8P49kGAA2cB7raqKsuK5R2aqVhtiiO8DedwHeCqh5C7EqRENMW75xCxVnQKAqbkzKJsGKUAqsJN9/Q6BIoR9N/3q6vILGMvLvmRURjCDaTPRcGSKs5PJ+a/OyDdchdk6s6jWUYsMh12jCLzqXwjwJehuHpdGPGeEjsAogwrfJwZT3vCIUTH6P5Yd8HzymUC5orbSbv8YqdFraHkcooUWZEHDQ192/VEA37+SWlZhFFu5sLjU3Zf4lNdTi72auBcyzHMEv6Ki2mdKenR0TL21sHEisTesSdw31FIS3iQdL63UT/miQRgt1c6zkVPUkFPbxhZ8/kKL0bW+gTT/WzP8yG4kwXEI8WbvU8MqE2t0xXjDjHJAzdUnZV/TvNWTTPWf/6J+VBsRXI1MKo8LzgioTxmogrZur2Kidkp4nKav8e9jd2jeDTD9yRTGxAIcgl76Hj5VFT4hb9A5f2tZQjhmcswFdUzF1rUxmfmWA0zMKomTVyhp/X2rL8l4pItpcgxkmmoZph/w0SRCvGPrTFUAHwSuA/IWhAHq9HweD/eLcEA0rt3HsBw5qB3j9yYX9xWurJn6NzQGJgeWRwng8bp/9yHtvt/COBawn5Vs3zb5qGn10zneKQ96ZllROe83hr89lgmMBv0xssMXYXmwIzQhZqCkCzy/k5rkX7kdZik49kLWZbcG/Je+3nyXeBTX61j3OBdOGsy2EGrpqABugXIpmoSGHXWMFwdyJOL8+e17UwWRWs/X0QZOk3YN1RN94sjwPdNJz0QskIMaXdzTOLJ5Q0+h87kOMtmXYa92T4+25HRWOmVLVJ8oK9C437YIqYp8D/EjztOYrcaOB1151SOGDxS"}}
995.	2020-12-14 23:17:26 +0800 CST:	[event;sealing.SectorCommitSubmitted]	{"User":{"Message":{"/":"bafy2bzaceaxgqrrycy52vgnuoph3cv2qywljixxtsxunokbdtaubtddgnn7l2"}}}
996.	2020-12-15 05:28:30 +0800 CST:	[event;sealing.SectorProving]	{"User":{}}
997.	2020-12-15 05:28:30 +0800 CST:	[event;sealing.SectorFinalizeFailed]	{"User":{}}
	finalize sector: storage call error 0: allocate local sector for fetching: couldn't find a suitable path for a sector
998.	2020-12-15 05:29:30 +0800 CST:	[event;sealing.SectorRetryFinalize]	{"User":{}}
999.	2020-12-15 05:29:30 +0800 CST:	[event;sealing.SectorFinalizeFailed]	{"User":{}}
	finalize sector: storage call error 0: allocate local sector for fetching: couldn't find a suitable path for a sector
1000.	2020-12-15 05:30:30 +0800 CST:	[event;sealing.SectorRetryFinalize]	{"User":{}}
1001.	2020-12-15 05:30:30 +0800 CST:	[event;sealing.SectorFinalizeFailed]	{"User":{}}
	finalize sector: storage call error 0: allocate local sector for fetching: couldn't find a suitable path for a sector
1002.	2020-12-15 05:31:30 +0800 CST:	[event;sealing.SectorRetryFinalize]	{"User":{}}
1003.	2020-12-15 06:49:11 +0800 CST:	[event;sealing.SectorFinalized]	{"User":{}}
1004.	2020-12-17 15:17:24 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}

**Lotus miner logs**

Please go through the logs of your miner, and include screenshots of any error-like messages you find.

Alternatively please upload full log files and share a link here

**Lotus miner diagnostic info**

![postwin](https://user-images.githubusercontent.com/38687618/102586763-b16a1380-4145-11eb-8191-66dd0b53fc88.png)

** Code modifications **

N/A

**Version**

root@lotus-master:~# lotus --version
lotus version 1.3.0+git.5324440f7

**Comment by leobelive** [comment]
i have same problem , someone know how to  solved it ？

**Comment by Reiers** [comment]
If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
