### ISSUE TITLE
Deal stuck in StorageDealTransferring for 2 days

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#5224]
I have two deals stuck in StorageDealTransferring for 2 days so far. I apologize that I cannot provide much more detail they just stuck there that's it. I haven't tried restart miner or daemon. Will do so when upgrade to v1.3.0.

Right now I'm at lotus version 1.2.2+git.93d26195f

Dec 16 13:07:09  bafyreihg6p3ofpi73wn2pz62alzg3myqpneocnld7qhc2b6dmnogfiireu  0        StorageDealTransferring  f3ufzpudvsjqyiholpxiqoomsd2svy26jvy4z4pzodikgovkhkp6ioxf5p4jbpnf7tgyg67dny4j75e7og7zeq  16GiB   0.00016628352 FIL        1039272 
Dec 16 21:45:30  bafyreigvsgeb7k2f77fi7zc3iw34hanqlxkdfcoef2wwbasdxrrdmnjmku  0        StorageDealTransferring  f3skvkycrxr3ktvglcbvwt2vivj4zafiohhqzlg72gusddi4vxrqzyqqb7bf3kcvnobn4ppgnikdyneomta4iq  16GiB   0.08872048 FIL           554503

@dineshshenoy @jennijuju

**Comment by dirkmc** [comment]
I believe this will be fixed by https://github.com/filecoin-project/lotus/pull/5210
