### ISSUE TITLE
lotus-worker has no "stop" command

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#5227]
## Edit (@jennijuju )
Add a `lotus-worker stop` to properly terminate worker process.

## Orignal 

the title says it all

1.2.3,1.3.0...you name it

see the second part of this slack thread:

https://filecoinproject.slack.com/archives/CPFTWMY7N/p1608251903163700

@dineshshenoy 

sorry for the low quality issue - in a hurry - i will be on it Monday again and make it beautiful!

**Comment by arajasek** [comment]
Doesn't seem like the highest priority

**Comment by f8-ptrk** [comment]
the problem is that PC2/C2 workers do corrupt their *.log files when killing+restarting them quite often. one needs to delete the files by hand in order to make the workers start up again or, if upgrades/restarts are performed automatically, purging the whole worker folder

**Comment by William8Work** [comment]
ran into this problem after upgrading v1.5.3 (I guess it's been there for a while). Had to manually located the corrupted log files and delete them in order to get the worker started.

**Comment by arajasek** [comment]
Yeah, we should get around to this -- see the `lotus-miner stop` [command](https://github.com/filecoin-project/lotus/blob/e0522a6b1fa2a27e7347c3b16575f1d261a40652/cmd/lotus-miner/stop.go#L12-L27) for inspiration

**Comment by rjan90** [comment]
Closing this feature request now, since the feature has be merged!
