### ISSUE TITLE
proof validation failed, sector not found in sector set after cron

### ISSUE THREAD

**Issue by yydfjt** [filecoin-project/lotus#5234]
**Describe the bug**
lotus-miner sectors status --log xxx

32.     2020-12-20 07:43:45 +0800 CST:  [event;sealing.SectorCommitSubmitted]   {"User":{"Message":{"/":"bafy2bzacea7hcywtvehmteeoj65gzodpdf7y6k7cc3pv7njqpsbdrt5p4gdu6"}}}
33.     2020-12-20 09:00:46 +0800 CST:  [event;sealing.SectorCommitFailed]      {"User":{}}
        failed to wait for porep inclusion: handler: websocket connection closed
34.     2020-12-20 09:51:27 +0800 CST:  [event;sealing.SectorRestart]   {"User":{}}
35.     2020-12-20 09:51:28 +0800 CST:  [event;sealing.SectorRetryCommitWait]   {"User":{}}
36.     2020-12-20 09:51:28 +0800 CST:  [event;sealing.SectorCommitFailed]      {"User":{}}
        proof validation failed, sector not found in sector set after cron

sealing.SectorRetryCommitWait again and again

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
1.4.0

**Additional context**

**Comment by shaodan** [comment]
duplicate https://github.com/filecoin-project/lotus/issues/3355

**Comment by askender** [comment]
not exactly same with #3355
I am wondering why will `failed to wait for porep inclusion: handler: websocket connection closed`  happen?
besides,  similar error:
```
6.	2021-03-23 15:56:13 +0800 CST:	[event;sealing.SectorChainPreCommitFailed]	{"User":{}}
	handler: websocket connection closed
```

How to solve such issues?  What is the best practice?  We should have a FAQ for these errors.

**Comment by RobQuistNL** [comment]
this happens when your miner loses connection to the daemon.
No idea if this will fix itself or if the sector is now stuck in CommitFailed... 🤔 time will tell

**Comment by Reiers** [comment]
Hi @yydfjt 

Thanks for filing a issue - it appears that a issue is already open about this.
Here: https://github.com/filecoin-project/lotus/issues/3355

Closing this ticket.
