### ISSUE TITLE
export snapshot bug

### ISSUE THREAD

**Issue by 2019jack** [filecoin-project/lotus#5236]
miner log:
2020-12-20T23:01:12.114+0800    ERROR   rpc     go-jsonrpc@v0.1.2/websocket.go:654      Connection timeout      {"remote": "127.0.0.1:1234"}
ERROR: incomplete export (remote connection lost?)

lotus sync status
sync status:
worker 7712:
        Base:   [bafy2bzaceacbmjzqidbjtuxj7qqs72a5taio6optcqjnhmfgmwjx76s6ec3sk]
        Target: [bafy2bzaceayq53sydrxf6wmaoodam7t6q42bqp6jfz4b2cim2rilrri2gqwjq] (339007)
        Height diff:    0
        Stage: complete
        Height: 339007
        Elapsed: 145.521512ms
worker 7713:
        Base:   [bafy2bzaceacbmjzqidbjtuxj7qqs72a5taio6optcqjnhmfgmwjx76s6ec3sk bafy2bzacedmnf2rsidmotcbydxxgoggoznekle2rjeqxfzsqrq3llnpftpyji]
        Target: [bafy2bzacedf2xvpvemvcounpmfrlweqtuyd6xvnjd7meqz2z2xrgidtj62vly] (339007)
        Height diff:    0
        Stage: complete
        Height: 339007
        Elapsed: 220.53598ms
worker 7714:
        Base:   [bafy2bzaceacbmjzqidbjtuxj7qqs72a5taio6optcqjnhmfgmwjx76s6ec3sk bafy2bzacedf2xvpvemvcounpmfrlweqtuyd6xvnjd7meqz2z2xrgidtj62vly bafy2bzacedmnf2rsidmotcbydxxgoggoznekle2rjeqxfzsqrq3llnpftpyji bafy2bzaceayq53sydrxf6wmaoodam7t6q42bqp6jfz4b2cim2rilrri2gqwjq]
        Target: [bafy2bzaceam23no63zfglwxt3d4rkiqzrp26deg3h74bnwl77gm2zrwgnhifw] (339007)
        Height diff:    0
        Stage: complete
        Height: 339007
        Elapsed: 735.730154ms

Daemon:  1.4.0+git.e9989d0e4+api1.0.0
Local: lotus version 1.4.0+git.e9989d0e4

@magik6k @dirkmc @jennijuju @whyrusleeping

**Comment by rjan90** [comment]
Are you still experiencing this issue when you try to export a snapshot? Or else, I think this issue can probably be closed. #rengjøring
