### ISSUE TITLE
lotus-miner info - mFIL is ambiguous

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#5237]
**Describe the bug**
since 1.2.2 ?!? the lotus-miner info command shows the amounts of FIL in the different actors as mFIL - it is not clear if that is milli or micro FIL.

**To Reproduce**
1. Run 'lotus-miner info'

**Screenshots**

**Version (run `lotus version`):**
lotus-miner version
Daemon:  1.4.0+git.e9989d0e4+api1.0.0
Local: lotus-miner version 1.4.0+git.e9989d0e4

**Comment by PatrickDeuse** [comment]
i assume it jumps the micro step? FIL -> milli -> nano -> pico -> femto -> atto?

**Comment by TippyFlitsUK** [comment]
Hey @f8-ptrk 

Thanks for the report. The ticket is rather outdated. 

If you would still like to propose this enhancement - please open a new enhancement suggestion ticket using the issue template.

Thank you !

**Comment by f8-ptrk** [comment]
bs. you know, i know that this is still an "issue" as on the day this was opened. but i accept that you have no desire to provide a solution or do not consider it an issue at all.

**Comment by f8-ptrk** [comment]
problems are not disappearing just because the issues. all you do is have people not report issues anymore....

**Comment by Kubuxu** [comment]
@f8-ptrk as you can see over [here ](https://github.com/filecoin-project/lotus/blob/master/chain/types/fil.go#L31 ) we use `μ` sign for micro, so the `m` sign is always used in the context of milli prefix. This is the [standard ](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes )SI prefix notation.

If you find any inconsistent usages of the `m` or `μ` prefix, please let us know and it should be easy to fix.
