### ISSUE TITLE
unable to submit mpool information

### ISSUE THREAD

**Issue by alingb** [filecoin-project/lotus#5238]
**Describe the bug**
I couldn't submit mpool information two days ago. How can I improve "gasfeecap" has no effect. Now all my computing power is offline. I tried to clear "mpool pending". After restarting, new messages still can't be submitted? What shall I do?

**To Reproduce**
1. Run '...'
2. See error

root@lotus-master:~# lotus mpool gas-perf
f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq	1058	2146778902893720	12162212600000000000.000000
f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq	1059	3100057542491798	15109031780000000000.000000

root@lotus-master:~# lotus mpool pending --local
{
  "Message": {
    "Version": 0,
    "To": "f057466",
    "From": "f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq",
    "Nonce": 1058,
    "Value": "6928977997314694496",
    "GasLimit": 1765122,
    "GasFeeCap": "1368899528",
    "GasPremium": "99644",
    "Method": 22,
    "Params": null,
    "CID": {
      "/": "bafy2bzacedkohjkfsyaabbt3j3riyxe7jhjcwi7u6zzxyjifuy3gwfgdaxnlo"
    }
  },
  "Signature": {
    "Type": 2,
    "Data": "oRffSwRY8gn++Tv3FsAoo5ii0Al0FrgdkuShf4TQw+GqVSZNHsyNTXOyyV0Otv6kBjrra2ey/ewM8jikTD5pjwTWU5B9KhviYuFkDXsRD4WsHKseL96QqWFSYFC5gsqO"
  },
  "CID": {
    "/": "bafy2bzacedkohjkfsyaabbt3j3riyxe7jhjcwi7u6zzxyjifuy3gwfgdaxnlo"
  }
}
{
  "Message": {
    "Version": 0,
    "To": "f057466",
    "From": "f3qpfr2klk77irdfmtkrk24znseci6j5wpcayakkgdunkathfgze73mgo2mkim2fqamxmj4rpsmphw4gg2tqhq",
    "Nonce": 1059,
    "Value": "0",
    "GasLimit": 2051791,
    "GasFeeCap": "1663581446",
    "GasPremium": "100061",
    "Method": 23,
    "Params": "RACQxgU=",
    "CID": {
      "/": "bafy2bzaceb2cs2tjdsehrkgqx4ttcvhgodguxdwczzyq365553srmsf4n66yc"
    }
  },
  "Signature": {
    "Type": 2,
    "Data": "iOdVglTGHfushD6KC1fhuotWyCDKQzBqYtE4C5D0MPVp4KaCcLhKwY/9RBlZea2pC5hDEhQJEBC0KKMAdvWFWop3gnIeJ2X4D8iKRqL0K5c7JLOJjN71dt7gpVzQ8FcI"
  },
  "CID": {
    "/": "bafy2bzaceb2cs2tjdsehrkgqx4ttcvhgodguxdwczzyq365553srmsf4n66yc"
  }
}

root@lotus-master:~# lotus chain head | xargs lotus chain getblock | jq -r .ParentBaseFee
151088750

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
root@lotus-master:~# lotus version
Daemon:  1.4.0+git.e9989d0e4+api1.0.0
Local: lotus version 1.4.0+git.e9989d0e4
**Additional context**

**Comment by alingb** [comment]
@ magik6k @dirkmc @jennijuju @whyrusleeping

**Comment by 1055834146** [comment]
解决了没，我也是这个问题
