### ISSUE TITLE
Can't send any message when my miner free fil < 0, but my wallet has full fil.

### ISSUE THREAD

**Issue by taoyonggang** [filecoin-project/lotus#5243]
**Describe the bug**
Can't send any message when my miner free fil < 0, but my wallet has full fil.

Can't send any messges!!!!  And eat my fil everyday!!!!

You are create a great blockchain.  I have to go on .....  My money has be eated. Nothing left.

**To Reproduce**
1. Blockchain is jamming.
2. SubmitWindowedPoSt is failed.  Your system begin to eat my miner FIL.
3. I try to send fil to my miner. then contiue, Fil was eated.
4. Sending FIL was failed. The miner has not full fil to be eated. free fil < 0.
5. Next,can't send any message on blockchain.  Now, wait to your great system eat my all FIL.
6. You are great!

My miner account is f084147; Now it is dead lock.

 lotus wallet list
Address                                                                                 Balance                    Nonce  Default  
f3untrij6i56tvdsnj26wkzhbdhp3qfas3nxbiw7xreo6vn54haath4vakyxzmrnaacucgh4zg6smvis2s2cua  0 FIL                      0               
f3vvtaswt5bpykksqteqm4yrddae2fpvatvqn2xj4n2bjlbbzk66jz6rw2n4v6q7u3zonam7l27qyo57mvdpja  0.010072242470906041 FIL   10     X        
f3wyp3hclq2y5psyw6yczfhxblipgzvmycv4rligotrznfb4yi7byk2ps3hu5kgisrl3ogdgej2dzuhe3bbjdq  14.117845425947358754 FIL  273  

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
1.4.0
**Additional context**

**Comment by taoyonggang** [comment]
2020-12-22T15:37:01.862Z	ERROR	storageminer	storage/wdpost_run.go:779	estimating gas	{"error": "estimating gas used: message execution failed: exit 19, reason: unlocked balance can not repay fee debt: unlocked balance can not repay fee debt (0 < 7300672643693078948) (RetCode=19)"}
2020-12-22T15:37:02.901Z	ERROR	storageminer	storage/wdpost_run.go:447	checking sector recoveries: pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 19, reason: unlocked balance can not repay fee debt: unlocked balance can not repay fee debt (0 < 7300672643693078948) (RetCode=19)

**Comment by xiaomdong** [comment]
I have the same question.

**Comment by hzhao79** [comment]
any solutions to solve this?  I am in the same trap.

**Comment by Reiers** [comment]
I can see that the miner went down, which is unfortunate : https://filfox.info/en/address/f084147

Read more about debt and repaying here: https://lotus.filecoin.io/storage-providers/operate/lotus-miner-cli/#lotus-miner-actor-repay-debt

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you.
