### ISSUE TITLE
I cant get fil test coin

### ISSUE THREAD

**Issue by Dsimple1994** [filecoin-project/lotus#5247]
I ceated  lotus wallet,but i cant send fil test coin to the address from faucet.
if there anything wroing?

![image](https://user-images.githubusercontent.com/30295063/102976255-3edda700-453c-11eb-95fa-b9719e827caf.png)
![image](https://user-images.githubusercontent.com/30295063/102976284-469d4b80-453c-11eb-8def-955140eba955.png)
![image](https://user-images.githubusercontent.com/30295063/102976390-72203600-453c-11eb-897c-15425f0f5a85.png)

**Comment by rjan90** [comment]
As long as you are on the calibration-network, test-FIL's can be aquired here: [https://faucet.calibration.fildev.network/](https://faucet.calibration.fildev.network/). This issue can probably be closed! #rengjøring
