### ISSUE TITLE
winpost failed

### ISSUE THREAD

**Issue by alingb** [filecoin-project/lotus#5248]
**Describe the problem**

After updating V1.40, there are about 7 sectors that cannot be proved. What's wrong with that?

**Sectors status**

miner.log

`2020-12-23T13:12:00.928+0800	ERROR	storageminer	storage/wdpost_run.go:103	runPost failed: running window post failed:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
        /root/lotus/storage/wdpost_run.go:613
  - generate_window_post: merkle_tree failed: SectorId(458)

    Caused by:
        0: failed to read 32 bytes from file at offset 4908534016
        1: failed to fill whole buffer
    github.com/filecoin-project/filecoin-ffi.GenerateWindowPoSt
    	/root/lotus/extern/filecoin-ffi/proofs.go:587
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).GenerateWindowPoSt
    	/root/lotus/extern/sector-storage/ffiwrapper/verifier_cgo.go:45
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
    	/root/lotus/storage/wdpost_run.go:591
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runGeneratePoST
    	/root/lotus/storage/wdpost_run.go:101
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).startGeneratePoST.func1
    	/root/lotus/storage/wdpost_run.go:85
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1374
2020-12-23T13:12:00.928+0800	ERROR	storageminer	storage/wdpost_run.go:47	Got err %!w(*xerrors.wrapError=&{running window post failed 0xc016e694e0 {[7549195 22547434 22528933]}}) - TODO handle errors`

`root@lotus-master:~# lotus-miner sectors status -log 458
SectorID:	458
Status:		Removed
CIDcommD:	baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq
CIDcommR:	bagboea4b5abcbxplybnbxoeez6mjrunwhpknzj6blzrf64opbeik4hvup7436pix
Ticket:		a1f59b213e9930aa6af6d9550df5ccfbfa807fec1ebe501d7eb4417fd4593c50
TicketH:	331281
Seed:		636bf51c4dad8282e34dc92ab3fa5984032bfd205fa1e27402c8ba53a28583ce
SeedH:		333581
Precommit:	bafy2bzacebltw7nm7qithowptm2ej25rvkfju6a5vr4lmixpcnrvonzp3tzoy
Commit:		bafy2bzaceautyzjc5ntjymprde54xwcnzx5xibjhc5e5fzi5sbgrmucxd4ive
Proof:		8dc921689ea6859273795438c589cf435d6d930f56d31a0e49a84d24f35f80521f337e4eccfb93c383545b0a23a6bd2db2ca1090355acd9f551d792762c2720b39514ad5b1d3d2db896bf81abb62d971ffe41695539e5e932d4198123be205cf022f34934a51b12f4e096bd5dd9e25662ec1dca8de52a970ec90fbe5a263d9318eba8389a87c96c6aca0f593cabbd093b32f183c503bcb20a258462ae584039ba5b3e730a77dada91ff951d0b780c35def7669a1ada946d99def886cf4d0b0b382e1a935d1bfc922a8c995cafee70642bc6e49f22efb3efdb8180cbafa2efdf30eae24bc377373dfda9d60199f3350ee8b498c3f0ef2fddd69a19aa37136107b86161eeb9da7ff6ca311196c33b29ff47d893b7637a72e4f4d46d8e1fcd4fe6a13ff7dae2c8505b4eddb7bd662468b26135e76d8c60b138080be2221e70a5b9e377f3acb4c5706211e9bb9c697af9f9bb05cc0ec98e008f033aae207969e493a6cbfe91fc6236a212de37bbd7b0401d36b059f0c3c3fc190b94f8d0ff13d70dbabdc689fddf5a2e269d19bcef660d76602364b79ea68d0ee682e60c8f1b6435348f69684eefed2cb7c2dd29541df806b935895cb8efb455778f79fc497af55f376c49b1372025fe22ad6e88b66d133acb27ffb0c386d82a22badc450aed0c3ba0ddaec8f7f4d0b36c501065afaf4105e03ab82dad404724fdae7a7b9bf77430f03131cdee2fb100a56d91bfda212c17ab4c760707e0c4bfa244bf21614e068a6b13db4002364e76b72d1444f991b596a21d15d6512fcd17d5f3b3a0d37ffb69284db69111670e19fd32125224bf3cfb3191c5bc9c151e4c6870905c845f49074971216bec8676fe1e272704b4840f8d3b8e19dcc35da28c1d329ad79ed33e2c753b1380f3488d0badd72b8234d7b32ccdf8f6e23b45147c3387f3405508991f9166993b960e87d3e709cb7de4335e96bc147285c4810d2a8443419efeb87da580eeb6c484b83887bdb64edb9197fa058956077c1078d49bed8a5a9441c9796b3e9169be5af4449095a38588f21224d8fee70d159e051517645209aa31185ed6daa96c047774d6f846919eba07dd0babd90c4af4b663f647bbfaa715cd7903996380d79e974a8634a174a5778bb542010b71085ccfdab323407e507dc39b13367f9d32b1667fef27f4e76228a68813505cc6ff5e85835e1c16275ac2edb73797214bdfdbf8b2b79307656f67ea22aaa013b4adeb2e4806b9ada040312e98d63d075684ec1f79543323f75e58c9a20a309ab84b105034a55aa1c91f1258c2773490ecb42dc7bfb64724a489ac3b4a2440ece75bc0400fb6b45e4fb40c0e70904b2a8131b02f04542a828bee22ef6e45f06016a55376d3f9c9f844043eedbf068b84b41abd552a0b59f2dc16fb9195c4e7e927f746c6e117082f78ad838f0884930afe2157d9a5f3048c390145bbcd5343cc49f459ea78916e7c52eacd2a1d80fbf0baa7cd3da6d4f6bd3647a1ba8c0cd1107b37cd924e02b620b1871bffa19fffedc1af24c13ca3f407faccb6b6b6ac69494046b76e2d04abd00ccadb270d3fd70e1a10028ceb0a1d113809a090982a4f4cd3ddba4286a1ad4666c2ae1514524008c4d6afeeab4d948f833527f9c9013996d69a01f3c99a0229f0196c7b24d7e3c9c7b1a27b77a7324ae12b9c03ceb6bd0b25d38d3386bc401e6d8da116f6614b4ec97900f4b3a41f01fef1147fbab0dcaeb0c952cbc3609053781f30d9748d59f11c397a221c9fa20ce9029e121618bb16eef150982a79178f5b5f40ac8b59b8e16e0fe56deda3839387c71570fe017c8b6b7963272a9a4a44046e8c63ce80ba524f691a23fdc1d77f3bfa2eea96b2173bdd5aefb38e5f3c51cca71e819ef1a1aac1142d250d9bd1629065452fab56145a194aea38cd85c004751fa304cd2b515e9cf7c1b7896bef223379cdd6994aa76a864aa471dd14cfcf706175284ab4de73559c1563f1bdd78217bba04ae3d5288d49fe476b512e84566ab662bb3ab0786135940474365c31b5ac7d16ce211d8f45f875345ef95f4052543c5f1b4f901da5438425ff5e0be2a5336d750a7f29c3788efb4fe57e41fbb9461b07bf148d8866f1ad2c78b4ffac838d33de288e8798a772d2c4da032bb06ff3dc82853695733855f2632351038e03e02c0c7fbfaedefaccadbd26ffb4ee7d95d99f57a3afc120c510e83106e30d719016524eb9c3de580cba2caaf24195ab5c7d12bc68eabe19e01a4a55f244ef3eeea8abde90368c7385e7da615a6849a1b1f420059e8191c0cd6c83d8570734c9afc1ea4d8c618f8205a3d2612d61c1c22482d88871adc200199e59eae321c762c37fc72fff68172952131e0d54a4f94fa30f3198f337a7a2426edc7b4790c9a080501c4fffdf503c7b72a00dcebd907758c2d478e51b7ac804a48c7daf9db833185d4563db3a042b9f64c2fd901014fad5c9b83d050685983ad8352e3b296d5483c1d8adf7ebe038e55542b15e4f76c7b528a2a30c1703a1e04ce5ca69f93bda1a8c7caa3d31c8fc1d1908846c84b251a6b7daa4e49b4c5047af2cda2042d583b718baa9603edc1386524ec9421aaa435e2b48705627236f580d5d96bb8bd815f85e9d75b91f0b1b4c0de7d99212df2fcef28b10f9caf4d0931c1bf8f4b6054e280385c99d292e1c222d14c0e3f1210dbd5ca24aabd59bc
Deals:		[0]
Retries:	0
--------
Event Log:
0.	2020-12-18 14:10:56 +0800 CST:	[event;sealing.SectorStartCC]	{"User":{"ID":458,"SectorType":8,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}},"DealInfo":null}]}}
1.	2020-12-18 14:10:56 +0800 CST:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
2.	2020-12-18 14:10:56 +0800 CST:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"ofWbIT6ZMKpq9tlVDfXM+/qAf+wevlAdfrRBf9RZPFA=","TicketEpoch":331281}}
3.	2020-12-18 14:12:53 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	seal pre commit(1) failed: storage call error 101: worker restarted
4.	2020-12-18 14:13:53 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
5.	2020-12-18 15:06:14 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	seal pre commit(1) failed: storage call error 101: worker restarted
6.	2020-12-18 15:07:14 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
7.	2020-12-18 18:42:51 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjFfMSIsImxhYmVscyI6eyJTdGFja2VkRHJnMzJHaUJWMSI6eyJsYWJlbHMiOlt7InBhdGgiOiIvZGF0YTIvTE9UVVNfV09SS0VSX1BBVEgvY2FjaGUvcy10MDU3NDY2LTQ1OCIsImlkIjoibGF5ZXItMSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEyL0xPVFVTX1dPUktFUl9QQVRIL2NhY2hlL3MtdDA1NzQ2Ni00NTgiLCJpZCI6ImxheWVyLTIiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhMi9MT1RVU19XT1JLRVJfUEFUSC9jYWNoZS9zLXQwNTc0NjYtNDU4IiwiaWQiOiJsYXllci0zIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YTIvTE9UVVNfV09SS0VSX1BBVEgvY2FjaGUvcy10MDU3NDY2LTQ1OCIsImlkIjoibGF5ZXItNCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEyL0xPVFVTX1dPUktFUl9QQVRIL2NhY2hlL3MtdDA1NzQ2Ni00NTgiLCJpZCI6ImxheWVyLTUiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhMi9MT1RVU19XT1JLRVJfUEFUSC9jYWNoZS9zLXQwNTc0NjYtNDU4IiwiaWQiOiJsYXllci02Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YTIvTE9UVVNfV09SS0VSX1BBVEgvY2FjaGUvcy10MDU3NDY2LTQ1OCIsImlkIjoibGF5ZXItNyIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEyL0xPVFVTX1dPUktFUl9QQVRIL2NhY2hlL3MtdDA1NzQ2Ni00NTgiLCJpZCI6ImxheWVyLTgiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhMi9MT1RVU19XT1JLRVJfUEFUSC9jYWNoZS9zLXQwNTc0NjYtNDU4IiwiaWQiOiJsYXllci05Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YTIvTE9UVVNfV09SS0VSX1BBVEgvY2FjaGUvcy10MDU3NDY2LTQ1OCIsImlkIjoibGF5ZXItMTAiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhMi9MT1RVU19XT1JLRVJfUEFUSC9jYWNoZS9zLXQwNTc0NjYtNDU4IiwiaWQiOiJsYXllci0xMSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N31dLCJfaCI6bnVsbH19LCJjb25maWciOnsicGF0aCI6Ii9kYXRhMi9MT1RVU19XT1JLRVJfUEFUSC9jYWNoZS9zLXQwNTc0NjYtNDU4IiwiaWQiOiJ0cmVlLWQiLCJzaXplIjoyMTQ3NDgzNjQ3LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LCJjb21tX2QiOls3LDEyNiw5NSwyMjIsNTMsMTk3LDEwLDE0NywzLDE2NSw4MCw5LDIyNyw3MywxMzgsNzgsMTkwLDIyMywyNDMsMTU2LDY2LDE4MywxNiwxODMsNDgsMjE2LDIzNiwxMjIsMTk5LDE3NSwxNjYsNjJdfQ=="}}
8.	2020-12-18 20:46:33 +0800 CST:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcbxplybnbxoeez6mjrunwhpknzj6blzrf64opbeik4hvup7436pix"},"Unsealed":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}}
9.	2020-12-18 20:46:37 +0800 CST:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzacebltw7nm7qithowptm2ej25rvkfju6a5vr4lmixpcnrvonzp3tzoy"},"PreCommitDeposit":"100362508015473121","PreCommitInfo":{"SealProof":8,"SectorNumber":458,"SealedCID":{"/":"bagboea4b5abcbxplybnbxoeez6mjrunwhpknzj6blzrf64opbeik4hvup7436pix"},"SealRandEpoch":331281,"DealIDs":[],"Expiration":1884398,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}
10.	2020-12-18 23:20:50 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
11.	2020-12-19 00:15:10 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
12.	2020-12-19 00:38:30 +0800 CST:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":"AXGg5AIgC8OKwjDsCcZnjDwbsWnBsTCndLObY2BJDYZ6zFRXwewBcaDkAiAcZCFqv/fk7Ux9DkT4FaTYzvkftJp1eJaKG1T8doNahwFxoOQCILI1+xCSfs3FP0NbitnGO3qaYhnf6E+1qWf6Gw4sUk+p"}}
13.	2020-12-19 01:53:30 +0800 CST:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"Y2v1HE2tgoLjTckqs/pZhAMr/SBfoeJ0Asi6U6KFg84=","SeedEpoch":333581}}
14.	2020-12-19 03:21:43 +0800 CST:	[event;sealing.SectorCommitted]	{"User":{"Proof":"jckhaJ6mhZJzeVQ4xYnPQ11tkw9W0xoOSahNJPNfgFIfM35OzPuTw4NUWwojpr0tssoQkDVazZ9VHXknYsJyCzlRStWx09LbiWv4Grti2XH/5BaVU55eky1BmBI74gXPAi80k0pRsS9OCWvV3Z4lZi7B3KjeUqlw7JD75aJj2TGOuoOJqHyWxqyg9ZPKu9CTsy8YPFA7yyCiWEYq5YQDm6Wz5zCnfa2pH/lR0LeAw13vdmmhralG2Z3viGz00LCzguGpNdG/ySKoyZXK/ucGQrxuSfIu+z79uBgMuvou/fMOriS8N3Nz39qdYBmfM1Dui0mMPw7y/d1poZqjcTYQe4YWHuudp/9soxEZbDOyn/R9iTt2N6cuT01G2OH81P5qE/99riyFBbTt23vWYkaLJhNedtjGCxOAgL4iIecKW543fzrLTFcGIR6bucaXr5+bsFzA7JjgCPAzquIHlp5JOmy/6R/GI2ohLeN7vXsEAdNrBZ8MPD/BkLlPjQ/xPXDbq9xon931ouJp0ZvO9mDXZgI2S3nqaNDuaC5gyPG2Q1NI9paE7v7Sy3wt0pVB34Brk1iVy477RVd495/El69V83bEmxNyAl/iKtboi2bRM6yyf/sMOG2CoiutxFCu0MO6Ddrsj39NCzbFAQZa+vQQXgOrgtrUBHJP2uenub93Qw8DExze4vsQClbZG/2iEsF6tMdgcH4MS/okS/IWFOBoprE9tAAjZOdrctFET5kbWWoh0V1lEvzRfV87Og03/7aShNtpERZw4Z/TISUiS/PPsxkcW8nBUeTGhwkFyEX0kHSXEha+yGdv4eJycEtIQPjTuOGdzDXaKMHTKa157TPix1OxOA80iNC63XK4I017Mszfj24jtFFHwzh/NAVQiZH5FmmTuWDofT5wnLfeQzXpa8FHKFxIENKoRDQZ7+uH2lgO62xIS4OIe9tk7bkZf6BYlWB3wQeNSb7YpalEHJeWs+kWm+WvREkJWjhYjyEiTY/ucNFZ4FFRdkUgmqMRhe1tqpbAR3dNb4RpGeugfdC6vZDEr0tmP2R7v6pxXNeQOZY4DXnpdKhjShdKV3i7VCAQtxCFzP2rMjQH5QfcObEzZ/nTKxZn/vJ/TnYiimiBNQXMb/XoWDXhwWJ1rC7bc3lyFL39v4sreTB2VvZ+oiqqATtK3rLkgGua2gQDEumNY9B1aE7B95VDMj915YyaIKMJq4SxBQNKVaockfEljCdzSQ7LQtx7+2RySkiaw7SiRA7OdbwEAPtrReT7QMDnCQSyqBMbAvBFQqgovuIu9uRfBgFqVTdtP5yfhEBD7tvwaLhLQavVUqC1ny3Bb7kZXE5+kn90bG4RcIL3itg48IhJMK/iFX2aXzBIw5AUW7zVNDzEn0Wep4kW58UurNKh2A+/C6p809ptT2vTZHobqMDNEQezfNkk4CtiCxhxv/oZ//7cGvJME8o/QH+sy2trasaUlARrduLQSr0AzK2ycNP9cOGhACjOsKHRE4CaCQmCpPTNPdukKGoa1GZsKuFRRSQAjE1q/uq02Uj4M1J/nJATmW1poB88maAinwGWx7JNfjycexont3pzJK4SucA862vQsl040zhrxAHm2NoRb2YUtOyXkA9LOkHwH+8RR/urDcrrDJUsvDYJBTeB8w2XSNWfEcOXoiHJ+iDOkCnhIWGLsW7vFQmCp5F49bX0Csi1m44W4P5W3to4OTh8cVcP4BfItreWMnKppKRARujGPOgLpST2kaI/3B1387+i7qlrIXO91a77OOXzxRzKcegZ7xoarBFC0lDZvRYpBlRS+rVhRaGUrqOM2FwAR1H6MEzStRXpz3wbeJa+8iM3nN1plKp2qGSqRx3RTPz3BhdShKtN5zVZwVY/G914IXu6BK49UojUn+R2tRLoRWarZiuzqweGE1lAR0Nlwxtax9Fs4hHY9F+HU0XvlfQFJUPF8bT5AdpUOEJf9eC+KlM211Cn8pw3iO+0/lfkH7uUYbB78UjYhm8a0seLT/rIONM94ojoeYp3LSxNoDK7Bv89yChTaVczhV8mMjUQOOA+AsDH+/rt76zK29Jv+07n2V2Z9Xo6/BIMUQ6DEG4w1xkBZSTrnD3lgMuiyq8kGVq1x9Erxo6r4Z4BpKVfJE7z7uqKvekDaMc4Xn2mFaaEmhsfQgBZ6BkcDNbIPYVwc0ya/B6k2MYY+CBaPSYS1hwcIkgtiIca3CABmeWerjIcdiw3/HL/9oFylSEx4NVKT5T6MPMZjzN6eiQm7ce0eQyaCAUBxP/99QPHtyoA3OvZB3WMLUeOUbesgEpIx9r524MxhdRWPbOgQrn2TC/ZAQFPrVybg9BQaFmDrYNS47KW1Ug8HYrffr4DjlVUKxXk92x7UooqMMFwOh4Ezlymn5O9oajHyqPTHI/B0ZCIRshLJRprfapOSbTFBHryzaIELVg7cYuqlgPtwThlJOyUIaqkNeK0hwVicjb1gNXZa7i9gV+F6ddbkfCxtMDefZkhLfL87yixD5yvTQkxwb+PS2BU4oA4XJnSkuHCItFMDj8SENvVyiSqvVm8"}}
15.	2020-12-19 03:21:44 +0800 CST:	[event;sealing.SectorCommitSubmitted]	{"User":{"Message":{"/":"bafy2bzaceautyzjc5ntjymprde54xwcnzx5xibjhc5e5fzi5sbgrmucxd4ive"}}}
16.	2020-12-19 10:01:29 +0800 CST:	[event;sealing.SectorProving]	{"User":{}}
17.	2020-12-19 10:26:53 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
18.	2020-12-19 10:39:18 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
19.	2020-12-19 10:43:22 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
20.	2020-12-19 10:48:12 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
21.	2020-12-19 10:52:12 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
22.	2020-12-19 10:56:07 +0800 CST:	[event;sealing.SectorFinalized]	{"User":{}}
23.	2020-12-19 11:09:56 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
24.	2020-12-19 15:08:52 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
25.	2020-12-19 15:15:42 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
26.	2020-12-19 16:48:36 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
27.	2020-12-19 17:01:21 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
28.	2020-12-19 19:46:47 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
29.	2020-12-19 22:21:04 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
30.	2020-12-19 22:56:38 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
31.	2020-12-19 23:12:20 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
32.	2020-12-19 23:52:05 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
33.	2020-12-20 07:37:42 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
34.	2020-12-20 08:15:51 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
35.	2020-12-21 02:12:22 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
36.	2020-12-21 09:41:51 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
37.	2020-12-21 10:43:33 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
38.	2020-12-21 11:49:39 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
39.	2020-12-21 12:35:12 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
40.	2020-12-21 12:43:51 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
41.	2020-12-21 12:47:39 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
42.	2020-12-21 13:39:45 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
43.	2020-12-21 13:57:48 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
44.	2020-12-21 21:29:43 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
45.	2020-12-21 22:39:23 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
46.	2020-12-21 23:29:36 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
47.	2020-12-21 23:36:36 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
48.	2020-12-22 13:47:16 +0800 CST:	[event;sealing.SectorRemove]	{"User":{}}
49.	2020-12-22 13:47:16 +0800 CST:	[event;sealing.SectorRemoved]	{"User":{}}
50.	2020-12-23 10:29:05 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
51.	2020-12-23 13:12:09 +0800 CST:	[event;sealing.SectorRemove]	{"User":{}}
52.	2020-12-23 13:12:11 +0800 CST:	[event;sealing.SectorRemoved]	{"User":{}}`

**Lotus miner logs**

Please go through the logs of your miner, and include screenshots of any error-like messages you find.

Alternatively please upload full log files and share a link here

**Lotus miner diagnostic info**

Please collect the following diagnostic information, and share a link here

* lotus-miner diagnostic info `lotus-miner info all > allinfo`

** Code modifications **

If you have modified parts of lotus, please describe which areas were modified,
and the scope of those modifications

**Version**

root@lotus-master:~# lotus --version
lotus version 1.4.0+git.e9989d0e4

**Comment by potato1992** [comment]
I have the same problem, it turns out that my Raid is missing one disk.
