### ISSUE TITLE
High frequency CPU sealing is slow

### ISSUE THREAD

**Issue by alingb** [filecoin-project/lotus#5250]
In addition to the CPU running configuration is the same, but PC1 and unseal phase high frequency CPU running slower, I do not know what is going on?

`CPU：AMD EPYC 7502 32-Core Processor 1.5Ghz`

results (v28) SectorSize:(34359738368), SectorNumber:(1)
seal: addPiece: 13m59.254204833s (39.04 MiB/s)
seal: preCommit phase 1: 2h52m52.439273079s (3.159 MiB/s)
seal: preCommit phase 2: 48m21.907720711s (11.29 MiB/s)
seal: commit phase 1: 1m2.510860945s (524.2 MiB/s)
seal: commit phase 2: 1h32m40.179029168s (5.893 MiB/s)
seal: verify: 13.770408ms
unseal: 3h7m23.407479593s  (2.914 MiB/s)
generate candidates: 2.858926ms (10.93 TiB/s)
compute winning post proof (cold): 3.989723624s
compute winning post proof (hot): 3.505605911s
verify winning post proof (cold): 80.776267ms
verify winning post proof (hot): 7.020409ms
compute window post proof (cold): 15m19.954807157s
compute window post proof (hot): 15m2.633881021s
verify window post proof (cold): 7.616474797s
verify window post proof (hot): 13.384488ms

`CPU：AMD EPYC 7F32 8-Core Processor 3.7Ghz`

results (v28) SectorSize:(34359738368), SectorNumber:(1)
seal: addPiece: 11m24.504301965s (47.87 MiB/s)
seal: preCommit phase 1: 4h38m2.451779924s (1.964 MiB/s)
seal: preCommit phase 2: 21m44.328580829s (25.12 MiB/s)
seal: commit phase 1: 768.628626ms (41.63 GiB/s)
seal: commit phase 2: 1h23m38.297546298s (6.53 MiB/s)
seal: verify: 9.938913ms
unseal: 4h42m47.67981238s  (1.931 MiB/s)
generate candidates: 1.735545ms (18.01 TiB/s)
compute winning post proof (cold): 5.473388843s
compute winning post proof (hot): 5.386709275s
verify winning post proof (cold): 80.787035ms
verify winning post proof (hot): 3.988812ms
compute window post proof (cold): 17m18.469504458s
compute window post proof (hot): 16m50.195602778s
verify window post proof (cold): 12.287114427s
verify window post proof (hot): 22.345083ms

**Comment by alingb** [comment]
```
export BELLMAN_CPU_UTILIZATION=0.875
export FIL_PROOFS_MAXIMIZE_CACHING=1
export FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1
export FIL_PROOFS_USE_GPU_TREE_BUILDER=1
export FIL_PROOFS_PARAMETER_CACHE=/nvme/miner/parameter_path
export FIL_PROOFS_PARENT_CACHE=/nvme/miner/parent_path
export TMPDIR=/nvme/tmp
export FIL_PROOFS_USE_MULTICORE_SDR=1
```

**Comment by rjan90** [comment]
I think can be closed, as it's not an issue per se, but rather a question/discussion about sealing times. #rengjøring
