### ISSUE TITLE
Already sync, but still got API problem

### ISSUE THREAD

**Issue by andiz1014** [filecoin-project/lotus#5253]
I have already completed sync for lotus, the state is " complete".
And when I run "lotus-miner run", and check the info of my miner, I got the message of `"ERROR: could not get API info: could not get api endpoint: API not running(no endpoint)"`.
I had already reinit my miner for several times, but it still doesn't run properly.
So if anyone can help me? I have already stuck in this problem for one week....

（If I need to provide any other information, please tell me, thanks)

![image](https://user-images.githubusercontent.com/76585341/103132052-32914f80-46de-11eb-9d30-ef2a68420bf9.png)

### lotus version
![image](https://user-images.githubusercontent.com/76585341/103132492-b8fa6100-46df-11eb-94aa-d49b1e47fb2b.png)

**Comment by cryptocamtech** [comment]
Have you got a firewall running? I had to open port 1234/tcp.

**Comment by andiz1014** [comment]
> Have you got a firewall running? I had to open port 1234/tcp.

The firewall is closed. Actually I can run the miner properly a week ago, but when I restart my miner, the communication goes wrong.
![image](https://user-images.githubusercontent.com/76585341/103163740-1c4dd580-483d-11eb-8c85-172b44670621.png)

**Comment by Reiers** [comment]
If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
