### ISSUE TITLE
lotus client list-transfers missing verbose option

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#5256]
Hello I am trying to cross reference list-transfers with list-deals but everything on the output of list-transfers are truncated and there is no verbose option.

Also list-transfers are missing a column of DealCid making it hard to correlate with the deals.

**Comment by alter-storage** [comment]
the same question, hope cometh soon.

**Comment by dirkmc** [comment]
I agree that it would be useful to include deal CID in list-transfers 👍 

In the mean time note that the verbose output of `list-deals` now includes the transfer ID (since https://github.com/filecoin-project/lotus/pull/5150)
