### ISSUE TITLE
Handle getting disconnected from the rest of the network while mining

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#526]
Currently, if you are mining and your node gets disconnected from the internet, you may mine yourself into a fork that you won't be able to recover from without manually resetting the chain to a point before the fork.

We should somehow detect and mitigate this.

Fixing this would address #473

**Comment by jennijuju** [comment]
Things got improved a lot since this ticket was open - please create a new issue if you are still running into it with the latest lotus release!
