### ISSUE TITLE
 API not running ( sync complete)

### ISSUE THREAD

**Issue by andiz1014** [filecoin-project/lotus#5260]
**Describe the bug**
I have already completed sync for lotus, the state is " complete".
And when I run "lotus-miner run", and check the info of my miner, I got the message of` "ERROR: could not get API info: could not get api endpoint: API not running(no endpoint)"`.
I had already reinit my miner for several times, but it still doesn't run properly.

**To Reproduce**
1. Run 'lotus-miner run'
2. Run 'lotus-miner info'
3. See error"ERROR: could not get API info: could not get api endpoint: API not running(no endpoint)"

**Expected behavior**
Get  the information of my miner.

**Screenshots**
![image](https://user-images.githubusercontent.com/76585341/103252165-9190e600-49b6-11eb-8716-20f7fc2b1e04.png)
And the firewall of my Linux is closed.
![image](https://user-images.githubusercontent.com/76585341/103252182-a53c4c80-49b6-11eb-8f44-5eb1fce8e5f0.png)

**Version (run `lotus version`):**
Daemon: 1.1.2+git.3908701b7+api0.17.0
Local: lotus version 1.1.2+git.3908701b7

**Additional context**
The internet branch is nerpa.
There was no API problem before. But after I met this problem first time, there was no way to solve it.

**Comment by mrntidu** [comment]
https://docs.filecoin.io/mine/lotus/miner-troubleshooting/#error-failed-to-get-api-endpoint

**Comment by mrntidu** [comment]
https://docs.filecoin.io/mine/lotus/miner-setup/#miner-initialization 
  
https://docs.filecoin.io/mine/lotus/miner-setup/#starting-the-miner 

https://docs.filecoin.io/mine/lotus/miner-setup/#publishing-the-miner-addresses

**Comment by danpintilie** [comment]
Hi! I have the same problem now. The sync is complete, the miner is running, but I get the same error when I run any "lotus-miner" command. How did you fix it?

**Comment by andiz1014** [comment]
> Hi! I have the same problem now. The sync is complete, the miner is running, but I get the same error when I run any "lotus-miner" command. How did you fix it?

I restart the computer, and then the problem is solved :)

**Comment by Reiers** [comment]
If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
