### ISSUE TITLE
sched_worker.go has dead lock

### ISSUE THREAD

**Issue by gavin-ygy** [filecoin-project/lotus#5267]
**Describe the bug**
if the miner can't add new worker anymore.

**Version (run `lotus version`):**
v1.4.0
**Additional context**
sector-storage/sched_worker.go
func (sh *scheduler) runWorker(ctx context.Context, w Worker) error {
	info, err := w.Info(ctx)
	if err != nil {
		return xerrors.Errorf("getting worker info: %w", err)
	}

	sessID, err := w.Session(ctx)
	if err != nil {
		return xerrors.Errorf("getting worker session: %w", err)
	}
	if sessID == ClosedWorkerID {
		return xerrors.Errorf("worker already closed")
	}

	worker := &workerHandle{
		workerRpc: w,
		info:      info,

		preparing: &activeResources{},
		active:    &activeResources{},
		enabled:   true,

		closingMgr: make(chan struct{}),
		closedMgr:  make(chan struct{}),
	}

	wid := WorkerID(sessID)

	sh.workersLk.Lock()
	_, exist := sh.workers[wid]
	if exist {
		log.Warnw("duplicated worker added", "id", wid)

		sh.workersLk.Unlock()  //****************Gavin adding this line and fix the bug!

		// this is ok, we're already handling this worker in a different goroutine
		return nil
	}
       sh.workers[wid] = worker
	sh.workersLk.Unlock()
//...
}

**Comment by magik6k** [comment]
Good catch! Fixed in https://github.com/filecoin-project/lotus/pull/5251
