### ISSUE TITLE
How can I recover/reimport my sectors?

### ISSUE THREAD

**Issue by hopkinskong** [filecoin-project/lotus#5269]
**Describe the problem**

Recently my `lotus-miner` crashed with a corrupted database. I have successfully recreated it but I am unsure how to re-import sealed sectors (was in `Proving`) from my disk.

**Sectors status**

Output of `lotus-miner sectors status`:
`<No output, as I have yet to import my sectors>`

Note that I can find my sector via `lotus-miner storage find <sect_no>`, it is just not visible in `lotus-miner sectors list` as I think I have to re-import them back to the miner in some way.

** Code modifications **

N/A

**Version**

`lotus version 1.4.0+git.bb5a92e2f`

**Comment by ipfslab** [comment]
same issue

**Comment by cmartins88** [comment]
do you have any solutions you can share?
