### ISSUE TITLE
Add Piece Worker holds completed tasks until all Deals finish adding pieces

### ISSUE THREAD

**Issue by cwhiggins** [filecoin-project/lotus#5272]
I have switched to using an add piece worker, from having it tied to PC1 workers.  It seems to me that the AP worker does not send completed tasks out, so long as it is busy with other work. Maybe this is normal behavior, maybe a bug?

While adding data for deals, the AP worker does not send any completed tasks to next worker so long as it is continues to have more deals jobs to add. This can lead to a real back up if a miner is actually focused on making deals with clients. 

When an AP worker finishes adding the pieces for a deal, it should be sent to miner for staging in sector, not held on AP worker.

<pre>lotus version
Daemon:  1.4.0+git.e9989d0e4+api1.0.0
Local: lotus version 1.4.0+git.e9989d0e4</pre>

**Comment by cwhiggins** [comment]
part of conversation on slack, similar issue, I believe
https://filecoinproject.slack.com/archives/CEGN061C5/p1610272676025500

I found sector seal hangs on AP worker, if AP worker is adding deal data it will not do send other jobs. I think it may be linear, only taking jobs in queue, so if you have 1Tb of data, and you queued them all up to AP, it will take, probably 12 hours for them to finish before the seal job will come up.

Patrick - Factor8 Solutions  3 minutes ago
PC1 shoudl fetch waitdeals sectors as soon as the seal delay is timedout (edited) 

Chris  2 minutes ago
yes, i agree, but it seems to me data is still on AP worker some how. AP needs to release it but can't because it is busy adding data for deal.

**Comment by PatrickDeuse** [comment]
https://github.com/filecoin-project/lotus/pull/5309

if this is true it needs to be fixed before https://github.com/filecoin-project/lotus/pull/5309 makes sense to be implemented

**Comment by TippyFlitsUK** [comment]
Hi @cwhiggins 

Thanks for the report. The issue is outdated. 

If this is a issue in the current release - please open a new ticket.

Thank you !
