### ISSUE TITLE
VM.Call failure: failed to submit proof for bulk verification (RetCode=7)

### ISSUE THREAD

**Issue by unk1911** [filecoin-project/lotus#5278]
i'm trying to start up the lotus daemon,  and it seems to start up in the sense that i can run various commands like check for available miners and even try to create deals, but no deals actually get sealed, i believe it is connected to these errors related to "not enough gas",  can anyone explain what it means?  (i'm running it on the latest Ubuntu distro in a VM with 125GB of disk space and 16GB of RAM.  is the problem that it needs more RAM?)

```
2020-12-31T09:26:06.742-0500	WARN	vm	vm/runtime.go:376	vmctx send failed: to: f04, method: 8: ret: [], err: not enough gas: used=68752431, available=69343060, use=716340 (RetCode=7)
2020-12-31T09:26:06.742-0500	WARN	vm	vm/runtime.go:332	Abortf: failed to submit proof for bulk verification
2020-12-31T09:26:06.742-0500	WARN	vm	vm/runtime.go:145	VM.Call failure: failed to submit proof for bulk verification (RetCode=7):
    github.com/filecoin-project/specs-actors/v2/actors/builtin.RequireSuccess
        /home/unk1911/go/pkg/mod/github.com/filecoin-project/specs-actors/v2@v2.3.3/actors/builtin/shared.go:49

```

**Comment by verynohair** [comment]
I have the same problem. Have you solved it?

**Comment by unk1911** [comment]
no unfortunately i haven't figured this out. after looking at this closer, i'm not even sure if these errors are coming from my own side or are are arriving over RPC from other nodes/miners...

**Comment by Fatman13** [comment]
Anyone had looked into it yet? Any updates?

**Comment by Reiers** [comment]
Hi @unk1911 

> is the problem that it needs more RAM?
- Its was part of the issue at least. 
https://lotus.filecoin.io/lotus/install/prerequisites/#minimal-requirements

The issue is outdated. 

If you are still experiencing problems - please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you !
