### ISSUE TITLE
Provide storage miner with configurable path for offline deal data when staging for sealing.

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#5291]
Issue1: When importing data for an offline deal the fstmp files are placed directly in the LOTUS_MINER_PATH (possibly in a sealing folder, not sure - but for sure not in a subfolder) folder. that robs miners of the possibility to organize offline deals well.

Issue2: the fstmp filenames are not useful. 

**To Reproduce**
1. Run 'lotus-miner storage-deals import-data someCID /path/to/import/data.car'
2. See LOTUS_MINER_PATH

**Expected behavior**
The files in a folder one could link another disk/partition/location to. Files with a name connected to the deal/imported file-name

**Version (run `lotus version`):**
Daemon:  1.4.0+git.e9989d0e4+api1.0.0
Local: lotus-miner version 1.4.0+git.e9989d0e4

**Additional context**
Nothing critical...

**Comment by s0nik42** [comment]
Can these files being removed safely ?

**Comment by PatrickDeuse** [comment]
@s0nik42 they should get removed as soon as the deal goes to Active. just from watching terminal windows while sealing offline deals.

**Comment by s0nik42** [comment]
@ribasushi @jennijuju , is this going to be solved at some point ? my miner is now creating 15GB of logs a day!, millions of useless connections to peers and with slingshot ending, in 3 days it's almost going to double as I've got a lot of deals that will never be served. 

Thank you,

**Comment by frrist** [comment]
Exploring this code for the first time, going to leave some bread crumbs for anyone else interested in following along as I suspect some thoughtful design decisions will need to be made before proceeding with a solution.

1. The `lotus-storage-miner` has a single repo that is initialized in the location specified by `LOTUS_MINER_PATH`([code](https://github.com/filecoin-project/lotus/blob/7a78527fdeaa948b1fa4631d2738d2538db863f/cmd/lotus-storage-miner/init.go#L176-L205))

2. When the storage miner is instructed to `run`, a storage miner node is instantiated using the aforementioned repo ([code](https://github.com/filecoin-project/lotus/blob/7a78527fdeaa948b1fa4631d2738d2538db863fa/cmd/lotus-storage-miner/run.go#L145-L156))

3. If the default storage miner config values are used, then the storage miner will instantiate a Market's Subsystem via dependency injection. As part of this instantiation a `StoreageProvider` is created ([code](https://github.com/filecoin-project/lotus/blob/7a78527fdeaa948b1fa4631d2738d2538db863fa/node/builder_miner.go#L160))

4. The `StorageProvider` accepts a `LockedRepo` as one of its params. The repo injected here will be the same repo the storage miner was instantiated with in step 2. ([code](https://github.com/filecoin-project/lotus/blob/7a78527fdeaa948b1fa4631d2738d2538db863fa/node/modules/storageminer.go#L590-L609))

5. During the `StorageProvider` initilzation a `FileStore` is created. 
>A `FileStore` is used for storing temporary file data when handing off a deal to the Storage Miner. Once the Storage Miner reads a file from the `FileStore` and seals them into a sector the files are removed from the `FileStore`. 

-  A `FileStore` accepts a file system path as its only initialization param. The path passed to the `FileStore` is the path of the Repo created in step 2 ([code](https://github.com/filecoin-project/lotus/blob/7a78527fdeaa948b1fa4631d2738d2538db863fa/node/modules/storageminer.go#L601)). **This is where the problem described in the OP lies**

The first ask here is to provide miner operators with the ability to configure their miners to use a path that is different than `LOTUS_MINER_PATH`. This will require code changes in Lotus.

The second ask is for the storage provider to create more informative names. This will require code changes in go-fil-markets and I have filed https://github.com/filecoin-project/go-fil-markets/issues/583 to address this. @f8-ptrk @s0nik42 feel free to chime in over there with your preference for file names.

**Comment by f8-ptrk** [comment]
```
The first ask here is to provide miner operators with the ability to configure their miners to use a path that is different than LOTUS_MINER_PATH. This will require code changes in Lotus.
```

a subfolder in the LOTUS_MINER_PATH would be enough. doesn't need to be configurable - folders can just be linked to that location and the requirements of "using another location" would be fulfilled

**Comment by raulk** [comment]
This will likely be coming with the DAG store.

**Comment by frrist** [comment]
That's a much simpler change than the one I initially described. If that meets your needs, I will go with the simpler (subfolder) implementation instead.

**Comment by f8-ptrk** [comment]
it's not user friendly but at least reverts the current logic of how to achieve this

putting LOTUS_MINER_PATH on the target for the fstmp files and then link the rest of the miner into that folder.
