### ISSUE TITLE
Storage-deals list should show why deals were rejected

### ISSUE THREAD

**Issue by NSC-FIL** [filecoin-project/lotus#5295]
In lotus-miner storage-deals list, when storage deal requests are rejected for not meeting miner ask criteria (i.e. price, size, etc.), the log simply shows as StorageDealError.  It would be helpful to see the reason a deal was rejected.

**Comment by jennijuju** [comment]
An option is to add another error code - reasoning table

**Comment by NSC-FIL** [comment]
Also the storage-deals list doesn't the accurate state of offline deals that have expired.  Currently, if a deal expires, the list shows  StorageDealAwaitingPreCommit or StorageDealWaitingForData.  Should show something about deal expiry.

**Comment by TippyFlitsUK** [comment]
Hi @NSC-FIL 

Many suggestions mentioned have been resolved with the introduction of Boost and through services such as CID Gravity.

Please open a new ticket using the [enhancement request template](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) if you feel it is still relevant to newer versions of Lotus

Thank you!
