### ISSUE TITLE
Can not push mpool message to chain?

### ISSUE THREAD

**Issue by killelder** [filecoin-project/lotus#5305]
**Describe the bug**

I use lotus-miner init and I saw there is cid in my screen
but I can not find this message in FILFOX

2021-01-07T17:42:51.860+0800    INFO    main    lotus-storage-miner/init.go:699 Pushed CreateMiner message: bafy2bzacecssxcvuizqegyx25t6w2cw3og5atvs6ltq3xehmj3xwqngju6pec
2021-01-07T17:42:51.860+0800    INFO    main    lotus-storage-miner/init.go:700 Waiting for confirmation

Even I use send FIL to another account, FILFOX can not find my trade message

**To Reproduce**
1. lotus-miner init
2. lotus send xxxxx 0.5

**Expected behavior**
I can find my init message on FILFOX.
and I did find my message in previous day, but I can not found my message on FILFOX today

**Version (run `lotus version`):**
Local: lotus version 1.4.0+git.bb5a92e

**Comment by PatrickDeuse** [comment]
please join the slack an search for "mpool replace" you will find plenty of answers to solve this problem of stuck messages in the mpool

**Comment by Reiers** [comment]
Hi @killelder 

Solution to the issue can be found [here.](https://lotus.filecoin.io/docs/storage-providers/message-pool/#replacing-messages-in-the-pool)

Closing ticket.
