### ISSUE TITLE
Unable to create a deal

### ISSUE THREAD

**Issue by ciwines** [filecoin-project/lotus#5322]
**Describe the bug**
When I try to make to deal to upload a file, i receive back this error:  
`ERROR: resolve address t1y4cyp35pllabealkgiip7cgbgbz667ufzjlmqby: actor not found`

**To Reproduce**
I have a daemon running in background.

1. Run 'lotus client import file.txt'
2. Run 'lotus client deal'

**Expected behavior**

**More info**
The ouput of 'lotus client deal' is this:
`Data CID (from lotus client import): bafkqadtgnfwgkideneqha4tpozqqu
.. calculating data size
Deal duration (days): 300
ERROR: resolve address t1y4cyp35pllabealkgiip7cgbgbz667ufzjlmqby: actor not found`

**Lotus version**
`Daemon:  1.3.0+git.9b47058cf+api1.0.0
Local: lotus version 1.3.0+git.9b47058cf`

**Additional context**
I'm using Ubuntu 20.10 and I'm using the ntwk-calibration branch

**Comment by magik6k** [comment]
The address t1y4cyp35pllabealkgiip7cgbgbz667ufzjlmqby doesn't exist on-chain / has no balance, so it can't make deals. To fix this, you need to 'initialize' the address on-chain by sending some funds to it (which you'll need for making deals anyways)
