### ISSUE TITLE
Ugly error message when rejecting transation on ledger

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#5335]
If i attempt to sign a transaction with my ledger, but then decide to reject when reviewing it on the device, i get a not great error message:
```
why@sirius ~/c/lotus (master)> ./lotus send --from=f1LEDGER f1MYBANK 0.01

ERROR: failed to sign message: [APDU_CODE_COMMAND_NOT_ALLOWED] Command not allowed (no current EF)
```

**Comment by rjan90** [comment]
Reproduced this error message, and it seems like this error messages comes from the Ledger Filecoin app. I have asked in https://github.com/Zondax/ledger-filecoin/issues/108 if it would be possible to change the error message to something more describing.

**Comment by Kubuxu** [comment]
We could also handle it better on our side. IMO the Zondax Ledger API itself doesn't need to provide better error messages.
