### ISSUE TITLE
Recovering a lost private key

### ISSUE THREAD

**Issue by huangmeibao** [filecoin-project/lotus#5344]
Hi, Dr.
I think I need some help.

This is my actor address ：  f27d7mzdscpkcrjjycx3fmyqnparesrhdynyxjd3a
This is my owner  address ：  f3xfx3owiur7mkwu5uhsjhs2eoof2wqzidq5wdpmjozaz4f66565vaimvqyl7c2iqonsy5psuoibd7mfgdxp3a
I lost actor address private key，How can I extract the coins inside to the Owner address ?

I hope to get your help. Thank you very much

**Comment by magik6k** [comment]
See comments in https://github.com/filecoin-project/lotus/issues/4571

**Comment by magik6k** [comment]
Alternatively, if you have a backup you can use the `lotus wallet import` command

**Comment by huangmeibao** [comment]
No backup yet. Attempts to restore data, but fails  
Can't use the owner to get back? I thought the owner could control everything, crying

**Comment by PatrickDeuse** [comment]
the owner cannot get you back other lost private keys. you can change the the addresses for a miner with the owner private key - that's it

**Comment by rjan90** [comment]
I think that this issue can be closed now, since this issue has been answered. #rengjøring
