### ISSUE TITLE
window post failed

### ISSUE THREAD

**Issue by nickboot** [filecoin-project/lotus#5351]
**Describe the bug**
runPost failed: running window post failed

**To Reproduce**
ERROR	storageminer	storage/wdpost_run.go:103	runPost failed: running window post failed:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
        /root/lotus/storage/wdpost_run.go:613
  - coordinate(s) do not lie on the curve

    Stack backtrace:
       0: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next
       1: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
       2: storage_proofs_core::compound_proof::CompoundProof::circuit_proofs
       3: storage_proofs_core::compound_proof::CompoundProof::prove
       4: filecoin_proofs::api::post::generate_window_post
       5: filecoin_proofs_api::post::generate_window_post_inner
       6: filecoin_proofs_api::post::generate_window_post
       7: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
       8: ffi_toolkit::catch_panic_response
       9: fil_generate_window_post
      10: _cgo_8d8f391b4e17_Cfunc_fil_generate_window_post
                 at /tmp/go-build/cgo-gcc-prolog:555
      11: runtime.asmcgocall
                 at /usr/local/go/src/runtime/asm_amd64.s:656
    github.com/filecoin-project/filecoin-ffi.GenerateWindowPoSt
    	/root/lotus/extern/filecoin-ffi/proofs.go:587
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).GenerateWindowPoSt
    	/root/lotus/extern/sector-storage/ffiwrapper/verifier_cgo.go:45
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost
    	/root/lotus/storage/wdpost_run.go:591
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runGeneratePoST
    	/root/lotus/storage/wdpost_run.go:101
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).startGeneratePoST.func1
    	/root/lotus/storage/wdpost_run.go:85
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1374

ERROR	storageminer	storage/wdpost_run.go:47	Got err %!w(*xerrors.wrapError=&{running window post failed 0xc0290757e0 {[7557291 22555530 22537029]}}) - TODO handle errors

**Version (run `lotus version`):**
lotus-miner version 1.4.0+git.e9989d0e4

**Comment by rjan90** [comment]
I think this issue can be closed, as the issue with coordinates not laying on the curve has been fixed. #rengjøring
