### ISSUE TITLE
fallocate does not work with some versions of ZFS.

### ISSUE THREAD

**Issue by Elycin** [filecoin-project/lotus#5365]
**Describe the bug**
https://github.com/filecoin-project/lotus/blob/60d442e36a6cc6b32da3fa7541537cfee3b7b050/extern/sector-storage/ffiwrapper/partialfile.go#L67

[ZFS has basic fallocate support](https://github.com/openzfs/zfs/pull/10408) but is generally not compatible in most active distributions, in the case where a user is using a zfs partition to store their miner data, they will not be able to pledge with filecoin.

**To Reproduce**
1. Create a ZFS Pool
2. Set pledge location to pool mountpoint
3. Attempt to pledge.

**Expected behavior**
Lotus should be able to allocate storage space.

**Screenshots**
N/A

**Version (run `lotus version`):**
```
root@filecoin:~/lotus# ./lotus-miner version
Daemon:  1.4.0+git.476df9917+api1.0.1
Local: lotus-miner version 1.4.0+git.476df9917

root@filecoin:~/lotus# ./lotus version
Daemon:  1.4.0+git.476df9917+api1.0.0
Local: lotus version 1.4.0+git.476df9917
```

**Additional context**
Miner Log:
```
{"level":"debug","ts":"2021-01-17T07:46:23.119Z","logger":"advmgr","caller":"sector-storage/worker_local.go:129","msg":"acquired sector {{132523 15} 8} (e:0; a:1): {{0 0} /root/.lotus/sealing/unsealed/s-t0132523-15  }"}
{"level":"warn","ts":"2021-01-17T07:46:23.130Z","logger":"ffiwrapper","caller":"ffiwrapper/partialfile.go:70","msg":"could not allocated space, ignoring: operation not supported"}
```

**Why ZFS?**   
In certain cases, it's more logical to use over mdadm w/ HBA or RAID card when you want to create a massive raid. I personally have a 24 drive storage array that I'd love to use with filecoin but cannot due to this constraint. I think it could be beneficial to support a widely used filesystem.

**Newer versions of zfs support fallocate, why can't you upgrade?**
Most distributions in their stable repositories are extremely slow to update. The feature was pushed to the master branch and released in version 2.0 which is still very new.

**Comment by PatrickDeuse** [comment]
some details in this thread

https://filecoinproject.slack.com/archives/CEGN061C5/p1610866892160000

**Comment by magik6k** [comment]
That logged error should be ignored:
https://github.com/filecoin-project/lotus/blob/60d442e36a6cc6b32da3fa7541537cfee3b7b050/extern/sector-storage/ffiwrapper/partialfile.go#L71

Fallocate is just an optimization to reduce file fragmentation. Pledging should work without it - is there anything else other than that log which suggests that pledging sectors doesn't work?
