### ISSUE TITLE
uninstall lotus from the computer

### ISSUE THREAD

**Issue by BATTLEROYALXS** [filecoin-project/lotus#5416]
**Describe the bug**

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by BATTLEROYALXS** [comment]
Hello it is possible a documentation of how to remove the lib ?

After install it on my nvme it takes all the storage and i want to remove it please.

**Comment by PatrickDeuse** [comment]
there is almost nothing installed.

if you ran `make install` then there are 3 binaries moved to `/usr/local/bin` `lotus`, `lotus-miner` and `lotus-worker`. if not then just delete the `lotus` folder git created when cloning the repo

see https://github.com/filecoin-project/lotus/blob/master/Makefile#L110 and the following lines

if you have already ran some of the binaries then they will have created folders, per default:

`~/.lotus` for the lotus (daemon)
`~/.lotusminer` for the lotus-miner

you'd know about the directory for the worker if you had one...

remove the dependencies as by your operating systems recommendations.

**Comment by BATTLEROYALXS** [comment]
so there is no proper way present in the Makefile ?

Alright no problem i was afraid to do something wrong thx for the answer and the work.

**Comment by PatrickDeuse** [comment]
nope, there is no way to reverse the install (basically a fancy copy -> https://linux.die.net/man/1/install ) in the Makefile. until this gets properly packaged for distribution via packet managers the installation needs to be reverted by hand.

**Comment by rjan90** [comment]
I think this issue can be closed as the question has been properly answered by f8-ptrk. #rengjøring

**Comment by Reiers** [comment]
**Solution provided by @f8-ptrk** 

Closing ticket.

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
