### ISSUE TITLE
Repo should contain version file

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#543]

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/lotus/blob/7b3f1c2b85a0eff2d7f8677aaf79da6dfac07bd9/build/version.go

**Comment by arajasek** [comment]
@jennijuju ^I don't think that's what this issue is describing -- I think the ask is that the Lotus storage repo itself should be (capable of being) versioned

**Comment by frrist** [comment]
Couple questions:
1. Does this issue expect version validation? e.g. should we abort starting the daemon if there is a version mismatch or no version file at all? Leads to -> 
2. How does the upgrade case look? e.g. If a daemon starts up for the first time after upgrading to this code should there be special handling in place to handle the case of there being no version file (something like a migration)?

**Comment by jennijuju** [comment]
Version validation would be nice but i think we should start a new ticket for that, starting with listing all the version need to be validated before fully start a daemon/miner process. That being said i think it's out of the scope for this ticket.

**Comment by frrist** [comment]
From a conversation with Magik: the version file in the repo should be separate from other lotus versions (build version, API version, etc) and start with `1`

**Comment by TippyFlitsUK** [comment]
Hi @magik6k 

This looks like a reminder. Should we close it or keep it open?
