### ISSUE TITLE
FR - miner side fast-retrieval flags

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#5435]
When taking deals the deal client can specify "fast retrieval" and then expects the unsealed sector to be available on the miner to save the time it needs to unseal the sector when retrieving.

the miner right now has no option to opt out or manually force an opt in.

it would be nice to have a flag for the miner: --enable-fast-retrieval 

- 0: turn fast retrieval off, never store unsealed copies
- 1: turn fast retrieval on, always store unsealed copies
- 2: let the client choose

as interesting the flag for taking deals would be sibling flag for retrieval deals that control what retrieval deals regarding fast retrieval should be accepted (or rejected)

**Comment by ribasushi** [comment]
@PatrickDeuse done
https://github.com/filecoin-project/lotus/pull/5433

**Comment by ribasushi** [comment]
@PatrickDeuse though there doesn't seem to be a `never keep` interpretation of the config - please add extra comments on #5433 when time permits

**Comment by PatrickDeuse** [comment]
sure @ribasushi

**Comment by Reiers** [comment]
Hi 

Thanks for the report. This is merged in the latest release.

Closing ticket.

**Comment by hyunmoon** [comment]
@Reiers @f8-ptrk 
I don't understand why this issue was flagged as merged.
All I see is **AlwaysKeepUnsealedCopy** on both lotus-miner and boost.
What happened?
