### ISSUE TITLE
[Feature Request] - Manually generate unsealed sector

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#5436]
With unsealing taking up a lot of resources it would be good to have a command to manually trigger the unsealing of a sector to be able to schedule it better. 

incoming retrieval deals triggering the unsealing might cause a "traffic jam" while at times the unsealing worker will possibly be idle for extended periods of time. A manual command would allow to manage resources better.

**Comment by Reiers** [comment]
Hi @f8-ptrk 

Thanks for this feature request. I have add labels and will assign it to the right team for analysis.

**Comment by donkabat** [comment]
Any progress?

**Comment by rjan90** [comment]
Closed with: https://github.com/filecoin-project/lotus/pull/10626
