### ISSUE TITLE
lotus client retrieve command doesn't download file in the correct dir when using relative paths

### ISSUE THREAD

**Issue by nonsense** [filecoin-project/lotus#5440]
**Describe the bug**
When trying to do a retrieval deal with a relative path, for example:
```
lotus client retrieve --miner f0127896 bafykbzacebkcdeogmsk35wwgicuuh6chwaxp2wtpn47kfsp3bwchm44vyl4sa sample.txt
```

The client is not downloading the file in the current working directory, but actually downloads the file in the directory where `lotus` binary was compiled.

**To Reproduce**
1. Go to directory other than the one where `lotus` binary was compiled.
2. Try to make a retrieval deal with a relative path for the output file, and check where it is being downloaded.

**Expected behavior**
I expect that `sample.txt` gets downloaded into my current working directory, and not in the directory where Lotus was compiled.

**Version (run `lotus version`):**
```
lotus version 1.4.0+git.84a91331c
```

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system, [which reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and has been completely removed from the code:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
