### ISSUE TITLE
Client memory usage is high when executing retrieval deal

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#5441]
Anton noticed that memory usage is high when executing  a retrieval deal (~32 GB size).  It appears that the data is first transferred into memory before being flushed to disk.

Ideally transfers should be regularly flushed to disk to reduce client resource requirements - especially when executing multiple retrieval deals.

Related to #4877 
cc: @hannahhoward

**Comment by raulk** [comment]
This should be fixed by graphsync v1.6.0, right, @dirkmc?

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
