### ISSUE TITLE
Miner accepts deal even if there's not enough collateral in miner to service the deal.

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#5444]
v1.4.1

Current behavior:  The miner accepts a deal and starts the data transfer.  After the data transfer is complete, it checks and aborts the deal because of insufficient funds.

Desired: It would be helpful to issue a warning or check funds before initiating the data transfer if the miner doesn't have the resources to accept the deal.

Open Questions:
1) We have a market actor concept when proposing deals.  Should we have an equivalent concept for miners when the accept a deal and are waiting for the data transfer (essentially lock the funds?)
2) Does this open up risks in terms of a DoS attack if funds are locked since some deals maybe aborted?

**Comment by PatrickDeuse** [comment]
> Current behavior: The miner accepts a deal and starts the data transfer. After the data transfer is complete, it checks and aborts the deal because of insufficient funds.

all that is off chain logic. the funds are needed when the deal gets published and not when accepted or transferred.
 
the miner should initiate an AddBalance message to add funds before the publish deals message - and as far as i know it is doing exactly that if there aren't enough funds to lock for a deal in the market actor for the miner

> Open Questions:

> 1. We have a market actor concept when proposing deals. Should we have an equivalent concept for miners when the accept > a deal and are waiting for the data transfer (essentially lock the funds?)
> 2. Does this open up risks in terms of a DoS attack if funds are locked since some deals maybe aborted?

1. you shouldn't touch any funds a miner rightfully owns and "lock" them. (whatever you mean with 'lock the funds'). the funds will get locked when the publish message gets on chain.
2. yes it does. an attacker makes enough deals and then transfers the data with snailmail-speed over to the miner. possibly "locking" funds for hours, days - even weeks

but still not sure what you mean with "lock funds"

**Comment by PatrickDeuse** [comment]
a client can always demand the deal to be published before he sends the data. what will happen is that miners will let the client pay for the publish deals message since they do not have the data before paying, right now, ~$6 to get the message on chain.

**Comment by PatrickDeuse** [comment]
so this is not an implementation problem but a specifications problem of how to define when a deal is accepted. right now, rightfully, the deal isn't "Accepted" before both parties have a message with they signature in/on it on chain. 

we you want to implement a soft lock on miners market balances before the deal is on chain - feel free to do so, but make it optional.

**Comment by rjan90** [comment]
It seems like a fix for this issue has been merged into Lotus, so this issue can probably be closed now? #rengjøring

**Comment by Reiers** [comment]
Merged.

Closing ticket.
