### ISSUE TITLE
Mpool method to estimate gas price

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#548]
Something like `MpoolEstimateGasPrice(likelyhoodOfInclusion, maxWait)`

**Comment by magik6k** [comment]
Also other permutations:
* `MpoolEstimateLikelyhoodOfInclusion(gasPrice, wait)`
* `MpoolEstimateWait(likelyhoodOfInclusion, gasPrice)`

**Comment by Schwartz10** [comment]
Hey @magik6k! Do you have any sense of when this might get implemented? Aiming for before mainnet launch?

**Comment by whyrusleeping** [comment]
This has been resolved in #1575
