### ISSUE TITLE
lotus-bench reports 'Inconsistent tree data' when generate-winning

### ISSUE THREAD

**Issue by tinker806** [filecoin-project/lotus#5488]
It's ok when the sector size is 2KiB, but when it comes to 32GiB,  the lotus-bench reports 'Inconsistent tree data' when generate-winning and I can't find it in the code. Why this is happening and how can i solve it?
![bugreporting](https://user-images.githubusercontent.com/73171958/106382139-8affef00-63f8-11eb-98d8-911d4019c7e5.jpg)

**Comment by rjan90** [comment]
Hi. Can this issue be closed now, or are you still experiencing this? #rengjøring
