### ISSUE TITLE
 PreCommitSector message gas used is to high

### ISSUE THREAD

**Issue by luhui123123** [filecoin-project/lotus#5490]
**Describe the bug**
 f03482 PreCommitSector message gas used is to high.

url:
https://filfox.info/en/message/bafy2bzacebjsopw3tquylaj2ljsvvvxpgr6zfcxhazyk5uv7txxuvdcldz6fo

**Comment by luhui123123** [comment]
help

**Comment by rjan90** [comment]
Hi! Can this issue be closed now? #rengjøring. If not, please elaborate more on what the actual issue is here.

**Comment by Reiers** [comment]
**The message seems fine.** Check your limits in config.toml. 
With no more information, there's not much to do about this issue. 

Closing ticket. 

If you still want to investigate this problem. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
