### ISSUE TITLE
Allow multiple miners to register to a single lotus daemon instance

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#550]
Right now we have it set up so that only one storage miner can use a lotus daemon, we have been intended to fix this for a little while, Just fililng an issue here so that we can track the work.

**Comment by Lindensys** [comment]
Is this about the "owner worker distinctioin“？

**Comment by sprwig** [comment]
Can a storage miner adapter multiple fullnode?

**Comment by magik6k** [comment]
This is now done
