### ISSUE TITLE
FR - lotus-miner *-deals set/get-ask custom information

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#5509]
Right now miners are limited to set a fixed ask price for online deals. This doesn't represent the reality of how deals are currently conducted on the network. Prices miners ask for vary between different clients based on an array of factors and the miner is, right now, unable to communicate this automatically to possible clients.

Since the needs miners have for something like this are hard to combine in a fixed set of features the idea is to have the possibility to set the ask price/s to "custom" and offer a field the miner can input contact details/or any other information he wants the possible client to know, eg.

`lotus-miner storage-deals set-ask --custom --custom-info "1-5FIL/32GB/year, depending on volume - please see https://what.ever/deals.html`

right now custom settings can only be enforced via filters - but those are invisible to the storage clients. having an option to flag custom settings will help clients to get a better overview of the available storage options the network offers.

**Comment by f8-ptrk** [comment]
@jennijuju  regarding the spwg NA call this morning

it was targeted at custom prices when opened, a lot of work has been done already to move in the direction of dynamic pricing with clients - but for communicating terms of use etc. this could be a fast way to implement "something" while real solutions are being worked out -be it on chain or off chain

**Comment by f8-ptrk** [comment]
even more: an external script call that allows to flip some switches to customize the answer

**Comment by raulk** [comment]
@f8-ptrk I was just reviewing this, and the request talks about filter setting on one hand, customisation of responses, possibly an external script, and a freetext/comments field. I'm trying to gain clarity on the actual requirement(s).

Would a feature similar to [dynamic retrieval pricing](https://docs.filecoin.io/mine/lotus/dynamic-retrieval-pricing/#default-policy) with its `external` mode work well for pricing storage deals?

**Comment by jennijuju** [comment]
> @jennijuju regarding the spwg NA call this morning
> 
> it was targeted at custom prices when opened, a lot of work has been done already to move in the direction of dynamic pricing with clients - but for communicating terms of use etc. this could be a fast way to implement "something" while real solutions are being worked out -be it on chain or off chain

@f8-ptrk Please correct me if I'm wrong, but the focus of the ticket has shifted from dynamic pricing to introduce a plain text field/data structure for storage miners to set term of service in StorageAsk, is that right? if so - is there any desired data format?

**Comment by rjan90** [comment]
Closing this ticket as the legacy lotus-miner markets subsystem has been deprecated.
