### ISSUE TITLE
handof errors are shadowed in markets

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#5516]
https://github.com/filecoin-project/go-fil-markets/blob/6f3bc83ee27227f9d11091c5a768d7059db7a1e0/storagemarket/impl/providerstates/provider_states.go#L323-L329

`err` will always be `write |1: broken pipe` when deal handoff fails, meaning that the real error - `packingErr` is not visible to the user. It's also very confusing.

**Comment by dirkmc** [comment]
That *is* confusing, I think it's important to get into the next release, I'll fix now
