### ISSUE TITLE
Gas values via command line flags ALWAYS overrides the estimated values 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#5522]
- [ ] in `mpool replace --auto` should forbid taking customized gas values

**Comment by PatrickDeuse** [comment]
isn't the whole purpose of --auto that they are not set by hand?

how would that work? set them auto first and then overwrite them? then whats the purpose of auto? 

`--auto` and `--gas-feecap` / `--gas-premium` should not be allowed in the same command!
