### ISSUE TITLE
Gasses for `mpool replace` message is not bounded by `DefaultMaxFee` in lotus config

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#5525]
`mpool replace` message is not bounded by `DefaultMaxFee` in lotus config and may cause unexpected cost for those who thought it is. The gases should be bounded by DefaultMaxFee unless a `--max-fee` is passed in.

**Comment by PatrickDeuse** [comment]
the replaced message is not a message the daemon created. i do not see a reason to apply the config of the daemon on the client
