### ISSUE TITLE
Postfix pubsub topics with genesis cid

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#553]
This ensures better node separation on the live network

**Comment by anorth** [comment]
See https://github.com/filecoin-project/specs/issues/477 and https://github.com/filecoin-project/specs/pull/456

A human-readable network name is much more ergonomic than a CID, and putting it in the Init actor's state achieves the desired genesis block distinction.

**Comment by whyrusleeping** [comment]
I think we can close this now
