### ISSUE TITLE
Bus Error(Core dumped) when add lots of sectors in a short time

### ISSUE THREAD

**Issue by zzx234234** [filecoin-project/lotus#5531]
**Describe the bug**
I run a localnet with 512MiB sectors and pledge lots of sectors in a very short time (using a script), then this error occured in minutes.

it seems this error caused by multicore addpiece. my cpu has 112 cores, when adding more than 20 pieces in the same time, lotus creates tens of thousands threads to do the work and receive SIGSEGV at __memmove_avx_unaligned_erms().

I revert /extern/sector-storage/ffiwrapper/sealer_cgo.go before #5320 , there's no error

**To Reproduce**
run a localnet with 512MiB sectors
pledge 100 sectors in a short time

**Version (run `lotus version`):**
since #5320

**Comment by Reiers** [comment]
@zzx234234 Hi

Well if you throw to many sectors at your miner or worker it will stop - shutdown with:  `Bus Error(Core dumped)`
My guess is that your CPU has 56 cores, and 56 threads - total 112.

> when adding more than 20 pieces in the same time, lotus creates tens of thousands threads to do the work and receive SIGSEGV at __memmove_avx_unaligned_erms().

- If you want utilize multicore then you can run max 18 AP jobs at once. 
If you dont have the environment `FIL_PROOFS_USE_MULTICORE_SDR=1` set, then you can throw 56 AP jobs at your CPU at once. 

I dont see this as an issue - just dont pledge more sectors than your system can handle.

If you are still experiencing problems, ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you !
