### ISSUE TITLE
WaitDealsDelay not honoured

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#5542]
**Describe the bug**
I have a sector in WaitDeals state. In order to kick it sooner I set WaitDealsDelay = "0h5m0s" and restarted the miner. Now it's been 15 min it's still in WaitDeals. Isn't it supposed to go to PC1 after 5 minutes?

**Comment by TippyFlitsUK** [comment]
You can't change the delay for an already existing WaitDeals sector. All new WaitDeals sectors will observe the new 5 minutes delay but any WaitDeals sectors created before the config.toml change and miner restart will observe the previous settings.
