### ISSUE TITLE
Increase default gas fee values based on network situation

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#5543]
Current default gas fee values are setting a too low upper bound limit for messages fee caps and is causing the messages can not be landed in the network in any reasonable time frame without replacing the message or changing the configuration constantly. We need to re-evaluate and update the values so that people are using the default settings can use the network.

Todo:

- [ ] figure out the right values base on the network situation
- [ ] update the fees

**Comment by PatrickDeuse** [comment]
how low the gasfeecap value is depends on how the vm estimates the gas-limit. 

gas-limit * gasfeecap = message cost (very rough...)

a*b=c 
d*e=c

if d > a then e < b. with c being the value in the config.

so a send msgs gets 11nFIl gasfeecap with default settigns a withdraw gets 0.006nFIL gasfeecap. 

i watch our precom's constantly and they can vary between accepting 4nFIl and 2.3 nFIL depending on the gas-limit the vm gives them.

**Comment by dirkmc** [comment]
Related: https://github.com/filecoin-project/lotus/discussions/5541

**Comment by PatrickDeuse** [comment]
he just set the gas-limit by hand and it failed @dirkmc

**Comment by ribasushi** [comment]
( DISCLAIMER: I am not proposing a specific number, not my call )

When doing some retrieval work last week, at the ~avg 5nfil basefee I had to set my config to `DefaultMaxFee = "0.08 FIL"` for payment channels to get established.

**Comment by PatrickDeuse** [comment]
@ribasushi when do payment chans send their messages to the chain?

**Comment by jennijuju** [comment]
> @ribasushi when do payment chans send their messages to the chain?

Could we please create a separate discussion q&a for this, unless this circles back to something around default gas fees?

**Comment by arajasek** [comment]
@raulk Can this be subsumed into broader "make message sending work"?

**Comment by BigLep** [comment]
I assume "make message sending work" is https://github.com/protocol/web3-dev-team/pull/15
