### ISSUE TITLE
above 1.4.1,Big  bug in sealing 

### ISSUE THREAD

**Issue by bugxzhu** [filecoin-project/lotus#5545]
**Describe the bug**
above 1.4.1，P2 always failed ！！！

**To Reproduce**
1. Run 'lotus-bench sealing  --storage-dir=/home/lotus_user --sector-size 512MiB  > /home/lotus_user/run3.log 2>&1  &'
2. See error
   2021-02-07T02:16:55.458 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   storing labels on disk
2021-02-07T02:16:55.713 INFO storage_proofs_porep::stacked::vanilla::create_label::multi >   generated layer 2 store with id layer-2
2021-02-07T02:16:55.771 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:finish: SectorId(0)
2021-02-07T02:16:55.771 INFO filcrypto::proofs::api > seal_pre_commit_phase1: finish
2021-02-07T02:16:55.771Z	INFO	lotus-bench	lotus-bench/main.go:573	[0] Running replication(2)...
2021-02-07T02:16:55.771 INFO filcrypto::proofs::api > seal_pre_commit_phase2: start
2021-02-07T02:16:55.771 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:start
2021-02-07T02:16:55.771 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:finish
2021-02-07T02:16:55.771 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:start
2021-02-07T02:16:55.771 TRACE filecoin_proofs::api::seal > seal phase 2: base tree size 33554431, base tree leafs 16777216, rows to discard 7
2021-02-07T02:16:55.771 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase2
2021-02-07T02:16:55.771 TRACE storage_proofs_porep::stacked::vanilla::proof > transform_and_replicate_layers
2021-02-07T02:16:55.771 TRACE storage_proofs_porep::stacked::vanilla::proof > nodes count 16777216, data len 536870912
2021-02-07T02:16:55.771 TRACE storage_proofs_porep::stacked::vanilla::proof > is_merkle_tree_size_valid(16777216, BINARY_ARITY) = true
2021-02-07T02:16:55.771 TRACE storage_proofs_porep::stacked::vanilla::proof > is_merkle_tree_size_valid(16777216, 8) = true
2021-02-07T02:16:55.771 TRACE storage_proofs_porep::stacked::vanilla::proof > tree_r_last using rows_to_discard=2
2021-02-07T02:16:55.771 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the GPU
2021-02-07T02:16:55.771 INFO storage_proofs_porep::stacked::vanilla::proof > Building column hashes
2021-02-07T02:16:55.773 INFO neptune::triton::cl > getting default futhark context
2021-02-07T02:16:55.773 INFO neptune::triton::cl > getting context for ~Index(0)
2021-02-07T02:16:55.773 TRACE storage_proofs_porep::stacked::vanilla::proof > processing config 1/1 with column nodes 800000
2021-02-07T02:16:55.947 TRACE storage_proofs_porep::stacked::vanilla::proof > node index 800000/800000/16777216
2021-02-07T02:17:05.775 DEBUG rust_gpu_tools::opencl::utils > loaded devices: {}
thread '<unnamed>' panicked at 'failed to create ColumnTreeBuilder: ClError(BusIdNotAvailable)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.4.0/src/stacked/vanilla/proof.rs:516:23
stack backtrace:
   0:          0x1f1dac0 - std::backtrace_rs::backtrace::libunwind::trace::he85dfb3ae4206056
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:          0x1f1dac0 - std::backtrace_rs::backtrace::trace_unsynchronized::h1ad28094d7b00c21
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:          0x1f1dac0 - std::sys_common::backtrace::_print_fmt::h901b54610713cd21
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys_common/backtrace.rs:79
   3:          0x1f1dac0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb0ad78ee1571f7e0
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys_common/backtrace.rs:58
   4:          0x1f8c27c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/core/src/fmt/mod.rs:1080
   5:          0x1f0f772 - std::io::Write::write_fmt::hf7b7d7b243f84a36
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/io/mod.rs:1516
   6:          0x1f2289d - std::sys_common::backtrace::_print::hd093978a5287b8ff
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys_common/backtrace.rs:61
   7:          0x1f2289d - std::sys_common::backtrace::print::h20f46787581d56d7
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys_common/backtrace.rs:48
   8:          0x1f2289d - std::panicking::default_hook::{{closure}}::h486cbb4b82ffc357
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:208
   9:          0x1f22548 - std::panicking::default_hook::h4190c9e3edd4d591
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:227
  10:          0x1f230c1 - std::panicking::rust_panic_with_hook::h72e78719cdda225c
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:577
  11:          0x1f22c69 - std::panicking::begin_panic_handler::{{closure}}::h8bd07dbd34150a96
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:484
  12:          0x1f1df4c - std::sys_common::backtrace::__rust_end_short_backtrace::hdb6b3066ad29028a
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys_common/backtrace.rs:153
  13:          0x1f22c29 - rust_begin_unwind
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:483
  14:          0x1f885a1 - core::panicking::panic_fmt::hb15d6f55e8472f62
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/core/src/panicking.rs:85
  15:          0x1f88213 - core::option::expect_none_failed::he492a18657d97593
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/core/src/option.rs:1234
  16:          0x163b765 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h940cd86515d1cc71
  17:          0x1fc7cde - std::panicking::try::h932b2672f9c04bcb
  18:          0x179fc19 - <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::hb136c87ad705cf2c
  19:          0x1eab481 - rayon_core::registry::WorkerThread::wait_until_cold::hd677f2fc93300658
  20:          0x1ea6f24 - rayon_core::scope::ScopeBase::steal_till_jobs_complete::h936fa42c02e8ad82
  21:          0x1642dbd - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc56657bd389f8b72
  22:          0x17a93f6 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h45d0ef70520df854
  23:          0x1eab481 - rayon_core::registry::WorkerThread::wait_until_cold::hd677f2fc93300658
  24:          0x1ea96c2 - rayon_core::registry::ThreadBuilder::run::h055ee17e713b5ed1
  25:          0x1eaf6f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h39369de0c1c71746
  26:          0x1eb0c24 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha9f50c0602ee0218
  27:          0x1f319fa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1080dfe0ef616bdf
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/alloc/src/boxed.rs:1042
  28:          0x1f319fa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd2747e1f2d5cec32
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/alloc/src/boxed.rs:1042
  29:          0x1f319fa - std::sys::unix::thread::Thread::new::thread_start::hd0f336b4ef6808a7
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys/unix/thread.rs:87
  30:     0x7f9149a316db - start_thread
  31:     0x7f914a31071f - __clone
  32:                0x0 - <unknown>
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.4.0/src/stacked/vanilla/proof.rs:502:34
stack backtrace:
   0:          0x1f1dac0 - std::backtrace_rs::backtrace::libunwind::trace::he85dfb3ae4206056
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:          0x1f1dac0 - std::backtrace_rs::backtrace::trace_unsynchronized::h1ad28094d7b00c21
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:          0x1f1dac0 - std::sys_common::backtrace::_print_fmt::h901b54610713cd21
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys_common/backtrace.rs:79
   3:          0x1f1dac0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb0ad78ee1571f7e0
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys_common/backtrace.rs:58
   4:          0x1f8c27c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/core/src/fmt/mod.rs:1080
   5:          0x1f0f772 - std::io::Write::write_fmt::hf7b7d7b243f84a36
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/io/mod.rs:1516
   6:          0x1f2289d - std::sys_common::backtrace::_print::hd093978a5287b8ff
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys_common/backtrace.rs:61
   7:          0x1f2289d - std::sys_common::backtrace::print::h20f46787581d56d7
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys_common/backtrace.rs:48
   8:          0x1f2289d - std::panicking::default_hook::{{closure}}::h486cbb4b82ffc357
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:208
   9:          0x1f22548 - std::panicking::default_hook::h4190c9e3edd4d591
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:227
  10:          0x1f230c1 - std::panicking::rust_panic_with_hook::h72e78719cdda225c
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:577
  11:          0x1f22c69 - std::panicking::begin_panic_handler::{{closure}}::h8bd07dbd34150a96
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:484
  12:          0x1f1df4c - std::sys_common::backtrace::__rust_end_short_backtrace::hdb6b3066ad29028a
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys_common/backtrace.rs:153
  13:          0x1f22c29 - rust_begin_unwind
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/panicking.rs:483
  14:          0x1f885a1 - core::panicking::panic_fmt::hb15d6f55e8472f62
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/core/src/panicking.rs:85
  15:          0x1f88213 - core::option::expect_none_failed::he492a18657d97593
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/core/src/option.rs:1234
  16:          0x1648f1c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he6c3a3be9c8e1fd6
  17:          0x1fc4fee - std::panicking::try::h69e598907476f0d8
  18:          0x179f390 - <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::h8b20d79049d6f925
  19:          0x1eab481 - rayon_core::registry::WorkerThread::wait_until_cold::hd677f2fc93300658
  20:          0x1ea96c2 - rayon_core::registry::ThreadBuilder::run::h055ee17e713b5ed1
  21:          0x1eaf6f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h39369de0c1c71746
  22:          0x1eb0c24 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha9f50c0602ee0218
  23:          0x1f319fa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1080dfe0ef616bdf
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/alloc/src/boxed.rs:1042
  24:          0x1f319fa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd2747e1f2d5cec32
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/alloc/src/boxed.rs:1042
  25:          0x1f319fa - std::sys::unix::thread::Thread::new::thread_start::hd0f336b4ef6808a7
                               at /rustc/beb5ae474d2835962ebdf7416bd1c9ad864fe101/library/std/src/sys/unix/thread.rs:87
  26:     0x7f9149a316db - start_thread
  27:     0x7f914a31071f - __clone

**Expected behavior**
PC1--->PC2   or  PC2->C2  also appear this error。
so，the worker have to repeat sealing work ,such as   PC1-->PC2 --->PC1, or PC2->C2->PC1      

**Version (run `lotus version`):**
1.4.1 and 1.4.2rc and  master

**Comment by bugxzhu** [comment]
I tested it on at least 5 servers。And  others have the same problems。

**Comment by bugxzhu** [comment]
I solved it。cose

**Comment by aijiaoming** [comment]
> 我解决了。



> I solved it。cose

can you ask how to solve it

**Comment by guopenglun** [comment]
how to fix this?
