### ISSUE TITLE
generate window post skipped sectors

### ISSUE THREAD

**Issue by nickboot** [filecoin-project/lotus#5546]
.**Describe the problem**

generate window post skipped sectors

**Sectors status**

lotus-miner proving faults
deadline  partition  sectors
2         0          4116
2         0          4126
2         0          4132
2         0          4133
2         0          4148

lotus-miner proving check --only-bad 2
deadline  partition  sector  status

**Lotus miner logs**
"error": "faulty sectors [SectorId(4116), SectorId(4126), SectorId(4133)]\n\nStack backtrace:\n   0: <storage_proofs_post::fallback::vanilla::FallbackPoSt<Tree> as storage_proofs_core::proof::ProofScheme>::prove_all_partitions\n   1: storage_proofs_core::compound_proof::CompoundProof::prove\n   2: filecoin_proofs::api::post::generate_window_post\n   3: filecoin_proofs_api::post::generate_window_post_inner\n   4: filecoin_proofs_api::post::generate_window_post\n   5: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n   6: ffi_toolkit::catch_panic_response\n   7: fil_generate_window_post\n   8: _cgo_8d8f391b4e17_Cfunc_fil_generate_window_post\n             at /tmp/go-build/cgo-gcc-prolog:555\n   9: runtime.asmcgocall\n             at /usr/local/go/src/runtime/asm_amd64.s:656", "errorVerbose": "faulty sectors [SectorId(4116), SectorId(4126), SectorId(4133)]\n\nStack backtrace:\n   0: <storage_proofs_post::fallback::vanilla::FallbackPoSt<Tree> as storage_proofs_core::proof::ProofScheme>::prove_all_partitions\n   1: storage_proofs_core::compound_proof::CompoundProof::prove\n   2: filecoin_proofs::api::post::generate_window_post\n   3: filecoin_proofs_api::post::generate_window_post_inner\n   4: filecoin_proofs_api::post::generate_window_post\n   5: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n   6: ffi_toolkit::catch_panic_response\n   7: fil_generate_window_post\n   8: _cgo_8d8f391b4e17_Cfunc_fil_generate_window_post\n             at /tmp/go-build/cgo-gcc-prolog:555\n   9: runtime.asmcgocall\n             at /usr/local/go/src/runtime/asm_amd64.s:656\ngithub.com/filecoin-project/filecoin-ffi.GenerateWindowPoSt\n\t/root/lotus/extern/filecoin-ffi/proofs.go:587\ngithub.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).GenerateWindowPoSt\n\t/root/lotus/extern/sector-storage/ffiwrapper/verifier_cgo.go:45\ngithub.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost\n\t/root/lotus/storage/wdpost_run.go:591\ngithub.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runGeneratePoST\n\t/root/lotus/storage/wdpost_run.go:101\ngithub.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).startGeneratePoST.func1\n\t/root/lotus/storage/wdpost_run.go:85\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374", "try": 0}

**Version**

lotus version 1.4.1+git.e5efe57c9

**Comment by wangyancun** [comment]
me too

**Comment by anshengme** [comment]
me too

**Comment by Reiers** [comment]
Hi @nickboot @wangyancun 

Thanks for the report. Could you please elaborate on the issue? Reproducing steps? 

Ticket will be closed by the bot if no input.

If you are still experiencing problems, open a new ticket or ask in our Discussions [forum](https://github.com/filecoin-project/lotus/discussions).
