### ISSUE TITLE
Error running lotus-soup testplans

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/lotus#5548]
**Describe the bug**
I am trying to run the following composition from the `testplans` directory:
```
testground run composition -f ./lotus-soup/_compositions/baseline-docker-5-1.toml
```
and I keep getting errors in the build process. First I was getting:
```
go: github.com/filecoin-project/lotus@v0.9.2-0.20201012041700-a2e0832a12f2: parsing /go.mod: open /go.mod: no suc
h file or directory
```
I thought it could be something related to the replace directives on `lotus-soup`'s `go.mod` so I commented that last line:
```
// replace github.com/filecoin-project/lotus => ../../
```
With this I don't get the previous error anymore, but now I get:
```
go: github.com/filecoin-project/lotus@v0.9.2-0.20201012041700-a2e0832a12f2 requires
        launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: reading http://testground-goproxy:8081/launchpa
d.net/gocheck/@v/v0.0.0-20140225173054-000000000087.mod: 404 Not Found
        server response:
        go mod download -json launchpad.net/gocheck@v0.0.0-20140225173054-000000000087:
        {
                "Path": "launchpad.net/gocheck",
                "Version": "v0.0.0-20140225173054-000000000087",
                "Error": "launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir
 -- https://launchpad.net/~niemeyer/gocheck/trunk . in /go/pkg/mod/cache/download/cache/vcs/f46ce2ae80d31f9b0a290
99baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: \"bzr\": executable file not found in $PATH"
        }
```
Any idea why this can be? Thanks!

**To Reproduce**
Steps to reproduce the behavior: https://github.com/filecoin-project/lotus/tree/master/testplans#running-the-baseline-deals-end-to-end-test-case

**Expected behavior**
The test plan runs without errors with `local:docker`

**Screenshots**

**Version (run `lotus version`):** commit 6de62411c6b2f2b80a502bbe2991bad4dd5e2550

**Comment by nonsense** [comment]
@adlrocha this has been fixed on latest `master`. The baseline tests were broken before these PRs:
- https://github.com/filecoin-project/lotus/pull/4995
- https://github.com/filecoin-project/lotus/pull/555 

It was indeed related to `// replace github.com/filecoin-project/lotus => ../../` which basically references `lotus` as dependency in a parent directory, but this directory is not serialized and passed to Testground by the testplan.

**Comment by nonsense** [comment]
`bzr` is no longer required, as we removed `gocheck` as a dependency of Lotus.
