### ISSUE TITLE
retrievals: MinPricePerByte and UnsealPrice semantics

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#5550]
While taking a look at `QueryOffer`s, I realized that retrieval prices are set in a field named `MinPricePerByte`.
The question is: why "Min"? I took a look at the spec, but didn't find why the price is returned as `Min`, which I understand as _minimum_. 

This makes me doubt if this means that when making the real retrieval, there's a chance of starting to pay more money per byte, which feels a bit weird. Maybe `MaxPricePerByte` makes more sense? Or simply `PricePerByte` if the cost is fixed?

Also, the total cost of the retrieval is calculated as:
```go
// PieceRetrievalPrice is the total price to retrieve the piece (size * MinPricePerByte + UnsealedPrice)
func (qr QueryResponse) PieceRetrievalPrice() abi.TokenAmount {
	return big.Add(big.Mul(qr.MinPricePerByte, abi.NewTokenAmount(int64(qr.Size))), qr.UnsealPrice)
}
```
While talking with @dirkmc, we discovered that `UnsealPrice` isn't set to zero for fast-retrieval deals. Since the data is in unsealed form at the miner, it doesn't sound right to charge the client to _unseal_ it. 

In my interpretation of the crypto economics, the miner should include the extra cost of having the data unsealed in the _PricePerEpoch_ since it's a cost that depends on time, thus shouldn't be _included_ as a mutated "UnsealPrice" extra cost.

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system, [which reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and has been completely removed from the code:

https://github.com/filecoin-project/lotus/pull/11999
https://github.com/filecoin-project/lotus/pull/12005
