### ISSUE TITLE
Clean up log levels

### ISSUE THREAD

**Issue by NSC-FIL** [filecoin-project/lotus#5556]
Seems that when a deal fails or is not processed properly a message gets posted in the miner log as follows:
ERROR	storagemarket_impl	impl/provider.go:464	failed to read DealStatusRequest from incoming stream: unmarshaling t.Signature: stream reset 

**To Reproduce**
Unsure how to recreated exactly... could be various scenarios like a client deal is stuck in StorageDealWaitingForData or perhaps timed out?  My miner logs and `lotus-miner storage-data list` can be shared to help debug this issue upon request. DM me on slack @Nelson if you need.

**Expected behavior**
Maybe this should not be and ERROR, but rather downgraded to an WARN message.

**Version (run `lotus version`):**
lotus version 1.4.1+mainnet+git.6de62411c

**Comment by jennijuju** [comment]
Thanks for the issue! Duplicated #3249

**Comment by arajasek** [comment]
Thanks for the issue! This is part of a broader problem where subsystems spam ERRORs even when the node's functioning is unaffected. We need to clean this up in a few different places, we can track that work here.

**Comment by rjan90** [comment]
Closing this issue, since the legacy lotus-miner markets subsystem is deprecated.

There might be other areas/subsystems that need some log-levels cleaned up, but please open a new ticket if you find such cases.
