### ISSUE TITLE
Set max-fee per storage or retrieval deal

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#5558]
Currently, as a client, there's the possibility of setting `DefaultMaxFee` in the toml config file as a hard cap of how much Lotus generated messages will pay for fees.

We have a use-case in which we use the same Lotus node for multiple external users, where each user has its own wallet address from which make deals in the network. These users aren't logically related, so might have different opinions about how much they would want to pay for fees.

Under the current possibilities, since the default max-fee is set node-wise, there's no chance to allow each user to decide how much it wants to pay in fees. As a proposal, it would be useful to allow to set how the max-fee attribute per deal/retrieval; so this would allow different users to decide their own value. Say, by adding attributes to the _start deal_ or _retrieve_ APIs.

Moving this multi-tenant use aside, there might be possible use-cases in which a single user of the Lotus node might want to pay higher or lower fees for different deals, since each dataset might have different priorities. This isn't our use case, but I'm mentioning it since may be interesting too.

**Comment by jennijuju** [comment]
To be more specific, the above use case is for `AddBalance` meesaeg that clients often send.

**Comment by jsign** [comment]
Yep, that's a particular message for deal-making. But other messages might apply, for example, a payment channel creation for retrievals (if needed). In general, whatever current or future message is part of the storage/retrieval process.

**Comment by jennijuju** [comment]
> Yep, that's a particular message for deal-making. But other messages might apply, for example, a payment channel creation for retrievals (if needed). In general, whatever current or future message is part of the storage/retrieval process _for the client_.

Would you imagine the need of different fee settings for different messages?

**Comment by jsign** [comment]
> > Yep, that's a particular message for deal-making. But other messages might apply, for example, a payment channel creation for retrievals (if needed). In general, whatever current or future message is part of the storage/retrieval process _for the client_.
> 
> Would you imagine the need of different fee settings for different messages?

I'm not entirely sure that many levels of detail might be surfaced to users, so a general max-fee cap for their wallets accounting for gas costs seems fine. If it's a ~zero-cost extra feature on top of the work that would be needed anyway, might be good to allow it in the API and let applications (like us) decide how much to surface to users.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
