### ISSUE TITLE
lotus-miner seems to be retaining a lot of space in LOTUS_MINER_PATH/datastore/staging

### ISSUE THREAD

**Issue by nonsense** [filecoin-project/lotus#5569]
**Describe the bug**
My `LOTUS_MINER_PATH/datastore/staging` database is >100G and this seems like a bug. I believe this datastore is used for retrieval deals, although I am not sure why this space is not reclaimed after the retrieval has finished (successfully or not).

Is there a workaround where I could manually delete this datastore and reclaim some of the disk space?

**Expected behavior**
I expect the `datastore/staging` directory to be mostly empty when there are no ongoing deals.

**Version (run `lotus version`):**

```
$ lotus-miner version
Daemon:  1.4.1+git.ebaa721e4+api1.0.1
Local: lotus-miner version 1.4.1+git.ebaa721e4
```

**Additional context**

1. Files in the `datastore/staging` are weeks old.

2. Disk usage:
```
~/lotus-miner-path/datastore
$ du -sh *
20K     client
5,8M    metadata
110G    staging
```

3. No ongoing retrieval-deals or data transfers...
```
$ lotus-miner retrieval-deals list
Receiver                                              DealID  Payload      State                PricePerByte  BytesSent    Message
12D3KooWNHFrhjRPafQrNK7h9zn5fAzMKDPszchvkVuEFM4EVXTW  0       ...44vyl4sa  DealStatusCompleted  2             23489267985
12D3KooWNHFrhjRPafQrNK7h9zn5fAzMKDPszchvkVuEFM4EVXTW  1       ...44vyl4sa  DealStatusErrored    2             1500620017   deal data transfer stalled (peer hungup)
12D3KooWNHFrhjRPafQrNK7h9zn5fAzMKDPszchvkVuEFM4EVXTW  2       ...44vyl4sa  DealStatusErrored    2             6345958      deal data transfer stalled (peer hungup)
12D3KooWNHFrhjRPafQrNK7h9zn5fAzMKDPszchvkVuEFM4EVXTW  3       ...44vyl4sa  DealStatusErrored    2             1103078      deal data transfer stalled (peer hungup)
12D3KooWNHFrhjRPafQrNK7h9zn5fAzMKDPszchvkVuEFM4EVXTW  4       ...44vyl4sa  DealStatusErrored    2             1103078      deal data transfer stalled (peer hungup)
12D3KooWNHFrhjRPafQrNK7h9zn5fAzMKDPszchvkVuEFM4EVXTW  5       ...44vyl4sa  DealStatusCompleted  2             23489267985
12D3KooWNHFrhjRPafQrNK7h9zn5fAzMKDPszchvkVuEFM4EVXTW  6       ...44vyl4sa  DealStatusCompleted  2             23489267985
```

**Comment by jennijuju** [comment]
may be related #5291

**Comment by rjan90** [comment]
@nonsense It is safe to delete the whole _/staging_-folder if you have stopped you miner, and don't have any deals currently sealing, it will be re-created when you start up the miner again.

From my experience it seems like unfinished deal-transfers (online deals) are left behind in the staging-folder, so over time it will grow just larger if/when more deal-transfers error-out / fails.

**Comment by raulk** [comment]
This needs fixing, though. GC should be automatic. Having to manually delete the directory every now and then it's not good UX for miners.

**Comment by funktafide** [comment]
It seems like the cleanup process in this folder is ok for successful deals.  The failed deals, stalled transfers and other issues dont seem to clear out unless you manually delete it. Im not to sure when it is ok to delete this folder.  There always seems to be deal activity, whether is sending/receiving, pending publish, waitdeals or actually sealing.  My concern with deleting the folder is messing up deals I have coming in or waiting to seal.

**Comment by rjan90** [comment]
I think this issue can be closed, as the /staging-dir is not retaining a lot space any longer. Even if deals has failed / not succeeded they seem to be garbage collected at restart of the markets-node #rengjøring

**Comment by Reiers** [comment]
**Correct @rjan90** 

Closing ticket.
If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
