### ISSUE TITLE
Create miner always failed with “Too Many Requests” error

### ISSUE THREAD

**Issue by maobisheng** [filecoin-project/lotus#557]
As I mentioned in slack #fil-lotus channel, create miner always failed with “Too Many Requests” error in https://lotus-faucet.kittyhawk.wtf/miner.html page.
I have tried it on Chrome & IE browser.
Is there any work around about this issue?
![image](https://user-images.githubusercontent.com/3703197/68528208-b3e72080-032a-11ea-810b-9670ff575d3d.png)

Thanks.

**Comment by Kubuxu** [comment]
I suggest adding better response messages so we can know which limiter was hit.

**Comment by maobisheng** [comment]
It works on IE browser.
