### ISSUE TITLE
[Feature Request] Dedicated deal making worker

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#5576]
Currently, accepting and proceeding deal for miners, winning post and window post are all performed in miners, where deal making may occupy necessary resources for performing windowpost and leads to a penalty. 

This is to request a dedicated worker for handling deal making processes to avoid the above situation.

**Comment by kernelogic** [comment]
Isn't deal making a lotus daemon client side thing? Just start a dedicated lotus daemon to make deals, don't use your miner's daemon to make deals.

**Comment by kernelogic** [comment]
Unless you are talking about "accepting the deal", that would be a miner side thing.

**Comment by jennijuju** [comment]
> Unless you are talking about "accepting the deal", that would be a miner side thing. And yes importing offline deals will slow down the miner and even affect wdpost. Currently there's no way to delegate it to a worker.

Yes that’s what I meant! Thanks for pointing it out, updated the Comment for clarity♥️

**Comment by jennijuju** [comment]
introduced in v1.11.1
