### ISSUE TITLE
Two Sectors stuck in C1

### ISSUE THREAD

**Issue by dgreuel2002** [filecoin-project/lotus#5577]
Please provide all the information requested here to help us troubleshoot "commit failed" issues.
If the information requested is missing, we will probably have to just ask you to provide it anyway,
before we can help debug.

**Describe the problem**
I have two sectors that showed stuck at committing for the last week. My miner went down during t he sealing of these sectors. They were bugged and would not move the state. I then went and **lotus-miner sectors remove --really-do-it=true 630** and it removed the data from the seal repo but did not change the state of the sectors. Now, every time I start my miner these two sectors get stuck in C1 phase and I have no way to remove them. The log is flooded with the scheduler trying to figure out what to do with them. It appears the terminate, abort, or remove features do not work on a sector stuck in C1.

**Sectors status**

The output of `lotus-miner sectors status --log <sectorId>` for the failed sector(s).
SectorID:       630
Status:         Committing
CIDcommD:       baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq
CIDcommR:       bagboea4b5abca6hmxqdbesf2asdkfvzwj62b4m2r4xk6yfugitu37ainh3kz2aq5
Ticket:         ef5d8dae6a8a994cd730bda137ac42da11e8b02b98f625a8533f1a34595e4b37
TicketH:        475452
Seed:           2c19aed0c4bfc2768a61ea37a0485384eabeba77309526771633ed762e6728c0
SeedH:          477307
Precommit:      bafy2bzaceb3qjcj4xxmy4gubkht4hdav4g4r5uf44hmum5if6tcvxzykbq3gg
Commit:         <nil>
Proof:
Deals:          [0]
Retries:        0
--------
Event Log:
0.      2021-02-06 01:36:26 -0600 CST:  [event;sealing.SectorStartCC]   {"User":{"ID":630,"SectorType":8,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}},"DealInfo":null}]}}
1.      2021-02-06 01:36:26 -0600 CST:  [event;sealing.SectorPacked]    {"User":{"FillerPieces":null}}
2.      2021-02-06 01:36:26 -0600 CST:  [event;sealing.SectorTicket]    {"User":{"TicketValue":"712NrmqKmUzXML2hN6xC2hHosCuY9iWoUz8aNFleSzc=","TicketEpoch":475452}}
3.      2021-02-06 07:53:00 -0600 CST:  [event;sealing.SectorPreCommit1]        {"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjFfMSIsImxhYmVscyI6eyJTdGFja2VkRHJnMzJHaUJWMSI6eyJsYWJlbHMiOlt7InBhdGgiOiIvbW50L21kMC93b3JrZXIxL2NhY2hlL3MtdDA0NzQxOS02MzAiLCJpZCI6ImxheWVyLTEiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9tbnQvbWQwL3dvcmtlcjEvY2FjaGUvcy10MDQ3NDE5LTYzMCIsImlkIjoibGF5ZXItMiIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21udC9tZDAvd29ya2VyMS9jYWNoZS9zLXQwNDc0MTktNjMwIiwiaWQiOiJsYXllci0zIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvbW50L21kMC93b3JrZXIxL2NhY2hlL3MtdDA0NzQxOS02MzAiLCJpZCI6ImxheWVyLTQiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9tbnQvbWQwL3dvcmtlcjEvY2FjaGUvcy10MDQ3NDE5LTYzMCIsImlkIjoibGF5ZXItNSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21udC9tZDAvd29ya2VyMS9jYWNoZS9zLXQwNDc0MTktNjMwIiwiaWQiOiJsYXllci02Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvbW50L21kMC93b3JrZXIxL2NhY2hlL3MtdDA0NzQxOS02MzAiLCJpZCI6ImxheWVyLTciLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9tbnQvbWQwL3dvcmtlcjEvY2FjaGUvcy10MDQ3NDE5LTYzMCIsImlkIjoibGF5ZXItOCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21udC9tZDAvd29ya2VyMS9jYWNoZS9zLXQwNDc0MTktNjMwIiwiaWQiOiJsYXllci05Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvbW50L21kMC93b3JrZXIxL2NhY2hlL3MtdDA0NzQxOS02MzAiLCJpZCI6ImxheWVyLTEwIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvbW50L21kMC93b3JrZXIxL2NhY2hlL3MtdDA0NzQxOS02MzAiLCJpZCI6ImxheWVyLTExIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fV0sIl9oIjpudWxsfX0sImNvbmZpZyI6eyJwYXRoIjoiL21udC9tZDAvd29ya2VyMS9jYWNoZS9zLXQwNDc0MTktNjMwIiwiaWQiOiJ0cmVlLWQiLCJzaXplIjoyMTQ3NDgzNjQ3LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LCJjb21tX2QiOls3LDEyNiw5NSwyMjIsNTMsMTk3LDEwLDE0NywzLDE2NSw4MCw5LDIyNyw3MywxMzgsNzgsMTkwLDIyMywyNDMsMTU2LDY2LDE4MywxNiwxODMsNDgsMjE2LDIzNiwxMjIsMTk5LDE3NSwxNjYsNjJdfQ=="}}
4.      2021-02-06 08:18:14 -0600 CST:  [event;sealing.SectorPreCommit2]        {"User":{"Sealed":{"/":"bagboea4b5abca6hmxqdbesf2asdkfvzwj62b4m2r4xk6yfugitu37ainh3kz2aq5"},"Unsealed":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}}
5.      2021-02-06 08:18:14 -0600 CST:  [event;sealing.SectorPreCommitted]      {"User":{"Message":{"/":"bafy2bzaceb3qjcj4xxmy4gubkht4hdav4g4r5uf44hmum5if6tcvxzykbq3gg"},"PreCommitDeposit":"79951450067268521","PreCommitInfo":{"SealProof":8,"SectorNumber":630,"SealedCID":{"/":"bagboea4b5abca6hmxqdbesf2asdkfvzwj62b4m2r4xk6yfugitu37ainh3kz2aq5"},"SealRandEpoch":475452,"DealIDs":[],"Expiration":2030166,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}
6.      2021-02-06 08:21:29 -0600 CST:  [event;sealing.SectorPreCommitLanded]   {"User":{"TipSet":"AXGg5AIghwWH7wKB8f7TW0L80xXNcJaH6TycJd9vXdF2Udyp/QoBcaDkAiBy5Mb8jGGyK0ftELeMFEAm9c3gp2BpqzjLuD22qKNobgFxoOQCIHxYBr81B3ERFktBfGyXxtfK1YYS2VqopD2f/IHNInvDAXGg5AIgNSrRjYyS5yvJJqaAn85TdkD2voyk5dxLyK5mxwryZWI="}}
7.      2021-02-06 09:36:30 -0600 CST:  [event;sealing.SectorSeedReady] {"User":{"SeedValue":"LBmu0MS/wnaKYeo3oEhThOq+uncwlSZ3FjPtdi5nKMA=","SeedEpoch":477307}}
8.      2021-02-06 10:09:41 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
9.      2021-02-06 11:30:38 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
10.     2021-02-06 11:50:06 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
11.     2021-02-06 11:59:49 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
12.     2021-02-06 12:29:42 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
13.     2021-02-06 12:37:03 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
14.     2021-02-07 11:57:01 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
15.     2021-02-08 09:51:04 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
16.     2021-02-08 18:27:05 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
17.     2021-02-08 18:39:51 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
18.     2021-02-09 06:06:54 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
19.     2021-02-09 22:36:22 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
20.     2021-02-10 18:48:29 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
21.     2021-02-10 19:21:27 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}

lotus-miner sectors status --log 631
SectorID:       631
Status:         Committing
CIDcommD:       baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq
CIDcommR:       bagboea4b5abcb4n2kiqch6z4q5qubt7b7zll7bshvy2mbrirk4suwkj5vh3siv2u
Ticket:         c8260a50c63edb4c1600315bead16a8db76a5b148e960abf72aa0ca50f446c00
TicketH:        475634
Seed:           b489d2621222f5e45d17eee8838720bef88b2fbba735157367f8e81ff861e60e
SeedH:          477503
Precommit:      bafy2bzaceatsxig2optlydeflyergbvamx4rdrdenxq4r2pfhloqeoivklcx4
Commit:         <nil>
Proof:
Deals:          [0]
Retries:        0
--------
Event Log:
0.      2021-02-06 03:07:15 -0600 CST:  [event;sealing.SectorStartCC]   {"User":{"ID":631,"SectorType":8,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}},"DealInfo":null}]}}
1.      2021-02-06 03:07:15 -0600 CST:  [event;sealing.SectorPacked]    {"User":{"FillerPieces":null}}
2.      2021-02-06 03:07:15 -0600 CST:  [event;sealing.SectorTicket]    {"User":{"TicketValue":"yCYKUMY+20wWADFb6tFqjbdqWxSOlgq/cqoMpQ9EbAA=","TicketEpoch":475634}}
3.      2021-02-06 09:18:44 -0600 CST:  [event;sealing.SectorPreCommit1]        {"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjFfMSIsImxhYmVscyI6eyJTdGFja2VkRHJnMzJHaUJWMSI6eyJsYWJlbHMiOlt7InBhdGgiOiIvbW50L21kMC93b3JrZXIxL2NhY2hlL3MtdDA0NzQxOS02MzEiLCJpZCI6ImxheWVyLTEiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9tbnQvbWQwL3dvcmtlcjEvY2FjaGUvcy10MDQ3NDE5LTYzMSIsImlkIjoibGF5ZXItMiIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21udC9tZDAvd29ya2VyMS9jYWNoZS9zLXQwNDc0MTktNjMxIiwiaWQiOiJsYXllci0zIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvbW50L21kMC93b3JrZXIxL2NhY2hlL3MtdDA0NzQxOS02MzEiLCJpZCI6ImxheWVyLTQiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9tbnQvbWQwL3dvcmtlcjEvY2FjaGUvcy10MDQ3NDE5LTYzMSIsImlkIjoibGF5ZXItNSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21udC9tZDAvd29ya2VyMS9jYWNoZS9zLXQwNDc0MTktNjMxIiwiaWQiOiJsYXllci02Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvbW50L21kMC93b3JrZXIxL2NhY2hlL3MtdDA0NzQxOS02MzEiLCJpZCI6ImxheWVyLTciLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9tbnQvbWQwL3dvcmtlcjEvY2FjaGUvcy10MDQ3NDE5LTYzMSIsImlkIjoibGF5ZXItOCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL21udC9tZDAvd29ya2VyMS9jYWNoZS9zLXQwNDc0MTktNjMxIiwiaWQiOiJsYXllci05Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvbW50L21kMC93b3JrZXIxL2NhY2hlL3MtdDA0NzQxOS02MzEiLCJpZCI6ImxheWVyLTEwIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvbW50L21kMC93b3JrZXIxL2NhY2hlL3MtdDA0NzQxOS02MzEiLCJpZCI6ImxheWVyLTExIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fV0sIl9oIjpudWxsfX0sImNvbmZpZyI6eyJwYXRoIjoiL21udC9tZDAvd29ya2VyMS9jYWNoZS9zLXQwNDc0MTktNjMxIiwiaWQiOiJ0cmVlLWQiLCJzaXplIjoyMTQ3NDgzNjQ3LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LCJjb21tX2QiOls3LDEyNiw5NSwyMjIsNTMsMTk3LDEwLDE0NywzLDE2NSw4MCw5LDIyNyw3MywxMzgsNzgsMTkwLDIyMywyNDMsMTU2LDY2LDE4MywxNiwxODMsNDgsMjE2LDIzNiwxMjIsMTk5LDE3NSwxNjYsNjJdfQ=="}}
4.      2021-02-06 09:56:05 -0600 CST:  [event;sealing.SectorPreCommit2]        {"User":{"Sealed":{"/":"bagboea4b5abcb4n2kiqch6z4q5qubt7b7zll7bshvy2mbrirk4suwkj5vh3siv2u"},"Unsealed":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}}
5.      2021-02-06 09:56:06 -0600 CST:  [event;sealing.SectorPreCommitted]      {"User":{"Message":{"/":"bafy2bzaceatsxig2optlydeflyergbvamx4rdrdenxq4r2pfhloqeoivklcx4"},"PreCommitDeposit":"79889875283754233","PreCommitInfo":{"SealProof":8,"SectorNumber":631,"SealedCID":{"/":"bagboea4b5abcb4n2kiqch6z4q5qubt7b7zll7bshvy2mbrirk4suwkj5vh3siv2u"},"SealRandEpoch":475634,"DealIDs":[],"Expiration":2030166,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}
6.      2021-02-06 09:59:29 -0600 CST:  [event;sealing.SectorPreCommitLanded]   {"User":{"TipSet":"AXGg5AIgQC4wAZvmfW88SRyu1cvqGkbmBsfnL85g0ZPweyDpuJEBcaDkAiBU0c5NkAP2rfWrMsiFQU+623SpIu1/IzD6SNquvOp/1gFxoOQCIIwV1SZZamm5I+JQugFQ1ECqIInAQyayvGP1SZvDDHReAXGg5AIgfs7inknhAGTn7KhWTEqbmf79oS6oGpuuO6UbSQGYtcEBcaDkAiChw2j4n1s2c2rVXhtmDRHglpnXEu5s0LvRMuSvIwHpQw=="}}
7.      2021-02-06 10:09:41 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
8.      2021-02-06 11:15:00 -0600 CST:  [event;sealing.SectorSeedReady] {"User":{"SeedValue":"tInSYhIi9eRdF+7og4cgvviLL7unNRVzZ/joH/hh5g4=","SeedEpoch":477503}}
9.      2021-02-06 11:30:38 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
10.     2021-02-06 11:50:06 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
11.     2021-02-06 11:59:49 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
12.     2021-02-06 12:29:42 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
13.     2021-02-06 12:37:03 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
14.     2021-02-07 11:57:01 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
15.     2021-02-08 09:51:04 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
16.     2021-02-08 18:27:05 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
17.     2021-02-08 18:39:51 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
18.     2021-02-09 06:06:54 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
19.     2021-02-09 22:36:22 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
20.     2021-02-10 18:48:29 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}
21.     2021-02-10 19:21:27 -0600 CST:  [event;sealing.SectorRestart]   {"User":{}}

**Lotus miner logs**

Please go through the logs of your miner, and include screenshots of any error-like messages you find.
build1@citadel:$ grep 630 /filecoin/logs/miner.log
2021-02-10T19:21:27.452-0600    INFO    sectors storage-sealing/states_sealing.go:390   KOMIT 630 ef5d8dae6a8a994cd730bda137ac42da11e8b02b98f625a8533f1a34595e4b37(475452); 2c19aed0c4bfc2768a61ea37a0485384eabeba77309526771633ed762e6728c0(477307); [{34359738368 baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq}]; r:626167626f65613462356162636136686d78716462657366326173646b66767a776a363262346d327234786b3679667567697475333761696e68336b7a32617135; d:626167613665613473656171616f377337337932346b637574616f7376616370646a67666535707737366f6f65666e79717734796e72336432793678326d7071
build1@citadel:$ grep 631 /filecoin/logs/miner.log
2021-02-10T19:21:27.452-0600    INFO    sectors storage-sealing/states_sealing.go:390   KOMIT 631 c8260a50c63edb4c1600315bead16a8db76a5b148e960abf72aa0ca50f446c00(475634); b489d2621222f5e45d17eee8838720bef88b2fbba735157367f8e81ff861e60e(477503); [{34359738368 baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq}]; r:626167626f656134623561626362346e326b69716368367a347135717562743762377a6c6c376273687679326d627269726b347375776b6a357668337369763275; d:626167613665613473656171616f377337337932346b637574616f7376616370646a67666535707737366f6f65666e79717734796e72336432793678326d7071

Here is results of **lotus-miner sealing sched-diag**
[lotus-miner sealing sched-diag.txt](https://github.com/filecoin-project/lotus/files/5963155/lotus-miner.sealing.sched-diag.txt)

Alternatively please upload full log files and share a link here
[miner.log](https://github.com/filecoin-project/lotus/files/5963154/miner.log)

**Lotus miner diagnostic info**

Please collect the following diagnostic information, and share a link here

* lotus-miner diagnostic info `lotus-miner info all > allinfo` **It stops at retrieval deals due to the unmarshalling issue**
[allinfo.txt](https://github.com/filecoin-project/lotus/files/5963161/allinfo.txt)

** Code modifications **

If you have modified parts of lotus, please describe which areas were modified,
and the scope of those modifications

**Version**

The output of `lotus --version`.
#: Version
Daemon:  1.4.1+mainnet+git.ba571794d+api1.0.1
Local: lotus-miner info version 1.4.1+mainnet+git.ba571794d

**Comment by jennijuju** [comment]
Thanks for reporting! Linking and closing this ticket since its duplicated with https://github.com/filecoin-project/lotus/issues/4086
