### ISSUE TITLE
Filecoin.StateGetReceipt returns incorrectly

### ISSUE THREAD

**Issue by GarFoonYellowLee** [filecoin-project/lotus#5578]
bafy2bzacediihfsrlnovprxiuu2ngi3k5smw3o24mu7oxc34z4jtryyejqdmu is failed message, but rpc Filecoin.StateGetReceipt return message : {"jsonrpc":"2.0","result":{"ExitCode":0,"Return":null,"GasUsed":445068},"id":1}

**Comment by jennijuju** [comment]
Why do you think the message failed?

**Comment by jennijuju** [comment]
Why do you think the message is failed?

**Comment by jennijuju** [comment]
Closing - lack of info
