### ISSUE TITLE
Mainnet: Thread panic in Rust component causes chain sync failure 

### ISSUE THREAD

**Issue by jburnett** [filecoin-project/lotus#5583]
**Describe the bug**
Lotus daemon encounters thread panic and cannot maintain chain integrity.

**To Reproduce**
1. Remove chain data: rm -fr $LOTUS_PATH/datastore/chain
2. Using shell, import recent chain snapshot: lotus daemon --import-snapshot <snapshot>
3. After import progress hits 100%, wait for 'thread <unnamed> panicked' messages. May take a few mins.
4. Use separate shell to get sync status: lotus sync status
5. Review error messages in status output

**Expected behavior**
Lotus should successfully sync and maintain chain integrity.

**Screenshots**
After import, daemon reports
`thread '<unnamed>' panicked at 'Once has panicked', /home/jb/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.5.2/src/once.rs:128:29`

lotus sync status reports

```
sync status:
worker 80:
        Base:   [bafy2bzacebvxusiqlcbgj32u3cqvy4iryk33qmyq2odtzxqyi5vyyttl3heaw bafy2bzaceaj7334zhlwssm4ftal7wxgbx2twkj66je6zqrtc5f4xdi6bdns5o
bafy2bzaceakxsy63k42c5s7rzgi5s6jewthfaa4c3wvovc5btbygewc43ay3y bafy2bzacebssz7qdgd7dedcvpt2gnvs4u46zea5sklmcqurmtjxn242kph2us bafy2bzaceac5qlct
jha2h4wou5sd64bqxlkmmi3wamrezxjtnokggilxmywmi]
        Target: [bafy2bzacea5pxpjtpr222ceemhqd2hwlk3jbl66p2w7q6g3ovwjjamsja3t2s] (491393)
        Height diff:    252
        Stage: error
        Height: 0
        Elapsed: 76.279µs
        Error: chain linked to block marked previously as bad ([bafy2bzacea5pxpjtpr222ceemhqd2hwlk3jbl66p2w7q6g3ovwjjamsja3t2s], bafy2bzaceacff
kbkqljmlygckwmjd3jmugrsfzdjjorphrm5xqzrgbwqsx2so) (reason: linked to bafy2bzaceakffkkrlvannxwyfnosuadxqiqvytuizukvnzky5rja6sfq5tud6 caused by:
[bafy2bzaceddkie7wh35wakj6hoai4e4umebj5q2fyzkntrszrftjqjdjvs67u] 2 errors occurred:
        * invalid election post:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func11
        /home/jb/src/github.com/filecoin-project/lotus/chain/sync.go:919
  - failed to verify election post:
    github.com/filecoin-project/lotus/chain.(*Syncer).VerifyWinningPoStProof
        /home/jb/src/github.com/filecoin-project/lotus/chain/sync.go:1014
  - Rust panic: no unwind information
    github.com/filecoin-project/filecoin-ffi.VerifyWinningPoSt
        /home/jb/src/github.com/filecoin-project/lotus/extern/filecoin-ffi/proofs.go:92
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.proofVerifier.VerifyWinningPoSt
        /home/jb/src/github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper/verifier_cgo.go:123
    github.com/filecoin-project/lotus/chain.(*Syncer).VerifyWinningPoStProof
        /home/jb/src/github.com/filecoin-project/lotus/chain/sync.go:1007
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func11
        /home/jb/src/github.com/filecoin-project/lotus/chain/sync.go:918
    github.com/Gurpartap/async.Err.func1
        /home/jb/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:29
    runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
        * parent state root did not match computed state (bafy2bzacedxoyendted7ugbsptk7ihevk52g2dirpjjfrxwgaf3itffvoed2e != bafy2bzacedl34auc3g
46w5yckqiytsvwxxymzp65gxcyqzu4i6m335hsyhsfe):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /home/jb/src/github.com/filecoin-project/lotus/chain/sync.go:802
```

**Version (run `lotus version`):**
lotus version 1.4.1+git.ebaa721e4
Ubuntu Server 20.04.2 LTS
AMD Epyc 7402p, 256 GB RAM, NVidia M5000
LOTUS_PATH backed by 12-drive ZFS pool in JBOD connected by LSI 9200-8e
Separate NVMes for TMPDIR, scratch, etc.

**Additional context**
We've testing the following with no positive effect:
- Clean build from mainline and 1.4.1 tag
-  FIL_PROOFS set & unset (caching, tree & column builder) for both mainline & 1.4.1 builds

`rustup show` reports
```Default host: x86_64-unknown-linux-gnu
rustup home:  /home/jb/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2020-10-05-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

**Comment by jburnett** [comment]
After many experiments, I think this panic occurs when FIL_PROOFS_USE_MULTICORE_SDR is set.  (Previous tests had not unset this env var correctly).  After ensuring this var was unset, we started Lotus daemon to import snapshot, and it has been maintaining the chain successfully for > 24 hrs.  Two questions remain:

1) Is it desirable to use multicore sdr for chain mgmt?
2) Are any of the panics or logs above useful to FC devs?  If not, feel free to close this issue.

Thanks.

**Comment by cryptonemo** [comment]
I don't think there's any benefit for a node that's not mining to use `FIL_PROOFS_USE_MULTICORE_SDR`.  I don't know why that would cause an issue though.  For logging, setting `RUST_LOG=info` would be more useful to help find where this is happening.

**Comment by jburnett** [comment]
@cryptonemo, thanks for your comments.  We learned the hard way that multicore SDR should not be set, but we'll leave it to dev team on whether to resolve for others.

**Comment by jennijuju** [comment]
sounds like this is not a lotus issue. closing for now
