### ISSUE TITLE
lotus-miner sectors remove / lotus-miner sectors update-state don't work

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/lotus#5587]
**Describe the bug**
lotus-miner sectors remove / lotus-miner sectors update-state don't work. 

**Version (run `lotus version`):**
V1.4.2

**Additional context**
Both commands don't work to remove sectors if the files do not exist anymore on disk?

**Comment by PatrickDeuse** [comment]
that is expected - how to remove them if they aren't there?

try creating mock versions of the sectors in the sealing folders and run the remove again. a simpel miner restart might do the job too

and the version is 1.4.2-rc1 :P

**Comment by cryptowhizzard** [comment]
Well .... lotus-miner sectors list still shows them. 

All these sectors below do not respond to anything.

ID    State           OnChain  Active  Expiration                     Deals  DealWeight  VerifiedPower  
17    removing        NO       NO      n/a                            CC                                
40    Precommit2      NO       NO      n/a                            CC                                
5188  FinalizeSector  YES      NO      1588722 (in 1 year 1 week)     CC                                
5189  FinalizeSector  YES      NO      1588722 (in 1 year 1 week)     CC                                
5423  FinalizeSector  YES      NO      1634802 (in 1 year 4 weeks)    CC                                
5424  FinalizeSector  YES      NO      1634802 (in 1 year 4 weeks)    CC                                
5434  FinalizeSector  YES      NO      1634802 (in 1 year 4 weeks)    CC                                
5496  FinalizeSector  YES      NO      1646322 (in 1 year 4 weeks)    CC                                
5715  Committing      NO       NO      n/a                            CC                                
5716  Committing      NO       NO      n/a                            CC                                
5720  Committing      NO       NO      n/a                            CC                                
5721  Committing      NO       NO      n/a                            CC                                
5724  Committing      NO       NO      n/a                            CC                                
5725  Committing      NO       NO      n/a                            CC                                
5726  Committing      NO       NO      n/a                            CC                                
5727  Committing      NO       NO      n/a                            CC                                
5767  Committing      NO       NO      n/a                            CC                                
5797  Committing      NO       NO      n/a                            CC                                
6345  Committing      NO       NO      n/a                            CC                                
6346  Committing      NO       NO      n/a                            CC                                
6351  Committing      NO       NO      n/a                            CC                                
6353  Committing      NO       NO      n/a                            9                                 
6355  Committing      NO       NO      n/a                            CC                                
6360  Committing      NO       NO      n/a                            CC                                
6362  Committing      NO       NO      n/a                            CC                                
6820  FinalizeSector  YES      NO      1807602 (in 1 year 12 weeks)   CC                                
7007  Committing      NO       NO      n/a                            CC                                
7699  FinalizeSector  YES      NO      1896882 (in 1 year 17 weeks)   CC                                
7702  FinalizeSector  YES      NO      1896882 (in 1 year 17 weeks)   CC                                
7704  FinalizeSector  YES      NO      1896882 (in 1 year 17 weeks)   CC                                
7705  FinalizeSector  YES      NO      1896882 (in 1 year 17 weeks)   CC                                
7706  FinalizeSector  YES      NO      1896882 (in 1 year 17 weeks)   CC                                
7707  FinalizeSector  YES      NO      1896882 (in 1 year 17 weeks)   CC                                
7709  Committing      NO       NO      n/a                            CC                                
7710  Committing      NO       NO      n/a                            CC                                
7711  Committing      NO       NO      n/a                            CC                                
7712  Committing      NO       NO      n/a                            CC    

Time to clean?

Btw ... making dummy sectors did not help.
