### ISSUE TITLE
lotus-bench prove not working

### ISSUE THREAD

**Issue by seccentral** [filecoin-project/lotus#5598]
**Describe the bug**
lotus-bench prove not working

**To Reproduce**
./lotus-bench prove

**Expected behavior**
[ results ]

**Screenshots**
```
fil@filecoin:~/benchmark$ ./lotus-bench prove
2021-02-15T21:14:33.544+0200    INFO    lotus-bench     lotus-bench/main.go:101 Starting lotus-bench
2021-02-15T21:14:33.544+0200    WARN    lotus-bench     lotus-bench/main.go:115 Usage: lotus-bench prove [input.json]:
    main.glob..func4
        /home/fil/lotus/cmd/lotus-bench/main.go:728
fil@filecoin:~/benchmark$ 
```

**Version (run `lotus version`):**
```
fil@filecoin:~/benchmark$ lotus version
Daemon:  1.4.1+mainnet+git.95e47cf99+api1.1.0
Local: lotus version 1.4.1+mainnet+git.95e47cf99
```
**Additional context**
compiled and ran as per documentation [here](https://docs.filecoin.io/mine/lotus/benchmarks/#usage)

**Comment by kelvinyasu** [comment]
Got the same problem here too.. is any input file I need to specify to run the test?

**Comment by seccentral** [comment]
update: same problem with 1.4.2

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/benchmarks#running-a-benchmark
