### ISSUE TITLE
Mpool gets into bad state after reorgs

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#561]
If you are sending a lot of messages, and the chain reorgs (and you are using BLS messages) your mempool will get into a bad state where the lowest nonce of any message in the mempool is higher than your actors nonce on chain, but any further messages you send will be given the next highest nonce of any message you have in the mempool. 

Two things we can do to improve this situation (we should do both):
- Fix handling of BLS messages during reorgs (Requires saving bls messages signatures separately in a place we can get them again)
- Detect nonce gaps in the message pool when requesting future nonces

**Comment by magik6k** [comment]
https://github.com/filecoin-project/lotus/pull/581

**Comment by whyrusleeping** [comment]
The BLS portion of this issue is done.
