### ISSUE TITLE
Incorrect address used in client retrieve

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/lotus#5610]
When making a retrieval query, the `QueryOffer.Miner` field is populated with the provider's payment address:
https://github.com/filecoin-project/lotus/blob/95e47cf9982c1c3538f4de8037ca5476cbaedab0/node/impl/client/client.go#L361

This is converted into a `RetrievalOrder`:
https://github.com/filecoin-project/lotus/blob/95e47cf9982c1c3538f4de8037ca5476cbaedab0/api/api_full.go#L743-L757

When making a retrieval, if the miner's peer ID is not set, the miner's info is retrieved from state using the `RetrievalOrder.Miner` field, however this doesn't make sense if the field is a payment address (instead of a miner address):
https://github.com/filecoin-project/lotus/blob/95e47cf9982c1c3538f4de8037ca5476cbaedab0/node/impl/client/client.go#L558-L568

We should make the following changes to `QueryOffer` and `RetrievalOrder`:
- add a `PaymentAddress` field for the miner's payment address
- only use the `Miner` field for the miner's address (don't use it for the payment address)

**Comment by arajasek** [comment]
This probably goes into the broader bucket of "stuff we'd like to change in markets protocols". Need to figure out how to track them.

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system, [which reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and has been completely removed from the code:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
