### ISSUE TITLE
chain missing messages - after re-import of pruned chain. 

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/lotus#5611]
**Describe the bug**
Our Chain NVME disk failed over the weekend. I notice after 9,5 hours that we where behind on sync.
We had sectors in the loop while this happen. I replaced the disk and downloaded the pruned chain from the docs.
Caught up on sync and most of the sectors finished.
But 8 sectors didn't . They are stuck in **PreCommitWait** and **CommitWait**.
Update-state to **SubmitCommit**, or just **Remove** doesn't work. Nothing happens, no logs - no error messages.

Our chain are missing the messages for the sectors - so they are in a state that I cant delete them, and they will not be activated by the chain because the messages is not there after the import of the pruned chain. 

**To Reproduce**

1. Start sealing a sector
2. Turn off daemon
3. Let it get to CommitWait or PreCommitWait
4. Wait 9 hours, and reimport chain
5. The messages are now gone from your chain and the sector are stuck forever.

**Expected behavior**
If something like this happens, you should be able to **update-state** or have command to update the ticket to get a new message on chain so the sector will proceed. Or maybe a option to import the missing message directly from the chain. 

**Screenshots**
```
lotus-miner sectors status 3307
SectorID:	3307
Status:		PreCommitWait
CIDcommD:	baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq
CIDcommR:	bagboea4b5abcalqfrn43mwojtnp72kik252djjvyknrhfksbwsaw4dj7g2ye6wzr
Ticket:		45bcd636fb1c05f08f69135e5ec9b6b521a451caccc80604e6f65dcddd1e1dc8
TicketH:	499563
Seed:		
SeedH:		0
Precommit:	bafy2bzacec3sd2cgzidn73mdaje2akitu5qrowzv4cs7q72qf35smtibsgrkk
Commit:		<nil>
Proof:		
Deals:		[0]
```
```
3305  CommitWait     YES      NO      2053030 (in 1 year 24 weeks)   CC
  RecoveryTimeout: 541210 (in 1 week 5 days)
3306  Proving        YES      YES     2053030 (in 1 year 24 weeks)   CC
3307  PreCommitWait  NO       NO      n/a                            CC
3308  PreCommitWait  NO       NO      n/a                            CC
3309  PreCommitWait  NO       NO      n/a                            CC
3310  PreCommitWait  NO       NO      n/a                            CC
3311  PreCommitWait  NO       NO      n/a                            CC
3312  PreCommitWait  NO       NO      n/a                            CC
3313  PreCommitWait  NO       NO      n/a                            CC

```

**Version (run `lotus version`):**
I tried tag v1.4.0 and v1.5.0-Pre3 lotus version 1.4.1+mainnet+git.7e55c44d4

**Comment by PatrickDeuse** [comment]
we always keep 2 days worth of snapshots downloaded to avoid exactly what you are experiencing. the whole idea of pruning the chain is to get rid of the old messages!

**Comment by magik6k** [comment]
A solution here would be to better support fetching missing messages from the network.

If you want a workaround for now:

* Download the full chain snapshot (containing all messages) - https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/complete_chain_with_finality_stateroots_latest.car (~240G)
* Build `lotus-shed`
* Stop your lotus daemon
* Run `lotus-shed import-car [chain.car]`
* Start your lotus daemon with the `LOTUS_ENABLE_CHAINSTORE_FALLBACK=1` env var (so your node will pull missing state/receipts from the network)

**Comment by ribasushi** [comment]
@magik6k would it help if we start producing "intermediate-length" snapshots in addition to what we have now. Looks like 24h+finality is needed, i.e. ~3800 epochs?

**Comment by Reiers** [comment]
**Okay - I went for the workaround.** @magik6k 
`lotus-shed import-car complete_chain_with_finality_stateroots_latest.car`
How long should I expect the import to run?

**I needed to turn off the miner...**
Its total 193440263 Messages, so are we talking hours, days, weeks.

And yes @ribasushi it would be nice with a 24h+ finality download. In this case the miner went down for 9 hours, and already the messages it needed was long gone from the minimal chain.

**Comment by sectrgt** [comment]
We have just experienced this exact same issue, we will attempt the listed workaround and report back on the results. A built-in mechanism to protect against this would definitely be very welcomed!

**Comment by Reiers** [comment]
I can already confirm that the workaround worked @sectrgt . _It did take a while though._ So make sure to start right after your last windowPost or do it on a other node/machine, if you have one to spare just for sync and import. 

Like Patrick said there are already plenty issues related to this - so I will go ahead and close this one. 
**Since a workaround was provided worked. Thanks !**

**Comment by kernelogic** [comment]
@Reiers did you import the whole chain? How big is your .lotus folder in the end? I'm thinking of doing the same because many deals are in bad state after I prune my chain. But I'm not sure if I have the space for the full chain.

**Comment by kernelogic** [comment]
@ribasushi right now if I have unfinished deals in the daemon and for whatever reason I have to prune the chain - all these deals will show "block not found" failed state. But the my providers can just continue sealing without problem and the deal ends up on the chain just fine.

Not ideal to have inconsistent state between me (client) and my providers.

**Comment by ribasushi** [comment]
@kernelogic could you please open a new ticket with the above description and tag `@dirkmc`. This is a client UX issue that will need to be addressed separately.
