### ISSUE TITLE
lotus daemon continuously printing 'error in RPC call to 'Filecoin.StateSectorExpiration': failed to find sector xxx'

### ISSUE THREAD

**Issue by narkissos** [filecoin-project/lotus#5623]
**Describe the bug**
I tried to remove a error sector but failed, then I find lotus demon print error info continuously. I tried many times to remove the bad sector but it still stucked in 'FinalizeSector' status (Yes I also want to remove it permanetly). I tried use 'lotus-miner sectors terminate' and 'lotus-miner sector update-state' to remove bad sectors but it didn't work as well. 
Could you please help? Thanks in advace.

**To Reproduce**
1. I don't know how the bad sectors appeared, may be I reboot the server incorrectly.
2. I tried many times to use lotus-miner sectors terminate --really-do-it <sector id> to remove it, but failed. 
3. I tried to use lotus-miner sectors update-state --really-do-it <sector id> to restart/remove/terminate the sector, but got failure as well
4. Then I found the lotus damon continuosly output 'error in RPC call to 'Filecoin.StateSectorExpiration': failed to find sector xxx' in log.

**Expected behavior**
1. Remove the bad sector correctly.
2. Lotus damon stops printing huge quantitis of this error log

**Screenshots**
Please see the screenshots attached.
![screenshot](https://user-images.githubusercontent.com/3976480/108326402-28cf2880-7205-11eb-8c95-87bde3b427d6.png)
![bad sectors](https://user-images.githubusercontent.com/3976480/108326641-7055b480-7205-11eb-8880-04fda2e9ef46.png)

**Version (run `lotus version`):**
Daemon:  1.4.2+mainnet+git.61eb91ff3+api1.1.0
Local: lotus version 1.4.2+mainnet+git.61eb91ff3

**Additional context**
N/A

**Comment by Reiers** [comment]
Hi @narkissos 

If the sector is still stuck on the latest release do this: 

```
1 cd lotus/
2  make lotus-shed
3  ./lotus-shed sectors terminate --really-do-it <sectornumb>
4  wait 10 minutes
5 lotus-miner sectors remove --really-do-it <sectorsnumb>

Wait until showed Removing, then:

6 lotus-miner sectors update-state --really-do-it <sectornumb> Removed
```

There are a lot of improvements in the[ current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1), and Im sure that you are able to remove it with the regular cmd as well.  

If you are still experiencing problems - please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you!
