### ISSUE TITLE
0 FILECOIN BALANCE

### ISSUE THREAD

**Issue by human8** [filecoin-project/lotus#5630]
**Describe the bug**
On the filecoin network, the balance of the public key address shows 3.3
When accessed from the lotus daemon, it shows 0. 

The addresses match on both: f3w64b3aenmcwdl7rgs4zzbkwd33xjg25inwterodad35kcr7jihxethdm5gks4m4ejodfvwsqasgw52hct5tq

Am I misunderstanding something here? I have also lost another 7 FIL just yesterday too...

I have the copies of the files of the private keys. Not sure what to do...

**Comment by PatrickDeuse** [comment]
you are confusing a few things here:

the miner has it's own "balance" - it is not the same with the owner address balance. that is why you see 0 in the miner and 3.29 in the address

https://filfox.info/en/address/f0219326 vs. https://filfox.info/en/address/f3w64b3aenmcwdl7rgs4zzbkwd33xjg25inwterodad35kcr7jihxethdm5gks4m4ejodfvwsqasgw52hct5tq


the only way to loose FIL is when you loose the private key to the wallet those FILs are in. the 7 FIL will be somehwere - if you have the private keys you used so far then they aren't lost

**Comment by jennijuju** [comment]
On a synced node the balance is 

```lotus state get-actor f3w64b3aenmcwdl7rgs4zzbkwd33xjg25inwterodad35kcr7jihxethdm5gks4m4ejodfvwsqasgw52hct5tq
Address:	f3w64b3aenmcwdl7rgs4zzbkwd33xjg25inwterodad35kcr7jihxethdm5gks4m4ejodfvwsqasgw52hct5tq
Balance:	3.297329945084451635 FIL
Nonce:		1
Code:		bafkqadlgnfwc6mrpmfrwg33vnz2a (fil/2/account)
Head:		bafy2bzacedbzjrubhfspgjvpqtoxsmbluuqm3haxnqlpegnrvyh2ckyxsex6s```
