### ISSUE TITLE
Lotus-worker does not recognize Numa memory bounds.

### ISSUE THREAD

**Issue by Eliovp** [filecoin-project/lotus#5649]
**Description**
Lotus-worker does not recognize Numa memory bounds.

When running multiple workers to be able to divide workloads per Numa Node, Lotus only recognizes the available CPU Cores per Numa Node but does not recognize the assigned bound memory.
This will create a scenario where Lotus keeps sending workloads to a specific worker even though that worker is out of memory.
A workaround to solve this is to create a separate worker per Numa Node and to limit the number of total workloads.
This however does **not** work when having multiple units with multiple workers as it will assign workloads to an already overloaded worker. This will also not work when there is not a global limit on workloads.

**Reproduce**
1. Create multiple Numa nodes
2. Create workers that are bound to their own dedicated node
3. Lotus will see enough free memory (while this is not the case) as it does not recognize the bound memory and will overload a worker with jobs until it crashes.

**Expectation**
Very simple, add a flag to lotus-worker which limits the number of workloads to a specific worker.

**Screenshots**
![exampleWrongMemory](https://user-images.githubusercontent.com/20194745/108642811-aca83f80-74a7-11eb-9c05-5235b7238ea3.PNG)

As you can see here, 4 workers, 1 per Numa Node, 16 cores recognized perfectly, unfortunately, each worker seems to recognize 2TiB of memory while it should be 512 per Node.

**Additional context**
Again, simple flag to limit amount of workloads per worker should save a ton of headaches.

**Comment by rjan90** [comment]
Hey @Eliovp! I´m not running my workers currently with numa, so I was just wondering if you could clarify if the lotus-workers still not are recognizing Numa memory bounds?

> Expectation
> Very simple, add a flag to lotus-worker which limits the number of workloads to a specific worker.

With regards to this, that feature has now been merged https://github.com/filecoin-project/lotus/pull/8725.

**Comment by rjan90** [comment]
Closing this issue as outdate, please open if you are still experiencing issues in this situation.

```
Expectation
Very simple, add a flag to lotus-worker which limits the number of workloads to a specific worker.
```
The expected behaviour, i.e ability to limit the number of workload to a specific worker is also possible now: https://lotus.filecoin.io/storage-providers/seal-workers/seal-workers/#limit-tasks-run-in-parallel
