### ISSUE TITLE
`make clean all` actually does compiling and building

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#565]
# Description
The `make clean all` is doing compiling and bulding after I `git clone` lotus to my local computer. 

I would expect `make clean all` finish its job very quick, however, it downloading packages and doing compiling and building. 

Should we use `make all` instead of `make clean all` for this? 

# Version
Master banch
Commit: 7150ee811d14aa4f7e79aa85d0d7420cb7bc8149  (Commits on Nov 10, 2019)

**Comment by whyrusleeping** [comment]
`make clean all` is great to have in the README as it ensures people will always start from a clean repo, and gives us (the maintainers) fewer random questions from people wondering why things didnt build quite right.

Before we did this, there were a lot of random questions from people who just needed to run make clean for one reason or another. Obviously, you can run whatever command to build once you know what you are doing.

**Comment by steven004** [comment]
I got you. the `make clean all` is a combination of `make clean` and `make all`. 

When the fist time I run this command, I thought it means to make clean of all the related modules, including lotus, bls, sector-builder, etc. 

Please feel free to close it.
