### ISSUE TITLE
**Note: All the time below are in EST (UTC -05:00).**

### ISSUE THREAD

**Issue by Joss-Hua** [filecoin-project/lotus#5678]
**Note: All the time below are in EST (UTC -05:00).**
> If you have any concerns or question, leave a comment [here](https://github.com/filecoin-project/lotus/discussions/5439).

## Tentative release and upgrade timeline
- [x]  Feb 19th, [v1.5.0-rc1 release](https://github.com/filecoin-project/lotus/releases/tag/v1.5.0-rc1)
- [x]  Feb 19th, [v1.5.0-rc2 release](https://github.com/filecoin-project/lotus/releases/tag/v1.5.0-rc2)
- [x] 18:10:00, Feb 19th, calibration net reset w/ [v1.5.0-rc2 release](https://github.com/filecoin-project/lotus/releases/tag/v1.5.0-rc2)
- [x]  ~23:10:00, Feb 20th, calibration net v3 upgrade epoch **600** 
- [x]  Feb 23rd, v1.5.0 release
- [ ]  Mar 3rd,  network v10 upgrade epoch 550321 (~19:00:30, March 3rd, 2021)

_Originally posted by @jennijuju in https://github.com/filecoin-project/lotus/discussions/5617_

**Comment by rjan90** [comment]
I think this issue can be closed? As the v10 upgrade has already happened. #rengjøring
