### ISSUE TITLE
make clean all error  and  Running lotus requires a miner to have a GPU?

### ISSUE THREAD

**Issue by qizukanshijie** [filecoin-project/lotus#568]
![QQ图片20191111165504](https://user-images.githubusercontent.com/46711275/68576304-cc7d4500-04a8-11ea-9bca-d687b32acc10.png)
I cannot install these dependencies now
![QQ截图20191111173138](https://user-images.githubusercontent.com/46711275/68576451-149c6780-04a9-11ea-8850-94c835b8a3f2.png)

**Comment by Kubuxu** [comment]
@qizukanshijie instal `ocl-icd` you don't need GPU to install it and it will allow to build.
Then `make clean`, `make`.
