### ISSUE TITLE
How to adjust the starting height of lotus Base

### ISSUE THREAD

**Issue by yzn5555** [filecoin-project/lotus#5688]
Worker: 0; Base: 501379; Target: 533127 (diff: 31748)
State: message sync; Current Epoch: 508321; Todo: 24806
Validated 0 messages (0 per second)
The height difference between the base and the current target is too large. During the synchronization period, the lotus node will always be restarted. After the restart, the height of the base will not change, and the height of the target will regain a new height, causing the diff to become larger and larger. Position, when the current Epoch height reaches a certain height, modify the Base to synchronize to the specified height, so that the diff gap can be smaller

**Comment by urugang** [comment]
it would help that.
```
lotus chain sethead 508321
```

**Comment by yzn5555** [comment]
Have found a solution，Find the height you want to adjust, query the head value of this height on the block explorer, you can adjust the height through commands, and the starting height of the restart node will become the adjusted height




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/lotus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecoin-project/lotus] How to adjust the starting height of lotus Base (#5688)





 
it would help that.
 lotus chain sethead 508321

**Comment by rjan90** [comment]
Hey! This issue seems to have been resolved, and probably can be closed? #rengjøring
