### ISSUE TITLE
Where is branch ntwk-calibration ?

### ISSUE THREAD

**Issue by qings2329** [filecoin-project/lotus#5696]
I want to setup a calibration node, but there is no such ntwk-calibration branch.

And the Nerpa chain stopped at height 306019,  I can't use it for testing.

**Comment by arajasek** [comment]
Build `master` or any recent release with `make calibnet`, and you will connect to the calibration network. Run `make nerpanet` for nerpa, though that network is not currently live -- it will be reset soon.
