### ISSUE TITLE
pc2 back to p1

### ISSUE THREAD

**Issue by bugxzhu** [filecoin-project/lotus#5708]
22.	2021-03-04 04:56:18 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: storage call error 0: presealing sector 2242 (): Rust panic: no unwind information
23.	2021-03-04 04:57:18 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
24.	2021-03-04 04:57:18 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: storage call error 0: presealing sector 2242 (): Rust panic: no unwind information
25.	2021-03-04 04:58:18 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
26.	2021-03-04 04:58:18 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: storage call error 0: presealing sector 2242 (): Rust panic: no unwind information
27.	2021-03-04 04:59:18 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
28.	2021-03-04 04:59:18 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: storage call error 0: presealing sector 2242 (): Rust panic: no unwind information
29.	2021-03-04 05:00:18 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
30.	2021-03-04 08:03:44 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjFfMSIsImxhYmVscyI6eyJTdGFja2VkRHJnMzJHaUJWMSI6eyJsYWJlbHMiOlt7InBhdGgiOiIvaG9tZS9sb3R1c191c2VyL2NhY2hlL3MtdDA5NzYxOC0yMjQyIiwiaWQiOiJsYXllci0xIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9sb3R1c191c2VyL2NhY2hlL3MtdDA5NzYxOC0yMjQyIiwiaWQiOiJsYXllci0yIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9sb3R1c191c2VyL2NhY2hlL3MtdDA5NzYxOC0yMjQyIiwiaWQiOiJsYXllci0zIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9sb3R1c191c2VyL2NhY2hlL3MtdDA5NzYxOC0yMjQyIiwiaWQiOiJsYXllci00Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9sb3R1c191c2VyL2NhY2hlL3MtdDA5NzYxOC0yMjQyIiwiaWQiOiJsYXllci01Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9sb3R1c191c2VyL2NhY2hlL3MtdDA5NzYxOC0yMjQyIiwiaWQiOiJsYXllci02Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9sb3R1c191c2VyL2NhY2hlL3MtdDA5NzYxOC0yMjQyIiwiaWQiOiJsYXllci03Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9sb3R1c191c2VyL2NhY2hlL3MtdDA5NzYxOC0yMjQyIiwiaWQiOiJsYXllci04Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9sb3R1c191c2VyL2NhY2hlL3MtdDA5NzYxOC0yMjQyIiwiaWQiOiJsYXllci05Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvaG9tZS9sb3R1c191c2VyL2NhY2hlL3MtdDA5NzYxOC0yMjQyIiwiaWQiOiJsYXllci0xMCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2hvbWUvbG90dXNfdXNlci9jYWNoZS9zLXQwOTc2MTgtMjI0MiIsImlkIjoibGF5ZXItMTEiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9XSwiX2giOm51bGx9fSwiY29uZmlnIjp7InBhdGgiOiIvaG9tZS9sb3R1c191c2VyL2NhY2hlL3MtdDA5NzYxOC0yMjQyIiwiaWQiOiJ0cmVlLWQiLCJzaXplIjoyMTQ3NDgzNjQ3LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LCJjb21tX2QiOls3LDEyNiw5NSwyMjIsNTMsMTk3LDEwLDE0NywzLDE2NSw4MCw5LDIyNyw3MywxMzgsNzgsMTkwLDIyMywyNDMsMTU2LDY2LDE4MywxNiwxODMsNDgsMjE2LDIzNiwxMjIsMTk5LDE3NSwxNjYsNjJdfQ=="}}
31.	2021-03-04 08:03:46 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: storage call error 0: presealing sector 2242 (): Rust panic: no unwind information
32.	2021-03-04 08:04:46 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
33.	2021-03-04 08:04:46 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: storage call error 0: presealing sector 2242 (): Rust panic: no unwind information
34.	2021-03-04 08:05:46 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
35.	2021-03-04 08:05:46 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: storage call error 0: presealing sector 2242 (): Rust panic: no unwind information
36.	2021-03-04 08:06:46 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
37.	2021-03-04 08:06:46 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: storage call error 0: presealing sector 2242 (): Rust panic: no unwind information
38.	2021-03-04 08:07:46 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}

**Comment by jburnett** [comment]
May be same as #5706

**Comment by jburnett** [comment]
@bugxzhu which version of Nvidia drivers are installed?  Check with _nvidia-smi_. We had to revert from 460 to 450.66 and are now completing PC2 (without rust panics).  See this [slack thread](https://filecoinproject.slack.com/archives/CEGN061C5/p1614783292319600).

HTH

**Comment by rjan90** [comment]
Hi. Are you still seeing this issue, or can this issue be closed? #rengjøring

**Comment by Reiers** [comment]
**Closing this ticket.**
If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
