### ISSUE TITLE
Network version 12

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#5715]
This is assuming version 11 is the sectors extension.

Just a quick place to catch stuff we probably want in the next network upgrade:

- FIP-0013
- Delete dead miners (there's lots of inactive miners, funds can be returned to owners)

**Comment by jburnett** [comment]
+1 for quicker renewal of expired ticket: #5501, #5526 & #5527

**Comment by deltazxm** [comment]
FIP-0014

**Comment by f8-ptrk** [comment]
do not delete dead miners. people paid for creating them!
