### ISSUE TITLE
StorageDealError to StorageDealRejected

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/lotus#5719]
**Describe the bug**

Just a minor thing - is it possible to change **StorageDealError** to **StorageDealRejected** in a future update?
Every time we get a **StorageDealError** I need to pull up the logs and find out why the deal failed.
Again - its not a huge deal _no pun intended_. Just easier to monitor the `lotus-miner storage-deals list`.

**To Reproduce**

Deal is rejected , because of the price or the piece is to small or large.
`lotus-miner storage-deals list
`
The deal show up as StorageDealError.

**Expected behavior**

The miner logs states the reason, price too low or size to small/large. 
lotus-miner storage-deals list should show **StorageDealRejected** so we as miners don’t have to look trough the logs to make sure that it wasn’t  a connection error or sealing problem.

**Version (run `lotus version`):**
v1.5.0+mainnet+git.55b85f314

**Comment by RobQuistNL** [comment]
+1 for this.

If a deal fails because of the filter not allowing it (but it got through the initial price check) - it will end up as StorageDealError.

**Comment by SBudo** [comment]
+1
It would be good to not have deals marked as "error" when they are not really errors.
Especially for future use so we can demonstrate the quality of each miner based on deals success rate

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks :pray:
