### ISSUE TITLE
The stateGetReceipt method reports an error!

### ISSUE THREAD

**Issue by Yangxin-GG** [filecoin-project/lotus#5720]
**Describe the bug**
rpc calls the stateGetReceipt method to report an error: checking for message execution during lookback: amt load: failed to root: blockstore: block not found
However, the transaction can be found in the chainGetBlockMessages method call, and chainGetMessage can also be successfully called

**To Reproduce**
The height of the messages in 550662 and 550731 is the same, it may be that there is a problem with the wallet synchronization

**Expected behavior**
I certainly hope it will not have such problems in the future

**Version (run `lotus version`):1.5.0+mainnet+git.55b85f314

**Additional context**
no，The only difference is that it has recently updated 1.5.0

**Comment by crow123** [comment]
Has this problem been solved？

**Comment by rjan90** [comment]
I think this issue can be closed now. Getting _block not found_ usually indicates that something is wrong with your chain. In this case this was around the v1.5 release where some node saw problems with the chain, but this was fixed in the later releases v1.5.x and up #rengjøring

**Comment by Reiers** [comment]
Solved.

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
