### ISSUE TITLE
lotus client deal (interactive) doesn't filter by min piece size

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#5736]
**Describe the bug**

I used `lotus client deal` interactively to try to place a deal with miner f022352 for a 256MiB deal.

Lotus client deal sent the deal, but it failed with: `unexpected deal status while waiting for data request: 11 (StorageDealFailing). Provider message: deal rejected: piece size less than minimum required size: 268435456 < 1073741824` 

Here's the ask for that miner:

```
$ lotus client query-ask f022352
Ask: f022352
Price per GiB: 0.000000018 FIL
Verified Price per GiB: 0 FIL
Max Piece size: 32 GiB
Min Piece size: 1 GiB
```

Since `lotus client deal` knew the size of my data, it really should have filtered out miner f022352 as a potential miner for the deal based on the ask it received.

**To Reproduce**
1. Import a 256MiB file
2. Try to use `lotus client deal` to make an interactive deal with miner f022352 (or any other miner with a high "Min Piece Size" ask)

**Expected behavior**

The client should filter out the miners that won't accept the piece size from the list of candidate miners.

**Version (run `lotus version`):**

```
$ lotus version
Daemon:  1.5.0+mainnet+git.191a05da4+api1.1.0
Local: lotus version 1.5.0+mainnet+git.191a05da4
```

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks :pray:
