### ISSUE TITLE
Ability to clear rejected deals from lotus-miner storage-deals list

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#5747]
**Describe the bug**
Currently lotus-miner storage-deals list contains rejected deals forever (due to size or price) - it can be a concern of miner's database size.

Would be great to have a way to turn this off. Rejected deals is not very useful for auditing purpose.

**Comment by rjan90** [comment]
Hey @kernelogic! Thanks for this ticket and feature request. Given that the Lotus-Miner Markets sub-system has reached EOL, and will be depreciated after nv21, I´m closing this ticket as something that we will not be worked on.
