### ISSUE TITLE
piece size less than minimum required

### ISSUE THREAD

**Issue by linmuqin** [filecoin-project/lotus#576]
Error:deal bafyreigetxgmgeesz4tqzacrjcfejthdr2lw4wze5wdwpd37ovrjbyvwpm failed: piece size less than minimum required size: 0 < 256

I made a deal following the instructions, but the piece size less than minimum required. What caused this？

**Comment by magik6k** [comment]
The file passed to `lotus client import` should have minimum size of 256b. We should fix the readme
