### ISSUE TITLE
NodeStatus API Endpoint for checking node health

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#5762]
Initially, it would be used to confirm that node is in a good state before producing a message.

Checks proposed:
- the sync status: how far out of sync the node is.
   - Use the difference between the current time and genesis to figure out which epoch we should be at.
- peering status: do we have more than 5 peers with positive pubsub scores?
   - i.e. are we confident that if we send this message now, it will be properly propagated to the network?

**Comment by magik6k** [comment]
Maybe also some chain health metric, based on something like the number of blocks in last X epochs vs the expected number

**Comment by raulk** [comment]
Closed in https://github.com/filecoin-project/lotus/pull/5767.
