### ISSUE TITLE
MpoolHealth API Endpoint for checking health of given sender

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#5763]
- arguments: sender address; array of new messages to be additionally validated
- check messages from sender’s mpool with new messages for consistency and balances
- emit warnings and errors on per message (or global if applicable) scope
- don’t stop at the first error

Checks:
- there is no nonce gap for the sender, messages can be selected
- message selection check should verify that messages have FeeCap buffer of _?_ blocks with max BaseFee growth
- check that balance allows to cover all messages for the worst-case scenario (full gas usage and BaseFee = FeeCap), issue warning otherwise
- messages are valid for inclusion

**Comment by vyzo** [comment]
So I don't think we need to pass the sender address -- just the messages themselves would do, they contain the server address already.

**Comment by raulk** [comment]
Solved in https://github.com/filecoin-project/lotus/issues/5763.
