### ISSUE TITLE
wallet balance

### ISSUE THREAD

**Issue by gy810986741** [filecoin-project/lotus#577]
Hello, I followed the steps and sent some founds to my address[t3recx27psvyl2dlyovkfcdyoknog3nqp3hyabovjhlfxyiyabbm64buv77v3gb3qc7jnlwioiddxviju6rzhq], but the balance was still 0, is there any mistake ?

**Comment by walkerxin** [comment]
I have the same problem as your description. How do you solve it?

**Comment by gy810986741** [comment]
> I have the same problem as your description. Do you get enough funds?

Yes, I got some ,but it seems I can only get 0.005 or around this number each time when I request for fund sending. And there is another problem I met, after I initiated the miner and tried to start mining, there was an error said 'ProvingPeriodEnd == 0'... This problem has plagued me for several days....
