### ISSUE TITLE
v1.5.0 start miner failed

### ISSUE THREAD

**Issue by hsn999** [filecoin-project/lotus#5793]
could not build arguments for function "github.com/filecoin-project/lotus/node/modules".HandleDeals (/home/vm/hsn/lotus/node/modules/storageminer.go:261): failed to build storagemarket.StorageProvider: could not build arguments for function "reflect".makeFuncStub (/home/vm/go/src/reflect/asm_amd64.s:12): failed to build *storedask.StoredAsk: could not build arguments for function "reflect".makeFuncStub (/home/vm/go/src/reflect/asm_amd64.s:12): failed to build storagemarket.StorageProviderNode: could not build arguments for function "reflect".makeFuncStub (/home/vm/go/src/reflect/asm_amd64.s:12): failed to build *sectorblocks.SectorBlocks: could not build arguments for function "reflect".makeFuncStub (/home/vm/go/src/reflect/asm_amd64.s:12): failed to build *storage.Miner: could not build arguments for function "reflect".makeFuncStub (/home/vm/go/src/reflect/asm_amd64.s:12): failed to build sectorstorage.SectorManager: could not build arguments for function "reflect".makeFuncStub (/home/vm/go/src/reflect/asm_amd64.s:12): failed to build *sectorstorage.Manager: received non-nil error from function "reflect".makeFuncStub (/home/vm/go/src/reflect/asm_amd64.s:12): opening path /lotus-data/f015926: parse sector id .s-t015926-3304.AAtrUy: sscanf sector name ('.s-t015926-3304.AAtrUy'): input does not match format

**Comment by hsn999** [comment]
start brand new miner is ok

**Comment by yuanlizbyy** [comment]
This is because you have a file named .s-t015926-3304.AAtrUy in your storage folder, which is causing lotus to fail to parse. Delete this file or name it to the correct name format and you will be OK.

**Comment by rjan90** [comment]
Hi. I think this issue can be solved, as it seems like yuanlizbyy gave you a solution to your problem. #rengjøring

**Comment by Reiers** [comment]
This is solved.

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
