### ISSUE TITLE
[BUG] opening path /cachedisk/seal: parse sector id api: sscanf sector name ('api'): input does not match format

### ISSUE THREAD

**Issue by johnjiangok** [filecoin-project/lotus#5797]
restart lotus-miner , lotus-miner does not work.

ERROR: creating node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules".HandleDeals (/home/block/lotus/lotus/node/modules/storageminer.go:261): failed to build storagemarket.StorageProvider: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *storedask.StoredAsk: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build storagemarket.StorageProviderNode: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sectorblocks.SectorBlocks: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *storage.Miner: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build sectorstorage.SectorManager: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sectorstorage.Manager: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): opening path /cachedisk/seal: parse sector id api: sscanf sector name ('api'): input does not match format

**Comment by micahpw** [comment]
Check to see if your path "/cachedisk/seal" contains any extra directories or files within that weren't generated by lotus or that don't follow the typical file format. I had a similar trouble starting up my miner since I had an extra directory within my storage path/directory.

**Comment by rjan90** [comment]
Closing this issue since @micahpw gave the correct answer & fix to why the `lotus-miner` could not start.
