### ISSUE TITLE
After blockpublish deals multiple AddPiece tasks run in parallel then go straight to PC1 without WaitDeals task

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#5809]
**Describe the bug**
While the new batch Publish feature is very welcome, the new behavior is that multiple small deals each get put into their own sector and then WaitDeals task is skipped. Additionally, a WaitDeals sector with no deals is also created at this time and one of the Deals is lost in a storage-deal "staged" status which will not be recovered until lotus-miner is restarted.

**Version (run `lotus version`):**
1.5.2+mainnet+git.09e78a0fe

**To Reproduce**
1. Import multiple offline deals using the batch publish settings (I allow up to 16 deals in 6 hours) but this happens with as few as 4 deals.
2. See attached file
[Staged-WaitDeals.txt](https://github.com/filecoin-project/lotus/files/6135990/Staged-WaitDeals.txt)

**Expected behavior**
After batched deals publish:
1. AddPiece should run sequentially (series not parallel) going into a WaitDeal sector until sector is full
2. No additional "CC" WaitDeal sectors that are empty should be created.
3. Deals should not be marked as Staged if there are available WaitDeals sectors available or can be created

**Logs**
See attached file
 
**Screenshots**
See attached image for orphaned staged deal which is available to miner only after restart
![Staged Deal](https://user-images.githubusercontent.com/49840642/111055827-bb9b6580-8447-11eb-8707-4bf001ec00c3.png)

**Additional context**
See Slack Discussion https://filecoinproject.slack.com/archives/G01KU7G441Y/p1615648834210200

**Comment by stuberman** [comment]
Additional images from newer import of 5 deals
![Import 5 offline deals](https://user-images.githubusercontent.com/49840642/111056353-8ba29100-844c-11eb-82d6-e2ea811295da.png)

<img width="1859" alt="Logs of import and AddPieces" src="https://user-images.githubusercontent.com/49840642/111056352-8a716400-844c-11eb-9f5c-1849e750d81e.png">

![Lotus-miner sealing jobs](https://user-images.githubusercontent.com/49840642/111056351-8a716400-844c-11eb-842e-db3fa87eaabe.png)

**Comment by stuberman** [comment]
An
![4 deal publish batch](https://user-images.githubusercontent.com/49840642/111203056-e9dd8a00-859a-11eb-9008-04e9c7bd66bc.png)
other publish deals now batch of 4 deals resulted in 6 new sectors - two "Wait Deals"

> 2021-03-15T18:25:30.361Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventFundsReleased", "proposal CID": "bafyreih5imraxfyypv3dgd23howhsfyypkm26upws5zbs4zn7dh2m66yy4", "state": "StorageDealPublishing", "message": ""}
> 2021-03-15T18:25:30.361Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventFundsReleased", "proposal CID": "bafyreihk26qpemjd4xnc2r5scblkkmnfgchgwfvhsycpaahiadrrh5idgu", "state": "StorageDealPublishing", "message": ""}
> 2021-03-15T18:25:30.362Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventFundsReleased", "proposal CID": "bafyreienvr25y3dpdtjc6jg6tqptvw4gbnyyik3cmegi23ehrguivqpzsu", "state": "StorageDealPublishing", "message": ""}
> 2021-03-15T18:25:30.365Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventFundsReleased", "proposal CID": "bafyreibx24zmf4rfdffewrn7yiid5kwgmo2gzn6ccztmgdg6jr4bhniyiu", "state": "StorageDealPublishing", "message": ""}
> 2021-03-15T18:25:30.383Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventDealPublished", "proposal CID": "bafyreih5imraxfyypv3dgd23howhsfyypkm26upws5zbs4zn7dh2m66yy4", "state": "StorageDealStaged", "message": ""}
> 2021-03-15T18:25:30.396Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventDealPublished", "proposal CID": "bafyreihk26qpemjd4xnc2r5scblkkmnfgchgwfvhsycpaahiadrrh5idgu", "state": "StorageDealStaged", "message": ""}
> 2021-03-15T18:25:30.401Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventDealPublished", "proposal CID": "bafyreienvr25y3dpdtjc6jg6tqptvw4gbnyyik3cmegi23ehrguivqpzsu", "state": "StorageDealStaged", "message": ""}
> 2021-03-15T18:25:30.417Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventDealPublished", "proposal CID": "bafyreibx24zmf4rfdffewrn7yiid5kwgmo2gzn6ccztmgdg6jr4bhniyiu", "state": "StorageDealStaged", "message": ""}
> 2021-03-15T18:25:30.426Z	INFO	sectors	storage-sealing/input.go:228	Adding piece for deal 1607471 (publish msg: bafy2bzacecj23pzencu7dikkpyyaoujikjs76nrtgurzhbz3hvct7uijwrvoc)
> 2021-03-15T18:25:30.433Z	INFO	sectors	storage-sealing/input.go:228	Adding piece for deal 1607472 (publish msg: bafy2bzacecj23pzencu7dikkpyyaoujikjs76nrtgurzhbz3hvct7uijwrvoc)
> 2021-03-15T18:25:30.446Z	INFO	sectors	storage-sealing/input.go:228	Adding piece for deal 1607473 (publish msg: bafy2bzacecj23pzencu7dikkpyyaoujikjs76nrtgurzhbz3hvct7uijwrvoc)
> 2021-03-15T18:25:30.459Z	INFO	sectors	storage-sealing/input.go:228	Adding piece for deal 1607474 (publish msg: bafy2bzacecj23pzencu7dikkpyyaoujikjs76nrtgurzhbz3hvct7uijwrvoc)
> 2021-03-15T18:25:30.463Z	WARN	advmgr	sector-storage/manager.go:323	stub NewSector
> 2021-03-15T18:25:30.463Z	INFO	sectors	storage-sealing/input.go:397	Creating sector	{"number": "812", "type": "deal", "proofType": 8}
> 2021-03-15T18:25:30.480Z	WARN	advmgr	sector-storage/manager.go:323	stub NewSector
> 2021-03-15T18:25:30.480Z	INFO	sectors	storage-sealing/input.go:397	Creating sector	{"number": "813", "type": "deal", "proofType": 8}
> 2021-03-15T18:25:30.504Z	WARN	advmgr	sector-storage/manager.go:323	stub NewSector
> 2021-03-15T18:25:30.504Z	INFO	sectors	storage-sealing/input.go:397	Creating sector	{"number": "814", "type": "deal", "proofType": 8}
> 2021-03-15T18:25:30.516Z	WARN	advmgr	sector-storage/manager.go:323	stub NewSector
> 2021-03-15T18:25:30.516Z	INFO	sectors	storage-sealing/input.go:397	Creating sector	{"number": "815", "type": "deal", "proofType": 8}
> 2021-03-15T18:25:30.534Z	WARN	advmgr	sector-storage/manager.go:323	stub NewSector
> 2021-03-15T18:25:30.534Z	INFO	sectors	storage-sealing/input.go:397	Creating sector	{"number": "816", "type": "deal", "proofType": 8}
> 2021-03-15T18:25:30.586Z	WARN	advmgr	sector-storage/manager.go:323	stub NewSector
> 2021-03-15T18:25:30.586Z	INFO	sectors	storage-sealing/input.go:397	Creating sector	{"number": "817", "type": "deal", "proofType": 8}

**Comment by cwhiggins** [comment]
<pre>1760  <font color="#C4A000">PreCommit1</font>     <font color="#CC0000">NO</font>       <font color="#CC0000">NO</font>      n/a                             <font color="#4E9A06">1</font>                                 
1761  <font color="#C4A000">PreCommit1</font>     <font color="#CC0000">NO</font>       <font color="#CC0000">NO</font>      n/a                             <font color="#4E9A06">1</font>                                 
1762  <font color="#3465A4">AddPiece</font>       <font color="#CC0000">NO</font>       <font color="#CC0000">NO</font>      n/a                             <font color="#3465A4">CC</font>                                
1763  <font color="#3465A4">WaitDeals</font>      <font color="#CC0000">NO</font>       <font color="#CC0000">NO</font>      n/a                             <font color="#3465A4">CC</font></pre>

I am experiencing similar behavior. Batch publish 3 deals. Three sectors of AP and an extra wait deals sector popped up. On an earlier batch 2 wait deals sectors were created. next batch used the sectors that were created, so it did not stop flow, but it is not right.  Also  wait delay is no longer working, deals go from batch publish->AP->PC1. As soon as AP is finished sectors are going to PC1 with no delay.

**Comment by kernelogic** [comment]
Seems this batch publish supersedes whatever was working before, regardless of waitdeals limit or maxsealingsectorsfordeals limit.

**Comment by arajasek** [comment]
Closed by https://github.com/filecoin-project/filecoin-docs/pull/761
