### ISSUE TITLE
Upgrade to proofs 6.1.0

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#5816]
Related work: https://github.com/filecoin-project/filecoin-ffi/pull/170

This will require some special-casing due to siggy verification changes.

**Comment by dignifiedquire** [comment]
@arajasek not sure what versioning scheme you use on the go side, but from the rust side the release is `6.1.0`

**Comment by arajasek** [comment]
> @arajasek not sure what versioning scheme you use on the go side, but from the rust side the release is `6.1.0`

Oops, thanks!
