### ISSUE TITLE
[BUG] Retrieval deal fails with "deal data transfer failed: incomplete response" - Client Side

### ISSUE THREAD

**Issue by ethanwu155** [filecoin-project/lotus#5829]
**Describe the bug**
Client cannot get stored file on FileCoin from miner. Stored file has `StorageDealActive` Status.

**Version (run `lotus version`):**
lotus version 1.5.0+mainnet+git.191a05da4

**To Reproduce**
1. Run `lotus client retrieve --miner <minerID> <data CID> <output file>`
2. Get the following error: 

```
ERROR: retrieval failed: Retrieve: Retrieval Error: error generated by data transfer: deal │ data transfer failed: incomplete response
```

**Expected behavior**
Expect to be able to retrieve stored file.

**Logs**
```
$ lotus client retrieve --miner f066596 bafyaa6qsgafcmalqudsaeiekkmiypfxq6vgdwepdafg6jyacye46gurjichuapbzxwqhoywq7yjaagelucbyabasgafcmalqudsaeif3e6tsyc7c3anlmobix3744duq7cyasjsmrsmbkdn4besizu5ffyjaagf6zcc36aykcqeaeghh3sbl6bzaqcaibaaeedt5zav7am output.mp4                                                                                       
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)                                  
> Recv: 0 B, Paid 0 FIL, ClientEventDealProposed (DealStatusWaitForAcceptance)            
> Recv: 122 B, Paid 0 FIL, ClientEventBlocksReceived (DealStatusWaitForAcceptance)        
> Recv: 122 B, Paid 0 FIL, ClientEventDealAccepted (DealStatusAccepted)                   
> Recv: 122 B, Paid 0 FIL, ClientEventPaymentChannelAddingFunds (DealStatusPaymentChannelAllocatingLane)                                                                            
> Recv: 122 B, Paid 0 FIL, ClientEventLaneAllocated (DealStatusOngoing)                   
> Recv: 122 B, Paid 0 FIL, ClientEventDataTransferError (DealStatusErrored)               
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)                                  
ERROR: retrieval failed: Retrieve: Retrieval Error: error generated by data transfer: deal data transfer failed: incomplete response 
 ```
 
**Screenshots**
See attachment

**Additional context**
None
<img width="638" alt="Screen Shot 2021-03-17 at 3 23 16 PM" src="https://user-images.githubusercontent.com/17772957/111430619-90f62900-8735-11eb-85db-863c376c8a26.png">

**Comment by kernelogic** [comment]
This is caused by two things:
https://github.com/filecoin-project/lotus/issues/5821
https://github.com/filecoin-project/lotus/issues/5409

The miner you tested have set unseal price to be non-zero. So it just go back to non-fast-retrieval, and unsealing failed.

**Comment by flyworker** [comment]
we tested both on 1.5.0 and 1.5.3 both have similar issue.

**Comment by boqian-nbai** [comment]
> This is caused by two things:
> #5821
> #5409
> 
> The miner you tested have set unseal price to be non-zero. So it just go back to non-fast-retrieval, and unsealing failed.

We have set unseal price to zero but failed.

**Comment by boqian-nbai** [comment]
We have exactly the same issue.

Client Side:
```
$ lotus client retrieve  --miner f019104 --pieceCid=baga6ea4seaqn6mlouekcaghi574xvkshq4kdkk57yboy5focxatabfio4iytwii mAXCg5AIgcSJzsW/ogYWKQQaYZruCwaGaqGmWMSNKDOKbR3W5x5s test-retrieval
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
> Recv: 0 B, Paid 0 FIL, ClientEventDealProposed (DealStatusWaitForAcceptance)
> Recv: 0 B, Paid 0 FIL, ClientEventDealAccepted (DealStatusAccepted)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelAddingFunds (DealStatusPaymentChannelAllocatingLane)
> Recv: 0 B, Paid 0 FIL, ClientEventLaneAllocated (DealStatusOngoing)
> Recv: 0 B, Paid 0 FIL, ClientEventDataTransferError (DealStatusErrored)
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
ERROR: retrieval failed: Retrieve: Retrieval Error: error generated by data transfer: deal data transfer failed: incomplete response
```

Miner Side:
```
Mar 17 17:38:36 miner4 lotus-miner[14143]: 2021-03-17T17:38:36.041Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventOpen", "deal ID": "15", "receiver": "12D3KooWLb3vya3V3ZU39jZRfVsTEY6KB93czht8AdVAF3pMCgqA", "state": "DealStatusNew", "message": ""}
Mar 17 17:38:36 miner4 lotus-miner[14143]: 2021-03-17T17:38:36.069Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventDealAccepted", "deal ID": "15", "receiver": "12D3KooWLb3vya3V3ZU39jZRfVsTEY6KB93czht8AdVAF3pMCgqA", "state": "DealStatusUnsealing", "message": ""}
Mar 17 17:40:34 miner4 lotus-miner[14143]: 2021-03-17T17:40:34.586Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventUnsealComplete", "deal ID": "15", "receiver": "12D3KooWLb3vya3V3ZU39jZRfVsTEY6KB93czht8AdVAF3pMCgqA", "state": "DealStatusUnsealed", "message": ""}
Mar 17 17:40:34 miner4 lotus-miner[14143]: 2021-03-17T17:40:34.597Z        INFO        dt-impl        impl/impl.go:370        resume channel 12D3KooWLb3vya3V3ZU39jZRfVsTEY6KB93czht8AdVAF3pMCgqA-12D3KooWH5PDdPxQsPSegABD8FUkSvcg7czGYWwWsj666aEAhyDx-15
Mar 17 17:40:34 miner4 lotus-miner[14143]: 2021-03-17T17:40:34.598Z        INFO        graphsync        responsemanager/responsemanager.go:481        response failed: %!w(traversal.SkipMe={})
Mar 17 17:40:34 miner4 lotus-miner[14143]: 2021-03-17T17:40:34.608Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventDataTransferError", "deal ID": "15", "receiver": "12D3KooWLb3vya3V3ZU39jZRfVsTEY6KB93czht8AdVAF3pMCgqA", "state": "DealStatusErrored", "message": "deal data transfer failed: incomplete response"}
```

**Comment by pooja** [comment]
Some related miner logs: 
![Screen Shot 2021-03-18 at 11 54 34 AM](https://user-images.githubusercontent.com/5668171/111681660-bbe98700-87e0-11eb-8734-5572b783185b.png)

**Comment by ethanwu155** [comment]
I upgraded `lotus` to 1.5.3rc and tried to run the retrieval again and the result is the same.

<img width="1280" alt="Screen Shot 2021-03-19 at 9 16 05 PM" src="https://user-images.githubusercontent.com/17772957/111788235-cdbf4d00-88fa-11eb-96bb-4e2fb70ec029.png">

**Comment by dirkmc** [comment]
It seems that the error is getting lost somewhere in the unsealing code.
First step is to have better error logging on unseal failure: https://github.com/filecoin-project/lotus/pull/5851

**Comment by dirkmc** [comment]
We need to bubble up the fix for a better message than "incomplete response" from https://github.com/filecoin-project/go-data-transfer/pull/145

**Comment by dirkmc** [comment]
In go-fil-markets close the reader after unsealing completes, and check the result of the close to see if it returns an error: https://github.com/filecoin-project/go-fil-markets/pull/507

**Comment by dirkmc** [comment]
Release markets v1.2.0: https://github.com/filecoin-project/go-fil-markets/pull/509
Next we need to bubble up to lotus and test out the release manually.

**Comment by pooja** [comment]
Hey team, adding a couple other details:
- The storage deal was made with an offline data transfer
- The miner was storing an unsealed copy of the data. Not sure if an unseal was triggered. Have asked the team to chime in here!

**Comment by kernelogic** [comment]
@dirkmc it's pretty easy to reproduce - let me know if there's a release that can be tested with I'll be happy to do it.

**Comment by dirkmc** [comment]
Thanks, that would be great - we're testing out the release and once it's ready we'd love for you to test it.
I'm not sure that the change I've made will fix the bug, as it may be on the unsealing side. But it should at least give more information in the logs.

**Comment by jamerduhgamer** [comment]
Looks like unsealing did occur even though we had an unsealed copy of the data. Pictures of the log from the miner below.
<img width="955" alt="Deal ID 4 Unseal" src="https://user-images.githubusercontent.com/16791309/112065438-db0a5080-8b21-11eb-976f-67ae8c04a6a0.png">
<img width="955" alt="Deal ID 4 Unseal Complete" src="https://user-images.githubusercontent.com/16791309/112065568-13aa2a00-8b22-11eb-9e52-0a6eee0a76f6.png">
<img width="958" alt="Graphsync ReceiveError" src="https://user-images.githubusercontent.com/16791309/112065448-e2315e80-8b21-11eb-88ed-349da58808c7.png">

**Comment by jamerduhgamer** [comment]
This is the corresponding journal entry for the retrieval deal above.
[Lotus Journal for DealID 4.txt](https://github.com/filecoin-project/lotus/files/6185916/Lotus.Journal.for.DealID.4.txt)

**Comment by jennijuju** [comment]
assigned as `blocked` b/c according to  https://github.com/filecoin-project/lotus/issues/5829#issuecomment-804242229 May be fixed  the new market release

**Comment by kernelogic** [comment]
@f8-ptrk stored a deal from me with fast-retrieval, he also set the unsealing price to 1 FIL.
When I do the retrieval with him, guess what, it immediately failed with the "incomplete response" message and he obtained 1 FIL from me.

@dirkmc if you think it is just a confusing message, no unsealing happened, I don't know how to explain the fee then

lotus client retrieve --miner f062353 bafykbzacebcilfo3sfu4o6re5lz7zh66xdz6la74nmp7y7idcofeysuvnb7p2 /mnt/ipfs/CC-MAIN-2018-47-index.tar.05
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
> Recv: 0 B, Paid 0 FIL, ClientEventDealProposed (DealStatusWaitForAcceptance)
> Recv: 0 B, Paid 0 FIL, ClientEventUnsealPaymentRequested (DealStatusAccepted)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelAddingFunds (DealStatusPaymentChannelAllocatingLane)
> Recv: 0 B, Paid 0 FIL, ClientEventLaneAllocated (DealStatusOngoing)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)
> Recv: 0 B, Paid 0 FIL, ClientEventSendFunds (DealStatusSendFunds)
> Recv: 0 B, Paid 0 FIL, ClientEventVoucherShortfall (DealStatusCheckFunds)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelAddingFunds (DealStatusPaymentChannelAddingFunds)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelReady (DealStatusOngoing)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)
> Recv: 0 B, Paid 0 FIL, ClientEventSendFunds (DealStatusSendFunds)
> Recv: 0 B, Paid 1 FIL, ClientEventPaymentSent (DealStatusOngoing)
> Recv: 0 B, Paid 1 FIL, ClientEventDataTransferError (DealStatusErrored)
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
ERROR: retrieval failed: Retrieve: Retrieval Error: error generated by data transfer: deal data transfer failed: incomplete response


https://filfox.info/en/message/bafy2bzaced7csrimf3r5kds6cmz3zw6o5pdaal6qw6gxtpa5bnhhktdimwerw

**Comment by kernelogic** [comment]
Re-tested retrieval on my own miner for both unseal price is zero (successful) and non-zero (failed). In the log there's some weirdness about unsealing (shouldn't even happen, deal is fast-retreival), also some weirdness about cancel-transfer saying channel not found.

lotus -v
lotus version 1.5.3+mainnet+git.358773e2b

[unsealprice_nonzero_failure.txt](https://github.com/filecoin-project/lotus/files/6226562/unsealprice_nonzero_failure.txt)
[unsealprice_zero_success.txt](https://github.com/filecoin-project/lotus/files/6226565/unsealprice_zero_success.txt)

**Comment by dirkmc** [comment]
Likely root cause: https://github.com/filecoin-project/go-fil-markets/issues/528
