### ISSUE TITLE
[Feature Request] Request to add option to disable automatic sealing of WaitDeals sectors.

### ISSUE THREAD

**Issue by TippyFlitsUK** [filecoin-project/lotus#5830]
1.5.X has brought multiple improvements to the deal making process including a new feature that automatically starts the sealing process of a `WaitDeals` sector once it is full, thus overriding the `WaitDealsDelay `setting in `.lotusminer/config.toml`.

Whilst this is an understandable and appreciated enhancement it also adds a level of unpredictability when trying to manage a complex sealing schedule with finite resources.

It would be very useful if it were possible to disable this new feature and revert strictly to the value specified in the `WaitDealsDelay` setting as in previous releases.

Many thanks team!!

**Comment by Reiers** [comment]
Thanks for the ticket !
