### ISSUE TITLE
[Feature Request] Migrate to more compact deal label

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#5849]
The labels placed in deals are currently a rather clunkily large object:
```json
{
	"pcids": [
		{
			"/": "bafykbzacea7zjgrqpknujdnrejhaoheef6xixwuv3hmdcqyo53hh2qiv73nfu"
		}
	]
}
```
The data is human readable json, with newlines and padding. This is an obnoxiously large amount of extra data to be put on chain. We should absolutely compact this.

My proposal is to use a cbor map. We can keep the 'pcids' string, but the contents should all be binary (no base32 encoded cids)

**Comment by ribasushi** [comment]
@whyrusleeping this has not been the case for a while, the `Label` field "evolved" through:
- json ( the thing you complain about )
- then shortly before mainnet it became cbor-in-a-text-string, causing all kinds of havoc on deserializers
- shortly after mainnet it is just a single text-cid string, either Qm (v0) or b64 `m...` (v1) : https://github.com/filecoin-project/go-fil-markets/blob/master/storagemarket/impl/clientutils/clientutils.go#L63-L71

**Comment by whyrusleeping** [comment]
@ribasushi oh amazing. I guess just the random selection of deals i was looking at had this. Sorry for the churn :)
