### ISSUE TITLE
TestDealFlow is flaky

### ISSUE THREAD

**Issue by vyzo** [filecoin-project/lotus#5896]
This test lives in `cmd/lotus-gateway` and intermittently fails, both locally and on Circle; quite annoying.

**Comment by Stebalien** [comment]
@Kubuxu wasn't this fixed with the libp2p mocknet changes?

**Comment by Stebalien** [comment]
Same with this one: https://github.com/filecoin-project/lotus/issues/4812?

**Comment by Kubuxu** [comment]
libp2p mocknet would fix nodes not proceeding to sync, IDK if that was the case here

**Comment by Stebalien** [comment]
I _think_ that was the case. At least I haven't seen this since. I'll just close it and we can reopen if it's still an issue.
