### ISSUE TITLE
[Feature Request] Feature request for timestamps in retrieval events output

### ISSUE THREAD

**Issue by ghost** [filecoin-project/lotus#5897]
**Basic Information**
This is actually a feature request, but its sole purpose is to help debug deal making issues, which is why I'm using this template.

**Describe the problem**
What I'd like to request is that we consider adding timestamp prefixes to each line of the `lotus client retrieve` event output.  Here's an example of what I mean:

```
$ lotus client retrieve --miner fXXXXX bafy...abc outfile.bin
> [2021-03-29T02:45:02.622Z] Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
> [2021-03-29T02:45:02.622Z] Recv: 0 B, Paid 0 FIL, ClientEventDealProposed (DealStatusWaitForAcceptance)
> [2021-03-29T02:45:02.622Z] Recv: 0 B, Paid 0 FIL, ClientEventDealAccepted (DealStatusAccepted)
> [2021-03-29T02:45:02.622Z] Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelCreateInitiated (DealStatusPaymentChannelCreating)
[2021-03-29T02:45:02.622Z] ERROR: retrieval timed out
```
The benefit of this is two-fold:
 - First, while I'm waiting in each stage of the retrieval, I could see the elapsed time in that stage.  This is something we want for retrieval deal success testing dashboards in the near-ish future.
 - Second, when a retrieval fails like in the above example, I as a tester of retrieval could contact the miner and ask for their logs at a specific point in time.  That's easier than asking the miner "hey, can you send me all your logs from the past week" and then grep'ing for the failure.

**Version**
I'm on `lotus version 1.5.3-rc2+mainnet+git.9afb5ff94`, but this feature does not currently exist in any version of Lotus that I'm aware of.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
