### ISSUE TITLE
Lotus 1.6.0

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#5903]
# Lotus 1.6.0 Release

We're happy to announce Lotus 1.6.0, which introduces network version 11 that implements [FIP-0014](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md). The network will upgrade to version 11 at height 

## 🗺 What's left for release

 - [x] Upgrade to actors 3.1.0

## 🚢 Estimated shipping date

Monday, April 5th, 2021

## 🔦 Highlights

[FIP-0014](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md)

## Changelog

< changelog generated by bin/mkreleaselog >

## ✅ Release Checklist

First steps:

  - [x] Fork a new branch (`release/vX.Y.Z`) from `releases` and make any further release related changes to this branch. If any "non-trivial" changes get added to the release, uncheck all the checkboxes and return to this stage.
  - [x] Prep the changelog
  - [x] Bump the version in `version.go` in the `master` branch to `vX.(Y+1).0-dev`.
  - [x] Follow the RC release process to cut the first RC.
    
Prepping an RC:

- [x] version string in `build/version.go` has been updated (in the `release/vX.Y.Z` branch).
- [x] tag commit with `vX.Y.Z-rcN`
- [x] cut a pre-release on [github](https://github.com/filecoin-project/lotus/releases)

Testing an RC:

- [x] **Stage 0 - Automated Testing**
  - Automated Testing
    - [x] CI: Ensure that all tests are passing.
    - [ ] Testground tests

- [x] **Stage 1 - Internal Testing**
  - Upgrade our testnet infra
    - [x] 1 bootstrap node
    - [x] 1 miner
    - [x] Scratch nodes
    - [ ] Wait 24 hours
    - [ ] Remaining testnet infra
  -  Upgrade our mainnet infra
    - [ ] Subset of development full archival nodes
    - [ ]Subset of bootstrappers (1 per region)
    - Report on new block validation time
    - TODO: What other stats would we care about?
    - If anything has worsened significantly, investigate + fix
  - Confirm the following work (some combination of Testground / Calibnet / Mainnet / MinerX)
    - [x] Seal a sector
    - [ ] make a deal
    - [x] Submit a PoSt
    - [ ] (ideally) let a sector go faulty, and see it be recovered
    
- [x] **Stage 2 - Community Dev Testing**
  - [ ] Inform early testers
  - [x] Ask close ecosystem partners to test their projects with the upgrade
    - [ ] Powergate
    - TODO: List of partners

- [x] **Stage 3 - Community Prod Testing**
  - [x] Documentation
    - [x] Ensure that [CHANGELOG.md](https://github.com/filecoin-project/lotus/blob/master/CHANGELOG.md) is up to date
    - [ ] TODO: Other docs checks?
  - [ ] Invite the wider community through (link to the release issue):
    - [ ] TODO: How should we announce this?
    
- [ ] **Stage 4 - Release**
  - [ ] Final preparation
    - [x] Verify that version string in [`version.go`](https://github.com/ipfs/go-ipfs/tree/master/version.go) has been updated.
    - [x] Ensure that [CHANGELOG.md](https://github.com/filecoin-project/lotus/blob/master/CHANGELOG.md) is up to date
    - [x] Ensure that [README.md](https://github.com/filecoin-project/lotus/blob/master/README.md) is up to date
    - [x] Merge `release-vX.Y.Z` into the `releases` branch.
    - [x] Tag this merge commit (on the `releases` branch) with `vX.Y.Z`.
    - [x] Cut the release on Github.
    - [x] Final announcements
        - [ ] Update network.filecoin.io
        - [ ] TODO: What / where else?

- [x] **Post-Release**
  - [x] Merge the `releases` branch back into `master`, ignoring the changes to `version.go` (keep the `-dev` version from master).
  - [x] Create an issue using this release issue template for the _next_ release.

## ❤️ Contributors

< list generated by bin/mkreleaselog >

Would you like to contribute to Lotus and don't know how? Well, there are a few places you can get started:

- TODO

## ⁉️ Do you have questions?

TODO

**Comment by jennijuju** [comment]
yahh.  we followed through the process!!
