### ISSUE TITLE
[BUG] After successful block generation, the next cycle  will be skipped

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/lotus#5920]
Version: master/f4a2c8fa49dfc456090f5a5ea1b4ae62d33b4f85

Describe the bug
Under normal circumstances, when the block is created in a cycle, the block is broadcast at the time of (timestamp), and the latest block is often not received directly from the next round, resulting in  lastbase==base staying in the previous cycle, so that it will be broadcast again. Jump one cycle (https://github.com/filecoin-project/lotus/blob/master/miner/miner.go#L272), miss a cycle and possibly produce blocks.

Expected behavior
Waiting for PropagationDelaySecs after each successful SyncSubmitBlock

```
if err := m.api.SyncSubmitBlock(ctx, b); err != nil {
	log.Errorf("failed to submit newly mined block: %+v", err)
}

nextRound := time.Unix(int64(b.Header.Timestamp)+int64(build.PropagationDelaySecs), 0)

select {
	case <-build.Clock.After(build.Clock.Until(nextRound)):
	case <-m.stop:
		stopping := m.stopping
		m.stop = nil
		m.stopping = nil
		close(stopping)
		return
}
```

**Comment by jennijuju** [comment]
@diwufeiwen Sounds like you know how to fix it! do you want to create a PR directly?

**Comment by diwufeiwen** [comment]
> @diwufeiwen Sounds like you know how to fix it! do you want to create a PR directly?

Okay, I try, I'm not sure if the original author has other thoughts about this

**Comment by jennijuju** [comment]
> > @diwufeiwen Sounds like you know how to fix it! do you want to create a PR directly?
> 
> Okay, I try, I'm not sure if the original author has other thoughts about this

@travisperson @magik6k thoughts maybe?

**Comment by diwufeiwen** [comment]
https://github.com/filecoin-project/lotus/pull/5925

**Comment by jennijuju** [comment]
> #5925

Thanks for the PR!
