### ISSUE TITLE
Demote log level "peer declared dead but still connected; respawning writer" to debug

### ISSUE THREAD

**Issue by freddieee** [filecoin-project/lotus#5935]
**Describe the bug**
I have an image of machine runing a lotus client. When I tried to set up another machine with this image, the daemon cannot start and keeps throwing erros:
peer declared dead but still connected; respawning writer

**Version (run `lotus version`):**
v1.5.3-rc2

**log**
`peer declared dead but still connected; respawning writer`
**To Reproduce**
1. Create an image of a machine running a lotus client
2. Create another machine with this image and run `lotus daemon`

**Additional context**
related issues
https://github.com/filecoin-project/lotus/issues/5385

**Comment by jennijuju** [comment]
This is not an error but a warning message and only suggests that a peer was disconnected but end up staying connected - this is not a bug but we think it makes sense to demote the log value to debug.
