### ISSUE TITLE
[BUG] 1.7.0 cannot cancel-retrieve

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/lotus#5938]
**Describe the bug**

In Lotus 1.5.x, receiving channels had monotonically increasing integer ids like 1, 2, 3, etc.  You could cancel a retrieve by using a command like:  `lotus client cancel-retrieval --deal-id=3`.

In 1.7.0, the receiving channel ids seem to be bigints and you cannot cancel them.  Here is an example.  First, here is my one receiving channel with id = 1617328731745316884:

```
$ lotus client list-transfers
Sending Channels



Receiving Channels

ID                   Status           Receiving From  Root Cid     Initiated?  Transferred  Voucher
1617328731745316884  ResponderPaused  ...XqC2kG9f     ...2n4oe546  Y           1.052MiB     ...lIncrease":1048576,"UnsealPrice":"0"}
```

Try to cancel it and get this error:
 
```
$ lotus client cancel-retrieval --deal-id=1617328731745316884
ERROR: failed to cancel retrieval deal: loadOrCreate state: saving initial state: failed to write cid field t.PayloadCID: undefined cid

```

Check again and the receiving channel did indeed fail to get canceled:

```
$ lotus client list-transfers
Sending Channels



Receiving Channels

ID                   Status           Receiving From  Root Cid     Initiated?  Transferred  Voucher
1617328731745316884  ResponderPaused  ...XqC2kG9f     ...2n4oe546  Y           1.052MiB     ...lIncrease":1048576,"UnsealPrice":"0"}
```

**Version (run `lotus version`):**

I'm using the current tip of `master`:

```
$ lotus version
Daemon:  1.5.3+mainnet+git.358773e2b+api1.1.0
Local: lotus version 1.5.3+mainnet+git.358773e2b
```

**To Reproduce**

Kick off a retrieval of any CID, e.g., `lotus client retrieve --miner f01240 bafykbzacea5dewvdatvbxc2tmi26bomowduqhoi7ery4yqi3n6li32n4oe546 baf-oe546.bin`

Then follow the steps under "Describe the Bug" to reproduce.

**Expected behavior**

`lotus client cancel-retrieval --deal-id=1617328731745316884` should have successfully canceled that retrieval.

**Logs**
Not available.

**Comment by jimpick** [comment]
I assume the transfer id is different than the deal id. The deal ids for the retrievals aren't in the CLI anywhere as far as I can tell.

**Comment by dirkmc** [comment]
I suspect that the error is coming from switching between branches, one of which has a migration. Details here:
https://github.com/filecoin-project/lotus/issues/5901

**Comment by mgoelzer** [comment]
@dirkmc That makes sense.  I'll wipe out my `.lotus` directory and try again to see if it's still happening.  (and stop switching branches ;))

**Comment by jennijuju** [comment]
> @dirkmc That makes sense. I'll wipe out my `.lotus` directory and try again to see if it's still happening. (and stop switching branches ;))

@mgoelzer was it resolved?

**Comment by mgoelzer** [comment]
@jennijuju I haven't had time to re-test yet and I probably won't until next week.  Why don't we close out this issue for now?  If I retest and discover the same problem, or if you notice a similar bug report from someone else, we can reopen.
