### ISSUE TITLE
Docker support lotus daemon/miner

### ISSUE THREAD

**Issue by deaswang** [filecoin-project/lotus#594]
Docker support will help user to run multiple Nodes in one PC easy.

**Comment by whyrusleeping** [comment]
@deaswang would you like to make a dockerfile for us?

**Comment by ldoublewood** [comment]
@whyrusleeping  I will provide Dockerfile soon

**Comment by whyrusleeping** [comment]
we now have dockerfiles in `tools/dockers/docker-examples`
