### ISSUE TITLE
Create a Lotus Release Philosophy document

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#5948]
Akin to https://github.com/ipfs/go-ipfs/blob/master/docs/releases.md

- [ ] Ensure Discussion https://github.com/filecoin-project/lotus/discussions/5889 is updated to point to the new document

**Comment by BigLep** [comment]
I added an item to ensure we update https://github.com/filecoin-project/lotus/discussions/5889 before resolving this.

**Comment by BigLep** [comment]
We want to get a Markdown file with the @Stebalien content in https://github.com/filecoin-project/lotus/discussions/5889#discussioncomment-602796

**Comment by arajasek** [comment]
Can this be closed?

**Comment by BlocksOnAChain** [comment]
This discussion + doc created(https://github.com/filecoin-project/lotus/discussions/7053) can be considered as "done" for this issue, so we can close
