### ISSUE TITLE
[Feature Request] Ability to extend life of a sector with deals from lotus client

### ISSUE THREAD

**Issue by gh3990** [filecoin-project/lotus#5963]
**Is your feature request related to a problem? Please describe.**
Unable to extend the life of a sector that has deals in it.

**Describe the solution you'd like**
Extending a sector with deals expiration time with the amount of weeks needed.
From a miners perspective : Somehow the Miner needs to accept that because it's needs to put up collateral for the sector again.
Resealing it as a new sector at the same miner would be fine by me too, the data gets copied in a new sector and sealed again with new collateral and the rest of the process. Probably the easiest way to do it, as everything is available at the miner.
On the client side it would be great to be able to specified it's an active deal and request a reseal with a new expiration date.

**Describe alternatives you've considered**
I considered copying the data from the old sector back to my client, and requesting a new deal..

**Additional context**

**Comment by ytbigvinny27** [comment]
?? Varussell23@outlook.com

**Comment by ytbigvinny27** [comment]
If possible I want to finish the sync with all the work we've done from my windows computer and the destination will be my crypto.com account. Or 3 accounts crypto, trust, and BRD accounts.

**Comment by ytbigvinny27** [comment]
If possible I want to finish the sync with all the work we've done from my windows computer and the destination will be my crypto.com account. Or 3 accounts crypto, trust, and BRD accounts. If this issue is relating to the memory errors in this account . I have two computers and two smartphones. Regardless I can make enough memory available when push comes to shove.

**Comment by jennijuju** [comment]
@gh3990 Could you please open a fip discussion for this actually? cuz that's a protocol change ->https://github.com/filecoin-project/FIPs/issues

**Comment by arajasek** [comment]
Kinda three thoughts here:

- You can always extend sectors that have deals in them (just the deals themselves can't be extended)
- It would be great if clients can request that deals be extended -- this needs a FIP, though
- I don't think it makes sense for miners to be able to request that deals be extended

**Comment by gh3990** [comment]
@jennijuju , a little late, but here goes : https://github.com/filecoin-project/FIPs/issues/95
@arajasek , thanks for your feedback
