### ISSUE TITLE
If possible I want to finish the sync with all the work we've done from my windows computer and the destination will be my crypto.com account. Or 3 accounts crypto, trust, and BRD accounts. If this issue is relating to the memory errors in this account . I have two computers and two smartphones. Regardless I can make enough memory available when push comes to shove.

### ISSUE THREAD

**Issue by ytbigvinny27** [filecoin-project/lotus#5969]
If possible I want to finish the sync with all the work we've done from my windows computer and the destination will be my crypto.com account. Or 3 accounts crypto, trust, and BRD accounts. If this issue is relating to the memory errors in this account . I have two computers and two smartphones. Regardless I can make enough memory available when push comes to shove. 

__Originally posted by @ytbigvinny27 in https://github.com/filecoin-project/lotus/issues/5963#issuecomment-813831002__

**Comment by jennijuju** [comment]
Please rephrase and elaborate more if you have a lotus related question/issue then reopen the tickets.
