### ISSUE TITLE
Sending from Lotus Lite results in 0 nonce

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#5995]
**Describe the bug**
When sending a message from Lotus Lite node the nonce is always set to 0.

**Version (run `lotus version`):**
Local:
```
Daemon:  1.7.0-dev+mainnet+git.8a19ddbb9+api1.1.0
Local: lotus version 1.7.0-dev+mainnet+git.8a19ddbb9
```
Remote:
```
Daemon:  1.7.0-dev+mainnet+git.8a19ddbb9+api1.1.0
Local: lotus version 1.7.0-dev+mainnet+git.8a19ddbb9
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Start lotus lite node.
2. Send two messages, second will fail with:
`ERROR: executing send: mpool push: failed to push message: minimum expected nonce is 6: message nonce too low`

**Expected behaviour**
Message sending works.

**Logs**
```
2021-04-08T19:25:08.071+0200	WARN	rpc	go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:279	error in RPC call to 'Filecoin.MpoolPushMessage': mpool push: failed to push message:
    github.com/filecoin-project/lotus/node/impl/full.(*MpoolAPI).MpoolPushMessage.func1
        /home/kubuxu/work/github.com/filecoin-project/lotus/node/impl/full/mpool.go:184
  - minimum expected nonce is 6: message nonce too low
```

**Comment by jennijuju** [comment]
related #5593

**Comment by jennijuju** [comment]
It works when you are using one node, but the nonce is not correctly tracked between different nodes.
