### ISSUE TITLE
[Mining Issue] Very low lucky vaulue

### ISSUE THREAD

**Issue by scvpark** [filecoin-project/lotus#6000]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

Please provide all the information requested here to help us troubleshoot "mining/WinningPoSt failed" issues.
If the information requested is missing, you may be asked you to provide it.

**Describe the problem**
I mined for more than 3 months, but I got only 7 blocks. It's a fairly low number compared to other minor numbers. I think this is not unlucky, but there are other problems. 
And I have an ID with similar power in other regions, and I get blocks every day from other IDs.

**Version**
from March to April : 1.5.0 

2021-04-09 14:00 KST updated miner version.
lotus version 1.6.0+mainnet+git.3fc23a785

**Setup**
No firewall.  
Only NAT 
miner id : f0110768
GPU : RTX 3090
CPU : AMD Ryzen Threadripper 3970X 32-Core Processor
variable
source "$HOME/.cargo/env"
export PATH=$PATH:$HOME/.cargo/bin:/usr/local/go/bin
export LOTUS_MINER_PATH=/usr/seal/lotusminer
export LOTUS_PATH="/usr/seal/.lotus"
export CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
export CGO_CFLAGS="-D__BLST_PORTABLE__"
export RUSTFLAGS="-C target-cpu=native -g"
export FFI_BUILD_FROM_SOURCE=1
export BELLMAN_CUSTOM_GPU="Geforce RTX 3090:10496"
export FIL_PROOFS_MAXIMIZE_CACHING=1
export FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1
export FIL_PROOFS_USE_GPU_TREE_BUILDER=1
export FIL_PROOFS_USE_MULTICORE_SDR=1
export LOTUS_BACKUP_BASE_PATH=/root/lotus_backups/
export FIL_PROOFS_PARAMETER_CACHE=/var/tmp/parameters
export FIL_PROOFS_PARENT_CACHE=/var/tmp/parents
export GOLOG_FILE="/root/miner.log"
export GOLOG_LOG_FMT="json"

when i start lotus daemon : 
nohup lotus daemon > /root/lotus.log 2>&1 &
when start lotus-miner  : 
nohup lotus-miner run > ~/lotus-miner.log 2>&1 &

**Lotus daemon and miner logs**
After getting the first block on January 21, 2021, we have continuously mined it, but so far we have 7 blocks.
I can see the mined block log on April 6th, but I didn't actually get it.

![image](https://user-images.githubusercontent.com/82202610/114143064-a7675d00-994e-11eb-819d-7f2d79af7fee.png)
![image](https://user-images.githubusercontent.com/82202610/114143128-b8b06980-994e-11eb-8e53-ccf60a1b73cd.png)

** Code modifications **
Nothing has been modified.

**Comment by jennijuju** [comment]
Converting to a discussion for community discussion - please open a new tickets when there is a more defined issue or request.
