### ISSUE TITLE
Handle expired sectors better locally - to have better ux

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6005]
When a sector is expired, one should see:
- in miner fsm the status is no longer proving
- files for that sector got cleared from storage 
- be able to compact the partitions 

There may be more things to add here.

**Comment by jennijuju** [comment]
This will be 👁️ after MRA stuff is landed

**Comment by rjan90** [comment]
I think this issue can be closed now, as we now have way better tooling for sectors that have expired with the `lotus-miner sectors expired` command. Further improvements can probably be handled in new proposal tickets? #rengjøring
