### ISSUE TITLE
[BUG] message:failed to load msgmeta (bafy2bzacectvige5z4vxx2y5wdbohw5mfzfgvaqa27uhvk5r2kkh4nocqxtz2): blockstore: block not found] 2021/04/11 fil_controller.go:379: jsonrpc call: map[code:1 message:failed to load msgmeta (bafy2bzacectvige5z4vxx2y5wdbohw5mfz

### ISSUE THREAD

**Issue by yuzhongrong** [filecoin-project/lotus#6008]
message:failed to load msgmeta (bafy2bzacectvige5z4vxx2y5wdbohw5mfzfgvaqa27uhvk5r2kkh4nocqxtz2): blockstore: block not found]
2021/04/11 fil_controller.go:379: jsonrpc call: map[code:1 message:failed to load msgmeta (bafy2bzacectvige5z4vxx2y5wdbohw5mfz

i will try this when asyn main chainnet ,and we try to after my fil-server restart

**Comment by yuzhongrong** [comment]
the coede. is.   follow

for  _, n := range ts.Cids{
		log.Println("开始遍历子块", height, n.String())
	}

	for _, n := range ts.Cids {
		log.Println("开始遍历子块", height, n.String())
		bm, err := c.ChainGetBlockMessages(context.Background(), n)
		if err != nil {
			log.Println(" 无效的块：",n.String(),err).  //this line. is error
			return nil, err
		}

**Comment by yuzhongrong** [comment]
A difference of 649 blocks can be synchronized. why?

**Comment by Reiers** [comment]
Hi @yuzhongrong 

Thanks for the report. The issue is outdated.

Read more about chain management here:
https://lotus.filecoin.io/docs/set-up/chain-management/

If this is a issue in current release, please open a new ticket.

Thanks again !
