### ISSUE TITLE
[Deal Making Issue] Batch import deal creates an extra sector that stuck in WaitDeals

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#6010]
Today I imported 3 offline deals and force publish by executing lotus-miner storage-deals pending-publish --publish-now

I would expect it creates 3 sectors but it actually created 4 sectors, the last sector stuck in WaitDeals forever, until I manually remove it.

`615  WaitDeals  NO       NO      n/a                             CC `

```
lotus-miner sectors status --log 615
SectorID:	615
Status:		WaitDeals
CIDcommD:	<nil>
CIDcommR:	<nil>
Ticket:		
TicketH:	0
Seed:		
SeedH:		0
Precommit:	<nil>
Commit:		<nil>
Proof:		
Deals:		[]
Retries:	0
--------
Event Log:
0.	2021-04-10 21:04:30 +0000 UTC:	[event;sealing.SectorStart]	{"User":{"ID":615,"SectorType":8}}
```

**Comment by f8-ptrk** [comment]
when we did your deals earlier we always ended up with ~46 sectors created per 25 deal batch. it would fill the extra, empty sectors with the deals of the next batch but then created a bunch of empty sectors again.

i am not sure what version we were on at that point

**Comment by kernelogic** [comment]
New observation, imported 3 deals, 3 sectors were created but only 2 went to PC1, the 3rd one stuck in WaitDeals with CC and this is from the logs

```
2021-04-12T18:23:59.835Z	ERROR	evtsm	go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:83	Executing event planner failed: running planner for state Removed failed:
    github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).plan
        /opt/lotus/extern/storage-sealing/fsm.go:250
  - didn't expect any events in state Removed, got [{User:{}}]:
    github.com/filecoin-project/lotus/extern/storage-sealing.final
        /opt/lotus/extern/storage-sealing/fsm.go:458
2021-04-12T18:23:59.838Z	WARN	advmgr	sector-storage/manager.go:323	stub NewSector
2021-04-12T18:23:59.845Z	WARN	advmgr	sector-storage/manager.go:323	stub NewSector
2021-04-12T18:23:59.850Z	WARN	advmgr	sector-storage/manager.go:323	stub NewSector
2021-04-12T18:25:41.626Z	WARN	storageadapter	storageadapter/provider.go:128	New Deal: deal 1718688
2021-04-12T18:25:44.421Z	WARN	storageadapter	storageadapter/provider.go:128	New Deal: deal 1718687
```

**Comment by ribasushi** [comment]
@kernelogic can you please confirm this got resolved from your perspective?

**Comment by kernelogic** [comment]
Maybe my version is too low but it's still happening.

lotus-miner version
Daemon:  1.9.0+mainnet+git.ada7f97ba+api1.0.1
Local: lotus-miner version 1.9.0+mainnet+git.ada7f97ba

![image](https://user-images.githubusercontent.com/3711825/121472035-7a96ec80-c975-11eb-9e1e-890aae0067f4.png)
