### ISSUE TITLE
[Mining Issue] Are lotus nodes required to be public accessible in order to get elected to mine new blocks?

### ISSUE THREAD

**Issue by hopkinskong** [filecoin-project/lotus#6014]
**Describe the problem**
I am talking about `lotus daemon`, not `lotus-miner`.
Running `lotus-miner` requires connecting to a `lotus daemon` with worker (and optionally owner) address imported.
Do running election per epoch requires the underlining node (`lotus daemon`) be publicly accessible?

My current setup is:
```
lotus net reachability
AutoNAT status:  Private
```

The `lotus-miner` is publicly accessible but it seems that I still cannot get elected to mine any blocks. 

**Version**

`lotus version 1.5.0+mainnet+git.191a05da4.dirty`

**Comment by hopkinskong** [comment]
No assistances, closing.

**Comment by Shekelme** [comment]
That's how tech support works here.
