### ISSUE TITLE
[BUG] A sector cannot be removed

### ISSUE THREAD

**Issue by askender** [filecoin-project/lotus#6018]
**Describe the bug**
A sector cannot be removed.

Everytime restart lotus-miner, the log is repeat below:
```
2021-04-11T23:42:33.026+0800	WARN	sectors	storage-sealing/fsm.go:509	sector 1684 got error event sealing.SectorTerminateFailed: checking precommit presence: sectorNumber is allocated, but PreCommit info wasn't found on chain
2021-04-11T23:42:33.036+0800	INFO	sectors	storage-sealing/states_failed.go:26	TerminateFailed(1684), waiting 59.963198128s before retrying
A clear and concise description of what the bug is. 
(If you are not sure what the bug is, try to figure it out via a [discussion](https://github.com/filecoin-project/lotus/discussions/new) first!
```
If I run `lotus-miner sectors update-state --really-do-it 1684 Removing`, the log is appear:
```
2021-04-11T23:45:33.013+0800	ERROR	evtsm	go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:83	Executing event planner failed: running planner for state Terminating failed:
    github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).plan
        /home/zzzz/lotus/extern/storage-sealing/fsm.go:250
  - planner for state Terminating received unexpected event sealing.SectorRemoved ({User:{}}):
    github.com/filecoin-project/lotus/extern/storage-sealing.planOne.func1
        /home/zzzz/lotus/extern/storage-sealing/fsm.go:524
```

**Version (run `lotus version`):**
Daemon:  1.6.0+mainnet+git.3fc23a78+api1.1.0
Local: lotus version 1.6.0+mainnet+git.3fc23a78

**To Reproduce**
1. Run `lotus-miner sectors terminate --really-do-it 1684`
2. See error:
```
11.     2021-03-25 01:06:29 +0800 CST:  [event;sealing.SectorTerminateFailed]   {"User":{}}
        checking precommit presence: sectorNumber is allocated, but PreCommit info wasn't found on chain
```
I know the problem is the sector is never on chain, so the `terminate` command should not be used.  But what I can do know?

**Comment by jennijuju** [comment]
Have you tried sector remove?
And can you attach the full sector status log?

**Comment by askender** [comment]
> Have you tried sector remove?
I have tried `lotus-miner sectors update-state --really-do-it 1684 Removing`

After using this command, the miner stop repeat warning log.  Once restart, the warning log occurs again. 

the full sector status log:
[lotus_sector_1684.log](https://github.com/filecoin-project/lotus/files/6304047/lotus_sector_1684.log)

> I know the problem is the sector is never on chain, so the terminate command should not be used. But what I can do know?
Maybe it is a eage case that `terminate ` should not be used.
