### ISSUE TITLE
Integrate v5 actor

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6022]

**Comment by magik6k** [comment]
Related -> https://github.com/filecoin-project/lotus/pull/5769

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/specs-actors/pull/1392

**Comment by BigLep** [comment]
@jennijuju : is this a duplicate of https://github.com/filecoin-project/lotus/issues/5985 ?  Can one of them be closed?  They both reference https://github.com/filecoin-project/lotus/pull/5769

**Comment by magik6k** [comment]
Done now
