### ISSUE TITLE
[Mining Issue]

### ISSUE THREAD

**Issue by luckydog8686** [filecoin-project/lotus#6026]
I build 2k environment according to the doc: https://docs.filecoin.io/build/local-devnet. And then I launch a new lotus 
./lotus daemon --genesis=devgen.car --bootstrap=false --api=12347
The lotus chain works fine. And Then I init a new miner, but a dead loop occurs. 
![image](https://user-images.githubusercontent.com/6648147/114509314-f15e8480-9c67-11eb-8696-3fc9a1f1c406.png)

lotus version 1.6.0+2k+git.3fc23a785
The following is the deadloop code 
![image](https://user-images.githubusercontent.com/6648147/114509516-2965c780-9c68-11eb-823b-512da49d3f29.png)

**Comment by rjan90** [comment]
Hey! Are you still experiencing this issue, or can this be closed now? #rengjøring
