### ISSUE TITLE
[BUG]  sectors extend --v1-sectors bugs

### ISSUE THREAD

**Issue by benjaminh83** [filecoin-project/lotus#6027]
## Edit (@jennijuju)

List of edge cases to handle in https://github.com/filecoin-project/lotus/blob/50b4ea30836618d199e24024f4f591de3dfbb516/cmd/lotus-storage-miner/sectors.go#L428:

- [ ] If the sector is expired by the the time the extension message lands on chain, the message will fail. Sectors that are legally allowed to be extended should be extended successfully, which is not the case right now as all sectors will fail extension.  example message bafy2bzaceawk4q2q52gr5ewouszkzl5plhp5lxkax6kk3axi4wkskqs24ricg
- [ ] For sectors that have deals and lifetime is over 540 days, we should not try to extend them.
- [ ] Is trying to extend the sector with an illegal extension duration 
       ```lotus-miner sectors extend --v1-sectors` exec with error below
ERROR: mpool push message: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: invalid expiration 1801153, total sector lifetime (1556194) cannot exceed 1555200 after activation 244959 (RetCode=16)```

**Describe the bug**
I was trying to run the command to extend my v1 sectors, as the network v11 was rolled out. I did the command: 

```
~$ lotus-miner sectors extend --v1-sectors
bafy2bzacear3hoscrxlkf3l6bfkahzijxwee2o7npgi3bdkuavghzpiv5h6gc
```
This did not get on chain when executed. 7h later, I restarted lotus-daemon and I also pushed some messages stuck in local mpool. It seems I now got the message on chain:
https://filfox.info/en/message/bafy2bzaceawk4q2q52gr5ewouszkzl5plhp5lxkax6kk3axi4wkskqs24ricg

**Two problems:** 
**1.** One sector expired in the meantime, before the message landed on chain, causing the whole batch message to be rejected. 
Status: ErrForbidden
Error Message: cannot extend expiration for expired sector 1131, expired at 665992, now 666145 (RetCode=18)
**2.** Some kind of overestimation happened on this batch deal, causing it to burn 2 FIL! 

**Version (run `lotus version`):**
```
Daemon:  1.6.0+mainnet+git.3fc23a785.dirty+api1.0.1
Local: lotus-miner version 1.6.0+mainnet+git.3fc23a785.dirty
```
Dirty because of GPU2...

**Comment by flyworker** [comment]
lotus-miner sectors extend --v1-sectors
ERROR: mpool push message: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: cannot reduce sector 1482's expiration to 1755634 from 1759443 (RetCode=16)

**Comment by arajasek** [comment]
@flyworker What is your miner ID?

**Comment by flyworker** [comment]
f02387

**Comment by TerenceClark** [comment]
https://github.com/filecoin-project/lotus/pull/6033, this helpful

**Comment by rjan90** [comment]
I think this issue about extending-bugs with V1-sectors has been fixed, and can be closed now? #rengjøring
