### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by junior88512** [filecoin-project/lotus#6037]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

**Describe the bug**
(If you are not sure what the bug is, try to figure it out via a [discussion](https://github.com/filecoin-project/lotus/discussions/new) first!

**Version (run `lotus version`):**

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Logs**
Provide daemon/miner/worker logs, and goroutines(if available) for troubleshooting.
 
**Screenshots**

**Additional context**

**Comment by f8-ptrk** [comment]
@jennijuju i think this can be closed
