### ISSUE TITLE
Increased time to run "lotus chain list --count 1 --height 0 --format="<tipset>"" command

### ISSUE THREAD

**Issue by symanovich-a** [filecoin-project/lotus#6039]
**Describe the bug**
Hi team, we use `lotus chain list --count 1 --height 0 --format="<tipset>"` in our healthcheck command in [docker ](https://github.com/glifio/filecoin-docker)image. Usually it takes not more 0.1-4 sec, but now 1-30min and this isn't very convenient for our service.  On calibration network all works good. This was started on all our nodes at the same time approximately at 6.50 P.M. 9 April 2021 UTC+3. 
All nodes have enough free cpu\memory\disk.
**Version (run `lotus version`):**
v1.6.0+

**To Reproduce**
1. start lotus in container
2. run `lotus chain list --count 1 --height 0 --format="<tipset>"`

**Expected behavior**
Calibrationnet:
```
lotus version
Daemon:  1.6.0-rc1+calibnet+git.f357530+api1.1.0
Local: lotus version 1.6.0-rc1+calibnet+git.f357530

time lotus chain list --count 1 --height 0 --format="<tipset>"
bafy2bzaceapb7hfdkewspic7udnogw4xnhjvhm74xy5snwa24forre5z4s2lm

real	0m0.103s
user	0m0.103s
sys	0m0.022s

```
 Mainnet 1.7.0-rc1, restored from snapshot, dev env(**4vcpu, 30GB ram, nvme**):
```
lotus version
Daemon:  1.7.0-rc1+mainnet+git.7d8ee0d+api1.1.0
Local: lotus version 1.7.0-rc1+mainnet+git.7d8ee0d

time lotus chain list --count 1 --height 0 --format="<tipset>"
bafy2bzacecnamqgqmifpluoeldx7zzglxcljo6oja4vrmtj7432rphldpdmm2

real	5m57.244s
user	0m0.603s
sys	0m0.045s
```
Mainnet 1.6.0, restored from snapshot, prod (**8vcpu, 60GB ram, 1.9-3.7TB nvme**):
```
lotus version
Daemon:  1.6.0+mainnet+git.3fc23a7+api1.1.0
Local: lotus version 1.6.0+mainnet+git.3fc23a7

time lotus chain list --count 1 --height 0 --format="<tipset>"
bafy2bzacecnamqgqmifpluoeldx7zzglxcljo6oja4vrmtj7432rphldpdmm2

real	2m22.336s
user	0m0.361s
sys	0m0.082s
```
Mainnet 1.6.0, full node(**32vcpu, 256GB ram, 6TB+ ebs**):
```
lotus version
Daemon:  1.6.0+mainnet+git.3fc23a7+api1.1.0
Local: lotus version 1.6.0+mainnet+git.3fc23a7

time lotus chain list --count 1 --height 0 --format="<tipset>"
bafy2bzacecnamqgqmifpluoeldx7zzglxcljo6oja4vrmtj7432rphldpdmm2

real	31m9.966s
user	0m1.371s
sys	0m0.079s
```
or restart not full synced node after `time lotus chain list --count 1 --height 0 --format="<tipset>"` command

i tried to run command
lotus chain list --count 1 --height 0 --format="<tipset>" just on instance in aws(lotus 1.6.0, ubuntu20, i3.2xlarge, 8vcpu,60GB, 1.7TB nvme) and have good, but still not the best results
Load average: 3.97, 3.56, 3.05
memory. instance is working without swap
              total        used        free      shared  buff/cache   available
Mem:           59Gi       6.1Gi       607Mi       0.0Ki        53Gi        55Gi
Swap:            0B          0B          0B
```
lotus version
Daemon:  1.6.0+mainnet+git.3fc23a785+api1.1.0
Local: lotus version 1.6.0+mainnet+git.3fc23a785

time lotus chain list --count 1 --height 0 --format="<tipset>"
bafy2bzacecnamqgqmifpluoeldx7zzglxcljo6oja4vrmtj7432rphldpdmm2
real	0m18.362s
user	0m0.401s
sys	0m0.042s
time lotus chain list --count 1 --height 0 --format="<tipset>"
bafy2bzacecnamqgqmifpluoeldx7zzglxcljo6oja4vrmtj7432rphldpdmm2
real	0m10.793s
user	0m0.317s
sys	0m0.042s
time lotus chain list --count 1 --height 0 --format="<tipset>"
bafy2bzacecnamqgqmifpluoeldx7zzglxcljo6oja4vrmtj7432rphldpdmm2
real	2m14.394s
user	0m0.429s
sys	0m0.033s
time lotus chain list --count 1 --height 0 --format="<tipset>"
bafy2bzacecnamqgqmifpluoeldx7zzglxcljo6oja4vrmtj7432rphldpdmm2
real	2m14.725s
user	0m0.401s
sys	0m0.052s
```

**Comment by ribasushi** [comment]
I apologize, at the time this was filed I did not fully understand what is being asked.
The command in question ( walk back through the entire chain and arrive at 0, examining thousands of tipsets in the process ) is expected to be slow. And is indeed expected to be **slower** when a full chain is available ( due to datastore inefficiencies ).

However: you do not need to do any of this. The actual background use-case here (relayed via slack) is "give me the timestamp of genesis". That can be trivially done via:

```
curl -s http://127.0.0.1:1234/rpc/v0 -X POST -H "Content-Type: application/json" --data '
  { "jsonrpc": "2.0", "id":1, "method": "Filecoin.ChainGetGenesis", "params": [] }
' | jq '.result.Blocks[0].Timestamp'
```

**Comment by eshon** [comment]
Filed CLI bug here: https://github.com/filecoin-project/lotus/issues/6293
