### ISSUE TITLE
[Deal Making Issue] Prune chain caused deal errors: failed to look up deal on chain

### ISSUE THREAD

**Issue by William8Work** [filecoin-project/lotus#6044]
**Basic Information**

Due to the lotus daemon chain size increasing, I need to prune the chain to get it smaller. However, this caused some existing deals error with failed to look up deal on chain. Are those deals lost? 

Is this a bug, if not, how to recover these deals?

**Describe the problem**

1. I stopped the lotus-miner and lotus daemon
2. Remove the lotus/datastore/chain folder.
3. Run the following:
`lotus daemon --import-snapshot https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car`
4. Restart the lotus daemon
5. Restart the lotus-miner
6. Found the following for the deals:

`lotus-miner storage-deals list -v`
`Apr 10 03:00:25  false  bafyreib2wneyp7njf4afonglph6gwhhju4axnjmjuzd5fdwsar35xhomvm  1693952  StorageDealError                         f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a  64MiB   0.001875 FIL         1000000  12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWGabRFTsGhQLP5sb5f6eSUDbhyDqiF3fK9mZQWxJK5xJG-1617928783410165796  error awaiting deal pre-commit: failed to set up called handler: called check error (h: 659357): failed to look up deal on chain: looking for publish deal message bafy2bzacedvtr3z53pv6tollayje7x2h4tdayhnk7sseermc3hzqctqnbgnmu: search msg failed: checking for message execution during lookback: amt load: failed to root: blockstore: block not found`

**Version**

The output of `lotus --version`.
lotus version 1.6.0+mainnet+git.3fc23a785
lotus-miner version 1.6.0+mainnet+git.3fc23a785

**Comment by f8-ptrk** [comment]
@William8Work if they are on chain i doubt that deals can fail without the sectors getting terminated. i thin k it's a display problem

**Comment by arajasek** [comment]
I think the correct answer here is to get the splitstore production-ready, and thus enable online GCing.
