### ISSUE TITLE
"lotus-worker wait-quiet" is not working

### ISSUE THREAD

**Issue by Shekelme** [filecoin-project/lotus#6049]
**Describe the problem**
Looks like `lotus-worker wait-quiet` command is not working. The worker continues to be assigned tasks despite the fact that this command is issued.

**Version**
 1.6.0+mainnet+git.3fc23a785.dirty (the same is on 1.5.0 also)

**Setup**
PC1 worker (Threadripper PRO 3995WX, 1 TB RAM).
lotus-worker starting script:
```
#Worker1 (AP/PC1)
nohup lotus-worker --worker-repo /media/sn750/worker1 --worker-repo /media/gigabyte  run --listen=192.168.11.35:3456 --precommit1=true --precommit2=false --commit=false --addpiece=true --unseal=false > ~/worker1.log 2>&1 &
```
Envars:
```
export RUST_LOG=info
export MINER_API_INFO=eyffffffffffffffWffffffff.yyyyyy_Cc-ddddd-xxxxx:/ip4/192.168.11.9/tcp/2345/http
export LOTUS_WORKER_PATH=/media/gigabyte
export FIL_PROOFS_MAXIMIZE_CACHING=1
export FIL_PROOFS_SDR_PARENTS_CACHE_SIZE=1073741824
export FIL_PROOFS_USE_MULTICORE_SDR=1
export FIL_PROOFS_MAXIMIZE_CACHING=1
```

**Commands**

`lotus-worker wait-quiet`
The command line prompt does not appear, the `lotus-worker` process seems to be waiting for something, but continues to receive tasks.

**Lotus miner logs**
Can't see anything related to this command in lotus-worker's log.

** Code modifications **
MinMemory: 52 << 30, for PC1 tasks on 32GiB sectors (extern/sector-storage/resources.go)

**Comment by Shekelme** [comment]
Note that I can successfully interact with `lotus-worker`:

```
admfc@asus25:~$ lotus-worker info
Worker version:  1.0.0
CLI version: lotus-worker version 1.6.0+mainnet+git.3fc23a785.dirty

Session: 5055a1b2-0c67-4ded-a4bd-f564204162de
Enabled: true
Hostname: asus25
CPUs: 128; GPUs: [GeForce RTX 3090]
RAM: 1008 GiB; Swap: 0 B
Reserved memory: 31.94 GiB
Task types: FIN GET C1 PC1 AP

6248ab65-61a8-4930-a58a-fb0d8631cfa5:
        Weight: 10; Use: Seal
        Local: /media/gigabyte
6248aa65-61a8-4930-a58a-aa0d8631aaa5:
        Weight: 10; Use: Seal
        Local: /media/sn750/worker1
```

**Comment by Reiers** [comment]
**Hi @Shekelme** 

Thanks for the report. 

**Are still experiencing this issue on the latest release?**
