### ISSUE TITLE
lotus-worker DONT use GPU during  PC2 works

### ISSUE THREAD

**Issue by hsjw12** [filecoin-project/lotus#6077]
The CPU 3800xt, GPU 2060, RAM 128GB nvme 2TB spec, the worker does not use the GPU when working with pc2. In case you didn't know, I replaced it with another worker with the same specifications that was newly installed, and the results were the same. 
i dont understand. Please help me.
Honestly, I don't know what log to attach.

>GPU status
![20210421_143258](https://user-images.githubusercontent.com/70571701/115501617-7ff98400-a2ae-11eb-9b27-bf71b7ce9f26.png)

>log (This is the worker's log when working with pc2)
2021-04-21T05:16:23.056Z        DEBUG   advmgr  sector-storage/worker_local.go:129      acquired sector {{490173 351} 8} (e:6; a:0): {{0 0}  /filecoin/sealworker/sealed/s-t0490173-351 /filecoin/sealworker/cache/s-t0490173-351}
2021-04-21T05:16:23.115Z        DEBUG   advmgr  sector-storage/worker_local.go:129      acquired sector {{490173 351} 8} (e:6; a:0): {{0 0}  /filecoin/sealworker/sealed/s-t0490173-351 /filecoin/sealworker/cache/s-t0490173-351}

> version
lotus version 1.7.1-dev+mainnet+git.2e6369012

**Comment by verynohair** [comment]
I have got the same problem. It seems like a bug.

**Comment by hsjw12** [comment]
Please help us~~~~~~

**Comment by ProgramAPE** [comment]
@verynohair @hsjw12 you should change the extern/filecoin-ffi/rust/Cargo.toml . Add the features = ["gpu"] to the filecoin-proofs-api dependency. Then rebuild from source again

**Comment by ProgramAPE** [comment]
1.7.0 has many bugs...

**Comment by hsjw12** [comment]
Thank you  so much.  I will  try...
Have a nice day

**Comment by hsjw12** [comment]
Finally solved the problem on your advice. Thank you so much. Do you know how to modify the source code to reduce the working time of C2?

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/lotus/issues/6103#issuecomment-827038773
