### ISSUE TITLE
init-miner failed

### ISSUE THREAD

**Issue by cyberdoy** [filecoin-project/lotus#6087]
**Describe the problem**
unable to init miner.
![Screenshot from 2021-04-22 08-44-22](https://user-images.githubusercontent.com/78981610/115670171-69ecd180-a349-11eb-80ad-042a0cdad3e6.png)

there are funds on each address
![Screenshot from 2021-04-22 08-47-5](https://user-images.githubusercontent.com/78981610/115670245-7e30ce80-a349-11eb-8d7d-ebc76c49cc99.png)

**Version**
lotus version 1.7.1-dev+mainnet+git.5e71bcedc

**Comment by rjan90** [comment]
Hi! Do you still have issues creating a miner on the network, or can this issue be closed now? #rengjøring
