### ISSUE TITLE
[BUG] lotus daemon crashed when turn off splitstore

### ISSUE THREAD

**Issue by narkissos** [filecoin-project/lotus#6088]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

**Describe the bug**
lotus daemon crashed when turn off splitstore feature in config.toml

**Version (run `lotus version`):**
Daemon:  1.7.1-dev+mainnet+git.ad0fdd5ec+api1.2.0
Local: lotus version 1.7.1-dev+mainnet+git.ad0fdd5ec

**To Reproduce**
1. shutdown lotus daemon
2. set splitstore = false in config.toml
3. start lotus daemon

**Expected behavior**
lotus daemon should start up correctly.

**Logs**
2021-04-22T16:31:43.752+0800    INFO    modules modules/services.go:152 subscribing to pubsub topic /fil/blocks/testnetnet
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf32ff3]

goroutine 1 [running]:
github.com/filecoin-project/lotus/chain/types.(*TipSet).Blocks(...)
        /root/lotus/chain/types/tipset.go:159
github.com/filecoin-project/lotus/chain/types.(*TipSet).MinTimestamp(0x0, 0x0)
        /root/lotus/chain/types/tipset.go:198 +0x13
github.com/filecoin-project/lotus/node/modules.waitForSync(0xc1a62d8820, 0xa, 0xc1a84b8f40)
        /root/lotus/node/modules/services.go:107 +0x45
github.com/filecoin-project/lotus/node/modules.HandleIncomingMessages(0x7f4014155360, 0xc001bb3020, 0x324dc00, 0xc001512e98, 0xc1a8670000, 0xc1a62d8820, 0xc1a9542a80, 0x32af720, 0xc001569400, 0x2de7406, ...)
        /root/lotus/node/modules/services.go:188 +0x28c
reflect.Value.call(0x2af9000, 0x30758d8, 0x13, 0x2dc4d43, 0x4, 0xc01737c600, 0x8, 0x8, 0x32bb120, 0x29c6f40, ...)
        /opt/go/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x2af9000, 0x30758d8, 0x13, 0xc01737c600, 0x8, 0x8, 0x8, 0xc000144970, 0xc01737c600)
        /opt/go/src/reflect/value.go:337 +0xb9
go.uber.org/dig.defaultInvoker(0x2af9000, 0x30758d8, 0x13, 0xc01737c600, 0x8, 0x8, 0xc0000fca00, 0xc01737c600, 0x8)
        /root/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:284 +0x65
go.uber.org/dig.(*Container).Invoke(0xc0000fca00, 0x2af9000, 0x30758d8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:439 +0x399
go.uber.org/fx.(*App).executeInvokes(0xc000019760, 0x29ea300, 0xc001aa9380)
        /root/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:547 +0x35f
go.uber.org/fx.New(0xc00118f610, 0x3, 0x3, 0xc001570700)
        /root/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:345 +0x490
github.com/filecoin-project/lotus/node.New(0x328b840, 0xc001411c20, 0xc0000fc230, 0x9, 0x9, 0x0, 0x0, 0x0)
        /root/lotus/node/builder.go:707 +0x49c
main.glob..func3(0xc001414980, 0x0, 0x0)
        /root/lotus/cmd/lotus/daemon.go:313 +0x131f
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc0005eb500, 0xc001414400, 0x0, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:432 +0x9bf
github.com/urfave/cli/v2.(*Command).startApp(0x449d980, 0xc001414400, 0x2ddf9de, 0x7ffca33ccaa7)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x6bb
github.com/urfave/cli/v2.(*Command).Run(0x449d980, 0xc001414400, 0x0, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0x9cd
github.com/urfave/cli/v2.(*App).RunContext(0xc0005eb380, 0x328b7c0, 0xc00003e068, 0xc00000e060, 0x2, 0x2, 0x0, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x81f
github.com/urfave/cli/v2.(*App).Run(...)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc0005eb380)
        /root/lotus/cli/helper.go:35 +0x7c
main.main()
        /root/lotus/cmd/lotus/main.go:75 +0x645
 
**Screenshots**

**Additional context**

**Comment by jennijuju** [comment]
Please see https://github.com/filecoin-project/lotus/issues/6737 - base on the splitstore design, we likely wont fix this.
