### ISSUE TITLE
[BUG] GPU is not used in 1.7.0 rc

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/lotus#6103]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

**Describe the bug**
While doing the wdpost with release 1.7.0 rc The GPU is not used.
after revert to 1.6.0, we pass the wdpost successfully.

**Version (run `lotus version`):**
1.7.0 -rc
**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Logs**
Provide daemon/miner/worker logs, and goroutines(if available) for troubleshooting.
 
**Screenshots**

**Additional context**

**Comment by jennijuju** [comment]
yes - there is small thing need to be fixed with proof so that gpu is used by default https://github.com/filecoin-project/filecoin-ffi/pull/162, but for now, if you build and run your lotus with `FFI_USE_GPU2=1` or `FFI_USE_GPU=1`, it will be loaded.

**Comment by jennijuju** [comment]
> yes - there is small thing need to be fixed with proof so that gpu is used by default [filecoin-project/filecoin-ffi#162](https://github.com/filecoin-project/filecoin-ffi/pull/162), but for now, if you build and run your lotus with `FFI_USE_GPU2=1` or `FFI_USE_GPU=1`, it will be loaded. let me know if it works

Confirmed it’s the case.

**Comment by jennijuju** [comment]
Resolved in #v1.9.0-rc2
