### ISSUE TITLE
[Feature Request] API endpoint for deal import

### ISSUE THREAD

**Issue by willscott** [filecoin-project/lotus#6113]
**Is your feature request related to a problem? Please describe.**
I am currently trying to automate a lotus client that loads data and stores it to the filecoin chain. As a daemon, the operations path of least resistance was to run this client in a separate container from lotus, so that they can be separately restarted and can communicate over the API exposed by lotus. Currently, the path of least resistance appears to be that my client packs data into a car file, that deployment with the lotus container is performed such that there is a shared volume between the two containers such that the car file can be placed in a location where it is visible to the lotus process, and then [`clientimport`](https://docs.filecoin.io/reference/lotus-api/#clientimport) is called over the lotus API to ask the lotus daemon to import the archive to be able to store it to the chain. This out-of-band shared file system is a more complex deployment story in terms of shared-machine constraints, and introduces plenty of edge cases where things can go wrong.

**Describe the solution you'd like**
I would like a parallel option to `clientimport` on the lotus API where the archive to have a deal made over can be sent in band over the lotus API

**Describe alternatives you've considered**
It would also be reasonable to transfer individual CID blocks that are contained in the car to the lotus node's data store, and then ask for the deal with the root cid of the dag being directly specified.

**Comment by jennijuju** [comment]
@willscott do you still want this?

**Comment by willscott** [comment]
I think in-band in API is probably not the most useful. This is probably not the right way to do it.
