### ISSUE TITLE
lotus chain sethead --epoch ---> panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by Derek-zd** [filecoin-project/lotus#6125]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

**Describe the bug**
(If you are not sure what the bug is, try to figure it out via a [discussion](https://github.com/filecoin-project/lotus/discussions/new) first!

**Version (run `lotus version`):**
1.8.0
**To Reproduce**
1. Run ' lotus chain sethead --epoch 710309'

2. See error
**lotus daemon  Process crash**

**Expected behavior**

**Logs**
Provide daemon/miner/worker logs, and goroutines(if available) for troubleshooting.
 panic: runtime error: index out of range [-1]

goroutine 842 [running]:
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).HeadChange(0xc001b03600, 0xc07b912030, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/workspace/diancun/lotus/blockstore/splitstore/splitstore.go:410 +0x1ac
github.com/filecoin-project/lotus/chain/store.(*ChainStore).reorgWorker.func1(0xc0001702d0, 0xc00105b800, 0xc068c0c780, 0x33f02c0, 0xc067e2fe40)
        /root/workspace/diancun/lotus/chain/store/store.go:525 +0x695
created by github.com/filecoin-project/lotus/chain/store.(*ChainStore).reorgWorker
        /root/workspace/diancun/lotus/chain/store/store.go:490 +0x118

**Screenshots**

**Additional context**

**Comment by Derek-zd** [comment]
1.6.0 is also available.

**Comment by jennijuju** [comment]
@Derek-zd are you using splitstore?

**Comment by Derek-zd** [comment]
yes

**Comment by jennijuju** [comment]
@vyzo @raulk mind taking a look please?

**Comment by Derek-zd** [comment]
![image](https://user-images.githubusercontent.com/54537021/116494408-560a1800-a8d3-11eb-9ab6-ef55186cfcd4.png)
