### ISSUE TITLE
[BUG] lotus 1.8.0 can not run by nobody

### ISSUE THREAD

**Issue by lcgogo** [filecoin-project/lotus#6139]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

**Describe the bug**
I run lotus in docker by nobody user before, after update to 1.8.0, met followed error in log

root@ip-172-30-0-56:/data/fil# ls -ltr
total 52
drwx------ 2 nobody nogroup 16384 Apr 28 10:54 lost+found
drw------- 2 nobody nogroup  4096 Apr 28 11:13 keystore
drwxr-xr-x 2 nobody nogroup  4096 Apr 28 11:34 heapprof
drwxr-xr-x 3 nobody nogroup  4096 Apr 28 12:30 kvlog_err
-rw------- 1 nobody nogroup   137 Apr 29 07:24 token
-rw-r--r-- 1 nobody nogroup   200 Apr 29 07:24 config.toml
drwxr-xr-x 6 nobody nogroup  4096 Apr 29 07:24 datastore
drwxr-xr-x 3 nobody nogroup  4096 Apr 29 07:38 kvlog
drwxr-xr-x 2 nobody nogroup  4096 Apr 29 07:38 data-transfer
drwxr-xr-x 2 nobody nogroup  4096 Apr 29 08:33 journal

2021-04-28T11:34:59.930Z`        INFO    modules modules/core.go:130     initialized system-driven watchdog
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".PstoreAddSelfKeys (/fil-src/lotus/node/modules/lp2p/libp2p.go:97): failed to build peer.ID: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build crypto.PubKey: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build crypto.PrivKey: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): permissions of key: 'libp2p-host' are too relaxed, required: 0600, got: 0644

then I chmod -R 600 keystore but met another error

2021-04-29T08:32:22.830Z	INFO	modules	modules/core.go:130	initialized system-driven watchdog
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".PstoreAddSelfKeys (/fil-src/lotus/node/modules/lp2p/libp2p.go:97): failed to build peer.ID: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build crypto.PubKey: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build crypto.PrivKey: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): opening key 'libp2p-host': stat /data/fil/keystore/NRUWE4BSOAWWQ33TOQ: permission denied

**Version (run `lotus version`):**
1.8.0

**Comment by rjan90** [comment]
Hi, are you still seeing this issue on newer versions of Lotus, or can this ticket be closed now? #rengjøring
