### ISSUE TITLE
E2E Testing for FIP8 & FIP13

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#6157]
FIP8 and FIP13 will allow batched pre-commits and batched prove-commits. This process needs end-to-end testing at scale (100s of sectors, test match batch sizes).

1. We need unit/integration tests to verify pre/prove-commit batching.
    1. What happens when a single sector fails?
2. We need to test this in a dev-net.

**Comment by BigLep** [comment]
Discussion notes:
1. Scale
 - 100's of sectors all at once

2. Assertions
 - What happens if 1 of 100 sectors fail
 - Pipeline is able to notice that we don't have enough sectors in a batch and thus wait.

**Comment by BigLep** [comment]
@magik6k and @vyzo : I want to make sure we're clear about the testing work for FIP8 and 13.  I want to make sure we're being precise about what we expect tested, that we have owners, and that we're tracking it (whether as a checklist or separate issues).  I took a first stab below based on what I saw in this issue and in PR #6235.  Please correct and ideally set as the subject of this issue or another.

In addition to making sure we don't lose track of anything, it'll be important as we update our estimates of the remaining work on 2021-05-20. 

<table>
<tr>
	<th>Item
	<th>Precommit Status
	<th>Postcommit Status
	<th>Comment
<tr>
	<td>Unit tests for CommitBatcher
	<td>[ ]
	<td>[ ]
	<td>Owner: @mention | Issue/PR: #XXXX  
<tr>
	<td>Commit Batching integration test: one porep fails
	<td>[ ]
	<td>[ ]
	<td>Owner: @mention | Issue/PR: #XXXX  
<tr>
	<td>Commit Batching integration test: one commit expires
	<td>[ ]
	<td>[ ]
	<td>Owner: @mention | Issue/PR: #XXXX  
<tr>
	<td>Commit Batching integration test: Batch fails (e.g., out of gas)
	<td>[ ]
	<td>[ ]
	<td>Owner: @mention | Issue/PR: #XXXX  
<tr>
	<td>Scale testing
	<td>[ ]
	<td>[ ]
	<td>This is automated verification that we can handle 100's of sectors

Owner: @mention | Issue/PR: #XXXX  
</table>

**Comment by magik6k** [comment]
(updated the comment above to have a better list of what needs to be done)

**Comment by arajasek** [comment]
#6432 adds unit tests for both the precommit and commit batchers

**Comment by arajasek** [comment]
- Unit tests landed in #6432 
- Integ tests landing soon from Magik
- Tested in a devnet

**Comment by BigLep** [comment]
I'm reopening this because I'm not seeing the integ tests PR created or merged (from looking https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+sort%3Aupdated-desc+ ), but let me know if I have that wrong.  I don't want to blur what "done" means.

**Comment by arajasek** [comment]
Tested on mainnet ;)
