### ISSUE TITLE
[API Enhancement] 

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/lotus#6168]
Calling DealsList method is extremely long

**Describe the problem**
Compared to lotus-miner command line , getting the list of deals via API is extremely long. I'm looking to implement Deals dashboards in lotus-farcaster. It it make it completely impossible for now. 

curl -s -X PST -H Authorization: Bearer SECRET -H Content-Type: application/json --data { "jsonrpc": "2.0", "method": "Filecoin.DealsList", "params": [], "id": 3 } http://127.0.0.1:2345/rpc/v0
```
real	0m27.322s
user	0m0.073s
sys	0m0.004s
```

```
time lotus-miner  storage-deals list --verbose|wc -l
2303

real	0m0.333s
user	0m0.568s
sys	0m0.128s
```
**Version**

lotus version 1.8.0+mainnet+git.5c56017db

Thank you,

Julien

**Comment by jennijuju** [comment]
Duplicated
