### ISSUE TITLE
[BUG] unsupported actor: actor xxx is a version 3 actor; chain only supports actor version 4 

### ISSUE THREAD

**Issue by chenjihu** [filecoin-project/lotus#6177]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

**Describe the bug**
(If you are not sure what the bug is, try to figure it out via a [discussion](https://github.com/filecoin-project/lotus/discussions/new) first!

**Version (run `lotus version`):*1.11.0-dev+calibnet+git.2a90de30b.dirty*

**To Reproduce**
1. Calibnet Run 1.7 lotus, run "lotus daemon" after rebuild with 1.11.0（master branch）
2. See error

**Expected behavior**

**Logs**
Provide daemon/miner/worker logs, and goroutines(if available) for troubleshooting.
```
unsupported actor: actor bafkqaddgnfwc6mzpojsxoylsmq is a version 3 actor; chain only supports actor version 4 at height 208030 and nver 12 (RetCode=9):
    github.com/filecoin-project/lotus/chain/vm.(*ActorRegistry).Invoke
        /home/root2/lotus/chain/vm/invoker.go:80
```
 
**Screenshots**

**Additional context**

**Comment by f8-ptrk** [comment]
please upgrade to v1.8.0

is this resolved already?

**Comment by chenjihu** [comment]
> please upgrade to v1.8.0
> 
> is this resolved already?

Yes, it works.
