### ISSUE TITLE
Create a util for miners to see IF they should have won blocks (looking back)

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#6179]
This is the only conclusive way to know whether miners are just "unlucky" or _should_ have won blocks but didn't because something went wrong.

**Comment by jennijuju** [comment]
To check if the miner actually get a winning ticket.

**Comment by f8-ptrk** [comment]
this needs a full node i think. a pruned node running on a snapshot might not do it

**Comment by rjan90** [comment]
Closing this issue since there is a `lotus-shed` util for it now:
```
./lotus-shed election backtest -h
NAME:
   lotus-shed election backtest - Backtest elections with given miner

USAGE:
   lotus-shed election backtest [command options] [minerAddress]

OPTIONS:
   --count value   number of won elections to look for (default: 120)
   --height value  blockchain head height (default: 0)
```
