### ISSUE TITLE
[Feature Request] CLI for batch sector extension

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/lotus#6180]
**Is your feature request related to a problem? Please describe.**
Right now, you can only extend sectors with a single expiration date. For example
`lotus-miner sectors extend --new-expiration 1791032 0`
However, there are so many sectors and it takes time to figure out which epoch to extend to for each sector

**Describe the solution you'd like**
A single CLI command to extend all sectors to the farthest possible future. Alternatively, for more advanced user, accept a CSV for which epoch each sector should be extended to. i.e.
`lotus-miner sector extend --all-sectors`
`lotus-miner sector extend < ./custom.csv`

**Comment by Reiers** [comment]
Hi @xinaxu 

Thanks for the report! 

You can:
```
NAME:
   lotus-miner sectors renew - Renew expiring sectors while not exceeding each sector's max life

USAGE:
   lotus-miner sectors renew [command options] [arguments...]

OPTIONS:
   --from value            only consider sectors whose current expiration epoch is in the range of [from, to], <from> defaults to: now + 120 (1 hour) (default: 0)
   --to value              only consider sectors whose current expiration epoch is in the range of [from, to], <to> defaults to: now + 92160 (32 days) (default: 0)
   --sector-file value     provide a file containing one sector number in each line, ignoring above selecting criteria
   --exclude value         optionally provide a file containing excluding sectors
   --extension value       try to extend selected sectors by this number of epochs, defaults to 540 days (default: 1555200)
   --new-expiration value  try to extend selected sectors to this epoch, ignoring extension (default: 0)
   --tolerance value       don't try to extend sectors by fewer than this number of epochs, defaults to 7 days (default: 20160)
   --max-fee value         use up to this amount of FIL for one message. pass this flag to avoid message congestion. (default: "0")
   --really-do-it          pass this flag to really renew sectors, otherwise will only print out json representation of parameters (default: false)
   --help, -h              show help (default: false)
```

Just add the flag `lotus-miner sectors renew --really-do-it  --to=<value of your choice>` to the cmd, and it will renew all sectors. 
If you dont add the flag `--really-do-it`, it will just show you what it will do with sectors. 

_Discaimer: BE CAREFUL, this will impact ALL sectors! 
Extending sectors with verified deals may result in power decrease._

Hope this help, and always make sure that your are running our latest release.
*Link to latest tags [here.](https://github.com/filecoin-project/lotus/tags)*

Thanks again, closing Lotus issue ticket.
