### ISSUE TITLE
Integrate PreCommitSectorBatch (FIP0008)

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6184]
This is introduced by [FIP0008](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0008.md) and being implemented in actor v5 - add integration in lotus

This includes:
1. Copy batch committing logic (rename)
2. Repurpose the batch committing tests
3. Integ tests need to some additional/changed assertions

**Comment by BigLep** [comment]
Closed by https://github.com/filecoin-project/lotus/pull/6235
