### ISSUE TITLE
Determining gas costs of aggregate porep verification

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6186]
Steps:
- [x] code inline aggregate proof benchmarking in a live node (with variety of aggregate sizes) by executing aggregate verification mid-block execution
- [x] inputs for inline aggregate proof benchmarking (need to generate them somehow)
- [x] run the benchmarks (let's say 24h of a continuous benchmark) 
(think can get through the above by 2021-05-19)
- [x] aggregate timing numbers, establish observed size correlation 
- [x] fill out a new gas entry (1h)
- [ ] write docs on general gas balancing (which we are most likely not doing today) (1d)
(think can get through the above by 2021-05-21)

Done state: the gas value for VerifyAggregateSeals is correct as far as we know, the tooling used is not in master (it won't be beautiful and not that useful as we will have real chain data for that).
* Not in master because it's very usecase specific and then it becomes useless by full gas balancing.

**Comment by BigLep** [comment]
@Kubuxu : when you pick this up, lets please add a checklist with the steps involved and the expected done state.  I know you said some of the done state includes documentation.  I want to make sure we're clear about what we're targeting.

**Comment by BigLep** [comment]
@magik6k : I'm going to keep it open until the docs work complete or we create a separate item for the docs work.
