### ISSUE TITLE
[Deal Making Issue] Retrieval stall after a few GiB of transfer

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#6187]
For a few weeks now I cannot perform any retrieval to completion. Tried with different miners and the retrieval would start transfer and just stall after a few GiBs. The latest failure happens on client 1.9.0-rc2 and miner 1.8.0.

On the miner side it shows "peer appears to have hung up" but I didn't "hung up" on anyone but patiently waiting.

lotus-miner data-transfers list -v
```
Sending Channels
ID          Status  Sending To                      Root Cid                            Initiated? Transferred Voucher                                                                                                                                           
1619927604752696324 Ongoing 12D3KooWEdkgB5RQCAZToi4d3U9GSYwjLR38tqaNVtrwy5KGH81q bafykbzacedpbmmbmfuj6o2oqsittex6s74p46mawknfvxqwqhmu6ojxz4lp3c N      3.051GiB   {"PayloadCID":{"/":"bafykbzacedpbmmbmfuj6o2oqsittex6s74p46mawknfvxqwqhmu6ojxz4lp3c"},"ID":1619927604753127530,"Selector":{"Raw":"oWFSomFsoWRub25loGI6PqFhYaFhPqFhQKA="},"PieceCID":null,"PricePerByte":"0","PaymentInterval":1048576,"PaymentIntervalIncrease":1048576,"UnsealPrice":"0"}  
 Message: other peer appears to have hung up. restart Channel
```

**Comment by stuberman** [comment]
I think this may be dealt with in https://github.com/filecoin-project/lotus/issues/6185

**Comment by dirkmc** [comment]
"peer appears to have hung up" means that the connection to the peer has gone down.

The next release of markets should take care of this issue - when the connection goes down the client will automatically reconnect and restart the data transfer. You can track progress here: https://github.com/filecoin-project/lotus/pull/6149

> I didn't "hung up" on anyone but patiently waiting

Thanks for your patience :)

**Comment by kernelogic** [comment]
Can't wait to try it out. I hope the slingshot judges will use this new version of market to do the judging.
