### ISSUE TITLE
[Feature Request] Manually scheduling 

### ISSUE THREAD

**Issue by vsharecoder** [filecoin-project/lotus#6197]
I think that the current worker scheduling tasks based on the remaining resources of the machine has a big problem. In many cases, the Miner and the worker cannot synchronize the resources in a timely manner. Many times, the task is sent to the fully loaded worker, which eventually causes the OOM process to crash, a lot of time was wasted.

So I suggest adding a form of manually setting the maximum number of tasks for different types of worker scheduling. The miner administrator himself can limit the number of tasks according to the actual situation of the machine. This can avoid worker crashes due to scheduling problems to the greatest extent. The implementation of scheduling is also simpler.

**Comment by rjan90** [comment]
Hey @vsharecoder!

Thanks for the feature request. Setting the maximum number of tasks running it parallel on workers is now possible https://github.com/filecoin-project/lotus/pull/8725.

Again, thanks for the feature request 👍

Closing this issue as completed.
