### ISSUE TITLE
How to get transaction fees before transfer?

### ISSUE THREAD

**Issue by NorthOrange** [filecoin-project/lotus#6209]
For example, one of my wallets has a balance of 3 fils. When I want to transfer all 3 fils through `lotus send`, how can I get the exact amount of `send`

**Comment by f8-ptrk** [comment]
you cant. the exact burn fees are determined when the messages are included in a block - depending on the baseFee at inclusion height

**Comment by donnol** [comment]
Is there a way to know how much fil I can send?

**Comment by f8-ptrk** [comment]
all - transaction fees. since you do not know the exact transaction fees in advance: no
