### ISSUE TITLE
Cannot faucet FIL coin from https://faucet.nerpa.interplanetary.dev/

### ISSUE THREAD

**Issue by cosfun** [filecoin-project/lotus#6217]
**Describe the bug**
Cannot faucet FIL coin from https://faucet.nerpa.interplanetary.dev/

**Version (run `lotus version`):**

**To Reproduce**
1. Go 'https://faucet.nerpa.interplanetary.dev/'
2. Input 't3udwu47mq3jsdz43eal6knz62ayzurokrwsnrv6gkql2x6r7ncljhpz4yexdo55pczqvsdmovu4ldn6yg3req' and click the button [Send Funds]
3. lotus wallet list
Address                                                                                 Balance  Nonce  Default  
t3udwu47mq3jsdz43eal6knz62ayzurokrwsnrv6gkql2x6r7ncljhpz4yexdo55pczqvsdmovu4ldn6yg3req  0 FIL    0      X   

**Expected behavior**
get test FIL coin

**Logs**
 
**Screenshots**

**Additional context**

**Comment by f8-ptrk** [comment]
@cosfun is this resolved?

**Comment by aaron3481** [comment]
> @cosfun is this resolved?

not yet

**Comment by ribasushi** [comment]
@aaron3481 I just tried this with the address in the bug - it just worked:
```
ubuntu@ip-172-31-18-243:~$ lotus state search-msg bafy2bzaceb3xp2utrym2mm2jkb25hc7xicnvjtthkj32myfgnzsmjrh6g43vq
Executed in tipset: [bafy2bzaced7onskc3jxsl4m3bw6yteyqxdsguaajxkeqfu5wivl6rgzqdk7rs bafy2bzaced5sq7trsq53nyx2chzqhrcut66uvsvm2v6l72rixgcdnpy5q3e3u]
Exit Code: 0
Gas Used: 2181918
Return: 

ubuntu@ip-172-31-18-243:~$ lotus wallet balance t3udwu47mq3jsdz43eal6knz62ayzurokrwsnrv6gkql2x6r7ncljhpz4yexdo55pczqvsdmovu4ldn6yg3req
1000 FIL
```

**Comment by ribasushi** [comment]
I will close for the time being, reopen with more information if the problem remanifests.
