### ISSUE TITLE
[Deal Making Issue] Cannot prune chain while deal is ongoing

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/lotus#6219]
**Basic Information**
Pruning the chain while deal is still ongoing makes the deal fail, become unrecoverable. This happens on both client side and miner side

**Describe the problem**

If a deal has not yet been successfully completed, the client nor the miner can prune the chain on their nodes. Doing so results in the deal failing. 

**Version**

lotus v1.6.0, and likely more recent versions as well.

**Comment by dkkapur** [comment]
@kernelogic - created per your flag in Slack. Would be great if you can share any updates / if you have been able to repro it on more recent versions

**Comment by dkkapur** [comment]
Likely related to https://github.com/filecoin-project/lotus/issues/6044 cc https://github.com/William8Work

**Comment by arajasek** [comment]
I think the correct answer here is to get the splitstore production-ready, and thus enable online GCing.
