### ISSUE TITLE
[Feature request] Client side validation on attempted deal

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/lotus#6221]
**Is your feature request related to a problem? Please describe.**
Clients today wait to see miners reject their deals due to factors like small piece sizes, miners not being open to accepting online deals, etc. This leads to lower deal success rate and results in a bad user experience for clients.

**Describe the solution you'd like**
Client side validation of the attempted deal to be made.

**Describe alternatives you've considered**
No specific alternatives other than to leave things as they are. 

**Additional context**
Note that there are a set of clients who will likely hit this issue and not benefit from such a fix since not all miners comply with requests that may meet their query-ask terms.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
