### ISSUE TITLE
[Feature Request] Path for miners to signal to clients/market when not currently considering online storage deals

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/lotus#6222]
**Is your feature request related to a problem? Please describe.**
Today, users can make deal proposals to miners who are not considering online storage deals and experience deal failures as a result. This results in a poor user experience for clients.

**Describe the solution you'd like**
Clients should not be able to make online data transfer deals to miners not accepting online data transfers. 

**Additional context**
Solution to address this could be related to https://github.com/filecoin-project/lotus/issues/6221

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
