### ISSUE TITLE
[Feature Request] Miners need a way to confirm they are correctly query-able

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/lotus#6223]
**Is your feature request related to a problem? Please describe.**
There needs to be an easy way for miners to know how to discover whether or not they are query-able and stay query-able with the right terms over time. As reputation systems become more of a core part of deal making and miner discovery, giving tools to miners to test and improve their status on these systems will be important.

**Describe the solution you'd like**
CLI command that outputs the perceived status of the miner on the network on behalf of the client, or something similar.

**Describe alternatives you've considered**
Better documentation, easy paths for miners to also participate in the network from the perspective of a client / use a different node.

**Additional context**
Flagged as part of testing done with some MinerX fellows.

**Comment by f8-ptrk** [comment]
can't a miner just query ask himself via lotus client?

**Comment by mgoelzer** [comment]
We built such an "Am I reachable?" tool for Space Race; @momack2 or @eshon may remember who did that and where it lives (she was the one who told me about it last summer).

**Comment by eshon** [comment]
@mgoelzer DMob built it using storage query-ask, and it's currently used in [Filrep.io](https://Filrep.io) under the Online Reachability metric. 

One question is whether there is or will be a separate type of query-ask for retrieval, if one current goal of reachability is to test retrievability.

Some miners interviewed said they do not respond to storage price query-asks because they only accept offline deals or do not accept random new deals at the moment.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
