### ISSUE TITLE
[Deal Making Issue] MaxSealingSectorsForDeals settings are ignored resulting in deals that crash the miner

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/lotus#6224]
**Describe the problem**

For storage deals being made from the miner side, even if the MaxSealingSectorsForDeals should be enforced as the miner is at a maximum, a deal is attempted resulting in a crash.

A deal should be automatically rejected if the miner is at capacity.

**Version**

Last reported around v1.5, v1.6.

**Comment by dkkapur** [comment]
@kernelogic - filed this per your note in Slack a few weeks ago. If you have any additional logs or details on a repro, please do share. Thanks!

**Comment by magik6k** [comment]
https://github.com/filecoin-project/lotus/pull/6041 is rewriting some related logic, worth checking if this was addressed there

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
