### ISSUE TITLE
[Deal Making Issue] Configuration issues for deal filters

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/lotus#6225]
**Basic Information**
Clients are unable to make deals that seem to comply with stated terms from a miner.

**Describe the problem**

As I understood the issue: if the deal acceptance filter is set to be higher than the offered price, and there is a deal filter script based on which the deal should have been accepted, lotus rejects a deal attempted at the offered price. This can get further complicated when filters are not configured correctly for verified vs. non-verified deals.

To make this work in once instance, @neondragon removed the code from lotus that rejects the deal based on the deal acceptance filter. @neondragon - I filed this issue based on your note in Slack from some testing last month; would be good to get some additional details from you on lotus version or additional context on the setup.

**Comment by dkkapur** [comment]
Note: this may also impact how filtering works based on min piece sizes. If anyone has any data points on this, would be great if you can share.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
