### ISSUE TITLE
Deal retrieval failed

### ISSUE THREAD

**Issue by boqian-nbai** [filecoin-project/lotus#6237]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

**Describe the bug**
Client failed to retrieve deal from miner

**Version (run `lotus version`):**
```
$ lotus version
Daemon:  1.9.0-rc3+mainnet+git.0398e556d+api1.2.0
Local: lotus version 1.9.0-rc3+mainnet+git.0398e556d
```

**To Reproduce**
```
lotus client retrieve --miner f0447183 bafykbzacedhlaek5flnggsdojwwv2v4nfk3jq2ek5vlxujpz2dupq6dd44ohw test0511
```

**Expected behavior**
Deal retrieval complete

**Logs**
Client stuck at here for a very long time:
```
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
> Recv: 0 B, Paid 0 FIL, ClientEventDealProposed (DealStatusWaitForAcceptance)
> Recv: 0 B, Paid 0 FIL, ClientEventDealAccepted (DealStatusAccepted)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelSkip (DealStatusOngoing)
```

Miner logs:
```
May 11 21:23:19 lotus-miner[8387]: 2021-05-11T21:23:19.464Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventDataTransferError", "deal ID": "1620766516060596709", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusErrored", "message": "deal data transfer failed: data transfer channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126252 failed to transfer data: graphsync response to peer 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g did not complete: response status code RequestFailedUnknown"}
```

List retrieval-deals on miner:
```
$ lotus-miner retrieval-deals list
tx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126251 failed to transfer data: graphsync response to peer 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g did not complete: response status code RequestFailedUnknown
```

**Comment by jennijuju** [comment]
It was mentioned that miner unsealing process was failed- could you please provide logs around that? Otherwise, no investigation can be done here.
Could you please provide the resource usage?

**Comment by boqian-nbai** [comment]
> It was mentioned that miner unsealing process was failed- could you please provide logs around that? Otherwise, no investigation can be done here.
> Could you please provide the resource usage?


Not sure if the unsealing process was failed or failed to start at all.
Full log on miner:
```
May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.123Z        INFO        dt-impl        impl/events.go:255        received new channel request from 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g
May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.137Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventOpen", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusNew", "message": ""}
May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.166Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventDealAccepted", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusUnsealing", "message": ""}
May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.185Z        DEBUG        advmgr        sector-storage/sched_worker.go:368        assign worker sector 109
May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.203Z        DEBUG        advmgr        sector-storage/worker_local.go:129        acquired sector {{447183 109} 9} (e:1; a:0): {{0 0} /home/nbfs/storage/storage/unsealed/s-t0447183-109  }
May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.204Z        DEBUG        advmgr        sector-storage/sched_worker.go:278        task done        {"workerid": "cdfaddcf-c064-411a-b59e-afdc4f0e175c"}
May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.222Z        DEBUG        advmgr        sector-storage/worker_local.go:129        acquired sector {{447183 109} 9} (e:1; a:0): {{0 0} /home/nbfs/storage/unsealed/s-t0447183-109  }
May 12 17:20:30 lotus-miner[8387]: 2021-05-12T17:20:30.025Z        INFO        badger        v2@v2.2007.2/db.go:1030        Storing value log head: {Fid:1622 Len:35 Offset:1014865963}
May 12 17:20:30 lotus-miner[8387]: 2021-05-12T17:20:30.138Z        INFO        badger        v2@v2.2007.2/levels.go:1000        [Compactor: 0] Running compaction: {level:0 score:1 dropPrefixes:[]} for level: 0
May 12 17:20:31 lotus-miner[8387]: 2021-05-12T17:20:31.479Z        INFO        badger        v2@v2.2007.2/levels.go:962        LOG Compact 0->1, del 7 tables, add 1 tables, took 1.340833199s
May 12 17:20:31 lotus-miner[8387]: 2021-05-12T17:20:31.479Z        INFO        badger        v2@v2.2007.2/levels.go:1010        [Compactor: 0] Compaction for level: 0 DONE
May 12 17:20:36 lotus-miner[8387]: 2021-05-12T17:20:36.423Z        INFO        miner        miner/miner.go:460        Time delta between now and our mining base: 6s (nulls: 0)
May 12 17:21:00 lotus-miner[8387]: 2021-05-12T17:21:00.279Z        INFO        badger        v2@v2.2007.2/db.go:1030        Storing value log head: {Fid:1624 Len:35 Offset:1048731381}
May 12 17:21:06 lotus-miner[8387]: 2021-05-12T17:21:06.689Z        INFO        miner        miner/miner.go:460        Time delta between now and our mining base: 6s (nulls: 0)
May 12 17:21:27 lotus-miner[8387]: 2021-05-12T17:21:27.545Z        INFO        badger        v2@v2.2007.2/db.go:1030        Storing value log head: {Fid:1626 Len:35 Offset:1048731381}
May 12 17:21:36 lotus-miner[8387]: 2021-05-12T17:21:36.235Z        INFO        miner        miner/miner.go:460        Time delta between now and our mining base: 6s (nulls: 0)
May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.553Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventUnsealComplete", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusUnsealed", "message": ""}
May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.577Z        INFO        dt-impl        impl/impl.go:386        resume channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253
May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.577Z        INFO        graphsync        responsemanager/responsemanager.go:481        response failed: %!w(traversal.SkipMe={})
May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.586Z        WARN        dt-impl        impl/events.go:235        data transfer channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253 failed to transfer data: graphsync response to peer 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g did not complete: response status code RequestFailedUnknown
May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.587Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventDataTransferError", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusErrored", "message": "deal data transfer failed: data transfer channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253 failed to transfer data: graphsync response to peer 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g did not complete: response status code RequestFailedUnknown"}
```

**Comment by jennijuju** [comment]
> > It was mentioned that miner unsealing process was failed- could you please provide logs around that? Otherwise, no investigation can be done here.
> > Could you please provide the resource usage?
> 
> Not sure if the unsealing process was failed or failed to start at all.
> Full log on miner:
> 
> ```
> May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.123Z        INFO        dt-impl        impl/events.go:255        received new channel request from 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g
> May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.137Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventOpen", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusNew", "message": ""}
> May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.166Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventDealAccepted", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusUnsealing", "message": ""}
> May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.185Z        DEBUG        advmgr        sector-storage/sched_worker.go:368        assign worker sector 109
> May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.203Z        DEBUG        advmgr        sector-storage/worker_local.go:129        acquired sector {{447183 109} 9} (e:1; a:0): {{0 0} /home/nbfs/storage/storage/unsealed/s-t0447183-109  }
> May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.204Z        DEBUG        advmgr        sector-storage/sched_worker.go:278        task done        {"workerid": "cdfaddcf-c064-411a-b59e-afdc4f0e175c"}
> May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.222Z        DEBUG        advmgr        sector-storage/worker_local.go:129        acquired sector {{447183 109} 9} (e:1; a:0): {{0 0} /home/nbfs/storage/unsealed/s-t0447183-109  }
> May 12 17:20:30 lotus-miner[8387]: 2021-05-12T17:20:30.025Z        INFO        badger        v2@v2.2007.2/db.go:1030        Storing value log head: {Fid:1622 Len:35 Offset:1014865963}
> May 12 17:20:30 lotus-miner[8387]: 2021-05-12T17:20:30.138Z        INFO        badger        v2@v2.2007.2/levels.go:1000        [Compactor: 0] Running compaction: {level:0 score:1 dropPrefixes:[]} for level: 0
> May 12 17:20:31 lotus-miner[8387]: 2021-05-12T17:20:31.479Z        INFO        badger        v2@v2.2007.2/levels.go:962        LOG Compact 0->1, del 7 tables, add 1 tables, took 1.340833199s
> May 12 17:20:31 lotus-miner[8387]: 2021-05-12T17:20:31.479Z        INFO        badger        v2@v2.2007.2/levels.go:1010        [Compactor: 0] Compaction for level: 0 DONE
> May 12 17:20:36 lotus-miner[8387]: 2021-05-12T17:20:36.423Z        INFO        miner        miner/miner.go:460        Time delta between now and our mining base: 6s (nulls: 0)
> May 12 17:21:00 lotus-miner[8387]: 2021-05-12T17:21:00.279Z        INFO        badger        v2@v2.2007.2/db.go:1030        Storing value log head: {Fid:1624 Len:35 Offset:1048731381}
> May 12 17:21:06 lotus-miner[8387]: 2021-05-12T17:21:06.689Z        INFO        miner        miner/miner.go:460        Time delta between now and our mining base: 6s (nulls: 0)
> May 12 17:21:27 lotus-miner[8387]: 2021-05-12T17:21:27.545Z        INFO        badger        v2@v2.2007.2/db.go:1030        Storing value log head: {Fid:1626 Len:35 Offset:1048731381}
> May 12 17:21:36 lotus-miner[8387]: 2021-05-12T17:21:36.235Z        INFO        miner        miner/miner.go:460        Time delta between now and our mining base: 6s (nulls: 0)
> May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.553Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventUnsealComplete", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusUnsealed", "message": ""}
> May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.577Z        INFO        dt-impl        impl/impl.go:386        resume channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253
> May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.577Z        INFO        graphsync        responsemanager/responsemanager.go:481        response failed: %!w(traversal.SkipMe={})
> May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.586Z        WARN        dt-impl        impl/events.go:235        data transfer channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253 failed to transfer data: graphsync response to peer 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g did not complete: response status code RequestFailedUnknown
> May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.587Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventDataTransferError", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusErrored", "message": "deal data transfer failed: data transfer channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253 failed to transfer data: graphsync response to peer 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g did not complete: response status code RequestFailedUnknown"}
> ```

<img width="405" alt="image" src="https://user-images.githubusercontent.com/42981373/118019360-e8280c80-b326-11eb-8f70-f05a6a513cf6.png">
any indicator for this would be great!

**Comment by boqian-nbai** [comment]
> > > It was mentioned that miner unsealing process was failed- could you please provide logs around that? Otherwise, no investigation can be done here.
> > > Could you please provide the resource usage?
> > 
> > 
> > Not sure if the unsealing process was failed or failed to start at all.
> > Full log on miner:
> > ```
> > May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.123Z        INFO        dt-impl        impl/events.go:255        received new channel request from 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g
> > May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.137Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventOpen", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusNew", "message": ""}
> > May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.166Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventDealAccepted", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusUnsealing", "message": ""}
> > May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.185Z        DEBUG        advmgr        sector-storage/sched_worker.go:368        assign worker sector 109
> > May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.203Z        DEBUG        advmgr        sector-storage/worker_local.go:129        acquired sector {{447183 109} 9} (e:1; a:0): {{0 0} /home/nbfs/storage/storage/unsealed/s-t0447183-109  }
> > May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.204Z        DEBUG        advmgr        sector-storage/sched_worker.go:278        task done        {"workerid": "cdfaddcf-c064-411a-b59e-afdc4f0e175c"}
> > May 12 17:20:23 lotus-miner[8387]: 2021-05-12T17:20:23.222Z        DEBUG        advmgr        sector-storage/worker_local.go:129        acquired sector {{447183 109} 9} (e:1; a:0): {{0 0} /home/nbfs/storage/unsealed/s-t0447183-109  }
> > May 12 17:20:30 lotus-miner[8387]: 2021-05-12T17:20:30.025Z        INFO        badger        v2@v2.2007.2/db.go:1030        Storing value log head: {Fid:1622 Len:35 Offset:1014865963}
> > May 12 17:20:30 lotus-miner[8387]: 2021-05-12T17:20:30.138Z        INFO        badger        v2@v2.2007.2/levels.go:1000        [Compactor: 0] Running compaction: {level:0 score:1 dropPrefixes:[]} for level: 0
> > May 12 17:20:31 lotus-miner[8387]: 2021-05-12T17:20:31.479Z        INFO        badger        v2@v2.2007.2/levels.go:962        LOG Compact 0->1, del 7 tables, add 1 tables, took 1.340833199s
> > May 12 17:20:31 lotus-miner[8387]: 2021-05-12T17:20:31.479Z        INFO        badger        v2@v2.2007.2/levels.go:1010        [Compactor: 0] Compaction for level: 0 DONE
> > May 12 17:20:36 lotus-miner[8387]: 2021-05-12T17:20:36.423Z        INFO        miner        miner/miner.go:460        Time delta between now and our mining base: 6s (nulls: 0)
> > May 12 17:21:00 lotus-miner[8387]: 2021-05-12T17:21:00.279Z        INFO        badger        v2@v2.2007.2/db.go:1030        Storing value log head: {Fid:1624 Len:35 Offset:1048731381}
> > May 12 17:21:06 lotus-miner[8387]: 2021-05-12T17:21:06.689Z        INFO        miner        miner/miner.go:460        Time delta between now and our mining base: 6s (nulls: 0)
> > May 12 17:21:27 lotus-miner[8387]: 2021-05-12T17:21:27.545Z        INFO        badger        v2@v2.2007.2/db.go:1030        Storing value log head: {Fid:1626 Len:35 Offset:1048731381}
> > May 12 17:21:36 lotus-miner[8387]: 2021-05-12T17:21:36.235Z        INFO        miner        miner/miner.go:460        Time delta between now and our mining base: 6s (nulls: 0)
> > May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.553Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventUnsealComplete", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusUnsealed", "message": ""}
> > May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.577Z        INFO        dt-impl        impl/impl.go:386        resume channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253
> > May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.577Z        INFO        graphsync        responsemanager/responsemanager.go:481        response failed: %!w(traversal.SkipMe={})
> > May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.586Z        WARN        dt-impl        impl/events.go:235        data transfer channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253 failed to transfer data: graphsync response to peer 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g did not complete: response status code RequestFailedUnknown
> > May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.587Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventDataTransferError", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusErrored", "message": "deal data transfer failed: data transfer channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253 failed to transfer data: graphsync response to peer 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g did not complete: response status code RequestFailedUnknown"}
> > ```
> 
> <img alt="image" width="405" src="https://user-images.githubusercontent.com/42981373/118019360-e8280c80-b326-11eb-8f70-f05a6a513cf6.png">
> any indicator for this would be great!

I thought this indicates that unsealing failed:
```
May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.553Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventUnsealComplete", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusUnsealed", "message": ""}
May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.577Z        INFO        dt-impl        impl/impl.go:386        resume channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253
May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.577Z        INFO        graphsync        responsemanager/responsemanager.go:481        response failed: %!w(traversal.SkipMe={})
May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.586Z        WARN        dt-impl        impl/events.go:235        data transfer channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253 failed to transfer data: graphsync response to peer 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g did not complete: response status code RequestFailedUnknown
May 12 17:21:40 lotus-miner[8387]: 2021-05-12T17:21:40.587Z        INFO        markets        loggers/loggers.go:30        retrieval provider event        {"name": "ProviderEventDataTransferError", "deal ID": "1620766516060596710", "receiver": "12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g", "state": "DealStatusErrored", "message": "deal data transfer failed: data transfer channel 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g-12D3KooWLHJ46AAKHWaWzs2SMizgqWcgGfiuZphMthUeitgHFNd3-1620766516060126253 failed to transfer data: graphsync response to peer 12D3KooWQC7pYowGqCodbtx5mQPVVwyQQxrXfXbCjsuLtfeZ2W1g did not complete: response status code RequestFailedUnknown"}
```
