### ISSUE TITLE
GasEstimateGasLimit return result of code id if fail to call msg

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/lotus#6252]
**Is your feature request related to a problem? Please describe.**
GasEstimateGasLimit return result of code id if fail to call msg
**Describe the solution you'd like**
GasEstimateGasLimit return a error with code 

**Describe alternatives you've considered**

**Additional context**

**Comment by rjan90** [comment]
Hey @hunjixin! This issue needs further explanations to what issue you actually are seeing, can you add that?
