### ISSUE TITLE
[BUG] Query ask causes segmentation violation

### ISSUE THREAD

**Issue by yry0008** [filecoin-project/lotus#6253]
When run `lotus client query-ask <miner-ID>` cause segmentation violation
![image](https://user-images.githubusercontent.com/76504564/118225615-07a26f00-b4b8-11eb-8a92-81d8b91621e7.png)

The lotus version is `v1.9.0-rc4`

system: CentOS 7

**Comment by arajasek** [comment]
Fixed by https://github.com/filecoin-project/lotus/pull/6590
