### ISSUE TITLE
[Feature Request] Configurable dealStartBufferHours

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6276]
The d[efault deal start epoch delay](https://github.com/filecoin-project/lotus/blob/d3ad897fe98464343ecbc00f3895e52eca56412f/node/impl/client/client.go#L70) should be configurable by the client.

https://github.com/filecoin-project/lotus/blob/d3ad897fe98464343ecbc00f3895e52eca56412f/node/impl/client/client.go#L70

**Comment by arajasek** [comment]
How desirable is this? Client config isn't really something Lotus has right now (and I don't think it should tbh). If the `dealStartBufferHours` isn't a good value for a client, I kinda think they should just supply the `DealStartEpoch` then.

Another option would be to add a new field to `StartDealParams` that can be supplied to say "i want the deal to start X epochs from now", but that is API-breaking.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
