### ISSUE TITLE
How to get enough funds after send and create miner?

### ISSUE THREAD

**Issue by walkerxin** [filecoin-project/lotus#629]
I try to go to the faucet page site: https://lotus-faucet.kittyhawk.wtf/, and sending successfully. But sometimes the wallet balance only would have a little increase.
How can I get more funds to higher than pledge-collateral?
And what's the mean of the return of sending funds?

**Comment by magik6k** [comment]
The create-miner endpoint - https://lotus-faucet.kittyhawk.wtf/miner.html - creates the actor for you, also paying the collateral.
