### ISSUE TITLE
Be able to update message CID in deal info state

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6303]
Currently, if a miner does a message replacement on their PublishStorageDeals message, they don't update that cid in their deal info state, so when the client requests deal status from them, the message CID in that status refers to the wrong message. We need a way to be able to update the message CID sent to the client.

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and is being completely removed from the code here:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
