### ISSUE TITLE
Can not run lotus daemon on the calibration

### ISSUE THREAD

**Issue by Pacificwestcoast** [filecoin-project/lotus#6307]
When I ran lotus daemon, got error blow, how should I do? thanks.

ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/devin/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:14): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:14): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:14): failed to build dtypes.AfterGenesisSet: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:14): genesis in the repo is not the one expected by this version of Lotus!

**Comment by Pacificwestcoast** [comment]
I found the answer, I forgot to delete the ./lotus, after I deleted it, it worked.

**Comment by yangjianyao** [comment]
I have the same problem, which lotus do I need to delete, what is its path？thanks

**Comment by yangjianyao** [comment]
export LOTUS_SKIP_GENESIS_CHECK=_yes_  ， it worked
