### ISSUE TITLE
lotus terrible programmer

### ISSUE THREAD

**Issue by MungerZ** [filecoin-project/lotus#6324]
![微信图片_20210525174955](https://user-images.githubusercontent.com/42316962/119477608-add85980-bd81-11eb-9481-72141e47f4fc.png)
and more!!!

no more to take!!!

terrible code style!!!

Why hire such a bad programmer(Magiera) ...

**Comment by MungerZ** [comment]
His code is so uncomfortable, it reminds me of an old saying: "A mouse shit makes a pot of soup broken."

**Comment by nonsense** [comment]
@MungerZ please be respectful of developers on the project! Derogatory language is not welcome here.

Furthermore this code is auto-generated.
