### ISSUE TITLE
Benchmark and implement FIP-0015

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#6335]
This tracks the benchmarking and gas evaluation needed for  FIP-0015 (reverting FIP-0009) per https://github.com/filecoin-project/FIPs/issues/86 for security and product consideration before it can be accepted for the network.

It also includes the corresponding test to assert appropriate base fee burn.

**Comment by arajasek** [comment]
The network uses about 5 trillion gas on SubmitWindowedPoSt per week (both successful and unsuccessful). Using a high estimate base fee of 2 nanoFIL, that is 10000 FIL per week for the entire network.

(For reference, the amount spent on PreCommit + ProveCommit is over 60 times more).

I think implementing FIP-0015 as part of HyperDrive is safe and good for the network.
