### ISSUE TITLE
[BUG] Readme doesnt contain basic build instructions

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#6348]
It seems pretty bad devex to not have at least the basic build instructions written in your readme. Which dependencies to install on a few common platforms, and the commands to run to build the thing are pretty simple to add and keep updated. Not sure why this got moved to the website exclusively and not even linked to in the readme (the link in the readme requires me to do some reading to figure out what the next link i need to click is before getting me to the right page)

**Comment by rjan90** [comment]
Added an initial draft for all the steps up until starting and syncing the daemon. Included only dependencies for Ubuntu & Fedora, linked to the rest
