### ISSUE TITLE
[BUG] Pre-built Lotus binaries cannot find libhwloc.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/lotus#6370]
The pre-built binaries do not run, and complain about a missing dependency `libhwloc`.

**Lotus Version:** v1.9.0

**Operating system:** Ubuntu 20.04

**To Reproduce**
1. Install deps [as listed from the docs](https://docs.filecoin.io/get-started/lotus/installation/#software-dependencies): `sudo apt install mesa-opencl-icd ocl-icd-opencl-dev gcc git bzr jq pkg-config curl clang build-essential hwloc libhwloc-dev wget -y && sudo apt upgrade -y`
1. Download pre-built binary: `wget https://github.com/filecoin-project/lotus/releases/download/v1.9.0/lotus_v1.9.0_linux-amd64.tar.gz`
1. Unpack tar: `tar xzvf lotus_v1.9.0_linux-amd64.tar.gz`
1. Move into `lotus` folder: `cd lotus`
1. Run Lotus: `./lotus`
1. View error message.

**Expected behavior**
Lotus runs without errors and doesn't require new dependencies OR list what those deps are OR package the deps in the pre-built binary (not sure if this last one is do-able).

**Logs**
This is the error message that gets spat out:

```shell
./lotus

> ./lotus: error while loading shared libraries: libhwloc.so.5: cannot open shared object file: No such file or directory
```

**Comment by johnnymatthews** [comment]
Kinda linked to #6208. Generating an AppImage with all the required deps would bypass this issue. Saying that, folks who still just want to download the pre-built binary from GitHub would still have an issue.

**Comment by travisperson** [comment]
The binaries published to the releases are built using Debian buster which installs `libhwloc.so.5`. Ubuntu 20.04 is installing `libhwloc.so.15` which results in the error, as the linked against library isn't installed.

This issue can be resolved by symlinking the installed package to the missing library. This should work for people who are just running a daemon. If the user is intending to run a miner or any software that requires the gpu, I'd advice that the user compiles directly against the hwloc library that their system has installed.

```
$ sudo ln -s /usr/lib/x86_64-linux-gnu/libhwloc.so.15 /usr/lib/x86_64-linux-gnu/libhwloc.so.5
```

**Comment by johnnymatthews** [comment]
Oh nice, that command works @travisperson, thanks! Since we don't yet recommend using the pre-built binaries in the docs, I guess this isn't really a problem. Hopefully the AppImage PR will get merged soon and we can start recommending that to users.

> If the user is intending to run a miner or any software that requires the gpu [...]

Yeah, I'll put a caveat in docs that says something like _miners should build their own binaries_.
