### ISSUE TITLE
Make "Circle CI tests green" for Hyperdrive

### ISSUE THREAD

**Issue by gagizoned** [filecoin-project/lotus#6380]
As we noticed while running the old test for 1.10 version, we experienced the CI test failing on multiple sides.
We want to track these issues as we moving close to our official RC, using this ticket on the Actors board

<img width="1137" alt="CIrlcle tests to green" src="https://user-images.githubusercontent.com/45310805/120520867-9b3ecf80-c3d4-11eb-8a62-43d4457b53fa.png">

**Comment by gagizoned** [comment]
Follow up on the test status: [https://app.circleci.com/pipelines/github/filecoin-project/lotus]
We are currently in the "green", but @magik6k will Continue investing some other flaky tests we found.

**Comment by BigLep** [comment]
2021-06-04: remaining flakiness:
1. sync tests
2. pledging batch of sectors, a couple sectors get duplicate "Sector Packed Events".  Has easy repo when run with single thread on debugger.
3. Other random hanging (maybe related to sync test fixes)

**Comment by BigLep** [comment]
A key fix is happening in https://github.com/libp2p/go-libp2p/pull/1116

**Comment by BigLep** [comment]
@magik6k : will confirm this is only an issue in master, and if so will create a new issue tagged to v0.11 and close this.

**Comment by magik6k** [comment]
Should be fixed now
