### ISSUE TITLE
[Mining Issue] Params cache download

### ISSUE THREAD

**Issue by kenshyx** [filecoin-project/lotus#6391]
**Describe the bug**
After upgrading my seal-worker to latest master I've noticed that there was a 
```
checksum mismatch in param file /mnt/tmp-fs/params-cache/v28-fil-inner-product-v1.srs, 786a02f742015903c6c6fd852552d272 != ae20310138f5ba81451d723f858e3797
```
The worker logged that it was trying to download it ` Fetching /mnt/tmp-fs/params-cache/v28-fil-inner-product-v1.srs from https://proofs.filecoin.io/ipfs/` but it was never created, I had to manually download it in the end. 

**Version (run `lotus version`):**
Tried with `lotus version 1.10.0-rc1+mainnet+git.1f10600f1` and from commit `bf468762b619c0cf018746a23d99f33a4f1026a9`

**To Reproduce**
1. Stop the lotus-worker
2. Rename one of the existing params v28 files
3. Start worker

**Expected behavior**
Worker starts and downloads missing param files without issues :)

**Logs**
```
main.glob..func5
Jun 04 12:45:41 lotus-worker[339441]:         /home/kenny/github/lotus/cmd/lotus-seal-worker/main.go:232
Jun 04 12:45:41 lotus-worker[339441]:   - the following errors occurred:
Jun 04 12:45:41 lotus-worker[339441]:      -  checking file /mnt/tmp-fs/params-cache/v28-fil-inner-product-v1.srs failed:
Jun 04 12:45:41 lotus-worker[339441]:             github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
Jun 04 12:45:41 lotus-worker[339441]:                 /home/kenny/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20210330140417-936748d3f5ec/paramfetch.go:112
Jun 04 12:45:41 lotus-worker[339441]:           - checksum mismatch in param file /mnt/tmp-fs/params-cache/v28-fil-inner-product-v1.srs, 6273332575563f5f31e9b2db5cf25ff0 != ae20310138f5ba81451d723f858e3797:
Jun 04 12:45:41 lotus-worker[339441]:             github.com/filecoin-project/go-paramfetch.(*fetch).checkFile
Jun 04 12:45:41 lotus-worker[339441]:                 /home/kenny/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20210330140417-936748d3f5ec/paramfetch.go:157
Jun 04 12:45:41 lotus-worker[339441]:      -  remove file /mnt/tmp-fs/params-cache/v28-fil-inner-product-v1.srs failed:
Jun 04 12:45:41 lotus-worker[339441]:             github.com/filecoin-project/go-paramfetch.(*fetch).maybeFetchAsync.func1
Jun 04 12:45:41 lotus-worker[339441]:                 /home/kenny/go/pkg/mod/github.com/filecoin-project/go-paramfetch@v0.0.2-0.20210330140417-936748d3f5ec/paramfetch.go:115

```
 
**Screenshots**

**Additional context**

**Comment by jennijuju** [comment]
Thanks for reporting!! The new proof param needs to be automatically downloaded

**Comment by BigLep** [comment]
Identify if there is a regression test we can add here.

**Comment by cryptonemo** [comment]
> The worker logged that it was trying to download it ` Fetching /mnt/tmp-fs/params-cache/v28-fil-inner-product-v1.srs from https://proofs.filecoin.io/ipfs/` but it was never created, I had to manually download it in the end.

Just noting that `https://proofs.filecoin.io/ipfs/` shown above is an incorrect path.

**Comment by arajasek** [comment]
@kenshyx Spent a good bit of time looking into this, but I don't see anything wrong, and I can't repro myself. Can you please:

- confirm that you are still facing this issue (maybe after making everything afresh)
- rename the relevant file, and try running `make lotus-shed && ./lotus-shed fetch-params --proving-params=2KiB` (or any other sector size). I'm curious to see if that works for some reason.

**Comment by kenshyx** [comment]
- this is still happening if I rename the `v28-fil-inner-product-v1.srs`, it looks more like a race condition, the worker doesn't wait for the param file to be downloaded before trying to start and
- I can reproduce this 100% on my `lotus-worker` that runs with `lotus-worker --enable-gpu-proving=true run --listen 0.0.0.0:1234 --precommit1=false --precommit2=true --commit=true --addpiece=true`

**Comment by kenshyx** [comment]
> * rename the relevant file, and try running `make lotus-shed && ./lotus-shed fetch-params --proving-params=2KiB` (or any other sector size). I'm curious to see if that works for some reason.

this finishes successfully `2021-06-09T17:42:45.829+0200	INFO	build	go-paramfetch@v0.0.2-0.20210330140417-936748d3f5ec/paramfetch.go:172	parameter and key-fetching complete`

**Comment by arajasek** [comment]
@kenshyx Interesting! Do you always get the same checksum mismatch?

`786a02f742015903c6c6fd852552d272 != ae20310138f5ba81451d723f858e3797`

or is it unpredictable

**Comment by kenshyx** [comment]
on the last test I got `a679afdce16446b132d4f5c454963c1f != ae20310138f5ba81451d723f858e3797`

**Comment by kenshyx** [comment]
wait a minute, this is inconsistent, so I get the error two times:

- once when the check is made ` WARN        build        go-paramfetch@v0.0.2-0.20210330140417-936748d3f5ec/paramfetch.go:97        checksum mismatch in param file /mnt/tmp-fs/params-cache/v28-fil-inner-product-v1.srs, 786a02f742015903c6c6fd852552d272 != ae20310138f5ba81451d723f858e3797`
- and when it errors it says `checksum mismatch in param file /mnt/tmp-fs/params-cache/v28-fil-inner-product-v1.srs, a679afdce16446b132d4f5c454963c1f != ae20310138f5ba81451d723f858e3797:
Jun 09 17:36:21 lotus-worker[384221]:             github.com/filecoin-project/go-paramfetch.(*fetch).checkFile`

**Comment by kenshyx** [comment]
the 2nd error might have a different hash each time because of the download completion

**Comment by arajasek** [comment]
Okay, sounds like this is a known issue caused by go-paramfetching getting quite confused when it's asked to `GetParams` in parallel. In this case, your miner / daemon is probably trying to fetch the params too.

Definitely a bug, but not the scariest thing in the world. Per @magik6k:

> The easiest fix would be to fetch to a file with random name, then only rename when it's done fetching
The correct fix would be to use fs locks, but those require effort and tend to get messed up

**Comment by arajasek** [comment]
Gonna keep the issue around, but descoping from HyperDrive
