### ISSUE TITLE
Update to latest FFI with Bellman fixes

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#6394]
Per @cryptonemo , there a new Proofs version will be needed before Hyperdrive.  It will be available sometime early the week of 2021-06-07.

**Comment by arajasek** [comment]
It's actually not gonna be a new proofs version, just an FFI update

**Comment by gagizoned** [comment]
Assigning @arajasek to follow up from Lotus side

**Comment by arajasek** [comment]
Done in #6438
