### ISSUE TITLE
[NV13/Simulation] Feature to export state

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#6408]
Simulation branch: https://github.com/filecoin-project/lotus/pull/6406

We need a way to easily export state to a CAR from a simulation. I've written a [command](https://github.com/filecoin-project/lotus/pull/6405) to export an arbitrary DAG, but it would be nice to have something a little more integrated to export a specific actor's state at a specific epoch on a specific simulation. E.g.:

```bash
lotus-sim [--simulation=...] state [--height=...] export [f0....]
```

Where the height, simulation, and actor are optional (if no actor is specified, we should export the state-tree.

**Comment by magik6k** [comment]
We could integrate this with the `chain get /ipld/path/with/the/selector/like/thing/@Ha:t0123/@state` command (and add an --export flag to it)

(for that to work we also would need to update the lotus [resolveOnce](https://github.com/filecoin-project/lotus/blob/master/node/impl/full/chain.go#L358) to work with different h/amt versions / widths (possibly just using ctx values to carry some metadata about network version))

**Comment by Stebalien** [comment]
Yeah. The main issue is that the lotus simulation runs offline and I'd rather not spin up a node just to export something. Ideally the simulation would run as a daemon and expose the API, but that's more complicated.

But we may be able to re-use some of the logic?

**Comment by magik6k** [comment]
It should be easy to just export the resolveOnce func, and use it in the export command in lotus-shed (https://github.com/filecoin-project/lotus/pull/6405)
