### ISSUE TITLE
[NV13/Simulation] Track ProveCommit Efficiency In Simulation

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#6410]
Simulation branch: https://github.com/filecoin-project/lotus/pull/6406

We should track the average, min, max, median, etc. batch size of prove commits, weighted by gas. This *should* be ~800 (max prove commit size) but could be lower.

Precisely:

1. Track the average gas for "full" prove commit messages (max batch size).
2. Track median, average, etc. of sectors/gas for each ProveCommit and AggregateProveCommit message.
3. Provide a way to extract our "gas efficiency" (e.g., how close we to "everything batched".

This *should* be somewhere near 100% because we try to pre-commit in batches of 819 which should all fit into a single prove-commit batch. But we need to verify this.

**Comment by jennijuju** [comment]
Ah nice = can this simulation produce some sort of gas <> #of  provecommit table?

**Comment by Stebalien** [comment]
Well, three things:

1. A gas/prove-commit theoretical (i.e., only taking the "full" messages into account).
2. A gas/prove-commit actual (taking all messages into account).
3. A comparison between the two.

These stats should, ideally, be saved in the datastore (or at least emitted to stderr and/or stdout as a log item).

**Comment by Stebalien** [comment]
Working through this a bit, I'd rather walk the chain and analyze this after the fact. There's now a `Simulation.Walk` function that can do just that, making all messages, their results, etc. available.

**Comment by Stebalien** [comment]
Done.
