### ISSUE TITLE
[BUG] batch commit, mpool message too large (33200B): message too big

### ISSUE THREAD

**Issue by lionsoul2014** [filecoin-project/lotus#6421]
**Version (run `lotus version`):** 1.10.0-rc1 2k test env

**Logs**
```
9.	2021-06-08 21:55:49 +0800 CST:	[event;sealing.SectorCommitted]	{"User":{"Proof":"oSB5YKvFkQm5J+ZiA5R36v+5aSghcm1M7n4G5xGVq40zRayyYFamkKjEFWlRLRYlg528FIf/pJWkpH5S63BGrBDUg5KMHyOcuVlAF9pbd9Z2cabeNER+3f0LYGN9yXPuBoZwfRkxOf92tT06uwhIxPyuaxhsLi27g6Fkm2hL2zG9y1oZ/p/S/YIj0hmlWWirpvugdZcbPEhlNjnxafMFBmwYifpHUQgenex1aDnU9dYwWT3gkvmnh1Ky2ZCEOAfc"}}
10.	2021-06-08 21:55:49 +0800 CST:	[event;sealing.SectorSubmitCommitAggregate]	{"User":{}}
11.	2021-06-08 22:28:22 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	aggregate error: sending message failed: mpool push: failed to push message: mpool message too large (33200B): message too big

```
 
there are 32 commits in the SectorSubmitCommitAggregate, when i flush it by running 'sectors batching commit --publish-now=true' and all commits failed with message too big error.

![2021-06-08_22-38](https://user-images.githubusercontent.com/7111577/121205775-85d11600-c8aa-11eb-9012-cb675fc6f633.png)

i've noticed the default max commit batch were set to 819 the config.toml, like: 
```
 48 #  AggregateCommits = true
 49 #  MinCommitBatch = 4
 50 #  MaxCommitBatch = 819
 51 #  CommitBatchWait = "24h0m0s"
 52 #  CommitBatchSlack = "1h0m0s"
```

should we consider about the message bytes for the batch commits ? and i did't see any logic for handling situations like in the commit_batch.go implementations.

**Comment by magik6k** [comment]
https://github.com/filecoin-project/lotus/pull/6419

**Comment by lionsoul2014** [comment]
simply increase the msg limit may not fundamentally solve this problem, we could check the batch msg bytes every time we invoke the CommitBatcher.AddCommit method and the aggregate message may not reach the config.MaxCommitBatch and forced to be published.
