### ISSUE TITLE
Investigate precommit message size and whether we'll exceed thresholds

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#6423]
Each precommit is ~300-400 bytes (depending on the number of included deals), which means that at the max precommit batch size (256), the batch precommit message will be ~80k, larger than the max message size allowed by the mpool.

~@magik6k

**Comment by magik6k** [comment]
This is probably actually fine, I initially looked at the whole message size, and not the params, which are much smaller - 65B - which means that max batch with no deals would be ~16KB, and have space for ~10000 deals, which should be more than enough
