### ISSUE TITLE
Export Metrics

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#6424]
We need to get timing metrics from `StateManager.ApplyBlocks`. They're recorded using our standard metrics system, but we need a way to extract and write them to disk.

**Comment by Stebalien** [comment]
Ok. I'd actually like this to get done eventually, but it's not a high priority.

Specifically, I'd like to periodically, randomly, record timing metrics to disk. Motivations include:

1. Ability to pipeline/optimize the simulation when _not_ timing.
2. Ability to "trim" the chain without losing information around timing changes.

**Comment by BigLep** [comment]
Removing from the Hyperdrive milestone since not essential for a quality 0.10 release.
