### ISSUE TITLE
Support early finalization before commit

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6431]
Currently lotus finalizing the sectors locally after sectors are onchain, however if a something goes wrong  in the FinalizeSector step, miners won’t be able to proving it and will have to terminate the sectors.

Allow early finalization can prevent it bit.

This is also important with ProveCommitAggregate, it may trigger a large amount of transfers from worker to the miner and can be too heavy for miners current setup to handle. Although `ParallelFetchLimit` can help a little with that.. it’s not ideal. It will be ideal if we can have #5339 , but for now, have an option for early finalization helps too.

**Comment by hxg8202** [comment]
It is important

**Comment by duzy555666** [comment]
if sector wait ProCommitAggregate  ,sector Will it go to the next step, or is it just waiting ?
