### ISSUE TITLE
[Feature Request] HTTP Health Check

### ISSUE THREAD

**Issue by ognots** [filecoin-project/lotus#6455]
**Is your feature request related to a problem? Please describe.**
When running lotus nodes in production, there's no HTTP health endpoint friendly to standard ops tooling.  JSONRPC is not conducive to health checks from tools like reverse proxy, kubernetes health checks, or other polling based monitoring.

**Describe the solution you'd like**
Create a separate HTTP listener with a `/healthz` endpoint. Additionally support query parameters to check specific sub-systems. 

**Describe alternatives you've considered**
Express health in standard HTTP response codes used for health checking.
Consider making Sync Status and API Availability as health parameters in initial health check.

**Comment by LaPetiteSouris** [comment]
@magik6k My first PR, trying to solve this issue. Hope that you may have sometimes to take a look

https://github.com/filecoin-project/lotus/pull/7602

**Comment by magik6k** [comment]
Done in https://github.com/filecoin-project/lotus/pull/8692
