### ISSUE TITLE
Add a LOTUS_DISABLE_V5_ACTOR_MIGRATION envvar

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6457]
as always = just in case, only needed before final release

**Comment by jennijuju** [comment]
@arajasek seems like the May you knew i would ask you to do this.. https://github.com/filecoin-project/lotus/blob/8286c6bd17de6d3499708cc2b68059de865505ff/build/params_mainnet.go#L74

**Comment by arajasek** [comment]
@jennijuju you're quite right! closing.
