### ISSUE TITLE
Minimum duration of `lotus-miner sectors pledge`, 180 or 540 days ?

### ISSUE THREAD

**Issue by nedosa** [filecoin-project/lotus#6459]
Hi,

I'm not sure yet if this is a bug or a plain question, but I've received conflicted answers on the minimum duration for CC sectors. Looking at https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/policy.go#L201 it looks like the minimum pledge duration is 180 days. My questions are 1/ does the `lotus-miner sectors pledge` operation support 180 or 540 days and 2/ is there a way to change the default without recompiling ?

Many thanks for any answers.

**Comment by f8-ptrk** [comment]
for pledged sectors the min lifetime is 540 days, or close to it - see https://github.com/filecoin-project/filecoin-docs/pull/879

the minimum duration param applies to deals and sector extensions

**Comment by jennijuju** [comment]
Please see https://docs.filecoin.io/mine/lotus/sector-pledging/#pledging-a-sector
