### ISSUE TITLE
[Mining Issue] Lotus sync wait current epoch only goes down

### ISSUE THREAD

**Issue by notusknot** [filecoin-project/lotus#6460]
**Describe the problem**

When I run `lotus sync wait` the current epoch starts at around 820,000 but goes down, while the `todo` keeps going up. After about an hour and a half of running `lotus sync wait`, the todo is at around 220,000. Is this intended? How long do I need to wait until the sync is complete?

**Version**

Lotus version: `lotus version 1.2.1+git.375b7a1c4`
Go version: `go1.15.5 linux/amd64`

**Setup**

I have double 2TB Nvme SSDs, an AMD Ryzen 9 3950x CPU, 128GB of ram, and a 256GB swapfile (although it doesn't seem to be in use). I am also running Ubuntu 20.04 LTS.

**Lotus daemon and miner logs**

I'm not sure which logs to check for this, so if logs would help for this specific issue, can I get instructions on how to access them and what I should share?

**Comment by jennijuju** [comment]
your lotus is way outdated and likely you are syncing on the wrong chain. We are currently at network 12 actor v4 lotus v1.8.0 and up.
