### ISSUE TITLE
[NV13/Simulation] Reclaim Space

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#6476]
The simulation is currently out of disk space and we need to figure out some way to reclaim space.

The simple approach would be to perform an import/export. However:

1. We'd need to export at least 2 virtual weeks worth of simulation for analysis.
2. Ideally, we'd keep a copy of the state-tree as of the start of the simulation.
3. We need to keep the messages *and* receipts for analysis.
4. We need to keep the simulation config (i.e., put it in the export). Ideally, we'd keep a copy of all simulations.

So we're probably going to need a custom export tool and this is going to be moderately frustrating.

**Comment by BigLep** [comment]
Removing from Hyperdrive since not required for a quality 0.10 Lotus release.  We unblocked ourselves by using a larger host.

**Comment by rjan90** [comment]
Hey!

Just checking if this issue can be closed now? As it seems this issue was related to a simulation for the NV13/HyperDrive upgrade!
