### ISSUE TITLE
[NV13/Simulation] Measure state-tree composition

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#6489]
We need to measure the composition of parts of the state-tree in nv13. Specifically, we need to know:

1. How much space (compared to the entire state-tree) is consumed by sector infos.
2. How much space is consumed by partitions, deadlines, etc.
3. Everything else.

**Comment by BigLep** [comment]
We can do this after the Hyperdrive release.

**Comment by Stebalien** [comment]
Given the current state growth, this is a super low priority so I'm going to punt.
