### ISSUE TITLE
Question: Is lotus-miner also a lotus-worker, in sense of sector acquiring?

### ISSUE THREAD

**Issue by kuchaguangjie** [filecoin-project/lotus#6496]
Say, when creating a new sector, **A** is the miner, **B** and **C** are its additional workers.

- **A** is configured to do no sealing work;
- **P1** and **P2** is done on worker **B**.
- **C1** and **C2** is done on worker **C**.

**The questions are:**
1. After P2, need move the sector from B to C, will A be used as _Transfer Stop_ or not ? Aka. is it `B -> C` or `B -> A -> C`.
2. Is `lotus-miner` also a normal `lotus-worker` in the sense of `worker selection`? Aka. Is `lotus-miner` a super set of `lotus-worker`?

**Comment by f8-ptrk** [comment]
1: B-->C
2. yes. `lotus-miner sealing workers` shows the miner process as a worker

**Comment by Reiers** [comment]
**Your questions have been answered by @f8-ptrk** 

Closing this ticket.  

For questions like this - Please visit our discussion forum or ask for help in Slack #fil-lotus-help.
