### ISSUE TITLE
[Sealing Issue]The SubmitCommitAggregate can't be send auto in calibnet network

### ISSUE THREAD

**Issue by swift-mx** [filecoin-project/lotus#6505]
**Describe the bug**
The SubmitCommitAggregate can't be send auto in calibnet network

**Version (run `lotus version`):**
1.11.0-dev calibnet

**To Reproduce**
1. Run lotus/miner/worker to seal

**Expected behavior**
 miner info
Chain: [sync ok] [basefee 100 aFIL]
Miner: t019128 (32 GiB sectors)
Power: 0  / 916 Ti (0.0000%)
        Raw: 0 B / 484.4 TiB (0.0000%)
        Committed: 0 B
        Proving: 0 B
Below minimum power threshold, no blocks will be won
Deals: 0, 0 B
        Active: 0, 0 B (Verified: 0, 0 B)

Miner Balance:    222.649 FIL
      PreCommit:  198.876 FIL
      Pledge:     0
      Vesting:    0
      Available:  23.772 FIL
Market Balance:   0
       Locked:    0
       Available: 0
Worker Balance:   4777.351 FIL
Total Spendable:  4801.124 FIL

Sectors:
        Total: 34
        Proving: 1
        PreCommit1: 25
        PreCommit2: 3
        SubmitCommitAggregate: 4
        ComputeProofFailed: 1
miner sectors batching commit list
6
14
20
23
miner sectors batching commit --publish-now
Batch 0:
        Message: bafy2bzacebrhdatwmjul6ughqaoxeecnldsotix62q7tjock5ixsgeetcirse
        Sectors:
                14      OK
                20      OK
                23      OK
                6       OK

**Logs**
   AggregateCommits: true,
   MinCommitBatch:   miner5.MinAggregatedSectors, // per FIP13, we must have at least four proofs to aggregate, where 4 is the cross over point where aggregation wins out on single provecommit gas costs
   MaxCommitBatch:   miner5.MaxAggregatedSectors, // maximum 819 sectors, this is the maximum aggregation per FIP13
   CommitBatchWait:  Duration(24 * time.Hour),    // this can be up to 30 days
   CommitBatchSlack: Duration(1 * time.Hour),     // time buffer for forceful batch submission before sectors/deals in batch would start expiring, higher value will lower the chances for message fail due to expiration

**Comment by jennijuju** [comment]
Was one of the MaxCommitBatch, CommitBatchWait or CommitBatchSlack hit?

**Comment by jennijuju** [comment]
See https://docs.filecoin.io/mine/lotus/miner-configuration/#provecommitaggregate
