### ISSUE TITLE
[Dynamic Retrieval Pricing]: Write  e2e retrieval deal tests that use an external pricing script

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/lotus#6508]
The Dynamic Retrieval Pricing functionality for the Retrieval Markets has been shipped as a part of https://github.com/filecoin-project/lotus/pull/6175.

However, that PR misses e2e tests that exercise the [external pricing script feature](https://github.com/filecoin-project/lotus/pull/6175#issuecomment-860374944). Please see https://github.com/filecoin-project/lotus/pull/6175#pullrequestreview-681686928 for notes on what tests need to be written.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
