### ISSUE TITLE
Re-examine HyperDrive params that depend on the size of aggregations

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#6517]
https://github.com/filecoin-project/lotus/issues/6515 revealed an issue (since fixed) in proof de/serialization that was leading to things being bigger than expected.

We need to reassess values

- We need to rerun gas calculations to see if there's a significant change in validation time resulting from the fix (a slowdown is expected, but unclear how large)
- If the change is small, we proceed with our current values
- If the change is large, we recompute gas values (takes ~2 days)
- If we recompute gas values, we also need to revisit bounds on aggregation batch sizes in actors

**If anyone knows of any other values similarly affected, please flag below**

**Comment by jennijuju** [comment]
small is defined within 20% by @Kubuxu

**Comment by jennijuju** [comment]
Also the balancer value?

**Comment by Kubuxu** [comment]
The result is 6% slower. Closing.
