### ISSUE TITLE
Mpool refactor

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#653]
Our mpool should do more things like other blockchain impls, e.g.: https://wiki.parity.io/Transactions-Queue

* Track message states explicitly (past / current / future)
* Implement logic for dropping stuff from mpoool
* Limit slots available
* Make sure 'local' mpool survives node restarts

**Comment by whyrusleeping** [comment]
@magik6k how much of this is done? I think we implemented the mpool dropping logic, and the local messages. Should we keep this issue open? or file new issues for the incomplete tasks?

**Comment by magik6k** [comment]
Yeah, I'm now happy with how it currently works
