### ISSUE TITLE
[Mining Issue] go-libp2p-nat : Soap request got Http 500 Internal Serve Error

### ISSUE THREAD

**Issue by KimJongYoon** [filecoin-project/lotus#6536]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

Please provide all the information requested here to help us troubleshoot "mining/WinningPoSt failed" issues.
If the information requested is missing, you may be asked you to provide it.

**Describe the problem**

After the successful Lotus-miner init operation, the following warning is issued when the Lotus-miner run operation is performed:

A libp2p related warning occurs after miner is run.

![image](https://user-images.githubusercontent.com/37894419/122687071-7c06c580-d24f-11eb-9d58-0d888fd1230d.png)

Mining doesn't seem to be working normally.

also, Nonce values increase slightly when checked with lotus wallet list -i
![image](https://user-images.githubusercontent.com/37894419/122687587-33044080-d252-11eb-80a5-20b5c9a3b3e3.png)

**Version**

The output of `lotus --version`.
lotus version 1.9.0+mainnet+git.ada7f97ba

**Setup**

You miner and daemon setup, including what hardware do you use, your environment variable settings, how do you run your miner and worker, do you use GPU and etc.

Swap : 255Gi
![image](https://user-images.githubusercontent.com/37894419/122687146-e7509780-d24f-11eb-972e-5d905e26695a.png)

Storage : /filecoine : 3.6T
![image](https://user-images.githubusercontent.com/37894419/122687130-d4d65e00-d24f-11eb-8767-8c14730d39a0.png)

CPU Info
![image](https://user-images.githubusercontent.com/37894419/122687211-35659b00-d250-11eb-894a-d4c2c0f2f731.png)

Env
![image](https://user-images.githubusercontent.com/37894419/122687279-8d9c9d00-d250-11eb-90d9-616a409c9816.png)

Config Path
![image](https://user-images.githubusercontent.com/37894419/122687310-b58c0080-d250-11eb-807e-06e996832066.png)

lotus config.toml(/filecoin/lotus/node/folder/config.toml)
```
# Default config:
[API]
# Binding address for the Lotus API
# ListenAddress = "/ip4/127.0.0.1/tcp/9200/http"
# Not used by lotus daemon
# RemoteListenAddress = "221.229.101.4:9200"
# General network timeout value
# Timeout = "30s"

#
[Backup]
#  DisableMetadataLog = false
#
[Libp2p]
#  ListenAddresses = ["/ip4/0.0.0.0/tcp/24001"]
#  AnnounceAddresses = ["/ip4/211.229.101.4/tcp/24001"]
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
[Client]
#  UseIpfs = false
#  IpfsOnlineMode = false
#  IpfsMAddr = ""
#  IpfsUseForRetrieval = false
#  SimultaneousTransfers = 20

[Metrics]
#  Nickname = ""
#  HeadNotifs = false

[Wallet]
#  RemoteBackend = ""
#  EnableLedger = false
#  DisableLocal = false
#
[Fees]
#  #DefaultMaxFee = "0.07 FIL"

[Chainstore]
#  EnableSplitstore = false
#  [Chainstore.Splitstore]
#    HotStoreType = "badger"
#    TrackingStoreType = ""
#    MarkSetType = ""
#    EnableFullCompaction = false
#    EnableGC = false
#    Archival = false
#

```

lotus-miner config.toml(/filecoin/miner/storage/config.toml)
```
# Default config:
[API]
  ListenAddress = "/ip4/127.0.0.1/tcp/2345/http"
  RemoteListenAddress = "127.0.0.1:2345"
  Timeout = "30s"
#
[Backup]
#  DisableMetadataLog = false
#
[Libp2p]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/24001"]
  AnnounceAddresses = ["/ip4/211.229.101.4/tcp/24001"]
#  NoAnnounceAddresses = []
  ConnMgrLow = 150
  ConnMgrHigh = 180
  ConnMgrGrace = "20s"
#
[Pubsub]
  Bootstrapper = false
  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
[Dealmaking]
  ConsiderOnlineStorageDeals = true
  ConsiderOfflineStorageDeals = true
  ConsiderOnlineRetrievalDeals = true
  ConsiderOfflineRetrievalDeals = true
  ConsiderVerifiedStorageDeals = true
  ConsiderUnverifiedStorageDeals = true
#  PieceCidBlocklist = []
  ExpectedSealDuration = "24h0m0s"
  PublishMsgPeriod = "1h0m0s"
  MaxDealsPerPublishMsg = 8
  MaxProviderCollateralMultiplier = 2
#  Filter = ""
#  RetrievalFilter = ""
#
[Sealing]
  MaxWaitDealsSectors = 2
  MaxSealingSectors = 0
  MaxSealingSectorsForDeals = 0
  WaitDealsDelay = "6h0m0s"
  AlwaysKeepUnsealedCopy = true
#
[Storage]
  ParallelFetchLimit = 10
  AllowAddPiece = true
  AllowPreCommit1 = true
  AllowPreCommit2 = true
  AllowCommit = true
  AllowUnseal = true
#
[Fees]
#  MaxPreCommitGasFee = "0.025 FIL"
#  MaxCommitGasFee = "0.05 FIL"
#  MaxTerminateGasFee = "0.5 FIL"
#  MaxWindowPoStGasFee = "5 FIL"
#  MaxPublishDealsFee = "0.05 FIL"
#  MaxMarketBalanceAddFee = "0.007 FIL"
#
[Addresses]
  PreCommitControl = ["f3sfwubigzqrrve6q4t3fpgwl26wmm5m7cftlw7crhyuc2umcqschv3kdu47jqbu44xj2l7y3c7twre3e55mga"]
  CommitControl = ["f3u2ww4xs74jahcdkddibkarfrqzg43tx5ixroiclybr2bd644vyj4mrdcoqqndjpwue6nmxdqtsfyzuyapika"]
  DisableOwnerFallback = false
  DisableWorkerFallback = false
#
```

If you have modified parts of lotus, please describe which areas were modified,
and the scope of those modifications

**Comment by cwhiggins** [comment]
I have seen this warning often, and it has always appeared after some sort of issue with my ISP's router/modem. Whether it be a reset or short power failure.  Results in needing to restart daemon and miner, then warning goes away. If you are seeing it all the time, then there is an issue somewhere between your miner and router/modem.

**Comment by KimJongYoon** [comment]
@cwhiggins 
Thank you very much for your answer. I'm setting up a file coin server after receiving a request from a customer. Let me check the customer's network environment.

**Comment by KimJongYoon** [comment]
@cwhiggins 
This issue has been resolved since the router was replaced. Thank you.
