### ISSUE TITLE
[BUG] Unable to exit sealing state "TerminateFailed"

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#6547]
**Describe the bug**
After trying to apply "lotus-miner sectors terminate" command, sector is stuck in Terminating loop.

**Version (run `lotus version`):**
Happens both in 1.10.0-rc6 and lotus-miner version 1.11.0-dev+mainnet+git.6e1cf6fdc 

**To Reproduce**
1. Run 'lotus-miner sectors terminate --really-do-it 1276' against broken sealing task
2. Sector remains in TerminateFailed state
3. Attempt lotus-miner sectors remove --really-do-it 1276 - (see errors below)

**Expected behavior**
I expect the sector to be removed from sectors list after lotus-miner restart

**Logs**
2021-06-22T13:56:26.028Z	INFO	stores	stores/remote.go:338	Delete http://192.168.1.96:3456/remote/sealed/s-t01278-1276
2021-06-22T13:56:26.065Z	ERROR	evtsm	go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:83	Executing event planner failed: running planner for state Terminating failed:
    github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).plan
        /home/stuart/lotus/extern/storage-sealing/fsm.go:296
  - planner for state Terminating received unexpected event sealing.SectorRemoved ({User:{}}):
    github.com/filecoin-project/lotus/extern/storage-sealing.planOne.func1
        /home/stuart/lotus/extern/storage-sealing/fsm.go:625

**Screenshots**
7.	2021-06-15 15:54:27 +0000 UTC:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: storage call error 0: task aborted
8.	2021-06-15 15:55:27 +0000 UTC:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
9.	2021-06-15 17:35:07 +0000 UTC:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: storage call error 101: worker restarted
37.	2021-06-16 16:56:49 +0000 UTC:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired: ticket expired: seal height: 848408, head: 851873
38.	2021-06-16 16:57:49 +0000 UTC:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
39.	2021-06-16 16:57:49 +0000 UTC:	[event;sealing.SectorOldTicket]	{"User":{}}
40.	2021-06-16 16:57:49 +0000 UTC:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"ESAlNc/5Rfzf4fVi1/GsR1zWnzn+o5lMvEjn0UwWeTo=","TicketEpoch":847508}}
7070.	2021-06-22 13:55:26 +0000 UTC:	[event;sealing.SectorTerminate]	{"User":{}}
7071.	2021-06-22 13:55:26 +0000 UTC:	[event;sealing.SectorTerminateFailed]	{"User":{}}
	checking precommit presence: sectorNumber is allocated, but PreCommit info wasn't found on chain
7072.	2021-06-22 13:56:26 +0000 UTC:	[event;sealing.SectorRemove]	{"User":{}}
7073.	2021-06-22 13:56:26 +0000 UTC:	[event;sealing.SectorTerminate]	{"User":{}}
7074.	2021-06-22 13:56:26 +0000 UTC:	[event;sealing.SectorTerminate]	{"User":{}}
7075.	2021-06-22 13:56:26 +0000 UTC:	[event;sealing.SectorRemoved]	{"User":{}}

`lotus-miner sectors list |grep 1276`
1276  Terminating  NO       NO      n/a       

**Additional context**
I have restarted the miner several times after trying to use remove command.

**Comment by Reiers** [comment]
**Hi @stuberman @KernelPanic80** 

Thanks for the report. This is fixed in the latest release.
Please upgrade Lotus [v1.15.1](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)

Closing issue ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

**Comment by RobQuistNL** [comment]
This is still happening in 1.15.1;

```
{"level":"warn","ts":"2022-05-09T18:08:14.022Z","logger":"sectors","caller":"storage-sealing/fsm.go:763","msg":"sector 46939 got error event sealing.SectorTerminateFailed: checking precommit presence: sectorNumber is allocated, but PreCommit info wasn't found on chain"}
{"level":"info","ts":"2022-05-09T18:08:14.028Z","logger":"sectors","caller":"storage-sealing/states_failed.go:28","msg":"TerminateFailed(46939), waiting 59.971208185s before retrying"}
```
