### ISSUE TITLE
[Proving Issue] I got one deadline Submitted window post, but the power is lost

### ISSUE THREAD

**Issue by EntropyPool** [filecoin-project/lotus#6585]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

Please provide all the information requested here to help us troubleshoot "proving/window PoSt failed" issues.
If the information requested is missing, we will probably have to just ask you to provide it anyway,
before we can help debug.

**Describe the problem**
A brief description of the problem you encountered while proving the storage.

**Version**

The output of `lotus --version`.

**Setup**

You miner and daemon setup, including what hardware do you use, your environment variable settings, how do you run your miner and worker, do you use GPU and etc.

**Proving status**

Miner: f07824
Current Epoch:           874158
Proving Period Boundary: 1877
Proving Period Start:    871637 (21 hours 30 seconds ago)
Next Period Start:       874517 (in 2 hours 59 minutes)

Faults:      37 (4.42%)
Recovering:  37
Deadline Index:       42
Deadline Sectors:     0
Deadline Open:        874157 (30 seconds ago)
Deadline Close:       874217 (in 29 minutes 30 seconds)
Deadline Challenge:   874137 (10 minutes 30 seconds ago)
Deadline FaultCutoff: 874087 (35 minutes 30 seconds ago)

The output of `lotus-miner proving` info.

**Lotus miner logs**

{"level":"info","ts":"2021-06-23T22:40:30.651+0800","logger":"storageminer","caller":"storage/wdpost_run.go:948","msg":"Submitted window post: bafy2bzaceaksdj26pikmczjy5qyadwych7nmdacsj6dfivqotvtlb7j44uox2"}

Please go through the logs of your miner, and include screenshots of any error-like messages you find, highlighting the one has "window post" in it.

Alternatively please upload full log files and share a link here

**Lotus miner diagnostic info**

Please collect the following diagnostic information, and share a link here

* lotus-miner diagnostic info `lotus-miner info all > allinfo.txt`

** Code modifications **

window post scheduler will communicate with multi lotus node, and select a live one to do the window post.

If you have modified parts of lotus, please describe which areas were modified,
and the scope of those modifications

**Comment by arajasek** [comment]
Please reopen with the requested info in the template.
