### ISSUE TITLE
Calibnet ProveCommitAggregate failure

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#6591]
Why did `bafy2bzacedtjb5jtsrymu3ljfj6dg6oslh7tf474qaqyius5bjck37zhbnabc` fail on calibration-net? Might well be some miner-side custom code going wonky, but we should confirm there's no bug on our end.

Also good to see what happened with the sectors eventually (did they ultimately get proven?)

**Comment by arajasek** [comment]
https://calibration.filscout.com/zh/message/bafy2bzacedtjb5jtsrymu3ljfj6dg6oslh7tf474qaqyius5bjck37zhbnabc

**Comment by ZenGround0** [comment]
100 Iterations of `lotus state replay bafy2bzacedtjb5jtsrymu3ljfj6dg6oslh7tf474qaqyius5bjck37zhbnabc` see the same behavior.

**Comment by ZenGround0** [comment]
One of the 819 sectors with sector id 1797 is not currently in the the miner's sector set.  All the others are.  This doesn't seem very surprising (maybe something went wrong with this single sector) or high impact (99 % of the sectors are currently proven) so closing down.

**Comment by arajasek** [comment]
Thanks @ZenGround0 !
