### ISSUE TITLE
[Feature Request] please add proposal CID to MarketPendingDeals result 

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/lotus#6597]
**Is your feature request related to a problem? Please describe.**

MarketPendingDeals should return the proposal CID of deals ! no more no less :)
otherwise its completely useless !

Julien

**Comment by s0nik42** [comment]
@jennijuju not a big change

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and is being completely removed from the code here:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
