### ISSUE TITLE
Allow PreCommit collateral to be moved from miner available balance

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6603]
Precommit collateral is moved from miner available balance in miner actor. Currently, in lotus, we are "forcing" the collateral to be paid from the worker/control address of the miner with the precommitsector message which leads miners to need to monitor the address balance closely so to maintain their miner operations = even they have enough funds in available balance to cover the collateral.

Two proposals we have:
A:  Add a check to see if miner's enough available balance to cover `collateral + buffer`, if it does, don't send any more funds with the message, if not, send the collateral with the message. 
B: make it configuration for miner to chose if they want to pay off using available balance or worker/control address.

**Comment by f8-ptrk** [comment]
people are doing this already, maybe ask how they implemented it and if they would pr it if the plan is ti implemented the advantage of keeping the code closed source will vanish and they can get at least "monetize" the PR

**Comment by jennijuju** [comment]
> people are doing this already, maybe ask how they implemented it and if they would pr it if the plan is ti implemented the advantage of keeping the code closed source will vanish and they can get at least "monetize" the PR

Pr is def welcomed, however, I don’t know what you meant by monetized.

**Comment by f8-ptrk** [comment]
having this is an advantage. not PR'ing it is keeping this advantage. if they PR it the advantage is gone and the prestige of having it PR'ed is the only thing they get out of it (--> monetized)

not PR'ing it and getting it implemented leaves them naked vs. the prestige of having it PR'ed

**Comment by jennijuju** [comment]
Option A is a better candidate, if we add the configuration, it should be "true" to move from miner balance by default.

**Comment by f8-ptrk** [comment]
B, option B!

we for example have mostly no access to the available balance as an operator - we do not have access to the owner key. if we now allow the worker key to, basically, withdraw and use block rewards we have a problem.

but since it is possible already we might have to revisit our thinking about the owner key anyways.

**Comment by jennijuju** [comment]
> B, option B!
> 
> we for example have mostly no access to the available balance as an operator - we do not have access to the owner key. if we now allow the worker key to, basically, withdraw and use block rewards we have a problem.
> 
> but since it is possible already we might have to revisit our thinking about the owner key anyways.

Good point - a combination of both sounds like a good idea.
