### ISSUE TITLE
[Deal Making Issue]

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/lotus#6609]
**Basic Information**
I am miner and I am accepting large number of small offline deals

**Describe the problem**
I am setting MaxDealsPerPublishMsg to 1024 and in one message I was publishing 300+ deals. It ends up with error
error calling node: publishing deal: mpool push: failed to push message: mpool message too large (79463B): message too big

** Expected Behavior**
Either the configuration should not be allowed, or the message should be publish when the maximum message size is reached.

**Version**

lotus version 1.10.0+mainnet+git.764fa9dae

**To Reproduce**
 1. MaxDealsPerPublishMsg to 1024
 2. Send large amount of small deals to the miner.

**Deal status**

error calling node: publishing deal: mpool push: failed to push message: mpool message too large (79463B): message too big

**Comment by f8-ptrk** [comment]
the miner cannot foresee how big the message is in the end --> how much gas it uses.  that is roughly known after the message is created and got simulated in the local vm. 

lower the configuration value.

**Comment by xinaxu** [comment]
Sure. Lower the configuration value will work. What it missed is a guidance for what value makes sense.

**Comment by f8-ptrk** [comment]
start small with 32 and see how much a single deal more adds to the gas usage from there

**Comment by xinaxu** [comment]
Thanks for the advice. We've been on 32 for a while. We were doing experiment to understand what can go wrong. 
A documentation or a validation would help so that other miners will not repeat the same mistake. Hence keep this open to track as a bug.

**Comment by xinaxu** [comment]
I will probably send out a pull request on the official doc later this week to add what you've suggested.

**Comment by rjan90** [comment]
Hi @xinaxu!

Where you able to do some experiments with this? Any recommendations to some ideal `MaxDealsPerPublishMsg` ? As Patrick noted, it´s impossible to know beforehand how big the message is - but I think if we add some conservative upperbound numbers to the comment in the config.toml file that should be sufficient to fix this.

**Comment by xinaxu** [comment]
They have increased the message size so now it seems safe to publish message with 100+ deals (I set mine to 256). But anything beyond 100 won't save you much gas cost.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
