### ISSUE TITLE
[BUG] big wast disk space (100GB/day) by /miner/kvlog/metadata/.log.cbor

### ISSUE THREAD

**Issue by Pacificwestcoast** [filecoin-project/lotus#6611]
Hello,

I am running calibnet v13 for just 5 days,
lotus version 1.10.0-rc6+calibnet+git.a641a0390

Today I got warning said my 500GB system hard disk almost full, I checked that this file takes  445GB, /miner/kvlog/metadata/***.log.cbor.
how could I do?

Thanks.

**Comment by f8-ptrk** [comment]
you can turn of the meta data log in the config.toml and delete the log file
