### ISSUE TITLE
appimage binary download is missing checksum

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#6613]
i just downloaded the appimage for someone who couldn't download it by himself and then realized that my "check with the official checksum" isn't working since there is none!

---> add check sums for binaries!

[edit]

see Assets at the bottom of https://github.com/filecoin-project/lotus/releases/tag/v1.10.0

**Comment by coryschwartz** [comment]
@f8-ptrk Thank you for the report!

Hope you like the AppImage.

We had a bug in our release script, that has since been fixed. Checksums updated on the release page.

**Comment by f8-ptrk** [comment]
not using it. just downloaded for someone else
