### ISSUE TITLE
ComputePost callback called again

### ISSUE THREAD

**Issue by linmuqin** [filecoin-project/lotus#662]
2019-11-21T17:31:43.841+0800	ERROR	storageminer	storage/post.go:268	BUG: computePost callback called again	{"ppe": 46093, "height": 45799, "curH": 45802, "called": 1}
github.com/filecoin-project/lotus/storage.(*Miner).computePost.func1
	/home/ylz/lotus/storage/post.go:268
github.com/filecoin-project/lotus/chain/events.(*heightEvents).headChangeAt.func2
	/home/ylz/lotus/chain/events/events_height.go:96
github.com/filecoin-project/lotus/chain/events.(*heightEvents).headChangeAt
	/home/ylz/lotus/chain/events/events_height.go:106
github.com/filecoin-project/lotus/chain/events.(*Events).headChange
	/home/ylz/lotus/chain/events/events.go:171
github.com/filecoin-project/lotus/chain/events.(*Events).listenHeadChangesOnce
	/home/ylz/lotus/chain/events/events.go:155
github.com/filecoin-project/lotus/chain/events.(*Events).listenHeadChanges
	/home/ylz/lotus/chain/events/events.go:97
2019-11-21T17:31:43.843+0800	ERROR	storageminer	storage/post.go:268	BUG: computePost callback called again	{"ppe": 46093, "height": 45799, "curH": 45802, "called": 2}
github.com/filecoin-project/lotus/storage.(*Miner).computePost.func1
	/home/ylz/lotus/storage/post.go:268
github.com/filecoin-project/lotus/chain/events.(*heightEvents).headChangeAt.func2
	/home/ylz/lotus/chain/events/events_height.go:96
github.com/filecoin-project/lotus/chain/events.(*heightEvents).headChangeAt
	/home/ylz/lotus/chain/events/events_height.go:106
github.com/filecoin-project/lotus/chain/events.(*Events).headChange
	/home/ylz/lotus/chain/events/events.go:171
github.com/filecoin-project/lotus/chain/events.(*Events).listenHeadChangesOnce
	/home/ylz/lotus/chain/events/events.go:155
github.com/filecoin-project/lotus/chain/events.(*Events).listenHeadChanges
	/home/ylz/lotus/chain/events/events.go:97

**Comment by Kubuxu** [comment]
As PoSt construction changes, this will be resolved very soon. Thus closing.
