### ISSUE TITLE
Why the transaction gaslimt in filecoin changes?

### ISSUE THREAD

**Issue by vae520283995** [filecoin-project/lotus#6624]
For example, the gaslimit for normal transfer in ethereum is 21000, and in filecoin it is 500000-600000. If the target address does not exist, it will be 2600000. Why is there such a difference?

**Comment by f8-ptrk** [comment]
do not nail me on this:

the gas usage of a message will depend on the states of the actors it is executed on/with for transfers the account actor. https://spec.filecoin.io/#section-systems.filecoin_vm.sysactors.accountactor

**Comment by arajasek** [comment]
> If the target address does not exist, it will be 2600000.

This is because the account for the target address gets created (if it doesn't exist), which costs more gas for the additional computation and storage.

**Comment by arajasek** [comment]
(closed since this isn't Lotus-specififc)
