### ISSUE TITLE
how to check base lotus sync status?

### ISSUE THREAD

**Issue by gitloverr** [filecoin-project/lotus#6626]
hi everyone,

lotus has the `lotus sync status` command, and it returning response like this: 

`
sync status:
worker 31050:
	Base:	[bafy2bzacebkcuyljmvgqrsdi4nyvvfeqrkd5mb7lhvxbn5k6rurnrpdhdhojs bafy2bzacednmfovkhkq7hdguxosk2t66fvtdbow2vhxbu6j2sdh2b3txxjpam bafy2bzacecegcsbroepwoz5rzqggbhgttdghln4dfym47wswc7cawzv7sskua]
	Target:	[bafy2bzaceackgwpqsv5kn6sksj5qifzjq47gtgg6hqj4d67bxlkpeo7q25w3m] (30167)
	Height diff:	0
	Stage: complete
	Height: 30167
	Elapsed: 16.718371ms
worker 31051:
	Base:	[bafy2bzaceackgwpqsv5kn6sksj5qifzjq47gtgg6hqj4d67bxlkpeo7q25w3m bafy2bzacebkcuyljmvgqrsdi4nyvvfeqrkd5mb7lhvxbn5k6rurnrpdhdhojs bafy2bzacednmfovkhkq7hdguxosk2t66fvtdbow2vhxbu6j2sdh2b3txxjpam bafy2bzacecegcsbroepwoz5rzqggbhgttdghln4dfym47wswc7cawzv7sskua]
	Target:	[bafy2bzaceakpfkltudmlj2myzt67jn3i3dxgsxihq2pgwa6rt42q44fx3hszw] (30168)
	Height diff:	1
	Stage: complete
	Height: 30168
	Elapsed: 16.398568ms
worker 31052:
	Base:	[bafy2bzaceakpfkltudmlj2myzt67jn3i3dxgsxihq2pgwa6rt42q44fx3hszw]
	Target:	[bafy2bzacecv6veiewi7yixc4hyogj4364iofntvojbjmwncncf6weguyezyhm] (30168)
	Height diff:	0
	Stage: complete
	Height: 30168
	Elapsed: 14.196654ms
`

now, I would like to know **sync status node** like: `ok` or `not`.  

I found a command like the answer I want at  issue #5766 . it has `Chain: [sync ok]` info. but I guess it's not valid now.

How can I understand (the best) this output according to whether I am sync or not?

thank you

**Comment by f8-ptrk** [comment]
you can run `lotus sync wait` and wait it to return to see if you are synced or not
