### ISSUE TITLE
why chainNotify method catching the same  cids? 

### ISSUE THREAD

**Issue by gitloverr** [filecoin-project/lotus#6630]
hi everyone,

I'm listening the network  newly published messages with chainNotifyMethod over websocket connection. but a previously sent message has been published like this:  Response has the same cids and same height. why? 

```
`
 Height 30876
Cid [
  {
    '/': 'bafy2bzacedqa57rzfgmuxqp5km2lsk2tj3hqhzjphuly4lit64axr4dbia6aq' 
  }
]
 Height 30876
Cid [
  {
    '/': 'bafy2bzaceahjfcyb2xoduaxblwanddhub2quuo43hrg5vcmybckva2lxqujw2'
  },
  {
    '/': 'bafy2bzacedqa57rzfgmuxqp5km2lsk2tj3hqhzjphuly4lit64axr4dbia6aq' **( published ID)**
  }
]
 Height 30876
Cid [
  {
    '/': 'bafy2bzacedpzr5mhroas3ohghhsknh7pdhgj6hi5sgxbprz47cvdsjtsxmtwk'
  },
  {
    '/': 'bafy2bzaceahjfcyb2xoduaxblwanddhub2quuo43hrg5vcmybckva2lxqujw2'
  },
  {
    '/': 'bafy2bzacedqa57rzfgmuxqp5km2lsk2tj3hqhzjphuly4lit64axr4dbia6aq'   **( published ID)**
  }
]

`
```

Can I get it when the block reaches final status over this chainNotify method or like this?

thank you

**Comment by Stebalien** [comment]
If you want finality, you need to look _back_ several blocks. ChainNotify will give you the latest head, but that can change.
