### ISSUE TITLE
syncing the chain is so slow and print a lot of error message

### ISSUE THREAD

**Issue by barnettshao** [filecoin-project/lotus#664]
![9-4](https://user-images.githubusercontent.com/10030218/69333107-06153380-0c93-11ea-9fae-3dfcfeebdeea.png)
![9-5](https://user-images.githubusercontent.com/10030218/69333108-06adca00-0c93-11ea-9853-aca6076c9b21.png)
![9-6](https://user-images.githubusercontent.com/10030218/69333110-06adca00-0c93-11ea-8215-eba94a4f6176.png)
![9-7](https://user-images.githubusercontent.com/10030218/69333133-13cab900-0c93-11ea-99ac-0b958ed8961b.png)

**Comment by whyrusleeping** [comment]
Thanks for submitting this, we are working on these.

**Comment by whyrusleeping** [comment]
some of these are resolved in the latest devnet, the post errors are being fixed as well. closing for now
