### ISSUE TITLE
[BUG] `lotus daemon` should refuse to run unless all verification params are present

### ISSUE THREAD

**Issue by ribasushi** [filecoin-project/lotus#6640]
**Describe the bug**

During the recent upgrade a number of folks ended up running their nodes with the new aggregate-proof validation param missing. This led to the formation of an uncomfortably long-lived side-chain.

Since the validation set is really small ( less than 300MiB ), we should just check its presence and integrity on every startup, regardless of `TRUST_PARAMS` or any other escape hatches.

**Comment by whyrusleeping** [comment]
This should be pretty high priority. Like P1 or so. Really bad sort of thing that caused a fork and a good number of miners to lose funds.

**Comment by placer14** [comment]
Context from @ribasushi:
> the core of the issue is that miners set TRUST_PARAMS all the time ( it is not feasible to not do that - startup time is too long without it )
> but setting TRUST_PARAMS disables all checks, including for the validation params, which in turn leaves nodes in a state where they can't validate what's coming from the network

**Comment by placer14** [comment]
I'm pretty sure the inputs here are:
- `build/proof-params/parameters.json` manifest of all params
- the path where the params are locally kept
- heuristics to determine "validation" from "proof" params (unknown and seeking clarification)
