### ISSUE TITLE
potential edge case in dynamic retrieval pricing

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#6678]
A few retrieval deals made by the dealbot with the same miner failed with the following. Recording here to analyse further:

```
got error in offer: retrieval query offer errored: failed to price deal: GetRetrievalPricingInput:
failed to look up deal 1912670 on chain: err=deal 1912670 not found - deal may not have completed
sealing before deal proposal start epoch, or deal may have been slashed: deal 1912670 not found -
deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed`
```

This may be a legitimate and genuine case of the miner failing to seal the storage deal on time, but let's analyse it.

**Comment by aarshkshah1992** [comment]
@raulk Have filed https://github.com/filecoin-project/lotus/pull/6679. We shouldn't error out the retrieval pricing input function if we fail to lookup the state of a storage deal because we could have other storage deals for the Piece we're trying to retrieve.
