### ISSUE TITLE
Mining upon a base with early block cause " weight draw", is this expected?

### ISSUE THREAD

**Issue by ricktian1226** [filecoin-project/lotus#6686]
### Discussed in https://github.com/filecoin-project/lotus/discussions/6685

<div type='discussions-op-text'>

<sup>Originally posted by **ricktian1226** July  6, 2021</sup>
miner tried to mine on 904463 as follow:
2021-07-05T07:11:11.247+0800 ^[[34mINFO^[[0m miner miner/miner.go:646 completed mineOne {"tookMilliseconds": 5164, "forRound": 904463, **"baseEpoch": 904461, "baseDeltaSeconds": 36, "nullRounds": 1,** "lateStart": false, "beaconEpoch": 1000307, "lookbackEpochs": 900, "networkPowerAtLookback": "8095175825230954496", "minerPowerAtLookback": "1396792084135936", "isEligible": true, "isWinner": true, "error": null}

Attention to  "baseDeltaSeconds": 36 . When miner mine 904463, the base it calculate on is 904461. And lotus encouters "weight draw", block was abandoned...

2021-07-05T07:11:30.125+0800 ^[[31mERROR^[[0m chainstore store/store.go:414 weight draw {"currTs": "[bafy2bzaceaxvae7ubj2k7stanbtax64wgou7vvdqyjgm7msuolkq2x7suyd4i]", "ts": "[bafy2bzacea7gtbjewlomps3c7tn5puw7hrx7cqedyq67zebooqqrzgu5h7p34]"}

The question is : Is it correct to mine 904463 base on 904461? I think the result will always be abandoned.</div>

**Comment by ricktian1226** [comment]
@whyrusleeping

**Comment by ribasushi** [comment]
> The question is : Is it correct to mine 904463 base on 904461?

It is correct provided your node has not seen *any* 904462 blocks, and therefore saw that as a nul-epoch

Please look through your node (daemon, not miner) logs/journal and grab more info from around that time.

**Comment by ricktian1226** [comment]
@ribasushi 
These are journal logs around that time on my node: 
{"System":"sync","Event":"head_change","Timestamp":"2021-07-05T07:10:30.3220087+08:00","Data":{"From":[{"/":"bafy2bzacecfjopmtemata47pgxwcjwzbotovdrtwk3v4mdzztvyts5iwqeovu"},{"/":"bafy2bzacecqynnpkgl3jzfj46a7s5um4wegm5z26gkewyx2zm2ansymw63miy"},{"/":"bafy2bzaceckpuhuogowqdxlipalhc7jz6ryfuu6jxt3f3naeat3oop4seqycc"}],"FromHeight":904460,"To":[{"/":"bafy2bzacedljp4mn5dwgyzoefxdudfbtnrvbkr2yy6g4pelqdhhaumzrq3cr4"}],"ToHeight":904461,"RevertCount":0,"ApplyCount":1}}
{"System":"sync","Event":"head_change","Timestamp":"2021-07-05T07:10:30.401850899+08:00","Data":{"From":[{"/":"bafy2bzacedljp4mn5dwgyzoefxdudfbtnrvbkr2yy6g4pelqdhhaumzrq3cr4"}],"FromHeight":904461,"To":[{"/":"bafy2bzacedljp4mn5dwgyzoefxdudfbtnrvbkr2yy6g4pelqdhhaumzrq3cr4"},{"/":"bafy2bzaceb3caxxf7bazdywst4qymgpy55fum6rdm23z5t3gnvbdnz4we4gos"}],"ToHeight":904461,"RevertCount":1,"ApplyCount":1}}
{"System":"sync","Event":"head_change","Timestamp":"2021-07-05T07:10:30.894050788+08:00","Data":{"From":[{"/":"bafy2bzacedljp4mn5dwgyzoefxdudfbtnrvbkr2yy6g4pelqdhhaumzrq3cr4"},{"/":"bafy2bzaceb3caxxf7bazdywst4qymgpy55fum6rdm23z5t3gnvbdnz4we4gos"}],"FromHeight":904461,"To":[{"/":"bafy2bzacedljp4mn5dwgyzoefxdudfbtnrvbkr2yy6g4pelqdhhaumzrq3cr4"},{"/":"bafy2bzaceb3caxxf7bazdywst4qymgpy55fum6rdm23z5t3gnvbdnz4we4gos"},{"/":"bafy2bzacebas2pjijl4mhmrhmg6dqffbn3tb3wekryhprsanq6lmdgmudxuve"}],"ToHeight":904461,"RevertCount":1,"ApplyCount":1}}
{"System":"sync","Event":"head_change","Timestamp":"2021-07-05T07:11:13.495614817+08:00","Data":{"From":[{"/":"bafy2bzacedljp4mn5dwgyzoefxdudfbtnrvbkr2yy6g4pelqdhhaumzrq3cr4"},{"/":"bafy2bzaceb3caxxf7bazdywst4qymgpy55fum6rdm23z5t3gnvbdnz4we4gos"},{"/":"bafy2bzacebas2pjijl4mhmrhmg6dqffbn3tb3wekryhprsanq6lmdgmudxuve"}],"FromHeight":904461,"To":[{"/":"bafy2bzaceaxvae7ubj2k7stanbtax64wgou7vvdqyjgm7msuolkq2x7suyd4i"}],"ToHeight":904462,"RevertCount":0,"ApplyCount":1}}
{"System":"sync","Event":"head_change","Timestamp":"2021-07-05T07:11:30.317147252+08:00","Data":{"From":[{"/":"bafy2bzaceaxvae7ubj2k7stanbtax64wgou7vvdqyjgm7msuolkq2x7suyd4i"}],"FromHeight":904462,"To":[{"/":"bafy2bzaced4ybczt32ti4nhbeycjsmmhlway4tne4iit7f2zxpqhbuqss47yu"},{"/":"bafy2bzacea2vzd3efut2gdx3upfl5d3motz4p2dybw6t5wyl27kw3z6zw2oxu"}],"ToHeight":904463,"RevertCount":0,"ApplyCount":1}}
{"System":"sync","Event":"head_change","Timestamp":"2021-07-05T07:11:30.327056382+08:00","Data":{"From":[{"/":"bafy2bzaced4ybczt32ti4nhbeycjsmmhlway4tne4iit7f2zxpqhbuqss47yu"},{"/":"bafy2bzacea2vzd3efut2gdx3upfl5d3motz4p2dybw6t5wyl27kw3z6zw2oxu"}],"FromHeight":904463,"To":[{"/":"bafy2bzaced4ybczt32ti4nhbeycjsmmhlway4tne4iit7f2zxpqhbuqss47yu"},{"/":"bafy2bzacea2vzd3efut2gdx3upfl5d3motz4p2dybw6t5wyl27kw3z6zw2oxu"},{"/":"bafy2bzacecsehdbbgr3n7csf3oax6ejsevyd3p6xjyj556d7dp3kfnj27zyry"}],"ToHeight":904463,"RevertCount":1,"ApplyCount":1}}
{"System":"sync","Event":"head_change","Timestamp":"2021-07-05T07:11:30.357714685+08:00","Data":{"From":[{"/":"bafy2bzaced4ybczt32ti4nhbeycjsmmhlway4tne4iit7f2zxpqhbuqss47yu"},{"/":"bafy2bzacea2vzd3efut2gdx3upfl5d3motz4p2dybw6t5wyl27kw3z6zw2oxu"},{"/":"bafy2bzacecsehdbbgr3n7csf3oax6ejsevyd3p6xjyj556d7dp3kfnj27zyry"}],"FromHeight":904463,"To":[{"/":"bafy2bzaced4ybczt32ti4nhbeycjsmmhlway4tne4iit7f2zxpqhbuqss47yu"},{"/":"bafy2bzacea2vzd3efut2gdx3upfl5d3motz4p2dybw6t5wyl27kw3z6zw2oxu"},{"/":"bafy2bzacecsehdbbgr3n7csf3oax6ejsevyd3p6xjyj556d7dp3kfnj27zyry"},{"/":"bafy2bzacede52mitmcflnw664dmqlvjmc3nbww5zazeess47skfoeqf7urylu"}],"ToHeight":904463,"RevertCount":1,"ApplyCount":1}}
{"System":"sync","Event":"head_change","Timestamp":"2021-07-05T07:11:30.426898718+08:00","Data":{"From":[{"/":"bafy2bzaced4ybczt32ti4nhbeycjsmmhlway4tne4iit7f2zxpqhbuqss47yu"},{"/":"bafy2bzacea2vzd3efut2gdx3upfl5d3motz4p2dybw6t5wyl27kw3z6zw2oxu"},{"/":"bafy2bzacecsehdbbgr3n7csf3oax6ejsevyd3p6xjyj556d7dp3kfnj27zyry"},{"/":"bafy2bzacede52mitmcflnw664dmqlvjmc3nbww5zazeess47skfoeqf7urylu"}],"FromHeight":904463,"To":[{"/":"bafy2bzaced4ybczt32ti4nhbeycjsmmhlway4tne4iit7f2zxpqhbuqss47yu"},{"/":"bafy2bzacebipvw4qcksjamoa6h64ifv7tfbejslfmhwnnnazn2sl76dd4akus"},{"/":"bafy2bzacea2vzd3efut2gdx3upfl5d3motz4p2dybw6t5wyl27kw3z6zw2oxu"},{"/":"bafy2bzacecsehdbbgr3n7csf3oax6ejsevyd3p6xjyj556d7dp3kfnj27zyry"},{"/":"bafy2bzacede52mitmcflnw664dmqlvjmc3nbww5zazeess47skfoeqf7urylu"}],"ToHeight":904463,"RevertCount":1,"ApplyCount":1}}
{"System":"sync","Event":"head_change","Timestamp":"2021-07-05T07:11:30.452673639+08:00","Data":{"From":[{"/":"bafy2bzaced4ybczt32ti4nhbeycjsmmhlway4tne4iit7f2zxpqhbuqss47yu"},{"/":"bafy2bzacebipvw4qcksjamoa6h64ifv7tfbejslfmhwnnnazn2sl76dd4akus"},{"/":"bafy2bzacea2vzd3efut2gdx3upfl5d3motz4p2dybw6t5wyl27kw3z6zw2oxu"},{"/":"bafy2bzacecsehdbbgr3n7csf3oax6ejsevyd3p6xjyj556d7dp3kfnj27zyry"},{"/":"bafy2bzacede52mitmcflnw664dmqlvjmc3nbww5zazeess47skfoeqf7urylu"}],"FromHeight":904463,"To":[{"/":"bafy2bzaced4ybczt32ti4nhbeycjsmmhlway4tne4iit7f2zxpqhbuqss47yu"},{"/":"bafy2bzacebipvw4qcksjamoa6h64ifv7tfbejslfmhwnnnazn2sl76dd4akus"},{"/":"bafy2bzacebkc3etgjvxjs743fb4ads4hdl64tqpvuarncgtnukr5l5fkz5i4m"},{"/":"bafy2bzacea2vzd3efut2gdx3upfl5d3motz4p2dybw6t5wyl27kw3z6zw2oxu"},{"/":"bafy2bzacecsehdbbgr3n7csf3oax6ejsevyd3p6xjyj556d7dp3kfnj27zyry"},{"/":"bafy2bzacede52mitmcflnw664dmqlvjmc3nbww5zazeess47skfoeqf7urylu"}],"ToHeight":904463,"RevertCount":1,"ApplyCount":1}}

**Comment by ricktian1226** [comment]
And I think the result of mining 904463 base on 904461 would always be abandoned, am I right?

**Comment by ribasushi** [comment]
@ricktian1226 no. If there was no 904462 tipset then of course 904463 will be based on 904461
For example [`908364`](https://filscan.io/tipset/chain?height=908364) bases off `908362`

**Comment by ribasushi** [comment]
@ricktian1226 to clarify: tipsets come every 30 seconds. No matter what. The "frequency" is driven by multiple factors including: https://en.wikipedia.org/wiki/League_of_entropy

You can find out the precise "what is the current height" without even looking at the chain, but simply:
`~$ echo "$(( ($( date "+%s" )-1598306400)/30))"`

**Comment by ricktian1226** [comment]
> @ricktian1226 no. If there was no 904462 tipset then of course 904463 will be based on 904461
> For example [`908364`](https://filscan.io/tipset/chain?height=908364) bases off `908362`

While miner "think" 904462 is nullRound but lotus synced 904462 then. Another 904463 mining was triggered, and "double-fork" showed up.

2021-07-05T07:11:33.936+0800 ^[[33mWARN^[[0m miner miner/miner.go:470 mined block in the past {"block-time": "2021-07-05T07:11:30.000+0800", "time": "2021-07-05T07:11:33.936+0800", "difference": 3.936910234, "#": "904463"}
2021-07-05T07:11:33.937+0800 ^[[31mERROR^[[0m miner miner/miner.go:477 <!!> SLASH FILTER ERROR: produced block would trigger 'double-fork mining faults' consensus fault; miner: f01061547; bh: bafy2bzacea5y2734rb7uo7zgwmg7vou3xg5xxxjyb7z5pgzpkn6rfgegvmlgy, other: bafy2bzacea7gtbjewlomps3c7tn5puw7hrx7cqedyq67zebooqqrzgu5h7p34

**Comment by ricktian1226** [comment]
So it was a "revert" behavior?
904462 was considered as a nul-epoch once upon a time. Then when new 904462 tipset was synced, chain reverted?

**Comment by ricktian1226** [comment]
@ribasushi thanks bro, I think I got it.
