### ISSUE TITLE
How can I import the miner after I removed lotusstorage

### ISSUE THREAD

**Issue by Malone-Ma** [filecoin-project/lotus#669]
I removed ~/.lotusstorage file, but I can't create a new miner by limited. and I also can't init miner by lacking of funds.

right now, what should I do, I can run the miner program...

thanks.

**Comment by magik6k** [comment]
For now you need to create new miner in https://lotus-faucet.kittyhawk.wtf/miner.html, you may need to create new wallet address for that if you are seeing 'too many requests'

**Comment by Malone-Ma** [comment]
I created a new wallet bls, but also can't create new miner in the link. there are too many requests.

**Comment by lvusyy** [comment]
> I created a new wallet bls, but also can't create new miner in the link. there are too many requests.

try running "lotus wallet new bls" to create a new wallet address, and you need to put the wallet address in lotus-faucet.kittyhawk.wtf/miner.html. 
Tip: Maybe you have to wait a few seconds.

**Comment by Malone-Ma** [comment]
> > I created a new wallet bls, but also can't create new miner in the link. there are too many requests.
> 
> try running "lotus wallet new bls" to create a new wallet address, and you need to put the wallet address in lotus-faucet.kittyhawk.wtf/miner.html.
> Tip: Maybe you have to wait a few seconds.

I ran lotus wallet new bls again, but nothing happen, although I waited for a few hours...it always stay by wait page...like this...nothing changed. I can't get actor ID...

[CREATING STORAGE MINER]
Gas Funds:   bafy2bzaceat3ypnfztcogdg2vjs6kxouk3co6jsccvc4dlnx2syff4pg7a77o - WAIT
Miner Actor: bafy2bzacecl62fonssnzdtmjsgqrmwi2vz7d3iqpnt5hgg4sf24udjqxicr3a - WAIT

**Comment by gy810986741** [comment]
> > > I created a new wallet bls, but also can't create new miner in the link. there are too many requests.
> > 
> > 
> > try running "lotus wallet new bls" to create a new wallet address, and you need to put the wallet address in lotus-faucet.kittyhawk.wtf/miner.html.
> > Tip: Maybe you have to wait a few seconds.
> 
> I ran lotus wallet new bls again, but nothing happen, although I waited for a few hours...it always stay by wait page...like this...nothing changed. I can't get actor ID...
> 
> [CREATING STORAGE MINER]
> Gas Funds: bafy2bzaceat3ypnfztcogdg2vjs6kxouk3co6jsccvc4dlnx2syff4pg7a77o - WAIT
> Miner Actor: bafy2bzacecl62fonssnzdtmjsgqrmwi2vz7d3iqpnt5hgg4sf24udjqxicr3a - WAIT

I got the same issue...

**Comment by whyrusleeping** [comment]
your problems were probably caused by the faucet being down. Things are looking better in the new devnet.
