### ISSUE TITLE
Proving Period error

### ISSUE THREAD

**Issue by linmuqin** [filecoin-project/lotus#670]
Miner: t0881
Sector Size: 1.0 GiB
Power: 0.0 B / 933.50 GiB (0.0000%)
Worker use: 0 / 5 (+1)
Proving Period: 52209, in -2529 Blocks (~-505m -48s)
Sectors:  map[PreCommitted:8 Proving:4 Total:12]

Why are blocks negative?

**Comment by gy810986741** [comment]
Hey, I got the issue like yours ,but mine is "proving period : not proving" and when I started mining there would be an error said  'ProvingPeriodEnd == 0'. Could you please tell me if I need to do something before starting mining? or how to avoid this error? Many thanks!

**Comment by gy810986741** [comment]
Perhaps it looks like your synchronization is not completed?

**Comment by whyrusleeping** [comment]
this has been improved, closing
