### ISSUE TITLE
Is Lotus RPC API "Filecoin.ChainHead"  fetch finalized block?  Or do I need to handle reorg situation

### ISSUE THREAD

**Issue by BomaxChen** [filecoin-project/lotus#6704]
as titile,  rpc api "Filecoin.ChainHead" fetch finalized block?  If not, how do I check reorg situation

**Comment by magik6k** [comment]
ChainHead returns current best tipset, which isn't finalized (has zero finality). You can use [`ChainGetPath`](https://github.com/filecoin-project/lotus/blob/master/api/v0api/full.go#L142) between calls to see if there were any reorgs.

Alternatively you can use `ChainNotify` to get atomic notifications (assuming that your jsonrpc client supports go-jsonrpc channels)
