### ISSUE TITLE
[Deal Making Issue] Fsm randomly breaks and gets into invalid state transitions

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#6712]
I've had this happen three times now, but periodically something breaks and throws the fsm into an infinite loop of invalid state transitioning. The logs look something like this:
```
2021-07-08T18:28:43.857Z        ERROR   fsm     fsm/fsm.go:92   Executing event planner failed: Invalid transition in queue, state `2`, event `21`:
    github.com/filecoin-project/go-statemachine/fsm.eventProcessor.Apply
        /home/why/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/fsm/eventprocessor.go:137
2021-07-08T18:28:43.858Z        ERROR   fsm     fsm/fsm.go:92   Executing event planner failed: Invalid transition in queue, state `2`, event `4`:
    github.com/filecoin-project/go-statemachine/fsm.eventProcessor.Apply
        /home/why/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/fsm/eventprocessor.go:137
```

Repeated ad-infinum.

I believe that it happens while im doing retrieval related things, since ive done something retrieval related since last process restart each time this has happened, but it does not happen temporally near my retrieval attempts.

**Comment by aarshkshah1992** [comment]
@whyrusleeping 

What's the lotus/markets/data-transfer/go-graphsync version on this one ?

**Comment by whyrusleeping** [comment]
```
why@sirius ~/c/estuary (master)> cat go.mod | grep data-transfer
	github.com/filecoin-project/go-data-transfer v1.6.0
why@sirius ~/c/estuary (master)> cat go.mod | grep graphsync
	github.com/ipfs/go-graphsync v0.6.3
```

Ill look through the logs and try to find which logfile was before this issue, I might have deleted it accidentally.

**Comment by raulk** [comment]
@whyrusleeping any luck with the logs? Have you seen this again in the last month?

**Comment by raulk** [comment]
@whyrusleeping you said you had logs. Can you attach them here?

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
