### ISSUE TITLE
. lotus is in the / root / path. Now it is prompted that the disk space is insufficient. How can I change the location of. / lotus? I don't seem to see any way

### ISSUE THREAD

**Issue by Motto-chen** [filecoin-project/lotus#6730]
. lotus is in the / root / path. Now it is prompted that the disk space is insufficient. How can I change the location of. / lotus? I don't seem to see any way
![image](https://user-images.githubusercontent.com/56291932/125235300-d4902680-e314-11eb-9911-e5149aeb9b4e.png)
![image](https://user-images.githubusercontent.com/56291932/125235358-ec67aa80-e314-11eb-94ea-0fe5dea6c8a8.png)

**Comment by dayou5168** [comment]
you can set $LOTUS_MINER_PATH to override the default option which is "~/.lotusminer". you can set the path to any path you want. then restart the lotus miner.

**Comment by dayou5168** [comment]
You may need this docs  for reference https://docs.filecoin.io/mine/lotus/backup-and-restore/#backup
