### ISSUE TITLE
 genesis in the repo is not the one expected by this version of Lotus! 

### ISSUE THREAD

**Issue by colccool** [filecoin-project/lotus#6731]
run- lotus daemon

version: lotus version 1.11.1-dev+calibnet+git.88ac2ebc0

ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/Users/pluto/lotus/node/modules/lp2p/addrs.go:98): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/opt/homebrew/Cellar/go/1.16.5/libexec/src/reflect/asm_arm64.s:12): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/opt/homebrew/Cellar/go/1.16.5/libexec/src/reflect/asm_arm64.s:12): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/opt/homebrew/Cellar/go/1.16.5/libexec/src/reflect/asm_arm64.s:12): failed to build dtypes.AfterGenesisSet: received non-nil error from function "reflect".makeFuncStub (/opt/homebrew/Cellar/go/1.16.5/libexec/src/reflect/asm_arm64.s:12): genesis in the repo is not the one expected by this version of Lotus!

someone can help me ?

**Comment by dayou5168** [comment]
Usually, this error is because you have not cleared the old version of the compilation environment. I suggest you download the master branch code again and recompile it. If lotus daemon can run normal, please let me know

**Comment by dayou5168** [comment]
Please  remember  to delete the old lotus folder before  you download lotus.

**Comment by colccool** [comment]
OK，i will try it ，thank you so much



发自我的iPhone


------------------ Original ------------------
From: chen wei ***@***.***&gt;
Date: Mon,Jul 12,2021 2:35 PM
To: filecoin-project/lotus ***@***.***&gt;
Cc: sexfody ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [filecoin-project/lotus]  genesis in the repo is not the one expected by this version of Lotus!  (#6731)
