### ISSUE TITLE
Usually, this error is because you have not cleared the old version of the compilation environment. I suggest you download the master branch code again and recompile it. If lotus daemon can run normal, please let me know

### ISSUE THREAD

**Issue by colccool** [filecoin-project/lotus#6734]
Usually, this error is because you have not cleared the old version of the compilation environment. I suggest you download the master branch code again and recompile it. If lotus daemon can run normal, please let me know

_Originally posted by @dayou5168 in https://github.com/filecoin-project/lotus/issues/6731#issuecomment-878010746_

**Comment by colccool** [comment]
the bug still exist ,I delete the old version

**Comment by jennijuju** [comment]
? This doesn’t seems like a github issue - I’d recommend you to read https://guides.github.com/features/issues/

for your original question - please follow up in https://github.com/filecoin-project/lotus/discussions/6732

**Comment by colccool** [comment]
> ? This doesn’t seems like a github issue - I’d recommend you to read https://guides.github.com/features/issues/
> 
> for your original question - please follow up in #6732

I submit the issues #6732 ,but not figure out

**Comment by jennijuju** [comment]
> > ? This doesn’t seems like a github issue - I’d recommend you to read https://guides.github.com/features/issues/
> > for your original question - please follow up in #6732
> 
> I submit the issues #6732 ,but not figure out

Someone was helping you in the discussion  - post another comment to let them you need further support instead of creating a new issue please
