### ISSUE TITLE
implement DAG store CLI commands

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#6736]
https://github.com/filecoin-project/lotus/pull/6671 removes Badger from the dealmaking flow, integrates indexed CARv2 that can act as standalone blockstores, and introduces a new component called "DAG store" to manage deal data in a sharded way, where each deal is a shard.

Read more about the DAG store in the [design document](https://github.com/filecoin-project/dagstore/blob/master/docs/design.md).

In order to make the DAG store observable and manageable, we should introduce a new command `lotus dagstore` in the Lotus miner binary, targeting the Lotus markets subsystem, with the following subcommands:

* `lotus dagstore shard-list` => enumerates shards and their status.
* `lotus dagstore shard-destroy --key <key> --force` => forcefully destroys a shard.
* `lotus dagstore shard-fetch --key <key>` => manual shard fetch.
* `lotus dagstore shard-index --key <key>` => manual reindex.
* `lotus dagstore gc` => calls DAGStore GC.

**Comment by rjan90** [comment]
Hey!

Closing this issue since we have multiple ways of observing and managing the Dagstore in Lotus now.

It also seems like most of the subcommands listed has been implemented. Only missing a potential `shard-destroy` command. If you want, I can create a separate ticket for that?
