### ISSUE TITLE
API Token not set and requested, capabilities might be limited. ERROR: unknown url scheme 'token'

### ISSUE THREAD

**Issue by colccool** [filecoin-project/lotus#6742]
lotus wallet list

2021-07-13T18:21:24.347+0800	WARN	cliutil	util/apiinfo.go:81	API Token not set and requested, capabilities might be limited.
ERROR: unknown url scheme 'token'

I don't know why ,someone can help me ?

**Comment by dayou5168** [comment]
You can refer to this page：https://docs.filecoin.io/get-started/lotus/send-and-receive-fil/#about-wallet-addresses
follow the steps to learn how to manange the wallet. btw. you can go to our slack channel for help : https://filecoin.io/slack
