### ISSUE TITLE
Ability to decline deals if overloaded (requires feedback from storage-miner code) [ P1 ]

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6750]

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and is being completely removed from the code here:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
