### ISSUE TITLE
caller type bafkqadlgnfwc6njpmfrwg33vnz2a cannot exec actor type bafkqadtgnfwc6mzpnv2wy5djonuwo (RetCode=18) 

### ISSUE THREAD

**Issue by jc0803kevin** [filecoin-project/lotus#6752]
When creating a multi-signature address, the broadcast transaction returns this error. codeCID("fil/5/multisig")

**Comment by dayou5168** [comment]
You can look at this document and try again：https://docs.filecoin.io/get-started/lotus/multisig/#create-a-multsig-wallet
i create one msg wallet. it works.

**Comment by jc0803kevin** [comment]
@dayou5168 不是采用rpc的访问的方式创建。这边是参考https://github.com/blitslabs/filecoin-js-signer，进行离线创建的。官方有离线创建的demo么？谢谢！

**Comment by dayou5168** [comment]
@jc0803kevin 据我所知，还没有离线创建的demo.我会反馈这个问题。你可以先尝试rpc创建

**Comment by jc0803kevin** [comment]
@dayou5168 rpc 访问需要将私钥保存在节点里面，这个不满足我们的生产要求。您知道其他的什么库么？？

**Comment by dayou5168** [comment]
@jc0803kevin 你在微信和slack群吗，其它成员也许有类似的解决经验　，加外：https://github.com/blitslabs/filecoin-js-signer/blob/master/src/signing-tools/methods/multisig.ts　你看下这个，或许有用。

**Comment by jc0803kevin** [comment]
@dayou5168 不在微信和stack群，您能拉我进一下群么？wx:jc0803kevin

您发的这个js库，目前就是参照这个做，但是参数解析不出来，看这笔交易https://filfox.info/zh/message/bafy2bzacechs5noqireds4omr6cx6t57vblu3sfvedywsjpneinaltrbbcq2y

**Comment by dayou5168** [comment]
> @dayou5168 不在微信和stack群，您能拉我进一下群么？wx:jc0803kevin
> 
> 您发的这个js库，目前就是参照这个做，但是参数解析不出来，看这笔交易https://filfox.info/zh/message/bafy2bzacechs5noqireds4omr6cx6t57vblu3sfvedywsjpneinaltrbbcq2y

不是我写的！

**Comment by jc0803kevin** [comment]
> > @dayou5168 不在微信和stack群，您能拉我进一下群么？wx:jc0803kevin
> > 您发的这个js库，目前就是参照这个做，但是参数解析不出来，看这笔交易https://filfox.info/zh/message/bafy2bzacechs5noqireds4omr6cx6t57vblu3sfvedywsjpneinaltrbbcq2y
> 
> 不是我写的！

那个是一个三方的，我就是参照这个做的，然后出现了这个问题，您能拉我进一下群么？wx:jc0803kevin

**Comment by Reiers** [comment]
**Thanks for the translation @dayou5168 !**
_and thanks for the report._

Closing ticket.

If you are still experiencing problems, open a new ticket or ask in our Discussions <link>forum.
