### ISSUE TITLE
[Mining Issue]  Pledge three sectors on miner, but the worker only runs the first one

### ISSUE THREAD

**Issue by huhuapop** [filecoin-project/lotus#6767]
There is one miner server and one worker server. 
I meet a problem it's about pledge three sectors, but the worker only runs the first one. 

The running command of worker is : 

lotus-worker --worker-repo=/mnt/md0/worker2345 --miner-repo=/mnt/md0/miner  run --listen=192.168.1.221:2345  --addpiece=false --precommit1=true --precommit2=true --unseal=false --commit=true --parallel-fetch-limit=2. 

What will be the problem?

**Version**
lotus --version:  lotus version 1.11.1-dev+mainnet+git.f0c9e4e8f

![image](https://user-images.githubusercontent.com/35068603/125812481-46f25433-eb86-45e9-9767-e927b46e1fe5.png)

**Comment by jburnett** [comment]
What is your disk layout?  Is there enough fast (NVMe, SSD) drive space available for all 3 sectors. Keep in mind that each 32-GB sector requires ~270 GB disk space until complete (state=Proving).

**Comment by huhuapop** [comment]
> What is your disk layout? Is there enough fast (NVMe, SSD) drive space available for all 3 sectors. Keep in mind that each 32-GB sector requires ~270 GB disk space until complete (state=Proving).

The disk has an 8 TB disk(4* 2T SSD combine). I consider space is enough

**Comment by jburnett** [comment]
And disks have locations attached to miner? e.g., all locations are listed in miner's storage.json.

**Comment by huhuapop** [comment]
I think it has enough space with the miner.

lotus-miner storage list
13059b89-fdab-4f19-9ce2-13331ea7d092:
	[###########################################       ] 6.315 TiB/7.219 TiB 87%
	Unsealed: 0; Sealed: 179; Caches: 179; Reserved: 0 B
	Weight: 10; Use: Store
	Local: /home/omega/hdd/storage
	URL: http://192.168.1.202:2345/remote

ab55f2e1-99af-42b9-866c-d60a0e581bba:
	[#######                                           ] 1.084 TiB/7.219 TiB 15%
	Unsealed: 0; Sealed: 23; Caches: 23; Reserved: 0 B
	Weight: 10; Use: Store
	Local: /home/omega/hdd2/storage
	URL: http://192.168.1.202:2345/remote

73a90acc-329e-46cc-9a40-18e702586c40:
	[#######                                           ] 1.022 TiB/7.219 TiB 14%
	Unsealed: 1; Sealed: 1; Caches: 1; Reserved: 0 B
	Weight: 10; Use: Seal 
	URL: http://192.168.1.221:2345/remote (latency: 2.5ms)

5fe7701b-5a8d-444a-add8-bb0cc6a93df3:
	[###############                                   ] 577.9 GiB/1.79 TiB 31%
	Unsealed: 0; Sealed: 1; Caches: 1; Reserved: 0 B
	Weight: 10; Use: Seal 
	Local: /home/omega/ssd2/seal
	URL: http://192.168.1.202:2345/remote

9a5e3365-bb3a-49a0-ae3e-25e536f4fbdd:
	[#################                                 ] 637.7 GiB/1.79 TiB 34%
	Unsealed: 6; Sealed: 6; Caches: 5; Reserved: 0 B
	Weight: 110; Use: Seal 
	Local: /home/omega/ssd/seal
	URL: http://192.168.1.202:2345/remote

ca86552c-9d0a-44c5-858c-bba0fc70b861:
	[##############                                    ] 545.9 GiB/1.79 TiB 29%
	Unsealed: 0; Sealed: 0; Caches: 1; Reserved: 0 B
	Weight: 10; Use: Seal 
	Local: /home/omega/nvme/seal
	URL: http://192.168.1.202:2345/remote

dce652ba-4cf5-4c8a-800e-6b8fe83b4a92:
	[###############                                   ] 577.9 GiB/1.79 TiB 31%
	Unsealed: 0; Sealed: 1; Caches: 1; Reserved: 0 B
	Weight: 10; Use: Seal 
	Local: /home/omega/ssd1/seal
	URL: http://192.168.1.202:2345/remote

**Comment by jburnett** [comment]
Looks like you have plenty of sealing space free.  I thought miner might not see enough resources.  Did you find anything interesting in sealing sched-diag?

I noticed your config does not allow worker to AddPiece. Are you expecting the miner to do that?  If so, could the low parallel fetch be interfering in some way?

**Comment by huhuapop** [comment]
> Looks like you have plenty of sealing space free. I thought miner might not see enough resources. Did you find anything interesting in sealing sched-diag?
> 
> I noticed your config does not allow worker to AddPiece. Are you expecting the miner to do that? If so, could the low parallel fetch be interfering in some way?

The miner will Add Piece and assign the task to worker. The parallel is 10. 

[Storage]
  ParallelFetchLimit = 10
  AllowAddPiece = true
  AllowPreCommit1 = false
  AllowPreCommit2 = false
  AllowCommit = false
  AllowUnseal = true

**Comment by jburnett** [comment]
The lotus-worker command line param shown is `--parallel-fetch-limit=2` Doesn't that limit worker to 2? 

More importantly, were you able to get past the problems?  Please share your solution if you did.

**Comment by huhuapop** [comment]
> The lotus-worker command line param shown is `--parallel-fetch-limit=2` Doesn't that limit worker to 2?
> 
> More importantly, were you able to get past the problems? Please share your solution if you did.

I test for a long time and the param "--parallel-fetch-limit=2" will not limit the jobs working on the server. Event  `--parallel-fetch-limit=1', the number of jobs can be more than one. 

I have solved this issue.  The issue is because I remove the sector files in the unsealed and sealed folder by mistake. 

1. Recreate the sector id and file on the unsealed and sealed folder:
touch s-t0xxxxxx-100

2.Restart the worker
3. After the status of this sector changes to PreCommit1, terminal this job 
   lotus-miner sealing abort <JobId>
   Jobid is different from SectorId. Please check it on command: lotus-miner sealing jobs 
4. Remove this sector
   lotus-miner sectors remove <SectorId>
