### ISSUE TITLE
[BUG] can't acquire read lock 

### ISSUE THREAD

**Issue by leaderz5201** [filecoin-project/lotus#6779]
**Describe the bug**
有些扇区显示can't acquire read lock  ， 同时 find又发现数据没有移动到存储上。这种情况有什么办法恢复，还是只能终止扇区损失质押。
Some sector show "can't acquire read lock" , meanwhile find command show data didnot move to storage。is there some way to recover this kindof sector or i have to terminal it .

root@172-22-36-53:~# lotus-miner proving check 2|grep bad
2         0          2884    bad (can't acquire read lock)
2         0          2891    bad (can't acquire read lock)

root@172-22-36-53:~# lotus-miner storage find 2884
In a0f93d36-b3bf-489b-b591-073f99a2269b (Sealed, Cache)
	Sealing: true; Storage: false
	Remote
	URL: http://172.22.37.52:3456/remote/sealed/s-t01095915-2884
In bb8eb961-7069-4171-8dca-6e1c6467c020 (Unsealed)
	Sealing: true; Storage: false
	Remote
	URL: http://172.22.37.76:3456/remote/unsealed/s-t01095915-2884

**Comment by Reiers** [comment]
Hi @leaderz5201 

Thanks for the report.

Looks like the something happen during sealing, a miner/worker restart that interfered with Finalize step and resulted in the sector data where corrupted. 

> is there some way to recover?
- You can try this community tool to try to save them: https://github.com/froghub-io/filecoin-sealer-recover
_(Its not from the Lotus team, use at own risk)_

Remember to keep [Lotus up to date](https://github.com/filecoin-project/lotus/tags) - to get the latest improvements and bug fixes.

Closing issue ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you!
