### ISSUE TITLE
Chain dashboard is not receiving any data

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#678]
https://lotus-metrics.kittyhawk.wtf/d/z6FtI92Zz/chain?orgId=1&refresh=30s&from=now-30m&to=now&kiosk is showing no data for all of the panels.

**Comment by magik6k** [comment]
This is caused by the devnet being dead - there was an attach which caused most miners to drop, and we didn't restart the devnet yet (we fixed the issues, but want election post in before restarting it)
