### ISSUE TITLE
[Mining Issue]lotus sync

### ISSUE THREAD

**Issue by Motto-chen** [filecoin-project/lotus#6790]
Does lotus have to wait for the block to be highly synchronized before it can operate the following process? How long does it take to synchronize

**Comment by dayou5168** [comment]
Yes. lotus need fully synchronized. you can download and import snapshot of lotus node to accelerate the sync. maybe several hours depend on the hardware configuration.

**Comment by Motto-chen** [comment]
> 是的。莲花需要完全同步。您可以下载并导入 lotus 节点的快照以加速同步。也许几个小时取决于硬件配置。

已经采用了建议，现在解决问题了，谢谢你

**Comment by Reiers** [comment]
https://lotus.filecoin.io/docs/set-up/chain-management/

If you are still experiencing problems - ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Closing lotus issue ticket.
