### ISSUE TITLE
[Mining Issue] I can't get Lotus Chain once every 5 days.

### ISSUE THREAD

**Issue by scvpark** [filecoin-project/lotus#6791]
**Describe the problem**
I can't get Lotus Chain once every 5 days.

My miner is not synced once every 5 days between 13:00 and 13:30 UTC.
Even if i try lotus sync wait,  i will not receive sync.

The work I did to solve the problem.
- Remove .lotus/datastore/chain and received a new chain.
- I transferred the main server to another equipment.
- Checked the network. All communication with the other external Internet works smoothly.

**Version**
lotus version 1.10.0+mainnet+git.764fa9dae
go version go1.16.4 linux/amd64

**Setup**
export PATH=$PATH:$HOME/.cargo/bin:/usr/local/go/bin
export LOTUS_MINER_PATH=/usr/seal/lotusminer
export LOTUS_PATH=/usr/seal/.lotus
export FIL_PROOFS_PARAMETER_CACHE=/usr/seal/filecoin-parameters
export FIL_PROOFS_PARENT_CACHE=/usr/seal/filecoin-parents
export CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
export CGO_CFLAGS="-D__BLST_PORTABLE__"
export RUSTFLAGS="-C target-cpu=native -g"
export FFI_BUILD_FROM_SOURCE=1
export BELLMAN_CUSTOM_GPU="Geforce RTX 3090:10496"
export FIL_PROOFS_MAXIMIZE_CACHING=1
export FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1
export FIL_PROOFS_USE_GPU_TREE_BUILDER=1
export FIL_PROOFS_USE_MULTICORE_SDR=1

lotus limits
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             1030084              1030084              processes 
Max open files            1048576              1048576              files     
Max locked memory         67108864             67108864             bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       1030084              1030084              signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    

ulimit -n
1048576

ulimit -Hn
1048576

**Comment by dayou5168** [comment]
Can you run my scirpt. and let me see the output.
https://github.com/dayou5168/fscript/blob/master/check-env.sh

**Comment by dayou5168** [comment]
I think we shouldn't disscuss this problem  here. it's not issue. can we move to slack.

**Comment by scvpark** [comment]
I run check-env.sh.
Check if you are using solid state drive
cat: /sys/block/md/queue/rotational: No such file or directory
./check-env.sh: line 27: [: : integer expression expected
looks normal. you are using solid state drive
./check-env.sh: line 35: [: 2.8: integer expression expected
You have about 2.8 gigabytes of space
cpu support sha extension

I installed OS : SSD lotus : NVME
/dev/sda3       914G   11G  857G   2% /
/dev/md0        3.6T  646G  2.8T  19% /usr/seal
