### ISSUE TITLE
lotus net peers failed (failed to get api endpoint)

### ISSUE THREAD

**Issue by NewMai** [filecoin-project/lotus#680]
When I execute command: 
`lotus net peers`
or
`lotus sync wait`
It toll me the following error:

2019-11-27T18:33:13.758+0800	WARN	main	lotus/main.go:72	failed to get api endpoint: API not running (no endpoint)

I used the lotus in the local private network, and i want to use the port-mapping technology to run a miner in my private network. How can I do?
(Mapping which port to the internet?)

**Comment by whyrusleeping** [comment]
That error means your lotus daemon was not running. Please check that it is and try again. Reopen the issue if the problem persists

**Comment by mzq1213** [comment]
> That error means your lotus daemon was not running. Please check that it is and try again. Reopen the issue if the problem persists

how to check whether daemon is up for running?
