### ISSUE TITLE
Retrieval Market Extraction And Spec Compliance Plan

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#681]
Hi Lotus Team,

We recently landed retrieval markets in the spec: https://filecoin-project.github.io/specs/#systems__filecoin_markets__retrieval_market

While it is largely based of the Lotus implementation of retrieval, it differs in some important ways, in order to support arbitrary DAGs as opposed to just UnixFS. 

Given that the impending testnet launch, I want to make the process of extracting the retrieval market and bringing it in line with spec as painless as possible for you all. With that in mind, I want to lay out my plan ahead of time:

- [ ] Preparing the retrieval market for extraction from Lotus. Includes:
    - bringing retrieval market client and provider top level interfaces in line with spec (without actually changing the implementation), so that the internals can change without affecting how you interact with the module.
    - creating an abstraction over direct calls to the lotus node so that it can be used by go-filecoin as well
    - eliminating use of shared types from lotus inside the implementation
    - would involve 1 or more PRs. Would appreciate guidance on whether you prefer one large PR or several small ones

- [ ] Bringing the module in line with spec V0
   - This would happen simultaneous will implementing CAR files on the storage market side
   - Some thorny issues to figure out -- mostly around discovery once payloadCID != pieceCID

- [ ] Extracting To A Seperate Repo (~12/16)

- [ ] Evolving implementation To V1 to support arbitrary selectors

The hope is in all of this, you would not have to write any new code and everything I do would be a drop in replacement for existing functionality.

**Comment by hannahhoward** [comment]
One side note: I think the first two steps could be reversed if you prefer. But would need to be simultaneous with adding CAR files on the storage side.

**Comment by whyrusleeping** [comment]
Yeah, I think it makes the most sense to do step 2 first. Making the change after extraction will be much more difficult.

**Comment by hannahhoward** [comment]
i appreciate the feedback. if there is anything that seems particularly off here as well let me know.
