### ISSUE TITLE
Do you want to use GPU 2080ti for Filecoin? 

### ISSUE THREAD

**Issue by llb890427** [filecoin-project/lotus#683]
Is the recently announced solution using GPU in Lotus? Will Filecoin use this scheme in the open test on December 11th? Will Filecoin use GPU2080ti as a solution in the future?

**Comment by Lindensys** [comment]
2080ti may be too luxury..  i think the team is still testing and the too-high-performance gpu may not required, you can check the discussions in Slack.

**Comment by llb890427** [comment]
> 2080ti may be too luxury.. i think the team is still testing and the too-high-performance gpu may not required, you can check the discussions in Slack.

Is there a link?

**Comment by whyrusleeping** [comment]
Having a nice fast card won't hurt, but we're working hard to make cheaper cards also work. My 2080 (not ti) should be good enough. The CPU you have also affects it pretty heavily, so both are important.

**Comment by llb890427** [comment]
> Having a nice fast card won't hurt, but we're working hard to make cheaper cards also work. My 2080 (not ti) should be good enough. The CPU you have also affects it pretty heavily, so both are important.

So is the next release GPU in FileCoin or in Lotus?

**Comment by whyrusleeping** [comment]
closing as this isnt really an issue
