### ISSUE TITLE
More User control over P1/P2 worker process assignment

### ISSUE THREAD

**Issue by dayou5168** [filecoin-project/lotus#6838]
**Is your feature request related to a problem? Please describe.**
In the current version, if a miner has multiple workers who can do PC1 and PC2 at the same time, then when a worker finishes PC1, the intermediate data will be transferred to another machine to continue to do PC2. This process is uncontrollable. More than 500g data in 32g sector will be transmitted through the intranet, which takes too long and increases the initial equipment cost of small miners.

**Describe the solution you'd like**
we can manually control a worker to finish PC1 and PC2 of a sector, or set the affinity of PC1 and PC2 process, so that they can finish their work more easily on one machine than on two separate machines.

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by jburnett** [comment]
I like the general idea.  Several times I have wished scheduler would prioritize the location of sealing data in to account.  IOW, given two nodes capable of PC2, chose the one which already has the necessary data.

That said, I can imagine several complicating areas: GPU type & count, network speed, sealing storage weights, resources. For example,
- If GPU is already busy w/PC2 or C2, would it be better to schedule to a separate node w/o GPU sealing in process?
- Faster networks impose less time impact on sealing.  If network is 10 Gb, is it better to schedule PC2 locally later?
- Should sealing storage weights be used, ignored, something else?
- If local resources (CPU, RAM, etc.) are heavily used, and other node's are not, is it still desirable to keep it local?

So...it's complicated.  Every time I consider these issues I end up thinking about a cost-based scheduler, similar to query engine in a database system.

**Comment by dayou5168** [comment]
Scheduling is indeed a complex matter. I don't think we need to make major changes to the scheduling for the time being. We just need to optimize it so that miners can control part of the scheduling process,

**Comment by iversonpuppets** [comment]
More ideas in this discussion
https://github.com/filecoin-project/lotus/discussions/3498

> Quote from patrick:
> - auto (as is now)
> - manual (fully manually scheduled)
> - semi-auto (manual override possible)

**Comment by iversonpuppets** [comment]
**auto (as is now)**
- current problem is the transfer, random workers selection

**manual (fully manually scheduled)**
- manually assign workers, make local P1, P2, C1, C2 sealing possible before finalizing.
- custom policy/configuration scheduler like setting max-mem resources
- multiple workers in same machine better corresponding with each other

semi-auto (manual override possible)
- through api or command to appoint tasks to workers

**Comment by iversonpuppets** [comment]
- [ ] view
- [ ] consider
- [ ] implement
- [ ] testing

**Comment by rjan90** [comment]
Hey!

Thanks for all the feedback on this issue / feature request. 😄 But I´m closing this issue now as Lotus supports [Sector storage groups](https://lotus.filecoin.io/storage-providers/seal-workers/seal-workers/#sector-storage-groups) to better control where the data moves between wokers/groups.

I see that other features where discussed briefly, but please make seperate feature request if for those, if they are still wanted.

Thanks again!
