### ISSUE TITLE
when change owner address to multisig address, using command: ./lotus-miner actor .an error occurred.

### ISSUE THREAD

**Issue by Reskorey** [filecoin-project/lotus#6845]
### Checklist

- [ ] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [ ] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [ ] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=hint%2Fneeds-triaging&template=feature_request.yaml) instead.
- [ ] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=hint%2Fneeds-triaging&template=enhancement.yaml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [ ] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

Other

### Lotus Version

Daemon:  1.11.0+2k+git.283793f94+api1.3.0
Local: lotus version 1.11.0+mainnet+git.283793f94

### Describe the Bug

```bash
afer changing owner address to mutlitsig address, using command './lotus-miner actor control list',an error occurred: "owner	f01004: error getting account key: failed to get account actor state for t01004: unknown actor code bafkqadtgnfwc6njpnv2wy5djonuwo"
```

### Logging Information

error image:
![image](https://user-images.githubusercontent.com/43715382/126766004-fb3bed19-205b-47e9-b565-001fa7f4857e.png)

### Repo Steps

```bash
1.changing owner address to multisig address
2.run './lotus-miner actor control list' 
3.see an error: "owner	f01004: error getting account key: failed to get account actor state for t01004: unknown actor code bafkqadtgnfwc6njpnv2wy5djonuwo"
```

**Comment by dayou5168** [comment]
Test in nerpa network. same err
Daemon:  1.11.1-dev+git.19048e6a9+api1.2.0
Local: lotus-miner version 1.11.1-dev+git.19048e6a9

**Comment by rjan90** [comment]
Closing this issue, since this has been fixed in https://github.com/filecoin-project/lotus/pull/9072
