### ISSUE TITLE
copied different amount than expected: 65536 != 4161536

### ISSUE THREAD

**Issue by amsandant** [filecoin-project/lotus#6846]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=hint%2Fneeds-triaging&template=feature_request.yaml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=hint%2Fneeds-triaging&template=enhancement.yaml) instead.
- [x] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus miner/worker - sealing

### Lotus Version

lotus version 1.10.1+calibnet+git.d920b47e7.dirty

lotus-miner version 1.10.1+calibnet+git.d920b47e7.dirty

lotus-worker version 1.10.1+calibnet+git.d920b47e7.dirty

### Describe the Bug

```bash
Calibration
AP: ffi-wrapper ffiwrapper/ffiwrapper.go:51 copied different amount than expected: 65536 != 4161536
```

### Logging Information

ffi-wrapper ffiwrapper/ffiwrapper.go:51 copied different amount than expected: 65536 != 4161536

### Repo Steps

```bash
1. Run 'miner'
2. Run 'worker'
3. Exc 'lotus-miner sectors pledge'
4. Worker get error 'ffi-wrapper ffiwrapper/ffiwrapper.go:51 copied different amount than expected: 65536 != 4161536'
```

**Comment by jennijuju** [comment]
We will need more information - please update your lotus to the latest release, try to reproduce the issue and share more logs
