### ISSUE TITLE
error "checksum mismatch in param file" when lotus and lotus-storage-miner are started at the same time

### ISSUE THREAD

**Issue by ldoublewood** [filecoin-project/lotus#685]
if  lotus and lotus-storage-miner are started in the same (can be separated in future?) fresh machine  ,  error "checksum mismatch in param file" will always be prompted because two processes are trying read/write data from/into the same file under directory /var/tmp/filecoin-proof-parameters.

**Comment by magik6k** [comment]
Yeah, we should have a param download fslock

**Comment by deaswang** [comment]
@magik6k I can use O_RDWR(not O_RDONLY) to Open File when check file. O_RDWR should has fslock itself.

**Comment by Kubuxu** [comment]
RDWR won't cause fslock. AFAIK.

**Comment by deaswang** [comment]
@Kubuxu you are right. so I use flock to lock paramfile now.

**Comment by whyrusleeping** [comment]
@Kubuxu update here?

**Comment by jennijuju** [comment]
@Kubuxu Is this fixed?
