### ISSUE TITLE
There is no data in lotus_process_* metrics in /debug/metrics endpoint

### ISSUE THREAD

**Issue by sergey989** [filecoin-project/lotus#6850]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=hint%2Fneeds-triaging&template=feature_request.yaml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=hint%2Fneeds-triaging&template=enhancement.yaml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus daemon - chain sync

### Lotus Version

Daemon:  1.11.0+mainnet+git.283793f+api1.3.0
Local: lotus version 1.11.0+mainnet+git.283793f

### Describe the Bug

```bash
Couldn't find lotus_process_*(memory, cpu, e.t.c) metrics data after updating to v1.11
```

### Logging Information

none

### Repo Steps

```bash
1. open */debug/metrics
2. find lotus_process_*
3.
# HELP lotus_process_sys_heap Bytes of heap memory obtained from the OS
# TYPE lotus_process_sys_heap gauge
lotus_process_sys_heap 0
# HELP lotus_process_sys_memory_alloc Number of bytes given to the process to use in total
# TYPE lotus_process_sys_memory_alloc gauge
lotus_process_sys_memory_alloc 0
# HELP lotus_process_sys_stack The memory used by stack spans and OS thread stacks
# TYPE lotus_process_sys_stack gauge
lotus_process_sys_stack 0
# HELP lotus_process_sys_stack_mcache Bytes of memory obtained from the OS for mcache structures
# TYPE lotus_process_sys_stack_mcache gauge
lotus_process_sys_stack_mcache 0
# HELP lotus_process_sys_stack_mspan Bytes of memory obtained from the OS for mspan structures
# TYPE lotus_process_sys_stack_mspan gauge
lotus_process_sys_stack_mspan 0
# HELP lotus_process_total_memory_alloc Number of allocations in total
# TYPE lotus_process_total_memory_alloc gauge
lotus_process_total_memory_alloc 0
```

**Comment by Reiers** [comment]
### Hi @sergey989 

Thanks for the report. The issue is a bit outdated.

If this is a issue in current release [(v1.15.1)](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1) ?

Thanks again !
