### ISSUE TITLE
MarketListDataTransfers returns wrong TransferID

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/lotus#6855]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=hint%2Fneeds-triaging&template=feature_request.yaml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=hint%2Fneeds-triaging&template=enhancement.yaml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus JSON-RPC API

### Lotus Version

Daemon:  1.10.0+mainnet+git.764fa9dae+api1.3.0
Local: lotus version 1.10.0+mainnet+git.764fa9da

### Describe the Bug

```bash
MarketListDataTransfers returns wrongs TransferIDs seems like they are round up.

**2 examples :**

lotus-miner  data-transfers list --verbose
1627022617225456771  Ongoing  12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw  QmcHV54udLP4ca2amVnCVfvC7Nz7Q2Lphemq9fEysKZzWe                  N           0B           {"Proposal":{"/":"bafyreiguhc2qxzjsd6lok7uoagdp4hol3tkh2tsvvff5czjyddjug7pht4"}}  
1627059635363216947  Ongoing  12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw  bafybeidvuw6x54jmw57e5uku55bvourxisiqkk5o32anjtbrv4j6fnoeru     N           0B           {"Proposal":{"/":"bafyreigeghivq7wfr6axdor42grv5gu6yyqv4m6wqzyezz2fksqoqg5uyq"}}   

result of MarketListDataTransfers : 
 
    {
      "TransferID": 1627022617225457000,
      "Status": 1,
      "BaseCID": {
        "/": "QmcHV54udLP4ca2amVnCVfvC7Nz7Q2Lphemq9fEysKZzWe"
      },
      "IsInitiator": false,
      "IsSender": false,
      "Voucher": "{\"Proposal\":{\"/\":\"bafyreiguhc2qxzjsd6lok7uoagdp4hol3tkh2tsvvff5czjyddjug7pht4\"}}",
      "Message": "",
      "OtherPeer": "12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw",
      "Transferred": 0,
      "Stages": null
    },
    {
      "TransferID": 1627059635363217000,
      "Status": 1,
      "BaseCID": {
        "/": "bafybeidvuw6x54jmw57e5uku55bvourxisiqkk5o32anjtbrv4j6fnoeru"
      },
      "IsInitiator": false,
      "IsSender": false,
      "Voucher": "{\"Proposal\":{\"/\":\"bafyreigeghivq7wfr6axdor42grv5gu6yyqv4m6wqzyezz2fksqoqg5uyq\"}}",
      "Message": "",
      "OtherPeer": "12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw",
      "Transferred": 0,
      "Stages": null
    },



```
```


### Logging Information

see above

### Repo Steps

```bash
1. Run '...'
2. Do '...'
3. See error '...'
...
```

**Comment by hannahhoward** [comment]
how is the second output being generated? curl? is this from javascript code?

**Comment by hannahhoward** [comment]
asking cause:

strong bet this is a serialization error due to javascript or jq being involved. all javascript numbers are IEEE 754 double precision floating points. there are several 64-bit integers (the default golang int type on 64-bit machines) that you cannot represent in javascript. (large numbers with high precision in particular--- like these transfer ids)

**Comment by s0nik42** [comment]
@hannahhoward 
its generated with  jq and I've got the same problem with grafana (js).
but I confirm the API return the proper  information. 

Thank you for your insights
