### ISSUE TITLE
Integrate the new proof patch to v1.11.1

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6873]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Proof has a patch for fixing https://github.com/filecoin-project/rust-fil-proofs/issues/1479 , would be nice to get in lotus asap 

### Describe the solution you'd like

Update the proof dep once ready

**Comment by cryptonemo** [comment]
Proofs`v8.0.3` is released!

FFI PR coming shortly.

**Comment by cryptonemo** [comment]
https://github.com/filecoin-project/filecoin-ffi/pull/191

If and when CI is green, merge at will!
