### ISSUE TITLE
Update to gfm v1.6.0

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6876]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Fancy improvements and new features in gfm v1.6.0 and we want them in lotus!

### Describe the solution you'd like

Update the dep of gfm v1.6.0 once it’s ready

**Comment by aarshkshah1992** [comment]
https://github.com/filecoin-project/go-fil-markets/releases/tag/v1.6.0.
