### ISSUE TITLE
Better user control over SyncWrites option of BadgerDB

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6877]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

lotus daemon - chain sync

### Improvement Suggestion

This is to more properly address the issue where  #6817 was the workaround for with splitstore,
according to @vyzo 
> The spllitstore badger uses the fsrepo options constructor, so we should be covered by this.

and @raulk suggested to implement blockstore.Sync() and sync at the transactional boundaries we care about (basically every time that we commit a tipset)

- [ ] upon resolve this ticket, we should consider revert #6817 as it may trade off reliability for performance

**Comment by raulk** [comment]
This is not so much about better control of `SyncWrites`, but it's basically this: https://github.com/filecoin-project/lotus/issues/5057
