### ISSUE TITLE
lotus-miner info doesn't work after MRA service separation

### ISSUE THREAD

**Issue by nonsense** [filecoin-project/lotus#6887]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus miner - mining and block production

### Lotus Version

$ lotus version
Daemon:  1.11.1-dev+mainnet+git.48e8f54c6+api1.3.0
Local: lotus version 1.11.1-dev+mainnet+git.48e8f54c6

`feat/replace-multistore-carv2` branch

### Describe the Bug

MRA feature allows miners to split their monolith miner node into multiple service - proving/sealing miner process, and markets process.

This creates a problem for `lotus-miner info` command - it is currently trying to fetch data from APIs that are available exclusively on one or the other process, so it will always return an error, for example:

```bash
$ LOTUS_MINER_PATH=~/lotus-miner-path ./lotus-miner info
Chain: [sync ok] [basefee 137.976 pFIL]
Miner: f0127896 (32 GiB sectors)
Power: 25.7 Ti / 8.15 Ei (0.0003%)
        Raw: 22.72 TiB / 8.149 EiB (0.0003%)
        Committed: 22.72 TiB
        Proving: 22.72 TiB
Projected average block win rate: 0.30/week (every 554h56m13s)
Projected block win with 99.9% probability every 3833h20m28s
(projections DO NOT account for future network and miner growth)

ERROR: fatal error calling 'Filecoin.MarketListIncompleteDeals': panic in rpc method 'Filecoin.MarketListIncompleteDeals': runtime error: invalid memory address or nil pointer dereference
```

or

```
$ LOTUS_MINER_PATH=~/markets-repo-location ./lotus-miner info
Chain: [sync ok] [basefee 143.99 pFIL]
ERROR: getting actor address: fatal error calling 'Filecoin.ActorAddress': panic in rpc method 'Filecoin.ActorAddress': runtime error: invalid memory address or nil pointer dereference
```

---

We should refactor `lotus-miner info` to return relevant information, depending on which repo is being targetted.
```


### Logging Information

.

### Repo Steps

_No response_

**Comment by jennijuju** [comment]
We want the fix to this to be in v1.11.1-rc2 (cc @jacobheun
