### ISSUE TITLE
fail to download the file in step "lotus-storage-miner init "

### ISSUE THREAD

**Issue by rogerlzp** [filecoin-project/lotus#689]
I tried and failed several times with the command: "lotus-storage-miner init --actor=t0560 --owner=t3 ..." 

31.09 KiB / 3.97 GiB [>-------------------------]   0.00% 75.60 KiB/s 15h16m40s2019-12-01T16:52:32.159+0800	WARN	build	build/paramfetch.go:80	checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v15-stacked-proof-of-replication-967b11bb59be11b7dc6f2b627520ba450a3aa50846dbbf886cb8b735fe25c4e7.params, 727c03b570ce88b447c0d441089ed249 != 64024e461b07c869df2463d33dd28035
 135.76 MiB / 3.97 GiB [>------------------------]   3.34% 635.80 KiB/s 1h45m18s
 962.77 MiB / 3.97 GiB [=====>-------------------]  23.71% 763.65 KiB/s 1h09m11s
 963.31 MiB / 3.97 GiB [=====>-------------------]  23.72% 763.60 KiB/s 1h09m11s
 963.92 MiB / 3.97 GiB [=====>-------------------]  23.74% 763.60 KiB/s 1h09m10s
...

019-12-01T17:52:48.502+0800	INFO	build	build/paramfetch.go:141	Fetching /var/tmp/filecoin-proof-parameters/v15-stacked-proof-of-replication-0c0b444c6f31d11c8e98003cc99a3b938db26b77a296d4253cda8945c234266d.params from https://ipfs.io/ipfs/
 37.08 MiB / 2.58 GiB [>---------------------------]   1.40% 813.12 KiB/s 54m38s
 57.92 MiB / 2.58 GiB [>---------------------------]   2.19% 835.20 KiB/s 52m36s

It failed because the file is too large to download without supporting resume breakpoint.
Maybe you can put the file into ipfs network or other way so that we can download with other tools.

Any suggestion to fix this?

Thanks,
Roger

**Comment by travisperson** [comment]
All proofs are on the IPFS network, you can find them @ https://proofs.filecoin.io/

If you have a local ipfs node, you can fetch them directly.

```
$ ipfs get /ipns/proofs.filecoin.io -o /var/tmp/filecoin-proof-parameters
```

Or pin them and point lotus to your local gateway

```
$ ipfs pin add --progress /ipns/proofs.filecoin.io
$ IPFS_GATEWAY=http://localhost:8080/ipfs/ lotus fetch-params
```

**Comment by rogerlzp** [comment]
sounds good, I will have a try, thanks very much.
