### ISSUE TITLE
'net ping [peerid]' command

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#6910]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

There is no 'net ping' command

### Describe the solution you'd like

* New `NetPing(ctx, peerid, dataSize) (Duration, error)` api using the libp2p ping protocol
* a `net ping [--count n] [--size x] [peerID]` command

**Comment by ychiaoli18** [comment]
@magik6k could you elaborate on what you mean about the size flag?

**Comment by rjan90** [comment]
Hey!

Closing this issue now, since a PR to fix this has been submitted and approved.

Thank you so much for implementing this @ychiaoli18!
