### ISSUE TITLE
New Executable for lotus-miner market pipeline

### ISSUE THREAD

**Issue by Meatball13** [filecoin-project/lotus#6922]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

Other

### Improvement Suggestion

With the move to the new Market split capability in lotus-miner it would be really good if we could have two separate executables to interact with the two separate pieces.

lotus-miner: To interact with the Mining, Sealing or SectorStorage pipelines
lotus-market: To interact with the Markets pipeline

**Comment by rjan90** [comment]
Hey @Meatball13!

Thanks for the feature request. With https://boost.filecoin.io you now have a separate executable to interact with the markets-pipeline. Separating the legacy `go-fil-markets` into a separate executable is not something that will be prioritzed so I´m closing this issue now.

Thanks again for the request 😄
