### ISSUE TITLE
Unable to complete Market initialization

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#6946]
### Checklist

- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] I **am** reporting a bug w.r.t one of the [M1 tags](https://github.com/filecoin-project/lotus/discussions/6852#discussioncomment-1043951). If not, choose another issue option [here](https://github.com/filecoin-project/lotus/issues/new/choose).
- [X] I am **not** reporting a bug around deal making. If yes, create a [M1 Bug Report For Deal Making](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fbug%2CM1-release&template=m1_bug_report_deal.yml).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.

### Lotus component

Other

### Lotus Tag and  Version

```text
m1.3.2

lotus-miner version
Daemon:  1.11.1-rc1+mainnet+git.72391cca2+api1.2.0
Local: lotus-miner version 1.11.1-rc1+mainnet+git.72391cca2
```

### Describe the Bug

After compiling new code and starting DAG Store migration, I followed the [guidance](https://docs.filecoin.io/mine/lotus/split-markets-miners/#splitting-the-lotus-miner-monolith) to initialize the markets using the command below. The process indicator reached 100% but never actually completed. I retried the same steps three times, including deleting the contents of the market_repo. Each time I also had to kill the process which seemed stuck. I am holding off on continuing the install process.

```
lotus-miner --markets-repo=/pool/markets init service --type=markets \
                                                                  --api-sealer=$APISEALER \
                                                                  --api-sector-index=$APISECTORINDEX \
                                                                  --config=~/.lotusmarket/config.toml \
                                                                  ~/lotus-backups/2021-07-29/backup.cbor
```

This is the stack trace
[stack trace lotus-miner markets init.txt](https://github.com/filecoin-project/lotus/files/6904702/stack.trace.lotus-miner.markets.init.txt)

### Logging Information

```text
No logs related to this install issue
```

### Repo Steps

1. See command above
2. Process stuck
...

**Comment by jennijuju** [comment]
The backup file size was 2.6 Gb with ~ 2500 deals

**Comment by raulk** [comment]
@jennijuju what's the status of this?

**Comment by jennijuju** [comment]
> @jennijuju what's the status of this?
> @stuberman have you already migrated?

We will know in the next few hours! @stuberman lets try again with stage IV - coming in 30 min!

**Comment by stuberman** [comment]
I will be available in 40 minutes - see my calendar!

**Comment by stuberman** [comment]
Running m1.3.5 this problem did not reoccur.
