### ISSUE TITLE
Make it clear that Ledger accounts cannot be used for client commands

### ISSUE THREAD

**Issue by parkan** [filecoin-project/lotus#6960]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

lotus client

### Improvement Suggestion

The [Ledger documentation](https://docs.filecoin.io/get-started/lotus/ledger/#setup-your-ledger-device) currently does not make it clear that the hardware device can NOT be used for any deal-making functionality, which appears to be the case based on my attempts.

Attempting to set a ledger wallet as default produces a confusing error:

```
lotus wallet set-default f16fw44ez2vngkzrsaagpxpadgzem5xudmrm5d2qy
ERROR: opening key 'wallet-f16fw44ez2vngkzrsaagpxpadgzem5xudmrm5d2qy': key info not found
```

The only way to get a useful error (`ERROR: failed to start deal: signing deal proposal failed: ledger can only sign chain messages`) is to pass the `--from` parameter to `lotus client deal`, which is also undocumented and only works preceding the positional arguments.

My suggestion would be to update the introductory text in the ledger guide:

~~Lotus supports using a Ledger hardware wallet as a backend for FIL transfers.~~ → `Lotus supports using a Ledger hardware wallet for FIL transfers **ONLY**. Accounts backed by a Ledger cannot make deals or interact with miners. Do not send DataCap to these accounts.`

Of course the preferred solution would be to add support for signing offline messages :dog:

**Comment by parkan** [comment]
everyone seems to be surprised by this so I am happy to be wrong! but I'm not seeing a way to do it

**Comment by parkan** [comment]
oh, one further confusing thing is that I was able to view a "private key" using `./lotus-shed ledger key-info "m/44'/461'/0'/0/0"` and even tried to import it using `lotus wallet import` but that command seems to expect a different format

```
{"Type":"secp256k1-ledger","PrivateKey":"e..."}
```


this is confusing because dumping the seed or the derived keys from a ledger should not be possible (without forensic tools at least) so I don't know what this value is

**Comment by parkan** [comment]
ok so it looks like ledger is restricted to signing `MTChainMsg` and not `MTDealProposal`, so it's probably more accurate to say ledger wallets cannot *propose* deals, but other on-chain deal-related messages would still work

I'm not sure what the motivation is -- both are going to be cbor blobs and I don't see why the [signing code](https://github.com/filecoin-project/lotus/blob/eede19fb0b2d3a7726f35392d0028b9e2ff56ce9/chain/wallet/ledger/ledger.go#L41) couldn't handle deal proposals

you can also use ethereum's message_sign with ledger in offline contexts, so at least on a high level it's not an unsound idea -- no obvious issues like replays or chosen plaintext attacks are immediately apparent

one possibility I can see is that maybe MTBlock block headers were meant to be excluded as it would not be practical to sign those interactively, and deal proposals got trampled?

**Comment by Beanow** [comment]
Indeed this would have been good to know before adding my DataCap to a ledger backed address.

> both are going to be cbor blobs and I don't see why the signing code couldn't handle deal proposals

While I don't know if this is what's actually blocking the issue, I do know Ledger apps are not supposed to do "blind signing" https://developers.ledger.com/docs/nano-app/functional-requirements/#blind-signing (not without explicit warnings anyway). For your own safety the messages are supposed to be interpreted and shown in human readable form on the Ledger display, so you can review what you're about to sign.

**Comment by rjan90** [comment]
Closing this ticket as Ledger supports this: https://github.com/Zondax/ledger-filecoin/pull/130
