### ISSUE TITLE
Unable to Run Lotus-miner Piecestore Commands With M1 Releases.

### ISSUE THREAD

**Issue by TippyFlitsUK** [filecoin-project/lotus#6964]
### Checklist

- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] I **am** reporting a bug w.r.t one of the [M1 tags](https://github.com/filecoin-project/lotus/discussions/6852#discussioncomment-1043951). If not, choose another issue option [here](https://github.com/filecoin-project/lotus/issues/new/choose).
- [X] I am **not** reporting a bug around deal making. If yes, create a [M1 Bug Report For Deal Making](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fbug%2CM1-release&template=m1_bug_report_deal.yml).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.

### Lotus component

lotus JSON-RPC API

### Lotus Tag and  Version

```text
Daemon:  1.11.1-rc1+mainnet+git.88efbfa6f+api1.2.0
Local: lotus-miner version 1.11.1-rc1+mainnet+git.88efbfa6f
```

### Describe the Bug

I am unable to run any `lotus-miner pieces` commands in the `miner` or `markets` instance.

Many thanks!!

### Logging Information

```text
lotus-miner pieces list-pieces
ERROR: fatal error calling 'Filecoin.PiecesListPieces': panic in rpc method 'Filecoin.PiecesListPieces': runtime error: invalid memory address or nil pointer dereference

lotus-miner --call-on-markets pieces list-pieces
ERROR: fatal error calling 'Filecoin.PiecesListPieces': panic in rpc method 'Filecoin.PiecesListPieces': runtime error: invalid memory address or nil pointer dereference

LOTUS_MINER_PATH=/mnt/nvme0n1/.lotusmarkets lotus-miner pieces list-pieces
ERROR: fatal error calling 'Filecoin.PiecesListPieces': panic in rpc method 'Filecoin.PiecesListPieces': runtime error: invalid memory address or nil pointer dereference
```

### Repo Steps

Run `lotus-miner pieces list-pieces` or any `pieces` command in the `miner` or `markets` instance.

## Edited by @jennijuju 
- [ ] Run an audit of all commands to proactively identify more cases like this before closing the issue.This means running all CLI commands with a segregated miner, and verifying they work.

**Comment by raulk** [comment]
This was solved in m1.3.4.
