### ISSUE TITLE
Logger config

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#6972]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Log levels need to be configured after each startup

### Describe the solution you'd like

Config for global / subsystem log levels

### Additional context

* Define new config structs in `node/config` (include in Common config)
* Consume the config in node constructor as part of common config handling code (`node/builder.go`)

**Comment by LexLuthr** [comment]
This was implemented in https://github.com/filecoin-project/lotus/pull/8283
