### ISSUE TITLE
submit window post failed

### ISSUE THREAD

**Issue by olier** [filecoin-project/lotus#6973]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus miner - proving(WindowPoSt)

### Lotus Version

```text
lotus version 1.10.1
lotus-miner version 1.10.1
```

### Describe the Bug

submit window post failed: pushing message to mpool:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).submitPost
        /root/back/lotus/storage/wdpost_run.go
  - mpool push: failed to push message: mpool message too large (68900B): message too big

### Logging Information

```text
submit window post failed: pushing message to mpool:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).submitPost
        /root/back/lotus/storage/wdpost_run.go
  - mpool push: failed to push message: mpool message too large (68900B): message too big
```

### Repo Steps

Hello, this error occurred when I submitted the message. How can I solve this problem?

![image](https://user-images.githubusercontent.com/6144637/127923282-3771e305-2f42-4f4b-80be-5b320997cd8d.png)

**Comment by jennijuju** [comment]
What’s your miner id? Can you provide the exact output of your  `lotus —version` And `lotus-miner —version` ?  And this deadline info can be helpful too
