### ISSUE TITLE
Miner deal duration longer than requested by client

### ISSUE THREAD

**Issue by parkan** [filecoin-project/lotus#6975]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus miner/market - storage deal

### Lotus Version

```text
lotus version 1.11.1-rc1+mainnet+git.193cb9134
```

### Describe the Bug

Attempting to create a deal for 540d (1555200) shows an Out-of-bounds error on the miner (1555856)

Requesting shorter durations likewise gives the wrong value on the miner, always higher but not by a constant:

1555200 -> 1555856

1554200 -> 1555843

518400 -> 519036

It seems like a padding value gets added (?) but this makes no sense as the client already rejects deal duration over > 1555200.

May be related to https://github.com/filecoin-project/lotus/issues/6959

### Logging Information

```text
relevant logs too far back now, will capture in the future
```

### Repo Steps

1. attempt to make deal for max duration `client deal --manual-piece-cid baga6ea4seaqajnnzricv2jpdvjnhu2klogyxpsuszwxxdtwcvvq5cks25mde2ky --manual-piece-size=8522825728 Qmdk4jahNe1gSRWdYS96Jmas9CD6c1Rdp8twSWkErgc6jK f022142 0 1555200`
2. Out of Bounds error on miner with actual duration shown as 1555856
3. make a deal for the min duration `client deal --manual-piece-cid baga6ea4seaqajnnzricv2jpdvjnhu2klogyxpsuszwxxdtwcvvq5cks25mde2ky --manual-piece-size=8522825728 Qmdk4jahNe1gSRWdYS96Jmas9CD6c1Rdp8twSWkErgc6jK f022142 0 518400`
4. deal succeeds but duration is wrong, 519036

**Comment by ribasushi** [comment]
@parkan yes it is exactly #6959. The UX here is pretty bad, my recommendation for now is to make deals with a duration of 535 days.

**Comment by parkan** [comment]
sounds good, closing in favor of the other issue
