### ISSUE TITLE
Rust Panic at "'failed to get gpu lock: PoisonError " in PC2 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6980]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus miner/worker - sealing

### Lotus Version

```text
lotus v1.11.0 and up
```

### Describe the Bug

Seeing rust panics in PC2 and sector stuck in SectorRetrySealPrecommit1,  a reboot of the miner/worker machine resolves the issue

### Logging Information

```text
lotus miner

{"level":"debug","ts":"2021-07-22T13:22:56.284-0700","logger":"stores","caller":"stores/local.go:117","msg":"getting disk usage of '/mnt/sealing/sealed/s-t0135078-6560': file does not exist"}
{"level":"info","ts":"2021-07-22T13:22:56.285-0700","logger":"stores","caller":"stores/remote.go:228","msg":"Fetch http://192.168.7.20:1234/remote/sealed/s-t0135078-6560 -> /mnt/sealing/sealed/fetching/s-t0135078-6560"}
{"level":"debug","ts":"2021-07-22T13:23:00.569-0700","logger":"stores","caller":"stores/local.go:117","msg":"getting disk usage of '/mnt/sealing/cache/s-t0135078-6560': file does not exist"}
{"level":"debug","ts":"2021-07-22T13:23:10.570-0700","logger":"stores","caller":"stores/local.go:117","msg":"getting disk usage of '/mnt/sealing/cache/s-t0135078-6560': file does not exist"}
{"level":"debug","ts":"2021-07-22T13:23:20.571-0700","logger":"stores","caller":"stores/local.go:117","msg":"getting disk usage of '/mnt/sealing/cache/s-t0135078-6560': file does not exist"}
{"level":"debug","ts":"2021-07-22T13:23:30.572-0700","logger":"stores","caller":"stores/local.go:117","msg":"getting disk usage of '/mnt/sealing/cache/s-t0135078-6560': file does not exist"}
{"level":"debug","ts":"2021-07-22T13:23:37.161-0700","logger":"stores","caller":"stores/util_unix.go:30","msg":"move sector data","from":"/mnt/sealing/sealed/fetching/s-t0135078-6560","to":"/mnt/sealing/sealed/s-t0135078-6560"}
{"level":"info","ts":"2021-07-22T13:23:37.164-0700","logger":"stores","caller":"stores/remote.go:338","msg":"Delete http://192.168.7.20:1234/remote/sealed/s-t0135078-6560"}
{"level":"info","ts":"2021-07-22T13:23:39.017-0700","logger":"stores","caller":"stores/remote.go:228","msg":"Fetch http://192.168.7.20:1234/remote/cache/s-t0135078-6560 -> /mnt/sealing/cache/fetching/s-t0135078-6560"}
{"level":"debug","ts":"2021-07-22T13:31:48.537-0700","logger":"stores","caller":"stores/util_unix.go:30","msg":"move sector data","from":"/mnt/sealing/cache/fetching/s-t0135078-6560","to":"/mnt/sealing/cache/s-t0135078-6560"}
{"level":"info","ts":"2021-07-22T13:31:48.542-0700","logger":"stores","caller":"stores/remote.go:338","msg":"Delete http://192.168.7.20:1234/remote/cache/s-t0135078-6560"}
{"level":"debug","ts":"2021-07-22T13:32:03.203-0700","logger":"advmgr","caller":"sector-storage/worker_local.go:137","msg":"acquired sector {{135078 6560} 8} (e:6; a:0): {{0 0}  /mnt/sealing/sealed/s-t0135078-6560 /mnt/sealing/cache/s-t0135078-6560}"}
{"level":"debug","ts":"2021-07-22T13:32:03.207-0700","logger":"advmgr","caller":"sector-storage/worker_local.go:137","msg":"acquired sector {{135078 6560} 8} (e:6; a:0): {{0 0}  /mnt/sealing/sealed/s-t0135078-6560 /mnt/sealing/cache/s-t0135078-6560}"}
{"level":"debug","ts":"2021-07-22T13:33:03.024-0700","logger":"advmgr","caller":"sector-storage/worker_local.go:137","msg":"acquired sector {{135078 6560} 8} (e:6; a:0): {{0 0}  /mnt/sealing/sealed/s-t0135078-6560 /mnt/sealing/cache/s-t0135078-6560}"}
{"level":"debug","ts":"2021-07-22T13:33:03.028-0700","logger":"advmgr","caller":"sector-storage/worker_local.go:137","msg":"acquired sector {{135078 6560} 8} (e:6; a:0): {{0 0}  /mnt/sealing/sealed/s-t0135078-6560 /mnt/sealing/cache/s-t0135078-6560}"}
```

rust proof log

```
2021-08-02T18:20:00.079 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase2
2021-08-02T18:20:00.079 INFO storage_proofs_porep::stacked::vanilla::proof > Building trees [1048576 descriptors max available]
2021-08-02T18:20:00.079 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the GPU
2021-08-02T18:20:00.079 INFO storage_proofs_porep::stacked::vanilla::proof > Building column hashes
thread '<unnamed>' panicked at 'failed to get gpu lock: PoisonError { .. }', /home//.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-8.0.3/src/stacked/vanilla/proof.rs:589:53
thread '<unnamed>' panicked at 'failed to receive base_data, tree_data for tree_c: RecvError', /home//.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-8.0.3/src/stacked/vanilla/proof.rs:641:26
thread '<unnamed>' panicked at 'failed to send columns: SendError { .. }', /home//.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-8.0.3/src/stacked/vanilla/proof.rs:584:34
```
```


### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by jennijuju** [comment]
from @cryptonemo 

>  Usually the GPU runs out of RAM or something like that and then has that error.  We haven't found out why it happens for some people and not others, and there are several issues open in proofs related to it

therefore, currently this iissue is blocked by a fix in proof.

**Comment by cryptonemo** [comment]
I believe the following issues are all the same/related errors:

https://github.com/filecoin-project/rust-fil-proofs/issues/1472
https://github.com/filecoin-project/rust-fil-proofs/issues/1476
https://github.com/filecoin-project/rust-fil-proofs/issues/1478

We don't have concrete information on why it's happening in either case, but it's safe to say there's a GPU issue (out of RAM or resources) and a lock can't be released because the GPU is in a bad state (even if the lock is released, the hardware is not in a state that proofs can use afterward).  A hardware reset is the current workaround, or disabling the GPU if it's 100% consistent on each run (this appears to never be the case).

Suspected issues are driver version, kernel version, GPU hardware failure, etc.  GPU RAM Monitoring is encouraged, as we may be able to line-up timestamps on what was happening at the time of the failure (i.e. X amount of RAM is used, and Y amount of RAM is needed for some other step).

**Comment by cryptonemo** [comment]
The version `lotus v1.11.0 and up` for this is not related, as it's been happening for some time for some miners.  Trying to narrow down specifically why has been difficult.

**Comment by magik6k** [comment]
So one of my workers (2080ti, Ubuntu (Desktop version)) was hit by this, and I tried a bunch of things, roughly in this order if I remember correctly:
* Restart worker
  * didn't help
* Reboot the machine
  * didn't help
* Upgrade and reboot the machine
  * didn't help
* Downgrade nvidia drivers to 450.x, reboot
  * didn't help
* Drop `.nv`/`.rust-fil-proofs`
  * didn't help

Then I've noticed that on miner startup I'm getting messages like `[..] /dev/dri/renderD128 [..] Permission denied`, so I ran `sudo usermod -a -G render [the user]`, then reboot. (I got the group name from `ls -l /dev/dri/renderD*`)

That made things work.

(potentially worth noting, first run after the reboot was run with `FIL_PROOFS_USE_GPU_TREE_BUILDER` unset, only `FIL_PROOFS_USE_GPU_COLUMN_BUILDER` was set to 1, not sure if that matters / was what actually fixed the issue)

**Comment by cryptonemo** [comment]
Interesting, I'll cross post and see if it helps others.

I'd argue the 'narrowing it down' part is largely due to missing logs, as even that kind of log (permission denied) on startup is useful to know about.  Thanks!

**Comment by noch3** [comment]
FYI: Even with `FIL_PROOFS_GPU_TREE_BUILDER=1` I still had to add the user to `render`.

**Comment by Shekelme** [comment]
Even after I have added the user to `render` group, I still see these errors from time to time. Now only one `lotus-working` is running per each GPU.

```
2021-08-28T21:15:37.399 INFO filcrypto::proofs::api > seal_pre_commit_phase2: start
2021-08-28T21:15:37.399 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:start
2021-08-28T21:15:37.399 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:finish
2021-08-28T21:15:37.399 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:start
2021-08-28T21:15:37.399 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase2
2021-08-28T21:15:37.399 INFO storage_proofs_porep::stacked::vanilla::proof > Building trees [1048576 descriptors max available]
2021-08-28T21:15:37.399 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the GPU
2021-08-28T21:15:37.399 INFO storage_proofs_porep::stacked::vanilla::proof > Building column hashes
thread '<unnamed>' panicked at 'failed to get gpu lock: PoisonError { .. }', /home/admfc/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-8.0.3/src/stacked/vanilla/proof.rs:589:53
stack backtrace:
   0:          0x22c9000 - std::backtrace_rs::backtrace::libunwind::trace::hdcf4f90f85129e83
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:          0x22c9000 - std::backtrace_rs::backtrace::trace_unsynchronized::h2669e30cb82f6732
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
.......
```
etc.

**Comment by Shekelme** [comment]
And even with `FIL_PROOFS_USE_GPU_TREE_BUILDER` unset (with host reboot) I see in worker's log that
`2021-09-23T15:42:28.440 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the GPU`

**Comment by cryptonemo** [comment]
> And even with `FIL_PROOFS_USE_GPU_TREE_BUILDER` unset (with host reboot) I see in worker's log that
> `2021-09-23T15:42:28.440 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the GPU`

Tree C is built with the Column Builder, not the Tree Builder

**Comment by arajasek** [comment]
Looks like we have 3 open issues in rust-fil-proofs for this, I think this can be closed.
