### ISSUE TITLE
Calling lotus-miner backup twice with the same output path corrupts the backup file

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/lotus#7028]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus miner - mining and block production

### Lotus Version

```text
none
```

### Describe the Bug

Calling lotus-miner backup twice with the same output path corrupts the backup file

### Logging Information

```text
none
```

### Repo Steps

1. lotus-miner backup /tmp/backup.cbor
2. lotus-miner backup /tmp/backup.cbor

Restoring from /tmp/backup.cbor fails after the second time backup is called with the same output file.

Suggested solution:
`lotus-miner backup` should remove any existing backup file before creating a new one.

See https://github.com/filecoin-project/lotus/pull/6978 for details.

**Comment by raulk** [comment]
It's a tiny bit problematic if the thing that's supposed to save you from a disaster ends up causing a problem in the first place.

This should refuse to do anything, unless a `--force` flag is passed (in which case it should overwrite the backup).
