### ISSUE TITLE
Separate Max SimultaneousTransfers configuration for storage and retrieval deals

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7031]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Currently, SimultaneousTransfers apply for all deals, storage providers can benefit from the separate configuration for storage and retrieval deals so they have more control over their service.

### Describe the solution you'd like

Separate Max SimultaneousTransfers configuration for storage and retrieval deals

**Comment by rjan90** [comment]
Storage Providers can get a lot of deals from one client (i.e Esturay) simultaneously, that can/will stay in a transferring state for a long time. If the Storage Provider then has a low/normal `MaxSimultaneousTransfers=20`, and the amount of storage-deals from that client are equal to this, another client (i.e web3.storage) could potentially be blocked from retrieving a file they have previously stored with the storage provider earlier.

Separating this into a configuration for both storage-deals and for retrieval-deals will allow the storage provider to always serve retrievals in a situation where they have a lot of storage-deals transferring.

**Comment by neondragon** [comment]
This makes sense to me. It increases flexibility and has no significant disadvantage that I can think of.

**Comment by jennijuju** [comment]
duplicated with #7030
