### ISSUE TITLE
Missed window post 2 days in a row on 1.11.1 rc2.  Miner never sent declared faults recovered messages 

### ISSUE THREAD

**Issue by Byeager1** [filecoin-project/lotus#7034]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus miner - proving(WindowPoSt)

### Lotus Version

```text
Daemon:  1.11.1-rc2+mainnet+git.40449f1cc+api1.3.1
Local: lotus version 1.11.1-rc2+mainnet+git.40449f1cc
```

### Describe the Bug

Had normal pledging operations / online deal making and on August 7th & August 8th, my miner never submitted window post messages.  Lost power and on the 8th, miner never attempted to send declared faults recovered messages.  Reverted back to 1.11.0 and miner was able to declared faults recovered.  

### Logging Information

```text
No relevant logs to explain the issue.  Ran hardware tests and found no issues.
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by Reiers** [comment]
Hi @Byeager1 

Thanks for the report. Sounds like the problem lies elsewhere. 
Please upgrade Lotus: https://github.com/filecoin-project/lotus/releases/tag/v1.13.1

Closing ticket for now.

If you are still experiencing problems, open a new ticket or ask in our Discussions [forum](<link>).
