### ISSUE TITLE
Add documentation for how to read lotus journal 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7040]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

lotus miner - proving(WindowPoSt)

### Improvement Suggestion

Miners sometimes are missing wdpost or missing fault declaration and the miner log doest have any signs to indicate what happened. Would be nice to have logs to indicate the certain process has started for example, `checksectors`, `checkprovable` and so on to help troubleshooting what went wrong.

**Comment by raulk** [comment]
This exact information is already printed in the journal.

**Comment by lanzafame** [comment]
> This exact information is already printed in the journal.

The journal is undocumented, so that is probably the actual issue here.

**Comment by rjan90** [comment]
Hey!

Closing the issue as the fix has been merged.
