### ISSUE TITLE
lotus-miner storage-deals set-ask  cannot set a size larger than the sealed sector

### ISSUE THREAD

**Issue by wjqxmlsb** [filecoin-project/lotus#7041]
### Checklist

- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] I **am** reporting a bug w.r.t one of the [M1 tags](https://github.com/filecoin-project/lotus/discussions/6852#discussioncomment-1043951). If not, choose another issue option [here](https://github.com/filecoin-project/lotus/issues/new/choose).
- [X] I am **not** reporting a bug around deal making. If yes, create a [M1 Bug Report For Deal Making](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fbug%2CM1-release&template=m1_bug_report_deal.yml).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.

### Lotus component

lotus miner/worker - sealing

### Lotus Tag and  Version

```text
lotus: 
Daemon:  1.11.1-m1.3.5+mainnet+git.3ff8e256b+api1.3.1
Local: lotus version 1.11.2-dev+mainnet+git.9d0cc2c9d
lotus-miner:
Daemon:  1.11.1-m1.3.5+mainnet+git.3ff8e256b.dirty+api1.2.0
Local: lotus-miner version 1.11.1-m1.3.5+mainnet+git.3ff8e256b.dirty
```

### Describe the Bug

lotus-miner storage-deals set-ask  cannot set a size larger than the sealed sector

### Logging Information

```text
ERROR: max piece size (w/bit-padding) 50 GiB cannot exceed miner sector size 32 GiB
```

### Repo Steps

lotus-miner storage-deals set-ask --price 0.0000000001 --verified-price 0 --min-piece-size 300MiB --max-piece-size 50GiB

**Comment by ribasushi** [comment]
@wjqxmlsb this is correct behavior. What do you expect to happen differently?

**Comment by jennijuju** [comment]
The max-piece-size needs to be smaller or equal than your sector size.
