### ISSUE TITLE
Lotus Market node backup does not work

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#7044]
### Checklist

- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] I **am** reporting a bug w.r.t one of the [M1 tags](https://github.com/filecoin-project/lotus/discussions/6852#discussioncomment-1043951). If not, choose another issue option [here](https://github.com/filecoin-project/lotus/issues/new/choose).
- [X] I am **not** reporting a bug around deal making. If yes, create a [M1 Bug Report For Deal Making](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fbug%2CM1-release&template=m1_bug_report_deal.yml).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.

### Lotus component

Other

### Lotus Tag and  Version

```text
Daemon:  1.11.1-m1.3.5+mainnet+git.3ff8e256b+api1.2.0
Local: lotus-miner version 1.11.1-m1.3.5+mainnet+git.3ff8e256b
```

### Describe the Bug

When I run lotus-miner backup on dedicated market node, no file is created

`lotus-miner backup /home/stuart/lotus-backups/2021-08-12/backup.cbor`
Success

`lotus-miner --call-on-markets backup /home/stuart/lotus-backups/2021-08-12/backup.cbor`
Success
 
`ls -Alhi /home/stuart/lotus-backups/2021-08-12`
total 12K
1341252 -rw-rw-r-- 1 stuart stuart 2.0K Aug 12 13:42 config.toml
1341255 -rw-rw-r-- 1 stuart stuart  107 Aug 12 13:42 sectorstore.json
1341254 -rw-r--r-- 1 stuart stuart   72 Aug 12 13:42 storage.json

### Logging Information

```text
Not relevant
```

### Repo Steps

1.  lotus-miner backup /home/stuart/lotus-backups/2021-08-12/backup.cbor
No file output

ENV already set:
`export LOTUS_BACKUP_BASE_PATH=/home/stuart/lotus-backups`

**Comment by f8-ptrk** [comment]
```
[bsm-miner] filecoin [~]$ lotus-miner --call-on-markets backup /home/filecoin/main/backup/markets_backup.cbor
Success
[bsm-miner] filecoin [~]$ ll main/backup/
total 681692
drwxrwxr-x  2 filecoin filecoin      4096 Aug 12 14:10 ./
drwxrwxr-x 12 filecoin filecoin      4096 Aug 11 14:29 ../
-rw-r--r--  1 filecoin filecoin 144403713 Aug 12 14:10 markets_backup.cbor
```

seems to work if both miner processes are on the same box

**Comment by jennijuju** [comment]
I would consider this as a tech debt from v1.11.1 and we should get this sorted out before the v1.11.2 final release.

**Comment by neondragon** [comment]
It works with MINER_API_INFO set to the API info string for the **markets** process, so that the lotus-miner client command runs the backup API call on the markets node. --call-on-markets doesn't appear to have the same result.

**Comment by stuberman** [comment]
Below is the backup string I used that @neondragon showed me as a work around.
It seems that using the markets token in the "miner_API_info" to run a markets backup command is counter intuitive.

My global settings in the dedicated markets machine is as follows
MARKET_API_INFO=[Markets_Token]
MINER_API_INFO=[Miner_Token]
FULLNODE_API_INFO=[Daemon_Token]


`MINER_API_INFO=[Markets_Token]:/ip4/[Markets IP address]/tcp/2345/http lotus-miner backup /market/lotus-backups/2021-08-21/markets.cbor`

**Comment by nonsense** [comment]
This should be addressed as part of https://github.com/filecoin-project/lotus/issues/7124 (also a discussion about it at https://github.com/filecoin-project/lotus/discussions/7170)

**Comment by stuberman** [comment]
Moved to Boostd and backups work well
