### ISSUE TITLE
Dagstore Initialize Command Hangs With Zero Concurrency

### ISSUE THREAD

**Issue by TippyFlitsUK** [filecoin-project/lotus#7048]
### Checklist

- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] I **am** reporting a bug w.r.t one of the [M1 tags](https://github.com/filecoin-project/lotus/discussions/6852#discussioncomment-1043951). If not, choose another issue option [here](https://github.com/filecoin-project/lotus/issues/new/choose).
- [X] I am **not** reporting a bug around deal making. If yes, create a [M1 Bug Report For Deal Making](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fbug%2CM1-release&template=m1_bug_report_deal.yml).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.

### Lotus component

Other

### Lotus Tag and  Version

```text
Daemon:  1.11.1-m1.3.5+mainnet+git.3ff8e256b+api1.2.0
Local: lotus-miner version 1.11.1-m1.3.5+mainnet+git.3ff8e256b
```

### Describe the Bug

Running the `lotus-miner dagstore initialize-all --concurrency=0`  command with a concurrency of zero causes the initialize process to hang indefinitely.

There is no output produced.

### Logging Information

```text
There is no output produced.
```

### Repo Steps

Run `lotus-miner dagstore initialize-all --concurrency=0`
[goroutines.log](https://github.com/filecoin-project/lotus/files/6978123/goroutines.log)

**Comment by dirkmc** [comment]
I believe the issue is caused by this line:
https://github.com/filecoin-project/lotus/blob/68269b23fb3e92720518e0cb16a65151477af56a/node/impl/storminer.go#L645

If `MaxConcurrency` is zero, `throttle` is nil, and there is no nil check in the `select` on `throttle` lower down in the code
