### ISSUE TITLE
Lotus crashed when import deals from bidbot

### ISSUE THREAD

**Issue by vht210** [filecoin-project/lotus#7067]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus daemon - chain sync

### Lotus Version

```text
1.11.1-rc2+mainnet+git.40449f1cc
```

### Describe the Bug

- Running bidbot https://github.com/textileio/bidbot
-  Won some auction and start import some deals
Observation:
- Lotus crashed
Expected:
- Not crashed
Detail stacktrace in Logging Information

### Logging Information

```text
2021-08-14T03:45:18.059+0200	ERROR	badgerbs	v2@v2.2007.2/iterator.go:170	Invalid read: vp: {Fid:307 Len:429 Offset:767773333}
2021-08-14T03:45:18.059+0200	ERROR	badgerbs	v2@v2.2007.2/iterator.go:105	Unable to read: Key: [47 98 108 111 99 107 115 47 85 68 83 65 69 73 66 72 55 75 77 86 67 51 76 90 87 65 77 54 51 84 52 70 84 51 55 90 80 86 68 86 77 73 79 66 90 65 52 69 65 85 66 77 67 81 71 77 78 76 66 73 79 55 73 65 55 77], Version : 43273422,
				meta: 66, userMeta: 0
2021-08-14T03:45:18.059+0200	WARN	vm	vm/runtime.go:149	VM.Call failure: failed to get cbor object bafy2bzaceat7vgkrnv43agpnz6cz574x2r2weha4qocakawbidggvquhpuapw: Invalid read: Len: 422 read at:[0:699393] (FATAL):
    github.com/filecoin-project/lotus/chain/vm.(*Runtime).StoreGet
        /home/tung/git/lotus/chain/vm/runtime.go:126
2021-08-14T03:45:18.069+0200	ERROR	badgerbs	v2@v2.2007.2/iterator.go:170	Invalid read: vp: {Fid:307 Len:410 Offset:772063030}
2021-08-14T03:45:18.069+0200	ERROR	badgerbs	v2@v2.2007.2/iterator.go:170	Invalid read: vp: {Fid:307 Len:841 Offset:772085482}
2021-08-14T03:45:18.069+0200	ERROR	badgerbs	v2@v2.2007.2/iterator.go:127	Unable to read: Key: [47 98 108 111 99 107 115 47 85 68 83 65 69 73 68 87 73 86 86 84 90 71 71 65 80 52 85 70 77 76 68 54 73 73 79 90 82 82 84 65 72 81 89 83 70 73 86 90 72 52 71 86 51 72 84 79 71 82 74 79 85 55 88 85 88 85], Version : 43273509,
				meta: 66, userMeta: 0
2021-08-14T03:45:18.069+0200	ERROR	badgerbs	v2@v2.2007.2/iterator.go:170	Invalid read: vp: {Fid:307 Len:242 Offset:772125650}
panic: runtime error: slice bounds out of range [-6:]

goroutine 1431 [running]:
github.com/dgraph-io/badger/v2.(*header).Decode(0xc13880c8f0, 0x7f9ac90ec4f7, 0xeb, 0x51fa9b07, 0x7f9ac90ec4f7)
	/home/tung/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/structs.go:105 +0x179
github.com/dgraph-io/badger/v2.(*valueLog).Read(0xc001a009d0, 0xeb00000133, 0x2e0564f7, 0xc0b3c43710, 0x20302a, 0x0, 0x56173b, 0x1, 0x0, 0xc09136e888)
	/home/tung/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/value.go:1584 +0x152
github.com/dgraph-io/badger/v2.(*Item).yieldItemValue(0xc0a999f1e0, 0x203040, 0xc111fd7410, 0x2e3b140, 0xc10af483c0, 0xc0a999f1e0, 0xc11e6be000)
	/home/tung/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/iterator.go:170 +0x13e
github.com/dgraph-io/badger/v2.(*Item).ValueCopy(0xc0a999f1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tung/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/iterator.go:127 +0x187
github.com/filecoin-project/lotus/blockstore/badger.(*Blockstore).Get.func1(0xc101f13e60, 0x0, 0xc101f13e60)
	/home/tung/git/lotus/blockstore/badger/blockstore.go:607 +0x173
github.com/dgraph-io/badger/v2.(*DB).View(0xc001a00800, 0xc13880ccf8, 0x0, 0x0)
	/home/tung/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/txn.go:802 +0x95
github.com/filecoin-project/lotus/blockstore/badger.(*Blockstore).Get(0xc0004aa6c0, 0xc0d6e229f0, 0x26, 0x0, 0x0, 0x0, 0x0)
	/home/tung/git/lotus/blockstore/badger/blockstore.go:604 +0x1f8
github.com/filecoin-project/lotus/blockstore.(*idstore).Get(0xc0771a2fe0, 0xc0d6e229f0, 0x26, 0x1, 0x0, 0x3faa580, 0xc0002f76f0)
	/home/tung/git/lotus/blockstore/idstore.go:64 +0x175
github.com/filecoin-project/lotus/blockstore.(*BufferedBlockstore).Get(0xc000805880, 0xc0d6e229f0, 0x26, 0x2, 0x2, 0x0, 0x0)
	/home/tung/git/lotus/blockstore/buffered.go:126 +0x105
github.com/ipfs/go-bitswap/internal/decision.(*blockstoreManager).getBlocks.func1(0xc0d6e229f0, 0x26)
	/home/tung/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.2/internal/decision/blockstoremanager.go:95 +0x70
github.com/ipfs/go-bitswap/internal/decision.(*blockstoreManager).jobPerKey.func1()
	/home/tung/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.2/internal/decision/blockstoremanager.go:116 +0x42
github.com/ipfs/go-bitswap/internal/decision.(*blockstoreManager).worker(0xc077a558f0)
	/home/tung/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.2/internal/decision/blockstoremanager.go:49 +0x2d
github.com/ipfs/go-bitswap/internal/decision.(*blockstoreManager).start.func1(0x400ce10, 0xc077b77500)
	/home/tung/go/pkg/mod/github.com/ipfs/go-bitswap@v0.3.2/internal/decision/blockstoremanager.go:38 +0x2a
github.com/jbenet/goprocess.(*process).Go.func1(0xc008905d20, 0xc077b77500, 0xc077b77560)
	/home/tung/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:134 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
	/home/tung/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:133 +0x1fe
```

### Repo Steps

[bidbot_lotuscrash_1408.log](https://github.com/filecoin-project/lotus/files/6985914/bidbot_lotuscrash_1408.log)
[miner_lotuscrash_1408.log](https://github.com/filecoin-project/lotus/files/6985915/miner_lotuscrash_1408.log)
[fil_daemon_lotuscrash_1408_last2000lines.log](https://github.com/filecoin-project/lotus/files/6985919/fil_daemon_lotuscrash_1408_last2000lines.log)

**Comment by jennijuju** [comment]
Please report to https://github.com/textileio/bidbot

**Comment by vht210** [comment]
I am not sure it is bidbot bug. The lotus should not crash in any case I guess

**Comment by jsign** [comment]
Yeah, bidbot logs doesn't show any crash. Looks like there was some panic in Lotus due to badger.

You mentioned something related to being out of disk before all this? I've experienced that can corrupt the badger database... so, may be that the case.

**Comment by vht210** [comment]
It actually not running out of disk 100% (having around 50 Gb left) where I suspect it related to running out of space. But anyway now I am running with latest lotus 1.1.11-rc3. If it still crash, i will reopen, otherwise, let it close for now.

**Comment by jennijuju** [comment]
Please reopen if issue still

**Comment by vht210** [comment]
I dont see it crash anymore (also lotus upgraded to rc3). So close for now
