### ISSUE TITLE
Duration for block validation time sporadically increases

### ISSUE THREAD

**Issue by sergey989** [filecoin-project/lotus#7092]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus daemon - chain sync

### Lotus Version

```text
Daemon:  1.11.0+mainnet+git.283793f+api1.3.0
Local: lotus version 1.11.0+mainnet+git.283793f
```

### Describe the Bug

We see high block validation time periodically and our nodes become out of service, because they become behind network more then 10 blocks. 
Here is some screenshots. Normal duration is not more 1000ms, but we see spikes up to 250 000 ms. All resources are ok(cpu, memory, storage), types of request to nodes as usually. Do  you have any information about sophisticated things in mainnet during time on screenshots? I mean some extremally load or any other activities.
time UTC+3
![image](https://user-images.githubusercontent.com/30037350/129591094-55840d76-7445-455d-a1b6-1b7dca68f743.png)
![image](https://user-images.githubusercontent.com/30037350/129583293-2a281494-f2e5-4645-a122-417b3c38e781.png)
![image](https://user-images.githubusercontent.com/30037350/129582714-141d619e-ad9e-4c4c-aa2d-7b0cb1c141dc.png)
![image](https://user-images.githubusercontent.com/30037350/129582468-b56830fd-edaf-4865-a4af-2e3134341a52.png)

### Logging Information

```text
mplex
routedhost
net/identify
boguskey
piecestore
data_transfer_network
badgerbs
statemgr
dht
storageadapter
bitswap_network
dt-impl
peerstore/ds
test-logger
cliutil
pathresolv
quic-transport
bs:sess
repo
wallet
peerstore
relay
metrics
retrieval_network
main
messagesigner
ffiwrapper
lock
peermgr
net/conngater
markets-rtvl-reval
tracing
storagemrkt
cli
dht/RtRefreshManager
addrutil
data-transfer
evtsm
storageminer
rpcenc
bs:sprmgr
graphsync
beacon
auth
chain
reuseport-transport
discovery
basichost
markets
vm
genesis
hello
events
p2p-config
ffi-wrapper
table
system
stream-upgrader
autorelay
rpc
preseal
retrieval-discovery
p2pnode
splitstore
markets-rtvl
sectors
fullnode
graphsync_network
paramfetch
advmgr
chainxchg
sub
tarutil
conngater
ipns
actors
dht.pb
retrievaladapter
payment-channel-settler
cborrrpc
statetree
journal
backupds
incrt
miner
blankhost
dt-chanmon
eventlog
builder
types
paych
metrics-prometheus
nat
mocknet
blockservice
providers
diversityFilter
ulimit
tcp-tpt
chainstore
filestore
cmds/http
dt_graphsync
pieceio
blockstore
drand
autonat
connmgr
bitswap
retrievalmarket_impl
messagepool
modules
storagemarket_network
build
partialfile
stores
gen
storagemarket_impl
pubsub
swarm2
fsm
watchdog
disputer
wallet-ledger
providerstates
fsutil
badger
storedask
node
bs:peermgr
retrieval
amt
market_adapter
routing/record
chunk
ping
engine
cmds
```

**Comment by jennijuju** [comment]
I think this was caused by some highly loaded cron back then and we introduced some optimization.

are you still observing the long validation since then with a newer lotus?

**Comment by sergey989** [comment]
@jennijuju thank you, @mur-me should check this

**Comment by mur-me** [comment]
Hi @jennijuju, can you please share in which version you've done improvements because we still rarely observe such behavior.

For example, one of the lotus instances experienced an increase in duration for block validation last week:
![image](https://user-images.githubusercontent.com/7295623/148211842-e0b47c51-42fe-4c52-820b-18882f337824.png)
I've also added logs for 30 minutes from this timeline:
[Uploading Saved search_1403820c-ec68-4c9f-a95f-693dc9b27ef5_2022-01-05T11 57 26.499Z_a69c7b30-6e1e-11ec-92a8-23a7e81c1b59.csv…](logs)

**Comment by jennijuju** [comment]
> Hi @jennijuju, can you please share in which version you've done improvements because we still rarely observe such behavior.
> 
> For example, one of the lotus instances experienced an increase in duration for block validation last week: ![image](https://user-images.githubusercontent.com/7295623/148211842-e0b47c51-42fe-4c52-820b-18882f337824.png) I've also added logs for 30 minutes from this timeline: [Uploading Saved search_1403820c-ec68-4c9f-a95f-693dc9b27ef5_2022-01-05T11 57 26.499Z_a69c7b30-6e1e-11ec-92a8-23a7e81c1b59.csv…](logs)

I’d recommend you get on the latest lotus releases - occasional high validation time is acceptable/expected when certain onchain events spike, for example, sector terminations.

**Comment by mur-me** [comment]
We always using using the latest version of a stable release.
I'll monitor on the freshest `1.13.2` release and will let you know if I find something either strange or interesting.

**Comment by mur-me** [comment]
Hi @jennijuju, I come with good news. We are using fresh `1.13.2` for one week on our nodes. 
I think it helped with the block timing.
Nowadays, our seven nodes have a block timing of no more than **2 seconds.**
I believe you can close this issue.

![image](https://user-images.githubusercontent.com/7295623/150309178-18ef4798-032e-48cf-8db9-8f86c8fe4b2b.png)

**Comment by Reiers** [comment]
That's great ! Thanks for the feedback @mur-me !

If you are experiencing problems again, please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you !

Closing issue ticket.
