### ISSUE TITLE
How to split Mining(winning PoSt) and Sealing(Sealing and Window Post) to two instance, They are in two subsystem now.

### ISSUE THREAD

**Issue by maweis1981** [filecoin-project/lotus#7100]
https://github.com/filecoin-project/lotus/blob/518b6f1d41316117489f58893cc7e4b05cf32ca4/node/builder_miner.go#L96

How to split Mining(winning PoSt) and Sealing(Sealing and Window Post) to two instance, They are in two subsystem now.

In config.toml, we can disable/enable  “enable_mining" and "enable_sealing", But when I check the code.
I saw these

`
		If(cfg.Subsystems.EnableMining,

			If(!cfg.Subsystems.EnableSealing, Error(xerrors.Errorf("sealing can't be disabled on a mining node yet"))),

			If(!cfg.Subsystems.EnableSectorStorage, Error(xerrors.Errorf("sealing can't be disabled on a mining node yet"))),
`

> 

Does 1.11.1 version support this feature now?

**Comment by rjan90** [comment]
It is not possible to spilt it in that way yet.

```
There are only two combinations that are supported right now:

1. The markets node - a lotus-miner process responsible for handling the storage market
subsystem, and all functionality related to serve storage and retrieval deals

2. The mining/sealing/proving node - a lotus-miner process responsible for Filecoin mining,
sector storage, sealing and proving
```

https://docs.filecoin.io/mine/lotus/split-markets-miners/#configuration
