### ISSUE TITLE
Integrate new proof for v1.11.2

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7109]
Integrate new proof - v8 or v9 is pending.

**Comment by cryptonemo** [comment]
Currently tracking this PR: https://github.com/filecoin-project/filecoin-ffi/pull/192

When merged, it should be tagged.  Will update after it's merged.

**Comment by cryptonemo** [comment]
At the final hour, we've come up with an alternative instead:

https://github.com/filecoin-project/filecoin-ffi/pull/196

**Comment by cryptonemo** [comment]
@jennijuju Looks like we're ready for tagging at current `filecoin-ffi` master.  At the moment, that's: `6e901ee3dd5399f5aa3395d48f7d9540b661b944`

https://github.com/filecoin-project/filecoin-ffi/commit/6e901ee3dd5399f5aa3395d48f7d9540b661b944

This resolves the GPU support on OS X and upgrades to Proofs v9.x as originally targeted! :tada:
