### ISSUE TITLE
  lotus chain encode params [command options] [toAddr method params]

### ISSUE THREAD

**Issue by longleilei** [filecoin-project/lotus#7114]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

lotus JSON-RPC API

### Improvement Suggestion

Please, suggest how I can run  **lotus chain encode params [command options] [toAddr method params]**  from a command line? 
When I run  **lotus chain decode params [command options] [toAddr method params]**, for example like:
**lotus chain decode params t01000 23 QwDqBw==**, I can get the desirable output: t01002, however, not able to encode  "t01002" this back to "QwDqBw==". 
Please, could you provide a valid example of  l**otus chain encode params [command options] [toAddr method params]**?

**Comment by rjan90** [comment]
Hi @longleilei!

You can encode it with `lotus chain encode params t01000 23 \"address\"`.

So in your example it would be:
```
lotus chain encode params t01000 23 \"t01002\"
QwDqBw==
```

Closing this issue as fixed now!
