### ISSUE TITLE
add tests for `Dagstore*` JSON-RPC operations.

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#7138]
These operations are tested in https://github.com/filecoin-project/dagstore and have been thouroughly tested by minerX.2 miners during M1. But we should add coverage in Lotus for the RPCs concretely.

**Comment by jennijuju** [comment]
@raulk could you please help define the scope so that we can have bloxico to work on this potentially?

**Comment by rjan90** [comment]
Closing this issue as outdated on the lotus-miner side of things. This issue is related to the legacy markets code in the Lotus-Miner which will be deprecated.
