### ISSUE TITLE
Make pubsub heartbeat log mssage DEBUG

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#7154]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

```
{"level":"info","ts":"2021-08-21T03:14:13.906+0200","logger":"pubsub","caller":"go-libp2p-pubsub@v0.5.3/gossipsub.go:1551","msg":"heartbeat"}
```

isn't this more of a DEBUG level message? the information included is not really informative... and it spams once a second!

**Comment by vyzo** [comment]
this has been fixed upstream.

**Comment by f8-ptrk** [comment]
!
