### ISSUE TITLE
Lotus market process crashes with SIGSEGV

### ISSUE THREAD

**Issue by cerblue** [filecoin-project/lotus#7161]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.11.1+mainnet+git.bc4724fe4+api1.3.0
Local: lotus version 1.11.1+mainnet+git.bc4724fe4

Daemon:  1.11.1+mainnet+git.bc4724fe4+api1.2.0
Local: lotus-miner version 1.11.1+mainnet+git.bc4724fe4
```

### Describe the Bug

I have separated out market subsystem process, which runs in the same machine as Lotus daemon and Lotus miner. This setup was running fine over a week, but started crashing at startup some time after moving to v1.11.1 from v1.11.1-rc2. Other parts of miner (sealing, proving) seem to be running okay.

### Logging Information

```text
2021-08-23T06:51:34.333Z INFO  storage provider event {"name":"ProviderEventRestart","proposal CID":"bafyreigp2zthjybmo5xzahvtssfg2m5cvqsu5kz5lybnlw56nnxyo44v7e","state":"StorageDealStaged","message":""}
2021-08-23T06:51:34.333Z INFO  storage provider event {"name":"ProviderEventRestart","proposal CID":"bafyreigp6ctjmmrdlkn66zfchvt3nbccsdeeoxzy7ods7s4p2t6uh2pjvq","state":"StorageDealActive","message":""}
2021-08-23T06:51:34.333Z INFO  storage provider event {"name":"ProviderEventRestart","proposal CID":"bafyreigplsns6kdu5brt33mux2lnw6xkm2w45d37xd6bbvyemknep2u47i","state":"StorageDealActive","message":""}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x15cfa76]
goroutine 21316 [running]:
github.com/ipld/go-car.(*selectiveCarTraverser).loader(0xc01324b320, 0x383a7d0, 0xc013bfc340, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jinsub/go/pkg/mod/github.com/ipld/go-car@v0.1.1-0.20201119040415-11b6074b6d4d/selectivecar.go:218 +0x76
github.com/ipld/go-ipld-prime/linking/cid.Link.Load(0xc013bb3c20, 0x22, 0x3845010, 0xc0000528d8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jinsub/go/pkg/mod/github.com/ipld/go-ipld-prime@v0.5.1-0.20201021195245-109253e8a018/linking/cid/cidLink.go:29 +0xa6
github.com/ipld/go-car.(*selectiveCarTraverser).traverseBlocks(0xc01324b320, 0x0, 0x0)
        /home/jinsub/go/pkg/mod/github.com/ipld/go-car@v0.1.1-0.20201119040415-11b6074b6d4d/selectivecar.go:257 +0x27f
github.com/ipld/go-car.(*selectiveCarTraverser).traverse(0xc01324b320, 0xc01324b320, 0x561b98, 0x10)
        /home/jinsub/go/pkg/mod/github.com/ipld/go-car@v0.1.1-0.20201119040415-11b6074b6d4d/selectivecar.go:184 +0x50
github.com/ipld/go-car.SelectiveCar.traverse(0x3845010, 0xc0000528d8, 0xc0132252c0, 0x1, 0x1, 0x0, 0x0, 0xc013bfc250, 0xc013bfc260, 0x120, ...)
        /home/jinsub/go/pkg/mod/github.com/ipld/go-car@v0.1.1-0.20201119040415-11b6074b6d4d/selectivecar.go:71 +0xe5
github.com/ipld/go-car.SelectiveCar.Prepare(0x3845010, 0xc0000528d8, 0xc0132252c0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jinsub/go/pkg/mod/github.com/ipld/go-car@v0.1.1-0.20201119040415-11b6074b6d4d/selectivecar.go:88 +0x13f
github.com/filecoin-project/go-commp-utils/pieceio/cario.carIO.PrepareCar(0x3845010, 0xc0000528d8, 0x0, 0x0, 0xc013bb3c20, 0x22, 0x3873158, 0xc013225200, 0x0, 0x0, ...)
        /home/jinsub/go/pkg/mod/github.com/filecoin-project/go-commp-utils@v0.1.1-0.20210427191551-70bf140d31c7/pieceio/cario/cario.go:30 +0x21b
github.com/filecoin-project/go-commp-utils/pieceio.(*pieceIO).GeneratePieceReader(0xc000e238f0, 0xc013bb3c20, 0x22, 0x3873158, 0xc013225200, 0x0, 0x0, 0x0, 0x0, 0x382f960, ...)
        /home/jinsub/go/pkg/mod/github.com/filecoin-project/go-commp-utils@v0.1.1-0.20210427191551-70bf140d31c7/pieceio/pieceio.go:57 +0x143
github.com/filecoin-project/go-fil-markets/storagemarket/impl.(*providerDealEnvironment).GeneratePieceReader(0xc00070e320, 0x0, 0xc013bb3c20, 0x22, 0x3873158, 0xc013225200, 0xc013718078, 0x17, 0x0, 0xc0136bdd40, ...)
        /home/jinsub/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.6.2/storagemarket/impl/provider_environments.go:92 +0x90
github.com/filecoin-project/go-fil-markets/storagemarket/impl/providerstates.HandoffDeal(0x7fc4f410ff68, 0xc0117e3710, 0x7fc4f410ff90, 0xc00070e320, 0xc013bb39e0, 0x27, 0x20000000, 0x0, 0xc013bf4580, 0x31, ...)
        /home/jinsub/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.6.2/storagemarket/impl/providerstates/provider_states.go:319 +0x956
reflect.Value.call(0x2fa5bc0, 0x35ff450, 0x13, 0x333a8e5, 0x4, 0xc01408d6c0, 0x3, 0x3, 0x55ec7f, 0x318b6a0, ...)
        /snap/go/7954/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x2fa5bc0, 0x35ff450, 0x13, 0xc0015196c0, 0x3, 0x3, 0xc0015196d0, 0x14fe390, 0xc012b6a410)
        /snap/go/7954/src/reflect/value.go:337 +0xb9
github.com/filecoin-project/go-statemachine/fsm.fsmHandler.handler.func1(0xc01321d9e0, 0x2, 0x2, 0xc01321d9e0, 0xf89bb70f3a860dd0, 0x55)
        /home/jinsub/go/pkg/mod/github.com/filecoin-project/go-statemachine@v1.0.1/fsm/fsm.go:187 +0x437
reflect.Value.call(0xc0134cc120, 0xc01321d980, 0x13, 0x333a8e5, 0x4, 0xc001519f30, 0x2, 0x2, 0x55ec7f, 0x309c380, ...)
        /snap/go/7954/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0134cc120, 0xc01321d980, 0x13, 0xc00c801730, 0x2, 0x2, 0x387bc70, 0x2fde920, 0xc00c8017c8)
        /snap/go/7954/src/reflect/value.go:337 +0xb9
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc013bfa048, 0xc013bfc040, 0x3845010, 0xc0000528f0, 0xc013bfc0f0, 0xc013bfc050, 0xc01324b0e0)
        /home/jinsub/go/pkg/mod/github.com/filecoin-project/go-statemachine@v1.0.1/machine.go:108 +0x3cc
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
        /home/jinsub/go/pkg/mod/github.com/filecoin-project/go-statemachine@v1.0.1/machine.go:103 +0x451
lotus-market.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
lotus-market.service: Failed with result 'exit-code'.
lotus-market.service: Scheduled restart job, restart counter is at 205.
Stopped Lotus Market.
```

### Repo Steps

1. Run 'lotus-miner --miner-repo {markets repo}'
2. Process crashes at startup

**Comment by cerblue** [comment]
The problem persists even after rolling back to last known good: v1.11.1-rc2.

**Comment by aarshkshah1992** [comment]
@cerblue Did you upgrade to the M1 tags at any point in time ?

**Comment by cerblue** [comment]
Yes, I have upgraded to m1.3 and m1.3.5 previously.

**Comment by aarshkshah1992** [comment]
@jacobheun 

As evident by the logs the user has attached, this is the issue where user upgraded to the M1 release -> initiated a storage deal but rolled back before it entered the `StorageDealWaitingPrecommit` state. As confirmed above, the user had upgraded to M1 earlier and sees this issue on both `v1.11.1` AND `v1.11.1-rc2` neither of which has the DagStore changes. 

Please can we point the user to the rollback docs and close the issue ?

**Comment by aarshkshah1992** [comment]
@cerblue -> Basically, you''ll have to cancel all your inflight deals -> then move to the `1.11.2-rc.1` release, wait for all your storage deals to start sealing and then rollback to `v1.11.1` if you still want to.

**Comment by jacobheun** [comment]
Please see the rollback docs at https://docs.filecoin.io/mine/lotus/dagstore/#lotus-version-rollback. Let us know if you continue to experience the issue after following the docs.
