### ISSUE TITLE
DealPublishControl setting not in effect

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#7168]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus-miner version
Daemon:  1.11.2-dev+mainnet+git.01ea39ada+api1.2.0
Local: lotus-miner version 1.11.2-dev+mainnet+git.01ea39ada
```

### Describe the Bug

Created new BLS wallet for DealPublishControl and funded it and made an actor control, but publish deal message costs are not subtracted from this wallet. Publish costs continue to come from worker wallet.  

`lotus-miner actor control list`
> control-3  f01192801  f3sgte3ew...  deals      50 FIL

**In .lotusminer/config.toml**
[Addresses]
  PreCommitControl = ["f095245"]
  CommitControl = ["f095246"]
  TerminateControl = []
  DealPublishControl = ["f01192801"]

### Logging Information

```text
No logs relevant to this new actor control

See new publish messages

Worker wallet
https://filfox.info/en/message/bafy2bzaceah2uegv333kpxedz4zdcy6m4z2e6yllm7vwpotgt3v3msq63yltk

Deal wallet
https://filfox.info/en/address/f01192801
```

### Repo Steps

Publish deal and follow the FIL

**Comment by jennijuju** [comment]
The issue may only occur on MRA.

**Comment by magik6k** [comment]
Can you confirm that the config is also set in the market node?

**Comment by stuberman** [comment]
> Can you confirm that the config is also set in the market node?

The fee section is only in the miner node, I will add that to the market node.

**Comment by jennijuju** [comment]
> > Can you confirm that the config is also set in the market node?
> 
> The Adresses section is only in the miner node, I will add that to the market node.

@da-you could you try to reprint/verify this in a local devnet?

**Comment by stuberman** [comment]
Adding the Fee address to the dedicated market node resolved this. Probably need this added to the docs.
