### ISSUE TITLE
Hard coded seed for garbage data

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lotus#718]
I came across:
https://github.com/filecoin-project/lotus/blob/master/storage/garbage.go#L26

While I concur that 42 is in fact the meaning of life, won't this generate identical random data each time you call it, which, assuming the size is the same, will generate identical sectors? 

I'm not sure I understand proofs well enough, but does this present issues in terms of actually making sure the miner is storing multiple sectors and not just using using the same one for multiple proofs?

**Comment by whyrusleeping** [comment]
the proof of replication ensures that even identical data generates a unique replica, though, maybe it would be better to test against different random buffers of data? 

I kinda like it this way because it makes it easy to look at the chain and see which sectors are garbage vs not

**Comment by hannahhoward** [comment]
yea I definitely do not understand proofs well enough that this makes sense.

Honestly I guess it doesn't really matter what garbage is stored in garbage.
