### ISSUE TITLE
[Serious Bug Report] Bad scheduling Cause OOM. And Windowd Post problem

### ISSUE THREAD

**Issue by aglcoder** [filecoin-project/lotus#7183]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner version 1.11.1+mainnet+git.15d90c24e.dirty
```

### Describe the Bug

OutPut Of `lotus-miner proving info`:
>Miner: f0495421
Current Epoch:           1054896
Proving Period Boundary: 596
Proving Period Start:    1054676 (1 hour 50 minutes ago)
Next Period Start:       1057556 (in 22 hours 10 minutes)
>
>Faults:      0 (0.00%)
Recovering:  0
Deadline Index:       3
Deadline Sectors:     0
Deadline Open:        1054856 (20 minutes ago)
Deadline Close:       1054916 (in 10 minutes)
Deadline Challenge:   1054836 (30 minutes ago)
Deadline FaultCutoff: 1054786 (55 minutes ago)

This is a serious bug!!
The current Miner Post function has big problems:
After experiencing an OOM, Miner will not take the initiative to calculate and submit proofs during Windowd Post until I restart Miner.
However, it takes about 10 minutes or more to restart, and it may not be able to successfully activate Windowd Post after restarting.
Not only that, the day after the failure occurred, I did not restart the Miner program again, and as a result, even the `DeclareFaultsRecovered`, that is, the sector recovery message, was not submitted.
After I restarted the node, I resubmitted the next Deadline `DeclareFaultsRecovered` message, but it was too late, and Deadline 0 was doomed to be an error.
As a result, most of the sector errors on my node were fault, and 4.55 FIL was confiscated....
During the entire process of the error, I did not take any action. It worked again after I restarted the node, so I felt very helpless and speechless...

And this failure is not the first time it has occurred. After upgrading v1.10, there has been a problem of Windowd Post not submitting it. This problem has also appeared on a large scale in the industry.

So by the way, why does it cause OOM?

I really have to scold this Miner's extremely stupid scheduling mechanism. Why should another Worker execute another Worker P2? About 1.2TB of data needs to be transferred in the middle, which is a waste of time and a lot of disk IO resources.
Moreover, officials have always claimed that the scheduler is "scheduling based on machine resource conditions", so may I ask, why can't we monitor the machine resource conditions on the machine where the Worker is running? Can only monitor the worker's own resource occupation? What if I run multiple workers with different functions on one machine? Is this reasonable? In the end, some workers were very idle, and then Miner assigned the task to a fully loaded Worker, which finally resulted in OOM.

![image](https://user-images.githubusercontent.com/71800187/130906884-2fc523a0-6fe6-43d3-b6db-f3d360809751.png)

Please, do you think this is smart? Now the entire Miner scheduler is extremely stupid.

Can you let the miners manually set the maximum number of tasks that different Workers can perform according to the actual situation of the equipment in their hands? In this way, the problem will be solved very simply, isn't it?

Please, Official developers, please fix these core issues first. We miners have stepped on so many bugs, don’t make us sad anymore, okay?

### Logging Information

```text
https://gateway.ipns.tech/ipfs/QmV2NoM6T2TzpJuhkkAoVcFtx4ua7tcAfmdtV1onNN4sUa/out-log.log
```

### Repo Steps

1. Periodic overcrowding tasks
2. OOM
3. Miner does not perform Windowd Post calculations and DeclareFaultsRecovered calculations

**Comment by rjan90** [comment]
Hey @aglcoder!

Closing this issue now since a lot of scheduling improvements has been made since this post. Its also possible to create specialized [sector storage groups](https://lotus.filecoin.io/storage-providers/seal-workers/seal-workers/#sector-storage-groups) between workers to avoid unnecessary data-transfers. The upcoming v1.15.2-rcX will also include PoSt workers which lets you separate out the windowPoSt to a dedicated machine.

Thanks again for your report.
