### ISSUE TITLE
[Test Failure] Baseline k8s 3-1

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/lotus#7186]
See https://github.com/filecoin-project/lotus/runs/3433876406.

Unfortunately, there's little information on _why_ it's failing. However, this time at least, it's not failing due to infrastructure issues.

**Comment by rjan90** [comment]
Closing this ticket as outdated. Lotus has moved from CircleCI to GHA, and we are currently monitoring Flaky jobs over time in this [Grafana dashboard](https://ipdx.grafana.net/dashboard/snapshot/TfD5JfybgB0odLmipdZniNgayqr1zv3c?var-interval=1d&var-org=$__all&var-repo=$__all&var-branch=&var-workflow=&var-job=&var-label=&var-granularity=&var-limit=&from=now-7d&to=now).

We have also consolidated flaky test reports into a single tracking issue here: https://github.com/filecoin-project/lotus/issues/12001
