### ISSUE TITLE
lotus, lotus-seed, lotus-bench, lotus-fountain, lotus-storage-miner do not repesect GOLOG_LOG_LEVEL

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#719]
[SetupLogging](https://godoc.org/github.com/ipfs/go-log#SetupLogging) of go-log handles the `GOLOG_LOG_LEVEL` variables, and is called during `init`, so all of these programs override any supplied log level.

https://github.com/filecoin-project/lotus/blob/0adfff9ae7afce64d5faec3e9ce0f01cafbee734/cmd/lotus/main.go#L16-L17
https://github.com/filecoin-project/lotus/blob/0adfff9ae7afce64d5faec3e9ce0f01cafbee734/cmd/lotus-storage-miner/main.go#L19-L20
https://github.com/filecoin-project/lotus/blob/0adfff9ae7afce64d5faec3e9ce0f01cafbee734/cmd/lotus-bench/main.go#L48-L49
https://github.com/filecoin-project/lotus/blob/0adfff9ae7afce64d5faec3e9ce0f01cafbee734/cmd/lotus-fountain/main.go#L31-L32
https://github.com/filecoin-project/lotus/blob/0adfff9ae7afce64d5faec3e9ce0f01cafbee734/cmd/lotus-chainwatch/main.go#L18-L19

**Comment by lanzafame** [comment]
What version of go-log is being used?

**Comment by travisperson** [comment]
v1.0.0

**Comment by whyrusleeping** [comment]
@travisperson is there a way we can change the go-log default to INFO? that way we could delete our manual setting of this and just rely on the SetupLogging call

**Comment by lanzafame** [comment]
@travisperson can you try v1.0.0-alpha-1?

**Comment by magik6k** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/1117
