### ISSUE TITLE
 Checking full node sync status

### ISSUE THREAD

**Issue by whhpc19891120** [filecoin-project/lotus#7196]
after execute lotus-miner init  , the program stay here for half an hours, what is the reason?

2021-08-27T13:34:23.033+0800    INFO    main    lotus-miner/init.go:154 Trying to connect to full node RPC
2021-08-27T13:34:23.248+0800    INFO    main    lotus-miner/init.go:166 **Checking full node sync status**

**Comment by f8-ptrk** [comment]
@jennijuju this is a a discussion too. for sure not an issue with lotus

**Comment by JelloHuang** [comment]
i have tested with devnet .lotus sync wait show nothing.and genesis daemon show some thing below:
[genesis_daemon.md](https://github.com/filecoin-project/lotus/files/7072461/genesis_daemon.md)

**Comment by JelloHuang** [comment]
i am busy at sat and sunday . And tomorrow i will continue to  debug
