### ISSUE TITLE
Integrate the proof patch

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7207]
There was something leaking RAM during PC2 that was included in the changes for the threadpool switch with proof  v9.0.1 inb lotus v1.11.2-rc1. A fix is being worked on and tested [here](https://github.com/filecoin-project/lotus/discussions/6904#discussioncomment-1241257) and showing promising result, and we want to include the fix in lotus v1.11.2-rc2.

**Comment by cryptonemo** [comment]
Lotus can tag our latest PR branch for testing: https://github.com/filecoin-project/filecoin-ffi/pull/200

Lotus should use `extern/filecoin-ffi` commit `b4e4271db8f6e961934cd6ffff44fda3c610b9c0` for further testing.

**Comment by cryptonemo** [comment]
I failed here and missed the `fr32` update and that `rust-filecoin-proofs-api` were still pulling in the bad deps.  I have updated the recommended commit hash to `5de64e7c45fa1b3b6becbbdb9f237bec3239545d`
