### ISSUE TITLE
Block sync stop at height 740

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#721]
cx@filecoin01:/$ lotus version
0.7.0+api0.7.1793 <nil>
lotus version 0.7.0

cx@filecoin01:/$ lotus sync status
sync status:
worker 0:
	Base:	[bafy2bzacedmiybvhaxlzlf6hkfupnlm4jvv3j2v7ztswcdd47t5fxaj7upazw]
	Target:	[bafy2bzaced5vbelmqbmrpdt3c2zsgebvizpnpybdhhaj3ql4h7jd3wjd73uwg]
	Height diff:	2763
	Stage: message sync
	Height: 740
worker 1:
	Base:	[bafy2bzaceaxuqgfwx2xsr53hx76m76y6n67rw65xnnyprioxdz6suz7kydgni]
	Target:	[bafy2bzacecgc7qhfx4btqf5ltbyfqoart5vkaoqtbybkaepuqv4d7vcrjeoxq]
	Height diff:	2105
	Stage: message sync
	Height: 740
worker 2:
	Base:	[bafy2bzacedmiybvhaxlzlf6hkfupnlm4jvv3j2v7ztswcdd47t5fxaj7upazw]
	Target:	[bafy2bzacedtded7fjvyjaykafzezewlyssc2b3xyyv7lisl55p2puq3b3rn3k]
	Height diff:	2828
	Stage: message sync
	Height: 740
steps:
1  rm -rf ~/.lotus ~/.lotusstorage .
2 build master code (git https://github.com/filecoin-project/lotus/commit/0adfff9ae7afce64d5faec3e9ce0f01cafbee734), 
3 lotus daemon
4  lotus sync status
I try three times, but get the same errror

**Comment by whyrusleeping** [comment]
yep. This is a bug caused by our 'fork' fix yesterday. We're going to reset the devnet for this.

**Comment by wy199129** [comment]
Always a height of 0

**Comment by wy199129** [comment]
Always a height of 0 

sync status:
worker 0:
        Base:   [bafy2bzaceaxuqgfwx2xsr53hx76m76y6n67rw65xnnyprioxdz6suz7kydgni]
        Target: [bafy2bzacea4gwbttan3wmzu75dadb7bjatsacspghknrzwasdg5ugybaz3nmc] (5823)
        Height diff:    5166
        Stage: error
        Height: 0
        Elapsed: 80.244µs
        Error: chain linked to block marked previously as bad ([bafy2bzacea4gwbttan3wmzu75dadb7bjatsacspghknrzwasdg5ugybaz3nmc], bafy2bzacecx6xkqvc55rjnukzg5fyw4dy3detk7s2fe7y6fchnc6w2sarwz5k)
worker 1:
        Base:   [bafy2bzaceaxuqgfwx2xsr53hx76m76y6n67rw65xnnyprioxdz6suz7kydgni]
        Target: [bafy2bzacednvdopv5i5kzccocasmktb5lo6z6m274pjgh56l7iz3m64jt7pai] (5823)
        Height diff:    5166
        Stage: error
        Height: 0
        Elapsed: 32.295µs
        Error: chain linked to block marked previously as bad ([bafy2bzacednvdopv5i5kzccocasmktb5lo6z6m274pjgh56l7iz3m64jt7pai], bafy2bzacecx6xkqvc55rjnukzg5fyw4dy3detk7s2fe7y6fchnc6w2sarwz5k)
worker 2:
        Base:   [bafy2bzaceaxuqgfwx2xsr53hx76m76y6n67rw65xnnyprioxdz6suz7kydgni]
        Target: [bafy2bzacedztldm5bjafukjyy3nii6ayg5zeykzg6lwx6655lock2iha5rudy] (2334)
        Height diff:    1677
        Stage: header sync
        Height: 2334
        Elapsed: 30.324506ms
