### ISSUE TITLE
Unable to cancel dead transfer in data-transfer list

### ISSUE THREAD

**Issue by funktafide** [filecoin-project/lotus#7212]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.11.1-m1.3.5+mainnet+git.3ff8e256b+api1.3.1
Local: lotus version 1.11.1-m1.3.5+mainnet+git.3ff8e256b
```

### Describe the Bug

I have several deals that have been stuck in `lotus-miner data-transfers list`. When I attempt to cancel the deals with `lotus-miner data-transfers cancel <ID>` I receive the following error:

`ERROR: No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWBt1wMR72cqS1HfZ1GtUdG2vdXECAMsLzKZrizr8WKZ14-1628515589356672355`

I receive this for all of the transfer that are stuck.

### Logging Information

```text
2021-08-28T11:58:53.804+0800	INFO	dt-impl	impl/impl.go:284	close channel 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWBt1wMR72cqS1HfZ1GtUdG2vdXECAMsLzKZrizr8WKZ14-1628515589356672355
2021-08-28T11:58:53.805+0800	WARN	rpc	go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:279	error in RPC call to 'Filecoin.MarketCancelDataTransfer': No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWBt1wMR72cqS1HfZ1GtUdG2vdXECAMsLzKZrizr8WKZ14-1628515589356672355
```

### Repo Steps

1. Run 'lotus-miner data-transfers cancel <ID>'
2. See error `ERROR: No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWBt1wMR72cqS1HfZ1GtUdG2vdXECAMsLzKZrizr8WKZ14-1628515589356672355'

**Comment by Reiers** [comment]
Hi @funktafide 

Thanks for the report. This is fixed in the latest release, and Im not able to reproduce the issue here:

```
lotus-miner data-transfers cancel <ID>
lotus-miner data-transfers restart <ID>
lotus-miner --call-on-markets data-transfers cancel <ID>
lotus-miner --call-on-markets data-transfers restart <ID>
```
All the commands above are working as expected.

Link to latest tags [here.](https://github.com/filecoin-project/lotus/tags)

Closing ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Thank you !
