### ISSUE TITLE
Add switch to configure tasks transfer enable/disable among workers

### ISSUE THREAD

**Issue by potato1992** [filecoin-project/lotus#7217]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

I have two lotus-workers which have the same software/hardware configuration. (do all `AP PC1 PC2 C2 UNS`)
When I seal new sectors, the tasks are evenly distributed to them, which is good.

However, I found they are transferring tasks among each other after PC1. The transfer of about 500GB cache takes soooo long time, even if I have 10GB network, **I believe lotus cannot fully ultilize the 10GB network, the average transfer speed is just 1-2G**

How can I disable transfer the task between these two workers, and force each of them to do the whole complete process individually?

### Describe the solution you'd like

Add a command to configure to disable transfer the task between these two workers, and force each of them to do the whole complete process individually.

**Comment by shotcollin** [comment]
desperately needed. I have similar setup and the unnecessary network transfers are crippling my sealing pipeline. Upgraded my network only to now discover that even with working 40Gb connections between workers, transfers Lotus initiates are often far slower.

**Comment by rjan90** [comment]
Hi @potato1992 

Thank you so much for the report. This issue/feature has been implemented in newer versions of Lotus, where you can create [worker-groups](https://lotus.filecoin.io/storage-providers/seal-workers/seal-workers/#sector-storage-groups)

Closing ticket.
