### ISSUE TITLE
Deleting data-layer cache files on the worker side immediately after sealing is completed

### ISSUE THREAD

**Issue by Shekelme** [filecoin-project/lotus#7219]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Is it possible to delete `sc-02-data-layer-X.dat` cache files on the worker side immediately after sealing is completed?

Very many times I noticed that the sector is finalized in an absolutely normal way if these files are deleted manually. This sometimes had to be done when the storage on the worker was overflowing.

### Describe the solution you'd like

Delete `sc-02-data-layer-X.dat` cache files on the production side right after sealing is completed (if it is possible).

**Comment by magik6k** [comment]
Those files are needed for Commit1, enabling early finalize will remove them after Commit.
