### ISSUE TITLE
command line flag and env for remote full node should be supported

### ISSUE THREAD

**Issue by ldoublewood** [filecoin-project/lotus#724]
Currently the following command lines should be executed in the same machine with full node:

- lotus-storage-miner init
- lotus-storage-miner run
- lotus client

The only reason is that the command line need to read 'api' and 'token' file under ~/.lotus/ directory in order to connect to full node (lotus daemon)
Above constraint should be avoid, so command line flag (with env) of 'api' and 'token' should be provided.

**Comment by magik6k** [comment]
This is now supported, see https://docs.lotu.sh/en+api-scripting-support
