### ISSUE TITLE
Seperating GPU does not work

### ISSUE THREAD

**Issue by potato1992** [filecoin-project/lotus#7249]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
v1.11.2-rc2
```

### Describe the Bug

It is claimed in document that I can use NVIDIA_VISIBLE_DEVICES=[device number] to assign different GPU for different worker.

However, that does not work at all.
My config:
```
export NVIDIA_VISIBLE_DEVICES=0
export NVIDIA_VISIBLE_DEVICES=1
```
And this does not work either:
```
export NVIDIA_VISIBLE_DEVICES=[0]
export NVIDIA_VISIBLE_DEVICES=[1]
```
The two workers are just racing to use the first GPU.

### Logging Information

```text
.
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by f8-ptrk** [comment]
it's CUDA_VISIBLE_DEVICES in most cases

**Comment by potato1992** [comment]
> it's CUDA_VISIBLE_DEVICES in most cases

I have not tested `CUDA_VISIBLE_DEVICES`, but I think this will not work either. As I cannot found `CUDA_VISIBLE_DEVICES` in the code through seach.

**Comment by f8-ptrk** [comment]
it is an OS thing and not a lotus code thing.

**Comment by potato1992** [comment]
> it is a cuda thing and not a lotus code thing.
> 
> https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/

Please update the documents `https://docs.filecoin.io/mine/lotus/seal-workers/#lotus-worker-co-location`.

**Comment by f8-ptrk** [comment]
https://github.com/filecoin-project/filecoin-docs/issues/957

**Comment by f8-ptrk** [comment]
@potato1992 create an issue in the docs repo. my issue aims at not recommending using containers

**Comment by potato1992** [comment]
> @potato1992 create an issue in the docs repo. my issue aims at not recommending using containers

I will try that later. Thanks
