### ISSUE TITLE
Lotus-miner error with MarketListIncompleteDeals when running market in separate machine

### ISSUE THREAD

**Issue by William8Work** [filecoin-project/lotus#7267]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
$ lotus version && lotus-miner version
Daemon:  1.11.2-rc2+mainnet+git.570edcbbb+api1.3.0
Local: lotus version 1.11.2-rc2+mainnet+git.570edcbbb
Daemon:  1.11.2-rc2+mainnet+git.570edcbbb+api1.2.0
Local: lotus-miner version 1.11.2-rc2+mainnet+git.570edcbbb

I am running a separate market node in different company from the lotus-miner.
```

### Describe the Bug

After upgraded to 1.11.2-rc2, found errors in miner log. Not sure what happened. 

This may related to the market node being separated since the error is about Filecoin.MarketListIncompleteDeals. However, the environment variable of MARKETS_API_INFO has been set in both the lotus-miner machine as well as the market machine.

### Logging Information

```text
2021-09-02T20:38:55.130-0700    ERROR   rpc     go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:158  panic in rpc method 'Filecoin.MarketListIncompleteDeals': runtime error: invalid memory address or nil pointer dereference
github.com/filecoin-project/go-jsonrpc.doCall.func1
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:158
runtime.gopanic
        /usr/local/go/src/runtime/panic.go:965
runtime.panicmem
        /usr/local/go/src/runtime/panic.go:212
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:734
github.com/filecoin-project/lotus/node/impl.(*StorageMinerAPI).MarketListIncompleteDeals
        /home/filecoin/filecoin/lotus/node/impl/storminer.go:482
reflect.Value.call
        /usr/local/go/src/reflect/value.go:476
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:337
github.com/filecoin-project/lotus/metrics.proxy.func1
        /home/filecoin/filecoin/lotus/metrics/proxy.go:60
github.com/filecoin-project/lotus/api.(*StorageMinerStruct).MarketListIncompleteDeals
        /home/filecoin/filecoin/lotus/api/proxy_gen.go:3945
reflect.Value.call
        /usr/local/go/src/reflect/value.go:476
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:337
github.com/filecoin-project/go-jsonrpc/auth.PermissionedProxy.func1
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/auth/auth.go:62
github.com/filecoin-project/lotus/api.(*StorageMinerStruct).MarketListIncompleteDeals
        /home/filecoin/filecoin/lotus/api/proxy_gen.go:3945
reflect.Value.call
        /usr/local/go/src/reflect/value.go:476
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:337
github.com/filecoin-project/go-jsonrpc.doCall
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:162
github.com/filecoin-project/go-jsonrpc.(*RPCServer).handle
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:259
2021-09-02T20:38:55.130-0700    ERROR   rpc     go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/server.go:95    RPC Error: fatal error calling 'Filecoin.MarketListIncompleteDeals': panic in rpc method 'Filecoin.MarketListIncompleteDeals': runtime error: invalid memory address or nil pointer dereference
2021-09-02T20:38:55.130-0700    WARN    rpc     go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/server.go:101   rpc error: fatal error calling 'Filecoin.MarketListIncompleteDeals': panic in rpc method 'Filecoin.MarketListIncompleteDeals': runtime error: invalid memory address or nil pointer dereference
2021-09-02T20:39:02.291-0700    WARN    rpc     go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:279  error in RPC call to 'Filecoin.NetPeers': method not supported:
    github.com/filecoin-project/lotus/api.init
        /home/filecoin/filecoin/lotus/api/proxy_gen.go:43
```

### Better Error Handling

Seems this is related to tools calling the new lotus-miner without proper market token. If that's case, we need some better handling than throwing code panic or exception.

**Comment by William8Work** [comment]
looks like the farcaster is calling lotus-miner info to get market info. Not related to 1.11.2-rc2.

**Comment by Reiers** [comment]
**Hi @William8Work** 

Thanks for the report. Separate markets node is still somewhat experimental.
Please update to the latest Lotus version: https://github.com/filecoin-project/lotus/releases/tag/v1.13.1

Also remember to have environments set for both miner and separate markets node:

```
export APISEALER=`lotus-miner auth api-info --perm=admin`
export APISECTORINDEX=`lotus-miner auth api-info --perm=admin`
```

https://lotus.filecoin.io/docs/storage-providers/split-markets-miners/

Closing ticket.

If you are still experiencing problems, open a new ticket or ask in our Discussions <link>forum.
