### ISSUE TITLE
flakey test-itest-deals_max_staging_deals 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7280]
https://app.circleci.com/pipelines/github/filecoin-project/lotus/17106/workflows/29220747-6824-42dd-9776-ac481425b8a7/jobs/260554 

test-itest-deals_max_staging_deals  failed after introducing #7276

**Comment by nonsense** [comment]
Done at https://github.com/filecoin-project/lotus/pull/7292
