### ISSUE TITLE
SWAP alongside low RAM for sealing

### ISSUE THREAD

**Issue by emad22552** [filecoin-project/lotus#7281]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

I've seen [minimum hardware requirements](https://docs.filecoin.io/mine/hardware-requirements/#general-hardware-requirements) before.
I'm on calibration with **64GB RAM** and **500GB NVMe SWAP**.
running PC1 or bench-tools for 32GiB sector ends to killed and swap usage does not changes.
I think it is strange that lotus-miner forces the OS to only use RAM without swap (first use RAM then swap).
**I think it would be better to have the ability to run sealing in low memory alongside with SWAP although it would be slower [than at least 128 GiB RAM].**

**Comment by Reiers** [comment]
**Hi @emad22552** 

Thanks for this feature request. 
But this is not something that will be changed in the near future, and you are below the minimum requirement with 64GB RAM.

We are always trying to optimize, but as it stands right now. The minimum will be 128 GB RAM to run a Storage Provider/miner service.

I personally would not recommend using that much swap anyway - the disk will burn out fast, and the sealing will be slow. 

Closing Lotus Issue ticket.
