### ISSUE TITLE
Query-ask version 2 - standardize per-customer pricing (with new query-ask format)

### ISSUE THREAD

**Issue by neondragon** [filecoin-project/lotus#7300]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

This is a suggested improvement to how storage providers present their storage prices to customers using Lotus.

**User Story**
Alice runs a successful Filecoin storage provider service.
Alice would like to offer different prices to different customers for business reasons.

**Existing implementation in Lotus**
Storage providers set a single set of deal acceptance criteria that is applied to all customers, using `lotus-miner storage-deals set-ask`

**Problem**
Lotus does not provide a way for a storage provider to offer a different price to different customers.

Storage providers work around this restriction by agreeing prices with customers outside of lotus. They then provide the customer specific pricing in non-standard ways e.g.:

- Temporarily lowering their global ask price to allow a customer to send deals, and then raising their prices back to normal. Other customers might also send deals and will unintentionally receive the lower price.
- Setting their ask price to 0, and fully relying on customers to manually specify the agreed prices in their deal proposals.

Both solutions break automation. A customer using the price a storage provider returns in their query-ask response may either pay more than they could have, or attempt to make a deal with a price of 0, which is rejected.

**Improvement**
My proposal for query-ask version 2:

1. Send the default wallet address in a query-ask request, or allow it to be specified: `lotus client query-ask --from <walletAddress>`
2. Sign the query-ask request with the provided wallet address, to prove the client has ownership of the address
3. On the storage provider, by default, respond using the acceptance criteria set in `lotus-miner storage-deals set-ask`.
4. Add an 'ask filter' script option to the storage provider. If an ask filter is present, first verify the query-ask message signature. Then, run the ask filter and provide to standard input a JSON representation of the query-ask parameters including the requesting wallet address. The ask filter script should return a price, minimum deal size, and maximum deal size. That data is sent back to the client as the query-ask response.
5. When a deal is received, call the ask filter with the deal's wallet address to retrieve the current deal acceptance criteria, and make the decision to accept or reject. If ask filter not present, use the default lotus criteria from set-ask.
6. Add extra metadata key-value pairs into the query-ask response, such as: storage provider name, storage provider geolocation, storage provider jurisdiction, website URL, a URL link to terms of service. I welcome discussion from people in this thread as to what metadata would be useful to include.
7. Additional arbitrary key-value pairs should be accepted from the ask filter script and passed to the client in the query-ask response. These could be used by the community to communicate custom data to clients that could more easily allow development of new software for the ecosystem.

**Comment by neondragon** [comment]
I changed my mind and am going to write a new suggestion based on providing deal acceptance criteria as well-formed JSON in the deal rejection reason payload.

**Comment by neondragon** [comment]
I un-changed my mind.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
