### ISSUE TITLE
Standardize per-customer pricing implementation with a JSON payload in the proposal rejection response

### ISSUE THREAD

**Issue by neondragon** [filecoin-project/lotus#7301]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

This is a suggested improvement to how storage providers present their storage prices to customers using Lotus.

**User Story**
Alice runs a successful Filecoin storage provider service.
Alice would like to offer different prices to different customers for business reasons.

**Existing implementation in Lotus**
Storage providers set a single set of deal acceptance criteria that is applied to all customers, using `lotus-miner storage-deals set-ask`

**Problem**
Lotus does not provide a way for a storage provider to offer a different price to different customers.

Storage providers work around this restriction by agreeing prices with customers outside of lotus. They then provide the customer specific pricing in non-standard ways e.g.:

- Temporarily lowering their global ask price to allow a customer to send deals, and then raising their prices back to normal. Other customers might also send deals and will unintentionally receive the lower price.
- Setting their ask price to 0, and fully relying on customers to manually specify the agreed prices in their deal proposals.

Both solutions break automation. A customer using the price a storage provider returns in their query-ask response may either pay more than they could have, or attempt to make a deal with a price of 0, which is rejected.

**Improvement**
A proposal to allow clients to access their custom deal acceptance criteria:

1. A client using this convention does not use query-ask.
2. The client proposes a deal with the storage provider for 0 FIL and for 0 bytes in size.
3. The storage provider recognises this deal proposal as a special case, rejects the deal, and responds with a well-formed JSON payload describing the deal acceptance criteria for that specific client, based on the data provided in the deal proposal.
4. The client parses the standards-based part of the information and sends deal proposals if it accepts the criteria.

This implementation retains combability with existing tooling.

The JSON payload returned to the client could be a set of keys and values like this:
```
{
  "response_type":"deal_criteria"
  "version":"1",
  "criteria": {
    "priceUnverified":2000000,
    "priceVerified":0,
    "minSize":134217728,
    "maxSize":34359738368,
    "x_nonstandard_key": "storage providers can send any extra non-standard data in the response by prefixing the custom key's name with 'x_'",
  }
}
```

I would like to ask the community what other data it may be useful to return in this payload, so that we can agree on the standard way to format it. Please comment in this thread with suggestions.

**Comment by s0nik42** [comment]
I like really like the approach and backward compatibility with what is in place today 

Here is my comments : 
A miner can for a specific client propose different prices  based on the size of the deal/duration/dealtype, etc...  like : 
1.  > 32GiB unverified : 0.00000001
2.  > 32GiB unverified < 1years : 0.00000001
2.  >4GiB unverified : 0.00000002
3. < 4GiB unverified : reject
4. verified : 0
5. offline : reject

Sending back the complete pricing could be complex to implement (but we are open to do that too). 
A simple solution will be to return the price based on the deal proposal properties.

I would imagine the following User Story: 
 
1. The client proposes a deal with the storage provider to a value that will probably be never used : -1 AttoFil (or 1AttoFil but may have some side effect)

2. The storage provider JSON answer : 
 {
  "response_type":"deal_price"
  "version":"1",
  "matching_price":  2000000,
  "matching_pricing_validity": 172800 
  "x_nonstandard_key": "storage providers can send any extra non-standard data in the response by prefixing the custom key's name with 'x_'",
  }
}

**Comment by neondragon** [comment]
I agree with @s0nik42 's idea to return just a price and validity, applicable for the type of deal proposed. That way, the logic that the deal filter uses to decide prices is irrelevant. The client just needs to know what the price is for a specific deal.

I suggested the special signal for a storage provider to return the JSON would be a deal proposal with price 0 FIL and piece size 0. We would need to specify a piece size to allow the deal filter script to be provided with the proposed size. Proposing a deal with price 0 FIL is valid so we can't use that.

Proposing a deal with price -1 attofil may be the best way to signal the storage provider to reject the proposal and return the JSON payload? That should be compatible with existing implementations (the proposal should just be rejected as invalid). 

Lotus would need to be altered so that an incoming deal with a price of -1 attoFIL would be sent to the deal filter script. The deal filter script can return REJECT {"response_type":"deal_price", ...}.

**Comment by s0nik42** [comment]
@ribasushi : that's even better ! 
@neondragon : seems like we've got all we need to wrapup, what do you think ?

**Comment by neondragon** [comment]
@ribasushi Fantastic suggestion!

I think two things should happen:

**1. Implement the 'just tell me stuff' magic API call**

The lotus client should allow sending a deal proposal using this magic PieceCID without actual data existing.

When lotus receives a deal proposal with magic PieceCID "baga6ea4seaqfilecoinpricingrequestversiononexxxxxxxxxxxxxxxxqqqq" it:

- Passes this full deal proposal to the deal filter script, if present.
- The deal filter script is responsible for returning the JSON payload as a rejection message
- Lotus then rejects the deal if the deal filter script did not.

The JSON payload format is:
```
{
  "response_type":"deal_criteria"
  "version":"1",
  "criteria": {
    "price":2000000,
    "validity": 1800
    "x_nonstandard_key": "storage providers can send any extra non-standard data in the response by prefixing the custom key's name with 'x_'",
  }
}
```

Price in attoFIL, validity in seconds.

**2. Clients that don't understand this protocol should be able to query-ask a storage miner as usual and receive a usable response.**
We don't *have* to do this, but if we don't, the existing query-ask system will remain unusable.
Currently, storage providers are setting their ask prices to 0. This breaks existing tools and is fragmenting the ecosystem. It is only necessary because lotus will reject deals priced lower than the ask price before sending them to the deal filter script.

go-fil-markets needs the price test to be moved to *after* the deal filter script is executed. If the deal filter script returns ACCEPT, then the price test should be skipped. ACCEPT should signal that the deal filter has performed all business logic and that go-fil-markets should only then reject the deal due to technical reasons.

I have been using this technique for about 8 months now. It works perfectly. It just needs to be made default behaviour in Lotus in a way that doesn't break existing installs (my current code will).

**Comment by neondragon** [comment]
**Making a deal - client uses existing query-ask system**

1. Client performs query-ask against storage provider.
2. Storage provider returns their default verified/unverified prices and min/max sizes from `set-ask` as normal. The prices are high enough for the storage provider to accept them.
3. Client proposes deal.

**Making a deal - client uses magic PieceCID**

1. Client proposes deal with magic PieceCID, and all other deal parameters the same as the real deal they intend to propose.
2. Storage provider invokes deal filter to return JSON response. Deal filter is able to return a price for deals that the regular 'query-ask' criteria would have rejected.
3. Client parses JSON response and if it is happy, it sends the real deal proposal.

**Comment by ribasushi** [comment]
@neondragon a skech from way back somewhat related to the above. Linking it here if of interest/inspiration: https://github.com/protocol/web3-dev-team/pull/61/files

**Comment by jimpick** [comment]
As a client ... I'm not sure I like where "per-customer" pricing is leading. It's already hard enough to discover the true price of storage on the network. Applications need to one-by-one query individual storage providers, of which there are hundreds/thousands (which may or may not be dialable), or rely on external indexing services which are not always up-to-date, trustworthy, canonical or consistent. The original concept for Filecoin as described in the whitepaper described a stock-market style system with "bid orders" and "ask orders" where the blockchain itself had an orderbook and matched deals and there was competition for deals and visibility. Textile's Bidbot sidecar is perhaps an implementation of that idea.

The original idea was to build the pricing scheme directly into the core of Filecoin itself, but it was subsequently implemented in the markets subsystem, and is evolving towards external scripts and sidecars. The introduction of Filecoin Plus has bifurcated the pricing into two different markets.

If the default pricing model on Filecoin becomes even more non-linear, conditional, opaque, and fragmented it won't be easily analyzable and indexable. It will be very difficult for application creators to build the pricing model into their end-user applications in a way that regular people will be able to understand. I'd like to see some voices from application creators in the design discussion of any new pricing schemes.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
