### ISSUE TITLE
load state tree: unsupported state tree version: 4

### ISSUE THREAD

**Issue by davidzhuwei** [filecoin-project/lotus#7332]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.9.0+mainnet+git.ada7f97ba+api1.3.0
Local: lotus version 1.9.0+mainnet+git.ada7f97ba
```

### Describe the Bug

{"request": {"jsonrpc":"","id":1,"method":"Filecoin.WalletBalance","params":["***"]}, "r.err": "load state tree: unsupported state tree version: 4", "res": "0"}

### Logging Information

```text
{"request": {"jsonrpc":"","id":1,"method":"Filecoin.WalletBalance","params":["***"]}, "r.err": "load state tree: unsupported state tree version: 4", "res": "0"}
```

### Repo Steps

{"request": {"jsonrpc":"","id":1,"method":"Filecoin.WalletBalance","params":["***"]}, "r.err": "load state tree: unsupported state tree version: 4", "res": "0"}

**Comment by TippyFlitsUK** [comment]
Hi @davidzhuwei 

Thanks for the report!

I have tested today with `1.15.1-rc4` and am unable to reproduce the error. Closing as resolved.

Many thanks
