### ISSUE TITLE
Update the default branch name to main

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7356]
As many are aware, Github has now made main the default branch on all new repositories, and Git itself is looking at doing so as well soon. The reason for the change is the branch name master is offensive to some communities.  more details on whys and hows can be found at https://github.com/github/renaming
https://sfconservancy.org/news/2020/jun/23/gitbranchname/.

Code owners of lotus agreed that we should respect the motivation of the change and do the same for lotus. To make sure the change is rolling out smoothly for all lotus contributors and users, we will process as the following:
- [x] create a `main` branch that tracks `master`
- [ ] Announce the migration to the community at least 1 month in advance
- [ ] update the internal infra and ci to use the `main` branch
- [ ] Update the docs + instructions
- [ ] “deprecate” `master`

**Comment by BigLep** [comment]
This push on changing the default branch to `main` from `master` was opened for good reason. 3 years later though, the migration was never completed and `master` has ossified 😔.  It's acknowledged by the maintainers that this isn't ideal and that such terms are legitimately offensive to some.  This certainly isn't how we'd want to structure the project if starting from scratch.  Given the effort hasn't completed after three years and having multiple main-like branches caused a snag during the [202409 operational event](https://github.com/filecoin-project/lotus/issues/12467), we're currently admitting defeat.  We welcome input if this branch migration is something contributors and consumers would want maintainers to prioritize above other work. 

Additional notes:
* The `main` branch was deleted on 2024-09-16 ([slack](https://filecoinproject.slack.com/archives/CP50PPW2X/p1726584534551829?thread_ts=1726584254.054589&cid=CP50PPW2X))
* https://github.com/filecoin-project/lotus/pull/12482 is where we undid the `master`/`main` syncing.
* Some captured notes on the [discussion about how the double branches tripped us up 2024-09-16](https://filecoinproject.slack.com/archives/CP50PPW2X/p1726612129316989?thread_ts=1726584254.054589&cid=CP50PPW2X):

> When working rapidly on something, I won't branch off master/main; I will work on it instead, then branch and then reset them back. Multiple times I referred to wrong branch, getting no error message because only one of them had my temporary commits (but was a valid ref as well)
> Existence of both main and master (vs one or the other) led to me not knowing which is canonical and asking around because I wasn't certain they were in sync
> My personal tooling/aliases prefer one over the other, and even I don't know which. This further tripped me up as I had commits on one of them.
> The[ PR being targeted at main](https://github.com/filecoin-project/lotus/pull/12447) further outlines the confusion issue (this PR would have merged and be promptly lost by the next commit merged to master). Someone would have probably noticed this time as it was a feature, but in the case of a smaller bugfix, it probably would have been missed.

As a result of the above, I'm marking this as "Close as not planned".  Community input though is welcome if we're off-base here.
