### ISSUE TITLE
COMPACTION ERROR

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#7365]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.11.2-rc1+mainnet+git.80624845c
```

### Describe the Bug

Should I worry about this error when shutting down lotus daemon?

### Logging Information

```text
ERROR	splitstore	splitstore/splitstore_compact.go:368	COMPACTION ERROR: error marking: error walking block (cid: bafy2bzaceazlcphx4ebza3p55sd67d5dfcuvhotbhtpdmb3zobtchhphgfhmi): error walking state root (cid: bafy2bzacebabbkzkculhyymuhlgluy3lfuz53ck5jcbwwzjxt56kfnmxp6gyy): error walking link (cid: bafy2bzaceal7q4blxhntoaklr4px2uku2urjuk53espoz5ysam2b5l5pi5jwa): error walking link (cid: bafy2bzaced37ph44e2cd4rk7anh6xa2svzls66arjroksi5xf3wejjmuqimny): error walking link (cid: bafy2bzacea5y47fcyhqu5yyu6sfulnh65hswj7e6mmoonh74dpctde4vti63s): error walking link (cid: bafy2bzacecir2ftj4qclrt6fjcivzzrw6z3mfmnfprn3cyeia4ddyqlb3t7zc): error walking link (cid: bafy2bzaceb75lujjre3y6kvpgdryndhv2dovtbjyyashw3lxjnummeu4zxvje): error walking link (cid: bafy2bzacebhaz3j462xatljkpy4w344ce5ymqxssj7gkftvquha66ghbzu6wi): error walking link (cid: bafy2bzaceavnfbzqps55kwuphnosv7kggd7zlmsfzcc2s6knbp3lo4yaxlo64): error walking link (cid: bafy2bzaceb7k6cul66aiosmet4vcaq7h6g4vtie3gzk7w6tmhxpde5xch3gyg): splitstore is closing
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by vyzo** [comment]
No, this is fine -- the daemon shut down during a compaction and it was
aborted.
