### ISSUE TITLE
Add MinerWithDrawBalance API

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7367]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Be able to withdraw miner balance via an API call 

### Describe the solution you'd like

Expose an API ep for miner.WithdrawBalance.

return CID + withdrawn balance(optional and blocked by actor v6).

**Comment by dirkmc** [comment]
We have
`MarketWithdraw(ctx context.Context, wallet, addr address.Address, amt types.BigInt) (cid.Cid, error)`

Would this be a different API?

**Comment by laudiacay** [comment]
You can withdraw the unlocked funds from the market actor's escrow but not have withdrawn the funds from the miner actor to the owner- is that what this means, I'm assuming? I just wrote some similar code on specs-actors and could probably look at this.

**Comment by jennijuju** [comment]
> You can withdraw the unlocked funds from the market actor's escrow but not have withdrawn the funds from the miner actor to the owner- is that what this means, I'm assuming? I just wrote some similar code on specs-actors and could probably look at this.

Yes, you are right!

**Comment by laudiacay** [comment]
to clarify for future-me: @jennijuju says just to pull out the miner actor's balance to its owner, nothing at all from the market actor's escrow.

**Comment by laudiacay** [comment]
aaaand reference: https://github.com/filecoin-project/lotus/blob/e196a81e99459cb368830c2490f51b186a4cec89/cmd/lotus-miner/actor.go#L209
