### ISSUE TITLE
make targets: install-app, nerpanet

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#7372]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Improvement Suggestion

1. install-app

https://github.com/filecoin-project/lotus/blob/master/Makefile#L136

what is this intended to install? `$(APP)` is not defined anywhere and if therefore fails on v1.11.3-rc1

```
make install-app
install -C ./ /usr/local/bin/
install: omitting directory './'
make: *** [Makefile:137: install-app] Error 1
```

if this does nothing - can it be removed? 

2. nerpanet

for me it looks as the nerpa network will not be revived. if that is the case and the decision is final - can i/we start getting nerpa remove from

- the docs
- the network page
- other palces

**Comment by jennijuju** [comment]
2 is not a lotus issue and has been already done

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/lotus/pull/5183#issue-762289432 for the app thing

**Comment by jennijuju** [comment]
might as well https://github.com/filecoin-project/lotus/pull/7373
