### ISSUE TITLE
Deal making pain points

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#7385]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
After 1.11.1
```

### Describe the Bug

Something has changed since 1.11.1 making sending deals even slower than before

1. Now if you don't import the car file first, you cannot make offline deals with piece cid only. It used to allow that on v1.11.1.
2. If you do import the car now, it's very fast, which is good, however, sending deals becomes very slow, I feel like it's computing commP on each deal making, that's a blocker.
3. journal folder size increase like crazy, 100GiB per hour on a client with about 1000 offline deals sent.
4. Dealmaking gets slower and slower when there are more than a few hundreds deals sent. Seems on every block lotus tries to update all deals status - causing slowness.
4. Lots deals have the error state, although the deal is actually active and on-chain: waiting for deal pre-commit message to appear on chain: failed to set up called handler: called check error (h: 1152606): failed to look up deal on chain: deal 2519755 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed. We used to believe this is caused by chain prune, but nowadays without chain prune this can still happen.

### Logging Information

```text
n/a
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by William8Work** [comment]
Had multiple of the errors related to look up deal on chain. Here is the latest one from DealBot: (Is it related to client chain-prone?)
`Oct  1 05:22:37  true  bafyreidqoqwbdis2ajmgtec4nyktyrlgzeujdunog2dn34bppgowikuimu  2530944  StorageDealError                         f1wdxdpqh3hirrhp353i4o6ld7bsw6evh3v7i5jtq                                               8GiB   0 FIL  520361   12D3KooWD7CbsHFJV8kNabCz5aKksd7ACc3GNcuRDguFAUZW3RUB-12D3KooWRkyFskoWEr7wGG6rSm8bCaNVY4cvfMogsLtbPt8P3sYD-1631206337448000509  error awaiting deal pre-commit: failed to set up called handler: called check error (h: 1159518): failed to look up deal on chain: deal 2530944 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed`
on the miner side however, the sector is still proceeding in sealing stages.

**Comment by aarshkshah1992** [comment]
@kernelogic 

- Which version of the Lotus client are you using ?

- Just to confirm, you are making **storage** deals with the **Lotus client** , right ? Which miner are you making them against ? Are you only talking about offline deals here or online and offline deals ?

> Now if you don't import the car file first, you cannot make offline deals with piece cid only. It used to allow that on v1.11.1.

Please can you share the commands you used for offline deals before and after moving to >v1.11.1 ?

> If you do import the car now, it's very fast, which is good, however, sending deals becomes very slow, I feel like it's computing commP on each deal making, that's a blocker.

> Dealmaking gets slower and slower when there are more than a few hundreds deals sent. Seems on every block lotus tries to update all deals status - causing slowness.


Are you talking about **_online_** deals here ? Do you see this slowness even if you are making just one deal or when you are trying to make 100s of deals simultaneously ? Are you saying that doing 100s of deals simultaneously was fast earlier but has now slowed down or that it has always been slow ?

It would be nice to have more information here about the number of deals you are trying to make simultaneously, whether they are online or offline deals and if you've only started seeing these problems now or you were seeing them earlier as well.

**Comment by kernelogic** [comment]
> Which exact version of the Lotus client are you using ?

Was using 1.11.3-rc2, now reverted to 1.11.1

> Just to confirm, you are making storage deals with the Lotus client , right ? Which miner are you making them against ? Are you only talking about only offline deals here or online and offline deals ?

Yes, lotus client. All offline deals. Miners are various MinerX members.

> Now if you don't import the car file first, you cannot make offline deals with piece cid only. It used to allow that on v1.11.1.
> 
> Please can you share the commands you used for offline deals before and after moving to >v1.11.1 ?

lotus client deal --fast-retrieval=true --from=f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq --manual-piece-cid=baga6ea4seaqgtx2mm5rzskqyx7poq3nil72mamijxdeweddr7a3xtrw5rxl42ki --manual-piece-size=34091302912 --verified-deal=false --start-epoch 1190053 QmbCvSy5XXH3zkNRyR1xFZFbeMBH1KSqYYkHrEntNQKfgM f010617 0 1065600


> Are you talking about online deals here ? Do you see this slowness even if you are making just one deal or when you are trying to make 100s of deals simultaneously ? Are you saying that doing 100s of deals simultaneously was fast earlier but has now slowed down or that it has always been slow ?

Again, offline deals only. I don't make deals simultaneously. I send them one by one. If I start with a clean lotus, deal making is very fast on 1.11.1, but after I sent a few hundreds of deals, it starts to get slower and slower, like 5 seconds to send one deal. If I keep sending deals to a thousand deals or more, lotus can no longer sync and journal folder gets very large. Therefore right now I have to delete the whole .lotus folder after every few hundreds of deals to start fresh.

On 1.11.3-rc2 (or any version after 1.11.1 for that matter), it is worse, first of all, I can no longer make deal without first import into lotus, second, each deal now takes several minutes (I suspect it's trying to re-calculate commP).

**Comment by kernelogic** [comment]
Hi @aarshkshah1992 @jennijuju 

Can we get an update on issue #1: you cannot make offline deals with piece cid only.

I have been using v1.11.1 to send offline deals but with the upcoming chocolate network update I don't think I can use that old version anymore. And this bug will make lotus un-usable to send large amount of offline deals.

Sample command: lotus client deal --manual-piece-cid=baga6ea4seaqlu63vnlhosu7wxdy3jwqxhziz3p6mrqkn7nnxylizu6wpiko5eky --manual-piece-size=34091302912 --verified-deal=false --start-epoch 1210196 QmVmt6yfxnDKb9W1vFCxrNhDmAoLfPCMLDg27yNCDMeGw1 f010617 0 1065600

Sample error: `ERROR: failed to start deal: failed to get blockstore for imported root QmVmt6yfxnDKb9W1vFCxrNhDmAoLfPCMLDg27yNCDMeGw1: no client blockstore for root QmVmt6yfxnDKb9W1vFCxrNhDmAoLfPCMLDg27yNCDMeGw1`

**Comment by dirkmc** [comment]
@kernelogic could you describe the process you were following before that is no longer working.

Did you import the file once before, and then make multiple deals with it? If that's the case, you will need to re-import the file again since lotus versions > v1.11.1. Note that after that you will be able to make multiple deals for it without having to re-import it (you only need to import once).

> each deal now takes several minutes

Which command takes several minutes? Please write out the full set of commands and output, so that we can pinpoint exactly where these issues might be coming from.

**Comment by jennijuju** [comment]
majority of these should be improved with rate limiting, new gs and so on in newer lotus releases. please create new tickets if a specific issue still exists.
