### ISSUE TITLE
lotus-bench cache stages to allow quick PC2 or C2 tests

### ISSUE THREAD

**Issue by neondragon** [filecoin-project/lotus#7437]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Improvement Suggestion

lotus-bench is a useful tool to test and compare sealing.

It may be more useful to Storage Providers if it could more accurately replicate a production workload. These features would help:

- Running a benchmark with --sector-size 32GiB or 64GiB takes many hours. We may only want to test the performance of PC2 or C2. So, cache the output between stages and allow lotus-bench to run only one stage such as C2, using the cached data, without the overhead of having to go all the way through the PC1/PC2/C1 steps every time.
- Add a toggle to disable GPU locking, so that we can test e.g. running two PC2 or C2 tasks that use the GPU concurrently.

The ideal result would be the ability to run a command such as:
`lotus-bench --sector-size=32GiB --c2=2 --pc2=2`
to run two C2 and two PC2 tasks simultaneously on the same GPU, without waiting for PC1 to run again.

**Comment by rjan90** [comment]
Hey @neondragon! Thanks for the feature request. This feature is now possible with https://github.com/filecoin-project/lotus/pull/8373. We will create some documentation for these features the next couple of days, they will eventually be placed here: https://lotus.filecoin.io/storage-providers/operate/benchmarks/.

Closing this issue as completed 😄

**Comment by rjan90** [comment]
The documentation for the new `lotus-bench simple` has been added to the Lotus docs. You can see it here: https://lotus.filecoin.io/storage-providers/operate/benchmarks/#single-task-benchmark
