### ISSUE TITLE
confirm-change-worker is not needed to change worker address

### ISSUE THREAD

**Issue by EmadMF** [filecoin-project/lotus#7498]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus version:
Daemon: 1.11.1+calibnet+git.15d90c24e+api1.3.0
Local: lotus version 1.11.1+calibnet+git.15d90c24e

lotus-miner version:
Daemon: 1.11.1+calibnet+git.15d90c24e+api1.2.0
Local: lotus-miner version 1.11.1+calibnet+git.15d90c24e
```

### Describe the Bug

**I'm not using latest release version but as I checked change logs, there were not anything about this topic**

When I called `lotus-miner actor propose-change-worker <new address>`, it said:
```
Propose Message CID: baf..............
Worker key change to t3................. successfully proposed.
Call 'confirm-change-worker' at or after height xxxxxx to complete.
```
but i never called `confirm-change-worker` and it confirmed automatically after epoch xxxxxx.

### Logging Information

```text
?!
```

### Repo Steps

1. Run `lotus-miner actor propose-change-worker <new address>`
2. Do wait until said epoch
3. See the result of `lotus-miner actor control list` and you'll see that worker address changed without your confirmation.

**Comment by Reiers** [comment]
**Hi @emad22552** 

Thanks for the report. I will add labels and will assign it to the right team for analysis.
I re-produced the steps, and got the same result in the latest release.

**Comment by ZenGround0** [comment]
Expected behavior if you have a deadline cron: https://github.com/filecoin-project/specs-actors/blob/97fc4480cbc9b7078c67276d8c3394e3423ef513/actors/builtin/miner/miner_actor.go#L2221

**Comment by rjan90** [comment]
Hey @EmadMF!

I have created #8384 to change the message to clarify that it´s only Storage Providers without active deadlines that needs to call  `confirm-change-worker`.

Thanks again.
