### ISSUE TITLE
FFI integration for SnapDeals implementation

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/lotus#7516]

**Comment by BlocksOnAChain** [comment]
@Kubuxu can we consider this work as "code complete?

**Comment by BlocksOnAChain** [comment]
@ZenGround0 PR for review - https://github.com/filecoin-project/filecoin-ffi/pull/208

**Comment by ZenGround0** [comment]
## Description

Integrate new proofs snap deals functionality into file coin ffi.  At a high level this introduces an endpoint to proofs that does the snap deals replica update and returns a proof that it was done correctly.  In practice there are a lot of pieces that need to be introduce to make this come together.

## Done criteria

* Functions calling into proofs across the ffi are added into the generated folders
* proofs.go has endpoints using the generated functions for calling into lotus

## Dependencies

No dependencies.

## Ongoing Work

* https://github.com/filecoin-project/filecoin-ffi/pull/208

**Comment by BlocksOnAChain** [comment]
https://github.com/filecoin-project/filecoin-ffi/pull/208 closed with this merge
