### ISSUE TITLE
Actors integration 

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/lotus#7517]
- [ ] consume V7 actors
- [ ] update the runtime
- [ ] add the forks logic

**Comment by ZenGround0** [comment]
## Description

Lotus must consume the v7 specs-actors code and be updated to support the new runtime requirements for `ProveCommitReplicaUpdate`.  It must also be prepared for upgrade logic, though the full migration code for the upgrade is out of scope.

## Done criteria
- Validation of snap deals replica update proofs is threaded all the way through from runtime to ffi
- The network upgrade logic and a stub for the state migration are in place
- lotus compiles consuming the specs-actors v7 module 

### Non-criteria 
- complete upgrade logic including state migration
- the ability of the lotus-miner to run a replica update and proof.
- integration tests of snap deals


## Dependencies
- [ ] https://github.com/filecoin-project/specs-actors/pull/1529
- [ ] https://github.com/filecoin-project/filecoin-ffi/pull/208

## Ongoing work

https://github.com/filecoin-project/lotus/pull/7617

**Comment by BlocksOnAChain** [comment]
@arajasek can we move it to done?

**Comment by jennijuju** [comment]
closing since its moved to Done
