### ISSUE TITLE
Lotus testing -  that will validate the changes we made for SnapDeals

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/lotus#7519]
Needed to validate changes we made for SnapDeals implementation on Lotus

**Comment by ZenGround0** [comment]
## Description

We need to test the basics of lotus-miner's new snap deals functionality.  This should include tests of the FSM and integration tests.  Behavior to be tested should include

* Happy path -- successful snap deals update for a variety of different configurations
* Handling of errors from chain, market, sector-storage interactions to the extent these are possible to induce
* Graceful handling of operator error: for example test that marking a deal-laden sectors as snap deals fails early, test what insufficient funds cases look like, exercise deals that live longer than remaining sector lifetime
* Marking for snap deals while sealing deals into another sector has the intended effects, i.e. snap deals prioritized

TODO -- need more input here this is my biggest blindspot both in terms of how tests are written and all sorts of cases we should try

## Done Criteria
* We've exercised all test cases

### Non-criteria
* sector-storage FFI integration test is not tracked here

## Dependencies
* we need a working FSM first: https://github.com/filecoin-project/lotus/issues/7515

**Comment by ZenGround0** [comment]
Plz add any missing test cases and edit the above issue @magik6k @jennijuju @arajasek.

**Comment by BlocksOnAChain** [comment]
Repeating what @ZenGround0  thinks this issue needs -  add more test scenarios we want to perform on Lotus side for snap deals implementation -  @magik6k @arajasek
