### ISSUE TITLE
lotus-miner storage attach --init --seal ERROR: could not get API info for StorageMiner: repo directory does not exist. Make sure your configuration is correct

### ISSUE THREAD

**Issue by tutorialevideo** [filecoin-project/lotus#7523]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

Anyone can help with this error?

lotus-miner storage attach --init --seal
ERROR: could not get API info for StorageMiner: repo directory does not exist. Make sure your configuration is correct

**Comment by dayou5168** [comment]
It doesn't look like a bug. you can ask for help here in slack：https://filecoinproject.slack.com/archives/CEGN061C5

**Comment by Reiers** [comment]
**Hi @tutorialevideo** 

Thanks for the report. The issue you are experiencing lies elsewhere.

Moving this issue to [Lotus Discussions](https://github.com/filecoin-project/lotus/discussions) for help and troubleshooting.
