### ISSUE TITLE
Lotus API: query highest lane number for a given payment channel address

### ISSUE THREAD

**Issue by tchardin** [filecoin-project/lotus#7526]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

When using an existing payment channel for multiple retrieval deals, a client must find a valid lane and nonce in order to send valid vouchers. If the client doesn't maintain a local state of the payment channel either by syncing the chain or storing a history of all previous vouchers sent, such is the case for a light client running in a web browser, they must query the actor state endpoint of a Lotus node then resolve the chain object(s) associated with the lane state which could result in 2 or more API queries. These queries may significantly slow down a retrieval deal, especially when using a rate limited public endpoint.

### Describe the solution you'd like

In order to reduce the amounts of round trips, it would be great to offer an endpoint to directly query the highest lane number so as to assign a new incremented lane number to execute payments on.

### Describe alternatives you've considered

A light client could also sync some part of the chain via a libp2p gossip endpoint though this would probably be slower.

### Additional context

The implementation should resolve the actor address, read the actor state, load the AMT for the payment channel lanes, then iterate over all the indices to return the highest one.

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and is being completely removed from the code here:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
