### ISSUE TITLE
Bubble up changes to ipfs/go-datastore

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#7536]
As part of https://github.com/ipfs/go-ipfs/issues/6803, go-ipfs Stewards have been bubbling up a new minor version of ipfs/go-datastore and affected packages in the Interplanetary Stack due to some interface changes to pass through a context.  They need help to cover the Filecoin side.  The go-ipfs side isn't blocking on Filecoin, but we do want to have it happen soon so we don't get left in a place of Lotus being able to update dependencies.

## How to determine what Lotus dependencies need to update?
See the internal note [here](https://www.notion.so/protocollabs/Upgrading-Across-Repos-a30be1ab5f004088999c4a9437fcaa0a).

**Comment by BigLep** [comment]
I believe this was resolved with https://github.com/filecoin-project/lotus/pull/7646 but will let @arajasek confirm.

**Comment by arajasek** [comment]
@BigLep Confirmed!
