### ISSUE TITLE
Lotus deletes sealed sector 

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#7545]
### Lotus component

- [X] lotus miner/worker - sealing

### Lotus Version
```text
v1.13.0-rc3
```

### Describe the Bug

Situation: I have my storages mounted on my daemon (for the windowpost) through NFS. I don't want the finalized sealed sector to go from worker -> daemon -> storage machine, so I created a lotus worker on the storage machine with the storage attached.

So, my s-1 storage has 2 URL's: 
- http://daemon:2345/remote
- http://s-1:1111/remote

Server: daemon (runs lotus daemon and miner)
Worker: w-pc1
Worker: w-pc2
Worker: w-c2
Storage: s-1

Lotus walks through the entire sealing process, and ends up with s-1 doing a GET for the sealed sector.
Daemon thinks "oh its on my remote w-c2 machine" so S-1 fetches from http://daemon:2345/remote (stupid, because why not just fetch from http://w-c2:2345/remote directly?)
Storage has it fetched and stored on disk. Now tells the remote to delete the sealed sector (because they don't need it anymore).
Daemon thinks "oh yeah I have that one local, in the NFS mount, lol" and deletes it.

Endpoint: FinalizeSector is stuck and all sealed data (complete sector) is gone.

I know I can prevent this by removing the s-1 worker. But then the daemon would do all the fetching directly into its own mounted NFS drive, effectively making the data do a stupid loop from W-c2 -> daemon -> S-1.

Preventing either one would be best.

**Comment by RobQuistNL** [comment]
Can confirm this is still happening in v1.13.1-rc1 ...

**Comment by Reiers** [comment]
**Hi @RobQuistNL** 

Did the issue get resolved in the merge?
If so, we can close this one :)
