### ISSUE TITLE
lotus msig inspect 不能查询多签地址信息 (Cannot query multi-signature address information)

### ISSUE THREAD

**Issue by jc0803kevin** [filecoin-project/lotus#7556]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
{
    "jsonrpc": "2.0",
    "result": {
        "Version": "1.13.1-dev+calibnet+git.e1deed3b1.dirty",
        "APIVersion": 66560,
        "BlockDelay": 30
    },
    "id": 7878
}
```

### Describe the Bug

t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri 【specs-actors MultisigActorCodeID fil/5/multisig】
t2l5hpmfuof7u2cxwxevvbdqfq4neoxjo4btcye3i 【specs-actors MultisigActorCodeID fil/6/multisig】

lotus msig inspect t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri
![企业微信截图_16351501224345](https://user-images.githubusercontent.com/16516973/138668963-aaaa4ad1-4e8b-497a-b5d4-c2612b1b3b67.png)

lotus msig inspect t2l5hpmfuof7u2cxwxevvbdqfq4neoxjo4btcye3i
![企业微信截图_16351501422681](https://user-images.githubusercontent.com/16516973/138668916-c93e48e0-8386-40e0-9db7-fb1642a73711.png)

代码路径：
https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/codes.go

在老版本【specs-actors MultisigActorCodeID fil/5/multisig】生成的louts 产生的多签地址，但是在 节点升级之后【specs-actors MultisigActorCodeID fil/6/multisig】，查询多签信息返回异常，老的多签地址不能使用

(In the old version [specs-actors MultisigActorCodeID fil/5/multisig] generated multi-signature addresses, but after the node upgrade [specs-actors MultisigActorCodeID fil/6/multisig], querying the multi-signature information returns an exception, the old ones Signed address cannot be used)

### Logging Information

```text
https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/codes.go
```

### Repo Steps

https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/codes.go

**Comment by SgtCoin** [comment]
@jc0803kevin We reviewed the chain and could not find that address (t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri) at any point. Please see below.

```
trey@lab:/usr/local/bin/lotus$ ./lotus state lookup t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri
ERROR: resolve address t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri: actor not found

trey@lab:/usr/local/bin/lotus$ ./lotus state --tipset @100000 lookup t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri
ERROR: resolve address t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri: actor not found

trey@lab:/usr/local/bin/lotus$ ./lotus state --tipset @50000 lookup t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri
ERROR: resolve address t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri: actor not found

trey@lab:/usr/local/bin/lotus$ ./lotus state --tipset @200000 lookup t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri
ERROR: resolve address t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri: actor not found

trey@lab:/usr/local/bin/lotus$ ./lotus state --tipset @400000 lookup t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri
ERROR: resolve address t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri: actor not found

trey@lab:/usr/local/bin/lotus$ ./lotus state --tipset @300000 lookup t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri
ERROR: resolve address t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri: actor not found
```
Can you show us where you pulled this address from?

**Comment by jc0803kevin** [comment]
t2zkfsqbflgl3n4xk6turlw65zn6assjvphibvmri 【specs-actors MultisigActorCodeID fil/5/multisig】 在这个版本离线签名 然后广播生成的。

**Comment by SgtCoin** [comment]
@jc0803kevin 

The fil/6/multisig is the current one, with /fil/7/multisig coming out soon, however your node should just update it when its upgraded.

**Comment by Reiers** [comment]
Closing ticket.

If you are still experiencing problems, open a new ticket or ask in our Discussions <link>forum.
