### ISSUE TITLE
Very large block validation times during / after chocolate update

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#7565]
We are running v1.13.0 on a few nodes with the experimental split-store enabled. A few of these nodes experienced desync issues immediately after the chocolate update (one node had zero issues) with block validation times up to 200+ seconds.

Profiles: https://bafybeiesexrmvtw7kftq4dul5hgbet7izan43imyhttphamwgg54bn3sd4.ipfs.dweb.link/

**Comment by vyzo** [comment]
Fix in #7734.

**Comment by vyzo** [comment]
afaict it should be fixed.
