### ISSUE TITLE
Improve worker lifecycle after disconnection

### ISSUE THREAD

**Issue by neondragon** [filecoin-project/lotus#7570]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

When a worker is disconnected from lotus-miner, there are a number of negative effects, including:

- Miner very frequently logs a warning:
`{"level":"warn","ts":"2021-10-25T16:46:28.776Z","logger":"advmgr","caller":"sector-storage/sched_worker.go:213","msg":"failed to check worker session","error":"RPC client error: sendRequest failed: Post \"http://1.2.3.4:3056/rpc/v0\": dial tcp 1.2.3.4:3056: connect: connection refused"}`

- `lotus-miner storage list` returns an error for storage locations associated with the disconnected worker, even if other workers are online with that location attached
`a41c4a28-13b1-11ec-bfa8-4b0300d2a63e:
	Error: do request: Get "http://1.2.3.4:3056/remote/stat/a41c4a28-13b1-11ec-bfa8-4b0300d2a63e": dial tcp 1.2.3.4:3056: connect: connection refused:`

The only way to resolve these problems is to restart lotus-miner.

This could be improved by:

- When a worker is disconnected, show it in `lotus-miner sealing workers`, with (Disconnected) after it
- Add a command `lotus-miner sealing workers forget <worker_id>` to cleanly remove all worker state from lotus-miner
- Ensure `lotus-miner storage list` and the storage system generally does not attempt to query a disconnected worker if other workers are online

**Comment by Reiers** [comment]
**Hi @neondragon** 

Thanks for this feature request. I will add labels and will assign it to the right team for analysis.

**Comment by marshyonline** [comment]
+1 on this
With having a large sealing cluster this log spam and unnecessary reconnect retries for ever can overwhelm our logs making useful information hard to find at a quick glance - I've had logs grow into the GB's in just a few hours.
A miner restart isn't always possible to kill the log spam when you want to keep a cluster online and remove some workers.

**Comment by kyle-parkinson** [comment]
+1

**Comment by benjaminh83** [comment]
+1

**Comment by rjan90** [comment]
Closing this since both issues have been fixed.

The 'lotus-worker stop' feature correctly disconnects the worker from the lotus-miner and stops the frequent log errors. It also properly disconnects the workers storage which resolves the error that came when running 'lotus-miner storage list'

Thanks for the ticket!
