### ISSUE TITLE
Make it abundantly clear that splitstore is still experimental

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus#7574]
# Problem
While https://github.com/filecoin-project/lotus/discussions/5788 states that the splitstore is experimental, we can do more to make it abundantly clear to "use at your own risk".

The problem we want to solve is to make sure no-one takes a dependency for mission-critical operations on software that is under active development.

# Ideas
1. Update text at https://github.com/filecoin-project/lotus/discussions/5788 with a headeline like

```none
# Attention
⚠️ Use at your own risk!  
This software is still under active development including added functionality, automated testing, and documentation updates.  
Until updated otherwise, this feature is not recommended for production / mission-critical workloads.
``` 

2. Rename ``EnableSplitstore`` to something like ``EXPERIMENTAL_USE_AT_YOUR_OWN_RISK_EnableSplitstore``

3. Get #2 into 1.13.1 and in the release notes:
 - Add the note above
 - Remind folks that they'll need to update their config key if they wish to keep using the splitstore.  They can keep ``EnableSplitstore`` around and it will be respected in a future Lotus version when Splitstore has shipped.

**Comment by arajasek** [comment]
I don't think we're experiencing people confusing this for non-experimental, so I'm gonna close this.
