### ISSUE TITLE
Send log notifications to lotus nodes when we need to force an upgrade

### ISSUE THREAD

**Issue by dayou5168** [filecoin-project/lotus#7582]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Some community members don't follow our notifications, or new community members don't know where to get our update notifications, which can cause them to run to a forked chain and their business is disrupted as a result, causing losses.
you can see the case [here](https://github.com/filecoin-project/lotus/discussions/7576)

### Describe the solution you'd like

Start sending logs to the lotus node 14 days before our mandatory update, increasing the frequency of logs as we get closer to the time
E.g
- More than 14 days before mandatory update. Notification logs are sent every hour
-  More than 7 days before mandatory update. Notification logs are sent every half an hour
-  More than 3 days before mandatory update. Notification logs are sent every 10 minutes

**Comment by rjan90** [comment]
Hey @dayou5168! Do you still think that this is something worth pursuing?

> Some community members don't follow our notifications, or new community members don't know where to get our update notifications, which can cause them to run to a forked chain and their business is disrupted as a result, causing losses.
> you can see the case https://github.com/filecoin-project/lotus/discussions/7576

Although I agree that community members should not need to constantly follow Slack for upgrade announcements, even though it´s probably worth checking in once in a while if your business depends on Lotus.

Lotus/Filecoin also offer multiple other outlets to get mandatory network-upgrade information like https://status.filecoin.io or subscribing to Lotus-releases in Github.

> Start sending logs to the lotus node 14 days before our mandatory update, increasing the frequency of logs as we get closer to the time

We can do a better effort to advertising the existing options, but I´m not sure the businesses that don´t follow along any mandatory network upgrade statuses/outlets will discover the notifications in the logs either?

**Comment by rjan90** [comment]
Closing this feature request as this is not a feature we are going to priotize for now or in the coming year!
