### ISSUE TITLE
Ledger wallet

### ISSUE THREAD

**Issue by longren610** [filecoin-project/lotus#7583]
To use the Ledger wallet, do I have to connect lotus to the main network and synchronize all the Lotus chain?

**Comment by jburnett** [comment]
You'll need a sync'd Lotus node, but not the full chain ("all the Lotus chain")

**Comment by longren610** [comment]
> You'll need a sync'd Lotus node, but not the full chain ("all the Lotus chain")

OK, thanks. Do I need a lot of storage space to synchronize Lotus nodes?

**Comment by dayou5168** [comment]
see minimal requirements here: https://docs.filecoin.io/get-started/lotus/installation/#minimal-requirements
and I think you can ask for help in our slack channel here filecoinio/slack or in lotus forum here:https://github.com/filecoin-project/lotus/discussions

**Comment by f8-ptrk** [comment]
wallet.glif.io does the job quite fine
