### ISSUE TITLE
cancel data-transfer panic in rpc method 'Filecoin.MarketCancelDataTransfer':

### ISSUE THREAD

**Issue by back0893** [filecoin-project/lotus#7584]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version:
Daemon:  1.12.0+mainnet+git.6d8a6c480+api1.4.0
Local: lotus version 1.12.0+mainnet+git.6d8a6c480
lotus-miner version:
Daemon:  1.12.0.21102109+mainnet+git.9b1089295
Local: lotus-miner version 1.12.0.21102109+mainnet+git.9b1089295
```

### Describe the Bug

lotus-miner data-transfers cancel 1634887862506359869 or 
lotus client cancel-transfer 1634551154490714919

both return ERROR: fatal error calling 'Filecoin.MarketCancelDataTransfer': panic in rpc method 
'Filecoin.MarketCancelDataTransfer': runtime error: invalid memory address or nil pointer dereference

### Logging Information

```text
2021-11-01T10:16:11.326+0800    ERROR   rpc     go-jsonrpc/server.go:95 RPC Error: fatal error calling 'Filecoin.MarketCancelDataTransfer': panic in rpc method 'Filecoin.MarketCancelDataTransfer': runtime error: invalid memory address or nil pointer dereference
2021-11-01T10:16:11.326+0800    WARN    rpc     go-jsonrpc/server.go:101        rpc error: fatal error calling 'Filecoin.MarketCancelDataTransfer': panic in rpc method 'Filecoin.MarketCancelDataTransfer': runtime error: invalid memory address or nil pointer dereference
2021-11-01T10:16:12.788+0800    INFO    dt-impl impl/impl.go:286        close channel 12D3KooWNtrJNfD7d9t4LSQ7UNS8zSGQgxeUUADxAX1LYWom1ejA-12D3KooWPRjsZzeZDCN28bF4sFjH9cWrtfLpGjXgeLr2bfEMfSuk-1634887862506359869
2021-11-01T10:16:12.788+0800    ERROR   rpc     go-jsonrpc/handler.go:158       panic in rpc method 'Filecoin.MarketCancelDataTransfer': runtime error: invalid memory address or nil pointer dereference
github.com/filecoin-project/go-jsonrpc.doCall.func1
        /home/bhdev/src_intel/go-jsonrpc/handler.go:158
runtime.gopanic
        /usr/local/go/src/runtime/panic.go:965
runtime.panicmem
        /usr/local/go/src/runtime/panic.go:212
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:734
github.com/filecoin-project/go-data-transfer/transport/graphsync.(*dtChannel).close
        /home/bhdev/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.10.1/transport/graphsync/graphsync.go:1058
github.com/filecoin-project/go-data-transfer/transport/graphsync.(*Transport).CloseChannel
        /home/bhdev/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.10.1/transport/graphsync/graphsync.go:264
github.com/filecoin-project/go-data-transfer/impl.(*manager).CloseDataTransferChannel
        /home/bhdev/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.10.1/impl/impl.go:294
github.com/filecoin-project/lotus/node/impl.(*StorageMinerAPI).MarketCancelDataTransfer
        /home/bhdev/src_intel/lotus/node/impl/storminer.go:617
reflect.Value.call
        /usr/local/go/src/reflect/value.go:476
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:337
github.com/filecoin-project/lotus/metrics.proxy.func1
        /home/bhdev/src_intel/lotus/metrics/proxy.go:60
github.com/filecoin-project/lotus/api.(*StorageMinerStruct).MarketCancelDataTransfer
        /home/bhdev/src_intel/lotus/api/proxy_gen.go:3891
reflect.Value.call
        /usr/local/go/src/reflect/value.go:476
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:337
github.com/filecoin-project/go-jsonrpc/auth.PermissionedProxy.func1
        /home/bhdev/src_intel/go-jsonrpc/auth/auth.go:62
github.com/filecoin-project/lotus/api.(*StorageMinerStruct).MarketCancelDataTransfer
        /home/bhdev/src_intel/lotus/api/proxy_gen.go:3891
reflect.Value.call
        /usr/local/go/src/reflect/value.go:476
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:337
github.com/filecoin-project/go-jsonrpc.doCall
        /home/bhdev/src_intel/go-jsonrpc/handler.go:162
github.com/filecoin-project/go-jsonrpc.(*RPCServer).handle
        /home/bhdev/src_intel/go-jsonrpc/handler.go:259
```

**Comment by dirkmc** [comment]
Fixed by https://github.com/filecoin-project/lotus/pull/7538
