### ISSUE TITLE
self-transfer: message can execute successfully when msg.value larger than address.balance

### ISSUE THREAD

**Issue by web3Zhaoxinlong** [filecoin-project/lotus#7588]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [X] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
mainnet -- 1.13.0
calibration -- 1.13.0
```

### Describe the Bug

detail can be found at:

1. [filfox](https://filfox.info/en/message/bafy2bzacebr2quxfina5pcy3uudh5lhrbapmbdaxd3l5qfkfhaun6yq44qxmu)
2. [filscout](https://filscout.com/en/message/bafy2bzacebr2quxfina5pcy3uudh5lhrbapmbdaxd3l5qfkfhaun6yq44qxmu)
3. [filscan](https://filscan.io/tipset/message-detail?cid=bafy2bzacebr2quxfina5pcy3uudh5lhrbapmbdaxd3l5qfkfhaun6yq44qxmu)

### Logging Information

```text
normal information, no debug logs.
```

### Repo Steps

```
        const param1
          = {
            Version: 0,
            To: this.targetAddress,
            From: this.address,
            Nonce: 0,
            Value: new BigNumber('1999999999').times(1e18)
              .integerValue(),
            GasLimit: 0,
            GasFeeCap: '0',
            GasPremium: '0',
            Method: 0,
            Params: ''
          }
        const param2 = { MaxFee: '1000000000000000' }
        const param3 = []
```

**Comment by dtynn** [comment]
when you use equaled `From` & `To` addresses, nothing will happen except gas charging for the execution.
according to the code lines [here](https://github.com/filecoin-project/lotus/blob/v1.13.0/chain/vm/vm.go#L873-L875)
and all filecoin implementations must be the same,.

so, it looks abnormal, but it's `correct` , at least for now.

----
当 `From` 和 `To` 一致的时候，实际上啥也没发生。因此 Value 可以任意填写。
代码在[这里](https://github.com/filecoin-project/lotus/blob/v1.13.0/chain/vm/vm.go#L873-L875)
并且由于涉及到执行结果的统一性，虽然这段代码出现在 lotus 里面，但是事实上所有的 Filecoin 实现目前都得遵循这个逻辑。

这才导致了这个看上去不合理，但是在 `Filecoin` 语境下是正确的结果

**Comment by web3Zhaoxinlong** [comment]
I know "nothing happens" (but gas), but it could be better if all messages follow the same rules.
such message, in which msg.value > add.balance may mislead people.

**Comment by dtynn** [comment]
> I know "nothing happens" (but gas), but it could be better if all messages follow the same rules. such message, in which msg.value > add.balance may mislead people.

I DO AGREE 😉

**Comment by RobQuistNL** [comment]
This is explicitly done to make the throughput faster, since looking up the balance of an account takes time. If from & to are the same, there's no need to do that lookup.

**Comment by web3Zhaoxinlong** [comment]
> This is explicitly done to make the throughput faster, since looking up the balance of an account takes time. If from & to are the same, there's no need to do that lookup.

hahahaha
ridiculous

**Comment by arajasek** [comment]
duplicate #7596
