### ISSUE TITLE
MacOS: File retrieval problem (Array too large ??)

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/lotus#763]
## What is the problem?

I'm running into an issue retrieving a valid **Data CID** from a Lotus Storage Miner. I can validate that the file is on the network.

## Reproduction

Verifying the **Data CID** exists and is of a `byte` size that is viable (greater than 127 minimum bytes).

```sh
lotus client find
```

Response

```sh
bafkreieuk7h4zs5alzpdyhlph4lxkefowvwdho3a3pml6j7dam5mipzaii
LOCAL
RETRIEVAL
t01424@12D3KooWBraTQud3Th21YNgru48cJjVhVtzC3Xtp6cYpcKi9MEFU-0.000000000000061236fil-30618b
```

The attempt to retrieve the file.

```sh
lotus client retrieve bafkreieuk7h4zs5alzpdyhlph4lxkefowvwdho3a3pml6j7dam5mipzaii test.txt
```

The error response

```sh
WARN
main
lotus/main.go:72
RetrieveUnixfs: retrieval exchange: reading fetchBlock response: t.Data: array too large (30618)
```

**Comment by magik6k** [comment]
Fixed
