### ISSUE TITLE
lotus-miner retrieval-deals list add verbose

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#7638]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

Please add a -v verbose flag to lotus-miner retrieval-deals list and include more details including data and time stamps for each line of retrievals. See current output. This is from v1.13.1-rc2 markets node.

[lotus-miner retrieval-deals list.txt](https://github.com/filecoin-project/lotus/files/7557769/lotus-miner.retrieval-deals.list.txt)
.

**Comment by jennijuju** [comment]
@stuberman could you please clarify if you want time stamps for retrieval deals' data transfer or deal life time for retrieval deals?

**Comment by stuberman** [comment]
To be consistent, I would lie it similar to `lotus-miner storage-deals list -v`,  deal transfer start date and time as well as any other details we can use.


_Retrieval deals list_
**Creation         Verified  ProposalCid                                                  DealId  State             Client                                                                                  Size   Price               Duration  TransferChannelID  Message**

> Aug 25 01:37:27  false     bafyreie7sxmn76mphh7aq6syo7rqblrxh2yhotqmre5zrt7fc27nnf2xha  0       StorageDealError  f3qfrxne7cg4ml45ufsaxqtul2c33kmlt4glq3b4zvha3msw4imkyi45iyhcpnqxt2iuaikjmmgx2xlr5myuxa  64KiB  0.000001160948 FIL  580474                       deal rejected: false

> Aug 25 13:03:28  false  bafyreih7dvodajltgzzqu4snf6pvaccml6vep7g4vgfvo3mvbdai7qfpve  5023   StorageDealExpired  f1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i                                               128KiB  0 FIL                     702942    

_Storage deals list_
**lotus-miner retrieval-deals list
Receiver                                              DealID               Payload      State                 PricePerByte  BytesSent    Message**

> 12D3KooWSrVTGNQP7UaXJYB8r6a2bfEcHzt2gnrHrrqwu5zYK1AD  2084                 ...tzsezn6g  DealStatusUnsealing   0             0

**Comment by Angelo-gh3990** [comment]
@stuberman , would a be a good idea to have a bytes/sec column as well. To know how the retrieval is performing. As feedback if a client asks.

**Comment by f8-ptrk** [comment]
> To be consistent, I would lie it similar to `lotus-miner storage-deals list -v`, deal transfer start date and time as well as any other details we can use.
> 
> _Retrieval deals list_ **Creation Verified ProposalCid DealId State Client Size Price Duration TransferChannelID Message**
> 
> > Aug 25 01:37:27  false     bafyreie7sxmn76mphh7aq6syo7rqblrxh2yhotqmre5zrt7fc27nnf2xha  0       StorageDealError  f3qfrxne7cg4ml45ufsaxqtul2c33kmlt4glq3b4zvha3msw4imkyi45iyhcpnqxt2iuaikjmmgx2xlr5myuxa  64KiB  0.000001160948 FIL  580474                       deal rejected: false
> 
> > Aug 25 13:03:28  false  bafyreih7dvodajltgzzqu4snf6pvaccml6vep7g4vgfvo3mvbdai7qfpve  5023   StorageDealExpired  f1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i                                               128KiB  0 FIL                     702942
> 
> _Storage deals list_ **lotus-miner retrieval-deals list Receiver DealID Payload State PricePerByte BytesSent Message**
> 
> > 12D3KooWSrVTGNQP7UaXJYB8r6a2bfEcHzt2gnrHrrqwu5zYK1AD  2084                 ...tzsezn6g  DealStatusUnsealing   0             0

the json output of the deal list combines deals and transfers already. but it would be nice to see in the formatted list too

**Comment by stuberman** [comment]
I would like to see the following columns added to see a list of retrieval deals:
Date
Time
Duration
CID
Bytes/second

**Comment by jennijuju** [comment]
@dirkmc ^

**Comment by jennijuju** [comment]
if still needed - please create a ticket in boost!
