### ISSUE TITLE
Cannot change from multisig address to standard address.

### ISSUE THREAD

**Issue by SgtCoin** [filecoin-project/lotus#7665]
### Discussed in https://github.com/filecoin-project/lotus/discussions/6925

<div type='discussions-op-text'>

<sup>Originally posted by **Reskorey** July 28, 2021</sup>
I changed the owner address fron normal address to multisig address. https://github.com/filecoin-project/lotus/pull/5342   , but I can not chang owner address from multisig address to normal address?   Lotus  version v1.11.0</div>

**Comment by SgtCoin** [comment]
Confirmed with @arajasek that this is not currently possible. Creating issue for tracking purposes.

**Comment by rjan90** [comment]
Hey!

Closing this ticket as it´s now possible to change the owner-address from a msig to a single signer address, either by using the `./lotus-shed miner-multisig` tool, or by using `lotus msig propose` with encoded params:

### Guide using `./lotus-shed`:

**1: Propose change from msig:**
`./lotus-shed miner-multisig --from=<msig-address-1> --multisig=<msig> --miner=<MinerID> propose-change-owner   <newOwnerAddress>
`

**2: Approve change on msig-address-2:**
`./lotus-shed miner-multisig --from=<msig-address-2> --multisig=<msig> --miner=<MinerID> approve-change-owner   <newOwnerAddress> <txnID> <msig-address-1/proposing-address>
`

**3: Confirm owner-change with new address:**
`lotus-miner  actor  set-owner --really-do-it <newOwnerAddress> <newOwnerAddress>`
