### ISSUE TITLE
Removed log from ~/.lotus/datastore/chain, triggered panic

### ISSUE THREAD

**Issue by SgtCoin** [filecoin-project/lotus#7666]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.13.1-dev+mainnet+git.d9100981a
```

### Describe the Bug

**From slack**

Has anyone encountered this:
2021-11-23T05:00:59.769+0800	INFO	modules	modules/services.go:162	subscribing to pubsub topic /fil/blocks/testnetnet
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf71cce]
```

I deleted some vlog in the chain because I ran out of space
I can no longer run lotus daemon
The files were earlier in ~/.lotus/datastore/chain

### Logging Information

```text
Gathering data
```

### Repo Steps

Not required.

**Comment by SgtCoin** [comment]
Waiting on user response in slack. 
https://filecoinproject.slack.com/archives/CEGN061C5/p1637614969158000

**Comment by SgtCoin** [comment]
[result.txt](https://github.com/filecoin-project/lotus/files/7619146/result.txt)

**Comment by SgtCoin** [comment]
Asking user to review https://lotus.filecoin.io/docs/set-up/chain-management/#compacting-the-chain-data to see if he can sync back up with the chain.

**Comment by rjan90** [comment]
Closing this issue as removing a couple of vlog-files from the datastore is expected to cause issues. The correct way of pruning the chain is to fully remove the chain data and import from a snapshot.

SplitStoreV2 will add automatic pruning which should mitigate that issue of users run out of disk space.
