### ISSUE TITLE
Stale ( not existing ) data-transfers after separation can not be removed

### ISSUE THREAD

**Issue by j1v** [filecoin-project/lotus#7687]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner version
Daemon:  1.13.0+mainnet+git.7a55e8e89.dirty+api1.2.0
Local: lotus-miner version 1.13.0+mainnet+git.7a55e8e89.dirty
```

### Describe the Bug

after going trough the process of separating lotus markets from miner, i have left with some data-transfers in "Ongoing" state although I have all of them cancelled before starting the migration and shutting down the old monolith miner

after migration cancelling them is not possible, as the process fails with :

`ERROR: No channel for channel ID 12D3....`

### Logging Information

```text
lotusmarkets@filecoin:~$ lotus-miner data-transfers cancel 1636854811581798758
ERROR: No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636854811581798758

2021-11-25T10:06:21.365+0200	WARN	rpc	go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:279	error in RPC call to 'Filecoin.MarketCancelDataTransfer': No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636854811581798758
```

Problem has been discussed in slack : https://filecoinproject.slack.com/archives/CEGN061C5/p1637068504024600

**Comment by j1v** [comment]
19 days later nothing has changed. 

Trtansfers still persist in the `data-transfers list` and on every restart of lotus-miner markets process it tries to resume them. 

```
ID                   Status   Receiving From  Root Cid     Initiated?  Transferred  Voucher
1635873640376399168  Ongoing  ...NMjoDien     ...i8bhuygp  N           13.23GiB     ...sfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea"}}
...

```

```
lotusmarkets@filecoin:~$ lotus-miner data-transfers cancel 1635873640376399168
ERROR: No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1635873640376399168
```

```
lotusmarkets@filecoin:~$ grep sfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea /var/log/lotus/markets.log
2021-12-13T09:45:08.801+0200	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventRestart", "proposal CID": "bafyreicqbkdyel2xhxpzeimzsfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea", "state": "StorageDealProviderTransferAwaitRestart", "message": ""}
2021-12-13T15:27:42.067+0200	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventRestart", "proposal CID": "bafyreicqbkdyel2xhxpzeimzsfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea", "state": "StorageDealProviderTransferAwaitRestart", "message": ""}
2021-12-13T21:30:34.588+0200	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventRestart", "proposal CID": "bafyreicqbkdyel2xhxpzeimzsfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea", "state": "StorageDealProviderTransferAwaitRestart", "message": ""}
2021-12-14T03:52:59.652+0200	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventRestart", "proposal CID": "bafyreicqbkdyel2xhxpzeimzsfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea", "state": "StorageDealProviderTransferAwaitRestart", "message": ""}
2021-12-14T09:53:55.252+0200	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventRestart", "proposal CID": "bafyreicqbkdyel2xhxpzeimzsfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea", "state": "StorageDealProviderTransferAwaitRestart", "message": ""}
2021-12-14T11:00:20.551+0200	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventRestart", "proposal CID": "bafyreicqbkdyel2xhxpzeimzsfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea", "state": "StorageDealProviderTransferAwaitRestart", "message": ""}
2021-12-14T13:22:27.477+0200	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventRestart", "proposal CID": "bafyreicqbkdyel2xhxpzeimzsfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea", "state": "StorageDealProviderTransferAwaitRestart", "message": ""}
2021-12-14T13:32:27.009+0200	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventRestart", "proposal CID": "bafyreicqbkdyel2xhxpzeimzsfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea", "state": "StorageDealProviderTransferAwaitRestart", "message": ""}
2021-12-14T13:43:14.974+0200	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventRestart", "proposal CID": "bafyreicqbkdyel2xhxpzeimzsfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea", "state": "StorageDealProviderTransferAwaitRestart", "message": ""}
2021-12-14T13:52:38.988+0200	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventRestart", "proposal CID": "bafyreicqbkdyel2xhxpzeimzsfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea", "state": "StorageDealProviderTransferAwaitRestart", "message": ""}
2021-12-14T14:06:06.463+0200	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventRestart", "proposal CID": "bafyreicqbkdyel2xhxpzeimzsfhpsiy5e67bjjfvlf4gu3dey4bt4qpvea", "state": "StorageDealProviderTransferAwaitRestart", "message": ""}
```

**Comment by Reiers** [comment]
**Hi @j1v** 

This should be fixed in a upcoming release. 
If you want to fix it right away:
upgrade to tag : `v1.13.2-rc4`
https://github.com/filecoin-project/lotus/releases/tag/v1.13.2-rc4

If you want them gone on the latest stable release, try this:
Reboot the markets process, deleted everything on deal-staging folder, start it up again and enter this cmd within 30sec:
`lotus-miner data-transfers list | grep Ongoing | awk '{ system("lotus-miner data-transfers cancel " $1) }'
`
This is a temporary fix - but will clean up the stale data-transfers and unfortunaly delete all Ongoing transfers. 
_But if Estuary is the client - they will try to send the same data again._ 

**If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help** 

Closing ticket.

**Comment by j1v** [comment]
lotusmarkets@filecoin:~$ lotus-miner data-transfers list --verbose | grep "Ongoing" | awk '{print $1}' | xargs -n 1 -t lotus-miner data-transfers cancel
lotus-miner data-transfers cancel 1635873640376399168
ERROR: No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1635873640376399168

lotus-miner data-transfers cancel 1635873640376399516
ERROR: No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1635873640376399516

lotus-miner data-transfers cancel 1635873640376399518
ERROR: No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1635873640376399518

lotus-miner data-transfers cancel 1635873640376400722
ERROR: No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1635873640376400722

lotus-miner data-transfers cancel 1636854811581798758
ERROR: No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636854811581798758

lotus-miner data-transfers cancel 1636854811581798764
ERROR: No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636854811581798764

lotus-miner data-transfers cancel 1636854811581798765
ERROR: No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636854811581798765

lotus-miner data-transfers cancel 1636854811581798788
ERROR: No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636854811581798788

lotus-miner data-transfers cancel 1636867944706654323
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654323

lotus-miner data-transfers cancel 1636867944706654345
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654345

lotus-miner data-transfers cancel 1636867944706654346
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654346

lotus-miner data-transfers cancel 1636867944706654347
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654347

lotus-miner data-transfers cancel 1636867944706654348
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654348

lotus-miner data-transfers cancel 1636867944706654397
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654397

lotus-miner data-transfers cancel 1636867944706654427
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654427

lotus-miner data-transfers cancel 1636867944706654428
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654428

lotus-miner data-transfers cancel 1636970222760073931
ERROR: No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636970222760073931

lotus-miner data-transfers cancel 1636998036692035750
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636998036692035750

lotus-miner data-transfers cancel 1637000602566713105
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1637000602566713105

lotus-miner data-transfers cancel 1637000602566713108
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1637000602566713108

**Comment by j1v** [comment]
Still the same with 1.13.2-rc4
```
lotusmarkets@filecoin:~$ lotus-miner version
Daemon:  1.13.2-rc4+mainnet+git.e05fdf892.dirty+api1.2.0
Local: lotus-miner version 1.13.2-rc4+mainnet+git.e05fdf892.dirty
```

```
lotusmarkets@filecoin:~$ lotus-miner data-transfers list --verbose | grep "Ongoing" | awk '{print $1}' | xargs -n 1 -t lotus-miner data-transfers cancel
lotus-miner data-transfers cancel 1635873640376399168
ERROR: No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1635873640376399168

lotus-miner data-transfers cancel 1635873640376399516
ERROR: No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1635873640376399516

lotus-miner data-transfers cancel 1635873640376399518
ERROR: No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1635873640376399518

lotus-miner data-transfers cancel 1635873640376400722
ERROR: No channel for channel ID 12D3KooWGBWx9gyUFTVQcKMTenQMSyE2ad9m7c9fpjS4NMjoDien-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1635873640376400722

lotus-miner data-transfers cancel 1636854811581798758
ERROR: No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636854811581798758

lotus-miner data-transfers cancel 1636854811581798764
ERROR: No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636854811581798764

lotus-miner data-transfers cancel 1636854811581798765
ERROR: No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636854811581798765

lotus-miner data-transfers cancel 1636854811581798788
ERROR: No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636854811581798788

lotus-miner data-transfers cancel 1636867944706654323
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654323

lotus-miner data-transfers cancel 1636867944706654345
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654345

lotus-miner data-transfers cancel 1636867944706654346
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654346

lotus-miner data-transfers cancel 1636867944706654347
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654347

lotus-miner data-transfers cancel 1636867944706654348
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654348

lotus-miner data-transfers cancel 1636867944706654397
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654397

lotus-miner data-transfers cancel 1636867944706654427
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654427

lotus-miner data-transfers cancel 1636867944706654428
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636867944706654428

lotus-miner data-transfers cancel 1636970222760073931
ERROR: No channel for channel ID 12D3KooWCVXs8P7iq6ao4XhfAmKWrEeuKFWCJgqe9jGDMTqHYBjw-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636970222760073931

lotus-miner data-transfers cancel 1636998036692035750
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1636998036692035750

lotus-miner data-transfers cancel 1637000602566713105
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1637000602566713105

lotus-miner data-transfers cancel 1637000602566713108
ERROR: No channel for channel ID 12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWNfaZqw9DD7mTkyfzudR3vFT9HcdBnaSNLGcuaANMFTh4-1637000602566713108
```

**Comment by Reiers** [comment]
I will re-open the ticket. Reports indicates that some users are still experiencing this issue on latest release. 

lotus-miner version
```
Daemon:  1.13.2-rc4+mainnet+git.e05fdf892.dirty+api1.2.0
Local: lotus-miner version 1.13.2-rc4+mainnet+git.e05fdf892.dirty
```

**Comment by j1v** [comment]
Actually I think it could be a different issue from what you are referring.

**Comment by TippyFlitsUK** [comment]
Hey @j1v 

I have not been able to reproduce this issue in https://github.com/filecoin-project/lotus/releases/tag/v1.15.0.

Can you please advise if you are still seeing this?

Many thanks!

**Comment by j1v** [comment]
Yes, those are still in my data transfers list and can not be removed :(

**Comment by rjan90** [comment]
Closing this ticket given that the Lotus-Miner Markets subsystem is EOL, and the code will be removed after the nv21 upgrade.
