### ISSUE TITLE
Estuary deal gets stuck in StorageDealPublish stage.

### ISSUE THREAD

**Issue by NSC-FIL** [filecoin-project/lotus#7736]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.13.2-rc1+mainnet+git.52c7fa242
lotus-miner version 1.13.2-rc1+mainnet+git.52c7fa242
```

### Describe the Bug

An Estuary deal is stuck in StorageDealPublish stage and no sector sealed for over 24 hours.  Normally the deal would seal within 12 hours. No error message is posted or found in any other logs.

### Logging Information

```text
Logs can be found in the MinerX.3 google drive under Nelson_v1.13.2-rc1.
Running lotus-miner successfully and sealing other client deals using the config.toml below:
[API]
  ListenAddress = "/ip4/127.0.0.1/tcp/2345/http"
  RemoteListenAddress = "127.0.0.1:2345"
  Timeout = "30s"

[Backup]
  DisableMetadataLog = false

[Libp2p]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/24001", "/ip6/::/tcp/0"]
  AnnounceAddresses = ["/ip4/184.152.161.170/tcp/24001"]
  NoAnnounceAddresses = []
  DisableNatPortMap = false
  ConnMgrLow = 200
  ConnMgrHigh = 500
  ConnMgrGrace = "20s"

[Pubsub]
  Bootstrapper = false
  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"

[Subsystems]
  EnableMining = true
  EnableSealing = true
  EnableSectorStorage = true
  EnableMarkets = true
  SealerApiInfo = ""
  SectorIndexApiInfo = ""

[Dealmaking]
  ConsiderOnlineStorageDeals = true
  ConsiderOfflineStorageDeals = true
  ConsiderOnlineRetrievalDeals = true
  ConsiderOfflineRetrievalDeals = true
  ConsiderVerifiedStorageDeals = true
  ConsiderUnverifiedStorageDeals = true
  PieceCidBlocklist = []
  ExpectedSealDuration = "12h0m0s"
  MaxDealStartDelay = "336h0m0s"
  PublishMsgPeriod = "1h0m0s"
  MaxDealsPerPublishMsg = 8
  MaxProviderCollateralMultiplier = 2
  MaxStagingDealsBytes = 0
  SimultaneousTransfersForStorage = 9
  SimultaneousTransfersForRetrieval = 2
  StartEpochSealingBuffer = 480
  Filter = "/home/supernsc/lotusminer_main/dealfilter.pl"
  RetrievalFilter = ""
  [Dealmaking.RetrievalPricing]
    Strategy = "default"
    [Dealmaking.RetrievalPricing.Default]
      VerifiedDealsFreeTransfer = false
    [Dealmaking.RetrievalPricing.External]
      Path = ""

[Sealing]
  MaxWaitDealsSectors = 1
  MaxSealingSectors = 2
  MaxSealingSectorsForDeals = 2
  CommittedCapacitySectorLifetime = "46.656ms"
  WaitDealsDelay = "12h0m0s"
  AlwaysKeepUnsealedCopy = false
  FinalizeEarly = true
  CollateralFromMinerBalance = false
  AvailableBalanceBuffer = "0 FIL"
  DisableCollateralFallback = false
  BatchPreCommits = true
  MaxPreCommitBatch = 256
  PreCommitBatchWait = "24h0m0s"
  PreCommitBatchSlack = "3h0m0s"
  AggregateCommits = false
  MinCommitBatch = 4
  MaxCommitBatch = 819
  CommitBatchWait = "24h0m0s"
  CommitBatchSlack = "1h0m0s"
  BatchPreCommitAboveBaseFee = "0.00000000032 FIL"
  AggregateAboveBaseFee = "0.00000000015 FIL"
  TerminateBatchMax = 100
  TerminateBatchMin = 1
  TerminateBatchWait = "5m0s"

[Storage]
  ParallelFetchLimit = 5
  AllowAddPiece = true
  AllowPreCommit1 = true
  AllowPreCommit2 = true
  AllowCommit = true
  AllowUnseal = true
  ResourceFiltering = "hardware"

[Fees]
  MaxPreCommitGasFee = "0.3 FIL"
  MaxCommitGasFee = "0.4 FIL"
  MaxTerminateGasFee = "0.5 FIL"
  MaxWindowPoStGasFee = "3 FIL"
  MaxPublishDealsFee = "0.3 FIL"
  MaxMarketBalanceAddFee = "0.3 FIL"
  [Fees.MaxPreCommitBatchGasFee]
    Base = "0 FIL"
    PerSector = "0.02 FIL"
  [Fees.MaxCommitBatchGasFee]
    Base = "0 FIL"
    PerSector = "0.03 FIL"

[Addresses]
  PreCommitControl = []
  CommitControl = []
  TerminateControl = []
  DealPublishControl = []
  DisableOwnerFallback = false
  DisableWorkerFallback = false

[DAGStore]
  RootDir = ""
  MaxConcurrentIndex = 5
  MaxConcurrentReadyFetches = 0
  MaxConcurrencyStorageCalls = 100
  GCInterval = "1m0s"
```

### Repo Steps

Run lotus-miner and send Estuary deal to it.  May be related to partial data transfer issues?

**Comment by magik6k** [comment]
What do you see in `lotus-miner storage-deals pending-publish`?

**Comment by NSC-FIL** [comment]
Yes. I check it routinely. It was empty.

**Comment by BBQFIL** [comment]
关于这个交易，miner日志显示它进行到了哪一步？或者任何关于它最后状态的信息？

**Comment by TippyFlitsUK** [comment]
Hey @NSC-FIL 

Are you still seeing this behaviour in recent Lotus versions?

**Comment by TippyFlitsUK** [comment]
Many thanks!!
