### ISSUE TITLE
state machine

### ISSUE THREAD

**Issue by sjxqqq** [filecoin-project/lotus#7740]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lorus-miner v1.13.0

fsm.go/fsmPlanners
GetTicket：planOne(
  on(SectorTicket{}, preCommit1),
  on(SectorCommitFailed{}, CommitFailed),
)
......................

state_sealing.go/handleGetTicket()
...
return ctx.Send(SectorSealPreCommit1Failed{..........})
```

### Describe the Bug

The SectorSealPreCommit1Failed state is not defined in GetTicket, but this state is indeed used in handleGetTicket()

### Logging Information

```text
2021-12-05T09:19:41.215+0800    ERROR   evtsm   go-statemachine@v1.0.1/machine.go:86    Executing event planner failed: running planner for state GetTicket failed:
    github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).plan
        /home/lwc/gitlab/filecoin-project/lotus/extern/storage-sealing/fsm.go:301
  - planner for state GetTicket received unexpected event sealing.SectorSealPreCommit1Failed ({User:getting ticket failed: getting precommit info: handleSealFailed(345356): temp error: call StateGetActor ,more than 10 second not retuen, time out}):
    github.com/filecoin-project/lotus/extern/storage-sealing.planOne.func1
        /home/lwc/gitlab/filecoin-project/lotus/extern/storage-sealing/fsm.go:643
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by Reiers** [comment]
Hi @sjxqqq 

Thanks for the report. Im unable to reproduce the issue here.
Can you share bit more, logs, and what caused this to happen? 

Thank you!
