### ISSUE TITLE
Add synchronous UNS job amount to configuration  

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7747]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

for better managing sealing resources. this will also help with SP that has many non-fast retrievals.

### Describe the solution you'd like

have a configurable variable for how many unseal job a worker can have.

**Comment by Angelo-gh3990** [comment]
It would be great if we can have our workers (PC1) do the unseal ... Right now when you enable unseal on the miner it works, but when you disbale it on the miner and enable it on the PC1 worker as an example it looks like it's wants to start but it time's out. Looks like it's not getting the data through the API from the miner to start the unsealing on the worker.
So the reason for this is so we can regulate it better on the miner for now to not overload it.

**Comment by benjaminh83** [comment]
Limiting the # of UNS jobs is a quick fix for making sure we do not overrun our lotus-miner with UNS jobs. This is a good start, but it does not solve the bug that it currently holding us from running UNS jobs seamlessly on our worker (Like the PC1 worker would be perfect for this task). Please see this perfect decription of the issue that is still present: 

https://github.com/filecoin-project/lotus/issues/7763
 
We need the UNS jobs **not running on the miner itself**, so worker bug should be fixed.
