### ISSUE TITLE
Expose mechanism to DeclareFaultsRecovered manually 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7748]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

after faulting a sector, most of the time it takes SP less than 24 hours to recover the sector. As soon as they've done that, they should be able to manually declare the sector to be recovered .

### Describe the solution you'd like

expose an api to call [DeclareFaultsRecovered](https://github.com/filecoin-project/specs-actors/blob/4d19cab4cc26e65e97bdaecd3f8c781e52b586ca/actors/builtin/miner/miner_actor.go#L1662)

have a cli like `lotus-miner proving declare-recovery [sector id1........sector idN]`

**Comment by jennijuju** [comment]
add api to lotus example https://github.com/filecoin-project/lotus/pull/6642/files

after adding this, run `make gen` will generate the api docs

**Comment by Aloxaf** [comment]
Is there any advantage to declare recovered as soon as sectors are recovered? As I understand, WindowPost will not be submitted and SP's power won't be recovered, until the deadline is reached.
