### ISSUE TITLE
`sectors update-state` should guard against senditg events to non-existing sectors

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#7754]
When that happens, a ghost sector will be created, which can mess with the sealing fsm in a bunch of very weird ways - I just had a sector like this cause my deals to get stuck when trying to create a new sector.

The 'ghost' sector wasn't in `lotus-miner sector list`, but `lotus-miner sectors status --log [id]` did show it.

**Comment by TippyFlitsUK** [comment]
addressed in https://github.com/filecoin-project/lotus/pull/7762
