### ISSUE TITLE
double forking

### ISSUE THREAD

**Issue by PerrywLiu** [filecoin-project/lotus#7775]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.11.2-rc2+2k+git.8a6d7f7.dirty+api1.2.0
Local: lotus-miner version 1.11.2-rc2+2k+git.8a6d7f7.dirty
```

### Describe the Bug

1. I build target with make 2k
2. run lotus daemon and lotus-miner
3. it can produce block normal
4. when I saw logs and find Error as 'double-fork mining faults'

### Logging Information

```text
<!!> SLASH FILTER ERROR: produced block would trigger 'double-fork mining faults' consensus fault; miner: t022957; bh: bafy2bzacebqez74uwx3li6jxkzktv76oytt2tets44g4ef3ezvpznpzpc3qxq, other: bafy2bzaceapw6sc4q22lu765xsgvynqj5dpfu3o7ux6oivjesi7lltsapqtwu

2021-12-10T22:23:05.270+0800	WARN	miner	miner/miner.go:498	completed mineOne	{"tookMilliseconds": 5677, "forRound": 86759, "baseEpoch": 86758, "baseDeltaSeconds": 18828, "nullRounds": 0, "lateStart": true, "beaconEpoch": 1456543, "lookbackEpochs": 900, "networkPowerAtLookback": "106496", "minerPowerAtLookback": "65536", "isEligible": true, "isWinner": true, "error": null}
2021-12-10T22:23:11.440+0800	WARN	miner	miner/miner.go:498	completed mineOne	{"tookMilliseconds": 5726, "forRound": 86759, "baseEpoch": 86758, "baseDeltaSeconds": 18834, "nullRounds": 0, "lateStart": true, "beaconEpoch": 1456543, "lookbackEpochs": 900, "networkPowerAtLookback": "106496", "minerPowerAtLookback": "65536", "isEligible": true, "isWinner": true, "error": null}
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by arajasek** [comment]
I don't think it's too unusual to have something like this on a devnet.
