### ISSUE TITLE
force to remove abnormal sector 

### ISSUE THREAD

**Issue by narkissos** [filecoin-project/lotus#7798]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

When I use `lotus-miner sectors terminate --really-do-it xxx` or `update-state` to remove abnormal sectors to make my workplace tidy, it always showed `ERROR: normal shutdown of state machine`.
Hope to add a cmd to remove these disgusting sectors mannualy.

**Comment by Reiers** [comment]
Hi @narkissos 

Thanks for the report. This is fixed in the latest release.
Please upgrade Lotus.

Link to latest tags [here.](https://github.com/filecoin-project/lotus/tags)

Closing Lotus issue ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

**Comment by RobQuistNL** [comment]
This is not resolved
