### ISSUE TITLE
brew install lotus Error: cargo is not installed

### ISSUE THREAD

**Issue by AllanOricil** [filecoin-project/lotus#7830]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
N/A
```

### Describe the Bug

I tried to install Lotus on my Mac M1 using homebrew and I keep getting this error, which makes no sense

````bash
+ echo '[build_from_source] Error: cargo is not installed.'
[build_from_source] Error: cargo is not installed.
+ echo '[build_from_source] install Rust toolchain to resolve this problem.'
````

In the image below you can see my PATH. And in the path I have cargo binnary.

![image](https://user-images.githubusercontent.com/55927613/146693991-4d222215-2967-479f-91f2-705069ad2812.png)

I can also run `cargo --version` and it gives me `cargo 1.57.0 (b2e52d7ca 2021-10-21)`

So what is the problem?

### Logging Information

```text
N/A
```

### Repo Steps

Follow these steps for Mac Users: https://lotu.sh/docs/set-up/install/#build-from-source

**Comment by Reiers** [comment]
**Hi @AllanOricil** 

Thanks for reporting - Take a look at this one: (https://github.com/filecoin-project/lotus/issues/7597)

**To solve this issue to this:**

```
reiers@M1Max-protocol ~ % rustup-init  

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  /Users/reiers/.rustup

This can be modified with the RUSTUP_HOME environment variable.

The Cargo home directory located at:

  /Users/reiers/.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  /Users/reiers/.cargo/bin

This path will then be added to your PATH environment variable by
modifying the profile files located at:

  /Users/reiers/.profile
  /Users/reiers/.bash_profile
  /Users/reiers/.zshenv

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.

Current installation options:


   default host triple: aarch64-apple-darwin
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

info: profile set to 'default'
info: default host triple is aarch64-apple-darwin
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: default toolchain set to 'stable-aarch64-apple-darwin'

  stable-aarch64-apple-darwin unchanged - rustc 1.57.0 (f1edd0429 2021-11-29)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source $HOME/.cargo/env
```

Remember to run this before the build:
`source $HOME/.cargo/env
`

You will most likely run in to another issue, a temporary solution is provided in the other ticket.

Closing this one.
