### ISSUE TITLE
Add builds for Mac M1 arm on the Latest Stable Release

### ISSUE THREAD

**Issue by AllanOricil** [filecoin-project/lotus#7832]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Improvement Suggestion

I spent more than 5 hours trying to install Lotus on a Mac M1. I tried doing it with homebrew and building the binnaries myself, both without any success. Then I thought about building the binnaries using a Ubuntu container, and again got errors. This is extremelly umpleasant. So, please, add M1 builds to the releases.

**Comment by TimGuo7** [comment]
use M1 chip to run a node with Lotus?

**Comment by AllanOricil** [comment]
@TimGuo7 Im not going to run a full node on it. It was just for learning purpose. I was following these tutorial: 

https://lotus.filecoin.io/docs/tutorials/store-and-retrieve/

nothing I did made it work. So I can't learn :/

**Comment by Reiers** [comment]
Hi @AllanOricil 

Thanks for filing an issue - it appears that a ticket is already open about this.
Here: [#7597 ](https://github.com/filecoin-project/lotus/issues/7597)

You will also find a temporary solution there on how to build.

Closing this one due to duplicate ticket. Feel free to add anything you like to the other ticket.
