### ISSUE TITLE
Disable worker prevents other workers to fetch finished jobs from their storage

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#7866]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.13.2-rc4
```

### Describe the Bug

Disabling a worker with the `--set-enabled` flag prevents it from getting any new jobs (which is good), but it also prevents other workers to fetch any data from the disabled worker (which is bad)

### Logging Information

```text
-
```

### Repo Steps

- Run PC2 / C2 on a dedicated worker
- Disable midway
- See no new tasks are coming in
- See that once it finishes, the miner log shows information about not being able to assign a FETCH / GET on that worker, thus is never able to finish that sector

**Comment by kyle-parkinson** [comment]
+1

**Comment by rjan90** [comment]
Hey! Looking for your thoughts about initially hiding, and evetually deprecating, this command. The wanted feature for this command seems to be able to gracefully shutdown the lotus-worker:

1. A lot of incoming sealing tasks in the pipeline, but want/need to shut down worker nr.124 for maintainence/upgrade
2. Issue a command to block incoming tasks, and let it finish its current task.
3. `lotus-worker stop` to detach it and do maintenance/upgrades.

And for this, the `lotus-worker tasks enable/disable` seems more applicable as it will come with an `--all` option in v1.21.0 as well, and will allow other workers to fetch the finished jobs as well.

For full context, check https://github.com/filecoin-project/lotus/issues/10210
