### ISSUE TITLE
Fail early if the deals are expired during PRU handlings 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#7869]
like in `handleReplicaUpdate`, we should add more deal error/expiration handling in `handleProveReplicaUpdate1` and `handleProveReplicaUpdate2`

**Comment by jennijuju** [comment]
probably in `handleSubmitReplicaUpdate` too

**Comment by BlocksOnAChain** [comment]
@jennijuju @arajasek  -  this can probably include the following "to do" you mentioned : https://github.com/filecoin-project/lotus/blob/f7884c4f4550f81bc411e389aa7bc677b3bfeb25/extern/storage-sealing/input.go#L118
