### ISSUE TITLE
ERROR: failed to resolve ID address: %!w(address.Address={})

### ISSUE THREAD

**Issue by SealStorage-Jacques** [filecoin-project/lotus#7919]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.13.1+mainnet+git.8943de27e.dirty+api1.4.0
Local: lotus version 1.13.1+mainnet+git.8943de27e.dirty
```

### Describe the Bug

We recently switched to f2 multisig owner actor on our SP which is requirement from our FIL lender, we're also using bidbot to accept deals onto our SP and bidbot requires a signator against the SP owner account, when running `lotus wallet sign ` on the new owner address it errors with:
`ERROR: failed to resolve ID address: %!w(address.Address={})`
I also noticed the following error on the SP side running `lotus-miner actor control list `produces error:
`getting account key: failed to get account actor state for [SP-id] unknown actor code [baf....]`

### Logging Information

```text
Lotus Log:
2022-01-10T19:37:26.767-0500	WARN	rpc	go-jsonrpc@v0.1.5/handler.go:279	error in RPC call to 'Filecoin.WalletSign': failed to resolve ID address: %!w(address.Address={}):
    github.com/filecoin-project/lotus/node/impl/full.(*WalletAPI).WalletSign
        /lotus/lotus/node/impl/full/wallet.go:41
```

### Repo Steps

1. Change SP owner address to f2 multisig actor.
2. Try to sign a message against: lotus wallet sign f2....

1. Run: lotus-miner actor control list

**Comment by jennijuju** [comment]
The only fix lotus should do here is to wrap the error better.

**Comment by jennijuju** [comment]
The reproduction step suggests a user behaviour error - multisig is an actor  account that doesn’t have keys to sign transactions. To send a message using multisg , singers of the multisig  need to propose and approve messages (based on the threshold) refer to lotus doc for the usage of multisg.

**Comment by arajasek** [comment]
I agree with @jennijuju  here -- there is easy UX improvements that can be made to handle multisig owners better. We can definitely improve the output of `lotus-miner actor control list`, and maybe provide a better error for `lotus wallet sign`. We can also audit other `lotus-miner` UX commands to see if they work gracefully with multisig owners.

I'm not sure if that actually solves @SealStorage-Jacques's problem, though -- not clear exactly what is needed.

**Comment by rjan90** [comment]
So this is half fixed:

> lotus-miner actor control list produces error:
> getting account key: failed to get account actor state for [SP-id] unknown actor code [baf....]

Has been fixed with https://github.com/filecoin-project/lotus/pull/9072. 

So the only thing missing is wrapping the error better.
