### ISSUE TITLE
API support for MsigGetVestingSchedule

### ISSUE THREAD

**Issue by willscott** [filecoin-project/lotus#7929]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Would like an easier way to understand the state of multisigs (e.g. the epochs when they begin and end vesting, and initial balance)

### Describe the solution you'd like

The api `MsigGetVestingSchedule` should be exposed on gateways.

### Additional context

the [read permission](https://github.com/filecoin-project/lotus/blob/4e16d600b0cfbc03f4d9df82f0aa8c288a4f6312/api/v0api/full.go#L614) API call is not available on the [api gateway](https://github.com/filecoin-project/lotus/blob/4e16d600b0cfbc03f4d9df82f0aa8c288a4f6312/api/api_gateway.go#L47)

**Comment by Reiers** [comment]
**Hi @willscott** 

Thanks for this feature request. 
I have added the labels and will forward it to the right team !

**Comment by magik6k** [comment]
#8104
