### ISSUE TITLE
lotus-miner storage-deals set-ask is completely broken 

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#7936]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
1.13.2-rc4
```

### Describe the Bug

Running the `set-ask` command is completely broken;

```
$ lotus-miner storage-deals set-ask --price=0 --verified-price=0
ERROR: cannot parse max-piece-size to quantity of bytes: invalid size: ''
```

The docs state those options are optional;
```
NAME:
   lotus-miner storage-deals set-ask - Configure the miner's ask

USAGE:
   lotus-miner storage-deals set-ask [command options] [arguments...]

OPTIONS:
   --price PRICE           Set the price of the ask for unverified deals (specified as FIL / GiB / Epoch) to PRICE.
   --verified-price PRICE  Set the price of the ask for verified deals (specified as FIL / GiB / Epoch) to PRICE
   --min-piece-size SIZE   Set minimum piece size (w/bit-padding, in bytes) in ask to SIZE (default: 256B)
   --max-piece-size SIZE   Set maximum piece size (w/bit-padding, in bytes) in ask to SIZE (default: miner sector size)
   --help, -h              show help (default: false)
```

They are not, but OK, I'll write them by hand;

```
$ lotus-miner storage-deals set-ask --price=0 --verified-price=0 --max-piece-size=32G --min-piece-size=256B
ERROR: fatal error calling 'Filecoin.MarketSetAsk': panic in rpc method 'Filecoin.MarketSetAsk': runtime error: invalid memory address or nil pointer dereference
```

I'm running split markets, so I'll add that flag;

```
$ lotus-miner --call-on-markets storage-deals set-ask --price=0 --verified-price=0 --max-piece-size=32G --min-piece-size=256B
ERROR: fatal error calling 'Filecoin.MarketSetAsk': panic in rpc method 'Filecoin.MarketSetAsk': runtime error: invalid memory address or nil pointer dereference
```

I'll add more env vars (all my markets calls work like that;)

```
$ LOTUS_MINER_PATH=~/.lotusmarkets lotus-miner --markets-repo=~/.lotusmarkets --call-on-markets storage-deals get-ask
Price per GiB/Epoch  Verified  Min. Piece Size (padded)  Max. Piece Size (padded)  Expiry (Epoch)  Expiry (Appx. Rem. Time)  Seq. No.
0.000000004 FIL      0 FIL     256 B                     32 GiB                    1329428         <expired>                 13
```

But, when using set-ask:

```
$ LOTUS_MINER_PATH=~/.lotusmarkets lotus-miner --markets-repo=~/.lotusmarkets storage-deals set-ask --price=0 --verified-price=0 --max-piece-size=32G --min-piece-size=256B
ERROR: fatal error calling 'Filecoin.ActorAddress': panic in rpc method 'Filecoin.ActorAddress': runtime error: invalid memory address or nil pointer dereference
```

### Logging Information

```text
none
```

**Comment by Reiers** [comment]
**Hi @RobQuistNL** 

Thanks for the report. The issue you are experiencing lies elsewhere.

Tested all cmds on miner, and separate markets node.

## Miner
```
reiers@miner:~$ lotus-miner storage-deals get-ask
Price per GiB/Epoch  Verified  Min. Piece Size (padded)  Max. Piece Size (padded)  Expiry (Epoch)  Expiry (Appx. Rem. Time)  Seq. No.
0 FIL                0 FIL     1 MiB                     32 GiB                    1542631         719h56m0s                 170
```

`reiers@miner:~$ lotus-miner storage-deals set-ask --price=0 --verified-price=0 --max-piece-size=32G --min-piece-size=256B
`

```
reiers@miner:~$ lotus-miner --call-on-markets storage-deals get-ask
Price per GiB/Epoch  Verified  Min. Piece Size (padded)  Max. Piece Size (padded)  Expiry (Epoch)  Expiry (Appx. Rem. Time)  Seq. No.
0 FIL                0 FIL     256 B                     32 GiB                    1542640         719h59m30s                171
```

`reiers@miner:~$ lotus-miner --call-on-markets storage-deals set-ask --price=0 --verified-price=0 --max-piece-size=32G --min-piece-size=1MiB`

```
reiers@miner:~$ lotus-miner --call-on-markets storage-deals get-ask
Price per GiB/Epoch  Verified  Min. Piece Size (padded)  Max. Piece Size (padded)  Expiry (Epoch)  Expiry (Appx. Rem. Time)  Seq. No.
0 FIL                0 FIL     1 MiB                     32 GiB                    1542641         720h0m0s                  172
```
## Markets 
`reiers@markets:~$ LOTUS_MINER_PATH=/mnt/Lotus_Markets_Path/Lotus_Markets lotus-miner storage-deals set-ask --price=0 --verified-price=0 --max-piece-size=32G --min-piece-size=256B`

```
reiers@markets:~$ LOTUS_MINER_PATH=/mnt/Lotus_Markets_Path/Lotus_Markets lotus-miner storage-deals get-ask
Price per GiB/Epoch  Verified  Min. Piece Size (padded)  Max. Piece Size (padded)  Expiry (Epoch)  Expiry (Appx. Rem. Time)  Seq. No.
0 FIL                0 FIL     256 B                     32 GiB                    1542648         720h0m0s                  173
```

`reiers@markets:~$ LOTUS_MINER_PATH=/mnt/Lotus_Markets_Path/Lotus_Markets lotus-miner storage-deals set-ask --price=0 --verified-price=0 --max-piece-size=32G --min-piece-size=1MiB`

```
reiers@markets:~$ LOTUS_MINER_PATH=/mnt/Lotus_Markets_Path/Lotus_Markets lotus-miner storage-deals get-ask
Price per GiB/Epoch  Verified  Min. Piece Size (padded)  Max. Piece Size (padded)  Expiry (Epoch)  Expiry (Appx. Rem. Time)  Seq. No.
0 FIL                0 FIL     1 MiB                     32 GiB                    1542648         720h0m0s                  174
```

Lotus version:
```
Daemon:  1.13.2+mainnet+git.f9db71ee1+api1.4.0
Local: lotus version 1.13.2+mainnet+git.f9db71ee1
```

Closing Lotus issue ticket. We will help you in the thread on [Slack ! ](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1641992865231800)

**Comment by RobQuistNL** [comment]
Hey @Reiers, try the `set-ask`. The `get-ask` is working for me, too, as you can see from my post. The issue is that the `set-ask` is not working.

**Comment by RobQuistNL** [comment]
Apart from that, even with broken config, a `panic` should never happen.

**Comment by RobQuistNL** [comment]
Where did you get that `APISEALER` and `APISECTORINDEX` from? What should it hold? There's nothing about that in the docs _or_ the Lotus source.

I am missing the `SealerApiInfo` and `SectorIndexApiInfo` nodes in my markets `config.toml` - those do not appear in the docs either. They are in the default miner config since 09-30-2021 so I think I missed that (I don't regenerate my configuration every time a new version is released, and it doesn't seem to be noted anywhere else in the repository (changelog / docs / readme's)..

Will add those and see what it does.

**Comment by RobQuistNL** [comment]
EDIT: I actually do have those in, in the markets node.

I don't have them in my miner config.

**Comment by Reiers** [comment]
Let me know - if its working.

We will send this to the Docs team, so thanks for flagging. I will even make short PR myself if its not clear that 
```
SealerApiInfo = 
SectorIndexApiInfo = 
```
Is needed and not explained where they came from.

+ we will add a section under Upgrades about your config.toml. 
```
[Subsystems]
  EnableMining = false
  EnableSealing = false
  EnableSectorStorage = false
  EnableMarkets = true
```

**Comment by RobQuistNL** [comment]
You want me to add them in my miner node? So the miner node needs an API URL to itself?
