### ISSUE TITLE
Markets Node shouldn't require write access to unsealed files that it serves for retrieval

### ISSUE THREAD

**Issue by neondragon** [filecoin-project/lotus#7938]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

**Motivation**
I set up a markets node attached to a sector store. The filesystem permissions on the sector store allow only read access.

Retrieval deals failed.

Example output of `lotus-miner retrieval-deals list`

```
12D3KooWBYzfWe6ztHqMF9NkgNhrwqDUbtLLUZEkocKM4xLCk3Sp  921688               ...czN8taba  DealStatusErrored         0             0            failed to load blockstore for piece baga6ea4seaqevvclfptke57tvj53aqn7hbgvcswqp32a5q42hd3tl2ters4nily: failed to acquire shard for piece CID baga6ea4seaqevvclfptke57tvj53aqn7hbgvcswqp32a5q42hd3tl2ters4nily: failed to unseal deal 2806302: failed to unseal piece from sector 4914: opening partial file: openning partial file '/store1/unsealed/s-t019551-4914': open /store1/unsealed/s-t019551-4914: permission denied
```

When the markets process was granted read-write access to the unsealed sectors, retrieval deals succeeded.

**Suggested Improvement**

Lotus markets node should support serving unsealed data from a sector store with read-only access. This will improve security.

**Comment by Reiers** [comment]
**Hi @neondragon** 

I agree - lets see if we can do anything about that. 
I will add labels and will assign it to the right team for analysis.

Thanks for taking the time to create the ticket !

**Comment by rjan90** [comment]
Closing this issue as not something that will be fixed, given that the Lotus-Miner Markets sub-system has reached EOL and the lotus-miner markets-code will be removed after the nv21-upgrade.
