### ISSUE TITLE
Lotus-miner set-ask (and probably many more!) do not get env var configuration from service

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#7964]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.13.2-rc4
```

### Describe the Bug

This original issue: https://github.com/filecoin-project/lotus/issues/7936

Was fixed by adding the following variables in my `~/.bashrc`:

```
export FULLNODE_API_INFO=eyJhbGxxxxxxxxxxx:/ip4/xxx.xxx.xxx.xxx/tcp/1234/http
export MARKETS_API_INFO=eyJhbGxxxxxxxxxxx:/ip4/xxx.xxx.xxx.xxx/tcp/2346/http
export MINER_API_INFO=eyJhbGxxxxxxxxxxx:/ip4/xxx.xxx.xxx.xxx/tcp/2345/http
```

This is not expected behaviour, because these variables are already declared in the services;
```
[Service]
(...)
Environment=FULLNODE_API_INFO={{ lotus_daemon_api_key }}:/ip4/{{ lotus_daemon_api_ip }}/tcp/{{ lotus_daemon_api_port }}
Environment=MARKETS_API_INFO={{ lotus_markets_api_key }}:/ip4/{{ lotus_markets_api_ip }}/tcp/{{ lotus_markets_api_port }}
Environment=MINER_API_INFO={{ lotus_miner_api_key }}:/ip4/{{ lotus_miner_api_ip }}/tcp/{{ lotus_miner_api_port }}
(...)
```

So this "solution" feels like a workaround. I think calling the API like that should use the internal evironment variables of the process, and not the environment variables of the current shell. 

Because, for example, the calls to the API will not work when not using an interactive shell that does not parse `~/.bashrc`

**Comment by Reiers** [comment]
Hi @RobQuistNL 

Thanks for the report. I have added labels and will assign it to the right team for analysis.

**Comment by LexLuthr** [comment]
@RobQuistNL Hey, where are you picking these variables from? Are you using an "EnvironmentFile" to inject these variables to the service file?

**Comment by RobQuistNL** [comment]
Hey @LexLuthr yeah, I think whats happening:

- I run lotus-miner as a service
- I manually run lotus-miner commands on my CLI
- The manually run spawns a seperate process and looks for environment variables (which do not exist in userland - only in the running process)
- The CLI commands are issues with wrong values because the service's environment variables are not used in userland

This is probably purely due to how the CLI is setup (using API calls) but it can be painful when you're running this stuff as a service and want to issue commands to it.

**Comment by LexLuthr** [comment]
@RobQuistNL I definitely understand the concern here but lotus client and daemons are decoupled for flexibility. Injecting variables using some script would probably be more unnecessary work then simply injecting 3 variables in `.bashrc` 
and changing code base to avoid writing 3 lines would not be efficient either.
If you have a solution mapped out, please let me know and we can discussion that.

**Comment by LexLuthr** [comment]
1. Miners can be managed remotely with exporting the APIs. Config can also be exported remotely by invoking the config command.
2. If you have multiple miners on a single node, they would still have a different API address and can simply be called by exporting the correct address. You can simply run a source .lotusminer4/.lotsminer3 etc and the run the command. I don't see a need to make changes to the code path if this can all be done with exporting 3 variables as max.

**Comment by RobQuistNL** [comment]
Fair point. So I guess we can close the issue? Biggest issue that was underlying to this was fixed :)
