### ISSUE TITLE
First parallel make invocation always fails

### ISSUE THREAD

**Issue by dithpri** [filecoin-project/lotus#7978]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
Not applicable / master@2f5c036faa19e839f3e71e36c0b0d8f79f00d093
```

### Describe the Bug

First build always fails in a newly cloned repo if make is invoked with multiple jobs.

### Logging Information

```text
$ make clean all
rm -rf build/.filecoin-install build/.update-modules lotus lotus-miner lotus-worker lotus-shed lotus-gateway lotus-seed lotus-pond lotus-fountain lotus-bench lotus-stats lotus-pcr lotus-health lotus-wallet lotus-keygen testground tvx lotus-sim
git submodule update --init --recursive
make -C extern/filecoin-ffi/ clean
awk: fatal: cannot open file `extern/filecoin-ffi/version.go' for reading: No such file or directory
FFI version mismatch, update submodules
make: *** [Makefile:47: ffi-version-check] Error 1
make: *** Waiting for unfinished jobs....
make[1]: Entering directory '/tmp/lotus/extern/filecoin-ffi'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory '/tmp/lotus/extern/filecoin-ffi'
make: [Makefile:277: clean] Error 2 (ignored)
Submodule 'extern/filecoin-ffi' (https://github.com/filecoin-project/filecoin-ffi.git) registered for path 'extern/filecoin-ffi'
Submodule 'extern/serialization-vectors' (https://github.com/filecoin-project/serialization-vectors.git) registered for path 'extern/serialization-vectors'
Submodule 'extern/test-vectors' (https://github.com/filecoin-project/test-vectors.git) registered for path 'extern/test-vectors'
Cloning into '/tmp/lotus/extern/filecoin-ffi'...
Cloning into '/tmp/lotus/extern/serialization-vectors'...
Cloning into '/tmp/lotus/extern/test-vectors'...
Submodule path 'extern/filecoin-ffi': checked out 'e660df5616e397b2d8ac316f45ddfa7a44637971'
Submodule path 'extern/serialization-vectors': checked out '5bfb928910b01ac8b940a693af2884f7f8276211'
Submodule path 'extern/test-vectors': checked out 'd9a75a7873aee0db28b87e3970d2ea16a2f37c6a'
Submodule 'gen/extern/fil-blst' (https://github.com/filecoin-project/fil-blst.git) registered for path 'extern/test-vectors/gen/extern/fil-blst'
Submodule 'gen/extern/filecoin-ffi' (https://github.com/filecoin-project/filecoin-ffi.git) registered for path 'extern/test-vectors/gen/extern/filecoin-ffi'
Cloning into '/tmp/lotus/extern/test-vectors/gen/extern/fil-blst'...
Cloning into '/tmp/lotus/extern/test-vectors/gen/extern/filecoin-ffi'...
Submodule path 'extern/test-vectors/gen/extern/fil-blst': checked out '5f93488fc0dbfb450f2355269f18fc67010d59bb'
Submodule path 'extern/test-vectors/gen/extern/filecoin-ffi': checked out 'f640612a1a1f7a2dd8b3a49e1531db0aa0f63447'
touch build/.update-modules
$ echo $?
2
```

### Repo Steps

1. Clone the repo: `git clone https://github.com/filecoin-project/lotus.git && cd lotus`
2. Try to build lotus with parallel jobs: `make -j2 clean all`
3. Build fails due to submodules not yet being initialized, yet the ffi-version-check target requires them: https://github.com/filecoin-project/lotus/blob/2f5c036faa19e839f3e71e36c0b0d8f79f00d093/Makefile#L46-L47

**Comment by dithpri** [comment]
Proposed fix:
```diff
diff --git a/Makefile b/Makefile
index f7b13cc..bbe78d4 100644
--- a/Makefile
+++ b/Makefile
@@ -43,7 +43,7 @@ MODULES+=$(FFI_PATH)
 BUILD_DEPS+=build/.filecoin-install
 CLEAN+=build/.filecoin-install
 
-ffi-version-check:
+ffi-version-check: $(FFI_DEPS)
 	@[[ "$$(awk '/const Version/{print $$5}' extern/filecoin-ffi/version.go)" -eq 3 ]] || (echo "FFI version mismatch, update submodules"; exit 1)
 BUILD_DEPS+=ffi-version-check
```

**Comment by Reiers** [comment]
Hi @dithpri 

Thanks for the report and the suggested solution. 
I have added labels and will assign it to the right team for analysis.

**Comment by rjan90** [comment]
Hey!

Thanks for the report. This issue has been resolved in the newest release of Lotus.

Closing ticket - thanks again!
