### ISSUE TITLE
help！How to start a remote seal-worker

### ISSUE THREAD

**Issue by KIMQI001** [filecoin-project/lotus#800]

**Comment by eshon** [comment]
@KIMQI001 See https://filecoinproject.slack.com/archives/CPFTWMY7N/p1575558809185600

**Comment by KIMQI001** [comment]
@eshon thanks,but it looks like I... do not have permission to open it

**Comment by KIMQI001** [comment]
@eshon lzyzoezoezoezoe@gmail.com please?

**Comment by eshon** [comment]
<img width="490" alt="Screen Shot 2019-12-10 at 12 04 21 PM" src="https://user-images.githubusercontent.com/1017762/70524375-499de780-1b45-11ea-9eab-444f4b89a6ab.png">

It's in the fil-lotus channel, Dec. 5th, 4:13 PM but will be added to the documentation soon. @KIMQI001

**Comment by KIMQI001** [comment]
@eshon I got it,thank u

**Comment by guodayang999** [comment]
@eshon 763917746@qq.com please?

**Comment by magik6k** [comment]
We now have docs about this on https://docs.lotu.sh/
