### ISSUE TITLE
deal failed: (State=26) deal data verification failed: proposal CommP doesn't match calculated CommP

### ISSUE THREAD

**Issue by aueam** [filecoin-project/lotus#8010]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version:
Daemon:  1.13.2+calibnet+git.f9db71e.dirty+api1.4.0
Local: lotus version 1.13.2+calibnet+git.f9db71e.dirty

lotus-miner version:
Daemon:  1.13.2+calibnet+git.f9db71e.dirty+api1.2.0
Local: lotus-miner version 1.13.2+calibnet+git.f9db71e.dirty
```

### Describe the Bug

Hi,
I have problem with failed deal on the side of the miner. It failed every time after `StorageDealTransferring`.
I found that it doesn't work if the translated dataCid (from `lotus client import`) entered in to `lotus client deal` contains **identity** instead of **blake2b-256**, you can look at an example:
https://cid.ipfs.io/#bafyaa6qsgafcmalqudsaeigs5eamwvxo6ipa6nw3e375szaxj33hlmzhibu723ajpcg4asicjujaagelucbyabasgafcmalqudsaeib2byxqv5qccaof6fccfccfcfccfccfc 

When I tried to make the same deal on another miner, it worked.  (You cannot download the data because the deal is still in the `StorageDealAwaitingPreCommit` state.)

Miner where the deal failed: `t01105` (version above)
Miner where the deal worked: `t028659`(unknown version)

When I import a file that has 1GiB or less, the translated cid have **blake2b-256** insted of **identity**,  it is shorter and the deal on miner `t01105` works.

Deal info from `lotus client list-deals -v --show-failed`:
```
Jan 30 13:43:53  bafyreihsasxcvozrewjsqxqn2hlbjthj5b5cjomm4owlyqghbte7k3epue  0       t01105    StorageDealError     N                 N                 baga6ea4seaqlcu5hmz2yid4jkwvp2eqplusoprvyhs2svwokr4dbwfunaexlomq  1.984 GiB  0.0015584754024 FIL   779004    12D3KooWMoahTDLLpdhWJCETqNZCGdtBCAfMnSMKZG3zAuMUrHMo-12D3KooWN4MX4hWHjsJUJi6bKCnmXJMN8jL6ne55nCCTaKV4HLSm-1643468399046691677  Completed       false     deal failed: (State=26) deal data verification failed: proposal CommP doesn't match calculated CommP
```

### Logging Information

```text
N/A
```

### Repo Steps

1. Create file `head -c 1610612736 /dev/urandom > /tmp/1.5GiB.txt`
2. Import file `lotus client import /tmp/1.5GiB.txt`
3. Make deal `lotus client deal <dataCid> t01105 0.00005 777600`
4. See error `lotus client list-deals -v --show-failed`

**Comment by aueam** [comment]
I tried downgrading the miner to `v1.13.1` and the problematic deal was successful. So I think the problem is in version `v1.13.2`.

**Comment by Reiers** [comment]
**Hi @aueam** 

Are you still having this issue on the latest tag `v1.15.0`?

*Link to latest tags [here.](https://github.com/filecoin-project/lotus/tags)

**Comment by margox** [comment]
I am facing the same issue with lotus/lotus-miner v1.14.1, and as @aueam said, the failed deal always with a long data cid,  like below:
```
bafyaa6qsgafcmalqudsaeiazs3ookqahnrckbzkwh2zjak7h5sqat23duzauz43zl4xt3dw2mijaagelucbyabasgafcmalqudsaeigifozhpcni5hngig7gongxjla3yjsxx5cvmuoy3ih4dnnirtnwdmjaaghgukn5waykcqeaegfpucmnwbzaqcaibaaeecx2bgg3am
```
by the way, this original file size of the failed deal is 2070286383, about 2GB, but I have other files successfully storaged with larger size (4GB) and smaller size (150MB) both.

**Comment by margox** [comment]
> Oops, seems like we needed more information for this issue, please comment with more details or this issue will be closed in 24 hours.

 I think @aueam has explained the problem in enough detail :(

**Comment by aueam** [comment]
Hi @margox and @Reiers!
lotus version:
```
Daemon:  1.15.0+calibnet+git.0ac1bbc.dirty+api1.5.0
Local: lotus version 1.15.0+calibnet+git.0ac1bbc.dirty
```
The import still generates a long CID. (`bafyaa6qsgafcmalqudsaeib3vflzvdia42fit5em2qafw3xcld6g3frdilb5ktt4zm6e7434tajaagelucbyabasgafcmalqudsaeifmrgyqfhwdxfxmelwanezhjbafw4qxtmcy65covvyxpcttbyrw54jaagel2cayaaqkcqeaegeaqcaiabraqcaibaaeecaibaeaai`)
 
I'm still getting a message after starting a deal: `Message: deal failed: (State=11) deal data verification failed: proposal CommP doesn't match calculated CommP`

*It's only a problem on calibnet on my side.*

**Comment by margox** [comment]
> Hi @margox and @Reiers! lotus version:
> 
> ```
> Daemon:  1.15.0+calibnet+git.0ac1bbc.dirty+api1.5.0
> Local: lotus version 1.15.0+calibnet+git.0ac1bbc.dirty
> ```
> 
> The import still generates a long CID. (`bafyaa6qsgafcmalqudsaeib3vflzvdia42fit5em2qafw3xcld6g3frdilb5ktt4zm6e7434tajaagelucbyabasgafcmalqudsaeifmrgyqfhwdxfxmelwanezhjbafw4qxtmcy65covvyxpcttbyrw54jaagel2cayaaqkcqeaegeaqcaiabraqcaibaaeecaibaeaai`)
> 
> I'm still getting a message after starting a deal: `Message: deal failed: (State=11) deal data verification failed: proposal CommP doesn't match calculated CommP`
> 
> _It's only a problem on calibnet on my side._

Maybe I should look into the lotus code and find out why long cid generated, I guess it might has something to do wtih the file size? two of my files with size 1934919433 and 2070286383 failed, both nearly 2GB, other files with larger or smaller size are working.

**Comment by margox** [comment]
Oh god it's hard for me to find out a little needle from the ocean, I give up ~ 😭, but I think it's because there's a little difference between the commp generating functions in lotus client side and market side ?

But I wondering why just us two (maybe three, I found someone else asking the same question in project **boost** LOL)  facing the issue if this is a lotus bug, coz there's no other people storage files larger than 1GB all over the world?🤪

**Comment by margox** [comment]
here is the commp generating function in client side:
https://github.com/filecoin-project/lotus/blob/master/node/impl/client/client.go#L1281

and here is the one in market side:
https://github.com/filecoin-project/go-fil-markets/blob/master/commp/commp.go#L14

**Comment by margox** [comment]
> here is the commp generating function in client side: https://github.com/filecoin-project/lotus/blob/master/node/impl/client/client.go#L1281
> 
> and here is the one in market side: https://github.com/filecoin-project/go-fil-markets/blob/master/commp/commp.go#L14

looks bit difference between the two ,but I am not golang developer so I don't know wheather the results will be equal :(
