### ISSUE TITLE
(SnapDeals) snap-up deal files does not move to long term storage, stays in sealing path. 

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/lotus#8012]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.14.0-rc5+butterflynet+git.40485eb88+api1.5.0
Local: lotus version 1.14.0-rc5+butterflynet+git.40485eb88
```

### Describe the Bug

Deal/sector files stays on your sealing disk, even after upgrading and the sector has gone back to proving. 

In these folders:
```
unsealed  
update  
update-cache
```

Even with fast retrieval on the files does not transfer to unsealed folder to you long term storage. 

### Logging Information

```text
/Sealing_Path/update-cache$ ls
s-t01012-23  s-t01012-24  s-t01012-28  s-t01012-31  s-t01012-35

/Sealing_Path/update$ ls
s-t01012-23  s-t01012-24  s-t01012-28  s-t01012-31  s-t01012-35

/Sealing_Path/unsealed$ ls
fetching  s-t01012-23  s-t01012-24 s-t01012-28 s-t01012-31  s-t01012-35

ID  State    OnChain  Active  Expiration                    Deals
23  Proving  YES      YES     1602959 (in 1 year 24 weeks)  1 
24  Proving  YES      YES     1602959 (in 1 year 24 weeks)  1 
28  Proving  YES      YES     1602959 (in 1 year 24 weeks)  1
31  Proving  YES      YES     1602959 (in 1 year 24 weeks)  1 
35  Proving  YES      YES     1602959 (in 1 year 24 weeks)  1
```

### Repo Steps

- `lotus-miner sectors snap-up sectornumb`
- Let it seal
- Files stays in sealing path

**Expected behavior:** deal/sector files moves to long term storage.

**Comment by jennijuju** [comment]
missing finalize


while implementing this might also consider the FinalizeEarly option mentioned in https://github.com/filecoin-project/lotus/issues/8011#issuecomment-1026095327
