### ISSUE TITLE
lotus daemon error

### ISSUE THREAD

**Issue by linmuqin** [filecoin-project/lotus#802]
sync status:
worker 0:
	Base:	[bafy2bzaceawk5vvih6wnxlar27bk4j7cwhgems6s72pyn2l5u2dudzn4sbpqu]
	Target:	[bafy2bzacedheapn4iv4rollpyn2dhpyghqeo3hrvoua7wh6vsrglz73rfssuk] (10992)
	Height diff:	10992
	Stage: error
	Height: 0
	Elapsed: 29.918µs
	Error: chain linked to block marked previously as bad ([bafy2bzacedheapn4iv4rollpyn2dhpyghqeo3hrvoua7wh6vsrglz73rfssuk], bafy2bzaceddbmfxw6zhrfynztukmytlgir4zcsg7y6sny3cqhz2rjo7gkwmxg)
worker 1:
	Base:	[bafy2bzaceawk5vvih6wnxlar27bk4j7cwhgems6s72pyn2l5u2dudzn4sbpqu]
	Target:	[bafy2bzacec437gtf3grj634edtudmjcamxvit2uyfnifjyctgv7cyhzq2wobo bafy2bzacecr5qunwjawulodqxivae7bxld6bfcp4p6jrtjwlio5x2setb6tbm] (10992)
	Height diff:	10992
	Stage: error
	Height: 0
	Elapsed: 43.219µs
	Error: chain linked to block marked previously as bad ([bafy2bzacec437gtf3grj634edtudmjcamxvit2uyfnifjyctgv7cyhzq2wobo bafy2bzacecr5qunwjawulodqxivae7bxld6bfcp4p6jrtjwlio5x2setb6tbm], bafy2bzaceddbmfxw6zhrfynztukmytlgir4zcsg7y6sny3cqhz2rjo7gkwmxg)
worker 2:
	Base:	[bafy2bzaceawk5vvih6wnxlar27bk4j7cwhgems6s72pyn2l5u2dudzn4sbpqu]
	Target:	[bafy2bzaceb4naow6sawc6zn5c2elddiozc42onygmuwnfyznchmtybegbn5og] (10991)
	Height diff:	10991
	Stage: error
	Height: 0
	Elapsed: 38.244µs
	Error: chain linked to block marked previously as bad ([bafy2bzaceb4naow6sawc6zn5c2elddiozc42onygmuwnfyznchmtybegbn5og], bafy2bzacea7mrdedw4vgpx7fbcn4s4i23npazvamuz3qvk2stb2qjimcge35o)

**Comment by TiDao** [comment]
How do you save the the porblem.? @linmuqin

**Comment by Jaschenn** [comment]
some like problem
```
lotus sync status
sync status:
worker 0:
	Base:	[bafy2bzaceaxm23epjsmh75yvzcecsrbavlmkcxnva66bkdebdcnyw3bjrc74u]
	Target:	[bafy2bzacebdfmd2d7iz2d76b6gnvgmyupxggqgwtgcd6ly3q2ovxn3juj6cqk bafy2bzaceannws77qx4s4ghznlm5hwjacbgvcu57sn534itiqhc4gyozyqbbg bafy2bzacecv67vf3dgd2ijk6mjw376lvf56gjwljtpqsj5fe275pbqzwpefaa bafy2bzacec6blmrydpxh7kclt6e3buy6cjok72yqoonitwrjtypztryaacrg2] (189044)
	Height diff:	189044
	Stage: error
	Height: 189044
	Elapsed: 22.658593s
	Error: failed to get blocks: GetBlocks failed with all peers: i/o deadline reached
worker 1:
	Base:	[bafy2bzaceaxm23epjsmh75yvzcecsrbavlmkcxnva66bkdebdcnyw3bjrc74u]
	Target:	[bafy2bzacebdfmd2d7iz2d76b6gnvgmyupxggqgwtgcd6ly3q2ovxn3juj6cqk bafy2bzaceannws77qx4s4ghznlm5hwjacbgvcu57sn534itiqhc4gyozyqbbg bafy2bzacecv67vf3dgd2ijk6mjw376lvf56gjwljtpqsj5fe275pbqzwpefaa bafy2bzacec6blmrydpxh7kclt6e3buy6cjok72yqoonitwrjtypztryaacrg2] (189044)
	Height diff:	189044
	Stage: error
	Height: 189044
	Elapsed: 20.986367s
	Error: failed to get blocks: GetBlocks failed with all peers: reading cid field t.Parents failed: i/o deadline reached
worker 2:
	Base:	[bafy2bzaceaxm23epjsmh75yvzcecsrbavlmkcxnva66bkdebdcnyw3bjrc74u]
	Target:	[bafy2bzacea3wxsvz7g2wl5nc4in5xdp2tnjxaxa3aa5szsr5bbuvt5s6xbdck bafy2bzacedocd4evafqrcbshervvuxtwen5nenurz2iji46qhhvyjyoaoeycg] (167357)
	Height diff:	167357
	Stage: header sync
	Height: 151509
	Elapsed: 1m46.937889s
```
