### ISSUE TITLE
Doc: Updating without deleting miner and/or chain data

### ISSUE THREAD

**Issue by eshon** [filecoin-project/lotus#803]
https://docs.lotu.sh/en+updating-lotus

May want to add that `rm -rf ~/.lotus ~/.lotusstorage` will delete your chain data and any miners you have set up. This may not be necessary for smaller updates. We will share information about when resetting your chain data and miners is required for an update.

**Comment by jimmylee** [comment]
Thanks @eshon I've add this to the documentation 🙌
