### ISSUE TITLE
Allow for dual VM execution for getting the price list

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8060]
Build on top of #8059 to run every tipset through _both_ the Lotus VM and the ref-fvm. This should be relatively easy to do. We probably want to:

- use the Lotus VM for the "real" validation
- use the FVM-with-lotus-gas-costs and make sure it always results in the same state as the lotus VM
- Add fuel accounting with unlimited fuel to trace fuel/gas statistics for the FVM itself (for the M1 milestone)

**Comment by jennijuju** [comment]
this is mostly for testing purpose (gas comparison) and the code should not land in master

**Comment by jennijuju** [comment]
We are uncertain this is necessary for the new gas model work scope. will confirm.
