### ISSUE TITLE
Epic: Implement FIP-0031

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8061]
- [x] #8062 
- [x] #8063
- [x] #8064
- [x] (actors) bake the Miner actor CID into the Power actor CID, and the Paych, msig and miner actor CIDs into the init actor
- [x] #8065 -- we can no longer use it for things like actor CIDs (or method nums)?
- [x] #8066
- [x] #8164

**Comment by arajasek** [comment]
[See FIPs #294](https://github.com/filecoin-project/FIPs/pull/294)

**Comment by jennijuju** [comment]
Done! GO TEAM
