### ISSUE TITLE
 Add canonical actor CARs to the statestore

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8062]
These will be coming out of https://github.com/filecoin-project/ref-fvm/issues/22 and need to be made accessible to the FVM

**Comment by arajasek** [comment]
We need to make super sure that the actor code never gets cleaned up by any GC / reachability analyser

**Comment by arajasek** [comment]
This is currently achieved by having the FFI put them in the store. This works, but should move into lotus itself.

**Comment by raulk** [comment]
@arajasek Any remaining action items here?

**Comment by raulk** [comment]
Implemented and landed in nv16 branch.
