### ISSUE TITLE
Add a migration that transforms dummy code CIDs to actual CIDs based on the actor code

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8066]
There's something of an open question about _where_this migration should go. I think it should just be in specs-actors -- the last thing that repo can do is transform the state tree to create the new version for the FVM-based future to use :)

**Comment by jennijuju** [comment]
migration of the v7 -> v8 CID https://github.com/filecoin-project/specs-actors/pull/1576

as a part of the https://github.com/filecoin-project/builtin-actors/issues/4 we will get the new CID into the migration

**Comment by raulk** [comment]
Implemented and landed in nv16 branch.
