### ISSUE TITLE
fake winning PoSt proofs _only_

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#8091]
## Context

Lotus currently has a mode to fake out all proofs, but this includes window PoSt and other verification calls.

For FVM testing, we would like to run a fast testnet (block time: 5s instead of 30s) with 512MiB sectors. Based on evidence, the computation time for winning PoSt ranges betweek 9-14 seconds in the current butterflynet infra, which makes the 5s block time unfeasible.

For these tests, we also don't want to disable every other proof, since several of those flow through the FVM and we do want to exercise the full code paths and get realistic execution numbers.

## Request

The request is to add an option (likely an env var) in Lotus to fake out _only_ winning PoSt proofs. All other proofs should remain unchanged.

**Comment by magik6k** [comment]
This is already done in debug testnets (`make debug`); achieved through setting `build.InsecurePoStValidation` https://github.com/filecoin-project/lotus/blob/master/build/params_debug.go#L7; All other proofs should be 'real'.

**Comment by raulk** [comment]
Fantastic, then we just need to expose it through an env var, @arajasek.

**Comment by arajasek** [comment]
I don't think this needs to be an envvar, it's fine being a build level thing, I think.
