### ISSUE TITLE
cli lotus client deal input validation crash 

### ISSUE THREAD

**Issue by smagdali** [filecoin-project/lotus#8100]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.15.0-rc1+mainnet+git.3031b4d98
```

### Describe the Bug

When using the golang lotus client to make a deal...

Input validation failure at the "Deals to make (1):" prompt causes the lotus client to crash. Hitting return instead of entering a value should either re-prompt or continue with the default (1).

### Logging Information

```text
I didn't see anything in the cli logs, even at debug level.
```

### Repo Steps

```ubuntu@ip-172-26-5-33:~$ lotus client deal
Data CID (from lotus client import): bafykbzacea6ns5swfl4rroe4sbhot3lw4vyarycejwmwpwfcxuku2sbb62qbm
.. calculating data size
Deal duration (days): 300

Make this a verified deal? (yes/no): yes
Miner Addresses (f0.. f0..), none to find: 
.. getting miner list
* Found 3774 miners with power
.. querying asks
* Queried 3724 asks, got 794 responses
Found 698 candidate asks
Average network latency: 608ms; Median latency: 474ms
Maximum network latency (default: 474ms) (ms): 
151 asks left after filtering for network latency
Proposing from f1zk5oufzpzeokprrtwv7lsdkr5jl7fg3jkp5kplq, Current Balance: 0 FIL
Maximum budget (FIL): 0.05
102 asks within budget
Deals to make (1):     # HIT RETURN HERE
ERROR: strconv.ParseInt: parsing "": invalid syntax```

BOOM!

**Comment by momack2** [comment]
Permalink to code: https://github.com/filecoin-project/lotus/blob/ef65ddf351fffa4fa1d7d368f1b7b720ec70afbf/cli/client.go#L796
