### ISSUE TITLE
(SnapDeals) `lotus-worker info` is missing RU PRU2

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/lotus#8110]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [x] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.14.0-rc7+calibnet+git.7fd4c9617
```

### Describe the Bug

**as the title stated.**

Add: RU PRU2

### Logging Information

```text
Session: 93e06d02-ad02-435f-9715-765a29210e91
Enabled: true
Hostname: lotustest5
CPUs: 48; GPUs: [GeForce RTX 2080 Ti GeForce RTX 2080 Ti]
RAM: 19.77 GiB/251.6 GiB; Swap: 0 B/0 B
Task types: FIN GET FRU UNS C1 PC2 PC1 PR1 AP 

21064779-0f18-4de7-a82b-fbdcaaa7d21e:
        Weight: 10; Use: Seal 
        Local: /mnt/md1/sealing
```

### Repo Steps

1. Run `lotus-worker info`

**Comment by arajasek** [comment]
@Reiers should've been fixed by #8090 #8092 #8093
