### ISSUE TITLE
Support built in actor updates

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8113]
We should have the logic ready to upgrade the FVM in the event of a consensus-critical bug being discovered in the FVM after M1 goes live for mainnet.

Testing that out in a testnet would be good too.

**Comment by jennijuju** [comment]
Rescope this issue to how to update the built in actor safely. (assuming that in FVM we will have network guards )

**Comment by jennijuju** [comment]
If things really are borked after the network v16 upgrade, we might want to consider upgrade the network to use the lotus vm with the latest stable actor (v7 like)

**Comment by arajasek** [comment]
> If things really are borked after the network v16 upgrade, we might want to consider upgrade the network to use the lotus vm with the latest stable actor (v7 like)

Elaborating on @jennijuju 's post, this would probably involve the following:

- having a migration that reverts to using synthetic CIDs
- introducing "v9" actors that are functionally equivalent to v8 actors (except for code cids)
- revert to using the LegacyVM for msg execution.

Note that this is disaster planning, and not related to the OP goal of supporting bulitin actor updates.

**Comment by raulk** [comment]
> Note that this is disaster planning, and not related to the OP goal of supporting bulitin actor updates

+1. In my head, the action plan here for the OP would be:

- If the bug is in actor code.
	1. Fix it in [`filecoin-project/builtin-actors`](https://github.com/filecoin-project/builtin-actors/)
	2. Produce a new release + bundle.
	3. Integrate it into Lotus by mapping it to a network version.
	4. Implement the migration logic to patch CodeCIDs in the state tree according to a lookup table, where the left side is populated from the previous bundle (or manually), and the right side is populated by the new bundle (or manually), joining on the actor type enum.
- If the bug is in ref-fvm and requires network versioning:
	1. Fix the bug behind version guards.
	2. Make a release of ref-fvm and integrate in Lotus.
	3. Implement the network upgrade logic in Lotus, no state migration necessary.

**Comment by arajasek** [comment]
By this point we have the logic / code needed for all of this, which is great!

**Comment by arajasek** [comment]
@jennijuju Feel free to reopen if you'd like to scope this down to "write down what would need to be done to upgrade builtin-actors".
