### ISSUE TITLE
ntwk v16 Migration integration and testing

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#8118]
- [ ]  Migration Integration
- [ ]  running the migration again using lotus-shed with the latest RC
- [ ]  Ensuring correctness and that it's fast enough
- [ ]  Running the migration in "online" mode -- this basically means letting the premigration happen while the lotus daemon is syncing the chain, making sure the time and memory usage are okay
- [ ]  Param finalization: based on time and memory usage of the experiments, we need to settle on the right number of and epochs for premigrations

**Comment by arajasek** [comment]
Note: when doing this look at the migration logic in specs-actors too as a re-review / audit.

**Comment by rjan90** [comment]
I think this can be closed now since network v16 has been shipped? Or are there some leftover items that would be nice to have in place for nv17?
