### ISSUE TITLE
checksum mismatch in param file

### ISSUE THREAD

**Issue by Elhorses** [filecoin-project/lotus#8124]
"checksum mismatch in param file" when I exe "lotus fetch-params <8MiB\512MiB\32GiB>", and my lotus version is: v1.14.0-rc6 or v1.14.0-rc7

**Comment by jennijuju** [comment]
missing logs and precise lotus version - https://github.com/filecoin-project/lotus/commit/9df19ae43683d0c47b46a6509fbfaea79fb8fd6c which was included in v1.14.0-rc7 should resolved this.

**Comment by Elhorses** [comment]
> missing logs and precise lotus version - [9df19ae](https://github.com/filecoin-project/lotus/commit/9df19ae43683d0c47b46a6509fbfaea79fb8fd6c) which was included in v1.14.0-rc7 should resolved this.
rc6: 1.14.0-rc6+calibnet+git.38605c9aa
rc7:  1.14.0-rc7+mainnet+git.7fd4c9617

missing logs:
ERROR: fetching proof parameters: checking file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-8-2-102e1444a7e9a97ebf1e3d6855dcc77e66c011ea66f936d9b2c508f87f2f83a7.vk failed: checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-8-2-102e1444a7e9a97ebf1e3d6855dcc77e66c011ea66f936d9b2c508f87f2f83a7.vk, 461aaa0801943abdb16d3ea0aafe9b64 != 80e366df2f1011953c2d01c7b7c9ee8e; checking file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-8-0-3b7f44a9362e3985369454947bc94022e118211e49fd672d52bec1cbfd599d18.vk failed: checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-8-0-3b7f44a9362e3985369454947bc94022e118211e49fd672d52bec1cbfd599d18.vk, ef0887a2649f170956b09fef392289d0 != 3a6941983754737fde880d29c7094905

**Comment by narkissos** [comment]
still not resolved in v1.14.1, roll back to 1.13
