### ISSUE TITLE
Markets process cannot connect to running daemon

### ISSUE THREAD

**Issue by masih** [filecoin-project/lotus#8129]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
master-spx.idxprov.rc-3
```

### Describe the Bug

When markets process is started with some delay after the daemon process, lip2p connection from markets to daemon fail with `read: connection reset by peer`.

Adding the peer ID of the markets to the list of protected peers does not resolve this issue either. 

But, when daemon is restarted, and markets connected to it as fast as possible (before other connections are established with daemon) the connection is successful.

Output from counting the number of connections:

```
$ lotus net peers | wc -l
409
```

Connection manager config:
```
   ConnMgrLow = 1000
   ConnMgrHigh = 1200
   ConnMgrGrace = "30s"
``

### Logging Information

```text
ERROR: connecting to full node (libp2p): failed to dial 12D3KooWNCcog7KWPsjWa1FmKyqeTeBxxc5cJf27X6vKBVqm1mW3:
  * [/ip4/192.168.20.40/tcp/10231] failed to negotiate security protocol: read tcp4 192.168.20.41:10241->192.168.20.40:10231: read: connection reset by peer
  * [/ip4/127.0.0.1/tcp/10231] dial tcp4 127.0.0.1:10231: connect: connection refused
  * [/ip4/78.31.252.253/tcp/10231] failed to negotiate security protocol: read tcp4 192.168.20.41:10241->78.31.252.253:10231: read: connection reset by peer
  * [/ip4/62.66.210.70/tcp/10231] dial tcp4 0.0.0.0:10241->62.66.210.70:10231: i/o timeout

2022-02-15T15:16:34.639+0100	ERROR	events	events/events_called.go:352	event diff fn failed: failed to get index 2709417 in root &{6 3 1711227 0xc0352e4510 0xc0359b56e0}: handler: websocket connection closed
```

### Repo Steps

1. Start Daemon, await for it to stat up.
2. Await for connections to it to accumulate.
3. Start markets process.

**Comment by rjan90** [comment]
Closing this issue, since this has been fixed on newer releases of Lotus.
