### ISSUE TITLE
lotus-storage-miner is claiming "success!" on file retrieval, when file isn't sealed, so the file returns with 0 bytes.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/lotus#819]
This is related to #763, #764, and #815

## Whats the problem?

See this screenshot:

<img width="1680" alt="Screen Shot 2019-12-09 at 9 54 32 AM" src="https://user-images.githubusercontent.com/310223/70459943-1a667800-1a6a-11ea-99c7-e08980cefc52.png">

* In the top terminal, we make a call to retrieve a file: `lotus client retrieve bafkreifieu3j4wztk3isarpd2ytokpdql2dj6nexoz3zd25f6tcjcywe44 image-outfile.gif`
* The response is `Success!`
* However image-outfile.gif is 0 bytes.

After discussion with @whyrusleeping and @magik6k it is because the file hasn't finished sealing. It looks like the solution here is to give a different response. It should not say the retrieval is successful on files that have not been sealed.

**Comment by jimmylee** [comment]
@magik6k put up this PR for addressing this issue partially: https://github.com/filecoin-project/lotus/pull/824

**Comment by magik6k** [comment]
cc @hannahhoward

**Comment by magik6k** [comment]
I think we got that fixed now
