### ISSUE TITLE
upgrade to lotus v1.14.2 failed

### ISSUE THREAD

**Issue by linhuatan** [filecoin-project/lotus#8220]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.14.2+mainnet+git.6347daf
```

### Describe the Bug

upgrade to lotus: v1.14.2 failed

### Logging Information

```text
error log message is


ERROR	statemgr	stmgr/forks.go:179	FAILED migration	{"height": "1594680", "from": "bafy2bzaceaclaz3jvmbjg3piazaq5dcesoyv26cdpoozlkzdiwnsvdvm2qoqm", "error": "migrating actors v6 state: upgrading to actors v7: context canceled", "errorVerbose": "migrating actors v6 state:\n    github.com/filecoin-project/lotus/chain/consensus/filcns.UpgradeActorsV7\n        /go/lotus/chain/consensus/filcns/upgrades.go:1230\n  - upgrading to actors v7:\n    github.com/filecoin-project/lotus/chain/consensus/filcns.upgradeActorsV7Common\n        /go/lotus/chain/consensus/filcns/upgrades.go:1282\n  - context canceled"}
```
```


### Repo Steps

it happened on one of my 2 nodes, the other node works well.  hard to reproduce

**Comment by Reiers** [comment]
**Hi @linhuatan** 

Like you stated, this is hard to reproduce. And all my nodes upgraded fine.

My suggestion is that you upgrade to the latest tag (1.14.3), download a snapshot and re-import the chain.
https://lotus.filecoin.io/docs/set-up/chain-management/

Thanks for the ticket !
