### ISSUE TITLE
Integrate autonat

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#825]
(this https://github.com/libp2p/go-libp2p-autonat)

Also expose NAT status through some command and tell miners to verify that they are reachable from the outside

**Comment by whyrusleeping** [comment]
I think this is actually done already, but we should expose the autonat client information through an api somehow

**Comment by whyrusleeping** [comment]
(probably want this wired through a CLI command)

**Comment by laser** [comment]
@whyrusleeping @magik6k 

> but we should expose the autonat client information through an api somehow

Would you list a few thingies here - properties of the autonat client - that you'd like to expose?

**Comment by laser** [comment]
@arajasek - pinging you for assistance in rounding up some requirements / expectations around CLI output
