### ISSUE TITLE
Integrate the FVM into Lotus via FFI callout, behind a feature flag

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#8256]

**Comment by rjan90** [comment]
Hey! I feel like this issue is outdated now, since the FVM is integrated in Lotus now. Or are there any work items in this issue that still are worth pursuing?

**Comment by vyzo** [comment]
lol stop bot!

**Comment by rjan90** [comment]
Bot stopped 😂

**Comment by Stebalien** [comment]
The original goal here was to speed up, e.g., IPLD blockstore access because cgo is really slow. However, we're unlikely to prioritize this, ever.

Going forward, we'd be better off moving the state-store into rust.
