### ISSUE TITLE
FVM: Investigate a receipt mismatch at epoch 1497990 +/-1

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8263]
Reported by Steb. While mismatches themselves are not M1 blockers, we need to understand what is wrong here, since it could indicate a bug in the FVM.

**Comment by arajasek** [comment]
After this, we should kick off another consensus check from the Chocolate upgrade all the way up to "latest".

**Comment by raulk** [comment]
This should be solved. Reopen if it wasn't.

**Comment by arajasek** [comment]
Will be closed by that^
