### ISSUE TITLE
lotus-shed miner-multisig add change-worker command

### ISSUE THREAD

**Issue by spark8899** [filecoin-project/lotus#8280]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Improvement Suggestion

The subcommand miner-multisig of lotus-shed lacks the change-worker function. The change-worker function requires the permission of onwer. If the onwer address is a multi-signature address, it is difficult to handle. Two subcommands can be added to enhance the modification of the multi-signature miner worker. address.

**Comment by rjan90** [comment]
Hey @spark8899!

Thanks for this issue and the PR. I see that you have gotten a feedback from the devs, and that parts of the code have been merged, so I´m closing this now.

Thanks again 😄
