### ISSUE TITLE
(wdPost) One sector `vanilla_proof fault` causes all the whole partition to fail.

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/lotus#8286]
### Discussed in https://github.com/filecoin-project/lotus/discussions/8274

<div type='discussions-op-text'>

<sup>Originally posted by **seantw1974** March  9, 2022, edited by: @Reiers </sup>
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus miner - proving(WindowPoSt)

### Lotus Version

```text
1.15.x 
ALL versions
```

### Describe the Bug

I got a HDD Failure and I used `lotus-miner proving check --slow` to find the issue ..
I found that I only have 1 sector error.

This causes the whole partition proof faults ..
In my opinion 1 sector should not result in failure of the whole partition/deadline. 

### Improvement Suggestion

```text
When its windowPost , your code just call fn "generate_window_post" and leave it alone ...
"Proving check --slow" call fn "generate_single_vanilla_proof" to check status ..
"generate_window_post" real code inside "RUST" and "filcoin_ffi" not in "lotus"
The real code inside "Filecoin_FFi=> genenrate_window_post or fi_generate_window_post " NO TRY/CATCH!!!
Lotus team should add try {} catch {} function inside !
```

**Comment by magik6k** [comment]
This should get fixed after https://github.com/filecoin-project/lotus/pull/7971 lands
