### ISSUE TITLE
lotus-miner backup file.cbor files with message "LOTUS_BACKUP_BASE_PATH env var not set"

### ISSUE THREAD

**Issue by orkowizard** [filecoin-project/lotus#8301]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.14.4+calibnet+git.5b33555fd+api1.4.0
Local: lotus-miner version 1.14.4+calibnet+git.5b33555fd
```

### Describe the Bug

When running and lotus-miner backup, gives error "LOTUS_BACKUP_BASE_PATH env var not set" when it is set.

### Logging Information

```text
lotus-miner log set-level debug
```

### Repo Steps

1. Run 'export LOTUS_BACKUP_BASE_PATH=/root/lotus-backups; lotus-miner backup backup.cbor'
2. See error 'ERROR: LOTUS_BACKUP_BASE_PATH env var not set'
...

**Comment by Reiers** [comment]
**Hi @orkowizard** 

Just tested it on my Storage Provider (miner) it works as expected here, so not an issue.

This environment should be set in the same terminal, that run the lotus-miner:
```
export LOTUS_BACKUP_BASE_PATH=/root/lotus-backups
lotus-miner run
```
then in other terminal:
`lotus-miner backup /root/lotus-backups/backup.cbor
`


From my testing:
```
lotus-miner backup /raid5/reiers/SP_Backup/11-3-22.cbor
Success
```

Miner log:
`2022-03-11T21:55:52.583+0100	INFO	backupds	backupds/datastore.go:130	Datastore backup done`

Lotus version:
```
Daemon:  1.14.4+mainnet+git.5b33555fd+api1.5.0
Local: lotus version 1.14.4+mainnet+git.5b33555fd
```
