### ISSUE TITLE
lotus sched plugin

### ISSUE THREAD

**Issue by llifezou** [filecoin-project/lotus#8315]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

1. Unbalanced task scheduling
2. There may be different scenario requirements
For example: https://github.com/filecoin-project/lotus/issues/7868

### Describe the solution you'd like

Extended scheduling, supporting multiple independent scheduling plugins

### Additional context

https://github.com/filecoin-project/community/pull/465

**Comment by llifezou** [comment]
The purpose of this issue is to discuss the technical feasibility of this plan. I hope to eventually merge the work into master, please let me know if you have a different opinion.

If you think this technical solution is not mature enough, it will exist as an independent branch, anyway, I want to get your opinion

**Comment by sedasdas** [comment]
Can I try it out?

**Comment by sedasdas** [comment]
Yes, a lot of people need it.

**Comment by llifezou** [comment]
> Yes, a lot of people need it.

I'm working on it, I'd be happy if you'd like to contribute

**Comment by sedasdas** [comment]
It would be a great achievement if you would contribute it.

**Comment by llifezou** [comment]
> It would be a great achievement if you would contribute it.

thank you, I will do it.

**Comment by llifezou** [comment]
Currently I plan to maintain this proposal separately and will not be merged into master anytime soon. I'm ready for long term maintenance. Minimize disruption to official team development plans.

Wondering if this job can be approved for development grants? @jennijuju

**Comment by hail100** [comment]
mark

**Comment by llifezou** [comment]
Existing scheduling is getting better and better, this idea will be closed, sorry
