### ISSUE TITLE
Used fvm sync failed in calibnet: parent state root not match

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/lotus#8344]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.15.1-dev+calibnet+git.9ea623e12.dirty
```

### Describe the Bug

parent state root did not match computed state 

### Logging Information

```text
2022-03-16T23:01:59.562+0800    INFO    chain   chain/sync.go:624   block validation    {"took": 0.006726387, "height": "779404", "age": -0.437149816}
2022-03-16T23:01:59.563+0800    ERROR   chain   chain/sync.go:948   failed to validate tipset: validating block bafy2bzacecrnmvx7hq2fyrlld43hvjhsboesgylj3zgv4wbegcawor4wkhzqo:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet.func1
        /root/hj/tmp/lotus_fvm/lotus/chain/sync.go:583
  - 1 error occurred:
    * parent state root did not match computed state (bafy2bzacedqudqfsx3dkzvn7j6z7pulmwhuaywqz24rotg2dealgf3lu33gx6 != bafy2bzacedrgl57ww7ntsftclbidj44jomf3ujst66uh664fliylh3j4x4ctc):
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).ValidateBlock.func4
        /root/hj/tmp/lotus_fvm/lotus/chain/consensus/filcns/filecoin.go:185
2022-03-16T23:01:59.563+0800    INFO    chain   chain/sync_manager.go:322   worker 338 done; took 8.263552ms
2022-03-16T23:01:59.563+0800    ERROR   chain   chain/sync_manager.go:253   error during sync in [bafy2bzacecrnmvx7hq2fyrlld43hvjhsboesgylj3zgv4wbegcawor4wkhzqo]: collectChain failed: collectChain syncMessages: message processing failed: validating block bafy2bzacecrnmvx7hq2fyrlld43hvjhsboesgylj3zgv4wbegcawor4wkhzqo: 1 error occurred:
    * parent state root did not match computed state (bafy2bzacedqudqfsx3dkzvn7j6z7pulmwhuaywqz24rotg2dealgf3lu33gx6 != bafy2bzacedrgl57ww7ntsftclbidj44jomf3ujst66uh664fliylh3j4x4ctc):
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by rjan90** [comment]
Hey @simlecode!

Thanks for the report. The current lotus build can only sync mainnet using FVM, so it´s expected to see these types of state root mismatches on the calibration network until the build supports calibnet!

Thanks again for the report!
