### ISSUE TITLE
Deals missing in indexer and lotus-miner info - 1.15.1-dev+mainnet+git.77a954c7c

### ISSUE THREAD

**Issue by Angelo-gh3990** [filecoin-project/lotus#8352]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.15.1-dev+mainnet+git.77a954c7c+api1.4.0
Local: lotus-miner version 1.15.1-dev+mainnet+git.77a954c7c
```

### Describe the Bug

Ok, well I'll try to explain it.
I went through the entire indexer upgrade : https://github.com/filecoin-project/lotus/discussions/8087
At first the dagstore upgrade didn't go as planned, so I had to restore the Market node from a backup that I made. Everything got up and running again and the Miner, Market and indexer config/upgrade went ok. So everything is up and running.

Now for me filing this bug, I noticed that there are only 1022 deals being indexed. (Well I think) Because that's how much there is in the dagstore being indexed. (lotus-miner --call-on-markets dagstore initialize-all)

So when I run "lotus-miner info" I see "Storage Deals: 1022", the same what the dagstore mentions. So I would say fine, that's accurate.
But I know I made more deals then that, if I run "lotus-miner sectors list --fast | grep -v CC | wc -l" so it doesn't even count the multiple deals per sector it says : 2632

I'm looking for an explanation and possible a way on reindex those sectors or reimport them so the indexer/dagstore/miner sees those deals again.

Also I have the feeling that I can retrieve all deals as far as I know and I'm pretty sure they are not all in that 1022 deals that are being indexed.

Any insights on this would be great.

Thanks

### Logging Information

```text
.
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by TippyFlitsUK** [comment]
Hey Angelo

Have you had a chance to dig any further with this?

Many thanks!!

**Comment by aarshkshah1992** [comment]
@Angelo-gh3990  Please note that the dagstore reinit does NOT create indices for deals that don't have an unsealed copy. I think that is why @TippyFlitsUK  is asking for stats on your sealed and update folders in the above comment.

**Comment by Angelo-gh3990** [comment]
Here is the folder info :

update folder always 1 in every attached LT storage location
total sealed 3863
total unsealed 2669

@TippyFlitsUK , we can discuss the "lotus-miner info all" offline if you want. It has to much info to share publicly.

thanks

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and is being completely removed from the code here:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
