### ISSUE TITLE
can not init lotus miner

### ISSUE THREAD

**Issue by alexchen123321** [filecoin-project/lotus#8366]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.15.2-dev+mainnet+git.1609317ac.dirty


lotus-miner version 1.15.2-dev+mainnet+git.1609317ac.dirty
```

### Describe the Bug

lotus sync wait
Worker: 807; Base: 1659696; Target: 1659697 (diff: 1)
State: complete; Current Epoch: 1659697; Todo: 0

Done!

 ------------------------------
lotus-miner init --owner=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  --no-local-storage
....................................
 
2022-03-24T09:26:31.903+0800	INFO	main	lotus-miner/init.go:169	Checking full node sync status
Worker: 9603; Base: 1659293; Target: 1659293 (diff: 0)
State: message sync; Current Epoch: 1659293; Todo: 0

Done!
2022-03-24T09:26:31.908+0800	INFO	main	lotus-miner/init.go:177	Checking if repo exists
2022-03-24T09:26:31.908+0800	INFO	main	lotus-miner/init.go:193	Checking full node version
2022-03-24T09:26:31.909+0800	INFO	main	lotus-miner/init.go:204	Initializing repo
2022-03-24T09:26:31.909+0800	INFO	repo	repo/fsrepo.go:140	Initializing repo at '/data/miner/storage'
2022-03-24T09:26:31.909+0800	INFO	main	lotus-miner/init.go:419	Initializing libp2p identity
2022-03-24T09:26:31.917+0800	INFO	badger	v2@v2.2007.2/levels.go:183	All 0 tables opened in 0s

2022-03-24T09:26:31.927+0800	INFO	badger	v2@v2.2007.2/levels.go:183	All 0 tables opened in 0s

2022-03-24T09:26:31.936+0800	ERROR	main	lotus-miner/init.go:264	Failed to initialize lotus-miner: creating miner failed:
    main.storageMinerInit
        /opt/lotus/cmd/lotus-miner/init.go:547
  - sender must exist on chain:
    main.createStorageMiner
        /opt/lotus/cmd/lotus-miner/init.go:664
  - resolve address f3v5ljznbrygtmjvwkvmwbepjbtlvo3b5lymq7vwl5n7vadybfuezs4ngya3czgsnbcgqkfhpz52yyc2urm5jq: actor not found
2022-03-24T09:26:31.936+0800	INFO	main	lotus-miner/init.go:269	Cleaning up /data/miner/storage after attempt...
ERROR: Storage-miner init failed

the lotus sync done already . I was trying to init lotus miner . get this error . who can help me 

### Logging Information

```text
lotus-miner log list
ERROR: could not get API info for StorageMiner: could not get api endpoint: API not running (no endpoint)
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'

**Comment by rjan90** [comment]
Hey @alexchen123321!

Thanks for the ticket. The reason the initialization fails is because you need to send some funds to the address before they can be found on-chain. Send a small amount of FIL to it, check that it has got a balance with `lotus wallet list` after a couple of epochs and then retry the initialization.

Another small tip, it seems like your are on the master-branch with some additional code-changes `lotus version 1.15.2-dev+mainnet+git.1609317ac.dirty`, please use a stable release like https://github.com/filecoin-project/lotus/releases/tag/v1.15.0.

Also troubleshooting like this is easier resolved in Slack so I reccomend you sign up and questions like these there 😃

**Comment by alexchen123321** [comment]
> Hey @alexchen123321!
> 
> Thanks for the ticket. The reason the initialization fails is because you need to send some funds to the address before they can be found on-chain. Send a small amount of FIL to it, check that it has got a balance with `lotus wallet list` after a couple of epochs and then retry the initialization.
> 
> Another small tip, it seems like your are on the master-branch with some additional code-changes `lotus version 1.15.2-dev+mainnet+git.1609317ac.dirty`, please use a stable release like https://github.com/filecoin-project/lotus/releases/tag/v1.15.0.
> 
> Also troubleshooting like this is easier resolved in Slack so I reccomend you sign up and questions like these there 😃

thanks very much . get it
