### ISSUE TITLE
[ lotus-daemon ] - segfaults in v1.15.0

### ISSUE THREAD

**Issue by mur-me** [filecoin-project/lotus#8396]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.15.0+mainnet+git.0ac1bbc+api1.5.0
Local: lotus version 1.15.0+mainnet+git.0ac1bbc
```

### Describe the Bug

We are running three lotus daemons behind load balancer. 
All calls are limited to `api:read` permissions.
We are also running lotus inside k8s(v1.19) and using docker as containers runtime.
For some reason we are catching segfault.

Please note, `/etc/lotus/docker/launch: line 36:    24 Segmentation fault      lotus daemon` it just a line from [how we are starting lotus](https://github.com/glifio/filecoin-docker/blob/008b4f701b643cdc4a4e1b2c0f304de1f9926063/scripts/launch#L25) 

Logs list:
[seg_fault_api_read_2_.log](https://github.com/filecoin-project/lotus/files/8370728/seg_fault_api_read_2_.log)
[seg_fault_api_read_2.log](https://github.com/filecoin-project/lotus/files/8370729/seg_fault_api_read_2.log)
[seg_fault_api_read_1.log](https://github.com/filecoin-project/lotus/files/8370730/seg_fault_api_read_1.log)
[seg_fault_api_read.log](https://github.com/filecoin-project/lotus/files/8370731/seg_fault_api_read.log)
[seg_fault_1.log](https://github.com/filecoin-project/lotus/files/8370733/seg_fault_1.log)
[seg_fault.log](https://github.com/filecoin-project/lotus/files/8370734/seg_fault.log)

### Logging Information

```text
Log level during this issues was `error` thus logs aren't detailed as `debug` ones.
When I enabled debug log level, issue have stopped to reproduce.
But, please check at least what I have at that moment, probably you will be able to find something suspicious.
And if issue reproduced with `debug` logs level, I'll post update to this issue.

Log list:

p2pnode
retrieval
payment-channel-settler
sectoraccessor
amt
types
advmgr
cmds
retrievaladapter
engine
tracing
vm
hello
wallet
markets-rtvl-reval
graphsync_allocator
client
panic-reporter
auth
net/conngater
ipns
chainxchg
storagemrkt
cborrrpc
rpcenc
dagstore/upgrader
beacon
fsm
peermgr
messagesigner
pstoremanager
connmgr
wallet-ledger
rpc
blockservice
incrt
filestore
storageadapter
watchdog
messagepool
relay
modules
dagstore
main
metrics-prometheus
fsjournal
nat
ulimit
swarm2
stream-upgrader
builder
test-logger
dht.pb
fil-consensus
routing/record
net/identify
basichost
actors
drand
importmgr
partialfile
tarutil
bs:sess
graphsync
fsutil
quic-transport
system
table
addrutil
p2p-holepunch
autonat
tcp-tpt
markets
badgerbs
lock
routedhost
sub
peerstore
providerstates
gs_request_executor
gs-unverifiedbs
stores
evtsm
badger
blankhost
conngater
backupds
providers
mplex
repo
dht/RtRefreshManager
market_adapter
unixfs
node
cmds/http
data-transfer
dt-impl
p2p-circuit
gen
chainstore
sectors
cliutil
retrieval-discovery
gs-notifications
storedask
statetree
autorelay
boguskey
dt_graphsync
retrievalmarket_impl
retrieval-fsm
graphsync_network
eventlog
fullnode
bitswap
p2p-config
splitstore
metrics
dht
ping
events
pathresolv
genesis
bs:peermgr
retrieval_network
pubsub
paych
disputer
build
mocknet
storagemarket_impl
markets-rtvl
rand
cli
bitswap_network
storageminer
dt-chanmon
gs-queryexecutor
alerting
diversityFilter
chain
peerstore/ds
data_transfer_network
discovery
ffi-wrapper
storagemarket_network
piecestore
miner
blockstore
paramfetch
bs:sprmgr
preseal
ffiwrapper
statemgr
reuseport-transport
chunk
```
```


### Repo Steps

1. Run lotus daemon
2. Do something some unknown request for now
3. See error

**Comment by magik6k** [comment]
This might be caused by hardware issues or datastore corruption, but in case there is some more interesting reason, it would be really helpful to get a gdb backtrace:

```
gdb ./lotus
(gdb) set logging on
(gdb) run daemon
[wait for sigsegv]
(gdb) bt
[quit after printing the backtrace]
[send gdb.txt]
```

(`dmesg` may also have some clues)
