### ISSUE TITLE
add command to delete retrievals

### ISSUE THREAD

**Issue by coryschwartz** [filecoin-project/lotus#8414]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Filecoin retrievals have no in-band method for removing retrievals.

filecoin retrievals end up in the repo under `retrievals/`, nodes that make a lot of deals can have a lot of data stored there without an obvious way to clear up the disk space. There ought to be a way to delete retrieved content other than just removing the car files found there.

### Describe the solution you'd like

Add a new command and API endpoint to remove retireved content

probably something like this.

```
ClientRemoveRetrieval(ctx context.Context, deal retrievalmarket.DealID) error
// remove referenece from the retrieval store
```

and a cli could be something like this

```
lotus client rm <id>
```

### Describe alternatives you've considered

Cleaning up using OS utilities works. But it probably isn't obvious that you can do this, and it isn't as easy to administer.

### Additional context

Nodes that make a lot of retrieval deals can have a couple of TB stored per week, the storage requirement can be higher than the chain. API clients, for example, dealbot, have no way to clean up this storage through API calls.

**Comment by coryschwartz** [comment]
You can assign this to me to implement

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system, [which reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and has been completely removed from the code:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
