### ISSUE TITLE
Gas Estimation around NV16

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8417]
While the final details of the FVM gas model are TBD, it seems likely that the cost of messages will increase after the upgrade to nv16. This poses a challenge for messages that are in the mempool at the time of the upgrade: they will have been estimated with the LegacyVM, and therefore are susceptible to running out of gas when they are executed using the FVM. 

We have a few options here:

1. Do nothing. A few epochs worth of messages will fail with Out of Gas, but all messages estimated after the upgrade will be fine. Most critical messages in Lotus have retry mechanisms on failure, so nothing too bad will happen.
2. Start naively overestimating at some period before the upgrade, by applying (say) a 2x factor. The question would be when to start doing this -- too early and messages that land before the upgrade will pay a lot in overestimation, too late and there will be some messages that were already estimated (and so might fail out of gas).
3. Start estimating using the actual FVM at some period before the upgrade. The same question about when to start would apply. This won't be too hard, but is probably more work than it's worth.

**Comment by arajasek** [comment]
I'm gonna go with option 2 for now.

**Comment by raulk** [comment]
Closed in https://github.com/filecoin-project/lotus/pull/8620.
