### ISSUE TITLE
Retrieval Deals Using CAR Export Method Creating Duplicate File Copies

### ISSUE THREAD

**Issue by TippyFlitsUK** [filecoin-project/lotus#8418]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [x] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.15.1-rc4+mainnet+git.6a88a94a8+api1.5.0
Local: lotus-miner version 1.15.1-rc4+mainnet+git.6a88a94a8
```

### Describe the Bug

As part of the [EverGreen](https://evergreen.filecoin.io/) program participants are required to initiate storage retrievals to download SlingShot data that is approaching expiry.

Example retrieval command:

`lotus client retrieve --provider f08403 --maxPrice 0 --car 'mAXCg5AIgCRPg8HwEzUbO597uxJ7b8TLOVEjJdTaXRWjK0g3XjEo' baga6e~ms5vteja__bafykb~uqn26geu.car
`

The command is executed successfully and the CAR file is downloaded to the storage path specified however an additional copy of the file is created in the `$LOTUS_MINER_PATH/retrievals` directory. The additional CAR file appears to be of identical size but is renamed with the `lotus-miner retrieval-deals list`  - `DealID`. 

The resulting folders produced from the above command:

```
~/baga6e~ms5vteja__bafykb~uqn26geu.car

$LOTUS_MINER_PATH/retrievals/1648634754134425009.car
```

This issue has the potential to crash the miner due to the rapid consumption of sealing disk space and has been reproduced.

### Logging Information

```text
N/A. The retrieval command completes successfully.
```

### Repo Steps

1. Initiate retrieval command with --car flag specified.
2. Examine folder structure

**Comment by iseriser** [comment]
There is even one more copy of the same file in lotus-miner repo `$LOTUS_MINER_PATH/deal-staging/fstmp4203583095`. So three copies of the same file.

**Comment by TippyFlitsUK** [comment]
Hey @iseriser 

The `fstmp` files in the `deal-staging` folder are expected and necessary. They will be automatically removed once the corresponding deal sector has completed sealing.

**Comment by iseriser** [comment]
In my setup those files are being created and never removed. I remove 'em like `find $LOTUS_MINER_PATH/deal-staging/ -type f -mtime +1 -delete`

**Comment by TippyFlitsUK** [comment]
You should be OK running the above delete command but just be aware that the sector will fail if you delete an `fstmp` file before sealing has completed,

**Comment by boramida** [comment]
Car file in /.lotus/retrievals is needed after active?

Daemon:  1.15.1-rc4+mainnet+git.6a88a94a8+api1.5.0
Local: lotus-miner version 1.15.1-rc4+mainnet+git.6a88a94a8

/.lotus/retrievals# du -h
535G

**Comment by RobQuistNL** [comment]
Probably related: https://github.com/filecoin-project/lotus/issues/5440

**Comment by RobQuistNL** [comment]
I think this should be easily fixed by directly writing to the given location instead of writing to the `~/.lotus/retrievals/` folder - and it would help us a lot :)

**Comment by Meest-NAM** [comment]
Please......~/.lotus/retrievals auto remove~~~~

**Comment by stuberman** [comment]
I am also seeing this problem, after a week of Evergreen renewals, I found 1.5T of duplicate CAR files in .lotus/retrievals

**Comment by benjaminh83** [comment]
Me-too. Have to prune this folder to make sure I don't crash the daemon, as this is where the chain data also builds up..

**Comment by benjaminh83** [comment]
@TippyFlitsUK Isn't the correct component for this bug: 

- [x]  lotus client

?

**Comment by TippyFlitsUK** [comment]
Updated... Thanks Ben!!

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and is being completely removed from the code here:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
