### ISSUE TITLE
lotus-miner proving deadlines shows sectors that are expired

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#8427]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus-miner version
Daemon:  1.14.2+mainnet+git.6347daf84+api1.4.0
Local: lotus-miner version 1.14.2+mainnet+git.6347daf84
```

### Describe the Bug

`lotus-miner proving deadlines` shows sectors that are expired.

![2022-04-03_14-47](https://user-images.githubusercontent.com/60559388/161415843-f4269d87-3cab-42a6-960a-cd19d725136f.png)
![2022-04-03_14-48](https://user-images.githubusercontent.com/60559388/161415852-5758bf91-bc3e-4405-afee-30d2c281cdcb.png)

running `lotus-miner sectors expired --remove-expired` does not resolve the display bug - i assume it needs a lotus-miner restart

### Logging Information

```text
not needed, display bug
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by f8-ptrk** [comment]
the sectors expired before the latest restart of the lotus-miner process

**Comment by rjan90** [comment]
Hi!

This should be fixed when https://github.com/filecoin-project/lotus/pull/8637 lands.

**Comment by rjan90** [comment]
Closing this issue now since the `compact-partitions` feature has landed! I'm currently testing this feature and will write up docs during the week. Will link the Docs-PR when I have written the initial commit.
