### ISSUE TITLE
`proving compute window-post <deadline>` fails when power is lost

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#8435]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.15.2-dev+mainnet+git.c802e4f5f
```

### Describe the Bug

This issue is based on the feedback/bug-report provided in the [PoSt test assignment](https://github.com/filecoin-project/lotus/discussions/8375#discussioncomment-2507265). It seems like the new `lotus-miner proving compute window-post [deadline index]` command does not work on a deadline/partition if that deadline/partition already has failed windowPoSt and lost power.

I see this command as an essential tool/command to validate that you are able to compute windowPoSt after failing a windowPoSt/loosing your storage power. So it would be ideal if this command also worked in that scenario.

### Logging Information

```text
lotus-miner proving compute window-post 0
Took 8.251475ms
[]
```

### Repo Steps

1. Miss windowPoSt for a deadline / loose storage power
2. Run `lotus-miner proving compute window-post <Deadline>` on the deadline that missed windowPoSt
3. The `lotus-miner proving compute window-post <Deadline>` command does not function properly.

**Comment by Reiers** [comment]
Miner log:
`2022-04-28T13:04:45.074+0200	WARN	storageminer	storage/wdpost_run.go:235	Checked sectors	{"checked": 0, "good": 0}`

Run: 
```
reiers@techhedge:~$ lotus-miner proving compute window-post 1
Took 4.47339ms
[]
```

_Same result if run at a wdPost worker._ 

All other deadlines that didnt fail, you can run fine. So only the deadlines that are missed cant be emulated/tested until the power is restored. 

Lotus version:
```
Daemon:  1.15.2-rc1+mainnet+git.dcf6f6414+api1.5.0
Local: lotus version 1.15.2-rc1+mainnet+git.dcf6f6414
```
