### ISSUE TITLE
Lotus PC1 worker can not utilize all cores/memory in FIL_PROOFS_USE_MULTICORE_SDR=1 mode

### ISSUE THREAD

**Issue by iseriser** [filecoin-project/lotus#8462]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.15.0+mainnet+git.0ac1bbc7a
```

### Describe the Bug

In case of using FIL_PROOFS_USE_MULTICORE_SDR=1 lotus-worker using only half of cores and half of memory available

### Logging Information

```text
FIL_PROOFS_USE_MULTICORE_SDR=0
------------------------------
%Cpu(s): 45.9 us,  1.0 sy,  0.0 ni, 53.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem : 1019535.+total,   4684.9 free, 970682.9 used,  44168.1 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  42012.5 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1050171 lotus     20   0  985.6g 944.9g      0 S  1501  94.9  70959:08 lotus-worker


FIL_PROOFS_USE_MULTICORE_SDR=1
------------------------------
%Cpu(s): 28.1 us,  0.7 sy,  0.0 ni, 71.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem : 1019535.+total,   3893.0 free, 524992.1 used, 490650.8 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used. 487706.1 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1078446 lotus     20   0  537.8g 510.7g  31180 S 925.6  51.3   7800:31 lotus-worker
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by rjan90** [comment]
Hey @iseriser!

Thanks for filing the issue report - although I´m not certain I completely understand the issue, and that this might just be a confusion about what the `FIL_PROOFS_USE_MULTICORE_SDR=1` env variable enables.

The `FIL_PROOFS_USE_MULTICORE_SDR` variable only enable one to use multiple cores to assemble nodes parents and perform some prehashing during the PreCommit1 phases, since this can be a bottleneck for the PC1-phase if it was entirely single core. The `multicore` part is restricted to a single core complex, which for the Zen2 architecture is for the most part 4 cores.

You can read more about that variable here: [https://github.com/filecoin-project/rust-fil-proofs](https://github.com/filecoin-project/rust-fil-proofs).

Did that clear up what the `FIL_PROOFS_USE_MULTICORE_SDR` evn does?

**Comment by iseriser** [comment]
If FIL_PROOFS_USE_MULTICORE_SDR=1 PC1 worker seals only 7 sectors in parallel (it consumes 25% of CPU power and 50% of RAM)
If FIL_PROOFS_USE_MULTICORE_SDR=0 PC1 worker seals only 15 sectors in parallel (it consumes 50% of CPU power and almost 100% of RAM)

**Comment by rjan90** [comment]
Yes, and depending on your CPU-architecture that might be reasonable. Which CPU do you have?

**Comment by iseriser** [comment]
```
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           33
Model name:                      AMD Ryzen 9 5950X 16-Core Processor
```

**Comment by rjan90** [comment]
The AMD 5950X CPU only has 2 core complexes, each with 8 cores. First the `FIL_PROOFS_USE_MULTICORE_SDR` variable is not optimized for the Zen3 architecture, as it´s mostly optimized for CPU with many cores and core complexes. So with that CPU you are definitely limited be the low amount of CCX´s and also the max amount of RAM it supports.

You can try to change the amount of `FIL_PROOFS_MULTICORE_SDR_PRODUCERS` to a lower the amount of worker threads, but I do not necessarily think it will change the outcome.

Anyways, this is not an issue with Lotus per se, so I´m closing this and we can rather discuss it in the lotus-help channel on Slack if you have further questions.
