### ISSUE TITLE
window-post failed,Tips - not on curve

### ISSUE THREAD

**Issue by tmzxi** [filecoin-project/lotus#8471]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner version 1.14.2+mainnet+git.a03b110.dirty
```

### Describe the Bug

window-post failed  error is not on curve

GeForce RTX 3090
AMD EPYC 7532 32-Core Processor

### Logging Information

```text
2022-04-11T23:24:35.347+0800    ERROR   storageminer    storage/wdpost_run.go:107       runPoStCycle failed: running window post failed:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPoStCycle
        /home/fil/git/lotus-1.14.2/storage/wdpost_run.go:742
  - not on curve

    Stack backtrace:
       0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
       1: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
       2: core::iter::adapters::process_results
       3: storage_proofs_core::compound_proof::CompoundProof::circuit_proofs
       4: storage_proofs_core::compound_proof::CompoundProof::prove
```

### Repo Steps

when run window-post ,Sometimes failed

**Comment by Reiers** [comment]
https://github.com/filecoin-project/lotus/issues/3576#issuecomment-1097730487

I answered your comment on the issue above. 
Closing issue until you have upgraded and build stock Lotus.

### Thanks!

**Comment by tmzxi** [comment]
Hi Reiers
     upgraded lotus version can this problem? I use lotus version is 1.14.2
I need upgraded 1.15?
