### ISSUE TITLE
Worker Restarted caused 3 snapup sectors to fault

### ISSUE THREAD

**Issue by scaseye** [filecoin-project/lotus#8485]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
~$ lotus --version
lotus version 1.15.1+mainnet+git.731da455d

~$ lotus-miner --version
lotus-miner version 1.15.1+mainnet+git.731da455d
```

### Describe the Bug

Was Snapping ~20 verified 32gig deals, two workers were killed by system with status=11/SEGV.  Results are attached. 

Run a 3 node miner.
Node 1:

- daemon
- miner
- market

Node 2:

- AP worker
- PC1 worker

Node 3: 1 AP, 4 PC2, 4 C2

- ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:14001 --addpiece=true --precommit1=false --unseal=false --precommit2=false --commit=false --replica-update=false --prove-replica-update2=false --regen-sector-key=false
- ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:15001 --addpiece=false --precommit1=false --unseal=false --precommit2=true --commit=false --parallel-fetch-limit=1
- ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:15002 --addpiece=false --precommit1=false --unseal=false --precommit2=true --commit=false --parallel-fetch-limit=1
- ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:15003 --addpiece=false --precommit1=false --unseal=false --precommit2=true --commit=false --parallel-fetch-limit=1
- ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:15004 --addpiece=false --precommit1=false --unseal=false --precommit2=true --commit=false --parallel-fetch-limit=1
- ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:16001 --addpiece=false --precommit1=false --unseal=false --precommit2=false --commit=true --parallel-fetch-limit=1
- ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:16002 --addpiece=false --precommit1=false --unseal=false --precommit2=false --commit=true --parallel-fetch-limit=1 
- ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:16003 --addpiece=false --precommit1=false --unseal=false --precommit2=false --commit=true --parallel-fetch-limit=1
- ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:16004 --addpiece=false --precommit1=false --unseal=false --precommit2=false --commit=true --parallel-fetch-limit=1

Node 3 Specs

- Ubuntu 20.04 (Focal Fossa):
- Processor: 2x AMD EPYC 7H12 (64 cores)
- GPUs: 2x RTX A6000 | 48 GB + 1x RTX A6000 | 2-Slot | NVLink
- Memory: 2 TB (32x 64 GB RDIMM ECC RAM)
- NVME drives: 3x 15.36 TB | U.2 | Gen4 | NVMe
- Disk1 - boot/os/lotusworker/proof ( 3TB )
- Disk2 - seal-scratch2 ( 15TB )
- Disk3 - seal-scratch3 ( 15TB )

```
Apr 13 10:05:13 homemate-server00 systemd[1]: lotus-worker-pc2-1.service: Main process exited, code=killed, status=11/SEGV
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit lotus-worker-pc2-1.service has exited.
-- 
-- The process' exit code is 'killed' and its exit status is 11.
Apr 13 10:05:13 homemate-server00 systemd[1]: lotus-worker-pc2-1.service: Failed with result 'signal'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit lotus-worker-pc2-1.service has entered the 'failed' state with result 'signal'.

Apr 13 10:10:39 homemate-server00 systemd[1]: lotus-worker-pc2-3.service: Main process exited, code=killed, status=11/SEGV
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit lotus-worker-pc2-3.service has exited.
-- 
-- The process' exit code is 'killed' and its exit status is 11.
Apr 13 10:10:39 homemate-server00 systemd[1]: lotus-worker-pc2-3.service: Failed with result 'signal'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit lotus-worker-pc2-3.service has entered the 'failed' state with result 'signal'.
Apr 13 10:10:49 homemate-server00 systemd[1]: lotus-worker-pc2-3.service: Scheduled restart job, restart counter is at 1.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Automatic restarting of the unit lotus-worker-pc2-3.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.

```

```
[pc2-3.log](https://github.com/filecoin-project/lotus/files/8485529/pc2-3.log)
[pc2-1.log](https://github.com/filecoin-project/lotus/files/8485528/pc2-1.log)
```

[sector-status-379.txt](https://github.com/filecoin-project/lotus/files/8485471/sector-status-379.txt)
[sector-status-398.txt](https://github.com/filecoin-project/lotus/files/8485472/sector-status-398.txt)
[sector-stauts-395.txt](https://github.com/filecoin-project/lotus/files/8485473/sector-stauts-395.txt)

### Logging Information

```text
logs attached
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by scaseye** [comment]
Happened again... lost another 2 sectors.

```
Apr 22 23:27:34 homemate-server00 systemd[1]: lotus-worker-pc2-2.service: Main process exited, code=killed, status=11/SEGV
Apr 22 23:27:34 homemate-server00 systemd[1]: lotus-worker-pc2-2.service: Failed with result 'signal'.

```

**Comment by scaseye** [comment]
any type of RETRIEVAL activity in the market node seems to cause this.

**Comment by scaseye** [comment]
if reproducing have 2-5 transfers happening while load snaping

~$ lotus-miner data-transfers list
Sending Channels

ID                   Status   Sending To   Root Cid     Initiated?  Transferred  Voucher                                   
1649820917281648842  Ongoing  ...EozWonTp  ...ie2s65ua  N           916.1MiB     ...lIncrease":1048576,"UnsealPrice":"0"}

**Comment by scaseye** [comment]
i wonder if poor worker scheduling is causing the worker to SIG out?  i have 8 workers running, but it assigns many tasks to only 2/3 workers.

8 workers running, 8 sectors being snapped, 3 workers assign all 8 sectors.  3 on 43069ad5, 3 on 91bb7649 and 2 on 6fd66ac0

```
ID        Sector  Worker    Hostname           Task  State    Time
d3396821  798     6fd66ac0  homemate-server00  PR2   running  8m3.6s
a2578e65  777     43069ad5  homemate-server00  RU    running  6m39.6s
b0b4ad74  775     91bb7649  homemate-server00  RU    running  6m23.5s
fc47ef6e  800     91bb7649  homemate-server00  RU    running  6m22.7s
2542062d  779     6fd66ac0  homemate-server00  RU    running  5m53.8s
3dd9a00b  778     91bb7649  homemate-server00  RU    running  3m18.7s
0c324843  776     43069ad5  homemate-server00  RU    running  1m51s
af3b9a33  799     43069ad5  homemate-server00  RU    running  1m50.4s
```

**Comment by scaseye** [comment]
worker log file.
[workerlog-pc2-2-00.tar.gz](https://github.com/filecoin-project/lotus/files/8556589/workerlog-pc2-2-00.tar.gz)

**Comment by scaseye** [comment]
another SEG fault on RU worker yesterday, running 1.15.2.  caused another sector to fail to copy the p_aux file.

**Comment by hyunmoon** [comment]
What an amazing piece of machineryQ!
Were you able to get it working properly for CC sealing in the first place?

**Comment by scaseye** [comment]
@hyunmoon yes, 100tibs worth.

**Comment by Reiers** [comment]
Hi @scaseye 

Thanks for the report. We are unable to reproduce the issue here.
We are rolling out a bunch of Snap Deal fixes in general, so things will get better soon.

Closing issue ticket for now - if you encounter the issue again in current/new releases, please open a new ticket and provide new logs. 
Thanks !
