### ISSUE TITLE
Docker Image Support

### ISSUE THREAD

**Issue by bonedaddy** [filecoin-project/lotus#849]
I wrote a [docker image](https://github.com/RTradeLtd/lotus/blob/master/Dockerfile) for `lotus`. Should I open a PR here? There is also now a docker-compose image :)

**Comment by eshon** [comment]
@bonedaddy getting a 404 to your link. There's also a thread for one here: https://github.com/filecoin-project/lotus/pull/745

**Comment by sixcorners** [comment]
Is either of these docker images published anywhere in an official capacity?

**Comment by eshon** [comment]
> Is either of these docker images published anywhere in an official capacity?

@sixcorners there are some docker images in tools/dockers but they are community-contributed

**Comment by whyrusleeping** [comment]
as @eshon mentions, we have some community contributed docker files in `tools/dockers`
