### ISSUE TITLE
Available state not handled correctly

### ISSUE THREAD

**Issue by Angelo-gh3990** [filecoin-project/lotus#8498]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
Daemon:  1.15.2-rc1+mainnet+git.dcf6f6414.dirty+api1.5.0
Local: lotus-miner version 1.15.2-rc1+mainnet+git.dcf6f6414.dirty
```

### Describe the Bug

I was looking into why bidbot was not ingesting data anymore...
We found out that the snap state (Available) is counted towards a sealing state, so it sees it as oh I can't seal anymore because you have so many sectors sealing already.
When I look at the lotus code : https://github.com/filecoin-project/lotus/blob/0ac1bbc7ae5ba4fd26392452bc18efda89cff64b/extern/storage-sealing/sector_state.go#L150
I think the "Available" state from snap-deals should be added to make clear to developers to handle that state correctly.

### Logging Information

```text
lotus-miner info will give you:

Sectors:
        Available: 23

That status is not in the link above
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by magik6k** [comment]
It is there on master / 1.15.2-rc1

https://github.com/filecoin-project/lotus/blob/4bd039902c66a3674a3c317ab0bd00e3f358c54c/extern/storage-sealing/sector_state.go#L166

**Comment by magik6k** [comment]
We probably want to add an API method to get those stats from lotus so that this logic doesn’t need to be reimplemented/updated outside of lotus

**Comment by jennijuju** [comment]
As magik stated this should be closed by the latest release rc, @rjan90 could you please confirm and reopen the ticket if the issue remains?
on lotus we have #8466 so that developers who’s building tooling on top of lotus May have an easier life to keep up with the changes
