### ISSUE TITLE
Pick the default indexer ingest topic based on network name

### ISSUE THREAD

**Issue by masih** [filecoin-project/lotus#8510]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

The indexer ingest topic in default config is fixed to `/indexer/ingest/mainnet`. But the allowed subscriptions topic name for the indexer is constructed based on the network name. For example, a miner running on `calibnet` is only allowed to contact to `/indexer/ingest/calibnet` and would fail to join the topic if the default config is not overridden to reflect the network name.

Ideally the default topic name should be selected based on network name unless explicitly specified by the user.

**Comment by jennijuju** [comment]
yes we need this, currently lotus node cannot start base on default settings (index provider enabled) on testnets and devnets. @masih are you planning to contribute a PR on this by any chance?

**Comment by masih** [comment]
Happy to; please feel free to assign this one to me thanks 🙏

**Comment by jennijuju** [comment]
> Happy to; please feel free to assign this one to me thanks 🙏

Thank YOU
