### ISSUE TITLE
ERROR: listing keystore: permissions of key: 'XXXX' are too relaxed, required: 0600, got: 0644

### ISSUE THREAD

**Issue by Alteryy** [filecoin-project/lotus#8529]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.15.0+mainnet+git.0ac1bbc7a
```

### Describe the Bug

./lotus wallet list
ERROR: listing keystore: permissions of key: 'XXXX' are too relaxed, required: 0600, got: 0644

What's wrong with this, the backed up keystore file cannot be accessed on the new node？

### Logging Information

```text
./lotus wallet list
ERROR: listing keystore: permissions of key: 'XXXX' are too relaxed, required: 0600, got: 0644
```

**Comment by Reiers** [comment]
`sudo chmod -R 600 /.lotus/keystore`

If you are still experiencing problems, please ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)
