### ISSUE TITLE
retrieval exchange: stream reset

### ISSUE THREAD

**Issue by linmuqin** [filecoin-project/lotus#853]
ylz@lotus:~$ lotus client retrieve bafkreia7izexnprrdhnmorhnxmcfhi7cpvvvwhcs2ieojray6uequlvy5i 1.jpg
2019-12-11T11:55:07.921+0800	WARN	main	lotus/main.go:72	RetrieveUnixfs: retrieval exchange: stream reset

**Comment by whyrusleeping** [comment]
more information is needed, its likely the other party is not online. Please open a new issue if the problem persists
