### ISSUE TITLE
ERROR: open minimal_finality_stateroots_1751760_2022-04-25_04-00-00.car: no such file or directory

### ISSUE THREAD

**Issue by coder-chenda** [filecoin-project/lotus#8554]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
v1.15.1
```

### Describe the Bug

<img width="852" alt="image" src="https://user-images.githubusercontent.com/83049018/165217784-27abce00-4ccd-472f-87b5-4cc13ecd57a9.png">

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/83049018/165217835-ec8320b9-2616-4303-9a95-33ec08e8a161.png">

not found the snapshot minimal_finality_stateroots_1751760_2022-04-25_04-00-00.car

### Logging Information

```text
ERROR: open minimal_finality_stateroots_1751760_2022-04-25_04-00-00.car: no such file or directory

ERROR: open minimal_finality_stateroots_1751760_2022-04-25_04-00-00.car: no such file or directory
ERROR: open minimal_finality_stateroots_1751760_2022-04-25_04-00-00.car: no such file or directory
```

### Repo Steps

ERROR: open minimal_finality_stateroots_1751760_2022-04-25_04-00-00.car: no such file or directory

**Comment by rjan90** [comment]
Hey @coder-chenda! You get that error because it can´t find the snapshot file you have downloaded - please add full path to the snapshot-file like this:

`lotus daemon --import-snapshot /path/to/minimal_finality_stateroots_xx_xx_xx.car`

For futher question like these, you can ask in the [Discussion forume](https://github.com/filecoin-project/lotus/discussions). 😄

**Comment by coder-chenda** [comment]
> 
I use docker to start. How to define this path?
