### ISSUE TITLE
lotus-miner proving check broken

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#8560]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [x] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
v1.15.2-rc1
```

### Describe the Bug

Command issued: `lotus-miner proving check 0`

Output:

`ERROR: rg is nil`

### Logging Information

```text
$ lotus-miner proving check 0
ERROR: rg is nil
```

### Repo Steps

1. Run wdpost / winningpost workers remote
2. Run `lotus-miner proving check 0`
3. See error `ERROR: rg is nil`

**Comment by Reiers** [comment]
Hi @RobQuistNL 

Thanks for the report. I have added labels. 
I will repro and add more logs.

**Comment by Reiers** [comment]
Hi @RobQuistNL 

Can you please tell me your exact environment(how the worker are connected to miner, does the wdPost worker have the storage paths to long term storage in `storage.json` or does it do through the miner , gpu or cpu, does the deadline have any expired sectors or faults etc.) 
- basically what you did to cause it?

Have been running these 3 deadlines over and over again with two wdPosts workers incl. the miner, and still unable to repro this and #8561 :

## Repro session:
```
deadline  partitions  sectors (faults)  proven partitions
0         1           2349 (0)          0
3         1           2349 (0)          0
4         1           2349 (0)          0
```

## Deadline 0
```
2022-04-28T13:19:25.596+0200	INFO	storageminer	storage/wdpost_run.go:662	computing window post	{"batch": 0, "elapsed": 111.126774509, "skip": 0, "err": null}

reiers@techhedge:~$ lotus-miner proving compute window-post 0
Took 3m24.560894065s
[{"Deadline":0,"Partitions":[{"Index":0,"Skipped":[0]}],"Proofs":[{"PoStProof":8,"ProofBytes":"jvNzO1LVAXTwftxByRh8GJFD+QCnOzYzoO/2PMmN7n2LcNAgyQUV33wkc+KCNvDAp/gXSdVomIe0Jq1hkowL0uIv0M0LMQgd9TzD/hYE1pPzBnsF78YDrI6XhUskZv7/A2TKMpcpNnRpO6d6x1RyAaAmPAnPBnY7PA8j8q027hQx+0XnK9CXhsj0T1eF+0ynh6FlAFb8qpeHXOMfx20QaoYEsZGBfTRO/q6SHqECzga8a+zbx0B9kMh/CgmgSVlx"}],"ChainCommitEpoch":0,"ChainCommitRand":null}]
```
## Deadline 3
```
2022-04-28T13:25:12.762+0200	INFO	storageminer	storage/wdpost_run.go:662	computing window post	{"batch": 0, "elapsed": 95.413437481, "skip": 0, "err": null}

reiers@techhedge:~$ lotus-miner proving compute window-post 3
Took 4m47.536180016s
[{"Deadline":3,"Partitions":[{"Index":0,"Skipped":[5965,1]}],"Proofs":[{"PoStProof":8,"ProofBytes":"kam4tLUboIiz6OXtQfznhKpTZo6ipU6y/9rhdkLYwwGarEL8eoTUrDFoaThp1jYlok6/lkHJosm93tkCk1yvB7wWkWnn6QCly+amsWVGK8DQoJFHgPVdMZFD3zP8L7tWAqOjo/sfwtnLlmmB3s+yhXdO39RuIivk35aYeaxNFewUQOgZoJmyz5VeBNMN4IApj6Kw0mbMcV2NjPRPpqtaRkT/ZaPk+Jk5NpE2vznZJvV29vmbuoptcTTfvikF+Nmd"}],"ChainCommitEpoch":0,"ChainCommitRand":null}]
```
## Deadline 4
```
2022-04-28T13:29:41.409+0200	INFO	storageminer	storage/wdpost_run.go:662	computing window post	{"batch": 0, "elapsed": 91.086533541, "skip": 0, "err": null}

reiers@techhedger:~$ lotus-miner proving compute window-post 4
Took 3m42.929210157s
[{"Deadline":4,"Partitions":[{"Index":0,"Skipped":[0]}],"Proofs":[{"PoStProof":8,"ProofBytes":"rDpYiiD5sCW36O7pDEha6+OwlJiPxMYzAc2w2d3KYZUCTkJNOLkUcLxXEd2h31kno6zkA+fVBFIDm4xTWyjqYg+vFt/2GdcxDw6nGDkttuq1sIdN7INwwRTvZMeMbUWmGUm+B7ORWuo8AvPxMjNNN8efTCegzzWN66ARd2tSpibUKhQz2C5QkjhVpbLzP+9isEMW6nvsx7nuTweD8WOlunwf+cMNlNZEeNQeg/m5VnolZH/B5vKqzlkktXgvY+wh"}],"ChainCommitEpoch":0,"ChainCommitRand":null}]
```

Lotus version:
```
Daemon:  1.15.2-rc1+mainnet+git.dcf6f6414+api1.5.0
Local: lotus version 1.15.2-rc1+mainnet+git.dcf6f6414
```

Thank you !

**Comment by RobQuistNL** [comment]
The compute window post command you posted works :)

Can you try `lotus-miner proving check 0` ? ;)

**Comment by RobQuistNL** [comment]
```
lotus-miner proving check --faulty 0
```

gives the same error

**Comment by Pegasus-starry** [comment]
I have met the same issue. It related to the code change of CheckProvable in extern/sector-storage/faults.go
