### ISSUE TITLE
lotus-miner proving compute window-post shows weird results

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#8561]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.15.2-rc1
```

### Describe the Bug

Running `lotus-miner proving compute window-post 0` yields weird results. I assumed "skipped" would contain skipped sector numbers. This bunch of random numbers makes no sense to me. Can't be sure its not sector numbers because of https://github.com/filecoin-project/lotus/issues/8560 though.

### Logging Information

```text
$ lotus-miner proving compute window-post 0
Took 3m35.236895707s
[{"Deadline":0,"Partitions":[{"Index":0,"Skipped":[3,1,4,1,2,2,1,1,1,1,2,1,2,1,7,1,7,1,1,1,1,1,4,2,2,2,1,2,10,3,5,1,6,2,9,1,5,1,5,1,1,2,1,2,1,1,6,1,1,2,2,1,1,2,1,3,1,1,3,1,2,2,1,2,1,1,3,1,1,3,5,2,1,3,1,3,5,2,1,1,4,1,2,1,5,1,1,3,1,3,1,1,1,3,1,1,13,3,1,2,1,1,2,2,1,1,13,1,1,1,1,1,2,3,1,1,1,1,3,1,1,1,1,1,1,1,1,3,4,1,1,3,1,1,2,2,1,1,1,3,4,4,1,2,1,1,4,1,1,1,1,1,3,1,1,6,1,4,4,2,10,1,2,2,8,2,4,1,1,1,5,1,1,2,1,1,1,3,1,1,5,4,1,1,3,1,1,1,3,3,2,1,3,1,1,4,1,1,2,1,2,1,2,2,2,4,1,1,1,1,1,1,1,5,3,1,3,2,1,1,2,2,1,1,1,1,5,1,1,1,2,1,2,1,1,1,1,3,1,1,1,1,1,3,1,1,3,1,1,2,1,1,2,2,5,2,1,1,1,1,1,1,1,2,2,1,1,2,1,3,5,1,1,2,5,2,2,5,2,1,4,5,6,5,1,3,2,1,2,1,1,2,2,6,1,1,1,2,2,3,2,2,2,1,2,1,1,3,3,1,1,1,1,1,3,1,3,2,1,2,1,3,2,1,2,3,6,1,1,1,2,2,2,2,3,2,1,2,2,1,5,3,2,1,8,6,7,1,1,4,2,11,1,5,2,5,1,19,1,5,2,1,1,4,1,1,1,1,2,3,2,4,1,3,2,3,3,1,1,2,1,8,1,1,1,2,1,1,1,1,2,3,1,3,1,8,1,1,2,1,1,4,1,1,3,1,4,1,1,1,2,1,3,1,4,1,2,1,2,2,1,1,2,1,3,1,2,3,1,2,1,1,1,2,2,6,1,2,3,1,1,2,2,3,2,3,1,3,3,1,5,2,2,1,1,1,2,1,2,1,2,1,4,2,2,1,2,1,3,1,2,2,1,1,2,1,1,1,2,1,1,4,6,1,2,3,4,1,1,1,1,1,1,1,2,2,1,1,1,1,1,1,2,1,2,1,1,1,2,1,2,1,1,1,2,1,1,1,1,2,1,1,2,3,1,1,4,4,1,2,1,3,7,3,1,2,1,8,1,1,1,5,2,4,1,1,1,1,1,5,3,2,2,4,1,1,3,1,1,8,4,1,2,1,4,1,1,1,4,1,5,3,2,1,1,2,1,3,7,2,3,7,1,1,3,1,2,2,1,1,1,1,1,2,2,1,5,2,1,1,1,1,1,2,4,1,1,5,1,2,2,2,1,1,1,9,1,3,1,2,7,2,2,4,1,1,3,1,2,1,1,2,11,1,1,2,2,1,1,2,2,1,2,2,1,1,2,1,3,1,2,3,2,1,2,2,1,2,5,3,2,1,1,2,1,1,1,1,1,1,1,1,2,1,3,2,1,1,2,3,6,2,2,1,2,1,1,1,1,4,3,3,2,1,2,1,4,2,1,1,1,3,1,4,1,1,1,7,1,1,1,1,1,1,1,3,8,1,2,4,1,1,1,1,1,4,2,1,1,1,3,1,3,4,3,1,3,1,3,1,1,2,2,1,2,1,5,3,5,2,2,2,3,1,2,2,3,2,2,2,1,2,1,1,1,4,1,1,2,1,1,1,2,3,1,11,1,2,1,1,2,1,2,2,1,1,1,1,5,3,1,1,1,1,2,1,3,2,2,1,4,6,2,2,2,3,1,1,1,5,1,1,2,1,2,2,4,3,1,2,2,1,1,3,1,1,1,2,1,1,1,4,3,1,1,1,1,2,1,1,2,2,2,1,3,1,1,2,4,1,1,1,2,2,1,2,4,1,1,1,1,2,4,1,1,1,1,3,2,1,3,3,2,1,5,1,2,2,1,1,3,3,1,1,2,2,1,1,2,1,3,2,3,1,6,2,1,2,3,2,2,1,2,1,1,1,2,1,1,1,1,1,1,4,1,2,1,2,4,2,2,1,3,3,2,2,1,1,1,1,2,2,2,3,1,1,1,1,1,1,2,1,1,2,1,2,1,2,1,2,1,2,1,1,2,1,1,3,3,1,1,1,2,3,3,10,2,1,3,4,1,1,1,3,1,6,1,1,3,1,3,1,2,1,3,1,1,2,2,2,3,1,2,1,2,4,1,1,3,2,2,1,6,1,1,2,2,3,2,2,1,2,2,1,8,1,2,2,2,4,8,1,5,1,2,1,3,1,1,3,3,3,4,5,5,1,1,3,1,2,2,2,4,1,3,1,1,1,1,2,3,2,2,2,4,2,1,4,2,4,1,6,3,2,1,5,2,1,3,1,1,3,3,1,1,1,3,1,2,1,1,1,2,1,3,1,1,2,4,1,3,1,4,1,1,1,2,1,2,1,1,1,1,1,7,1,2,1,1,2,3,1,7,1,1,1,7,1,10,1,1,1,1,1,6,2,80,1,5,1,20,1,22,1,5,1,10,1,7,1,12,1,14,1,14,1,2,1,4,1,3,2,3,1,1,1,2,1,2,2,4,1,4,1,3,1,1,4,1,1,1,1,5,1,1,3,2,2,4,1,2,1,5,1,3,1,1,4,3,7,1,7,1,1,4,1,1,1]}],"Proofs":[{"PoStProof":8,"ProofBytes":"tm1gl4xzdTyJ5arbcVIs9bGcJeV70NPEzcR7jnFV7oVXDZIUkQglelePhEUOaQBAiNFt42IrqkWweg4mkCLEra1z2h8WfVNTbreZCV2hfmpgG6P9P4Ed3dnn93d2UUH+BIdtE/1Ek2UvwYPW5MLDIOAlZ26khyAOTDFk/kyGyedFySruzvq6AXntgP8p7yNjh5X18VNoWFCzjNvV3p+KqjK11S3uAJhh9S40ZVPeqLCsOQvcpPttNAztEZ6I/jAg"}],"ChainCommitEpoch":0,"ChainCommitRand":null}]
```

### Repo Steps

1. Run `lotus-miner proving compute window-post 0`

**Comment by Reiers** [comment]
Hi @RobQuistNL 

Im transferred my results from the other issue. 

Have been running these 3 deadlines over and over again with two wdPosts workers incl. the miner, and still unable to repro this. Still investigation - let me know if you find some more info of what cause this output. 

## Repro session:
```
deadline  partitions  sectors (faults)  proven partitions
0         1           2349 (0)          0
3         1           2349 (0)          0
4         1           2349 (0)          0
```

## Deadline 0
```
2022-04-28T13:19:25.596+0200	INFO	storageminer	storage/wdpost_run.go:662	computing window post	{"batch": 0, "elapsed": 111.126774509, "skip": 0, "err": null}

reiers@techhedge:~$ lotus-miner proving compute window-post 0
Took 3m24.560894065s
[{"Deadline":0,"Partitions":[{"Index":0,"Skipped":[0]}],"Proofs":[{"PoStProof":8,"ProofBytes":"jvNzO1LVAXTwftxByRh8GJFD+QCnOzYzoO/2PMmN7n2LcNAgyQUV33wkc+KCNvDAp/gXSdVomIe0Jq1hkowL0uIv0M0LMQgd9TzD/hYE1pPzBnsF78YDrI6XhUskZv7/A2TKMpcpNnRpO6d6x1RyAaAmPAnPBnY7PA8j8q027hQx+0XnK9CXhsj0T1eF+0ynh6FlAFb8qpeHXOMfx20QaoYEsZGBfTRO/q6SHqECzga8a+zbx0B9kMh/CgmgSVlx"}],"ChainCommitEpoch":0,"ChainCommitRand":null}]
```
## Deadline 3
```
2022-04-28T13:25:12.762+0200	INFO	storageminer	storage/wdpost_run.go:662	computing window post	{"batch": 0, "elapsed": 95.413437481, "skip": 0, "err": null}

reiers@techhedge:~$ lotus-miner proving compute window-post 3
Took 4m47.536180016s
[{"Deadline":3,"Partitions":[{"Index":0,"Skipped":[5965,1]}],"Proofs":[{"PoStProof":8,"ProofBytes":"kam4tLUboIiz6OXtQfznhKpTZo6ipU6y/9rhdkLYwwGarEL8eoTUrDFoaThp1jYlok6/lkHJosm93tkCk1yvB7wWkWnn6QCly+amsWVGK8DQoJFHgPVdMZFD3zP8L7tWAqOjo/sfwtnLlmmB3s+yhXdO39RuIivk35aYeaxNFewUQOgZoJmyz5VeBNMN4IApj6Kw0mbMcV2NjPRPpqtaRkT/ZaPk+Jk5NpE2vznZJvV29vmbuoptcTTfvikF+Nmd"}],"ChainCommitEpoch":0,"ChainCommitRand":null}]
```
## Deadline 4
```
2022-04-28T13:29:41.409+0200	INFO	storageminer	storage/wdpost_run.go:662	computing window post	{"batch": 0, "elapsed": 91.086533541, "skip": 0, "err": null}

reiers@techhedger:~$ lotus-miner proving compute window-post 4
Took 3m42.929210157s
[{"Deadline":4,"Partitions":[{"Index":0,"Skipped":[0]}],"Proofs":[{"PoStProof":8,"ProofBytes":"rDpYiiD5sCW36O7pDEha6+OwlJiPxMYzAc2w2d3KYZUCTkJNOLkUcLxXEd2h31kno6zkA+fVBFIDm4xTWyjqYg+vFt/2GdcxDw6nGDkttuq1sIdN7INwwRTvZMeMbUWmGUm+B7ORWuo8AvPxMjNNN8efTCegzzWN66ARd2tSpibUKhQz2C5QkjhVpbLzP+9isEMW6nvsx7nuTweD8WOlunwf+cMNlNZEeNQeg/m5VnolZH/B5vKqzlkktXgvY+wh"}],"ChainCommitEpoch":0,"ChainCommitRand":null}]
```

Lotus version:
```
Daemon:  1.15.2-rc1+mainnet+git.dcf6f6414+api1.5.0
Local: lotus version 1.15.2-rc1+mainnet+git.dcf6f6414
```

Thank you !

**Comment by RobQuistNL** [comment]
I you can cause a few sectors to be faulty (e.g. rename the cache folder) and you run it again, the results look really strange. 

I almost feel like someone is retuning the array / loop index in the "skipped" instead of the actual sector number

**Comment by magik6k** [comment]
The `Skipped` array contains a bitfield RLE in json form - see https://github.com/filecoin-project/go-bitfield/blob/master/rle/rleplus.go#L70-L71

**Comment by magik6k** [comment]
If you want to interpret the skipped list as a more readable format:
- Let's say you have this example list: `[0, 3, 5, 2]`
- Make each value be sum of all previous values: `[0, 3, 8, 10]`
- Take numbers pairs to get sector ranges: `0-3, 8-10`

(Yes, we need to make output from this command human readable)

**Comment by beck-8** [comment]
```All returns a slice of set bits in sorted order.
For example, given:
    1 0 0 1
All will return:
    []uint64{0, 3}
This operation's runtime is O(number of bits).
This composite literal allocates a new struct instance with the given values.
You may either specify the field values in order or use their names.
```
For example, this example is not easy to understand.🤯
