### ISSUE TITLE
long Duration for Block Validation after 1.15.1 for full history Lotus node  

### ISSUE THREAD

**Issue by mur-me** [filecoin-project/lotus#8565]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.15.1+mainnet+git.731da45+api1.5.0
Local: lotus version 1.15.1+mainnet+git.731da45
```

### Describe the Bug

Hi, Glif.io team faced with long duration for block validation after update update to the newest stable version `1.15.1`.
Most of the time node is working as usual but sometimes we are facing that block could be validated for more than the 120 seconds.
I haven't observed any memory usage spikes when it is happened.
Have it looks like on the graph in ms:
![image](https://user-images.githubusercontent.com/7295623/165773807-2131b982-08e3-49e1-839f-d4e539e15992.png)

Logs for the spike from screenshot:
[space07_long_block_validation.txt](https://github.com/filecoin-project/lotus/files/8583621/space07_long_block_validation.txt)

**I want to highlight, that we are observing this behavior on our both archive nodes 3-4 times per day:**
![image](https://user-images.githubusercontent.com/7295623/165778424-11beee32-0bb1-44fc-a049-88914450f79a.png)

### Logging Information

```text
Example from logs:

2022-04-28T08:21:48.707Z        INFO    chain   chain/sync.go:624       block validation        {"took": 141.064101394, "height": "1760915", "age": 258.70718164}
```
Please check the `space07_long_block_validation.txt` file in the previous section
```

And this happens time to time with our both archive nodes, check the screenshot for the last 10 days:
![image](https://user-images.githubusercontent.com/7295623/165777806-f3dbd624-b78d-40a9-acd8-99452f31ba22.png)


### Repo Steps

1. Run full node from the genesis block
2. Update it to the 1.15.1 version
3. Observe spontaneous long Duration for Block Validation after 1.15.1 for full node

**Comment by rjan90** [comment]
Just adding a update here that although the symptoms are different in this issue (slow sync) then in https://github.com/filecoin-project/lotus/issues/7803 - where the sync was stuck, they seem somewhat related.

So would be nice to get some feedback if this issue is still observable when https://github.com/filecoin-project/lotus/pull/8635 lands and gets tested.

**Comment by Stebalien** [comment]
I don't have a lot of data, but these long block validation times look highly correlated with badger compaction.

![plot](https://user-images.githubusercontent.com/310393/171969578-04bfc5a2-cc34-47f5-8d33-70bed0558d91.png)

**Comment by mur-me** [comment]
Hi @Stebalien, how did you collect this data? Probably, I can try to check this on my end

**Comment by rjan90** [comment]
Nice! Glad to hear that there are way less spikes in the validation times after the fix 😄! If you see similar issues again, do not hesitate to reopen this or open a new issue!

Thank you so much for the issue report, and testing the new version!
