### ISSUE TITLE
WDPost skips completely full sector and causes faults

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#8570]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.15.2-rc1
```

### Describe the Bug

This speaks for itself;

```
$ lotus-miner proving compute window-post 28
Took 6.047981ms
[]
```

Log event:
```
{"level":"warn","ts":"2022-04-30T10:43:01.473Z","logger":"storageminer","caller":"storage/wdpost_run.go:235","msg":"Checked sectors","checked":0,"good":0
```

```
$ lotus-miner proving deadlines
deadline  partitions  sectors (faults)  proven partitions
0         1           2349 (0)          0
1         1           2349 (0)          0
2         1           2349 (0)          0
3         1           2349 (0)          0
4         1           2349 (0)          0
5         1           2349 (0)          0
6         1           2349 (0)          0
7         1           2349 (0)          0
8         1           2349 (0)          0
9         1           2349 (0)          0
10        1           2349 (0)          0
11        1           2349 (0)          1  (current)
12        1           2349 (0)          0
13        1           2349 (0)          0
14        1           2349 (0)          0
15        1           2349 (0)          0
16        1           2349 (0)          0
17        1           2349 (0)          0
18        1           2349 (0)          0
19        1           2349 (0)          0
20        1           2349 (0)          0
21        1           2349 (0)          0
22        1           2349 (0)          0
23        1           2349 (0)          0
24        1           2349 (0)          0
25        1           2349 (0)          0
26        1           2349 (0)          0
27        1           2349 (0)          0
28        1           2349 (2349)       0
29        1           2349 (2349)       0
30        1           2349 (0)          0
```

`lotus-miner proving check --slow 28` shows everything as "good"

There is something _seriously_ wrong here!

Happens with and without a wdpost worker.

### Logging Information

```text
-
```

### Repo Steps

1. Run 1.15.2-rc1

**Comment by rjan90** [comment]
Hey @RobQuistNL!

Thanks for the ticket. But can you provide some more logs around/before the wdPoSt? And clarify a bit more about the events before/after here? That said, I have only seen that error-log type before when there have been some issues with the storage-paths to the long-term storage. 

With regards to this:
> ```
> This speaks for itself;
> $ lotus-miner proving compute window-post 28
> Took 6.047981ms
> ```

That is a known issue with the `proving compute window-post` command when that partition already has failed. Currently being tracked here: https://github.com/filecoin-project/lotus/issues/8435

**Comment by Reiers** [comment]
Closing due to duplicate https://github.com/filecoin-project/lotus/issues/8435

**Comment by rjan90** [comment]
The underlying wdPoSt-failure is not a duplicate of any current issue afaik. But we would need some further information/logs to understand why it failed to get a better understanding if it´s actually an issue or not.

I suspect that there is either some network-failure/storage-paths (seen the above error-message in those situations), or some issue sending the recovery declaration message (based on Slack-history). But Rob can probably provide some more context around what was actually happening.

**Comment by RobQuistNL** [comment]
Okay, yea that issue then is related, but I have no idea why these 2 partitions failed to begin with.
