### ISSUE TITLE
(SnapDeals) ParallelFetchLimit is not honour with `FinalizeReplicaUpdate`

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/lotus#8571]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.15.2-rc1+mainnet+git.dcf6f6414+api1.5.0
Local: lotus version 1.15.2-rc1+mainnet+git.dcf6f6414
```

### Describe the Bug

Because of issue https://github.com/filecoin-project/lotus/issues/8496 - after the deadline closes, the scheduler get flooded with GET tasks `FinalizeReplicaUpdate` - and this become a problem for next deadline when the ParallelFetchLimit is not honoured. 

```
[Storage]
  # type: int
  # env var: LOTUS_STORAGE_PARALLELFETCHLIMIT
  ParallelFetchLimit = 5
```

FinalizeReplicaUpdate: 19

**Note:** that for every other task(AP->PC1-PC2-C2) I can see that the throttle work as expected - its just snap related tasks.

### Logging Information

```text
e89d2e03  6553    7f042786  plato-amd-worker     PR2   running      43m49s
50615473  6283    baae41fb  filecoin-amd-sp      GET   running      19m30.8s
3ecf3ac1  6429    baae41fb  filecoin-amd-sp      GET   running      19m1.1s
11b966da  6541    646dc436  edith-intel-worker   PR2   running      18m12.7s
df48ee8d  6457    baae41fb  filecoin-amd-sp      GET   running      17m24s
05283343  6622    baae41fb  filecoin-amd-sp      GET   running      17m24s
34299444  6317    baae41fb  filecoin-amd-sp      GET   running      12m46.2s
05a2c381  6255    baae41fb  filecoin-amd-sp      GET   running      12m46.2s
a6a3ec6b  6583    baae41fb  filecoin-amd-sp      GET   running      12m46.2s
78e3d17b  6504    baae41fb  filecoin-amd-sp      GET   running      12m46.2s
30a0f35f  6288    baae41fb  filecoin-amd-sp      GET   running      12m46.2s
009dfda7  6459    baae41fb  filecoin-amd-sp      GET   running      12m46.2s
477e4798  6281    baae41fb  filecoin-amd-sp      GET   running      12m46.2s
488fd3ed  6393    baae41fb  filecoin-amd-sp      GET   running      12m46.2s
0693e68f  6513    baae41fb  filecoin-amd-sp      GET   running      12m46.2s
75186a54  6665    baae41fb  filecoin-amd-sp      GET   running      12m46.2s
e6a5ff01  6562    5215877a  reiers-PL-tests      PR2   running      11m50.6s
47639875  6569    baae41fb  filecoin-amd-sp      GET   running      11m12.4s
d7d037c3  6252    baae41fb  filecoin-amd-sp      GET   running      11m12.4s
3abb6a23  6627    baae41fb  filecoin-amd-sp      GET   running      11m12.4s
99172756  6260    baae41fb  filecoin-amd-sp      GET   running      11m12.4s
f51f6cb5  6494    0cd9bb1d  veronica-amd-worker  GET   running      11m12.4s
2e7bd666  6419    6732f412  helen-intel-worker   PR2   running      6m43.4s
b0e7476c  6381    047a1111  karen-intel-worker   RU    running      5m8.5s
4d6cf162  6540    047a1111  karen-intel-worker   GET   running      5m4.2s
9c455b8f  6271    837a2d19  ultron-epyc-worker   AP    running      5m4.2s
d456dbcc  6641    7b4f7e53  vision-epyc-worker   AP    running      5m4.2s
```

### Repo Steps

1. snap-up a lot of sectors in certain deadline
2. Wait until that deadline closes - because sector upgrades cant happen during wdPost.
See: https://github.com/filecoin-project/lotus/issues/8496
3. A lot GET spawns because now they can be sent since the deadline is closed.

**Comment by scaseye** [comment]
the RU workers are not honoring the parallel fetch limit either...

**Comment by scaseye** [comment]
4 RU workers running but every time all sectors get sent to same worker!

```
ID        Sector  Worker    Hostname           Task  State    Time
ddfb1bbf  1548    c88a45a2  homemate-server00  GET   running  5m54.6s
578bf9d9  1547    c88a45a2  homemate-server00  GET   running  5m36.1s
0a10cebb  1545    c88a45a2  homemate-server00  GET   running  3m38.4s
619643f3  1546    c88a45a2  homemate-server00  GET   running  3m29.8s
340a01de  1550    c88a45a2  homemate-server00  RU    running  2m5.2s
06f09c63  1549    c88a45a2  homemate-server00  RU    running  39.6s

```

parrallel fetch limit is set to 1.

**Comment by scaseye** [comment]
version 1.15.3 some improvement on RU worker scheduling...

I publish batches of 6 deals.   1.15.2 all 6 would be assigned to 1 RU worker....  

example:

- worker-RU.1 -> 6 sectors
- worker-RU.2 -> 0 sectors
- worker-RU.3 -> 0 sectors
- worker-RU.4 -> 0 sectors

in 1.15.3 now 3 go to the first RU worker, 3 go to 2nd RU worker, 3rd and 4th RU workers sit idle.

- worker-RU.1 -> 3 sectors
- worker-RU.2 -> 3 sectors
- worker-RU.3 -> 0 sectors
- worker-RU.4 -> 0 sectors

The scheduling window seems shorter, as i have had instants where 1st RU worker gets 4th sector.  meaning 3 went to 1st RU worker, 3 went to 2nd RU worker then i publish 2 deals and they end up on 1st RU worker again for a total of 5 on 1st RU worker.

- worker-RU.1 -> 3 sectors, after 2nd publish, 5 sectors
- worker-RU.2 -> 3 sectors
- worker-RU.3 -> 0 sectors
- worker-RU.4 -> 0 sectors

**Comment by scaseye** [comment]
@jennijuju why can lotus not utilize all RU workers??

**Comment by scaseye** [comment]
https://github.com/filecoin-project/lotus/issues/8676 has details on my setup

**Comment by donkabat** [comment]
`lotus-miner version 1.17.0+mainnet+git.2830429ad`
```
[Storage]
  ParallelFetchLimit = 2
```
GET to long- time storage, just CC sectors:
```
ID        Sector  Worker    Hostname  Task  State    Time
11cd018f  37867   526be472  fil-0     GET   running  26m22.4s
bd7de2b2  37866   526be472  fil-0     GET   running  26m3.4s
053bb165  37859   526be472  fil-0     GET   running  26m0.3s
84b56315  37861   526be472  fil-0     GET   running  25m53.1s
50313c1e  37851   526be472  fil-0     GET   running  25m53.1s
122dc80d  37845   526be472  fil-0     GET   running  25m53.1s
844f47e9  37846   526be472  fil-0     GET   running  25m53.1s
984debb1  37849   526be472  fil-0     GET   running  25m53.1s
0ac428e2  37856   526be472  fil-0     GET   running  25m53.1s
03f96e23  37858   526be472  fil-0     GET   running  25m53.1s
a7cdb921  37860   526be472  fil-0     GET   running  25m53.1s
a6aaf032  37853   526be472  fil-0     GET   running  25m53.1s
d01a631a  37874   526be472  fil-0     GET   running  25m34.1s
ea4c0ad5  37855   526be472  fil-0     GET   running  25m34.1s
c80c09e5  37857   526be472  fil-0     GET   running  25m34.1s
2e1dc9d2  37862   526be472  fil-0     GET   running  25m34.1s
957d6504  37854   526be472  fil-0     GET   running  25m34.1s
8dd5d618  37863   526be472  fil-0     GET   running  25m34.1s
d783cc1a  37865   526be472  fil-0     GET   running  25m34.1s
1ffbc697  37864   526be472  fil-0     GET   running  25m34.1s
4dcb380a  37875   526be472  fil-0     GET   running  25m34.1s
400efc95  37840   526be472  fil-0     GET   running  25m34.1s
07a74a2d  37847   526be472  fil-0     GET   running  25m34.1s
f911a72a  37848   526be472  fil-0     GET   running  25m34.1s
a2884f38  37841   526be472  fil-0     GET   running  25m34.1s
e5b8d075  37843   526be472  fil-0     GET   running  25m34.1s
0bd289fc  37850   526be472  fil-0     GET   running  25m34.1s
3456725a  37844   526be472  fil-0     GET   running  25m34.1s
93e83720  37852   526be472  fil-0     GET   running  25m34.1s
630549d8  37870   526be472  fil-0     GET   running  25m34.1s
631cab7d  37868   526be472  fil-0     GET   running  25m34.1s
dda2c44f  37869   526be472  fil-0     GET   running  25m34.1s
275b0288  37871   526be472  fil-0     GET   running  25m34.1s
fdf8ed04  37872   526be472  fil-0     GET   running  25m34.1s

```

**Comment by donkabat** [comment]
but it's only display problem, in the background only 2 sectors are fetching.

**Comment by Reiers** [comment]
Might be fixed by: https://github.com/filecoin-project/lotus/pull/9598
Closing for now.
