### ISSUE TITLE
lotus client retrieve doesn't cancel request when process is killed

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#8572]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.15.1
```

### Describe the Bug

When starting a retrieval, sometimes the retrieval is stuck on `Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 3ms` forever.

After 10 minutes, I kill the process.

This transfer can still be open though, and suddenly start downloading stuff after 20 minutes.

If I kill the request, I'd expect the retrieval to also be cancelled.

### Logging Information

```text
-
```

### Repo Steps

1. Run `lotus client retrieve`
2. Close the process
3. See that the transfer continues

**Comment by RobQuistNL** [comment]
Related: https://github.com/filecoin-project/lotus/issues/8573 (this would allow me to work around this issue)

**Comment by TippyFlitsUK** [comment]
Hi @RobQuistNL 

Can you please clarify how you are cancelling the retrieval?

Are you using the `lotus client cancel-retrieval` command?

Many thanks!

**Comment by RobQuistNL** [comment]
I cancel the process.

That does not cancel the retrieval. I can not run the `lotus client cancel-retrieval` because I do not know the ID

**Comment by TippyFlitsUK** [comment]
Thanks Rob

I will close this ticket as the functionality to cancel the retrieval actually already exists. I understand that the usability of this command is highly dependent on https://github.com/filecoin-project/lotus/issues/8573 and will continue to actively monitor that ticket.

Many thanks!

**Comment by RobQuistNL** [comment]
I wouldn't close it :/

If I cancel the process that does the retrieval, I don't want it to continue downloading behind my back.

Maybe a flag like `--background` would be nice for this functionality, but if I start a downloading process, and I cancel it, I want the download to stop..

**Comment by TippyFlitsUK** [comment]
You will need to use the `lotus client cancel-retrieval` command Rob rather than killing it. 

Hopefully the resolution of https://github.com/filecoin-project/lotus/issues/8573 will make that easier.

**Comment by RobQuistNL** [comment]
@LexLuthr

**Comment by RobQuistNL** [comment]
Can this be reopened? I still think this is a valid feature request.

**Comment by TippyFlitsUK** [comment]
Hey @RobQuistNL 
There are many scenarios where an SP would want the retrievals to continue after a process restart.

**Comment by RobQuistNL** [comment]
This is why I mentioned the `--background` flag. 

In the case of a user downloading a file (and the retrieval hangs, as often happens) they hit CTRL+C.
In the case of an automated system doing the same - it would keep the thread open. As a developer I would assume the download request ends when I hit CTRL+C. (wget / curl / aria2c)
If someone would really want it to continue in the background - then we have a flag for it. I really don't see why they would want that because nothing reports back that it finished and they can't efficiently find the status of it.
