### ISSUE TITLE
linux buff/cache is too height

### ISSUE THREAD

**Issue by dalingng** [filecoin-project/lotus#8599]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner version 1.15.3-dev+mainnet+git.88f8c7d16.dirty
lotus-worker version 1.15.3-dev+mainnet+git.88f8c7d16.dirty
```

### Describe the Bug

Somehow cached usage is ridiculously high, not so with 1.15.1

### Logging Information

```text
`root@node-0001:~# free -h
              total        used        free      shared  buff/cache   available
Mem:          188Gi       6.3Gi        35Gi        15Mi       146Gi       180Gi
Swap:            0B          0B          0B
root@node-0001:~# cat /proc/meminfo
MemTotal:       197732140 kB
MemFree:        37560956 kB
MemAvailable:   189401036 kB
Buffers:          227336 kB
Cached:         152900732 kB
SwapCached:            0 kB
Active:         128100984 kB
Inactive:       30773164 kB
Active(anon):       1568 kB
Inactive(anon):  5760936 kB
Active(file):   128099416 kB
Inactive(file): 25012228 kB
Unevictable:           4 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                52 kB
Writeback:             0 kB
AnonPages:       5708256 kB
Mapped:         10592772 kB
Shmem:             16344 kB
KReclaimable:     467544 kB
Slab:             698608 kB
SReclaimable:     467544 kB
SUnreclaim:       231064 kB
KernelStack:       15248 kB
PageTables:       153640 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    98866068 kB
Committed_AS:    9058352 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      205068 kB
VmallocChunk:          0 kB
Percpu:            40448 kB
HardwareCorrupted:     0 kB
AnonHugePages:    296960 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      930316 kB
DirectMap2M:    81768448 kB
DirectMap1G:    119537664 kB`
```

### Repo Steps

lotus-miner run
lotus-worker run

**Comment by Kubuxu** [comment]
Cached usage is a non-issue. Linux will handle it and free cache as other usages of memory require it.
The system has 180GiB of memory available whenever it is needed.
See https://www.linuxatemyram.com/ for more details.
