### ISSUE TITLE
Sealing limit count is wrong for snap deal sectors

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#8602]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.15.1
```

### Describe the Bug

If you set a sealing limit in the config you can not pledge even if your machines are not working at all.

The count of "sealing" is wrong - sectors in `SnapDealsWaitDeals` or `Available` seem to be counted towards "active" sealing.

### Logging Information

```text
master@daemon:~$ lotus-miner sealing jobs
ID        Sector  Worker    Hostname   Task  State    Time
7600b749  163130  9ee5ca7e  c7-pc2-6   PR2   running  37m37.7s
344bb4da  163132  7076a257  c7-pc2-4   PR2   running  34m47.9s
43dae42e  163133  7e6eb530  c7-pc2-0   PR2   running  27m47.4s
e958f636  163136  0407acc6  c7-c2-9    PR2   running  14m53.2s
7bcfb94c  163135  816583a3  c1-pc2-2   PR2   running  14m9.9s
dcfde61b  163134  65bfe011  c7-pc2-8   PR2   running  12m8.6s
f15daf4d  163137  49006483  c7-pc2-2   PR2   running  7m50.6s
8b376e9f  163139  4147201e  c1-pc2-0   RU    running  4m30.1s
31aa75ea  163131  3c6d0fd9  c8-pc2-4   GET   running  2m34.4s
b38e7ddc  163138  eecc4e40  c7-pc2-12  PR2   running  53s

master@daemon:~$ lotus-miner sectors pledge
ERROR: too many sectors sealing (curSealing: 901, max: 800)
```
```


### Repo Steps

- Set sealing limit
- Use snap deals
- Run lotus-miner sectors pledge

**Comment by rjan90** [comment]
Hey @RobQuistNL!

This is a know thing on v1.15.1, and should have been fixed on the upcoming v1.15.2.

Duplicated and fixed/closed issue here https://github.com/filecoin-project/lotus/issues/8498. Will track and reopen if we still see this on v1.15.2
