### ISSUE TITLE
rust log time format problem

### ISSUE THREAD

**Issue by rickiey** [filecoin-project/lotus#8603]
![image](https://user-images.githubusercontent.com/34705031/166852594-d73d96c7-e1d9-4cb8-9d75-b5fcc4a8dfa0.png)

**Comment by rjan90** [comment]
Hey @rickiey!

Thanks for the report! This issue has been fixed in the v1.15.2-rc2/3 release, https://github.com/filecoin-project/lotus/issues/8504

Closing this issue now! Thanks again for the report!
