### ISSUE TITLE
A fully windowpost process should work on a single windowpost worker

### ISSUE THREAD

**Issue by huhuapop** [filecoin-project/lotus#8608]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.15.2-rc1-mainnet+git.1117b44bb
lotus-miner version 1.15.2-rc1-mainnet+git.1117b44bb
```

### Describe the Bug

I have a miner server and a windowpost worker. Both of them could access remote storage servers. But I find the generate_single_vanilla_proof and challenges is working on miner, not windowpost worker.
After the challenges are generated, the windowpost worker will continue work on the partial_tree.
I think the fully windowpost process should work on a single windowpost worker

### Logging Information

```text
miner: %Y-%m-%dT%H:%M:%S%.3f INFO filcrypto::proofs::api > generate_single_vanilla_proof: start
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:start: SectorId(3988)
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:start: SectorId(3987)
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:start: SectorId(3989)
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:start: SectorId(3991)
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:start: SectorId(3994)
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:start: SectorId(3992)
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:start: SectorId(3990)
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:start: SectorId(3993)
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:finish: SectorId(3787)
%Y-%m-%dT%H:%M:%S%.3f INFO filcrypto::proofs::api > generate_single_vanilla_proof: finish
%Y-%m-%dT%H:%M:%S%.3f INFO filcrypto::proofs::api > generate_fallback_sector_challenges: start
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_sector_challenges:start
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_sector_challenges:finish

windowpost worker:
%Y-%m-%dT%H:%M:%S%.3f DEBUG merkletree::merkle > generated partial_tree of row_count 4 and len 585 with 8 branches for proof at 27309828
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:finish: SectorId(26166)
%Y-%m-%dT%H:%M:%S%.3f INFO filcrypto::proofs::api > generate_single_vanilla_proof: finish
%Y-%m-%dT%H:%M:%S%.3f DEBUG merkletree::merkle > generated partial_tree of row_count 4 and len 585 with 8 branches for proof at 25264019
%Y-%m-%dT%H:%M:%S%.3f DEBUG merkletree::merkle > generated partial_tree of row_count 4 and len 585 with 8 branches for proof at 39860496
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:finish: SectorId(21649)
%Y-%m-%dT%H:%M:%S%.3f INFO filcrypto::proofs::api > generate_single_vanilla_proof: finish
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:finish: SectorId(22242)
%Y-%m-%dT%H:%M:%S%.3f INFO filcrypto::proofs::api > generate_single_vanilla_proof: finish
%Y-%m-%dT%H:%M:%S%.3f DEBUG merkletree::merkle > generated partial_tree of row_count 4 and len 585 with 8 branches for proof at 131774310
%Y-%m-%dT%H:%M:%S%.3f INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:finish: SectorId(21969)
%Y-%m-%dT%H:%M:%S%.3f INFO filcrypto::proofs::api > generate_single_vanilla_proof: finish
%Y-%m-%dT%H:%M:%S%.3f INFO filcrypto::proofs::api > generate_single_window_post_with_vanilla: start
```

### Repo Steps

1. Run 'lotus-miner proving compute window-post 0'

**Comment by rjan90** [comment]
In the v1.17.0 release you now have an option to fully disable windowPoSt-tasks on the `lotus-miner`. https://lotus.filecoin.io/storage-providers/advanced-configurations/workers/#post-computations.

Note that this setting will be respected even if there are no connected window PoSt workers. Before enabling this option please ensure that your PoSt workers are correctly configured and available.

Thanks for the issue ticket!
