### ISSUE TITLE
The time zone of the log is changed from East 8 to UTC when starting wdpost

### ISSUE THREAD

**Issue by bruce20319** [filecoin-project/lotus#8615]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner version 1.15.1 git.731da455d.dirty
```

### Describe the Bug

The time zone of the log is changed from East 8 to UTC when starting wdpost

### Logging Information

```text
May 06 16:13:21 mXJHY lotus-miner[10765]: 2022-05-06T16:13:21.935+0800        INFO        storageminer        storage/wdpost_sched.go:118        restarting window post scheduler
May 06 16:13:22 mXJHY lotus-miner[10765]: 2022-05-06T08:13:22.719 INFO bellperson::groth16::prover > Bellperson 0.18.0 is being used!
May 06 16:13:22 mXJHY lotus-miner[10765]: 2022-05-06T08:13:22.882 INFO bellperson::groth16::prover > synthesis time: 163.131384ms
May 06 16:13:22 mXJHY lotus-miner[10765]: 2022-05-06T08:13:22.882 INFO bellperson::groth16::prover > starting proof timer
May 06 16:13:22 mXJHY lotus-miner[10765]: 2022-05-06T08:13:22.899 INFO bellperson::gpu::locks > GPU is available for FFT!
```

### Repo Steps

just check 
journalctl --since="2h ago" -fu lotus-miner|egrep "wdpost|bell"

**Comment by Reiers** [comment]
Hi @bruce20319 

Thanks for the report. This is fixed in the latest release.
Please upgrade Lotus to v1.15.2

*Link to latest tags [[here.](https://github.com/filecoin-project/lotus/tags)](https://github.com/filecoin-project/lotus/tags)*

Closing ticket.

If you are still experiencing problems - please open a new ticket or ask for help in our [[Discussions forum.](https://github.com/filecoin-project/lotus/discussions)](https://github.com/filecoin-project/lotus/discussions)
