### ISSUE TITLE
The time zone of the log is changed from East 8 to UTC when starting wdpost

### ISSUE THREAD

**Issue by bruce20319** [filecoin-project/lotus#8618]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner version 1.15.2+mainnet+git.518dc962e.dirty
```

### Describe the Bug

The time zone of the log is changed from East 8 to UTC when starting wdpost

### Logging Information

```text
May 07 15:30:52 mXJHY lotus-miner[13876]: 2022-05-07T15:30:52.369+0800        DEBUG        advmgr        sector-storage/sched.go:457        SCHED windows: [{allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:0 cpuUse:0 cond:<nil> waiting:0} todo:[]} {allocated:{memUsedMin:0 memUsedMax:0 gpuUsed:0 cpuUse:0 cond:<nil> waiting:0} todo:[]}]
May 07 15:30:52 mXJHY lotus-miner[13876]: 2022-05-07T15:30:52.370+0800        DEBUG        advmgr        sector-storage/sched.go:458        SCHED Acceptable win: [[] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] []]
May 07 15:30:52 mXJHY lotus-miner[13876]: 2022-05-07T07:30:52.778 INFO storage_proofs_core::compound_proof > vanilla_proofs:finish
May 07 15:30:52 mXJHY lotus-miner[13876]: 2022-05-07T07:30:52.783 INFO storage_proofs_core::compound_proof > snark_proof:start
May 07 15:30:52 mXJHY lotus-miner[13876]: 2022-05-07T07:30:52.784 INFO bellperson::groth16::prover > Bellperson 0.18.0 is being used!
May 07 15:30:52 mXJHY lotus-miner[13876]: 2022-05-07T07:30:52.941 INFO bellperson::groth16::prover > synthesis time: 156.965424ms
May 07 15:30:52 mXJHY lotus-miner[13876]: 2022-05-07T07:30:52.941 INFO bellperson::groth16::prover > starting proof timer
May 07 15:30:52 mXJHY lotus-miner[13876]: 2022-05-07T07:30:52.961 INFO bellperson::gpu::locks > GPU is available for FFT!
```

### Repo Steps

just check syslog

**Comment by rjan90** [comment]
Answer from `vmx` in the rust-fil-logger issue:
```
This issue occurs in multithreaded programs, and Lotus is multithreaded. Lotus would need to initialize the logger while it's still single threaded (I don't know if that's possible in Go). Then you would get the local time.

If you compile from source, you can try setting RUSTFLAGS="--cfg unsound_local_offset", though be aware that it [might lead to unexpected segmentation faults](https://docs.rs/time/0.3.5/time/#feature-flags).
```

**Comment by johnnymatthews** [comment]
I'm getting the same error, but for some reason that `unsound_local_offset` flag doesn't seem to be fixing the problem. I'm trying `use_chrono_for_offset` instead ([seen here](https://github.com/emabee/flexi_logger#use_chrono_for_offset)).

**Comment by rjan90** [comment]
Hey! To my knowledge the error seems to have been fixed in the chrono-dependecy. So we will just have to wait until they release a new version, and for that version to bubble up into rust-fil-logger and then Lotus!

**Comment by rjan90** [comment]
Closing this issue now since the chrono fixes has made their way into Lotus dependecies, and the timezone for the RUST_LOGs now are in your local time.

Tested by changing the timezone to NY time:

```
root@Ubuntu-2004-focal-amd64-base ~ # timedatectl
               Local time: Sun 2023-03-05 06:17:20 EST  
           Universal time: Sun 2023-03-05 11:17:20 UTC  
                 RTC time: Sun 2023-03-05 11:17:20      
                Time zone: America/New_York (EST, -0500)
System clock synchronized: yes                          
              NTP service: active                       
          RTC in local TZ: no                           
```

And running a `lotus-miner proving compute window-post` to get RUST_LOGs:

```
2023-03-05T06:14:02.176-0500    INFO    wdpost  wdpost/wdpost_run.go:260        starting PoSt cycle     {"cycle": "2023-03-05T06:14:02.176-0500", "manual": true, "ts": "[bafy2bzacec3h3tqh4xcp7z2gx4tcm6u26ohl4hwxo7wuvw5hycvbdrqw6grqo]", "deadline": 2}
2023-03-05T06:14:02.178 INFO filcrypto::util::types > generate_fallback_sector_challenges: start
2023-03-05T06:14:02.178 INFO filecoin_proofs::api::post_util > generate_sector_challenges:start
2023-03-05T06:14:02.178 INFO filecoin_proofs::api::post_util > generate_sector_challenges:finish
2023-03-05T06:14:02.178 INFO filcrypto::util::types > generate_fallback_sector_challenges: end
2023-03-05T06:14:02.178 INFO filcrypto::util::types > generate_single_vanilla_proof: start
2023-03-05T06:14:02.178 INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:start: SectorId(33)
2023-03-05T06:14:02.197 INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:finish: SectorId(33)
2023-03-05T06:14:02.198 INFO filcrypto::util::types > generate_single_vanilla_proof: end
```

The logs are now consistent with the local time.
