### ISSUE TITLE
lotus-shed terminate sectors fails with Multisig Owner

### ISSUE THREAD

**Issue by marshyonline** [filecoin-project/lotus#8664]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus-shed version 1.15.3-rc1
```

### Describe the Bug

When a miner is using a MultiSig Owner - The `lotus-shed terminate sectors` command will fail with

```/lotus# ./lotus-shed sectors terminate --really-do-it 79563
2022-05-17T18:37:03.800+1000    WARN    lotus-shed      lotus-shed/main.go:106  mpool push message:
    main.glob..func92
        /root/workspace/lotus/cmd/lotus-shed/sectors.go:150
  - getting key address: failed to get account actor state for f01687229: unknown actor code bafkqadtgnfwc6nzpnv2wy5djonuwo
```

Changing the following allows the message to goto chain via the worker address -https://github.com/filecoin-project/lotus/blob/33a05d33a9a00925219b7aeffd3d98e31fdd128b/cmd/lotus-shed/sectors.go#L142

To: 
`From:   mi.Worker,`
 Allowed the message to goto chain and the sectors to terminate

### Logging Information

```text
~/workspace/lotus# ./lotus-shed sectors terminate --really-do-it 79563
2022-05-17T18:37:03.800+1000    WARN    lotus-shed      lotus-shed/main.go:106  mpool push message:
    main.glob..func92
        /root/workspace/lotus/cmd/lotus-shed/sectors.go:150
  - getting key address: failed to get account actor state for f01687229: unknown actor code bafkqadtgnfwc6nzpnv2
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by geoff-vball** [comment]
@marshyonline All of the commands meant for miners will fail if trying to send with the multisig address. Multisig messages must be send with msig 'propose' and 'approve' messages. You can see the cli command to the `propose` command [here](https://github.com/filecoin-project/lotus/blob/29fff4fb0626362ee10dae9bd3c33ec8cd66694c/cli/multisig.go#L357).

There are some shortcut commands for miner multisigs [here](https://github.com/filecoin-project/lotus/blob/master/cmd/lotus-shed/miner-multisig.go). We are hoping to add more functionality here later.

Can can limit your worker's access to terminate as well as other functionality with actor controls [here](https://github.com/filecoin-project/lotus/blob/29fff4fb0626362ee10dae9bd3c33ec8cd66694c/cmd/lotus-miner/actor.go#L591).

cc @rjan90 @TippyFlitsUK @Reiers

**Comment by marshyonline** [comment]
Hi 
In my case, I don't have access to the MultiSig - it's held by our lender..
This means without making this change, I can't terminate sectors with shed.

**Comment by geoff-vball** [comment]
@marshyonline I understand your issue now. There's a [PR here](https://github.com/filecoin-project/lotus/pull/9285) that you can track that will solve your issue.
