### ISSUE TITLE
Sever remaining v8 actors dependencies

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8674]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

Currently Lotus has almost entirely removed references to v8 specs-actors (see #8534). There is one unfortunate dependence on v8 specs-actors for `ActorNameByCode`, which is used when setting up the registry. This is only needed for being able to decode params and return types based on actor code id and method numbers.

We can either:

- architect around the synthetic CIDs in the registry, so that we can avoid this entirely
- keep the current workaround in place, but move the actors exports to go-state-types.

**Comment by jennijuju** [comment]
can this be closed?

**Comment by arajasek** [comment]
Since done
