### ISSUE TITLE
6+ sectors all running at same time on 1 RU worker

### ISSUE THREAD

**Issue by scaseye** [filecoin-project/lotus#8676]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.15.2+mainnet+git.518dc962e
```

### Describe the Bug

All sectors get assigned to 1 RU worker, and they all run at same time...

No matter how many sectors are sent, they all go to the **same RU worker every time,  _and they all run in parallel_**...
<img width="677" alt="image" src="https://user-images.githubusercontent.com/69066370/169079609-49003220-6c63-436c-9929-6cfe8dad5d0a.png">

### 4x RU workers running and available
```
ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:15001 --addpiece=false --precommit1=false --unseal=false --precommit2=true --commit=false --replica-update=true --prove-replica-update2=false --regen-sector-key=true --parallel-fetch-limit=1
ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:15002 --addpiece=false --precommit1=false --unseal=false --precommit2=true --commit=false --replica-update=true --prove-replica-update2=false --regen-sector-key=true --parallel-fetch-limit=1
ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:15003 --addpiece=false --precommit1=false --unseal=false --precommit2=true --commit=false --replica-update=true --prove-replica-update2=false --regen-sector-key=true --parallel-fetch-limit=1
ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:15004 --addpiece=false --precommit1=false --unseal=false --precommit2=true --commit=false --replica-update=true --prove-replica-update2=false --regen-sector-key=true --parallel-fetch-limit=1
```
### 4x PR2 workers running and available
```
ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:16001 --addpiece=false --precommit1=false --unseal=false --precommit2=false --commit=true --replica-update=false --prove-replica-update2=true --regen-sector-key=true --parallel-fetch-limit=1
ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:16002 --addpiece=false --precommit1=false --unseal=false --precommit2=false --commit=true --replica-update=false --prove-replica-update2=true --regen-sector-key=true --parallel-fetch-limit=1
ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:16003--addpiece=false --precommit1=false --unseal=false --precommit2=false --commit=true --replica-update=false --prove-replica-update2=true --regen-sector-key=true --parallel-fetch-limit=1
ExecStart=/usr/local/bin/lotus-worker run --listen 0.0.0.0:16004 --addpiece=false --precommit1=false --unseal=false --precommit2=false --commit=true --replica-update=false --prove-replica-update2=true --regen-sector-key=true --parallel-fetch-limit=1
```

Video Showing Exactly everything that happens. (you can watch in 4x speed)

- 12 sectors get published
- all 12 one by one get assigned to worker c88a45a2 (there are 3 idle RU workers the entire time)
- 6+ sectors all running in RU state at same time
- none are ever in prepared state, they all just run as they make it to the worker.
- once they get pasted RU, they then get distributed as expected to the PRU2 workers. 

https://youtu.be/ltKSCIpRWX0

### Logging Information

```text
got lucky this time, all completed without error.  this has caused SEG faults in the past.
```

### Repo Steps

setup 2+ RU workers on a remote machine.
snap enough verified deals to fill 12 sectors. 
they all get assigned to 1 RU worker. 
they all run at same time.

**Comment by TippyFlitsUK** [comment]
Hi Casey

Thanks for the detailed report - There are multiple issues already open with regards to this. https://github.com/filecoin-project/lotus/issues/8655

I will close this ticket and reference this ticket to the other one so your logs are fully available.

Thanks again!

**Comment by scaseye** [comment]
Expected Behaviour from above Example:

Publish Batch of 6:

worker-RU.1 -> 1 sector running
worker-RU.2 -> 1 sector running
worker-RU.3 -> 1 sector running
worker-RU.4 -> 1 sector running
worker-RU.1 -> 1 sector Prepared
worker-RU.2 -> 1 sector Prepared
