### ISSUE TITLE
Make builds with NetworkBundle set do not have git version

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#8684]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus version 1.16.0-dev+interopnet

:=P
```

### Describe the Bug

When running `make <network>` the resulting binaries do not have commit information.

This is due to setting the `ldflags` multiple times.

```
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.d39b9a8d8" -tags=interopnet -ldflags=-X=github.com/filecoin-project/lotus/build.NetworkBundle=interopnet -o lotus ./cmd/lotus
```

Due to the ordering of the `ldflags`, this either will set the `NetworkBundle` build var or the `CurrentCommit` build var, but never both.

On the network reset / update side (calibration, butterfly, interop) the `ldflags` are reversed. This resulted in the `CurrentCommit` being set correctly, but the `NetworkBundle` was not set, and mainnet builtin actors would be downloaded.

### Logging Information

```text
$ make interopnet
rm -f lotus
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.d39b9a8d8" -tags=interopnet -ldflags=-X=github.com/filecoin-project/lotus/build.NetworkBundle=interopnet -o lotus ./cmd/lotus
rm -f lotus-miner
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.d39b9a8d8" -tags=interopnet -ldflags=-X=github.com/filecoin-project/lotus/build.NetworkBundle=interopnet -o lotus-miner ./cmd/lotus-miner
rm -f lotus-worker
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.d39b9a8d8" -tags=interopnet -ldflags=-X=github.com/filecoin-project/lotus/build.NetworkBundle=interopnet -o lotus-worker ./cmd/lotus-worker
dCaution: you have an existing lotus binary in your PATH. This may cause problems if you don't run 'sudo make install'
rm -f lotus-seed
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.d39b9a8d8" -tags=interopnet -ldflags=-X=github.com/filecoin-project/lotus/build.NetworkBundle=interopnet -o lotus-seed ./cmd/lotus-seed
rm -f lotus-shed
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.d39b9a8d8" -tags=interopnet -ldflags=-X=github.com/filecoin-project/lotus/build.NetworkBundle=interopnet -o lotus-shed ./cmd/lotus-shed
rm -f lotus-wallet
go build -o lotus-wallet ./cmd/lotus-wallet
drm -f lotus-gateway
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.d39b9a8d8" -tags=interopnet -ldflags=-X=github.com/filecoin-project/lotus/build.NetworkBundle=interopnet -o lotus-gateway ./cmd/lotus-gateway
rm -f lotus-fountain
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.d39b9a8d8" -tags=interopnet -ldflags=-X=github.com/filecoin-project/lotus/build.NetworkBundle=interopnet -o lotus-fountain ./cmd/lotus-fountain
go run github.com/GeertJohan/go.rice/rice append --exec lotus-fountain -i ./cmd/lotus-fountain -i ./build
no calls to rice.FindBox() or rice.MustFindBox() found in import path `github.com/filecoin-project/lotus/build`
rm -f lotus-stats
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.d39b9a8d8" -tags=interopnet -ldflags=-X=github.com/filecoin-project/lotus/build.NetworkBundle=interopnet -o lotus-stats ./cmd/lotus-stats
```

### Repo Steps
```
make interopnet
./lotus --version
```

**Comment by jennijuju** [comment]
closed by #8716
