### ISSUE TITLE
SectorSubmitReplicaUpdateFailed - %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by scaseye** [filecoin-project/lotus#8699]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner version 1.15.2+mainnet+git.518dc962e
```

### Describe the Bug

I have 2 snap verified deal sectors in this state. 

```
41.	2022-05-21 14:57:20 -0700 PDT:	[event;sealing.SectorSubmitReplicaUpdateFailed]	{"User":{}}
42.	2022-05-21 14:58:20 -0700 PDT:	[event;sealing.SectorAbortUpgrade]	{"User":{}}
	%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
43.	2022-05-21 14:58:20 -0700 PDT:	[event;sealing.SectorRevertUpgradeToProving]	{"User":{}}
```

```
2151  Proving                YES      NO      3382130 (in 1 year 24 weeks)  CC                                
2152  Proving                YES      NO      3382130 (in 1 year 24 weeks)  CC                
```

after the next deadline i was able to mark them for snap upgrade they now look like this, but i also still have 2 phantom storage deals showing in my miner info.

```
2151  Available           YES      YES     3382130 (in 1 year 24 weeks)  CC
2152  Available              YES      YES     3382130 (in 1 year 24 weeks)  CC 
```

`
[2152.txt](https://github.com/filecoin-project/lotus/files/8755058/2152.txt)
[rustlogs-attime.txt](https://github.com/filecoin-project/lotus/files/8755059/rustlogs-attime.txt)
[minerlog-14.58-time.txt](https://github.com/filecoin-project/lotus/files/8755060/minerlog-14.58-time.txt)
[2151.txt](https://github.com/filecoin-project/lotus/files/8755057/2151.txt)`

### Logging Information

```text
attached to ticket
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...
happened while snapping during deadline the sector was in.

**Comment by scaseye** [comment]
should i abort the snap, or try to put another snap deal in these sectors?

**Comment by TippyFlitsUK** [comment]
Hi Casey

As mentioned in DM's, I would suggest terminating these 2 problematic sectors as I think that recovery is unlikely at this point.

We need to get to the root of this panic though!! I can't seem to find it in the `rustlogs-attime.txt` that you kindly attached. Would you mind having another look and re-posting it here?

Many thanks!

**Comment by scaseye** [comment]
terminated.

**Comment by scaseye** [comment]
[minerlog.tar.gz](https://github.com/filecoin-project/lotus/files/8793615/minerlog.tar.gz)

**Comment by mtelka** [comment]
We hit this problem too for sector 747:

```
22.     2022-06-02 09:29:15 +0200 CEST: [event;sealing.SectorProveReplicaUpdate]        {"User":{"Proof":"***REDACTED***"}}
23.     2022-06-02 09:58:13 +0200 CEST: [event;sealing.SectorFinalized] {"User":{}}
24.     2022-06-02 09:58:13 +0200 CEST: [event;sealing.SectorSubmitReplicaUpdateFailed] {"User":{}}
25.     2022-06-02 09:59:13 +0200 CEST: [event;sealing.SectorRetrySubmitReplicaUpdate]  {"User":{}}
26.     2022-06-02 09:59:13 +0200 CEST: [event;sealing.SectorSubmitReplicaUpdateFailed] {"User":{}}
27.     2022-06-02 10:00:13 +0200 CEST: [event;sealing.SectorRetrySubmitReplicaUpdate]  {"User":{}}
28.     2022-06-02 10:00:13 +0200 CEST: [event;sealing.SectorSubmitReplicaUpdateFailed] {"User":{}}
29.     2022-06-02 10:01:13 +0200 CEST: [event;sealing.SectorRetrySubmitReplicaUpdate]  {"User":{}}
30.     2022-06-02 10:01:13 +0200 CEST: [event;sealing.SectorSubmitReplicaUpdateFailed] {"User":{}}
31.     2022-06-02 10:02:13 +0200 CEST: [event;sealing.SectorRetrySubmitReplicaUpdate]  {"User":{}}
32.     2022-06-02 10:02:13 +0200 CEST: [event;sealing.SectorSubmitReplicaUpdateFailed] {"User":{}}
33.     2022-06-02 10:03:13 +0200 CEST: [event;sealing.SectorAbortUpgrade]      {"User":{}}
        %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
34.     2022-06-02 10:03:13 +0200 CEST: [event;sealing.SectorRevertUpgradeToProving]    {"User":{}}
```

The sector was finalized during WdPoSt calculation (the SubmitWindowedPoSt message was added to blockchain on 10:02:00) and I see these related entries in the miner's log:

```
2022-06-02T09:32:01.379+0200    WARN    advmgr  sector-storage/faults.go:91     CheckProvable Sector FAULT: can't acquire read lock     {"sector": {"ID":{"Miner":838684,"Number":747},"ProofType":8}}
2022-06-02T09:58:13.427+0200    INFO    sectors storage-sealing/states_failed.go:28     ReplicaUpdateFailed(747), waiting 59.57238476s before retrying
2022-06-02T09:59:13.149+0200    INFO    sectors storage-sealing/states_failed.go:28     ReplicaUpdateFailed(747), waiting 59.851005174s before retrying
2022-06-02T10:00:13.156+0200    INFO    sectors storage-sealing/states_failed.go:28     ReplicaUpdateFailed(747), waiting 59.843071461s before retrying
2022-06-02T10:01:13.396+0200    INFO    sectors storage-sealing/states_failed.go:28     ReplicaUpdateFailed(747), waiting 59.603624831s before retrying
2022-06-02T10:02:13.061+0200    INFO    sectors storage-sealing/states_failed.go:28     ReplicaUpdateFailed(747), waiting 59.938154131s before retrying
2022-06-02T10:03:13.042+0200    ERROR   sectors storage-sealing/states_failed.go:247    sector marked for upgrade 747 no longer active, aborting upgrade
2022-06-02T10:03:13.044+0200    WARN    sectors storage-sealing/fsm.go:763      sector 747 got error event sealing.SectorAbortUpgrade: %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
```

**Comment by mtelka** [comment]
Daemon:  1.15.2+mainnet+git.518dc96.dirty+api1.5.0
Local: lotus-miner version 1.15.2+mainnet+git.518dc96.dirty

**Comment by Reiers** [comment]
Hi guys

Thanks for the report. The issue is starting to be outdated. 
Im unable to reproduce the issue here.

If you see this:
```
33.     2022-06-02 10:03:13 +0200 CEST: [event;sealing.SectorAbortUpgrade]      {"User":{}}
        %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
```
in current release [v1.16.1](https://github.com/filecoin-project/lotus/releases/tag/v1.16.1) - please open a new ticket.

Thank you !
