### ISSUE TITLE
lotus-shed: hello protocol dump

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#8711]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

I would like to be able to query remote peers for their hello protocol data.

https://github.com/filecoin-project/lotus/blob/518dc962ee52a31bce3eecb4f525d4ed91e029e5/node/hello/hello.go#L33-L38
https://github.com/filecoin-project/lotus/blob/v1.15.2/node/hello/hello.go#L33-L38

This will make it easier to probe remote peers and inspect their heaviest tipset, and find what genesis block they are using.

### Describe the solution you'd like

Add a command to `lotus-shed` accepts a multiaddr as an argument and a path to a genesis car file. The command should run the hello protocol against the remote peer, using the genesis data for itself, and then dumps the `HelloMessage` from the peer to stdout as formatted json (such that the output of the command can be used with `jq`.

To the remote peer this should look identical to a new node joining the network with no chain data synced.

This will require setting up a libp2p node, a random PeerID should be fine. Nothing should be written to disk.

**Comment by rjan90** [comment]
Hey! I´m closing this issue now since the desired feature has been implemented and merged 😄 Thanks @swift-mx for making this!
