### ISSUE TITLE
unknown import: `vm::context` has not been defined when MessagePool addLoaded message

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#8714]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.15.4-dev+mainnet
lotus version 1.15.4-dev+mainnet+git.df98a2a0
```

### Describe the Bug

export LOTUS_USE_FVM_EXPERIMENTAL=1
lotus daemon

### Logging Information

```text
2022-05-24T20:28:40.981+0800    INFO    vm      vm/fvm.go:260   using the FVM, this is experimental!
2022-05-24T20:28:40.996+0800    ERROR   messagepool     messagepool/messagepool.go:1552 adding local message: failed to look up actor state nonce: computing tipset state for GetActor: applying msg: [from=f3q6obs6p7z74whc7udg74xcmbzfgzozzgbvrm2zp5r57cajganmge36gybl5uao2jg4sp2hrfgzwh3h5mmefq, to=f030347, seq=1573468, m=6, h=1836285] fatal error

    Caused by:
        unknown import: `vm::context` has not been defined:
    github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).addLoaded
        /mnt/lotus/lotusbuild/20220524120705/marco/chain/messagepool/messagepool.go:920
  - validation failure
```

### Repo Steps

1 export LOTUS_USE_FVM_EXPERIMENTAL=1
2 lotus daemon

**Comment by TippyFlitsUK** [comment]
Hi @marco-storswift 

Thanks for the report. Looks like you are running the master branch of Lotus. It is not uncommon to see errors with the most recent master commits.

Please revert to the [latest stable version](https://github.com/filecoin-project/lotus/releases/tag/v1.15.2) and let us know if you continue to see this error.

Thank you !

**Comment by Stebalien** [comment]
This is because we haven't updated the FFI in lotus for a while, and the version of the FFI that lotus uses doesn't correctly lock these dependencies to the minor version.

Want me to update master?

**Comment by jennijuju** [comment]
@marco-storswift if you wanna test the upcoming  v1.16.0 - use `feat/nv16` branch
