### ISSUE TITLE
Lotus markets journal log fills up with useless events (ProviderEventBlockSent)

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#8730]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.15.2
```

### Describe the Bug

Probably also happens with the client when retrieving (receiving a block is also an event) so the journal file will be filled with small single lines about a block of data being transferred. Useless IMHO.

### Logging Information

```text
$ cat lotus-journal-2022-05-26T084149Z.ndjson | jq .Data.Event | grep ProviderEventBlockSent | wc -l
1106125
```

```
-rw-r--r-- 1 master master 1.1G May 25 06:17 lotus-journal-2022-05-25T061700Z.ndjson
-rw-r--r-- 1 master master 1.1G May 25 09:05 lotus-journal-2022-05-25T090546Z.ndjson
-rw-r--r-- 1 master master 1.1G May 25 12:30 lotus-journal-2022-05-25T123044Z.ndjson
-rw-r--r-- 1 master master 1.1G May 25 15:55 lotus-journal-2022-05-25T155520Z.ndjson
-rw-r--r-- 1 master master 1.1G May 25 18:09 lotus-journal-2022-05-25T180928Z.ndjson
-rw-r--r-- 1 master master 1.1G May 25 19:43 lotus-journal-2022-05-25T194316Z.ndjson
-rw-r--r-- 1 master master 1.1G May 25 22:51 lotus-journal-2022-05-25T225158Z.ndjson
-rw-r--r-- 1 master master 1.1G May 26 02:00 lotus-journal-2022-05-26T020002Z.ndjson
-rw-r--r-- 1 master master 1.1G May 26 04:38 lotus-journal-2022-05-26T043852Z.ndjson
-rw-r--r-- 1 master master 1.1G May 26 06:39 lotus-journal-2022-05-26T063930Z.ndjson
-rw-r--r-- 1 master master 1.1G May 26 08:41 lotus-journal-2022-05-26T084149Z.ndjson
```
```


### Repo Steps

1. Run Lotus

**Comment by rjan90** [comment]
Hey @RobQuistNL! Thanks for the ticket. I agree that having those event included as default in the journal is not needed anymore. I will investiagte if we can turn down the log-level on those events.

**Comment by RobQuistNL** [comment]
Log was already fixed; https://github.com/filecoin-project/lotus/pull/8622/files

**Comment by rjan90** [comment]
> I will investiagte if we can turn down the log-level on those events.
Yeah, sorry about the bad phrasing here. I meant that I will investigate if these events can be turned off in the journal

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and is being completely removed from the code here:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
