### ISSUE TITLE
Allow directory import in `lotus client import` as well as `lotus client generate-car`

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/lotus#8746]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

Currently, we can only import files in `lotus client import` and `lotus client generate-car` commands. The code doesn't seems to be using go-car but unixfs pathing and lower level ipld functionalities. 

Proposal:

1. To import a directory, calculate the size and make sure it is less than 64 GiB. Covert to car and then import. Conversion should happen outside the API to reduce the load on daemon.
2. The generate-car function can be implemented to use go-car locally rather than calling import APIs. This can be reused in point 1.
3. Car files are currently not copied over when importing. This saves space and is faster but it also creates re-work if car files has been deleted and deal fails. If we copy the car file then this functionality can be reused to import directory car files without making change to the method params. 
4. All car files will be V2. 
5. We add additional extract command to allow unixfs extraction from a retrieved car file. This will be help when users import a car file directly.
6. Extraction would also need to be integrated with directory retrieval in general so end user doesn't have to care about the car file when dealing with directory. I have not scoped out the work on retrieval side yet. I will need some help with figuring this out.

**Comment by LexLuthr** [comment]
- It would seem that lotus import cannot handle a carv2 file created using go-car library. We are using v1 methods to make calculation on the imported car. Result is below.
  ```
  $ lotus client import --car test.car 
    ERROR: car file can have one and only one header
  ```
- As per the https://filecoinproject.slack.com/archives/CP50PPW2X/p1653654095686329 we are supposed to use carV2.
- PR would require additional changes to incorporate carV2 method when handling car import and ensure backward compatibility with V1.

**Comment by LexLuthr** [comment]
Needs revaluation and redesign

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
