### ISSUE TITLE
ASCII art for network name

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8753]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

When starting up the lotus daemon, print out ASCII art for the network that's being synced (mainnet / calibnet / etc) along with some details of the network.

Or be boring and log it, I guess.

**Comment by rjan90** [comment]
I like this idea! Then we could also print the ascii-art with the `lotus info` cmd for example, so that users easily can see what network they are on:

I liked this style:
```
               _                             
              (_)                        _   
 ____   _____  _  ____   ____   _____  _| |_ 
|    \ (____ || ||  _ \ |  _ \ | ___ |(_   _)
| | | |/ ___ || || | | || | | || ____|  | |_ 
|_|_|_|\_____||_||_| |_||_| |_||_____)   \__)
                                                                                  
```
```
               _   _  _                           _               
              | | (_)| |                     _   (_)              
  ____  _____ | |  _ | |__    ____  _____  _| |_  _   ___   ____  
 / ___)(____ || | | ||  _ \  / ___)(____ |(_   _)| | / _ \ |  _ \ 
( (___ / ___ || | | || |_) )| |    / ___ |  | |_ | || |_| || | | |
 \____)\_____| \_)|_||____/ |_|    \_____|   \__)|_| \___/ |_| |_|
```
```
 _                                            ___  _         
| |              _      _                    / __)| |        
| |__   _   _  _| |_  _| |_  _____   ____  _| |__ | |  _   _ 
|  _ \ | | | |(_   _)(_   _)| ___ | / ___)(_   __)| | | | | |
| |_) )| |_| |  | |_   | |_ | ____|| |      | |   | | | |_| |
|____/ |____/    \__)   \__)|_____)|_|      |_|    \_) \__  |
                                                      (____/ 
```
