### ISSUE TITLE
Check execution trace differences for v16

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8757]
We have a new stream of execution trace info with v16 as we upgrade to the FVM. While care has been taken to make sure the same amount of information is captured, there may be unintended changes in the format / shape of the returned information.

We should remove any such changes if possible -- ideally the output of exec traces with the FVM will be identical to the current output we get on the LegacyVM. This way we guarantee no UX issues arising from the v16 changes, as users won't observe any difference.

**Comment by arajasek** [comment]
We should also test an `MsigAprrove`, since that is the message that's most relevant to our known users of this feature.

**Comment by geoff-vball** [comment]
Note: In nv16, subcall exec traces are no longer populated by default, to get the previous behaviour you must set the env var `LOTUS_VM_ENABLE_TRACING=1` (this was formerly `LOTUS_VM_ENABLE_GAS_TRACING_VERY_SLOW`.

One small change was made in https://github.com/filecoin-project/lotus/pull/8804 to make the exec traces line up.
