### ISSUE TITLE
fstmp files not removed when import failed

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#8775]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.15.2
```

### Describe the Bug

When we import a deal, and the importing fails with;
```
ERROR: normal shutdown of state machine
```
after running or 3 minutes - the fstmp file is not removed.

### Logging Information

```text
-
```

**Comment by RobQuistNL** [comment]
no :sweat_smile: 

I don't want garbage collection (I can do that myself too) - I want Lotus to properly clean up after itself :yum:

**Comment by RobQuistNL** [comment]
Or actually, this one just isn't called properly; 
https://github.com/filecoin-project/go-fil-markets/blob/v1.20.1/storagemarket/impl/provider.go#L339

**Comment by RobQuistNL** [comment]
@LexLuthr

**Comment by LexLuthr** [comment]
It seems cleanup function is called up manually after each error state. I haven't checked the complete path till addpiece() is called but a better way would be to defer cleanup() in the https://github.com/filecoin-project/go-fil-markets/blob/v1.20.1/storagemarket/impl/provider.go#L339 and use the original file path for the addpiece after verifying that car file is good to import. Not sure why we are importing from the temporary file path here.
Need more analysis to find the correct way to fix this.

**Comment by LexLuthr** [comment]
@dirkmc This is the issue we were discussing in the meeting. Can you take a look at this?

**Comment by LexLuthr** [comment]
@RobQuistNL Can you get me the deal state after import failure? I need to understand sectors state and piece's state. So, I can trace what is being traced in the market FSM to try to figure out why delete is not happening.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
