### ISSUE TITLE
Enable "lightweight" migration support

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8780]
As discussed in #8534, Lotus is continuing to rely on specs-actors for migrations, despite the refactor to have state types in go-state-types, and the introduction of the FVM.

While this motivates a larger redesign (that might eventually involve having the FVM perform these migrations through the FFI), there is a smaller actionable item: supporting actor code-only migrations in Lotus (no state transformation except the System Actor).

The inputs would simply be the old manifest, new manifest, and state root, and all the migration needs to do is convert all actor CIDs based on the manifests, and update the system actor state. This should be relatively easy to do quickly without any bells and whistles.

It would be good to have this ready sooner rather than later so as to support quick actor upgrades if needed.

**Comment by arajasek** [comment]
- Link to actors top-level migration: https://github.com/filecoin-project/specs-actors/blob/07de54e8c13def08f585334d54b6e798b606e7a0/actors/migration/nv15/top.go#L86
  - We need to poach most of this logic
  - We will need to either add an _input_ manifest CID, or just have the migration use the system actor state. Latter is probably better.
  - We may want to drop the concurrent migration, just for simplicity.
  - We will need to keep the system actor state migration (changing from old manifest to new manifest). This is the only state migration we will need.
- We probably want to put the new lightweight migration in [chain/filcns/upgrades.go](https://github.com/filecoin-project/lotus/blob/4fa04abb8c77016a99d355e16525ad22b8a028a5/chain/consensus/filcns/upgrades.go#L50), or a new file alongside it.

**Comment by vyzo** [comment]
Shouldnt this link to the nv16 migration?

We should use the system actor state for source, and only argument should be the new manifest cid i think.
