### ISSUE TITLE
go-libp2p-pubsub@v0.7.0  panic

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#8806]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus versino  1.15.4-dev  master
```

### Describe the Bug

2-06-04T17:29:01.003+0800    INFO    chainstore      store/store.go:646      New heaviest tipset! [bafy2bzacea55kgjloc6nohfkfdmn4u2fynwh45bt6d22pvo4memo5lnoypz2e bafy2bzaceac3t7mvj5er2oscfxrpmqhp74bj66d2wvgqo6rqranpcaazdhdn6 bafy2bzacedthsuo7rne2zzriol37rh5zkqrcr553gytbedavvzza22aqjsoc6 bafy2bzacebofgzcz42rtwj4lrvksgbvankh5zjoxmh5ehanbgzkrhvqxp3nms bafy2bzacecd6bkaw2kqxshzb6jdlqy5levryby3pj74ixrguyjio7ek56eax2 bafy2bzacebgqiu767gnhuoxwgpvw4pqn6izkouynxjwvzjkbqs6m2wkrjv6i4] (height=1867618)
2022-06-04T17:29:01.003+0800    INFO    chain   chain/sync_manager.go:322       worker 4075 done; took 493.670501ms
panic: send on closed channel
        panic: close of closed channel

goroutine 1610 [running]:
github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop.func1()
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/pubsub.go:534 +0x74
panic({0x3ad0ce0, 0x499a710})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).doSendRPC(0xc0005e6780, 0xc0eb1bb0a0, {0xc1d2a262d0, 0x26}, 0xc12d26ae00?)
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/gossipsub.go:1178 +0x3e
github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).sendRPC(0xc0005e6780, {0xc1d2a262d0, 0x26}, 0xc0eb1bb0a0)
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/gossipsub.go:1150 +0x509
github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).flush(0xc0005e6780)
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/gossipsub.go:1753 +0x85
github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).heartbeat(0xc0005e6780)
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/gossipsub.go:1583 +0xbf7
github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop(0xc0ec0ab800, {0x49b4b60, 0xc0ec0c8040})
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/pubsub.go:619 +0xbb7
created by github.com/libp2p/go-libp2p-pubsub.NewPubSub
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/pubsub.go:322 +0xdea

### Logging Information

```text
2-06-04T17:29:01.003+0800    INFO    chainstore      store/store.go:646      New heaviest tipset! [bafy2bzacea55kgjloc6nohfkfdmn4u2fynwh45bt6d22pvo4memo5lnoypz2e bafy2bzaceac3t7mvj5er2oscfxrpmqhp74bj66d2wvgqo6rqranpcaazdhdn6 bafy2bzacedthsuo7rne2zzriol37rh5zkqrcr553gytbedavvzza22aqjsoc6 bafy2bzacebofgzcz42rtwj4lrvksgbvankh5zjoxmh5ehanbgzkrhvqxp3nms bafy2bzacecd6bkaw2kqxshzb6jdlqy5levryby3pj74ixrguyjio7ek56eax2 bafy2bzacebgqiu767gnhuoxwgpvw4pqn6izkouynxjwvzjkbqs6m2wkrjv6i4] (height=1867618)
2022-06-04T17:29:01.003+0800    INFO    chain   chain/sync_manager.go:322       worker 4075 done; took 493.670501ms
panic: send on closed channel
        panic: close of closed channel

goroutine 1610 [running]:
github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop.func1()
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/pubsub.go:534 +0x74
panic({0x3ad0ce0, 0x499a710})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).doSendRPC(0xc0005e6780, 0xc0eb1bb0a0, {0xc1d2a262d0, 0x26}, 0xc12d26ae00?)
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/gossipsub.go:1178 +0x3e
github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).sendRPC(0xc0005e6780, {0xc1d2a262d0, 0x26}, 0xc0eb1bb0a0)
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/gossipsub.go:1150 +0x509
github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).flush(0xc0005e6780)
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/gossipsub.go:1753 +0x85
github.com/libp2p/go-libp2p-pubsub.(*GossipSubRouter).heartbeat(0xc0005e6780)
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/gossipsub.go:1583 +0xbf7
github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop(0xc0ec0ab800, {0x49b4b60, 0xc0ec0c8040})
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/pubsub.go:619 +0xbb7
created by github.com/libp2p/go-libp2p-pubsub.NewPubSub
        /home/fil/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.7.0/pubsub.go:322 +0xdea
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by vyzo** [comment]
looks like a new bug in v0.7.

**Comment by rjan90** [comment]
Closing this since go-libp2p-pubsub has been updated to v0.7.1 on master, wich includes the handling of dead peers fix!
