### ISSUE TITLE
could not read full once and got 0 peers

### ISSUE THREAD

**Issue by liang199122** [filecoin-project/lotus#881]
2019-12-12T16:32:49.804+0800	WARN	peermgr	peermgr/peermgr.go:131	failed to connect to bootstrap peer: failed to dial : all dials failed
  * [/ip4/147.75.80.17/tcp/1347] failed to negotiate security protocol: privnet: could not read full nonce

**Comment by whyrusleeping** [comment]
You likely were connected to the wrong bootstrap peers, ensure you are running the latest code, and file a new issue if the problem persists
