### ISSUE TITLE
Error message enhancement: "actor not found" (aka Insufficient FIL)

### ISSUE THREAD

**Issue by wesfloyd** [filecoin-project/lotus#8817]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
v1.15.3
```

### Describe the Bug

To reproduce: 
Attempting to [create a Lotus deal](https://docs.filecoin.io/get-started/store-and-retrieve/store-data/#create-a-deal
) with no FIL in my wallet I encountered the error "resolve address f1qim...jjy: actor not found"

Expected result:
Error message would inform the user they have insufficient FIL in their wallet. E.g. "Insufficient funds in wallet for this transaction"

Actual result:
Error message does not communicate the user's issue (mistake)
"ERROR: resolve address f1qim...jjy: actor not found"

```
wfmb14:launchpad wes$ lotus client deal
Data CID (from lotus client import): bafykbzacebp52galmm6yb5kqr46s7n3hglgv43wyos7zvywlrdvmlom4ficb6
.. calculating data size
Deal duration (days): 180
ERROR: resolve address f1qim6rnkdnqk5mgo6b2675jxvw3xaefhrwozljjy: actor not found
```

### Logging Information

```text
messagepool
disputer
bitswap
bs:sprmgr
fsm
peerstore/ds
blockservice
cmds/http
dagstore/upgrader
dht/RtRefreshManager
fsjournal
engine
graphsync_allocator
badger
chainxchg
rpcenc
relay
preseal
gs-queryexecutor
miner
market_adapter
go-legs/head
pubsub
dht.pb
retrievaladapter
client
idxprov
retrieval
incrt
p2p-holepunch
rcmgr
upgrader
mocknet
filestore
bs:peermgr
retrieval_network
partialfile
repo
fil-consensus
metrics-prometheus
swarm2
peerstore
data-transfer
gs-reconciledlaoder
fsutil
bitswap_network
sub
provider/engine
cli
markets-rtvl-reval
build
statetree
chainstore
advmgr
actors
gs-notifications
payment-channel-settler
basichost
blankhost
boguskey
fullnode
bs:sess
retrieval-discovery
drand
builder
metrics
tarutil
rand
connmgr
p2p-config
events
storageadapter
discovery
routing/record
pathresolv
hello
ffi-wrapper
autonat
system
storageminer
go-legs-httpsync
data_transfer_network
backupds
ipns
wallet
retrievalmarket_impl
chunk
stores
diversityFilter
nat
gen
go-legs
paych
storagemarket_network
providers
gs_request_executor
go-legs-dtsync
lock
table
autorelay
sectoraccessor
chain
evtsm
wallet-ledger
retrieval-fsm
storagemarket_impl
go-legs-gpubsub
watchdog
test-logger
alerting
vm
reuseport-transport
main
cmds
beacon
cliutil
dagstore
dt_graphsync
graphsync
piecestore
importmgr
ffiwrapper
messagesigner
genesis
unixfs
ulimit
tcp-tpt
conngater
dt-impl
blockstore
amt
quic-transport
eventlog
auth
statemgr
tracing
paramfetch
pstoremanager
ping
p2pnode
splitstore
chunker/cached-entries-chunker
types
badgerbs
markets
sectors
net/identify
markets-rtvl
graphsync_network
rpc
storagemrkt
panic-reporter
dht
providerstates
routedhost
peermgr
net/conngater
storedask
modules
cborrrpc
p2p-circuit
dt-chanmon
indexer/schema
node
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

1. Run: attempt to [create a Lotus deal](https://docs.filecoin.io/get-started/store-and-retrieve/store-data/#create-a-deal
) with no FIL in the wallet: "lotus client deal"

3. See "ERROR: resolve address f1qim...jjy: actor not found"

**Comment by rjan90** [comment]
Hey @wesfloyd! Thanks for the issue report. I agree that the error message could be more describing in this context, and that we could describe better that a fresh wallet needs to have some funds sent to it to be initialized/recognized by the chain.

I think also this error should be caught a bit earlier, instead of halfway through the `lotus client deal` flow. It seems like we do not check if the actor (address in this case) is initialized before starting the `uiLoop`:
https://github.com/filecoin-project/lotus/blob/e3f1eb29a14c7acb198e21b86aba1ada74c2cbb1/cli/client.go#L547-L560

So it only errors out when we get to this part in the `uiLoop` when checking if the given address has a datacap:
https://github.com/filecoin-project/lotus/blob/e3f1eb29a14c7acb198e21b86aba1ada74c2cbb1/cli/client.go#L640-L642
