### ISSUE TITLE
Lotus wallet new failed Filename too long

### ISSUE THREAD

**Issue by 0xc0de4c0ffee** [filecoin-project/lotus#883]
`> lotus wallet new`

returns 
`2019-12-12T14:28:42.644+0545	WARN	main	lotus/main.go:74	saving to keystore: checking key before put 'wallet-t3uoivtpw7.......qel77ihtoa': stat /home/username/.lotus/keystore/O5QWY3D....LONG....TO2LIORXWC: file name too long`

`>lotus wallet list`
returns blank

I'm running Ubuntu 18.04.2 and used gvm to install go1.13.

**Comment by magik6k** [comment]
The filename should be 150 characters long. It's likely caused by your filesystem not supporting long file names. Please use a filesystem which supports long file names.

(Reopen if you think the cause is different. We won't be supporting legacy filesystems which only support short file names)

**Comment by jsign** [comment]
@0xc0de4c0ffee , @magik6k , I hit this wall, but length was 179. Too short to have problems.
In my case, was using eCryptFS for my home folder.
Two options:
- not use eCryptFS
- use other folder non-encrypted folder and set-up envs properly
