### ISSUE TITLE
Lotus have double sealing deals with offline deals on boost.

### ISSUE THREAD

**Issue by Araquiel** [filecoin-project/lotus#8832]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [X] Other

### Boost Version

```text
boostd version 0.0.1+git.feb2719
lotus version 1.15.2+mainnet+git.518dc962e
```

### Describe the Bug

lotus not clean stage or maybe have a double import for offline imported deals.
try to seal deals normal but have error ob RU state with faled.
failed sectors have no CID on RU

miner log show error like this:
2022-06-07T15:40:17.066+0500	ERROR	sectors	storage-sealing/states_replica_update.go:173	handleSubmitReplicaUpdate: error sending message: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: no valid updates (RetCode=16)

lotus daemon log show error like this:
2022-06-08T07:33:55.074+0500    WARN    vm      vm/runtime.go:161       LegacyVM.Call failure in call from: f01163272 to f05: deal 6851923 already included in another sector (RetCode=16):
2022-06-08T07:33:55.074+0500    WARN    vm      vm/runtime.go:394       vmctx send failed: from: f01163272 to: f05, method: 6: err: deal 6851923 already included in another sector (RetCode=16)

### Logging Information

```text
lotus daemon log show error like this:
2022-06-08T07:33:55.074+0500    WARN    vm      vm/runtime.go:161       LegacyVM.Call failure in call from: f01163272 to f05: deal 6851923 already included in another sector (RetCode=16):
2022-06-08T07:33:55.074+0500    WARN    vm      vm/runtime.go:394       vmctx send failed: from: f01163272 to: f05, method: 6: err: deal 6851923 already included in another sector (RetCode=16)
```

### Repo Steps

1) import offline deal with boosd storage-deals import data
2) waiting for sealing all
3) wait when sealing finish with non empty stage or have RUFailed statet.
4) all sectors from stage seal with RUFailed error.

**Comment by Reiers** [comment]
Hi @Araquiel 

Thanks for the report. I have added labels and will assign it to the right team for analysis.

**Comment by marshyonline** [comment]
+1 on this issue - i just did a big batch of offline imports where all sealing completed correctly  - except the deals stayed in "DealStaged" status - apon a restart of the miner and boost - ~500 sectors started to seal again
![image](https://user-images.githubusercontent.com/1223011/179901649-13c17ce8-509c-4be6-a4a6-93840d040abf.png)

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
