### ISSUE TITLE
validate full sync since nv15 till today

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#8836]
as we approach to code freeze - we should validate that the all states are gucci gucci since v15 (the version fvm starts to support) till today!

so:
- build from branch `release/v1.16.0`
- import a snapshot that has the state since 1594678 (2 epoch before the v15 upgrade)
- set  LOTUS_USE_FVM_TO_SYNC_MAINNET_V15 to 1
- confirm it can keep syncing mainnet!

@angelo-gh3990 will be helping on this! thank you - please leave a comment in this issue if anything is found!

**Comment by Angelo-gh3990** [comment]
* Lotus is upgraded to release/v1.16.0
      Daemon:  1.16.0-dev+mainnet+git.87d1e8ddf+api1.5.0
      Local: lotus version 1.16.0-dev+mainnet+git.87d1e8ddf
* env variable is set to LOTUS_USE_FVM_TO_SYNC_MAINNET_V15=1
* Snapshot is imported
* Daemon is syncing the chain as we speak
      root@bru-fil-ap-01-dev:/# lotus sync wait
      Worker: 0; Base: 1595280; Target: 1884110 (diff: 288830)
      State: header sync; Current Epoch: 1699776; Todo: 184334
      Validated 0 messages (0 per second) 

I will update the github page if I run into any issues (edited)

**Comment by happyhq** [comment]
> 

I will try it.

**Comment by jennijuju** [comment]
@happyhq how did it go?

**Comment by rjan90** [comment]
Closing this issue now since we now have upgraded to nv16.
