### ISSUE TITLE
checksum mismatch

### ISSUE THREAD

**Issue by IPSE-TEAM** [filecoin-project/lotus#885]
main.glob..func2
        /home/circleci/project/cmd/lotus-storage-miner/init.go:96
  - the following errors occurred:
     -  checking file /var/tmp/filecoin-proof-parameters/v20-proof-of-spacetime-election-a4e18190d4b4657ba1b4d08a341871b2a6f398e327cb9951b28ab141fbdbf49d.vk failed:
            github.com/filecoin-project/lotus/build.(*fetch).maybeFetchAsync.func1
                /home/circleci/project/build/paramfetch.go:100
          - checksum mismatch in param file /var/tmp/filecoin-proof-parameters/v20-proof-of-spacetime-election-a4e18190d4b4657ba1b4d08a341871b2a6f398e327cb9951b28ab141fbdbf49d.vk, e79bfd539e942f171f7ea20ef8be7611 != 91fac550e1f9bccab213830bb0c85bd6:

**Comment by chengwds** [comment]
2019-12-12T18:47:51.269+0800	INFO	main	lotus-storage-miner/init.go:116Checking if repo exists
2019-12-12T18:47:51.270+0800	WARN	main	lotus-storage-miner/main.go:76	repo at '~/.lotusstorage' is already initialized:
    main.glob..func2
        /home/circleci/project/cmd/lotus-storage-miner/init.go:129

**Comment by whyrusleeping** [comment]
it could be caused either by your download failing, or by you starting the daemon and miner at the same time. This might be resolved by #686, but in any case is a known issue.
