### ISSUE TITLE
[missing docs] no link named "lotus" under ...

### ISSUE THREAD

**Issue by pinheadmz** [filecoin-project/lotus#8870]
I was hoping to find some instructions on building lotus and setting up, but...

https://docs.filecoin.io/get-started/lotus/:
`ipfs resolve -r /ipfs/bafybeic7oy5trxty3e7qjqz3s47mgqk52gh24i6vomxpvymtwcfadx5slm/get-started/lotus/: no link named "lotus" under QmWwbyRwRECG6fXkY318FpD99tV9KsJf8UVaSsMq64aKsS`

https://docs.filecoin.io/get-started/lotus/installation/#build-and-install-lotus:
`ipfs resolve -r /ipfs/bafybeic7oy5trxty3e7qjqz3s47mgqk52gh24i6vomxpvymtwcfadx5slm/get-started/lotus/installation/: no link named "lotus" under QmWwbyRwRECG6fXkY318FpD99tV9KsJf8UVaSsMq64aKsS`

https://docs.filecoin.io/build/examples/:
`ipfs resolve -r /ipfs/bafybeic7oy5trxty3e7qjqz3s47mgqk52gh24i6vomxpvymtwcfadx5slm/build/examples/: no link named "examples" under Qmar8SM2cgm5tYwPXxKT2hEvRqX12P7MCdum5PEPgi2ZzN`

**Comment by TippyFlitsUK** [comment]
Hi @pinheadmz 

Please refer to [https://lotus.filecoin.io/lotus/get-started/what-is-lotus/](https://lotus.filecoin.io/lotus/get-started/what-is-lotus/) for the current Lotus docs.

Many thanks!!

**Comment by TippyFlitsUK** [comment]
Closing as this is not a Lotus issue. The correct repo for this is [https://github.com/filecoin-project/lotus-docs](https://github.com/filecoin-project/lotus-docs).
