### ISSUE TITLE
collectChain failed: chain linked to block marked previously as bad  

### ISSUE THREAD

**Issue by happyhq** [filecoin-project/lotus#8874]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
$ lotus version
Daemon:  1.16.0-rc1+mainnet+git.5a67bb0f6+api1.5.0
Local: lotus version 1.16.0-rc1+mainnet+git.5a67bb0f6
```

### Describe the Bug

When I use lotus sync wait.It doesn't work.It just say like this：
、
$ lotus sync wait
Worker: 90; Base: 1902240; Target: 1903350 (diff: 1110)
State: error; Current Epoch: 0; Todo: 1903350
Validated 425 messages (0 per second)

### Logging Information

```text
2022-06-16T19:18:01.334Z        ERROR   chain   chain/sync_manager.go:253       error during sync in [bafy2bzacecb5qksdhaanvjn72om34ecf5fiipp53fccnn3aicet36fgqyukzg]: collectChain failed: chain linked to block marked previously as bad ([bafy2bzacecb5qksdhaanvjn72om34ecf5fiipp53fccnn3aicet36fgqyukzg], bafy2bzaced24iatmo5ozq2wv5uc7bmvemj5xr6iabrzljuz5a5fdqsjvtgp66) (reason: linked to bafy2bzacean3572mgbyxjmtrxh3hve6lh3imwplhnxffkr7lyhvnjsp5gpequ caused by: [bafy2bzacebnfvn27tgxrsqt3ouizrmeuafvpio6bs3ngzprxnq6t4cogkviie] 2 errors occurred:
        * invalid election post:
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).ValidateBlock.func9
        /home/fil/workspaces/lotus/chain/consensus/filcns/filecoin.go:303
  - failed to verify election post:
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).VerifyWinningPoStProof
        /home/fil/workspaces/lotus/chain/consensus/filcns/filecoin.go:425
  - No cached parameters found for proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-b62098629d07946e9028127e70295ed996fe3ed25b0f9f88eb610a0ab4385a3c [failure finding /storage/sg081/lotus/fil_proofs_parameter_cache/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-b62098629d07946e9028127e70295ed996fe3ed25b0f9f88eb610a0ab4385a3c.params]
        * parent state root did not match computed state (bafy2bzacecwi64m5xmna6r7xpp7u7g2wjoqboakwhm4ivguztlkos3sxv6ql2 != bafy2bzacea45hxtvr4ztzmszamtwbpw2xsxapcfqc3atz4vvqr77zieattjty):
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).ValidateBlock.func4
        /home/fil/workspaces/lotus/chain/consensus/filcns/filecoin.go:185

)
```

### Repo Steps

1. Run 'lotus daemon --import-snapshot_stateroots_1902240_2022-06-16_10-00-00.car'
2. Do 'lotus sync wait'
3. See error
4.  '$ lotus sync wait
Worker: 205; Base: 1902240; Target: 1903371 (diff: 1131)
State: error; Current Epoch: 0; Todo: 1903371
Validated 425 messages (0 per second)'
...

**Comment by yuanlizbyy** [comment]
You may set env var `LOTUS_USE_FVM_TO_SYNC_MAINNET_V15=1` and restart lotus.

**Comment by happyhq** [comment]
Thanks.
I have solved the problem. I switched from a mechanical disk to an SSD disk . The problem was solved.
