### ISSUE TITLE
API: get Manifest / actors code CID

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#8906]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

so people can get CID easily!

### Describe the solution you'd like

open question, we the abi should look like? just return all? or specific cid?

**Comment by jennijuju** [comment]
take a account key name https://github.com/filecoin-project/lotus/blob/b368d085963621cb3e877e085b00821df99a2753/build/builtin_actors_gen.go#L82-L92  and return a cid

**Comment by jennijuju** [comment]
network veresion should also be a param input,. and we get the actor version maps to that network version

**Comment by rjan90** [comment]
Closing this issue since this API feature has been made and merged.
