### ISSUE TITLE
In v1.16.0, use make clean all to compile different

### ISSUE THREAD

**Issue by coder-chenda** [filecoin-project/lotus#8920]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/83049018/175877764-5779e4d2-0090-47af-8318-0f784e9bb95b.png">

**Comment by coder-chenda** [comment]
> * Which go-version are you using?

go version go1.17.6 linux/amd64

OS is ubuntu 
cpu 
According to the official requirements
It is normal before upgrading, but after upgrading this version, the upgrade steps are somewhat different from those in the past

**Comment by rjan90** [comment]
Hey @coder-chenda!

Please update your Go-version to Go 1.17.9 or higher as that is needed for the v1.16.0 version: https://lotus.filecoin.io/lotus/install/linux/#go

**Comment by coder-chenda** [comment]
Hello, I want to ask whether this go version upgrade is mandatory? Because I installed some required libraries last time, the compilation of Lotus can still succeed, and now the nodes are synchronized normally, so I don't know whether it is mandatory.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/lotus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月1日(星期五) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecoin-project/lotus] In v1.16.0, use make clean all to compile different (Issue #8920)





 
Hey @coder-chenda!
 
Please update your Go-version to Go 1.17.9 or higher as that is needed for the v1.16.0 version: https://lotus.filecoin.io/lotus/install/linux/#go

**Comment by rjan90** [comment]
I strongly reccomend to be on a Go 1.17.9 or higher when using v1.16.0. Although you might be in sync currently, other commands might fail due to being on a Go-version lower then that.

That said, it seems you are not having any compiling issues, which this issue-ticket was created about. So I´m closing this one now! If you want to troubleshoot or ask questions about other things I recommend using the Github Discussions or Slack 😄
