### ISSUE TITLE
Core dumped will be occurred when ParallelCheckLimit set a high value 

### ISSUE THREAD

**Issue by Pegasus-starry** [filecoin-project/lotus#8922]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
release/v1.16.0
```

### Describe the Bug

For the new release 1.16.0,  if I  set the parameter ParallelCheckLimit to a big value, such as 1024, or set to 0(is use the len(sectors), eg 2049).  
[Proving]
ParallelCheckLimit = 1024

One core dumped will meet.  I consider the function GenerateSingleVanillaProof can’t support big concurrence. 

### Logging Information

```text
{"level":"info","ts":"2022-06-27T08:34:30.784+0000","logger":"filecoin_proofs::api::post_util","caller":"/home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/filecoin-proofs-11.1.1/src/api/post_util.rs:132","msg":"generate_single_vanilla_proof:start: SectorId(18513)"}
{"level":"info","ts":"2022-06-27T08:34:30.784+0000","logger":"filecoin_proofs::api::post_util","caller":"/home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/filecoin-proofs-11.1.1/src/api/post_util.rs:132","msg":"generate_single_vanilla_proof:start: SectorId(18246)"}
{"level":"info","ts":"2022-06-27T08:34:30.784+0000","logger":"filecoin_proofs::api::post_util","caller":"/home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/filecoin-proofs-11.1.1/src/api/post_util.rs:132","msg":"generate_single_vanilla_proof:start: SectorId(17469)"}
{"level":"info","ts":"2022-06-27T08:34:30.784+0000","logger":"filecoin_proofs::api::post_util","caller":"/home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/filecoin-proofs-11.1.1/src/api/post_util.rs:132","msg":"generate_single_vanilla_proof:start: SectorId(17478)"}
{"level":"info","ts":"2022-06-27T08:34:30.784+0000","logger":"filecoin_proofs::api::post_util","caller":"/home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/filecoin-proofs-11.1.1/src/api/post_util.rs:132","msg":"generate_single_vanilla_proof:start: SectorId(18199)"}
{"level":"info","ts":"2022-06-27T08:34:30.784+0000","logger":"filecoin_proofs::api::post_util","caller":"/home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/filecoin-proofs-11.1.1/src/api/post_util.rs:132","msg":"generate_single_vanilla_proof:start: SectorId(18197)"}
{"level":"info","ts":"2022-06-27T08:34:30.784+0000","logger":"filecoin_proofs::api::post_util","caller":"/home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/filecoin-proofs-11.1.1/src/api/post_util.rs:132","msg":"generate_single_vanilla_proof:start: SectorId(19598)"}
{"level":"info","ts":"2022-06-27T08:34:30.784+0000","logger":"filecoin_proofs::api::post_util","caller":"/home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/filecoin-proofs-11.1.1/src/api/post_util.rs:132","msg":"generate_single_vanilla_proof:start: SectorId(18290)"}
{"level":"info","ts":"2022-06-27T08:34:30.784+0000","logger":"filecoin_proofs::api::post_util","caller":"/home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/filecoin-proofs-11.1.1/src/api/post_util.rs:132","msg":"generate_single_vanilla_proof:start: SectorId(18505)"}
{"level":"info","ts":"2022-06-27T08:34:30.784+0000","logger":"filecoin_proofs::api::post_util","caller":"/home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/filecoin-proofs-11.1.1/src/api/post_util.rs:132","msg":"generate_single_vanilla_proof:start: SectorId(18716)"}
....
(Comment: so many "generate_single_vanilla_proof:start", but NO "generate_single_vanilla_proof:finish" found.)

 Segmentation fault      (core dumped) /home/ps/share/ssd/bin/bin_$V/lotus-miner run
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by rjan90** [comment]
Hey @Pegasus-starry! Yes, this error is expected if you set that value as high as you did. We currently do not set an upper-bound limit on the config because it is an advanced value that only experienced storage providers testing their setup would change.

As noted in the docs, the changing this value should be done with caution:
`Use with caution. Changing these values to extremes might cause you to miss windowPoSt.`

**Comment by Pegasus-starry** [comment]
@rjan90 thanks for your reply. But even I set to a normal small value to let WindowPost work,  if I use "lotus-miner proving check --slow 0" at the same time, the core dumped also occurred.

**Comment by Pegasus-starry** [comment]
@rjan90  Can you confirm the problem I describe above?

**Comment by rjan90** [comment]
Hey @Pegasus-starry! No, I was not able to reproduce the `(core dumped)`-error when running `lotus-miner poving check --slow <deadline>` with the default `ParallelCheckLimit`-value.

Did you remember to restart after you changed it?

Can you also try to run: `lotus-miner proving compute window-post 0`, as that will simulate a real windowPoSt.

**Comment by Elhorses** [comment]
> Hey @Pegasus-starry! No, I was not able to reproduce the `(core dumped)`-error when running `lotus-miner poving check --slow <deadline>` with the default `ParallelCheckLimit`-value.
> 
> Did you remember to restart after you changed it?
> 
> Can you also try to run: `lotus-miner proving compute window-post 0`, as that will simulate a real windowPoSt.

The same problem occurred when we ran the V16 version of Lotus

**Comment by Pegasus-starry** [comment]
@rjan90 This issue is not hard to reproduce.  because the cause is more GenerateSingleVanillaProof will be invoked when "proving check" running!   You can turn up the ParallelCheckLimit-value to let it can run Windowpost normal, can run "Proving check" at the same time the wdpost.

**Comment by Pegasus-starry** [comment]
Another issue :  the below command take so much time. only 2349 sectors 
~$ lotus-miner proving compute window-post 4
Took 3m30.01366566s
[{"Deadline":4,"Partitions":[{"Index":0,"Skipped":[0]}],"Proofs":[{"PoStProof":8,"ProofBytes":"j9FtmQGexyuwmS6Yxmwjt7iOuue8h9HvID4TxalZP8vtkKKDfiQvhK13cR1QLYlVsLpqUMpJnkT44cOK6V2CTiuOivblr545evyh6qlLAu7h1TTLH9JySTDANwIodhccEvmjg/uNStd2TV5MNAmX+3NFDa0kAEuL7rmUDpyicTlA/dPyriM2Tw7TuN9OwWlClireCyCb8tAPhF7/sQ4SD0H5PXTIWa6C0fP4bKM8izQfbaWSMIkE6XEqwNmK6B5E"}],"ChainCommitEpoch":0,"ChainCommitRand":null}]
