### ISSUE TITLE
lotus to calibnet sync ERROR

### ISSUE THREAD

**Issue by yangyueqiangyy** [filecoin-project/lotus#8932]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [x] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.16.0+calibnet+git.01254ab32
```

### Describe the Bug

lotus to calibnet sync ERROR：
$lotus-1.16.0 sync wait
Worker: 47; Base: 1077294; Target: 1077388 (diff: 94)
State: error; Current Epoch: 0; Todo: 1077388
Validated 0 messages (0 per second)

### Logging Information

```text
2022-06-28T10:10:31.045+0800    ERROR   chain   chain/sync_manager.go:253       error during sync in [bafy2bzacedtqv37mmsep52e7lxkizllablhjm53zjoups33gtq4xbfyycci5w]: collectChain failed: chain linked to block marked previously as bad ([bafy2bzacedtqv37mmsep52e7lxkizllablhjm53zjoups33gtq4xbfyycci5w], bafy2bzacecmz7luj4cmaihirgzp2vg7p6dl55g4wspqoo2rtsyfefqb22klo6) (reason: linked to bafy2bzaced6asbqwbzltsqnb2q6t4yxkjksnyko36hs2xsy3old5gr7voznpi caused by: [bafy2bzacebxvpnipkc5mdeng2hfsfz5476zfsxb77hwwvabqpksieqaf4frqm] 4 errors occurred:
        * failed to validate blocks random beacon values:
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).ValidateBlock.func7
        /home/pack/lotus-v1.16.0/lotus/chain/consensus/filcns/filecoin.go:269
  - expected final beacon entry in block to be at round 2031620, got 2031619:
    github.com/filecoin-project/lotus/chain/beacon.ValidateBlockValues
        /home/pack/lotus-v1.16.0/lotus/chain/beacon/beacon.go:84
        * determining if miner has min power failed:
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).ValidateBlock.func5
        /home/pack/lotus-v1.16.0/lotus/chain/consensus/filcns/filecoin.go:208
  - loading power actor state:
    github.com/filecoin-project/lotus/chain/stmgr.minerHasMinPower
        /home/pack/lotus-v1.16.0/lotus/chain/stmgr/actors.go:409
  - load state tree:
    github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).ParentState
        /home/pack/lotus-v1.16.0/lotus/chain/stmgr/read.go:28
  - failed to load state tree bafy2bzacedrhnlxxckrkewcqevu6xckxkqrx5nkr3v2cua3yocguqxhaoq7xq:
    github.com/filecoin-project/lotus/chain/state.LoadStateTree
        /home/pack/lotus-v1.16.0/lotus/chain/state/statetree.go:285
  - failed to load hamt node:
    github.com/filecoin-project/specs-actors/actors/util/adt.AsMap
        /root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.15/actors/util/adt/map.go:41
  - blockstore: block not found
        * block had invalid messages:
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).ValidateBlock.func1
        /home/pack/lotus-v1.16.0/lotus/chain/consensus/filcns/filecoin.go:134
  - failed to compute tipsettate for {bafy2bzacedde6z32molda4qzvej2d2colddn4ld24rzr3mf3oucsoxoxnh7sa,bafy2bzacedrf4wct2ecdkgqbodjelmaqrqexhexmrathln4brwzptgdw4jqkc}:
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).checkBlockMessages
        /home/pack/lotus-v1.16.0/lotus/chain/consensus/filcns/filecoin.go:462
  - making cron vm:
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*TipSetExecutor).ApplyBlocks
        /home/pack/lotus-v1.16.0/lotus/chain/consensus/filcns/compute_state.go:150
  - Serialization error for Cbor protocol: RequireLength { name: "tuple", expect: 1, value: 0 }
        * get tipsetstate(1077295, [bafy2bzacedde6z32molda4qzvej2d2colddn4ld24rzr3mf3oucsoxoxnh7sa bafy2bzacedrf4wct2ecdkgqbodjelmaqrqexhexmrathln4brwzptgdw4jqkc]) failed:
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).ValidateBlock.func4
        /home/pack/lotus-v1.16.0/lotus/chain/consensus/filcns/filecoin.go:170
  - making cron vm:
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*TipSetExecutor).ApplyBlocks
        /home/pack/lotus-v1.16.0/lotus/chain/consensus/filcns/compute_state.go:150
  - Serialization error for Cbor protocol: RequireLength { name: "tuple", expect: 1, value: 0 }

)
```

**Comment by xutao123777** [comment]
Worker: 26; Base: 1080459; Target: 1080477 (diff: 18)
State: error; Current Epoch: 0; Todo: 1080477
Validated 0 messages (0 per second)
I have the same problem
