### ISSUE TITLE
error: rg is nil

### ISSUE THREAD

**Issue by Elhorses** [filecoin-project/lotus#8948]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
daemon: lotus version 1.16.0+mainnet+git.01254ab32
miner:  lotus version 1.16.0+mainnet+git.01254ab32
```

### Describe the Bug

when I ran "lotus-miner proving check 0", get error "rg is nil"

### Logging Information

```text
ERROR: rg is nil, I can't check fast, just slow

On the one hand, if I set the 'LOTUS_PROVING_PARALLELCHECKLIMIT' value to a large value, for example 1024, I'll get error 'core dump' when I ran 'proving check', but I get this error again when I set the 'LOTUS_PROVING_PARALLELCHECKLIMIT' value to 128 and open three window to run 'proving check'
```

### Repo Steps

1. Run 'lotus-miner proving check 0'
2. Get error 'rg is nil'

**Comment by rjan90** [comment]
Hey @Elhorses! Thanks for the issue-report 🙂 This is a know issue, and is being tracked here: https://github.com/filecoin-project/lotus/issues/8560.

As you noted, it is still possible to use the command with tha `--slow` option. Closing this issue as it is a duplicate, and referencing it in #8560 instead!
