### ISSUE TITLE
proto: is printing out annoying lines for CLIs when starting 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#8953]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
v1.17.1-dev
```

### Describe the Bug

 All commands now print
2022/07/01 18:32:58 proto: duplicate proto type registered: pb.NoiseHandshakePayload

### Logging Information

```text
see above
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by jennijuju** [comment]
cc @vyzo

**Comment by vyzo** [comment]
@marten-seemann can we figure this one out? It's deep in the stack, in noise.

**Comment by marten-seemann** [comment]
Sure, can you transfer this to go-libp2p please, or create a new issue there?

**Comment by marten-seemann** [comment]
We're not seeing this anywhere in libp2p or IPFS, so this might actually be a Lotus issue. The way to debug this would be to figure out where the duplicate function calls are originating from.

**Comment by jennijuju** [comment]
(lolol I swear to god I saw a transfer issue comment and a magic refresh made it gone lolol

**Comment by marten-seemann** [comment]
> (lolol I swear to god I saw a transfer issue comment and a magic refresh made it gone lolol

Indeed, then I looked into it and realized that this is _probably_ not a libp2p issue.

**Comment by Stebalien** [comment]
The issue is that lotus is using both go-libp2p-noise, and the noise go-libp2p repo. See https://github.com/filecoin-project/lotus/pull/8996 for a fix.

Ideally we'd pull in https://github.com/drand/drand/pull/1035 as well, but that's not critical.
