### ISSUE TITLE
`lotus-miner storage-deals list -v` misses TransferChannelID

### ISSUE THREAD

**Issue by mtelka** [filecoin-project/lotus#8960]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.16.0+calibnet+git.01254ab.dirty+api1.5.0
Local: lotus-miner version 1.16.0+calibnet+git.01254ab.dirty
```

### Describe the Bug

I noticed that after upgrade of our calibnet miner from `v1.16.0-rc1` to `v1.16.0` the `lotus-miner storage-deals list -v` output changed.  The output no longer contains the `TransferChannelID` entry (but `TransferChannelID` is still in the header).

The difference looks like this:
```
< Sep 3 09:02:59 false bafyreifzfokvyebjn63zzi47czabxbywr5n72n7gsxiv3fgr2473ke3fxm 28061 StorageDealExpired t3w4w7dnbkz3yd6vk6zrcoetbeno2l3unpcxdhf6uk6uxfc4holkbtyvubyizfwylcoe4nkyj2nk5234hstbxq 256B 0.0002602495 FIL 520499 12D3KooWEa8J8L9mfsyxCXUg7JXce7EA21bZGi1JSvbjHEdzoL8e-12D3KooWN4MX4hWHjsJUJi6bKCnmXJMN8jL6ne55nCCTaKV4HLSm-1630650046789708641
> Sep 3 09:02:59 false bafyreifzfokvyebjn63zzi47czabxbywr5n72n7gsxiv3fgr2473ke3fxm 28061 StorageDealExpired t3w4w7dnbkz3yd6vk6zrcoetbeno2l3unpcxdhf6uk6uxfc4holkbtyvubyizfwylcoe4nkyj2nk5234hstbxq 256B 0.0002602495 FIL 520499
```
I suspect the problem could be related to `go-fil-markets` because it got updated from `v1.20.1-v16-1` in `v1.16.0-rc1` to `v1.20.1-v16-2` in `v1.16.0`.

### Logging Information

```text
When `lotus-miner storage-deals list -v` is run it produces no new miner log entries.
```

### Repo Steps

Run `lotus-miner storage-deals list -v` at lotus `v1.16.0` and compare the output when run at lotus `v1.16.0-rc1` or older.

**Comment by rjan90** [comment]
Hey @mtelka!

I tried to reproduce it here locally (on v1.17.0-rc3), but where unable to see the missing TransferChannelID when I made a deal against myself. But I suspect that this might be an issue if the client and/or the sp is using Boost? So was just wondering if you have Boost set up?

```
lotus version
Daemon:  1.17.0-rc3+butterflynet+git.9794652e0+api1.5.0
Local: lotus version 1.17.0-rc3+butterflynet+git.9794652e0
```

```
lotus-miner storage-deals list -v
Creation         Verified  ProposalCid                                                  DealId  State               Client                                     Size    Price               Duration  TransferChannelID                                                                                                              Message
Jul 18 15:50:30  false     bafyreihy27uodutyc5tdwsqdhghadq6qtt3w2vvmpcara3t4wsvfnh5ei4  2880    StorageDealSealing  t1p34z3ex72fa3v7h7thkwl6n3ggqzgne3sz5ls3y  128MiB  0.000032556125 FIL  520898    12D3KooWKaxCBsWPc9X893uq5r1tcEK75tfS32g1RVkKd179n48Y-12D3KooWNScfH1SyNjGNZbQwRieZTsSAsPHVELpXodocjcEuvPwT-1658136052522026352 
```

If you are not using Boost then I suspect that there might have been some dependency fixes between v1.16.0 and v1.17.0-rc3 that fixed this issue 😄

**Comment by mtelka** [comment]
This happens without boost.

**Comment by rjan90** [comment]
Okay! I will try to downgrade to v1.16.0 and reproduce it there then, but as you wrote this might have been an issue is an dependency (go-fil-markets), which now seems to have been fixed in v1.17.0 (v1.17.0 is using go-fil-markets v1.23.1).

**Comment by mtelka** [comment]
@rjan90 I see this all the time on both mainnet and calibnet.

**Comment by rjan90** [comment]
Okay! Then the problem boils down to the differences between our configs/nodes. Using go v1.17.9 here. Do you by any chance get deals from Estuary? Just to further narrow it down that it's not a client side thing.

`Jul 22 15:06:45  true   bafyreibigqwhlj4x64oqmlz7doi5di6mey2z2pjvum5g5zeqgjpxnjr4ma  8148457  StorageDealAwaitingPreCommit  f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a  8GiB    0 FIL                     1494720   12D3KooWN8vAoGd6eurUSidcpLYguQiGZwt4eVgDvbgaS7kiGTup-12D3KooWLVyjYwoWCPYmvnCkAzwmYBmPAR2zb7g1DT3eALWU2twY-1658491580141506313`

**Comment by mtelka** [comment]
No Estuary.  v1.15.3 (where it worked) was compiled using go 1.17.9 here too.

**Comment by rjan90** [comment]
Hey @mtelka! I have been unable to reproduce the missing TransferChannelID on v1.16.x and on v1.17.0 + v1.17.1-rc1 from the clients that I´m recieving from. So only sucpision I have is that there is something wrong with the client here, do you happen to know who the client is?

**Comment by mtelka** [comment]
All our storage deals from all clients are missing TransferChannelID.  This affects really all deals, even those created long time ago.

**Comment by TippyFlitsUK** [comment]
Hi 👋 

The Legacy Lotus Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023.

This ticket is being marked as `won't fix` and closed as the Lotus Team will no longer be making any further fixes or enhancements to the legacy markets subsystem.

Please feel free to re-open this ticket in the new Boost markets sub-system repository at https://github.com/filecoin-project/boost if you feel that it is still relevant.

Many thanks 🙏
