### ISSUE TITLE
lotus client retrieve fails after initial retrieval

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#8964]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.16.0+mainnet+git.01254ab32+api1.5.0
Local: lotus version 1.16.0+mainnet+git.01254ab32
```

### Describe the Bug

In running Evergreen retrieval commands, first retrieval works as expected and car file downloads.
Next retrieval attempt fails with error below.

Even this fails now:
`lotus client retrieve --provider f0867429 --car QmfCy3zQohXN1vXuTDpVugZMujCvpxcNE8rSnkYaGusCJ6 --help`

> ERROR: fatal error calling 'Filecoin.ClientMinerQueryOffer': panic in rpc method 'Filecoin.ClientMinerQueryOffer': runtime error: invalid memory address or nil pointer dereference

### Logging Information

```text
No particular events seen in logs
```

### Repo Steps

1. Run 'lotus client retrieve --provider f0838684 --maxPrice 0 --allow-local --car 'QmZBimEhj4CuozSp113cBKvLrNDUQ9mZd6przWAwBexEok' $(pwd)/baga6e~v3sh3yhi__QmZBim~AwBexEok.car'
2. After retrieval completes run a new retrieval:
3. Run 'lotus client retrieve --provider f0867429 --maxPrice 0 --allow-local --car 'QmfCy3zQohXN1vXuTDpVugZMujCvpxcNE8rSnkYaGusCJ6' $(pwd)/baga6e~p77dqqjy__QmfCy3~YaGusCJ6.car'
4. See error 'ERROR: fatal error calling 'Filecoin.ClientMinerQueryOffer': panic in rpc method 'Filecoin.ClientMinerQueryOffer': runtime error: invalid memory address or nil pointer dereference'
5. All subsequent attempts for other retrievals also fail
...

**Comment by stuberman** [comment]
Other retrievals also fail:

`lotus client retrieve --provider f0134516 --maxPrice 0 --allow-local --car 'QmRvVnt4qijnTHK8jAZxA6thSg9rEGW5AhNVNpQ11deqJz' $(pwd)/baga6e~jmbnqupi__QmRvVn~Q11deqJz.car`

2022-07-03T11:58:30.848Z	WARN	rpc	go-jsonrpc@v0.1.5/client.go:544	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWCue8qy4otYP68SZFQCvZbVTE2gYAuVk2q77auyS7te5a:\\n  * [/ip4/192.35.244.45/tcp/26734] dial tcp4 0.0.0.0:46718-\\u003e192.35.244.45:26734: i/o timeout\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f0134516\",\"MinerPeer\":{\"Address\":\"f0134516\",\"ID\":\"12D3KooWCue8qy4otYP68SZFQCvZbVTE2gYAuVk2q77auyS7te5a\",\"PieceCID\":null}}"}

ERROR: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'

**Comment by stuberman** [comment]
Apparently these 'errors' are simply very obscure and misleading logs for 'unable to retrieve the requested piece'.

**Comment by stuberman** [comment]
Reopened due to "invalid memory address or nil pointer dereference" error when trying to retrieve using
`lotus client retrieve --provider f0838684 --maxPrice 0 --allow-local --car 'QmZBimEhj4CuozSp113cBKvLrNDUQ9mZd6przWAwBexEok' $(pwd)/baga6ev3sh3yhi__QmZBimAwBexEok.car`

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system, [which reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and has been completely removed from the code:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
