### ISSUE TITLE
lotus-stats incorrectly decodes some actors IDs

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#8973]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
$ lotus-stats --version
lotus-stats version 1.16.0+mainnet+git.01254ab32
```

### Describe the Bug

Some actors are failing to parse correctly and results in a mangled actor code. This is causing the writes to fail around actor message
<img width="1498" alt="Screen Shot 2022-07-06 at 7 33 58 AM" src="https://user-images.githubusercontent.com/165274/177575649-afdbfcb7-a5fc-4b2d-9632-f95bd903ae0d.png">
s

### Logging Information

```text
2022-07-06T14:31:36.664Z	WARN	stats/influx	influx/influx.go:50	Failed to write batch	{"error": "{\"error\":\"write failed: partial write: key contains invalid unicode: \\\"chain.message_count,actor=?6?l5?I?|\\\\\\\\ 5??_?z?#?2?Q?,exitcode=7,method=7\\\" dropped=10\"}\n"}
```

**Comment by rjan90** [comment]
Hey @travisperson! It seems like this issue has been addressed and fixed with your PR? Just wanted to double-check before.
