### ISSUE TITLE
v16: Things to monitor

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#8975]
This issue captures a list of things to monitor for over the days / weeks following the v16 upgrade?

- When and where does the basefee stabilise after 2-3 days? Is it more uneven than before?
- Are the number of messages running out of gas (in particular PreCommit and ProveCommits) noticeably higher a week later?

**Comment by raulk** [comment]
* Keep an eye on the gas expenditure of messages that deserved "special attention" as per FIP-0032: https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0032.md#incentive-considerations:

> DeclareFaultsRecovered (miner actor): highest variability between executions and highest multiplier; on average, gas cost increases 8.67x, with some instances spiking as much as 33.3x in the backtest. All executions were within the block gas limit.
> ExtendSectorExpiration (miner actor): infrequent; was already an expensive message. Some executions lead to gas usage beyoned the block limit, rendering them inviable (up to 2.3e10 gas). However, this is a batched message, so clients should size batches within gas limits.
