### ISSUE TITLE
lotus daemon continuously printing 'error in RPC call to 'Filecoin.StateSectorExpiration': failed to find sector xxx'

### ISSUE THREAD

**Issue by mtelka** [filecoin-project/lotus#8981]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.16.0+mainnet+git.01254ab.dirty+api1.5.0
Local: lotus-miner version 1.16.0+mainnet+git.01254ab.dirty
```

### Describe the Bug

Lotus node outputs the following warning for Removed (e.g. expired) sectors:

```
2022-07-07T11:23:19.484+0200    WARN    rpc     go-jsonrpc@v0.1.5/handler.go:279        error in RPC call to 'Filecoin.StateSectorExpiration': failed to find sector 412:
    github.com/filecoin-project/lotus/chain/actors/builtin/miner.(*state8).GetSectorExpiration
        /opt/src/lotus/lotus/chain/actors/builtin/miner/v8.go:192
```

This issue is similar (or same) as #5623.  I'm opening new ticket as was suggested in #5623.

### Logging Information

```text
2022-07-07T11:23:19.484+0200    WARN    rpc     go-jsonrpc@v0.1.5/handler.go:279        error in RPC call to 'Filecoin.StateSectorExpiration': failed to find sector 412:
    github.com/filecoin-project/lotus/chain/actors/builtin/miner.(*state8).GetSectorExpiration
        /opt/src/lotus/lotus/chain/actors/builtin/miner/v8.go:192
```

### Repo Steps

1. Make sure you have at least one Removed sector that was on-chain previously.
2. Run `lotus-miner sectors list -u`
3. Look at the **node** log.

**Comment by TippyFlitsUK** [comment]
Hi @mtelka 

Many thanks for your ticket and for taking the time to search for similar issues!

This has been the standard behavior when running `lotus-miner sectors list` for a long time but I agree that the additional logging is really not useful.

I will add labels and make sure this gets to the relevant team.

:pray:

**Comment by TippyFlitsUK** [comment]
Just out of interest @mtelka, have you tried running `lotus-miner sectors compact-partitions` on the deadlines with the removed sectors?

**Comment by mtelka** [comment]
No, but I expect it will solve the issue.

**Comment by TippyFlitsUK** [comment]
Would you be able to give it a try and report back @mtelka?

Many thanks!!

**Comment by shotcollin** [comment]
Hi @TippyFlitsUK - is this continuous logging of warnings for removed sectors the expected behavior for any/all sectors that have been removed? Maybe I hadn't noticed it before b/c I didn't have as many removed sectors, but now my lotus logs are filling up with these warnings, which are printed once every 60 seconds, one for each removed sector. Before I set the log level to error for rpc messages, my daemon log file was growing by almost 1GB per day.

**Comment by TippyFlitsUK** [comment]
Hey @shotcollin 

These log entries appear when running `lotus-miner sectors list`. It looks like you are seeing this repeat every 60s so that would indicate you are maybe running the command with `watch` or with a dashboard such as Farcaster.

You can limit these repeated log entries by running [partition compaction](https://lotus.filecoin.io/storage-providers/operate/daily-chores/#compacting-partitions).
