### ISSUE TITLE
gas used of SubmitWindowPoSt message has significantly increased and batching in one is much expensive than splited messages

### ISSUE THREAD

**Issue by joyceqingling** [filecoin-project/lotus#8983]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.16.0+mainnet+git.01254ab32
```

### Describe the Bug

I notice a miner with 7 partions in a deadlines, the SubmitWindowPoSt gas used has increased from 24,910,764 before FVM to 323,538,305 post FVM, which means the one SubmitWindowPoSt message costs nearly 12.9 times now. To my surprise, if one send one SubmitWindowPoSt only with one partition, it seems the gas will be much cheaper. The total cost would be almost half of the message contains 7 partitions. I think it is not reasonable or common sense, since batching all the things in just one message should be cheaper than 7 seperate messages. Should it be a system defect or something? 

### Logging Information

```text
No need to put logs
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by Stebalien** [comment]
Are you comparing _identical_ window posts? Any window post that recovers power will be significantly more expensive than a window post that doesn't, so if the first (batched) window post was recovering power, it should be significantly more expensive.

Can you link to the specific messages you're looking at?
