### ISSUE TITLE
It has been running for a day, why is it still 201

### ISSUE THREAD

**Issue by ocean00** [filecoin-project/lotus#899]
worker 1:
        Base:   [bafy2bzaceaxxuwhafbawu73j4byhp7h5lrblgdhoja2eiljpweujoj5lwf5cc]
        Target: [bafy2bzaceavqop4ty4fzv2bkoq2mb4zw52yvkm2byeglntpltvrwsomfhtp2m
bafy2bzacedhxnc5hfvhokje6opuah3o253hsshw4qjc3mfwzsajodiwhhi4ky] (1977)
        Height diff:    1977
        Stage: message sync
        Height: 201
        Elapsed: 17m59.722215519s

**Comment by magik6k** [comment]
What's your `lotus version`? Does updating to master help?

**Comment by ocean00** [comment]
work@test:~$ lotus -v
lotus version 0.1.1+gitd4902dde
work@test:~$

**Comment by ocean00** [comment]
worker 1:
        Base:   [bafy2bzaceaxxuwhafbawu73j4byhp7h5lrblgdhoja2eiljpweujoj5lwf5cc]
        Target: [bafy2bzaced2hoqsu7uzfitwpczaooq7xqri67mv57ephenzu3ohi4t6l7dtok]
 (5114)
        Height diff:    5114
        Stage: message sync
        Height: 201
        Elapsed: 32m27.618064337s

**Comment by ocean00** [comment]
work@test:~$ lotus -v
lotus version 0.1.1+gitd187161d

**Comment by ocean00** [comment]
I have updated and still stopped at 201

worker 1:
Base: [bafy2bzaceaxxuwhafbawu73j4byhp7h5lrblgdhoja2eiljpweujoj5lwf5cc]
Target: [bafy2bzaced2hoqsu7uzfitwpczaooq7xqri67mv57ephenzu3ohi4t6l7dtok]
(5114)
Height diff: 5114
Stage: message sync
Height: 201
Elapsed: 32m27.618064337s

work@test:~$ lotus -v
lotus version 0.1.1+gitd187161d
