### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by LesnyRumcajs** [filecoin-project/lotus#9000]
A bunch of links in the [README](https://github.com/filecoin-project/lotus/blob/master/README.md) seem to be broken, e.g at the bottom of the page:
> You should now have Lotus installed. You can now [start the Lotus daemon and sync the chain](https://docs.filecoin.io/get-started/lotus/installation/#start-the-lotus-daemon-and-sync-the-chain)

results in
```
ipfs resolve -r /ipfs/bafybeidrc4quytdmhtkg7f2xwbvvcfkrlmtfsgtt7mnhabhip5ilto4ph4/get-started/lotus/installation/: no link named "lotus" under QmUbRyoiek6GiVTCANK9oEqaf7wRy31rBpwx3pryRq9TTm
```

Same goes for others, like:
https://docs.filecoin.io/get-started/lotus/configuration-and-advanced-usage/
https://docs.filecoin.io/get-started/lotus/installation/#build-and-install-lotus
https://docs.filecoin.io/get-started/lotus/tips-running-in-china/
https://docs.filecoin.io/get-started/lotus/switch-networks/

**Comment by TippyFlitsUK** [comment]
Hi @LesnyRumcajs 

There is an open PR pending review that will address all these broken links - https://github.com/filecoin-project/lotus/pull/8966

Many thanks for your feedback!!
