### ISSUE TITLE
Adaptive SectorChallengeRatio

### ISSUE THREAD

**Issue by steven004** [filecoin-project/lotus#901]
# Description: 
This is a request. Currently the `SectorChallengeRatioDiv` is defined as a constant `25`, which will need too much IO access when a miner has thousands of sectors, or more, especially, when generate_candidates is required to complete in a very short time. Remember that the block time is the same for everyone. 

It is suggested to let SectorChallengeRatio be adaptive to sectorNumbers, and also it is good to set a min and max number of challenge count.

**Comment by whyrusleeping** [comment]
@steven004 it is critical to the security of the protocol that this cost linearly to the number of sectors the miner has.

**Comment by steven004** [comment]
Remember that the more a miner has sectors, the more chances to do proving.
Otherwise, the miner gets less reward.

This makes it fair.
