### ISSUE TITLE
Starting local network node failed using `experimental/fvm-m2` branch

### ISSUE THREAD

**Issue by Taction** [filecoin-project/lotus#9011]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
N/A.
```

### Describe the Bug

I want to set up a Lotus devnet and follow the instruction: https://lotus.filecoin.io/developers/local-network/.
I checkout the lotus to experimental/fvm-m2 branch, everything works well until I [start the node](https://lotus.filecoin.io/developers/local-network/#start-the-nodes) with command ./lotus daemon --lotus-make-genesis=devgen.car --genesis-template=localnet.json --bootstrap=false. Here is the output of this command:
```
2022-07-11T16:13:42.067+0800	INFO	badgerbs	v2@v2.2007.3/value.go:1158	Replaying file id: 0 at offset: 0

2022-07-11T16:13:42.135+0800	INFO	badgerbs	v2@v2.2007.3/value.go:1178	Replay took: 67.207434ms

2022-07-11T16:13:42.135+0800	WARN	chainstore	store/store.go:222	no previous chain state found
2022-07-11T16:13:42.136+0800	WARN	genesis	testing/genesis.go:57	Generating new random genesis block, note that this SHOULD NOT happen unless you are setting up new network
init set t3w4hhsho7y7z3necvd3c3s2e4vg57j7filjsqshjvaff27zsn6vu24spufj24um72feuc5pvverkmjwy7ewnq t0100
init set t1ceb34gnsc6qk5dt6n7xg6ycwzasjhbxm3iylkiy t0101
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
2022-07-11T16:13:52.069+0800	INFO	basichost	basic/natmgr.go:84	DiscoverNAT error:no NAT found
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/root/github/ipfs/lotus-local-net/node/modules/lp2p/addrs.go:85): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:30): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:30): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:30): failed to build dtypes.AfterGenesisSet: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:30): genesis func failed: make genesis block: setup miners failed: failed to create genesis miner: doExec apply message failed: applying msg: failed to lookup actor f3w4hhsho7y7z3necvd3c3s2e4vg57j7filjsqshjvaff27zsn6vu24spufj24um72feuc5pvverkmjwy7ewnq

Caused by:
    Serialization error for Cbor protocol: RequireLength { name: "tuple", expect: 3, value: 4 }
```

### Logging Information

```text
N/A
```

### Repo Steps

1. Create the following environment variable in your terminal:
```
export LOTUS_PATH=~/.lotus-local-net
export LOTUS_MINER_PATH=~/.lotus-miner-local-net
export LOTUS_SKIP_GENESIS_CHECK=_yes_
export CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
export CGO_CFLAGS="-D__BLST_PORTABLE__"
```
2. Clone Lotus repo
```
git clone https://github.com/filecoin-project/lotus lotus-local-net
cd lotus-local-net
```
3. Checkout to the latest branch and build
```
git checkout -b fvm-m2 origin/experimental/fvm-m2
rm -rf ~/.genesis-sectors
make 2k
```
4. generate genesis info
```
./lotus fetch-params 2048
./lotus-seed pre-seal --sector-size 2KiB --num-sectors 2
./lotus-seed genesis new localnet.json
./lotus-seed genesis add-miner localnet.json ~/.genesis-sectors/pre-seal-t01000.json
```
5. Start the nodes and encounters the error
```
./lotus daemon --lotus-make-genesis=devgen.car --genesis-template=localnet.json --bootstrap=false
```

**Comment by hunjixin** [comment]
i have this issue too

**Comment by yzuyhp** [comment]
root@3d40b2dcc66c:/lotus# ./lotus daemon --lotus-make-genesis=devgen.car --genesis-template=localnet.json --bootstrap=false
init set t3ugdxqdkcvx3l3ovmalvfdu2rrm26vj3qwh6o6hksk2kuj3xg52256woxrzfeawk3xacuf52akxfirs2lvy2a t0100
init set t1ceb34gnsc6qk5dt6n7xg6ycwzasjhbxm3iylkiy t0101
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/lotus/node/modules/lp2p/addrs.go:85): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build dtypes.AfterGenesisSet: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): genesis func failed: make genesis block: setup miners failed: failed to create genesis miner: doExec apply message failed: applying msg: failed to lookup actor f3ugdxqdkcvx3l3ovmalvfdu2rrm26vj3qwh6o6hksk2kuj3xg52256woxrzfeawk3xacuf52akxfirs2lvy2a

Caused by:
    Serialization error for Cbor protocol: RequireLength { name: "tuple", expect: 3, value: 4 }

**Comment by Tom-OriginStorage** [comment]
Tried creating on most recent commit and face this error too
