### ISSUE TITLE
sealing pipeline: Support importing (partially) sealed sectors

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#9012]
This is a feature needed by things like external sealing services.

We should add some new APIs to lotus-miner which would make it possible to import sector data and metadata in any state.

This would enable a lot of new alternative sealing architectures - for example making it possible to offload PC1/2 compute to an external service, ship sector data to the miner before any (Commit/PreCommit) messages are sent to the chain, and let the miner handle the remaining sealing steps (sending chain messages, running Commit1/2 (possibly using external snarking service for PoRep))

Example architecture:
![sealing-service](https://user-images.githubusercontent.com/3867941/178242370-4dfc56eb-4354-436c-9e9a-7b80fd21e227.png)

**Comment by ImmanuelSegol** [comment]
@magik6k [magik6k](https://github.com/magik6k) Is this new architecture being worked on now?

**Comment by jennijuju** [comment]
> 

not atm. We will pick this up maybe, later in Q3

**Comment by jennijuju** [comment]
can close now?
