### ISSUE TITLE
Filecoin.MarketListIncompleteDeals must be ran on Markets, is not forwarded by miner

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#9022]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.16.1 + split markets
```

### Describe the Bug

Running `Filecoin.MarketListDeals` on the Miner API works.
Running `Filecoin.MarketListIncompleteDeals` on the Miner API returns 
```
fatal error calling 'Filecoin.MarketListIncompleteDeals': panic in rpc method 'Filecoin.MarketListIncompleteDeals': runtime error: invalid memory address or nil pointer dereference
```

Running `Filecoin.MarketListDeals` on the Markets API returns 
```
fatal error calling 'Filecoin.MarketListDeals': panic in rpc method 'Filecoin.MarketListDeals': runtime error: invalid memory address or nil pointer dereference.
```
Running `Filecoin.MarketListIncompleteDeals` on the Markets API works

Also, (probably because Bidbot is using it), the miner log is filled with the nil pointer dereference errors, and bidbot possibly doesn't work right.

This probably happened somewhere around v1.15.3 -> 1.17.0 / 1.16.0

**Comment by rjan90** [comment]
Closing this ticket as the legacy lotus-miner markets subsystem has been deprecated.
