### ISSUE TITLE
lotus client ls --allowLocal=true does not work

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#9023]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.16.1
```

### Describe the Bug

--allowLocal flag does not work for `client ls`

### Logging Information

Local miner = f01392893
```shell
master@daemon:~$ lotus client ls --allow-local=true --pieceCid baga6ea4seaqjkxqtmdyxgxscqqld6ycpm4vhy5bypwvri4tlya2dspay2kdhabq QmU6CzcU6PYyhFCtkryVv6AL5mnrCSekHZU6ReAXw93g2w
Failed to find file

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1a3f03e]

goroutine 1 [running]:
github.com/filecoin-project/lotus/cli.glob..func36(0xc00083b540)
	/home/master/lotus-source/cli/client_retr.go:522 +0x85e
github.com/urfave/cli/v2.(*Command).Run(0x99682a0, 0xc00083b200)
	/home/master/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000602b60, 0xc00083af00)
	/home/master/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:434 +0x9a6
github.com/urfave/cli/v2.(*Command).startApp(0x99683c0, 0xc00083af00)
	/home/master/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x713
github.com/urfave/cli/v2.(*Command).Run(0xc0008994a0, 0x7fffffffe3d8)
	/home/master/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0x7bc
github.com/urfave/cli/v2.(*App).RunContext(0xc000602820, {0x4aa3270, 0xc0000520c0}, {0xc00004e070, 0x7, 0x7})
	/home/master/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
	/home/master/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/filecoin-project/lotus/cli.RunApp(0x3924b20)
	/home/master/lotus-source/cli/helper.go:35 +0x4e
main.main()
	/home/master/lotus-source/cmd/lotus/main.go:111 +0x8ec
```

```shell
master@daemon:~$ lotus client ls --provider=f01392893 --pieceCid baga6ea4seaqjkxqtmdyxgxscqqld6ycpm4vhy5bypwvri4tlya2dspay2kdhabq QmU6CzcU6PYyhFCtkryVv6AL5mnrCSekHZU6ReAXw93g2w
Recv 0 B, Paid 0 FIL, Open (New), 0s [1657407151274525390|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 1ms [1657407151274525390|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 17ms [1657407151274525390|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 17ms [1657407151274525390|0]
Recv 5.618 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 280ms [1657407151274525390|5753]
Recv 5.618 KiB, Paid 0 FIL, AllBlocksReceived (BlocksComplete), 280ms [1657407151274525390|5753]
Recv 5.618 KiB, Paid 0 FIL, Complete (CheckComplete), 281ms [1657407151274525390|5753]
Recv 5.618 KiB, Paid 0 FIL, CompleteVerified (FinalizingBlockstore), 281ms [1657407151274525390|5753]
Recv 5.618 KiB, Paid 0 FIL, BlockstoreFinalized (Completed), 281ms [1657407151274525390|5753]

QmQraen57D6Tgr4xY27D9ct1sRZnBGyYtauAJuKPpUnZRD ethereum2.validators.000000007397.json.0001	68024615
QmNTjAM9g2XEzdzwJQG4pKkJB9eu7pXyK3ZcuNNhbpq4Kg ethereum2.validators.000000007398.json	223620190
QmWJhjYtSshUTkVqekJ7virgHG4suuUgPYydAFjtfVMgAA ethereum2.validators.000000007399.json	223321455
(....)
```

**Comment by RobQuistNL** [comment]
This was @magik6k 's work (nice one BTW mate, this is awesome stuff) but if someone else wants to fix it, the issue is in here;

https://github.com/filecoin-project/lotus/blob/master/cli/client_retr.go#L482-L593

**Comment by TippyFlitsUK** [comment]
Hi @RobQuistNL 

Thanks for the report. I will add labels and assign it to the right team for analysis.
We might tag you again for more information.

🙏

**Comment by rjan90** [comment]
Closing this ticket as the Legacy Lotus/Lotus-Miner Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and is being completely removed from the code here:

- https://github.com/filecoin-project/lotus/pull/11999
- https://github.com/filecoin-project/lotus/pull/12005
