### ISSUE TITLE
Feat rq: Add the abilty to rescan storage locations for sectors 

### ISSUE THREAD

**Issue by marshyonline** [filecoin-project/lotus#9024]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

When moving sectors from one storage to the next, a miner or worker restart is required to redeclare these sectors.
This can be a burden when in production and building sectors. 

### Describe the solution you'd like

Add a command to the miner/worker to rescan and redeclare/undeclare sectors that may have been moved around avoiding miner or worker restarts
eg: `lotus-[miner/worker] storage rescan $storage_id`

**Comment by rjan90** [comment]
Hey @marshyonline! This is a great idea, and a similar feature request was recently created by magik in #9019 as it will be nice to have when https://github.com/filecoin-project/lotus/pull/9013 gets merged 😄. So I think this feature might be implemented quite fast.

Closing this feature request as it´s a duplicate.
