### ISSUE TITLE
lotus daemon ,  Data path can be specified ?

### ISSUE THREAD

**Issue by wangbb-aaa** [filecoin-project/lotus#903]
lotus daemon ,  Data path can be specified ?
Value:  my path ,

exp：
	app := &cli.App{
		Name:    "lotus",
		Usage:   "Filecoin decentralized storage network client",
		Version: build.UserVersion,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "repo",
				EnvVars: []string{"LOTUS_PATH"},
				Hidden:  true,
				Value:   "~/.lotus", // TODO: Consider XDG_DATA_HOME
			},
		},

		Commands: append(local, lcli.Commands...),
	}

**Comment by magik6k** [comment]
You can either start the daemon with LOTUS_PATH env var set:
```
LOTUS_PATH="somePath" lotus daemon
```
Or by specifying the repo flag:
```
lotus --repo="somePath" daemon
```
