### ISSUE TITLE
How to solve the problem of running nodes

### ISSUE THREAD

**Issue by coder-chenda** [filecoin-project/lotus#9030]
<img width="1576" alt="image" src="https://user-images.githubusercontent.com/83049018/178765475-61238b20-c218-4bff-8e4f-5fb015cdb1a6.png">

**Comment by coder-chenda** [comment]
> IPFS_GATEWAY=https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/

Hello, it seems that the error is still the same

**Comment by rjan90** [comment]
Hey @coder-chenda! Did you manage to download the proof-params correctly? If not, can you try again with `IPFS_GATEWAY=https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/` set?
