### ISSUE TITLE
1.16.0 掉算力之后，之后我的节点不再释放锁仓的币了

### ISSUE THREAD

**Issue by haheihou5** [filecoin-project/lotus#9045]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

升级1.16.0之后，我的节点掉算力48小时，之后由于数据丢失的问题，我终结了非常多的扇区，大约270个32G的CC扇区，
当故障排除并终结掉所有故障扇区后，现在我的节点不再从vesting中释放币到可用余额，我也无法查看未来的释放计划或者列表

我的节点号是f01390330
FVM升级之后甚至还未爆一个块。。

我希望可以查看lotus-miner vesting
能够返回一个未来fil的释放列表或者计划，
现在我该怎么办？我的go版本是1.82.1，lotus版本是1.16.0mannet

**Comment by haheihou5** [comment]
go版本1.18.2，是输入错误了

**Comment by beck-8** [comment]
我觉得你在胡扯

**Comment by haheihou5** [comment]
> 
忘了说了，在升级FVM版本之前，在另一台机器上进行过lotus-miner restore /backup 并 lotus-miner run过，但是节点依然在之前的节点机器上继续运行，新的计算机只是作为了一个备用机，并没有持续运行miner

**Comment by beck-8** [comment]
你终止的扇区是不是有datacap ？

**Comment by haheihou5** [comment]
含有1-2个datacap，所以会导致什么后果？

**Comment by beck-8** [comment]
我看了两天的数据，确实没有释放。
我怀疑你终结的扇区有datacap，链上处理有BUG，数据没有正确处理。
现在你看到还有211左右未释放，其实是已经没了，所以不释放。

**Comment by haheihou5** [comment]
个别的datacap终止会导致款项全部被罚没吗？除非我现在再爆新块，是这个意思吗？

**Comment by haheihou5** [comment]
请问我现在应该如何处理？

**Comment by beck-8** [comment]
你终结的扇区只有几个有datacap，还是每个扇区当中都有1-2个datacap？
如果只有几个，应该不会有这么大的影响。
以上是我的猜测，我也没有证据去说明，而且现在actor那边增加日志几乎没法做，所以你只能求助官方看看吧。

**Comment by beck-8** [comment]
> 个别的datacap终止会导致款项全部被罚没吗？除非我现在再爆新块，是这个意思吗？

我觉得你再新爆块，就会正常释放。

**Comment by haheihou5** [comment]
大多数是cc 其中 总共只有1-2个 32G的datacap，目前FVM版本之后，一直没爆块，总觉得是有隐式的错误导致不释放也不爆块，所以我现在把节点迁移到了新的机器，使用官方推荐的go版本1.17.9，现在版本是1.17.0rc-3,期待能解决吧

**Comment by beck-8** [comment]
够呛，用英文问下官方吧

**Comment by beck-8** [comment]
共识问题，不是你升级个版本就能解决的

**Comment by haheihou5** [comment]
我找到了一个类似帖子
https://github.com/filecoin-project/lotus/discussions/6032
说是罚款并更改了付款列表，推迟了，但是我用这个命令返回的值我看的不清楚，类似的情况大家自己试试吧

**Comment by haheihou5** [comment]
![be86a4d1e1e02c2634831d56f66dfb7](https://user-images.githubusercontent.com/54048258/179347377-d6320af7-1caf-4e6e-9417-45cc855b6a1f.png)
查了一下，返回值不是他说的列表，看不明白
顺便看了一下miner状态
![d9f9da2034c487e386377b5cb104ada](https://user-images.githubusercontent.com/54048258/179347378-995a277d-1ae4-4105-9aa9-debc671cbb57.jpg)
不知道这个-1值是正常还是不正常

**Comment by jennijuju** [comment]
`lotus state read-state` gives you the vesting schedule, you can pass in the @tipset and see when it changed 

given that you have faults for a couple days 
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/42981373/179364729-401fd3ac-fbaa-4801-84d6-ca3337344942.png">


so penalties definitely are being charged for you faulted sectors, and the penalties are taken from the locked funds/reward first.

**Comment by beck-8** [comment]
@jennijuju  
How to check this `lotus state read-state ` result please
I understand being fined. But the current situation is that his lock position has not been released, what is going on?It is not simply that the available balance has not increased.

>I don't have this problem, I'm just curious about this situation,hhh
