### ISSUE TITLE
InvocResult not returning all Subcalls

### ISSUE THREAD

**Issue by Schwartz10** [filecoin-project/lotus#9046]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
This is occurring on the public Glif API nodes running v1.16.0
```

### Describe the Bug

Calling `StateCall` through the JSON RPC is not returning all Subcalls as I would expect it to (I think this may have changed in the latest network upgrade).

My specific example:
- Create a multisig with 2 signers, 1 NumApprovalsThreshold
- Call `StateCall` with a `Propose` to `RemoverSigner`, setting `Decrease: true` (which should fail to apply)
- Observe that `Subcalls` is `null` when I would expect to see the internal `RemoveSigner` message with a non-zero `ExitCode`

Example curl command for StateCall ^^ is in the repro steps section below

The Glif `filecoin-wallet-provider` package has a test for our `SimulateMessage` function, which catches a bad transaction, and then doesn't allow the user to send the message. We call `StateCall` and inspect all the Subcalls for non-zero exit codes. Recently our tests for `SimulateMessage` started failing on a transaction similar to the one referenced above. However, I'm not 100% sure they started failing _because of_ the network upgrade?

### Logging Information

```text
See below
```

### Repo Steps

StateCall:

```
curl --location --request POST 'https://calibration.node.glif.io/rpc/v0' \
--header 'Content-Type: application/json' \
--data-raw '{
"jsonrpc": "2.0",
"method": "Filecoin.StateCall",
"id": 1,
"params": [{"To":"t2kn7ej2p6zmd5mufcrjrjibccm5wxacsl2vgnd6a","From":"t13koa6kz5otquokcgwusvtsxcdymuq7lqe4twb4i","Nonce":25,"Value":"0","Method":2,"Params":"hFUCU35E6f7LB9ZQoopilARCZ21wCktABlgYglUBXQYmzqyEVUgkEgoyAL2D6qACCPf1"}, null]
}
'
```

**Comment by jennijuju** [comment]
are you sure that glif node has the enable trace on? https://github.com/filecoin-project/lotus/blob/e950421e8793bc05d828b183172143c9b7b388bf/CHANGELOG.md?plain=1#L77

**Comment by Schwartz10** [comment]
Ahhh sorry @jennijuju this sounds very much like the culprit.

@ArseniiPetrovich do you know if `LOTUS_VM_ENABLE_TRACING` is set to `true` on the public API nodes?
