### ISSUE TITLE
sync error

### ISSUE THREAD

**Issue by IPSE-TEAM** [filecoin-project/lotus#905]
Worker 2: Target: [bafy2bzaceahdzchpce6pyow7diofio7pqznerdxwt3h423lkqg27bv3drxaf2]	State: error	Height: 3489

**Comment by IPSE-TEAM** [comment]
I just reboot the OS solved the problem.WTF.

**Comment by IPSE-TEAM** [comment]
why need so much params data?

**Comment by sedasdas** [comment]
i canot solve it
