### ISSUE TITLE
failed to remove partitions from deadline 45: partition index 4 out of range [0, 4)

### ISSUE THREAD

**Issue by dispensable1988** [filecoin-project/lotus#9065]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.16.1+mainnet+git.bedc107.dirty+api1.5.0
Local: lotus version 1.16.1+mainnet+git.bedc107.dirty
```

### Describe the Bug

When there are more than 4 partitions in deadline,  compact-partitions will fail

### Logging Information

```text
ERROR: mpool push: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: message failed with backtrace:
00: (method 19) -- failed to remove partitions from deadline 45: partition index 4 out of range [0, 4) (16)
(RetCode=16)
```

### Repo Steps

lotus-miner sectors compact-partitions --deadline 45 --partitions 4 --really-do-it

**Comment by dispensable1988** [comment]
@rjan90 I compact many partitions in different deadline, but all encountered the same error
**before compact:**
`lotus-miner proving deadline 47
Deadline Index:           47
Partitions:               6
Proven Partitions:        0
Current:                  false

Partition Index:          0
Sectors:                  2349

**after compact:**
`lotus-miner proving deadline 47 
Deadline Index:           47
Partitions:               4
Proven Partitions:        0
Current:                  false

Partition Index:          0
Sectors:                  2349
`


`lotus-miner sectors compact-partitions --deadline 47 --partitions 0 --really-do-it
compacting 1 paritions
Requested compact partitions in message bafy2bzaceaeazmflpvcw3kar2lm2kuqml22hpynlnjgz76oij3az4lbdmkqba
lotus-miner sectors compact-partitions --deadline 47 --partitions 1 --really-do-it
compacting 1 paritions
Requested compact partitions in message bafy2bzacebtxxtu4gksb6zqgzqgvjyxh5umjqyw37yjglgwxq7fvuw6a5udue
lotus-miner sectors compact-partitions --deadline 47 --partitions 2 --really-do-it
compacting 1 paritions
Requested compact partitions in message bafy2bzacebuys27sbb5rkympltsiym4kf7y2f5plruvpc7ojc3c3pszoqt6fw
lotus-miner sectors compact-partitions --deadline 47 --partitions 3 --really-do-it
compacting 1 paritions
Requested compact partitions in message bafy2bzacedv74y5rt55kaqf25jox5tscbhjxhrpoiesz3tx4ulkqrk7j25mve
lotus-miner sectors compact-partitions --deadline 47 --partitions 4 --really-do-it
compacting 1 paritions
ERROR: mpool push: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: message failed with backtrace:
00:  (method 19) -- failed to remove partitions from deadline 47: partition index 4 out of range [0, 4) (16)
 (RetCode=16)
lotus-miner sectors compact-partitions --deadline 47 --partitions 5 --really-do-it
compacting 1 paritions
ERROR: mpool push: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: message failed with backtrace:
00: (method 19) -- failed to remove partitions from deadline 47: partition index 5 out of range [0, 4) (16)
 (RetCode=16)
`

**Comment by rjan90** [comment]
@dispensable1988 I might be missing something here:

> after compact:
> lotus-miner proving deadline 47
> Deadline Index: 47
> Partitions: 4
> Proven Partitions: 0
> Current: false
> 
> Partition Index: 0
> Sectors: 2349

But if this is your current proving deadline 47, it seems like you only have 4 partitions in that deadline. Which explains why every command `lotus-miner sectors compact-partitions --deadline 47 --partitions x --really-do-it` where you set --partitions to 4 or higher fails, because your current Partition Index is like this?

```
Partition Index: 0 ------> Partition 1
Partition Index: 1 ------> Partition 2
Partition Index: 2 ------> Partition 3
Partition Index: 3 ------> Partition 4
```
