### ISSUE TITLE
Window PoSt Failed: coordinate(s) do not lie on the curve

### ISSUE THREAD

**Issue by xiaoliuxiao6** [filecoin-project/lotus#9080]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
GeForce RTX 3090
AMD EPYC 7542 32-Core Processor


lot[23:34:49 root@zz-miner-01 ~ $]lotus -v
lotus version 1.16.0+mainnet+git.01254ab32.dirty

[23:34:52 root@zz-miner-01 ~ $]lotus-miner -v
lotus-miner version 1.16.0+mainnet+git.01254ab32.dirty
[23:34:54 root@zz-miner-01 ~ $]
```

### Describe the Bug

GeForce RTX 3090
AMD EPYC 7542 32-Core Processor

lot[23:34:49 root@zz-miner-01 ~ $]lotus -v
lotus version 1.16.0+mainnet+git.01254ab32.dirty

[23:34:52 root@zz-miner-01 ~ $]lotus-miner -v
lotus-miner version 1.16.0+mainnet+git.01254ab32.dirty
[23:34:54 root@zz-miner-01 ~ $]

### Logging Information

```text
2022-07-24T23:17:33.166+0800    INFO    storageminer    storage/wdpost_run.go:664   computing window post   {"batch": 0, "elapsed": 123.663133869, "skip": 0, "err": "not on curve"}
2022-07-24T23:17:33.166+0800    ERROR   storageminer    storage/wdpost_run.go:666   error generating window post: not on curve
2022-07-24T23:17:33.166+0800    ERROR   storageminer    storage/wdpost_run.go:100   runPoStCycle failed: running window post failed:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPoStCycle
        /root/v1.16.0/storage/wdpost_run.go:727
  - not on curve
```

### Repo Steps

GeForce RTX 3090

**Comment by PatHoo** [comment]
me too, all SubmitWindowedPoSt fail today, miner & lotus v1.16.0

**Comment by rjan90** [comment]
Hey @xiaoliuxiao6! The `error generating window post: not on curve` is usually a hardware issue, so I would recommend you run some hardware testing of the GPU and Memory. If it was some disk issues, it would have indicated it with: `I/O error: not on curve`

**Comment by TippyFlitsUK** [comment]
Hi @xiaoliuxiao6 

Have you had a chance to run the hardware testing that @rjan90 recommended?

Many thanks :pray:
