### ISSUE TITLE
lotus-miner actor compact-allocated performs check for arguments it doesn't need / strange error message

### ISSUE THREAD

**Issue by dd45e640b42e6da7da96faee3996ef7c** [filecoin-project/lotus#9091]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [] lotus miner/worker - sealing
- [] lotus miner - proving(WindowPoSt)
- [] lotus miner/market - storage deal
- [] lotus miner/market - retrieval deal
- [] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
master
```

### Describe the Bug

the command checks if args exist, even it doesn't use any of the args and then, if no args present,  logs 

`ERROR:  must pass address of new owner address`

please have a look at the code at

https://github.com/filecoin-project/lotus/blob/master/cmd/lotus-miner/actor.go#L1053-L1055

### Logging Information

```text
not needed

https://filecoinproject.slack.com/archives/CEGN061C5/p1659003538860849 as ref
```

### Repo Steps

1. Run `lotus-miner actor compact-allocated --mask-last-offset 1000  --really-do-it`

**Comment by rjan90** [comment]
Yeah, I can confirm that the `lotus-miner actor compact-allocated` command does not need the `address of new owner address` to just execute the command, and that you can just put in whatever value you want in there.

What needs to be understood is if a `new owner address` is actually needed for the command to properly function, and not just send a message without any meaning to the chain. And if there is an easy way to confirm that the passed value is a new owner address?

```
lotus-miner actor compact-allocated --really-do-it --mask-last-offset 10 123
CompactSectorNumbers Message CID: bafy2bzacedmzcz4fuuwl4r6uegyhna3p42i3inuu3v3xoq3fs3e7sdukgmvh2
```
