### ISSUE TITLE
integrate actor v10.0.0-alpha.1 bundles

### ISSUE THREAD

**Issue by raulk** [filecoin-project/lotus#9092]
There are now two extra bundles being produced from the `next` branch of `builtin-actors`:

- `devnet-wasm`
- `wallaby`

Using the `experimental/fvm-m2` branch as a base, we probably need two new branches:

- `experimental/devnet-wasm`
- `experimental/wallaby`

These two branches would integrate the respective bundles to allow spinning up nodes for the respective networks.

- `experimental/devnet-wasm`: local devnets, supporting Wasm actor installation.
- `experimental/wallaby`: [Wallaby testnet](https://github.com/filecoin-project/testnet-wallaby/), supporting Wasm actor installation.

Note: we need to test these bundles in the first place with the CLI commands under the `experimental/fvm-m2` branch.

**Comment by jennijuju** [comment]
v10? llol

note -  i prefer new network settings land in master (instead of having dedictaed network branch).

**Comment by arajasek** [comment]
> Using the experimental/fvm-m2 branch as a base, we probably need two new branches:

- experimental/devnet-wasm
- experimental/wallaby

@raulk Thoughts on landing both in `experimental/fvm-m2`? The devnet-wasm bundles will be used for local devnets, and Wallaby bundles for the Wallaby testnet.

The biggest reasons _not_ to would be:

- different versions (branches) of the FVM are needed to run these two bundles
- we think work on them will get tangled up, and need to be disentangled eventually (one needs to land in master before the other).

**Comment by raulk** [comment]
@arajasek landing them in the same branch is fine.

**Comment by arajasek** [comment]
sweet

**Comment by jennijuju** [comment]
we got a wallabynet jumping
