### ISSUE TITLE
The seal worker fetch data always broken pipe!

### ISSUE THREAD

**Issue by KIMQI001** [filecoin-project/lotus#913]
1.18 GiB / ? [-------=--------------------------] 12684165.12% 43.92 MiB/s 27s 
2019-12-14T11:16:12.681+0800	INFO	main	lotus-seal-worker/sub.go:77	Task 4 done, err: fetching sector:
    main.(*worker).processTask
        /home/zoe/go/src/github.com/filecoin-project/lotus/cmd/lotus-seal-worker/sub.go:100
  - fetch failed:
    main.(*worker).fetchSector
        /home/zoe/go/src/github.com/filecoin-project/lotus/cmd/lotus-seal-worker/transfer.go:144
  - malformed chunked encoding

**Comment by magik6k** [comment]
This code was rewritten multiple times since this issue was opened
