### ISSUE TITLE
wrong logs - node daemon dedicated string var reused for worker

### ISSUE THREAD

**Issue by dd45e640b42e6da7da96faee3996ef7c** [filecoin-project/lotus#9135]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Improvement Suggestion

https://github.com/filecoin-project/lotus/blob/b706efc33bd392d5be4f0be6679f8c5b23d98e26/node/repo/interface.go#L31

seems to be reused for the lotus worker (maybe the miner too)

resulting in a "wrong" error message

**Comment by rjan90** [comment]
Hey @f8-ptrk! When do you see this error pop up? When trying to run a second `lotus-worker ` on the same port?

**Comment by rjan90** [comment]
So it´s these lines:
https://github.com/filecoin-project/lotus/blob/0c91b0dc1012c3e54b305a76bb25fb68390adf9d/cmd/lotus-worker/main.go#L114-L117

**Comment by rjan90** [comment]
No, think that is more then enough 😄!

**Comment by Reiers** [comment]
Can confirm that the line` ("repo is already locked (lotus daemon already running)") ` are promted if the miner is forcefully shut down as well as lotus markets.
