### ISSUE TITLE
Missing the receipt for `lotus-miner actor withdraw`

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/lotus#9154]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus version 1.17.1-rc1+mainnet+git.98e1282a3
```

### Describe the Bug

Missing the receipt for `lotus-miner actor withdraw`

When the cmd is entered - it will still withdraw the funds wait 5 epochs, but no message in the shell (it just looks like it hangs when entered.)

Nothing breaks, just small UX thing.

### Logging Information

```text
The missing message(taken from v1.17.0):

Requested rewards withdrawal in message bafy2bzacealngp36t2x5iy7muvnjefjisot23gzvzg3bsxibf2gqseyiwve3y
waiting for 5 epochs for confirmation..
```
```


### Repo Steps

1. Run `lotus-miner actor withdraw`

**Comment by Reiers** [comment]
@geoff-vball the issue is still in `v1.17.1 ` stable - any idea what happen here? 
```
lotus version
Daemon:  1.17.1+mainnet+git.8db6a939c+api1.5.0
Local: lotus version 1.17.1+mainnet+git.8db6a939c
```

_because it works fine on `main/master` 🤔_

**Comment by geoff-vball** [comment]
We merged that change on August 11 but we cut the release branch for v1.17.1 on August 9 so it didn't make it. It will be in the next release :)
