### ISSUE TITLE
How to get approve transaction details by hash?

### ISSUE THREAD

**Issue by Wangmmx** [filecoin-project/lotus#9157]
Hi, I used to get the normal transfer type transaction details by `Filecoin.ChainGetMessage`, but in Approve transactions, I can not get the transfer body parameters, like from, to, amount ..., so I want to know how can to get the whole details?

txHash: bafy2bzacedmqmmj5d7wzic72itmst6fiufevdvh7uqz4w36mgxwqgh2r67iok(means messageId)
Look forward to your reply, thanks

**Comment by TippyFlitsUK** [comment]
Hi @Wangmmx 

Please use the [official templates](https://github.com/filecoin-project/lotus/issues/new/choose) to report any new issues or report bugs.

Many thanks!!
