### ISSUE TITLE
Allow lotus-worker to unseal sector even if does not store unsealed data long-term

### ISSUE THREAD

**Issue by geoff-vball** [filecoin-project/lotus#9159]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

Currently if a lotus-miner sends an unseal job to a lotus-worker, the job will fail unless the storage of the worker has the `store` flag for unsealed data set. This is because the worker tries to store the unsealed data long-term before sending it back to the miner, but this fails and the miner never gets the unsealed data. 

There are reasons the worker might not want to store unsealed data long-term, so we should allow the worker to store the data temporarily. The worker should be able to unseal the data, store it temporarily, send it back to the miner, then erase the unsealed data. 

In addition to this, when the worker returns the unsealed data to the miner, the miner should be able to choose whether to keep a copy of the unsealed data, or erase it after it is served to the client. We can do this with an env var.

Relevant slack discussion: https://filecoinproject.slack.com/archives/CP50PPW2X/p1660224454108749

**Comment by stuberman** [comment]
`the job will fail unless the storage of the worker has the store flag for unsealed data set`

I did try to set the sealing worker to 'store' in addition to 'seal' and then the long term sectors were being stored on the sealing worker and not in the lotus-miner long term storage repo.

**Comment by donkabat** [comment]
@geoff-vball the same problem

**Comment by arajasek** [comment]
@geoff-vball Can you add some links to code to this issue? I suspect it'll save whoever works on this a lot of time.

> Currently if a lotus-miner sends an unseal job to a lotus-worker, the job will fail unless the storage of the worker has the `store` flag for unsealed data set. This is because the worker tries to store the unsealed data long-term before sending it back to the miner, but this fails and the miner never gets the unsealed data.

- Where does this `store` flag live?
- Can you link where the `worker tries to store the unsealed data long-term` step happens?

**Comment by geoff-vball** [comment]
@shrenujbansal @arajasek 

The `store` flag lives in `sectorestore.json` in your `lotus-worker` path.

I don't exactly remember where the issue was in code. You should be able find it relatively easily by reproducing the issue.

Steps to repro: easy test: 
- have a miner & worker
- make deal
- delete unsealed data
- disable unsealing on miner
- trigger retrieval

Steps to set up worker: 
- Set up lotus daemon and miner as usual
- In a new tab: 
  - `export LOTUS_PATH=<path to your lotus folder>`
  - `export LOTUS_MINER_PATH=<path to your miner folder>`
  - `export LOTUS_WORKER_PATH="<make up this new path>"`
  - ulimit -n 200000

**Comment by arajasek** [comment]
Thanks @geoff-vball.

Per @magik6k, we _should_ be able to create an itest to demonstrate this issue, [here's a good blueprint](https://github.com/filecoin-project/lotus/blob/bc13fef81f37ef2fcfb3713ec0959838deb5c2a8/itests/worker_upgrade_test.go). @shrenujbansal can you give this a go? It might be a bit slower to write than doing the manual repro, but will give you a faster turnaround time as you 🕵️ (and give us a test for posterity).
