### ISSUE TITLE
ERROR handleSubmitReplicaUpdate

### ISSUE THREAD

**Issue by lbj2004032** [filecoin-project/lotus#9160]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner 1.16.0+mainnet+git.01254ab32.dirty
```

### Describe the Bug

sectors stauts ReplicaUpdateFailed

lotus@miner-172:/mnt/lotus1/.lotusminer$ lotus-miner sectors status 136973
SectorID:       136973
Status:         ReplicaUpdateFailed
CIDcommD:       baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq
CIDcommR:       bagboea4b5abcbg2vga74r4b2y4jnucuntcrxlikkiw3gkvyqx6wjc73p6wzr7c3b
Ticket:         bbc125bbea108611e499f27444e6b89554a6ef6ee932fe3b3f6957a89e0ea183
TicketH:        1938852
Seed:           16be9b0ed6955353fabec0eb56717cb6ba8e888bff902c9b0bcf1dc9b956f5d8
SeedH:          1940399
Precommit:      bafy2bzaceas4pwderzipmtf5a2ophtupslam3preiwf2dfozupa7ww3elza4u
Commit:         bafy2bzacecxfau7n6eutw4rzbgiyfp4d4spvabumvlanojzwqnckuhiokfrv4
Deals:          [8710113]
Retries:        0

### Logging Information

```text
handleSubmitReplicaUpdate2022-08-12T08:58:29.117+0800   ERROR   sectors storage-sealing/states_replica_update.go:174    handleSubmitReplicaUpdate: error sending message: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: message failed with backtrace:
00: f01715688 (method 27) -- failed to verify replica proof for sector 136967: invalid replica (16)
 (RetCode=16)
2022-08-12T08:58:31.111+0800    ERROR   sectors storage-sealing/states_replica_update.go:174    handleSubmitReplicaUpdate: error sending message: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: message failed with backtrace:
00: f01715688 (method 27) -- failed to verify replica proof for sector 136973: invalid replica (16)


config.toml

[Fees]
  MaxPreCommitGasFee = "0.025 FIL"
  MaxCommitGasFee = "0.05 FIL"
  MaxTerminateGasFee = "0.5 FIL"
  MaxWindowPoStGasFee = "5 FIL"
  MaxPublishDealsFee = "0.05 FIL"
  MaxMarketBalanceAddFee = "0.007 FIL"
  [Fees.MaxPreCommitBatchGasFee]
    Base = "0 FIL"
    PerSector = "0.02 FIL"
  [Fees.MaxCommitBatchGasFee]
    Base = "0 FIL"
    PerSector = "0.03 FIL"
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by TippyFlitsUK** [comment]
Hi @lbj2004032 

Thanks for the report. It looks like you are running Lotus with custom code or adjustment .`dirty`

Please upgrade to stock lotus, `make clean all` and let us know If the issue persists with new snap-up sectors. 

Thank you!

**Comment by Reiers** [comment]
@lbj2004032 
you could you please share the output of:
`lotus-miners sectors status --log 136973`
`lotus-miners sectors status --log 136967`

I dont think it is a Gas issue, `invalid replica (16)` - my suspicion,  something went wrong during sealing or the same deals got added to two different sectors and is in a state where it cant send the message twice.
