### ISSUE TITLE
 Miners have been running for a long time

### ISSUE THREAD

**Issue by chengwds** [filecoin-project/lotus#917]
root@cheng-ipfs:~# lotus-storage-miner info
Miner: t01378
Sector Size: 32 GiB
Power: 0 B / 74.4 TiB (0.0000%)
	Committed: 0 B
	Proving: 0 B
Worker use:
	Local: 1 / 4 (+1 reserved)
	Remote: 0 / 0
Queues:
	AddPiece: 0
	PreCommit: 0
	Commit: 0
	Unseal: 0
Proving Period: Not Proving
Sectors:  map[Total:1 Unsealed:1]

No one has access to data

**Comment by chengwds** [comment]
root@cheng-ipfs:~# lotus-storage-miner state power t01378
0

**Comment by magik6k** [comment]
Sealing 32G sectors can take a while, how long have you been running this?

**Comment by chengwds** [comment]
I'll try again

**Comment by chengwds** [comment]
root@cheng-ipfs:~# lotus-storage-miner info
Miner: t01378
Sector Size: 32 GiB
Power: 0 B / 74.4 TiB (0.0000%)
Committed: 0 B
Proving: 0 B
Worker use:
Local: 1 / 4 (+1 reserved)
Remote: 0 / 0
Queues:
AddPiece: 0
PreCommit: 0
Commit: 0
Unseal: 0
Proving Period: Not Proving
Sectors: map[Total:1 Unsealed:1]

Two days

**Comment by whyrusleeping** [comment]
have you run `lotus-storage-miner pledge-sector` ? your miner won't automatically do anything if you don't tell it to

**Comment by madper** [comment]
Howdy @whyrusleeping ,
I also found the 32G sector mode takes tons of diskio and time.
I'm using my messy PC: 3700x + 128G memory + nvme 2T *2 (with zfs) + 1080Ti *2
While after showing `2020-01-10T15:02:08.654+0800    INFO    storageminer    storage/sector_states.go:66     performing sector replication...        {"sector": 1}
`
The diskio keeps 3.2GB/s which is the upper bound of my disks:
![Screenshot from 2020-01-11 11-57-51](https://user-images.githubusercontent.com/451815/72198503-a0ab1b00-3469-11ea-98ba-95865aa213be.png)

Please may I know if it is normal. (I mean extreme high diskio for more than 20 hours.)
Also I found committing one 32G sector takes much more time than committing 32 1G sectors. Is that expected?

Thanks a lot in advance,
M

**Comment by whyrusleeping** [comment]
Hey @madper, probably want to file a new issue for this, but have you been able to run a 32GB lotus bench? continuous IO at those speeds seems very wrong, most of the replication process happens in memory, and only hits disk a (relatively) few times.

Do you have swap set up to that pool? Also how much ram do you have? If you have not enough ram, and thats your swap partition, then its likely youre just stuck in swapdeath.

**Comment by madper** [comment]
Hey @whyrusleeping ,
I have 128GB physics memory + 256G swap. 
According to the output of `free`, there are still numerous free memory space:
![Screenshot from 2020-01-11 17-32-32](https://user-images.githubusercontent.com/451815/72202328-11b5f700-3499-11ea-9d92-53e9d3387fd5.png)

And thanks for the advice, I will run 32G bench now.
BR,
M

**Comment by rosenjiang** [comment]
continuous concern

**Comment by taoyonggang** [comment]
Miner: t017111
Sector Size: 32 GiB
Power: 0 B / 1.95 PiB (0.0000%)
	Committed: 544 GiB
	Proving: 544 GiB
Worker use:
	Local: 2 / 4 (+1 reserved)
	Remote: 0 / 0
Queues:
	AddPiece: 0
	PreCommit: 0
	Commit: 0
	Unseal: 0
PoSt Submissions:
	Previous: Epoch 17614 (10663 block(s), ~7997m 15s ago)
	Fallback: Epoch 17644 (in 10693 blocks, ~8019m 45s)
	Deadline: Epoch 17814 (in 10863 blocks, ~8147m 15s)
Sectors:  map[Proving:17 Total:19 Unsealed:2]

**Comment by taoyonggang** [comment]
I am also that the power is 0.

**Comment by magik6k** [comment]
Please reopen a new issue if you still have problems, also, please include output of `lotus-storage-miner sectors list` / `lotus-storage-miner sectors status --log [sectorID]`
