### ISSUE TITLE
Sync UI bug for line wrap

### ISSUE THREAD

**Issue by NukeManDan** [filecoin-project/lotus#919]
Minor bug: the sync command (`lotus sync wait`) will flood the window if it wraps a line:

![image](https://user-images.githubusercontent.com/35669742/70855900-a411ad80-1e8f-11ea-8be3-e038ce170c79.png)

otherwise the line updates the block height on the same line just fine.

**Comment by magik6k** [comment]
This code lives in https://github.com/filecoin-project/lotus/blob/master/cli/sync.go#L148, if anyone wants to take stab at this all contributions are welcome
