### ISSUE TITLE
[M2] unknown method 2 for evm smart contract - log warn message

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/lotus#9199]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
experimental/fvm-m2 

https://github.com/filecoin-project/lotus/commit/94895fbdf0f7a970e3c4a1a111172d7ddfc50e12
```

### Describe the Bug

when invoking the smart contract the daemon logs:

`2022-08-22T15:41:32.011Z        WARN    fullnode        full/state.go:616       unknown method 2 for actor t01002`

```
[silicon-0] wallaby-keep-alive [~/genesis]$ lotus chain invoke-evm-actor t01002 f8b2cb4f 0000000000000000000000000000000000000000000000000000000000000065
sending message...
waiting for message to execute...
0000000000000000000000000000000000000000000000000000000000000000
```

see https://filecoinproject.slack.com/archives/C029MT4PQB1/p1661182618256529

### Logging Information

```text
the log is the "bug"
```

### Repo Steps

follow 

https://github.com/filecoin-project/testnet-wallaby/issues/2

see the daemon log

**Comment by vyzo** [comment]
yrah, we should either remove tgis log or downgrade it to DEBUG.
We'll fix it for the next wallaby release.
