### ISSUE TITLE
BlockSync should remove syncPeers when peer disconnects 

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#92]
Should be easy with libp2p eventbus

**Comment by whyrusleeping** [comment]
So, I thought we could close this, but i think theres some things that arent quite wired up. The peer manager gets passed into the blocksync client, but its then never really used. 

Relooking through this code, it seems like we're duplicating a good deal of tracking code here.

**Comment by arajasek** [comment]
@schomatis Hey, not sure if you have any insight into this, but do you think it might have been solved in the blocksync refactor?

**Comment by schomatis** [comment]
> @schomatis Hey, not sure if you have any insight into this, but do you think it might have been solved in the blocksync refactor?

No, the blocksync refactor (now chain exchange) didn't modify any of the peer tracking code (which I frankly don't really understand, I basically just moved the code to its own [file](https://github.com/filecoin-project/lotus/blob/2a294f048ac211d999ea6b044fe4412963901fe7/chain/exchange/peer_tracker.go#L3)).

I could take ownership of this but I would first need someone to work on the spec side to clearly document in detail how the different cases should be handled.
