### ISSUE TITLE
deal 

### ISSUE THREAD

**Issue by Superzhangs** [filecoin-project/lotus#921]
WARN	main	lotus/main.go:74	failed to start deal: connecting to storage provider failed: routing: not found

**Comment by hackervera** [comment]
I have something similar

vera@acer:~$ lotus client query-ask t02692
2019-12-15T18:52:32.443-0800	WARN	main	lotus/main.go:74	routing: not found

**Comment by whyrusleeping** [comment]
this means you can't connect to the miner youre trying to connect to, its probably behind a NAT
