### ISSUE TITLE
itests: 'unknown actor code' in block miner

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#9215]
(this seems to be causing good % of current flakiness)

Some tests are flaky due to not being able to load miner actor state. This is possibly due to some racy manifest-loading logic. 

The fix is potentially loading the manifest when constructing the ensemble, but some more digging is needed.

https://app.circleci.com/pipelines/github/filecoin-project/lotus/22759/workflows/0e0d87a2-9dd3-4fd1-be00-a6fa5e26ebb9/jobs/561727

```
2022-08-25T14:22:48.343Z	ERROR	miner	miner/miner.go:283	mining block failed: failed to create block:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /home/circleci/project/miner/miner.go:559
  - failed to get miner worker:
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).CreateBlock
        /home/circleci/project/chain/consensus/filcns/mine.go:35
  - (get sset) failed to load miner actor state:
    github.com/filecoin-project/lotus/chain/stmgr.GetMinerWorkerRaw
        /home/circleci/project/chain/stmgr/actors.go:43
  - unknown actor code bafk2bzacebucngwdhxtod2gvv52adtdssafyg43znsoy4omtfkkqe2hbhvxeu:
    github.com/filecoin-project/lotus/chain/actors/builtin/miner.Load
        /home/circleci/project/chain/actors/builtin/miner/miner.go:67
```

**Comment by rjan90** [comment]
Closing this ticket as outdated. Lotus has moved from CircleCI to GHA, and we are currently monitoring Flaky jobs over time in this [Grafana dashboard](https://ipdx.grafana.net/dashboard/snapshot/TfD5JfybgB0odLmipdZniNgayqr1zv3c?var-interval=1d&var-org=$__all&var-repo=$__all&var-branch=&var-workflow=&var-job=&var-label=&var-granularity=&var-limit=&from=now-7d&to=now).

We have also consolidated flaky test reports into a single tracking issue here: https://github.com/filecoin-project/lotus/issues/12001
