### ISSUE TITLE
nv17: Update go-state-types

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#9218]
This will be something of a living issue -- as we develop nv17, we will have various changes to go-state-types that we'll need to integrate into Lotus (eg https://github.com/filecoin-project/go-state-types/issues/52, https://github.com/filecoin-project/go-state-types/issues/53, https://github.com/filecoin-project/go-state-types/issues/54). 

Each integration will likely involve work to Lotus's state abstractions as well.

**Comment by jennijuju** [comment]
included in #9246
