### ISSUE TITLE
Potential Issue With the AutoPrune SpiltStore Feature in v1.17.1-rc3

### ISSUE THREAD

**Issue by TippyFlitsUK** [filecoin-project/lotus#9236]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.17.1-rc3+mainnet+git.079dab0d7
```

### Describe the Bug

TSEs are tracking a potential issue with the new  `EnableColdStoreAutoPrune` feature. 

Lotus is configured with the following settings:

 ```
[Chainstore]
  EnableSplitstore = true
  ColdStoreType = "universal"
  EnableColdStoreAutoPrune = true
```
We are currently not observing any noticeable automatic pruning of the chain taking place on Lotus nodes with `EnableColdStoreAutoPrune` enabled and `ColdStoreType` set to `universal`. This behaviour has been confirmed by multiple SPs currently taking part in SplitStore testing.

I have attached an hourly log of folder sizes for both `/.lotus/datastore/splitstore` and `/.lotus/datastore/chain` directories below dating back to 10th August 2022.

https://github.com/filecoin-project/lotus/files/9461826/splitstore.log

### Logging Information

```text
https://github.com/filecoin-project/lotus/files/9461826/splitstore.log
```

### Repo Steps

Set the following in `/.lotus/config.toml`:
 ```
[Chainstore]
  EnableSplitstore = true
  ColdStoreType = "universal"
  EnableColdStoreAutoPrune = true
```
Run Lotus daemon and monitor `/.lotus/datastore/chain` folder size.

**Comment by TippyFlitsUK** [comment]
Updated daemon logs below @ZenGround0 :pray:

https://drive.google.com/drive/folders/1z3RhhaywWZZeeV0dwFDE31tenksKu-5t?usp=sharing

**Comment by ZenGround0** [comment]
Unfortunately it looks like I miscommunicated the configuration 

It should be 

```
[Chainstore]
 EnableSplitstore = true
```

```
[Chainstore.Splitstore]
 ColdStoreType = "universal"
 EnableColdStoreAutoPrune = true
```

I'm not sure if lotus config is smart enough to match fields in the top level to matching fields in sublevels but I'm suspicious that it is not.  I think this would explain the behavior you are seeing because universal is the default coldstore type and false is the default for enabling auto prune of the cold store.

**Comment by jennijuju** [comment]
should we close this?

**Comment by TippyFlitsUK** [comment]
This is still happening even with the updated `config.toml` @jennijuju.

**Comment by TippyFlitsUK** [comment]
Updated logs taken after the `config.toml` update @ZenGround0 👍.

https://drive.google.com/drive/folders/1rxjPOt4otb4dSuZHBWen_rlvBPHnyqCM?usp=sharing

**Comment by mur-me** [comment]
Thanks for this feature guys, looking forward for this to use it! :heart:

**Comment by rjan90** [comment]
I think its fair to close this issue now @TippyFlitsUK given that `EnableColdStoreAutoPrune` has been deprecated?
