### ISSUE TITLE
As a member of the lotus community, I should be able to see aggregate, anonymous metrics about the number of downloads on each platfrom (Github Releases, Homebrew, Snapcraft, Docker Hub)

### ISSUE THREAD

**Issue by ianconsolata** [filecoin-project/lotus#9243]
"as a member of the lotus community" means that anyone interested should eventually be able to access this dashboard without authentication.

This will be done via a public Grafana dashboard displaying data from a mix of custom and off-the-shelf Prometheus Exporters. Each Exporter will pull data from a single place, and will be written in a way that other projects in the ecosystem should be able to reuse the same exporters for to monitor their release metrics.

**Comment by ianconsolata** [comment]
Finished up the first pass at a https://github.com/filecoin-project/homebrew-exporter and https://github.com/filecoin-project/snapcraft-exporter. These will be combined with https://github.com/infinityworks/github-exporter and https://github.com/infinityworks/docker-hub-exporter to give us a comprehensive picture of how many folks are downloading our releases on each platform, including Github, Docker Hub, Homebrew, and Snapcraft. That information will then be combined into a public grafana dashboard.

**Comment by ianconsolata** [comment]
Really? Do you have data on that I can check out?

**Comment by ianconsolata** [comment]
Why can't storage providers use the `lotus-miner` and `lotus-worker` binaries we build and include in our releases? That sounds like a serious problem for usability and onboarding of storage providers

Even so, our numbers for these platforms are high enough that a dashboard for these metrics will be useful. Not sure how many for those are storage providers compared to folks using lotus for other reasons. Not even sure how to track that?  Plus, the way I've built them they should be reusable by projects across the Filecoin ecosystem. Should have something to show off next week, I hope.

**Comment by ognots** [comment]
@ianconsolata the build process detects hardware and architecture, and optimizes the binary. I believe `blst` is one such dependency that requires this. 
it's mainly relevant to sealing sectors. using "unoptimized" binaries can mean the difference between 4h or 24h to seal a single 32GiB sector.
there is no known workaround, by my understanding.

**Comment by Kubuxu** [comment]
Yes, @ognots is correct, in essence, the inner loop of sealing code is highly optimised using CPU intrinsics, but we need to deliver binaries that run everywhere in our downloads. This is done by CPU feature detection and using the best code path available. Unfortunately, this results in a significant hit to the performance.

Also, we don't build with CUDA for the release binaries because that introduces a large runtime dependency only SPs find helpful.
In the case of blockchain projects, building from source is generally encouraged as it reduces the risk of supply chain attacks.

**Comment by ianconsolata** [comment]
Hmm. So we really should be pushing folks to compile themselves, rather than using the pre-built binaries. Let me noodle on how to best design the release process to support that. Do either of you know who would be a good person to schedule some time with to really dig into the `blst` / `hwloc` / architecture specific requirements of lotus sector sealing / storage providers? Having a deep dive with someone knowledgeable would help a lot to figure out all the requirements that need to be taken into consideration.

Sounds like this dashboard / metrics will mostly give us info on new folks trying out lotus, and folks using lotus-lite / lotus client nodes. That's still valuable information, since that is a critical step on the path to becoming a storage provider, but it sounds like there is a lot more on top of that we need to do to support their use cases.

**Comment by ianconsolata** [comment]
We can get around the dangers of supply chain attacks with singed binaries though, can't we?

**Comment by ognots** [comment]
building from source should not be the _only_ tangible option, IMHO.
there are many cases where a pre-built, optimized binary would be beneficial.

**Comment by Kubuxu** [comment]
> We can get around the dangers of supply chain attacks with signed binaries though, can't we?

Yes and no, the danger is the single point of building the binary.

> So we really should be pushing folks to compile themselves, rather than using the pre-built binaries

We already share that information with SPs in the docs. It doesn't affect people who are running full nodes to have access to the network as much.

> Do either of you know who would be a good person to schedule some time with to really dig into the blst / hwloc / architecture specific requirements of lotus sector sealing / storage providers?

**Comment by Kubuxu** [comment]
Re blst, hwloc, arch. The important points are, afaik, ADX, SHA intrinsic and some vector intrinsic. hwloc is used to optimize scheduling, treat it as dependency and the proofs code will do the best it can.

The reason that natively built binaries are also faster is that vector intrinsics moved forward a lot over the years, unfortunately, we have to deliver binaries that will run everywhere which means using a subset of them.

**Comment by ianconsolata** [comment]
First draft of this dashboard is live: https://protocollabs.grafana.net/d/lbNX6PVVk/lotus-release-metrics?orgId=1&from=now-7d&to=now

Unfortunately, it's not possible to make it public as I originally hoped. So far, I've had requests for to add support for:
- CircleCI Insights / build metrics (https://app.circleci.com/insights/github/filecoin-project/lotus)
- Github Insights / Traffic (https://github.com/filecoin-project/lotus/graphs/traffic)
- Output from `lotus net peers -a` on api.chain.love nodes

If there are other metrics you think we should track, let me know!
