### ISSUE TITLE
ntwk v17 migration integration and testing 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9246]
- [x] Update go-state-types 
- [x]  Migration Integration
This will be something of a living issue -- as we develop nv17, we will have various changes to go-state-types that we'll need to integrate into Lotus (eg https://github.com/filecoin-project/go-state-types/issues/52, https://github.com/filecoin-project/go-state-types/issues/53, https://github.com/filecoin-project/go-state-types/issues/54).
Each integration will likely involve work to Lotus's state abstractions as well.

- [x] rerunning the migration using lotus-shed with the latest RC
- [x]  Ensuring correctness and that it's fast enough
- [ ]  Running the migration in "online" mode -- this means letting the premigration happen while the lotus daemon is syncing the chain, making sure the time and memory usage are okay
- [x]  Param finalization: based on time and memory usage of the experiments, we need to settle on the correct number of and epochs for premigration

**Comment by arajasek** [comment]
The migration is now fully integrated, and testing has begun in #9446. Here is a list of further assertions we should make:

- that for each pending, verified deal in v8 market, there is a corresponding allocation in v9 verifreg Allocations
- that nextAllocationID is equal to the number of pending, verified deals in v8 market
- that for each pending, verified deal in v8 market, there is a corresponding entry in v9 market PendingDealAllocationIds
- that all miners that have PreCommits with deals in them have non-nil UnsealedCid, and this CID is correctly calculated:
  - IMPORTANT: Perform this calculation using the [FFI's GenerateUnsealedCID](https://github.com/filecoin-project/lotus/blob/39af6e0365eefaa22bbdd3393055cdcd67f0b101/storage/sealer/ffiwrapper/sealer_cgo.go#L166). This will help us test the correctness of t[he new go-based CommD calculator](https://github.com/filecoin-project/go-commp-utils/pull/9) that the migration is using.

**Comment by jennijuju** [comment]
@arajasek did we do 
> Running the migration in "online" mode -- this means letting the premigration happen while the lotus daemon is syncing the chain, making sure the time and memory usage are okay ?
