### ISSUE TITLE
integrate v9 bundle 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9248]
- get the v8 bundle from actor
- make sure the manifest cids are correct

**Comment by arajasek** [comment]
- I think this should be the v9 bundle?
- There is now a v9 dev bundle in https://github.com/filecoin-project/lotus/pull/9267, so the work is mostly done. 
- I would still leave this issue open until we have the final bundle in as a reminder, though (maybe with an `effort/minutes` tag.
