### ISSUE TITLE
Integrate FIP-0034

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9251]
introduced by https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0034.md

actor code: [here](https://github.com/filecoin-project/builtin-actors/pull/484)

**Comment by jennijuju** [comment]
@arajasek @Kubuxu i dont think lotus needs to do anything wrt fip0034 . could you please confirm and close the issue if thats the case?

**Comment by jennijuju** [comment]
we always [check on chain on how much PCD will need ](https://github.com/filecoin-project/lotus/blob/2e29b460d2dce124e082ad046c34cc9b8e9b7f26/storage/pipeline/states_sealing.go#L359), then [we will check where we should get the deposit](https://github.com/filecoin-project/lotus/blob/2c3dbb239a55590970066d61e68aaed734c6e299/storage/pipeline/utils.go#L69) 

when use miner avaiable(DisableCollateralFallback), we have the buffer default https://github.com/filecoin-project/lotus/blob/8b7be6d47e25eb8c281fb864971445b5f492cfed/node/config/def.go#L119 set to 0, so guess nothing needs to be changed here.

**Comment by jennijuju** [comment]
closing given ^

@magik6k could you please confirm and reopen the issue if something is missing?

**Comment by Kubuxu** [comment]
This calculation will need to change: https://github.com/filecoin-project/lotus/blob/45d1bd61cecd8e723f2239979377b8ac92c62362/node/impl/full/state.go#L1186-L1227

Especially: `PreCommitDepositForPower` and the signature of `VerfiyDealsForActivation` is changed IIRC.

**Comment by jennijuju** [comment]
@Kubuxu  thanks - could you please work on this?

**Comment by Kubuxu** [comment]
This will be part of the integration work for v9 (??) actors, but I can take it on then.

**Comment by jennijuju** [comment]
> This will be part of the integration work for v9 (??) actors, but I can take it on then.

Thanks

**Comment by arajasek** [comment]
> This calculation will need to change:
> 
> https://github.com/filecoin-project/lotus/blob/45d1bd61cecd8e723f2239979377b8ac92c62362/node/impl/full/state.go#L1186-L1227
> 
> Especially: `PreCommitDepositForPower` and the signature of `VerfiyDealsForActivation` is changed IIRC.

This has likely already happened as v9 integration, will check

**Comment by arajasek** [comment]
Confirmed done.
