### ISSUE TITLE
Add ChangeBeneficiary API

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9253]
introduced by[ fip 0029](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0029.md)

actor impl [here](https://github.com/filecoin-project/builtin-actors/blob/b7ad2c55363c363f61275ca45ef255e28f305254/actors/miner/src/lib.rs#L3334)

**Comment by arajasek** [comment]
Lowering this to P3 too -- note that we don't have API endpoints for either `ChangeOwnerAddress` or `ChangeWorkerAddress`.

Honestly I'd just close this issue.

**Comment by jennijuju** [comment]
I think this needs to stay as p2 - as I can see lenders want this API.

**Comment by jennijuju** [comment]
(“We don’t have things” is not the reason to not have things 😜)

**Comment by rjan90** [comment]
Closing this since Geoff added this in #9307, which has been merged.
