### ISSUE TITLE
Add a cli for ChangeBeneficiary

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9254]
related #9253 

I think for a better user experience, we should have to CLI

-  `lotus-miner actor propose-change-beneficiary`
   - fail early if the caller is not the owner
   - should show if its a replacement of a pendingchange
   - we should handle the situation when the owner is a msig
-  `lotus-miner actor confirm-change-beneficiary` 
   - fail early if the caller is not the new beneficiary or the existing beneficiary
  - we should create tooling for performing this action via msig (this can be a separate issue later)

**Comment by jennijuju** [comment]
@geoff-vball please review the scope and adjust the estimation accordingly

**Comment by geoff-vball** [comment]
Msig tooling definitely shouldn't be in this ticket. I'd argue we might not want it at all? @arajasek

**Comment by arajasek** [comment]
Let's do both accounts and multisigs as part of this ticket. We just have to build off the existing change-worker functionality, which makes this very easy.

- That's 2 new commands in the lotus-miner CLI, following https://github.com/filecoin-project/lotus/blob/15ea3953f09311d1587d1c3291013771ca7ba3e7/cmd/lotus-miner/actor.go#L47-L48.

- And 2 new commands in the lotus-shed -- following https://github.com/filecoin-project/lotus/blob/e65fae28de2a44947dd24af8c7dafcade29af1a4/cmd/lotus-shed/miner-multisig.go#L33-L34.

**Comment by geoff-vball** [comment]
@arajasek I'm super duper confused at the workflow for `actorProposeChangeWorker` and `actorConfirmChangeWorker`. Propose sends a message signed by the owner key with a new worker address. Then Confirm sends a message with no params, also signed by the owner address. I don't understand the point of this. It would make sense to me that that message would be signed by the new worker address.
