### ISSUE TITLE
Integrate the new WithdrawBalance to support caller as owner or beneficairy 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9257]
Two options I can think of
-  move [ActorWithdrawBalance](https://github.com/filecoin-project/lotus/blob/45d1bd61cecd8e723f2239979377b8ac92c62362/node/impl/storminer.go#L1330) out of Storage Miner API to full node API.
   - take the caller's address as a param
   - make sure the caller is either the beneficiary or the owner 
   - then proceed
   - we should rename the API to `MinerWithdrawBalace` probably
- or we can keep ActorWithdrawBalance as it is today, and add a `BeneficiaryWithdrawBalance` 

I prefer 1 personally but that might be considered as a breaking api change. if so we might wanna do 2.  @magik6k @geoff-vball  - thoughts?

**Comment by jennijuju** [comment]
discussed in standup - we will go with @geoff-vball 's reco Option 2

**Comment by TippyFlitsUK** [comment]
From an SP's perspective, I agree that option 2 would be the preferred option.
