### ISSUE TITLE
RTX 2080 GPU failed to seal 32g file, GPU code optimization

### ISSUE THREAD

**Issue by ytQiao** [filecoin-project/lotus#926]
GPU information
```root@r730xd8:/fsave# nvidia-smi
Mon Dec 16 02:21:55 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:82:00.0 Off |                  N/A |
| 18%   49C    P0    49W / 215W |     10MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by ytQiao** [comment]
> GPU information
> 
> ```
> Mon Dec 16 02:21:55 2019       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce RTX 2080    Off  | 00000000:82:00.0 Off |                  N/A |
> | 18%   49C    P0    49W / 215W |     10MiB /  7982MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+```

> Wrong log
> ```
> 2019-12-15T11:23:10.993Z INFO storageminer storage/sectors.go:162 Sector 20 updated state to SealCommitFailed
> 2019-12-15T11:23:10.997Z ERROR storageminer storage/sectors.go:189 sector 20 failed: computing seal proof failed:
> github.com/filecoin-project/lotus/storage.(*Miner).handleCommitting
> /root/lotus/storage/sector_states.go:178
> 
> * commit:
>   github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).SealCommit
>   /root/lotus/lib/sectorbuilder/sectorbuilder.go:606
> * StandaloneSealCommit:
>   github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).sealCommitLocal
>   /root/lotus/lib/sectorbuilder/sectorbuilder.go:564
> * Rust panic: no unwind information
>   github.com/filecoin-project/filecoin-ffi.SealCommit
>   /root/lotus/extern/filecoin-ffi/proofs.go:488
>   github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).sealCommitLocal
>   /root/lotus/lib/sectorbuilder/sectorbuilder.go:549
>   github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).SealCommit
>   /root/lotus/lib/sectorbuilder/sectorbuilder.go:602
>   github.com/filecoin-project/lotus/storage.(*Miner).handleCommitting
>   /root/lotus/storage/sector_states.go:176
>   github.com/filecoin-project/lotus/storage.(*Miner).handleSectorUpdate.func1
>   /root/lotus/storage/sector_states.go:19
>   runtime.goexit
>   /usr/local/go/src/runtime/asm_amd64.s:1357
>   github.com/filecoin-project/lotus/storage.(*Miner).onSectorUpdated
>   /root/lotus/storage/sectors.go:189
>   github.com/filecoin-project/lotus/storage.(*Miner).sectorStateLoop.func2
>   /root/lotus/storage/sectors.go:124
>   2019-12-15T11:23:10.998Z	WARN	storageminer	storage/sectors.go:254	sector 20 entered unimplemented state 'SealCommitFailed'
>   2019-12-15T11:39:19.608Z	INFO	storageminer	storage/fpost_run.go:69	running fPoSt	{"chain-random": "VBR0i5y80I2jVrzrBqiGLcY9PkeTYlKT4PFi/Cb3ts4=", "eps": 7178, "height": 7212}
>   2019-12-15T11:39:30.216Z	INFO	storageminer	storage/fpost_run.go:83	submitting PoSt	{"pLen": 192, "elapsed": 10.607183992}
> 
> 2019-12-15T10:47:39.151Z WARN storageminer storage/fpost_sched.go:147 Aborting Fallback PoSt (EPS: 7102)
> thread '' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel("radix_fft") \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 2019-12-15T11:11:58.458Z INFO storageminer storage/fpost_run.go:69 running fPoSt {"chain-random": "6rgAcFzMp37bkWrWIZoFTQY/Yk5PyZKybxmhJ9Xp7FQ=", "eps": 7142, "height": 7176}
> thread '' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel("radix_fft") \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
> 2019-12-15T11:12:38.061Z INFO storageminer storage/fpost_run.go:83 submitting PoSt {"pLen": 192, "elapsed": 39.602672376}
> 2019-12-15T11:12:38.077Z INFO storageminer storage/fpost_run.go:150 Submitted fallback post: bafy2bzacecpmorrp357a2i2gzmewdukgqudqq6tkfjhhghsmazxui3dklggxi
> 2019-12-15T11:13:49.386Z WARN storageminer storage/fpost_sched.go:147 Aborting Fallback PoSt (EPS: 7142)
> thread '' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel("radix_fft") \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
> thread '' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel("radix_fft") \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
> thread '' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel("radix_fft") \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
> thread '' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel("radix_fft") \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
> 2019-12-15T11:23:10.992Z WARN sectorbuilder sectorbuilder/sectorbuilder.go:561 StandaloneSealCommit error: Rust panic: no unwind information
> 2019-12-15T11:23:10.993Z WARN sectorbuilder sectorbuilder/sectorbuilder.go:562 sid:20 tkt:{6834 [226 12 100 153 231 73 250 125 91 49 209 96 115 45 118 139 17 205 195 54 255 181 243 8 160 255 250 19 101 242 45 30]} seed:{7131 [208 93 174 111 242 126 27 51 129 157 58 74 171 114 244 84 229 57 2 19 60 35 181 201 97 151 41 57 209 94 3 72]}, ppi:[{34091302912 [253 47 195 200 241 49 105 17 23 102 198 44 98 146 98 117 43 43 228 104 245 49 207 200 140 11 71 209 172 19 198 46]}] rspco:{[253 47 195 200 241 49 105 17 23 102 198 44 98 146 98 117 43 43 228 104 245 49 207 200 140 11 71 209 172 19 198 46] [25 33 239 194 246 177 205 146 62 164 248 183 53 52 84 9 74 22 185 106 145 231 103 64 20 78 200 38 121 53 25 35]}
```

**Comment by ytQiao** [comment]
Wrong log
```
2019-12-15T11:23:10.993Z	INFO	storageminer	storage/sectors.go:162	Sector 20 updated state to SealCommitFailed
2019-12-15T11:23:10.997Z	ERROR	storageminer	storage/sectors.go:189	sector 20 failed: computing seal proof failed:
    github.com/filecoin-project/lotus/storage.(*Miner).handleCommitting
        /root/lotus/storage/sector_states.go:178
  - commit:
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).SealCommit
        /root/lotus/lib/sectorbuilder/sectorbuilder.go:606
  - StandaloneSealCommit:
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).sealCommitLocal
        /root/lotus/lib/sectorbuilder/sectorbuilder.go:564
  - Rust panic: no unwind information
    github.com/filecoin-project/filecoin-ffi.SealCommit
    	/root/lotus/extern/filecoin-ffi/proofs.go:488
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).sealCommitLocal
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:549
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).SealCommit
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:602
    github.com/filecoin-project/lotus/storage.(*Miner).handleCommitting
    	/root/lotus/storage/sector_states.go:176
    github.com/filecoin-project/lotus/storage.(*Miner).handleSectorUpdate.func1
    	/root/lotus/storage/sector_states.go:19
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*Miner).onSectorUpdated
	/root/lotus/storage/sectors.go:189
github.com/filecoin-project/lotus/storage.(*Miner).sectorStateLoop.func2
	/root/lotus/storage/sectors.go:124
2019-12-15T11:23:10.998Z	WARN	storageminer	storage/sectors.go:254	sector 20 entered unimplemented state 'SealCommitFailed'
2019-12-15T11:39:19.608Z	INFO	storageminer	storage/fpost_run.go:69	running fPoSt	{"chain-random": "VBR0i5y80I2jVrzrBqiGLcY9PkeTYlKT4PFi/Cb3ts4=", "eps": 7178, "height": 7212}
2019-12-15T11:39:30.216Z	INFO	storageminer	storage/fpost_run.go:83	submitting PoSt	{"pLen": 192, "elapsed": 10.607183992}

2019-12-15T10:47:39.151Z	WARN	storageminer	storage/fpost_sched.go:147	Aborting Fallback PoSt (EPS: 7102)
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
2019-12-15T11:11:58.458Z	INFO	storageminer	storage/fpost_run.go:69	running fPoSt	{"chain-random": "6rgAcFzMp37bkWrWIZoFTQY/Yk5PyZKybxmhJ9Xp7FQ=", "eps": 7142, "height": 7176}
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
2019-12-15T11:12:38.061Z	INFO	storageminer	storage/fpost_run.go:83	submitting PoSt	{"pLen": 192, "elapsed": 39.602672376}
2019-12-15T11:12:38.077Z	INFO	storageminer	storage/fpost_run.go:150	Submitted fallback post: bafy2bzacecpmorrp357a2i2gzmewdukgqudqq6tkfjhhghsmazxui3dklggxi
2019-12-15T11:13:49.386Z	WARN	storageminer	storage/fpost_sched.go:147	Aborting Fallback PoSt (EPS: 7142)
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
2019-12-15T11:23:10.992Z	WARN	sectorbuilder	sectorbuilder/sectorbuilder.go:561	StandaloneSealCommit error: Rust panic: no unwind information
2019-12-15T11:23:10.993Z	WARN	sectorbuilder	sectorbuilder/sectorbuilder.go:562	sid:20 tkt:{6834 [226 12 100 153 231 73 250 125 91 49 209 96 115 45 118 139 17 205 195 54 255 181 243 8 160 255 250 19 101 242 45 30]} seed:{7131 [208 93 174 111 242 126 27 51 129 157 58 74 171 114 244 84 229 57 2 19 60 35 181 201 97 151 41 57 209 94 3 72]}, ppi:[{34091302912 [253 47 195 200 241 49 105 17 23 102 198 44 98 146 98 117 43 43 228 104 245 49 207 200 140 11 71 209 172 19 198 46]}] rspco:{[253 47 195 200 241 49 105 17 23 102 198 44 98 146 98 117 43 43 228 104 245 49 207 200 140 11 71 209 172 19 198 46] [25 33 239 194 246 177 205 146 62 164 248 183 53 52 84 9 74 22 185 106 145 231 103 64 20 78 200 38 121 53 25 35]}

**Comment by ldoublewood** [comment]
Hi, It seems I have the same or similar as below: 
Dec 19 05:03:12 gucloud lotus-storage-miner[56265]: 2019-12-19T05:03:12.771Z        INFO        storageminer        storage/fpost_run.go:69        running fPoSt        {"chain-random": "9QaYXzSRVVYNACUXwqGvHdWMRVh2zj2MOvrpYGNBd9g=", "eps": 14296, "height": 14364}
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/libcore/result.rs:1165:5
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]: 2019-12-19T05:03:15.449Z        ERROR        storageminer        storage/fpost_run.go:39        runPost failed: running post failed:
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:     github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:         /s/hub/ldoublewood/lotus/storage/fpost_run.go:79
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:   - Rust panic: no unwind information
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:     github.com/filecoin-project/filecoin-ffi.GeneratePoSt
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:             /s/hub/ldoublewood/lotus/extern/filecoin-ffi/proofs.go:675
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:     github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:             /s/hub/ldoublewood/lotus/lib/sectorbuilder/sectorbuilder.go:685
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:     github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:             /s/hub/ldoublewood/lotus/storage/fpost_run.go:77
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:     github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:             /s/hub/ldoublewood/lotus/storage/fpost_run.go:37
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:     runtime.goexit
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:             /s/opt/go/src/runtime/asm_amd64.s:1357
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]: github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
Dec 19 05:03:15 gucloud lotus-storage-miner[56265]:         /s/hub/ldoublewood/lotus/storage/fpost_run.go:39

**Comment by whyrusleeping** [comment]
@ytQiao it looks like youre running multiple seals in parallel, and the gpu is running out of resources.

**Comment by ytQiao** [comment]
@whyrusleeping   OK, thank you for your reply. I will test it, but it will take 2-3 days

**Comment by ytQiao** [comment]
I started a worker, but the error still exists
`Miner: t010164
Sector Size: 32 GiB
Power: 0 B / 68.6 TiB (0.0000%)
	Committed: 32 GiB
	Proving: 32 GiB
Worker use:
	Local: 0 / 1 (+1 reserved)
	Remote: 0 / 0
Queues:
	AddPiece: 0
	PreCommit: 0
	Commit: 0
	Unseal: 0
PoSt Submissions:
	Previous: Epoch 58260 (4147 block(s), ~3110m 15s ago)
	Fallback: Epoch 58290 (in 4177 blocks, ~3132m 45s)
	Deadline: Epoch 58460 (in 4347 blocks, ~3260m 15s)
Sectors:  map[Proving:1 SealCommitFailed:4 Total:5]
`
@whyrusleeping

**Comment by ytQiao** [comment]
I started a worker, but the error still exists
`Miner: t010164
Sector Size: 32 GiB
Power: 0 B / 68.6 TiB (0.0000%)
	Committed: 32 GiB
	Proving: 32 GiB
Worker use:
	Local: 0 / 1 (+1 reserved)
	Remote: 0 / 0
Queues:
	AddPiece: 0
	PreCommit: 0
	Commit: 0
	Unseal: 0
PoSt Submissions:
	Previous: Epoch 58260 (4147 block(s), ~3110m 15s ago)
	Fallback: Epoch 58290 (in 4177 blocks, ~3132m  45s)
	Deadline: Epoch 58460 (in 4347 blocks, ~3260m 15s)
Sectors:  map[Proving:1 SealCommitFailed:4 Total:5]
` 
@whyrusleeping

**Comment by ytQiao** [comment]
```
2020-01-12T08:57:48.999Z	INFO	storageminer	storage/sector_states.go:135	precommit message landed on chain: 5
2020-01-12T08:57:49.001Z	INFO	storageminer	storage/sector_states.go:138	precommit for sector 5 made it on chain, will start proof computation at height 60764
2020-01-12T09:04:08.117Z	WARN	storageminer	storage/sector_states.go:162	revert in interactive commit sector step
2020-01-12T09:04:30.181Z	WARN	storageminer	storage/sector_states.go:162	revert in interactive commit sector step
2020-01-12T09:04:32.286Z	WARN	storageminer	storage/sector_states.go:162	revert in interactive commit sector step
2020-01-12T09:04:53.472Z	WARN	storageminer	storage/sector_states.go:162	revert in interactive commit sector step
2020-01-12T09:08:15.519Z	INFO	storageminer	storage/sectors.go:162	Sector 5 updated state to Committing
2020-01-12T09:08:15.519Z	INFO	storageminer	storage/sector_states.go:174	scheduling seal proof computation...
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
thread '<unnamed>' panicked at 'GPU FFT failed!: GPUError { msg: "\n\n################################ OPENCL ERROR ############################### \n\nError executing function: clEnqueueNDRangeKernel(\"radix_fft\")  \n\nStatus error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  \n\nPlease visit the following url for more information: \n\nhttps://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  \n\n############################################################################# \n" }', src/libcore/result.rs:1165:5
2020-01-12T09:39:40.432Z	WARN	sectorbuilder	go-sectorbuilder@v0.0.0-20200107152336-0cbb2c483013/sectorbuilder.go:565	StandaloneSealCommit error: Rust panic: no unwind information
2020-01-12T09:39:40.433Z	WARN	sectorbuilder	go-sectorbuilder@v0.0.0-20200107152336-0cbb2c483013/sectorbuilder.go:566	sid:5 tkt:{60474 [101 90 101 54 190 76 13 84 87 111 172 14 141 189 229 107 233 97 63 248 70 16 148 2 191 16 228 110 217 86 227 208]} seed:{60764 [37 0 6 184 97 89 227 47 76 93 225 183 165 203 15 77 251 156 69 54 87 80 174 33 165 232 27 67 190 187 117 122]}, ppi:[{34091302912 [253 47 195 200 241 49 105 17 23 102 198 44 98 146 98 117 43 43 228 104 245 49 207 200 140 11 71 209 172 19 198 46]}] rspco:{[253 47 195 200 241 49 105 17 23 102 198 44 98 146 98 117 43 43 228 104 245 49 207 200 140 11 71 209 172 19 198 46] [101 33 144 48 7 246 178 245 133 163 1 233 144 1 98 132 140 139 116 100 127 14 72 150 187 15 24 196 36 160 207 53]}
2020-01-12T09:39:40.435Z	INFO	storageminer	storage/sectors.go:162	Sector 5 updated state to SealCommitFailed
2020-01-12T09:39:40.438Z	ERROR	storageminer	storage/sectors.go:189	sector 5 failed: computing seal proof failed:
    github.com/filecoin-project/lotus/storage.(*Miner).handleCommitting
        /root/lotus/storage/sector_states.go:178
  - commit:
    github.com/filecoin-project/go-sectorbuilder.(*SectorBuilder).SealCommit
        /root/BlockchainExperiment/GoCode/pkg/mod/github.com/filecoin-project/go-sectorbuilder@v0.0.0-20200107152336-0cbb2c483013/sectorbuilder.go:610
  - StandaloneSealCommit:
    github.com/filecoin-project/go-sectorbuilder.(*SectorBuilder).sealCommitLocal
        /root/BlockchainExperiment/GoCode/pkg/mod/github.com/filecoin-project/go-sectorbuilder@v0.0.0-20200107152336-0cbb2c483013/sectorbuilder.go:568
  - Rust panic: no unwind information
    github.com/filecoin-project/filecoin-ffi.SealCommit
    	/root/lotus/extern/filecoin-ffi/proofs.go:488
    github.com/filecoin-project/go-sectorbuilder.(*SectorBuilder).sealCommitLocal
    	/root/BlockchainExperiment/GoCode/pkg/mod/github.com/filecoin-project/go-sectorbuilder@v0.0.0-20200107152336-0cbb2c483013/sectorbuilder.go:553
    github.com/filecoin-project/go-sectorbuilder.(*SectorBuilder).SealCommit
    	/root/BlockchainExperiment/GoCode/pkg/mod/github.com/filecoin-project/go-sectorbuilder@v0.0.0-20200107152336-0cbb2c483013/sectorbuilder.go:606
    github.com/filecoin-project/lotus/storage.(*Miner).handleCommitting
    	/root/lotus/storage/sector_states.go:176
    github.com/filecoin-project/lotus/storage.(*Miner).handleSectorUpdate.func1
    	/root/lotus/storage/sector_states.go:19
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*Miner).onSectorUpdated
	/root/lotus/storage/sectors.go:189
github.com/filecoin-project/lotus/storage.(*Miner).sectorStateLoop.func2
	/root/lotus/storage/sectors.go:124
2020-01-12T09:39:40.438Z	WARN	storageminer	storage/sectors.go:254	sector 5 entered unimplemented state 'SealCommitFailed'
```

**Comment by ytQiao** [comment]
I started a worker, but the error still exists
`Miner: t010164
Sector Size: 32 GiB
Power: 0 B / 68.6 TiB (0.0000%)
	Committed: 32 GiB
	Proving: 32 GiB
Worker use:
	Local: 0 / 1 (+1 reserved)
	Remote: 0 / 0
Queues:
	AddPiece: 0
	PreCommit: 0
	Commit: 0
	Unseal: 0
PoSt Submissions:
	Previous: Epoch 58260 (4147 block(s), ~3110m 15s ago)
	Fallback: Epoch 58290 (in 4177 blocks, ~3132m 45s)
	Deadline: Epoch 58460 (in 4347 blocks, ~3260m 15s)
Sectors:  map[Proving:1 SealCommitFailed:4 Total:5]
`
@whyrusleeping

**Comment by carryon** [comment]
we met the same problem. @whyrusleeping. when will fix the problem?
![image](https://user-images.githubusercontent.com/2255313/72676207-92907680-3ac9-11ea-833d-fcd2e229b413.png)

**Comment by whyrusleeping** [comment]
Several bugfixes to this code have been merged, You may still see openCL complaining about things, but it should no longer cause failures to seal
