### ISSUE TITLE
Synchronization failure

### ISSUE THREAD

**Issue by huangchundi** [filecoin-project/lotus#927]
root@root:~/block/lotus# lotus sync status
sync status:
worker 0:
        Base:   [bafy2bzacedlusrmhwxo4mxkmvqgtif7uwndvp44pbnyhqu46uavxmr7nxowgy]
        Target: [bafy2bzaceclchzbszhol56u5nk5qrvrhkmg7kihv474635gclprwq4r5qbdig bafy2bzacec3xpg4jfic63k2tqy6p7u6kvr2q3x6t2hdy2xjq3ewhfjfmwq24o] (8413)
        Height diff:    6119
        Stage: error
        Height: 0
        Elapsed: 50.41µs
        Error: chain linked to block marked previously as bad ([bafy2bzaceclchzbszhol56u5nk5qrvrhkmg7kihv474635gclprwq4r5qbdig bafy2bzacec3xpg4jfic63k2tqy6p7u6kvr2q3x6t2hdy2xjq3ewhfjfmwq24o], bafy2bzaceahqfon2v7rf6tadtqvpuvlqgsnwdxu7jl5h5z2lktdstox7r2qvs)
worker 1:
        Base:   [bafy2bzacedlusrmhwxo4mxkmvqgtif7uwndvp44pbnyhqu46uavxmr7nxowgy]
        Target: [bafy2bzaceclchzbszhol56u5nk5qrvrhkmg7kihv474635gclprwq4r5qbdig bafy2bzacec3xpg4jfic63k2tqy6p7u6kvr2q3x6t2hdy2xjq3ewhfjfmwq24o] (8413)
        Height diff:    6119
        Stage: error
        Height: 0
        Elapsed: 53.882µs
        Error: chain linked to block marked previously as bad ([bafy2bzaceclchzbszhol56u5nk5qrvrhkmg7kihv474635gclprwq4r5qbdig bafy2bzacec3xpg4jfic63k2tqy6p7u6kvr2q3x6t2hdy2xjq3ewhfjfmwq24o], bafy2bzaceahqfon2v7rf6tadtqvpuvlqgsnwdxu7jl5h5z2lktdstox7r2qvs)
worker 2:
        Base:   [bafy2bzacedlusrmhwxo4mxkmvqgtif7uwndvp44pbnyhqu46uavxmr7nxowgy]
        Target: [bafy2bzacebxsbey2w3i4cx3x2vjrxy7x2pkuydnmr5occ2v6m5gqwpk2uvk2s] (8365)
        Height diff:    6071
        Stage: error
        Height: 0
        Elapsed: 56.488µs
        Error: chain linked to block marked previously as bad ([bafy2bzacebxsbey2w3i4cx3x2vjrxy7x2pkuydnmr5occ2v6m5gqwpk2uvk2s], bafy2bzaceclnl7wdwhyrai34phxfdjfjpqfwwttufsj4vd2bwvyto3tyzepgw)

Problem Description: error is reported after synchronization to a certain height.
version:lotus_v0.1.0_linux-amd64.tar.gz
GPU:1050ti
Thank you! What should I do?

**Comment by hunjixin** [comment]
stop at bafy2bzacedlusrmhwxo4mxkmvqgtif7uwndvp44pbnyhqu46uavxmr7nxowgy always

**Comment by whyrusleeping** [comment]
the testnet had some sync issues over the holiday break, these should be mostly resolved, and the upcoming testnet reset will fix the rest.
