### ISSUE TITLE
update StateVerifiedClientStatus w/ token contract

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9274]
with fip 0045 The `VerifiedClients` map of addresses to balances is removed from the verified registry state.
The balances of DataCap tokens held by verified clients are extracted to a DataCap token actor.

we should update the API to  call the token contract to get the balance of a specific holder 
-  [`balance of`](https://github.com/helix-onchain/filecoin/blob/a3f2234e8464386f2d433139049019712af758ac/fil_fungible_token/src/token/types.rs#L54) fn

**Comment by geoff-vball** [comment]
Implemented in https://github.com/filecoin-project/lotus/pull/9355. Does not call `balance of`, but inspects the datacap actor state directly.
