### ISSUE TITLE
update filplus list-clients

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9275]
with fip 0045 The VerifiedClients map of addresses to balances is removed from the verified registry state.
The balances of DataCap tokens held by verified clients are extracted to a DataCap token actor.

we need to update `lotus filplus list-clients` to
- inspect https://github.com/helix-onchain/filecoin/blob/a3f2234e8464386f2d433139049019712af758ac/fil_fungible_token/src/token/state.rs#L88 to get all verifeirs and their balance

**Comment by geoff-vball** [comment]
Included in https://github.com/filecoin-project/lotus/pull/9355
