### ISSUE TITLE
Trying to install a Lotus/Filecoin node build errors #546 [ related to bellperson ]

### ISSUE THREAD

**Issue by teliten** [filecoin-project/lotus#9278]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
from source https://github.com/filecoin-project/lotus.git
```

### Describe the Bug

following basic instructions here https://lotus.filecoin.io/tutorials/lotus-miner/run-a-miner/ results in a build error related to "bellperson" this is frustrating to say the least.

### Logging Information

```text
following basic instructions here https://lotus.filecoin.io/tutorials/lotus-miner/run-a-miner/


 Compiling polling v2.2.0
   Compiling kv-log-macro v1.0.7
   Compiling blstrs v0.4.2
   Compiling merkletree v0.21.0
   Compiling derive_builder_macro v0.11.2
   Compiling wasmtime-types v0.37.0 (https://github.com/filecoin-project/wasmtime?branch=fix/sse-feature#cbb8a3de)
   Compiling addr2line v0.17.0
   Compiling multihash-derive v0.8.0
   Compiling async-io v1.7.0
   Compiling bellperson v0.21.0
   Compiling neptune v5.2.0
   Compiling derive_builder v0.11.2
   Compiling bls-signatures v0.11.3
   Compiling wasmtime-environ v0.37.0 (https://github.com/filecoin-project/wasmtime?branch=fix/sse-feature#cbb8a3de)
   Compiling multihash v0.16.2
   Compiling async-global-executor v2.2.0
   Compiling cranelift-frontend v0.84.0 (https://github.com/filecoin-project/wasmtime?branch=fix/sse-feature#cbb8a3de)
   Compiling cranelift-native v0.84.0 (https://github.com/filecoin-project/wasmtime?branch=fix/sse-feature#cbb8a3de)
error: failed to run custom build command for `bellperson v0.21.0`

Caused by:
  process didn't exit successfully: `/root/lotus/extern/filecoin-ffi/rust/target/release/build/bellperson-b7ffadd7636fe08e/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Cannot run nvcc.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bellperson-0.21.0/build.rs:65:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
+ rm -f /tmp/tmp.pK9pamMxJZ
make[1]: *** [Makefile:14: .install-filcrypto] Error 101
make[1]: Leaving directory '/root/lotus/extern/filecoin-ffi'
make: *** [Makefile:39: build/.filecoin-install] Error 2
root@ATLAS:~/lotus# cargo build bellperson
error: Found argument 'bellperson' which wasn't expected, or isn't valid in this context

USAGE:
    cargo build [OPTIONS]

For more information try --help
```

thanks in advance. #otii
```


### Repo Steps

# Installation 

We have bundled all the install steps into the below code snippets so you can just copy and paste them into your terminal. If you would prefer to run each command step by step, take a look at the [Installation guide](https://lotus.filecoin.io/lotus/install/linux/#building-from-source). FFI_USE_CUDA=1 variable forces the use of CUDA architecture instead of OpenCL for Nvidia cards. RUST_GPU_TOOLS_CUSTOM_GPU variable need to be set after driver 475+ due to a change in naming convention.

```
sudo apt install mesa-opencl-icd ocl-icd-opencl-dev gcc git bzr jq pkg-config curl clang build-essential hwloc libhwloc-dev wget -y && sudo apt upgrade -y
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

### Follow the prompts to install Rust, and then run these commands:

```
wget -c https://golang.org/dl/go1.17.9.linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local
echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc && source ~/.bashrc
git clone https://github.com/filecoin-project/lotus.git
cd lotus/
git checkout releases
export CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
export CGO_CFLAGS="-D__BLST_PORTABLE__"
export FFI_BUILD_FROM_SOURCE=1
export RUSTFLAGS="-C target-cpu=native -g"
export FFI_USE_CUDA=1
export RUST_GPU_TOOLS_CUSTOM_GPU="Quadro RTX 6000:4608"
make clean calibnet
./lotus --version
```

**Comment by TippyFlitsUK** [comment]
Hi @teliten 

You need to install Cuda Toolkit - https://lotus.filecoin.io/tutorials/lotus-miner/cuda/

**Comment by teliten** [comment]
thanks that did it.
