### ISSUE TITLE
create Groth parameters locally instead of fetching through internet

### ISSUE THREAD

**Issue by zouzichun** [filecoin-project/lotus#929]
hello Sir,Miss:
I was focusing on lotus project, and found that lotus will download the Groth parameters from internet, which is different form go-filecoin that could be generated locally.
is it costly when generate locally? or, will lotus support generating these parameters locally in the future? (forgive me for that i have a relatively bad network...)

**Comment by Kubuxu** [comment]
Generated Groth parameters are not secure. The ones use by lotus in testnet are source of small trusted setup ceremony (the mainnet parameters will be coming from much bigger testnet ceremony).
