### ISSUE TITLE
Since 1.17.1 wdpost skips sectors on read-only storage

### ISSUE THREAD

**Issue by clinta** [filecoin-project/lotus#9298]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

`lotus-miner version 1.17.1+mainnet+git.576082149`

This is 1.17.1, with my pull request #9089 cherry-picked.

After encountering this bug I've reverted to `1.17.0+mainnet+git.00822622a` which is 1.17.0 with the same PR cherry-picked. Which works fine.

### Describe the Bug

I have a few store locations that are mounted read-only, this is a safety measure as there are health issues on the storage, and mounting the stores read only allows them to remain accessible for windowpost while backups are restored to another server.

In previous versions of lotus this was never a problem. In 1.17.1, these sectors on these read-only stores are skipped in windowpost.

### Logging Information

The wdpost worker logs the following for the sectors affected:

```
2022-09-12T21:54:57.212Z        ERROR        advmgr        sealer/worker_local.go:680        reading PoSt challenge for sector 24456, vlen:0, err: non-200 code from http://qcysrmr001.qcy.w3bstorage.com:2345/remote/vanilla/single: 'generate_single_vanilla_proof: merkle_tree failed: SectorId(24456)
Caused by:
    Read-only file system (os error 30)'
```

### Repo Steps

Re-mount a sector store as read-only, try to to compute a window post with sectors on that storage using `lotus-miner proving compute window-post <deadline>`

**Comment by clinta** [comment]
This is also reproducible with `lotus-bench`.

`lotus-bench version 1.17.0+mainnet+git.2830429ad` is able to bench window-post on a read-only mount with no issues.

`lotus-bench version 1.17.1+mainnet+git.8db6a939c` fails with the following logs:
```
2022-09-13T23:51:20.766Z	INFO	lotus-bench	lotus-bench/main.go:99	Starting lotus-bench
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
2022-09-13T23:51:20.767 INFO filcrypto::util::types > generate_fallback_sector_challenges: start
2022-09-13T23:51:20.767 INFO filecoin_proofs::api::post_util > generate_sector_challenges:start
2022-09-13T23:51:20.767 INFO filecoin_proofs::api::post_util > generate_sector_challenges:finish
2022-09-13T23:51:20.767 INFO filcrypto::util::types > generate_fallback_sector_challenges: end
2022-09-13T23:51:20.767 INFO filcrypto::util::types > generate_single_vanilla_proof: start
2022-09-13T23:51:20.767 INFO filecoin_proofs::api::post_util > generate_single_vanilla_proof:start: SectorId(24456)
2022-09-13T23:51:20.767 INFO filcrypto::util::types > generate_single_vanilla_proof: end
2022-09-13T23:51:20.767Z	WARN	lotus-bench	lotus-bench/main.go:114	generate_single_vanilla_proof: merkle_tree failed: SectorId(24456)

Caused by:
    Read-only file system (os error 30)
```

**Comment by clinta** [comment]
Git bisect has determined that this issue started with fa04496c81a7348e4ca75b3c0b9299cab4e898ec.

And probably requires a bug in rust-fil-proofs.

**Comment by solopine** [comment]
WinningPost can also fail if WinningPost machine uses readonly storage.

**Comment by TippyFlitsUK** [comment]
Hi @clinta 

Thanks for the report. I will add labels and will assign it to the right team for analysis.
We might tag you again for more information.
