### ISSUE TITLE
./lotus-storage-miner pledge-sector

### ISSUE THREAD

**Issue by IPSE-TEAM** [filecoin-project/lotus#930]
o such file or directory (os error 2)
github.com/filecoin-project/filecoin-ffi.GeneratePieceCommitmentFromFile
	/home/kunzhangs/workspace/filecoin/lotus/extern/filecoin-ffi/proofs.go:333
github.com/filecoin-project/lotus/lib/sectorbuilder.GeneratePieceCommitment
	/home/kunzhangs/workspace/filecoin/lotus/lib/sectorbuilder/simple.go:65
github.com/filecoin-project/lotus/storage.(*Miner).pledgeSector
	/home/kunzhangs/workspace/filecoin/lotus/storage/garbage.go:26
github.com/filecoin-project/lotus/storage.(*Miner).PledgeSector.func1
	/home/kunzhangs/workspace/filecoin/lotus/storage/garbage.go:120
runtime.goexit
	/usr/local/share/go/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*Miner).PledgeSector.func1
	/home/kunzhangs/workspace/filecoin/lotus/storage/garbage.go:122

**Comment by magik6k** [comment]
Please retry on testnet/3, and reopen if you're still seeing this issue
