### ISSUE TITLE
Power: 0 B / 120 TiB (0.0000%)     and     Power: 0 B / 122 TiB (0.0000%)

### ISSUE THREAD

**Issue by chengwds** [filecoin-project/lotus#933]
root@cheng-ipfs:~# lotus-storage-miner info
Miner: t01356
Sector Size: 32 GiB
Power: 0 B / 120 TiB (0.0000%)
Worker use:
	Local: 0 / 4 (+1 reserved)
	Remote: 0 / 1
Queues:
	AddPiece: 0
	PreCommit: 0
	Commit: 0
	Unseal: 0
Proving Period: Not Proving
Sectors:  map[Total:0]
root@cheng-ipfs:~# lotus-storage-miner info
Miner: t01356
Sector Size: 32 GiB
Power: 0 B / 122 TiB (0.0000%)
Worker use:
	Local: 0 / 4 (+1 reserved)
	Remote: 0 / 1
Queues:
	AddPiece: 0
	PreCommit: 0
	Commit: 0
	Unseal: 0
Proving Period: Not Proving
Sectors:  map[Total:0]

Power: 0 B / 120 TiB (0.0000%)     and     Power: 0 B / 122 TiB (0.0000%)

**Comment by magik6k** [comment]
You need to either accept deals, or store random data to gain power.

The latter can easily be done with `lotus-storage-miner pledge-sector`, which creates a random sector each time it's called, and starts sealing it in background.
