### ISSUE TITLE
`lotus state compute-state` broken (on master)

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#9332]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
$ ./lotus version
Daemon:  1.17.2-dev+mainnet+git.4abc38dac.dirty+api1.5.0
Local: lotus version 1.17.2-dev+mainnet+git.4abc38dac.dirty
```

### Describe the Bug

Running `lotus state compute-state` fails.

### Logging Information

```text
$ ./lotus state compute-state
ERROR: running cron: failed to unmarshal exectrace: t.GasCharges: array too large (103676)
```
```


### Repo Steps

1. Run './lotus state compute-state'

**Comment by jimpick** [comment]
I downgraded to commit for [Release v1.17.1](https://github.com/filecoin-project/lotus/releases/tag/v1.17.1) and it appears to be working there, so it looks like a recent regression:

```
$ ./lotus state compute-state
computed state cid:  bafy2bzacebkc5m7o5753vqwknvzmqp5wapjaxicpssnev6bp5adnx44t7xil2
$ ./lotus version
Daemon:  1.17.1+mainnet+git.8db6a939c.dirty+api1.5.0
Local: lotus version 1.17.1+mainnet+git.8db6a939c.dirty
```

**Comment by arajasek** [comment]
Thanks for the report! This is a regression introduced by the [FVM's new support for gas charge tracing](https://github.com/filecoin-project/ref-fvm/pull/709). It's just returning too much information in the ExecTrace for Go's CBOR code to unmarshal.

We can either look into increasing the limit (might already have happened in newer Cbor-gen code), or simply excluding this info for cron (which returns the most info).

**Comment by Pegasus-starry** [comment]
Hi, I use the release/v1.17.2 and the latest commit id is  c4901e998a7bf30ff2a251aac064b46dc30a17ee. but still meet this error:
