### ISSUE TITLE
1.17.1 and 1.17.2-rc1 mac (darwin) binary crashes on launch on M1: dyld[19175]: symbol not found in flat namespace (_hwloc_bitmap_alloc)

### ISSUE THREAD

**Issue by smagdali** [filecoin-project/lotus#9357]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
stefan@StefMacBookPro lotus_1.17.2-rc1_darwin_all % ./lotus
dyld[19124]: symbol not found in flat namespace (_hwloc_bitmap_alloc)
zsh: abort      ./lotus
stefan@StefMacBookPro lotus_1.17.2-rc1_darwin_all % 

I first observed this when upgrading via Homebrew, then tested the direct download. 1.17.0 was working fine. 

I can confirm that building 1.17.2-rc1 from source on M1 works fine.

Problem has existed at least since 08-31-2002 (when the launchpad lotus test cohort encountered it). I'm not sure which version they would have installed from.
```

### Describe the Bug

The downloadable mac binary of [1.17.2.-rc1](https://github.com/filecoin-project/lotus/releases/download/v1.17.2-rc1/lotus_1.17.2-rc1_darwin_all.tar.gz) crashes on launch. 

stefan@StefMacBookPro lotus_1.17.2-rc1_darwin_all % lotus --version
dyld[19175]: symbol not found in flat namespace (_hwloc_bitmap_alloc)
zsh: abort      lotus --version
stefan@StefMacBookPro lotus_1.17.2-rc1_darwin_all %

<img width="238" alt="image" src="https://user-images.githubusercontent.com/942675/191739052-42eb582a-d684-4e82-9716-26c2e34afa22.png">

### Logging Information

```text
client clashes on launch.
```

### Repo Steps

1. Download and unpack https://github.com/filecoin-project/lotus/releases/download/v1.17.2-rc1/lotus_1.17.2-rc1_darwin_all.tar.gz
2. Do 'lotus'
3. See error 'dyld[19124]: symbol not found in flat namespace (_hwloc_bitmap_alloc)'

**Comment by rjan90** [comment]
@ianconsolata I feel this is in your expertise area, do you know why this would happen?

**Comment by ianconsolata** [comment]
This issue was originally flagged on the homebrew-lotus project: https://github.com/filecoin-project/homebrew-lotus/issues/16, and I wanted to confirm it was an issue with the binary and not with homebrew so I asked Stef to run it manually as well.

I don't know what's causing it, and I haven't changed anything about the build process since 1.17.1, so I assume this regression is due to a change in the codebase. I think we should fix it before we release 1.17.2 final. @jennijuju do you know of anything hwloc related that changed between the 1.17.1 release and the 1.17.2-rc1 release? The solution I used to get M1 support was a bit brittle, so I'll prioritize getting a more robust process in place over the next month so code changes are less likely to break the build.

**Comment by smagdali** [comment]
I just tested https://github.com/filecoin-project/lotus/releases/tag/v1.17.1 - which also crashes so it looks like the bug was introduced between 1.17.0 and 1.71.1 not later.

**Comment by smagdali** [comment]
datapoint - this binary works fine on Intel macs.

**Comment by thedarkrai07** [comment]
I faced the same issue. Installed through source and it worked

**Comment by ianconsolata** [comment]
This works for these releases, but future releases will still likely fail until https://github.com/filecoin-project/lotus/issues/9422 is done. Since this issue is specific to those releases, we can close for now.
