### ISSUE TITLE
Test FIP0045

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9371]
A list of tests that should be performed to make sure deal making still work as expected with the new datacap flow:

- [ ] add.

(test should be performed on both devnet and butterfly with scale. i.e with batch PSD aggregation PC and such )

**Comment by jennijuju** [comment]
@Reiers this should be our next video priority. We should do
-  a high-level fip0045 introduction with concepts explanation
- guides for client
- guides for storage provider

**Comment by rjan90** [comment]
**Check that current FIL+ related command functions as expected:**
- [ ] lotus filplus grant-datacap
- [ ] lotus filplus list-notaries
- [ ] lotus filplus list-clients
- [ ] lotus filplus check-client-datacap
- [ ] lotus filplus check-notary-datacap
- [ ] lotus filplus sign-remove-data-cap-proposal
- [ ] ./lotus-shed verifreg add-verifier
- [ ] ./lotus-shed verifreg add-verifier-from-account 
- [ ] ./lotus-shed verifreg remove-verified-client-data-cap

**Client side:**
- [ ] Send a verified storage deal:
- [ ] Send a batch of verified storage deals:
- [ ] Send a mixed batch of verified storage deals and regular deals

**Storage Provider side:**
- [ ] Get a verified storage deal, seal and confirm that it gets QAP
- [ ] Get a verified storage deal + regular storage deal in the same sector, seal and confirm that it gets QAP accordingly
- [ ] Get multiple verified storage deals, batch precommits and aggregate commits and confirm that sectors gets QAP
- [ ] Get a mixed bag of regular and verified storage deals, batch precommits and aggregate commits and confirm that the sectors get QAP
- [ ] Extend a sector that contains a FIL+ deal and check that the extension works (check both renew and extend commands)
- [ ] Extend a sector that contains both FIL+ and regular deals, and check that the extension works (check both renew and extend commands)
- [ ] Batch Extend multiple FIL+ sectors and check that the extension works (check both renew and extend commands)

**Check that new FIL+ related commands functions as expected:**
- [ ] lotus filplus remove-expired-claim
- [ ] lotus filplus remove-expired-allocation

Need further investigation:
How the [FIP0045 Deal Packing](https://github.com/filecoin-project/lotus/issues/9276) effects SnapDeals, and confirm/check that the current configurations still applies.

**Comment by rjan90** [comment]
FIP0045-testing:

- [ ] lotus filplus grant-datacap
- [x] lotus filplus list-notaries
   ```
   lotus filplus list-notaries
   t01006: 10000000
   t081: 0
   ```
- [ ] lotus filplus list-clients
- [ ] lotus filplus check-client-datacap
- [ ] lotus filplus check-notary-datacap
- [ ] lotus filplus sign-remove-data-cap-proposal
- [x] ./lotus-shed verifreg add-verifier
   - bafy2bzacediank33mkgdj52qyjrxenkdytfrggl6lu2yxlx3mlxuawageiqfe
- [ ] ./lotus-shed verifreg add-verifier-from-account 
- [ ] ./lotus-shed verifreg remove-verified-client-data-cap

**Client side:**
- [ ] Send a verified storage deal:
- [ ] Send a batch of verified storage deals:
- [ ] Send a mixed batch of verified storage deals and regular deals

**Storage Provider side:**
- [ ] Get a verified storage deal, seal and confirm that it gets QAP
- [ ] Get a verified storage deal + regular storage deal in the same sector, seal and confirm that it gets QAP accordingly
- [ ] Get multiple verified storage deals, batch precommits and aggregate commits and confirm that sectors gets QAP
- [ ] Get a mixed bag of regular and verified storage deals, batch precommits and aggregate commits and confirm that the sectors get QAP
- [ ] Extend a sector that contains a FIL+ deal and check that the extension works (check both renew and extend commands)
- [ ] Extend a sector that contains both FIL+ and regular deals, and check that the extension works (check both renew and extend commands)
- [ ] Batch Extend multiple FIL+ sectors and check that the extension works (check both renew and extend commands)

**Check that new FIL+ related commands functions as expected:**
- [ ] lotus filplus remove-expired-claim
- [ ] lotus filplus remove-expired-allocation

_Need further investigation:_
How the [FIP0045 Deal Packing](https://github.com/filecoin-project/lotus/issues/9276) effects SnapDeals, and confirm/check that the current configurations still applies.
We should probably test SnapDeals with different values for these configurations:
```
#MinUpgradeSectorExpiration = 0
#MinTargetUpgradeSectorExpiration = 0
```

**Comment by ianconsolata** [comment]
Is this something that should be turned into an automated testing flow?

**Comment by jennijuju** [comment]
> Is this something that should be turned into an automated testing flow?

would be cool yes! or just integration tests (we probably have some already
