### ISSUE TITLE
[ Help ] - ho to encode data for a signature

### ISSUE THREAD

**Issue by fabriziogianni7** [filecoin-project/lotus#9374]
hey guys,
wondering how to correctly encode data for this signature here (datacap removal notaries signature) ---> https://github.com/filecoin-project/lotus/blob/ba89d2ccac4ff8621cc78906f3f102317313f2b8/cli/filplus.go#L392

I need to replicate this flow in JS, what should be the correct way?
any help here ? thank you very much

**Comment by fabriziogianni7** [comment]
tagging @geoff-vball here since he checked this file a few days ago. thanks for any help :)

**Comment by fabriziogianni7** [comment]
doing smt like this:
```
 const fil_removedatacap_buffer = Buffer.from("fil_removedatacap:")
      const obj =
      {
        verifiedClient,
        datacapAmount,
        removalProposalID: 1,
      }

      const cb = cbor.encode(obj)
      console.log('cb ',cb)
      const conct = Buffer.concat([fil_removedatacap_buffer,cb])



      const bytesToSign = []
      for (const i of conct) { bytesToSign.push(i) }

      // // sign the bytes
      const signResult = await this.client.walletSign(notary, bytesToSign)

      const bf= Buffer.from(signResult.Data, 'base64')
      console.log(bf)

      const cc = Buffer.concat([typeAsBuffer, dataAsBuffer])
      return toHexString(cc)
      ```
      
      it seems not working tho

**Comment by geoff-vball** [comment]
@fabriziogianni7 What is not working, exactly?

**Comment by fabriziogianni7** [comment]
well, basially if I sign through the cli, I get something different than if I do it with my js interface..
from js I get: `014452798bfe4f187dd6db6578f6a37bec3416c7c20d0e229b8b1692029ec3fabe5fa5dccae9ce658863fd9cd55e35e845431911875046b06ea4c9ea82d7b7cdea00`
from cli I get: `013365a256051f6b61e15f38c4f3c4dbec87f5bf2545d9191f50a1972852ea695b3949ce4f26340d96eef9a0f2a959ee38fc80462c2dcab1191545952c051e073601`
signResult is 
```
{
  Type: 1,
  Data: 'RFJ5i/5PGH3W22V49qN77DQWx8INDiKbixaSAp7D+r5fpdzK6c5liGP9nNVeNehFQxkRh1BGsG6kyeqC17fN6gA='
}
```

any thought?
do you know if there is something I can use to just sign something using custom parameters?
Because right now I use [filecoin signing tools](https://github.com/Zondax/filecoin-signing-tools) and I have some method to sign _messages_ , but as far as I know, there is anything to sign custom parameters like in this case where the notary has to sign just _client address, datacap to remove and ID_

**Comment by geoff-vball** [comment]
@fabriziogianni7 I looked through the signing tools and as far as I can tell, there is no method for signing arbitrary bytes. The implementation in lotus can be found here. https://github.com/filecoin-project/lotus/blob/d11248b9989174599e7472306f3f99cd6f8d68b9/lib/sigs/sigs.go#L18

Sorry but I'm not super knowledgeable about our tooling so I can't really point you in any good direction.

**Comment by fabriziogianni7** [comment]
yeah, thank you geo,
i guess is just matter of getting the right bytes and then sign using the api method.
