### ISSUE TITLE
Lotus 1.17.1 macOS Monterey v12.6 (chip m1 pro) - fail on launch: dyld[41083]: symbol not found in flat namespace (_hwloc_bitmap_alloc)

### ISSUE THREAD

**Issue by BTT21000** [filecoin-project/lotus#9381]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
https://github.com/filecoin-project/lotus/releases/download/v1.17.1/lotus_1.17.1
```

### Describe the Bug

The lotus version 1.17.1 installed with Homebrew crashes on launch & version check on macOS Monterey v12.6 (chip m1 pro):

:~ xxxx$ brew install lotus
==> Downloading https://github.com/filecoin-project/lotus/releases/download/v1.17.1/lotus_1.17.1
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/75fc9a64b93bfa7f2fe476f6b35478cfef6f07dd4ae977bab197ffd57610dc8a--lotus_1.17.1_darwin_all.tar.gz
==> Installing lotus from filecoin-project/lotus
🍺  /opt/homebrew/Cellar/lotus/1.17.1: 5 files, 778.5MB, built in 4 seconds
==> Running `brew cleanup lotus`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
:~ xxxx$ lotus -v
dyld[40836]: symbol not found in flat namespace (_hwloc_bitmap_alloc)
Abort trap: 6

### Logging Information

```text
client clashes on launch

dyld[41083]: symbol not found in flat namespace (_hwloc_bitmap_alloc)
Abort trap: 6
```

### Repo Steps

1. Run `brew install lotus`
2. Do `lotus -v`
3. See error `dyld[40836]: symbol not found in flat namespace (_hwloc_bitmap_alloc)
Abort trap: 6`
...

**Comment by geoff-vball** [comment]
Closing as duplicate
