### ISSUE TITLE
Chain sync slow

### ISSUE THREAD

**Issue by pfista** [filecoin-project/lotus#943]
**Describe the bug**
Unable to complete chain sync, it exponentially slows as it reaches the current block height. 

> lotus sync status
sync status:
worker 0:
        Base:   [bafy2bzaceaxxuwhafbawu73j4byhp7h5lrblgdhoja2eiljpweujoj5lwf5cc]
        Target: [bafy2bzacedzlq6sa45x37edejkkj57fav5q652jpkp5tzoovooyma4mhav6lq bafy2bzacecrltbnblijunfdorgyuznrzkfyawjonpjwltc5dx2in5o5f6jn2k] (5959)
        Height diff:    5959
        Stage: message sync
        Height: 5596
        Elapsed: 52h14m22.562352918s

In the 52 hours it took to sync to 5596 the chain size doubled. 

**To Reproduce**
1. Run `lotus sync wait`

**Expected behavior**
Chain to sync in a few hours.

**Version (run `lotus --version`):**
lotus version 0.1.1+gita73a698a

**Additional context**

Running this on digital ocean:
 1 GB Memory / 25 GB Disk + 50 GB / SFO2 - Ubuntu 18.04.3 (LTS) x64
+ 
~50GB Swap Memory

**Comment by whyrusleeping** [comment]
Yeah, i'm actively investigating this. Right now the top culprits are bls signature validation, and PoRep validation. GetRandomness calls were a bit slow too, but i PRed a fix earlier today that makes them no longer show up in the profile.

I have the proofs team investigating why the PoRep validation is so slow, hoping that gets better soon.

Then theres BLS... Theres a small amount of that we can parallelize, but i'm beginning to think that the space savings we get from it isnt worth the 100x verification cost.

**Comment by whyrusleeping** [comment]
the proofs have gotten a small amount faster on verification, still not great though. The getrandomness calls are improved, but still have some bad cases i need to address. And I just merged a PR that defaults new keys created to be secpk, which should help quite a bit.

I'm going to keep this issue open, because I still expect sync speed to be subpar, none of the fixes so far are '10x' improvements.

**Comment by jingniao** [comment]
sync still slow for last testnet
is any progress for perf?

**Comment by arajasek** [comment]
sync is now pretty fast, and definitely keeps up with the chain.
