### ISSUE TITLE
lotus-miner failed

### ISSUE THREAD

**Issue by AYDIN23** [filecoin-project/lotus#9443]
### Discussed in https://github.com/filecoin-project/lotus/discussions/9442

<div type='discussions-op-text'>

<sup>Originally posted by **AYDIN23** October  6, 2022</sup>
I am in the stage of sector pledge and I made 19 sectors until now. 
I had to format and re-partition one of the NVME drives to create a swap partition. 
Now when I run Lotus-miner I get error.

ERROR: creating node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules".HandleDeals (/home/aydin/lotus/node/modules/storageminer.go:308): failed to build storagemarket.StorageProvider: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build *storedask.StoredAsk: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build storagemarket.StorageProviderNode: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build *sectorblocks.SectorBlocks: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build sectorblocks.SectorBuilder: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build *storage.Miner: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build sectorstorage.SectorManager: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build *sectorstorage.Manager: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build *stores.Local: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): opening path : unmarshalling storage metadata for : invalid character '"' after object key:value pair

I dont know what to do. </div>

**Comment by Reiers** [comment]
Hi @AYDIN23 

Thanks for the report. The issue you are experiencing lies elsewhere.

Moving it back Lotus Discussions https://github.com/filecoin-project/lotus/discussions/9442 for help and troubleshooting. 

Closing Lotus issue ticket.
