### ISSUE TITLE
Daemon hanging with splitstore compaction error

### ISSUE THREAD

**Issue by Nayhol** [filecoin-project/lotus#9448]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.17.1+mainnet+git.8db6a939c.dirty
```

### Describe the Bug

We noticed miners failing their proving deadlines and determined that the daemon was out of sync.
"Lotus sync wait" revealed that the diff was exceptionally low, but there were no updates to the sync and that we were not seeing a "Done!" message in a reasonable time given that the daemon was previously synced to the chain.

We restarted the daemon process and it started back up again as normal.

### Logging Information

```text
{"level":"error","ts":"2022-10-07T05:51:14.898Z","logger":"splitstore","caller":"splitstore/splitstore_compact.go:535","msg":"COMPACTION ERROR: error marking: error walking block (cid: bafy2bzacedgykslhqrtegrqnutrvkwces6h6xb2jng25m4x2rqjwiakdhwevm): error walking state root (cid: bafy2bzacedqe4f5mian6vk6z3cjymf4waj2okni6ew6apwbbxpn4ipes6par6): error walking link (cid: bafy2bzacedhs7zk2plqj2hvjrf7ed2vdjitudzvek2fjdk5wuuwnchwhrb7le): error walking link (cid: bafy2bzacedcynrzhbc2b46xn4hzvoxblswgvw7avzcpbxvf4utuwrrzmzmiwi): error walking link 
(cid: bafy2bzacedn4vsuxxbryeh56evc6wqolynelcsfnqvo7o5eelth6jnqpk6a4c): error walking link (cid: bafy2bzaceaumrcbw2hinrewl2la44mam7cbj7zrfyjo2kf2cdwqwo7fmln4ha): error walking link (cid: bafy2bzaceay2uv3pa4i6xehabh6ldq6
kr4swceuhdtwfzaax7r3do4fjajb54): error walking link (cid: bafy2bzacedtfrwk4ukbajcjo7r47a3jenr5udndctfewefdz5gdlqlfmmf7m6): error walking link (cid: bafy2bzacecexsyuidfvj4fatwzobcuyb4mgb6pegv75diawzkifajro7cpham): error walking link (cid: bafy2bzacea3s2b5grvztryurevmhr3gjea3yqm2miq6ql7g4hzwvp6aarfrq4): error walking link (cid: bafy2bzacedh5wj3s6zrfktsi4l7m7aoc2gwpuif46eq76leddr2j73fyt55qs): error walking link (cid: bafy2bzaceai3khxcg
df6rejvm42k4ytxcawofyhiwfmdbqbaz43ktm745yuew): error walking link (cid: bafy2bzaceco56bwxnglfugi7mphgjz2jhv5v
iyjzqaqoc3yjbc3vnilwseaew): splitstore is closing"}
{"level":"info","ts":"2022-10-07T05:51:14.898Z","logger":"splitstore","caller":"splitstore/splitstore_compact
.go:134","msg":"compaction done","took":407.038182383}
{"level":"error","ts":"2022-10-07T05:51:15.605Z","logger":"statetree","caller":"state/statetree.go:283","msg"
:"failed to load state tree: failed to load hamt node: badger blockstore closed"}
{"level":"warn","ts":"2022-10-07T05:51:15.605Z","logger":"rpc","caller":"go-jsonrpc@v0.1.5/handler.go:279","m
sg":"error in RPC call to 'Filecoin.StateSectorGetInfo': (get sset) failed to load miner actor:\n    github.com/filecoin-project/lotus/chain/stmgr.MinerSectorInfo\n        /home/filecoin/lotus/chain/stmgr/actors.go:109\n  - load state tree:\n    github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).ParentState\n        /home/filecoin/lotus/chain/stmgr/read.go:28\n  - failed to load state tree bafy2bzacedqe4f5mian6vk6z3cjymf4
waj2okni6ew6apwbbxpn4ipes6par6:\n    github.com/filecoin-project/lotus/chain/state.LoadStateTree\n        /home/filecoin/lotus/chain/state/statetree.go:284\n  - failed to load hamt node:\n    github.com/filecoin-project/specs-actors/actors/util/adt.AsMap\n        /home/filecoin/go/pkg/mod/github.com/filecoin-project/specs-act
ors@v0.9.15/actors/util/adt/map.go:41\n  - badger blockstore closed"}
{"level":"error","ts":"2022-10-07T05:51:15.613Z","logger":"statetree","caller":"state/statetree.go:283","msg"
:"failed to load state tree: failed to load hamt node: badger blockstore closed"}
{"level":"warn","ts":"2022-10-07T05:51:15.613Z","logger":"rpc","caller":"go-jsonrpc@v0.1.5/handler.go:279","msg":"error in RPC call to 'Filecoin.StateSectorGetInfo': (get sset) failed to load miner actor:\n    github.com/filecoin-project/lotus/chain/stmgr.MinerSectorInfo\n        /home/filecoin/lotus/chain/stmgr/actors.go:109\n  - load state tree:\n    github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).ParentState\n        /home/filecoin/lotus/chain/stmgr/read.go:28\n  - failed to load state tree bafy2bzacedqe4f5mian6vk6z3cjymf4waj2okni6ew6apwbbxpn4ipes6par6:\n    github.com/filecoin-project/lotus/chain/state.LoadStateTree\n        /home/filecoin/lotus/chain/state/statetree.go:284\n  - failed to load hamt node:\n    github.com/filecoin-project/specs-actors/actors/util/adt.AsMap\n        /home/filecoin/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.15/actors/util/adt/map.go:41\n  - badger blockstore closed"}
{"level":"error","ts":"2022-10-07T05:51:15.625Z","logger":"statetree","caller":"state/statetree.go:283","msg":"failed to load state tree: failed to load hamt node: badger blockstore closed"}
```

### Repo Steps

Can't easily reproduce.

**Comment by rjan90** [comment]
@Nayhol Can you also add your SplitStore configuration?

**Comment by Nayhol** [comment]
[Chainstore]
EnableSplitstore = true
ColdStoreType = "discard"

**Comment by Reiers** [comment]
I have been running with the same config for months now without any issues, even on release candidates. 
```
[Chainstore]
  # type: bool
  # env var: LOTUS_CHAINSTORE_ENABLESPLITSTORE
   EnableSplitstore = true

  [Chainstore.Splitstore]
    # ColdStoreType specifies the type of the coldstore.
    # It can be "universal" (default) or "discard" for discarding cold blocks.
    #
    # type: string
    # env var: LOTUS_CHAINSTORE_SPLITSTORE_COLDSTORETYPE
     ColdStoreType = "discard"
```

- How many peers do you have?
- What hardware specs does the full node have?
- What kind of disk is chain on? 
- Is the `config.toml` up to date? Compare the output of `lotus config default`

//Side questions:

- Do you stop the daemon with ctrl+c or use lotus daemon stop?
- Are you running it as a service?

**Comment by ZenGround0** [comment]
It looks like the splitstore is being shut down for some external reason which then shuts down compaction.  My hypothesis is that this does not originate from the splitstore.   Could you share the logs leading up to the splitstore failure?

**Comment by Nayhol** [comment]
Immediately before the compaction failure:

`{"level":"warn","ts":"2022-10-07T05:51:06.541Z","logger":"rpc","caller":"go-jsonrpc@v0.1.5/handler.go:279","m
sg":"error in RPC call to 'Filecoin.StateSectorExpiration': failed to find sector 30653:\n    github.com/filecoin-project/lotus/chain/actors/builtin/miner.(*state8).GetSectorExpiration\n        /home/filecoin/lotus/cha
in/actors/builtin/miner/v8.go:192"}
{"level":"warn","ts":"2022-10-07T05:51:06.544Z","logger":"rpc","caller":"go-jsonrpc@v0.1.5/handler.go:279","msg":"error in RPC call to 'Filecoin.StateSectorExpiration': failed to find sector 31191:\n    github.com/file
coin-project/lotus/chain/actors/builtin/miner.(*state8).GetSectorExpiration\n        /home/filecoin/lotus/cha
in/actors/builtin/miner/v8.go:192"}
{"level":"warn","ts":"2022-10-07T05:51:09.378Z","logger":"rpc","caller":"go-jsonrpc@v0.1.5/handler.go:279","msg":"error in RPC call to 'Filecoin.MpoolPush': message from f3qt3fbn6s4zu5gzp2j4xmg3oxnjzlsghgcui2rpvsygczon
xtqjl5z24y4vnkfrigriuquc5srofihibdzeqa with nonce 142 already in mpool, increase GasPremium to 10144337 from 7500000 to trigger replace by fee:\n    github.com/filecoin-project/lotus/chain/messagepool.(*msgSet).add\n  
      /home/filecoin/lotus/chain/messagepool/messagepool.go:272\n  - replace by fee has too low GasPremium"}
{"level":"warn","ts":"2022-10-07T05:51:09.843Z","logger":"rpc","caller":"go-jsonrpc@v0.1.5/handler.go:279","msg":"error in RPC call to 'Filecoin.StateSectorExpiration': failed to find sector 31849:\n    github.com/filecoin-project/lotus/chain/actors/builtin/miner.(*state8).GetSectorExpiration\n        /home/filecoin/lotus/cha
in/actors/builtin/miner/v8.go:192"}
{"level":"warn","ts":"2022-10-07T05:51:09.847Z","logger":"rpc","caller":"go-jsonrpc@v0.1.5/handler.go:279","m
sg":"error in RPC call to 'Filecoin.StateSectorExpiration': failed to find sector 31852:\n    github.com/filecoin-project/lotus/chain/actors/builtin/miner.(*state8).GetSectorExpiration\n        /home/filecoin/lotus/cha
in/actors/builtin/miner/v8.go:192"}`

...

`{"level":"warn","ts":"2022-10-07T05:51:12.748Z","logger":"rpc","caller":"go-jsonrpc@v0.1.5/handler.go:279","m
sg":"error in RPC call to 'Filecoin.StateSectorExpiration': failed to find sector 32172:\n    github.com/filecoin-project/lotus/chain/actors/builtin/miner.(*state8).GetSectorExpiration\n        /home/filecoin/lotus/cha
in/actors/builtin/miner/v8.go:192"}
{"level":"warn","ts":"2022-10-07T05:51:14.570Z","logger":"builder","caller":"node/shutdown.go:31","msg":"rece
ived shutdown","signal":"interrupt"}
{"level":"warn","ts":"2022-10-07T05:51:14.570Z","logger":"builder","caller":"node/shutdown.go:36","msg":"Shut
ting down..."}
{"level":"info","ts":"2022-10-07T05:51:14.571Z","logger":"builder","caller":"node/shutdown.go:44","msg":"rpc server shut down successfully "}
{"level":"warn","ts":"2022-10-07T05:51:14.572Z","logger":"events","caller":"events/observer.go:61","msg":"listenHeadChanges quit"}
{"level":"info","ts":"2022-10-07T05:51:14.572Z","logger":"dt-impl","caller":"impl/impl.go:170","msg":"stop data-transfer module"}
{"level":"warn","ts":"2022-10-07T05:51:14.572Z","logger":"events","caller":"events/observer.go:66","msg":"not restarting listenHeadChanges: context error: context canceled"}
{"level":"warn","ts":"2022-10-07T05:51:14.572Z","logger":"events","caller":"events/observer.go:61","msg":"listenHeadChanges quit"}
{"level":"warn","ts":"2022-10-07T05:51:14.572Z","logger":"events","caller":"events/observer.go:66","msg":"not restarting listenHeadChanges: context error: context canceled"}
{"level":"warn","ts":"2022-10-07T05:51:14.572Z","logger":"sub","caller":"sub/incoming.go:435","msg":"error from message subscription: context canceled"}
{"level":"warn","ts":"2022-10-07T05:51:14.572Z","logger":"sub","caller":"sub/incoming.go:437","msg":"quitting HandleIncomingMessages loop"}
{"level":"warn","ts":"2022-10-07T05:51:14.572Z","logger":"sub","caller":"sub/incoming.go:55","msg":"quitting HandleIncomingBlocks loop"}
{"level":"error","ts":"2022-10-07T05:51:14.572Z","logger":"market_adapter","caller":"market/fundmanager.go:585","msg":"waiting for results of message bafy2bzacedsxqnfumpt5g32dwjr263zmu7uwiqcudi6hgnjwkm2nwklfxmc5g for addr f01208189: context canceled"}
{"level":"warn","ts":"2022-10-07T05:51:14.572Z","logger":"peermgr","caller":"peermgr/peermgr.go:154","msg":"closing peermgr done"}
{"level":"warn","ts":"2022-10-07T05:51:14.572Z","logger":"peermgr","caller":"peermgr/peermgr.go:172","msg":"exiting peermgr run"}
{"level":"warn","ts":"2022-10-07T05:51:14.572Z","logger":"chainstore","caller":"store/store.go:615","msg":"reorgWorker quit"}
{"level":"warn","ts":"2022-10-07T05:51:14.573Z","logger":"splitstore","caller":"splitstore/splitstore.go:790","msg":"close with ongoing compaction in progress; waiting for it to finish..."}
{"level":"info","ts":"2022-10-07T05:51:14.573Z","logger":"pubsub","caller":"go-libp2p-pubsub@v0.7.1/pubsub.go:639","msg":"pubsub processloop shutting down"}`

**Comment by Nayhol** [comment]
> * How many peers do you have?

Anywhere from 99 to 173.
I am trying to do a "lotus net ping" command across peers the peer list and can't seem to get a positive ping. Not sure if that's the fault of the command or my usage of the command or not.

> * What hardware specs does the full node have?

Ryzen 3600 with 128GB RAM

> * What kind of disk is chain on?

Nvme SSD

> * Is the `config.toml` up to date? Compare the output of `lotus config default`

> * Do you stop the daemon with ctrl+c or use lotus daemon stop?

We use scripts to start up and shutdown the daemon. 
> * Are you running it as a service?

as in systemd service? no. It's actually a bit of a hassle to run lotus via systemd. For a start it defaults to running as root (security issues) and managing environment variables outside of a config file is a real pain. We'd have to keep playing with the unit files.

**Comment by ZenGround0** [comment]
The problem looks like lotus got a shutdown signal that you didn't expect or want

```
07T05:51:14.570Z","logger":"builder","caller":"node/shutdown.go:31","msg":"rece ived shutdown","signal":"interrupt"} {"level":"warn","ts":"2022-10-07T05:51:14.570Z","logger":"builder","caller":"node/shutdown.go:36","msg":"Shut ting down..."}
```

This signal happened at `5:51:14.571Z` immediately before the splitstore error at `5:51:14.898Z`.  The splitstore message is just what you would expect if lotus was shutdown during a splitstore compaction.  There might be more to dig into regarding the unexpected shutdown but I don't think there's any indication this issue was caused by splitstore

**Comment by piknikSteven2021** [comment]
We are also seeing the same issue. So far only our v1.17 daemons have had the issue, but v1.16 have had no issues.

**Comment by marco-storswift** [comment]
We are also seeing the same issue

**Comment by marco-storswift** [comment]
https://github.com/filecoin-project/lotus/issues/9743

**Comment by piknikSteven2021** [comment]
`~$ lotus sync status
sync status:
worker 14:
        Base:   [bafy2bzacear37m5nnpcf5ktphnqs4yulnrqus2acyzdvnwuvyct77jaksfr4s bafy2bzaceatwvws4hvvn5vzjyohg4w23brov6blw7m5vwgd2d4i2w5dalfsl2 bafy2bzacebadroivbph6tsedffa6qlxcmuwpdewxbwcr235635jjg4bhu6bua bafy2bzacecxnu7fiq3k2ztt5n2hiueg5izi2phmksp62tqwxpoh4rtk3cwofc bafy2bzacec5jhiv6wgtw54in5uang3icwvghxmxmndhvgs7w3ruojgalz2ozo]
        Target: [bafy2bzaced7mhm5qj4fsmmkq36u4jcothiig6qars637jtskum2hflhl7n3wy] (2378691)
        Height diff:    8
        Stage: complete
        Height: 2378691
        Elapsed: 58.300371358s
worker 17:
        Base:   [bafy2bzaceanenmlrl4566brjco3pcndx4ybcj4pfh6xrnrzwwp5vqivjeqhs2 bafy2bzacebgvv2qvkj3sabfm3j2djzxx77b2b2x4b3pkxjg4udgohzkiezuas bafy2bzacebfagg3r7y3maw4i65s7lorktjubkldcnf2k5xi2vnzhyhm3gqbvy bafy2bzaced33mgyfwz2tczjxkmyvlsrok7mk73xsxlxx23oqhxbhrvf4hwdr4]
        Target: [bafy2bzacedjw37yfilzeuo73vvjwl3ktxjhnbb4mkwqgtamhmx7gfmhdsuygi] (2378692)
        Height diff:    2
        Stage: complete
        Height: 2378692
        Elapsed: 14.43745351s
worker 18:
        Base:   [bafy2bzaceanenmlrl4566brjco3pcndx4ybcj4pfh6xrnrzwwp5vqivjeqhs2 bafy2bzacebgvv2qvkj3sabfm3j2djzxx77b2b2x4b3pkxjg4udgohzkiezuas bafy2bzacebfagg3r7y3maw4i65s7lorktjubkldcnf2k5xi2vnzhyhm3gqbvy bafy2bzaced33mgyfwz2tczjxkmyvlsrok7mk73xsxlxx23oqhxbhrvf4hwdr4]
        Target: [bafy2bzacecypru5ubut3c4vnlq725kfap723omjyp5seuu4pddjauntjhw7te] (2378692)
        Height diff:    2
        Stage: complete
        Height: 2378692
        Elapsed: 14.401727961s
worker 19:
        Base:   [bafy2bzacecef2acn5ynzqysnro6jng5fabh37ie3mnz2536hqzu4adl7ua6wa]
        Target: [bafy2bzacebxb3vsv3x6sj54vkwwtqjleoxcztnkltynjcbnu5h4tngjn457qa] (2378693)
        Height diff:    2
        Stage: message sync
        Height: 2378691
        Elapsed: 19h27m29.555407089s
worker 20:
        Base:   [bafy2bzaced7mhm5qj4fsmmkq36u4jcothiig6qars637jtskum2hflhl7n3wy bafy2bzacecef2acn5ynzqysnro6jng5fabh37ie3mnz2536hqzu4adl7ua6wa bafy2bzaceas6srwzg5cmyblnnuk6xspg6yrrouj4jkqetnoad3dsp4bnb7e6i]
        Target: [bafy2bzacecez6z7mvif6klslqjlrincipp6kdumwnvozfznpjchwlw2zej5d6] (2378693)
        Height diff:    2
        Stage: message sync
        Height: 2378692
        Elapsed: 19h27m29.550017531s
worker 21:
        Base:   [bafy2bzaced7mhm5qj4fsmmkq36u4jcothiig6qars637jtskum2hflhl7n3wy bafy2bzacecef2acn5ynzqysnro6jng5fabh37ie3mnz2536hqzu4adl7ua6wa bafy2bzaceas6srwzg5cmyblnnuk6xspg6yrrouj4jkqetnoad3dsp4bnb7e6i]
        Target: [bafy2bzacecpn6nn5biexh6ir6i4ovc4fe7iao4wvddloakynwko47bnmidti2] (2378693)
        Height diff:    2
        Stage: message sync
        Height: 2378692
        Elapsed: 19h27m29.528353308s
worker 22:
        Base:   [bafy2bzacea42dma22mu5pmoclt6gj25k3yebavef6ccbbk6swdngllmeukd5i bafy2bzacecyzo5nk2yvykc7twqe4acvcun6i5zq7gxep5pdajcrswi57ibdim bafy2bzacecypru5ubut3c4vnlq725kfap723omjyp5seuu4pddjauntjhw7te bafy2bzacedjw37yfilzeuo73vvjwl3ktxjhnbb4mkwqgtamhmx7gfmhdsuygi]
        Target: [bafy2bzacea5k7z3iwgkyvu3kupjci3wlhc65g7fi6vaf6agetdzfjdmzc7ops] (2378693)
        Height diff:    1
        Stage: message sync
        Height: 2378692
        Elapsed: 19h27m21.996754979s
worker 23:
        Base:   [bafy2bzacea42dma22mu5pmoclt6gj25k3yebavef6ccbbk6swdngllmeukd5i bafy2bzacecyzo5nk2yvykc7twqe4acvcun6i5zq7gxep5pdajcrswi57ibdim bafy2bzacecypru5ubut3c4vnlq725kfap723omjyp5seuu4pddjauntjhw7te bafy2bzacedjw37yfilzeuo73vvjwl3ktxjhnbb4mkwqgtamhmx7gfmhdsuygi]
        Target: [bafy2bzaced7jc5zt6352emtejawrbid5efhf3w2veozvnoettfsu46dsgxm36] (2378693)
        Height diff:    1
        Stage: message sync
        Height: 2378692
        Elapsed: 19h27m21.993888532s`
        
        
This is still present in v1.18

**Comment by rjan90** [comment]
Closing this issue as outdated now, given that SplitStore has gone through numerous iterations/enhancements/bugfixes since this issue-report. If you encounter any issues with regards to SplitStore in newer versions of Lotus, please open up a new issue report.
