### ISSUE TITLE
Deal packing logic update for snapping 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9453]
like #9276  - we also need to update the logic when assign new deals to `Available` sectors according to the sector expiration date and the deal term

this might  be the time we consider, instead of requiring users to extend the sector for a random period, BUT we assign the deal to the sector, and extend the sector to the most beneficial duration according to the datacap term on the fly

**Comment by jennijuju** [comment]
I mean data cap term. Which is decoupled from deal term (covers deal duration but can go beyond)

**Comment by jennijuju** [comment]
That was covered in another issue and pr is up already - see the description

**Comment by jennijuju** [comment]
Which logic? The auto extend?

**Comment by magik6k** [comment]
I don't think extending sectors on-the-fly will make economic sense, given that those extend messages would have very few sectors in them, making them very expensive for limited benefit.

The TermMin~TermMax window is only 90 days, which isn't that long, it's probably better for the sealing logic to just aim for a sector with highest allowable expiration - this is captured in https://github.com/filecoin-project/lotus/pull/9412 in this comment: https://github.com/filecoin-project/lotus/pull/9412/files#diff-9f01bacdba70c8974f5857f18218d219c8e04e31c7166c52b0b43781e7368b69R725-R728.

(the behavior of picking sectors with highest working expiration can be achieved by setting the `TargetExpiration` in miner config to a high value)

**Comment by jennijuju** [comment]
@magik6k okay so you are saying the AP assignment was covered for snapdeal as well?

the potential issue I can see with the existing TargetExpiration to be set too high, is its gonna easily exceed the term max, and we will end up failing finding any Available sector that can snap on  and create a new sector for that deal.

I don’t have a strong opinion- tho I’d like @filecoin-project/lotus-tse to advice here

**Comment by magik6k** [comment]
> AP assignment was covered for snapdeal as well

Yes, that's what all the pendingPieceEpochBounds/findBound logic in #9412 is for.

> potential issue I can see with the existing TargetExpiration to be set too high, is its gonna easily exceed the term max

Assigning logic only pays attention to TargetExpiration after we've found at least one sector which can be fully filled with queued deals based on TermMin/Max bounds

**Comment by jennijuju** [comment]
i can really something like this https://github.com/filecoin-project/lotus/issues/9453#issuecomment-1274729472 😉

**Comment by arajasek** [comment]
Sounds like this is no longer needed for nv17.

**Comment by jennijuju** [comment]
@magik6k i think we should do a full audit on snap deal packing -  so here https://filecoinproject.slack.com/archives/CP50PPW2X/p1666042100533989?thread_ts=1666012236.383589&channel=CP50PPW2X&message_ts=1666042100.533989
