### ISSUE TITLE
make lotus-fountain failed with go version 1.19.2 

### ISSUE THREAD

**Issue by beatyman** [filecoin-project/lotus#9456]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus 1.17.2 releases
```

### Describe the Bug

![image](https://user-images.githubusercontent.com/16757974/194732849-af84e8c0-fea4-4653-8330-d048a69b1daa.png)
go version 1.18.1 works ok , 1.19.2 make failed

### Logging Information

```text
go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.48225944d" -o lotus-fountain ./cmd/lotus-fountain
go run github.com/GeertJohan/go.rice/rice append --exec lotus-fountain -i ./cmd/lotus-fountain -i ./build
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x56dc06]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc00018ecc0?, {0xc000313400?, 0x70?, 0x7fb4d3a05fff?}, 0x7fb4d381ad00?)
	<autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0x6847f8, 0xc000227280}, 0xa680)
	/usr/local/go/src/archive/zip/reader.go:526 +0xf5
archive/zip.(*Reader).init(0xc0002987e0, {0x6847f8?, 0xc000227280}, 0xa680)
	/usr/local/go/src/archive/zip/reader.go:97 +0x5c
archive/zip.NewReader({0x6847f8, 0xc000227280}, 0xa680)
	/usr/local/go/src/archive/zip/reader.go:90 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0x684c18?, 0xc0001864e8}, 0x72ab298)
	/root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:128 +0x8b
github.com/daaku/go%2ezipexe.NewReader({0x684c18, 0xc0001864e8}, 0x0?)
	/root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:48 +0x98
github.com/daaku/go%2ezipexe.OpenCloser({0xc000208240?, 0x3d?})
	/root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:30 +0x57
github.com/daaku/go%2ezipexe.Open(...)
	/root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:16
main.operationAppend({0xc000185350, 0x2, 0xb4fab375b8?})
	/root/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.2/rice/append.go:39 +0x418
main.main()
	/root/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.2/rice/main.go:42 +0x1a5
exit status 2
Makefile:193: recipe for target 'lotus-fountain' failed
make: *** [lotus-fountain] Error 1
```

### Repo Steps

make lotus-fountain

**Comment by rjan90** [comment]
Hey @beatyman! I have changed the title to better reflect what the issues is about, that Go version > 1.19 are not currently supported, hope that is fine!

**Comment by smagdali** [comment]
Am I reading this right that the failure here isn't just a version/compatibility error but a crash in some dependency that hasn't had an update in 2 years? https://github.com/GeertJohan/go.rice

**Comment by ianconsolata** [comment]
@rjan90 I don't think that's accurate. I just upgraded to go 1.19.2 and was able to `make lotus lotus-worker lotus-miner` just fine. I think this is specifically related to a dependency used to build `lotus-fountain`.

**Comment by magik6k** [comment]
Should be fixed with https://github.com/filecoin-project/lotus/pull/9683
