### ISSUE TITLE
FIP 0045 verified client claim extension

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/lotus#9466]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

After nv17 builtin actors allows two different claim extension modes

1. Free Extension. The client of the claim (verified deal client in current state of the world) can extend the claim up to five years from the original claim term start (epoch of ProveCommit).  This works even if the claim is expired (claim term start + term max > current epoch)

2. Paid Extension.  Anyone who spends datacap can extend the claim up to five years from the current epoch.  This does *not* work if the claim is expired.

Each probably warrants a cli command in the place where other verified client commands exist.  Free Extension works by calling verifreg ExtendClaimTerms with straightforward params.  Paid Extension works by actually calling DataCap actor Transfer method from a verified client with datacap to spend.

**Comment by beck-8** [comment]
Related issues: https://github.com/filecoin-project/lotus/issues/10001

**Comment by rjan90** [comment]
> I see here that this method only allows the transfer of tokens between governors, and does not apply to clients and sps. Is it not supported by the current network version?

That is correct! Transfers between clients are not allowed today, because it breaks FIL+ governance assumptions. A change here is a political / governance decision, not a technical one.

**Comment by beck-8** [comment]
Got it, now the second way (other client renewing the claim) is not supported.

**Comment by anorth** [comment]
The verified registry is the "governor" referred to in that comment. So transferring tokens to it (only) is supported.

**Comment by rjan90** [comment]
Closed by: https://github.com/filecoin-project/lotus/pull/11711
