### ISSUE TITLE
API: Ethereum compatible actor event methods backed by FVM

### ISSUE THREAD

**Issue by iand** [filecoin-project/lotus#9473]
The Ethereum blockchain has the concept of logs, which are events emitted from smart contracts during execution. The EVM compatiblity in Filecoin will need to support Ethereum logs at the protocol level and the JSON-RPC level. This issue is for adding the necessary JSON-RPC methods to Lotus. The protocol changes are covered by [ref-fvm#728](https://github.com/filecoin-project/ref-fvm/issues/728). 

A FIP will be submitted, introducing the actor events mechanism, on-chain commitments, schemas, expectation on clients, API surfaces, etc. ([draft](https://github.com/filecoin-project/FIPs/pull/483))

Our goal is to reach end-to-end functional completeness first (even if it’s with subpar performance), and then focus on adding indices and improving performance. The goal is having these methods working in Lotus (satisfying this part of the  Ethereum JSON-RPC API spec which has remained unimplemented), backed by event data produced by the FVM:

- [ ]  eth_subscribe
- [ ]  eth_unsubscribe
- [ ]  eth_getLogs
- [ ]  eth_getFilterChanges
- [ ]  eth_getFilterLogs
- [ ]  eth_newBlockFilter
- [ ]  eth_newFilter
- [ ]  eth_newPendingTransactionFilter
- [ ]  eth_uninstallFilter

See [Ethereum JSON-RPC Specification](https://ethereum.org/en/developers/docs/apis/json-rpc/)

Some of these methods are not just scoped to events, but also include the ability to subscribe to new heads and pending transactions.

The way to get there includes creating a new store with its associated indices in Lotus to store and index emitted events. We are conceiving it as a separate domain-specific store because these are technically not exchangeable chain objects, nor state tree objects. They are side effects that can be reconstructed any time by replaying the transaction

**Comment by iand** [comment]
I believe these methods will need to be accessible by the specified names which don't match Lotus's naming convention. I plan to add aliases in the jsonrpc server (already supported but filed https://github.com/filecoin-project/go-jsonrpc/pull/80 to make it easier to config)

So the method names in Lotus would follow the usual convention, e.g. `Filecoin.EthGetLogs`, but also be accessible as `eth_getLogs` etc.

**Comment by iand** [comment]
## Indexing Requirements

We won't have a bloom filter on each transaction to assist the filtering so if we want reasonable performance for searching logs we need to maintain a side index. 

A log filter can be applied as an ad hoc query, or a persistent query that may be polled. They may also be used in a subscription to match continously (excluding the block range or hash)

Filters can also be created to match new blocks and pending transactions but these can be handled as special cased matchers that share an ID space with log filters. They don't follow the same query requirements. The API overloads return types to cater for this

Need to track reorgs to determine if a log was removed from the chain. Index must therefore be updateable.

Requirements are primarily driven by the expressiveness of the querying defined by a log filter, which is the intersection of:

 - a range of block heights or a single block hash
 - a list of from addresses
 - a list of topics for each position (up to 4 lists)

Log filter query satisfaction could be catered for by a single indexing table, one row per log:

 - height
 - address
 - topic1
 - topic2
 - topic3
 - topic4
 - removed 
 - other columns...

The other columns could be minimal to optimize for space efficiency: the message cid, the events AMT root cid and index of the event in the AMT. The filtering implementation would retrieve the message and the log to build responses.

Or all data from the EthEventLog type could be kept in the table for speed of access: LogIndex, TransactionIndex, TransactionHash, BlockHash, BlockNumber and Data. In this case the filtering implementation would simply read from the table to build the response.


### Index implementation

Simplest implementation would be to use embedded SQLite which avoid re-implementing query logic. A single indexed table would cover the needs of the API. 

Note that this is just an index over data that can be reconstructed from the chain. 

We could also store filters in a table if we wanted them to survive restarts of Lotus.

### Index Space Requirements

From above, minimum row size is 8+32+(32*4)+1=169 bytes plus other columns.

Assuming minimal assitional columns (message cid, event root, index) qwould be 2*62+8=132 additional bytes for a total of 301

Indexing overhead of 50% takes it to ~450 bytes

Average 250 messages per tipset, assuming average of 2 logs per message, gives 219KiB per tipset, ~618MiB per day. 

Index could be configured by SP to retain a maximum number of epochs, e.g. 20000 (~1 week) to put an upper bound on index size if required.

**Comment by raulk** [comment]
> Log filter query satisfaction could be catered for by a single indexing table, one row per log:

The proposed structure indexes by specific named entries known to exist for events emitted by FEVM smart contracts (topic{1..4}). This specialization works for Ethereum APIs, but it won't work for events emitted from builtin-actors (which I expect might be added shortly after this functionality goes live), nor from upcoming Wasm actors. Actors outside FEVM are free to use whichever entry keys they'd like.

**Comment by iand** [comment]
> > Log filter query satisfaction could be catered for by a single indexing table, one row per log:
> 
> The proposed structure indexes by specific named entries known to exist for events emitted by FEVM smart contracts (topic{1..4}). This specialization works for Ethereum APIs, but it won't work for events emitted from builtin-actors (which I expect might be added shortly after this functionality goes live), nor from upcoming Wasm actors. Actors outside FEVM are free to use whichever entry keys they'd like.
> 
> Do you consider the specialization to be indispensable at this stage? Or can we incorporate keys as an indexable item too?

We could support arbitrary keys. In relational terms we'd have a keyvalues table with 3 columns: eventid/key/value and construct joins in the query based on the number of keys specified. This would give the most flexibility since it's agnostic to key names.

**Comment by raulk** [comment]
I'd prefer that if the performance hit is acceptable. In fact, I'd construe the specialized Ethereum index/table/view as food for future optimization, if needed.

**Comment by iand** [comment]
> 

Agree. there is a non-cgo version of sqlite which I think would suit this limited use case (simple joins across two tables): https://gitlab.com/cznic/sqlite

**Comment by iand** [comment]
An alternative approach, which avoids using Sqlite is to match messages against filters as they arrive and add them to a bounded results list per filter. These would then either be transmitted as part of any subscription or retrieved via a call to eth_getFilterChanges (which then clears the list).  We would satisfy the `getLogs` call by a scan through historic tipsets. 

This has the advantage of no overhead until there is an active filter or subscriptions. The main disadvantage is the slow scan needed for historic data.

**Comment by arajasek** [comment]
Thank you for the fantastic write-up! This broadly sounds good to me, there's nothing that seems like a no-go here. It's a little hard to provide feedback on what we should do, cuz I'm not quite sure what the product requirements here are. I wonder whether we could take a "build up" approach here -- start with a skinny MVP, and optimize things as needed as user feedback comes in.

> An alternative approach, which avoids using Sqlite is to match messages against filters as they arrive and add them to a bounded results list per filter. These would then either be transmitted as part of any subscription or retrieved via a call to eth_getFilterChanges (which then clears the list). We would satisfy the eth_getLogs call by a scan through historic tipsets.
This has the advantage of no overhead until there is an active filter or subscriptions. The main disadvantage is the slow scan needed for historic data

So this is really nice, and should work. It would be great to at least _support_ this mode, where a node can choose to do nothing until queried, but can still answer all queries (even if most nodes serving this info wind up actually indexing). The problem is that scanning through historic tipsets will be SLOW -- realistically this approach can't do much more a range of (say) 10 epochs or so.

Some things that I would like more details on:

- I have concerns about having the index being based on height -- it's difficult to get consistent views of blockchains (esp those with 30 sec blocktimes). On what event is the index populated? 
  - I think we need the indexer to be a notifee of head change events, and de/populate the table based on MessageReceipts in the head change tipset? This...works, and should be reorg
- What does the pruning process (`Index could be configured by SP to retain a maximum number of epochs, e.g. 20000 (~1 week) to put an upper bound on index size if required`) look like?
- Nit: We're talking about SPs (I assume "Storage Providers"?) in this issue, but this is a node-level feature that non-SPs will also be running.

**Comment by magik6k** [comment]
I'm generally ok with having a built-in log index, and I'm not against adding sqlite to support that. Initially I'd expect it to be opt-in given that most node operators will not need it; When logs see broader use, and we have more experience with the index we can flip the switch.

I'd keep block hashes in the index, and maintain it based on those - maintaining blocks based on just height will be flimsy - in lotus you can manually switch heads, even beyond finality (may need to be done by SPs which get disconnected from the network and end-up on large forks where they mine themselves)

I'm not entirely sure how to integrate this cleanly with the block syncer. State compute is part of block validation, but that logic is 2-3 levels of abstraction removed from the logic which decides which chain is "synced".

One way to go about this would be to just index all logs from all executions, and filter for logs from the actually synced chain in GetLogs calls - I would prefer that approach, as it reduces changes is chain sync code, and it reduces the amount of state which needs to be kept clean/in sync (log index is append-only, so no data has to be removed from it in case of reorgs)

**Comment by raulk** [comment]
> We would satisfy the eth_getLogs call by a scan through historic tipsets.

Quite frankly I would just disable eth_getLogs support in that case.´

---

Generally speaking the insight I'm getting is that we should make indexing entirely opt-in and regulate which Ethereum JSON-RPC operations are effectively available or not at runtime based on the configuration.

That way, one could:

1. Activate full indexing, in which case filter-dependent operations and `eth_getLogs` would all be available.
2. Disable full indexing, in which case only filter operations would be available, and `eth_getLogs` would error.

---

Even more generally speaking, we may need to add a configuration flag to entirely enable/disable the Ethereum JSON-RPC endpoint (e.g. SPs won't want to run it and would probably welcome the ability to cut it out of their API surface).

**Comment by iand** [comment]
> Thank you for the fantastic write-up! This broadly sounds good to me, there's nothing that seems like a no-go here. It's a little hard to provide feedback on what we should do, cuz I'm not quite sure what the product requirements here are. I wonder whether we could take a "build up" approach here -- start with a skinny MVP, and optimize things as needed as user feedback comes in.
> 
> > An alternative approach, which avoids using Sqlite is to match messages against filters as they arrive and add them to a bounded results list per filter. These would then either be transmitted as part of any subscription or retrieved via a call to eth_getFilterChanges (which then clears the list). We would satisfy the eth_getLogs call by a scan through historic tipsets.
> > This has the advantage of no overhead until there is an active filter or subscriptions. The main disadvantage is the slow scan needed for historic data
> 
> So this is really nice, and should work. It would be great to at least _support_ this mode, where a node can choose to do nothing until queried, but can still answer all queries (even if most nodes serving this info wind up actually indexing). The problem is that scanning through historic tipsets will be SLOW -- realistically this approach can't do much more a range of (say) 10 epochs or so.

Yes, and 10 epochs is really not enough to make this useful. I suspect getLogs would be frequently used to check events over 24 hour timeframe

> 
> Some things that I would like more details on:
> 
>     * I have concerns about having the index being based on height -- it's difficult to get consistent views of blockchains (esp those with 30 sec blocktimes). On what event is the index populated?
>       
>       * I think we need the indexer to be a notifee of head change events, and de/populate the table based on MessageReceipts in the head change tipset? This...works, and should be reorg

Ack, I was thinking something like:

- Apply - will populate the index for new messages and set removed = false for already existing, using messageid + events root cid as the unique key. 
- Revert - will update index to set removed = true for all messages in the reverted tipset




> 
>     * What does the pruning process (`Index could be configured by SP to retain a maximum number of epochs, e.g. 20000 (~1 week) to put an upper bound on index size if required`) look like?

A periodic (daily) delete from the relevant tables, where `height < (current height - configured limit)`
> 
>     * Nit: We're talking about SPs (I assume "Storage Providers"?) in this issue, but this is a node-level feature that non-SPs will also be running.
Yes, just a slip of my terminology

**Comment by iand** [comment]
Realtime filtering requires some thought when working with revertable tipsets. If the client is subscribed then they will receive a websocket notification of the logs when the tipset is applied, then a repeat of the logs with removed=true when the tipset is reverted. The same will be true for filter results. (This is the [behaviour of go-ethereum](https://github.com/ethereum/go-ethereum/blob/master/eth/filters/api.go#L288))

**Comment by jennijuju** [comment]
We should make a decision on this by EOW

**Comment by jennijuju** [comment]
@iand hiii im catching up -whats the status on this?

**Comment by oberstet** [comment]
are you planning to support WebSocket too, or only HTTP?
specifically, at least `eth_subscribe` over WebSocket, and ideally, any of the JSON-RPC methods over WebSocket ("JSON-RPC over WSS") in addition to those same methods over HTTP ("JSON-RPC over HTTPS POST"). Ethereum execution clients often support that. Without WebSocket, at least `eth_subscribe` events must be polled for rather than events pushed ..

**Comment by oberstet** [comment]
fwiw, commenting in general on the ethereum json-rpc api, in particular events and filters:

one specific challenge is that the events api provides both "query on historic data" and "filter on real-time streaming data"

another challenge is that filters are dynamic (by filter conditions) and transient (they time out when not queried) objects created from one session, but then available on any session

here are snippets from the respective docs:

* eth_getLogs

> Returns an array of all logs matching a given filter object.

*  eth_newFilter

> Creates a filter object, based on filter options, to notify when the state changes (logs). Filters expire after 5 minutes of inactivity (no queries).

* fromBlock

> Either the hex value of a block number OR One of the following block tags

----------

one more comment, if you allow a newbie (here) to chime in the conversation above;)

"sqlite": please do not. it's not the right tool for the use case of quickly and robustly persisting massive event log data for efficient batch querying later.

have you considered e.g. LMDB? it provides true ACID operation and zero-copy (mmap'ed) multiple reader access. it's used in openldap and other projects https://www.symas.com/symas-lmdb-tech-info

now, LMDB is a C library, and looking forward, probably a pure Rust library would be preferable:

https://sled.rs/
https://github.com/pjtatlow/jammdb

**Comment by iand** [comment]
> @iand hiii im catching up -whats the status on this?

@jennijuju  This was completed and merged into the feat/nv18-events branch via https://github.com/filecoin-project/lotus/pull/9623 and one or two follow on fixes went on top from me and @raulk
