### ISSUE TITLE
sectorbuilder  func (sb *SectorBuilder) GetPath is wrong

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#949]
**Describe the bug**
func (sb *SectorBuilder) GetPath(typ string, **sectorName** string) (string, error) {
	_, found := overheadMul[dataType(typ)]
	if !found {
		return "", xerrors.Errorf("unknown sector type: %s", typ)
	}
        return sb.filesystem.pathFor(dataType(typ)), nil
	//return filepath.Join(sb.filesystem.pathFor(dataType(typ)), **sectorName**), nil
}

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**

**Additional context**

**Comment by magik6k** [comment]
Thanks for catching that! See #953
