### ISSUE TITLE
renew or extend? only one can stay!

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9501]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

lotus miner sectors cli has two cmd `renew` and `extend` shares highly duplicated features, evaluate which one has the better ux and keep it - remove the other one in favor of the winner.

**Comment by Reiers** [comment]
_I have always used `extend`._ 

But `renew` have more options, nicer ux and it's easier to use. 
So my vote is to keep `renew`.

**Comment by TippyFlitsUK** [comment]
I have always used extend as well but I think that renew would be better going forward as it has the new `only-cc` option.

**Comment by Reiers** [comment]
> whats the on chain message called?

Nice, sarcasm, it doesn't change the fact that `renew` is the better option here.
If you take a close look at both cmds, I bet you will come to the same conclusion. If not, +1 for to keep `extend` instead of `renew`. 👍

**Comment by Reiers** [comment]
Oh, then apologies! @f8-ptrk 
The message is `ExtendSectorExpiration` for both `renew` and `extend`.
