### ISSUE TITLE
proof validation failed, sector not found in sector set after cron

### ISSUE THREAD

**Issue by beatyman** [filecoin-project/lotus#9540]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.18.0-rc4
```

### Describe the Bug

`

1. lotus client import a.txt 

Import 1666342397102885330, Root bafk2bzacebtdwksd2teh73mwh27fsdyynbwskp4qj7enov2p42jnqll572qf2 

2. lotus  client deal  bafk2bzacebtdwksd2teh73mwh27fsdyynbwskp4qj7enov2p42jnqll572qf2 t01010 0.000001 518400

`

**an error occurred in the client storage deals  seal, and the C2 message failed to be committed to the lotus chain**

lotus-miner error log:
`
2022-10-22T23:27:14.300+0800    WARN    sectors pipeline/fsm.go:835     sector 24 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
2022-10-22T23:27:14.385+0800    WARN    sectors pipeline/fsm.go:835     sector 24 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
`

lous error log:
`
2022-10-22T23:25:28.228+0800    INFO    markets loggers/loggers.go:16   storage client event    {"name": "ClientEventDealActivationFailed", "proposal CID": "bafyreid2qyugkonav75vzbj5th6bn2uw6iozi6642p4jdqllcnsxiqfefm", "state": "StorageDealError", "message": "error in deal activation: handling applied event: deal wasn't active: deal=8, parentState=bafy2bzacecqucqq23t4awa77guyk2cdujuou6oqgfhofw7let5vw4pll7xosq, h=11123"}
`
lotus client get-deal bafyreid2qyugkonav75vzbj5th6bn2uw6iozi6642p4jdqllcnsxiqfefm
`
{
  "DealInfo: ": {
    "ProposalCid": {
      "/": "bafyreiccnolwdgbdtg4irxirbsfn6mvsteptzciwgoy6233qa2cvj2rqma"
    },
    "State": 26,
    "Message": "error in deal activation: handling applied event: deal wasn't active: deal=1, parentState=bafy2bzacecxj5qpc6re3yb25nv7yark2tlhtl5tjitelnzkotorlbykf5a6li, h=178",
    "DealStages": {
      "Stages": [
        {
          "Name": "StorageDealReserveClientFunds",
          "Description": "Reserving client funds",
          "ExpectedDuration": "a few minutes",
          "CreatedTime": "2022-10-21T16:50:43.282280373+08:00",
          "UpdatedTime": "2022-10-21T16:50:43.300717564+08:00",
          "Logs": [
            {
              "Log": "funds reserved, amount \u003c522229000000000\u003e",
              "UpdatedTime": "2022-10-21T16:50:43.282280373+08:00"
            },
            {
              "Log": "reserving funds for storage deal, message cid: \u003cbafy2bzacea5vyuiywsck53asuxfm2oobb5gf3klmuudmjonbflyqdx4iupbqo\u003e",
              "UpdatedTime": "2022-10-21T16:50:43.300717564+08:00"
            }
          ]
        },
        {
          "Name": "StorageDealFundsReserved",
          "Description": "FundsReserved",
          "ExpectedDuration": "a few minutes",
          "CreatedTime": "2022-10-21T16:51:58.190556323+08:00",
          "UpdatedTime": "2022-10-21T16:51:58.190556323+08:00",
          "Logs": [
            {
              "Log": "opening data transfer to storage provider",
              "UpdatedTime": "2022-10-21T16:51:58.190556323+08:00"
            }
          ]
        },
        {
          "Name": "StorageDealStartDataTransfer",
          "Description": "Starting data transfer",
          "ExpectedDuration": "a few minutes",
          "CreatedTime": "2022-10-21T16:51:58.271662993+08:00",
          "UpdatedTime": "2022-10-21T16:51:58.271662993+08:00",
          "Logs": [
            {
              "Log": "provider data transfer request added to client's queue: channel id \u003c12D3KooWGwFyXEYWhUsgd8xc6sctW3H5mgjGxK4Fx4BdqgJ1TWrk-12D3KooWCW2g2TreHtA7s6vWPb5mjfwp4Viu5MpxwHYKMejZzKSn-1666341920471570880\u003e",
              "UpdatedTime": "2022-10-21T16:51:58.271662993+08:00"
            }
          ]
        },
        {
          "Name": "StorageDealTransferQueued",
          "Description": "",
          "ExpectedDuration": "",
          "CreatedTime": "2022-10-21T16:51:58.298387142+08:00",
          "UpdatedTime": "2022-10-21T16:51:58.298387142+08:00",
          "Logs": [
            {
              "Log": "data transfer initiated on channel id \u003c12D3KooWGwFyXEYWhUsgd8xc6sctW3H5mgjGxK4Fx4BdqgJ1TWrk-12D3KooWCW2g2TreHtA7s6vWPb5mjfwp4Viu5MpxwHYKMejZzKSn-1666341920471570880\u003e",
              "UpdatedTime": "2022-10-21T16:51:58.298387142+08:00"
            }
          ]
        },
        {
          "Name": "StorageDealCheckForAcceptance",
          "Description": "Checking for deal acceptance",
          "ExpectedDuration": "a few minutes",
          "CreatedTime": "2022-10-21T16:51:59.475558922+08:00",
          "UpdatedTime": "2022-10-21T16:59:07.945702742+08:00",
          "Logs": [
            {
              "Log": "provider is verifying the data",
              "UpdatedTime": "2022-10-21T16:51:59.475558922+08:00"
            },
            {
              "Log": "provider has submitted the deal on-chain and is waiting for confirmation",
              "UpdatedTime": "2022-10-21T16:52:00.499231969+08:00"
            },
            {
              "Log": "deal has been accepted by storage provider",
              "UpdatedTime": "2022-10-21T16:59:07.945702742+08:00"
            }
          ]
        },
        {
          "Name": "StorageDealProposalAccepted",
          "Description": "Proposal accepted",
          "ExpectedDuration": "a few minutes",
          "CreatedTime": "2022-10-21T16:59:07.964936217+08:00",
          "UpdatedTime": "2022-10-21T16:59:07.973247551+08:00",
          "Logs": [
            {
              "Log": "funds released, amount \u003c522229000000000\u003e",
              "UpdatedTime": "2022-10-21T16:59:07.964936217+08:00"
            }
          ]
        },
        {
          "Name": "StorageDealAwaitingPreCommit",
          "Description": "Awaiting a PreCommit message on chain",
          "ExpectedDuration": "a few minutes",
          "CreatedTime": "2022-10-21T16:59:07.989694844+08:00",
          "UpdatedTime": "2022-10-21T16:59:07.989694844+08:00",
          "Logs": [
            {
              "Log": "deal pre-commit message has landed on chain",
              "UpdatedTime": "2022-10-21T16:59:07.989694844+08:00"
            }
          ]
        },
        {
          "Name": "StorageDealSealing",
          "Description": "Sealing",
          "ExpectedDuration": "a few hours",
          "CreatedTime": "2022-10-21T17:01:18.156957831+08:00",
          "UpdatedTime": "2022-10-21T17:01:18.156957831+08:00",
          "Logs": [
            {
              "Log": "error in deal activation: handling applied event: deal wasn't active: deal=1, parentState=bafy2bzacecxj5qpc6re3yb25nv7yark2tlhtl5tjitelnzkotorlbykf5a6li, h=178",
              "UpdatedTime": "2022-10-21T17:01:18.156957831+08:00"
            }
          ]
        }
      ]
    },
    "Provider": "t01010",
    "DataRef": {
      "TransferType": "graphsync",
      "Root": {
        "/": "bafk2bzacebl4pgluxsmhchxfycprmwjin2fnlevx5vvs5cnogofwgz7cjuhrs"
      },
      "PieceCid": null,
      "PieceSize": 0,
      "RawBlockSize": 0
    },
    "PieceCID": {
      "/": "baga6ea4seaqnhqxmaquam5ijlk52w42ggrt64namqo4vglcn4cxiqe3jnkvqwpq"
    },
    "Size": 508,
    "PricePerEpoch": "1000000000",
    "Duration": 522229,
    "DealID": 1,
    "CreationTime": "2022-10-21T16:50:43.234855905+08:00",
    "Verified": false,
    "TransferChannelID": {
      "Initiator": "12D3KooWGwFyXEYWhUsgd8xc6sctW3H5mgjGxK4Fx4BdqgJ1TWrk",
      "Responder": "12D3KooWCW2g2TreHtA7s6vWPb5mjfwp4Viu5MpxwHYKMejZzKSn",
      "ID": 1666341920471570880
    },
    "DataTransfer": {
      "TransferID": 1666341920471570880,
      "Status": 6,
      "BaseCID": {
        "/": "bafk2bzacebl4pgluxsmhchxfycprmwjin2fnlevx5vvs5cnogofwgz7cjuhrs"
      },
      "IsInitiator": true,
      "IsSender": true,
      "Voucher": "{\"Proposal\":{\"/\":\"bafyreiccnolwdgbdtg4irxirbsfn6mvsteptzciwgoy6233qa2cvj2rqma\"}}",
      "Message": "",
      "OtherPeer": "12D3KooWCW2g2TreHtA7s6vWPb5mjfwp4Viu5MpxwHYKMejZzKSn",
      "Transferred": 391,
      "Stages": {
        "Stages": [
          {
            "Name": "Requested",
            "Description": "",
            "CreatedTime": "2022-10-21T16:51:58.218956568+08:00",
            "UpdatedTime": "2022-10-21T16:51:58.286157329+08:00",
            "Logs": null
          },
          {
            "Name": "Ongoing",
            "Description": "",
            "CreatedTime": "2022-10-21T16:51:58.306487619+08:00",
            "UpdatedTime": "2022-10-21T16:51:58.373944914+08:00",
            "Logs": [
              {
                "Log": "sending data",
                "UpdatedTime": "2022-10-21T16:51:58.340471683+08:00"
              }
            ]
          },
          {
            "Name": "ResponderCompleted",
            "Description": "",
            "CreatedTime": "2022-10-21T16:51:58.390611093+08:00",
            "UpdatedTime": "2022-10-21T16:51:58.390611093+08:00",
            "Logs": null
          },
          {
            "Name": "Completing",
            "Description": "",
            "CreatedTime": "2022-10-21T16:51:58.416284103+08:00",
            "UpdatedTime": "2022-10-21T16:51:58.416284103+08:00",
            "Logs": null
          }
        ]
      }
    }
  },
  "OnChain": {
    "Proposal": {
      "PieceCID": {
        "/": "baga6ea4seaqnhqxmaquam5ijlk52w42ggrt64namqo4vglcn4cxiqe3jnkvqwpq"
      },
      "PieceSize": 512,
      "VerifiedDeal": false,
      "Client": "t01002",
      "Provider": "t01010",
      "Label": "mAVWg5AIgV8eZdLyYcR7lwJ8WWShuitWSt+1rLomuM4tjZ+JNDxk",
      "StartEpoch": 69240,
      "EndEpoch": 591469,
      "StoragePricePerEpoch": "1000000000",
      "ProviderCollateral": "0",
      "ClientCollateral": "0"
    },
    "State": {
      "SectorStartEpoch": -1,
      "LastUpdatedEpoch": -1,
      "SlashEpoch": -1,
      "VerifiedClaim": 0
    }
  }
}

`

lotus-miner sectors status --log 24 

`
SectorID:	24
Status:		CommitWait
CIDcommD:	baga6ea4seaqa5xgrkepp7pw3gxfuf3mmdkh4qxvjqyutc4hnkr2xyk4254zaiiy
CIDcommR:	bagboea4b5abca6i3w6s52ffzk6dictoscbitc2umoqanfcenwmur6ip27bz62htd
Ticket:		d8eef89583d3e949d0b8a7a74dbca0922038472aaca00a078d58785bcc1a13eb
TicketH:	10194
Seed:		eae1d08e128ca94b9f0892824b7d4132a537fefcdf07bba66e9773a32c5c38f3
SeedH:		11113
Precommit:	bafy2bzaceaqf35qnfdb6nql6zod3kj7dzajamrs4b4oqg75jyvjjnbtuzt6fk
Commit:		bafy2bzaceavd7uczg4exovpjpnzbfsmfo2di3fdwrl2nblippfwn2pykflqmu
Deals:		[8 0 0]
Retries:	0
--------
Event Log:
0.	2022-10-22 23:19:38 +0800 CST:	[event;sealing.SectorStart]	{"User":{"ID":24,"SectorType":5}}
1.	2022-10-22 23:19:38 +0800 CST:	[event;sealing.SectorAddPiece]	{"User":{}}
2.	2022-10-22 23:19:38 +0800 CST:	[event;sealing.SectorPieceAdded]	{"User":{"NewPieces":[{"Piece":{"Size":512,"PieceCID":{"/":"baga6ea4seaqj64fsk2jjoqkl5n4dc34uembct27hguv7ow4jlcy62rort7bymda"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacebbhrpvfbjxasincqxffii662om4apykdiprlaufrybz2mmuzs2zm"},"DealID":8,"DealProposal":{"PieceCID":{"/":"baga6ea4seaqj64fsk2jjoqkl5n4dc34uembct27hguv7ow4jlcy62rort7bymda"},"PieceSize":512,"VerifiedDeal":false,"Client":"t3u6acxqdjt34qjbht7u6a3guk4cewwfli3berljop3nuao2wrb46oh5vlkjgcn6yyowzosnbduhg2falokcjq","Provider":"t01010","Label":"mAVWg5AIgZjsqQ9TIf+2WPr5ZDxhobSU/kE/I11dP5pLYLX3+oF0","StartEpoch":80201,"EndEpoch":600109,"StoragePricePerEpoch":"1000000000000","ProviderCollateral":"0","ClientCollateral":"0"},"DealSchedule":{"StartEpoch":80201,"EndEpoch":600109},"KeepUnsealed":true}}]}}
3.	2022-10-22 23:19:38 +0800 CST:	[event;sealing.SectorStartPacking]	{"User":{}}
4.	2022-10-22 23:19:41 +0800 CST:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":[{"Size":512,"PieceCID":{"/":"baga6ea4seaqfpirydiugkk7up5v666wkm6n6jlw6lby2wxht5mwaqekerdfykjq"}},{"Size":1024,"PieceCID":{"/":"baga6ea4seaqb66wjlfkrbye6uqoemcyxmqylwmrm235uclwfpsyx3ge2imidoly"}}]}}
5.	2022-10-22 23:19:41 +0800 CST:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"2O74lYPT6UnQuKenTbygkiA4RyqsoAoHjVh4W8waE+s=","TicketEpoch":10194}}
6.	2022-10-22 23:19:46 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	seal pre commit(1) failed: {"Code":"EOF","As":[["errors.parse(errors.go:159)","[init]"],["client.(*HttpClient).Download(http_file.go:486)","[/data/cache/.lotusworker/unsealed/s-t01010-24 unsealed/s-t01010-24]"],["main.(*worker)
7.	2022-10-22 23:20:46 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
8.	2022-10-22 23:20:46 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJfbG90dXNfU2VhbFJhbmRvbW5lc3MiOiIyTzc0bFlQVDZVblF1S2VuVGJ5Z2tpQTRSeXFzb0FvSGpWaDRXOHdhRStzPSIsImNvbW1fZCI6WzE0LDIyMCwyMDksODEsMzAsMjU1LDE5MCwyMTksNTMsMjAzLDY2LDIzNywxNDAsMjYsMTQzLDIwMCw5NCwxNjksMTM0LDQxLDQ5LDExMiwyMzcsODQsMTE3LDEyNCw0MywxNTQsMjM5LDUwLDQsMzVdLCJjb25maWciOnsiaWQiOiJ0cmVlLWQiLCJwYXRoIjoiL2RhdGEvY2FjaGUvLmxvdHVzd29ya2VyL2NhY2hlL3MtdDAxMDEwLTI0Iiwicm93c190b19kaXNjYXJkIjo1LCJzaXplIjoxMjd9LCJsYWJlbHMiOnsiU3RhY2tlZERyZzJLaUJWMSI6eyJfaCI6bnVsbCwibGFiZWxzIjpbeyJpZCI6ImxheWVyLTEiLCJwYXRoIjoiL2RhdGEvY2FjaGUvLmxvdHVzd29ya2VyL2NhY2hlL3MtdDAxMDEwLTI0Iiwicm93c190b19kaXNjYXJkIjo1LCJzaXplIjo2NH0seyJpZCI6ImxheWVyLTIiLCJwYXRoIjoiL2RhdGEvY2FjaGUvLmxvdHVzd29ya2VyL2NhY2hlL3MtdDAxMDEwLTI0Iiwicm93c190b19kaXNjYXJkIjo1LCJzaXplIjo2NH1dfX0sInJlZ2lzdGVyZWRfcHJvb2YiOiJTdGFja2VkRHJnMktpQlYxXzEifQ=="}}
9.	2022-10-22 23:20:55 +0800 CST:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abca6i3w6s52ffzk6dictoscbitc2umoqanfcenwmur6ip27bz62htd"},"Unsealed":{"/":"baga6ea4seaqa5xgrkepp7pw3gxfuf3mmdkh4qxvjqyutc4hnkr2xyk4254zaiiy"}}}
10.	2022-10-22 23:20:55 +0800 CST:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzaceaqf35qnfdb6nql6zod3kj7dzajamrs4b4oqg75jyvjjnbtuzt6fk"},"PreCommitDeposit":"1","PreCommitInfo":{"SealProof":5,"SectorNumber":24,"SealedCID":{"/":"bagboea4b5abca6i3w6s52ffzk6dictoscbitc2umoqanfcenwmur6ip27bz62htd"},"SealRandEpoch":10194,"DealIDs":[8],"Expiration":618924,"UnsealedCid":null}}}
11.	2022-10-22 23:22:08 +0800 CST:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":[{"/":"bafy2bzacea3mn5jswcvzbkknajw4gvakwai4pjqtmtvgorcxa2wkjahwsx6l4"}]}}
12.	2022-10-22 23:23:48 +0800 CST:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"6uHQjhKMqUufCJKCS31BMqU3/vzfB7umbpdzoyxcOPM=","SeedEpoch":11113}}
13.	2022-10-22 23:24:09 +0800 CST:	[event;sealing.SectorCommitted]	{"User":{"Proof":"idPqx7I3TJ/4WlEXRxTe+xZaZAt/XveX5gJt4qj4+jZVt8OzKpXQaOeiKQ18U10lktnqZ9ZuUvPem+Qsd9LHuTGcokpBU3taW65jo7ZacmQdAOGb31+G1IlmfcoZTb1XGcEuLdKR+AFjIlve/qAe1liHWWSKHBc6iP73MHLfzpxA7lTN4rdt2Wn1ybK9a4k1k1FVf1Iz4nuUCDoAHGCRCXd8Qe6GhuFMpQbfqDlWVjiGL1VEbsxlEivlSo0piSz5"}}
14.	2022-10-22 23:24:09 +0800 CST:	[event;sealing.SectorCommitSubmitted]	{"User":{"Message":{"/":"bafy2bzaceavd7uczg4exovpjpnzbfsmfo2di3fdwrl2nblippfwn2pykflqmu"}}}
15.	2022-10-22 23:25:18 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	proof validation failed, sector not found in sector set after cron
16.	2022-10-22 23:25:18 +0800 CST:	[event;sealing.SectorRetryCommitWait]	{"User":{}}
17.	2022-10-22 23:25:18 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	proof validation failed, sector not found in sector set after cron
18.	2022-10-22 23:25:18 +0800 CST:	[event;sealing.SectorRetryCommitWait]	{"User":{}}
19.	2022-10-22 23:25:18 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	proof validation failed, sector not found in sector set after cron
20.	2022-10-22 23:25:18 +0800 CST:	[event;sealing.SectorRetryCommitWait]	{"User":{}}
21.	2022-10-22 23:25:18 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
	proof validation failed, sector not found in sector set after cron
22.	2022-10-22 23:25:18 +0800 CST:	[event;sealing.SectorRetryCommitWait]	{"User":{}}
23.	2022-10-22 23:25:18 +0800 CST:	[event;sealing.SectorCommitFailed]	{"User":{}}
`

lotus-miner info:

`
Enabled subsystems (from miner API): [Mining Sealing SectorStorage Markets]
Enabled subsystems (from markets API): [Mining Sealing SectorStorage Markets]
Chain: [sync ok] [basefee 100 aFIL]
Miner: t01010 (2 KiB sectors)
Power: 0  / 20 Ki (0.0000%)
        Raw: 0 B / 2 KiB (0.0000%)
        Committed: 34 KiB
        Proving: 34 KiB (34 KiB Faulty, 100.00%)
Below minimum power threshold, no blocks will be won

Deals: 0, 0 B
        Active: 0, 0 B (Verified: 0, 0 B)

Miner Balance:    154082.368 FIL
      PreCommit:  7.533 μFIL
      Pledge:     1.013 μFIL
      Vesting:    40016.3 FIL
      Available:  114066.068 FIL
Market Balance:   5000 FIL
       Locked:    0
       Available: 5000 FIL
Worker Balance:   2979998.954 FIL
Total Spendable:  3099065.021 FIL

Beneficiary:    t01002

Workers: Seal(0) WdPoSt(0) WinPoSt(0)

Storage Deals: 0, 0 B

Retrieval Deals (complete): 0, 0 B
`

### Logging Information

```text
2022-10-22T23:47:05.591+0800    WARN    sectors pipeline/fsm.go:835     sector 24 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
2022-10-22T23:47:05.701+0800    WARN    sectors pipeline/fsm.go:835     sector 24 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
2022-10-22T23:47:05.812+0800    WARN    sectors pipeline/fsm.go:835     sector 24 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
2022-10-22T23:47:05.894+0800    WARN    sectors pipeline/fsm.go:835     sector 24 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
^C2022-10-22T23:47:05.974+0800  WARN    sectors pipeline/fsm.go:835     sector 24 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
2022-10-22T23:47:06.087+0800    WARN    sectors pipeline/fsm.go:835     sector 24 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
2022-10-22T23:47:06.152+0800    WARN    sectors pipeline/fsm.go:835     sector 24 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
```

### Repo Steps

1. lotus client import a.txt 

Import 1666342397102885330, Root bafk2bzacebtdwksd2teh73mwh27fsdyynbwskp4qj7enov2p42jnqll572qf2 

2. lotus  client deal  bafk2bzacebtdwksd2teh73mwh27fsdyynbwskp4qj7enov2p42jnqll572qf2 t01010 0.000001 518400

**Comment by beatyman** [comment]
same error: 
https://github.com/filecoin-project/lotus/issues/8694
https://github.com/filecoin-project/lotus/issues/8747

**Comment by Reiers** [comment]
Thanks for the report! 
Close due to duplicate.

**Comment by beatyman** [comment]
@Reiers  This problem has not been solved，I tried to solve the problem according to the above issue, but it didn't work，so this issue cannot be closed .

**Comment by beatyman** [comment]
`github.com/filecoin-project/go-fil-markets v1.24.0-v17  `
I guess it's the problem here

**Comment by beatyman** [comment]
Here are some discussions ：https://filecoinproject.slack.com/archives/CPFTWMY7N/p1666239588880669

**Comment by jennijuju** [comment]
Which network?

**Comment by beatyman** [comment]
dev 2k

**Comment by Linuxpizi** [comment]
how to deal with it, i have the same problem ?

**Comment by bachue** [comment]
how to deal with it? i have the same problem either.

**Comment by beatyman** [comment]
@bachue @RobQuistNL  The latest version of lotus  branch r**elease/v1.18.0** has solved this problem

**Comment by Shekelme** [comment]
@beatyman Nope. [https://filecoinproject.slack.com/archives/CPFTWMY7N/p1670079351678259?thread_ts=1668481128.067859&cid=CPFTWMY7N](url)

```
2022-12-03T20:00:30.383+0300    WARN    sectors pipeline/fsm.go:342     truncating sector log   {"sector": "27620"}
2022-12-03T20:00:30.383+0300    WARN    sectors pipeline/fsm.go:792     sector 27620 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
2022-12-03T20:00:30.628+0300    WARN    sectors pipeline/fsm.go:792     sector 27620 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
2022-12-03T20:00:30.838+0300    WARN    sectors pipeline/fsm.go:792     sector 27620 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
2022-12-03T20:00:31.041+0300    WARN    sectors pipeline/fsm.go:792     sector 27620 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
2022-12-03T20:00:31.241+0300    WARN    sectors pipeline/fsm.go:792     sector 27620 got error event sealing.SectorCommitFailed: proof validation failed, sector not found in sector set after cron
```
