### ISSUE TITLE
The lotus latest version(v1.18.0-rc5) could not boot

### ISSUE THREAD

**Issue by uranuschen365** [filecoin-project/lotus#9594]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.18.0-rc5+calibnet+git.c1e1d00d0.dirty
```

### Describe the Bug

The lotus latest version(v1.18.0-rc5) could not boot

### Logging Information

```text
2022-11-05T15:59:57.683+0800	INFO	backupds	backupds/log.go:232	new log head	{"loghead": "1667209037.log.cbor;1fab7833-a796-44d6-9d29-e560efb920d4;1667635197"}
2022-11-05T15:59:57.842+0800	INFO	badgerbs	v2@v2.2007.3/levels.go:183	All 32 tables opened in 153ms

2022-11-05T15:59:57.843+0800	INFO	badgerbs	v2@v2.2007.3/value.go:1158	Replaying file id: 42 at offset: 500382935

2022-11-05T15:59:57.865+0800	INFO	badgerbs	v2@v2.2007.3/value.go:1178	Replay took: 22.373567ms

ERROR: initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/root/go/src/v1.18.0-rc5/lotus/node/modules/lp2p/addrs.go:85): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build dtypes.AfterGenesisSet: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): genesis in the repo is not the one expected by this version of Lotus!
```

### Repo Steps

1. make clean calibnet
2. lotus daemon
3. See error 'initializing node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/root/go/src/v1.18.0-rc5/lotus/node/modules/lp2p/addrs.go:85): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build lp2p.BaseIpfsRouting: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build dtypes.NetworkName: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build dtypes.AfterGenesisSet: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): genesis in the repo is not the one expected by this version'

**Comment by White957** [comment]
How to solve it？

**Comment by uranuschen365** [comment]
Delete old lotus path and restart lotus daemon.That's all.I think the reason why Calibnet was reset.-------- 原始邮件 --------发件人： White957 ***@***.***>日期： 2022年11月7日周一 15:11收件人： filecoin-project/lotus ***@***.***>抄送： uranuschen365 ***@***.***>, State change ***@***.***>主    题： Re: [filecoin-project/lotus] The lotus latest version(v1.18.0-rc5) could not boot (Issue #9594)

How to solve it？
