### ISSUE TITLE
Daemon and miner "config The "Libp2p" configuration item in the toml "configuration file does not support dnsaddr, and an error is reported after configuration.

### ISSUE THREAD

**Issue by ChaiWenyu1983** [filecoin-project/lotus#9606]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.17.2+mainnet+git.fb0fb7144+api1.5.0
Local: lotus version 1.17.2+mainnet+git.fb0fb7144
```

### Describe the Bug

I try to connect daemon and miner "config In the toml "configuration file, the" Libp2p "configuration item is set to" dnsaddr ". After configuration, miner cannot run.

### Logging Information

```text
A series of error outputs are changed to "ip4", and then they return to normal.
```

### Repo Steps

1. Set the "Libp2p" configuration item in the "miner/config. toml" configuration file as: AnnounceAddresses=["/dnsaddr/xxxx. xxxx. com/tcp/24001", "/ip6/::/tcp/0"]
2. Do 'lotus miner run'
3. See error '...'
...

**Comment by TippyFlitsUK** [comment]
Hi @ChaiWenyu1983 
DNS addresses are definitely supported, I have personally been using one for 2 years +.
What values are you actually setting?

**Comment by ChaiWenyu1983** [comment]
Hi man
&nbsp;&nbsp;My setting is ：
&nbsp; &nbsp;ListenAddresses = ["/ip4/0.0.0.0/tcp/24001", "/ip6/::/tcp/0"]
&nbsp; &nbsp;AnnounceAddresses = ["/dnsaddr/xxx.tpddns.cn/tcp/24001", "/ip6/::/tcp/0"]
Can you share your configuration? Remember to hide key information.




柴文煜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/lotus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月8日(星期二) 晚上9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecoin-project/lotus] Daemon and miner "config The "Libp2p" configuration item in the toml "configuration file does not support dnsaddr, and an error is reported after configuration. (Issue #9606)





 
Hi @ChaiWenyu1983
 DNS addresses are definitely supported, I have personally been using one for 2 years +.
 What values are you actually setting?

**Comment by TippyFlitsUK** [comment]
Set it like this @ChaiWenyu1983 

`/dns4/xxx.tpddns.cn/tcp/24001`

**Comment by ChaiWenyu1983** [comment]
> 
After using the domain name：
lotus-miner net reachability 
AutoNAT status:  Private

**Comment by ChaiWenyu1983** [comment]
> Set it like this @ChaiWenyu1983
> 
> `/dns4/xxx.tpddns.cn/tcp/24001`

After using the domain name：
lotus-miner net reachability
AutoNAT status: Private

**Comment by TippyFlitsUK** [comment]
You also need to publish your address - https://lotus.filecoin.io/storage-providers/setup/initialize/#publishing-the-addresses

**Comment by ChaiWenyu1983** [comment]
"lotus-miner actor set-addrs ..."
I did not forget this. I set it, but it seems to have no effect. I tried to restart Miner and then set it again.



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/lotus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 晚上7:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecoin-project/lotus] Daemon and miner "config The "Libp2p" configuration item in the toml "configuration file does not support dnsaddr, and an error is reported after configuration. (Issue #9606)





 
You also need to publish your address - https://lotus.filecoin.io/storage-providers/setup/initialize/#publishing-the-addresses

**Comment by TippyFlitsUK** [comment]
It can take a little while for the change to be reflected. If you continue to see private it will be a continuing issue with your router or firewall. This is not being caused by Lotus internally, you need to review your network settings.

**Comment by ChaiWenyu1983** [comment]
Do I set "Libp2p" of daemon at the same time? Although different ports are used, they can only set one?






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/lotus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 晚上9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecoin-project/lotus] Daemon and miner "config The "Libp2p" configuration item in the toml "configuration file does not support dnsaddr, and an error is reported after configuration. (Issue #9606)





 
It can take a little while for the change to be reflected. If you continue to see private it will be a continuing issue with your router or firewall. This is not being caused by Lotus internally, you need to review your network settings.

**Comment by ChaiWenyu1983** [comment]
Now it's OK, but the displayed IP is not the domain name. Is this normal?


# lotus-miner net reachability&nbsp;
AutoNAT status:&nbsp; Public
Public address:&nbsp; /ip4/xxx.144.252.205/tcp/24001





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/lotus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 晚上9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecoin-project/lotus] Daemon and miner "config The "Libp2p" configuration item in the toml "configuration file does not support dnsaddr, and an error is reported after configuration. (Issue #9606)





 
It can take a little while for the change to be reflected. If you continue to see private it will be a continuing issue with your router or firewall. This is not being caused by Lotus internally, you need to review your network settings.
