### ISSUE TITLE
[M2] can’t read state of actor t01 while others are ok

### ISSUE THREAD

**Issue by chadwick2143** [filecoin-project/lotus#9612]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version
Daemon:  1.17.1-dev+wallabynet+git.4758f8907+api1.5.0
Local: lotus version 1.17.1-dev+wallabynet+git.4758f8907

and

lotus version
Daemon:  1.17.1-dev+wallabynet+git.c602412eb+api1.5.0
Local: lotus version 1.17.1-dev+wallabynet+git.c602412eb
```

### Describe the Bug

got `ERROR: dumping actor state (a:t01): unmarshaling actor state: cbor input had wrong number of fields` 
when run `lotus state read-state t01`

see https://filecoinproject.slack.com/archives/C03KGBTJ0BY/p1667997376819329

### Logging Information

```text
2022-11-09T21:17:51.845+0800    WARN    rpc     go-jsonrpc@v0.1.9/handler.go:334        error in RPC call to 'Filecoin.StateReadState': dumping actor state (a:t01):
    github.com/filecoin-project/lotus/node/impl/full.(*StateAPI).StateReadState
        /Users/chlore/code/filecoin-project/lotus/node/impl/full/state.go:519
  - unmarshaling actor state:
    github.com/filecoin-project/lotus/chain/vm.DumpActorState
        /Users/chlore/code/filecoin-project/lotus/chain/vm/invoker.go:303
  - cbor input had wrong number of fields
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by raulk** [comment]
This has to do with the `installed_actors` field. Likely the state type hasn't been updated. Regardless, the next release is going to drop support for native actors in preparation for nv18. And this field in the init actor will be dropped anyway, so the problem will disappear.
