### ISSUE TITLE
Sync state: error  version:0.1.2+git0f7be020

### ISSUE THREAD

**Issue by lh232510** [filecoin-project/lotus#967]
2019-12-18T12:20:24.639+0800	ERROR	chain	chain/sync.go:1010	failed to validate tipset: validating block bafy2bzacecj2pzimjyvhu7gvylzrosv4kchhknqz5mdrqno7p2nuecj77r424:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet
        /root/lotus/chain/sync.go:427
  - block was from the future:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock
        /root/lotus/chain/sync.go:488
  - temporal error
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
	/root/lotus/chain/sync.go:1010
github.com/filecoin-project/lotus/chain.(*Syncer).iterFullTipsets
	/root/lotus/chain/sync.go:1034
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState
	/root/lotus/chain/sync.go:1007
github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
	/root/lotus/chain/sync.go:1142
github.com/filecoin-project/lotus/chain.(*Syncer).Sync
	/root/lotus/chain/sync.go:386
github.com/filecoin-project/lotus/chain.(*SyncManager).syncWorker
	/root/lotus/chain/sync_manager.go:386
2019-12-18T12:20:24.640+0800	ERROR	chain	chain/sync_manager.go:388	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /root/lotus/chain/sync.go:392
  - collectChain syncMessages:
    github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /root/lotus/chain/sync.go:1143
  - message processing failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
        /root/lotus/chain/sync.go:1011
  - validating block bafy2bzacecj2pzimjyvhu7gvylzrosv4kchhknqz5mdrqno7p2nuecj77r424:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet
        /root/lotus/chain/sync.go:427
  - block was from the future:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock
        /root/lotus/chain/sync.go:488
  - temporal error
github.com/filecoin-project/lotus/chain.(*SyncManager).syncWorker
	/root/lotus/chain/sync_manager.go:388

**Comment by magik6k** [comment]
This likely means that your system clock is behind. Enabling NTP on your system should solve the issue.
