### ISSUE TITLE
after remove .lotusstorage fold and init same miner ID,going on erro

### ISSUE THREAD

**Issue by chenlvqing** [filecoin-project/lotus#968]
2019-12-18T12:43:48.901+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12418}
2019-12-18T12:43:48.901+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39
2019-12-18T12:43:49.029+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12418}
2019-12-18T12:43:49.030+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39
2019-12-18T12:43:49.789+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12418}
2019-12-18T12:43:49.789+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39
2019-12-18T12:44:47.074+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12419}
2019-12-18T12:44:47.074+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39
2019-12-18T12:44:51.186+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12419}
2019-12-18T12:44:51.186+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39
2019-12-18T12:44:51.214+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12419}
2019-12-18T12:44:51.214+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39
2019-12-18T12:44:51.252+0800	WARN	rpc	jsonrpc/client.go:170	rpc output message buffer	{"n": 2}
2019-12-18T12:44:51.270+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12419}
2019-12-18T12:44:51.270+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39
2019-12-18T12:44:51.522+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12419}
2019-12-18T12:44:51.522+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39
2019-12-18T12:45:37.286+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12420}
2019-12-18T12:45:37.286+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39
2019-12-18T12:45:54.444+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12421}
2019-12-18T12:45:54.445+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39
2019-12-18T12:45:55.650+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12421}
2019-12-18T12:45:55.650+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39
2019-12-18T12:46:29.597+0800	INFO	storageminer	storage/fpost_run.go:69running fPoSt	{"chain-random": "AiNDXcgD7rYcTsvl3aZXJdMa/RPjuTjj3d6avV4f7OQ=", "eps": 12068, "height": 12422}
2019-12-18T12:46:29.598+0800	ERROR	storageminer	storage/fpost_run.go:39runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /root/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 101) from cache
    
    Caused by:
        0: could not open path="/root/.lotusstorage/cache/s-t03177-101/p_aux"
        1: No such file or directory (os error 2)
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
    	/root/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
    	/root/lotus/lib/sectorbuilder/sectorbuilder.go:680
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
    	/root/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    	/root/lotus/storage/fpost_run.go:37
    runtime.goexit
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
	/root/lotus/storage/fpost_run.go:39

**Comment by magik6k** [comment]
What version was this on?

Looking at line numbers this appears to have been happening before we implemented fault handling in fPoSt code, which should get this fixed. Please repoen if you see this issue again
