### ISSUE TITLE
ERROR: failed to open stream to miner: exhausted 15 attempts but failed to open stream, err: failed to dial...

### ISSUE THREAD

**Issue by ChaiWenyu1983** [filecoin-project/lotus#9682]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version
Daemon:  1.17.2+mainnet+git.fb0fb7144+api1.5.0
Local: lotus version 1.17.2+mainnet+git.fb0fb7144

lotus-miner version
Daemon:  1.17.2+mainnet+git.fb0fb7144+api1.5.0
Local: lotus-miner version 1.17.2+mainnet+git.fb0fb7144
```

### Describe the Bug

It seems that everything is normal, but it cannot be linked.

### Logging Information

```text
lotus-miner net reachability  
AutoNAT status:  Public
Public address:  /ip4/xxx.144.252.122/tcp/24001

lotus client query-ask f01862xxx
ERROR: failed to open stream to miner: exhausted 15 attempts but failed to open stream, err: failed to dial 12D3KooWRZZZEZGN9oaRiGAgPZSPDtwKNyvHdq8B16HFMYrhdxxx:
  * [/ip4/219.144.252.122/tcp/24001] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWRZZZEZGN9oaRiGAgPZSPDtwKNyvHdq8B16HFMYrhdxxx but remote key matches 12D3KooWSoM3NkWAz1cEYFq63h46tARnQFEn7JerxJT7WocJkxxx

lotus net peers | wc -l 
125
lotus-miner net peers | wc -l
64
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by Reiers** [comment]
Hi @ChaiWenyu1983 

I see no issues here, make sure you have the right peerID as the ERROR message states. failed to negotiate security 
```
protocol: peer id mismatch: expected 12D3KooWRZZZEZGN9oaRiGAgPZSPDtwKNyvHdq8B16HFMYrhdxxx but remote key matches 12D3KooWSoM3NkWAz1cEYFq63h46tARnQFEn7JerxJT7WocJkxxx
```

I did some testing to make sure - I have no issues connecting to your node with the correct peerID. 

```
lotus-miner net connect /dns4/219.144.252.122/tcp/24001/p2p/12D3KooWSoM3NkWAz1cEYFq63h46tARnQFEn7JerxJT7WocJkA2J
connect 12D3KooWSoM3NkWAz1cEYFq63h46tARnQFEn7JerxJT7WocJkA2J: success
```
```
lotus-miner net connect /dns4/chaiwenyu2.tpddns.cn/tcp/24001/p2p/12D3KooWSoM3NkWAz1cEYFq63h46tARnQFEn7JerxJT7WocJkA2J
connect 12D3KooWSoM3NkWAz1cEYFq63h46tARnQFEn7JerxJT7WocJkA2J: success
```

**Comment by ChaiWenyu1983** [comment]
> 

Where can I configure peerID?

**Comment by ChaiWenyu1983** [comment]
> 

Where can I configure peerID?

**Comment by Reiers** [comment]
First,
`lotus-miner net id`
It should return the new key

Then:
`lotus-miner actor set-peer-id <newkey>`
Wait, for the message to land onChain.

Now it should match ✅ and you should be able to connect without any more changes.

**Comment by ChaiWenyu1983** [comment]
> First, `lotus-miner net id` It should return the new key
> 
> Then: `lotus-miner actor set-peer-id <newkey>` Wait, for the message to land onChain.
> 
> Now it should match ✅ and you should be able to connect without any more changes.

ok,Thank you。
