### ISSUE TITLE
NV17 - Improve Error Message for Invalid Sector Extension

### ISSUE THREAD

**Issue by TippyFlitsUK** [filecoin-project/lotus#9699]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

The current error message displayed to SPs following an invalid deal sector extension in NV17 reads:

```
ERROR: mpool push message: GasEstimateMessageGas error: message execution failed: exit 18, reason: message failed with backtrace:
00: f01013 (method 8) -- cannot use legacy sector extension for simple qa power with deal weight 15 (18)
 (RetCode=18)
```

The current error message may cause unnecessary confusion for SPs who are unfamiliar with the terms - `legacy sector extension` and `simple qa power`.

This enhancement ticket proposes updating the current error message to a more user-friendly format.

Many thanks! :pray:

**Comment by geoff-vball** [comment]
I don't think anyone should actually ever see this message on mainnet. When we implement https://github.com/filecoin-project/lotus/issues/9369, all calls to extend will use `ExtendSectorExpiration2`, which is backwards compatible.

**Comment by TippyFlitsUK** [comment]
Thanks for confirming Geoff 🙏
