### ISSUE TITLE
Use pubsub validator for block validation

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#97]
We should be doing some amount of block validation before rebroadcasting blocks over pubsub, not the full validation, but some structural validation.

This is described in the block propagation spec: https://github.com/filecoin-project/specs/blob/master/data-propagation.md#block-propagation

**Comment by schomatis** [comment]
Closing in favor of https://github.com/filecoin-project/lotus/issues/1535 which includes this.
