### ISSUE TITLE
v1.19.0-rc2 beneficiary	<empty>: error getting actor: GetActor called on undefined address

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#9732]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.19.0-rc2+mainnet+git.2520b1644+api1.5.0
Local: lotus-miner version 1.19.0-rc2+mainnet+git.2520b1644
```

### Describe the Bug

When running `lotus-miner actor control list` without a defined beneficiary, I get this error

> beneficiary	<empty>: error getting actor: GetActor called on undefined address
> name       ID         key        use        balance                     
> owner      f034045    f3quok...          

I expect the control list to simply show  beneficiary as empty or not display it.

### Logging Information

```text
N/A
```

### Repo Steps

`lotus-miner actor control list`
beneficiary	<empty>: error getting actor: GetActor called on undefined address
name       ID         key        use        balance                     
owner      f034045    f3quok...

**Comment by rjan90** [comment]
Hey!

You are seeing the `GetActor called on undefined address` error because the network is still on network version 16 and supporting beneficiary addresses are coming in network version 17. After the upgrade epoch `2383680` on Nov 30th, the actor-address will be on the network and you should not get that error anymore.
