### ISSUE TITLE
Booster-http ID shows up in lotus-miner storage list

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#9733]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon: 1.19.0-rc2+mainnet+git.2520b1644+api1.5.0
Local: lotus-miner version 1.19.0-rc2+mainnet+git.2520b1644

boostd version 1.5.1-rc2+git.2c5604e 
booster-http version 1.5.1-rc2+git.2c5604e
```

### Describe the Bug

When running booster-http the ID for the instance shows up in lotus-miner with an error.
After quitting booster-http the error remains until lotus-miner is restarted.

### Logging Information

```text
1788f7f6-a4e3-42cd-9f4b-225b922bf464:
        Error: no known URLs for remote storage 1788f7f6-a4e3-42cd-9f4b-225b922bf464:
76e06d75-350c-44e7-9042-4cf999183d42:
        Error: no known URLs for remote storage 76e06d75-350c-44e7-9042-4cf999183d42:
b7564b89-95fb-4d02-a9aa-e405b5190693:
        Error: no known URLs for remote storage b7564b89-95fb-4d02-a9aa-e405b5190693:
```

```text
2022-11-26T14:27:18.573Z	WARN	rpc	go-jsonrpc@v0.1.8/handler.go:329	error in RPC call to 'Filecoin.StorageStat': no known URLs for remote storage 1788f7f6-a4e3-42cd-9f4b-225b922bf464:
    github.com/filecoin-project/lotus/storage/paths.(*Remote).FsStat
        /home/stuart/lotus/storage/paths/remote.go:388
2022-11-26T14:27:18.573Z	WARN	rpc	go-jsonrpc@v0.1.8/handler.go:329	error in RPC call to 'Filecoin.StorageStat': no known URLs for remote storage 76e06d75-350c-44e7-9042-4cf999183d42:
    github.com/filecoin-project/lotus/storage/paths.(*Remote).FsStat
        /home/stuart/lotus/storage/paths/remote.go:388
2022-11-26T14:27:18.573Z	WARN	rpc	go-jsonrpc@v0.1.8/handler.go:329	error in RPC call to 'Filecoin.StorageStat': no known URLs for remote storage b7564b89-95fb-4d02-a9aa-e405b5190693:
    github.com/filecoin-project/lotus/storage/paths.(*Remote).FsStat
        /home/stuart/lotus/storage/paths/remote.go:388
```

### Repo Steps

1. Run 'nohup booster-http run --api-boost=$BOOST_API_INFO --api-fullnode=$FULLNODE_API_INFO --api-storage=$MINER_API_INFO'
2. See error as shown above
...

**Comment by magik6k** [comment]
This is likely a boost issue

**Comment by nonsense** [comment]
`booster-http` was incorrectly registering a random UUID for a storage location on every restart. This is now fixed.

**Comment by stuberman** [comment]
Thanks - now running:
`boostd version 1.5.1-rc2+git.b5768c8`
