### ISSUE TITLE
Integrate FIP-0047 into Lotus with Migration

### ISSUE THREAD

**Issue by geoff-vball** [filecoin-project/lotus#9734]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Write a migration for FIP-0047 so we can start testing.

This should probably be built on top of `feat-nv18`

### Describe the solution you'd like

Integrate https://github.com/filecoin-project/go-state-types/pull/124 into lotus

Include migration for https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0047.md

**Comment by jennijuju** [comment]
> @jennijuju I think we may need to wait for [this comment](https://github.com/filecoin-project/builtin-actors/pull/518#issuecomment-1234616889) to be resolved to know exactly what to implement.
> 
> Sectors will start coming into the proof refresh window right after the upgrade, so we will have to implement the mechanism for refreshing them,

Anyone knows this is blocking? Who is driving that to be resolved?

**Comment by jennijuju** [comment]
we dont need this with the latest design of fip0047 any more@
