### ISSUE TITLE
TestGoRPCAuth is flaky

### ISSUE THREAD

**Issue by geoff-vball** [filecoin-project/lotus#9735]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
Master
```

### Describe the Bug

TestGoRPCAuth fails with the following error: 
`        	Error Trace:	/home/circleci/project/itests/ensemble.go:673
        	            				/home/circleci/project/itests/raft_messagesigner_test.go:554
        	Error:      	Received unexpected error:
        	            	failed to sign message: key not found, addr=f3vrsoe2mloxxj22x277fcizcctqc5i6ay6z37mz6ewy5tisf5rxohfulsy7gtur54umumsd3bzagaay3pklta: key not found`

### Logging Information

```text
.
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by geoff-vball** [comment]
@shrenujbansal @magik6k I may have found the source of this bug. https://github.com/filecoin-project/lotus/blob/8fd38750693c8985fc3bdf6925ca4bccf5756aa2/cli/util/api.go#L277 here we don't do anything with this error. I put in a `if err != nil { panic() }` below and it was hit by the test. I'm not sure what the behaviour here should be, so I'm going to leave it up to you to fix :)

(Also remember how happy Aayush gets when we fix flaky tests)

**Comment by rjan90** [comment]
Closing, as the raft node cluster has been dropped: https://github.com/filecoin-project/lotus/pull/11468
