### ISSUE TITLE
splitstore_compact fatal error

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#9743]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
const BuildVersion = "1.19.0-rc2"
```

### Describe the Bug

.lotus/config.toml
[Chainstore]
  EnableSplitstore = true

[Chainstore.Splitstore]
    ColdStoreType = "discard"

start lotus daemon run 
get error

### Logging Information

```text
2022-11-29T07:16:31.038+0800	INFO	chain	chain/sync.go:625	block validation	{"took": 0.492591756, "height": "2379033", "age": 1.038364084}
2022-11-29T07:16:31.039+0800	INFO	chainstore	store/store.go:644	New heaviest tipset! [bafy2bzacectoxvaofxf5lb4jqpa2hjlqdcjlzt36a35hmdghbz33exv64k62a bafy2bzacedokhnhoysxrzjwldicabibp4hww4yptam3yqvmt2ox4524lyi556 bafy2bzaceaqczfpmh65aubsjuprp6ofpu3nxl7b2dfmrm2vyh4vsenbfgzsuq bafy2bzaceafnpjnrqpoqbdtwempjvjbllfq65jxs6bcp7mldvjoibkrvllvmq bafy2bzacecaloqjj7ad4saizksmqnc57optrasyeq4oiizjoduqph5ds4txko bafy2bzacedfttkaovsgfutzr7jy56dtq72ksh3q5tn2swa3ibqvtfrbkmwdbi bafy2bzacebizu5hmc7wgbtpcv3fopccvsxhq2mm2zzbj6eo4i6zwn2zpbemhs] (height=2379033)
2022-11-29T07:16:31.040+0800	INFO	chain	chain/sync_manager.go:323	worker 4083 done; took 496.397186ms
unexpected fault address 0x7bd6d2f87205
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7bd6d2f87205 pc=0x157c81d]

goroutine 18813015 [running]:
runtime.throw({0x412ff11?, 0x0?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc4d46d51c0 sp=0xc4d46d5190 pc=0x6ce991
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:815 +0x125 fp=0xc4d46d5210 sp=0xc4d46d51c0 pc=0x6e4c85
github.com/dgraph-io/badger/v2.(*header).Decode(0x1e6ea5c0?, {0x7bd6d2f87205?, 0x0?, 0xc422581873?})
	/home/fil/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/structs.go:97 +0x1d fp=0xc4d46d5230 sp=0xc4d46d5210 pc=0x157c81d
github.com/dgraph-io/badger/v2.(*valueLog).Read(0xc00cdd69d0, {0xd0ad2270?, 0x7b55?, 0x0?}, 0x7f1d42cd2fe8?)
	/home/fil/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/value.go:1591 +0x2f4 fp=0xc4d46d5360 sp=0xc4d46d5230 pc=0x158a614
github.com/dgraph-io/badger/v2.(*Item).yieldItemValue(0xc0b3f51550)
	/home/fil/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/iterator.go:170 +0x16d fp=0xc4d46d54d0 sp=0xc4d46d5360 pc=0x155c0cd
github.com/dgraph-io/badger/v2.(*Item).Value(0xc0b3f51550, 0xc4dd673e30)
	/home/fil/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/iterator.go:105 +0xc7 fp=0xc4d46d5528 sp=0xc4d46d54d0 pc=0x155ba07
github.com/filecoin-project/lotus/blockstore/badger.(*Blockstore).View.func1(0xc00cdd6800?)
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/badger/blockstore.go:545 +0x10b fp=0xc4d46d55a8 sp=0xc4d46d5528 pc=0x15cb72b
github.com/dgraph-io/badger/v2.(*DB).View(0xc0007cc000?, 0xc4d46d5680)
	/home/fil/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/txn.go:802 +0x9c fp=0xc4d46d55f8 sp=0xc4d46d55a8 pc=0x15809fc
github.com/filecoin-project/lotus/blockstore/badger.(*Blockstore).View(0xc0007cc000, {0x6a135d?, 0x3d157a0?}, {{0xc6c96666f0?, 0xc00025c001?}}, 0xc4dd673e30)
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/badger/blockstore.go:542 +0x1e5 fp=0xc4d46d56e0 sp=0xc4d46d55f8 pc=0x15cb505
github.com/filecoin-project/lotus/blockstore.(*idstore).View(0xc37d029c70, {0x55658c8, 0xc2ad8e61c0}, {{0xc6c96666f0?, 0x3ec77a0?}}, 0xc4dd673e30)
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/idstore.go:89 +0xe2 fp=0xc4d46d5740 sp=0xc4d46d56e0 pc=0xd41322
github.com/filecoin-project/lotus/blockstore.(*discardstore).View(0x5554540?, {0x55658c8?, 0xc2ad8e61c0?}, {{0xc6c96666f0?, 0xc4dd673e30?}}, 0xc4dd673e30?)
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/discard.go:38 +0x30 fp=0xc4d46d5780 sp=0xc4d46d5740 pc=0xd40330
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).view(0xc0002a2780, {{0xc6c96666f0?, 0xc00025c001?}}, 0xc4dd673e30)
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1158 +0x12e fp=0xc4d46d57f0 sp=0xc4d46d5780 pc=0x202ee6e
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObjectIncomplete(0xc0002a2780, {{0xc6c96666f0?, 0xc00025c001?}}, {0x554bb60, 0x8f58e88}, 0xc4d012c090, 0x5235b60)
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1125 +0x265 fp=0xc4d46d58f0 sp=0xc4d46d57f0 pc=0x202e785
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObjectIncomplete(0xc0002a2780, {{0xc6b8faeed0?, 0xc00025c001?}}, {0x554bb60, 0x8f58e88}, 0xc4d012c090, 0x5235b60)
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1136 +0x505 fp=0xc4d46d59f0 sp=0xc4d46d58f0 pc=0x202ea25
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObjectIncomplete(0xc0002a2780, {{0xc6b8faec90?, 0xc00025c001?}}, {0x554bb60, 0x8f58e88}, 0xc4d012c090, 0x5235b60)
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1136 +0x505 fp=0xc4d46d5af0 sp=0xc4d46d59f0 pc=0x202ea25
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObjectIncomplete(0xc0002a2780, {{0xc6b8faeb70?, 0xc00025c000?}}, {0x554bb60, 0x8f58e88}, 0xc4d012c090, 0x5235b60)
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1136 +0x505 fp=0xc4d46d5bf0 sp=0xc4d46d5af0 pc=0x202ea25
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObjectIncomplete(0xc0002a2780, {{0xc6b8faea80?, 0xc4c8cd1428?}}, {0x554bb60, 0x8f58e88}, 0xc4d012c090, 0x5235b60)
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1136 +0x505 fp=0xc4d46d5cf0 sp=0xc4d46d5bf0 pc=0x202ea25
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkChain.func2({{0xc6c0358390?, 0x0?}})
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:959 +0x670 fp=0xc4d46d5ed0 sp=0xc4d46d5cf0 pc=0x202d830
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkChain.func3()
	/mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1013 +0x7d fp=0xc4d46d5f78 sp=0xc4d46d5ed0 pc=0x202d0dd
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/fil/go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75 +0x64 fp=0xc4d46d5fe0 sp=0xc4d46d5f78 pc=0x1700b24
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc4d46d5fe8 sp=0xc4d46d5fe0 pc=0x7025a1
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/fil/go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:72 +0xa5

goroutine 1 [chan receive, 415 minutes]:
main.glob..func9(0xc000d064c0)
```

### Repo Steps

lotus daemon run

**Comment by ZenGround0** [comment]
Very nice find, I'll be looking at this over the next 24 hours

**Comment by ZenGround0** [comment]
Can you reproduce by restarting?  I would expect that to be the case with an unrecoverable compaction error. If so it would help if you could rerun with splitstore logs set to debug mode.  If that works I'll probably also ask you to run a new branch of code with custom log messages to really get to the bottom of this.

**Comment by marco-storswift** [comment]
Ok， test me how to run in debug mode.  It look like  happens every seven hours.

**Comment by ZenGround0** [comment]
Should be this `./lotus log set-level --system splitstore debug`

**Comment by ZenGround0** [comment]
If you want to set this up persistently you can use the config too:

change this
```
[Logging]
  [Logging.SubsystemLevels]
    # env var: LOTUS_LOGGING_SUBSYSTEMLEVELS_EXAMPLE-SUBSYSTEM                                                                                                              
    #example-subsystem = "INFO"     
```

to this 

```
[Logging]
  [Logging.SubsystemLevels]
    # env var: LOTUS_LOGGING_SUBSYSTEMLEVELS_EXAMPLE-SUBSYSTEM                                                                                                              
    splitstore = "DEBUG"     
```

**Comment by marco-storswift** [comment]
Ok , I will restart lotus daemon now

**Comment by marco-storswift** [comment]
@ZenGround0  I run ./lotus log set-level --system splitstore debug， but it look not useful. it crash again.
2022-11-30T18:55:02.584+0800    INFO    chain   chain/sync.go:625       block validation        {"took": 1.487987785, "height": "2383310", "age": 2.584839084}
2022-11-30T18:55:02.586+0800    INFO    chainstore      store/store.go:644      New heaviest tipset! [bafy2bzacecbjuvyrybtcc7w3bsp6gdpxf2qapmcg3yqdyb6citzi7mkqg6sio bafy2bzaceawclx2prxjdp2yaryhoscn4sl54y62myudinthjpz3p52mt6byyg bafy2bzacedcf36ouhyoc4zaohungbluxfu6l2wxkh4qx3vkizwe4vydfjpbze] (height=2383310)
2022-11-30T18:55:02.586+0800    INFO    chain   chain/sync_manager.go:323       worker 4832 done; took 1.492441618s
unexpected fault address 0x7d1ca8a287b3
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7d1ca8a287b3 pc=0x157c81d]

goroutine 20534097 [running]:
runtime.throw({0x412ff11?, 0x0?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc3e5cb71c0 sp=0xc3e5cb7190 pc=0x6ce991
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:815 +0x125 fp=0xc3e5cb7210 sp=0xc3e5cb71c0 pc=0x6e4c85
github.com/dgraph-io/badger/v2.(*header).Decode(0x17f4194d?, {0x7d1ca8a287b3?, 0x0?, 0xc341153053?})
        /home/fil/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/structs.go:97 +0x1d fp=0xc3e5cb7230 sp=0xc3e5cb7210 pc=0x157c81d
github.com/dgraph-io/badger/v2.(*valueLog).Read(0xc00cc5add0, {0x42ef26c8?, 0x7bea?, 0x0?}, 0x7fc4b17a21d8?)
        /home/fil/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/value.go:1591 +0x2f4 fp=0xc3e5cb7360 sp=0xc3e5cb7230 pc=0x158a614
github.com/dgraph-io/badger/v2.(*Item).yieldItemValue(0xc3623cb4a0)
        /home/fil/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/iterator.go:170 +0x16d fp=0xc3e5cb74d0 sp=0xc3e5cb7360 pc=0x155c0cd
github.com/dgraph-io/badger/v2.(*Item).Value(0xc3623cb4a0, 0xc3bd53dd50)
        /home/fil/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/iterator.go:105 +0xc7 fp=0xc3e5cb7528 sp=0xc3e5cb74d0 pc=0x155ba07
github.com/filecoin-project/lotus/blockstore/badger.(*Blockstore).View.func1(0xc00cc5ac00?)
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/badger/blockstore.go:545 +0x10b fp=0xc3e5cb75a8 sp=0xc3e5cb7528 pc=0x15cb72b
github.com/dgraph-io/badger/v2.(*DB).View(0xc000d62000?, 0xc3e5cb7680)
        /home/fil/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/txn.go:802 +0x9c fp=0xc3e5cb75f8 sp=0xc3e5cb75a8 pc=0x15809fc
github.com/filecoin-project/lotus/blockstore/badger.(*Blockstore).View(0xc000d62000, {0x6a135d?, 0x3d157a0?}, {{0xc421eadcb0?, 0xc00025c001?}}, 0xc3bd53dd50)
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/badger/blockstore.go:542 +0x1e5 fp=0xc3e5cb76e0 sp=0xc3e5cb75f8 pc=0x15cb505
github.com/filecoin-project/lotus/blockstore.(*idstore).View(0xc37e008880, {0x55658c8, 0xc18ad61080}, {{0xc421eadcb0?, 0x3ec77a0?}}, 0xc3bd53dd50)
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/idstore.go:89 +0xe2 fp=0xc3e5cb7740 sp=0xc3e5cb76e0 pc=0xd41322
github.com/filecoin-project/lotus/blockstore.(*discardstore).View(0x5554540?, {0x55658c8?, 0xc18ad61080?}, {{0xc421eadcb0?, 0xc3bd53dd50?}}, 0xc3bd53dd50?)
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/discard.go:38 +0x30 fp=0xc3e5cb7780 sp=0xc3e5cb7740 pc=0xd40330
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).view(0xc0003ff180, {{0xc421eadcb0?, 0xc00025c001?}}, 0xc3bd53dd50)
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1158 +0x12e fp=0xc3e5cb77f0 sp=0xc3e5cb7780 pc=0x202ee6e
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObjectIncomplete(0xc0003ff180, {{0xc421eadcb0?, 0xc00025c001?}}, {0x554bb60, 0x8f58e88}, 0xc58794fda0, 0x5235b60)
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1125 +0x265 fp=0xc3e5cb78f0 sp=0xc3e5cb77f0 pc=0x202e785
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObjectIncomplete(0xc0003ff180, {{0xc34c7a8810?, 0xc00025c001?}}, {0x554bb60, 0x8f58e88}, 0xc58794fda0, 0x5235b60)
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1136 +0x505 fp=0xc3e5cb79f0 sp=0xc3e5cb78f0 pc=0x202ea25
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObjectIncomplete(0xc0003ff180, {{0xc3c54ff290?, 0xc00025c001?}}, {0x554bb60, 0x8f58e88}, 0xc58794fda0, 0x5235b60)
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1136 +0x505 fp=0xc3e5cb7af0 sp=0xc3e5cb79f0 pc=0x202ea25
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObjectIncomplete(0xc0003ff180, {{0xc3c54ff050?, 0xc00025c000?}}, {0x554bb60, 0x8f58e88}, 0xc58794fda0, 0x5235b60)
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1136 +0x505 fp=0xc3e5cb7bf0 sp=0xc3e5cb7af0 pc=0x202ea25
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObjectIncomplete(0xc0003ff180, {{0xc3c54fee70?, 0xc2bc663138?}}, {0x554bb60, 0x8f58e88}, 0xc58794fda0, 0x5235b60)
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1136 +0x505 fp=0xc3e5cb7cf0 sp=0xc3e5cb7bf0 pc=0x202ea25
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkChain.func2({{0xc57139e0c0?, 0x0?}})
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:959 +0x670 fp=0xc3e5cb7ed0 sp=0xc3e5cb7cf0 pc=0x202d830
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkChain.func3()
        /mnt/lotus/lotusbuild/20221125094048/marco/blockstore/splitstore/splitstore_compact.go:1013 +0x7d fp=0xc3e5cb7f78 sp=0xc3e5cb7ed0 pc=0x202d0dd
golang.org/x/sync/errgroup.(*Group).Go.func1()

the normal log like this
2022-11-30T18:36:35.363+0800    INFO    splitstore      splitstore/splitstore_compact.go:1026   chain walk done {"walked": 11324894, "scanned": 17203}
2022-11-30T18:36:35.363+0800    INFO    splitstore      splitstore/splitstore_compact.go:608    marking done    {"took": 28533.282937697, "marked": 77623099}
2022-11-30T18:36:35.363+0800    INFO    splitstore      splitstore/splitstore_compact.go:362    protecting transactional references     {"refs": 12072018}
2022-11-30T18:56:51.686+0800    WARN    splitstore      splitstore/splitstore_compact.go:445    missing object reference bafy2bzaceb4lpxlfpedwknzmpfntlharnmy4ahvl6brzaiwhl3nns7dohhecu in bafy2bzacedfluo4dqkwusymyrphczfuoglo3riipwykaeupq4rfxo3lusrxby
2022-11-30T18:56:51.686+0800    WARN    splitstore      splitstore/splitstore_compact.go:445    missing object reference bafy2bzacecn6tkoukh3qmkbpgcg44ir7eixvwkpvmuwhiyvun5ip3zsoxfotu in bafy2bzacedfluo4dqkwusymyrphczfuoglo3riipwykaeupq4rfxo3lusrxby
2022-11-30T18:57:11.622+0800    WARN    splitstore      splitstore/splitstore_compact.go:445    missing object reference bafy2bzaceaivz4grik327756mwuseve5iffjcp2ocouxrjgzrtwipgkdevt74 in bafy2bzacec4meahec4uvb7ejxfpuaooc6xc5ke56gatwdnlsm2teabw5bkgf4
2022-11-30T18:57:11.622+0800    WARN    splitstore      splitstore/splitstore_compact.go:445    missing object reference bafy2bzacecsk6ejtx3lfcwolvp4d2le5tuwmksbllrnunlzgtyqihebxz3ega in bafy2bzacec4meahec4uvb7ejxfpuaooc6xc5ke56gatwdnlsm2teabw5bkgf4
2022-11-30T18:57:36.823+0800    WARN    splitstore      splitstore/splitstore_compact.go:445    missing object reference bafy2bzacebwzxlusr3yeoo5ojqjngvioudu6xzpi5qqdm4g3a4bkklwewfcce in bafy2bzacea6wzyhvsgantt75ot4z3ljcawfpu6dtljv2ifryid6yposylleya
2022-11-30T18:57:36.823+0800    WARN    splitstore      splitstore/splitstore_compact.go:445    missing object reference bafy2bzaceayrl4kzjsyyzu36tq5eeegdy7s545x232u3rjpspthl77v7cc7jk in bafy2bzacea6wzyhvsgantt75ot4z3ljcawfpu6dtljv2ifryid6yposylleya

**Comment by ZenGround0** [comment]
Aha thanks for the WARN splitstore logs, that is helpful

**Comment by Shekelme** [comment]
Not sure if it's related, but I'm getting this right after lotus start (pls. see the attachment).
[lotus_splitstore_issue.log](https://github.com/filecoin-project/lotus/files/11359948/lotus_splitstore_issue.log)

`lotus version 1.23.0+mainnet+git.d1d4b35ad`

**Comment by rjan90** [comment]
Thank you so much for this issue report @marco-storswift!  I will close the issue now, given that this issue is outdated and has been fixed. If you encounter any issue related to SplitStore, please open a new issue!
