### ISSUE TITLE
Problems with the plus sector

### ISSUE THREAD

**Issue by yushui468** [filecoin-project/lotus#9756]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

How to distinguish between normal sector and plus sector

### Describe the solution you'd like

Please provide a method to distinguish the normal sector from the plus sector

### Describe alternatives you've considered

Please provide a method to distinguish the normal sector from the plus sector

**Comment by TippyFlitsUK** [comment]
You can see if a sector deal is verified using the `lotus-miner sectors list` command @yushui468.
