### ISSUE TITLE
nv18 migration integration and testing

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9775]
- [x] Update go-state-types 
- [x]  Migration Integration
This will be something of a living issue -- as we develop nv18, we will have various changes to go-state-types that we'll need to integrate into Lotus 
Each integration will likely involve work to Lotus's state abstractions as well.

- [ ] rerunning the migration using lotus-shed with the latest RC
- [ ]  Ensuring correctness and that it's fast enough
- [ ]  Running the migration in "online" mode -- this means letting the premigration happen while the lotus daemon is syncing the chain, making sure the time and memory usage are okay
- [ ] run state invariant check 
- [ ]  Param finalization: based on time and memory usage of the experiments, we need to settle on the correct number of and epochs for premigration

**Comment by hunjixin** [comment]
please leave the migration time and machine for refrence.

**Comment by geoff-vball** [comment]
Link to FIP-0047 testing here https://filecoinproject.slack.com/archives/CP50PPW2X/p1670912316841949

**Comment by rjan90** [comment]
Closing as the nv18-upgrade has happened!
