### ISSUE TITLE
NV18: Confirm tooling that assumes knowledge of method params / returns don't break

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#9776]
We have tooling that can be used to encode / decode the params & return value of messages. This is important to support for builtin-actors, but cannot be supported for user-defined actors. We need to make sure that such tooling gracefully fails in this case.

**Comment by jennijuju** [comment]
can be a thing happen during calibration

**Comment by scotthconner** [comment]
Is this client side tooling, or libraries/functions inside of lotus itself? Trying to understand this item.

**Comment by jennijuju** [comment]
@scotthconner in lotus cli/api

**Comment by arajasek** [comment]
The best way to confirm this is to call `lotus chain decode params` with the params supplied to messages that deploy and invoke contracts on a devnet / testnet. We expect the "outer" params to decode correctly, but not those that are actually passed to the contract.

More importantly, no panicking / ugly failing.
