### ISSUE TITLE
NV18: EVM actor: Add tooling to inspect state

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#9778]
We'll probably want CLI (and perhaps API) tooling to query an EVM contract's `contract_state` and other fields.

**Comment by jennijuju** [comment]
- get contract params
- get contract address (eth and filecoin)
- eth contract storage location map
- offline mode of `invoke-evm-actor`
- translate between eth tx id to filecoin message cid

**Comment by Stebalien** [comment]
> `eth contract stat <filecoin-or-eth-address>`

Returns:

- Eth address
- Fil address
- Code hash

> `eth contract storage get <filecoin-or-eth-address> <key>`

Returns the value of the storage slot.

> `eth contract call [--to <filecoin-or-eth-address>] [--from ...] <params>`

Call `EthCall` to test a contract execution. I believe this already mostly exists in `invoke-evm-actor`, we just need a version that only runs it locally.


> `eth contract storage list <filecoin-or-eth-address>`

Returns a list of storage keys.

> `eth contract storage list --include-values <filecoin-or-eth-address>`

Returns a list of storage key/value tuples.

**Comment by Stebalien** [comment]
- And some way to convert eth addresses to fil addresses and vice-versa.
- And some way to do the same for eth txn ids and message CIDs.

**Comment by Stebalien** [comment]
Note: storage listing will be hard right now because we don't expose this from the actors.

**Comment by jennijuju** [comment]
@shrenujbansal I found this can be useful for eth tx hash -> filecoin cid https://github.com/filecoin-project/lotus/blob/f681a350fcc9c39a3022a6708fa5da777dd83efa/api/eth_types.go#L415

**Comment by shrenujbansal** [comment]
Revised scope for now:

eth contract stat <filecoin-or-eth-address>
eth contract call [--to <filecoin-or-eth-address>] [--from ...] <params>
<ways to use convert filecoin/eth addrs back and forth>

Postponing:
storage slot tools - needs updated go libs for KAMT parsing
eth tx id -> filecoin cid
