### ISSUE TITLE
Shall we bump lotus to v2.0.0?

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9782]
Supporting user deployed smart contract is a HUGE milestone for Filecoin, should we consider to bump the major version as the ref impl to celebrate this amazing milestone?

**Comment by deltazxm** [comment]
Yes,we should

**Comment by arajasek** [comment]
I would be in favour, assuming it would solely be cosmetic -- don't want any unexpected consequences.

Quoting from the Lotus Release Doc:


> Bumps to the Lotus major version number (1.0.0, 2.0.0, etc.) are reserved for significant changes tothe Filecoin protocol that dramatically transform the network itself. Such changes could include the addition of new Virtual Machines to the protocol, major upgrades to the Proofs of Replication used by Filecoin, etc. These releases are expected to take lots of time to develop and will be rare.


I see no reason not to follow that!

**Comment by scotthconner** [comment]
If its not critical, this could be painting a shed and we should simply table it in favor of fixing bugs, finalizing features, etc. If there could be risk in doing this with no actual user value, let's skip it for now. If people will be confused it isn't 2.0 (I doubt this), then lets skip

**Comment by jennijuju** [comment]
@arajasek what you quoted is correct tho I feel like for that, we probably should wait for the native FVM to be here 😉 😉 

also  from go doc
> You should only update to a new major version when it’s absolutely necessary. A major version update represents significant churn for both you and your module’s users
> ....

> > Be ready to take on the maintenance of two versions: the old and the new. For example, if you fix bugs in one, you’ll often be porting those fixes into the other.
> 
> Remember that a new major version is a new module from a dependency management perspective. Your users will need to update to use a new module after you release, rather than simply upgrading.
> 
> That’s because a new major version has a different module path from the preceding major version. For example, for a module whose module path is example.com/mymodule, a v2 version would have the module path example.com/mymodule/v2.
> 
> When you’re developing a new major version, you must also update import paths wherever code imports packages from the new module. Your module’s users must also update their import paths if they want to upgrade to the new major version.


sounds like a PITA - so imma gonna say lets not bump it /
