### ISSUE TITLE
proving check command for lotus miner must be ran with slow flag

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus#9786]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
Daemon:  1.18.0+calibnet+git.bd10bdf99+api1.5.0
Local: lotus-miner version 1.18.0+calibnet+git.bd10bdf99
```

### Describe the Bug

Running `lotus-miner proving check` against a valid deadline partition fails with the error `ERROR: rg is nil` when the `--slow` flag is not provided.

The storage miner API does not provided a `storiface.RGetter` when the `expensive` parameter for `CheckProvable` is false.

https://github.com/filecoin-project/lotus/blob/bd10bdf99a977fa0f4c538984cf9e3fb84533b0a/node/impl/storminer.go#L1298-L1325

This flag should just not exist, or a "fast" `storiface.RGetter` function needs to be provided when `expensive` is false.

### Logging Information

```text
sudo lotus-miner proving check 0
ERROR: rg is nil
```

**Comment by Reiers** [comment]
PR: https://github.com/filecoin-project/lotus/pull/9643 - it was was understanding that the issue above was fixed.  
Similar issue https://github.com/filecoin-project/lotus/issues/8560
I will leave it open, if this is something else. 👍

**Comment by travisperson** [comment]
Looks the same, not sure why that didn't show up when I searched issues, I swore I just searched `proving check`.
