### ISSUE TITLE
Emergency mitigation backup plan: Disable FEVM

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9797]
https://github.com/filecoin-project/ref-fvm/issues/1202

**Comment by scotthconner** [comment]
Both this item and ref-fvm#1202 are on the nv18 board. For the purposes of clarity I'm not going to modify either - but this seem like a duplicate.

**Comment by jennijuju** [comment]
FVM has too implement a flag for lotus to call, so from lotus side, we just need to integrate it.

**Comment by rjan90** [comment]
Closing this issue now as the FEVM has landed.
