### ISSUE TITLE
Strip out empty spaces around contract bytes

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9803]
for `lotus chain create-evm-actor --hex`

when there is unintentional newlines/empty spaces in  the byte code, one will run into 

`ERROR: failed to decode contract: encoding/hex: invalid byte: U+000`

for user's sake, we should stripe it out before compilation

**Comment by magik6k** [comment]
https://github.com/filecoin-project/lotus/pull/10224
