### ISSUE TITLE
Lotus splitstore not discarding - chain keeps growing

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#9840]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.19.0-rc2+mainnet+git.2520b1644+api1.5.0
Local: lotus-miner version 1.19.0-rc2+mainnet+git.2520b1644

[Chainstore]
  # type: bool
  # env var: LOTUS_CHAINSTORE_ENABLESPLITSTORE
  EnableSplitstore = true

 [Chainstore.Splitstore]
   # ColdStoreType specifies the type of the coldstore.
   # It can be "messages" (default) to store only messages, "universal" to store all chain state or "discard" for discarding cold blocks.
   #
   # type: string
   # env var: LOTUS_CHAINSTORE_SPLITSTORE_COLDSTORETYPE
   ColdStoreType = "discard"
   # EnableColdStoreAutoPrune = false

   # HotStoreType specifies the type of the hotstore.
   # Only currently supported value is "badger".
   #
   # type: string
   # env var: LOTUS_CHAINSTORE_SPLITSTORE_HOTSTORETYPE
   #HotStoreType = "badger"

   # MarkSetType specifies the type of the markset.
   # It can be "map" for in memory marking or "badger" (default) for on-disk marking.
   #
   # type: string
   # env var: LOTUS_CHAINSTORE_SPLITSTORE_MARKSETTYPE
   #MarkSetType = "badger"

   # HotStoreMessageRetention specifies the retention policy for messages, in finalities beyond
   # the compaction boundary; default is 0.
   #
   # type: uint64
   # env var: LOTUS_CHAINSTORE_SPLITSTORE_HOTSTOREMESSAGERETENTION
   #HotStoreMessageRetention = 0

   # HotStoreFullGCFrequency specifies how often to perform a full (moving) GC on the hotstore.
   # A value of 0 disables, while a value 1 will do full GC in every compaction.
   # Default is 20 (about once a week).
   #
   # type: uint64
   # env var: LOTUS_CHAINSTORE_SPLITSTORE_HOTSTOREFULLGCFREQUENCY
   #HotStoreFullGCFrequency = 20
```

### Describe the Bug

Splitstore does not seem to discard old blocks (this is after I imported a new snapshot three days ago)

`du -sch /.lotus/datastore/* | sort -rh`
392G	total
284G	/.lotus/datastore/splitstore
109G	/.lotus/datastore/chain
8.1M	/.lotus/datastore/metadata
20K	/.lotus/datastore/staging
20K	/.lotus/datastore/client

I noticed that the lotus daemon will also quit randomly - see logs below

### Logging Information

```text
2022-11-24T04:49:42.692 INFO filcrypto::util::types > fvm_machine_execute_message: end
2022-11-24T04:49:42.794 INFO filcrypto::util::types > fvm_machine_flush: start
2022-11-24T04:49:43.008 INFO filcrypto::util::types > fvm_machine_flush: end
2022-11-24T04:49:56.902Z	WARN	builder	node/shutdown.go:33	received shutdown
2022-11-24T04:49:56.902Z	WARN	builder	node/shutdown.go:36	Shutting down...
2022-11-24T04:49:56.903Z	INFO	builder	node/shutdown.go:44	rpc server shut down successfully 
2022-11-24T04:49:56.903Z	INFO	dt-impl	impl/impl.go:170	stop data-transfer module
2022-11-24T04:49:56.903Z	WARN	events	events/observer.go:61	listenHeadChanges quit
2022-11-24T04:49:56.903Z	WARN	events	events/observer.go:66	not restarting listenHeadChanges: context error: context canceled
2022-11-24T04:49:56.903Z	WARN	events	events/observer.go:61	listenHeadChanges quit
2022-11-24T04:49:56.903Z	WARN	events	events/observer.go:66	not restarting listenHeadChanges: context error: context canceled
2022-11-24T04:49:56.904Z	WARN	sub	sub/incoming.go:438	error from message subscription: context canceled
2022-11-24T04:49:56.904Z	WARN	sub	sub/incoming.go:440	quitting HandleIncomingMessages loop
2022-11-24T04:49:56.904Z	WARN	sub	sub/incoming.go:55	quitting HandleIncomingBlocks loop
2022-11-24T04:49:56.904Z	WARN	peermgr	peermgr/peermgr.go:154	closing peermgr done
2022-11-24T04:49:56.904Z	WARN	peermgr	peermgr/peermgr.go:172	exiting peermgr run
2022-11-24T04:49:56.904Z	WARN	chainstore	store/store.go:616	reorgWorker quit
2022-11-24T04:49:56.904Z	WARN	splitstore	splitstore/splitstore.go:779	close with ongoing compaction in progress; waiting for it to finish...
2022-11-24T04:49:56.908Z	INFO	pubsub	go-libp2p-pubsub@v0.8.0/pubsub.go:640	pubsub processloop shutting down
2022-11-24T04:49:57.891Z	ERROR	splitstore	splitstore/splitstore_warmup.go:40	error warming up hotstore: error walking block (cid: bafy2bzacea4aeq6v2gdvre2txt3mmc5hsnz2j4ksrhheovmvn3uxbapuxx4cw): error walking state root (cid: bafy2bzacedi5adkbupv3cu5ichsa776jvgochor4or3k6n7cxarm4dnbza2qs): error walking link (cid: bafy2bzacectp2gnv2e5zzmlbhcxryggvpt3okboxfv3kacguz4ezthi4m4lje): error walking link (cid: bafy2bzacecl6tsngoa47mpboat65k6v6hwu7yagclr5bhxfsgoetpdtxzatwg): error walking link (cid: bafy2bzacedvrnrtom4fadhpoyvqmmoac5bxvzucorzwckr3qhtf5wlqs6gdzq): error walking link (cid: bafy2bzacecqx5xs4uk232v2xe7euwbj5s47zo4z64t75yfowjgjiz54bu42ya): error walking link (cid: bafy2bzacecs4vfmtttelwagv7stdw777mkrcgyatqv253uthilay3hst6qv5w): error walking link (cid: bafy2bzaceasb4hymydff2eej7jr4vsfiqedpcyajzotanrgjb3np3wqymqd46): error walking link (cid: bafy2bzacecmhi4kfcbmo2efxp677yifh7yz2pnhski7pxf42xunt3dqs4qoy2): error walking link (cid: bafy2bzacecouc4r5sc7pc2hmg67g3oe6ne64t7nhtdmzalevbrfzxw3d6bwuk): error walking link (cid: bafy2bzacebmdcqvc4plfhi5ufnqr4npov42tt5gnwd45bnghssq43yshknf4u): error walking link (cid: bafy2bzaceb2cs5w5z75qqa7bppnfh53b5xkjd2helbifwmavvhmsbkgyu3jsi): splitstore is closing
2022-11-24T04:49:58.230Z	INFO	badgerbs	v2@v2.2007.3/db.go:1031	Storing value log head: {Fid:66 Len:34 Offset:1041111137}

2022-11-24T04:49:58.438Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1000	[Compactor: 173] Running compaction: {level:0 score:1.73 dropPrefixes:[]} for level: 0

2022-11-24T04:49:59.778Z	INFO	engine	decision/engine.go:657	aborting message processingshutting down
2022-11-24T04:49:59.898Z	INFO	engine	decision/engine.go:657	aborting message processingshutting down
2022-11-24T04:50:00.048Z	INFO	engine	decision/engine.go:657	aborting message processingshutting down
2022-11-24T04:50:00.171Z	INFO	engine	decision/engine.go:657	aborting message processingshutting down
2022-11-24T04:50:00.205Z	INFO	badgerbs	v2@v2.2007.3/levels.go:962	LOG Compact 0->1, del 7 tables, add 6 tables, took 1.766679993s

2022-11-24T04:50:00.205Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1010	[Compactor: 173] Compaction for level: 0 DONE
2022-11-24T04:50:00.205Z	INFO	badgerbs	v2@v2.2007.3/db.go:554	Force compaction on level 0 done
2022-11-24T04:50:00.378Z	INFO	builder	node/shutdown.go:44	node shut down successfully 
2022-11-24T04:50:00.378Z	WARN	builder	node/shutdown.go:47	Graceful shutdown successful
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by stuberman** [comment]
Chain log from last hour:

[chain.txt](https://github.com/filecoin-project/lotus/files/10204969/chain.txt)

**Comment by stuberman** [comment]
Chainlog (node) last 5 hours

[chain2.txt](https://github.com/filecoin-project/lotus/files/10204989/chain2.txt)

**Comment by vyzo** [comment]
try setting HotStoreFullGCFrequency to something like 1, so as ti force moving gc on badger.

It happens once a week by default. You can set it to 3 if you want it to occur daily.

**Comment by NodeKing** [comment]
I'm experiencing the same issues. The splitstore seems to keep growing. I have implemented the HotStoreFullGCFrequency=1 configuration, but it hasn't helped:

current size: 
lotus/datastore                                                                                                                                
  476.5 GiB  /splitstore
  110.2 GiB /chain

docker run command in use:
P2P_ANNOUNCE_IP=$(wget -qO- ifconfig.me/ip)
  docker run -d --name lotus \
    --user 532:532 \
    --network host \
    -e LOTUS_API_LISTENADDRESS=/ip4/0.0.0.0/tcp/8545/http \
    -e LOTUS_LIBP2P_LISTENADDRESSES=/ip4/0.0.0.0/tcp/6665 \
    -e LOTUS_LIBP2P_ANNOUNCEADDRESSES=/ip4/$P2P_ANNOUNCE_IP/tcp/6665 \
    -e LOTUS_LIBP2P_DISABLENATPORTMAP=true \
    -e LOTUS_CHAINSTORE_ENABLESPLITSTORE=true \
    -e LOTUS_CHAINSTORE_SPLITSTORE_COLDSTORETYPE=discard \
    -e LOTUS_CHAINSTORE_SPLITSTORE_ENABLECOLDSTOREAUTOPRUNE=false \
    -e LOTUS_CHAINSTORE_SPLITSTORE_HOTSTOREFULLGCFREQUENCY=1 \
    -v /blockchain/lotus:/var/lib/lotus \
    -v /blockchain/lotus-tmp/filecoin-proof-parameters:/var/tmp/filecoin-proof-parameters \
    filecoin/lotus:v1.18.2 daemon

**Comment by NodeKing** [comment]
I also have a second server running with the following config (same issue)

lotus/datastore                                                                                                                              
  593.4 GiB  /splitstore
  104.7 GiB  /chain
  
  Using essentially the same config. But has pruning enabled, and missing the HOTSTOREFULLGCFREQUENCY=1 config
  
  P2P_ANNOUNCE_IP=$(wget -qO- ifconfig.me/ip)
  docker run -d --name lotus \
    --user 532:532 \
    --network host \
    -e LOTUS_API_LISTENADDRESS=/ip4/0.0.0.0/tcp/8545/http \
    -e LOTUS_LIBP2P_LISTENADDRESSES=/ip4/0.0.0.0/tcp/6665 \
    -e LOTUS_LIBP2P_ANNOUNCEADDRESSES=/ip4/$P2P_ANNOUNCE_IP/tcp/6665 \
    -e LOTUS_LIBP2P_DISABLENATPORTMAP=true \
    -e LOTUS_CHAINSTORE_ENABLESPLITSTORE=true \
    -e LOTUS_CHAINSTORE_SPLITSTORE_COLDSTORETYPE=discard \
    -e LOTUS_CHAINSTORE_SPLITSTORE_ENABLECOLDSTOREAUTOPRUNE=true \
    -v /blockchain/lotus:/var/lib/lotus \
    -v /blockchain/lotus-tmp/filecoin-proof-parameters:/var/tmp/filecoin-proof-parameters \
    filecoin/lotus:v1.18.2 daemon

I have been experimenting with different configurations for weeks without success.. Any guidance would be greatly appreciated.

**Comment by stuberman** [comment]
I did not see this helping this issue, downloading a new minimal snapshot, by deleting the cold store (/chain) and hot store ( ./lotus/lotus-shed splitstore clear --repo=/.lotus) and setting  HOTSTOREFULLGCFREQUENCY=1.

What seems to work is downloading a minimal snapshot and then before importing, renaming .lotus/datastore to .lotus/datastore.old. The import process would then rebuild the entire directory possibly eliminating any corrupt or old entries.

**Comment by TippyFlitsUK** [comment]
`./lotus/lotus-shed splitstore clear` is essentially doing exactly the same thing, Stu. `HOTSTOREFULLGCFREQUENCY` can also be set to a lower number if hotstore space is limited.

**Comment by stuberman** [comment]
> `./lotus/lotus-shed splitstore clear` is essentially doing exactly the same thing, Stu. `HOTSTOREFULLGCFREQUENCY` can also be set to a lower number if hotstore space is limited.

However, it also removes the metadata, client and staging data.

BTW - It is now fully obvious to me that lotus client retrievals (legacy deals from Evergreen) cause all sorts of chain issues. That process uses GraphSync and causes the chain to lose sync.

**Comment by TippyFlitsUK** [comment]
> However, it also removes the metadata, client and staging data.

Those folders have no impact on the splitstore size. `./lotus/lotus-shed splitstore clear` is the recommended method of clearing the splitstore for a re-import.

> BTW - It is now fully obvious to me that lotus client retrievals (legacy deals from Evergreen) cause all sorts of chain issues. That process uses GraphSync and causes the chain to lose sync.

Very interesting!! Thanks Stu, I will add that to our current monitoring. 🙏

**Comment by NodeKing** [comment]
I created a new server when starting to use the HOTSTOREFULLGCFREQUENCY=1 setting @TippyFlitsUK . 

I first run the container with the config from my first post, but with this final line instead to import from snapshot:
`filecoin/lotus:v1.18.2 daemon --import-snapshot https://snapshots.mainnet.filops.net/minimal/latest --halt-after-import true`

**Comment by stuberman** [comment]
I am still seeing the chain grow even with `HotStoreFullGCFrequency = 1`

`du -sch /.lotus/datastore/* | sort -rh`

> 715G	total
> 604G	/.lotus/datastore/splitstore
> 112G	/.lotus/datastore/chain
> 9.5M	/.lotus/datastore/metadata
> 20K	/.lotus/datastore/staging
> 20K	/.lotus/datastore/client

**Comment by stuberman** [comment]
BTW - I continue to see the chain sync get stuck and fall behind several times a day. I restart the service every 12 hours to keep the chain sync'ed. I hear this is a common problem.

**Comment by stuberman** [comment]
`./lotus-shed splitstore info`

> warmup epoch: 2.43576e+06
> base epoch: 2.43576e+06
> compacting: true
> compactions: 0
> hotstore size: 8.02180837946e+11
> prunes: 0

`~/lotus$ du -sch /.lotus/datastore/* | sort -rh`

> 862G	total
> 751G	/.lotus/datastore/splitstore
> 112G	/.lotus/datastore/chain
> 12M	/.lotus/datastore/metadata
> 20K	/.lotus/datastore/staging
> 20K	/.lotus/datastore/client

**Comment by stuberman** [comment]
I was forced to download a new snapshot again two days ago as the size of the hot store was at 1 TiB
`HotStoreFullGCFrequency = 1`

`./lotus-shed splitstore info`

> base epoch: 2.46768e+06
> compacting: true
> compactions: 0
> hotstore size: 4.30981607577e+11
> prunes: 0
> warmup epoch: 0

`du -sch /.lotus/datastore/* | sort -rh`

> 541G	total
> 426G	/.lotus/datastore/splitstore
> 115G	/.lotus/datastore/chain
> 7.1M	/.lotus/datastore/metadata
> 20K	/.lotus/datastore/staging
> 20K	/.lotus/datastore/client

**Comment by NodeKing** [comment]
I'm creating a new server too, as the server is now using 1.5TB of space.

**Comment by TippyFlitsUK** [comment]
Have you tried adjusting the splistore settings at all @NodeKing ?

**Comment by NodeKing** [comment]
Have tried variants of the below env var's, without any success. Can you suggest a config to try?

`LOTUS_CHAINSTORE_ENABLESPLITSTORE=true
LOTUS_CHAINSTORE_SPLITSTORE_COLDSTORETYPE=discard
LOTUS_CHAINSTORE_SPLITSTORE_ENABLECOLDSTOREAUTOPRUNE=true
LOTUS_CHAINSTORE_SPLITSTORE_HOTSTOREFULLGCFREQUENCY=1`

**Comment by shawnp0wers** [comment]
I had a miner that cleaned up after itself for a while, but now just keeps growing and growing. The discard process doesn't seem to happen. How does that part work? Once stuff is moved to coldstore, when does it get deleted? (It seems that "prune" means something different in this instance?)

**Comment by NodeKing** [comment]
I'm under the impress that the pruning never occurs because the cold store is meant to be discarding, so the autoPrune env var is probably redundant config. Would be good to get some clarity on this. 

lotus-shed splitstore info
prunes: 0
warmup epoch: 0
base epoch: 2.492838e+06
compacting: true
compactions: 4
hotstore size: 1.75710129714e+11

**Comment by TippyFlitsUK** [comment]
What version of lotus are you running @NodeKing?

**Comment by NodeKing** [comment]
Still using the same version as the docker run commands above @TippyFlitsUK : filecoin/lotus:v1.18.2

**Comment by TippyFlitsUK** [comment]
Thanks @NodeKing!

Would you be able to upgrade to [v1.19.0](https://github.com/filecoin-project/lotus/releases/tag/v1.19.0) with a fresh snapshot and fully clean `chain `and `datastore` folders?

`1.19.0` includes SplitStore updates that may help with the issues that you are seeing. I have been using this version for weeks with the settings below and am not experiencing any issues at all.

Please note that the AutoPrune feature has been retired in `1.19.0`, you can see all the [updated docs here](https://lotus.filecoin.io/lotus/configure/splitstore/).

Many thanks!!

```
LOTUS_CHAINSTORE_ENABLESPLITSTORE=true
LOTUS_CHAINSTORE_SPLITSTORE_COLDSTORETYPE=discard
LOTUS_CHAINSTORE_SPLITSTORE_HOTSTOREFULLGCFREQUENCY=10
```

**Comment by shawnp0wers** [comment]
I have 2 miners on splitstore with discard now. Both 1.19.0.

My test miner (mainnet) did discard once, going from 500ish to 350ish, but after that kept growing until it was over 750GB, then it fell out of sync completely.

My production miner on splitstore (still sealing) grew to about 650GB, but did go down to 400GB overnight. The process seems to be hit or miss, and troubleshooting is like peering into a mysterious black box.

**Comment by TippyFlitsUK** [comment]
What settings are you using @shawnp0wers and did you fully clean the `chain` and `splitstore` folder before importing?

**Comment by shawnp0wers** [comment]
Yes, multiple times in multiple ways. In fact now, I delete everything in the `datastore` folder, and import a new snapshot allowing/forcing lotus to create whatever it likes in there.

The settings I have are:
```
[Chainstore]
EnableSplitstore = true

[Chainstore.Splitstore]
ColdStoreType = "discard"
```

**Comment by TippyFlitsUK** [comment]
Thanks Shawn!!
Using the default 20 for `HotStoreFullGCFrequency` will definitely result in a much larger hotstore and a longer process when it comes to GC.
I have found that 10 works very well for me. Would you be able to redo the snapshot import on a clean dtatastore with `HotStoreFullGCFrequency=10`?
Many thanks :pray:

**Comment by shawnp0wers** [comment]
Changed, and doing a fresh snapshot import now!

What is the tradeoff for a lower number? Is there a reason not to set it to `1` for instance?

**Comment by shawnp0wers** [comment]
Also, I assume this setting goes in the `[Chainstore.Splitstore]` section, correct?

**Comment by TippyFlitsUK** [comment]
Thanks Shawn!!

It does indeed live in the `[Chainstore.Splitstore]` section.

Setting 20 will trigger a GC about once a week and 10 would trigger it twice a week. Setting 1 would cause a GC in every compaction (finality) and may well work for you but it does mean that the daemon will be processing a lot more GC jobs which are pretty resource intensive and can cause temp loss of sync on less powerful systems. Also bear in mind that a GC only once a week will obviously be a bigger and longer GC job when it gets triggered as it has more chain to walk.

Is a question of finding a number that works best for your unique setup.

**Comment by RobQuistNL** [comment]
I have been running with that setting set to 5 for the month. Worked fine, up until 4 days ago. 

Blue dotted line is upgrade to 1.19 (that should have fixed the older hotstore GC issues that were introduced in 1.18)

But somehow since 01/06 you can see it starts behaving like 1.18 again.

![image](https://user-images.githubusercontent.com/1442796/211921820-a14b80b0-134e-4eba-a6d5-a8957395e2ef.png)

**Comment by TippyFlitsUK** [comment]
https://filecoinproject.slack.com/archives/CPFTWMY7N/p1673472134663959

**Comment by TippyFlitsUK** [comment]
Can you please attach your daemon logs covering 04/01-11/01 @RobQuistNL? :pray:

**Comment by NodeKing** [comment]
We have three filecoin servers running on version 1.19 and they're all consuming over 1TB of space once again.. 

Using the settings as you recommended @TippyFlitsUK 
`LOTUS_CHAINSTORE_ENABLESPLITSTORE=true
LOTUS_CHAINSTORE_SPLITSTORE_COLDSTORETYPE=discard
LOTUS_CHAINSTORE_SPLITSTORE_HOTSTOREFULLGCFREQUENCY=10`


Should I lower the LOTUS_CHAINSTORE_SPLITSTORE_HOTSTOREFULLGCFREQUENCY to 5 ? 

Can you advise what storage usage we should expect with the above settings?

**Comment by stuberman** [comment]
I have tried GV settings of (default) 20, then 1 and now 10 with the same results.   Got store continues to grow and sync falls behind after a few days causing me to restart lotus daemon to catch up.   I will have to import a minimal snapshot again soon.

**Comment by vyzo** [comment]
Are there any splitstore logs?
It sounds to me that compaction is not running to completion.

**Comment by vyzo** [comment]
Its right there -- warm up is erroring with a missing ref; cc @ZenGround0

**Comment by William8Work** [comment]
my daemon ran into similar issue. Change the hotstore GC frequency to 20, then to 10, now is running at 1. Did not help. The hotstore size is now at 1.7TB out of 1.9 TB drive. I need to delete the datastore folder and re-import the snapshot to clear the disk space.
[daemon-f08399-2023.zip](https://github.com/filecoin-project/lotus/files/10574735/daemon-f08399-2023.zip)

**Comment by RobQuistNL** [comment]
Some more discussions about this issue; https://filecoinproject.slack.com/archives/CPFTWMY7N/p1673472134663959

**Comment by vyzo** [comment]
I think we should -- pinging @jennijuju @ZenGround0 

The issue is that compaction fails with some unreachable object. Root cause may be changes in what is reachable with the new fvm stuffs or some other change that makes the compactor try to traverse something unreachable.

**Comment by jennijuju** [comment]
> I think we should -- pinging @jennijuju @ZenGround0
> 
> The issue is that compaction fails with some unreachable object. Root cause may be changes in what is reachable with the new fvm stuffs or some other change that makes the compactor try to traverse something unreachable.

Haha great timing! https://filecoinproject.slack.com/archives/CP50PPW2X/p1676297112125189

**Comment by ZenGround0** [comment]
> Its right there -- warm up is erroring with a missing ref

@vyzo Where?

**Comment by vyzo** [comment]
One of the top logs...

**Comment by ZenGround0** [comment]
Do you mean this one?

```
2022-11-24T04:49:57.891Z	ERROR	splitstore	splitstore/splitstore_warmup.go:40	error warming up hotstore: error walking block (cid: bafy2bzacea4aeq6v2gdvre2txt3mmc5hsnz2j4ksrhheovmvn3uxbapuxx4cw): error walking state root (cid: bafy2bzacedi5adkbupv3cu5ichsa776jvgochor4or3k6n7cxarm4dnbza2qs): error walking link (cid: bafy2bzacectp2gnv2e5zzmlbhcxryggvpt3okboxfv3kacguz4ezthi4m4lje): error walking link (cid: bafy2bzacecl6tsngoa47mpboat65k6v6hwu7yagclr5bhxfsgoetpdtxzatwg): error walking link (cid: bafy2bzacedvrnrtom4fadhpoyvqmmoac5bxvzucorzwckr3qhtf5wlqs6gdzq): error walking link (cid: bafy2bzacecqx5xs4uk232v2xe7euwbj5s47zo4z64t75yfowjgjiz54bu42ya): error walking link (cid: bafy2bzacecs4vfmtttelwagv7stdw777mkrcgyatqv253uthilay3hst6qv5w): error walking link (cid: bafy2bzaceasb4hymydff2eej7jr4vsfiqedpcyajzotanrgjb3np3wqymqd46): error walking link (cid: bafy2bzacecmhi4kfcbmo2efxp677yifh7yz2pnhski7pxf42xunt3dqs4qoy2): error walking link (cid: bafy2bzacecouc4r5sc7pc2hmg67g3oe6ne64t7nhtdmzalevbrfzxw3d6bwuk): error walking link (cid: bafy2bzacebmdcqvc4plfhi5ufnqr4npov42tt5gnwd45bnghssq43yshknf4u): error walking link (cid: bafy2bzaceb2cs5w5z75qqa7bppnfh53b5xkjd2helbifwmavvhmsbkgyu3jsi): splitstore is closing
```
from stuberman's original comment? I thought so at first too but its just wrapping a splitstore closure, this is expected.  I saw a proper COMPACTION ERROR like this when digging through f08399's logs too and they were all splitstore closures.

Let me know if it was a different one, if you can point me to an unexpected compaction failure it would be obviously be very helpful.

**Comment by ZenGround0** [comment]
High level possible reasons state grows without bound in discard mode.  Somewhere somehow some expected GC work is not getting done.

1) Compaction is erroring. We will see COMPACTION ERROR in the logs (note we'll also see this during lotus shutdown when compacting which is not an error)
2) Compaction isn't getting called.
3) Compaction is getting called and its skipping out on work leaving dead state hanging
4) cid level compact is working great but badger level GC leaves dead state hanging even after forcing badger compaction

Whatever the root cause it also seems somewhat non deterministic because some configurations can get it to work.

**Comment by ZenGround0** [comment]
My next step is to modify debug logs to closely track data movement during compaction and badger GC.  This should help us classify the scenario into one of the four options above.  Once I've got a decent set of logs merged somewhere I'll request impacted operators to run this patch and we can consolidate measurements here.

In the meantime if anyone has logs with evidence that compaction is not running as often as expected or that compaction is failing unexpectedly please post them here.  I can't rule these options out yet but also haven't found evidence of either behaviors from the provided logs in thread.

**Comment by stuberman** [comment]
Daemon log can be found [here](https://drive.google.com/drive/folders/17aWZJipHVbbWBlGTqhjiSnkoBn_hqhoW?usp=sharing)

**Comment by SBudo** [comment]
Having the same issue, but only on one of our daemons.
All the other daemons, which are identical (hardware, software) are fine.
Tried to clean up the chain folder, as well as the splitstore and re-import a fresh snapshot multiple times, but it keeps on filling up the disk and eventually runs out

**Comment by NodeKing** [comment]
Has this issue be addressed in the latest release 1.20.0 ?

**Comment by stuberman** [comment]
> Has this issue be addressed in the latest release 1.20.0 ?

Not yet. It is prevalent with those running lotus daemon with systemd.

**Comment by Shekelme** [comment]
> rabinovitch@lotus:~$ du -h -s /home/rabinovitch/.lotus/datastore/splitstore && du -h -s /home/rabinovitch/.lotus/datastore/chain
> 1,5T    /home/rabinovitch/.lotus/datastore/splitstore
> 217G    /home/rabinovitch/.lotus/datastore/chain

((

**Comment by stuberman** [comment]
@ZenGround0 one thing we noted when using systemd is that the default profile for lotus is not suitable

Lotus default

> MemoryAccounting=true
> MemoryHigh=8G
> MemoryMax=10G
> LimitNOFILE=8192:10240

This improves splitstore compaction:

> MemoryAccounting=false
> MemoryHigh=16G
> MemoryMax=infinity
> LimitNOFILE=1024000:1024000

`cat lotus/scripts/lotus-daemon.service`

> [Unit]
> Description=Lotus Daemon
> After=network-online.target
> Requires=network-online.target
> 
> [Service]
> Environment=GOLOG_FILE="/var/log/lotus/daemon.log"
> Environment=GOLOG_LOG_FMT="json"
> ExecStart=/usr/local/bin/lotus daemon
> Restart=always
> RestartSec=10
> 
> MemoryAccounting=true
> MemoryHigh=8G
> MemoryMax=10G
> LimitNOFILE=8192:10240
> 
> [Install]
> WantedBy=multi-user.target

**Comment by YuXiaoCoder** [comment]
I have the same problem, my configuration is as follows
```toml
[Chainstore]
  EnableSplitstore = true
  [Chainstore.Splitstore]
    ColdStoreType = "discard"
    HotStoreType = "badger"
    MarkSetType = "badger"
    HotStoreMessageRetention = 0
    HotStoreFullGCFrequency = 3
```
The software version is 1.20.1

**Comment by froid1911** [comment]
Have the same issue :(((

**Comment by RobQuistNL** [comment]
Related: https://github.com/filecoin-project/lotus/issues/10712 https://github.com/filecoin-project/lotus/issues/10711 https://github.com/filecoin-project/lotus/issues/10710

**Comment by PierreTwo** [comment]
We still have the issue and are rebuilding our servers every couple of weeks.

**Comment by NodeKing** [comment]
We still have the issue and are rebuilding our servers every couple of weeks.

**Comment by NodeKing** [comment]
v1.23.0 resolved our issue too. Our servers were pretty flakey on this version for some time, getting out of sync with the network. Servers needed frequent rebooting to get back in sync. Everything eventually stabilised on it's own and we ended up with massive disk space savings. 

Our nodes were getting up to 2TB of used space before we would rebuild them, now they're using usage ~280GB.

**Comment by Shekelme** [comment]
![image](https://github.com/filecoin-project/lotus/assets/26449500/c7d8bc8b-aa2f-4d75-9a8e-c250872e99b8)
![image](https://github.com/filecoin-project/lotus/assets/26449500/989b4660-04d2-4784-8d13-f574f7b8b33d)
![image](https://github.com/filecoin-project/lotus/assets/26449500/2824e677-dbd1-464a-a1d0-8f7c36a393e0)

Can't say the same as @NodeKing. But apparently the volume is not growing and the drives are not overflowing.

**Comment by TippyFlitsUK** [comment]
Can you run a lotus chain prune hot-moving @Shekelme? My most recent run took me all the way down to 126 GiB.

**Comment by stuberman** [comment]
I have not had any problems with compaction since I changed the sync from systemd to a local task.
My chain has been running for months now without a need to reimport a minimal snapshot.
