### ISSUE TITLE
proof validation failed, sector not found in sector set after cron

### ISSUE THREAD

**Issue by phantom-rabbit** [filecoin-project/lotus#9841]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
The code has changed。
```

### Describe the Bug

I have a sector that has an error in CommitWait.
message in browser：https://filscout.com/en/message/bafy2bzacedrekodgatlqbbfmoejtjo3vu4dlzxwrejz2fckecvj4bmmnrqqna
It looks similar to other successful sectors。

[seal.log](https://github.com/filecoin-project/lotus/files/10206317/seal.log)

It seems that the whole sealing process is normal. My miner code has been modified, but it looks like an error in the chain。
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/49083897/207004846-1a7a27b0-c8c9-414c-a13f-2a8d75125e46.png">

I'm sure my lotus code hasn't changed。

This is a valid data transaction, and I am eager to make it work normally。
Welcome friends with such faults to discuss。

### Logging Information

```text
none
```

### Repo Steps

I can't reproduce the problem。

**Comment by iseriser** [comment]
I do confirm the problem exists.
But `lotus-miner sectors update-state --really-do-it [sectorId] CommitFinalize` helps

**Comment by iseriser** [comment]
More details:
1) If sector is with the following log details - it Finalizes okay!
`4841.	2022-12-28 09:45:00 +0000 UTC:	[event;sealing.SectorCommitFailed]	{"User":{}}
	proof validation failed, sector not found in sector set after cron
4842.	2022-12-28 09:45:00 +0000 UTC:	[event;sealing.SectorFinalized]	{"User":{}}
4843.	2022-12-28 09:45:00 +0000 UTC:	[error;*xerrors.wrapError]	state machine error: running planner for state CommitFinalize failed: planner for state CommitFinalize received unexpected event sealing.SectorCommitFailed ({User:proof validation failed, sector not found in sector set after cron})
4844.	2022-12-28 09:45:00 +0000 UTC:	[event;sealing.SectorFinalized]	{"User":{}}`

2) If sector is with the following log details - it continues to hop between SectorRetryCommitWait and SectorCommitFailed
`6784.	2022-12-28 09:36:21 +0000 UTC:	[event;sealing.SectorRetryCommitWait]	{"User":{}}
6785.	2022-12-28 09:36:21 +0000 UTC:	[event;sealing.SectorRetryCommitWait]	{"User":{}}
6786.	2022-12-28 09:36:21 +0000 UTC:	[event;sealing.SectorRetryCommitWait]	{"User":{}}
6787.	2022-12-28 09:36:21 +0000 UTC:	[event;sealing.SectorFinalized]	{"User":{}}
6788.	2022-12-28 09:36:21 +0000 UTC:	[error;*xerrors.wrapError]	state machine error: running planner for state CommitFinalize failed: planner for state CommitFinalize received unexpected event sealing.SectorRetryCommitWait ({User:{}})
6789.	2022-12-28 09:36:21 +0000 UTC:	[event;sealing.SectorRetryCommitWait]	{"User":{}}
6790.	2022-12-28 09:36:21 +0000 UTC:	[event;sealing.SectorFinalized]	{"User":{}}
6791.	2022-12-28 09:36:21 +0000 UTC:	[error;*xerrors.wrapError]	state machine error: running planner for state CommitFinalize failed: planner for state CommitFinalize received unexpected event sealing.SectorRetryCommitWait ({User:{}})
6792.	2022-12-28 09:36:21 +0000 UTC:	[event;sealing.SectorFinalized]	{"User":{}}`

**Comment by phantom-rabbit** [comment]
thank you , I'll try
