### ISSUE TITLE
NV18 -  Documentation 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9844]
- [ ] for node operators on the new events/logs and eth_subscribe https://github.com/filecoin-project/lotus/blob/6da93cf921af29e1c6a5e5b701170ef83a3e93e7/documentation/en/default-lotus-config.toml#L267-L314

**Comment by daredevil3435** [comment]
I would like to contribute. How do I get started?

**Comment by TippyFlitsUK** [comment]
In what way are you hoping to contribute @daredevil3435?

**Comment by TippyFlitsUK** [comment]
NV18 is now complete

**Comment by daredevil3435** [comment]
> In what way are you hoping to contribute @daredevil3435?

every possible way
