### ISSUE TITLE
Eth JSON RPC API integration tests

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9849]
## Fetching information

- [x]  eth_getBalance @shrenujbansal https://github.com/filecoin-project/lotus/pull/9966#issue-1519451852
	- [x]  for existent f4 address
	- [x]  for inexistent f4 address (returns 0x0)
	- [x]  for existent ID masked address
	- [x]  for inexistent ID masked address (returns 0x0)
- [ ]  eth_getBlockByHash 
	- [ ]  with true/false in the second parameter (to return transactions or not) -- check it does the right thing
	- [ ]  tipset with multiple blocks, verify txs deduplicated
	- [ ]  inexistent block hash
	- [ ]  invalid block hash
- [ ]  eth_getBlockByNumber 
	- [ ]  same as above, but with inexistent block number
	- [ ]  null round
- [ ]  eth_getTransactionByBlockHashAndIndex 
    - [ ]  in the same test case as above, verify that we're able to retrieve a transaction by its index within a tipset
- [ ]  eth_getTransactionByBlockNumberAndIndex
	- [ ]  same as above
- [ ]  eth_protocolVersion returns network version

## Logs @iand  

- [x] eth_getLogs (see https://github.com/filecoin-project/lotus/pull/10052)
  - [x] Validate AND filters
  - [x] Validate OR filters
  - [x] Validate block range queries
  - [x] Validate address filter
- [ ] eth_getTransactionReceipt
  - [ ] Validate logs correctly populated
- [x] Validate logs correctness with respect to a Solidity contract ABI. Assert correct event signature, values, and data. Can use a no table ERC-20 token contact. (part of #10052)

## Submitting transactions @shrenujbansal 

**Contract invocations**
https://github.com/filecoin-project/lotus/pull/9966
- [x] Submit a correctly formed EIP-1559 transaction with valid signature => returns tx id
- [x] Submit a correctly formed EIP-1559 transaction with invalid signature => returns error
- [ ] Submit a mangled EIP-1559 transaction with valid signature => returns error
- [x] Submit a well-formed Legacy transaction with valid signature => returns error
- [x] Submit a transaction with invalid V in signature => returns error (might not be easy to produce)
	- https://github.com/filecoin-project/lotus/pull/9970/files#r1068006314

**Value transfers**

All of the above for value transfers.

**Contract deployments**

All of the above with contract creations (nil To).

## Filters @iand 

- [ ]  Pending transaction filters; already lightly tested in #9922
	- [ ]  test with non-Ethereum transactions
- [x]  New block filter; currently untested
	- [x]  subscribe to ChainNotify and verify that we get the same blocks
- [x]  Normal filters (events) - covered by Logs section above
- [x]  Verify APIs disabled when config param not passed (https://github.com/filecoin-project/lotus/pull/10062)

## Subscription @iand 

- [ ] Subscribe and unsubscribe, with correct, unrecognised ID, invalid ID
- [x] Validate filters applied correctly (all kinds of filters)
- [x] Validate all kinds of subscriptions
- [ ] Heads subscription on bull rounds
- [ ] Fork behaviours (reverts and applies)

**Comment by shrenujbansal** [comment]
@raulk Could you advise how I could construct/where I could find misaligned EIP-1559 and legacy style transactions to be used in my test? In addition, do you expect the errors to be different for each of these? If not, aren't they same use case of an incorrectly formatted transaction?

**Comment by maciejwitowski** [comment]
@ychiaoli18 are you still planning to work on items assigned to you here?

**Comment by maciejwitowski** [comment]
@shrenujbansal 
>  Submit a mangled EIP-1559 transaction with valid signature => returns error

What is the update on this? done/to-be-done/can't-be-done?

**Comment by Stebalien** [comment]
This issue has outlived its usefulness.
