### ISSUE TITLE
Cannot pull from miner available balance using lotus wallet

### ISSUE THREAD

**Issue by jamerduhgamer** [filecoin-project/lotus#9856]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus version
Daemon:  1.18.0+mainnet+git.4154e9652+api1.5.0
Local: lotus version 1.18.0+mainnet+git.4154e9652

lotus-miner version
Daemon:  1.18.0+mainnet+git.4154e9652+api1.5.0
Local: lotus-miner version 1.18.0+mainnet+git.4154e9652

lotus-wallet --version
lotus-wallet version 1.18.0+mainnet+git.bd10bdf99
```

### Describe the Bug

The Lotus miner cannot pull from the available balance using `lotus-miner actor withdraw` if the owner wallet is on a remote lotus wallet server. However, you can run `lotus wallet list | grep <owner address>` from the lotus-miner and are able to see the owner wallet which means you have connectivity to the remote lotus wallet server and that the correct `FULLNODE_API_INFO` is exported as well.

### Logging Information

```text
On the lotus miner server:

lotus-miner actor control list --verbose
name       ID         key                                          use        balance
owner      f0763314   f1mddpc4i2hayggkdfwskezcfqlb6u3ymnklazsvq               22.816796733938610151 FIL

Also on the lotus miner server that does not have the owner key locally:

lotus wallet list | grep f1mddpc4i2hayggkdfwskezcfqlb6u3ymnklazsvq
f1mddpc4i2hayggkdfwskezcfqlb6u3ymnklazsvq                                 22.816796733938610151 FIL   61

On the lotus miner server:

lotus-miner actor withdraw 19.89
ERROR: failed to sign message: key not found
```

### Repo Steps

1. Have the owner wallet for a miner sit on a remote server running lotus wallet.
2. Set the lotus wallet API info on your lotus daemon server in the config.toml file under "RemoteBackEnd"
3. Have your lotus miner connected to the lotus daemon server that is also connected to the lotus wallet server.
4. Run `lotus wallet list | grep <owner address>` to see your connectivity to the lotus daemon and from the lotus daemon to the lotus wallet.
5. Attempt to withdraw FIL from the available balance of the SP

**Comment by geoff-vball** [comment]
@jamerduhgamer Do you have a beneficiary set for your miner?

**Comment by jamerduhgamer** [comment]
Hi @geoff-vball, no beneficiary has been set!

**Comment by jamerduhgamer** [comment]
I tried another test today, where I moved the wallet private key from the lotus wallet server onto the lotus daemon server itself and still ran into the same issue!

`lotus-miner actor control list --verbose | grep f1mddpc4i2hayggkdfwskezcfqlb6u3ymnklazsvq`
`owner      f0763314   f1mddpc4i2hayggkdfwskezcfqlb6u3ymnklazsvq 22.816796733938610151 FIL`

`lotus wallet list | grep f1mddpc4i2hayggkdfwskezcfqlb6u3ymnklazsvq`
`f1mddpc4i2hayggkdfwskezcfqlb6u3ymnklazsvq 22.816796733938610151 FIL    61`

`lotus-miner actor withdraw 119.8998`
`ERROR: failed to sign message: key not found`

**Comment by geoff-vball** [comment]
Does your miner have an sign/admin token for the node?

**Comment by jamerduhgamer** [comment]
Hi @geoff-vball, figured it out!

What happened was we are running two identical lotus daemons however the lotus wallet server was only connected to one of them but the lotus miner server was connected to the other lotus daemon.

Even though exporting the `FULLNODE_API_INFO` for the correct lotus daemon, since the miner itself was connected to the other one, it wasn't able to see the key. This method worked in the past on previous versions so not sure why this is only showing up now but at least its resolved.
