### ISSUE TITLE
`lotus daemon --import-snapshot` ignores SIGINT (Ctrl-C)

### ISSUE THREAD

**Issue by Kubuxu** [filecoin-project/lotus#9862]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.19.1-dev+mainnet+git.59431631a+api1.5.0
Local: lotus version 1.19.1-dev+mainnet+git.59431631a
```

### Describe the Bug

When `lotus daemon --import-snapshot` is started, it cannot be interrupted apart from using SIGKILL.
The Ctrl-C or sending SIGINT by `pkill lotus` doesn't work, the import process continues.

### Logging Information

```text
N/A
```

### Repo Steps

1. Run 'louts daemon --import-snapshot SNAPSHOT'
2. Do 'Ctlr-C' or `pkill lotus`
3. Nothing happens

**Comment by Kubuxu** [comment]
Similar issue https://github.com/filecoin-project/lotus/issues/4866

**Comment by geoff-vball** [comment]
PR for this if you want to review :) https://github.com/filecoin-project/lotus/pull/9874
