### ISSUE TITLE
TestPaymentChannelsAPI is flaky

### ISSUE THREAD

**Issue by geoff-vball** [filecoin-project/lotus#9883]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
master
```

### Describe the Bug

Test sometimes fails

### Logging Information

https://app.circleci.com/pipelines/github/filecoin-project/lotus/25015/workflows/d4f9890d-ca91-4a01-8ae3-c4354fc57066/jobs/719963/tests#failed-test-0

https://app.circleci.com/pipelines/github/filecoin-project/lotus/25014/workflows/06172fc3-c528-4e3e-a47e-86d721561c24/jobs/719831/tests#failed-test-0

https://app.circleci.com/pipelines/github/filecoin-project/lotus/25013/workflows/14081630-92d5-4e95-bf92-3bcd54ee1c8a/jobs/719805/tests#failed-test-0

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by magik6k** [comment]
Should be fixed by https://github.com/filecoin-project/lotus/pull/10100
