### ISSUE TITLE
Raft node can break into external cluster by knowing peer IDs

### ISSUE THREAD

**Issue by geoff-vball** [filecoin-project/lotus#9888]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
master
```

### Describe the Bug

Discovered because TestGoRPCAuth is flaky. There are 3 nodes in a cluster, and one outside that cluster. The outside node is passed the peerIDs of the 3 other nodes, and seems like it is able to break into the cluster and become the leader. This is a security risk and shouldn't happen. This is why the test flakes ~25% of the time. 

See https://github.com/filecoin-project/lotus/pull/9763 for more info.

The test should be re-enabled with this fix.

### Logging Information

```text
n/a
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by jennijuju** [comment]
@shrenujbansal could you please take this one please?

**Comment by rjan90** [comment]
Closing, as the raft cluster support has been dropped entirely: https://github.com/filecoin-project/lotus/pull/11468
