### ISSUE TITLE
There will be no data until the end of time

### ISSUE THREAD

**Issue by chengwds** [filecoin-project/lotus#994]
2019-12-20T11:44:22.416+0800	INFO	main	lotus-seal-worker/sub.go:64	Waiting for new task

Observation, there will never be data

**Comment by chengwds** [comment]
root@cheng-ipfs:~# lotus client query-ask t06012
Ask: t06012
Price per GiB: 0.0000000005
root@cheng-ipfs:~# lotus client deal QmPNEvxBzWHfDTmwePrYkXtogtjXiWYVE3z5WbUVXmKP25 t06012 0.0000000005 100000

**Comment by chengwds** [comment]
t01475 | 0.89
-- | --
t01004 | 0.48
t01493 | 0.28
t04771 | 0.22
t01485 | 0.17
t0333 | 0.04
t0444 | 0.02

All of the above are self-made codes, Only learning to change the codes can they be used normally.

**Comment by chengwds** [comment]
t01475，This company can be considered as the project party

**Comment by whyrusleeping** [comment]
the testnet had a few issues over the holiday break, these will be resolved soon
