### ISSUE TITLE
Devnets: Start from v17 and upgrade

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#9943]
This is our standard dev flow as we test network upgrades, but was circumvented because we didn't have the v18 migration yet. Now that we do, we should revert to doing this, so as to exercise the migration as we run devnets.

**Comment by jennijuju** [comment]
can we close this via https://github.com/filecoin-project/lotus/commit/9d3e50f140a459368454edcea20a4cbbeffb26b9 ?
