### ISSUE TITLE
lotus-miner info shows StartTime of lotus node while should show its own

### ISSUE THREAD

**Issue by mrworkdev** [filecoin-project/lotus#9947]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
Daemon:  1.19.0+mainnet+git.64059ca87+api1.5.0
Local: lotus version 1.19.0+mainnet+git.64059ca87
```

### Describe the Bug

lotus-miner info shows "StartTime" of node instead of miner.

$ lotus info
```
Network: mainnet
StartTime: 14h53m37s (started at 2022-12-27 20:20:54 +0000 UTC) <------------------------- same
Chain: [sync ok] [basefee 13.702 pFIL] [epoch 2463989]
...
```

$ lotus-miner --color info --hide-sectors-info
```
Enabled subsystems (from miner API): [Mining Sealing SectorStorage]
Enabled subsystems (from markets API): [Markets]
StartTime: 14h53m37s (started at 2022-12-27 20:20:54 +0000 UTC) <------------------------- same
...
```

Shouldn't lotus-miner show its own StartTime?

### Logging Information

```text
no logs
```

**Comment by rjan90** [comment]
Hey @mrworkdev! Thanks for the issue report! Yes, the miner should show its own startTime, which has been fixed with this PR which is merged to the master-branch, but did not make it in time for the final v1.19.0-release: https://github.com/filecoin-project/lotus/pull/9823.

Closing this issue, since this has been fixed! Thanks again for the issue-report!
