### ISSUE TITLE
not enough DataCap available for a verified deal

### ISSUE THREAD

**Issue by lbj2004032** [filecoin-project/lotus#9953]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
$ lotus -v
lotus version 1.19.0+mainnet+git.64059ca87
```

### Describe the Bug

I have applied datacap large dataset,
But the transmission data prompt: .. not enough DataCap available for a verified deal
Here is my application link:  https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1172

-----------------

Request Proposed
Your Datacap Allocation Request has been proposed by the Notary

Message sent to Filecoin Network
bafy2bzacedsucap7kkc66t3ivnvb4pi6eea44dbcym5emns7dwcmgzmvascd6

Address
f1djeaxezazhlg5334gla2j5jojkna6qnzxg7ovba

Datacap Allocated
25.00TiB

Signer Address
f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq

Id
77afd132-3526-44ea-9d39-53fc256e9b15

You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsucap7kkc66t3ivnvb4pi6eea44dbcym5emns7dwcmgzmvascd6

### Logging Information

```text
$ lotus client deal
Data CID (from lotus client import): bafykbzaceb6c4iahukohke4h5kuaxgg6tph33zugwpggidi3qaehdeu5qtz5c
.. calculating data size
Deal duration (days): 180
.. not enough DataCap available for a verified deal
Miner Addresses (f0.. f0..), none to find:
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by Reiers** [comment]
Hi @lbj2004032 

Thanks for the report, but is not an issue - you need two notaries to sign your [application](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1172#issuecomment-1356885576). 

The Request is Proposed, and you need another Notary to Approve. 

When the second message has been sent, you will have Available DataCap. 

Closing ticket since it's not an issue.

**Comment by lbj2004032** [comment]
> Hi @lbj2004032
> 
> Thanks for the report, but this is not an issue - you need two notaries to sign your [application](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1172#issuecomment-1356885576).
> 
> The Request is Proposed, and you need another Notary to Approve.
> 
> When the second message has been sent, you will have Available DataCap at the address you provided.
> 
> Closing ticket since it's not an issue.

Hown should I send the second message

**Comment by lbj2004032** [comment]
> Hi @lbj2004032
> 
> Thanks for the report, but this is not an issue - you need two notaries to sign your [application](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1172#issuecomment-1356885576).
> 
> The Request is Proposed, and you need another Notary to Approve.
> 
> When the second message has been sent, you will have Available DataCap at the address you provided.
> 
> Closing ticket since it's not an issue.

how can i get another Notary to Approve
