### ISSUE TITLE
With the operation of the Lotus daemon and the increase in the amount of data, will the memory used also increase?

### ISSUE THREAD

**Issue by YuXiaoCoder** [filecoin-project/lotus#9967]
### Discussed in https://github.com/filecoin-project/lotus/discussions/9945

<div type='discussions-op-text'>

<sup>Originally posted by **YuXiaoCoder** December 27, 2022</sup>
Lotus Version:
```bash
./lotus version
Daemon:  1.18.0+mainnet+git.1f6b30c14+api1.5.0
Local: lotus version 1.18.0+mainnet+git.1f6b30c14
```

I run two nodes with the same configuration. One node has 393G of data, and the corresponding memory used is 54G, while the other node has 168G of data, and the corresponding memory used is only 11G. Is there any relationship between them?</div>

**Comment by TippyFlitsUK** [comment]
Please continue your discussion @YuXiaoCoder.
