### ISSUE TITLE
Allow number of BadgerDB Compaction workers to be adjusted via environment variable

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lotus#9972]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Improvement Suggestion

Sentinel has a use case for Lily where it can import a snapshot for read-only indexing purposes. This results in a badger blockstore does not intend to be updated further. When importing such a snapshot, a long compaction process occurs on the blockstore which blocks the quick availability of the repo for indexing. As an operator, I would like to disable this compaction in certain (all of?) Sentinel's use cases to decrease the wait until the node can become ready.

To this end, I would like to use some interface to manipulate [the badger configuration for the number of compactors used during runtime](https://github.com/dgraph-io/badger/blob/7a3a87a78191c4dae4bf6ce0d1ef5ad90ce99a7f/options.go#L619-L626).

Open Questions: Is this a bad idea? Why? Are there other details I'm overlooking?

**Comment by magik6k** [comment]
https://github.com/filecoin-project/lotus/pull/9973
