### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by luhong123** [filecoin-project/lotus#9986]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [X] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [X] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotusv1.18.0
Daemon:  1.18.0+mainnet+git.bd10bdf99.dirty+api1.5.0
Local: lotus-miner version 1.18.0+mainnet+git.bd10bdf99.dirty
```

### Describe the Bug

I found an error when renewing the sector. It was successful yesterday. It was the same problem as restarting the server

### Logging Information

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2287774]

goroutine 1 [running]:
main.glob..func78(0xc000ed3f40)
	/root/bule/lotusv1.18.0/lotus1.18.0/cmd/lotus-miner/sectors.go:924 +0xc14
github.com/urfave/cli/v2.(*Command).Run(0x7a85ee0, 0xc000ed3c00)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:169 +0x631
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000783520, 0xc000ed3a40)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:490 +0xd0a
github.com/urfave/cli/v2.(*Command).startApp(0x7a87b00, 0xc000ed3a40)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:287 +0x77b
github.com/urfave/cli/v2.(*Command).Run(0xc000ed3a40?, 0xc000576600?)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:95 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc0007831e0, {0x48da168?, 0xc000050d18}, {0xc00004e0b0, 0xb, 0xb})
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbc8
github.com/urfave/cli/v2.(*App).Run(...)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
github.com/filecoin-project/lotus/cli.RunApp(0x3c55580?)
	/root/bule/lotusv1.18.0/lotus1.18.0/cli/helper.go:39 +0x4e
main.main()
	/root/bule/lotusv1.18.0/lotus1.18.0/cmd/lotus-miner/main.go:172 +0x1165
```

### Repo Steps

lotus-miner sectors renew --sector-file=xx  --new-expiration xxx--tolerance 0  --really-do-it=true   

****

**Comment by Reiers** [comment]
Hi @luhong123 👋 

I'm not able to reproduce the issue here.
```
lotus-miner sectors renew --sector-file=/home/reiers/repro --new-expiration 4060000
nothing to extend
```


Remember that `--sector-file` has to be a file and not sector number - it's also important to _**not**_ have any accidental "spaces" in the file.

( `provide a file containing one sector number in each line, ignoring above selecting criteria` )

I also notice that you have a .dirty build, have you made any changes or modifications to code? 
If not, I would advise to upgrade to the latest stable version `v1.19.0` and `make clean`.

**Comment by TippyFlitsUK** [comment]
On it now buddy!!

**Comment by TippyFlitsUK** [comment]
I am not seeing the same issue here. Tested with 6 sectors without issue:
```
Daemon:  1.19.1-dev+mainnet+git.fb90ba1fd+api1.5.0
Local: lotus-miner version 1.19.1-dev+mainnet+git.fb90ba1fd

lotus-miner sectors renew --sector-file=/home/tippyflits/renew.txt --new-expiration 4060398 --tolerance 0 --really-do-it=true
Renewing 6 sectors: bafy2bzacect7zx4fv53ho74ct2a64zdzoltbbtbvbgpymbrnlwujxen5d5gha
6 sectors renewed
```
@luhong123 can you please verify the exact command that you used when this error occurred?

**Comment by marshyonline** [comment]
Ive been seing this since 1.19.0 in a lot of area's of lotus. 
My issue was that it never given me a rust panic UNTILL TODAY!

```
root@syd-hu1-041:~# lotus-miner actor withdraw
Requested withdrawal in message bafy2bzaceaqp5rpv42gafppsupnw6ozas424nmhbycs3crwbfvbczlhm6634e
waiting for it to be included in a block..
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x22a1375]

goroutine 1 [running]:
main.glob..func3(0xc0004c9300)
        /root/workspace/lotus/cmd/lotus-miner/actor.go:293 +0x6f5
github.com/urfave/cli/v2.(*Command).Run(0x7b10920, 0xc0004c9180)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:169 +0x631
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000702d00, 0xc0004c8fc0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:490 +0xd0a
github.com/urfave/cli/v2.(*Command).startApp(0x7b0f840, 0xc0004c8fc0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:287 +0x77b
github.com/urfave/cli/v2.(*Command).Run(0xc0004c8fc0?, 0xc00020f500?)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:95 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc0007029c0, {0x4927248?, 0xc000240c70}, {0xc000222150, 0x3, 0x3})
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbc8
github.com/urfave/cli/v2.(*App).Run(...)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
github.com/filecoin-project/lotus/cli.RunApp(0x3c8bc60?)
        /root/workspace/lotus/cli/helper.go:39 +0x4e
main.main()
        /root/workspace/lotus/cmd/lotus-miner/main.go:168 +0x10e5
```

I get the same `panic: runtime error: invalid memory address or nil pointer dereference` when fetching deal counts, importing deals, loading sector lists and even in wdpost


```
2023-01-12 09:09:29{"level":"info","ts":"2023-01-12T09:09:29.431+1100","logger":"wdpost","caller":"wdpost/wdpost_sched.go:160","msg":"restarting window post scheduler"}
2023-01-12 09:09:19{"level":"error","ts":"2023-01-12T09:09:19.429+1100","logger":"wdpost","caller":"wdpost/wdpost_sched.go:153","msg":"ChainNotify error: %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)"}
2023-01-12 09:09:04{"level":"warn","ts":"2023-01-12T09:09:04.426+1100","logger":"wdpost","caller":"wdpost/wdpost_sched.go:166","msg":"window post scheduler notifs channel closed"}
```

I think this is a larger issue that is lurking here.
@Trevor-K-Smith is seeing the same issues

**Comment by Reiers** [comment]
@TippyFlitsUK Thanks for confirming. 🙏 

@marshyonline Please open a second ticket, because this is not related to **this** issue ticket. Other than you both have a panic. (That should not happen).

I'm not seeing any of these panics on `v1.19.0` and up, and we are monitoring.  
So if you could open a issue ticket, give me a few scenarios - maybe I will be able to reproduce them and find the cause. 🔍 

Thank you!

**Comment by marshyonline** [comment]
Thanks @Reiers - #9988 opened
