### ISSUE TITLE
--import-snapshot does not give error when compressed snapshot is imported

### ISSUE THREAD

**Issue by iand** [filecoin-project/lotus#9991]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Built from current master (9a46682d9d3bd14733698659c10c6fed3256d121)
```

### Describe the Bug

If you pass a compressed car file to `lotus daemon --import-snapshot` by mistake Lotus appears to import it, taking 30+ minutes for a light snapshot and expanding the datastore by about 100GB. However no actual state is imported. Lotus should return an error when the passed file is not a valid CAR.

### Logging Information

```text
See below
```

### Repo Steps

1. Run `aria2c -x5 https://snapshots.mainnet.filops.net/minimal/latest.zst`
2. Do `lotus daemon --import-snapshot 2506580_2023_01_12T06_00_00Z.car.zst --halt-after-import`
3. No error, lotus imports something and badger logs show data is being written
4. Run `lotus daemon`
5. Logs show errors that actor states cannot be loaded

**Comment by magik6k** [comment]
Compressed snapshot imports are meant to work, this was implemented in https://github.com/filecoin-project/lotus/pull/9741

**Comment by iand** [comment]
Closing as this was user error
